### ISSUE TITLE
How to implement document load complete event of ChromiumWebBrowser ?

### ISSUE THREAD

**Issue by ismailkocacan** [cefsharp/CefSharp#1000]
I was implement document load complete event as below.
When I load big html string(60 MB) then continue loading ???
Any idea ?

<pre><code class='language-cs'>
var html = "big html string"; // 60 MB 
webBrowser.LoadHtml(html, "blah blah blah");
</code></pre>

<pre><code class='language-cs'>
webBrowser.IsLoadingChanged += webBrowser_IsLoadingChanged;

void webBrowser_IsLoadingChanged(object sender, IsLoadingChangedEventArgs e)
{
   lblState.Text = e.IsLoading == true ? "Loading" : "Loaded";
   if (e.IsLoading == true)
   {
      // to do
    }
 }
</code></pre>

**Comment by amaitland** [comment]
`IsLoadingChanged` is unreliable and will be removed. Use `NavStateChanged` instead.

You can use a `SchemeHandler` or a `ResourceHandler` to load a file from disk. `ResourceHandler` only supports `sync` operations at the moment so isn't recommended for large files, this will be resolved in `41`

http://rawgit.com/cefsharp/CefSharp/master/CefSharp.Example/Resources/Home.html#features-custom-schemes

**Comment by amaitland** [comment]
Dig through the example projects and you'll find lots of features demonstrated.

**Comment by ismailkocacan** [comment]
Ok. I'm looking demos.
Thanks you so much.

**Comment by ismailkocacan** [comment]
it worked.
<pre><code class='language-cs'>
webBrowser.NavStateChanged += webBrowser_NavStateChanged;
void webBrowser_NavStateChanged(object sender, NavStateChangedEventArgs e)
{
   if (webBrowser.IsLoading == true)
   {
      lblDurum.Text = "loaded";
   }
}
</code></pre>

**Comment by amaitland** [comment]
If you look at `IWebBrowser` it has some useful doco

https://github.com/cefsharp/CefSharp/blob/master/CefSharp/IWebBrowser.cs
