### ISSUE TITLE
can not open project with visual studio 2010

### ISSUE THREAD

**Issue by unknow123** [cefsharp/CefSharp#1001]
i'm using visual studio 2010.
i'm changed version from this project...but when i open it...very more error!
anyone can help me?
my pc can not install visual 2013++
can fix .net 4.5 to 4.0 and visual version?
thanks!

**Comment by jankurianski** [comment]
Why not use the NuGet packages?

> i'm changed version from this project...but when i open it...very more error!

Do you have a screenshot of the error?

> can fix .net 4.5 to 4.0 and visual version?

I don't understand what you mean.  Can you be more specific?

**Comment by unknow123** [comment]
@jankurianski : what's NuGet packages?
yes...it show need convert net framwork from 4.5 to 4.0...

**Comment by jankurianski** [comment]
Here is an explanation: https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#CefSharp_binaries

The CefSharp project is not meant to be built from source code.  We already provide binary files in a NuGet format.  The .NET framework target is 4.0.

**Comment by unknow123** [comment]
@jankurianski : thanks i'm downloading clone desktop and try now :+1:

**Comment by unknow123** [comment]
@jankurianski : sory! i read https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#CefSharp_binaries

and i'm can not see binaries link!?
help me!

**Comment by jankurianski** [comment]
Everything is done in NuGet - no link and no downloads.  Have you used it before?

Here is a guide with screenshots: http://docs.nuget.org/consume/package-manager-dialog

When you have the NuGet window open, search for *CefSharp* and then choose either *WPF* or *WinForms* package.

**Comment by amaitland** [comment]
See the `MinimalExample` for a working demo of using the `nuget` packages (this should compile using `VS2010` as it targets `.Net 4.0` only).

https://github.com/cefsharp/CefSharp.MinimalExample

**Comment by unknow123** [comment]
sory mate! i'm not use it before :(

**Comment by amaitland** [comment]
If your using `VS2010` then that's your only option as you need a minimum of `VS2012` to build from source.
