### ISSUE TITLE
WPF: ChromiumWebBrowser as child to ScrollViewer prevent focus of HTML elements

### ISSUE THREAD

**Issue by robinwassen** [cefsharp/CefSharp#1002]
If you put the `ChromiumWebBrowser` as a child to a `ScrollViewer` the focus will start to misbehave.

Focus is lost if you left click a html element in the browser and it kind of works if you right click.

**Steps to reproduce:**
1. Add a `ScrollViewer` in the XAML
2. Add the `ChromiumWebBrowser` with a HTML document containing a text input as a child to the `ScrollViewer`
3. Try to focus the text input by left clicking in it

**Expected outcome:** The text input in the HTML document should get focus.

**Outcome:** The text input get focus for a fraction of a second and then loses it.

**Earlier mentions of this issue:** [CefSharp Google Groups](https://groups.google.com/forum/#!topic/cefsharp/KgUoEMHIfxM) by @vgrishin

**Comment by robinwassen** [comment]
**Pure C# workaround:**

1. Add a event listener to `MouseDown` on the `ChromiumWebBrowser `
2. Add `e.Handled = true` in the handler to prevent MouseDown from bubbling

**XAML:**
```XAML
<cefSharp:ChromiumWebBrowser x:Name="chromiumWebBrowser" MouseDown="chromiumWebBrowser_MouseDown"  Height="800"  Address="http://www.example.com" />
```

**C#:**
```C#
void chromiumWebBrowser_MouseDown(object sender, System.Windows.Input.MouseButtonEventArgs e)
{
	e.Handled = true;
}
```

**Comment by amaitland** [comment]
Can you include the version your using.

**Comment by robinwassen** [comment]
v39.0.1 (Stable)

**Comment by john123951** [comment]
great!
