### ISSUE TITLE
Code Cleanup - Consistent C++ Naming

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#1005]
At the moment there is no consistent naming convention for the `C++` classes, some use `wrapper` in their name, others use `adapter`, some are prefixed with `Cef`, some aren't.

Hopefully `Resharper C++` can help with this :smile: 

Some possibilities
- For classes that implement functionality e.g. `CefSharpApp` which implements `CefApp`, we drop the `Cef` prefix and it just becomes `App`. (This becomes a little messy with things like `CefTask`)
- Add a suffix maybe `CefAppImpl`? Not really loving this one, though it's common enough (I think `Cef` it's self uses this sort of naming convention).
- Something entirely different???

Public facing `API` classes will stay the same for now, though I'd like to make the `enum` naming consistent.

Will implement after #996 has been merged.

**Comment by amaitland** [comment]
@rassilon Any thoughts on this one? I know you've been digging through a lot of the `c++` classes recently. Ideas on a naming scheme?

**Comment by rassilon** [comment]
We could do `SharpApp` for a C++ child of `CefApp`.
For a managed wrapper of a `SharpApp` instance, we could do `SharpAppAdapter`?

Bill

**Comment by amaitland** [comment]
> For a managed wrapper of a SharpApp instance, we could do SharpAppAdapter?

So `Adapter` over `Wrapper`?

**Comment by rassilon** [comment]
One or the other, I'm not particularly picky. Adapter might help us remember it's "contains a" vs "maybe is a".

**Comment by amaitland** [comment]
I'm somewhat in favor of using `Wrapper` for classes that use `MCefRefPtr` to wrap an instance. And every class that implements a `Cef` interface has some sort of consistent naming, maybe `Sharp` as a prefix instead of `Cef`.

**Comment by rassilon** [comment]
That's fine with me.

**Comment by amaitland** [comment]
Move classes like `SchemeHandlerFactoryWrapper` to `Internals` namespace and rename to `CefSchemeHandlerFactoryWrapper`

**Comment by perlun** [comment]
@amaitland @rassilon Was this ever done?
