### ISSUE TITLE
i can not add cefsharp to my toolbox and design?

### ISSUE THREAD

**Issue by unknow123** [cefsharp/CefSharp#1006]
i'm newbie cefsharp...i added referent cefsharp to my project
but i can not design cefsharp with my application!
what's happened?

**Comment by jankurianski** [comment]
The visual studio designer is not supported.

See https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#Wpf_designer

And please use the search box at the top of Github to search existing issues before asking a question.
