### ISSUE TITLE
Render process crashes if you try to access localStorage (via JavaScript) on a custom scheme (e.g. client://)

### ISSUE THREAD

**Issue by talias** [cefsharp/CefSharp#1014]
If you try to access the localStorage via JavaScript on a custom scheme the render process crashes.
 
This issue only occurs if you're using a custom scheme, like "client://".

Seems to be the same issue as described in detail for JCEF here:
https://code.google.com/p/javachromiumembedded/issues/detail?id=123

*"The reason for that is that the render process (as well as all others except the main process) doesn't know anything from your custom schemes.
The solution for this issue: Tell the render process to register your custom schemes by implementing the method CefApp::OnRegisterCustomSchemes() within jcef_helper.app."*

Maybe this fix can somehow be implemented in CefSharp as well.

**Comment by amaitland** [comment]
Interesting. Are you working on a `PR`?

**Comment by talias** [comment]
Unfortunately it's not possible for me to do that.

**Comment by amaitland** [comment]
> Unfortunately it's not possible for me to do that.

Any particular reason?

**Comment by talias** [comment]
I'm not the reporter of the corresponding JCEF issue.
I just ran into the problem with CefSharp and searched the web for help.
My C++ skills are a bit too outdated to work on a PR myself.

But I could create a C# example demonstrating the issue, if that helps.

**Comment by rassilon** [comment]
It sure would help! Based on MinimalExample if possible.

Thanks,
Bill
