### ISSUE TITLE
In Cef.Initialize, CefSettings.CefCommandLineArgs does not work properly

### ISSUE THREAD

**Issue by yeunglee** [cefsharp/CefSharp#1020]
Please try the WinForms example (e.g. CefSharp.WinForms.Example). I notice the command line arguments are not appended properly.

The attached screenshot is for original CefSharp.WinForms.Example. It has two issues.
1) The argument "--log-severity=verbose" is appended twice.
2) The proxy server argument is not appended at all. (see CefExample.Init method in Cef.Example\CefExample.cs) In my case, the "no-proxy-server" should be appended.

![cef_initialize](https://cloud.githubusercontent.com/assets/5395714/7553604/dd99c61e-f734-11e4-88f1-511cd0563644.png)

Please check the original CefSharp.WinForms.Example project.

**Comment by amaitland** [comment]
> The argument "--log-severity=verbose" is appended twice.

Comment out https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/CefExample.cs#L63 and try again. `LogSeverity` is already set.

**Comment by yeunglee** [comment]
The core problem is that the command line arguments are not appended properly.

The "--log-severity=verbose" is used to explain why i think the Cef.Initialize is improper.

Did you try CefSettings.CefCommandLineArgs? I see no argument is appended. Please double check.

Thanks

**Comment by amaitland** [comment]
> Did you try CefSettings.CefCommandLineArgs? I see no argument is appended. Please double check.

No time at the moment, the code is there, feel free to investigate further and report back.

**Comment by amaitland** [comment]
The code has been there many times, and I've seen it used successfully by countless users, so whilst it may not be perfect in it's implementation, it works for the most part.

**Comment by yeunglee** [comment]
I think less people use command line arguments. That is why this is not found.

I saw the bug. I am newbie on github. could you help me post this fix?

modify https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Internals/CefSharpApp.h#L57-L66

			for each(KeyValuePair<String^, String^>^ kvp in _cefSettings->CefCommandLineArgs)
			{
				CefString name = StringUtils::ToNative(kvp->Key);

				// Right now the command line args handed to the application (global command line) have higher
				// precedence than command line args provided by the app
				if (!commandLine->HasSwitch(name))
				{
					// The switch without value must use AppendSwitch
					if (kvp->Value->Equals("1") || kvp->Value->Equals(kvp->Key)) {
						commandLine->AppendSwitch(name);
					}
					else {
						CefString value = StringUtils::ToNative(kvp->Value);
						commandLine->AppendSwitchWithValue(name, value);
					}
				}
			}
