### ISSUE TITLE
How do I give permission for ChromiumWebBrowser to access my microphone for speech input?

### ISSUE THREAD

**Issue by jamespearce2006** [cefsharp/CefSharp#1022]
If I browse to Google's home page with Chrome, I can click the microphone icon and I'll be prompted with a dialog to allow access to the mic. If I agree, I can speak my search request.

If I do this with CefSharp's ChromiumWebBrowser, I can click the icon, but I'm never prompted to give my permission.

Is there a handler I need to implement to do this, or is it something that still needs to be implemented?

**Comment by jornh** [comment]
I'm not sure there is a handler exposed in the upstream CEF API for hooking in UI

But you need to enable WebRTC alltogether via the `enable-media-stream` flag as show in https://github.com/cefsharp/CefSharp/blob/v39.0.1/CefSharp.Example/CefExample.cs#L35 - maybe that's enough for your usage scenario?

**Comment by jamespearce2006** [comment]
That certainly works for some sites. Strange that Google seems unable to access my mic, though...

It'd be good to give the user the opportunity to allow or deny access too...

**Comment by jornh** [comment]
Sorry. Related to the `enable-speech-api` flag instead (since you clarified it was related to speech access on Google :smile:) found that out by fiddling around with the upstream `cefclient.exe` and it's **Other Tests** menu which point to https://www.google.com/intl/en/chrome/demos/speech.html 

Also, see http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=12744 where there is a pointer to a CEF issue with mention of need for building the CEF binaries with a Google API key.

I think its safe to mark as `upstream`, and `wont-fix` (really can't-fix) plus made minor clarification in issue title. OK with that?

**Comment by jamespearce2006** [comment]
That's fine. Thanks

**Comment by jamespearce2006** [comment]
It would be good to find out how we can hook into the permission request that Chrome displays, though...

**Comment by jornh** [comment]
Feel free to explore upstream in CEF. A starting point is http://magpcss.org/ceforum/apidocs3/index-all.html#_O_ where I see `OnXxx` handlers for `CefGeolocationHandler`, `CefJSDialogHandler` etc. I haven't seen handlers exposed for neither speech input nor WebRTC there ... yet.

There's little the CefSharp project can do if it's not available in the CEF API. 

Closing this issue as I think your request for handler API is another separate issue and should be resolved with CEF.

**Comment by i524304** [comment]
Hi @jornh 

I am trying to enable microphone from zfbrowser by --enable-main-stream on unity but not getting any success. Could you please help me regarding the same. Thanks in advance and hoping to hear from you soon.

Kind regards

**Comment by dzunglean** [comment]
None is working for my case. I load skype page and video+speaker are disable.

**Comment by amaitland** [comment]
Please don't ask questions on 8+yr old issues.

You can implement [PermissionHandler](https://cefsharp.github.io/api/112.2.x/html/P_CefSharp_IWebBrowser_PermissionHandler.htm) to allow media requests.

In future please use [Discussions](https://github.com/cefsharp/CefSharp/discussions) to ask support related questions.
