### ISSUE TITLE
Possible to add CefRequestHandler.onResourceRedirect()?

### ISSUE THREAD

**Issue by LeMoussel** [cefsharp/CefSharp#1023]
I found nothing about onResourceRedirect in [IRequestHandler ](https://github.com/cefsharp/CefSharp/blob/master/CefSharp/IRequestHandler.cs) interface.
Is it possible to integrate [onResourceRedirect](http://magpcss.org/ceforum/apidocs/projects/%28default%29/CefRequestHandler.html#OnResourceRedirect%28CefRefPtr%3CCefBrowser%3E,constCefString&,CefString&%29) API in CefSharp?

**Comment by amaitland** [comment]
It's in the `2272` branch and will be part of the `41` release.

https://github.com/cefsharp/CefSharp/blob/cef/2272/CefSharp/IRequestHandler.cs#L113

**Comment by amaitland** [comment]
Also be careful when referencing the `CEF1 API` documentation, it's quite out of date in most cases.

The `CEF3 API` is http://magpcss.org/ceforum/apidocs3/index-all.html

**Comment by LeMoussel** [comment]
Oups ! Sorry the CEF1 API documentation,I noted for the CEF3 API documentation.
That's in the 2272 branch, I test it & close this issue.
