### ISSUE TITLE
Does Flash plugin enable with offscreen browser?

### ISSUE THREAD

**Issue by LeMoussel** [cefsharp/CefSharp#1024]
Hello! 
I am using offscreen browser, how to tell if flash plugins is enable?
May have to install the Flash player manually? (perhaps from this page: http://get.adobe.com/flashplayer/?fpchrome)

Thanks!

**Comment by amaitland** [comment]
In `2272` you can see what plugins are loaded.

https://github.com/cefsharp/CefSharp/blob/cef/2272/CefSharp.Example/CefExample.cs#L107

**Comment by amaitland** [comment]
Also you can use the `debug-plugin-loading` command line option and look in the log file (this should work for all versions of `CefSharp`)

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/CefExample.cs#L40

**Comment by LeMoussel** [comment]
In `2272` with `CefSharp.OffScreen.Example`, I set `debug-plugin-loading ` command line option in `CefExample.cs` like this 
```
settings.CefCommandLineArgs.Add("debug-plugin-loading", "1"); //Dumps extra logging about plugin loading to the log file.
```

I got this in the log file
```
[0513/092618:ERROR:plugin_list.cc(215)] Loading plugin D:\VS Project\CEFSharp\2272\CefSharp-cef-2272\CefSharp.OffScreen.Example\bin\x86\Debug\pdf.dll
[0513/092618:ERROR:plugin_list.cc(215)] Loading plugin C:\Program Files\Adobe\Reader 11.0\Reader\Browser\nppdf32.dll
[0513/092618:ERROR:plugin_list.cc(215)] Loading plugin C:\windows\system32\Macromed\Flash\NPSWF32_17_0_0_169.dll
[0513/092618:ERROR:plugin_list.cc(215)] Loading plugin disabled
[0513/092618:ERROR:plugin_list_win.cc(275)] Could not get version info for plugin disabled
```

**Comment by jankurianski** [comment]
Is there an actual problem with Flash on your computer, or do you just want a C# example to detect if Flash is available on your user's computers?

**Comment by LeMoussel** [comment]
I haven't problem with Flash. On my computer, Flash plugin run OK on FireFox/IE/Chrome browser.
Yes I want to detect if Flash is available on users computers.

In `async void MainAsync()` I do `var plugins = await Cef.GetPlugins();`
In `plugins` variable, I have,  
```
-		[9]	{CefSharp.Plugin}	CefSharp.Plugin
		Description	"Shockwave Flash 17.0 r0"	string
		Name	"Shockwave Flash"	string
		Path	"C:\\windows\\system32\\Macromed\\Flash\\NPSWF32_17_0_0_169.dll"	string
		Version	"17,0,0,169"	string
```
So Flash plugin seems loaded.
So I don't understand why this is indicated `ERROR:plugin_list.cc .....` in the log file

**Comment by jankurianski** [comment]
I think the error is about a different plugin.  Does Flash work in CefSharp.Wpf?  Does it work in CefSharp.OffScreen?

**Comment by LeMoussel** [comment]
I test with this Adobe Flash tester page : http://www.adobe.com/fr/software/flash/about/
Flash work in CefSharp.Wpf.  I don't know if flash works with CefSharp.OffScreen because there is no flash information when the screenshot is taken.

**Comment by jankurianski** [comment]
I think Chrome loads the web page first, then the plugins later.  So if you are just taking the first screenshot, you won't see Flash loaded yet.

Try adding a delay before taking the screenshot, as in the comment here: https://github.com/cefsharp/CefSharp/issues/874#issuecomment-78396416

**Comment by LeMoussel** [comment]
*Adobe Flash Player Succesfuly installed*. It's work fine.
Thank you very much.
