### ISSUE TITLE
 Feature Request - JavaScript Integration Register Extension

### ISSUE THREAD

**Issue by LeMoussel** [cefsharp/CefSharp#1026]
Extensions are like window bindings except they are loaded into the context for every frame and cannot be modified once loaded : [CEF JavaScriptIntegration Extension](https://bitbucket.org/chromiumembedded/cef/wiki/JavaScriptIntegration#markdown-header-extensions)

Feature Request is to expose  cef / JavaScript tIntegration `CefRegisterExtension()`

**Comment by amaitland** [comment]
Would likely need to implement the new `Message Router`

http://magpcss.org/ceforum/apidocs3/projects/%28default%29/cef_message_router.h.html

**Comment by amaitland** [comment]
@LeMoussel Do you have a `PR` in the works?

**Comment by LeMoussel** [comment]
@amaitland : No.

**Comment by amaitland** [comment]
No problem, I've added this to the `3000` milestone.

**Comment by amaitland** [comment]
See #1164
