### ISSUE TITLE
cefsharp.common.xp

### ISSUE THREAD

**Issue by Alberttg77** [cefsharp/CefSharp#1027]
Hi,
I'm using CefSharp with visual studio.
What's the porpouse of the cefsharp.common.xp references?
I've I want to distribute my app in an XP system should I use this references and the CefSharp.Common references for W7 and W8?

Thanks.

**Comment by amaitland** [comment]
> What's the porpouse of the cefsharp.common.xp references?

`CefSharp.Common.XP` is not produced by the maintainers of this project. I've never seen it before. So can't help you there.

Official package is `CefSharp.Common`. `CefSharp` doesn't support `Windows XP` see https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#XPSupport

**Comment by amaitland** [comment]
You can see the official list of packages at https://www.nuget.org/profiles/amaitland

**Comment by xelplogoog** [comment]
Hi, see this topic
https://groups.google.com/forum/#!topic/cefsharp/J5gX7OKf7Rc

The only difference from oddicial package is that Platform Toolset changed to Visual Studio 2012 - Windows XP (v110_xp)

If you want your app working on XP you should use it, the official one just doesn't work. This one works on win7 and (I guess win8) as well.

There is only wpf package available, we don't use WinForms, sorry

**Comment by amaitland** [comment]
> The only difference from oddicial package is that Platform Toolset changed to Visual Studio 2012 - Windows XP (v110_xp)

@xelplogoog If you choose to build another set of packages, would be ideal if you could include this info, and also that they're `unofficial` packages, not provided by the `CefSharp` project directly. Thanks :+1:
