### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by bertnz** [cefsharp/CefSharp#1028]
Just did a clean clone from git and ran the build as per instructions.

Getting this error.

Error	1	error C1083: Cannot open include file: 'include/cef_base.h': No such file or directory	e:\cefsharp\cefsharp\cefsharp.core\Stdafx.h	15	1	CefSharp.Core

Looks like a bunch of header files are missing? 

Not sure exactly what the issue is - there was a support incident from 2014 related maybe to this around cef.sdk. I did a restore for the CefSharp.Core project but still no luck.

Can someone tell me where those header files should be coming from?

cheers,
Robert

**Comment by amaitland** [comment]
Try doing a rebuild all, then close `VS`, and try again.

> Can someone tell me where those header files should be coming from?

They come from `cef.sdk`. Check the packages are physically on disk, you should see a large number of header files in the `cef\include` folder. 

Most of the time this sort of problem is related to `VS+Nuget` not restoring things correctly. Make sure you have the latest version of `nuget` installed.

**Comment by bertnz** [comment]
OK so I just manually grabbed stuff from the cef.sdk package. Not sure why NuGet wasn't restoring them for me.

I took the CEF\include folder and pasted into CefSharp.Core and CefSharp.CefSharp.BrowserSubprocess.Core project folders. 

I then took the CEF\win32\debug\libcef.lib and CEF\win32\debug\vs2013\libcef_dll_wrapper.lib files from the cef.sdk nuget package and pasted them into the same two projects.

I can now build successfully!

**Comment by amaitland** [comment]
You shouldn't need to do any of that. It should just work magically. Are you using `VS2012` or `VS2013`? Do you have the latest `nuget` installed?

The fallback option is always using a `nuget restore` from the command line which is pretty much bulletproof. (Our build script uses this method).

Anyways, sounds like you've got it sorted.

**Comment by bertnz** [comment]
I am on Visual Studio 2013 NuGet 2.8.something. I have been missing with NuGet.configs on my machine so that may be something to do with it.

**Comment by amaitland** [comment]
If you go `Manage Nuget Packages for Solution` -> Settings (bottom left). Is `Nuget.org` in the package list and also ticked?
