### ISSUE TITLE
AccessViolationException in CefSharp.BrowserSubprocess.exe

### ISSUE THREAD

**Issue by jamespearce2006** [cefsharp/CefSharp#1034]
I get intermittent application crashes when dragging/dropping stuff into my browser window, following interaction with a bound object.
The exception information is below. I will try to reproduce the problem in the debugger.

Q - why does a crashing BrowserSubprocess.exe take out my entire application rather than just crashing the one web control instance?

    Application: CefSharp.BrowserSubprocess.exe
    Framework Version: v4.0.30319
    Description: The process was terminated due to an unhandled exception.
    Exception Info: System.AccessViolationException
    Stack:
       at CefSharp.Internals.MCefRefPtr<CefV8Value>.op_Assign(CefV8Value*)
       at CefSharp.Internals.JavascriptCallbackWrapper.Dispose(Boolean)
       at CefSharp.Internals.JavascriptCallbackWrapper.Dispose()
       at CefSharp.Internals.JavascriptCallbackRegistry.~JavascriptCallbackRegistry()
       at CefSharp.Internals.JavascriptCallbackRegistry.Dispose(Boolean)
       at CefSharp.Internals.JavascriptCallbackRegistry.Dispose()
       at CefSharp.CefBrowserWrapper.~CefBrowserWrapper()
       at CefSharp.CefBrowserWrapper.Dispose(Boolean)
       at CefSharp.BrowserSubprocess.CefRenderProcess.DoDispose(Boolean)
       at CefSharp.DisposableResource.Dispose()
       at CefSharp.CefAppWrapper.Dispose(Boolean)
       at CefSharp.CefAppWrapper.Dispose()
       at CefSharp.BrowserSubprocess.Program.Main(System.String[])

**Comment by jamespearce2006** [comment]
Exception is occurring in MCefRefPtr.h, at _ptr->Release();

            MCefRefPtr<T>% operator=(T* p)
            {
                // AddRef first so that self assignment should work
                if (p)
                {
                    p->AddRef();
                }
                if (_ptr)
                {
                    _ptr->Release();
                }

                _ptr = p;
                return *this;
            }

**Comment by jamespearce2006** [comment]
OK, I can reproduce this with the WpfExample project, and a gmail account.

1. Launch the Example project and go to gmail (assuming you have an account). 
2. Drag and drop a file from the desktop into the browser window
3. You'll be prompted to save the file. Provide a local filename, and click OK
4. Click "Compose" to start a new email
5. Drag a file into the mail composition window
6. If it doesn't crash, close the composition window, and repeat from step 2.

This may crash first time, or it may take a few tries.

**Comment by amaitland** [comment]
Much of the `Dispose/Finalize` code has been rewritten recently. Including a minor change to `MCefRefPtr` https://github.com/cefsharp/CefSharp/commit/9212cd4ba0a4fb2095c0b311288087303869c982

Hopefully this issue has been resolved (I haven't checked yet).

**Comment by amaitland** [comment]
See also https://github.com/cefsharp/CefSharp/commit/431cb511c366b2bcacb93c0551993466be512a08

**Comment by amaitland** [comment]
@jamespearce2006 Are you still experiencing this problem with a newer version?

**Comment by jamespearce2006** [comment]
I'll try and make some time to check...

**Comment by jamespearce2006** [comment]
Sorry for the delay.
I wasn't able to reproduce the problem with the version on the master
branch. I'd say it looks fixed.

**Comment by amaitland** [comment]
> I'd say it looks fixed.

Excellent :+1:
