### ISSUE TITLE
Strange behavior while await task.

### ISSUE THREAD

**Issue by LeMoussel** [cefsharp/CefSharp#1035]
#### Issue Summary
OffscreenBrowser task wait for while page to finish loading.

#### Technical details
* CefSharp Version: `2272`
* Operating System: Windows
* x86/x64: x86
* OffScreen: 

#### Steps to Reproduce
C# code:  [LeMoussel / CefSharpOSRex](https://gist.github.com/LeMoussel/598dd0a31c9a8369b262)

If I use  `MainAsync() ` (Line: 31) with  `await ` task, after a few seconds program exit with no errors. No execution off  `Console.ReadKey() ` &  `Cef.Shutdown() ` functions.

It works fine if used  `task.Wait()` (Line: 34 to 42).

What is your opinion?

**Comment by jankurianski** [comment]
If I use `MainAsync()` in `Debug` or `Release` mode (with/without debugger attached), I get a win32 crash:

Debug (debugger attached):

```
Problem signature:
  Problem Event Name:	BEX
  Application Name:	CefSharp.OffScreen.Example.vshost.exe
  Application Version:	11.0.50727.1
  Application Timestamp:	5011d445
  Fault Module Name:	StackHash_c68f
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	00000000
  Exception Offset:	PCH_03_FROM_libcef+0x011080BD
  Exception Code:	c0000005
  Exception Data:	00000008
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	3081
  Additional Information 1:	c68f
  Additional Information 2:	c68f81caa5aa69a210ea258f658351c5
  Additional Information 3:	7971
  Additional Information 4:	7971876b1d4f16198daba68af728eb08
```

Release (no debugger attached):

```
Problem signature:
  Problem Event Name:	BEX
  Application Name:	CefSharp.OffScreen.Example.exe
  Application Version:	41.0.0.0
  Application Timestamp:	555c2a3f
  Fault Module Name:	StackHash_5861
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	00000000
  Exception Offset:	PCH_A4_FROM_ntdll+0x0003CA2C
  Exception Code:	c0000005
  Exception Data:	00000008
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	3081
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	a10f
  Additional Information 4:	a10ff7d2bb2516fdc753f9c34fc3b069
```

Unfortunately not having used the new `async` keyword stuff before, I don't know what's going wrong.  But I thought it worth mentioning my symptoms are different from yours.

How are you running the program - in Visual Studio or double-clicking the .exe?  I wonder why you don't get an error?

**Comment by LeMoussel** [comment]
I running the program in 
   - Visual Studio 2012
   - Debug mode without debugger attached.

Indeed I do not understand why I don't get win32 crash but it seems that he has a symptom.

**Comment by amaitland** [comment]
Without looking into this in much detail it looks like disposing of `ChromiumWebBrowser` is causing the problem, likely `CEF` is still trying to render in the background, and it accesses some sort of disposed resource. The joys of `async` and subtle timings.

**Comment by amaitland** [comment]
Try this https://github.com/cefsharp/CefSharp/commit/8bcab8669475fd8523f70869fe24b06158700926

**Comment by LeMoussel** [comment]
Hélas, amaitland
Always the symptom.

**Comment by amaitland** [comment]
> Always the symptom.

Not sure I understand?

**Comment by amaitland** [comment]
> A track ......

Your code works fine now for me with https://github.com/cefsharp/CefSharp/commit/8bcab8669475fd8523f70869fe24b06158700926

**Comment by amaitland** [comment]
Anyways, if your still having problem I'd hold off on disposing the `ChromiumWebBrowser` instance, like wait until your ready to exit before disposing.

Also you should set `shutdownOnProcessExit` to `false` as your going to handle the `Cef.Shutdown()` call. (Should really always be false for `OffScreen`, it's better to explicitly handle.

**Comment by LeMoussel** [comment]
I set `shutdownOnProcessExit` to `false`., but I have always a crash with [8bcab86 ](https://github.com/cefsharp/CefSharp/commit/8bcab8669475fd8523f70869fe24b06158700926)

If I do 
```C#
await LoadPageAsync(browser).ContinueWith(prevTask => prevTask.Wait());
```
 my code works fine now for me with  [8bcab86 ](https://github.com/cefsharp/CefSharp/commit/8bcab8669475fd8523f70869fe24b06158700926)

**Comment by amaitland** [comment]
> I set shutdownOnProcessExit to false., but I have always a crash with 8bcab86

That wasn't really related, I just think it's better to handle the `Cef.Shutdown()` manually in the `OffScreen` scenario.

> await LoadPageAsync(browser).ContinueWith(prevTask => prevTask.Wait());

I would have though that `Wait()` is a `noop` in that scenario. Does it work in `Release` mode? Wondering if the compiler optimizes that away.

**Comment by LeMoussel** [comment]
Alex, I do not understand what you said by *"it's better to handle the Cef.Shutdown() manually in the OffScreen scenario."*

Have you an example?

**Comment by amaitland** [comment]
When you call `Cef.Initialize(settings, shutdownOnProcessExit: true)`, `AppDomain::CurrentDomain->ProcessExit` is hooked and will attempt to call `Cef.Shutdown()`, I think for `OffScreen`, your better to call `Cef.Shutdown()` manually (as your code currently does).

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Cef.h#L182

**Comment by amaitland** [comment]
No action is required, your code is fine now. I was just **attempting** (though obviously not very successfully) trying to provide clarification.
