### ISSUE TITLE
ChromiumWebBrowser Code Duplication

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#1037]
Look ways to reduce the duplication between the three flavors.

- Can possibly use extension methods to handle repeating code blocks internally, like clearing handlers and events that are common to `IWebBrowser`
- Make `Cut/Copy/Paste/etc` as obsolete so they can be removed in `43`

If anyone else has thoughts or suggestions I'd be interested to hear them.

**Comment by rassilon** [comment]
Close this one?
