### ISSUE TITLE
.Net User Control, proper way to clean up CefSharp

### ISSUE THREAD

**Issue by bjwallwin** [cefsharp/CefSharp#1039]
When my user control is terminating I want to ensure that CefSharp and all the sub-processes are shutdown properly and gracefully.  I looked in the WinForms sample and didn't see anything specific.  I could just null my  variable to the browser instance, but that seems clumsy to me.  I found a Dispose() method on CefSharp, should this be called as part of my cleanup process?

I am looking to ensure that things are shutdown properly so on subsequent initializations of my control there is no stagnant Cef resources hanging around.

**Comment by amaitland** [comment]
If you add a breakpoint to the `ChromiumWebBrowser.Dispose` method and run the `WinForms.Example` you'll see when you close a tab the `Dispose` method is called, we hook into the standard `Dispose` mechanism provided in `WinForms`.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.WinForms/ChromiumWebBrowser.cs#L94

You can of course explicitly `Dispose()` the control, there's no harm in calling `Dispose()` multiple times.

A basic example https://github.com/cefsharp/CefSharp/blob/master/CefSharp.WinForms.Example/Minimal/SimpleBrowserForm.cs#L130

It's also preferably to call `Cef.Shutdown()` explicitly, though if you don't `CefSharp` will attempt to cleanup for you.
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.WinForms/ChromiumWebBrowser.cs#L72

For every instance of `ChromiumWebBrowser` you create we keep a reference (until it's `Disposed`). If somehow there is a dangling reference, then `Cef.Shutdown()` will attempt to `Dispose()` them and release all of the managed resources. See
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Cef.h#L441

For the most part this works nicely. There are of course a cases where things don't go to plan, mostly involving `Threading`. `Cef.Shutdown()` should be called on the same thread as `Cef.Initalize()`, ideally both are executed on your `UI` thread to keep things simple.

**Comment by bjwallwin** [comment]
Great, thank you.

**Comment by infiniteloopltd** [comment]
I'm not sure if this will shed any light on the issue, but I found that both the Dispose() and Cef.Shutdown() hung if they were called by a thread that was not the same thread that created them - *EVEN IF* the call to dispose() & Shutdown() was correctly marshalled using Control.Invoke()

The solution I found was to poll on a public static variable from the main thread, until such time that it indicated that the application should exit, and then call dispose from there.  - Any improvements on this approach would be welcome, but at least it means that I don't end up with dangling "SubBowser" processes.

**Comment by amaitland** [comment]
> I found that both the Dispose() and Cef.Shutdown() hung if they were called by a thread that was not the same thread that created them - _EVEN IF_ the call to dispose() & Shutdown() was correctly marshalled using Control.Invoke()

If you `Dispose` of the `ChromiumWebBrowser` control whilst it's attached to the parent control/form it will by default send a `WM_CLOSE` message, so your `Form` closes and is never able to successfully return to the calling `Thread`. You could use a `SynchronizationContext` see https://stackoverflow.com/a/7480544/4583726 (You can probably also use `BeginInvoke`).

In my opinion calling `Dispose` for any `UI Component` from `Control.Invoke` is asking for trouble. (Calling `Control.Invoke` really should be avoided in general, `BeginInvoke` should be used if at all possible). 

If you haven't already please read https://github.com/cefsharp/CefSharp/wiki/General-Usage#initialize-and-shutdown

You must call `Cef.Shutdown` on the same thread that `Cef.Initialize` was called. Version `55` and above will throw an exception if you call `Cef.Shutdown` on a different thread. You can see in https://github.com/cefsharp/CefSharp/blob/cefsharp/67/CefSharp.Core/Cef.h#L413 I'm surprised you're not seeing this exception when you attempted to `Shutdown` from the non `UI` thread. Are you using version `67`? (The current supported version)

> The solution I found was to poll on a public static variable from the main thread, until such time that it indicated that the application should exit, and then call dispose from there.

Is there a reason you are not using the standard `Form` closing events/overrides and just dealing with this when the form closes?

If you so choose you can disable the default `Application.Exit` hook and manually call `Cef.Shutdown`. See https://github.com/cefsharp/CefSharp/blob/cefsharp/67/CefSharp/CefSharpSettings.cs#L71

You can call `Cef.Initialize` before the app message loop starts (`Application.Run`) and call `Cef.Shutdown`  after the app message loop exits.

In general I would prefer not to resurrect **3 1/2year** old closed issues, see https://github.com/cefsharp/CefSharp#contact for support options.

**Comment by amaitland** [comment]
As a general comment I'll also point out that calling `Form.Close` on a form that was displayed with `ShowDialog` won't call `Dispose`, you'll need to manage that scenario manually. See 
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.form.close?view=netframework-4.7.2#remarks 

Also I should point out that having the sub processes not closing is a common problem with `Chromium`, the problem isn't limited to `CEF/CefSharp`. See #2359 for a more detailed discussion.
