### ISSUE TITLE
The problem that don't show font.

### ISSUE THREAD

**Issue by BestofBestDeokwan** [cefsharp/CefSharp#1040]
hi, everyone.

I found error that don't show font.

Almost, this symptom is occurred  by small font.

I found solution about this problem.  but i don't like this solution.

that i found, below look at.

Turn off this option. so above problem solve.

Computer > Properties > advanced System settings > Performance Options > Smooth
 edges of screen fonts.

ladies and zentleman, please tell me solution about this problem.

Spec 

OS : Window 7

Use : CefSharp.WinForms

Version :  CefSharp.WinForms    37.0.0.0

**Comment by jankurianski** [comment]
Please include answers to every question under the sentence "Your bug report should always follow this template:" in this document:
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue

**Comment by amaitland** [comment]
Talk about cryptic! lol

It's probably worth using `cefclient` to see if the problem is reproducible, I'd imagine anything font related is probably an upstream thing (unless it's `WPF High DPI` support related).
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

**Comment by amaitland** [comment]
@BestofBestDeokwan Any further comment?  Will close this in a few days if no response.
