### ISSUE TITLE
Are the handles for the cursors constant?

### ISSUE THREAD

**Issue by cuddlyogre** [cefsharp/CefSharp#1042]
I am using CefSharp to draw to a Texture2d in monogame. I have run across a bit of complication with regards to the mouse cursor.

Does void IRenderWebBrowser.SetCursor(IntPtr handle) always return the same handle for any given mouse cursor? I was able to record 65541 for auto, 65547 for crosshair, and so on, and they appear to be constant between runs. I am concerned though, because some cursors such as copy, cell, and row-resize all have radically changing numbers, sometimes 8 digits long, and sometimes negative.

I've tried to use 
        `CursorInteropHelper.Create(new SafeFileHandle(handle, ownsHandle: false)) `
from the WPF example but I feel I am missing something.

**Comment by jankurianski** [comment]
> but I feel I am missing something

To be precise, you are missing the `CursorType` and `CefCursorInfo`:

Here is where in CefSharp that CEF tells us about the new cursor (and CefSharp throws away the extra info):
https://github.com/cefsharp/CefSharp/blob/8755a9496ffbd5f21bc6ef062bce687a22d83938/CefSharp.Core/Internals/RenderClientAdapter.h#L174-L178

Here is the CEF documentation about the extra info:
http://magpcss.org/ceforum/apidocs3/projects/%28default%29/CefRenderHandler.html#OnCursorChange(CefRefPtr<CefBrowser>,CefCursorHandle,CursorType,constCefCursorInfo&)

The `CefCursorHandle` on Windows is defined as `HCURSOR`:

`#define cef_cursor_handle_t HCURSOR`

http://magpcss.org/ceforum/apidocs3/projects/%28default%29/cef_types_win.h.html

Hopefully this is enough to get you on the path to figure out what the parameters mean and hopefully submit a PR for extra parameters or documentation? :smile:

**Comment by amaitland** [comment]
The extra params are relatively new see https://bitbucket.org/chromiumembedded/cef/commits/eb3f80b41dd857038b0fdf73c8550e32c573763e?at=2171

At some point it would be nice to add custom cursor support to `WPF`, so any contributions would be most welcome :+1:

**Comment by amaitland** [comment]
> I am using CefSharp to draw to a Texture2d in monogame

Open Source?

**Comment by cuddlyogre** [comment]
> Open Source?

If you are asking if I'm willing to share... sure. I used the OffScreen example as my inspiration. [Gist](https://gist.github.com/cuddlyogre/7115b0c8164cd0b841b1). 

What my ultimate goal is, is to be able to do my interface in HTML. I had considered building a barebones HTML parser, but found CefSharp and was immediately overjoyed.

**Comment by amaitland** [comment]
> If you are asking if I'm willing to share... sure. I used the OffScreen example as my inspiration. Gist.

Thanks :+1: Was curious on how you were mapping to the `Texture2D`. Just for reference, for every frame that's rendered the data is being copied twice, so your performance may suffer a little.

**Comment by amaitland** [comment]
Also with a couple of tweaks to the `OffScreen` version you could implement your own rendering and have it handle the rest, save the code duplication.

**Comment by cuddlyogre** [comment]
I'll look into the data being copied twice. Can't have that...

I actually started with the Offscreen browser, but it doesn't implement mouse events. I worked off of the WPF control next, which lead me to just using the IRenderWebBrowser, which is what the Offscreen and WPF libraries both use to do their thing. It wound up being very straightforward.

**Comment by amaitland** [comment]
> I'll look into the data being copied twice. Can't have that...

To get the best performance you might have to rewrite some of the internals to suite your unique requirements.
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Internals/RenderClientAdapter.h#L169

**Comment by cuddlyogre** [comment]
I've submitted a PR to add the cursor type to the SetCursor call.
https://github.com/cefsharp/CefSharp/pull/1044

**Comment by fr0** [comment]
@cuddlyogre - do you have a version of your example that works with the latest `CefSharp.Offscreen` code? I wasn't able to compile it.

**Comment by cuddlyogre** [comment]
I do not. I'm sorry.
