### ISSUE TITLE
ClearType in off-screen rendering

### ISSUE THREAD

**Issue by robertvazan** [cefsharp/CefSharp#1045]
I am having trouble getting CefSharp to render fonts correctly. CefSharp renders text in shades of gray, which looks blurry. I would like all text to be rendered using cleartype / subpixel rendering.

I am using WPF API of CefSharp. I've tested with CefSharp.MinimalExample and it looks like WinForms API does render using CefSharp. Off-screen API has the same problem as WPF API.

I've also tested with cefclient to see whether there's support for this feature in CEF itself. I ran cefclient with --off-screen-rendering-enabled parameter and it did render using cleartype.

What prevents CefSharp from rendering via cleartype?

I am using CefSharp 39 and I tested with cefclient 3.2171.1979.

**Comment by jankurianski** [comment]
I recall a few similar issues in the past, could you take a look at these and figure out if the issue you are seeing is different, try out the recorded workarounds, and see what happens?

#819 WPF blurry problem Windows 8.1
#428 Fix text rendering in WPF

**Comment by amaitland** [comment]
If #428 is relevant then #1019 was merged recently which provides the ability to specify `transparently`

I'd also look at testing again with `CefSharp.Wpf.Example` as it has an `app.manifest` which has some bearing on this sort of thing (at least in `WinForms`).

**Comment by robertvazan** [comment]
Thanks for pointers. #428 turned out to be relevant. One has to use the following option to enable ClearType in WPF:

```` C#
browser.BrowserSettings = new BrowserSettings()
{
    OffScreenTransparentBackground = false
};
````

This option is unfortunately available only in trunk. There appears to be a new release that didn't make it into NuGet yet. This new release will likely include the option.

**Comment by amaitland** [comment]
If you look closely at #1019 then you'll see that it's been set for `Milestone` `39.0.2`, which will probably be on `Nuget` in the next week. (It's on `MyGet` currently, just needs a final round of testing).

**Comment by jankurianski** [comment]
Added a new section to the troubleshooting wiki:
https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#blurry-text

**Comment by amaitland** [comment]
`39.0.2` has been released to `Nuget.org`

https://github.com/cefsharp/CefSharp/releases/tag/v39.0.2
