### ISSUE TITLE
RegisterJsObject works for WinExe output but not Library project

### ISSUE THREAD

**Issue by quisquous** [cefsharp/CefSharp#1046]
I have a super simple WPF example that creates a Window that contains a UserControl that contains a ChromiumWebBrowser.  In the custom UserControl code WebBrowser property setter, it registers a dummy object and loads an HTML string that just checks if the dummy object was bound and sets a div to display success or not.

If I add an App.xaml that loads the Window, then the dummy .net object is registered successfully.  If I compile the project into a dll, which some other code loads and then calls a function that creates a Window and Show()s that window, the .net object is not registered successfully.

In both cases the Window, UserControl, and ChromiumWebBrowser are all created exactly once.  The same calls happen, but in one case the registration is successful and in the other it fails.  There's no difference but the way the Window is created, which seems really odd.  I do not think this is the same as issue 602, as the call to RegisterJsObject is in the same place in both cases.

Is there some way to debug why RegisterJsObject may be failing?

I'll try to simplify my code and post a test case.

**Comment by amaitland** [comment]
> If I compile the project into a dll, which some other code loads and then calls a function that creates a Window and Show()s that window, the .net object is not registered successfully.

Is the `html` rendering in this scenario? Are you copying the `CEF` dependencies to your projects `bin` directory? If you call `Cef.Initailize()` with `performDependencyCheck:true` to make sure all the relevant files are in place.

> I'll try to simplify my code and post a test case.

If you can fork https://github.com/cefsharp/CefSharp.MinimalExample to demo your problem that would be great :+1:

**Comment by quisquous** [comment]
Thanks for the quick response.  I don't mean to waste anybody's time getting my code working, but it's very mysterious to me why one framework succeeds and the other does not, and it smelled like maybe being a legitimate bug.

To answer your questions, the html renders in both cases.  The html itself checks if the object was registered and displays text.  In one case, it succeeds and in the other it does not.  I am copying dependencies (it crashes without them). If I call Cef.Initialize with performDependencyCheck=true, then it loads just fine.

Working: https://github.com/quisquous/CefSharp.MinimalExample/tree/registration_working_app
Broken: https://github.com/quisquous/CefSharp.MinimalExample/tree/registration_broken_dll

I didn't have a chance yet to write a standalone C++ app that loads the dll.  You can see the commit message for details on how to load it.

**Comment by amaitland** [comment]
Hmm, if everything else is working then it's likely the `WCF` channel has failed to open. Does running the `3rd` party app as `administrator` resolve the problem?

If you debug the browser sub process you might get a better understanding of what's going on.
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/CefExample.cs#L35
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/CefExample.cs#L73

If you build the source locally, specify the `BrowserSubprocessPath`, add the `renderer-startup-dialog` command line arg and then attach `Visual Studio` to the running instance (it'll prompt you, attach the debugger before pressing ok to the dialog message).

This is a pretty obscure one, so you'll have to do some stuffing around if you want to get it resolved.

**Comment by quisquous** [comment]
A friend built my broken example and it worked for them.  This led me to try a few things with the third party app.  It turned out that the third party app was also loading https://github.com/RainbowMage/OverlayPlugin, which also uses Cef (but not CefSharp).  And, if both of them are loaded, then I am unable to register js objects.  It smells a lot like a shared dll and something static.

I guess the end result is that this really is the same as issue 602.  Thanks for your help!
