### ISSUE TITLE
Dialog Handler not firing when invoked from Flex component

### ISSUE THREAD

**Issue by Davidhanson90** [cefsharp/CefSharp#1047]
I have a simple web page which is hosted via CEF 3.  The page hosts a flex widget (owned by another team and hosted in an IFRAME) which provides the user the ability to pick a file and upload it.  To do this they use the FileReference API

http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/FileReference.html

Accoridng to the docs this will invoke the OS file dialog picker.  I have tested this inside of CEF and it does show the dialog. However its an old looking dialog and not the windows 7 one I get when I run in chrome. Also its worth mentioning that the one in CEF does not enforce modality. 

So in order to sort this out I thought I would hook into the dialog handler and handle the process itself in our app code. I created a Dialog Handler and attached it to my ChromiumWebBrower window but it does not fire. 

However it does fire with this test page

http://jsfiddle.net/fEBFp/2/

Has anyone come across this issue before or know where I may be going wrong?

**Comment by amaitland** [comment]
`CefSharp` being a wrapper around `CEF` means that a lot of features are just basic wrappers, like this one in particular. See code 

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Internals/ClientAdapter.cpp#L525

In this instance you might be better searching through http://magpcss.org/ceforum/ and posting there if your unable to find anything relevant. Before posting it's probably worth attempting to replicate the problem using `cefclient`, if you build it from source you should be able to put a breakpoint in the relevant method. (You don't have to build the whole thing from source, if you download a version from `cefbuilds.com` you can just build `cefclient`).

https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

The other option is to try a newer version you can build the `2272` branch from source if your so inclined which is available at https://github.com/cefsharp/CefSharp/tree/cef/2272

(In future please include version and flavor, e.g. `WinForms`, or `WPF` when creating an issue).

**Comment by amaitland** [comment]
Anything further before closing this?

**Comment by Davidhanson90** [comment]
No fine thanks
