### ISSUE TITLE
WPF: Not loading (white screen) when opened from a slow location

### ISSUE THREAD

**Issue by arogozine** [cefsharp/CefSharp#1048]
Hello,

CEF# 39.0.1 - .NET 4.5.2 / .1 WPF (VS2013) project on Windows 7 - 32-bit executable, RELEASE and DEBUG builds. I am using the NuGet package.

I am having an issue where the CEF# control does not render the web browser - the control remains blank (white).
Reproducible when running from a slow drive such as a network drive (takes a minute to load) - not reproducible when running app from an SSD (instant load). I suspect a race condition somewhere in the code?
I cannot reproducible while running from Visual Studio.

I have a right click menu with various bindings (Print, Refresh, Etc.) when this issue occurs the right click menu is not present - so it errors out before that.

Opening the application a second usually fixes this issue (CEF# gets rendered) - I am guessing because Windows cached things.

As I was writing about this issue, I tried the Test-App..
I tried the cefclient.exe (Test-App 21MB) and that complained that libcef.dll is missing from my system (but libcef is part of the 7z package) when loading from a network location (slow) but locally it did not complain and loaded http://www.google.com/ (!!)

Is this something that can be worked around somehow?

**Comment by amaitland** [comment]
We have no control over how the dependencies are loaded. You can search/ask on http://magpcss.org/ceforum/ and hope someone has some ideas.

Otherwise you might need to get creative, maybe have some sort of app loader that copies your app locally and executes.

**Comment by rassilon** [comment]
It wouldn't be completely silly to have a splash screen displayed until the web page is further along being loaded. I've considered this for our CefSharp usage due to not having intelligently combined all of the .js files our web UI currently fetches from browsers.

**Comment by arogozine** [comment]
The app executes locally actually - it is just easy to reproduce a white screen of death while loading from a network location.

Any tips on detecting such an error? (Preferably before loading `<cefSharp:ChromiumWebBrowser ...>`)
`Cef.Initialize(settings, true, false)` doesn't seem to return false.
Setting `BrowserSettings` and Handlers doesn't seem to throw.
And `browser.LoadError` doesn't seem to be hit.

**Comment by amaitland** [comment]
What about `IRequestHandler.OnRenderProcessTerminated`, does that get called?

Sounds like the `BrowserSubProcess` that's having trouble launching.

You could try copying all the dependencies locally on startup to a temp location and then specifying `CefSettings.BrowserSubprocessPath` (full path, including filename).

**Comment by amaitland** [comment]
Anything further before closing this?

**Comment by creeveshft** [comment]
I have this same issue.  I have tried running the minimal example and it works fine, but when I try the same code in my application it shows a white screen instead of rendering google.com.

My application does not have its own app.xaml and is actually a class library DLL that is loaded by another executable. Perhaps this causes some issue?

When the control first loads it does not show the right click context menu and is just a white screen.

**Comment by amaitland** [comment]
> actually a class library DLL that is loaded by another executable

And how are you copying the `unmanaged` dependencies? You will need to manually copy them to the executing folder. `CefSharp` adds `.targets` files to your project file, you can see which files are copied.

Further questions please ask them on https://gitter.im/cefsharp/CefSharp#
