### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by canton7** [cefsharp/CefSharp#1052]
Received this report from a user. Stack trace comes from the Windows event log. I'm afraid I don't have any other information, or steps to reproduce, but I thought it would be best to mention it anyway.

CefSharp-WPF 37. Windows 8. 64-bit.

```
Application: SyncTrayzor.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
Stack:
   at <Module>.scoped_refptr<CefBrowser>.{ctor}(scoped_refptr<CefBrowser>*, scoped_refptr<CefBrowser>*)
   at <Module>.CefSharp.Internals.ClientAdapter.GetCefBrowser(CefSharp.Internals.ClientAdapter*, CefRefPtr<CefBrowser>*)
   at <Module>.CefSharp.Internals.RenderClientAdapter.TryGetCefMainFrame(CefSharp.Internals.RenderClientAdapter*, CefRefPtr<CefFrame>*)
   at CefSharp.ManagedCefBrowserAdapter.ExecuteScriptAsync(System.String)
   at <Module>.CefSharp.Internals.ClientAdapter.OnLoadEnd(CefSharp.Internals.ClientAdapter*, CefRefPtr<CefBrowser>*, CefRefPtr<CefFrame>*, Int32)
```

**Comment by amaitland** [comment]
> CefSharp-WPF 37

`37` is no longer maintained.

**Comment by canton7** [comment]
You're saying this issue, whatever it is, has been fixed?

**Comment by amaitland** [comment]
> You're saying this issue, whatever it is, has been fixed?

Where did you get that impression? I'm saying that we no longer support version `37`. Latest stable build is `39.0.2`.

**Comment by canton7** [comment]
I'm not asking for support. I'm reporting a potential issue. 

If someone reported a crash in an old version of one of my libraries, I would check to see whether it was still an issue in the latest version. If it wasn't, then I'd use the "not supported: you should upgrade" line. If it was, I would fix it.

I'm not a Cefsharp contributer, so of course what you do with crash reports is entirely up to you. I can see whether the affected code is still present in master if you'd like though?

**Comment by amaitland** [comment]
> If someone reported a crash in an old version of one of my libraries, I would check to see whether it was still an issue in the latest version. If it wasn't, then I'd use the "not supported: you should upgrade" line. If it was, I would fix it.

The code has changed dramatically since `37` was released, at least one of the methods in the `stack trace` no longer exists. Much of the other code base was rewritten (something in the other of `500+` commits were made since the initial `37` release). Without a way to reproduce the problem, logging an issue against `37` is somewhat of a moot point.

> I can see whether the affected code is still present in master if you'd like though?

By all means.

**Comment by canton7** [comment]
Cool, thanks for the detail/explanation! That figures.

>>    I can see whether the affected code is still present in master if you'd like though?
> By all means. 

I'll believe you :)
