### ISSUE TITLE
Feature Request ability to pass CefRequestContext through BrowserSettings 

### ISSUE THREAD

**Issue by etomm** [cefsharp/CefSharp#1056]
This is needed to have multi user and multi indpendent zoomed pages. 

We are really dependant on this feature to be implemented

**Comment by amaitland** [comment]
@etomm Are you working on a `PR`?

**Comment by etomm** [comment]
Yes I worked on a PR https://github.com/cefsharp/CefSharp/pull/1125 

Sorry to be so late, but I had other works to finish before it. Still not working the independent zoom level... someone can look at the PR? I suppose I did something wrong

**Comment by amaitland** [comment]
Merged #1135 so closing
