### ISSUE TITLE
CefSharp.Wpf slow at high resolution.

### ISSUE THREAD

**Issue by JohannesMoersch** [cefsharp/CefSharp#1058]
I have an empty WPF project with only a ChomiumWebBrowser control and it is really slow. At 1080p scrolling up and down a web page or playing a youtube video feels a little choppy, but it isn't all that noticable. However, at 3840x2160 everything is super choppy. A chrome window at the same website is totally smooth. I have confirmed this on another computer as well. Any idea what the problem is? Perhaps it has to do with how CefSharp draws the browser into WPF?

**Comment by jankurianski** [comment]
> Perhaps it has to do with how CefSharp draws the browser into WPF?

Correct.  The WPF control uses off-screen rendering (in simple terms, each frame is copied into a bitmap instead of being drawn directly onto the screen as Chrome does).  There are some possible performance improvements I have read about in previous issues (searching for `OSR` and `bitmap` should yield something).

So, a comparison between the WPF control and Chrome isn't fair.  A fair comparison is running CEF's `cefclient` test application in off-screen rendering mode.  There are instructions for that here:

https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

Could you try out the command line next to `To compare with WPF run...` and let us know what you observe at 3840x2160?

**Comment by amaitland** [comment]
If your using an `Intel` graphics card then it might be worth disabling `GPU acceleration` and testing again.

https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#troubleshooting-graphics-video-or-performance-problems

**Comment by JohannesMoersch** [comment]
This is running on the integrated Intel GPU (on a Haswell chip) and I can't seem to force it to use the Nvidia (I tried through drivers). Disabling GPU acceleration helped, but it still wasn't great.

I compared my WPF performance to the cef client (3.2171) application jankurianski linked. Performance with off-screen rendering was comparable to in my WPF app. However, disabling off-screen rendering completely solved the performance problems, so the problem seems to lie the off-screen rendering techniques. I know that isn't in your hands, but I did compare 3.2171 with 3.2378 and there was a noticable performance improvement (at least with GPU acceleration disabled). I tried just dropping the new dlls into my WPF application, but after doing so my app would crash on load failing at Cef::Initialize(). I was careful to use x64 for my WPF x64 build. How would I go about updating to a newer version of CEF?

**Comment by LukePulverenti** [comment]
@JohannesMoersch out of curiousity, have you tried with windows forms just for comparison purposes?

**Comment by markwaddle** [comment]
Out of curiosity, why does the WCF control use off-screen rendering where-as the WinForms one does not?

**Comment by amaitland** [comment]
> Out of curiosity, why does the WCF control use off-screen rendering where-as the WinForms one does not?

`WPF` support for hosting native controls in `.Net 4.0` is abysmal. The fixes introduced in `.Net 4.5 beta` never made it into the official release.

Some of the problems include

> - Resizing is limited because only the container(hwndhost) will be resized, not the contained component itself.
> - Forget about rotation and skewing.
> - The hosted component is a black hole for your application : always at the top (forget the z-order!).
> - Opacity can’t be applied to an hosted Win32 control.
> - VisualBrush do not work with Win32 controls.

http://www.jonathanantoine.com/2011/09/24/wpf-4-5-%E2%80%93-part-8-no-more-airspace-problems-integrating-wpf-with-win32/
http://stackoverflow.com/questions/9535167/has-airspace-support-definitely-been-dropped-in-wpf-4-5

Here's quite a comprehensive article on mitigating some of the problem.
http://blogs.msdn.com/b/dwayneneed/archive/2013/02/26/mitigating-airspace-issues-in-wpf-applications.aspx

The pieces are there should you wish to experiment with implementing a native version hosted in `WPF`. (Or there is of course the `WinForms host` control`).

**Comment by amaitland** [comment]
> How would I go about updating to a newer version of CEF?

There are quite a few steps involved, basically each version of `CefSharp` is statically compiled against a specific version of `CEF`. You can start with repackaging the binaries https://github.com/cefsharp/cef-binary/wiki, then you need to upgrade `CefSharp` to use those updated packages, including modifying the source to reflect any upstream changes.

For reference `master` has been updated to `2357`. `CEF` has recently created a `2454` branch, though still waiting for compiled versions to appear on `cefbuilds.com`

**Comment by amaitland** [comment]
https://bitbucket.org/chromiumembedded/cef/commits/e3c1d8632eb43c1c2793d71639f3f5695696a5e8?at=2454

Based on the `upstream` commit you can try a specific set of command line arguments for best performance.

**Comment by amaitland** [comment]
I've added a helper method to `CefSettings` so will add the command line arguments in one go. 

https://github.com/cefsharp/CefSharp/commit/fa89d306e1c50164405e7b8792762c7d3a4ce3c2

**Comment by ourplan9000** [comment]
CefSharp.Wpf  at high resolution is slow ,is not fix?
