### ISSUE TITLE
Bug: can't run in another computer

### ISSUE THREAD

**Issue by khoaakt** [cefsharp/CefSharp#1061]
I develop my web browser in my computer and it run perfectly. But i copied it to another computer(it isn't have Visual Studio, just install .net 4.0 and it get crashed) 
![11406830_375442059316906_5004218933353406840_n](https://cloud.githubusercontent.com/assets/6000592/8029505/25f6a1ce-0de8-11e5-8d19-4f06c9a0ae0c.jpg)
I make sure i copied all of component without missing any file. How can I fix it and why?
(CefSharp 39.0.0.2):

Update: Example App Crashed with that message, too :cry:

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/blob/master/NuGet/Readme.txt#L18

**Comment by khoaakt** [comment]
@amaitland yes, i have read it. i installed it and get that error again

**Comment by jamespearce2006** [comment]
@khoaakt, the exception is System.IO.FileNotFoundException.

Can you use [ProcMon](https://technet.microsoft.com/en-us/library/bb896645.aspx) to see what files are being accessed during startup of the process, and see which file is not being found?

**Comment by amaitland** [comment]
Based on your second screenshot you've built `CefSharp.WinForms.Example` from source in `Debug` mode. You need to build in `Release` mode to run on a a computer without `VS` installed.

Read the **Note** in the following `FAQ` item.
https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#6-how-do-i-include-the-visual-studio-c-2012-redistributables-on-the-target-app

**Comment by khoaakt** [comment]
thanks @amaitland. It's fixed, please highlight the note more with red color !

**Comment by jankurianski** [comment]
> It's fixed, please highlight the note more with red color !

@khoaakt Anyone can edit the wiki.  Please don't tell others to do work in open-source projects, it is impolite.

Also, most people are using the NuGet packages and will not have this problem.

**Comment by khoaakt** [comment]
@jankurianski Sorry, it's my bad.
