### ISSUE TITLE
Can't get EvaluateScriptAsync to return anything

### ISSUE THREAD

**Issue by MJPA** [cefsharp/CefSharp#1062]
Trying something really basic as a test:

    var task = _browser.EvaluateScriptAsync(@"
      (function () {
        return 'hello!';
      })();
    ");
    
    task.ContinueWith(t =>
      {
        if (t.IsFaulted || !t.Result.Success) return;
        MessageBox.Show(t.Result.Message);
      }, TaskScheduler.FromCurrentSynchronizationContext());

The above code is an event handler for FrameLoadEnd and just gives me a blank Message property. Success is true. Any ideas? (CefSharp.Winforms - 39.0.2)

**Comment by jamespearce2006** [comment]
The result of the evaluation is in JavascriptResponse.Result, not JavascriptResponse.Message. Message contains information regarding the cause of a failure.

The line should be:

    MessageBox.Show(t.Result.Result.ToString());

**Comment by MJPA** [comment]
So stupid! Thanks!!

I misread the example on the FAQs... t.Result.Result works fine!
