### ISSUE TITLE
Delay in browser initialisation

### ISSUE THREAD

**Issue by bharatdwarkani** [cefsharp/CefSharp#1064]
While using ceff sharp Browser there is an noticeable delay in browser initialisation ```IsBrowserInitialized Property to become true``` how can this be minimised. Because in an application there are 5-6 browsers and it depends on html content retrieved from Data base doesn't uses website for loading. - WPF Application

**Comment by amaitland** [comment]
Try disable proxy resolution
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/CefExample.cs#L39

See item `20` in the `CEF FAQ` http://magpcss.org/ceforum/viewtopic.php?f=6&t=10567&p=16258&hilit=no+proxy+server#p16258

If you don't use plugins you can disable their discovery
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/CefExample.cs#L41

**Comment by bharatdwarkani** [comment]
I have disabled it still delay persists

```
public partial class App : Application
    {
        public App()
        {
            var settings = new CefSettings();

            settings.PackLoadingDisabled = true;
            settings.CefCommandLineArgs.Add("disable-plugins-discovery", "1");
            settings.CefCommandLineArgs.Add("no-proxy-server", "1");

            Cef.Initialize(settings);
        }
    }
```

**Comment by amaitland** [comment]
Newer versions of `CEF` are faster, you can try the `41.0.0-pre01` package I released today, see if that makes any difference. See #617 for details of the `MyGet` feed.

Otherwise you can try searching http://magpcss.org/ceforum/
Someone there might have some ideas.

**Comment by amaitland** [comment]
Anything further before we close this?

**Comment by bharatdwarkani** [comment]
I will check this after CEF 41 stable release is out.
