### ISSUE TITLE
WPF Flash (NPAPI) plugin not accepting IME input

### ISSUE THREAD

**Issue by coldicelion** [cefsharp/CefSharp#1065]
i use NPAPI flash plugin in cefsharp project ,i found that every IME can not be used in flash page.
of course i can input english words but not (chinese, korean,japanese) words in the flash page's textbox.

there is a test page,please try it in the cefsharp WPF project:
http://baseonmars.co.uk/bugs/wmode/

**Comment by amaitland** [comment]
Try https://github.com/cefsharp/CefSharp/pull/934/files#diff-670f0330cbeb12f911a2f6f4af481dc2R23

If that doesn't work it's probably worth seeing if the problem reproduces using `cefclient` example app. See https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

To my knowledge nobody on the `CefSharp` team is particular familiar with `IME`, so there probably isn't much help we can offer.

**Comment by coldicelion** [comment]
thanks! i just download a new chromium version(3.2357.1780),i found if i use the PPAPI FLASH plugin,  there is no problem, IME works fine, i can input anything chinese words i want. but currently Cefsharp's version is 3.2272(41.0), can not use the PPAPI FLASH plugin, i just want to know, when will you update the version to 3.2357.1780? thank you very much!

**Comment by amaitland** [comment]
An official `2357` release is a few months away I'd imagine. Plan was to update our development branch when `cefbuilds.com` produces a `CEF 3.2357.1280` `x64` build.

**Comment by coldicelion** [comment]
thanks again !

**Comment by amaitland** [comment]
`master` has been updated to include `PPAPI` support, might be worth taking it for a spin.

**Comment by coldicelion** [comment]
that's a very good news! thank you very much! ^_^

**Comment by coldicelion** [comment]
i've just tested it, it works fine, but there is another problem with the PPAPI plugin, when we load a page with a flash content in it, it will pop a black console window very quickly and then it automatic closed itself, could you please tell me why?

**Comment by jankurianski** [comment]
> when we load a page with a flash content in it, it will pop a black console window very quickly and then it automatic closed itself

This is a known CEF issue, see http://magpcss.org/ceforum/viewtopic.php?f=6&t=13094

**Comment by coldicelion** [comment]
thanks again!!  i find a way to fix it, but i can't find the SandBox option in CefSharp,  is there any option in  CefSharp i can turn on SandBox ?

**Comment by amaitland** [comment]
There is no `SandBox` support in `CefSharp`. See #697

**Comment by amaitland** [comment]
Closing this as the problem in question has been resolved.

I had made a note about the `PPAPI` console flashing up see https://github.com/cefsharp/CefSharp/issues/799#issuecomment-124034087
