### ISSUE TITLE
Support Mouse Event in CefSharp.Winforms

### ISSUE THREAD

**Issue by khoaakt** [cefsharp/CefSharp#1066]
It's me agian!
Do anyone planned to put mouse event (mousedown, mousemove,...etc) to CefSharp.Winforms?
It will very important for cef developer. Example is developing a mouse-gesture handler and more...

**Comment by rassilon** [comment]
CEF doesn't expose these kinds of events, so CefSharp can't expose them from the WinForms wrapper control either. You would need to inject the correct JavaScript handlers into every created frame that callback into .Net functions with the necessary data.

However, CEF does expose an interface for controlling the contents of the context menu.

Bill
