### ISSUE TITLE
How to disable right click context menu

### ISSUE THREAD

**Issue by richmondwang** [cefsharp/CefSharp#107]
Hey, how can I disable the right click context menu on the web view.

I need not to show the source code of my html... thanks

**Comment by joseph-benoy** [comment]
> @richmondwang if you are in control of the HTML being loaded (i.e. you're loading it in manually or restricting the WebView to only navigate to a certain set of pages) then just add this to the body tag of your page(s):
> 
> ```js
> oncontextmenu="return false"
> ```
> 
> See https://github.com/intninety/yaircc/blob/master/yaircc/UI/default.htm if you need an example.

Works fine thanks!
