### ISSUE TITLE
Find Option Dialog doesn't appears on pressing CTRL+F by default in WPF

### ISSUE THREAD

**Issue by bharatdwarkani** [cefsharp/CefSharp#1070]
Is there any interface or option which needs to be implemented/enabled for Find Dialog (CTRL+F) by default this doesn't appears in browser.

**Comment by amaitland** [comment]
> Find Dialog (CTRL+F) by default this doesn't appears in browser.

There is no `Find Dialog` built in, you have to implement that yourself.
