### ISSUE TITLE
Get crashed when popup

### ISSUE THREAD

**Issue by khoaakt** [cefsharp/CefSharp#1074]
In lastest source code, CefSharp get crashed when popup.
![untitled](https://cloud.githubusercontent.com/assets/6000592/8101374/c044fd70-1040-11e5-992b-2e8792b30460.png)

**Comment by amaitland** [comment]
Use one of the branches instead, the next release will be using https://github.com/cefsharp/CefSharp/tree/cefsharp/41

`master` has had a large number of changes merged in over the last `24hrs` and is not ready for general use.
