### ISSUE TITLE
Proper Way to Initialize multiple instances of CefSharp

### ISSUE THREAD

**Issue by bjwallwin** [cefsharp/CefSharp#1076]
Currently using CefSharp 39.0.2.

My situation is I have a user control that uses CefSharp, each user control needs to initialize a new instance of CefSharp not share a single instance.  So in my controls constructor I setup and call a new Cef.Initialize(cefsettings, shutdown=true, performDCheck=true), then eventually do a new ChromiumWebBrowser().

The problem I am running into is that upon creating my second user control instance the call to Cef.Initialize() fails and my second control instance stops working.  

I recall this pattern worked previously, I think in 37.0.1, its been awhile since I tested this scenario.  I am wondering if there were changes in CefSharp that would have altered this behavior?  or if I am wrong that it worked, in which case "what would be the proper way in initializing separate independent instances of CefSharp?"

**Comment by amaitland** [comment]
> The problem I am running into is that upon creating my second user control instance the call to Cef.Initialize() fails and my second control instance stops working.

You can only initialize `CEF` once, per application. Nothing has changed in regards to this. It's just how `CEF` functions.

What settings are you trying to customise between the different instances?

**Comment by bjwallwin** [comment]
@amaitland each user control is "technically" a separate application.  If I drop two user controls onto a container I have two separate applications.  My thought was that I "should" be able to initialize cef per user control?

One of the things we are doing is automating the testing of the user control and the Selenium tool we are using allows to hook into the remote debugging port to automate the testing of the browser.  The issue is that if I have multiple user controls I need Selenium to be able to connect to each control which implies that I need to set the remote debugging port in cef to the port generated by Selenium.

**Comment by jornh** [comment]
No the architecture of CEF3 and thus CefSharp (which is merely a .NET binding on top of it) is different: https://bitbucket.org/chromiumembedded/cef/wiki/Architecture#markdown-header-process-considerations. There is a **one** common `Browser` process which then spawn a `Renderer` process for each "window" or "tab". (You can see them in your Windows Task Manager)

You now mention Selenium automation. I haven't really dabbled in Selenium in a Chromium let alone CEF context , so you have to do some research to verify this. If https://code.google.com/p/selenium/wiki/JsonWireProtocol is still the right spec for the protocol then the table of contents suggest you wouldn't connect to different ports for each renderer but that you connect once and then can navigate `session`s which have `windows`. Is that what you are looking for?

**Comment by bjwallwin** [comment]
So @jornh just to restate so I understand what you are saying, it's Monday and all my brain isn't firing on all cylinders yet.  "So even though each of my user controls are separate processes (i.e. each instance fires a separate control constructor and in every way are separate and unique, they will all share the same browser process and thus the same cef settings). they will share one common browser process?", can I then assume this means "that no matter how many applications use Cef (CefSharp), the first application that initializes cef will dictate the settings for every application thereafter?

Just trying to get my head around this, thanks.

**Comment by jornh** [comment]
Yep it *is* Monday ... so you're excused :smile: ... now I'm beginning to doubt that I grasp what you said in the first place

> @amaitland each user control is "technically" a separate application. If I drop two user controls onto a container I have two separate applications.

Could you explain these expressions a bit further: *user control is "technically" a separate application* and *container*? 

> "So even though each of my user controls are separate processes (i.e. each instance fires a separate control constructor and in every way are separate and unique, they will all share the same browser process and thus the same cef settings). they will share one common browser process?" can I then assume this means "that no matter how many applications use Cef (CefSharp), the first application that initializes cef will dictate the settings for every application thereafter?

Nope - shouldn't be a problem (afaik) if  they e.g. are installed in different disk locations so that they in no way step on each others toes OR you make 100% sure now and in the future as CEF's implementation might change they are all configured so they don't step on each other toes with e.g. cache file areas, log files etc.. So the 2nd option is not exactly middle of the road.

**Comment by amaitland** [comment]
> My situation is I have a user control that uses CefSharp, each user control needs to initialize a new instance of CefSharp not share a single instance. So in my controls constructor I setup and call a new Cef.Initialize(cefsettings, shutdown=true, performDCheck=true), then eventually do a new ChromiumWebBrowser().

Sounds like an over simplification of what your actually doing.

Anyways, there are some inherent `CEF` limitations in place. Read https://code.google.com/p/chromiumembedded/issues/detail?id=421 for background.

**Comment by bjwallwin** [comment]
Closing issue, now that I understand CEF and its behavior a bit more, I need to work within the constraints.  Closing issue.

**Comment by amaitland** [comment]
Updating link to `bitbucket` website (one day in the not too distant future `google code` will be no more).

https://bitbucket.org/chromiumembedded/cef/issues/421
