### ISSUE TITLE
Select playback device or access live streaming audio

### ISSUE THREAD

**Issue by awaitforitb** [cefsharp/CefSharp#1078]
We are developing an application which is supposed to download audio of multiple live streams parallel on the same machine. To do this we have created multiple virtual audio playback devices using virtual audio cable. Is there a way we can assign an audio playback device at runtime or some other way to tap into the live audio stream, Applications like VLC and Windows Media player do allow to select the playback device in settings. 

Any suggestions are welcome. Thanks.

**Comment by avspeed** [comment]
you ask your question on stackoverflow .. not here
