### ISSUE TITLE
Adobe Flash Player is disabled in chromium browser in Windows .

### ISSUE THREAD

**Issue by dineshbabu65** [cefsharp/CefSharp#1081]
I'm not able to play any videos from chromium browser in windows 7 and windows 8.
It is saying flash player is disabled in my machine, but i have adobe flash player installed .
When I play same video in fire fox or in internet explorer , it is working fine. 
I don't know how to enable it.

I'm using 
cef sharp version of 3.2171.1979,
Chromium version of 39.0.2171.95,
Flash version of 17.0.0.169

Please help me to resolve this.

**Comment by jornh** [comment]
For a plugin related issue it's a good idea to start by looking upstream in the CEF forum. Also see https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef in particular it mentions you can see if the plugin is picked up in both CEF and CefSharp by going to chrome://version/ 

Finally note plugin support is currently in a state of flux right now with Chromium/Chrome deprecating the NPAPI

**Comment by amaitland** [comment]
> cef sharp version of 3.2171.1979,

Are you using a `-pre` release version of `CefSharp`? Latest official release is `39.0.2`.
(Strictly speaking the version number you've quoted is a `CEF` version number, one for which there was never an official release of `CefSharp`).

Are you using `x86` or `x64`? `WinForms`, `WPF`, `OffScreen`?

Your post is a little lacking in detail, maybe reading over the `Contributing.md` guide will give you some ideas
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue

> When I play same video in fire fox or in internet explorer

What about using `Chrome`? Much closer comparisom.

Also check in the `debug.log` file (should be in your `bin` directory).

> in particular it mentions you can see if the plugin is picked up in both CEF and CefSharp by going to chrome://version/

If you run `custom://cefsharp/plugins` in either `CefSharp.Wpf.Example` or `CefSharp.WinForms.Example`, does it list `Shockwave Flash`?

> Flash version of 17.0.0.169

If possible I'd suggest updating to a newer version. You need to install the `NPAPI` version. There isn't a version of `CefSharp` that supports `PPAPI` yet.

**Comment by amaitland** [comment]
Anything further on this?

**Comment by JSturn** [comment]
I just had the same problem and I am almost sure I know what first persons issues was.

If you install chromium directly from a snapshot, while having never installed chrome before, you may not have the correct version of flash installed. Should note, even when you go to the adobe web site to get flash, it will not install the correct version. To check if you have the right version, go to control panel, then click on "flash player (32- bit)", then click the Updates tab at the top, and it should show that you have the "PPAPI Plug - In Version:" installed. If it says not installed, you can download that version from this web page, http://labs.adobe.com/downloads/flashplayer.html .

**Comment by amaitland** [comment]
> "PPAPI Plug - In Version:" installed. 

`PPAPI` = `Pepper Flash` which currently isn't supported by version `39` or `41`. May actually have to wait until vesion `45` to support `Pepper Flash`. The relevant `upstream` issue is https://bitbucket.org/chromiumembedded/cef/issue/1586/add-pepper-flash-plugin-support

> If it says not installed, you can download that version from this web page, http://labs.adobe.com/downloads/flashplayer.html .

Not sure I'd recommend installing a beta version of `Flash` for production use.

**Comment by amaitland** [comment]
This question was asked on `ceforum` (@dineshbabu65 it would have been ideal if you posted a link and followed up on this issue)

http://magpcss.org/ceforum/viewtopic.php?f=6&t=13106&p=26358

Basically `Chromium` has changed to block `NPAPI` by default see https://chromium.googlesource.com/chromium/src/+/0539f2f5214fc17fdd5d1964be0ceedf98fdb9ce
I haven't tracked which branch this change first appeared in, I suspect the `2357` (`43`) is the first, though some reports on `ceforum` suggest it effects the `2272` branch.
