### ISSUE TITLE
A procedure imported by 'CefSharp.Core.dll' could not be loaded.

### ISSUE THREAD

**Issue by ismailkocacan** [cefsharp/CefSharp#1082]
1- I have installed that release https://www.nuget.org/packages/CefSharp.WinForms/39.0.1
2- I was compile net 4.0 project for x86 and x64 cpu.
3- I also have installed VC++ 2012 Update 4
4- When I run project on XP machine then getting that error "A procedure imported by 'CefSharp.Core.dll' could not be loaded."

How can I solve ?
Thanks

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#9-windows-xp2003-support

**Comment by ismailkocacan** [comment]
Thanks for reply
