### ISSUE TITLE
CefSharp - .NET 2.0 - legacy support?

### ISSUE THREAD

**Issue by code0tt** [cefsharp/CefSharp#1085]
hi CefSharp, is there a version for .net 2.0, and could build with vs2008?

**Comment by jornh** [comment]
Nothing that is maintained any more so you are on your own https://github.com/cefsharp/CefSharp/tree/CefSharp1#binary-release - it's based on the old CEF1 architecture so on the CefSharp1 branch and stopped around Chromium 25. 

A bit of build-from-source info also on the https://github.com/cefsharp/CefSharp/wiki/Building-CefSharp page.

**Comment by code0tt** [comment]
THANKS jornh, it's GREAT!
But binary files is 32-bits based, I think.
When I reference those files to my 64-bits app, program will crashed. So, should I download  https://github.com/cefsharp/CefSharp/wiki/Building-CefSharp and build my owns?

**Comment by amaitland** [comment]
There is no `64bit` version that supports `.Net 2.0`, only a `32bit` version.
