### ISSUE TITLE
Proxy reconfiguration problem

### ISSUE THREAD

**Issue by wplong11** [cefsharp/CefSharp#1089]
I want to reconfigure proxy. But CEF doesn't support re-initialization. Roughly, I found i can use ProxyHandler Pattern for this problem in the Google search. But CefSharp also dosen't support ProxyHandler.

Is there any solution for reconfiguration proxy?

**Comment by amaitland** [comment]
> Is there any solution for reconfiguration proxy?

We're very much limited by `CEF` here as `CefSharp` is just a basic wrapper.

**Comment by amaitland** [comment]
The open upstream issue https://bitbucket.org/chromiumembedded/cef/issue/1058/cef3-allow-reconfiguration-of-proxy

**Comment by amaitland** [comment]
New `upstream` issue has been opened to represent this problem.

https://bitbucket.org/chromiumembedded/cef/issues/1709/allow-configuration-of-preferences-during

**Comment by amaitland** [comment]
Duplicate of #1308
