### ISSUE TITLE
How to load html string with local external reference style sheets & JS?

### ISSUE THREAD

**Issue by bharatdwarkani** [cefsharp/CefSharp#1090]
I am loading a string of html data using LoadHtml. Html string data contains link to external JS / CSS . I have tried implementing ISchemeHandler but it will trigger only when address is given. In my case there is no html file since I am loading html string stored in Database. How to support this scenario in Cefsharp WPF?

EG: This will be in string format not stored local .html file but it contains reference to some local files (scripts/shCore.js)

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Hello SyntaxHighlighter</title>
	<script type="text/javascript" src="scripts/shCore.js"></script>
	<script type="text/javascript" src="scripts/shBrushJScript.js"></script>
	<link type="text/css" rel="stylesheet" href="styles/shCoreDefault.css"/>
	<script type="text/javascript">SyntaxHighlighter.all();</script>
</head>

<body style="background: white; font-family: Helvetica">

<h1>Hello SyntaxHighlighter</h1>
<pre class="brush: js;">
function helloSyntaxHighlighter()
{
	return "hi!";
}
</pre>

</html>


```

WPF

```
webBrowser.LoadHtml(HtmlString, "http://example/");

```

**Comment by amaitland** [comment]
For reading items from the database a scheme handler is your best bet as you can process the requests in an async fashion.

The `CefSharp.Wpf.Example` project loads resources that are embedded in the project. There's no reason you can't source them from anywhere you so choose.

https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.Example/CefSharpSchemeHandler.cs#L20
https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.Example/CefSharpSchemeHandler.cs#L46

If you open `custom://cefsharp/home` in the `CefSharp.Wpf.Example` project you'll get a working example. (`master` is unstable at the moment, so use either the `39` or `41` branches).

**Comment by lamerbug** [comment]
Okay, but what if string of html data is unknown in advance? So we cannot hardcode anything?

**Comment by amaitland** [comment]
> Okay, but what if string of html data is unknown in advance?

You return true to handle the request, spawn off a `Task` to do the processing, and then execute the callback when the content is available.

The example uses embedded resources, you can just as easily use a file on the file system or read from a database. You can even make web requests yourself if you should choose to.

**Comment by amaitland** [comment]
Find a workable solution?

**Comment by bharatdwarkani** [comment]
I tried it. It was not triggering when Html sting was used. In sample Html was loaded from Html file. To work around it I have used hosted html page external url reference in html string.

**Comment by amaitland** [comment]
Without a sample it's hard to say. It should work without a problem, you should be able to load any resource as you choose.
