### ISSUE TITLE
How to dispose whilst browser is loading

### ISSUE THREAD

**Issue by ajdyer** [cefsharp/CefSharp#1091]
I'm using CefSharp.WinForms in an Application in order to display HTML dynamically. As part of our UI tests, browsers may be created and disposed of in quick succession. However, if the browser's parent control tries to dispose when the browser is still loading, I get an unhandled CommunicationException in System.Threading.Tasks.dll.

Background:
v41.0.0pre01 (also get the same behavior with v37.0.0)
x86
WinForms
Windows 7

I've tried to reproduce this in the example project by adding this event handler to the BrowserTabUserControl:

		void browser_IsLoadingChanged(object sender, IsLoadingChangedEventArgs e)
		{
			if (e.IsLoading)
				this.Invoke(new Action(() => this.Dispose()));
		}

When running this, I get an access violation when the control attempts to dispose:

The program '[11048] CefSharp.WinForms.Example.vshost.exe: Managed (v4.0.30319)' has exited with code -1073741819 (0xc0000005) 'Access violation'.

How should I dispose of the browser and its parent control if the browser is loading?

Thanks,
Andrew

**Comment by jankurianski** [comment]
I think your aim should be to work around this, because trying the fix the underlying cause may be a big job (for example, the `CommunicationException` sounds like a crash in `WCF`, and the solution to this would be to replace the use of `WCF` with CEF's `IPC` mechanism).

So why not avoid disposing the browser until it is in a good state?

**Comment by ajdyer** [comment]
The best work-around seems to be to do something along the lines of:

    browser.Parent.Controls.Remove(browser);

before disposing of the browser's parent control. Then the browser can be disposed when it's no longer loading.

The Access violation seems quite severe though...

**Comment by amaitland** [comment]
Do you use `Javascript Binding` or `EvaluateScriptAsync`? A change was recently merged into `master` that allows you to disable `WCF`. Consequently both those features will be disabled.

You could pretty easily backport this into the `41` branch if required.

**Comment by ajdyer** [comment]
Sadly I'm quite heavily reliant on EvaluateScriptAsync for getting information about the DOM back from javascript. Is there another way I could do this?

**Comment by rassilon** [comment]
I think the work around you describe above is the best long term way to go about handling this scenario for a Winforms application. Even once we are able to discontinue using WCF for JavaScript bindings, I would not be surprised if CEF itself becomes unhappy about trying to tear things down while the initial browser state is still being created/loading.

Bill

**Comment by ajdyer** [comment]
So will there be an alternative way of calling JavaScript functions from .NET post-v41?

**Comment by amaitland** [comment]
#1095 was merged recently, it uses the native `IPC` mechanism to communicate. Still a while before `master` is production ready though.

**Comment by ajdyer** [comment]
Awesome, thanks :)
