### ISSUE TITLE
Is the version of Chromium in CefSharp affected by this privacy warning?

### ISSUE THREAD

**Issue by roschler** [cefsharp/CefSharp#1092]
Looks like Google's been doing some things with the microphone that are making some people unhappy.  According to the article, it affects the Chromium toolkit too.  Is CefSharp affected by this?:

http://www.msn.com/en-us/news/technology/google-eavesdropping-tool-installed-on-computers-without-permission/ar-AAc1CpO?pfr=1

Need to know for my users since one of my favorite apps uses CefSharp.  Thanks.

**Comment by amaitland** [comment]
From the brief read I had the article is lacking in specifics, no mention of which versions are affected.

Might be worth asking on http://magpcss.org/ceforum/ someone there might know.

**Comment by roschler** [comment]
Hello Alex,

Another update.  It looks like they are not auto-enabling that "feature" anymore in Chromium 45 builds:

http://arstechnica.com/security/2015/06/not-ok-google-chromium-voice-extension-pulled-after-spying-concerns/

What Chromium version is embedded in CefSharp and is replacing the relevant DLLs from a new build easy to do (and how so)?  I'm assuming the Chromium DLLs are in the CefSharp file set.  Apologies in advance if not.

-- roschler

**Comment by amaitland** [comment]
The latest official release is `41`.

> is replacing the relevant DLLs from a new build easy to do (and how so)?

`CefSharp` is compiled against a specific version of `CEF`. There are quite a few steps involved in upgrading. The first one is detailed at https://github.com/cefsharp/cef-binary/wiki With a bit of searching you can find the rest, it's a fairly common question people ask. `CEF` has not yet officially released a `45` build. From a stability point of view you'd likely be advised to wait a few months as the current official build of `Chrome` is only `43`

**Comment by roschler** [comment]
Thanks.  I'll go to the Chromium forum you linked me and ask them if Chromium 41 has the HotWords problem we're discussing.

**Comment by amaitland** [comment]
http://www.technipages.com/enable-or-disable-google-voice-hotword-search-in-google-chrome

> The feature runs as a plug-in, and is listed in the Chrome Task Manager as “Google Voice Hotword Search” and does utilize some system resources to constantly listen for the hotword

There's some indication that it runs as a plugin. `Cef` doesn't support the `Chrome Plugin API`, so if that's the case it's likely not an issue. Likely need to do more research to confirm.

**Comment by roschler** [comment]
Thanks for that update.  Here's a link to the post I just added to the Chromium forum, asking if Chromium 41 is affected:

http://magpcss.org/ceforum/viewtopic.php?f=6&t=13131

**Comment by amaitland** [comment]
Just as an interesting note, if you open `chrome://voicesearch/` in `Chrome` it provides some basic information.

**Comment by amaitland** [comment]
> CEF does not support Chromium extensions so you're safe.

Official response is in. Pretty much as expected. So no need to worry.

**Comment by roschler** [comment]
Thanks Alex.  Closing issue.
