### ISSUE TITLE
EvaluateScriptAsync result in System.NullReferenceException

### ISSUE THREAD

**Issue by gicque** [cefsharp/CefSharp#1093]
I used the cefsharp.OffScreen.Example project and added in line 
var res = await browser.EvaluateScriptAsync("1 + 1");

https://gist.github.com/gicque/f506cbaf6cc62a0bdc7c

the execution of the project resulted in an  system.nullreferenceexception in handlereturnmessage

![cefsharp-error](https://cloud.githubusercontent.com/assets/297225/8338094/102435a4-1aaf-11e5-912c-5a5ce858f24b.png)

i tested in win32 and x64

**Comment by amaitland** [comment]
What branch are you using?

**Comment by gicque** [comment]
I tried with **CefSharp.WinForms 41.0.0** and **CefSharp.WinForms 41.0.0-pre01** (installed through nugget) with the same result.
I am on windows 7 x64.

**Comment by amaitland** [comment]
What did the stack-trace say?

When I run your `gist` against the latest `master` (which is in somewhat a state of flux, so it's quite possibly a little unstable) I get the following value for `res.Message`

> Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src assets-cdn.github.com collector-cdn.github.com".

So everything is working as expected. I modified your `gist` slightly so the javascript will eval https://gist.github.com/amaitland/3fbcc2b8a0316efabba6

**Comment by gicque** [comment]
I just downloaded the master branch and tried your example; i got the same exception, here is the stack trace

https://gist.github.com/gicque/46ed48740789cb7e3046

**Comment by amaitland** [comment]
When you step into the function with the debugger at what point does it fail? Stack trace isn't particularly helpful.

What other information can you provide? Can you try `39.0.2`? It's been out for quite some time, if you still get problems then it's likely something unusual with your setup.

**Comment by gicque** [comment]
i couldn't step into the function other then my code

i tried with 39.0.2 i have the same exception, so the problem must be from my environement ?

**Comment by amaitland** [comment]
> i tried with 39.0.2 i have the same exception, so the problem must be from my environement ?

I can't say that for sure. All I can say is that `39.0.2` is fairly widely used.

Do you have all the latest `.Net` updates installed? Latest `Visual Studio` service pack? What version of `Visual Studio` are you using?

**Comment by gicque** [comment]
I have **visual studio ultimate 2013** with **update 4** and **.NET 4.5.1**

**Comment by jamespearce2006** [comment]
I wonder whether this is to do with the user's locale and the parsing of commas vs periods. (I notice the screenshots show VS running in French). I see that the stack trace occurs during deserialization. 
For example, double.Parse("1.0") fails under a French or German locale, as it expects "1,0".

We've run into similar issues with our commercial product which ran fine in our test environment, but failed at a customer site. This turned out to be the parsing of some Xaml containing a Thickness value. The value "1,1,1,1" failed to parse running in German - it expected "1.1.1.1".

@gicque is there any way you can try your code running in English locale?

James

**Comment by gicque** [comment]
I tried adding 

Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");
Thread.CurrentThread.CurrentUICulture = new CultureInfo("en-US");

to both threads with the same result

**Comment by jamespearce2006** [comment]
@gicque That may not be enough, since I'm guessing EvaluateScriptAsync uses its own thread (or a thread pool thread), which may be using the default culture.

Can you try using AppLocale, or temporarily switch your system locale, to run the entire app in en-US?

**Comment by gicque** [comment]
i changed the system locale with the same result

**Comment by jamespearce2006** [comment]
Oh well. Sorry to make you jump through hoops for nothing...

**Comment by gicque** [comment]
not at all @jamespearce2006 , your help is appreciated, thank you

**Comment by jamespearce2006** [comment]
Could this be it?

https://connect.microsoft.com/VisualStudio/feedback/details/1175993/nullreferenceexception-in-system-runtime-serialization-when-etw-enabled

**Comment by gicque** [comment]
ETW is disabled

**Comment by canton7** [comment]
Specifically, the setting that needs to be changed is the 'Format', in the 'Regional and Language Settings' area of the Windows Control Panel.

**Comment by gicque** [comment]
yes, i did that with the same result.

**Comment by amaitland** [comment]
`EvaluateScriptAsync` has been rewritten to use native `IPC`, so hopefully this is a non issue now.

(Some parts of `JSB` still use `WCF`)

Changes were merged into `master` a while ago.

**Comment by gicque** [comment]
Thanks @amaitland 
The project using **CefSharp-43.0.0-pre01** don't throw the error

**Comment by SethTurin** [comment]
Forgive me if this is a different issue, but I'm receiving the same error in the wpf example when on github.com. Here is a screencast demonstrating: http://screencast.com/t/EUpTGJF3PJPg

**Comment by amaitland** [comment]
> Forgive me if this is a different issue, but I'm receiving the same error in the wpf example when on github.com.

This particular error relates to the `WCF` channel that was previously used to `eval` javascript. The error your seeing is because `Github` is using `CSP` you cannot just randomly execute javascript on their site. See https://developer.chrome.com/extensions/contentSecurityPolicy for more details. So the error your seeing is expected and valid.

There is a known issue with `master` and it's currently `javascript binding implementation` See #1203 for more details

**Comment by SethTurin** [comment]
Thanks for the quick answer. I understand why this would be an issue for github. In particular, I'm using CefSharp to plug into my web automation software. Without javascript, my automation tools simply won't work on github. Is there any workaround that will let me run javascript despite the policy?

Please let me know if there is a better place to discuss this.

**Comment by amaitland** [comment]
> Is there any workaround that will let me run javascript despite the policy?

Nothing specific that I'm aware of in `CefSharp`. I can't say that I'm particular familiar with `CSP` though.

> Is there any workaround that will let me run javascript despite the policy?

`Stackoverflow` is probably the best place to ask/search.

**Comment by amaitland** [comment]
A quick search on `ceforum` and it looks like others have attempted something similar.

http://magpcss.org/ceforum/viewtopic.php?f=6&t=10334&p=19338&hilit=content+security+policy#p19338

**Comment by SethTurin** [comment]
Thanks again for your help on this. With a little more probing, I've noticed that things like ```alert("hello")``` work just fine on pages like github, and it's apparently only the bound objects that are failing. Do you think this might be resolved with #1203?

If not, I think my next step is to do as mentioned in your recent link and look into response header rewriting.

**Comment by amaitland** [comment]
> Do you think this might be resolved with #1203?

I get an error when trying to execute simple things like `1 + 1`;

In general you should be using the latest stable release aka `41.0.1` as it's `javascript binding` implementation is stable. This particular issue is a very rare case and I'd be surprised if it affected more than a handful of people.
