### ISSUE TITLE
Is it possible file upload with html input file via ChromiumWebBrowser as programmatically ?

### ISSUE THREAD

**Issue by ismailkocacan** [cefsharp/CefSharp#1096]
```
<!DOCTYPE html>
<html>
<body>
<form action="upload.php" method="post" enctype="multipart/form-data">
    Select image to upload:
    <input type="file" name="fileToUpload" id="fileToUpload">
    <input type="submit" value="Upload Image" name="submit">
</form>
</body>
</html>
```

Is it possible set upload file as programmatically with ChromiumWebBrowser ?

thanks for your help

**Comment by amaitland** [comment]
`IDialogHandler.OnFileDialog` maybe?

**Comment by ismailkocacan** [comment]
thanks for reply

**Comment by daphonk** [comment]
Hi ismailkocacan

did you get this working ?

**Comment by leog** [comment]
@ismailkocacan could you share what you did please, I have the same question.

**Comment by mitchcapper** [comment]
@leog I can't speak to if he got it working however you could use javascript to likely trigger a click on the submit button and then if you have told the browser to use your own IDalogHandler that has a OnFileDialog  that just returns the local file path for the file you want to upload.  The other option would be to hand generate the post data and load that in, but it would be far more complicated.

**Comment by leog** [comment]
@mitchcapper thank you very much for the quick reply! so, if I manage to handle the file dialog myself I could control what it does? I have the file path already, I just need to let the web app know about it to start an upload for it and do stuff to then return a JSON when the process finishes.

**Comment by ranieresantos** [comment]
Hello! I can use IDialogHandler, I would like to know how to trigger input type = "file" through javascript ??

**Comment by amaitland** [comment]
You cannot directly open a file dialog due to security restrictions see https://blog.mariusschulz.com/2016/05/31/programmatically-opening-a-file-dialog-with-javascript

You can probably set focus to the button then send an enter key 

See https://github.com/cefsharp/CefSharp/issues/2143 for some examples of sending keys
