### ISSUE TITLE
IWebBrowser Load/LoadHtml url formatting issue

### ISSUE THREAD

**Issue by lamerbug** [cefsharp/CefSharp#1106]
I was checking out latest builds and ran into issue with url formatting when using Load/LoadHtml methods. I've implemented custom resource handler just like in void RegisterTestResources(IWebBrowser browser)
and noticed that "http://test/resource/load" example url works fine, but when I change it to "http://test" it doesn't load later, because when Load fires url turns into "http://test/" with additional slash at the end, and looks like it makes sense. This happens only with short URLs:
http://test becomes http://test/ when loading
http://te.st/test becomes http://te.st/test/
http://test/test/okay works ok.
and because of that LoadHtml doesn't work for short urls too. 
The same story happens when loading regular web urls.

not sure if I'm able to fix it now (just started to learn changes in latest cefsharp since v37) so decided to let u know...

**Comment by amaitland** [comment]
I think the class your looking for is `DefaultResourceHandlerFactory`. It just uses a basic dictionary (needs to be changed to a `ConcurrentDictionary` at some point). Will likely need to use `Uri.TryCreate` to turn the `string url` into a proper `Uri` including the trailing slash on the `hostname`

https://github.com/cefsharp/CefSharp/blob/master/CefSharp/DefaultResourceHandlerFactory.cs#L38

**Comment by lamerbug** [comment]
Yeah, since incoming IRequest (at GetResourceHandler) already contains canonical URL, we just turn string into canonical URL when registering it. Works well so far... 
```C#
public virtual bool RegisterHandler(string url, IResourceHandler handler)
        {
            try
            {
                Uri uri;
                if (Uri.TryCreate(url, UriKind.Absolute, out uri))
                {
                    Handlers.TryAdd(uri.ToString(), handler);
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch
            {
                return false;
            }
        }
```
(I decided to return bool to be sure if it registered or not, just in case of bad string)

**Comment by amaitland** [comment]
You can scrap the `try...catch` block and should probably return `Handlers.TryAdd`. Also the `else` block is redundant since returning in the `if` block.

**Comment by lamerbug** [comment]
Sure, I just had some other code in that blocks for testing purposes,

**Comment by amaitland** [comment]
Feel free to submit a `PR` against `master` if you'd like to see this changed :+1:

**Comment by lamerbug** [comment]
Not sure if I did a PR correctly, be careful )

**Comment by amaitland** [comment]
Few comments inline, basics look solid, thanks :+1:

**Comment by amaitland** [comment]
Changed merged into `master`
