### ISSUE TITLE
WinForms browser hanging on return from C# code

### ISSUE THREAD

**Issue by TCSolutions** [cefsharp/CefSharp#1108]
I have a main window which contains an instance of a ChromiumWebBrowser. Upon click of a button, it calls a void() on an object from RegisterJSObject, which then creates a new window.

This new window contains another ChromiumWebBrowser instance. Now, if I close this new window without interacting with the web browser, when it returns back to the Javascript code in the main window, it hangs.

I have tried disposing the ChromiumWebBrowser object in the second window before the form gets disposed, however that makes it hang 100% of the time.

The Javascript code is very minimal. It just calls this void and that is the end of it.

It is also worth noting that when I manually dispose the object, no exceptions are created. However, when I let the GC take care of it, it produces the following first chance:

```
A first chance exception of type 'System.IO.PipeException' occurred in System.ServiceModel.dll
A first chance exception of type 'System.ServiceModel.CommunicationException' occurred in System.ServiceModel.dll
A first chance exception of type 'System.ServiceModel.CommunicationException' occurred in System.ServiceModel.dll
A first chance exception of type 'System.ServiceModel.CommunicationException' occurred in System.ServiceModel.dll
A first chance exception of type 'System.IO.PipeException' occurred in System.ServiceModel.dll
A first chance exception of type 'System.ServiceModel.CommunicationException' occurred in System.ServiceModel.Internals.dll
A first chance exception of type 'System.ServiceModel.CommunicationException' occurred in System.ServiceModel.dll
A first chance exception of type 'System.ServiceModel.CommunicationException' occurred in System.ServiceModel.Internals.dll
A first chance exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll
A first chance exception of type 'System.ServiceModel.CommunicationException' occurred in mscorlib.dll
```

**Comment by amaitland** [comment]
Version? Can you provide a `Gist` or fork https://github.com/cefsharp/CefSharp.MinimalExample to demo your problem?

**Comment by jankurianski** [comment]
@TCSolutions Please fill in all of the details in this issue template:

https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue

From my perspective, I can't even tell whether you are using WinForms or WPF and this makes it difficult for me to help you.

**Comment by jankurianski** [comment]
Oh, I just noticed you have WinForms in your title, but it would be good to get all of the issue template questions answered in one comment in Github - makes it easier for all of us to help you.

**Comment by amaitland** [comment]
> Quick edit: the Javascript code is very minimal. It just calls this void and that is the end of it.

Better to post follow up comments rather than edit as `github` doesn't provide notifications when you edit something. Also it's helpful to markup code/exception blocks see https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks

**Comment by TCSolutions** [comment]
Sorry, let me try to make it a bit clearer.

I am on Windows 8.1, using the latest Nuget build with .NET Framework 4.5 x86

I have created a gist to demonstrate the issue:

https://gist.github.com/TCSolutions/43d4f554d347bc100569

**Comment by jankurianski** [comment]
Just an initial hunch based on a quick read of the code...

`Application.Run(new Form2());`

You are starting a new Windows application message loop on a CEF callback thread, and when the form closes it is probably raising Application.Exit event.  Normally there is only one Windows message loop in a program, and if you have 2 you have to be very careful.

Considered starting the new form on your existing UI thread using BeginInvoke?

**Comment by TCSolutions** [comment]
That seems to resolve the issue. I will test this further and if I encounter anymore errors, I will get back to you.

Thanks everyone for your input, it's really appreciated. I'll be sure to follow that issue template next time I need to post one.

Cheers!

**Comment by amaitland** [comment]
> You are starting a new Windows application message loop on a CEF callback thread, and when the form closes it is probably raising Application.Exit event. Normally there is only one Windows message loop in a program, and if you have 2 you have to be very careful.

Not only that, `Application.Run` blocks which is far from ideal. For anything long running, it's better to use a callback into `javascript`. 

https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.Example/BoundObject.cs#L43

In general when interacting between `CefSharp` and `WinForms` `UI` (or `WPF` for that matter) it's best to check if `Invoke` is required. A simply extension method is usually the way to go.

https://github.com/cefsharp/CefSharp.MinimalExample/blob/master/CefSharp.MinimalExample.WinForms/Controls/ControlExtensions.cs#L19

**Comment by TCSolutions** [comment]
Thanks for the advice, I am actually looking for the second window to block, but I can accomplish that with ShowDialog().

I will fiddle around with using the callbacks as well.

**Comment by amaitland** [comment]
> Thanks for the advice, I am actually looking for the second window to block, but I can accomplish that with ShowDialog().

`ShowDialog` is fine if you use `BeginInvoke`. If you block the thread `JSB` uses too long the `render` process will likely terminate.
