### ISSUE TITLE
RenderProcess troubles

### ISSUE THREAD

**Issue by ray007** [cefsharp/CefSharp#1109]
I've had the problem of the render process crashing when handling big data for quite some time.
Catching the problem in `IRequestHandler.OnRenderProcessTerminated` and triggering a reload of the browser solved the problem most times.

After upgrading to CefSharp Version 41, there now sometimes is a new problem: after triggering a new load, everything seems to be fine on the surface (even looking good in developer tools), but the Browser control still shows the contents of before the reload - no changes to the DOM do anything.
Other than seeing the problem on my screen, there seems to be no new error triggered anywhere...

**Comment by ray007** [comment]
Update: the problem is easy to reproduce - just kill the `BrowserSubprocess` and try to load the browser control anew from `IRequestHandler.OnRenderProcessTerminated`.

**Comment by amaitland** [comment]
`WinForms` or `WPF`? ` `x86` or `x64`?

Does the problem only occur after running for a long time? e.g. If you load a simple page like `google.com` and immediately terminate the render process, will a redirect work?

**Comment by ray007** [comment]
It's `WPF` on `x86`.
And I always get the problem rather sooner by trying to load a big gzipped xml file with a XmlHttpRequest...
I'm trying to get the CefSharp checkout from V 41.0.0 to render something again so I can answer your last question - our application uses a constant url that's currently pointing at a html file in the local filesystem.

**Comment by ray007** [comment]
Haven't been able to reproduce the problem with `CefSharp.Wpf.Example` so far.
I've downgraded to V39.0.2 locally for now - will try to check up on this again as soon as I'm able to.

**Comment by amaitland** [comment]
Looks like a bug was introduced when fixing something else in the `2272` branch, appears to be fixed in `2357`
https://bitbucket.org/chromiumembedded/cef/issues/1161/resizing-window-shows-undesired-background#comment-18076872

**Comment by amaitland** [comment]
`master` has been updated with a newer version of `2357` that should resolve this issue. Reopen if the problem still persists.

**Comment by ray007** [comment]
I just tried with a new version and the problem persists.

**Comment by amaitland** [comment]
Probably best to post on `bitbucket` and say your still having problems. Nothing we can do on the `CefSharp` end.

**Comment by ray007** [comment]
I just testet with `cefclient.exe` from the `2357` branch and killing the renderprocess there doesn't exhibit the same problem.

How does one reopen an issue?

**Comment by amaitland** [comment]
Testing using the `WPF Example` from `master`, everything appears to be working correctly. 

I added a very basic demo see https://github.com/cefsharp/CefSharp/commit/48d364aed775dc938fec3165912b912b0ff289be

If I open the `WPF Example`, then it task manager terminate the `render process`, it loads the page as expected.

What additional information can you provide about your app?

**Comment by ray007** [comment]
It seems to load as expected. Try to resize the window, the content doesn't fit to the window anymore.
Surprisingly this issue seems to fix itself when I navigate to a new page.

**Comment by amaitland** [comment]
> Try to resize the window, the content doesn't fit to the window anymore.

The window resizes, scrollbars appear as expected. Not seeing anything out of the ordinary. I even changed it to load `http://github.com` and everything seems to work, I can resize, click links.

**Comment by ray007** [comment]
Hmm, strange, let me provide some more detail to find out why there's a difference.

I start the CefSharp.Wpf.Example, un-maximize it and load a different page.
This leads us to screenshot 1.
![before-render-kill](https://cloud.githubusercontent.com/assets/126712/9488907/6981396c-4bdd-11e5-90a6-5bbb084b99f7.png)

Then I kill the render-process and enlarge the window after a bit of waiting.
Leading to screenshot 2:
![after-render-kill](https://cloud.githubusercontent.com/assets/126712/9488929/906cbe98-4bdd-11e5-9c4e-94a8f3a92a00.png)

Only loading a new page makes things work again as expected...

Anything I'm doing wrong?

**Comment by amaitland** [comment]
> Only loading a new page makes things work again as expected...

It's my understanding that you need to load a url for `CEF` to spawn a new `render process`. A `Reload` may have worked in older versions, I don't believe that's the case now.

`cefclient` does the same thing https://bitbucket.org/chromiumembedded/cef/src/47e6d4bf84444eb6cb4d4509231a8c9ee878a584/tests/cefclient/browser/client_handler.cc?at=2357#client_handler.cc-582
(If you navigate to a different page, terminate the render process, it'll return you to `google.com`)

Never hurts to ask on `ceforum` for clarification though....

**Comment by amaitland** [comment]
So it does look like `Reload` is supposed to work.

http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=12312
https://code.google.com/p/chromiumembedded/issues/detail?id=1429
https://bitbucket.org/chromiumembedded/cef/issues/1429

Will likely need to test by modifying `cefclient` to call `Reload` instead of `LoadUrl`.

**Comment by amaitland** [comment]
`Reload` works in the `WinForms` example. I modified `cefclient` to call `browser-Reload()`, works fine when rendering normally, crashes with `--off-screen-rendering-enabled`.

Tested with `cef_binary_3.2357.1287.g861c26e_windows32`

So you'll likely need to follow up on `ceforum` if you need `Reload` fixed (though that will likely take weeks/months before it appears in `CefSharp`).

**Comment by ray007** [comment]
Yes, the url has to actually change for things to work. And a little timing problem somewhere...
For now the following solution seems to mostly work for me:
```
void IRequestHandler.OnRenderProcessTerminated(IWebBrowser browser, CefTerminationStatus status)
{
	view.LoadHtml(<error-html>, <some-url>);
	var t0 = new System.Timers.Timer(300);
	t0.Elapsed += (timerSender, timerEvent) =>
	{
		view.Load(<app-url>);
		t0.Stop();
		t0.Dispose();
	};
	t0.Start();
}
```
If I remove the `view.LoadHtml()`, the `view.Load()` call doesn't work as expected - see initial problem.
If I try the `view.Load(<app-url>)` directly after `view.LoadHtml()` or with less delay, it also doesn't work.
The `view.LoadHtml()` unfortunately only shows a solid black content area instead of my error message, not sure why that is.

Seems the offscreen renderer from cef isn't as stable as I'd like...

**Comment by amaitland** [comment]
> If I remove the view.LoadHtml(), the view.Load() call doesn't work as expected - see initial problem.
> The view.LoadHtml() unfortunately only shows a solid black content area instead of my error message, not sure why that is.

The code block you've provided doesn't reference the latest version. As stated above, you need the latest `2357` version which includes a fix for calling `Load`.

**Comment by ray007** [comment]
I did use yesterday's tip of the 2357 (2357.1291) branch.
How do you think my code block should look like?

**Comment by amaitland** [comment]
The code block you provided is missing the `IBrowser` param, so it looks like your using an older version.
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/RequestHandler.cs#L98

**Comment by ray007** [comment]
Thank you.
You just made me realize, I checked out a branch `cefsharp/43` a while ago, which doesn't exit in your repo anymore - hence no updates when pulled.
Updated to current `master`, fixed all errors visual studio complained about (which are a few more than in the docs), and I'm running again.

Found one problem/difference so far: The bound object on the `ChromiumWebBrowser` doesn't exist anymore after the new load.

**Comment by amaitland** [comment]
> Found one problem/difference so far: The bound object on the ChromiumWebBrowser doesn't exist anymore after the new load.

Probably #1203

**Comment by ray007** [comment]
Thanks, but while adding `settings.CefCommandLineArgs.Add("process-per-tab", "1");` brings back my bound object, it also brings back the display update problem that made me start this issue.

Still working to find a way to recover from that problem. Or maybe I should roll back to the CefSharp version I used this morning...

**Comment by ray007** [comment]
Back to where you once had the `cefsharp/43` branch, that one's working for me now.
Will revisit this topic once I've dealt with my other problems...

**Comment by ray007** [comment]
Update: I just tried this with current `cefsharp/45` branch and cef version `2454.1344` and the problem still persists.
Since the problem started somewhere along the `cefsharp/43` branch while using the exact same `libcef`, I don't understand how this can be an upstream problem.

The bound object now does exists still/again after the new load, but rendering still doesn't get updated.

Guess I'll have to try bisecting the `cefsharp/43` branch next week...

**Comment by ray007** [comment]
Hmm, bisecting this is harder than I thought it would be.
Killing the renderprocess with a process explorer doesn't trigger `IRequestHandler.OnRenderProcessTerminated`, and triggering the problem causing the crash many times seems to be quite hard with some versions...

**Comment by ray007** [comment]
Retrying to bisect, the fact that most versions I'm trying show 2 build errors in visual studio doesn't make things easier:
```
Error	682	'CefSharp.Internals.IntPtrExtensions.CastToInt32(System.IntPtr)' is inaccessible due to its protection level	C:\data\devel\cef\CefSharp\CefSharp.Wpf\ChromiumWebBrowser.cs	970	85	CefSharp.Wpf
Error	683	'CefSharp.Internals.IntPtrExtensions.CastToInt32(System.IntPtr)' is inaccessible due to its protection level	C:\data\devel\cef\CefSharp\CefSharp.Wpf\ChromiumWebBrowser.cs	970	107	CefSharp.Wpf
```
And visual studio still declares the build as successful...

**Comment by ray007** [comment]
Another round of bisect, and I got a result:
```
...\CefSharp>git bisect good
56766723785dc82c6c7b539f90c553e8faf0eb95 is the first bad commit
commit 56766723785dc82c6c7b539f90c553e8faf0eb95
Author: amaitland <alex@maitlandcomputing.com.au>
Date:   Tue Sep 8 16:29:25 2015 +1000

    Implement temp workaround for #1203 - enable process-per-tab by default

:040000 040000 dacea42f769b9b6e61f362c37cb638998335ecca 637b1d481189f49c71c11438532d92ff785ce9d6 M      CefSharp.Core
```
Which introduces just a small change in `CefSharp.Core/CefSettings.h`:
```
@@ -35,6 +35,9 @@
 
             //Automatically discovered and load a system-wide installation of Pepper Flash.
             _cefCommandLineArgs->Add("enable-system-flash", "1");
+
+            //Temp workaround for https://github.com/cefsharp/CefSharp/issues/1203
+            _cefCommandLineArgs->Add("process-per-tab", "1");
         }
 
         !CefSettings()
```

**Comment by ray007** [comment]
Update: unsurprinsingly this leaves me with the problem from issue #1203 - so no real solution yet.

**Comment by ray007** [comment]
Still not sure why `IRequestHandler.OnRenderProcessTerminated` is not triggered anymore when killing the `BrowserSubprocess`, but I got a workaround for when it does get triggered:
remove current browser control and add a new one instead of trying to reload the existing one.

**Comment by ray007** [comment]
Update: tried with CefSharp 45, but the problem's still here.

**Comment by amaitland** [comment]
https://bitbucket.org/chromiumembedded/cef/issues/1779/osr-stop-rendering-when-render-process-is maybe of interest to this issue

**Comment by ray007** [comment]
Thanks, I'll try that with CefSharp master once I get my pending Release done here...

**Comment by amaitland** [comment]
> I'll try that with CefSharp master

Changes won't appear in `master` for a few months I'd imagine.

**Comment by amaitland** [comment]
Calling `Reload(true)` in `OnRenderProcessTerminated` restarts the render process as expected now. Tested using `3.2704.1418`.

```c#
void IRequestHandler.OnRenderProcessTerminated(IWebBrowser browserControl, IBrowser browser, CefTerminationStatus status)
{
	browser.Reload(true);
}
```

Marking this as `51.0.0` milestone as that's what I've tested, it should work with `47.0.4` and upwards.
