### ISSUE TITLE
v41: NullReferenceException at startup in WPF ChromiumWebBrowser

### ISSUE THREAD

**Issue by jamespearce2006** [cefsharp/CefSharp#1110]
I've just switched my app from v39 to v41, but ChromiumWebBrowser always seems to throw a NullReferenceException at startup.

In OnApplyTemplate hasn't been called yet because the browser hasn't yet been added to the Visual Tree, any attempt to set the Address (manually, or via binding) will fail.

The NullReferenceException is thrown in Load() - the call to GetMainFrame() returns null.

Since it's relatively likely that an address will be set before the control appears (particularly if the MVVM  pattern is being used), this seems like a problem...

**Comment by amaitland** [comment]
> I've just switched my app from v39 to v41, but ChromiumWebBrowser always seems to throw a NullReferenceException at startup.

Your saying this worked in `39`?

Your welcome to submit a `PR` against `41`, I'm reluctant to spend too much time on that branch as `master` is a huge rewrite still requiring a lot more effort and refinement before it's released.

**Comment by jamespearce2006** [comment]
OK - I think it's a relatively easy change.
Note - I'm looking at master... I'm confused by your comment about the 41 branch.

**Comment by amaitland** [comment]
`master` is very much a work in progress and not ready for prime time yet. So best to base your `PR` on https://github.com/cefsharp/CefSharp/tree/cefsharp/41

It's unlikely that `41` will see many more commits as it was simply intended to upgrade the `CEF` version with a couple of small `API` fixes along the way.

**Comment by jamespearce2006** [comment]
@amaitland I based on master before I saw your comment...
Still, it's a simple change.

**Comment by amaitland** [comment]
> Still, it's a simple change.

That's fine.
