### ISSUE TITLE
Navigating to URL with self-signed certificate shows empty screen

### ISSUE THREAD

**Issue by udo75** [cefsharp/CefSharp#1118]
Hi Guys,

I have an issue where I need your support.

The customer where we are running Cef framework ask what happens when the user navigates to a URL which has a self-signed certificate.
So I made a test with a test URL I found in the web.

My test setup is a WPF application with CEF 39.0.0-pre03.
The result was confusing. When I navigate to the test URL https://www.pcwebshop.co.uk/ I see only an emtpy screen.
Navigating to http://www.google.de shows the Google web page correctly.

Following the code, any idea why I see a blank screen?
Navigating https://www.pcwebshop.co.uk/ to in the web browser IE or Chrome shows up that the site has a self-signed certificate

```csharp
		public MainWindow()
        {
            InitializeComponent();
            Cef.Initialize(new CefSettings());
            
            //this handler will be assigned to get the callback called OnBeforeClose and OnBeforePopup
            //the interdace ILifeSpanHandler is implemented in this case directly by the MainWindow
            //therefore assinged this to browser.LifeSpanHandler
            browser.LifeSpanHandler = this;

            browser.Address = "https://www.pcwebshop.co.uk/";
            //browser.Address = "http://www.google.de";
        }
```

Thank you!

**Comment by ray007** [comment]
Try with `new CefSettings { IgnoreCertificateErrors = true }`

**Comment by udo75** [comment]
Sorry that did not help... I still see the empty screen

**Comment by amaitland** [comment]
Does the problem reproduce using the latest version? (`41.0.0`)

Try implementing `IRequestHandler.OnCertificateError`

https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp/IRequestHandler.cs#L29

**Comment by udo75** [comment]
Hi Alex,

I'll give a try with version 41, currently we deployed version 39 on the customer side.

About the RequestHandler I'll check but one question back. Does it mean that I need to define what to display to the user in this case? I was expecting that this is a general "issue" to show "general" message in this case as done in the browsers.

Thanks for the hint so far.

**Comment by amaitland** [comment]
> I was expecting that this is a general "issue" to show "general" message in this case as done in the browsers.

`CefSharp` is based on `CEF` which is basically a no frills browser framework, you have to implement things like that yourself.

Also there is  #1009 which is outstanding, so there isn't currently a way to get detailed info on the `certificate`.



> I'll give a try with version 41, currently we deployed version 39 on the customer side.

You say your using a `-pre` release, I'd suggest at least you upgrade to the production release of that version.

**Comment by udo75** [comment]
Hi Alex,

thanks for the update. Some comments from me:

1. I just tested with pre-Release. In production environment we have stable 39.0.0 running
2. I just made a small test with implementing IRequestHandler and see that the code is hit in the debugger. My question is now: If I built a new RequestHandler and assign it to browser.RequestHandler I lose the "default" behavior of the "Default" RequestHandler. I there a possibility that I only override the OnCertificateError()?
3. Test with 41 is still outstanding. I think delivering 41 makes sense when #1009 is done

**Comment by amaitland** [comment]
> My question is now: If I built a new RequestHandler and assign it to browser.RequestHandler I lose the "default" behavior of the "Default" RequestHandler. I there a possibility that I only override the OnCertificateError()?

There is no default implementation. Basically `return false` for all the methods (except for those with return type of `void` of course) and you'll have the default behavior.

> I think delivering 41 makes sense when #1009 is done

#1009 won't make it into `41` as it's a breaking change to the `API`. It will hopefully be in the `43` release.

**Comment by udo75** [comment]
Thank you very much for the info.

To my test with 41.0.0: the result is the same as in 39.0.0, empty screen.

I tested the ``` IRequestHandler``` interface. Returning with ``` false``` keeps the browser empty - stated as default behaviour.

In case I want to allow the user to navigate to the page with the certificate error - as possible in Chrome - I tested the return value ``` true ``` with the test URL mentioned earlier. In this case the navigation continues to this page but I see that resources are not downloaded and the site setup look completely different. 

My idea is to in this case to display an interim page as in Chrome to show the user a warning and allow him to navigate to the URL - but this time the certificate should not be verified as I would run into a loop.
Any idea how to achieve this?

Thank you in advance

**Comment by amaitland** [comment]
> I tested the return value true with the test URL mentioned earlier. In this case the navigation continues to this page but I see that resources are not downloaded and the site setup look completely different.

Possibly the same as #1104? I think there's likely an `upstream` bug.

> My idea is to in this case to display an interim page as in Chrome to show the user a warning and allow him to navigate to the URL - but this time the certificate should not be verified as I would run into a loop.
> Any idea how to achieve this?

Just keep a simply dictionary of the domain names? If there is no dictionary entry then display some embedded html, based on user action add the domain name with a bool to indicate if they're happy to proceed

**Comment by udo75** [comment]
Is it this what you suggest - just to understand you correctly 

1. User navigates to a page with a self-signed certificate (e.g. an application in a test environment or web)
2. ``` OnCertificateError ``` is triggered which will show a page displaying a warning and a "proceed" button/link to the requested URL
3. User clicks on "proceed", so now I can take the domain into a dictionary
4. The browser is told to navigate to the requested URL with the self-signed certificate

And now? Does again ``` OnCertificateError ``` run and I can check the dictionary if the domain is existing and return with ``` true ``` this time?

**Comment by amaitland** [comment]
> And now? Does again OnCertificateError run and I can check the dictionary if the domain is existing and return with true this time?

Basically, if you navigate to a different domain, then back again you should be asked to validate the certificate again.

**Comment by amaitland** [comment]
How'd you go? Find a workable solution? If you've got something working I'm sure others would benefit from a code sample (preferable a `Gist` or similar). Thanks :+1:

**Comment by udo75** [comment]
I was unfortunately on sick leave almost the whole last week. Currently I have another urgent topic I need to deal with. As soon as I have something working for this topic I'll share it. I have currently no clue what ```Gist``` is but I'll check it out what the best way will be to share :)

**Comment by amaitland** [comment]
It's just a code sharing tool from `GitHub`.

https://gist.github.com/

**Comment by mbsvpn** [comment]
This worked for me as @ray007 mentioned above.

C#
```
CefSettings cfsettings = new CefSettings();
cfsettings.IgnoreCertificateErrors = true;
Cef.Initialize(cfsettings);
```
CefSharp Version: 57.0.0.0
CefSharp Runtime Version: v4.0.30319

**Comment by PauldeKoning** [comment]
> CefSharp Version: 57.0.0.0
> CefSharp Runtime Version: v4.0.30319

Confirm it works on the mentioned version however it does not work for me on the latest version `v75.1.143`

**Comment by amaitland** [comment]
Known issue See #2887

**Comment by amaitland** [comment]
The problem is also listed in the known issues section of the release notes. 

https://github.com/cefsharp/CefSharp/releases/tag/v75.1.141

**Comment by HockeyJustin** [comment]
`CefSettings.IgnoreCertificateErrors ` not working in v75.1.141 (see above for release notes), was a big issue for us. 

This [StackOverflow post](https://stackoverflow.com/a/35564187/852806) details a much needed work-around in C#.
