### ISSUE TITLE
Bug: BrowserSubProcess Dependency Checker Seems Flawed

### ISSUE THREAD

**Issue by bjwallwin** [cefsharp/CefSharp#1120]
Issue Summary
I don't set the CefSettings.BrowserSubProcessPath, I have no reason to for my application.  This causes the checking code in DependencyChecker.cs to fail and always report missing dependencies. In addition the code in DependencyChecker.cs starting at line 128 (if..else) will always cause missing dependencies to be reported. 

Steps to Reproduce
1. Do not set any value for CefSettings.BrowserSubProcessPath.
2. call Cef.Initialize(settings, shutdownOnProcessExit[true|false], performDependencyChecks: true)
3. Start your app, step into Cef.Initialize and observe the behavior of DependencyChecker.cs code when it gets to the BrowserSubProcessChecking.

What I observed:
1. L122 if (!File.Exists(browserSubProcessPath) returns false because the the value being evaluated is simply "CefSharp.BrowserSubProcess.exe".  There is no "path" specified, so the check fails.  I get one tick for a missing dependency.
2. L128 (if..else) You will never get past this without ticking a missing dependency, if your browserSubProcessDir is null, tick, if not tick.

Technical details
* CefSharp Version: 39.0.1, 39.0.2 & 41.0.0 (Line numbers above are for 41.0.0)
* Operating System: Windows 7
* x86/x64: x86
* WinForms/WPF/OffScreen: WinForms

**Comment by amaitland** [comment]
Feel free to submit a PR.

**Comment by amaitland** [comment]
> simply "CefSharp.BrowserSubProcess.exe". There is no "path" specified, so the check fails. I get one tick for a missing dependency.

No path specified will default to using the current executing directory, which for most purposes is the `bin` directory. For most this should be just fine. Are you using a standalone application?

How are you running your test cases?

**Comment by bjwallwin** [comment]
@amaitland agreed that specifying "no path" should default to the relative directory (executing directory), so I did a bit more digging (sorry for not doing that to begin with).

1. Turns out that File.Exists using the relative directory (which does point to the executing directory) is throwing an access denied, which is causing the missing dependency tick.  So I updated the code to pass in the absolute path + filename and this time the check passed.  So its file directory permission that actually failed the check, which ends up being a false negative because the dependency actually does exist.

I don't know if the answer is to always specify the "executing directory" and combine it with the filename. I know that you can pass in an absolute location for the subprocess in the CefSettings, the code would have to be beefed up to account for these possibilities.

I don't think we want an access permission to fail a dependency check, because the file may still exist (such as in my case.

2. In the "else" block that checks for the browser subprocess dependencies the same type of situation is at fault, because no absolute path is passed to CheckDependencyList, its just the relative , the checks fail because of access denied, but the files still exists.

**Comment by bjwallwin** [comment]
perhaps adding complementary code that already exists a bit farther down the class would address the situation.

**Comment by bjwallwin** [comment]
@amaitland  perhaps adding code similar to that directly below the browser sub process check would do the trick.  In the locale pack file check, the localePath variable is constructed as:

var localePath = Path.IsRooted(localePath) ? localPakFile : Path.Combine(path, localePackFile)

if we do this for the browserSubprocess check that might do the trick? would need to see if passes various scenario's, but looks promising?

**Comment by amaitland** [comment]
> if we do this for the browserSubprocess check that might do the trick? would need to see if passes various scenario's, but looks promising?

Can you submit a `PR`? Happy to see the `DependencyChecker` improved :+1:

**Comment by amaitland** [comment]
@bjwallwin Any update on this?
