### ISSUE TITLE
About WinForm Questions

### ISSUE THREAD

**Issue by jackche2006** [cefsharp/CefSharp#1121]
I use CefSharp for WinForm to meet three questions, to ask you:：

1.MainForm has menuscript and ChromiumWebBrowser，click menuscript show dropdownitems，after click ChromiumWebBrowser，but menuscript dropdownitems always show，I want to hide them。

2.CefSharp how to use Chrome extensions？For example: wechat screenshot :http://mail.qq.com/cgi-bin/readtemplate?check=false&t=browser_addon

3.I want to use OffScreen to get Bitmap, but I want to get full page not current screen size.How can i do?

**Comment by jankurianski** [comment]
1. Same issue here, with workaround code in the comments you can paste into your own code:
https://github.com/cefsharp/CefSharp/issues/570

2. https://github.com/cefsharp/CefSharp/issues/719

3. 2 options:

a) Calculate page size with JavaScript.  Set the `ChromiumWebBrowser.Size` to desired screenshot size.  Get new Bitmap of new size.

b) Use JavaScript to scroll page down by `Size.Height`.  Get new Bitmap.  Repeat until you reach end of page.  Combine Bitmaps vertically.

**Comment by jackche2006** [comment]
Thanks for your help.

**Comment by jackche2006** [comment]
Sorry,I has some new questions:
1.Html5 page,use JS to listen offline event, but no work.
               window.addEventListener('offline', function() {
                            alert(123);
                   });

2.ChromiumWebBrowser SizeChanged page content shake, but other browser no shake.(PS: Pull the wide move right, not shake)

**Comment by amaitland** [comment]
1. What version are you using?
2. Can you elaborate? What are the steps to reproduce? Can you reproduce using the `cefclient` example application?

https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

**Comment by jackche2006** [comment]
ChromiumVersion:41.0.2272.104
CefSharpVersion:41.0.0.0

**Comment by jackche2006** [comment]
Use Test App 
2015-05-29 CEF 3.2272.32.gbda8dc7 (78MB) - Chromium 41.0.2272.104 for Windows 64bit

questions 2 :on shake, the same as Chrome 42.0.2311.135
                    but CefSharp Version:41, will shake

**Comment by amaitland** [comment]
What do you mean by `shake`?

Did the `offline` event work with the `cefclient` app?

**Comment by jackche2006** [comment]
shake question, may i give me you E-Mail, I send move to you.

offline event question, cefclient app not work, but Chrome 42.0.2311.135 can work.

**Comment by amaitland** [comment]
> offline event question, cefclient app not work, but Chrome 42.0.2311.135 can work.

Can you try the `43` version of `cefclient`? That'll be what the next release version of `CefSharp` is based on.

> shake question, may i give me you E-Mail, I send move to you.

No thank you.

**Comment by jackche2006** [comment]
offline event question
cefclient TestApp both no work:`3.2272.32` ; `3.2357.1276`; `3.2378.1276`

`shake` mean by, For example, use this page, and set browser FormWindowState to Normal, you can drop right border to change Form size, If you widen something or if it widens:
Chrome and cefclient TestApp, page content relative stability.
But CefSharp, page content will first move left,and them move right.

**Comment by amaitland** [comment]
> offline event question
> cefclient TestApp both no work:3.2272.32 ; 3.2357.1276; 3.2378.1276

You'll have to ask on `http://magpcss.org/ceforum/ then, it's likely not supported for whatever reason.

> But CefSharp, page content will first move left,and them move right.

`CefSharp` will only redraw when you finished resizing the form.
