### ISSUE TITLE
Cef.Initialize causes BEX error in protected 3rd party module

### ISSUE THREAD

**Issue by lamerbug** [cefsharp/CefSharp#1123]
Maybe it's not related to Cefsharp, but here it is...
In my app I have 3rd party native win32 dll, it works okay until I call Cef.Initialize
After that I can see windows reporting about BEX c0000005 error in this dll and my app closes.
I don't have debug version / sources of this dll... Running on 8.1 x64, app compiled as x32.
I looked through Cef.Initialize and found nothing suspicious... what may cause this error?

Native dll is packed (looks like with old AsPack 2.12)
Running on WindowsXP - works okay

Is there something I can do now, or should I contact dll authors for unpacked version? I think aspack is to blame...

**Comment by amaitland** [comment]
@lamerbug Did obtaining an `unpacked` lib solve your problem?

**Comment by amaitland** [comment]
Closing do to lack of feedback.
