### ISSUE TITLE
White screen when switch Windows account

### ISSUE THREAD

**Issue by sapopilas** [cefsharp/CefSharp#1124]
Latest stable version of cefsharp.

Steps to reproduce:
1. Create two windows accounts on win8.
2. Logon under any account.
3. Open cefsharp application installed to all users.
4. Logon under other account.
5. Open cefsharp application installed to all users. (Here i see white screen).
6. All other scenarios related with switching accounts give the same result.

Thanks for answer.

**Comment by amaitland** [comment]
- So your effectively trying to run two instances of `CefSharp` at the same time?
- Are you using `WinForms` or `WPF`?
- Have you specified the `CefSettings.CachePath`?
- Do both users have sufficient privileges? Is one admin and another a lower level user account?
- If you launch your application twice under the same profile do you see the same problem?

Can you please be specific with the version your using, `latest stable` doesn't translate very well when someone looks at this in a few months time. (I've almost seen instances where users says they're using the latest only to find out later that they're not, so I'd rather people were explicit)

**Comment by sapopilas** [comment]
CefSharp.Wpf.37.0.0
I using WPF.
I do not use(specify) cache.
My application is a service. I cant launch it twice.
Both users are the same.

And this scenario:
1. logon first user.
2. launch cef app.
3. switch to second user.
4. switch to first user.
5. white screen.

after getting a white screen the first time you can not return to correct application vehavior.

**Comment by amaitland** [comment]
> CefSharp.Wpf.37.0.0

`41.0.0` is the latest stable version. Can you try upgrading to see if that resolves your problem?

> My application is a service. I cant launch it twice.

Under what user is it running? How do you display the `UI` if it's a service?

**Comment by sapopilas** [comment]
I have service which launch my app.
The application is simple WPF app.
i test when app launched under everyone users, and only under first user.
I need 1 hour for test it on latest version.

**Comment by sapopilas** [comment]
no matter where the application is running . At any manipulation with switching users we get a white screen.

And this scenario:
1. logon first user.
2. launch cef app.
3. switch to second user.(without launching cef app. simple switch).
4. switch to first user.
5. white screen.

**Comment by amaitland** [comment]
What does the log file say? Is the `CefSharp.BrowserSubProcess.exe` still running? Does the render process terminate at any stage? See `OnRenderProcessTerminated`

https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp/IRequestHandler.cs#L81

You can manually ask for a refresh using `Invalidate`, use `View` as the type.
https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.Wpf/ChromiumWebBrowser.cs#L1463

Is the control `visible`? For performance reasons rendering is paused when the control is no longer `visible`
https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.Wpf/ChromiumWebBrowser.cs#L878

**Comment by sapopilas** [comment]
This behavior ONLY on Windows 8. May be this is a OS defect?

**Comment by sapopilas** [comment]
Control is visible.
CefSharp.BrowserSubProcess.exe still running.

**Comment by amaitland** [comment]
Does your app do anything in `Unloaded`? 

https://social.msdn.microsoft.com/Forums/vstudio/en-US/b83195f0-6b39-45cb-ae35-1df959298a80/unloaded-event-gets-fired-if-i-switch-user-in-win-8?forum=wpf

**Comment by sapopilas** [comment]
Ok. I solve this. 
I handle SystemEvents,SessionSwitch for refresh view.

**Comment by sapopilas** [comment]
Thanks!

**Comment by amaitland** [comment]
Can you post a more detailed answer for the benefit of other users, thanks :+1:

**Comment by amaitland** [comment]
@sapopilas Any more info you can provide?
