### ISSUE TITLE
Pressing enter on a select input will close and re-open the select menu.

### ISSUE THREAD

**Issue by wiscow** [cefsharp/CefSharp#1126]
I have some select inputs that we have tight keyboard integration with.  We noticed that when you press enter on an open select input the menu will close and quickly re-open.  If you try this in chrome or the CEFClient.exe the menu you will close and select the option in which enter was pressed. I tested this with the WPF test client in the repository and I achieved the same open/close issue.   

I tested all enviroments with this link: http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select

**Comment by jornh** [comment]
With `cefclient.exe` did you test the behavior with offscreen-rendering enabled?
 (see https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef) 

Version?

**Comment by wiscow** [comment]
I am currently running CEFSharp V 41.0/CEF 3.2272.32.

Hmm interesting.  When i run with `--offscreen-rendering-enabled` with the `cefclient.exe` the select input behaves as expected.    As an FYI we just updated to 41 recently from 39 and the issue was present in 39.

**Comment by jornh** [comment]
Sounds like it's isolated to CefSharp.Wpf - and not CEF - then. 

https://github.com/cefsharp/CefSharp/blob/v41.0.0/CefSharp.Wpf/ChromiumWebBrowser.cs#L937 might be a starting point for debugging if you are up for some debugging.

**Comment by amaitland** [comment]
As `DropDowns` are rendered through the use of a `Popup` in `WPF`, it's probably worth checking that all the params are coming through correctly as well.

https://github.com/cefsharp/CefSharp/blob/v41.0.0/CefSharp.Wpf/ChromiumWebBrowser.cs#L290
https://github.com/cefsharp/CefSharp/blob/v41.0.0/CefSharp.Wpf/ChromiumWebBrowser.cs#L295

**Comment by wiscow** [comment]
well i am getting somewhere. looks like enter may be being processed twice.  once natively by CEF and once by an event handler on the WPF side.  More to come hopefully.

**Comment by amaitland** [comment]
Remember for every key press there is a corresponding `KeyUp` and `KeyDown`.

**Comment by amaitland** [comment]
A quick test on `master` with some `Debug.WriteLine` statements and it appears the `Popup` is being closed then opened again. The dimensions and position are exactly the same. I only witnessed two key events, one up and one day. Probably need to dig through the `cefclient` source and see what's different.

**Comment by amaitland** [comment]
Tested with latest `master` and unable to reproduce. If someone can reproduce the problem we can reopen this.
