### ISSUE TITLE
Clearing cache

### ISSUE THREAD

**Issue by sapopilas** [cefsharp/CefSharp#1128]
I need to disable or clear all caching.
When cache path not specified, i cant clear cache which already in memory.
And i cant reinitialize cef browser for this.

Thanks for your answers.

**Comment by amaitland** [comment]
You can reload a page ignoring cache, if you need something more complex then you'll need to 'search/ask' on http://magpcss.org/ceforum/index.php

**Comment by noone2407** [comment]
Check this https://github.com/cefsharp/CefSharp/issues/1133
