### ISSUE TITLE
Cookies Not Working?

### ISSUE THREAD

**Issue by fanlovejx** [cefsharp/CefSharp#113]
![Untitled](https://f.cloud.github.com/assets/3885850/267330/790b88ee-8e78-11e2-9e5d-dfbba3249c34.jpg)

I'm trying excute Script to get Cookies in my favour page but no thing happens, i'm open devtool but it blank. please help me!

**Comment by james-c-m-kim** [comment]
Could you please give us a passthrough functionality for SetCookies()?

**Comment by amaitland** [comment]
Please don't comment on dead issues.

If you search the code you'll find there is already a method for setting cookies.

**Comment by james-c-m-kim** [comment]
Sorry about that...
