### ISSUE TITLE
Capture Devtools Console output

### ISSUE THREAD

**Issue by avspeed** [cefsharp/CefSharp#1130]
Hello,

Is it possible to capture the  Dev tools console output and display it in my .NET app ?

Thanks

**Comment by jornh** [comment]
There is nothing specific for it in CefSharp. But as Devtools is implemented in JavaScript it's "just" a matter of injecting some JS and using [`EvaluateScriptAsync`](https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#CallJSWithResult).

So it's more of an upstream CEF/Chromium question and you have to dig around there to see if there's a sensible API exposed. A few starting points:

* https://developer.chrome.com/extensions/devtools probably isn't available in CEF as it's an Chrome Extension API (and those are generally only available in Google Chrome - not the open source Chromium)
* https://developer.chrome.com/devtools/docs/debugger-protocol via e.g. C# `WebRequest`might be an alternative depending on what you really want/need
* Lacking a proper stable API simply dig around the DOM of the console and hack something. Though this may sound terrible the good part is that you are in complete control of when you push upgrades - still you have to verify each time :-(

**Comment by amaitland** [comment]
For basic console messages there is of course https://github.com/cefsharp/CefSharp/blob/master/CefSharp/IWebBrowser.cs#L14

**Comment by jornh** [comment]
Good catch @amaitland :smile: I completely forgot about that one!

**Comment by avspeed** [comment]
Exactly what I need - Thank you!

**Comment by amaitland** [comment]
The `DevTools` reference in the initial question was a little misleading. Initially I read the question the same way @jornh did :smile:

**Comment by aslamiqbal** [comment]
@amaitland 
> For basic console messages there is of course https://github.com/cefsharp/CefSharp/blob/master/CefSharp/IWebBrowser.cs#L14

Awesome. I was looking for this all over the internet full day.
