### ISSUE TITLE
How to find current focused UI element in cefsharp wpf chromiumwebbrowser

### ISSUE THREAD

**Issue by TrivikramP** [cefsharp/CefSharp#1131]
Hi,
I am using cefsharp wpf chromium web browser in my application. I need to find current focused element type in web page( like textbox, checkbox, button etc...).  How do I find it?

Also, how do I shift focus on page elements programmatically?

**Comment by jornh** [comment]
2nd item in the FAQ https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#CallJSWithResult should tell you how to use the .NET -> JS binding.

From there your questions are essentially reduced to a JavaScript problem. Start with e.g. http://makandracards.com/makandra/12823-how-to-find-out-the-currently-focused-dom-element-with-javascript

**Comment by amaitland** [comment]
Any followup? Can we close this?

**Comment by TrivikramP** [comment]
First issue is solved after using javascript.
But, I am facing issues in moving focus. My requirement is that Keyboard left should act like tab press and right should act like shift tab press.  I am able to move the focus using javascript by iterating through all DOM elements and compare against current focused element to determine the next focusable or previous focusable element. Though it seems to be working but i am looking for a simpler solution like mapping directly keyboard left to tab and right to shift+Tab. 
Is there any way?  Can I use SendKeyEvent() for this purpose? If so, how to use it?

**Comment by amaitland** [comment]
> Can I use SendKeyEvent() for this purpose? If so, how to use it?

You can send key events, yes. It's probably one of the most complicated methods in the whole framework unfortunately (as keyboard handling in general is quite complex). Your best bet is to put some debug logging in the currently handle and see what gets send when you press those keys.

https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.Wpf/ChromiumWebBrowser.cs#L966

You can try intercepting key presses with `IKeyboardHandler`

https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp/IKeyboardHandler.cs#L7

If that doesn't work then you'll have to extend the `ChromiumWebBrowser` class and override some of the `WPF` keyboard handling methods.

**Comment by TrivikramP** [comment]
Thanks. Tab focus is working by using SendKeyEvent(0x0104, 9, 0). But, Shift+tab is not. 
I believe, shift key code should be passed as lParam to this method. I have tried few combinations but nothing seems to worked. How to accomplish this?

**Comment by amaitland** [comment]
You'll have to dig through the code. Shift is a modifier, from memory it's appended to `wParam`

https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.Core/ManagedCefBrowserAdapter.h#L191

**Comment by amaitland** [comment]
Next version will make things like this much easier as you can access the underlying `CefBrowserHost` implementation https://github.com/cefsharp/CefSharp/blob/master/CefSharp/IBrowserHost.cs#L44

**Comment by amaitland** [comment]
If your still having problems with sending key events then please open a new issue. Closing as the original issue was resolved.
