### ISSUE TITLE
Cef does not shutdown after calling  Cef.Shutdown();

### ISSUE THREAD

**Issue by noone2407** [cefsharp/CefSharp#1133]
I created a small program through Nuget using CefSharp WinForm 41.0.0 Stable version.
This is my code
``` C#
        public Form1()
        {
            new Thread(() =>
            {
                var settings = new CefSettings
                {
                    
                    IgnoreCertificateErrors = true,
                    CachePath = Path.Combine(Application.StartupPath, "Cache"),
                    LogSeverity = LogSeverity.Info,
                    LogFile = Path.Combine(Application.StartupPath, "log.txt")
                };
                Cef.Initialize(settings);
              var  browser = new ChromiumWebBrowser("http://google.com")
                {
                    Dock = DockStyle.Fill,
                    BrowserSettings = { ApplicationCacheDisabled = true },
                };
                while (panel1 == null || !panel1.IsHandleCreated)
                {
                    Thread.Sleep(10);
                }
                Invoke(new Action(() =>
                {
                    panel1.Dock = DockStyle.Fill;
                    panel1.Controls.Add(browser);
                }));
            }) { IsBackground = true }.Start();
            InitializeComponent();
        }

        private void Form1_FormClosed(object sender, FormClosedEventArgs e)
        {
            Cef.Shutdown();
            Application.Exit();
        }
```
I have 2 problems that I need someone help me find answers.
The first: when I close form, one CefSharp.BrowserSubprocess.exe ends but another one and the main process still run and the form disappears. Why don't all processes end?
The second question is: the first time I run it creates Cache folder and it creates a few f_00000* files, but when I shut it down, remove those f_00000* cache files and rerun it does not create any cache files any more. Instead it shows me some log. Here is the log created 

```
[0721/144626:ERROR:cache_util_win.cc(20)] Unable to move the cache: 5
[0721/144626:ERROR:cache_util.cc(132)] Unable to move cache folder c:\Users\Dung\Documents\Visual Studio 2013\Projects\CefSharp41\CefSharp41\bin\X86\Debug\Cache to c:\Users\Dung\Documents\Visual Studio 2013\Projects\CefSharp41\CefSharp41\bin\X86\Debug\old_Cache_000
[0721/144626:ERROR:cache_creator.cc(133)] Unable to create cache
```

Please notice that I set ApplicationCacheDisabled = true;

**Comment by amaitland** [comment]
You basically need to `Initialize` and `Shutdown` on the same thread. Preferably the `UI` thread. If at all possible you'd be better to simplify your code. You can see https://github.com/cefsharp/CefSharp.MinimalExample/blob/master/CefSharp.MinimalExample.WinForms/BrowserForm.cs#L23 for a basic example.

If your still having problems shutting down cleanly, then removing the control and manually disposing usually works.

Do you have an explicit need to create the `ChromiumWebBrowser` control in a separate thread? `CEF` has some subtle threading complexities so best to avoid doing anything too fancy unless absolutely necessary.

> [0721/144626:ERROR:cache_util_win.cc(20)] Unable to move the cache: 5

The cache errors are due to the shutdown problem, see https://bitbucket.org/chromiumembedded/cef/issues/1432 for an explanation (second comment from the bottom)

**Comment by noone2407** [comment]
OK I get it. Now I run   Cef.Initialize(settings); and  Cef.Shutdown(); in UI thread it can shutdown. What about cache, can I disable the disk cache completely, so it will always download whole page when loading a web? Or just a simple method to clear cache, because I don't want the cache to consume so much disk usage. 
I can easily disable Local Storage by this 
settings.CefCommandLineArgs.Add("--disable-local-storage", "1");
but when I use this line, it does not work
settings.CefCommandLineArgs.Add("--disable-cache", "1");

**Comment by amaitland** [comment]
Your sample showed `CachePath = Path.Combine(Application.StartupPath, "Cache")`, if you don't set a cache path then it will use an `InMemory`, so nothing will be persisted.

A quick search on http://magpcss.org/ceforum/search.php?keywords=clear+cache and there are a few people asking similar questions, not a lot of workable solutions from what I can see.

**Comment by noone2407** [comment]
I use this line 
CachePath = Path.Combine(Application.StartupPath, "Cache")
Because I need to keep cookie. 
Now I realize that when I need cookie and no cache I just have to use 
Cef.SetCookiePath(Path.Combine(Application.StartupPath, "Cookie"), true);
Thank you for your helping.
