### ISSUE TITLE
How to Hide PDF Viewer Toolbar

### ISSUE THREAD

**Issue by indigophoenix** [cefsharp/CefSharp#1139]
When loading a PDF document into browser, is there a way to hide the toolbar (zoom, save, print, etc.)?  I've spent some time searching and even some time experimenting, but with no success.

It seems if I load a PDF into Chrome and use the developer tools, I can inspect the element and then set display: none.  That does the trick there, but when I try to execute some javascript via CefSharp, it doesn't seem to have any effect.

From poking at some view source information, it looks like Chrome (the official Google version) is somehow intercepting the PDF view request and displaying the PDF in a container or frame or something of that sort that I can't directly access from operating on the main CEF frame.

Any ideas?  Any help would be much appreciated.  Thanks in advance!

**Comment by amaitland** [comment]
Try `asking/searching` the `upstream` forum, at http://magpcss.org/ceforum/

The other option might be to fallback to using the `Adobe` plugin and seeing if something like https://geertzijlmans.wordpress.com/2009/06/04/hiding-the-toolbar-and-navpanes-of-adobe-acrobat-reader-in-a-browser/ works

**Comment by indigophoenix** [comment]
Thanks @amaitland, I will try asking the CEF forum.  One of the things that we like about CEF/CefSharp is that we can view PDF files without having to have the Adobe plugin. :)  If it can't end up being done at the moment, not a huge deal.  Right now, it's just a slight visual inconvenience.

**Comment by amaitland** [comment]
It looks like `pdfium` exposes some sort of `API` see http://stackoverflow.com/questions/28391198/does-pdfium-expose-its-api-to-javascript-i-want-to-get-the-number-of-current-pa
I've never tried it myself, so cant comment past that.

If you dig through the `pdfium` source you might find something http://src.chromium.org/viewvc/chrome/trunk/src/pdf/instance.cc

**Comment by indigophoenix** [comment]
Including the thread from the upstream forum for findability:
http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=13234

**Comment by xeleoss** [comment]
Ну и как это решили?

**Comment by gitmarcalinascris** [comment]
Any updatE?

**Comment by gksky** [comment]
add in URL #toolbar=0, like below:

**Comment by ukandrewc** [comment]
You can also modify the style of the `<embed>`

`position:absolute; left: 0; top: -59px; height: calc(100vh + 59px)`
