### ISSUE TITLE
Sharing Cookies

### ISSUE THREAD

**Issue by edohy2y** [cefsharp/CefSharp#1140]
Hi CefSharp experts:

I have successfully used CefSharp.OffScreen to navigate pages and was able to create some interactions with certain websites.  I would like to be able to use CefSharp.WinForm to show an embedded page to clients.  I am running into some issues attempting this.  The reason I am attempting to do this is some pages will put session information inside of Cookies.

Here are some details:
Here is what I have tried:
1. Initialize with CachePath = @".\"
2. CookiePath = @".\"
3. Using CefSharp.OffScreen, navigate to different pages, performed some operations.  This included javascript actions.
4. <Operations here varies>
5. Using CefSharp.WinForm, attempt to navigate to certain web page.

The various things I have tried in step 4:
a. Initialize
b. initialize, then set cookie path
c. setting cookie path without initialize(this works because I didn't do Cef.Shutdown before step 5)
d. initialize, set cookie path, then call Cef.SetCookie(this does not create any file as far as I can tell)
e. Cef.SetCookie without initialize or setting cookie path.
f. Cef.Flush, then initialize, then set cookie path, then set cookie.
g. Cef.Flush, then set cookie without initialize or setting cookie path.

Questions:
It seems I cannot generate any kind of cookie related files even when I attempted flush.  How does the cookies work in my usage context?
I have tried to do this entirely by using the CefSharp.WinForm.ChromiumBrowser.  But I cannot seem to get NavStateChanged event to fire.  If someone can point me in the right direction as to why it doesn't fire when am running my code with respect to CefSharp.WinForm.ChromiumBrowser, I would love to try and see if running everything within the WinForm framework would work.

Thanks for reading, Hope to hear from someone soon.

Eddie

**Comment by edohy2y** [comment]
Um, my bad guys, I as able to create cookie files.  However the cookies just not seem to be able to be shared.  How can I verify if the CefSharp.WinForm.ChromiumBrowser is indeed using the cookie files generated?

**Comment by amaitland** [comment]
You can use `VisitAllCookies` to see get basic information. Probably worth a try.
https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.Core/Cef.h#L280

I believe the cookie operations need to be performed after the `Context` has been initialized (basically you need to wait for `CEF` to at least partially load before you can perform certain operations)
https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.Example/CefExample.cs#L84

**Comment by edohy2y** [comment]
Thanks amaitland, I will check out those links.  Logs wise, I seem to be getting these during the OffScreen part(although OffScreen part seems to have succeed):
[0722/184708:ERROR:renderer_main.cc(212)] Running without renderer sandbox
[0722/184708:ERROR:cache_util_win.cc(20)] Unable to move the cache: 32
[0722/184708:ERROR:cache_util.cc(132)] Unable to move cache folder .\ to old_._000
[0722/184708:ERROR:cache_creator.cc(133)] Unable to create cache
[0722/184712:ERROR:content_client.cc(137)] No localized string available for id 19019
[0722/184712:ERROR:content_client.cc(137)] No localized string available for id 19020
[0722/184712:ERROR:content_client.cc(137)] No localized string available for id 19021
[0722/184712:ERROR:content_client.cc(137)] No localized string available for id 19103

**Comment by amaitland** [comment]
> [0722/184708:ERROR:renderer_main.cc(212)] Running without renderer sandbox

Safe to ignore, it's really just a warning. `sandbox` hasn't been implemented.

> [0722/184708:ERROR:cache_util_win.cc(20)] Unable to move the cache: 32

See https://github.com/cefsharp/CefSharp/issues/1133#issuecomment-123214054

> [0722/184712:ERROR:content_client.cc(137)] No localized string available for id 19019

Have you disabled `pak` loading? Are the `pak` file present? I've not seen this error before, probably worth `searching/asking` on the http://magpcss.org/ceforum/index.php

**Comment by amaitland** [comment]
Any further comment? Happy to close?
