### ISSUE TITLE
compressing libcef

### ISSUE THREAD

**Issue by avspeed** [cefsharp/CefSharp#1145]
Hello,

Has anybody had any success compressing libcef.dll using upx for example, while keeping the cefsharp functionality intact ?

Thanks

**Comment by avspeed** [comment]
I compressed libcef with upx ( no special switches ) and my app still works -
the release version of libcef.dll went from 40MB to about 13MB

Closing

**Comment by avspeed** [comment]
after compressing, I am running into issues running my app from the IDE ( debug mode ) I am getting a Type Initialization exception.
The same exception does not get thrown when running the app outside of the IDE. Does anyone have any experience with compressing libcef.dll ?

Thanks

**Comment by amaitland** [comment]
Asking on http://magpcss.org/ceforum/index.php will likely expose your question to a wider audience of `CEF` users.

Sounds like you have a workable solution really, just need to compress when you package your app up for release.

**Comment by avspeed** [comment]
Sounds good. Thanks.

**Comment by jornh** [comment]
Someone had the same experience before: https://github.com/cefsharp/CefSharp/search?q=upx&type=Issues&utf8=%E2%9C%93

**Comment by gsiry** [comment]
Indeed - Thank you

On Sat, Jul 25, 2015 at 9:21 AM, jornh <notifications@github.com> wrote:

> Someone had the same experience before:
> https://github.com/cefsharp/CefSharp/search?q=upx&type=Issues&utf8=%E2%9C%93
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cefsharp/CefSharp/issues/1145#issuecomment-124846932>.
>



-- 
Gaetan "G" Siry
twitter  - @gsiry
gvoice - 7815199201
mobile - 7819603668
Email  - gaetan.siry@gmail.com
Links :
https://geekli.st/avspeed
http://www.avspeed.com
