### ISSUE TITLE
Hi Team (Please Delete Me once Read)

### ISSUE THREAD

**Issue by shawty** [cefsharp/CefSharp#1146]
Hi All,

Sorry about doing things this way (GH don't make it easy to contact project owners)

I thought you might all like to know, I finally got around to doing that blog post on Cef-Sharp that I was going to do months ago, along with a sample on my own repo here on GH.

http://www.codeguru.com/columns/dotnet/if-you-like-it-put-an-html5-ui-on-it.html

Regards
Shawty

**Comment by amaitland** [comment]
Great :+1:

I've not seen any problems installing `CefSharp.Common` before. Any additional information?

**Comment by shawty** [comment]
Yea it was just a few hiccups with NuGet, Not got time to document them this week, but prod me next week and I will.

 

Shawty
