### ISSUE TITLE
Feature Request - Add ability to customise BrowserSubProcess

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#1149]
So it should be possible for the user to implement their on `BrowserSubProcess` executable for which they can plugin some custom code.
- Rename classes so they're standardized
- Add some interfaces and default implementations with `virtual` methods so that users can override.

Should be relatively easy and potentially users can then plugin features that have previously been missing by simply contributing a basic wrapper for whatever class has yet to be exposed.

**Comment by amaitland** [comment]
First steps towards this are complete, `CefSharp.BrowserSubProcess.exe` is now just a single `c#` class for which you can basically copy and paste into your own project.

https://github.com/cefsharp/CefSharp/blob/cefsharp/51/CefSharp.BrowserSubprocess/Program.cs#L14

For those of you obsessed with trying to rename `CefSharp.BrowserSubProcess.exe`, this is a much better way, copy and paste the code, add the references, create your own implementation! Don't forget to set the `settings.BrowserSubProcessPath` property to point to your new `exe`.

Will be available in `51.0.0-pre01` and newer

**Comment by giangcoi48k** [comment]
Hi @amaitland 
I tried create subProcess follow your guide Program.cs.
But SubProcess does not exist,

**Comment by amaitland** [comment]
At this stage there are no further plans to expand the customisation of the subprocess.

**Comment by SiriusED** [comment]
Can't make it to work, something changed I assume or something... But when I pul everything according this guide my console application just crashes or says "**Could not load file or assembly 'CefSharp.BrowserSubprocess.Core**"

Could someone share an example c# project with working code that renames and successfully runs **CefSharp 
 BrowserSubprocess**?

**Comment by amaitland** [comment]
> Could someone share an example c# project with working code that renames and successfully runs CefSharp
BrowserSubprocess?

Renaming is not recommend/supported. 

You can self host the browser subprocess see https://github.com/cefsharp/CefSharp/blob/cefsharp/97/CefSharp.Core/BrowserSubprocess/SelfHost.cs#L22


- https://github.com/cefsharp/CefSharp.MinimalExample/blob/master/CefSharp.MinimalExample.WinForms/Program.PublishSingleFile.cs#L25
- https://github.com/cefsharp/CefSharp.MinimalExample/blob/master/CefSharp.MinimalExample.Wpf/Program.PublishSingleFile.cs#L24

Further questions please use https://github.com/cefsharp/CefSharp/discussions
