### ISSUE TITLE
Subprocess crashes when JavascriptCallback feature used after page reload

### ISSUE THREAD

**Issue by arsher** [cefsharp/CefSharp#1152]
I've been playing around with the binding tests on the master branch when I noticed that the javascript callbacks are only working for the first load in a browser after a reload/redirect etc. they crash the subprocess. It seems like a NRE in the subprocess but couldn't locate it, there wasn't any stack trace (??).
I'll continue looking into it tonight.

**Comment by amaitland** [comment]
I just committed a change to `master`, let me know if that solves the problem. Code should be simpler to follow, looks like we also missed passing in a reference to `JavascriptPropertyWrapper`, so any methods of a sub object wouldn't have worked properly. I don't believe the direct cause of the problem, just a side now. I think the `NullReferenceException` was `dispose` released, likely we'd cleaned up something too early

https://github.com/cefsharp/CefSharp/commit/3d19b3a587e364b1501bfc3423185fc132047a79#diff-264431655280d70fe5cd908a3682fecdR39

Full commit is
 https://github.com/cefsharp/CefSharp/commit/3d19b3a587e364b1501bfc3423185fc132047a79

**Comment by arsher** [comment]
Awesome (Y). This fixed it, thanks!
