### ISSUE TITLE
Ability to click drag/move selected/highlighted text 

### ISSUE THREAD

**Issue by KiyaDoig** [cefsharp/CefSharp#1154]
Currently this functionality does not appear to be implemented. 
It should be possible to select/highlight text and then click (hold) and drag to drop/copy the text.

Any information about the amount of changes required to achieve this would also be helpful. (I.e. Are there just missing lines of code or is the current implementation blocking this functionality.)

**Comment by amaitland** [comment]
It's a little bit complicated, what your actually looking at with the `WPF` control is an image. Every action is forwarded to the underlying `CEF` browser control and new frames (images) are generated.

It's probably worth testing out the `Upstream` `CEF` demo application, `cefclient`, if the feature is implemented in there, then it should be relatively straight forward to port across. (Make sure to run it with the `--off-screen-rendering-enabled` command line param so it uses `OffScreen Rendering`) If not, it'll be a matter of determining if it's possible. 

https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

**Comment by mmamone** [comment]
If you run the cef demo in with offscreen rendering enabled, click to drag copy *does* work, but you don't get the visual indicator.
When offscreen rendering is disabled, again, click to drag works, but you also get that nice visual of the highlighted text moving with the mouse.

**Comment by amaitland** [comment]
> If you run the cef demo in with offscreen rendering enabled, click to drag copy does work, but you don't get the visual indicator.

If that's the case then it's just a matter of someone implementing the missing features. `PR's` are welcome :+1:

**Comment by mmamone** [comment]
Already on it :)

**Comment by amaitland** [comment]
Great :+1: 

Please make sure to read https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#pull-requestsfeature-branches
