### ISSUE TITLE
Feature Request - Support for CefZipArchive

### ISSUE THREAD

**Issue by martijn189** [cefsharp/CefSharp#1155]
Using CEFsharp via NuGet packages in our vb.net project. I cannot find a way to use "CefZipArchive", it is not defined. It would be great to have support for the CefZipArchive. In CEF it is possible to load a zip file and use it with a custom schemehandler. CEFsharp does not seem to have the CefZipArchive method.

The WBEA application (Asterclick) uses the CefZipArchive class to load a zip file into CEF, for this project there is source availlible in C#.

Information about the class is found at: http://magpcss.org/ceforum/apidocs/projects/(default)/CefZipArchive.html

**Comment by amaitland** [comment]
Planning on submitting a `PR`?

**Comment by martijn189** [comment]
I assume you mean a Problem report?, i do not know how to explain it techically, as far as i can tell this class is not availible in CEFsharp (not linked). I cannot use "New CefSharp.CefZipArchive()"

**Comment by amaitland** [comment]
`PR` = `Pull Request`. Basically are you working towards implementing the feature?

**Comment by martijn189** [comment]
Oh sorry, first time here... I would like to contribute but do not know how to make this work or which code to create for CEFsharp to get this feature. I need a way to load zip files (which contain the web files) into CEFsharp. I am using vb.net, i figgurerd that i should create a custom scheme and must load the zip into a memorystream (later it should be have encode/decode support). There is a project called WBEA, they ysed CEF directly to load a zip file, but for vb.net i think i need CEFsharp.

**Comment by amaitland** [comment]
Should be relatively trivial to implement with a `Scheme` handler, a lot easier than trying to implement the `CefZipArchive` wrappers.

It would be something like 
- Unzip archive to a temp location and simply have some sort of mapping between url and disk location
- Use `ZipArchive` to load a zip file from `Stream`, on request, find matching zip entry for url, then populate `ResponseStream`

**Comment by amaitland** [comment]
> This class should not be used with large archive files because all data will be resident in memory at the same time.

Due to the limitations of the native implementation I believe it's better to implement the equivalent in `.Net`.
