### ISSUE TITLE
Winform Sample Crash!

### ISSUE THREAD

**Issue by qiurideyun** [cefsharp/CefSharp#1157]
Hi : when i request the URL = http://m.vvipone.com/h5 ,the winform samle crash.what the reason cause crash.

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue

**Comment by amaitland** [comment]
Closing due to lack of feedback.
