### ISSUE TITLE
Cannot set default css rules for pages

### ISSUE THREAD

**Issue by gomidas** [cefsharp/CefSharp#1163]
I was using Awesomium it had CustomCSS feature and more but it was freezing window on certain pages. Then I started using CEFsharp but I did not find same features on this. Is there a way to set up default css rules?

**Comment by jornh** [comment]
customCSS got removed from Chromium: #315. You can use the .NET to JavaScript bridge to inject CSS into the DOM.

**Comment by amaitland** [comment]
No feedback from `OP`, assuming this is resolved.

**Comment by Paulo-Faustino** [comment]
Just double checking, in this case the change on the page layout (colors, margins, etc) will be noticeable to the user  since the Java script css injections will happen after the page is already visible depending on the website?

**Comment by amaitland** [comment]
How it looks likely depends on the page your injecting code into. It's one of those were I think you have to try it, determine if you can live with the limitations.

If you need a seamless experience then you would have to intercept the request for the main page or one of it's css document, fulfill the request yourself and inject some code directly. 

There is an open `upstream` issue that would give better control
https://bitbucket.org/chromiumembedded/cef/issues/1454
