### ISSUE TITLE
Empty devtools after location change

### ISSUE THREAD

**Issue by Remo** [cefsharp/CefSharp#1165]
I'm using `Chromium: 39.0.2171.95, CEF: r2069, CefSharp: 39.0.1.0, Environment: x86`.

When I open the dev tools the first time they work fine, but when I change the location through a link they are just empty. Closing and hiding doesn't help. Any idea on how I can track down my JavaScript errors?

![image](https://cloud.githubusercontent.com/assets/129864/9023215/6d4dfd04-3892-11e5-8f40-cddfeee6072c.png)

**Comment by amaitland** [comment]
Does the problem reproduce with the latest official release?

**Comment by Remo** [comment]
I think this happened because the second page caused a JavaScript error which we've fixed yesterday night. Having a hard time to reproduce since we've changed a lot yesterday.
I'll try to see if I can reproduce it again, closing it till then.
