### ISSUE TITLE
GetResourceHandler doesn't appear to be implemented / firing

### ISSUE THREAD

**Issue by MarshallOfSound** [cefsharp/CefSharp#1166]
I am trying to intercept a request to a JS file and append some code to the end of it before it even reaches the browser.  To do this it seemed like `GetResourceHandler` was the way to go but it doesn't fire.

Even the simplest implentation does not work at all
````
public ResourceHandler GetResourceHandler(IWebBrowser browser, IRequest request)
    {
        Debug.WriteLine("handled");
        return null;
    }
````

Any help / examples would be great

**Comment by amaitland** [comment]
You did remember to assign the newly created instance of `IResourceHandlerFactory` to the `ChromiumWebBrowser.ResourceHandlerFactory` property?

https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp/IWebBrowser.cs#L156

As a general rule you need to include version, flavor, etc when creating an issue. See https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue

**Comment by MarshallOfSound** [comment]
@amaitland Sorry about not following the issue guidelines
I am using CefSharp for WinForms version 41

````
private bool once = false;
    public ResourceHandler GetResourceHandler(IWebBrowser browser, IRequest request)
    {
        if (Regex.Match(request.Url, @"gu-util.js", RegexOptions.IgnoreCase).Success && !once)
        {
            once = true;
            Debug.WriteLine("Injected JS into response");
            using (WebClient webClient = new WebClient())
            {
                string data = Google_Play_Music.Properties.Resources.inject;
                ResourceHandler tmp = new ResourceHandler();
                tmp.Stream = new MemoryStream(Encoding.UTF8.GetBytes(webClient.DownloadString(request.Url) + data));
                tmp.MimeType = webClient.ResponseHeaders["Content-Type"];
                return tmp;
            }
        }
        return null;
    }
````

I managed to get the `GetResourceHandler` to fire but now I am getting Null Exceptions whenever `tmp` is returned.  If I return null everything works fine, but whenever it goes into the if and returns `tmp` I get Null Exceptions.

Any idea whats going on?

**Comment by amaitland** [comment]
Can you confirm that `MimeType` is not null?

The underlying code can be found it https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.Core/Internals/ClientAdapter.cpp#L314

**Comment by MarshallOfSound** [comment]
`MimeType` is not null, just double checked.  It is a string `'text/javascript'`

I should also point out that the posted code was a bit innacurate.  I had to make a Custom Resource Handler because the `Stream` and `MimeType` properties were read only.

````
public class CustomResourceHandler : ResourceHandler
{
    Stream str;
    public Stream Stream
    {
        get { return str; }
        set { str = value; }
    }

    string mime_type;
    public string MimeType
    {
        get { return mime_type; }
        set { mime_type = value; }
    }
}
````

Could that be breaking it?

**Comment by amaitland** [comment]
> Could that be breaking it?

That's likely it yes.

There's a number of static methods used for creating `ResourceHandler` objects, see https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp/ResourceHandler.cs#L140

**Comment by MarshallOfSound** [comment]
Thanks so much, I've got it all working now :)
