### ISSUE TITLE
VS2015 BrowserSettings options not available in 41?

### ISSUE THREAD

**Issue by Levia-** [cefsharp/CefSharp#1167]
Trying to set OffScreenTransparentBackground but it is only showing a few font related properties - not all the ones defined in BrowserSettings.h. I'm 100% sure I'm using the correct version, anyone any idea what is going on here?

**Comment by amaitland** [comment]
Are you using `VS2015`?

**Comment by Levia-** [comment]
Yes. Getting:
Severity	Code	Description	Project	File	Line
Error	CS1545	Property, indexer, or event 'BrowserSettings.OffScreenTransparentBackground' is not supported by the language; try directly calling accessor methods 'BrowserSettings.get_OffScreenTransparentBackground()' or 'BrowserSettings.set_OffScreenTransparentBackground(?)'	SEOAuditor.Screenshot	Program.cs	47

**Comment by amaitland** [comment]
> Yes. Getting:

If your using `VS2015` it's a known issue, #1101

**Comment by Levia-** [comment]
Alright thanks

**Comment by amaitland** [comment]
If your up for submitting a `PR`, I'm happy to release an updated version, that's a slightly annoying bug.

**Comment by amaitland** [comment]
Resolved with https://github.com/cefsharp/CefSharp/commit/cf3d27be842b4bee08103484b859b661cb95a6f5

**Comment by amaitland** [comment]
New package pushed to `nuget.org`

**Comment by Levia-** [comment]
Thanks for that, didn't have much time yesterday.
