### ISSUE TITLE
Disable capture of drag drop events

### ISSUE THREAD

**Issue by stephendalyctg** [cefsharp/CefSharp#1171]
I know that it is currently possible to intercept the DragEnter event by implementing IDragHandler.OnDragEnter.

It would be good if there was a way to either also intercept the drop event, or to disable drag events for the browser entirely and allow them to be handled by the parent control.

What I am trying to achieve is to allow the user to drag and drop files anywhere onto a form which contains a ChromiumWebBrowser control and handle this by opening the files in the application. As the browser captures all drag events, it is not possible for me to handle dropping files onto the browser control.

The Windows .NET WebBrowser control has an AllowWebBrowserDrop property. If this is set to false, the WebBrowser does not capture drag events at all and allows the parent control to handle them. It would be good if there was a similar option for the ChromiumWebBrowser.

**Comment by amaitland** [comment]
`WinForms`, `WPF`?

The underlying `CEF API` only exposes limited drag functionality

http://magpcss.org/ceforum/apidocs3/projects/%28default%29/CefDragHandler.html

**Comment by stephendalyctg** [comment]
Sorry, in WinForms.

In that case is it possible to have a setting to disable drag-drop entirely for the WinForms control?
The current work around we're using is to call RevokeDragDrop on the child window inside the control that is capturing the drag-drop events.

https://msdn.microsoft.com/en-us/library/windows/desktop/ms692643(v=vs.85).aspx

Doing this allows us to handle all drag-drop events on the browser in the parent control, but this isn't an ideal way of doing it.

Would it be possible to not subscribe to the drag/drop events in CefSharp, or is this done in CEF?

**Comment by amaitland** [comment]
> Would it be possible to not subscribe to the drag/drop events in CefSharp, or is this done in CEF?

`CEF` handles all drag and drop in `WinForms`.

Looks like there was some discussion in relation to `CEF`.

https://code.google.com/p/chromiumembedded/issues/detail?id=644
https://bitbucket.org/chromiumembedded/cef/issues/601

I'm open to suggestions as to implementing something in `CefSharp`.

**Comment by amaitland** [comment]
http://magpcss.org/ceforum/viewtopic.php?f=6&t=10548&p=16182

**Comment by amaitland** [comment]
As there is a workable solution I'm closing this.

If `CEF` at some point in the future adds the ability to disable drop then this can be reopened.
