### ISSUE TITLE
RegisterJsObject alternative

### ISSUE THREAD

**Issue by Paulo-Faustino** [cefsharp/CefSharp#1172]
Is there an alternative way of capturing data from ChromiumWebBrowser besides calling RegisterJsObject?

I'm having an issue with threading when using RegisterJsObject due to the complexity of my project and I was looking for a simple way to pass stringified JSON Objects from the browser to my Winforms main form.

Thanks

**Comment by amaitland** [comment]
You can create a `scheme` handler and make `AJAX` calls, little bit more work, pretty straight forward though.

**Comment by Paulo-Faustino** [comment]
Hey man, does it have to be Ajax calls? Is there an official  documentation on this technique? I want to make it as simple as possible to pass these strings between the browser and the form to ensure it will be reliable.

Thank you.

**Comment by amaitland** [comment]
> does it have to be Ajax calls?

You could probably use an old school `iframe` approach, though I'd go with `AJAX` over that any day. A `Scheme` handler is just a custom way of responding to a request.

> Is there an official documentation on this technique?

No. It's the technique that people used before `Javascript Binding` was implemented. Example `Scheme` handler is https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.Example/CefSharpSchemeHandler.cs#L46

> I want to make it as simple as possible to pass these strings between the browser and the form to ensure it will be reliable.

The simple approach is `Javascript Binding`. If you don't have to use that, then you need to implement pieces of request handling yourself.

Incase you haven't seen it already, you can implement a callback in `JSB`, so you can effectively implement `async` operations. https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.Example/BoundObject.cs#L43

**Comment by amaitland** [comment]
Any follow up on this? Happy to close?

**Comment by Paulo-Faustino** [comment]
Yes please, sorry that I forgot to reply, your help is much appreciated.
Thanks a lot!

**Comment by amaitland** [comment]
Great :smile:
