### ISSUE TITLE
DropDowns are not working when WPF control initial size is very small

### ISSUE THREAD

**Issue by arsher** [cefsharp/CefSharp#1174]
When the WPF control is created with small size, say 100x100 the dropdowns are either very small or not working at all even after resizing.

By looking at the CEF code I believe it's related to the fact that it falls back to the value provided by  `CefRenderHandler::GetViewRect` to determine max popup sizes when `CefRenderHandler::GetRootScreenRect` is not implemented. I experimented with returning some big enough adhoc value from `GetRootScreenRect` and it indeed solved the issue. However I'm not sure what would be the valid value there. Cefclient uses the parent window size but that solution applied to here again seems to fail with the same problem as `GetRootScreenRect` doesn't get called after resizing. Currently I've just put in the size of my entire desktop but I'm pretty sure this is not the best solution. What do you think?

**Comment by amaitland** [comment]
> Currently I've just put in the size of my entire desktop but I'm pretty sure this is not the best solution.

I like that's probably correct when implementing `GetRootScreenRect`

http://magpcss.org/ceforum/viewtopic.php?f=6&t=12835&p=25519&hilit=GetRootScreenRect#p25519

There is an old `PR`, which adds an implementation of `GetRootScreenRect`, it's related to `High DPI` support, long way from being ready for merge though.
https://github.com/cefsharp/CefSharp/pull/937/files#diff-abed174f3903eb62b98999938e4f67d0R83

**Comment by arsher** [comment]
Interesting, so this seems like the right approach then. I've added a small PR for this: #1175

**Comment by amaitland** [comment]
> // The |rect| and |available_rect| properties are used to determine the
>  // available surface for rendering popup views.

http://magpcss.org/ceforum/apidocs3/projects/%28default%29/_cef_screen_info_t.html#available_rect

The other option appears to be setting the `available_rect` for `GetScreenInfo` may also be worth trying. `CEF`.

> The |parent| value will be used to identify
>  // monitor info and to act as the parent window for dialogs, context menus,
>  // etc.

`SetAsWindowless` says it will use the `parent` handle to determine some information, so it's supposed to work out some of that by it's self......

**Comment by amaitland** [comment]
@arsher Do you have a sample URL to use for testing this?

I've just tried http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select 

I set the initial `Window` size to `100x100`, had to resize it a bit before I could use the actual browser, after loading the above URL it appeared to work correctly. Tried with latest `master`, https://github.com/cefsharp/CefSharp/commit/36bf1c5c58d17977ec71637ee2f42e18ae2dd835

**Comment by amaitland** [comment]
@arsher Any update?

**Comment by arsher** [comment]
Sorry I forgot to check back on this. I took branch 43 for a spin and it seems to be alright now. I think this can be closed, also I don't think we need the PR either, will close that too.

**Comment by amaitland** [comment]
Great, thanks :+1:
