### ISSUE TITLE
What does IrenderWebBrowser.SetCursor handle contain?

### ISSUE THREAD

**Issue by Dia6lo** [cefsharp/CefSharp#1176]
I'm talking about IRenderWebBrowser.SetCursor(IntPtr handle, CefCursorType type). I saw that in WPF browser it's passed into .NET's SetCursor as SafeHandle, but what data is in it?

**Comment by amaitland** [comment]
For some background see https://github.com/cefsharp/CefSharp/issues/1042#issuecomment-104132458

I believe it's a `HCURSOR` under windows.

**Comment by Dia6lo** [comment]
Ah, I forgot to tell my intentions: in OpenTK there is public MouseCursor(int hotx, int hoty, int width, int height, IntPtr data), and I tried to adapt your handle to this constructor.

**Comment by amaitland** [comment]
I'm not sure what your asking.....

the `IntPtr handle` is a pointer to a data structure, on windows that's a `HCURSOR`, which `WPF` knows how to load. No idea about `OpenTK`

**Comment by Dia6lo** [comment]
Yep, feels like OpenTk can't handle this handle (haha, get it?). Thanks for the answer.

**Comment by amaitland** [comment]
I don't really know anything about `OpenTK`, a quick search for `opentk HCURSOR` and there are internal code references.

https://github.com/mono/opentk/blob/master/Source/OpenTK/Platform/Windows/API.cs#L837

So I'm guessing there would be a way to convert `HCURSOR` into whatever structure they're expecting.

Are you still targeting `Windows`?

**Comment by Dia6lo** [comment]
Erm, I guess the original repository of OpenTK is here (as it is on official site):
https://github.com/opentk/opentk
And not there (as in your link):
https://github.com/mono/opentk/

**Comment by Dia6lo** [comment]
Yep, at mono/opentk they wrote: "Please do not contribute changes here, contribute them to the upstream maintainers at"

**Comment by Dia6lo** [comment]
Anyway, officially OpenTK don't support changing to any system cursor (except to default one).

**Comment by amaitland** [comment]
> Yep, at mono/opentk they wrote: "Please do not contribute changes here, contribute them to the upstream maintainers at http://www.opentk.com http://www.opentk.com"

Just what google returned as a search result.
