### ISSUE TITLE
Feature Request - Distinguish between console.log and console.error in ConsoleMessage event

### ISSUE THREAD

**Issue by JohnHardy** [cefsharp/CefSharp#1178]
I'm not sure this is supported by CEF3 at this stage, but it would be useful to tell the difference between console.info and console.error messages. 

IWebBrowserInternal.OnConsoleMessage.

[Please label this as a feature request ]

**Comment by amaitland** [comment]
You'd be better making your request `upstream`. 

There's a forum for that, see http://magpcss.org/ceforum/viewforum.php?f=7&sid=459179b62a122776b68a7b0a459eb953

We currently only expose what `CEF` currently provides.
https://bitbucket.org/chromiumembedded/cef/src/9e0d84d94af8acc5b7af0ee13218c2ed9ba4a021/include/cef_display_handler.h?at=master#cef_display_handler.h-110

**Comment by JohnHardy** [comment]
Done, thanks!

**Comment by amaitland** [comment]
If `CEF` ever implements this functionality we can reopen this.
