### ISSUE TITLE
Flash plugin instance of CefSharp.BrowserSubprocess.exe get crashed 

### ISSUE THREAD

**Issue by rover886** [cefsharp/CefSharp#1179]
I am developing a application using cefsharp version 37.0.1.0 (WinForms). Application is working so fine but while testing I observed very strange behavior of application, whenever there is a webpage which contains  an flash content the flash plugin get crashed after sometime of rendering flash content.

Later while searching why this is happening I observed that an process with name `CefSharp.BrowserSubprocess.exe` is getting crashed. Flash plugin keep crashing when I tried browsing flash content sites In cefsahrp master version 37. 

Following things I tried but no success

Disabling hardware acceleration.
Installing/re-installing flash plugin and player (latest version).
Tried with latest cefsharp master version 41.

I tried with upstream and it's working fine where I am doing wrong?

Process command line as below:

![github](https://cloud.githubusercontent.com/assets/8499500/9143086/adbe4780-3d61-11e5-8e18-d1b8e0dd26db.png)

**Comment by amaitland** [comment]
`WinForms`, or `WPF`?

**Comment by rover886** [comment]
@amaitland Sorry I forget to mention this, I am using `WinForms`

**Comment by amaitland** [comment]
Hmm, `WinForms` support for flash is usually pretty rock solid.

> flash plugin get crashed after sometime of rendering flash content.

What sort of time period are we talking here?

Any chance you can take `master` for a spin? It's an ever new build of `CEF`

**Comment by rover886** [comment]
@amaitland, the flash file total length is of 90 seconds and in cefsharp flash get played is of only 1-2 seconds (just a glimpse of first frame). While digging I found this info through event viewer.

Version=1
EventType=APPCRASH
EventTime=130835132352726466
ReportType=2
Consent=1
UploadTime=130835132353086487
ReportIdentifier=51abf441-3dcf-11e5-af3b-38607750fa8c
IntegratorReportIdentifier=51abf440-3dcf-11e5-af3b-38607750fa8c
Response.BucketId=25440044
Response.BucketTable=25
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=CefSharp.BrowserSubprocess.exe
Sig[1].Name=Application Version
Sig[1].Value=37.0.0.0
Sig[2].Name=Application Timestamp
Sig[2].Value=549256a5
Sig[3].Name=Fault Module Name
Sig[3].Value=ntdll.dll
Sig[4].Name=Fault Module Version
Sig[4].Value=6.1.7601.17514
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=4ce7b96e
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=00052d37
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=6.1.7601.2.1.0.256.4
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=0a9e
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=0a9e372d3b4ad19135b953a78882e789
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=0a9e
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=0a9e372d3b4ad19135b953a78882e789
UI[2]=C:\Program Files\Default\ClientApp\CefSharp.BrowserSubprocess.exe
UI[3]=CefSharp.BrowserSubprocess has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\Program Files\Default\ClientApp\CefSharp.BrowserSubprocess.exe
LoadedModule[1]=C:\windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\windows\SYSTEM32\MSCOREE.DLL
LoadedModule[3]=C:\windows\system32\KERNEL32.dll
LoadedModule[4]=C:\windows\system32\KERNELBASE.dll
LoadedModule[5]=c:\program files\net protector 2014\Zvfort32.dll
LoadedModule[6]=C:\windows\system32\SHLWAPI.dll
LoadedModule[7]=C:\windows\system32\GDI32.dll
LoadedModule[8]=C:\windows\system32\USER32.dll
LoadedModule[9]=C:\windows\system32\LPK.dll
LoadedModule[10]=C:\windows\system32\USP10.dll
LoadedModule[11]=C:\windows\system32\msvcrt.dll
LoadedModule[12]=C:\windows\system32\ADVAPI32.dll
LoadedModule[13]=C:\windows\SYSTEM32\sechost.dll
LoadedModule[14]=C:\windows\system32\RPCRT4.dll
LoadedModule[15]=C:\windows\system32\OLEAUT32.dll
LoadedModule[16]=C:\windows\system32\ole32.dll
LoadedModule[17]=C:\windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_50934f2ebcb7eb57\MSVCR90.dll
LoadedModule[18]=C:\windows\system32\IMM32.DLL
LoadedModule[19]=C:\windows\system32\MSCTF.dll
LoadedModule[20]=C:\windows\system32\WINSTA.dll
LoadedModule[21]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscoreei.dll
LoadedModule[22]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
LoadedModule[23]=C:\windows\system32\MSVCR100_CLR0400.dll
LoadedModule[24]=C:\windows\assembly\NativeImages_v4.0.30319_32\mscorlib\f014b1f34734c93956924e68c67ecb55\mscorlib.ni.dll
LoadedModule[25]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\nlssorting.dll
LoadedModule[26]=C:\windows\system32\CRYPTBASE.dll
LoadedModule[27]=C:\windows\system32\CRYPTSP.dll
LoadedModule[28]=C:\windows\system32\rsaenh.dll
LoadedModule[29]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\clrjit.dll
LoadedModule[30]=C:\Program Files\Default\ClientApp\CefSharp.BrowserSubprocess.Core.dll
LoadedModule[31]=C:\Program Files\Default\ClientApp\MSVCP110.dll
LoadedModule[32]=C:\Program Files\Default\ClientApp\MSVCR110.dll
LoadedModule[33]=C:\Program Files\Default\ClientApp\libcef.dll
LoadedModule[34]=C:\windows\system32\PSAPI.DLL
LoadedModule[35]=C:\windows\system32\WINSPOOL.DRV
LoadedModule[36]=C:\windows\system32\COMDLG32.dll
LoadedModule[37]=C:\windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.17514_none_41e6975e2bd6f2b2\COMCTL32.dll
LoadedModule[38]=C:\windows\system32\SHELL32.dll
LoadedModule[39]=C:\windows\system32\WINHTTP.dll
LoadedModule[40]=C:\windows\system32\webio.dll
LoadedModule[41]=C:\windows\system32\USERENV.dll
LoadedModule[42]=C:\windows\system32\profapi.dll
LoadedModule[43]=C:\windows\system32\urlmon.dll
LoadedModule[44]=C:\windows\system32\WININET.dll
LoadedModule[45]=C:\windows\system32\iertutil.dll
LoadedModule[46]=C:\windows\system32\CRYPT32.dll
LoadedModule[47]=C:\windows\system32\MSASN1.dll
LoadedModule[48]=C:\windows\system32\dhcpcsvc.DLL
LoadedModule[49]=C:\windows\system32\WS2_32.dll
LoadedModule[50]=C:\windows\system32\NSI.dll
LoadedModule[51]=C:\windows\system32\WTSAPI32.dll
LoadedModule[52]=C:\windows\system32\Secur32.dll
LoadedModule[53]=C:\windows\system32\SSPICLI.DLL
LoadedModule[54]=C:\windows\system32\IPHLPAPI.DLL
LoadedModule[55]=C:\windows\system32\WINNSI.DLL
LoadedModule[56]=C:\windows\system32\OLEACC.dll
LoadedModule[57]=C:\windows\system32\WINMM.dll
LoadedModule[58]=C:\windows\system32\VERSION.dll
LoadedModule[59]=C:\windows\system32\SETUPAPI.dll
LoadedModule[60]=C:\windows\system32\CFGMGR32.dll
LoadedModule[61]=C:\windows\system32\DEVOBJ.dll
LoadedModule[62]=C:\windows\assembly\NativeImages_v4.0.30319_32\System\6783353a6277418227e5b0e5a043049e\System.ni.dll
LoadedModule[63]=C:\windows\assembly\NativeImages_v4.0.30319_32\System.Core\9f0b6b22e726b112ba814c628b85e6c7\System.Core.ni.dll
LoadedModule[64]=C:\Program Files\Teamviewer\Version4\tv.dll
LoadedModule[65]=C:\windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.7601.17514_none_ec83dffa859149af\COMCTL32.dll
LoadedModule[66]=C:\windows\system32\uxtheme.dll
LoadedModule[67]=C:\windows\system32\dwmapi.dll
LoadedModule[68]=C:\windows\system32\Macromed\Flash\NPSWF32_18_0_0_209.dll
LoadedModule[69]=C:\windows\system32\DSOUND.dll
LoadedModule[70]=C:\windows\system32\POWRPROF.dll
LoadedModule[71]=C:\windows\system32\DINPUT8.dlla
LoadedModule[72]=C:\windows\system32\mscms.dll
LoadedModule[73]=C:\windows\system32\credssp.dll
LoadedModule[74]=C:\windows\system32\schannel.DLL
LoadedModule[75]=C:\windows\system32\CLBCatQ.DLL
LoadedModule[76]=C:\windows\System32\MMDevApi.dll
LoadedModule[77]=C:\windows\System32\PROPSYS.dll
LoadedModule[78]=C:\windows\system32\NcAudEP.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
State[1].Key=DataRequest
State[1].Value=Bucket=25440044/nBucketTable=25/nResponse=1/n
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=CefSharp.BrowserSubprocess
AppPath=C:\Program Files\Default\ClientApp\CefSharp.BrowserSubprocess.exe

I am not getting one thing if cef si able to find `NPSWF32_18_0_0_209.dll` then why it's getting crashed.?

**Comment by amaitland** [comment]
Do other flash videos play correctly?

The advantage with trying `master` out is it supports the new `PPAPI` plugin, so you can try `Pepper Flash`, which is what google chrome uses it's self.

**Comment by rover886** [comment]
@amaitland 

>> Do other flash videos play correctly?

No, I tired so many sites which is having flash videos,games but every time behavior is same.

Ok, I will try with `master` but I already tried with version [41.0.1](https://github.com/cefsharp/CefSharp/tree/v41.0.1). Is this different from `master`?

**Comment by amaitland** [comment]
> https://github.com/cefsharp/CefSharp/tree/v41.0.1. Is this different from master?

`41` is the current release branch, which is based on `Chromium 41`, where as `master` is based on `Chromium 43`.

By default `NPAPI` is disabled in `43`, so you'll have to enable it or use `Pepper Flash`.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/CefExample.cs#L54

Have you tried on different hardware? Far as I know basic flash is working.

**Comment by rover886** [comment]
@amaitland After extensive testing on windows 2K3, XP, Vista, Win 7 and Win 8 here is the result:
>Have you tried on different hardware? 

In my question or previous post I forget to mention that I am testing cefsharp winforms (version 37 and 41) on [nComputing](http://www.ncomputing.com/) setup. 
@amaitland after your last comment (Have you tried on different hardware?) I tested same version on standalone machines with all windows mentioned above and I found it's working fine :) and as you said I downloaded `master` which is based on `Chromium 43` and I again tested on nComputing with all windows mentioned above and it's working fine with  `Pepper Flash` (PPAPI) and NPAPI. Why I am considering because our 90% clients have [nComputing](http://www.ncomputing.com/) setup. So..

is there any specific reason why version (version 37 and 41) are not working on nComputing?
As `41` is released version and `43` is under development, so can I use `Pepper Flash` in `41`?

**Comment by amaitland** [comment]
> is there any specific reason why version (version 37 and 41) are not working on nComputing?

I'm not familiar with `nComputing` so I can't really pass any comment there. 

> As 41 is released version and 43 is under development, so can I use Pepper Flash in 41?

Unfortunately no, `Pepper Flash` is only available in the `2357` branch and newer. The underlying `CEF` version is `stable`, it's just the `CefSharp` `API` has undergone a huge rewrite. I'll likely package the first `43-pre` version this week.

@jankurianski Did you end up using a version based on `master` in your application?

**Comment by jankurianski** [comment]
Yes, I'm using a `master` version of `WinForms` and `OffScreen` in my application, configured with `WcfEnabled = false`.  No problems so far.
