### ISSUE TITLE
Two Questions before i dive into CEFSharp

### ISSUE THREAD

**Issue by Healian** [cefsharp/CefSharp#1180]
1- Does cefsharp support SetCookies from a CookieContainer (Web Control Specific)?
2- Does it support setting custom proxy for a web control or not ?

**Comment by amaitland** [comment]
> Does cefsharp support SetCookies from a CookieContainer (Web Control Specific)?

Can you be more specific? What exactly are you trying to achieve?

> Does it support setting custom proxy for a web control or not ?

What exactly is a `web control`? `CefSharp` supports providing a custom proxy

**Comment by amaitland** [comment]
For reference there are a number of cookie related methods, most of which reside in the `Cef` class.

https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.Core/Cef.h#L328

**Comment by amaitland** [comment]
Any follow up on this? Happy to close?
