### ISSUE TITLE
Window scrolls too much with mouse wheel

### ISSUE THREAD

**Issue by makkesk8** [cefsharp/CefSharp#1182]
When scrolling, you scroll too much, this was fixed in chromium embedded but not in cefsharp (winforms), seems to be working in wpf however. Link to fixed issue @ chromiumembedded below.

https://bitbucket.org/chromiumembedded/cef/issues/1481/windows-2171-window-scrolls-too-much-with

**Comment by jankurianski** [comment]
This will be fixed soon on CefSharp `master` as I will integrate the latest `2357`-branch CEF build that includes this fix.  Shortly afterwards there will by a continuous integration package available on MyGet.  However it will be a while before there is a proper NuGet release with this fix as there is lots of work to do for CefSharp's `43` milestone: https://github.com/cefsharp/CefSharp/milestones/43.0.0

**Comment by jankurianski** [comment]
@makkesk8 CefSharp `master` is now using the fixed CEF version.  Could you see if your issue is fixed?  You can either build from source or use the latest `CI`-marked packages from `https://www.myget.org/F/cefsharp/`

**Comment by amaitland** [comment]
As `master` has been updated, closing. If problem still exists please reopen.
