### ISSUE TITLE
Next Official Release - Feedback Welcome

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#1183]
The work on `master` is progressing, though still a little ways away from being release ready. I think we can likely push out a `-pre` package sometime this week though the `API` will likely change before the official release.

What would people prefer?
- A `43.0.0` maintenance release, basically upgrading the `41` branch to use a newer `CEF` version, minimal changes, should be stable and can likely push out a new release version in the next one/two weeks. The changes on `master` will then slip to being the `45` release.
- Keep the `43.0.0` release based on `master`, which will likely delay an official release by 1-2 months

Thoughts?

**Comment by ray007** [comment]
There are several issues marked "upstream", so it would seem to me moving sooner to version 43 is a good idea.

**Comment by amaitland** [comment]
The `API` rewrite has some pretty compelling features also

- Access to the underlying `CefBrowser` and `CefFrame` objects (major win in my opinion).
- `Async` callbacks
- Native `IPC` used for `EvaluateScriptAsync`
- Much better support for popups (previously a lot of functionality wasn't accessible)
- Async `ResourceHandler` support
- Ability to use `RequestContext's` to isolate browser instances.

Full list of merged `PR's` https://github.com/cefsharp/CefSharp/issues?q=milestone%3A43.0.0+is%3Aclosed

**Comment by martijn189** [comment]
I would also like to vote for a 43 release, our project could really use a new version of CEF because of a memory leak. As i am not a C# developer i cannot debug this myself, i can only see that the test application of CEF does not have this issue, so i assume that if CEFSharp would build against new CEF that our problems would disappear.

**Comment by amaitland** [comment]
Short term I've created https://github.com/cefsharp/CefSharp/tree/cefsharp/43

@jankurianski @rassilon @jornh Any comments on a direction?

Will wait a few days before making a final call on this one :smile:

**Comment by jankurianski** [comment]
Personally I am happy with the API changes so I think it is less work to push ahead with `master`.  Anyone wanting `43` can use a CI build.  Sure, the `master` API is not stable yet, but the functionality is.

**Comment by martijn189** [comment]
@jankurianski, for me personally it is not clear how to use those CI nightly build, we are using NuGet for example, and these CI build are for another package manager. I cannot find good examples on how to use that in a VS project.

**Comment by amaitland** [comment]
> Personally I am happy with the API changes so I think it is less work to push ahead with master. Anyone wanting 43 can use a CI build. Sure, the master API is not stable yet, but the functionality is.

Personally this is my preference also. Have to bite the bullet at some point, may as well be now.

> The availible NuGet version of cef.redist.x86 is: 3.2357.1287. Is there an archive or solution for this?

You'll need to use a newer `CI` build, as it's recently been upgraded and the old `cef` packages were removed yesterday. Try `v43.0.0-CI1350`

https://www.myget.org/gallery/cefsharp

**Comment by martijn189** [comment]
Still not working sorry, when i install cefsharp.winforms (43.0.0-c11350) it depends on .common, which depends on redist version 3.2357.1274, that package is not availible. The only redist is 3.2357.1287

Please advice

**Comment by amaitland** [comment]
The `build` script hadn't been updated (the upgrade to `1287` literally happened yesterday)

https://github.com/cefsharp/CefSharp/commit/eabc5e5c6cd446f24bfb4738196ea7781d1d50b8

New packages should be up shortly, I'll try them when I get a second. Should be resolved.

**Comment by martijn189** [comment]
Now i can install the packages, only problem now is that Visual Studio complaints that there is no way to resolve a reference.... I noticed this every time i updated CEFsharp, something to do with eferences, but do not know how to easyally fix it.

**Comment by amaitland** [comment]
Most issues arise because the old `MsBuild` nuget restore method doesn't play nicely with the mixed mode assemblies.

http://blog.davidebbo.com/2014/01/the-right-way-to-restore-nuget-packages.html

The `powershell` script I use to migrate to the newer method can be found at https://github.com/owen2/AutomaticPackageRestoreMigrationScript#migatetoautomaticpackagerestoreps1

**Comment by martijn189** [comment]
@amaitland After doing this i am getting new errors in VS like: `ChromiumWebBrowser is ambiguous in the namespace 'CefSharp.WinForms`. In my VB form i have:

`Private WithEvents ChromiumWebBrowser As ChromiumWebBrowser`

Did i miss somethign that needs to be changed in this new build?

**Comment by amaitland** [comment]
> So sorry for hijacking this ticket, i cannot find PM feature and i did not want to open a new issue for this.

There is no `PM` feature. Just create a new issue. The main class is still called `ChromiumWebBrowser`, lots of stuff has changed in this build though. Not sure the reason for the ambiguous reference. Can't say that I know `VB.Net`...

**Comment by amaitland** [comment]
I think in the interest of moving the project forward I'm going to release a `43-pre` version based on `master`. I just committed a large number of `API` changes including some new features. Hopefully the `API` is now fairly stable and only a few minor changes made before the official release.

**Comment by jankurianski** [comment]
Nice one :+1: 

I have updated https://github.com/cefsharp/CefSharp/wiki/ChangeLog with breaking changes that I know of, and where possible upgrade tips and examples of new usage where it is significantly different.

**Comment by amaitland** [comment]
Fantastic thanks :+1: I'll review the `PR's` tagged with `breaking-change` later and see what I can add.

**Comment by amaitland** [comment]
I've tagged the `-pre` package, will test it out with the `MinimalExample`. Probably push to `nuget.org` in the next day or two.

**Comment by amaitland** [comment]
I deleted the `-pre` packages and created new ones as I missed implementing `OnOpenURLFromTab`.

I've created a new `MinimalExample` branch https://github.com/cefsharp/CefSharp.MinimalExample/tree/cefsharp/43

Everything appears to be working, so I guess we can push to `nuget.org` shortly.

**Comment by amaitland** [comment]
I've pushed the packages to `nuget.org`, will be a little while before their appear in `VS` as they still need to be indexed apparently.
