### ISSUE TITLE
System.IO.FileLoadException A procedure imported by 'CefSharp.Core.dll' could not be loaded

### ISSUE THREAD

**Issue by canton7** [cefsharp/CefSharp#1184]
Hi,

A user's seeing the following error:

```
An unhandled exception occurred System.IO.FileLoadException A procedure imported by 'CefSharp.Core.dll' could not be loaded. Void GetSignature(Void*, Int32, System.RuntimeFieldHandleInternal, System.IRuntimeMethodInfo, System.RuntimeType)
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Signature..ctor(IRuntimeFieldInfo fieldHandle, RuntimeType declaringType)
<my code>
```

The interesting thing is that it worked successfully at least once, but started hitting this error after a reboot. It now hits it on every start, even after a re-install. The Visual Studio C++ 2012 Redistributable DLLs are included in the same folder as the app (the folder which also contains CEF and CefSharp). I've checked the contents of that folder, and it isn't a case of an anti-virus program stealing away some of CEFs files either.

Any ideas? Any other information which might help?

Thanks!

**Comment by Suwmlee** [comment]
Hello. maybe you can use ' cff explorer' or ' depends ' to find out what is missing while loading CefSharp.Core.dll.

**Comment by canton7** [comment]
Worth doing, thanks! I've added instructions, and will report back when I've got some results.

**Comment by canton7** [comment]
Apart from a load of API-MS-WIN-* stuff, nothing seems to be missing. I ran dependency walker on a similar machine which had no problems, and a similar list of API-MS-WIN-* dlls were missing, so I think they're a bit of a red herring. 

The dependency walker output from the borked machine is here: https://gist.github.com/Aeyoun/ece72beee5b5e1304a7e

**Comment by canton7** [comment]
Everything magically fixed itself on the user's machine after a reboot, suggesting that a windows update may have broken something, then another fixed it?

Closing this off anyway.

**Comment by canton7** [comment]
This has re-appeared in canton7/SyncTrayzor#137. Re-opening, and will update if I get any more useful debug info.

**Comment by canton7** [comment]
Looks like this one was caused by a process called HydraVisionDesktopManager, a pieceof software which ATI (used to?) distribute with their graphics card drivers. Another bit of knowledge to stash away into the bank...

**Comment by amaitland** [comment]
Thanks for the status update :+1:

**Comment by hpposch** [comment]
Hi.. 
I have the same problem at the moment.
How did you fix this?

**Comment by canton7** [comment]
Your issue is also caused by HydraVisionDesktopManager? I believe the user uninstalled HydraVisionDesktopManager

**Comment by robinwassen** [comment]
One of our users has reported this problem on multiple Lenovo Thinkpad T410, at the same time the user is able to install and run the application without errors on other identical machines. The machines uses Intel/Nvidia for graphics, so it is not probable that it is related to the HydraVisionDesktopManager.

We do not have access to the machines that are affected, but we will keep trying to debug this issue remotely.

CefSharp version: 43.0.0

@amaitland You might want to re-open this issue since it still seems to be a problem.

**Comment by amaitland** [comment]
> @amaitland You might want to re-open this issue since it still seems to be a problem.

@robinwassen See #1841
