### ISSUE TITLE
silent crash due to kernelbase.dll

### ISSUE THREAD

**Issue by Remo** [cefsharp/CefSharp#1185]
I've created a fresh project of CefSharp.MinimalExample.WinForms, set everything to release and x86. Works fine on my computer, but on my customers computer it crashes silently and only reports two entries in the event log.

First entry:
```
Application: CefSharp.MinimalExample.WinForms.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
Stack:
   at CefSharp.MinimalExample.WinForms.Program.Main()
```

Second entry:
```
Faulting application name: CefSharp.MinimalExample.WinForms.exe, version: 1.0.0.0, time stamp: 0x55c9f3c8
Faulting module name: KERNELBASE.dll, version: 6.1.7601.23049, time stamp: 0x554d9e4a
Exception code: 0xe0434352
Fault offset: 0x0000c44d
Faulting process id: 0x2104
Faulting application start time: 0x01d0d43700b77650
Faulting application path: E:\Release\CefSharp.MinimalExample.WinForms.exe
Faulting module path: C:\Windows\syswow64\KERNELBASE.dll
Report Id: 3f836aeb-402a-11e5-9f77-f0def1004f71
```

.NET framework 4.0 is installed.. Not really sure how to fix that, any feedback appreciated! Thanks

**Comment by Remo** [comment]
I also monitored the file access, here's the output of process monitor http://www.wish.town/Logfile.zip

**Comment by Remo** [comment]
turns out that computer didn't have the x86 version of msvcp110.dll
Had to install this http://www.microsoft.com/en-gb/download/confirmation.aspx?id=30679

Any chance we could have a slightly nicer error there?

**Comment by amaitland** [comment]
> Any chance we could have a slightly nicer error there?

Error is generated by `.Net` when attempting to load the `VC++` component. If you know of a way to handle this is a nicer fashion, open to suggestions.

**Comment by dana-p** [comment]
Make sure you have the Visual C++ Redistributable Package for VS 2013 installed. https://www.microsoft.com/en-ca/download/details.aspx?id=40784

That's what worked for me, in the end :)

**Comment by sagopalm** [comment]
@dana-p Thank you - it solved my problem!
