### ISSUE TITLE
Hotkeys Cefsharp 

### ISSUE THREAD

**Issue by Sential** [cefsharp/CefSharp#1186]
Hello, how to make hotkeys in cefsharp? My code doesn't work:
        If e.Control AndAlso e.KeyCode = Keys.X AndAlso e.Modifiers = Keys.Alt Then
            webcontrol1.Load("www.google.com/")
            e.Handled = False
        End If

I'm using WinForms and VB.NET

**Comment by amaitland** [comment]
You can implement `IKeyboardHandler`

https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp/IKeyboardHandler.cs#L30

**Comment by Sential** [comment]
Yes i tried that but i don't know how to use this. Can you give me sample code, how to check keydown?

**Comment by amaitland** [comment]
I don't have a simple example to give you. The `WinForms.Example` project has a rather complicated example https://github.com/cefsharp/CefSharp/blob/master/CefSharp.WinForms.Example/Handlers/KeyboardHandler.cs#L10

> how to check keydown

Dig a little deeper and you'll find the information is there.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp/KeyType.cs

**Comment by amaitland** [comment]
Get a working solution? Can we close this?

Also might be helpful to others if you can post a code snippet if you have something working.
