### ISSUE TITLE
Ambiguous in the namespace after upgrade to 43 CI Nuget

### ISSUE THREAD

**Issue by martijn189** [cefsharp/CefSharp#1188]
When using the nuget packages to update a project that was using the stable CEFSharp to the latest CI build of the 43 alpha many things break in the vb.net project. CEFSharp 43 must provide a much better access to the underlying CEF API and as such there are many changes over version 39.

There is a document on <a href="https://github.com/cefsharp/CefSharp/wiki/CefSharp-43-(Alpha)">the Wiki</a> that will proberbly be filled with useful upgrade information, however, at this point there is no information and i am stuck.

Could someone explain to us how to upgrade a project from 41 to 43? In my case i have a vb.net application based on the examples. After upgrading i get compuile errors such as:

'ChromiumWebBrowser' is ambiguous in the namespace 'CefSharp.WinForms'.
'CefSettings' is ambiguous in the namespace 'CefSharp'
'LogSeverity' is ambiguous in the namespace 'CefSharp'.
'Cef' is ambiguous in the namespace 'CefSharp'.
'IDownloadHandler' is ambiguous in the namespace 'CefSharp'.
'DownloadItem' is ambiguous in the namespace 'CefSharp'.

**Comment by amaitland** [comment]
What steps have you tried so far?

If you haven't already try something like
- Clean solution
- Remove package
- Delete all the `bin/obj` directories (I'd typically close visual studio and ask `git` to perform a cleanup, deleting all unversioned files)
- Install fresh copies of the nuget packages

**Comment by amaitland** [comment]
I've just upgraded the `MinimalExample` project to use `CI1351`, everything went according to plan.

https://github.com/cefsharp/CefSharp.MinimalExample/commits/latest/ci

Steps I used
- Open Manage nuget packages for solution
- Select the `CefSharp MyGet` feed.
- Click `Update All`
- Close visual studio
- Manually edit `.csproj` files to remove the nuget msbuild taget
- Open `VS`
- Compile
- Fix compile errors due to new`API`
- Run

**Comment by martijn189** [comment]
That is my problem, "Fix compile errors due to newAPI", i really do not know how to fix it with. For example. The CEFsettings is no longer availible, it does not accept any settings like logseverity.

**Comment by amaitland** [comment]
> That is my problem, "Fix compile errors due to newAPI", i really do not know how to fix it with.

I don't actually think that's you problem. Usually it's VS not playing nice and you need to perform a full clean.

> For example. The CEFsettings is no longer availible, it does not accept any settings like logseverity.

Easy to check those things in the source code. `CefSettings` still exists, it's only had minor changes.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/CefSettings.h#L116

**Comment by martijn189** [comment]
OK i understand now, i opened my app.vbproj file and verry carefully read trough it, it had 7 lines of references like:

`    <Reference Include="CefSharp">
      <HintPath>..\..\..\..\Chromium 43\CEFSharp\CefSharp-master\CefSharp.WinForms.Example\bin\x86\Release\CefSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>`

Now it seems to work.... pfew :-)

**Comment by jornh** [comment]
Can this be closed then? If, then please do so ...
