### ISSUE TITLE
Dependency Check VC++

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#1189]
I'm not sure if it's possible to do reliable. If we got something that worked in 95% of cases I think that would help quite a bit. Rather than making it mandatory add it to the current `DependencyChecker`

http://stackoverflow.com/questions/12206314/detect-if-visual-c-redistributable-for-visual-studio-2012-is-installed

Needs further investigation.

**Comment by jankurianski** [comment]
There's another way to bundle the VC++ redist that I use in my app.  The directory structure looks like this:

```
C:\Program Files\MyApp\
  
    myapp.exe
    libcef.ddl
    ...

    Microsoft.VC90.CRT\

        Microsoft.VC90.CRT.manifest
        msvcm90.dll
        msvcp90.dll
        msvcr90.dll
```

**Comment by amaitland** [comment]
Were you thinking of including the `VC++` runtime as part of the nuget package?

**Comment by jankurianski** [comment]
No, just more that the detection code could cover this case as well.

But now that you say it, including the runtime would cut out a common source of errors and do away with the detection code...

**Comment by amaitland** [comment]
> No, just more that the detection code could cover this case as well.

Yeah, I was thinking we'd include that check to see if the runtime was included in the bin directory. I wasn't aware it could be in a sub directory.

> But now that you say it, including the runtime would cut out a common source of errors and do away with the detection code...

It would. Not sure what restrictions there are on distributing the runtime.

I think maybe add some additional checking, if that cuts down the number of problems then we leave it at that.

**Comment by amaitland** [comment]
Thoughts?

**Comment by jankurianski** [comment]
> Yeah, I was thinking we'd include that check to see if the runtime was included in the bin directory. I wasn't aware it could be in a sub directory.

Oops you're right there, I was looking at an older VC++ redist version that used `winsxs`, but Microsoft no longer use that.  We only have to worry about it being in the bin directory, like:

```
C:\Program Files\MyApp\
    myapp.exe
    libcef.dll
    vccorlib110.dll
    msvcr110.dll
    msvcp110.dll
    ...
```

I think a check of these files in the application bin directory or `%windir%\system32` would be enough for now like you say.

**Comment by Remo** [comment]
isn't this the same problem I had over here https://github.com/cefsharp/CefSharp/issues/1185 ?
As far as I can see it, the .NET process doesn't even start when those DLLs are missing..

**Comment by amaitland** [comment]
> isn't this the same problem I had over here #1185 ?

Not quite. We have no control over the error message that is throw. This is about adding some checks to our optional `DependencyChecker` class. We currently don't enforce dependency checking.

**Comment by amaitland** [comment]
Thanking about this further and we'd likely need to have a separate call on `DependencyChecker` as it couldn't be passed through the `Cef.Initialize` param option. So I think just a simple static method that checks if the files exist in the executing path or they're on disk in the default location. Also add a disclaimer that it may not work in all cases.

**Comment by jankurianski** [comment]
> Thanking about this further and we'd likely need to have a separate call on DependencyChecker as it couldn't be passed through the Cef.Initialize param option

Ah you're right... because the static initialization of the `Cef` class will try to load the `VC++` DLLs and crash before the dependencies can be checked.

**Comment by amaitland** [comment]
> Ah you're right... because the static initialization of the Cef class will try to load the VC++ DLLs and crash before the dependencies can be checked.

Unfortunately :frowning: An extra method to call is better than nothing I suppose.

**Comment by bjarteskogoy** [comment]
Worth telling somewhere that cef 45 needs a newer version of vc++ probably. Probably a breaking change for a lot.

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp#version-branches

Will also update the `nuget` readme, and `FAQ` at some point. As `45` is experimental at this stage, I'm not too worried, still need to get `43` out the door!

**Comment by amaitland** [comment]
I'd also like to upgrade to `.Net 4.5` at some point (It has been out for over 3 years now). I guess maybe `47`, so people get a little bit of notice.

**Comment by amaitland** [comment]
As we now use `VC++2015` and `MS` has improved things quite a bit I think we can make a little progress on this.

- [ ] Check Reg entry confirm that Major version is listed as 14 (Have to take into account `WOW64`)
- [ ] Validate dlls are in executing folder

https://docs.microsoft.com/en-gb/cpp/ide/redistributing-visual-cpp-files?view=vs-2017
https://stackoverflow.com/questions/46178559/how-to-detect-if-visual-c-2017-redistributable-is-installed

**Comment by amaitland** [comment]
https://github.com/bitbeans/RedistributableChecker is an existing library to check the registry. It's MIT licensed so we can adapt the code we need.

**Comment by amaitland** [comment]
https://github.com/bitbeans/RedistributableChecker/blob/master/RedistributableChecker/RedistributablePackage.cs

**Comment by amaitland** [comment]
Rather than reinventing the wheel I think I'm just going to recommend users pick one of the existing nuget packages.

- https://github.com/enclave-networks/mscversion
- https://github.com/bitbeans/RedistributableChecker
