### ISSUE TITLE
Installing CefSharp in Windows 10 64bit, visual studio 2015, from NuGet fails

### ISSUE THREAD

**Issue by rmacy** [cefsharp/CefSharp#1192]
When trying to install CefSharp via NuGet on Microsoft Windows 10, 64 Bit, Visual Studio 2015 community edition I experience the following failure:

```
Using source https://api.nuget.org/v3/index.json.
Restoring packages for UAP,Version=v10.0...
Resolving conflicts for UAP,Version=v10.0...
Scanning packages for runtime.json files...

...

Checking compatibility for Microsoft.NETCore.Platforms 1.0.0 with UAP,Version=v10.0 (win10-x64-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).
Package restore failed for 'PeanutButter'.
========== Finished ==========
```

Is CefSharp not compatible with VS15 or Windows 10 yet?

**Comment by amaitland** [comment]
> Is CefSharp not compatible with VS15 or Windows 10 yet?

Specifically `VS2015`. As each version of `VC++` is tied heavily with `VS`. `libcef_dll_wrapper.lib` needs to be compiled specifically. Currently there are builds for `VS2012` and `VS2013`. 

 #979 adds a basic hack to get `VS2015` working (I believe it requires you have `VS2013` installed as well).

**Comment by amaitland** [comment]
Sorry, my comments should be taken in the context of trying to build `CefSharp` from source on `VS2015`. So can be ignored.

**Comment by amaitland** [comment]
I'm not really familiar with `UAP` as yet. My guess is that if you tried it in a `WinForms` or `WPF` then it would install correctly.

At a guess you'd need to at least have `CefSharp` compiled for `VC++ 2015` (currently `VC++ 2012`). Likely more research is needed.

**Comment by amaitland** [comment]
Looks like changes to the `Nuget` packages maybe required also
http://firstfloorsoftware.com/news/win10-dev-msbuild-uwp-and-project.json

**Comment by amaitland** [comment]
https://msdn.microsoft.com/library/windows/apps/dn894631.aspx

> A UWP app or Windows Runtime Component written in C++/CX has access to the Win32 APIs that are part of the UWP. These Win32 APIs are implemented by all Windows 10 device families. Link your app with Windowsapp.lib. Windowsapp.lib is an "umbrella" lib that provides the exports for the UWP APIs. Linking to Windowsapp.lib will add to your app dependencies on dlls that are present on all Windows 10 device families.

So a `UAP` is similar to a `Windows Store` app? I wonder if `CEF` would actually run as it doesn't have full access to the `Win32` API?

**Comment by rmacy** [comment]
I see. It works with WPF, I seem to have lacked knowledge about UAP and selected an incompatible project type. Thanks for the note!

**Comment by amaitland** [comment]
> UWP Apps run in a protected environment, and as a result, many Win32, COM, and CRT API calls that might compromise the security of the platform are not allowed. The compiler can detect such calls and generate an error, if the /ZW option is used. You can use the App Certification Kit on your application to detect code that calls forbidden APIs.

[How to: Use Existing C++ Code in a Universal Windows Platform App
](https://msdn.microsoft.com/en-us/library/mt186162.aspx)
