### ISSUE TITLE
RegisterJsObject Hanging

### ISSUE THREAD

**Issue by Paulo-Faustino** [cefsharp/CefSharp#1193]
I'm still having issues when launching methods from JavaScript when using RegisterJsObject, the scenario is: Main Form page runs a JS code that triggers a function which launches a secondary form also containing a CEFSharp browser, when this happens the secondary form freezes and closes, sometimes the whole app closes too.

I removed the CefSharp browser from the secondary form but that didn't help, even without any components or any code at all on the second form it will freeze when called from the main from through a registered js object.

I'm going to show some simple code which I came up with to try to demonstrate, I also uploaded a sample project here: https://mega.nz/#!jdMADA6I!3WtRRn7p1zmVsrghrKKw7zDMiWggaovzaFvO-CU3cpw, it uses the NuGet packages but I deleted the folder from the zip to make it smaller, just restore them upon loading on Visual Studio.

I would appreciate if you could point me to the right direction here on how to use RegisterJsObject  correctly.

Thanks.

Main Form:

    public partial class FrmOne : Form
    {
        public static ChromiumWebBrowser BrowserCtl;
        WebInterface webInt;

        public FrmOne()
        {
            InitializeComponent();
        }

        private void FrmOne_Load(object sender, EventArgs e)
        {
            BrowserCtl = new ChromiumWebBrowser("http://www.google.com")
            {
                Dock = DockStyle.Fill
            };

            webInt = new WebInterface();
            webInt.OwnerForm = this;
            BrowserCtl.RegisterJsObject("WebInterface", webInt, true);
            this.Controls.Add(BrowserCtl);
        }

        private void btRunMsgScript_Click(object sender, EventArgs e)
        {
            BrowserCtl.ExecuteScriptAsync("WebInterface.doTaskOne();");
        }

        private void btRunWndScript_Click(object sender, EventArgs e)
        {
            BrowserCtl.ExecuteScriptAsync("WebInterface.doTaskTwo();");
        }

        public void ReceiveMessage(String msg)
        {
            MessageBox.Show("Received::" + msg);//Perfect
        }

        public void LaunchPopup()
        {
            FrmTwo newForm = new FrmTwo();
            newForm.Show();//Form shows and freezes then closes, sometimes the app freezes and closes
        }
    }

    public class WebInterface
    {
        public Form OwnerForm;

        public void doTaskOne()
        {
            ((FrmOne)OwnerForm).ReceiveMessage("Status Message");
        }

        public void doTaskTwo()
        {
            ((FrmOne)OwnerForm).LaunchPopup();
        }
    }

Secondary Form:

    public partial class FrmTwo : Form
    {
        public static ChromiumWebBrowser BrowserCtl;

        public FrmTwo()
        {
            InitializeComponent();
        }

        private void FrmTwo_Load(object sender, EventArgs e)
        {
            //Even removing the code bellow won't help, the form still freezes
            BrowserCtl = new ChromiumWebBrowser("http://www.google.com")
            {
                Dock = DockStyle.Fill
            };

            this.Controls.Add(BrowserCtl);
        }
    }

**Comment by amaitland** [comment]
Couple of house keeping things first (These are outlined in https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue)
- Prefer for people not to post large code blocks in issues, a `GIST` would be cleaner and allow for commenting inline
- When demonstrating a problem, it's also preferable to fork the `MinimalExample` project or provide your code in an open fashion. I personally won't download a zip file from an unknown source where possible.

https://github.com/cefsharp/CefSharp.MinimalExample

> FrmTwo newForm = new FrmTwo(); newForm.Show(

As for your code, I'd suggest trying to invoke this code on the `UI` thread

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.WinForms/Internals/ControlExtensions.cs#L17

**Comment by Paulo-Faustino** [comment]
Hi Alex, sorry for not reading the guidelines before posting code and sharing outside links.

As of your advise it worked perfectly, here's what I did:

    this.Invoke((MethodInvoker)delegate {
        FrmTwo newForm = new FrmTwo();
        newForm.Show();
    });

Again thank you so much and feel free to close this.

**Comment by amaitland** [comment]
> Hi Alex, sorry for not reading the guidelines before posting code and sharing outside links.

No problem, just for future reference :+1: 

> Again, thanks for the help and feel free to close this issue.

Great :smile:
