### ISSUE TITLE
Question: Network tab log

### ISSUE THREAD

**Issue by jonas-nordicfactory** [cefsharp/CefSharp#1195]
Hi

Is it possible to get a log of everything the browser downloads when visiting an url, i.e. the developer 
Network tab in chrome?

Preferably with offscreen if it's possible.

Thanks

**Comment by jankurianski** [comment]
You should be able to do this by implementing `IResourceHandler` and using `OnBeforeResourceLoad`.  There's an example here:
https://github.com/cefsharp/CefSharp/blob/25be7265f20d4a4651cd607cabe4cd6797c77169/CefSharp.Example/RequestHandler.cs

**Comment by amaitland** [comment]
Any follow up on this?

**Comment by jonas-nordicfactory** [comment]
Sorry for the delay, and yes I have been partially successful.
I can get a list of all the resources but I haven't been able to find any way of getting the size (most often gzip:ed) and the type of the resource (e.g. XHR, Script, Style etc) without needing to match mimetypes and downloading the file myself.

**Comment by amaitland** [comment]
> I can get a list of all the resources but I haven't been able to find any way of getting the size (most often gzip:ed)

Not sure about getting the size, if you dig through the `CEF API` you might find something.

> the type of the resource (e.g. XHR, Script, Style etc)

Only part of `CefRequest` is actually exposed, you would likely need to implement `GetResourceType()`

http://magpcss.org/ceforum/apidocs3/projects/%28default%29/CefRequest.html#GetResourceType%28%29
