### ISSUE TITLE
Something wrong when I embedded a gallery webpage(CefSharp.WPF)

### ISSUE THREAD

**Issue by metametametaphysics** [cefsharp/CefSharp#1198]
When I try to embed the juicebox gallery(http://www.juicebox.net/demos/lite/full/)
 in c# WPF, I found there was something wrong with this web page.

Origin screenshot(open this page in Chrome):
![first](https://cloud.githubusercontent.com/assets/13810207/9289209/4b2dafea-439a-11e5-9525-d825ba5fa265.png)

However ,when I embed this gallery to C# WPF by CefSharp.Wpf:

![second](https://cloud.githubusercontent.com/assets/13810207/9289210/4f6cd4d2-439a-11e5-8e56-7ca86461ec8f.png)
 there was something wrong happened!

Interestingly, when I use CefSharp.Winform, this page can be displayed correctly....

How can i fix this problem? thanks!

**Comment by amaitland** [comment]
What version are you using?

Need to check if the problem is related directly to `CefSharp` or is an upstream problem with `CEF`
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

**Comment by amaitland** [comment]
@metametametaphysics Were you able to reproduce the problem using the `cefclient` example?

**Comment by gsiry** [comment]
@metametametaphysics <https://github.com/metametametaphysics>  Do you get
any errors in the DevTools Console ( ShowDevTools() )

On Mon, Aug 17, 2015 at 11:41 PM, Alex Maitland <notifications@github.com>
wrote:

> @metametametaphysics <https://github.com/metametametaphysics> Were you
> able to reproduce the problem using the cefclient example?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cefsharp/CefSharp/issues/1198#issuecomment-132062583>.
>



-- 
Gaetan "G" Siry
twitter  - @gsiry
gvoice - 7815199201
mobile - 7819603668
Email  - gaetan.siry@gmail.com
Links :
https://geekli.st/avspeed
http://www.avspeed.com

**Comment by amaitland** [comment]
@metametametaphysics Were you able to debug the issue?

**Comment by amaitland** [comment]
Closing due to lack of feedback from OP.
