### ISSUE TITLE
How to get HtmlDocument?

### ISSUE THREAD

**Issue by looselive** [cefsharp/CefSharp#1199]
Like ie WebBrowser:
WebBrowser.Document.GetElementById(string id); 
I am a new user of CefSharp.
thanks!

**Comment by amaitland** [comment]
There is no direct access to the `DOM`.

You can either use `Javascript Binding` or simply execute some `javascript` directly.

https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#2-how-do-you-call-a-javascript-method-that-return-a-result
https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#3-how-do-you-expose-a-net-class-to-javascript

(In general, probably a good idea to read the `FAQ`)

**Comment by looselive** [comment]
It's not convenient, I found a Library named “EO.WebBrowser”, it seems pretty good

**Comment by amaitland** [comment]
Great!

**Comment by avspeed** [comment]
@looselive EO.WebBrowser is about $400 .. CefSharp is provided to you for free. Have a little appreciation for people'a hardwork that they provide to you for free ...
