### ISSUE TITLE
How to set Accept-Language?

### ISSUE THREAD

**Issue by looselive** [cefsharp/CefSharp#1200]
I want to add "Accept-Language" header to the request, I guess CefSharp default value is "es".
I'm a Chinese, I want to add "zh,zh-cn,zh-tw" for local people.
I was found some solution like
webView.RequestHandler = RequestHandler; 

    

```c#
public class RequestHandler : IRequestHandler  
{  
	public bool OnBeforeResourceLoad(IWebBrowser browser, IRequestResponse requestResponse)  
	{ 
		IDictionary<string, string> headers = requestResponse.Request.GetHeaders(); 
		headers.Add("Accept-Language", "zh,zh-cn,zh-tw"); 
		requestResponse.Request.SetHeaders(headers);         
		return false;  
	}  
}
```
But the new version is not supported.

I hope to give me a solution. Thank you.

**Comment by amaitland** [comment]
Same solution likely works, the `API` has likely changed.

https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp/IRequestHandler.cs#L50

**Comment by looselive** [comment]
##### My  code:
```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using CefSharp.WinForms;
using CefSharp;

namespace WindowsFormsApplication1
{
	class RequestHandler : IRequestHandler
	{
		public bool GetAuthCredentials(IWebBrowser browser, bool isProxy, string host, int port, string realm, string scheme, ref string username, ref string password)
		{
			return false;
		}

		public bool OnBeforeBrowse(IWebBrowser browser, IRequest request, bool isRedirect, bool isMainFrame)
		{
			return false;
		}

		public bool OnBeforePluginLoad(IWebBrowser browser, string url, string policyUrl, WebPluginInfo info)
		{
			return true;
		}

		public CefReturnValue OnBeforeResourceLoad(IWebBrowser browser, IRequest request, bool isMainFrame)
		{
			var headers = request.Headers;
			headers.Add("Accept-Language", "zh,zh-cn");
			Console.WriteLine("--------已经被执行---------");
			return CefReturnValue.Continue;
        }

		public bool OnCertificateError(IWebBrowser browser, CefErrorCode errorCode, string requestUrl)
		{
			return false;
		}

		public void OnPluginCrashed(IWebBrowser browser, string pluginPath)
		{
			
		}

		public void OnRenderProcessTerminated(IWebBrowser browser, CefTerminationStatus status)
		{
			 
		}
	}
}
```

That's right? But still not effective! Why?

**Comment by amaitland** [comment]
Headers is actually a shallow copy of the underlying `CEF` type, you have to reassign it after you make changes.

`request.Headers = headers;`

**Comment by looselive** [comment]
Thank you very much!

**Comment by amaitland** [comment]
No problem, if there's nothing further, please close this issue,

**Comment by frank-liu** [comment]
You should do like this  @looselive 
public CefReturnValue OnBeforeResourceLoad(IWebBrowser browserControl, IBrowser browser, IFrame frame, IRequest request, IRequestCallback callback)
        {
            //request.Headers["User-Agent"] = "CloudAshur Client";
            //request.Headers["Custom-Header"] = "7849";
            //Console.WriteLine("set header\n\n");

            //return CefReturnValue.Continue;

            var headers = request.Headers;
            headers.Add("Custom-Header", "XYZ");
            request.Headers = headers;
            return CefReturnValue.Continue;
        }

**Comment by frank-liu** [comment]
@looselive @amaitland 

public CefReturnValue OnBeforeResourceLoad(IWebBrowser browserControl, IBrowser browser, IFrame frame, IRequest request, IRequestCallback callback)
        { 
            //return CefReturnValue.Continue;

            var headers = request.Headers;
            headers.Add("Custom-Header", "MyClient");
            request.Headers = headers;
            return CefReturnValue.Continue;
        }
