### ISSUE TITLE
Downloading, Unzipping, Compiling in VS2013 Community issues 18 errors

### ISSUE THREAD

**Issue by AcousticGuitar** [cefsharp/CefSharp#1201]
Here's just a few, if I do what is suggested I cannot find "Upgrade Solution" anywhere.  Please advise.

Error	6	error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...".	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets	64	5	CefSharp.Core
Error	7	error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...".	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets	64	5	CefSharp.BrowserSubprocess.Core
Error	8	Metadata file 'C:\Users\John\Downloads\CefSharp-master\CefSharp-master\CefSharp.Core\bin\Debug\CefSharp.Core.dll' could not be found	C:\Users\John\Downloads\CefSharp-master\CefSharp-master\CefSharp.Example\CSC	CefSharp.Example

**Comment by Dinius** [comment]
In solution explorer, right click "CefSharp.Core" -> Properties -> "Platform toolset". It's trying to compile with a toolset you don't have installed. So first thing to try is to simply change that to one you HAVE installed, they should pop up in that list automatically.

http://i.imgur.com/HygGuRn.jpg

**Comment by amaitland** [comment]
At some point did you open the project in `VS2015`? `V140` Is the platform tools set for `VS2015`.

Try Reverting all changes to the project/solution and opening first in `VS2013`

**Comment by amaitland** [comment]
Closing due to lack of feedback from op.
