### ISSUE TITLE
Feature Request - Add Support for compiling with VS2015

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#1202]
Now that `VS2015` is officially out we can look at including support in the next major release. As `43` is well under way (`nuget` packages for `sdk` have already been generated) this will be pushed to the `45` release.

`2454` branch of `CEF` has some issues compiling under `2012` so support will be dropped. (Original plan was always to support `current` and `current-1` when it comes to `VS`)

**Comment by amaitland** [comment]
I've repackaged `2454` and build with `VS 2013` and `VS 2015`, hasn't been fully tested as yet.

Code is visible on my branch https://github.com/amaitland/CefSharp

**Comment by jankurianski** [comment]
Cool!  I'm excited about the new `2454` version.  Did you build the `sdk` packages that are on `MyGet` with `VS 2013` or `VS 2015`?

**Comment by amaitland** [comment]
> Did you build the sdk packages that are on MyGet with VS 2013 or VS 2015?

Should have `libcef_dll_wrapper.lib` build for both `VS2013` and `VS2015`, removed `VS2012` as it doesn't build anymore. I haven't done much testing with `VS2015` as yet.

`cef-binary` branch is https://github.com/cefsharp/cef-binary/commits/cef/2454, though it looks like I forgot to push the final changes, from memory it's just updating the version number.

I was pondering branching `master` as `cefsharp/43` then upgrading `master` to `2454`. Thoughts?

**Comment by jankurianski** [comment]
> I was pondering branching master as cefsharp/43 then upgrading master to 2454. Thoughts?

Just for `cef-binary` for now, yea?  Good call.  And eventually we will go the same route with `CefSharp` after the first official release?

**Comment by amaitland** [comment]
> And eventually we will go the same route with CefSharp after the first official release?

I was pondering going down a similar path to `CEF`, as `43` is nearing release, branch it off now, then upgrade `master`. Would mean a bit of double handling for `PR's`, so there's a downside. I'm open to suggestions.

**Comment by jankurianski** [comment]
I see what you mean, like how in the `CEF` project Marshall applies fixes to the 2 most recent branches (so right now `45` and `43`)?

Looking at our `43` milestone there are no big changes in store so it seems like a good time.

**Comment by amaitland** [comment]
> I see what you mean, like how in the CEF project Marshall applies fixes to the 2 most recent branches (so right now 45 and 43)?

Yeah, just mimicking `CEF` in that regard. It may prove to be difficult. I think in general the `CEF` policy is target `PR's` against `master` and they'll be selectively ported into other branches as required.

> Looking at our 43 milestone there are no big changes in store so it seems like a good time.

There's only one show stopper in `43` at the moment, a few improvements to be made, nothing else major.

**Comment by amaitland** [comment]
Turns out there's a new `pak` file for `PDF` support, so I've rebuilt the `2454` packages and uploaded them to `MyGet`

I moved the branch to https://github.com/amaitland/CefSharp/tree/cefsharp/45

Should now build with `VS2015`, had to fix a bunch of compiler issues. Also updated the build scripts and other items.

I'll fork `master` to `cefsharp/43` at some point in the near future and merge `45` into `master`.

**Comment by amaitland** [comment]
Branching done, changes merged into `master` :smile:

**Comment by amaitland** [comment]
Basic `VS2015` support is enabled in `master`

**Comment by jankurianski** [comment]
Just FYI, I know Windows XP support is not an on-going concern for most, but I was worried that this change to compiling with `VS2013` might break it.  However I tested out my app on Windows XP and it works fine.  I used `WinForms` and `OffScreen` with version `2454`, and my app targets `.NET 4.0 Client Profile`.

**Comment by amaitland** [comment]
From memory `VC++ 2013` actually has less problems on `Windows XP` than the `VC++ 2012` version, so in all likely hood you can use the `45` version on a `Windows XP` version out of the box.

**Comment by jankurianski** [comment]
That is a bit of a relief for us, because `3%` of our customers are still on `Windows XP`!  The majority are on `Windows 7`, and funnily enough `1%` on `Vista` :stuck_out_tongue:

**Comment by amaitland** [comment]
> That is a bit of a relief for us, because 3% of our customers are still on Windows XP

I hope your charging them extra! lol
