### ISSUE TITLE
Feature Request - Expost CefPostDataElement and CefPostData

### ISSUE THREAD

**Issue by dmytropopov** [cefsharp/CefSharp#1206]
This is very nice that it is possible to sniff `IPostData.Elements` but it is not possible to alter this collection or create new instance of `CefPostDataWrapper`.
Both `CefPostDataWrapper` and `CefPostDataElementWrapper` don't have public constructors.

For reference, my use-case is to intercept request in `IRequestHandler.OnBeforeResourceLoad` and alter data being sent to server - specifically, set a file to be uploaded. This seems to be the cleanest approach to upload file programmatically (without showing 'Open File' dialog etc)

**Comment by jankurianski** [comment]
Considered making a PR?

Apart from being able to create/modify a `CefPostDataWrapper`, you would also need to expose `_wrappedRequest->SetPostData()` in `CefRequestWrapper`.  That is how CEF understands that you have modified the request:
http://magpcss.org/ceforum/apidocs3/projects/(default)/CefRequest.html#SetPostData(CefRefPtr<CefPostData>)

Perhaps by a new `set()` method underneath the existing `get` here?
https://github.com/cefsharp/CefSharp/blob/153c955885a4f0a73b903ff3c954581b7c569839/CefSharp.Core/Internals/CefRequestWrapper.cpp#L75

**Comment by amaitland** [comment]
I'm wondering if rather than expose any sort of public constructor, it's worth just having some sort of `CreateAndSetPostData` method? Haven't totally though this though, so it might not be feasible.

**Comment by amaitland** [comment]
Now that #1440 has been merged this should be trivial to resolve. Just need a new method that effectively calls `request->SetPostData(CefPostData::Create());`

https://github.com/cefsharp/CefSharp/pull/1440/files#diff-a2d549048dbe04c80f924131d8fe805bR306

**Comment by amaitland** [comment]
Resolved with https://github.com/cefsharp/CefSharp/commit/a28f43462fdd6e26507f99048334e9abf3dfd31d
