### ISSUE TITLE
cefsharp.offline screenshots out of date

### ISSUE THREAD

**Issue by twilly86** [cefsharp/CefSharp#1209]
Is there a way to trigger cefsharp to redraw a screen shot when using ScreenshotAsync?  

I'm injecting html into the page and then taking a screen shot and about 30% of the time the screen shot it out of date.

I've modified the cefsharp.offline.example project to inject letters of the alphabet sequentially and take a screen shot after each javascript execution and this is what I'm getting (file explorer with screenshot in preview mode)...

![Generated Images](http://i.imgur.com/6K0wlbN.png)
Each screen shot should be ordered A,B,C,....X,Y,Z

Here is the modified example code I am using..

    using(var requestContext = new RequestContext(requestContextSettings))
    using (var browser = new ChromiumWebBrowser(TestUrl, browserSettings, requestContext))
    {
        if (zoomLevel > 1)
        {
            browser.FrameLoadStart += (s, argsi) =>
            {
                var b = (ChromiumWebBrowser)s;
                if (argsi.IsMainFrame)
                {
                    b.SetZoomLevel(zoomLevel);
                }
            };
        }

        await LoadPageAsync(browser); // loads the first page
        
        // once we are on the page, we want to inject html and take a screen shot
        for(int i = 0; i < 26; i++)          {

            var html = "<div style=\"font-size:300px !important;\">" + GetColNameFromIndex(i) + "</div>";

            // inject content
            var htmlEncoded = html.Replace("\"", "\\\"")
                .Replace(Environment.NewLine, "\\" + Environment.NewLine);

            var javascript3 = "(function() { $('#content').html(\"" + htmlEncoded + "\");   return true; })()";
            await browser.EvaluateScriptAsync(javascript3);

            var bitmap = await browser.ScreenshotAsync();

            await browser.EvaluateScriptAsync("(function() {  $('#content').empty(); return true; })()");
                    
            SaveBitmap(bitmap);
        }
    }

I've seen this method and it looks like if chrome has a screen shot already rendered, it takes that, but this can be out of date.  Is there a way to pass in a parameter to this and then have to always redraw?  What's the cost of asking chromium to redraw the bitmap?

     public Task<Bitmap> ScreenshotAsync()
      {
            // Try our luck and see if there is already a screenshot, to save us creating a new thread for nothing.
             var screenshot = ScreenshotOrNull();
            var completionSource = new TaskCompletionSource<Bitmap>();
            if (screenshot == null)
            {
                EventHandler newScreenshot = null; // otherwise we cannot reference ourselves in the anonymous method below
                newScreenshot = (sender, e) =>
                {
                    // Chromium has rendered.  Tell the task about it.
                    NewScreenshot -= newScreenshot;
                    completionSource.SetResult(ScreenshotOrNull());
                };
                NewScreenshot += newScreenshot;
            }
            else
            {
                completionSource.SetResult(screenshot);
            }
            return completionSource.Task;
        }

**Comment by amaitland** [comment]
`ScreenshotAsync` is just a wrapper around the `NewScreenshot` event, so you can pretty much do anything you like with that. 

https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.OffScreen/ChromiumWebBrowser.cs#L74

There is an `Invalidate` method, that will ask `CEF` to redraw, that however has not been exposed in `41.0.x` (It should be accessible in the upcoming `-pre` release).

http://magpcss.org/ceforum/apidocs3/projects/%28default%29/CefBrowserHost.html#Invalidate%28PaintElementType%29

You can see that it's exposed in the `WPF` version. https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.Wpf/ChromiumWebBrowser.cs#L1463

**Comment by amaitland** [comment]
Any further comment on this one? I think if you need find grained control then your better hooking the event and implementing the screen shot functionality yourself.

**Comment by twilly86** [comment]
Would I need to trigger invalidate() first, and then that should re-render a screen shot and then I can capture the screen shot inside the  NewScreenShot event?

**Comment by amaitland** [comment]
> Would I need to trigger invalidate() first

Not sure, you'd have to find out.

**Comment by twilly86** [comment]
I'm still not getting the expected results.  I added the following the ChromiumWebBrowser class in the branch you sent me.  The screenshot code now invalidates the view, which should trigger a re-paint and then it waits for the NewScreenshot event and returns the next bitmap.  Things still aren't rendering in the correct order though. It seems as if something is happening out of sync. Any ideas?  I forked the cefsharp/41 branch and checked in my test project in CefSharp.Offline.Example if you want to check it out here...
https://github.com/twilly86/CefSharp/tree/cefsharp/41
Would you mind taking a look to see if you can reproduce?

        public void Invalidate(PaintElementType type)
        {
            lock (bitmapLock)
            {
                if (bitmap != null)
                {
                    bitmap.Dispose();
                    bitmap = null;
                }
                managedCefBrowserAdapter.Invalidate(type);
            }
        }

        public Task<Bitmap> ScreenshotAsync()
        {
            var completionSource = new TaskCompletionSource<Bitmap>();
            
            lock (bitmapLock)
            {
                EventHandler newScreenshot = null; // otherwise we cannot reference ourselves in the anonymous method below

                newScreenshot = (sender, e) =>
                {
                    // Chromium has rendered.  Tell the task about it.
                    NewScreenshot -= newScreenshot;
                    completionSource.SetResult(ScreenshotOrNull());
                };

                NewScreenshot += newScreenshot;
                Invalidate(PaintElementType.View);                
            }
            return completionSource.Task;
        }

**Comment by twilly86** [comment]
Adding in Thread.Sleep(50); right before taking a screenshot makes everything render correctly.  Maybe the EvaluateScriptAsync is returning too soon?  Adding in invalidate seems to always trigger the new screen shot event, so we might just be trying to take the screen shot too soon?

**Comment by jankurianski** [comment]
The `OffScreen` class works fundamentally the same as the `WPF` control, in that they both use CEF's off-screen rendering to capture each frame into a bitmap.  Perhaps a better name for `NewScreenshot` would be `RenderedNewFrame`.  Remember that Chrome can render frames over 30 fps.  (It would be a slow browser that only rendered 1 frame per navigation event.)

You can see how the `NewScreenshot` event is being triggered here:

https://github.com/cefsharp/CefSharp/blob/1691e172bd85acc65e12d58d73787c2a54de592e/CefSharp.OffScreen/ChromiumWebBrowser.cs#L316

You may be able to get some more insight into what is happening by adding a console log every time the event is triggered and see how many frames are returned in the 50ms sleep time?

Also perhaps a more precise approach to waiting (instead of `Thread.Sleep()`) would be to compare subsequent frame bitmaps and only fire the event when the bitmap changes?

**Comment by amaitland** [comment]
> Maybe the EvaluateScriptAsync is returning too soon?

What exactly do you mean? It returns when it's finished executing the javascript.

**Comment by twilly86** [comment]
Maybe the EvaluateScriptAsync is returning too soon? - ignore this, I don't think this is the issue.

So here is my flow..

while(
  1) Execute javascript to insert content
  2) Take screen shot (this invalidate current frame, and triggers rendering of a new frame)
  3) Save screen shot
}

I'm getting a screen shot of prior to the javascript being executed in some cases, even though I'm invalidating the current frame, which should trigger cef to re-render the frame, correct?

Any ideas on why the newly rendered frame would be returning an older frame?

**Comment by amaitland** [comment]
> which should trigger cef to re-render the frame, correct?

Prob worth asking on `ceforum` for some clarification.

> Any ideas on why the newly rendered frame would be returning an older frame?

I likely takes a few `frames` to process the update.

**Comment by amaitland** [comment]
Just at idea at this stage, you could try limiting the frame rate to `1fps`, which may work better for taking screen shots. Not sure if you can set the frame rate successfully on `41`, should be fine on `43` and above though. See #1205 for details.

**Comment by amaitland** [comment]
@twilly86 Any further comment?

**Comment by twilly86** [comment]
Sorry, haven't been able to look at this yet.  I'll try giving your latest suggestion a shot sometime this week. Will keep you posted.

**Comment by amaitland** [comment]
Added frame rate options to `master` and `cefsharp/43`

https://github.com/cefsharp/CefSharp/commit/19afbfe167b8d708d38de0aca51ddbec2ac59f87
https://github.com/cefsharp/CefSharp/commit/5e8e7e6d2e3126fe328f06570baa5b42e9dec738

**Comment by amaitland** [comment]
Looks like you can't set the frame rate dynamically in `2357` branch, so removed with subsequent commit

https://github.com/cefsharp/CefSharp/commit/c558b2db57bf29dd4a1f415043a4ac3af05adb3b

**Comment by amaitland** [comment]
A quick and dirty example using `master` (`2454`) is https://github.com/cefsharp/CefSharp/commit/78a5fc63937f7279403796bd71ee102967c4a5b1

Seems to work, only tested on one machine a handful of times, so hardly real world scenario

**Comment by amaitland** [comment]
Closing due to lack of feedback.

**Comment by twilly86** [comment]
Hey, I just tested this and it's working as expected now.  The only drawback is that it takes about 1 second per render now where it was taking 30ms before. Would there be any way to speed this up?

**Comment by twilly86** [comment]
updating browserSettings.WindowlessFrameRate to 1/15; causes the issue to come back.

I was hoping cefsharp would give me a performance boost over phantomjs since it uses chromium but having to set the framerate to 1 second removes any performance that would be gained.

**Comment by jankurianski** [comment]
> I was hoping cefsharp would give me a performance boost over phantomjs since it uses chromium but having to set the framerate to 1 second removes any performance that would be gained.

It's basically the same technology, so they have solved the problem somehow.  If you can find out how they did it, and re-apply the solution to CefSharp `OffScreen`, that would be appreciated.  It would improve the situation for everyone.

**Comment by twilly86** [comment]
PhantomJS just switched over to the QTWebkit framework.  They are looking at switching to QtWebEngine which uses chromium, however phantomjs development seems to have slowed recently.  I have much higher hopes for CefSharp.  

Is this where I should be going to submit an issue?
https://bitbucket.org/chromiumembedded/cef

It would be an issue with the Chromium Embedded Framework right since CefSharp is just a wrapper around that?

**Comment by twilly86** [comment]
This may be related to our issue
https://bitbucket.org/chromiumembedded/cef/issues/1722/inconsistent-behavior-between-cef-versions

**Comment by amaitland** [comment]
> This may be related to our issue
> https://bitbucket.org/chromiumembedded/cef/issues/1722/inconsistent-behavior-between-cef-versions

There is currently no version based on `2494`, so it's unclear if this is relevant.

> Is this where I should be going to submit an issue?
> https://bitbucket.org/chromiumembedded/cef

Ask a question on http://magpcss.org/ceforum/ first

**Comment by appakz** [comment]
Sorry to poke this old issue, but I was wondering if @twilly86 ever found a way to get this to work. I'm having similar issues on a current project.
