### ISSUE TITLE
InteropBitmapInfo - InvalidHandle

### ISSUE THREAD

**Issue by bsw-msc** [cefsharp/CefSharp#1212]
In generally the CefSharp Browser works fine but under unknown circumstances, one of our customers receives the following exception when navigating to a WebSite. 

Unfortunately I was unable to reproduce this error on my site. I don't know if it's relevant but the WebAddress is: [https://patentscope.wipo.int](https://patentscope.wipo.int/search/de/detail.jsf?docId=WO2014070898&recNum=1&office=&queryString=ALLTXT%3A%28BULK+NICKEL-BASED+CHROMIUM+AND+PHOSPHORUS+BEARING+METALLIC+GLASSES+WITH+HIGH+TOUGHNESS%29&prevFilter=&sortOption=Relevanz&maxRec=67)

![bdl-vorschau](https://cloud.githubusercontent.com/assets/8156529/9378682/91456c34-4723-11e5-9052-91881d52c007.jpg)

I am using CefSharp v41 that contains the [CefSharp.WPF.Rendering.InteropBitmapInfo](https://github.com/cefsharp/CefSharp/blob/a4507d3c2ea8fc2b0bdb7b26970cbf78290fc376/CefSharp.Wpf/Rendering/InteropBitmapInfo.cs#L44) File with the FileMappingHandle-Check.

Hope this are enough informations. Feel free to ask if not.

Is there anything I can do about this?

Regards Mark

**Comment by amaitland** [comment]
> In generally the CefSharp Browser works fine but under unknown circumstances, one of our customers receives the following exception when navigating to a WebSite.

How often does the error occur? You could implement your own `InteropBitmapInfo` based on the current version, add some extra checking, a `try catch` maybe with some logging, see what the handle actually is, make sure the other values are correct. All the relevant pieces should be public, 

> Is there anything I can do about this?

There is another rendering option which you could try, may work around the issue.
https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.Wpf/Rendering/BitmapFactory.cs#L13

**Comment by bsw-msc** [comment]
Thanks for the fast reply! I enabled the [WritableBitmapInfo](https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.Wpf/Rendering/BitmapFactory.cs#L13) mode and could not find any issues. I questioned myself why there are these two options and found [this commits](https://github.com/cefsharp/CefSharp/commit/bfec2c95b11a053b5ea79de63b6ba141e65ebf8f) in the [history of the BitmapFactory](https://github.com/cefsharp/CefSharp/commits/master/CefSharp.Wpf/Rendering/BitmapFactory.cs).

Based on the check-in comment. Is it possible (good/bad practice) to add a IBitmapFactory(Handler) on the [IWebBrowser](https://github.com/cefsharp/CefSharp/blob/a904c78399d84af26eb91540aa78bb741d3fee3b/CefSharp/IWebBrowser.cs)? Like for the [IRequestHandler](https://github.com/cefsharp/CefSharp/blob/a904c78399d84af26eb91540aa78bb741d3fee3b/CefSharp/IWebBrowser.cs#L83). 

So in my case I simply would derive from [WritableBitmapInfo](https://github.com/cefsharp/CefSharp/blob/a904c78399d84af26eb91540aa78bb741d3fee3b/CefSharp.Wpf/Rendering/WritableBitmapInfo.cs) or [WritableBitmapInfo](https://github.com/cefsharp/CefSharp/blob/a904c78399d84af26eb91540aa78bb741d3fee3b/CefSharp.Wpf/Rendering/WritableBitmapInfo.cs) and add some try catch with logging to my logging system without editing the CefSharp-Components.

I don't know how often this issue occurs but I asked our client advisor to get this information.

**Comment by amaitland** [comment]
> why there are these two options

Each option has it's own different set of performance characteristics. Historically `InteropBitmap` has always been used for `CefSharp`. 

> Based on the check-in comment. Is it possible (good/bad practice) to add a IBitmapFactory(Handler) on the IWebBrowser? Like for the IRequestHandler.

`IBitmapFactory` is only used in the context of the `WPF` control and as such cannot be added to `IWebBrowser`. You'll note that it lives in the `CefSharp.Wpf` namespace.

> So in my case I simply would derive from WritableBitmapInfo or WritableBitmapInfo and add some try catch with logging to my logging system without editing the CefSharp-Components.

There is no need to rebuild `CefSharp`, you can simply set the `BitmapFactory` property.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf/ChromiumWebBrowser.cs#L55

**Comment by bsw-msc** [comment]
Sorry, I must have overlooked that part. But this is exactly what I was looking for. Issue can be closed.

Many thanks :) !
