### ISSUE TITLE
CefSharp Sometimes webpage could not be loaded.

### ISSUE THREAD

**Issue by ming526197zhang** [cefsharp/CefSharp#1213]
I user cefsharp work show web page using wpf similar to the example cesharp provided, my program always work normally, but sometimes could load the page but with null. you can see the following image:
![1](https://cloud.githubusercontent.com/assets/13885604/9382041/79979124-476f-11e5-914a-96ea22419ef8.png)

When I debug , I found after "WebBrowser" changed, WebBrowser is not null, then ConsoleMessage , StatusMessage , LoadError , FrameLoadEnd all not be invoked. As you can see, if I add "_webBrowser.Load(_webBrowser.Address);", the count that could not be loaded reduce, but still has little.
```c#
public class BrowserTabItemData : TabItemData
{
	#region INotifyPropertyChanged??
	public override void OnPropertyChanged(object sender, PropertyChangedEventArgs e)
	{
		switch (e.PropertyName)
		{
			case "Address":
				{
					break;
				}
			case "WebBrowser":
				{
					if (WebBrowser != null)
					{
						//_webBrowser.Load(_webBrowser.Address);
						WebBrowser.ConsoleMessage += OnWebBrowserConsoleMessage;
						WebBrowser.StatusMessage += OnWebBrowserStatusMessage;
						WebBrowser.LoadError += OnWebBrowserLoadError; 
						WebBrowser.FrameLoadEnd += (s, ee)=>
						{
							//Application.Current.Dispatcher.BeginInvoke((Action)(() => _webBrowser.Focus()));
							if (ee.IsMainFrame)
							{
							}
						};
					}break;
				} 
		}
	}
}
```

Besides, I can see the following message in Visual studio output window after I use settings.LogSeverity = LogSeverity.Verbose,
[0820/183635:WARNING:message_in_transit_queue.cc(18)] Destroying nonempty message queue
The thread '<No Name>' (0x7b20) has exited with code 0 (0x0).
The thread '<No Name>' (0x5974) has exited with code 0 (0x0).
The thread '<No Name>' (0x5ad0) has exited with code 0 (0x0).
The thread '<No Name>' (0x8964) has exited with code 0 (0x0).
I am not sure if this time related to my problem.

Anyone encounter the same problem ? who has ideas ? Thanks.

**Comment by amaitland** [comment]
What version are you using? Can you reliable reproduce the problem? If you fork the `MinimalExample` to demonstrate your problem that will greatly increase the changes of getting a helpful response.

https://github.com/cefsharp/CefSharp.MinimalExample

Also please take the time to markup your code so it's easier to read.
https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting

**Comment by ming526197zhang** [comment]
Hi Amaitland,
 My program sometimes works normally, it display web page. But sometimes it could not load the page, I found, in class CefSharp.Wpf.ChromiumWebBrowser, SetLoadingStateChange and SetAddress, two functions will be called when display a web page normally, but not be called unnormally. I don’t know why they are not called? And that is the main reason.

**Comment by jankurianski** [comment]
Can you make your problem occur with the CefSharp WPF example project?  It also uses tabs and works OK.

**Comment by ming526197zhang** [comment]
Hi Jankurianski,
    I write my program similar to CefSharp.Wpf.Example, use CefSharp 3.2171.2069, the example works ok, but my program sometimes has problem, I also send Email to you, if needed, I could send my codes to you

**Comment by amaitland** [comment]
> But sometimes it could not load the page,

Does `LoadError` get called?

https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp/IWebBrowser.cs#L41

> CefSharp 3.2171.2069

Have you tried using the latest version? `41.0.1`

> I also send Email to you, if needed, I could send my codes to you

Please keep things in the public domain. If you can reproduce the problem by forking the `MinimalExample` project then we'll try to have a look.

**Comment by amaitland** [comment]
@ming526197zhang Any updates on this?

**Comment by ming526197zhang** [comment]
LoadError does not be invoked.
The latest version 41.0.1 has some conflict with my codes, so I will not change to 41.0.1 in recent days.
No I have a temporary solution for solve this problem. I set address to Browser control directly, then it works normally.

**Comment by 537mfb** [comment]
This happened to me also
Unfortunately in my case it happens in my gmail account so i can't provide a test sample
Most email i click and it opens - some i click, a 'loading' warning shows on top of the page but it stays like so until i click some other link (one that works). Ones that won't open, won't open no matter how many times i try
I'm using the latest build - CEFSharp WPF 71.0.0 with cef.redist.x64 3.3578.186
Neither LoadError or ConsoleMessage get called - it just stays there

Is there some way to get a log or something of what happens from the moment i click the link?

**Comment by amaitland** [comment]
It's not unheard of for `Google Apps` to attempt accessing features that are only available in `Chrome`. See https://bitbucket.org/chromiumembedded/cef/issues/2588/branch-version-3683-does-not-support#comment-50542267 for details, try the workaround listed there.

You can test with the `CEF Sample Application`, details at https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-chromium-embedded-frameworkcef

It's important to remember that `CefSharp` is just a wrapper. In future please don't comment on incredibly old closed issues. https://github.com/cefsharp/CefSharp#contact lists contact information.

**Comment by 537mfb** [comment]
Changing the User-Agent doesn't make any difference - it would be odd if it did
Like i said - it always happens with certain emails and never happens with others - so it has to be something about those specific emails (or maybe their addresses) that cause this

As for commenting here - i figured it was important to note that although this is closed, it hasn't been fixed

**Comment by amaitland** [comment]
Changing the user agent has been shown to influence how Google identifies the browser and what features it attempts to access, Google Drive will only work if you pretend to be Firefox. CEF only implements a subset of the features provided by Chrome.

I suggest you test with the CEF sample application, it's very unlikely that the problem you are seeing is a bug in CefSharp.
