### ISSUE TITLE
NuGet package breaks solution

### ISSUE THREAD

**Issue by RichardD2** [cefsharp/CefSharp#1214]
1. Create a new WPF project;
2. Change the platform target to x86;
3. Add the CefSharp.Wpf NuGet package (v41.0.1);
4. CefSharp references do not appear in the project references;
5. Save, close and re-open the solution;
6. CefSharp references appear, but now *all* references have a warning icon, and absolutely every line of code is an "unable to resolve type" error;

I've tried this in both VS2015 and VS2013, and the result is the same.

I've tried upgrading to the pre-release version of the package, and it doesn't make any difference.

What am I missing? How do I install this NuGet package without destroying my project?

**Comment by amaitland** [comment]
Can you download the `MinimalExample` and make sure that builds correctly?

https://github.com/cefsharp/CefSharp.MinimalExample

If `nuget` added a `EnsureNuGetPackageBuildImports` target to your project file, try removing that manually. (Prob best to close VS after making the change)

https://github.com/cefsharp/CefSharp/commit/9bb3210694f90eb1bab6e02f69e3e75a0de45b3a#diff-29fd0bc3e7368ee6b74384a0f2869f61

**Comment by RichardD2** [comment]
I think I've found the problem. It's not enough to change the Platform Target in the project's properties - you actually have to create a new build configuration and set the platform to x86 in there.

After doing that and removing the `EnsureNuGetPackageBuildImports` target, the references now resolve correctly.

**Comment by amaitland** [comment]
Feel free to submit a `PR` that elaborates on the error message generated by the `.targets` file.

https://github.com/cefsharp/CefSharp/blob/master/NuGet/CefSharp.Common.targets#L4

**Comment by amaitland** [comment]
Anything further before closing this?

**Comment by RichardD2** [comment]
No, all good thanks.
