### ISSUE TITLE
How do I include the Visual Studio C++ 2012 redistributables in ClickOnce?

### ISSUE THREAD

**Issue by bguyb** [cefsharp/CefSharp#1215]
In the FAQ (https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#6-how-do-i-include-the-visual-studio-c-2012-redistributables-on-the-target-app)
It's say: "by copying over to your project the contents of this folder". 
Where do I need to put those files?

**Comment by amaitland** [comment]
In the executing folder e.g. `bin`

**Comment by amaitland** [comment]
See `Taking care of Visual C++ 2012 Runtime Files` in http://stackoverflow.com/questions/22841585/deploying-wpf-application-with-3rd-party-dlls/24287807#24287807

For this sort of non `CefSharp` specific question, `stackoverflow` is a good place to start.
