### ISSUE TITLE
Cef.Shutdown() implicitly closes main app?

### ISSUE THREAD

**Issue by lamerbug** [cefsharp/CefSharp#1217]
Looks like I'm missing something obvious, or maybe Cef is not designed to do so, but where can I change this behaviour? I'd like my app keep running after Cef.Shutdown() call. And is there a way to re-initialize cef after shutdown? (subsequent call to cef.Initialize fails).
p.s. i'm sure I've seen some comments explaining this issue but it was long time ago and now I cannot find them to clarify it...

**Comment by amaitland** [comment]
Version? WinForms? WPF? 

You cannot shutdown and reinitialize cef, its not supported by chromium. That being said it shouldn't shutdown your app.

Take a look at the source for the relevant version.

**Comment by lamerbug** [comment]
Version: all latest versions incl. current
Winforms, release, x32
>You cannot shutdown and reinitialize cef, its not supported by chromium.
Okay, thanks for clarification
>That being said it shouldn't shutdown your app.
but it does ) Compile Winforms.Example, place button with Cef.Shutdown(), run example and push the button and app closes.

**Comment by amaitland** [comment]
> but it does ) Compile Winforms.Example, place button with Cef.Shutdown(), run example and push the button and app closes.

If you manually dispose of all the `ChromiumWebBrowser` instance before calling `Cef.Shutdown()` it won't exit your application. If you call `Cef.Shutdown()` with instances still active then they will be disposed, which is likely causing the exit.

**Comment by amaitland** [comment]
@lamerbug Make sense now?
