### ISSUE TITLE
Context Menu does not show text.

### ISSUE THREAD

**Issue by Spiderpig86** [cefsharp/CefSharp#1220]
Hey guys. I am currently using CefSharp in Winforms version 41.0.1 on Windows 10. For some reason, the context menu items do not show the text. I am not sure what I'm doing wrong. This is an offscreen control.
![screenhunter_01 aug 25 21 29](https://cloud.githubusercontent.com/assets/2801187/9483788/c4e579a6-4b71-11e5-9a64-0ef646f854a5.jpg)

**Comment by amaitland** [comment]
> This is an offscreen control.

You said your using `WinForms`? Can you clarify. 

Have you tested on different operating systems or just `Windows 10`?

**Comment by Spiderpig86** [comment]
I have tested on Windows 7 and Windows 10. The sample does work, but when I tried to implement it in my own project, the context menu text does not appear. I am currently using WinForms targetting .NET Framework 4.0 Client Profile in a 32-bit application. I have tried .NET Framework 4.0, but it had the same issue.

**Comment by amaitland** [comment]
Does your application have an `app.manifest`?

https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.WinForms.Example/app.manifest

**Comment by Spiderpig86** [comment]
Indeed it does have an app.manifest

**Comment by amaitland** [comment]
> Indeed it does have an app.manifest

That specifically includes https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.WinForms.Example/app.manifest#L15

Your going to have to help me out here, very little information to go on and brief answers don't help me.

**Comment by Spiderpig86** [comment]
Apologies for the brief answers. Currently I am quite confused as to what would be causing the context menu text to disappear.

This is currently my app.manifest:
```
<?xml version="1.0" encoding="utf-8"?>
<asmv1:assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1" xmlns:asmv1="urn:schemas-microsoft-com:asm.v1" xmlns:asmv2="urn:schemas-microsoft-com:asm.v2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <assemblyIdentity version="1.0.0.0" name="MyApplication.app"/>
  <dependency>
    <dependentAssembly>
      <assemblyIdentity type="Win32" name="Microsoft.Windows.Common-Controls" version="6.0.0.0" processorArchitecture="*" publicKeyToken="6595b64144ccf1df" language="*"></assemblyIdentity>
    </dependentAssembly>
  </dependency>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v2">
    <security>
      <requestedPrivileges xmlns="urn:schemas-microsoft-com:asm.v3">
        <!-- UAC Manifest Options
            If you want to change the Windows User Account Control level replace the 
            requestedExecutionLevel node with one of the following.

        <requestedExecutionLevel  level="asInvoker" uiAccess="false" />
        <requestedExecutionLevel  level="requireAdministrator" uiAccess="false" />
        <requestedExecutionLevel  level="highestAvailable" uiAccess="false" />

            If you want to utilize File and Registry Virtualization for backward 
            compatibility then delete the requestedExecutionLevel node.
        -->
        <requestedExecutionLevel level="asInvoker" uiAccess="false" />
      </requestedPrivileges>
    </security>
  </trustInfo>
</asmv1:assembly>
```

**Comment by amaitland** [comment]
Have you disabled pak loading or removed any of the pak files from your distribution? 

Does `debug.log` show anything helpful if you crank up the logseverity. Having a second look at the screen shot, it looks like it's missing the localized resources.

**Comment by Spiderpig86** [comment]
I have filled in the missing localized resources. Everything is working now! Thank you so much! I feel pretty stupid for not realizing this in the first place.

**Comment by amaitland** [comment]
> I feel pretty stupid for not realizing this in the first place.

Easy enough thing to leave out and there's really no warning provided from `CEF`.

Just as a reference you can try `performDependencyCheck: true` when calling `Cef.Initialize`, the hope is that it will pickup missing files (At some point we might turn it on by default)

https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.Core/Cef.h#L156
