### ISSUE TITLE
Zoom levels don't seem to work when using a custom scheme handler

### ISSUE THREAD

**Issue by mmamone** [cefsharp/CefSharp#1221]
#### Issue Summary
Invoking Zoom when using a custom scheme doesn't actually zoom the document.

#### Steps to Reproduce
1. Visit a page using a custom scheme (the Cef WPF sample page is a good one)
1. Click zoom in/zoom out, and observe nothing happens
1. Try the same on a regular http page, and everything works as expected

Cannot check this against a cef build, as I cannot use a custom scheme with them.

#### Technical details
* CefSharp Version: 1691e172bd85acc65e12d58d73787c2a54de592e
* Operating System: Windows 8.1
* x86
* WPF

**Comment by amaitland** [comment]
For clarity, your using `WPF` in this context?

If you open `cefclient`, go `Tests->Other Tests`, there should be a `Scheme Handler` test which equates to `client://tests/handler.html`

**Comment by mmamone** [comment]
Yes - WPF.
Thanks for the cefclient pointer. The scheme handler test zooms correctly. I'll see if there is any magic in their osr client, but if you know of any shortcuts, let me know :)

**Comment by mmamone** [comment]
As an aside - the WinForms version doesn't seem to do this correctly either.

**Comment by amaitland** [comment]
> As an aside - the WinForms version doesn't seem to do this correctly either.

I'm surprised the `WinForms` version doesn't work correctly. I guess it's less likely a `WPF` specific implementation detail then and something more generic.

**Comment by mmamone** [comment]
I'll add that both versions do report the correct zoom level (ie, hit zoom in 4 times, and the current zoom level is reported as 0.4 )

**Comment by amaitland** [comment]
I'd probably reach out on `ceforum`, see if someone can suggest an implementation detail we might be missing.

**Comment by mmamone** [comment]
Entered this post :
http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=13345

Hopefully someone has an answer.

**Comment by amaitland** [comment]
Cool, hopefully someone can point out what we're missing :+1:

**Comment by amaitland** [comment]
Seems as if the custom schemes aren't being registered in the sub processes, looks like fixing that resolves this as well.

See #1268
