### ISSUE TITLE
Dev tools not displaying

### ISSUE THREAD

**Issue by bjarteskogoy** [cefsharp/CefSharp#1227]
When using the new `SetOffScreenRenderingBestPerformanceArgs()` the dev tools window opens, but it's empty. Clicking around in it proves that there is content. It's just not visible.

**Comment by amaitland** [comment]
Best to report upstream, nothing we can do other than say don't use that feature.

**Comment by bjarteskogoy** [comment]
Seems to be ok in master now (cef 45).

**Comment by amaitland** [comment]
Ok cool, re-open if required.
