### ISSUE TITLE
ShowDevTools error

### ISSUE THREAD

**Issue by Sential** [cefsharp/CefSharp#1228]
I don't know what is it, but it throws me error when I close DevTools.
![przechwytywanie](https://cloud.githubusercontent.com/assets/11065386/9555972/53169e42-4dd1-11e5-9aa7-72632c6b9bfe.PNG)

**Comment by jankurianski** [comment]
WinForms or WPF?

Version?

What are the steps to reproduce this problem on the CefSharp Example app?

**Comment by Sential** [comment]
WinForms Cefsharp 43, sorry i forget :P

**Comment by amaitland** [comment]
Steps to reproduce?

**Comment by Sential** [comment]
So I used IBrowserHost and I used this code: webcontrol1.GetBrowser.GetHost().ShowDevTools and devtools are showing, but if i close then VisualStudio throws me error.

**Comment by amaitland** [comment]
When I open/close `DevTools` in the `CefSharp.WinForms.Example` project everything appears to be working correctly. Are you using the `43.0.0-pre01`? Can you provide a sample to reproduce the problem?

The `MinimalExample` project has a branch that uses the `43.0.0-pre01` packages if required.
https://github.com/cefsharp/CefSharp.MinimalExample/tree/cefsharp/43

**Comment by amaitland** [comment]
Can reproduce the problem using the `Wpf.Example` project, only appears if an instance of `LifeSpanHandler` is assigned.
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Internals/ClientAdapter.cpp#L205

Will need to be careful when fixing this, little bit fiddly.
