### ISSUE TITLE
Replace content 

### ISSUE THREAD

**Issue by Jayman1305** [cefsharp/CefSharp#1229]
I used to do the following in my IRequestHandler.OnBeforeResourceLoad but i cant find anything to help me do this in the current build. 

```c#
if (request.Url == "http://localhost/styles.css")
                    {
                        var handler = browser.ResourceHandlerFactory;
                        if (handler != null)
                        {
                            if (string.IsNullOrEmpty(_styleCss))
                            {
                                using (var stream = Assembly.GetExecutingAssembly().GetManifestResourceStream("MultiBrowser.Emulators.EmbeddedResources.styles.css"))
                                {
                                    if (stream != null)
                                    {
                                        using (var streamReader = new StreamReader(stream))
                                        {
                                            _styleCss = streamReader.ReadToEnd();
                                        }
                                    }
                                }
                            }
                            handler.RegisterHandler(request.Url, ResourceHandler.FromString(_styleCss, ".css"));
                        }
                    }
```

**Comment by amaitland** [comment]
The register methods were removed from the interface as the much of the code is shared with the scheme handler implementation. The default implementation is the same for the factory, so you should be able to cast it.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp/DefaultResourceHandlerFactory.cs

**Comment by Jayman1305** [comment]
@amaitland Im a bit lost. Do you have a sample of how i can intercept the request and replace the content.

**Comment by amaitland** [comment]
> var handler = browser.ResourceHandlerFactory;

Try casing `browser.ResourceHandlerFactory`, rest of your code will hopefully remain unchanged.

```c#
var handler = (DefaultResourceHandlerFactory)browser.ResourceHandlerFactory;
```

**Comment by Jayman1305** [comment]
Thought that's what you meant but there is no ResourceHandlerFactory exposed by the browser.

Has ResourceHandlerFactory been renamed. I can't see any option to case from in intellisense.

**Comment by amaitland** [comment]
Interface changed a little with the addition of `IBrowser`.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp/IRequestHandler.cs#L86

By default `IWebBrowser` is now called `browserControl`

**Comment by Jayman1305** [comment]
Awesome. Thanks for the pointer
