### ISSUE TITLE
NullReferenceException at OnBeforePopup

### ISSUE THREAD

**Issue by Spiderpig86** [cefsharp/CefSharp#1230]
Hello all. I am currently trying to handle and intercept popup requests via the LifeSpanHandler. Problem is that I'm not sure why it would just crash the application. I am currently using CefSharp 41.0.1 for Winforms on Windows 10 and tested with both .NET 4.0 and 4.5. Both frameworks yielded the same results. I'm currently unsure of what could be causing this and can someone help me? Thanks in advance.
```
Imports CefSharp

Public Class LifeSpanHandler
    Implements ILifeSpanHandler
    Public Event PopupRequest As Action(Of String)
    Public Function OnBeforePopup(WebControl As IWebBrowser, sourceUrl As String, targetUrl As String, ByRef x As Integer, ByRef y As Integer, ByRef width As Integer, ByRef height As Integer) As Boolean Implements ILifeSpanHandler.OnBeforePopup
        RaiseEvent PopupRequest(targetUrl)
        If My.Settings.blockPopups = True Then
            MsgBox("One or more popups have been blocked on " + sourceUrl + ".")
        End If
        Return False
    End Function
  Public Sub OnBeforeClose(browser As IWebBrowser) Implements ILifeSpanHandler.OnBeforeClose

    End Sub
End Class
```
Error Details from EventViewer:

```
Fault bucket 128903468014, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: CefTestProj.exe
P2: 1.0.0
P3: 55e23e9c
P4: CefTestProj
P5: 1.0.0
P6: 55e23e9c
P7: 6b5
P8: 27
P9: System.NullReferenceException
P10: 
```

**Comment by amaitland** [comment]
What line causes the exception? Do you have a proper stack trace? Are you sure it's a `CefSharp` problem? I don't program in `VB.Net`, so can't validate your code.

**Comment by Spiderpig86** [comment]
Unfortunately, I could not get a proper stack trace since the code always leads to vhost.exe has stopped working. The error always occurs when I try to reference some other part of the program.
Eg:
```
   If My.Settings.blockPopups = True Then
```
The program does not get an error when I remove the if statement.

**Comment by amaitland** [comment]
Methods on handlers including `LifeSpanHandler` are executed on a `CEF` thread. You either have to marshall onto the thread that can access the object your using or just pass in some params wen you create the `ILifespanHandler` instance.

**Comment by Spiderpig86** [comment]
Would you mind giving me an example in C# of marshalling onto a thread? I think the threading issue is also affecting the downloadhandler for the project too. For some reason I can't seem to add a UserControl to a panel in that handler. Thank you for all the help.

**Comment by amaitland** [comment]
Sure, the source code has a few places in the `WinForms` project that marshall onto the `UI` thread.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.WinForms/ChromiumWebBrowser.cs#L195
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.WinForms/Internals/ControlExtensions.cs#L17

> For some reason I can't seem to add a UserControl to a panel in that handler.

As it's running on one of the `CEF` background threads I'm not surprised.

**Comment by Spiderpig86** [comment]
This time I was able to get the exception: Invoke cannot be called on a control until the window handle has been created

This exception occurs any time I try to call a function or access a property on the main form. I have tried this but to no avail.

```
 Form1.Invoke(DirectCast(Sub() Button1.Enabled = True, MethodInvoker))
```

**Comment by amaitland** [comment]
If you can reproduce the problem in `c#` then I can help, otherwise there's not much more I can do other than suggest, something like `stackoverflow`

**Comment by Spiderpig86** [comment]
I have found the solution for this issue. You were right about marshalling calls onto a thread. What caused trouble for me was calling a function in a conditional without invoking. Thank you so much for your help.

**Comment by amaitland** [comment]
No problem :+1:
