### ISSUE TITLE
document ready

### ISSUE THREAD

**Issue by SethTurin** [cefsharp/CefSharp#1231]
Hello

I've spent the day looking and I can't find a good way to determine when the dom is ready. At the moment I'm trying a pretty unsatisfying way:

```
    private void FrameLoadStartHandler(object sender, FrameLoadStartEventArgs e) {
      if (e.IsMainFrame) {
        DomReady = false;
        new Thread(() => {
          int count = 0;
          while (count < 20 && DomReady == false) {
            count++;
            Thread.Sleep(500);
            string ready = ExecuteScriptWithResult("document.readyState").ToString();
            if (ready == "complete") {
              DomReady = true;
            }
          }
        }).Start();
      }
    }
```

This works on some sites but on other sites it crashes everything. I imagine there's probably a more sane way to accomplish this. Can someone point me in the right direction?

Thanks

**Comment by amaitland** [comment]
What version are you using?

**Comment by SethTurin** [comment]
39.0.1

**Comment by amaitland** [comment]
What exactly are you trying to do?

I'd typically stay away from `FrameLoadStart/FrameLoadEnd` as they're not ultra reliable. The recommended event is `NavStateChanged`

https://github.com/cefsharp/CefSharp/blob/cefsharp/39/CefSharp/IWebBrowser.cs#L48

**Comment by SethTurin** [comment]
This is for a web automation tool, so my purpose is actually to just wrap the dom ready event and pass it along to the end user. Dom ready is the mostly logical place to begin the next automation action most of the time, so a reliable event is crucial to the process.

I can use the same code in NavStateChanged, but is there a better solution to hook directly into the event? Having a timed loop poking at it feels like a bit of a hack.

**Comment by amaitland** [comment]
When `IsLoading = false` then the `DOM` can safely be used (if there's no `IsLoading` in `39`, then `use `CanReload = true`). It's a property of the event args.

Typically you'd use a combination of `EvaluateScriptAsync/ExecuteScriptAsync` and `javascript binding` see https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#3-how-do-you-expose-a-net-class-to-javascript

There is no easy way to hook the `document.onreadystatechanged` handler that I can think of.

**Comment by SethTurin** [comment]
This is helpful, thanks. I'll report back on what I come up with.

**Comment by SethTurin** [comment]
Ok, unfortunately it looks like both IsLoading and CanReload only indicate when the page is fully loaded, including all images and resources. The purpose of hooking the dom ready event is to allow work on the dom before loading external resources, as said resources take considerably longer to load than the dom.

So that's a dud. Is there any way to know with confidence the first moment that it's safe to run javascript?

**Comment by jankurianski** [comment]
> So that's a dud. Is there any way to know with confidence the first moment that it's safe to run javascript?

As far as I know there is no specific event in CEF that tells you the first exact time at which you can execute JavaScript safely.  Perhaps this is worth asking on the CEF forums.  The CEF method that performs JavaScript execution is `ExecuteJavaScript` in the class `CefFrame`.  Here is where CefSharp calls it:
https://github.com/cefsharp/CefSharp/blob/ac269e860c90a85482ff6de61479635559f137d3/CefSharp.Core/Internals/CefFrameWrapper.cpp#L172

**Comment by amaitland** [comment]
There is an open upstream issue https://bitbucket.org/chromiumembedded/cef/issues/1454

`ceforum` suggests a few possible workarounds in the meantime, though none of them are currently exposed in `CefSharp`.

**Comment by SethTurin** [comment]
The issue of the dom ready event came up in the cef forums, and they had a solution, but it again looks like like it's not something exposed in cef sharp (correct me if I'm wrong). Here is that URL: http://magpcss.org/ceforum/viewtopic.php?f=6&t=10277

I'll keep looking for a workaround in the mean time, but do you feel this would be a reasonable feature to request? I could mount a pretty strong argument for it.

**Comment by amaitland** [comment]
> I'll keep looking for a workaround in the mean time, but do you feel this would be a reasonable feature to request?

Your welcome to implement the feature, though I'll make note that it's infinitely more complex that it looks as `VisitDOM` can only be called in the `render` process. 

https://bitbucket.org/chromiumembedded/cef/src/4a8546efd70700eed1e1f921e85293abf90d2691/include/cef_frame.h?at=master#cef_frame.h-217

There are also references in `ceforum` to the `DOM API` being deprecated and as such could be removed at any point in the future.

> I could mount a pretty strong argument for it.

I'm sure many people would benefit from it, so by all means keep looking for an elegant solution.

**Comment by SethTurin** [comment]
Ok, it's definitely not pretty, but I found a solution that seems to work pretty well. I have to use FrameLoadStart because the other options don't indicate whether it's the main frame. In case it's useful for anyone else, here is my code:

```    private void FrameLoadStartHandler(object sender, FrameLoadStartEventArgs e) {
      if (e.IsMainFrame) {
        DomReady = false;
        EvaluateScriptAsync(@"(function () {
  if(document.readyState === 'complete') {
    return 'complete';
  }
  else {
    document.addEventListener('DOMContentLoaded', function () { boundObject.domReady(); }, false);
    return document.readyState;
  }
}).call()
                          ", null).ContinueWith(task => {
                             if (task.IsFaulted) {
                               //throw an error or log the issue
                             } else if (task.Result.Result.ToString() == "complete") {
                               DomReady = true;
                             }
                           });

      }
    }
```

And then on my bound object I just have:

```    public void DomReady() {
      MyBrowser.DomReady = true;
    }```

**Comment by amaitland** [comment]
@SethTurin Nice :+1: Probably worth adding something like this to one of the example projects if your interested.

**Comment by SethTurin** [comment]
I might not mind doing that. In my project I'm using a custom implementation of the chromiumwebbrowser, and I added the DomReady property to that. I'm not supper happy with setting the property externally from the bound object, but it works. Is there any way in particular you'd like to see it implemented?

**Comment by amaitland** [comment]
> Is there any way in particular you'd like to see it implemented?

Simplest possible implementation :smile: Probably just a method on the bound object to notify that it's ready would be enough. 

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/BoundObject.cs#L10

**Comment by amaitland** [comment]
@SethTurin Just looking at this a little closer, in the limited testing I've done it appears that `document.readyState === 'complete'` is always `true`. Does it ever add the event listener?

**Comment by SethTurin** [comment]
on my end I've had it hit the event listener. dom renders pretty fast in chromium, so depending on what pages you're loading, it's not surprising that readystate shows as complete right away. The real thing to test is whether you can safely make changes to the dom after domready. I've had mixed luck with this, but my project is huge and complex so I need to mess around with it more.

**Comment by SethTurin** [comment]
hey just for an update on this issue, I've yet to find a solution that works in 100% of cases. sometimes it seems to just not bind the event with no errors given or anything. I have something that works for my purposes for now, but it's pretty messy and I wouldn't really want to publish it.

do you think it would be worth leaving the issue open as a feature request? if I had the time or dev resources, I'd take a crack at it myself, but unfortunately that's not currently in the cards for me.

**Comment by amaitland** [comment]
I have an idea for a solution, will try it out at some point. New issue created, see #1373
