### ISSUE TITLE
CookieManager not implemented?

### ISSUE THREAD

**Issue by MihaMarkic** [cefsharp/CefSharp#1233]
Hi guys,

While there is ICookieManager interface I don't see any implementation. Am I missing something or it is simply not there?

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Internals/CookieManager.h#L16

**Comment by amaitland** [comment]
You can get the global cookie manager using https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Cef.h#L308

**Comment by MihaMarkic** [comment]
Right, but that doesn't seem to be available in 41.0.1. I guess I have to switch to 43.0.0+? Which branch is that?

**Comment by MihaMarkic** [comment]
Master, of course. I guess not yet on NuGet.

**Comment by amaitland** [comment]
> Master, of course. I guess not yet on NuGet.

There is a `-pre` package on `nuget.org`.

In `41` and below there are cookie related methods available on the `Cef` class. Only a subset is there from memory.

https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.Core/Cef.h#L280

**Comment by MihaMarkic** [comment]
Excellent, it works. I actually need to wipe out session (cookies) and hence the ICookieManager. With 43.0.0-pre01 it works.
Thanks for the help.
