### ISSUE TITLE
A way to clear cache?

### ISSUE THREAD

**Issue by MihaMarkic** [cefsharp/CefSharp#1234]
Hi guys,

I'm looking into a way to clear cache files. I'm enabling cache like this:

var settings = new CefSettings();
settings.CachePath = @"SOMEPATH\chromiumcache\";
Cef.Initialize(settings);

And trying to figure out how to clear the cache in a clean way. Simple deleting the folder content won't do due to the conflicts with cookies (other process might be holding the file(s)). A dirty solution would be to delete all cache files except for the cookies.
So far I couldn't find a clean way to do it.

**Comment by Spiderpig86** [comment]
My solution would be to delete the cache files on exit, but that might not be what you are looking for. You can try deleting the files after shutting down Cef.

**Comment by MihaMarkic** [comment]
Yep, but I'd like it without killing Cef in between. (I'd delete the cache after user logs out).

**Comment by amaitland** [comment]
There is no explicit feature as outlined in http://magpcss.org/ceforum/viewtopic.php?f=6&t=11992&p=22282#p22282

By default a `in-memory` cache is used, so that's the easiest way, though that might not meet your requirements. I believe you can still set the cookie path whilst using the `in-memory` cache.

**Comment by MihaMarkic** [comment]
It really looks like there is currently no (clean) way since Chromium doesn't support it. For cookies I'm happy with CookieManager.
I wonder why such features were omitted in first place.

**Comment by jviolas** [comment]
There is new responses in the mentioned thread from CEF Forum https://magpcss.org/ceforum/viewtopic.php?f=6&t=11992&p=22282#p54054 and it seems the "cleanest" way to do it might be by using [Chrome DevTools API](https://chromedevtools.github.io/devtools-protocol/tot/Storage/) and executing devTools methods with `ExecuteDevToolsMethod`. 

Code example from the thread:
```
for (auto browser : browsers) {
   CefRefPtr<CefDictionaryValue> params = CefDictionaryValue::Create();
   params->SetString("origin", browser->getCurrentURL());
   params->SetString("storage_types", "local_storage");
   browser->getHost()->ExecuteDevToolsMethod(0, "Storage.clearDataForOrigin", params);
   params->Clear();
   browser->getHost()->ExecuteDevToolsMethod(0, "Page.resetNavigationHistory", params);
   browser->reload();
}
```
It seems using `*` as `origin` for the `clearDataForOrigin` can clear for all origins.
And in the `Network` API, there is a [`clearBrowserCache`](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-clearBrowserCache) that can also clear the entire cache.

I'm not sure this is something that should be directly implemented in CefSharp with for example a method `clearStorage(origin, storageTypes)`, but at least it's possible to do it with the already exposed  `IBrowserHost.ExecuteDevToolsMethod()` method.
