### ISSUE TITLE
CefSharp.SubProcess bug

### ISSUE THREAD

**Issue by Blue-Locus** [cefsharp/CefSharp#1236]
I'm currently looking on how to disable image loading so I won't have to code an adblock system and have a site telling the user to disable it. Any help? If so, is there a way to disable specific formats including video?

**Comment by amaitland** [comment]
There is `BrowserSettings.ImageLoadingDisabled`.

`API` documentation http://magpcss.org/ceforum/apidocs3/projects/%28default%29/_cef_browser_settings_t.html#image_loading

https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.Core/BrowserSettings.h#L208

As for video, you can block the plugin load request if you choose. See https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.Example/RequestHandler.cs#L43 or you can simply disable plugins using something like https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.Example/CefExample.cs#L41

**Comment by Blue-Locus** [comment]
@amaitland Hey thanks for replying but I'm currently using VB.NET since I'm trying to learn it. I'm trying to learn on programming language at a time so is there a VB.NET tutorial or snippet?

**Comment by amaitland** [comment]
> so is there a VB.NET tutorial or snippet?

Currently no. You used to be able to use something like `Reflector` and de-compile code into `VB.Net`.

**Comment by Blue-Locus** [comment]
Oh ok, but what code do I de-compile? mind giving me a link?

**Comment by amaitland** [comment]
> Oh ok, but what code do I de-compile?

Whatever code out of the `C#` based examples you need to use in `VB.Net`. Try starting with the current example, getting that to work in your scenario then worry about porting the code to `VB.Net`

**Comment by Blue-Locus** [comment]
Ok, cause C# is my next programming language I'm going to learn but I'm trying to learn one by one.

**Comment by amaitland** [comment]
> Ok, cause C# is my next programming language I'm going to learn but I'm trying to learn one by one.

Personally I dislike `VB.Net` and see no point in learning it! lol

**Comment by Blue-Locus** [comment]
VB.NET is actually taking a name but I see why many don't like it. I'd also like to start a Learn Coding organization so I want to be ready for all occasions. :)

**Comment by amaitland** [comment]
> VB.NET is actually taking a name but I see why many don't like it

I've written `VB 3/4/6`, so my dislike for the syntax/language goes a long way back!

**Comment by Blue-Locus** [comment]
Really? Wow. Well, thanks for everything. How do I rate you on GitHub? I'm new to GitHub haha I use BitBucket.

**Comment by amaitland** [comment]
> Well, thanks for everything.

Got it sorted? Happy to close this?

**Comment by Blue-Locus** [comment]
not really, I'm still trying to figure this out. haha
Sorry for the late reply.

**Comment by amaitland** [comment]
> There is BrowserSettings.ImageLoadingDisabled.

This works as expected for me.

> not really, I'm still trying to figure this out. haha

What problem are you experiencing?

**Comment by amaitland** [comment]
I just remembered that I had seen one project using `VB.Net` check out https://github.com/Emposoft/Opaque

**Comment by Blue-Locus** [comment]
Ya, see. I'm not sure how to call:
> BrowserSettings.ImageLoadingDisabled

in `VB.NET`.
I've been trying to figure it out for when (for example) `Form1` loads I can call that `function`.

**Comment by numbersint** [comment]
I think the key problem is in your Form Load code it is too late to call "Cef.Initialize()" because it would have been automatically initialized already. VB automatically loads your main form and all controls by default before any of your code runs.

You will need to introduce a "Public Sub Main" method like described here:
http://stackoverflow.com/a/10534791

Then you can add a call to "Cef.Initialize()" and supply your own "BrowserSettings".

**Comment by amaitland** [comment]
Based on the `cefsharp/43` branch (property is slightly different in the `41` branch). You'd set it like 

https://gist.github.com/amaitland/4bb5d40afbf926283462#file-browsertabusercontrol-cs-L27

Not sure how that translates to `VB.Net`, I'm guessing it's a fairly direct mapping.

**Comment by Blue-Locus** [comment]
I'm so sorry guys, I'm not sure how I didn't figure it out earlier. Thanks so much for the help!! :D

**Comment by jankurianski** [comment]
@Blue-Locus you're welcome.  Do you mind posting a snippet of the VB code you ended up using?  It will help future Googlers :smile: 

Here's a quick guide on how to format the code so it looks good in GitHub: https://help.github.com/articles/markdown-basics/#multiple-lines

**Comment by Blue-Locus** [comment]
I've forgotten that CefSharp uses a Panel for its component so I thought I had to use the CefSharp settings to call these functions.

    Public Sub New()
        InitializeComponent()

        Dim settings As New CefSettings()
        CefSharp.Cef.Initialize(settings)

        browser = New ChromiumWebBrowser("http://bluelocus.tk/locustv/channels/ssports/ss1.php") With {
            .Dock = DockStyle.Fill
        }
        stream.Controls.Add(browser)

        browser.BrowserSettings.ImageLoadingDisabled = True
    End Sub

I'm currently having a bug issue now, CefSharp.SubProcess

**Comment by Blue-Locus** [comment]
Nevermind, my mistake. one time fix bug

**Comment by amaitland** [comment]
> I'm currently having a bug issue now, CefSharp.SubProcess

Please open a new issue if you encounter a unique problem.
