### ISSUE TITLE
CefSharp.Wpf.Example.exe crash in Windows 7 when shutdown computer in 3.2171.2069

### ISSUE THREAD

**Issue by ming526197zhang** [cefsharp/CefSharp#1240]
I use cefsharp for my application with Version 3.2171.2069, I found my application crash when shutdown computer, I also test CefSharp.Wpf.Example.exe, it has the same problem, the following is my screenshot.
![qq 20150902104825](https://cloud.githubusercontent.com/assets/13885604/9621980/2d5a736c-5160-11e5-8113-4ef71644279d.jpg)

**Comment by amaitland** [comment]
Known issue, fixed by upgrading to the `41` branch.

https://github.com/cefsharp/CefSharp/issues/800#issuecomment-97802045
