### ISSUE TITLE
Windows 10 Universal

### ISSUE THREAD

**Issue by bjarteskogoy** [cefsharp/CefSharp#1241]
Has anyone looked into what would be required to support Windows 10 universal app?

**Comment by amaitland** [comment]
Not in any detail, only research I've done can be see via #1192

I do have a `2454` build that compiles using `VS2015`, so it may work though I think the limited `C++` library means that it's unlikely.

**Comment by amaitland** [comment]
@bjarteskogoy Did you find out anything more?

**Comment by bjarteskogoy** [comment]
Haven't spent time on this, no.

**Comment by amaitland** [comment]
If anyone makes progress with this then please comment and we can reopen.
