### ISSUE TITLE
Form visibility

### ISSUE THREAD

**Issue by bboycs** [cefsharp/CefSharp#1242]
Hi sorry for posting at the wrong place previously.

http://www.codeproject.com/Articles/990346/Using-HTML-as-UI-Elements-in-a-WinForms-Applicatio

i been follow the link above as reference for the create browser form.

I would like to know is that any method to hide the content inside the form (web browser) until the page complete loaded then only i display it?

thanks in advance

**Comment by amaitland** [comment]
What exactly trying to achieve and what have you tried so far?

**Comment by bboycs** [comment]
hi, thanks for the reply..
previously i tried add a picturebox to overlap the form..after that 
wait for the event chromium_NavStateChanged when the e.isloading == false then i set the picturebox visibility to false.
but the action above i tried will force close the form with chromebrowser.

so i looking for help is that any other method can achieve my objective

thanks

**Comment by amaitland** [comment]
Can you fork the `MinimalExample` or `Tutorial` project to demo what your have currently. In theory your solution should work.

**Comment by bboycs** [comment]
hi.. 
i solved the issue with assign the picturebox action to another working thread

thanks
