### ISSUE TITLE
Does high constrast still not work?

### ISSUE THREAD

**Issue by Mecommited** [cefsharp/CefSharp#1245]

**Comment by amaitland** [comment]
`high constrast`? Do you mean `High DPI`?

Progress has been made on `High DPI` on the `43` branch.

**Comment by amaitland** [comment]
As a general rule please include version, flavour, e.g. `WinForms` or `WPF`.

Please take the time to read over https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue (makes my life easier not having to ask the same questions over and over again).

**Comment by amaitland** [comment]
@Mecommited Any further update?

**Comment by Mecommited** [comment]
I looked it up over the net, it seems neither Cef nor Chrome do not support HighContrast mode and Chrome itself requires an extension to work with high contrast mode.

https://chrome.google.com/webstore/detail/high-contrast/djcfdncoelnlbldjfhinnjlhdjlikmph?hl=en

**Comment by amaitland** [comment]
Ok cool, in that case there is nothing we can do. `CEF` does not support extensions so this is likely unsupported.

**Comment by bensonz** [comment]
Hello fellas, does CefSharp support High contrast mode now? We are using the v4.0.30319 and it seems like still no support. But Chrome seems to have included support for high contrast mode
https://support.google.com/chrome/answer/7040464?hl=en#zippy=%2Chigh-contrast-adjust-or-remove-colors
![image](https://user-images.githubusercontent.com/6411481/120594922-3470f300-c474-11eb-9988-2e33892c0133.png)

I can't tell which versions tho.

**Comment by amaitland** [comment]
prefers-color-scheme media queries are supported (#2741).

If you require a feature over and above this you'll need to discuss on https://magpcss.org/ceforum/index.php
