### ISSUE TITLE
43.0.0-pre01 Nuget package won't install VS2015

### ISSUE THREAD

**Issue by MihaMarkic** [cefsharp/CefSharp#1248]
Creating a new WPF 4.6 project in Visual Studio 2015 and then using NuGet. 
Installation will yield this message:
"Severity	Code	Description	Project	File	Line
Error		Could not install package 'cef.redist.x86 3.2357.1287'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0"
where .net version doesn't matter (tried with 4.5 and 4.6 as well). Upgrading from 41.x doesn't work either.
However, a week or so ago I did upgrade successfully. Not sure what changed in between.

**Comment by amaitland** [comment]
> Error Could not install package 'cef.redist.x86 3.2357.1287'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework.

That part is true, it only contains native code.

> Not sure what changed in between.

Did you upgrade `nuget` recently? Likely something has changed there.

**Comment by amaitland** [comment]
Do you have `Nuget 3.0` installed?

**Comment by MihaMarkic** [comment]
Yes, I have 3.1.60724.766 dated 14.8 (latest stable). Not sure if it changed recently.

**Comment by amaitland** [comment]
I have the same version and it installed just fine.

As `VS2015` is so new, I'm not surprised their are little issues here and there. I'm not across all the `Nuget` updates, so there are possibly some changes required to the packages.

**Comment by amaitland** [comment]
@MihaMarkic Did you have any luck tracking this down?

**Comment by MihaMarkic** [comment]
Still failing even with 43.0.0.0. Before "Error Could not install package ..." it says that there is no package in target folder or something like that. No problems with 41.0.0.0. Huh.

**Comment by MihaMarkic** [comment]
Blah, ignore it. Looks like a local problem on my machine somehow. Will post more when I fix it.

**Comment by MihaMarkic** [comment]
Yep. I went to C:\Users\MYUSERNAME\.nuget\packages and there I deleted all Cef packags. On next try it worked fine.
