### ISSUE TITLE
The program '[6832] CefSharp.Wpf.Example.vshost.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.

### ISSUE THREAD

**Issue by luciusli** [cefsharp/CefSharp#1251]
When using custom popup with `LifeSpanHandler` in 43.0.0-pre01, sometimes when I access the parent window with `window.opener.document`, JavaScript will stop execution. After I close the window, and try to reopen the popup, the program will crash with the following error

> The program '[6832] CefSharp.Wpf.Example.vshost.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.

I am trying to find the steps to reproduce this problem, but it seems it occurs quite randomly

**Comment by amaitland** [comment]
You say `43.0.0-pre01`, yet you reference the `CefSharp.Wpf.Example`. Specifically which commit are you using?

The custom popup in general is not quite stable, so could easily have some issue. Can you reproduce the problem using the default popup?

**Comment by luciusli** [comment]
Sorry I mean this commit https://github.com/cefsharp/CefSharp/commit/83ce71e91cf1bdfb8622b78cf389f33b15f8c58e

Default popups work great without issues.

**Comment by amaitland** [comment]
Thanks.

The custom popup is unstable, there's at least one other known issue #1232

**Comment by amaitland** [comment]
Moving this to the `45` milestone, hopefully releasing `43` in the next week or two. In general I'd suggest avoiding `custom popups` as there's quite a few bugs (at least in the `WPF` version)
