### ISSUE TITLE
Feature Request - Implement OnFocusedNodeChanged

### ISSUE THREAD

**Issue by MihaMarkic** [cefsharp/CefSharp#1256]
I need to detect when an input element gets focus (to show the soft keyboard) - like a mobile OS does. I wonder whether there is some supported way in there.
Currently I am thinking of polling for document.activeElement and comparing last one with current.

**Comment by amaitland** [comment]
> I wonder whether there is some supported way in there.

`CEF` it's self does have an `OnFocusedNodeChanged` handler, though it's only called in the `render` process, so it's not currently exposed in `CefSharp`.

http://magpcss.org/ceforum/apidocs3/projects/%28default%29/CefRenderProcessHandler.html#OnFocusedNodeChanged%28CefRefPtr%3CCefBrowser%3E,CefRefPtr%3CCefFrame%3E,CefRefPtr%3CCefDOMNode%3E%29

> Currently I am thinking of polling for document.activeElement and comparing last one with current.

Some form of javascript is likely your best bet as it stands currently.

**Comment by MihaMarkic** [comment]
As usual, kudos for a prompt answer even if is not what I'd like to hear :).
I think javascript approach will work, not as slick though.
I'll take a look at OnFocusedNodeChanged as well to see how hard would be to implement it (any idea?).

**Comment by amaitland** [comment]
> I'll take a look at OnFocusedNodeChanged as well to see how hard would be to implement it (any idea?).

You'd have to generate an `IPC` message containing information about the frame and the node, it's probably not that hard. The native `IPC` is used fairly extensively now, so quite a few examples of sending/receiving messages. I guess there would be some sort of event that's fired when the node change message was received?

**Comment by amaitland** [comment]
Some samples of `IPC`:

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Internals/ClientAdapter.cpp#L998
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Internals/ClientAdapter.cpp#L944

**Comment by MihaMarkic** [comment]
> I guess there would be some sort of event that's fired when the node change message was received?
That'd be a proper way.

**Comment by rlmcneary2** [comment]
I have started implementing support for a notification through IRequestHandler when an element (any type) gets focus. I'm planning to return the following element information: tag name and attributes.
