### ISSUE TITLE
WinForms: browser focus does not seem to work for touch

### ISSUE THREAD

**Issue by illfang** [cefsharp/CefSharp#1258]
Current State:
Only mouse events activate the browser.

Expected:
Touch and mouse events activate the browser

Example:
Do not use the mouse only use touch.
Access http://html5demos.com/contenteditable with 
CefSharp.MinimalExample.WinForms ( cefsharp/CefSharp.MinimalExample@08f4d67e59c7728520839be797eec3d4c70edf55 )
When touching the editable area, the browser cursor is set. However, keyboard events will not be processed by the browser. After clicking one time with the mouse anywhere within the browser and then touching the editable area keyboard input becomes possible until windows are switched.

**Comment by amaitland** [comment]
Take a look at #1054

**Comment by illfang** [comment]
This issue is not related to the system's virtual keyboard it also occurs using a hardware keyboard.

**Comment by amaitland** [comment]
The problem in general relates to focus related touch events in the `WinForms`.

Specifically see
https://github.com/cefsharp/CefSharp/issues/1054#issuecomment-109123540

**Comment by illfang** [comment]
Removing the focus handler results in the same behaviour.
Seems more likely to be related to the ParentFormMessageInterceptor not receiving a NativeMethods.WM_ACTIVATE message for touch.
The received messages for a touch seem to be
528
587
161
528
161

**Comment by amaitland** [comment]
> Seems more likely to be related to the ParentFormMessageInterceptor not receiving a NativeMethods.WM_ACTIVATE message for touch.

`ParentFormMessageInterceptor` deals with high level `Form` related events.

> When touching the editable area, the browser cursor is set. However, keyboard events will not be processed by the browser.

If it's not related to the focus handler getting in the way then it's likely an `upstream` issue.

**Comment by amaitland** [comment]
Possible upstream issue
https://bitbucket.org/chromiumembedded/cef/issues/1223/text-input-broken-on-windows-81-tablets

Can you test with `cefclient` to see if the problem persists?
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

It's possible this might be fixed in a newer version.

**Comment by illfang** [comment]
You are right seems like a CEF bug. Excuse me for not confirming with the test app first.

**Comment by amaitland** [comment]
You can keep the issue open to track the progress.

**Comment by amaitland** [comment]
You maybe able to intercept the `touch` even and manually set focus. I'm not sure what touch events translate to in terms of raw messages though.

**Comment by illfang** [comment]
The problem seems to be fixed for the 3.2494.1320 test app. Might be worth to confirm the issue when the CEF version in CefSharp has been updated further.

**Comment by amaitland** [comment]
Looking at the commits to `master` and `2454` branches for `CEF` and there is one fix that was applied in the last two weeks that only appears in `master` that relates to `keyboard focus/activation`

https://bitbucket.org/chromiumembedded/cef/commits/4a8546efd70700eed1e1f921e85293abf90d2691?at=master

Can you retry your test with a slightly older version, say `CEF 3.2478.1316`?

**Comment by illfang** [comment]
I've tried 3.2478.1316.gaa72f40 and it was impossible to type anything even when using the mouse to set the cursor. 
3.2494.1319.g4a8546e is working as intended with touch only and mouse.

**Comment by illfang** [comment]
Seems like they added a fix between 2015-08-29 and 2015-08-24 which would only leave the commit you mentioned before.

**Comment by MihaMarkic** [comment]
Fcuk on this. What can we do today? git clone, replace cef with newer build?

**Comment by MihaMarkic** [comment]
BTW, can confirm that it works with 2494 but not 2454, no idea about 2478 since it is not there anymore.

**Comment by amaitland** [comment]
> BTW, can confirm that it works with 2494 but not 2454, no idea about 2478 since it is not there anymore.

`CEF` only releases for every second `Chromium` version, so there will never be a `2478` branch, just as an FYI.

Can someone try with `CEF 3.2454.1329.g29055f6`, it's based on `Chromium 45.0.2454.101` which is newer than the current version we're using. A `45.0.0` release will likely be based on this or something slightly newer.

> git clone, replace cef with newer build?

You have to download/compile/repackage a build from `cefbuilds.com`, currently `CEF 3.2494.1328.g2328b9b` looks like a good candidate as their is both `x64` and `x86` builds available.
https://github.com/cefsharp/cef-binary/wiki
https://github.com/cefsharp/CefSharp/wiki/Building-Nupkg-Files

**Comment by MihaMarkic** [comment]
Honestly I gave up on CEF even though you are doing an amazing job.
Now, I tried a shortcut, copied binaries from test application over my test project's package and it crashed at Initialize. Tried briefly debugging but got nowhere. So I ditched CEF and went with IE as it is good enough for my current project.

**Comment by amaitland** [comment]
`master` has been upgraded to `CEF 3.2526.1347`

**Comment by illfang** [comment]
I`ll try the master version soon and report if the issue seems to be resolved.

**Comment by illfang** [comment]
The problem has become a little better.

> After clicking one time with the mouse anywhere within the browser and then touching the editable area keyboard input becomes possible until windows are switched.

Initial input still remains impossible. One click will enable the input.
However, now when windows are switched, the input remains possible. If there has been no click before, a window switch will enable input.

Using the Test App `cef_binary_3.2526.1347.gcf20046_windows32_client` the problem can not be reproduced.
I believe there has been an upstream bug related to this issue which has been solved by now. However, it seems like there is also a bug related to the initial focus of the WinForms CefSharp.

**Comment by illfang** [comment]
The upstream issue seems also to be resolved for `3.2454.1344` of the `cefsharp/45` branch.

**Comment by amaitland** [comment]
> I believe there has been an upstream bug related to this issue which has been solved by now. However, it seems like there is also a bug related to the initial focus of the WinForms CefSharp.

Remove the default focus handler and switch to single threaded message loop is likely the quick solution to this.

**Comment by illfang** [comment]
Ah, yes the Focus Handler from #1054 
Setting `browser.FocusHandler = null;` solves the initial focus problem. Single threaded message loop is not required.
Thank you.

I guess the issue can be marked as resolved since `cefsharp/45`

**Comment by amaitland** [comment]
> Single threaded message loop is not required.

Maybe not in your case, I believe there are some cases that it's required when using `Keyboard` oriented focus.

**Comment by illfang** [comment]
> I believe there are some cases that it's required when using Keyboard oriented focus.

That might be the case. I was just reporting how it behaves in the CefSharp.WinForms.Example
