### ISSUE TITLE
Pepper Flash Opens Console Window

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#1259]
> When I open the first website that uses flash (twitch.tv, for example), a windows console is opened for a split second, I managed to capture a screenshot of it and it says "NOT SANDBOXED". How can I prevent this console window from opening?

There is a known issue with the Pepper flash implementation. Only known solution is to implement sandboxing which is not currently available in `CefSharp`. #697

http://magpcss.org/ceforum/viewtopic.php?f=6&t=13094

**Comment by amaitland** [comment]
Relevant `Chromium` issue https://code.google.com/p/chromium/issues/detail?id=508002

The problem is reproducible with `Chrome` and `no-sandbox` enabled, so hopefully it will be fixed `upstream`

**Comment by amaitland** [comment]
The `Chromium` issue has been marked as `wontfix`, so if this problem affects anyone else please take the time to comment (on the `Chromium` issue linked above).

**Comment by okatip1** [comment]
Is there any solution about this topic?

**Comment by amaitland** [comment]
See http://magpcss.org/ceforum/viewtopic.php?f=6&t=13094 for other options solutions, there is nothing that can be done in `CefSharp`.
