### ISSUE TITLE
Promises from async binding objects not resolving with iframe and dev. tools open

### ISSUE THREAD

**Issue by Antonyo** [cefsharp/CefSharp#1260]
A quite strange bug but a bit annoying for developers, I spent quite some time to figure out the whole scenario.

## Description
If you have an async bound object, no matter whether wcf is enabled or not, the web page calling the bound object has an iframe and the Dev. Tools window opened, the promise returned from calling a method of the async bound object is never resolved.

## Version
43.0.0-pre2 or latest dev. code. `wpf` and `winForms`. Windows 8.1 x86.

## How to recreate

1. Edit `\CefSharp\CefSharp.Example\Resources\BindingTest.html` to add an iframe anywhere, for instance:

```
<body>
    <iframe></iframe>
        <p>
....
```
2. Launch `CefSharp.WinForms.Example` project
3. Open Dev. Tools by going to File > Show Dev Tools
4. Navigate to `custom://cefsharp/BindingTest.html`

The `Async Binding Test` section is not populated since promises are never resolved. 
You can now close the Dev. Tools window and reload the page to see how the `Async Binding Test` now works properly.

**Comment by amaitland** [comment]
Interesting sequence required to reproduce. It's not the first time I've seen the `DevTools` do strange things.

I have no ideas where to start on fixing this one.

**Comment by amaitland** [comment]
> Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError

I now see this in the console

**Comment by amaitland** [comment]
(running with latest `master`)

**Comment by amaitland** [comment]
Appears to be working in `master` now, likely resolved with the merge of #1284

**Comment by amaitland** [comment]
Changes merged into `43` branch, hopefully release `43.0.1` shortly (just needs more testing).

**Comment by amaitland** [comment]
`43.0.1` has been released to `Nuget.org` See https://github.com/cefsharp/CefSharp/releases/tag/v43.0.1 for more details
