### ISSUE TITLE
How to achieve 60FPS in WPF?

### ISSUE THREAD

**Issue by consindo** [cefsharp/CefSharp#1261]
Using the CefSharpMinimalExample, loading http://www.goodboydigital.com/pixijs/bunnymark/ will report 60FPS with the built in JavaScript FPS counter in both the WPF and Winforms implementations.

However, if you look visually, you will see that the Winforms implementation is actually running at 60FPS while the WPF implementation is quite janky and running closer to 30FPS. Using Cefsharp Winforms in a Winforms host under WPF does indeed run at 60FPS, but introduces weird high dpi bugs.

Is it possible to achieve the smooth 60FPS using the CefSharp WPF bindings?

**Comment by illfang** [comment]
You can try the "best performance arguments".

https://github.com/cefsharp/CefSharp/commit/fa89d306e1c50164405e7b8792762c7d3a4ce3c2#diff-f0bbcfc29edf16b3e8fb0d18e42da7f8R197

**Comment by amaitland** [comment]
There is another setting which I don't believe is exposed yet.

http://magpcss.org/ceforum/apidocs3/projects/%28default%29/_cef_browser_settings_t.html#windowless_frame_rate

> The maximum rate in frames per second (fps) that CefRenderHandler::OnPaint will be called for a windowless browser. The actual fps may be lower if the browser cannot generate frames at the requested rate. The minimum value is 1 and the maximum value is 60 (default 30).

**Comment by amaitland** [comment]
I've added `BrowserSettings.WindowLessFrameRate` to `master` and `cefsharp/43` branches

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.Core/BrowserSettings.h#L353

Will be in the next `-pre` release (probably out in a few weeks). In the meantime you can try building from source or use the `CI` builds from https://www.myget.org/F/cefsharp/api/v2

I haven't tested the setting to see if it makes any difference. The link that @illfang provided is likely to boost the speed in some scenarios.

**Comment by consindo** [comment]
I tested out various combinations of the flags in the link that @illfang provided.

- The `disable-gpu-compositing` flag fixes this issue - it brings it up to 60fps without disabling WebGL.
- The `enable-begin-frame-scheduling` flag brings it back down to 30fps, visually and reported by the in built JS benchmark.

I guess my issue is fixed - thanks. I haven't tried the new setting, but I will try building from source and see if it makes any difference.

**Comment by amaitland** [comment]
With both the following enabled and manually specifying `60fps`, the demo reports `60fps`

```
settings.CefCommandLineArgs.Add("disable-gpu-compositing", "1");
settings.CefCommandLineArgs.Add("enable-begin-frame-scheduling", "1");
```

Obviously results with vary greatly depending on hardware.

**Comment by amaitland** [comment]
@consindo Anything else before closing this?

**Comment by consindo** [comment]
@amaitland Nope, issue can be closed - thanks!

**Comment by dhswg20077** [comment]
setting.CefCommandLineArgs.Add("disable-gpu-compositing", "1");
            setting.CefCommandLineArgs.Add("enable-begin-frame-scheduling", "1");

still only 30 fps

**Comment by cristiancarli** [comment]
> setting.CefCommandLineArgs.Add("disable-gpu-compositing", "1");
> setting.CefCommandLineArgs.Add("enable-begin-frame-scheduling", "1");
> 
> still only 30 fps

Also for me only 30 FPS

**Comment by amaitland** [comment]
Make sure you are setting http://cefsharp.github.io/api/71.0.0/html/P_CefSharp_BrowserSettings_WindowlessFrameRate.htm
