### ISSUE TITLE
Launching popup from a page using a custom scheme causes the render process to crash

### ISSUE THREAD

**Issue by haileqsr** [cefsharp/CefSharp#1263]
Steps to reproduce:
- Open the CefSharp WPF example application
- In the execute script pane run the script <code>window.open("http://google.com")</code>

This is because custom schemes need to be registered in both the parent and all sub processes.  When the browser subprocess is run <code>CefAppUnmanagedWrapper::OnRegisterCustomSchemes</code> is executed by Cef before <code>CefAppUnmanagedWrapper::OnRenderThreadCreated</code> so the subprocess has no access to the custom scheme settings at the time of register.

Suggested solution maybe is to share scheme settings through a named pipe before calling <code>CefExecuteProcess</code>

**Comment by amaitland** [comment]
Thanks for the detailed bug report :+1: 

> Suggested solution maybe is to share scheme settings through a named pipe before calling CefExecuteProcess

I'd like to avoid adding another `IPC` mechanism if possible, there's already `WCF` in the mix as well as the `Native IPC` provided by `CEF`, so adding a third technology isn't ideal.

I think the short term quick fix is to pass append the scheme names to the command line params for the `render process`, then just register them with default settings.

Also I think we should raise the problem on `ceforum`, see if there's a better long term solution.

**Comment by haileqsr** [comment]
No worries :smile: , I was actually thinking something similar also in regards to using command args ..I'll also look into the cef forums and raise an issue if it isn't logged already

**Comment by amaitland** [comment]
Sample URL to reproduce this `custom://cefsharp/PopupTest.html`

**Comment by illfang** [comment]
possibly related to #1226

**Comment by amaitland** [comment]
> possibly related to #1226

Maybe worth submitting a `PR` that demo's your problem? Just another test page would do the job.
