### ISSUE TITLE
Host a WPF control in a winform project

### ISSUE THREAD

**Issue by metametametaphysics** [cefsharp/CefSharp#1264]
Hello All,

I create a WinForm project and try to host a WPF control with the cefSharp.wpf in a winform by the elementhost component. The webpage loads normally, however, when I close the application, the application crash. The error message said that:

``` 
An unhandled exception of type 'System.InvalidOperationException' occurred in WindowsBase.dll
Additional information:
The calling thread cannot access this object because a different thread owns it.
``` 

Interestingly, if I create a "WPF project" and add a winForm,  I host a WPF control with the cefSharp.wpf in this winForm by the elementhost component, there is no error message shown

What's wrong? 

WPF UserControl code:
``` 
<UserControl x:Class="wpftest.UserControl1"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:cefSharp="clr-namespace:CefSharp.Wpf;assembly=CefSharp.Wpf"
             mc:Ignorable="d" 
             d:DesignHeight="300" d:DesignWidth="300">
    <Grid Background="LightBlue">
        <cefSharp:ChromiumWebBrowser Grid.Row="0"
        Address="http://www.google.com" />
    </Grid>
</UserControl>
 ``` 

Form1 partial Code:
``` 
  private void Form1_Load(object sender, EventArgs e)
        {
            elementHost1.Child = new UserControl1();
        }
```

**Comment by amaitland** [comment]
Thats not supported. Any reason you don't use the WinForms version?

**Comment by metametametaphysics** [comment]
Because I want to embed a video as a background and make the page with a transparent background.

**Comment by amaitland** [comment]
From memory it's not possible. Your welcome to debug the source and submit a PR with a fix.

**Comment by amaitland** [comment]
You should try manually `removing/disposing` of the control before the form closes.

Also try initializing `Cef` manually with `shutdownOnProcessExit = false`, then manually call `Cef.Shutdown()` before your application closes. You need to initialize/shutdown on the `UI thread`

https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.Core/Cef.h#L156

**Comment by amaitland** [comment]
@metametametaphysics Any follow up on this?

**Comment by amaitland** [comment]
Closing due to lack of feedback.
