### ISSUE TITLE
Flash is inactive, when it is bigger than window of program

### ISSUE THREAD

**Issue by MartySVK** [cefsharp/CefSharp#1265]
Hi, I have a problem with NPAPI plugins like flash and Unity Web Player.
x86
winforms
all cefsharp versions
please check the video - https://www.youtube.com/watch?v=o_KxbrDM0ts
I used CefSharp.MinimalExample with small edit:
```
//WindowState = FormWindowState.Maximized;
browser = new ChromiumWebBrowser("http://www.gameflare.com/embed/car-eats-car-5/")
```

The problem will happen, when the program starts with the window, which is smaller than flash object. When you will change the size to bigger than flash obejct, flash will be inactivated (unclickable). The same will happen with Unity. But pepper flash works great.

But it looks like, that it is working with WPF.

Is it a bug ? Or do I need some additional settings to solve my problem ?

Thanks a lot

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

**Comment by MartySVK** [comment]
thanks, so it is probably cef bug
