### ISSUE TITLE
TL;DR; on scrolling touch support, please

### ISSUE THREAD

**Issue by MihaMarkic** [cefsharp/CefSharp#1266]
Can somebody TL;DR; on the status of scrolling browser content with a touch screen using a finger.
Chromium supports it, CefSharp doesn't apparently. Would this be correct status?
If yes, where is the problem, is it in CEF I suppose?

**Comment by amaitland** [comment]
Touch in WPF? See #975

Far asIi know touch scroll works fine in WinForms

**Comment by MihaMarkic** [comment]
Yes, WPF.
How does it work in WinForms? By translating touch events to mousewheel? I looked at Cef and there are no SendTouch* methods or anything.

**Comment by amaitland** [comment]
WinForms has native support. CEF has yet to implement touch events in OSR mode.

**Comment by amaitland** [comment]
https://bitbucket.org/chromiumembedded/cef/issues/1059

**Comment by amaitland** [comment]
https://github.com/amaitland/CefSharp/commit/d854551a90e55c917a80d60bc67cf641f2f02d9b

This is as far as I got with attempting to use the mouse wheel event

**Comment by amaitland** [comment]
Closing this issue as duplicate..
