### ISSUE TITLE
Intercepting WinForms mouse and touch events

### ISSUE THREAD

**Issue by MihaMarkic** [cefsharp/CefSharp#1269]
Somehow it looks like it is hard to intercept both touch and mouse events for WinForms. The usual suspects aren't fired (i.e. MouseDown event). I see that some messages could be intercepted by overriding WndProc but not many.

I'm trying to figure out when browser is idling (user doesn't do anything) and thus I'm interested in Mouse/Touch Up/Down events.

**Comment by amaitland** [comment]
You need to hook a lower level handle, there are examples floating around see
https://github.com/cefsharp/CefSharp/issues/1098#issuecomment-118208651

**Comment by MihaMarkic** [comment]
Most excellent, thanks.
