### ISSUE TITLE
WPF, WebGL Inspected target disconnected

### ISSUE THREAD

**Issue by mortalV** [cefsharp/CefSharp#1270]
CefSharp  45.0.0.0
Cef 3.2454.1317.0
WPF control. Builded from master branch.

Webpage with webgl content has worked fine before added some 3d objects. 
Now it render scene but when try move camera DevTools show message "Inspected target disconnected. Once it reloads we will attach to it automatically." and browser freezes.

Chrome in this case freezes for 1 second (I think at this moment textures loading to GPU) but after unfreeze works normal.

WPF minimal example also works but not load some textures because not access local files (allow-file-access-from-files).

My app uses also parameters "disable-gpu-compositing" and "enable-begin-frame-scheduling".

In debug.log this information

[0915/174622:ERROR:renderer_main.cc(200)] Running without renderer sandbox
[0915/174623:ERROR:renderer_main.cc(200)] Running without renderer sandbox
[0915/174623:WARNING:CONSOLE(0)] "/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source:  (0)
[0915/174624:ERROR:ipc_channel_win.cc(435)] pipe error: 232
[0915/174629:ERROR:renderer_main.cc(200)] Running without renderer sandbox
[0915/174633:ERROR:renderer_main.cc(200)] Running without renderer sandbox
[0915/174633:WARNING:CONSOLE(0)] "/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source:  (0) 

Any ideas what's wrong and why CefSharp freezes?
Thanks.

Update. 
After enabling local file access WinForms and WPF examples crashed with message "Your seeing this message as the render process has crashed"

**Comment by amaitland** [comment]
> My app uses also parameters "disable-gpu-compositing" and "enable-begin-frame-scheduling".

Have you tried without any params? 

https://bitbucket.org/chromiumembedded/cef/commits/e3c1d8632eb43c1c2793d71639f3f5695696a5e8#Ltests/cefclient/browser/client_app_browser.ccT31

Can you try the relevant reference `cefclient` example? https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

**Comment by mortalV** [comment]
I've found more critical conditions.
1. cefclient with allow local files load works fine.
2. main problem with loading images for textures. 
2.1. 4096*4096 texture(S) works fine.
2.2. 8192*4096 and above crush render.

**Comment by mortalV** [comment]
And I think problem not only for WPF. WinForms also crushed.

**Comment by amaitland** [comment]
Do you have a sample webpage to reproduce the problem? 

> 1. cefclient with allow local files load works fine.

Did you compare exactly the same version e.g. `3.2454.1317` and use the off screen command line argument?

**Comment by mortalV** [comment]
On cefbuilds version 3.2454.1317 only for x64 so I've used 3.2454.1320 x86

With --off-screen-rendering-enabled argument in logs "Error creating WebGL context" 
But with --multi-threaded-message-loop and --disable-gpu-compositing and --enable-begin-frame-scheduling all works fine

Unfortunately application it's not a website but complex local application with many data. 
Perhaps I will prepare a test web page which load big texture , but not now (sorry)

**Comment by amaitland** [comment]
> On cefbuilds version 3.2454.1317 only for x64 so I've used 3.2454.1320 x86

Click `more revisions` to find the `3.2454.1317` build. Both the `x86` and `x64` versions were sourced from `cefbuilds.com`

> With --off-screen-rendering-enabled argument in logs "Error creating WebGL context"

If that's the case then it's unlikely to work in the `WPF` version of `CefSharp`. You should also try your app on a different machine, make sure it's not a hardware related incompatibility. `Chrome` enables/disables features based on the hardware your running to workaround known bugs, whereas in `CEF` you have to manually tweaks the configuration.

**Comment by mortalV** [comment]
I've test exactly with 3.2454.1317 x86 - results the same.

I still think this problem not only for WPF. WinForms also have this problem.

Hardware can't be problem because GPU support 16K x 16K textures

**Comment by amaitland** [comment]
> I still think this problem not only for WPF. WinForms also have this problem.

My guess is that's it's an `upstream` problem if you can reproduce using `WinForms`, will need an example to confirm.

> Hardware can't be problem because GPU support 16K x 16K textures

Make sure your drivers are up to date.

Open `chrome://gpu/` in `Chrome` (preferable as close to the version of `CEF` as possible), you'll see detailed information on your graphics card.

See also
https://code.google.com/p/chromium/codesearch#chromium/src/gpu/config/software_rendering_list_json.cc

**Comment by mortalV** [comment]
I've done samples.

http://87.242.76.45/webgltest/test.html - will crush
http://87.242.76.45/webgltest/test2.html - will works

first used texture with dimensions 8192 x 4096
second the same but texture 4096 x 4096

**Comment by amaitland** [comment]
> http://87.242.76.45/webgltest/test.html - will crush
> http://87.242.76.45/webgltest/test2.html - will works

Both work for me using the latest `master` branch. Tested with `CefSharp.Wpf.Example` in both `x86` and `x64`

**Comment by amaitland** [comment]
What hardware are you using? Are you sure your drivers are up to date?

**Comment by amaitland** [comment]
Tested on a different machine with an `NVIDIA` graphics card this time (Previously `ATI`) and I'm not seeing any problems.

**Comment by mortalV** [comment]
My config GeForce GTX670, latest drivers, Win 10, 16Gb RAM
In CEF and Chrome all works as expected even if open simultaneously.

I've fetch last master one more time and make clean build.
1. x64 version WPF and WinForms works perfectly
2. x86 sometimes works sometimes no. No in most cases. Specially after Reload crush in 100%. 
Did you try make reload of problem page several times?

I think something wrong with memory allocation in .net because in the same time I have a problem with create Bitmap with dimensions 16K x 8K. Do you have any ideas how check think about memory in CefSharp?

p.s. maybe in future I'll use x64 version and close this problem for me but now application uses some x86 libraries and required redesign for x64.

**Comment by amaitland** [comment]
> My config GeForce GTX670, latest drivers, Win 10, 16Gb RAM

I'd suggest trying on a different machine, preferably one with `Windows 7` or `Windows 8.1` installed.

> x86 sometimes works sometimes no. No in most cases. Specially after Reload crush in 100%.

The fact that it's intermittent leads me to believe it's an `upstream` issue, If the problem occurs in the `WinForms` version then `CefSharp` is a very minimal wrapper around `CEF` in this instance.

It's probably worth downloading the release symbols from `cefbuilds.com`, see if `CEF` will provide a more detailed error message.

> p.s. maybe in future I'll use x64 version and close this problem for me but now application uses some x86 libraries and required redesign for x64.

Your welcome to leave the problem open. To be honest there is little more that I can do.

**Comment by amaitland** [comment]
It's also worth trying the `cefsharp/43` branch, it's using a release version of `Chromium` where as the current `master` is a pre-release version of `Chromium`

The next official release will be `43.0.0`

**Comment by amaitland** [comment]
Make sure your building for `Release`

**Comment by amaitland** [comment]
@mortalV Any further update on this?

`master` has been updated to a release version of `Chromium`.

**Comment by amaitland** [comment]
Closing due to lack of feedback.
