### ISSUE TITLE
Windows 8 popup keyboard

### ISSUE THREAD

**Issue by DDeas** [cefsharp/CefSharp#1274]
When focusing on web input elements using a tablet (tested on Surface Pro), the native windows popup keyboard does not appear.

This feature is imperative for tablet development. Can it please be added.

I am using CefSharp Chromium (WinForms) 41.0.0, with Cef 3.2272.32

**Comment by amaitland** [comment]
See  #1054

**Comment by DDeas** [comment]
Thanks, but that is not the same problem. That is a focusing issue, where the element does not appear to receive full focus (they refer to a call I originally raised). 

The issue I am talking about, is that when a web element inside the chromium browser is focused (bearing in mind I have already implemented the work around described in #1054 >> #684) the native windows virtual keyboard doesnt popup. Whereas the same page loaded in Chrome, does invoke the popup keyboard.

I have download CEF Binary 3.2272.32 from CEF builds.com and used their browser (CEFClient.exe), and this behaves as i would expect (keyboard pops up and dismisses itself).

**Comment by amaitland** [comment]
> This feature is imperative for tablet development. Can it please be added.

It's not really so much a feature, if it works in `cefclient` then it's a matter of determining the difference in how it's implemented.

> The issue I am talking about, is that when a web element inside the chromium browser is focused (bearing in mind I have already implemented the work around described in #1054 >> #684) the native windows virtual keyboard doesnt popup. Whereas the same page loaded in Chrome, does invoke the popup keyboard.

This information probably should have been included in your original post?

> I have download CEF Binary 3.2272.32 from CEF builds.com and used their browser (CEFClient.exe), and this behaves as i would expect (keyboard pops up and dismisses itself).

Can you test with the `cefsharp/43` branch? Based on the `CEF 2357`

**Comment by DDeas** [comment]
> This information probably should have been included in your original post?

Apologies... I didn't want to confuse the two, as they are separate issues.

OK, I built the winforms example application from versions 43 and 37 and tested with both, it appears this was working in v37, but not now in 43. Ill edit this response in a minute with what version it stopped working in.

**Comment by DDeas** [comment]
Actually, it also worked in .43 once I undocked from the type cover. So the issue is definitely with my own implementation.

Ill close this ticket once I have worked out where the issue is, in case anyone else finds this useful in future.

**Comment by DDeas** [comment]
Issue was with a workaround we'd put in place at the beggining of this project, to counteract this exact problem. Once I removed that, this started working perfectly. So the issue must have been resolved some time back without us realizing.

Can we delete the question please?

**Comment by amaitland** [comment]
> Can we delete the question please?

Unfortunately `GitHub` doesn't support deleting of questions
