### ISSUE TITLE
Feature Request - Print to PDF

### ISSUE THREAD

**Issue by makealeft** [cefsharp/CefSharp#1275]
Cef now supports Print To PDF.  It was added it June 4, 2015 https://bitbucket.org/chromiumembedded/cef/commits/85f8368

Any timeline when this will be supported? This would be a great feature.

**Comment by amaitland** [comment]
> Any timeline when this will be supported?

Interested in implementing the functionality yourself?

**Comment by makealeft** [comment]
I actually tried and spent a couple of days on it but couldn't get it to
compile.  Unfortunately I don't know C++.  I know you must get lots of
requests so sorry if that came across rude.  All I meant by it was are you
planning on adding the functionality and if there was any timeline.

**Comment by amaitland** [comment]
> I actually tried and spent a couple of days on it but couldn't get it to compile. Unfortunately I don't know C++

If you push the changes to `GitHub`, I can take a look maybe provide some pointers.

> I know you must get lots of requests so sorry if that came across rude.

No offense taken :smile: 

> All I meant by it was are you planning on adding the functionality and if there was any timeline.

No plans as this stage, hopefully be included in the `45` release, though will depend on how much time I have.

**Comment by arsher** [comment]
I was experimenting with this. I'll tidy up a bit and create a PR.

**Comment by amaitland** [comment]
This should now be avaiable in `master` See PR #1278

**Comment by makealeft** [comment]
You guys rock!

**Comment by ismailkocacan** [comment]
this feature available in winforms ?

**Comment by amaitland** [comment]
> this feature available in winforms ?

Yes. You need at least version `45.0.0`.

 We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask any followup questions there.

**Comment by ismailkocacan** [comment]
thank you  @amaitland for response.
