### ISSUE TITLE
eat memory

### ISSUE THREAD

**Issue by gitlsl** [cefsharp/CefSharp#1280]
i seted cache path and new 200 instances,    reload all the urls of the 200 instances in a timer callback,   the memory is more and more large and never go down , eat more than 18G memory,  is it Memory leak? or how should i do to make memory down

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue

**Comment by amaitland** [comment]
@gitlsl Can you provide more information as per the link above?

**Comment by gitlsl** [comment]
@amaitland 
i use the newest version, my purpose is open a website on timer (for example  30seconds)


code like :
            Cef.Initialize(new CefSettings()
            {
               CachePath = "cache",
                IgnoreCertificateErrors = true
            });
            Cef.SetCookiePath("cookie", true);

privite void timer_tick()
{
   browswe.reload();
}
i found the memory is more and more large and never go down

**Comment by amaitland** [comment]
> i use the newest version, my purpose is open a website on timer (for example 30seconds)

Include the exact version your using please. Latest release version is `43.0.0`

**Comment by amaitland** [comment]
I edited your code above to make it easier to read, please markup your code in future posts.

**Comment by gitlsl** [comment]
<package id="CefSharp.WinForms" version="41.0.1" targetFramework="net40" />
private void Form1_Load(object sender, EventArgs e)
{
    Browser.Load(“http://www.google.com”);
    timer1.Enable = true;
}
private void timer1_Tick(object sender, EventArgs e)
{
     Browser.Reload();
}
Over time more and more memory and never go down

**Comment by amaitland** [comment]
> Over time more and more memory and never go down

`41.0.1` is known to have some memory leaks, please upgrade to `43.0.0`

(Again, please take the time to markup your code).

**Comment by gitlsl** [comment]
@amaitland 3q very much

**Comment by amaitland** [comment]
@gitlsl happy to close this?
