### ISSUE TITLE
Certain Javascript variables are not accessible from JS code from C#

### ISSUE THREAD

**Issue by roschler** [cefsharp/CefSharp#1281]
I am having a really strange problem when calling JS code from C# via the CefSharp ExecuteScriptAsync() method.  I have a global variable that is initialized via code that is triggered by the jQuery document ready function, called during the window.onLoad() handler:

```javascript
var g_GlobalObj = null;

   window.onload = function ()
    {
        // jQuery document ready function.
        $(document).ready(function (e)
        { 
            ... // g_GlobalObj is created/instantiated during a call to the TeeChart charting package.  
        }
    }
```

I created a timer function just so I could set a breakpoint in the Javascript code while in the Chrome DevTools.  When I hit the breakpoint, g_GlobalObj is fully accessible.  However, when I set a breakpoint in a JS method that is called by my host C# code that embedes CefSharp, via an ExecuteScriptAsync() call, g_GlobalObj is *not* accessible and this leads to reference Exceptions from code that is trying to access it.  Also, if I put a watch on g_GlobalObj the DevTools Watch windows says "Not Available".

Triggering a breakpoint on the helper timer function after the Exception(s) again shows g_GlobalObj as fully accessible.  Is this because I am in a different process, that is, in the C# process instead of the Chrome process wrapped by CefSharp?

Has anybody encountered this before and know of a quick solution?  Or do I have to move everything into an initialization method called by the C# code at startup, so that all objects are in the same process space?  I'm hoping not because that would be a sizable job.

**Comment by jankurianski** [comment]
I've reformatted your code so it is readable.  Here's how you can do it for your next post:
https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting

**Comment by jankurianski** [comment]
As to your question... `ExecuteScriptAsync` is time sensitive, and there is no guarantee your `g_GlobalObj` will have been defined yet, or even that your JavaScript code has been parsed yet.  I have had many timing issues because my `ExecuteScriptAsync` has been executed and relies on variables created by `$(document).ready()`.

Possible solutions:
- Retry the `ExecuteScriptAsync` if `g_GlobalObj` is not defined yet.  `EvaluateScriptAsync` is more useful for this because you could return a boolean flag indicating whether it succeeded or not.
- Have your JavaScript code send a signal back to `C#` indicating it has loaded completely.  I personally do this using a custom scheme.  Then my `C#` code knows it is safe to call `ExecuteScriptAsync`

**Comment by roschler** [comment]
Hello Jan,

Thanks for the code formatting tip!

As far as a timing problem concerned, the only problem with that idea is that I believe the test I ran rules out that possibility.  Please point out any errors in my logic.  To summarize:

- I put a breakpoint on the helper timer function.  When that breakpoint was hit, DevTools showed g_GlobalObj as fully created with a valid value.  Then I deactivated the breakpoint.

- After confirming that g_GlobalObj was indeed valid, I triggered a JS call that accesses g_GlobalObj via ExecuteScriptAsync() .  It was not accessible.

- To double-check, I re-enabled the breakpoint on the helper timer function and again, it showed g_GlobalObj as holding a valid value.

Also, I repeated the above test several times.

UPDATE: I just added code so that when the Browser reload event fires, the C# objects I use and expose to the CefSharp Javascript engine are re-registered.  This did not change anything and the problem still persists.

**Comment by jankurianski** [comment]
My only other thought is that the DevTools debugging is related.  I say this because I have noticed that whilst I am debugging `ExecuteScriptAsync`-fired code, breakpoints in normal browser event code (such as `setTimeout`) are not hit, and vice versa.  Does the problem occur if you do not have the DevTools window open?

Apart from this I'm out of speculative ideas, but if you could post an example of the problem on GitHub (preferably by forking `CefSharp` and modifying the existing examples), then I'm sure myself or others could help further.

**Comment by amaitland** [comment]
@roschler What version are you using? Have you tried `43.0.0`?

**Comment by amaitland** [comment]
Also as a general rule if you post somewhere else, please make reference to that post.

http://stackoverflow.com/questions/32706255/cant-access-certain-javascript-objects-during-cefsharp-executescriptasync-cal

**Comment by roschler** [comment]
Hello Jan and Alex.  Thank  you for your tips.  Late at night and I can't see straight so I'll follow up with your questions tomorrow.  Crazy deadline bearing down on me.  Apologies in advance.

I still have the problem.  However, this code worked fine in an older rev of my app with a different web page being loaded into the CefSharp browser.  However, it is the exactsame version of CefSharp between the two cases.  In any case, I believe I am seeing some strange behavior in my Javascript registered object.  

The C# class object that I expose to Javascript is registered with the name "SharedFlags".
I have a property in the C# class object that I expose called TriggerBreakpoint.  As a test, I put a Visual Studio breakpoint in that property's getter.  I then added code in the Javascript code that fires in the web page's onload() event handler to set "SharedFlags.TriggerBreakpoint" to TRUE.  I then put a DevTools breakpoint on that Javascript line.  

When that breakpoint is hit, I see the following anomalous behavior.  If I hover the cursor over "SharedFlags.TriggerBreakpoint", the qualified property name, **nothing** happens and I get "undefined" displayed by the DevTools hover tip, when I should be getting back "false" for that property since that is what the property is initialized to on the C# side.  However, if I hover the cursor over the top level registered object, the object named "SharedFlags", the break point **is** hit and I see this on the stack in the Visual Studio C# debugger:

ExecuteScriptAsync
 	CefSharp.dll!CefSharp.Internals.JavascriptObjectRepository.CreateJavaScriptProperty.AnonymousMethod__10(object o) Line 203	C#

It's as if the registered object isn't bound yet, but when the DevTools debugger tries to evaluate it for tooltip help, the object or at least it's interface is suddenly instantiated.  

Are there any clues in this anecdotal evidence to help diagnose the problem and is this the proper behaviour?  

Note, I did add diagnostic code and everything is definitely happening in the **same** process, but **different** threads, if that matters.  The calls into the CefSharp Javascript code "from" the C# side happens on one thread, and the calls coming "from" the CefSharp Javascript code into the C# side happen on another.  But I assume that Javascript variables (data and code space) can be shared across threads in the same process?

**Comment by amaitland** [comment]
So for reference `JSB` happens in a synchronous fashion and as such you're likely blocking the `render` thread by putting breakpoints in your `JSB` methods. So don't be surprised that things don't show up quite as you expected them to.

> Are there any clues in this anecdotal evidence to help diagnose the problem and is this the proper behaviour?

Your describing quite a complex set of technical characteristics, without a workable sample it's really hard to say anything.

> But I assume that Javascript variables (data and code space) can be shared across threads in the same process?

As `JSB` is executed in the `render` process, it shouldn't be relevant unless you've got some kind of race condition where your reading and writing at the same time.

**Comment by amaitland** [comment]
@roschler Are you able to provide an example that reproduces your problem?

**Comment by amaitland** [comment]
Closing due to lack of feedback.
