### ISSUE TITLE
v43: Google reports cookies not enabled

### ISSUE THREAD

**Issue by jamespearce2006** [cefsharp/CefSharp#1286]
I just grabbed the 43 branch, and I've run the WpfExample in both x86 and x64.
In both cases, attempting to log into Google results in this error:

![image](https://cloud.githubusercontent.com/assets/12157851/10075866/1226f436-62d0-11e5-82e2-68793b79792c.png)

I also see the same with my own app, even though I'm calling SetStoragePath on the global cookie manager.

Am I doing something wrong?

Update:
The problem seems to be with the SetSupportedSchemes call. If this is called, cookies don't seem to work correctly.

**Comment by amaitland** [comment]
Easy enough to workaround

https://github.com/cefsharp/CefSharp/commit/94c508eb0b858ff364699011b6dd95f4e2183b6d

**Comment by amaitland** [comment]
I believe this was fixed `upstream`

https://bitbucket.org/chromiumembedded/cef/commits/29bd7d2c53d01653e0e823f7e85a414390f138d8?at=master

**Comment by jamespearce2006** [comment]
That works. Thanks
