### ISSUE TITLE
After updated to the version 43 all RegisterJsObject() calls fails

### ISSUE THREAD

**Issue by DominikPalo** [cefsharp/CefSharp#1287]
I've updated the library to the version 43 and now all calls to the RegisterJsObject() throws an exception:  `Browser is already initialized. RegisterJsObject must becalled before the underlying CEF browser is created.`

I'm binding my WebBrowser from WPF control to the ViewModel and calling RegisterJsObject() instantly after the WebBrowser is created (before browser loads URL). In older versions it worked without problems.

My XAML: 
```
    <cefSharp:ChromiumWebBrowser
            Address="{Binding Address, Mode=TwoWay}" 
            WebBrowser="{Binding WebBrowser, Mode=OneWayToSource}" />
```

My ViewModel contains
```
        public ChromiumWebBrowser WebBrowser {
            get 
            { 
                return _webBrowser; 
            }
            set 
            { 
                _webBrowser = value; 
                 if (_webBrowser != null) OnBrowserCreated(); 
            } 
        }

        private void OnBrowserCreated()
        {
            WebBrowser.RegisterJsObject("bound", jsBoundObject); //this fails
        }     
```

**Comment by amaitland** [comment]
@DominikPalo I take it you figured it out?

The message is supposed to be self explanatory. Objects need to be registered before the browser has been `initialized` otherwise they won't be registered correctly.

**Comment by erikipedia** [comment]
Same problem, and the solution isn't readily apparent. The XAML binding OneWayToSource is what constructs the WebBrowser, but removing that and creating the WebBrowser inside the view model doesn't work either (IBrowser instance is null. Browser has likely not finished initializing or is in the process of disposing). Is there a tutorial for creating a databound web browser in v43, that can display the same page with multiple calls to RegisterJsObject? Because I haven't found one.

**Comment by amaitland** [comment]
> but removing that and creating the WebBrowser inside the view model doesn't work either (IBrowser instance is null. Browser has likely not finished initializing or is in the process of disposing).

What `IBrowser` instance are you referring to?

> Is there a tutorial for creating a databound web browser in v43, that can display the same page with multiple calls to RegisterJsObject? Because I haven't found one.

No such tutorial exists. It's not that simple, there's only a very small window to bind an object before the browser initializes. To do that properly then you'd need to implement #602

**Comment by erikipedia** [comment]
Okay, but what changed in version 43? I mean, I wouldn't be surprised to find out I've been doing it wrong, but doing it wrong got the desired result up until now. Just trying to understand better how it works. So if you can only call into RegisterJsObject once, is the preferred method to run EvaluateScript against a JS method to update the object when it needs to change?

**Comment by GitHubber10** [comment]
I would like to hear an answer to that question, too. Just like you, @erikipedia I recently upgraded from version 41.0.1 to 43.0.1 and now face the same issue that you ran into.

**Comment by canton7** [comment]
I ended up putting a `ContentControl` in the View, creating the `ChromiumWebBrowser` in the ViewModel, and binding the `ContentControl`'s `Content` property to that `ChromiumWebBrowser`. That way I can call `RegisterJsObject` immediately after the `ChromiumWebBrowser` is created.

It stinks a bit, but it seems to work.

**Comment by RafPe** [comment]
In my solution I'm using AutoFac and my solution is following 

* I register my view so I do have only one single instance 
````
                ContainerHelper.Builder.RegisterType<PlayerViewModel>()
                .AsSelf()
                .AsImplementedInterfaces()
                .SingleInstance();
```

* In my view I have used public ChromiumWebBrowser object as @DominikPalo 
```
        private ChromiumWebBrowser  _webBrowser;

        public ChromiumWebBrowser WebBrowser
        {
            get
            {
                return _webBrowser;
            }
            set
            {
                _webBrowser = value;
            }
        }
```

* Then in the constructor I have the following 
```

            _webBrowser = new ChromiumWebBrowser() {Address = "file:///C:/temp/testme.html"};
            _webBrowser.FrameLoadEnd += delegate(object sender, FrameLoadEndEventArgs args)
            {
                this.isBrowserReady = true;
            };
```

* and in XAML used suggestion of @canton7 
```
        <ContentControl Grid.Row="1" Content="{Binding WebBrowser,Mode=TwoWay}" >
```

And since then have no problem with initialisation of browser and all my actions I preceed with 
```
If (isBrowserReady) { .... } 
```

Hope this would help someone - and since I'm hobby dev constructive feedback much welcome!
