### ISSUE TITLE
BrowserTabViewModel.cs in the example WPF project is not compatible with version 43

### ISSUE THREAD

**Issue by DominikPalo** [cefsharp/CefSharp#1291]
The BrowserTabViewModel.cs contains calls `IWpfWebBrowser. ExecuteScriptAsync()` and `IWpfWebBrowser.EvaluateScriptAsync()` which are not working with version 43. Please update this  example. 

I'm also didn't find in the documentation how can I now call these methods, but I found that these methods were moved to the `IFrame.cs` interface so now can be called using `IWebBrowser.GetBrowser().MainFrame.ExecuteJavaScriptAsync()` and `IWebBrowser.GetBrowser().MainFrame.EvaluteScriptAsync()`

**Comment by amaitland** [comment]
Calls should be the same, the `API` uses extension methods now. The live in the `CefSharp` namespace, so work without making any changes.

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp/WebBrowserExtensions.cs#L584

> Please update this example.

Your welcome to submit a `PR`

**Comment by amaitland** [comment]
Quick test and the `js` example may be outdated, the functionality still works.

**Comment by amaitland** [comment]
> Quick test and the js example may be outdated, the functionality still works.

Actually that works as expected, it's just further down the page than it used to be.
