### ISSUE TITLE
How to know the frame of all load completed?

### ISSUE THREAD

**Issue by looselive** [cefsharp/CefSharp#1294]
If a website have any redirect(server 301,client http-equiv="Refresh" of html, "location.href" of javascript), example: https://w.mail.qq.com
the event of "FrameLoadEnd" will trigger multiple times, I want to know what time of the frames load completed?
Is there any way?
thanks!

**Comment by amaitland** [comment]
Can you be more specific? 

> I want to know what time of the frames load completed?

What time? Like how long it takes?

**Comment by looselive** [comment]
Until the page has no jump

**Comment by amaitland** [comment]
What's jump? That's not a term I've used in the context of a web browser.

For overall page loading status I like to use the `LoadingStateChanged` event

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.OffScreen.Example/Program.cs#L98

If your looking for something else then please be as clear as possible in what it is your trying to achieve.

**Comment by gitlsl** [comment]
@looselive  你英文比我好多了 。。
may be he wants to know when the website is loaded all,redirect frames above

**Comment by looselive** [comment]
Example,We Open the url :"http://mail.qq.com", It will jump to "https://mail.qq.com/cgi-bin/loginpage" (May be it's used server redirect).
https://mail.qq.com/cgi-bin/loginpage source code:
```html
<!DOCTYPE html>
<script>
(function() {
location.replace("https://w.mail.qq.com");
}
</script>
```
https://w.mail.qq.com source code:
```html
<meta http-equiv="Refresh" content="0;url=https://w.mail.qq.com/cgi-bin/loginpage" />
```
How to know this webpage https://w.mail.qq.com/cgi-bin/loginpage load complete?

**Comment by jankurianski** [comment]
1. When `LoadingStateChanged` event fires, set a timer for 500 milliseconds.
2. If the event fires again, clear the existing timer and set a new timer.
3. When the timer callback is finally fired, the load is complete.

**Comment by amaitland** [comment]
Also take a look at `IRequestHandler.OnResourceRedirect`

`upstream` doco http://magpcss.org/ceforum/apidocs3/projects/%28default%29/CefRequestHandler.html#OnResourceRedirect%28CefRefPtr%3CCefBrowser%3E,CefRefPtr%3CCefFrame%3E,CefRefPtr%3CCefRequest%3E,CefString&%29

**Comment by looselive** [comment]
3Q
