### ISSUE TITLE
Binding Javascript Children

### ISSUE THREAD

**Issue by airbrowsetechnologies** [cefsharp/CefSharp#1295]
I'm wondering if it is currently possible to bind Javascript children callbacks.
For example I know you can call something like 
`myGlobalObj.doSomething();`

but what about 
`myGlobalObj.child.doSomething(); myGlobalObj.child2.doSomething();`

I have not found a way yet and am wondering if it is possible. If not this would be a great feature.
Thanks!

**Comment by amaitland** [comment]
> I'm wondering if it is currently possible to bind Javascript children callbacks.

Do you mean `functions`? Your code sample doesn't show a callback.

In the context of the `CefSharp.Wpf.Example` project you can already execute

```c#
bound.subObject.getMyType();
```

If your trying to do something else, please provide a more detailed code example.

**Comment by airbrowsetechnologies** [comment]
Yes that's what I meant. Sorry I was at a lack of words.

So I know how to get to this point:

` browser.RegisterJsObject("MyObject", New MyObject, False)`
```     
     Public Class MyObject
        Public Function doSomething()
            Return True
        End Function
     End Class
``` 
How would I bind the subObject?
Would creating an object in the class do that automatically?
```     
     Public Class MyObject
         Public subItem as new SubItem

         Public Class SubItem
             Public Function doSomething()
                 Return True
             End Function
         End Class
 

        Public Function doSomething()
            Return True
        End Function
     End Class
``` 

or do I have to bind it with `browser.RegisterJsObject("kratos.subObject", New SubObject, False)` ?
I have tried both and both say that `kratos.subObject.doSomething();` is null when executed through the console.

**Comment by amaitland** [comment]
> or do I have to bind it with browser.RegisterJsObject("kratos.subObject", New SubObject, False) ?

No, simply specifying a property is enough. See https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.Example/BoundObject.cs#L45

Have a look at the example projects for a reference.

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.Example/Resources/BindingTest.html

**Comment by airbrowsetechnologies** [comment]
Ohhh. I see. I was defining a variable not a property. Thanks.
