### ISSUE TITLE
Unable to get CefSharp (43) working in WPF

### ISSUE THREAD

**Issue by rocky050371** [cefsharp/CefSharp#1297]
I first ensured the project was set to build in x86, I then downloaded the latest NuGet package - CefSharp.WPF (43), I saved the project, closed it then reopened it. The project builds fine, however when I add the following:

 xmlns:cefSharp="clr-namespace:CefSharp.Wpf;assembly=CefSharp.Wpf"

  cefSharp:ChromiumWebBrowser Address="http://www.google.com"

The designer shows the following

```
Could not load file or assembly 'CefSharp.Core, Version=43.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138' or one of its dependencies. The system cannot find the file specified.
```

I have ensured that all required distribution files are in the relevant folder.

(Visual C++ Redist is installed)

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#Wpf_designer

There is no designer support at this point in time.

**Comment by amaitland** [comment]
For a working example of the `43.0.0` release check out the `MinimalExample` project.

https://github.com/cefsharp/CefSharp.MinimalExample

**Comment by rocky050371** [comment]
So there is no way I can use it in the designer?

**Comment by amaitland** [comment]
> So there is no way I can use it in the designer?

Short answer, no.

Long answer: maybe See https://groups.google.com/forum/#!topic/cefsharp/rGGXh6wAkCU
(I've never tried, as I don't personally use the designer, so I can't provide any more information than the link).

**Comment by rocky050371** [comment]
Thanks for your help

**Comment by rocky050371** [comment]
Having looked at the code, I ideally don't want to break the pattern, how would I go about setting up bindings and keeping the code in the view?

**Comment by rocky050371** [comment]
Does it support Binding? If not, is there a way around it?
