### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by rocky050371** [cefsharp/CefSharp#1298]
Is there a way to enable the default context menu?

**Comment by amaitland** [comment]
At a minimum questions need to include version and flavor, e.g. `WPF`, `WinForms`, or `OffScreen`.

Please read over https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue then post a followup.

**Comment by rocky050371** [comment]
My apologies, it is the latest version (43) and it is WPF

**Comment by amaitland** [comment]
So there is no default context menu in `WPF`, so you have two options.

1. You can create a basic `ContextMenu` in `xaml` like https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.Wpf.Example/Views/BrowserTabView.xaml#L187
2. You can implement `IContextMenuHandler.OnBeforeContextMenu` which should be triggered on a `right click`, it will provide you information in context to generate your own menu on the fly. (`IWebBrowser` can be cast to `ChromiumWebBrowser` so you can access it's `WPF` specific features).

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.Wpf.Example/Handlers/MenuHandler.cs#L13

There is no example that demos `2.` that I'm aware of.

**Comment by amaitland** [comment]
@rocky050371 Did you find a workable solution?

**Comment by amaitland** [comment]
Closing due to lack of feedback.

**Comment by tylerlong** [comment]
Why is there no default one provided? For example, when user select some text and right click, at least the context menu should contain the "Copy" menu item. Currently the default behavior is absolutely no context menu. In order to support "Copy", I need to dive into the source code of CefSharp. This is not ideal. It is better to just provide a default context menu.

**Comment by amaitland** [comment]
Submit a pull request with your proposed changes and we can look at getting merged. Also your post comes across as rude, consider being polite in future if you wish to continue receiving support.
