### ISSUE TITLE
Make IRequestHandler into smaller interfaces

### ISSUE THREAD

**Issue by svantreeck** [cefsharp/CefSharp#1299]
Would it be possible to break IRequestHandler into smaller interfaces?  There are lots of methods that seem relatively unrelated (for example, OnRenderProcessTerminated vs GetAuthCredentials), such that implementing something like OnRenderProcessTerminated means also doing custom implementations for some of the other methods.

Or, would it be possible that the event style methods from IRequestHandler could be raised as events (for example, have a RenderProcessTerminated event on the Wpf ChromiumWebBrowser)?

Thanks!

**Comment by amaitland** [comment]
The `API` currently mimics the underlying `CEF API` see http://magpcss.org/ceforum/apidocs3/projects/%28default%29/CefRequestHandler.html

Of course it's possible to change this, though I'm personally not keen on that. As it stands it's relatively easy to translate a problem or example that references `CEF` directly for use with `CefSharp`.

Also that would be a breaking change and there's been quite a lot of that recently, so for at least a couple of versions I'll be limiting `breaking` changes.

> Or, would it be possible that the event style methods from IRequestHandler could be raised as events (for example, have a RenderProcessTerminated event on the Wpf ChromiumWebBrowser)?

Events are more work relatively speaking and more likely to cause memory leaks. The better option would be to provide a default implementation of `RequestHandler` which has `virtual` methods that you can override only the `method` your interested in.
