### ISSUE TITLE
CefSharp Browser Subprocess won't dispose

### ISSUE THREAD

**Issue by RGerculy** [cefsharp/CefSharp#1305]
I having a little trouble with CefSharpBrowserSubprocess.exe . It seems like it won't dispose automatically after the job is done.

Info : 
OS : Windows 10 x64
CefSharp Version : 45 ( Branch : Master ) - Winforms 

The Application was tested on two machines running the same OS;

I initialize CefSharp in public Form1() and later update the URL with Browser.Load(WebsiteURL); 
Browser.Load(WebsiteURL); is trigger every 10 to 120 seconds.
It's important to know that is NOT a tabbed browser. It has one tab, I update the URL every X seconds

The "TAB" is started with  : 
```csharp
var browser = new ChromiumWebBrowser("https://www.example.com")
    {
      Dock = DockStyle.Fill
    };
toolStripContainer1.ContentPanel.Controls.Add(browser);.
```
Here is a screenshot of what is going on : 

![screenshot 2015-09-30 16 48 31](https://cloud.githubusercontent.com/assets/4413496/10200038/ee85ad9e-679b-11e5-8f8e-93c7a26c6b7f.png)

This machine has an I5 CPU (4x3.1GHz) and it goes to 99% when the processes show up.

Strange thing, when I start the application I start with 2x CefSharp Browser Subprocess. It's normal. However, when a new url is being loaded that happens(image), over 20 processes show up.When the Application is idle ( web page was already loaded ) it goes back to two processes and CPU usage drops. 

I understand that CefSharp is working like this, each tab has it's own process, but here something is wrong.

**Comment by RGerculy** [comment]
Update : 
Seems like placing Browser.Load in a background worker wasn't a good idea. I removed it and left the application run for about two hours. The maximum of subprocesses didn't go higher than 3 ( the 3rd process start upon load, and closes when the page was fully loaded )

**Comment by amaitland** [comment]
> The maximum of subprocesses didn't go higher than 3 ( the 3rd process start upon load, and closes when the page was fully loaded )

For reference if you look at the command line args in `Task Manager` you can see what the different process types are.

**Comment by RGerculy** [comment]
I see, thank you.
