### ISSUE TITLE
Sometimes a race condition happens when a browser is disposed 

### ISSUE THREAD

**Issue by Antonyo** [cefsharp/CefSharp#1307]
This is a 'question'.

### Version

Latest version. 'Wpf' Windows 8.1 x86.

### Description

In our program we create and dispose browsers very frequently, sometimes a browser is disposed right after it's created and in that case sometimes the browser crashes because some disposed resources need to be accessed on any of the events that occur right after creation. For instance, a common error occurs here:

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/ManagedCefBrowserAdapter.cpp#L42

because the '_clientAdapter' is in the process of being disposed. Ant there's other places that it could happen something similar. For instance in that case I can check if the adapter is disposed itself but it would involve locking in the dispose method and I don't want to do it. In most case I have to rely in internal flags to check if the object itself is disposed. In resume this a very unsafe and hard to maintain code.

Do you have any recommendations on how can I achieve to get rid of this error in the better way possible?

**Comment by amaitland** [comment]
> Latest version. 'Wpf' Windows 8.1 x86.

As `latest version` is relative, please include the actual commit your using.

Can you include an example to reproduce the problem? Makes it easier to test any possible solutions.

**Comment by amaitland** [comment]
One possibility would be to create the `IBrowser` instance in `ClientAdapter` and pass it through as a param to `OnAfterBrowserCreated`

**Comment by Antonyo** [comment]
Thanks for answering. 
I'm using this commit 8f2dbcbe91e8467eaa57424161c1cf4fa153b7e1

Please to see a test apply this patch: https://www.dropbox.com/s/868lhp9los97v6m/SpawnBrowsersTest.diff?dl=0

Then run the Wpf example. The test window have a list of items, each time you click on one a new browser is created and rendered in the screen, If you click on the 'Test' button a simulation of clicking each item will be performed.

With the default speed click on the 'Test' button, you'll eventually get into an error. It could be the one I references in my first comment. 

Another common error  could happen here: https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf/ChromiumWebBrowser.cs#L548

in the patch I've added some comments lines that check if it's already disposed, in this case the disposal and that method both runs in the UI thread so the flag has the correct value.

**Comment by amaitland** [comment]
> Please to see a test apply this patch: https://www.dropbox.com/s/868lhp9los97v6m/SpawnBrowsersTest.diff?dl=0

Can you fork `CefSharp` and commit your changes to `GitHub` please, I'm not a fan of downloading things from `DropBox`

**Comment by Antonyo** [comment]
Sorry @amaitland, didn't know that. Here it's:
6bfbbbd68fbea24df22b16f82d8b4a3895bcd768

**Comment by amaitland** [comment]
See https://github.com/amaitland/CefSharp/tree/bug/issue-1307 for a quick and dirty update. Not sure if it's a viable solution yet, just an idea.

**Comment by Antonyo** [comment]
Thanks @amaitland it was pretty much like the code I've already working on but I've added some other places where the browser could be already disposed: c2b712f06cc72231c47426a6687eabf820def2c5
Still it's not the best solution since the browser adapter could be disposed at any time but I'd involved locking the dispose method and I prefer not to do that.

Some questions, why did you use a ´Interlocked.Increment´ in the ´ChromiumWebBrowser´ disposal? Could it be accesed from more than one thread?

And another thing, have you noticed that many 'dead' processes remains in memory when the speed test is too fast?

**Comment by amaitland** [comment]
> Some questions, why did you use a Interlocked.Increment in the ChromiumWebBrowser disposal? Could it be accesed from more than one thread?

You might access `IsDisposed` from one of the `CEF` threads. It's not as bullet proof as locking, still better than just checking a bool.

> And another thing, have you noticed that many 'dead' processes remains in memory when the speed test is too fast?

I didn't look at the task manager, if they're still running, then need to check that `CloseBrowser` was called successfully.

**Comment by mattjhammond** [comment]
Possibly on a related issue, I've been testing 43 and the latest builds and I am seeing the browser dispose taking 10 seconds or more.  This can be duplicated using the SimpleBrowserForm in the WinForms example.

**Comment by amaitland** [comment]
> Possibly on a related issue, I've been testing 43 and the latest builds and I am seeing the browser dispose taking 10 seconds or more.

Unrelated to this issue, see #1304 for the relevant issue.

**Comment by amaitland** [comment]
@Antonyo Do you have something that can we turned into a `PR`?

**Comment by Antonyo** [comment]
I can use the latest commit 6f0cb47803a2ededc4f7a822ba4a6d9f64f3f373 into a PR, I've also merged the master branch.

**Comment by amaitland** [comment]
I squashed all the changes into https://github.com/cefsharp/CefSharp/commit/7aa128781df73d37d9be9e1534338d61943d04a9

Will make it easier to back port to `cefsharp/43`

Let me know if you think I missed anything.

**Comment by Antonyo** [comment]
Everything looks fine @amaitland. Thanks.
