### ISSUE TITLE
Feature Request - Allow configuration of proxy during runtime

### ISSUE THREAD

**Issue by help3r** [cefsharp/CefSharp#1308]
i need change proxy when job is finish, but if init twice i get error
how can i solve?

**Comment by amaitland** [comment]
`CEF` does not currently support that feature. See the `upstream` issue https://bitbucket.org/chromiumembedded/cef/issues/1709/allow-configuration-of-preferences-during

**Comment by amaitland** [comment]
`upstream` issue has been resolved on the `CEF master` branch, there is no release branch of `CEF` that includes these changes. When the next release branch is created we can look at upgrading.

Code changes will be required, so anyone keep on implementing this feature please make yourself known.

**Comment by Oceanswave** [comment]
+1

**Comment by amaitland** [comment]
> Code changes will be required, so anyone keep on implementing this feature please make yourself known.

`master` has been upgraded to `CEF 3.2526.1347`, anyone interested can now start working on this feature.

**Comment by amaitland** [comment]
See  #1444 for a partial implementation of this

**Comment by midas643** [comment]
Good

**Comment by amaitland** [comment]
> Good. This is very important feature that CefSharp lacks :+1:

@midas643 If this is a feature you require then please take the time to test out #1444, the basic feature should now be complete. Once we establish some use cases, it's probably worth someone writing some extension methods to simplify working with the interface.

**Comment by amaitland** [comment]
Change have been merged into `master`. New feature needs testing/feedback so please let me know how it goes.

**Comment by amaitland** [comment]
Basic example of changing a `Preference` is https://github.com/cefsharp/CefSharp/commit/8a93ba65649cd3f9d3330b2bef6d01d927f17e29

You can use `GetPreferences` to get the current preferences and locate the relevant proxy ones.

**Comment by GreatFireWall** [comment]
What value should pass to GetPreferences first param?

**Comment by amaitland** [comment]
> What value should pass to GetPreferences first param?

The source code is documented, please check it out.

**Comment by GreatFireWall** [comment]
why not use an enum or static class contains the value of string, it's more readable and easy to use.

**Comment by amaitland** [comment]
> Once we establish some use cases, it's probably worth someone writing some extension methods to simplify working with the interface.

As I've already said, this simply wraps the `CEF` interface. You can contribute some helper/extension methods that make the interface easier to use.

> why not use an enum or static class contains the value of string, it's more readable and easy to use.

Rather than stating what's not there, how about contributing some code to make the project better? Also have a dig through the source, there is no such list provided by `CEF`. They're also likely to change from version to version, so it'll be a moving target for some commands.
