### ISSUE TITLE
System.BadImageFormatException

### ISSUE THREAD

**Issue by hpposch** [cefsharp/CefSharp#1309]
When i want to compile my project with the cefsharp solution (I added my project to the CefSharp solution and referenced the assemblies) i always get a System.BadImageFormatException.
Assembly \"CefSharp.Wpf, Version=45.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138\"

Has anybody an idea how to solve this?

**Comment by hpposch** [comment]
Ok, i solved it by change the platform to x86..

But now i get e new exception:
System.IO.FileNotFoundException
Assembly "CefSharp.Core.dll"

It occures when i execute the following code line:
browser = new ChromiumWebBrowser();

**Comment by amaitland** [comment]
How are you copying the `CEF` dependencies? The `Nuget` packages copies them for you.

The example projects have extra code to copy them

- Include the `cef.redist` dependencies
- Copy the `BrowserSubProcess` using `props` file.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf.Example/packages.config#L4
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf.Example/CefSharp.Wpf.Example.csproj#L189

As I said before, it's easier to build the `Nuget` packages and use them.

**Comment by hpposch** [comment]
Hmm..
Yes i tried to build the nuget package, but it doesnt work :(
Can you maybe generate it for me, and then send it to me.. This would be great.. :)

**Comment by amaitland** [comment]
> Can you maybe generate it for me, and then send it to me.. This would be great.. :)

There's the `MyGet` feed that I also referenced, it generates them for every commit on `master`.

Latest version built successfully, so you should have no problem (the `CI` builds use the same `build.ps1` script, so it should work just fine for creating your own).

https://ci.appveyor.com/project/cefsharp/cefsharp/build/45.0.0-CI1493

**Comment by amaitland** [comment]
Newer version is available, hadn't updated the build script to reference the newer `cef.redist` package.

https://ci.appveyor.com/project/cefsharp/cefsharp/build/45.0.0-CI1495

**Comment by amaitland** [comment]
@hpposch Anything else before closing this?

**Comment by hpposch** [comment]
No, thanks..
It worked for me. :)

For the future i will always use the nuget - packages ;)
