### ISSUE TITLE
Need help to implement custom scheme

### ISSUE THREAD

**Issue by rover886** [cefsharp/CefSharp#1311]
Actually i am not facing any issue but I wanted to know whether the way I coded is correct or not. I am using CefSharp version 43. I used CefSharp in other application. All the implementation is working fine. Now I want to implement an Custome Scheme (prq) I have added code to set `SchemeHandlerFactory`. Factory class is as follows : 

```
public class TestSchemeHandler : ISchemeHandlerFactory, IResourceHandler
    {
        SBMainForm mainForm;
        public TestSchemeHandler(SBMainForm mainForm)
        {
            this.mainForm = mainForm;
        }           

        public IResourceHandler Create(IBrowser browser, IFrame frame, string schemeName, IRequest request)
        {
            return this;
        }

        public Stream GetResponse(IResponse response, out long responseLength, out string redirectUrl)
        {
            responseLength = 0;
            redirectUrl = null;
            return null;
        }

        public bool ProcessRequestAsync(IRequest request, ICallback callback)
        {
            Uri uri = new Uri(request.Url);
            Dictionary<string, object> list = new Dictionary<string, object>();
            foreach (string item in uri.Query.Replace("?", "").Split('&'))
            {
                list.Add(item.Split('=')[0], item.Split('=')[1]);
            }
            list.Add("WebUrl", clsProperty.getProperty("NavigateURL"));
            mainForm.InvokeOnUiThreadIfRequired(() => mainForm.openTest(list));
            return false;  
        }
    }
```
Through website I will get URL something like : `prq:url?pid=45174&did=7485698`, I want to open an windows application when user clicks on above link, so opening of that windows application code is handled by method `openTest()` which is called in `ProcessRequestAsync()`. 

__Once windows application get opened webpage should remain unchanged (same where user clicked the link) hence I returned `false` from `ProcessRequestAsync()` and returned `null` from `GetResponse()`, Is it correct and safe to do so?__

**Comment by jankurianski** [comment]
> Once windows application get opened webpage should remain unchanged (same where user clicked the link) hence I returned false from ProcessRequestAsync() and returned null from GetResponse(), Is it correct and safe to do so?

Yes.  Because you returned false, `GetResponse` will never be called.

**Comment by amaitland** [comment]
You may not need to implement `IResourceHandler,` you can try returning `null` in `Create`, performing your logic in there. Returning `null` should invoke the default action, for a custom scheme it shouldn't do anything.

As a side note, might be worth looking into `HttpUtility.ParseQueryString`, save you parsing the query string yourself.

https://msdn.microsoft.com/en-us/library/ms150046%28v=vs.110%29.aspx

**Comment by rover886** [comment]
@amaitland Do you mean to say like this only:

```
public class TestSchemeHandler : ISchemeHandlerFactory
    {
        SBMainForm mainForm;
        public TestSchemeHandler(SBMainForm mainForm)
        {
            this.mainForm = mainForm;
        }           

        public IResourceHandler Create(IBrowser browser, IFrame frame, string schemeName, IRequest request)
        {
            //call to mainForm.openTest(); which will open other windows application
            return null;  
        }       
    }
```

**Comment by amaitland** [comment]
> @amaitland Do you mean to say like this only:

Yep, exactly that.

**Comment by rover886** [comment]
Ohh, gr8.. Tons of Thanks :)

**Comment by bbonczek** [comment]
Since Cefsharp changed a bit since this discussion, and the fact that this issue is one of the first appearing in google, [look at my blog post](https://bbonczek.github.io/jekyll/update/2018/04/24/serve-content-in-cef-without-http-server.html) if you need to serve your app in CEF via custom protocol, without hosting http server. feedback is welcome :)
