### ISSUE TITLE
CefSharp.BrowserSubprocess.exe running after application exit

### ISSUE THREAD

**Issue by NKumarPraveen** [cefsharp/CefSharp#1312]
Hello,

I am launching cefsharp browser inside c# async await methods, found browser working fine and when I exit my application CefSharp.BrowserSubprocess.exe instance running. It works fine in synchronous methods.
May I know any solution for this

Thank you

**Comment by amaitland** [comment]
`Version`? `WinForms`, `WPF` or `OffScreen`?

See below for more info on creating a useful issue, there's even a link that creates a template
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue

> I am launching cefsharp browser inside c# async await methods

That's not particularly meaningful without a code example.

**Comment by NKumarPraveen** [comment]
Hi,
     Thanks for correction.

#### Issue Summary
What is the expected output? What do you see instead?

Expected: CefSharp.BrowserSubprocess.exe exit
Observation: CefSharp.BrowserSubprocess.exe running after application exit

#### Technical details
* Version: Chromium: 45.0.2454.62, CEF: r3.2454.1317.gc22b77d, CefSharp: 45.0.0.0
*  Windows 7
*  x86
*  WinForms
*.Net framework :4.5

#### Steps to Reproduce

public partial class Form2 : Form,IDisposable
    {
        private ChromiumWebBrowser browser;
        public Form2()
        {
            InitializeComponent();
            var res =  CreateMyBrowser();
        }

        private async Task<dynamic> CreateMyBrowser()
        {
            try
            {
                var settings = new CefSettings
                {
                    IgnoreCertificateErrors = true,
                    CachePath = Path.Combine(Application.StartupPath, "Cache"),
                    LogSeverity = LogSeverity.Info,
                    LogFile = Path.Combine(Application.StartupPath, "log.txt")
                };
              
                Task<bool> ta = Task.Factory.StartNew(() =>
                {
                    browser = new ChromiumWebBrowser("www.google.com")
                    {
                        Dock = DockStyle.Fill,
                        BrowserSettings = { ApplicationCache = CefState.Enabled },
                    };
                    return true;
                });

                var res = await ta;
                toolStripContainer1.ContentPanel.Controls.Add(browser);

                return res;                
            }
            catch (Exception)
            {
                
                throw;
            }
          
        }

        private void Form2_FormClosing(object sender, FormClosingEventArgs e)
        {
            //Tried all possibities of shutting down, still issue exists
            //browser.Dispose();
            //Cef.Shutdown();
            //Close();
            //this.Dispose();
        }

        void IDisposable.Dispose()
        {
            browser.Dispose();
        }
    }

**Comment by amaitland** [comment]
Is there a reason you spawn the ChromiumWebBrowser instance in a Task? Creating an instance is a lightweight operation as the underlying browser is created once the control is assigned a handle.

Anyways, you problem likely lies in the fact that you need to Initialize and Shutdown Cef on the same thread. Typically your UI thread. As I don't see a reference to Cef.Initialize, you'll be relying on the first instance to do that for you, which takes a small amount of time.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.WinForms/ChromiumWebBrowser.cs#L81
https://github.com/cefsharp/CefSharp.MinimalExample/blob/master/CefSharp.MinimalExample.WinForms/Program.cs#L15

**Comment by NKumarPraveen** [comment]
Thank you for the reply.

I am using chromium browser to show custom forms to get user inputs. I have a library (DLL) which contains winform chromium web browser . it has public interface to

ShowForm(formName) in this function I initialize chromium browser and navigating to html form.

 
As per your suggestion I am initializing in constructor and disposing in the same form in form closing event. Now I can see that CefSharp.BrowserSubprocess instance is closing when user form is closed. My main UI form (from where I am referring above dll) if I re-launch the form,  Chromium embedded DLL as well as parent application are crashing with following error in debug.log

 

[1007/101714:ERROR:renderer_main.cc(200)] Running without renderer sandbox

[1007/101916:FATAL:content_main_runner.cc(772)] Check failed: InitializeSandbox(params.sandbox_info).

**Comment by amaitland** [comment]
> As per your suggestion I am initializing in constructor and disposing in the same form in form closing event. Now I can see that CefSharp.BrowserSubprocess instance is closing when user form is closed. My main UI form (from where I am referring above dll) if I re-launch the form, Chromium embedded DLL as well as parent application are crashing with following error in debug.log

Are you trying to `Shutdown` then `Reinitialize`? One of the limitations of `CEF` is no way to reinitialize once `Shutdown` has been called.

**Comment by NKumarPraveen** [comment]
Thank you for the solution. I have fixed by initializing and shutting down cef from UI thread.

**Comment by supperlitt** [comment]
原来如此，我也解决了问题了。

**Comment by supperlitt** [comment]
thanks
