### ISSUE TITLE
How do you access / interact with flash elements?

### ISSUE THREAD

**Issue by markrussel** [cefsharp/CefSharp#1313]
A few months ago I was asking how to access web elements by Xpath?

The answer here: https://github.com/cefsharp/CefSharp/issues/830
works well for me using document .evaluate.

How now I want to the same with a flash page - ie: control individual flash elements - is this possible and how?
Mark

**Comment by jankurianski** [comment]
Probably a better question for the cef forums.  Would help if you re-state your environment when you ask a new question - i.e. `WinForms` or `WPF`, version, etc.  If you ask a question on the cef forums, and you use the `WPF` controls, be sure to include a note that you use the offscreen rendering mode.

**Comment by markrussel** [comment]
Thanks Jan
Environment is winforms.  Will do as you advise.

Regards,
Mark

**Comment by jankurianski** [comment]
Thanks Mark.  I'll close this issue in CefSharp, but please do add a link here to your CEF forum thread when you post it.  Will help future googlers :smile:
