### ISSUE TITLE
JavascriptCallback also has problem when the page include iframe

### ISSUE THREAD

**Issue by euler82** [cefsharp/CefSharp#1315]
In Branch Master and 43
If the page include iframe ,the JavascriptCallback not work correctly.
But in Branch 41 
It work correctly.

In the issues #1216 ,There is a detailed description for this problem.

Now the version 41 has some other problem,
such as Scroll too much with MouseWheel, it's a bug: https://bitbucket.org/chromiumembedded/cef/issue/1481 for cef.

I want upgrate to version 43,but the JavascriptCallback also not work correctly.

How to solve this problem. thanks!

**Comment by amaitland** [comment]
> How to solve this problem. thanks!

To start debugging this, download the source code, add your changes to demo the problem (ideal if you can push those to your `GitHub` fork)

Add breakpoint to https://github.com/cefsharp/CefSharp/blob/master/CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.cpp#L63

Enable `renderer-startup-dialog`
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/CefExample.cs#L48

Attach the debugger to the process that displays a message dialog on load (from memory it's got `Chromium Render` in the description).

See if `CefAppUnmanagedWrapper::OnContextCreated`, step through to see if the binding happens. The `OnContextCreated` event should be called for the main frame and `iframes` (going from memory with that one also)

Along the way you might need to compare to the `41` version
https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.cpp#L47

**Comment by illfang** [comment]
@amaitland I'm working on a patch for this issue. I believe there is a flaw in the CefSharp binding logic for context creation / destruction.

**Comment by amaitland** [comment]
Changes merged into `43` branch, hopefully release `43.0.1` shortly (just needs more testing).

**Comment by amaitland** [comment]
`43.0.1` has been released to `Nuget.org` See https://github.com/cefsharp/CefSharp/releases/tag/v43.0.1 for more details
