### ISSUE TITLE
EvaluateScriptAsync Deadlock

### ISSUE THREAD

**Issue by MagicWang** [cefsharp/CefSharp#1327]
I have expose a .NET class to Javascript.In my function,i want to call js method with a result.Unluckly,at the task.Wait(), i get a System.Threading.Tasks.TaskCanceledException: A task was canceled.Who can help me.

```c#
public class BoundObject
{
    public void MyMethod()
    {
        var task = webBrowser.EvaluateScriptAsync(script);
        task.Wait();
    }
}
```

**Comment by amaitland** [comment]
Pass the function in as a param and use a `callback`.

See example
https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.Example/BoundObject.cs#L49

**Comment by amaitland** [comment]
(In future please markup your code, I edited your code to provide you with a sample for future reference)

**Comment by MagicWang** [comment]
Thank you,amaitland.But i just want a sync method,beause i use this in a Map Class,which expose method like GetZoomLevel,GetCenterPoint,MapPointToScreen,and so on.my user donot want to invoke my method with a callback.
My code is like this:
public class Map
{
    public void RectSelect()
   {
        webBrowser.ExecuteScriptAsync("rectSelect()");
   }
    public int GetZoomLevel()
    {
        var task = webBrowser.EvaluateScriptAsync("getZoomLevel()");
        task.Wait();
        return task.Result.Result;
    }
}
public class BoundObject
{
    public void OnRectSelected()
    {
        var level = map.GetZoomLevel(); //invkoe this method get a  task was canceled exception
        ...
    }
}

**Comment by amaitland** [comment]
> (In future please markup your code, I edited your code to provide you with a sample for future reference)

Your code is hard to read, please mark it up.

> Thank you,amaitland.But i just want a sync method,beause i use this in a Map Class,which expose method like GetZoomLevel,GetCenterPoint,MapPointToScreen,and so on.my user donot want to invoke my method with a callback.

You cannot block on a bound method as they're run on the `render` process thread and will cause you all sorts of problems (as you've found it).

Calling a bound method, to then execute some javascript sounds like a problematic design choice. Is there any reason you don't just pass in the result from `getZoomLevel()` as param to the `GetZoomLevel` function?

It may also be worth looking into `async bound objects` which effectively use a javascript promise to continue execution when complete.

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.Example/Resources/BindingTest.html#L44

**Comment by MagicWang** [comment]
Sorry,i'm new to this,i will have a try.My application use wpf webbrowser,it's InvokeScript method is sync.And now i'm replace it with cef.so a lot of work...

**Comment by amaitland** [comment]
For reference you can retreive the result from a callback, so you might be able to create a few extra javascript functions to bridge the interface without too much effort.

```c#
public void TestCallback(IJavascriptCallback javascriptCallback)
{
	const int taskDelay = 1500;

	Task.Run(async () =>
	{
		await Task.Delay(taskDelay);

		using (javascriptCallback)
		{
			var response = await javascriptCallback.ExecuteAsync("This callback from C# was delayed " + taskDelay + "ms");
			//Do something with the result
			//response.Result;
		}
	});
}
```

**Comment by MagicWang** [comment]
At last,i have find a way to invoke a js method in a bound method.I just change RegisterJsObject to RegisterAsyncJsObject.Thank you for your help

**Comment by amaitland** [comment]
> At last,i have find a way to invoke a js method in a bound method.I just change RegisterJsObject to RegisterAsyncJsObject.Thank you for your help

Great :+1: If there's nothing else then please close this issue.
