### ISSUE TITLE
Tooltip issues with winform

### ISSUE THREAD

**Issue by NKumarPraveen** [cefsharp/CefSharp#1328]
Hi,

#### Issue Summary
Tooltip is not displayed in windows form project.
I have launched your tooltipTest.html from following path in winform
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/Resources/TooltipTest.html
Tooltip is not dislayed in winform, works with WPF.

#### Technical details
*  version 45.0.0.0.
*  windows 7 64 bit
* x86/x64: x86
* WinForms

Thanks and Regards
Praveen Kumar

**Comment by amaitland** [comment]
If you load `http://www.google.com` and hover over the `Google` logo what happens?

Running latest `master` on `Windows 8.1 x64` and I'm unable to reproduce your problem. I'll try on `Windows 7 x64` tomorrow. 

Can you try on a different machine with another operating system?

**Comment by amaitland** [comment]
> Running latest master on Windows 8.1 x64 and I'm unable to reproduce your problem. I'll try on Windows 7 x64 tomorrow.

Running the latest `master` on `Windows 7 x64` and tools tips are working.

What exactly are you seeing? Can you provide a screenshot? Can you think of anything else that might be relevant?

**Comment by NKumarPraveen** [comment]
I tried on different machine, its working.

Thanks

**Comment by bruce5794163** [comment]
@NKumarPraveen how do you solve this problem?
my Technical details are same to you。
• version 45.0.0.0.
• windows 7 64 bit
•x86/x64: x86
•WinForms
the  appearance is the same.Tooltip is not dislayed in winform, works with WPF.

**Comment by NKumarPraveen** [comment]
Add app.manifest file to project

**Comment by amaitland** [comment]
Specifically you need to add `Microsoft.Windows.Common-Controls`, see the `CefSharp.WinForms.Example` project for a sample.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.WinForms.Example/app.manifest#L15
