### ISSUE TITLE
wpf drag always copy

### ISSUE THREAD

**Issue by bjarteskogoy** [cefsharp/CefSharp#1332]
Check out this demo: http://ckeditor.com/demo

Select and drag text or try to move the image. In WPF it always copies everything.
In WinForms it moves the content, as it should.

Running cefclient offscreen from cef_binary_3.2357.1287.g861c26e_windows32_client seems to work correctly.

Any ideas?

**Comment by amarant** [comment]
I have the same issue, a drag move in ckeditor is not recognized as drag move but a drag copy, with a simple input the dragged part is just deleted.

**Comment by amaitland** [comment]
Likely need to compare the `cefclient` implementation and adjust the current implementation accordingly. `Pull Requests` welcome :+1:

**Comment by amaitland** [comment]
Resolved with https://github.com/cefsharp/CefSharp/commit/11564beccae0b0746b6d62176cc689d2a608e1bf
