### ISSUE TITLE
[Custom OffScreen] IRenderWebBrowser.InvokeRenderAsync is only called if i explicitly call IBrowserHost.Invalidate

### ISSUE THREAD

**Issue by bartwe** [cefsharp/CefSharp#1333]
I'm using cefsharp to render ingame user interface elements.
To do this i create an offscreen browser and copy the data received through InvokeRenderAsync into a directx texture (an abgr-argb swizzle is needed here sadly)
BrowserSettings.WindowlessFrameRate seems to be ignored or offscreen rendering simply doesn't do periodic calls to InvokeRenderAsync
Built from git master
Windows 7
x86
If i explicitly call IBrowserHost.Invalidate i do get a frame from InvokeRenderAsync
Due to lack of DirtyRectSupport this means a full screen update every frame even when the page is static.
Am i using an incorrect event model ? is there a way to get sparse calls to InvokeRenderAsync having DirtyRectSupport at WindowlessFrameRate rate ?

Currently i do have cefsharp working but it is eating too much cpu time due to having a full invalidated frame 60 times a second.

**Comment by amaitland** [comment]
> Due to lack of DirtyRectSupport this means a full screen update every frame even when the page is static.

Your welcome to extend the `OffScreen` project so that it uses the `IBitmapFactory`, you can then implement your own rendering.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp/IBitmapFactory.cs
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf/Rendering/WritableBitmapInfo.cs#L31
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.OffScreen/ChromiumWebBrowser.cs#L307

**Comment by amaitland** [comment]
`SetWindowlessFrameRate` was added relatively recently, personally I've never used it for more than trivial things. Might be worth looking at the code, see if anything stands out.

https://bitbucket.org/chromiumembedded/cef/commits/483a841

**Comment by bartwe** [comment]
Could we perhaps sponsor a bit of development in this direction ?

**Comment by amaitland** [comment]
> Could we perhaps sponsor a bit of development in this direction ?

What game are you working on?

The changes required are actually pretty trivial, see https://github.com/cefsharp/CefSharp/commit/12383926426a760be7e6d83c5bd7aec9fdec92bd

You can create you own `BitmapInfo` and override `InvokeRenderAsync`, you don't need to create a bitmap, you can get access to the buffer it's self and presumably copy it directly into a texture.

> BrowserSettings.WindowlessFrameRate seems to be ignored or offscreen rendering simply doesn't do periodic calls to InvokeRenderAsync

Can you fork `CefSharp`, and modify `CefSharp.OffScreen.Example` to demo your problem?

**Comment by bartwe** [comment]
I'm working on http://playstaxel.com/

Yeah i wrote my own IBitmapFactory, doesn't fix that InvokeRenderAsync only
gets called on Invalidate, and then doesn't have a dirtyrect ? (this is how
i did it initially, i'm not using CefSharp.OffScreen at all, merely used it
as an example when building the code)

**Comment by amaitland** [comment]
> i did it initially, i'm not using CefSharp.OffScreen at all, merely used it as an example when building the code)

Would probably have been useful if you mentioned that up front.

> doesn't fix that InvokeRenderAsync only gets called on Invalidate, and then doesn't have a dirtyrect ?

Does the problem reproduce using the `OffScreen` project, maybe your implementation is missing something?

Did you set `DirtyRectSupport = true`?

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Internals/RenderClientAdapter.h#L123

**Comment by bartwe** [comment]
Apologies for not being clearer that my offscreen rendering is without the
CefSharp.Offscreen library.

I was not setting DirtyRectSupport  to true :) i thought that was a feature
set by the library itself, woops.

looking at
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Internals/RenderClientAdapter.h#L123
it does still seem to copy from the memorymapped file and call
InvokeRenderAsync
when there is no region marked dirty.

**Comment by amaitland** [comment]
> it does still seem to copy from the memorymapped file and call InvokeRenderAsync when there is no region marked dirty.

Up until `43.0.0` the `DirectyRectSupport` option was never actually used, it was just something I implemented as an experiment. I've never revisited the code. Feel free to submit a `PR` with improvements.

**Comment by bartwe** [comment]
Ok i'll send you a PR later today or tomorrow.

Do you also perhaps know why i don't get an OnPaint without calling
Invalidate ?

**Comment by bartwe** [comment]
Apologies, i incorrectly copied the line
' settings.CefCommandLineArgs.Add("disable-gpu-vsync", "1"); //Disable
Vsync'
from an example which causes cef to only provide frames on invalidate,
works perfectly now :)

Thank you, you have been a massive help :)

**Comment by amaitland** [comment]
Great, closing :smile:
