### ISSUE TITLE
[Custom OffScreen] RegisterAsyncJsObject fails to register reliably.

### ISSUE THREAD

**Issue by bartwe** [cefsharp/CefSharp#1334]
I'm having some trouble getting callbacks to work.
The object i register using RegisterAsyncJsObject isn't available reliably (mostly unavailable, maybe works 1 in 20 runs)
I can get it to be more reliable( 9 out of 10 runs) by doing a Thread.Sleep(10000) after calling CreateOffscreenBrowser, which strongly seems to suggest a timing issue.

Also i have to call IBrowserHost.Invalidate all the time to get callbacks on IRenderWebBrowser.InvokeRenderAsync which seems wrong.

My application is a game using xna and cef to render the ingame user interface, had it working on awesomium before and i'm currently converting to cefsharp because it is easier to bugfix and contribute to.

I do have a message loop and i'm successfully passing it keyboard and mouse events and can browse websites currently through cefsharp, just not reliably call back from the website into the registered callback.

**Comment by amaitland** [comment]
> The object i register using RegisterAsyncJsObject isn't available reliably (mostly unavailable, maybe works 1 in 20 runs)

To my knowledge binding has never been tested in the `OffScreen` project. As a whole it's not particularly actively developed, most people just want to take screen shots.

The fact the call to `CreateOffscreenBrowser` happens in the constructor means their isn't time for the binding to happen successfully. I'd like to keep this as the default behavior, though more than happy to allow for customization, there is another case with #1170 where the browser creation needs to happen elsewhere. A bool param with a default param of `true` will likely do, and expose the call to `CreateOffscreenBrowser`

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.OffScreen/ChromiumWebBrowser.cs#L97

**Comment by amaitland** [comment]
#1170 has been resolved with https://github.com/cefsharp/CefSharp/commit/dca52f931fcb7e0d435b2e1f46cd1d49fed5a2d3

See if that works for your scenario. Use `automaticallyCreateBrowser = false` and call `CreateBrowser` once you've finished registering your objects.

**Comment by amaitland** [comment]
Did you restructure you code to call register before calling `CreateOffscreenBrowser`?

**Comment by bartwe** [comment]
For now i switched to a polling system over ExecuteScriptAsync which works
a bit simpler threading wise too :)

**Comment by amaitland** [comment]
If your happy and it's working then please close this :+1:
