### ISSUE TITLE
Can we change the color of highlighted search results in Chromium?

### ISSUE THREAD

**Issue by Amal22** [cefsharp/CefSharp#1339]
Hello,
I have successfully embedded CefSharp in a .Net application. Now, i am working on searching a text in the web browser. I have two questions :   
- Can we change the color of highlighted search results?
- Can we know the current position in the search results? 

Thanks in advance,

**Comment by amaitland** [comment]
I don't believe `CEF` exposes either currently.

The `API` documentation can be found http://magpcss.org/ceforum/apidocs3/index-all.html might be worth seeing if there's something I missed,

Subsequently you can ask on `ceforum`, see if it's possible. I believe changes to `CEF` would be required for both.

http://magpcss.org/ceforum/index.php

**Comment by Amal22** [comment]
I looked at the API documentation and I found nothing. Yes, changes are required for both cef and cefSharp.
Anyway, thank you for the reply :) I will look for a solution at ceforum.

**Comment by Amal22** [comment]
@amaitland  returning to this issue, I found in the API documentation a class called "CefFindHandler" that handle events related to find results. Actually, in our application we need to know the number of search results and the current position of the search result.

**Comment by amaitland** [comment]
`CefFindHandler` has yet to be implemented in `CefSharp`, there is issue #1459 as a placeholder.

**Comment by Amal22** [comment]
okay :+1:

**Comment by amaitland** [comment]
@Amal22 If you have time to implement `CefFindHandler` then see #768 for an example of what's required (mostly just plumbing code, not particularly hard).
