### ISSUE TITLE
Performance issues with v43

### ISSUE THREAD

**Issue by jamespearce2006** [cefsharp/CefSharp#1340]
I use CefSharp with WPF, and I've noticed a significant performance hit since moving from v41 to v43. I see that the same performance problems affect the WPF Example. I can see a big difference with the WPF Example if I just switch between v41 and v43.

Basically, just trying to scroll a page is difficult, where the page will hang frequently, leaving the app almost unusable.

I can improve the performance by setting disable-gpu-compositing and enable-begin-frame-scheduling, but these disable features like WebGL. They were unnecessary with v41.

**Comment by jamespearce2006** [comment]
The other strange thing is that it gets worse as the window gets smaller.
If I maximize the example window, the problem is pretty much gone. If I shrink it to a quarter of my screen, the problems gets much worse.

**Comment by jamespearce2006** [comment]
This looks like it might be a problem specific to a certain GPU, coupled with an upstream issue.
I see the issue on Windows 7 with Quadro K2100, running the latest nVidia drivers. If I disable desktop compositing, the problem goes away.
I do not see the issue on Windows 10 with a GTX 960.

**Comment by amaitland** [comment]
Opening `chrome://gpu/` in `Chrome` is often useful. Also see what command line arguments `Chrome` used.

`GPU` issues are fairly common, specially on more exotic video cards (and anything from `Intel`).

**Comment by amaitland** [comment]
Did you find out if `Chrome` was disabling the `GPU` automatically for you when using the `Quadro` card?

**Comment by jamespearce2006** [comment]
Sorry for the delay in replying.

Chrome is using the GPU. In fact, there's not much difference reported by
Chrome between the machine that works OK and the one that doesn't (beyond
DirectX and Windows versions). There's nothing that jumps out at me.

It's kind of frustrating as the performance is so bad as to close to
unusable.

**Comment by amaitland** [comment]
Other than trying a newer version of `CEF` there probably isn't much else that can we done.

**Comment by jamespearce2006** [comment]
I think you're probably right.

The performance issue does seem to clear itself after the browser has been running a while too. I've not yet worked what triggers that, but I'll keep you posted if I work it out.

**Comment by jamespearce2006** [comment]
v45 seems to have fixed the performance issues for me, so you can probably close this.

**Comment by amaitland** [comment]
Excellent news, closing :smile:
