### ISSUE TITLE
Browser crashes on very large resolution (8K, +)

### ISSUE THREAD

**Issue by KennyKay** [cefsharp/CefSharp#1342]
I was testing the browser on a large monitor with high definition (8K)  and it stopped responding after a certain amount of usage on full screen.

The browser is stable when it takes only a portion of the screen (1080p, for example) but has a high possibility to crash when it goes higher than 4K resolution.

As a temporary solution, I would like to know if it can be resolved by limiting the resolution of the browser itself (to only render in 1080p in the settings?).

Thanks

**Comment by KennyKay** [comment]
To add more info, I am currently running CefSharp 41.0.1.0 in Winforms on Windows 7.

**Comment by amaitland** [comment]
> To add more info, I am currently running CefSharp 41.0.1.0 in Winforms on Windows 7.

Have you tried `43.0.0`? See if using a newer version of `CEF` helps.

> As a temporary solution, I would like to know if it can be resolved by limiting the resolution of the browser itself (to only render in 1080p in the settings?).

No such setting exists in `CefSharp`. I'm not sure it does in `CEF` either. The `API` is http://magpcss.org/ceforum/apidocs3/index-all.html should you wish to take a look.

My first though would be to try a newer version, even try out `master` which is based on `Chromium 45`

**Comment by KennyKay** [comment]
Alright, I will try the newest versions of CefSharp on the same computer sometime this week and give you my results.

**Comment by amaitland** [comment]
`45.0.0-pre01` is pending release and `master` has been upgraded to a pre release version of `47`. A few options should you wish to try them.

I'd probably check out the `45` release as it's based on a `release` version of `Chromium`

**Comment by amaitland** [comment]
`45.0.0-pre01` has been released to `nuget.org`
