### ISSUE TITLE
crash when run the "CefSharp.Cef.Initialize();"

### ISSUE THREAD

**Issue by billycat** [cefsharp/CefSharp#1343]
hi, I just installed the cefsharp 43 with nuget. My application is on x64 platform. Visual Studio 2010, winform.

my code is here,
```
    public Mainform()    
    {
            InitializeComponent();
            CefSharp.Cef.Initialize();
            ChromiumWebBrowser wb = new ChromiumWebBrowser("http://www.baidu.com");
            wb.Dock = DockStyle.Fill;
            this.Controls.Add(wb);
    }
```

when the code `CefSharp.Cef.Initialize();` run, and the application crash.

how can I work out this problem.

**Comment by amaitland** [comment]
Does exception are you seeing? Do you have the `VC++ 2012 Redist` installed?

**Comment by bruce5794163** [comment]
maybe you lose some file.

**Comment by billycat** [comment]
visual c++ 2012 redist has installed.
![image](https://cloud.githubusercontent.com/assets/6973133/10595005/a6a238d4-7705-11e5-84c7-664ff72001a6.png)

and I get nothing about the exception, just popup the dialog
![image](https://cloud.githubusercontent.com/assets/6973133/10595049/4c1e19ea-7706-11e5-90b1-6086d70f00c3.png)

**Comment by amaitland** [comment]
What operating system? Have you checked the event viewer for more information?

**Comment by amaitland** [comment]
Also try enabling dependency checking to validate the libs are being copied to the relevant folder. (The third param of `Cef.Initialize`)

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.Example/CefExample.cs#L127

**Comment by billycat** [comment]
here is the screenshot of the Debug folder, I think all the dll have copyed .
my operating system is Win 7 . but not the sp1 version.
 
![image](https://cloud.githubusercontent.com/assets/6973133/10595362/c1ad1c62-7709-11e5-8b85-a6f940e638d3.png)

**Comment by amaitland** [comment]
What happens if you run the `MinimalExample`? Do you have a newer version of `VS` you can try with?

https://github.com/cefsharp/CefSharp.MinimalExample

**Comment by billycat** [comment]
I'm sorry, I just have Visual Studio 2010, and I can't run the MinimalExample.

**Comment by illfang** [comment]
For work on an open source project you can use the free VS 2013 community edition
https://www.visualstudio.com/en-us/news/vs2013-community-vs.aspx

(license https://www.visualstudio.com/support/legal/dn877550 )

**Comment by amaitland** [comment]
@billycat Any follow up on this?

**Comment by amaitland** [comment]
Closing due to lack of feedback

**Comment by dreamminister** [comment]
Hi! I have similar issue, and I can provide feedback!

**Comment by belliez** [comment]
did you resolve this?

**Comment by dreamminister** [comment]
https://stackoverflow.com/questions/46075760/chromiumwebbrowser-offscreen-does-not-work-with-mstest-nunit

**Comment by imPRAGMA** [comment]
This is occuring on my end, somewhere in Cef.Initialize() string its throwing a NullReferenceException.

**Comment by imPRAGMA** [comment]
I checked event viewer and it was failing on my app level to load the core.dll if i dont .Initialize() at all, and before that, the BrowserSubProcess DLL had an error occur:
https://i.imgur.com/QorLQe2.png

Exception Info: System.IO.FileNotFoundException
   at CefSharp.BrowserSubprocess.Program.Main(System.String[])
Event ID: 1026

Is the source for the sub process available? What could be missing?

**Comment by imPRAGMA** [comment]
also when it "errors" the subprocess is never ever ran (or crashes insanely fast that i dont see it in task mgr)

**Comment by imPRAGMA** [comment]
Ok so odd enough it ended up boiling down to C++ 2015 x86 not being installed. My checks on it being installed (by looking for msvcp140.dll in Sys32) passed but it wasnt actually installed (the dll existed without it being installed idk why)

**Comment by Preknight** [comment]
I met this issue. My cause is the en-US.pak in locales is wrong version. 
At first it doesn't throw an exception, I found it because I deleted the whole locales folder,  then the Cef.Initialize(settings, true) throws this:
_Unable to locate required Cef/CefSharp dependencies: Missing \locales\en-US.pak_
so maybe delete some dll could be easier to locate the exception？
