### ISSUE TITLE
CefSharp does not work in new windows

### ISSUE THREAD

**Issue by m0hs3n52** [cefsharp/CefSharp#1345]
Hi,

i've a simple WPF CefSharp project it's working fine on my machine and also another machine but when i've tried to installed the application and run it on a clean Windows 8 machine, i get Stop working (CLR20r3) error.

i've installed .Net Framework 4.6 on this machine and when i run another application which is not using CefSharp is working fine.

**Comment by amaitland** [comment]
Do you have all the pre-requisites installed? `CefSharp` requires `.Net 4.0` and `VC++ 2012 Redist`

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/NuGet/Readme.txt#L19

**Comment by m0hs3n52** [comment]
Thanks amaitland  i've installed VC++ 2012 Redist and it's working now.
