### ISSUE TITLE
tooltipText not display(web element title)

### ISSUE THREAD

**Issue by bruce5794163** [cefsharp/CefSharp#1347]
I'm using CefSharp at winform mode by build the source,But the application don't display the webelement tooltiptext,how to display it?

**Comment by amaitland** [comment]
Do you have an app.manifest similar to the link below?

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.WinForms.Example/app.manifest#L15

**Comment by bruce5794163** [comment]
no,I haven't. let me try it .

**Comment by bruce5794163** [comment]
error could not find “Microsoft.Windows.Common-Controls, Version=6.0.0.0, Culture=*, PublicKeyToken=6595b64144ccf1df, ProcessorArchitecture=*, Type=win32”。	
what should id do?

**Comment by bruce5794163** [comment]
I have regsvr32 mscomctl.ocx,but vs ide tell me could not find the ocx,it's not a good idea.

**Comment by amaitland** [comment]
Try the WinForms example, make sure it works on your system.

**Comment by bruce5794163** [comment]
The win Forms example  doesn't work,app.manifest contains the below content.
  <dependency>
    <dependentAssembly>
      <assemblyIdentity type="Win32" name="Microsoft.Windows.Common-Controls" version="6.0.0.0" processorArchitecture="*" publicKeyToken="6595b64144ccf1df" language="*"></assemblyIdentity>
    </dependentAssembly>
  </dependency>

**Comment by bruce5794163** [comment]
The winForms example doesn't work,app.manifest contains the below content.
![20151020092428](https://cloud.githubusercontent.com/assets/15192211/10595569/69115930-770c-11e5-8e37-1e0e489b5089.png)

**Comment by amaitland** [comment]
> The winForms example doesn't work,app.manifest contains the below content.

Please elaborate. I can't help you if you don't provide enough information.

**Comment by bruce5794163** [comment]
The example has contain the mainfest file ,and the content has owne mscomctl.ocx ,but after run the example it don't  display the web element tooltiptext .test.html content like this <a title="test" >112</a>
but the title don't display when the mouse hover it.
![mainfest](https://cloud.githubusercontent.com/assets/15192211/10596318/9e4851e0-7715-11e5-99b0-aa4f1ee31c6e.png)
![test](https://cloud.githubusercontent.com/assets/15192211/10596317/9e24c07c-7715-11e5-92b1-c006ef8400a1.png)

**Comment by amaitland** [comment]
`master` running using `VS2013`
![capture](https://cloud.githubusercontent.com/assets/307872/10596471/f39d3c16-7727-11e5-8639-b3672627c11c.PNG)

**Comment by amaitland** [comment]
See http://magpcss.org/ceforum/viewtopic.php?f=6&t=11514&p=20387&hilit=Microsoft.Windows.Common+Controls#p20387

**Comment by bruce5794163** [comment]
master running using vs2013 ,
![test](https://cloud.githubusercontent.com/assets/15192211/10598962/9009dfca-7730-11e5-9e1c-456dadca6ba2.png)

**Comment by bruce5794163** [comment]
![20151020134252](https://cloud.githubusercontent.com/assets/15192211/10598967/a3e641e6-7730-11e5-8c8b-d6849cb68fbb.jpg)
master in 2013,not display .......

**Comment by amaitland** [comment]
Is your system completely up to do? Looking at your fonts compared to mine, they don't look crisp and clear.

I don't believe the problem is related to `CefSharp` or even `CEF` directly.

**Comment by bruce5794163** [comment]
![error](https://cloud.githubusercontent.com/assets/15192211/10599890/e6a71df4-7738-11e5-80e4-07ff67f098ba.jpg)

**Comment by bruce5794163** [comment]
![error](https://cloud.githubusercontent.com/assets/15192211/10599911/0b97b9d4-7739-11e5-8965-f1489c5695b0.jpg)
they don't look crisp and clear? the problem is related to mscomctl.ocx file?

**Comment by bruce5794163** [comment]
![123](https://cloud.githubusercontent.com/assets/15192211/10599938/5791f3d6-7739-11e5-8260-e7e33993b90a.jpg)
they don't look crisp and clear? the problem related to mscomctl.ocx file?

**Comment by amaitland** [comment]
> the problem related to mscomctl.ocx file?

I was under the impression `Microsoft.Windows.Common-Controls = Comctl32.dll`. I could be mistaken.

You'll have to investigate this further on your own.

**Comment by bruce5794163** [comment]
comctl32.dll is already exist,but still not display the tooltip ,boring .

**Comment by bruce5794163** [comment]
comctl32.dll is already exist,but still not display the tooltip.

**Comment by bruce5794163** [comment]
Is it relate to simple chinese system ? I am running application  at win7 simple chinese system for ultimate.

**Comment by amaitland** [comment]
> comctl32.dll is already exist,but still not display the tooltip.

Your app manifest must include  the relevant entry for tooltips to work

> Is it relate to simple chinese system ? I am running application at win7 simple chinese system for ultimate.

Possible, I have no experience with Chinese systems.

**Comment by bruce5794163** [comment]
I am using the example .have include it.
![manfest20151020170302](https://cloud.githubusercontent.com/assets/15192211/10602712/89737006-774c-11e5-9216-9d6d472d3a54.png)

**Comment by amaitland** [comment]
Try downloading the `cefclient` example applicaiton and running that on your system.

https://cefbuilds.com/

Grab the latest 32bit build from the `2357` branch. If that doesn't work then it's a problem with your system.

Not much more I can do sorry, good luck sorting it!

**Comment by amaitland** [comment]
`cefclient = TestApp` on the `cefbuilds.com` website

**Comment by bruce5794163** [comment]
It works well ,here is the screen shot
![Uploading streen2.jpg…]()

**Comment by bruce5794163** [comment]
It works well ,here is the screen shot
![streen2](https://cloud.githubusercontent.com/assets/15192211/10605373/6f73d0b8-775d-11e5-8eca-8f88ed0976fa.jpg)

**Comment by bruce5794163** [comment]
and at the wpf project ,the tooltiptext can display ,but the winform can't display.

**Comment by bruce5794163** [comment]
I got it,run at release mode ,the tooltip show,thank's .
