### ISSUE TITLE
Grey outline around fonts in transparent background

### ISSUE THREAD

**Issue by Antonyo** [cefsharp/CefSharp#1351]
## Description

I'm experiencing a thin grey border around fonts when the background is transparent which causes small fonts hard to read:
![Example](https://dl.dropboxusercontent.com/u/15434420/outlineborder.PNG)

## Version

v43.0.0 in `wpf`. Windows 10 x86 but I think it happens in any Windows version.

## How to recreate

I've set up an example here:
fc2aae9c885c94d795e28ee7b5b7f0e95efda73f

Just run the wpf example project.

**Comment by amaitland** [comment]
Possibly related http://magpcss.org/ceforum/viewtopic.php?f=6&t=13404

**Comment by amaitland** [comment]
@Antonyo Did you come up with a solution?

**Comment by Antonyo** [comment]
Not really, we decided just to always specify a solid color so the halo problem was gone.

**Comment by amaitland** [comment]
Fair enough.

Anyone needing further clarification on this will need to ask on `ceforum`, the link provided above is a likely starting point.
