### ISSUE TITLE
Bug: C# Code Behind Stops Interacting With Browser When Window Focus Changes

### ISSUE THREAD

**Issue by matthax** [cefsharp/CefSharp#1353]
#### Issue Summary
The issue I am encountering occurs when content has been rendered onto a canvas element in the CefSharp browser using data from a C# object. When the window focus changes, the rendered content is lost a the C# code is no longer called by the browser.

#### Steps to Reproduce
1. Create an index.html file with a canvas element.
2. Register a C# object to the browser with a method GetLine (return data for drawing on canvas)
3. Call GetLine repeatedly, update the canvas with the new line
4. Click off of the main browser screen (or load dev tools)
5. Return focus to the browser screen (the content should then re-render)

#### Technical details
* CefSharp Version: nuget - v43.0.0
* Operating System: 
* x64: Windows 10
* WPF

**Comment by amaitland** [comment]
First step is to confirm if the bug exists in the `cefclient` example application.

https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

Can you provide a `jsfiddle` that can be used to reproduce the problem?

**Comment by matthax** [comment]
Here is the <code> jsfiddle</code> http://jsfiddle.net/MattDev/v5y2swu3/
I was able to run the sample there on both my code and the test application. It looks like the issue is actually a result of the Javascript/C# interaction through the registered object when the focus is lost. I will attempt to force the C# code to do the update and see if that fixes the problem.

Apologies for not doing my due diligence, feel free to close the issue.

**Comment by illfang** [comment]
One reason a Canvas can lose it's data is when the Canvas gets resized. Maybe you trigger a resize of the canvas once focus gained.

**Comment by matthax** [comment]
Here is a short gif showing the issue. The spectrum is updated every 25ms, so any breakpoints set should be hit almost instantly, which is not the case.
https://i.gyazo.com/dbcb8608b725e812acf19fc2c26a590e.gif
https://i.gyazo.com/794a1738bffebeddb2ceb5c6a97f016b.gif

I am not really familiar with the CEF to the extent where I could say it is some sort of delayed execution or cpu delegation but perhaps that is the cause. Unfortunately I cannot test my instance directly with the test application so this could still be an issue simply with my code.

**Comment by matthax** [comment]
@amaitland 
Here is some updated sample code that should allow you to recreate the issue (Requires JSON serializer):
HTML:
<code>
canvas id='canvas' class="" width="700" height="300"></canvas>
</code>
JavaScript:
<code>
     var canvas = document.getElementById('canvas');

     var ctx = canvas.getContext('2d');

     var gradient = ctx.createLinearGradient(0, 0, 0, this.canvas.height);

     gradient.addColorStop(0.5, #ff0);

     ctx.fillStyle = gradient; 

     setTimeout(function () { 
        ctx.clearRect(0, 0, thisContext.canvas.width, thisContext.canvas.height);
        var spectrum = JSON.parse(bugger.getArray());
        for(var i = 0; i < spectrum.length; i++) {
            ctx.fillRect(i * (12), canvas.height - spectrum[i], 10, canvas.height);
        }, 1000);
</code>

C#
<code>
    ChromiumBrowser.RegisterJsObject("bugger", new CefSharpBugSample());


    public class CefSharpBugSample
    {
        private int[] array;
        Random r;
        public CefSharpBugSample()
        {
            this.array = new int[16];
            this.r = new Random();
        }
        public string getArray()
        {
            for(int i =0; i < this.array.Length; i++)
            {
                this.array[i] = r.Next(255);
            }
            return JsonConvert.SerializeObject(this.array);
        }
    }
</code>

**Comment by amaitland** [comment]
@matthax Please fork `CefSharp` and demo the problem using one of the example projects or use the `MinimalExample` :+1: 

https://github.com/cefsharp/CefSharp.MinimalExample

**Comment by matthax** [comment]
Seems to be an issue with the BASS.NET API

**Comment by matthax** [comment]
@amaitland 
The official verdict is as follows:
de-focusing and re-focusing the window caused the content in the pages script tags to be re-evaluated and executed. This caused my callback function to be toggled on and off. I'm not really sure why the code was re-evaluated but that may be a chromium thing. Thanks for putting up with the flood of comments, you've done a really nice job here.
