### ISSUE TITLE
114 Erros to open CefSharp3.sln?

### ISSUE THREAD

**Issue by shirotzu** [cefsharp/CefSharp#1362]
I get 114 Errors only to open the CefSharp3.sln and if 12 more errors if change the startup project to CefSharp.WinForms.Example
What should I do?

Compile Error : 

    Restoring NuGet packages...
    To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
    NuGet Package restore failed for project CefSharp.Test: Unable to find version '3.18.7' of package 'AutoFixture'..
    NuGet Package restore failed for project CefSharp.Test: Unable to find version '3.18.7' of package 'AutoFixture.Xunit'..
    NuGet Package restore failed for project CefSharp.Wpf.Example: Unable to find version '5.1.1' of package 'MvvmLightLibs'..
    NuGet Package restore failed for project CefSharp.Test: Unable to find version '1.9.2' of package 'xunit'..
    NuGet Package restore failed for project CefSharp.Wpf.Example: Unable to find version '1.3.0' of package 'CommonServiceLocator'..
    NuGet Package restore failed for project CefSharp.Test: Unable to find version '1.9.2' of package 'xunit.extensions'..
    NuGet package restore failed.
    1>------ Build started: Project: CefSharp.Example, Configuration: Debug x86 ------
    2>------ Build started: Project: CefSharp.BrowserSubprocess, Configuration: Debug x86 ------
    3>------ Build started: Project: CefSharp.WinForms, Configuration: Debug x86 ------
    2>CSC : error CS0006: Metadata file 'C:\Users\Kevin\Desktop\CefSharp-master\Debug\CefSharp.BrowserSubprocess.Core.dll' could not be found
    3>CSC : error CS0006: Metadata file 'C:\Users\Kevin\Desktop\CefSharp-master\CefSharp.Core\bin\Debug\CefSharp.Core.dll' could not be found
    1>CSC : error CS0006: Metadata file 'C:\Users\Kevin\Desktop\CefSharp-master\CefSharp.Core\bin\Debug\CefSharp.Core.dll' could not be found
    4>------ Build started: Project: CefSharp.WinForms.Example, Configuration: Debug x86 ------
    4>CSC : error CS0006: Metadata file 'C:\Users\Kevin\Desktop\CefSharp-master\CefSharp.Core\bin\Debug\CefSharp.Core.dll' could not be found
    4>CSC : error CS0006: Metadata file 'C:\Users\Kevin\Desktop\CefSharp-master\CefSharp.Example\bin\x86\Debug\CefSharp.Example.dll' could not be found
    4>CSC : error CS0006: Metadata file 'C:\Users\Kevin\Desktop\CefSharp-master\CefSharp.WinForms\bin\x86\Debug\CefSharp.WinForms.dll' could not be found
    ========== Build: 0 succeeded, 4 failed, 1 up-to-date, 0 skipped ==========

In NuGet Package Manager set the next message : 
An error accurred while trying to restore packages. Unable to find version '1.9.2' of package 'xunit.extensions'.
Too
An error accurred while trying to restore packages. Unable to find version '3.18.7' of package 'AutoFixture.Xunit'. and maybe others because i get fail building.

Fail to Build image 
http://i.stack.imgur.com/BuUP0.png

OS : Window 10 | 64 bits
Visual Studio 2015

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue

**Comment by shirotzu** [comment]
>Edited

**Comment by amaitland** [comment]
Check your nuget package manager sources, make sure `nuget.org` is checked. If obviously won't compile until your resolve the `nuget` problems.

`VS2013` is what I actively develop in. `VS2015` was added, though not well tested (as I don't use it for everyday development). So try using `VS2013` if you have a copy, otherwise get the `VS2013 Community` edition which is free for `OS projects`.

**Comment by shirotzu** [comment]
Okay I'll download the Visual Studio 2013 Community and see how it goes.

**Comment by amaitland** [comment]
Do you have other projects that can successfully download packages from `nuget.org`

**Comment by shirotzu** [comment]
I created projects as a game agar.io with CEF1,
And restore NuGet successfully without any problem but now with the CEF3 no, because apart from only install 3 packages NuGet is asking me others that not found.

**Comment by amaitland** [comment]
Is there are reason your trying to build `master` from source?

There are nightly builds generated by the `CI` server 

https://www.myget.org/gallery/cefsharp

**Comment by shirotzu** [comment]
Not that I know much about CEF and CSharp, I'm still a rookie but I have every intension to learn and would soon be working with CEF3 to start my projects with CEF3 already that is much more stable and updated that CEF1.

normally i did was:
1. download the CefSharp-master.zip
2. Open file 'Build.bat' or run with PowerShell the file 'Build.ps1'
3. Run CefSharp3.sln
4. Change the startup project by CefSharp.WinForms.Example
5. Try to compile/run

But just in step 3 I have about 114 errors.
I did something wrong, I am missing something, I'm really mad?

**Comment by shirotzu** [comment]
I get 2 error and much adverticements but this work ! Thank you !
http://prntscr.com/8ubjrt

**Comment by shirotzu** [comment]
How remove the message "When running this Example outside of Visual Studio please make sure you compile in Release mode"?
