### ISSUE TITLE
Cookie header not working

### ISSUE THREAD

**Issue by Farcek** [cefsharp/CefSharp#1365]
help please.

i cannot write cookie value.  already GetGlobalCookieManager.SetCookieAsync used. it is not worink

    Cef.GetGlobalCookieManager()
         .SetCookieAsync(wc.ResponseUrl.BaseUrl(), new CefSharp.Cookie())

----

    ResourceHandler rh = ResourceHandler.FromString(html);
    rh.Headers.Add("Set-Cookie", wc.CookieHeadersString());                        <<-- not work
    rh.Headers.Add("X-Powered-By", "test");                          <<-- working

    rsHandlderFactory.RegisterHandler(wc.ResponseUrl.ToString(), rh);
    chromiumWebBrowser.Load(wc.ResponseUrl.ToString());

chromiumWebBrowser version 43.0.0

**Comment by amaitland** [comment]
> Cef.GetGlobalCookieManager() .SetCookieAsync(wc.ResponseUrl.BaseUrl(), new CefSharp.Cookie())

You need to provide values for the `Cookie` class, name, value, domain, etc

If the `X-Powered-By` works correctly, then the `Set-Cookie` it's likely not supported by `CEF`.

**Comment by Farcek** [comment]
hmm. already GetGlobalCookieManager.SetCookieAsync used. it is not worink

    var cm = Cef.GetGlobalCookieManager();    
    Task<bool> t = cm.SetCookieAsync(wc.ResponseUrl.BaseUrl(), new CefSharp.Cookie()
    {
        Domain = uri.Host,
        Name = "test",
        Value = "test val " + DateTime.Now.ToString(),
        Creation = DateTime.Now,
        Expires = DateTime.Now.AddDays(20)
    });

    t.Wait();

    PrintAllCookies(String.Format("add : {0}", t.Result));  
    //     t.Result     <-- is value true

**Comment by Farcek** [comment]
also configration

    CefSettings settings = new CefSettings();
    ...
    settings.CachePath = "app-cache";

    Cef.Initialize(settings,true,true);
    Cef.OnContextInitialized = () =>
    {
        var cm= Cef.GetGlobalCookieManager();
        cm.SetStoragePath("cookies1", true);
        cm.SetSupportedSchemes("chrome-devtools", "http", "https");
    };

**Comment by amaitland** [comment]
It appears to be working as expected

```c#
var cookieManager = Cef.GetGlobalCookieManager();
var success = await cookieManager.SetCookieAsync("custom://cefsharp/Home.html", new Cookie
{
	Name = "test" + DateTime.Now.Ticks,
	Value = "test val " + DateTime.Now.ToString(),
	Creation = DateTime.Now,
	Expires = DateTime.Now.AddHours(1)
});

//await cookieManager.FlushStoreAsync();

var cookieVisitor = new ListCookieVisitor();
cookieManager.VisitAllCookies(cookieVisitor);

var cookies = await cookieVisitor.Task;

foreach(var cookie in cookies)
{
	Console.WriteLine("Cookie Name:" + cookie);
}
```

**Comment by amaitland** [comment]
@Farcek Anything further on this?

**Comment by amaitland** [comment]
Closing due to lack of feedback.

**Comment by bavly** [comment]
Hi amaitland 

I did that in the code 

var cookieManager = Cef.GetGlobalCookieManager();
            var success = cookieManager.SetCookieAsync(url, new CefSharp.Cookie()
            {
                Name = key.ToString(),
                Value = value.ToString(),
                
            });

            MessageBox.Show(success.Result.ToString());
            
            browser.Address = url;
            
it's still open on login page although success.result returns True 
Any help please

Thanks

**Comment by amaitland** [comment]
If you have a question then ask it on https://gitter.im/cefsharp/CefSharp
