### ISSUE TITLE
EvaluateScriptAsync missing from latest build

### ISSUE THREAD

**Issue by hgupta9** [cefsharp/CefSharp#1367]
I downloaded CefSharp.WinForms 43.0.0 using NuGet. It appears that the "EvaluateScriptAsync" and "ExecuteScriptAsync" methods are missing from ChromiumWebBrowser. There are numerous examples around the internet where the function is used to execute JS. Why was it removed? Are there any plans to add it back in? How do I execute JS anymore?

**Comment by amaitland** [comment]
It wasn't removed, it was just moved. It's now frame aware and can be executed on a per frame basis. The existing behavior is maintained by an extension method. (Quite a lot of functionality was moved into extension methods as to remove code duplication from the three flavors).

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp/WebBrowserExtensions.cs#L584

Anything your looking for `GitHub` has an excellent search functionality. You can of course download the source code.

https://github.com/cefsharp/CefSharp/search?utf8=%E2%9C%93&q=EvaluateScriptAsync

**Comment by hgupta9** [comment]
Yes I downloaded the latest trunk code & the v43 DLLs from nuget and the function seemed to be missing. So then I went ahead and downloaded the r43 branch (source), opened those files in VS, and then the function magically reappeared in VS. I guess it was linking to the source code on my disk even though the v43 DLL had the function. VS is crazy.
