### ISSUE TITLE
EvaluateScriptAsync not returning any value

### ISSUE THREAD

**Issue by hgupta9** [cefsharp/CefSharp#1368]
I'm doing this on `FrameLoadEnd` 

     browser.ExecuteScriptAsync("document.body.onmouseup = function(){ jsObject.OnSelected() }");

And so when the user selects a bit of text using the mouse I'm doing this;

     public void OnSelected(){
         Task<JavascriptResponse> t = browser.EvaluateScriptAsync("window.getSelection()");
         t.Wait();
         object result = t.Result.Result; // null
     }

If I do the following instead, it correctly displays the selected text:

     browser.ExecuteScriptAsync("document.body.onmouseup = function(){ alert(window.getSelection()) }");

I'm using this round-about method because there is no way to pass a string from JS to C# using `jsObject`, if there was, I would've liked to do:

     browser.ExecuteScriptAsync("document.body.onmouseup = function(){ jsObject.OnSelected(window.getSelection()) }");

**Comment by hgupta9** [comment]
I solved my problem as of now (see http://stackoverflow.com/questions/33302464/how-to-get-an-event-when-the-user-selects-text-in-cefsharp/33302511#33302511) but the issue remains. EvaluateScriptAsync returns null when it should not.

**Comment by amaitland** [comment]
Use a `IJavascriptCallback` instead, you cannot execute `EvaluateScriptAsync` in a `sync` bound method call (you can in the `async` version, though that's a totally different feature).

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.Example/BoundObject.cs#L49

**Comment by amaitland** [comment]
Your FAQ entry needs some changes, will post details later. In general I'm not a fan of having code in the FAQ as there then becomes the maintenance task of keeping it up to date. I'm thinking it might be better to have an entry that links to the example project code an move your sample there.

**Comment by amaitland** [comment]
`OnDocumentLoad` should be renamed to something like `OnFrameLoadEnd` to keep things simple. Follow on to that, `FrameLoadEnd` is called for every frame, so a page with multiple frames will be executing the script multiple times, which is likely unexpected for most people. Should check the `e.Frame.IsMain` argument to make that clear. The  `RegisterJsObject` is called using the defaults and as such `OnSelected` will be camelCased to `onSelected`.

I'd suggest that the notes would be better as comments so they're in context. As I mentioned earlier, I'm not really a fan of adding blocks of code to the `FAQ`. I know there are a few entries there already, and I'd ideally remove them if there weren't links out there pointing to them.

**Comment by hgupta9** [comment]
I'm sorry. I did my best. All I could do with less than a day's worth of time invested into learning CefSharp. From a dev's standpoint, I actually like code examples in the FAQ because they let you see exactly the snippet that's required to perform a certain task, rather than a full-class .cs file that may contain too much of extraneous stuff that you don't really need (or have the time to understand). They also let you copy-paste-modify, instead of going through a huge class file and cherry-picking the lines that pertain to the issue. I think they FAQ is the best document you have here, and its a pity its not linked prominently from the project's readme markdown file.

Good luck with your project, its the COOLEST browser in C# that I can possibly find. I've tried like 6 including Gecko wrappers and Awesomium. Yes, its better than Awesomium which is totally non-awesome in C# BTW. 10-15 sec startup time on a decent machine and buggy implementation (hangs up frequently, slow browsing compared to chrome, etc). CefSharp starts in <100 ms which is fantastic, and browsing speed is actually a bit faster than Google Chrome! What gives?!. And its 100% reliable, no bugs, crashes, hangs or whatever. I just had trouble with the events which I attempted to fix for newbies (like myself) by adding a FAQ entry. 

If you really want to know the best way to write good, readable, useful docs, see ObjectListView. This (http://objectlistview.sourceforge.net/cs/index.html) and this (http://objectlistview.sourceforge.net/cs/gettingStarted.html) and this (http://objectlistview.sourceforge.net/cs/recipes.html). Really useful; the help is there when you need it, SO not required.

**Comment by amaitland** [comment]
> I'm sorry. I did my best.

No need to apologize, you had a go, which is more than most :+1: 

> I actually like code examples in the FAQ because they let you see exactly the snippet that's required to perform a certain task, rather than a full-class .cs file that may contain too much of extraneous stuff that you don't really need (or have the time to understand). They also let you copy-paste-modify, instead of going through a huge class file and cherry-picking the lines that pertain to the issue.

I can understand that, and you'll have no argument from  me, it really is just about the amount of time required to write and then subsequently maintain the doco.

> CefSharp starts in <100 ms which is fantastic, and browsing speed is actually a bit faster than Google Chrome! What gives?!

That's not really `CefSharp`, all the credit goes to the `CEF` project. `CefSharp` is just a wrapper. (`CEF` is a no frills framework, so it should be fairly quick as it doesn't have extensions and other features to worry about).

> If you would like help with the docs maybe I could help? I'm good with C#, C++/CLI and anything else that's required. Graphics too! Maybe if you tell me the sections that require docs I could help? Maybe. Maybe if I find time I could do a kinda cage-match for the various browser engines and post it on codeproject.

Whatever time you have to contribute would be fantastic :+1: 

Having `recipes` does make sense in a lot of ways, so I have to wonder if there's a way to combine that with having real code? Maybe some sort of `App`? Maybe load each example and you get to see the `html` and `c# back end code`? I guess maybe like what you get from `jsfiddle`. Just an idea at this stage of course.

**Comment by hgupta9** [comment]
BTW what do you mean by "real code"? How does "real code" differ from 
code examples in an FAQ?

Yes, something like an "examples explorer". Have you seen tour de flex? 
(http://flex.apache.org/tourdeflex/) Only it should be shipped in binary 
form so devs don't have to compile the examples explorer from source in 
order to actually begin browsing!

One way is just create it in JS with a screenshot to show the result. 
Tree of topics on the left. Click an item to see the code sample and the 
screenshot. Bingo. Click the "download" button to download a CS file or 
project for that example.

**Comment by amaitland** [comment]
> BTW what do you mean by "real code"? How does "real code" differ from code examples in an FAQ?

Code that you can compile and execute. Code in markdown/html is hard to maintain and prone to inaccuracies. 

> Yes, something like an "examples explorer". Have you seen tour de flex? (http://flex.apache.org/tourdeflex/) Only it should be shipped in binary form so devs don't have to compile the examples explorer from source in order to actually begin browsing!

Something similar I guess. I'd prefer to stay away from distributing in binary format. I'd prefer to go with something like the `MinimalExample` project, a project that uses the latest release `Nuget` packages, you can download and then modify the source. Each example would be logically grouped so you can identify the relevant code. e.g. You could be able to browse the individual examples on `GitHub` and get a fairly clear understanding of what's going on.

> These are also good examples of stuff that I could help create:

In my experience few stick around to help out for the long haul, so I'm not interested in creating a huge `markdown` document that needs maintaining and then being the only person willing/able to contribute in three months time. The `CefSharp.Tutorial` project is just one example of such happening.

I admire the enthusiasm and any time/effort your prepared to contribute would be greatly appreciated :+1:

**Comment by amaitland** [comment]
@hgupta9 If your still interested in contributing then feel free to open a new issue to discuss.
