### ISSUE TITLE
How merge CefSharp.Browser  Subprocess.exe and CefSharp.Minimal Example.WinForms.exe?

### ISSUE THREAD

**Issue by shirotzu** [cefsharp/CefSharp#1369]
In the latest version of CEF I've noticed that just exist an executable file and is opened 3 times, and the other have to be 2 executables.

Chromium Embedded Framework (CEF) Client Binary Distribution for Windows
-------------------------------------------------------------------------------

Date:             October 13, 2015

CEF Version:      3.2526.1330.g8aac233
CEF URL:          https://bitbucket.org/chromiumembedded/cef.git
                  @8aac23386e83a7bde597fec28a0d3d117d8e981c

Chromium Verison: 47.0.2526.0
Chromium URL:     https://chromium.googlesource.com/chromium/src.git
                  @cb947c0153db0ec02a8abbcb3ca086d88bf6006f

How I can make it only be one executable file?

**Comment by amaitland** [comment]
> How I can make it only be one executable file?

`CEF3` uses a multi process model, it requires additional processes for rendering, gpu, plugins. It's by design and not something you can change.
