### ISSUE TITLE
Replacing HTML source code

### ISSUE THREAD

**Issue by shirotzu** [cefsharp/CefSharp#1370]
I'm trying clear page source code and load other code but opened it in the current url of the clear page
as if modified from devtools.

I used several javascript codes to try to achieve but still nothing

This only work with tampermonkey extension
```
window.stop(),document.documentElement.innerHTML=null,GM_xmlhttpRequest({method:"GET",url:"http://trafficmonsoon.byethost32.com",onload:function(e){document.open(),document.write(e.responseText),document.close()}});
```

```
      var newContent='HTML HERE';
      function ReplaceContent(NC) {
        document.write(NC);
        document.close();
      }
      function Hi() {
        ReplaceContent(newContent);
      }
```

**Comment by amaitland** [comment]
Please only ask CefSharp specific questions here. For general help try somewhere like stackoverflow.
