### ISSUE TITLE
runtime system   environment 

### ISSUE THREAD

**Issue by bruce5794163** [cefsharp/CefSharp#1371]
I have a case to comfirm,In the release note ,cef is define to run in at least vs2010 build ide,so ,the framework is 4.0 version. can this application run at windows xp sp3 system?

**Comment by amaitland** [comment]
CEF it's self will. The latest Nuget package for CefSharp does not.

**Comment by bruce5794163** [comment]
can you rebulid a  package at master source ?then,i can  realize the example run at windows xp sp3 system?

**Comment by amaitland** [comment]
You can build the source or use the CI builds listed on the project homepage.

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#XPSupport
