### ISSUE TITLE
Feature Request - Document Ready

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#1373]
This is somewhat a place holder for an idea. 

In `OnContextCreated` execute some js to hook up a `well known` function to the relevant `document ready` handler. Check if function exists and wire up the appropriate event if it does. Potentially combine this with `RegisterExtension` to allow for injecting code into an existing page.

http://magpcss.org/ceforum/apidocs3/projects/%28default%29/CefRenderProcessHandler.html#OnContextCreated%28CefRefPtr%3CCefBrowser%3E,CefRefPtr%3CCefFrame%3E,CefRefPtr%3CCefV8Context%3E%29

Other suggestions are welcome.

**Comment by amaitland** [comment]
First attempt at https://github.com/amaitland/CefSharp/commit/eaade258660bb4f5cea049a13b80a2161207a73a implementing this.

Not sure the concept is sound yet. Would like to only execute the script if the relevant extension is registered (maybe the extension needs to be a specific name).

You can call into a bound object using the code.

**Comment by rover886** [comment]
@amaitland I am also searching for the same. An event to detect the `document.ready` event from the native browser not from JS. Actually it will be very helpful if we can trap this event and modify some DOM objects.

In my CEFSharp flavored application I am facing issue of dropdown box going behind application when application is set to `TopMost=true;`, for that we are using an Jquery based solution which will transform native dropdown to div based dropdown. Now for this I have to change EACH web application :(. If we can trap native `document.ready` event then I can call javascript to transform the native dropdown. Also I need to load an js file for the same on this event.

**Comment by amaitland** [comment]
@rover886 Your welcome to test out what I've hacked together. I don't have any time to continue working on this. If it's something you need and have time/resources then feel free to create a `PR` implementing the feature your require.

**Comment by amaitland** [comment]
Thinking about this a little more, and I'm inclined to go with an approach where a user can register a block of javascript that will be executed when the context is created. Similar to how an object is `bound` with `JSB`. 

- Register script e.g. `RegisterScript`
- When context is created execute script using main frame the main frame.
- Maybe even execute two blocks of script, one before and one after the objects have been bound.

**Comment by rover886** [comment]
What I understand from [OnContextCreated](http://magpcss.org/ceforum/apidocs3/projects/%28default%29/CefRenderProcessHandler.html#OnContextCreated%28CefRefPtr%3CCefBrowser%3E,CefRefPtr%3CCefFrame%3E,CefRefPtr%3CCefV8Context%3E%29) is, this event gets called immediately when an `CefFrame` gets created. (correct me if I am wrong)

So if a web page is having `iframe` then the registered block of javascript will execute two times (1. main frame and 2. iframe) or just once? If it's just for once then what if registered javascript is having some code block where some hidden values from `iframe` are accessed?

**Comment by amaitland** [comment]
> Called immediately after the V8 context for a frame has been created

It gets called immediately after `CefV8Context` is created. (In the `Render` process). The call is made once for every `CefFrame` that's on the page. So if a page has a single `iframe`, it will be called twice. You can check `IsMain()` to determine if the context belongs to the main frame.

https://github.com/amaitland/CefSharp/commit/eaade258660bb4f5cea049a13b80a2161207a73a#diff-a27ca20dcc4f76e2dde0c785dd2abb9cR83

> If it's just for once then what if registered javascript is having some code block where some hidden values from iframe are accessed?

I'm not sure I understand the question. What exactly is a `hidden` value? You should be able to register for the `DOMContentLoaded` event and then access any sub frames through the main frame. Executing in `sub` frames, will likely cause a lot of problems as there would be no way to pick which frames the script would be explicitly called in.

My proposed solution won't work for `100%` of use cases. Implementing #1149 would be required to have complete control.

**Comment by amaitland** [comment]
Just as a side note, if a page/frame has no javascript on it then no `CefV8Context` will be created.

**Comment by amaitland** [comment]
I've implemented a different approach, see #1460

**Comment by rover886** [comment]
Thanks a lot :+1:. I will also test with my web application where multiple `Iframes` are used. Currently I am achieving this by exposing an C# object  using `RegisterJsObject` method and calling methods from that object on Jquery `document.ready` event. So on every `Iframe` `document.ready` I have done this.

**Comment by amaitland** [comment]
Great, let me know how it goes :+1:

**Comment by amaitland** [comment]
With #1460 merged you can now hook the `DOMContentLoaded` event. See https://github.com/cefsharp/CefSharp/pull/1460/files#diff-aaf166e702850ed55270d9b58e2c3aa6R183 for a basic example.

**Comment by canton7** [comment]
(For anyone finding this issue from Google, and wondering where `OnContextLoaded` went, it was moved to [`IRenderProcessMessageHandler`](https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/RenderProcessMessageHandler.cs#L18)).
