### ISSUE TITLE
How to get Page load time?

### ISSUE THREAD

**Issue by LeMoussel** [cefsharp/CefSharp#1376]
I want to measure page load time.
Code I am using 
````C#
     using (ChromiumWebBrowser browser = new ChromiumWebBrowser("http://crawlbin.com/"))
     {
          Stopwatch sw = new Stopwatch();
          sw.Start();
          await LoadPageAsync(browser);
          sw.Stop();
          string timeToLoad = sw.Elapsed.TotalSeconds.ToString();
     }
````
Is it correct? or any better way?

**Comment by jankurianski** [comment]
I searched the CefSharp code in `master` and could not find a `LoadAsync` method.

Please read over the following guide and add more detail (e.g. version, WPF/WinForms, etc.) https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue

Also I do not understand what you mean by page load time.  Are you looking for DOM to be ready, for all external resources to be loaded, etc.?

**Comment by LeMoussel** [comment]
Oups ! Mistake with `LoadAsync` method., I update with `LoadPageAsync`method. (Rem: I use [OffScreen example] (https://github.com/cefsharp/CefSharp/tree/master/CefSharp.OffScreen.Example) for my tests)
I want  to measure the time it takes to load the page with all external resources.

**Comment by amaitland** [comment]
There is no built in method that I'm aware of. If your just interested in loading external resouces then the code you have should be fine assuming your using `LoadingStateChanged`. The other option you might look at is `Chrome Driver/Selenium`. There may be some useful metrics there if you need more detailed information. (A quick google and I'm sure you'll find some examples that can be ported across).

https://bitbucket.org/chromiumembedded/cef/wiki/UsingChromeDriver.md

**Comment by LeMoussel** [comment]
I found [Navigation Timing API](https://developer.mozilla.org/en-US/docs/Web/API/Navigation_timing_API).
*The Navigation Timing API provides data that can be used to measure the performance of a website. Unlike other JavaScript-based mechanisms that have been used for the same purpose, this API can provide end-to-end latency data that can be more useful and accurate.*

To calculate the total time required to load a page, I do this 
````C#
JavascriptResponse JavaScriptResponsePageLoadTime = await browser.EvaluateScriptAsync(@"
(function() {
    var perfData = window.performance.timing;
    var pageLoadTime = perfData.loadEventEnd - perfData.navigationStart;
    return pageLoadTime;
 })();
");
Int32 JavaScriptResultPageLoadTime = (Int32)(JavaScriptResponsePageLoadTime.Success ? (JavaScriptResponsePageLoadTime.Result ?? "") : JavaScriptResponsePageLoadTime.Message);

````

**Comment by amaitland** [comment]
Handy, thanks :+1:
