### ISSUE TITLE
Open All Links In Current Window - Disallow New Windows / Tabs (.NET- WinForms)

### ISSUE THREAD

**Issue by CFlanc** [cefsharp/CefSharp#1378]
How to Prevent Opening Links in New Windows / Tab In .Net WinForms I Know This Question Has Been Asked And Answered Many Times But I Couldn't Figure Out How to Do So On .NET- WinForms

I haven't Tried Anything so far
Here's My Code :

```vb.net
Imports CefSharp.WinForms
Imports CefSharp
 
Public Class Form1
 
    Private WithEvents browser As ChromiumWebBrowser
 
    Public Sub New()
        InitializeComponent()
 
        Dim settings As New CefSettings()
        settings.CachePath = "Cache"
        CefSharp.Cef.Initialize(settings)
 
        browser = New ChromiumWebBrowser("http://website.com") With {
            .Dock = DockStyle.Fill
        }
        panBrowser.Controls.Add(browser)
 
    End Sub
End Class
```

Now Where Do I add The Code From #600 Comment And What Code

**Comment by amaitland** [comment]
What have you tried so far?

What was the result from using https://github.com/cefsharp/CefSharp/issues/600#issuecomment-62859981

Please read over https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue your issue is rather brief and lacking information.

**Comment by amaitland** [comment]
@CFlanc It's preferred if you post additional comments when updating information, `GitHub` provides no notification if you edit the previous comment.

**Comment by amaitland** [comment]
What version are you using?

> Now Where Do I add The Code From #600 Comment And What Code

What is your difficulty? Implement `ILifeSpanHandler` as suggested.

**Comment by amaitland** [comment]
See how I edited your original post to markdown your code, makes it much easier to read, please apply markdown in future.

**Comment by CFlanc** [comment]
@amaitland 
I haven't tried anything yet i still trying to figure out where to implement the code from #600

**Comment by amaitland** [comment]
> I haven't tried anything yet

Here is a general usage example if `ILifeSpanHandler`, you need to apply the suggested implementation.

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.WinForms.Example/BrowserTabUserControl.cs#L33
https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.WinForms.Example/Handlers/LifeSpanHandler.cs

The rest is really upto to you, if your not prepared to at least have a go then there isn't any more we can do to help.

**Comment by CFlanc** [comment]
Thanks I will try to work it out

**Comment by amaitland** [comment]
Closing due to lack of feedback.
