### ISSUE TITLE
is there any way catch all requests like devtool's network Monitor

### ISSUE THREAD

**Issue by gitlsl** [cefsharp/CefSharp#1379]
just like the title, i want catch all requests like devtool's network Monitor, in addtional if it can modify the request and response  is better!
3q

**Comment by amaitland** [comment]
A new option was recently added to the `CEF 2454` branch which is available in the current `master`. (There has been no official release based on this branch, there will likely be a `-pre` release coming up).

The method is `IRequestHandler.OnResourceResponse`

https://github.com/cefsharp/CefSharp/blob/master/CefSharp/IRequestHandler.cs#L172

It doesn't give you everything your after, it's the best that currently exists. Your other option is to intercept all requests, download them yourself using the build in `.Net` classes, which gives your full control.

**Comment by gitlsl** [comment]
@amaitland sorry for my english , i didn't understand your answer cleanly, 
so what you say  is   “in a coming up version there would be  a method named IRequestHandler.OnResourceResponse” can meet my needs ？  if i want use this feature now i should download source Compile by myself    

does it right?3q

**Comment by amaitland** [comment]
> if i want use this feature now i should download source Compile by myself

That or use a `CI` build from `MyGet` e.g. `v45.0.0-CI1555`

https://www.myget.org/gallery/cefsharp

**Comment by gitlsl** [comment]
oh i get it   thank you very much @amaitland

**Comment by amaitland** [comment]
> IRequestHandler.OnResourceResponse” can meet my needs ？

It's the best candidate that I can think of. I make no guarantees that it will meet your requirements as your requirements are quite vague.

**Comment by gitlsl** [comment]
for example: 
when a register an account on bbs, i input my username, then it will make a ajax request to check whether my username is existed， so i want catch the response dierecly to know the result,Why don't I start with DOM is that DOM may slowly and ajax'response contains more detail infomation

**Comment by amaitland** [comment]
> so i want catch the response dierecly to know the result

Unfortunately `CEF` only exposes limited access to the `Response` object. So that's unlikely to be useful in your scenario.

**Comment by gitlsl** [comment]
@amaitland  what a pity  this is a common feature request  ,  so  i use fiddler to capture and modify request or response it's helpfull if cefsharp give this feature

**Comment by amaitland** [comment]
> so i use fiddler to capture and modify request or response it's helpfull if cefsharp give this feature

`CEF` does not expose this feature, we've bound by the underlying framework here.

**Comment by amaitland** [comment]
@gitlsl Anything else before closing this?

**Comment by gitlsl** [comment]
@amaitland oh nothing close it
