### ISSUE TITLE
How exactly do I use pdf?

### ISSUE THREAD

**Issue by renestalder** [cefsharp/CefSharp#1382]
I couldn't get pdf working. Nothing happens on a click to a pdf file, referenced to a online web server.

I looked up several threads here on github and read about the pdf.dll. I can't find a pdf.dll, not in the lib folders nor in my built project.

After spending too much time, I honestly have to ask: How do I correctly embed a pdf with CefSharp into a WinForms project?

**Comment by amaitland** [comment]
What version are you using? For `43.0.x` see #1144

**Comment by renestalder** [comment]
Oh, thank you. I will watch over the thread and try the NPAPI solution until the version 45 is up in nuget. I will move further discussion to the other issue.
