### ISSUE TITLE
Release 45.0.0-pre01

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#1383]
Need to update the `cef.redist/cef.sdk` packages with a newer build from `cefbuilds.com` then release the `-pre`.

Check over the `nuget\Readme.txt` before hand just to make sure everything is in order as updating `VC++ 2013`.

**Comment by amaitland** [comment]
Upgraded to `3.2454.1344` this will likely be the version used for the `45.0.0` release. 

https://github.com/cefsharp/CefSharp/commit/bfe9fe63d96fd4122c9701bf7dea4ca608f81bbb

**Comment by amaitland** [comment]
With the upcoming `-pre` release I think it's time to create the `cefsharp/45` branch.

**Comment by amaitland** [comment]
New branch created https://github.com/cefsharp/CefSharp/tree/cefsharp/45

**Comment by amaitland** [comment]
Packages created and release tagged, just needs the final eyes over and test with `MinimalExample` before pushing to `Nuget.org`

**Comment by amaitland** [comment]
Packages are now on `Nuget.org`

**Comment by jankurianski** [comment]
Yay!  Nice work @amaitland :smile: :beer:

**Comment by amaitland** [comment]
Thanks @jankurianski :smile: Hopefully it'll only be a few weeks before the official `45.0.0` release :+1:

**Comment by amaitland** [comment]
With #1426 merged, that's the last change I had planned for `45`, so will create the packages and release the official version when I have some spare time.

**Comment by amaitland** [comment]
Packages should be up on `MyGet` shortly. Will do the usual tests and release to `Nuget` in the next few days.
