### ISSUE TITLE
Cefsharp.Winform.Example - browser doesn't render website. Why?

### ISSUE THREAD

**Issue by hungud** [cefsharp/CefSharp#1384]
I'm newbie, I use Cefsharp few days recently. I look it alternative window browser control in .NET

But when I try address:

http://www.vietjetair.com/Sites/Web/en-US/Home

And I try input flight form require and submit form. Next Url post, the Cefsharp browser don't render website

https://book.vietjetair.com/ameliapost.aspx?lang=en

But chrome, firefox, ie render website well 

Please check help me why? and explain it for me

Thanks you

**Comment by amaitland** [comment]
What branch are you using? The release branch is https://github.com/cefsharp/CefSharp/tree/cefsharp/43

For general testing please use the `MinimalExample` project as it uses the latest official `Nuget` packages.

https://github.com/cefsharp/CefSharp.MinimalExample

**Comment by jankurianski** [comment]
I don't understand what you mean by "don't render".  Is there an error? Is it blank?  Can you open the DevTools window and see what it says?

If you can post screenshots that would help too.

**Comment by hungud** [comment]
I had use branch master, and build sources

But I use CefSharp.MinimalExample.WinForms projects from

https://github.com/cefsharp/CefSharp.MinimalExample

And look good

Thanks
