### ISSUE TITLE
Limit the cache size?

### ISSUE THREAD

**Issue by ogborstad** [cefsharp/CefSharp#1385]
Is it possible to limit the cache size? I tried adding --disk-cache-size to CefCommandLineArgs to no avail.

**Comment by amaitland** [comment]
> There is no explicit way to limit the cache size.

Comment from the `CEF` project maintainer (for which `CefSharp` is based).
http://magpcss.org/ceforum/viewtopic.php?f=6&t=12702&p=24754#p24755
