### ISSUE TITLE
Feature Request - Add CefSettings.UserDataPath

### ISSUE THREAD

**Issue by myrnazhou** [cefsharp/CefSharp#1386]
Where are the files for spellchecker saved? If i remember it correctly it was on the ```CachePath\Dictionaries```, but i think it's no longer there.

**Comment by amaitland** [comment]
`ceforum` is probably your best bet to ask that question. Make sure you include which version your using.

http://magpcss.org/ceforum/index.php

**Comment by amaitland** [comment]
For anyone else interested looks like a new property was added to `CefSettings`. `user_data_path` has yet to be exposed as part of `CefSharp`.

http://magpcss.org/ceforum/viewtopic.php?f=6&t=13563

**Comment by amaitland** [comment]
> ///
  // The location where user data such as spell checking dictionary files will
  // be stored on disk. If empty then the default platform-specific user data
  // directory will be used ("~/.cef_user_data" directory on Linux,
  // "~/Library/Application Support/CEF/User Data" directory on Mac OS X,
  // "Local Settings\Application Data\CEF\User Data" directory under the user
  // profile directory on Windows).
  ///

So the relevant info for windows is it's stored in `Application Data`.
