### ISSUE TITLE
Bad response StatusCode with redirection

### ISSUE THREAD

**Issue by LeMoussel** [cefsharp/CefSharp#1387]
I intercept response before returning it to the browser with the `OnResourceResponse` method like this 
````C#
bool IRequestHandler.OnResourceResponse(IWebBrowser browserControl, IBrowser browser, IFrame frame, IRequest request, IResponse response)
{
            // Some stuff ...
            Console.WriteLine("HTTP Status Code: {0}", response.StatusCode);

            // allow the resource to load normally
            return false;
}
````

But with redirection (3xx), `response.StatusCode` is set to 200 (OK), not with the 3xx value.
I test it with this url http://crawlbin.com/response_301/ that have an HTTP Status: 301 (Moved Permanently) to http://crawlbin.com/

**Comment by amaitland** [comment]
Bug in the `CefResponseWrapper.h` implementation, the actual values are always overwritten.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Internals/CefResponseWrapper.h#L25

**Comment by LeMoussel** [comment]
I update with 45.0.0-pre01.
With this new version `OnResourceResponse` is never called with `request.Url="http://crawlbin.com/response_301/"`
Only one call to `OnResourceResponse` with `request.Url="http://crawlbin.com/"`

**Comment by amaitland** [comment]
Was `OnResourceRedirect` called?

**Comment by LeMoussel** [comment]
`OnResourceRedirect` is call with `request.Url="http://crawlbin.com/response_301/"` and  `newUrl="http://crawlbin.com/"`

**Comment by amaitland** [comment]
> With this new version OnResourceResponse is never called with request.Url="http://crawlbin.com/response_301/"

Any this was being called twice previously? What version were you using before?

**Comment by LeMoussel** [comment]
Yes, called twice previously. One call with `request.Url="http://crawlbin.com/response_301/"` & second call with `request.Url="http://crawlbin.com/"`
This is the first call that the status code was not set to 301. I use before V 45.0.0-CI1575 (I'm not sure, perhaps older version).
There is V [47.0.0-CI1579](https://www.myget.org/feed/cefsharp/package/nuget/CefSharp.OffScreen/47.0.0-CI1579) can I update to it ?

**Comment by amaitland** [comment]
> There is V 47.0.0-CI1579 can I update to it ?

It appears you were already using a build from the `2526` branch. I had not updated the `CI` build script to change the `major` version number at that point.

https://ci.appveyor.com/project/cefsharp/cefsharp/build/45.0.0-CI1575

So upgrading to `45.0.0-pre01` was likely a downgrade in reality.

**Comment by LeMoussel** [comment]
Release 45.0.0-pre01 #1383 , you indicate "*are now on Nuget.org*". Is it with downgrade? Must we wait the official `45.0.0` release?

**Comment by amaitland** [comment]
> Release 45.0.0-pre01 #1383 , you indicate "are now on Nuget.org". Is it with downgrade? Must we wait the official 45.0.0 release?

The official release will be based on the same version. You accidentally used a version based on the `2526` branch which from your reports appears to have a different behavior.

Your choice which version you use. `2526` maybe unstable, I don't know, it's based on an unreleased version of `Chromium`

> I use before V 45.0.0-CI1575 (I'm not sure, perhaps older version).

If you read the build status tor this you'll see that it's actually version `47`.

https://ci.appveyor.com/project/cefsharp/cefsharp/build/45.0.0-CI1575
