### ISSUE TITLE
Taking a Screenshot

### ISSUE THREAD

**Issue by Spiderpig86** [cefsharp/CefSharp#1389]
Hey. I know there are already posts about taking a screenshot with CefSharp, but I can't seem to find screenshotasync. I am currently using the Winforms version of CefSharp version 41.0.0 stable on Windows 10. I can't seem to find a way to call that method. Do I need to implement something first?

**Comment by amaitland** [comment]
> but I can't seem to find screenshotasync

That method only exists in the `OffScreen` project.

Under `WinForms` you'll need to use the `BitBlt` method to generate the screenshot. @jankurianski has kindly provided an example `Gist`

https://gist.github.com/jankurianski/f3419d4580517516c24b

**Comment by Spiderpig86** [comment]
Thanks for the solution! I'll definitely give it a shot when I get the chance.

**Comment by Spiderpig86** [comment]
So far the solution is working fine. However, it won't display a bitmap of the other controls in different panels. I stored them into a collection and despite iterating through each one, the pictures generated from each window with a webcontrol always displays a photo of the last item in the collection. Any thoughts?

**Comment by jankurianski** [comment]
The code in the `Gist` only provides a `Bitmap` of what is on the screen.  So you need to ensure that each window is in the foreground before taking a screenshot.

**Comment by Spiderpig86** [comment]
Alright. So I've decided to try and implement an offscreen webview and see how it goes.

**Comment by Spiderpig86** [comment]
I can't seem to get the offscreen webview to render any content even after following the offscreen example. Nothing is being called. I will add more details later.

**Comment by Spiderpig86** [comment]
I've done some testing while I could. Still nothing is being fired. Most of the functions in the iwebbrowser interface was left empty. Could that be the issue?

**Comment by jankurianski** [comment]
Why don't you use the existing `ChromiumWebBrowser` in the `CefSharp.OffScreen` project?  Seems like you are just trying to reproduce that?

**Comment by Spiderpig86** [comment]
I have tried implementing that class but it doesn't seem to be initializing. It may sound like a stupid question, but is it necessary to fill in all the necessary functions of the interface in order for the OffScreen webview to work?

**Comment by amaitland** [comment]
> I have tried implementing that class but it doesn't seem to be initializing. It may sound like a stupid question, but is it necessary to fill in all the necessary functions of the interface in order for the OffScreen webview to work?

You can work out what's required from the `Offscreen` source code. About half of the methods are actually required.

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.OffScreen/ChromiumWebBrowser.cs#L378

@Spiderpig86 using the `CefSharp.Offscreen` project is going to be far easier than trying to implement yourself as @jankurianski suggested.

**Comment by Spiderpig86** [comment]
Thanks for the answer. I'll be sure to try it again and hope that it works. Not too sure why nothing seemed to initialize the first time, but I'll figure it out.

**Comment by amaitland** [comment]
The `MinimalExample` project has a working demo of the `OffScreen` project, so you can take it for a spin.

https://github.com/cefsharp/CefSharp.MinimalExample/tree/master/CefSharp.MinimalExample.OffScreen

**Comment by jankurianski** [comment]
Are you saying the minimal OffScreen example does not work for you? https://github.com/cefsharp/CefSharp.MinimalExample/tree/master/CefSharp.MinimalExample.OffScreen

I can't really answer your question about implementing the interface - some bits are critical, some are not.  You should look at the working implementation in the OffScreen browser for a guide:
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.OffScreen/ChromiumWebBrowser.cs

**Comment by jankurianski** [comment]
Oops, ignore my post - @amaitland got in before me :smile: (welcome back)

**Comment by amaitland** [comment]
> Oops, ignore my post - @amaitland got in before me :smile: (welcome back)

@jankurianski I wouldn't ignore your post, I think it's relevant :+1: Thanks for taking the time to help out, much appreciated :smile:

**Comment by Spiderpig86** [comment]
After working for about an hour, I still could not get the offscreen webview to work. However, I found another solution instead with a windowed webview. Problem is when I call .Hide() on the form with the webview, it crashes. I could not use Cef.Shutdown() or else my whole application would close. Any thoughts? Thanks.

**Comment by amaitland** [comment]
> After working for about an hour, I still could not get the offscreen webview to work

Did you run `OffScreen.Example` project, did that work for you? There isn't a whole lot too it.

> Problem is when I call .Hide() on the form with the webview, it crashes

You'll have to elaborate. Which `Hide` method are you referring? Have you upgraded to the latest stable release yet? (`43.0.1`)

> I could not use Cef.Shutdown() or else my whole application would close. Any thoughts?

You have to remove all instances of `ChromiumWebBrowser` before calling `Shutdown`. Remember once you call shutdown there is no way to reinitialize, so only do that after you've finished all browser related tasks.

**Comment by Spiderpig86** [comment]
The Offscreen project works fine, but the problem is converting the language to VB.

I am calling the .Hide method for the form to close. (It also crashes when I call any method that interacts with the webview (like .stop) or interacts with the form.

I am still using 41.0.0 and will upgrade soon.

I could not seem to figure out
` BitmapFactory = new BitmapFactory(BitmapLock);`
since it keeps pointing to the interface.

I am still a learning developer and this is something I do on my spare time. My proficiency in C# is not great.

**Comment by amaitland** [comment]
> The Offscreen project works fine, but the problem is converting the language to VB.

I can't help you there, I stay away from `VB.Net`.


> I could not seem to figure out
> BitmapFactory = new BitmapFactory(BitmapLock);
> since it keeps pointing to the interface.

Figure out what exactly? `BitmapFactory` is used internally, noting you should have to worry about as an end user.

**Comment by Spiderpig86** [comment]
For the offscreen webview, I was at least able to get something loading by putting the screen capture code into FrameLoadEnd. Not sure why it wouldn't work with navstatechanged despite adding the handler on the main method.

**Comment by Spiderpig86** [comment]
I am now using the Offscreen dll version 41.0.1 and so far the one error that is keeping it from working is `System.MissingMethodException: Method not found: 'Void CefSharp.Internals.IWebBrowserInternal.OnFrameLoadStart(CefSharp.FrameLoadStartEventArgs)'.`
I am compiling it in Any CPU. Does anyone know how to fix the issue?

**Comment by amaitland** [comment]
> I am compiling it in Any CPU. Does anyone know how to fix the issue?

Compiling what? As a general rule `CefSharp` doesn't support `AnyCpu`, you need `x86` or `x64`.

**Comment by Spiderpig86** [comment]
I have tried compiling my application with x86 and the .dll from nuget seems toproduce the same error.

**Comment by amaitland** [comment]
> I am now using the Offscreen dll version 41.0.1 and so far the one error that is keeping it from working is System.MissingMethodException: Method not found: 'Void CefSharp.Internals.IWebBrowserInternal.OnFrameLoadStart(CefSharp.FrameLoadStartEventArgs)'.

The signature for `41.0.1` is different to the exception your getting, so I'm guessing you've got some dependencies mixed up some how.
https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp/Internals/IWebBrowserInternal.cs#L16

> I have tried compiling my application with x86 and the .dll from nuget seems toproduce the same error.

Not a lot to go by, remember I can't see what's going on. Provide more information if you can please.

**Comment by Spiderpig86** [comment]
I'll try to check for the binary versions again and hope it would finally work.

**Comment by Spiderpig86** [comment]
Thanks for all the help! I have gotten a working version now after getting the right version of the .dll. (Really bad mistake on my part).

**Comment by khurramsaddique** [comment]
to take full page screenshot please read this article
https://stackoverflow.com/questions/39411950/full-page-screenshot-with-cefsharp-in-c-sharp/65719973#65719973

**Comment by khurramsaddique** [comment]
> The code in the `Gist` only provides a `Bitmap` of what is on the screen. So you need to ensure that each window is in the foreground before taking a screenshot.

https://stackoverflow.com/questions/39411950/full-page-screenshot-with-cefsharp-in-c-sharp/65719973#65719973
