### ISSUE TITLE
.NET-BroadcastEventWindow.4.0.0.0.ea7f4a.0: CefSharp.WinForm.Example.exe - Application Error

### ISSUE THREAD

**Issue by shirotzu** [cefsharp/CefSharp#1390]
Message of Error : http://prntscr.com/8ww1qu

Title : .NET-BroadcastEventWindow.4.0.0.0.ea7f4a.0: Agarium.exe - Application Error

Message : Unexpected exception occurred exception of the program (0xe0434352) on location 0x75799617.

I'm Builded 32 bits (x86) in Released. And to pass the program to a friend, but he get this error.

Image of Files :
http://prntscr.com/8ww3pp

P.D. Agar.exe is CefSharp.BrowserSubprocess.exe I'm Renamed it.
In my case the program works perfectly

http://prntscr.com/8ww4a7

**Comment by amaitland** [comment]
Do they have the `VC++ 2012 x86 Redist` installed?

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#Including_vcredist

**Comment by shirotzu** [comment]
I have only Visual Studio 2013 Community and Visual Studio 2015, i Install VC++ 2012 x86 Redist?

**Comment by amaitland** [comment]
Install the version based on the table in this link.

https://github.com/cefsharp/CefSharp#version-branches

**Comment by shirotzu** [comment]
Ok, as i use the CEFSharp-master i need install the VC++ 2013

**Comment by shirotzu** [comment]
Ready, http://prntscr.com/8wx6m1
VC++ 2013 has been installed.

I noticed that my friend did not have the .NET Framework 4.5,
as only I can compile the CeF 3 to that version.

once installed the .NET 4.5 it worked perfectly.

But now another friend tells me that when opened will crashed


Firma del problema 01:	Agarium.exe
Firma del problema 02:	2.0.0.0
Firma del problema 03:	56329bae
Firma del problema 04:	CefSharp
Firma del problema 05:	45.0.0.0
Firma del problema 06:	5631b8ec
Firma del problema 07:	ce
Firma del problema 08:	cf
Firma del problema 09:	System.Exception
Versión del sistema operativo:	6.1.7601.2.1.0.256.1
Id. de configuración regional:	10250
Información adicional 1:	0a9e
Información adicional 2:	0a9e372d3b4ad19135b953a78882e789
Información adicional 3:	0a9e
Información adicional 4:	0a9e372d3b4ad19135b953a78882e789

OS : Windows 7 Ultimate x64

**Comment by amaitland** [comment]
> But now another friend tells me that when opened will crashed

Please try diagnosing the problem yourself. His system is likely missing a dependency or you compiled `CefSharp` in `debug` mode where you **must** compile in `Release` mode when distributing to client machines..

**Comment by amaitland** [comment]
Read the `FAQ` it it's entirety, specially the sections around `VC++`

https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#6-how-do-i-include-the-visual-studio-c-2012-redistributables-on-the-target-app

> Note When building from source make sure you compile in Release mode when deploying to machines that don't have Visual Studio installed. Visual C++ uses a different set of run-time libraries for Debug and Release builds. The Debug run-time libraries are only installed with Visual Studio. If you use the official Nuget packages they're already built in Release mode and you can subsequently build your app in debug mode as only the Visual C++ projects need to be compiled in Release mode.

**Comment by shirotzu** [comment]
I compile in Released Win32 
Screenshot current project http://prntscr.com/8wxaan

**Comment by amaitland** [comment]
> I compile in Released Win32
> Screenshot current project http://prntscr.com/8wxaan

Screen shot is not necessary, just confirming that it's no `Release` mode is sufficient.

Other than making sure the dependencies are installed there is nothing else I can suggest with the information you provided.

**Comment by shirotzu** [comment]
I passed the debug (x86) 32-bit Release, and what is dependencies that you say?

These are all files that were compiled
http://prntscr.com/8wxbok

the red crossed file are the that i deleted before uploading it to Mega.co.nz

**Comment by shirotzu** [comment]
indeed some told me that the antivirus detects the program, is it normal that?

**Comment by amaitland** [comment]
`GitHub` has a great search feature

https://github.com/cefsharp/CefSharp/search?q=antivirus&type=Issues&utf8=%E2%9C%93

**Comment by shirotzu** [comment]
I've read one that is about the same antivirus detects this, but this is not solved

And now there is even another friend who opens the program and nothing. it does not open the program simply does not open

What would be the best choice to fix this? I fix this if change to a newer version?

**Comment by amaitland** [comment]
> indeed some told me that the antivirus detects the program, is it normal that?

Only a handful of people have reported having problems, so no it's not common.

> P.D. Agar.exe is CefSharp.BrowserSubprocess.exe I'm Renamed it.

Is there a reason you did this? Try going with a vanilla version.

> I fix this if change to a newer version?

What never version? Your using `master`.

I'll be honest, you don't really seem to even attempt to troubleshoot problems yourself. Your say it's blocked by `antivirus`, which file caused the problem? Which antivirus? What exactly did it classify the file as?

Beyond that, your on your own....

**Comment by shirotzu** [comment]
I Added the 3 dll files of VC ++ 2013 from 
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\redist\x86\Microsoft.VC120.CRT

to the  project Released And already solved that the program don't open to the executed, now if Habre and works perfectly.

For now the error not know:

Problem signature 01: Agarium.exe
Problem signature 02: 2.0.0.0
Problem signature 03: 56329bae
Problem signature 04: CefSharp
Problem signature 05: 45.0.0.0
Problem signature 06: 5631b8ec
Problem signature 07: EC
Problem signature 08: cf
Problem signature 09: System.Exception
Operating system version: 6.1.7601.2.1.0.256.1
Locale ID. 10250
Additional Information 1: 0a9e
Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
Additional Information 3: 0a9e
Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

So until my friend be connect and tell me if the error is fix,Then I'll let you know to close the topic
Thank you very much for taking into account each question and answer.

**Comment by shirotzu** [comment]
Error : Open Agarium.exe Don't Execute
http://prntscr.com/8x7dxk
Apparently it stays in the loading screen because it never reaches a state of document ready.
