### ISSUE TITLE
SetIsLoading don't Execute?

### ISSUE THREAD

**Issue by shirotzu** [cefsharp/CefSharp#1394]
Postscript: This problem don't get my OS, is from a client

Explanation:
of last problem I had
https://github.com/cefsharp/CefSharp/issues/1390

It was that opening the compiled Program jumps me an error message of Window 7
This was due to some missing files VC++ 2013 within the project folder,
Add these files VC++ 2013, fixed up this above problem.

Apart from that problem was also a problem when you open the executable file,
the program did not run, but with those files from VC ++ 2013 too has fixed up.

But apparently it was not working quite right and that is not running the ExecuteScriptAsync
that line remained locked and not longer followed the lines of code below that followed.
The ExecuteScriptAsync has been added it in the SetIsLoading within a bool with the variable "false"
later of this the variable change to "true" for don't create a loop,
since loading the page to ads makes repeat the SetIsLoading process.

How to fix it ?, thanks in advance

A little code of the problem :

        private void SetIsLoading(bool isLoading,string url)
        {
            IsLoadingSite = isLoading ?
                true :
                false;
            if (IsLoadingSite == false)
            {
                    IsLoadingSite = true; //probably this line not runs
			string adblock = "here javascript code"; //probably this line also not runs
			Browser.ExecuteScriptAsync(adblock); //This don't execute
			... //Rest of code too not runs
            }
        }

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue

**Comment by amaitland** [comment]
This is not a generic support forum, only ask CefSharp specific questions. Don't post code as screenshots.

**Comment by shirotzu** [comment]
Edited UP*

**Comment by shirotzu** [comment]
Solved, I removed unnecessary bool and now works normally
-.Topic Closed

**Comment by amaitland** [comment]
As I said, nothing to do with CefSharp, use something like stackoverflow for generic support questions.
