### ISSUE TITLE
We need easy example tutorials, Cefsharp load request with post data 

### ISSUE THREAD

**Issue by hungud** [cefsharp/CefSharp#1395]
I search on google and see StackOverFlow post:

http://stackoverflow.com/questions/12978338/how-do-i-send-post-and-header-data-with-chromium

and code to do easy:

procedure TForm1.Button1Click(Sender: TObject);
var
  Header: ICefStringMultimap;
  Data: ICefPostData;
  Request: ICefRequest;
begin
  Request := TCefRequestRef.New;
  Request.Url := 'http://example.com/';
  Request.Method := 'POST';
  Request.Flags := WUR_FLAG_NONE;

  Header := TCefStringMultimapOwn.Create;
  Header.Append('Content-Type', 'application/x-www-form-urlencoded');
  Request.SetHeaderMap(Header);

  Data := TCefPostDataRef.New;
  Data.AddElement(CreateField('Data.id=27'));
  Data.AddElement(CreateField('&Data.title=title'));
  Data.AddElement(CreateField('&Data.body=body'));
  Request.PostData := Data;

  Chromium1.Browser.MainFrame.LoadRequest(Request);
end;

I see on all example of Cefsharp and I see CefPostDataWrapper. I see some method send with postdata feature important must have of Cefsharp.

I also see code modify with post before, but I see not easy to do for some beginners as me

 CefReturnValue IRequestHandler.OnBeforeResourceLoad(IWebBrowser browserControl, IBrowser browser, IFrame frame, IRequest request, IRequestCallback callback)
             

Please do it feature and easy example tutorials

Thanks you

**Comment by amaitland** [comment]
That feature has not been implemented, see #912

Pull requests are welcome if this is a feature you require.

**Comment by hungud** [comment]
"That feature has not been implemented" Why? this feature is not important?

"Pull requests are welcome if this is a feature you require". Ok, I will try

Thanks

**Comment by amaitland** [comment]
#912 has some information, continue the conversation there.
