### ISSUE TITLE
CefSharp.WinForm.Example.exe stopped working (x64)

### ISSUE THREAD

**Issue by shirotzu** [cefsharp/CefSharp#1396]
newly another mistake.

Agarium.exe (x86)
Error : don't open it, when executed.

Agarium.exe (x64)
Error : Agarium stopped working 
Error Img : http://prntscr.com/8ycvqs

Computer Information : 

Windows 7 Professional Service Pack 1
Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz 3.40 GHz
8,00 GB RAM
OS 64 bits

Windows Activated

debug.txt (x64)

[1103/054306:VERBOSE1:pref_proxy_config_tracker_impl.cc(215)] 0000000020A95290: set chrome proxy config service to 000000001B1CED80
[1103/054306:VERBOSE1:pref_proxy_config_tracker_impl.cc(353)] 0000000020A95290: Done pushing proxy to UpdateProxyConfig
[1103/054328:VERBOSE1:child_thread_impl.cc(343)] Mojo is disabled on child
[1103/054328:WARNING:ipc_channel_win.cc(297)] Unable to create pipe "\\.\pipe\chrome.3976.0.57117163" in client mode: El sistema no puede encontrar el archivo especificado. (0x2)
[1103/054328:VERBOSE1:ipc_sync_channel.cc(386)] Canceling pending sends
[1103/054328:VERBOSE1:ipc_sync_channel.cc(386)] Canceling pending sends
[1103/054328:VERBOSE1:statistics_recorder.cc(269)] Collections of all histograms
Histogram: GPU.ANGLE.D3D11CreateDeviceMS recorded 1 samples, average = 14.0 (flags = 0x1)
0   ... 
14  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
17  ... 
Histogram: GPU.ANGLE.D3D11FeatureLevel recorded 1 samples, average = 5.0 (flags = 0x1)
0  ... 
5  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
6  O                                                                         (0 = 0.0%) {100.0%}
Histogram: GPU.ANGLE.D3D11InitializeResult recorded 1 samples, average = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 
Histogram: GPU.ANGLE.DisplayInitializeMS recorded 1 samples, average = 16.0 (flags = 0x1)
0   ... 
14  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
17  ... 
Histogram: GPU.ANGLE.Renderer11InitializeDLLsMS recorded 1 samples, average = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 
Histogram: GPU.ANGLE.Renderer11InitializeDeviceMS recorded 1 samples, average = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 
Histogram: GPU.ANGLE.SupportsDXGI1_2 recorded 1 samples, average = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  O                                                                         (0 = 0.0%) {100.0%}
Histogram: GPU.CollectContextGraphicsInfo recorded 1 samples, average = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 
Histogram: GPU.InitializeOneOffMediumTime recorded 1 samples, average = 20.0 (flags = 0x1)
0   ... 
18  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
22  ... 
Histogram: V8.Initializer.LoadV8Snapshot.Result recorded 1 samples, average = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 
Histogram: V8.Initializer.OpenV8File.Result recorded 2 samples, average = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (2 = 100.0%)
1  ... 
[1103/054333:VERBOSE1:pref_proxy_config_tracker_impl.cc(215)] 00000000211E9DB0: set chrome proxy config service to 000000002120B240
[1103/054333:VERBOSE1:pref_proxy_config_tracker_impl.cc(353)] 00000000211E9DB0: Done pushing proxy to UpdateProxyConfig
[1103/054333:VERBOSE1:child_thread_impl.cc(343)] Mojo is disabled on child
[1103/054348:INFO:child_thread_impl.cc(708)] ChildThreadImpl::EnsureConnected()

**Comment by jankurianski** [comment]
A few problems with your post:
- This doesn't seem to have anything to do with CefSharp.  The screenshot of the crash window refers to your own application "Agarium.exe".
- You do not include any actual error message.  You can Google on how to find error messages from Windows crashes.
- You have not demonstrated that you spent any time trying to debug the cause of the problem yourself.

In general, CefSharp works on lots of computers for lots of people.  If something is going wrong, it is most likely a problem in your code, your environment, or your deployment.  There are lots of existing issues and help on this website that you should search through before posting.
