### ISSUE TITLE
Ways to get data from localhost port using CefSharp

### ISSUE THREAD

**Issue by ahgan84** [cefsharp/CefSharp#1397]
Hi guys, currently developing a .net C# application which is showing the Chromium browser. But I'm having problem getting data from localhost port.

In C# I load the web browser:

     var test = new CefSharp.WinForms.ChromiumWebBrowser(AppDomain.CurrentDomain.BaseDirectory +  "html\\index.html")
     {
         Dock = DockStyle.Fill,
    };
    this.Controls.Add(test);

Then on the index.html page, I tried the below 2 ways to get data.

Below is the 2 ways I tried to get the data:

Using xmlhttprequest:

    var xmlhttp = new XMLHttpRequest();
      var url = "http://localhost:1000/api/data1";
      var services;
      xmlhttp.onreadystatechange = function () {
          if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
              services = jQuery.parseJSON(xmlhttp.responseText);
          }
      }
      xmlhttp.open("GET", url, true);
      xmlhttp.send();

Using jquery's .get() function:

      $.get("http://localhost:1000/api/data1", function (data) {
          var services = data;
      });

Both ways fail to return the data I need. But if I use normal Chrome or firefox browser to load the index.html, I can get the data.

Is it something missing in my code that's why I can't get the data if using CEF?

**Comment by amaitland** [comment]
What version are you using? 

Please markup your code see https://guides.github.com/features/mastering-markdown/

You may need to configure some of the browser settings to allow the requests. Have a look at the `BrowserSettings`.

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.Core/BrowserSettings.h#L205
https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.Core/BrowserSettings.h#L215

If that doesn't work then you might be best to switch to using a `ResourceHandler` or `LoadHtml` to show the data is a standard `URL`

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp/WebBrowserExtensions.cs#L246

**Comment by ahgan84** [comment]
I have tried putting in the Browser settings before showing the web browser in C#:

            BrowserSettings browserSettings = new BrowserSettings();
            browserSettings.WebSecurity = CefState.Disabled;
            browserSettings.FileAccessFromFileUrls = CefState.Enabled;
            browserSettings.UniversalAccessFromFileUrls = CefState.Enabled;

     var test = new CefSharp.WinForms.ChromiumWebBrowser(AppDomain.CurrentDomain.BaseDirectory +  "html\\index.html")
     {
         Dock = DockStyle.Fill,
    };
    this.Controls.Add(test);

But still I cannot get the data. Is it there something mussing in the browser setting?

**Comment by amaitland** [comment]
You need to assign `BrowserSettings` to the `ChromiumWebBrowser` instance or modify the existing settings.

```c#
test.BrowserSettings.WebSecurity = CefState.Disabled;
test.BrowserSettings.FileAccessFromFileUrls = CefState.Enabled;
test.BrowserSettings.UniversalAccessFromFileUrls = CefState.Enabled;
```

Technically I believe your trying to make a `cross origin` request, for which disabling web security should work.

http://magpcss.org/ceforum/viewtopic.php?f=17&t=13341&p=27295

**Comment by amaitland** [comment]
If you cross post, please provide links 

http://magpcss.org/ceforum/viewtopic.php?f=6&t=13572

**Comment by ahgan84** [comment]
There seems to be error when assigning like this "test.BrowserSettings". Is there some example to assign BrowserSettings to the ChromiumWebBrowser?

**Comment by amaitland** [comment]
> There seems to be error when assigning like this "test.BrowserSettings".

Just saying there is an error isn't very helpful, what does it say? What does your code look like?

> Is there some example to assign BrowserSettings to the ChromiumWebBrowser?

Not sure, you can search through the code and see.

https://github.com/cefsharp/CefSharp/search?utf8=%E2%9C%93&q=BrowserSettings

**Comment by ahgan84** [comment]
The error for test.BrowserSettings is "Error	1	'CefSharp.WinForms.ChromiumWebBrowser' does not contain a definition for 'browserSettings' and no extension method 'browserSettings' accepting a first argument of type 'CefSharp.WinForms.ChromiumWebBrowser' could be found (are you missing a using directive or an assembly reference?)"

**Comment by amaitland** [comment]
> does not contain a definition for 'browserSettings'

According to the error message you're missing a capital `B`.

**Comment by amaitland** [comment]
@ahgan84 Did you get this working? Can we close this?

**Comment by ahgan84** [comment]
Yup. It's working. Thanks!!
