### ISSUE TITLE
Some dll issue during debugging

### ISSUE THREAD

**Issue by ahgan84** [cefsharp/CefSharp#1398]
I'm using Visual Studio c# and put in a CefSharp browser inside. But after debugging successfully a few times, the below error will appear:

     Error  15  Could not copy "C:\Work\Project 2015\Printing-io\Printing-io\packages\cef.redist.x64.3.2357.1287\build\..\CEF\x64\ffmpegsumo.dll" to "C:\Work\Project 2015\Printing-io\Printing-io\Printing-io\bin\x64\Debug\ffmpegsumo.dll". Exceeded retry count of 10. Failed.   Printing-io
     Error 16  Unable to copy file "C:\Work\Project 2015\Printing-io\Printing-io\packages\cef.redist.x64.3.2357.1287\build\..\CEF\x64\ffmpegsumo.dll" to "C:\Work\Project 2015\Printing-io\Printing-io\Printing-io\bin\x64\Debug\ffmpegsumo.dll". The process cannot access the file 'C:\Work\Project 2015\Printing-io\Printing-io\Printing-io\bin\x64\Debug\ffmpegsumo.dll' because it is being used by another process.  Printing-io
     Error  27  Could not copy "C:\Work\Project 2015\Printing-io\Printing-io\packages\cef.redist.x64.3.2357.1287\build\..\CEF\x64\libcef.dll" to "C:\Work\Project 2015\Printing-io\Printing-io\Printing-io\bin\x64\Debug\libcef.dll". Exceeded retry count of 10. Failed.   Printing-io
     Error  28  Unable to copy file "C:\Work\Project 2015\Printing-io\Printing-io\packages\cef.redist.x64.3.2357.1287\build\..\CEF\x64\libcef.dll" to "C:\Work\Project 2015\Printing-io\Printing-io\Printing-io\bin\x64\Debug\libcef.dll". The process cannot access the file 'C:\Work\Project 2015\Printing-io\Printing-io\Printing-io\bin\x64\Debug\libcef.dll' because it is being used by another process.  Printing-io
     Error  39  Could not copy "C:\Work\Project 2015\Printing-io\Printing-io\packages\cef.redist.x64.3.2357.1287\build\..\CEF\x64\natives_blob.bin" to "C:\Work\Project 2015\Printing-io\Printing-io\Printing-io\bin\x64\Debug\natives_blob.bin". Exceeded retry count of 10. Failed.   Printing-io
    Error  40  Unable to copy file "C:\Work\Project 2015\Printing-io\Printing-io\packages\cef.redist.x64.3.2357.1287\build\..\CEF\x64\natives_blob.bin" to "C:\Work\Project 2015\Printing-io\Printing-io\Printing-io\bin\x64\Debug\natives_blob.bin". The requested operation cannot be performed on a file with a user-mapped section open.
         Error  51  Could not copy "C:\Work\Project 2015\Printing-io\Printing-io\packages\cef.redist.x64.3.2357.1287\build\..\CEF\x64\snapshot_blob.bin" to "C:\Work\Project 2015\Printing-io\Printing-io\Printing-io\bin\x64\Debug\snapshot_blob.bin". Exceeded retry count of 10. Failed. Printing-io
        Error  52  Unable to copy file "C:\Work\Project 2015\Printing-io\Printing-io\packages\cef.redist.x64.3.2357.1287\build\..\CEF\x64\snapshot_blob.bin" to "C:\Work\Project 2015\Printing-io\Printing-io\Printing-io\bin\x64\Debug\snapshot_blob.bin". The requested operation cannot be performed on a file with a user-mapped section open.

I can only restart my pc to fix this and then it will debug successfully again. But after debugging success a few times, the same error like above appear again.
Do you guys know what causes these error?
Is it that the dll did not terminate itself and still running after I stop debugging?

**Comment by amaitland** [comment]
Did you let the browser shutdown properly or did you just terminate debugging? Usually this only happens if `Cef.Shutdown` was not called successfully.

Open `Task Manager`, terminate the `CefSharp.BrowserSubprocess.exe` instances that have been orphaned.

**Comment by ahgan84** [comment]
I just use terminate debugging. How do we shutdown the browser properly? There's no close button to press.

**Comment by amaitland** [comment]
> I just use terminate debugging. How do we shutdown the browser properly? There's no close button to press.

What application are you using? You let the application close normally. or explicitly call `Cef.Shutdown`

Please read over https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue and include more information about your problem, including version your using (if from source which branch), `WinForms`, `WPF` and anything else that might be useful. Please include all basic information when creating an issue.

**Comment by ahgan84** [comment]
I'm using the Visual Studio 2013 and it's a Winform solution.

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#11-build-process-cant-copy-cef-files

**Comment by ahgan84** [comment]
Where do I write the snippet to?
For me, I do declare Cef.Initialize(new CefSettings()); in my Program.cs file.

**Comment by amaitland** [comment]
If you let your application close normally, then `CefSharp` will cleanup for you otherwise you can call shutdown after the last instance of `ChromiumWebBrowser` has been `Disposed`.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.WinForms/ChromiumWebBrowser.cs#L79

Read https://htmlpreview.github.io/?https://github.com/cefsharp/CefSharp/blob/cefsharp/45/CefSharp.Example/Resources/Home.html#the-basics

**Comment by ahgan84** [comment]
Ok. But how do we detect when is it the application shut down? Normally I just press the stop debugging button or terminate button.

**Comment by amaitland** [comment]
> Ok. But how do we detect when is it the application shut down? Normally I just press the stop debugging button or terminate button.

That's not really a `CefSharp` specific question. 

Try `stackoverflow` for general programming answers, a quick search brings up many on the topic.

http://stackoverflow.com/questions/2414244/how-do-i-properly-close-a-winforms-application-in-c

**Comment by ahgan84** [comment]
ok. Thanks!

**Comment by samsamm777** [comment]
I'm getting this same issue. However i do NOT have the `CefSharp.BrowserSubprocess.exe` running during build. Any further information?

**Comment by amaitland** [comment]
> However i do NOT have the CefSharp.BrowserSubprocess.exe running during build.

You would have to use something like `Process Explorer` to investigate further.

The next version should improve on this slightly, see https://github.com/cefsharp/cef-binary/commit/3b5d2a8ed67e2612837ad51b2e2a42f29bb29259

**Comment by samsamm777** [comment]
@amaitland It looks like `msvsmon.exe` is holding the dll reference open. This exe doesnt seem to ever exit. Im aware its the Visual Studio Remote Debugger but im not sure why its open here? once i close that, building works fine.

**Comment by amaitland** [comment]
> Im aware its the Visual Studio Remote Debugger but im not sure why its open here?

You'd have to google/research this further as I've got no idea.
