### ISSUE TITLE
could not find assembly 'mscorlib.dll'

### ISSUE THREAD

**Issue by CarbonMan** [cefsharp/CefSharp#1401]
could not find assembly 'mscorlib.dll': please specify the assembly search path using /AI or by setting the LIBPATH environment variable (C1107) - CefSharp-master\CefSharp.Core\Stdafx.cpp

Sorry I know that this is probably a very basic question, but I am getting this while attempting to compile the CefSharp.WinForms project.
Any suggestions?

**Comment by amaitland** [comment]
What branch are you trying to build? What version of `Visual Studio` are you using? Do you have the `VC++ Dev Component`installed? Newer versions require `Visual Studio 2013` as a minimum. As it's an open source project you can use the community edition if you require.

You can check the current build status https://github.com/cefsharp/CefSharp/branches
You'll see a green tick next to each branch that's currently building successfully.

Is there any particular reason your trying to compile from source?

`CI` builds are available from https://www.myget.org/gallery/cefsharp

**Comment by CarbonMan** [comment]
Thanks I was able to build using the CI builds.
