### ISSUE TITLE
Keyboard events not trapped by ChromeWidgetMessageInterceptor

### ISSUE THREAD

**Issue by nerodark** [cefsharp/CefSharp#1402]
I wanted to trap WM_KEYUP (0x0101) and I was unable to accomplish this.
All mouse events are trapped though.
I got it to trap keyboard events in ChromeWidgetMessageInterceptor by moving the creation of browsers directly in the Form instead of UserControl in the CefSharp.WinForms.Example project.

Anyone knows why it would be trapped in the form and not in the usercontrol? My goal is to keep the creation of them in usercontrol like in the example project. Anyone could fix it in the example project to support keyboard events or tell me a quick fix?

Thanks

**Comment by amaitland** [comment]
Did you look at `IKeyboardHandler`?

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp/IKeyboardHandler.cs

> Anyone could fix it in the example project to support keyboard events or tell me a quick fix?

Most of it's undocumented and found by trial and error, so you'll have to do the same.

**Comment by nerodark** [comment]
Exactly what i wanted, thanks, i was only looking at RawKeyDown, not KeyUp

**Comment by jankurianski** [comment]
@nerodark Good to hear you got it working.  If nothing else, could you close the issue off?
