### ISSUE TITLE
Cannot embed WebRTC within WPF

### ISSUE THREAD

**Issue by moranamon** [cefsharp/CefSharp#1403]
Hi Guys,

I'm using WebRTC for conferencing between my users. some use windows application (WPF) and some use smartphones (Android).
I managed to do it using chrome browser.

The thing is that i need it to be fully embedded within my WPF application (for windows users), so i use CefSharp and i managed to display web sites.
But, my issue is that i can't open the video call. the loading icon is displayed and rotates without open the camera.

Please advice...

**Comment by jankurianski** [comment]
Did you search existing issues?  Seems like related stuff there:
https://github.com/cefsharp/CefSharp/search?q=webrtc&type=Issues&utf8=%E2%9C%93

**Comment by moranamon** [comment]
Thanks for your reply.

Unfortunately I can't find an answer on GitHub to my issue.

i just tried to run the tests from WebRTC web sites (
https://test.webrtc.org/) on my chrome browser and the tests have passed
successfully.

But when i run the same test web site from my WPF application, i relaized
that it cannot access my camera and microphone.

The below popup comes up:

Failed to access your computer's camera and microphone (
PermissionDeniedError).



this is my XAML code:



    <Grid  >
        <cefSharp:ChromiumWebBrowser  Address="https://test.webrtc.org/" />
    </Grid>

How can i allow it through the XAML/C# code?

Thanks.

**Comment by jankurianski** [comment]
> i just tried to run the tests from WebRTC web sites (
> https://test.webrtc.org/) on my chrome browser and the tests have passed
> successfully.

Chrome is less relevant.  You need to try the CEF test app that is linked to from here, with the correct arguments that mimic CefSharp WPF control behaviour:
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

Did you find the issue where it says you need to enable WebRTC via command-line arguments?

Does it work when you try it in the CefSharp WPF example project?

**Comment by moranamon** [comment]
Hi,
i've ran the test app with the argument "--use-fake-ui-for-media-stream",
but the result was the same.

this is how i typed it:
https://opentokrtc.com/1 --use-fake-ui-for-media-stream

the result:
[image: Inline image 1]

Am i doing something wrong here?

Thanks.

**Comment by amaitland** [comment]
> i've ran the test app with the argument "--use-fake-ui-for-media-stream",

I think the `fake` part gives away that it's no the parameter your looking for.

`GitHub` does have an amazing search feature though, when I type in `WebRtc` exactly what your looking for, so I'm not quite sure what your looking for when your search?

https://github.com/cefsharp/CefSharp/search?utf8=%E2%9C%93&q=webrtc

**Comment by moranamon** [comment]
i just want to enable to access from my WPF page,

in the link you have shared is developed in C# code and i just add the
below to my XAML
 <cefSharp:ChromiumWebBrowser  Address="https://opentokrtc.com/1" />

i'm new to GitHub, how can i download the entire project from there?

**Comment by amaitland** [comment]
> i just want to enable to access from my WPF page, in the link you have shared is developed in C# code and i just add the below to my XAML <cefSharp:ChromiumWebBrowser Address="https://opentokrtc.com/1" />

There is no way to enable it from `XAML`. You need to pass in a command line argument when you initialize `CEF`.

https://github.com/cefsharp/CefSharp/blob/a3dff183dc7bf963779be80521fdc71c041fb24e/CefSharp.Example/CefExample.cs#L49

> i'm new to GitHub, how can i download the entire project from there?

I'm sure a quick google will answer that question for you :+1:

**Comment by amaitland** [comment]
Add the command line argument to the `CefSettings` object before calling `Initialize`.

https://github.com/cefsharp/CefSharp.MinimalExample/blob/master/CefSharp.MinimalExample.Wpf/App.xaml.cs

**Comment by moranamon** [comment]
Alex,
i managed to access the camera.

Thank you very much.

your assistance has been very helpful.

Have a great weekend.

Moran

**Comment by moranamon** [comment]
Alex,
I've another question regarding the same topic if a may.

In the past, i used WebRTC to open a conference call via Chrome as follows:
;
            chat.On<string, string>("broadcastMessage", (name, message) =>
{ Console.Write(name + ": "); Console.WriteLine(message); });

            chat.On<string, string>("broadcastMessage", (name, message) =>

                Dispatcher.InvokeAsync(() =>
                {
                   System.Diagnostics.Process.Start(UrlVideoCall);

                })
                );

            hubConnection.Start().Wait();
            chat.Invoke("Notify", "CMCP", hubConnection.ConnectionId);


My question is how can i open this video call within a WPF window?

i managed to open my camera within WPF, but now i'm trying to do the same
with a WebRTC call.

Thanks in advanced.

**Comment by jankurianski** [comment]
Open a new WPF window with a ChromiumWebBrowser, and navigate to the URL?

**Comment by moranamon** [comment]
hi Jan,
Thanks for your reply.
It works like charm!.

Now, what about multiple users on the same conference call?

What should i do?

Thanks.

**Comment by jankurianski** [comment]
I don't know how to answer this question.  Also, it seems off-topic to CefSharp.

**Comment by moranamon** [comment]
Ok,

Appreciate it.

Thanks.
