### ISSUE TITLE
Method bindings returning wrong error messages

### ISSUE THREAD

**Issue by cefsharp-ms** [cefsharp/CefSharp#1404]
I think this change: 010a7f326decdd05a7912238be48f55bc7fb27ee causing some problems when the called method throws an exception. The output will be the same generic InvalidOperationException message (Missing parameters...) instead of the inner exception from the TargetInvocationException, because of the catchall around the actual method call.

**Comment by amaitland** [comment]
@illfang Any comment on this?

**Comment by illfang** [comment]
Running the ExceptionTest.html a generated example exception message for a method that throws an exception is as follows
```
System.InvalidOperationException: Could not execute method: triggerNestedExceptions() - Missing Parameters: 0 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.OperationCanceledException: Nested Exception Canceled ---> System.InvalidOperationException: Nested Exception Invalid ---> System.DivideByZeroException: Attempted to divide by zero. 
[... stack traces ...]
```
All nested exception messages are contained even the nested exceptions created for the thrown exception in the invoked method.
e.g.: `System.DivideByZeroException: Attempted to divide by zero. `, `System.InvalidOperationException: Nested Exception Invalid`

It is furthermore logged which bound method has been invoked which caused the exception `triggerNestedExceptions()`.

In my opinion this exception message handling contains all information required to debug exceptions thrown in a bound method.

**Comment by illfang** [comment]
And yes, the `System.Reflection.TargetInvocationException` is also contained in the exception chain which is important to determine where the exception has been thrown within CefSharp.
e.g.
```
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) 
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) 
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) 
at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) 
at CefSharp.Internals.JavascriptObjectRepository.TryCallMethod(Int64 objectId, String name, Object[] parameters, Object& result, String& exception) in c:\temp\CefSharp\Internals\JavascriptObjectRepository.cs:line 123 
```

Using this information the location within CefSharp is clear `JavascriptObjectRepository.cs:line 123` which allows debugging of CefSharp - if necessary.

**Comment by cefsharp-ms** [comment]
My mistake, you're right the exception is there just in a different presentation. The problem is just the changed format, it's hard to handle errors on the javascript side with the all of the c# exceptions serialized. I mean getting the original error message from the actual call. Would it make sense to create an array/object instead of just a string that contains both the original error and the entire serialized exception tree as well?

**Comment by amaitland** [comment]
> Would it make sense to create an array/object instead of just a string that contains both the original error and the entire serialized exception tree as well?

And what would you do with the array/object? At the end of the day the exception passed back to the `V8` engine is just a string.

**Comment by cefsharp-ms** [comment]
I think nothing prevents us from passing an object to the Promise.reject instead of a string, so that can be one solution. An other one could be to make this functionality configurable somehow. What do you think?

**Comment by amaitland** [comment]
The same method is used by the `sync` version, so it would have to be converted back into a string at some point.

> An other one could be to make this functionality configurable somehow.

Sounds unnecessarily complicated. 

> What do you think?

I'm inclined to leave the code base stabilise a bit, we've only just ironed out a large number of bugs so I'm not really keep to make changes at this point in time. If you feel strongly enough about it and have time then by all means submit a `PR` against `master` and we can evaluate the options for the `47` milestone.

The overall plan was just to release the `45.0.0` branch as a bugfix release (even though it's a major `Chromium` upgrade).

**Comment by cefsharp-ms** [comment]
Sounds reasonable, I'll put together something for the master branch and let's see how it goes. I think I'll close this for now, let's continue under the PR when it's up.
