### ISSUE TITLE
BrowserProcessServiceHost null exception

### ISSUE THREAD

**Issue by DominikPalo** [cefsharp/CefSharp#1408]
CEFSharp library sometimes throws this exception that I don't know how to catch (so it is routed as unhandled domain error and my WPF app crashes):

```
Object reference not set to an instance of an object.    
at CefSharp.Internals.BrowserProcessServiceHost..ctor(JavascriptObjectRepository javascriptObjectRepository, Int32 parentProcessId, IBrowserAdapter browserAdapter)\r\n   
at CefSharp.ManagedCefBrowserAdapter.OnAfterBrowserCreated(Int32 browserId)\r\n   
at CefSharp.Internals.ClientAdapter.OnAfterCreated(ClientAdapter* , CefRefPtr<CefBrowser>* browser)
```

Library version: 43.0.0

**Comment by jankurianski** [comment]
- Does the problem occur with newer CefSharp versions?
- Can you reproduce the problem with the CefSharp example?

**Comment by DominikPalo** [comment]
I can't reproduce this problem with example (also I can't replicate it on my developer PC), because I've got these exceptions from my remote client's logs (but this exception was thrown on different versions of Windows). I will update lib to the version 45 when it goes to the stable version (currently it is still in prerelease and I don't want to use prerelease versions in production)

**Comment by amaitland** [comment]
> Library version: 43.0.0

Have you tried `43.0.1`? There were many bugs fixed, including some related to opening/closing instances quickly which is a common cause of `nullreference` exceptions.

https://github.com/cefsharp/CefSharp/commit/aa14254c06109c0ca0bad1c711472c7c327d705e

**Comment by amaitland** [comment]
@DominikPalo Any follow up on this one?
