### ISSUE TITLE
can cefsharp offer an complicated offscreen example ？

### ISSUE THREAD

**Issue by Ace8793** [cefsharp/CefSharp#1409]
I saw a example here http://www.ogre3d.org/forums/viewtopic.php?f=11&t=79079.
It's great .So I wonder if CEFSharp can do this?

**Comment by illfang** [comment]
I guess the WPF implementation is a complex offscreen example.

**Comment by Ace8793** [comment]
Sorry for my English andI'm newer to CEFSharp.Does WPF implementation use offscreen?
I seached google and Knew there is some frames tree.Can we get the tree in CEFsharp?Is there any way to get each frames' img buffer?
if I can do that ,I can do many other job

**Comment by illfang** [comment]
> Does WPF implementation use offscreen

Yes, CEF is rendered to a bitmap for use in WPF
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf/ChromiumWebBrowser.cs#L301


> I seached google and Knew there is some frames tree.Can we get the tree in CEFsharp?

You have access to all frames using CefSharp. I don't think there are actual frame trees. You have to keep track of that yourself.
http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=541



> Is there any way to get each frames' img buffer?

I believe, you can only get image data of the full browser. If you need every frame you might as well just use multiple browsers instead.

**Comment by Ace8793** [comment]
I made a mistake.frames tree is in firefox,in CEF it's a render tree.So I mean can I get the rectangle in render tree, use cef API or other method

**Comment by illfang** [comment]
> I believe, you can only get image data of the full browser.

I think, it is further possible to retrieve updated dirty rectangles in the render callback.

**Comment by amaitland** [comment]
There is a rendering implementation that supports dirty rects currently implemented.

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.Wpf/Rendering/WritableBitmapInfo.cs#L55

**Comment by amaitland** [comment]
@Ace8793 What is it that your actually trying to achieve?

**Comment by Ace8793** [comment]
Thanks for all.The solution can be deal just like what the WPF example do.
But I face another problem.There is an ActiveX object in the page I want to render.
Is there any way to solve this?

**Comment by amaitland** [comment]
> There is an ActiveX object in the page I want to render.
> Is there any way to solve this?

Does `Chromium` support `ActiveX`? From what I can tell people use `extensions` to provide support. Just as an FYI CEF does not support extensions.

**Comment by Ace8793** [comment]
Yes, I know CEF as well as Chromium doesn't support ActiveX.But I seach a project webkitX(https://github.com/mobileFX/WebKitX),it seems that ,an CEF can be wapper and then run a ActiveX object.Can CEFSharp do some similar thing to support ActiveX?

**Comment by amaitland** [comment]
> This is a Visual Studio 2010 SP1 C++ MFC/ATL ActiveX Project that wraps Chromium Embedded Framework (CEF) version 1.1364.1123 for use with OLE/COM languages such as Visual Basic 6.0 SP1.

From how I read it, the project wraps `CEF` in an `ActiveX` control for use in language like `VB6`, it's not about running `ActiveX` in CEF`.

> Can CEFSharp do some similar thing to support ActiveX?

Overall `CefSharp` doesn't really do much more than wrap `CEF`. so if it's supported in `CEF` (which I believe is unlikely `then it can be implemented in `CefSharp`).

**Comment by Ace8793** [comment]
THX.,I get it.I'll find other way to the ActiveX problem.
If you have good advise ，please tell me.Thanks again

**Comment by amaitland** [comment]
> If you have good advise ，please tell me.

You can try asking on http://magpcss.org/ceforum/index.php to see if someone else has any ideas.
