### ISSUE TITLE
How update to the version Chromium 47.0.2526.0

### ISSUE THREAD

**Issue by shirotzu** [cefsharp/CefSharp#1410]
its possible update the project files to Chromium 47 and that this work?
frrom https://cefbuilds.com/ files

**Comment by jankurianski** [comment]
Yes.  There is plenty of information on this in previous issues and on the wiki.

Here is a starting point: https://github.com/cefsharp/cef-binary/wiki

**Comment by amaitland** [comment]
`master` was upgraded to `3.2526.1347` a while ago.

https://github.com/cefsharp/CefSharp/commit/0ecd64dfd24cfc8ea8aa68ce46560cda14ae1921

**Comment by shirotzu** [comment]
Thanks
