### ISSUE TITLE
Executing JS - visibility to the page content scripts?

### ISSUE THREAD

**Issue by Sasstraliss** [cefsharp/CefSharp#1411]
If I run the following on a page in Cef:

    browser.ExecuteScriptAsync("function doSomething() { /* do things */ }");
    browser.ExecuteScriptAsync("var testvar = 5");

The page content scripts can see any variables and functions declared from ExecuteScriptAsync.

Is there a way around this, much like how the browser extension Tampermonkey has a virtual window separated from the page content scripts?

**Comment by shirotzu** [comment]
I'm not the most appropriate to help in anything but a way around it would be adding Model.clear ()
or simply removing the Devtools Show and View Source from the menu that appears when you right-click

Another way would be making the script is removed once executed

--------
string script = "function doSomething() { /* do things */ }" +
                       "var testvar = 5";
browser.ExecuteScriptAsync(script);

**Comment by illfang** [comment]
I believe this is not related to CefSharp and is just a common JavaScript problem which should be better discussed on stackoverflow.

You can achieve this by wrapping your calls in a closure.

```
(function() {
browser.ExecuteScriptAsync("(function() {function doSomething() { /* do things */ }}());");
browser.ExecuteScriptAsync("(function() {var testvar = 5;}());");
```

`Private variables can be made possible with closures.`
http://www.w3schools.com/js/js_function_closures.asp

For similar questions, I believe you should rather use stackoverflow.

**Comment by jankurianski** [comment]
@illfang is correct.  This is a JavaScript issue rather than a CefSharp issue.
