### ISSUE TITLE
Unable to work horizontal scroll using [shift + mouse wheel]

### ISSUE THREAD

**Issue by I-TMK** [cefsharp/CefSharp#1414]
Unable to work horizontal scroll using [shift + mouse wheel]. CefSharp 43.0.1 WPF. But it was working at CefSharp 1.25.7.

I am used to simulate the touch scroll.

```
        private void SendSimulateScroll(ManipulationDeltaEventArgs e, double xTranslation, double yTranslation)
        {
            if (Math.Abs(e.CumulativeManipulation.Translation.X) > Math.Abs(e.CumulativeManipulation.Translation.Y))
            {
                keybd_event(VK_SHIFT, VK_SHIFT, KEYEVENTF_KEYDOWN, 0);
                mouse_event(0x0800 /* MOUSEEVENTF_WHEEL */, (int)this.manipulationStartedPoint.X, (int)this.manipulationStartedPoint.X, (int)xTranslation, 0);
            }
            else
            {
                mouse_event(0x0800 /* MOUSEEVENTF_WHEEL */, (int)this.manipulationStartedPoint.X, (int)this.manipulationStartedPoint.Y, (int)yTranslation, 0);
            }
        }
```

**Comment by I-TMK** [comment]
mentioned #975.

**Comment by amaitland** [comment]
Currently only the `Y` value is sent to `SendMouseWheelEvent`.

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.Wpf/ChromiumWebBrowser.cs#L1138

> I am used to simulate the touch scroll.

What exactly does this block of code relate to?

**Comment by I-TMK** [comment]
I have changed the code as follows, but it did not work.

``` ChromiumWebBrowser.cs
protected override void OnMouseWheel(MouseWheelEventArgs e)
        {
            var point = e.GetPosition(this);

            var browser = GetBrowser();

            if (browser != null)
            {
                var modifiers = e.GetModifiers(); // add mofifies
                browser.SendMouseWheelEvent(
                    (int)point.X,
                    (int)point.Y,
//                    deltaX: 0,
                    deltaX: e.Delta, // set delta
                    deltaY: e.Delta,
//                    modifiers: CefEventFlags.None); 
                    modifiers: modifiers); // set modifiers
            }
        }
```

> What exactly does this block of code relate to? 
I am calling the mouse_event function when there is a manipulation event using touch.
``` cs
        // for generate mouse wheel event
        [DllImport("USER32.dll", CallingConvention = CallingConvention.StdCall)]
        static extern void mouse_event(int dwFlags, int dx, int dy, int dwData, int dwExtraInfo); 

        // get a touch of events in the UserControl
        this.cefWebView.ManipulationStarted += cefWebView_ManipulationStarted;
        this.cefWebView.ManipulationDelta += OnManipulationDelta;
        this.cefWebView.ManipulationCompleted += cefWebView_ManipulationCompleted;
        this.cefWebView.ManipulationInertiaStarting += cefWebView_ManipulationInertiaStarting;

        // * vertical scroll action  : fire mouse wheel event
        // * horizontal scroll action : fire shift + mouse wheel event
```


Thank you for your response !

**Comment by amaitland** [comment]
> I have changed the code as follows, but it did not work.

Perhaps based on the `ctrl` modifier we need to set the `deltaX`, I don't imagine you can use both at the same time.

For `Touch` you can try implement something like https://github.com/amaitland/CefSharp/commit/d854551a90e55c917a80d60bc67cf641f2f02d9b#diff-bfec65df46ec49f4ed79472147689599R1523

**Comment by amaitland** [comment]
> Perhaps based on the ctrl modifier we need to set the deltaX, I don't imagine you can use both at the same time.

I should have said `shift`.

**Comment by I-TMK** [comment]
ManagedCefBrowserAdapter::OnMouseWheel did not exist in v43 or later.  I tried to implement in a different workaround.  It work fine.

*** cs
        // ChromiumWebBrowser
        protected override void OnMouseWheel(MouseWheelEventArgs e)
        {
            var point = e.GetPosition(this);

            var browser = GetBrowser();

            if (browser != null)
            {
                var modifiers = e.GetModifiers();
                int deltaX = 0;
                int deltaY = 0;
                if (((uint)modifiers & (uint)CefEventFlags.ShiftDown) > 0)
                {
                    deltaX = e.Delta;
                }
                else
                {
                    deltaY = e.Delta;
                }

                browser.SendMouseWheelEvent(
                    (int)point.X,
                    (int)point.Y,
                    deltaX: deltaX,
                    deltaY: deltaY,
                    modifiers: modifiers);
            }
        }
***

Thank you.

**Comment by amaitland** [comment]
> ManagedCefBrowserAdapter::OnMouseWheel did not exist in v43 or later. I tried to implement in a different workaround.

`OnMouseWheel` = `SendMouseWheelEvent` it was just renamed to match the `CEF` interface.

**Comment by amaitland** [comment]
If your interested I've quickly ported the `Touch Scroll` changes
https://github.com/amaitland/CefSharp/commit/3981cea0655ea74a93b18b57c180ec5b2c32b71b

Full disclaimer I haven't tried the code so it might take some toying around to get it working.

**Comment by amaitland** [comment]
I've turned my changes into #1418

If anyone has a chance to test it out, please comment there.
