### ISSUE TITLE
Is there any way to set Timeout in cefsharp when load a url ?

### ISSUE THREAD

**Issue by coldicelion** [cefsharp/CefSharp#1415]
Hi,could you please tell me that Is there any way i can set a Timeout attribute in cefsharp when load a url ? i want make a web crawler, so i think when i load a url, may be i could set a timeout for the crawler,thank you so much!

**Comment by Jayman1305** [comment]
It depends what you trying to achieve.
You could always attach to the LoadingStateChanged event with a timer.
if (e.IsLoading)
{
	IsBusy = true;
	if (_exitStopWatch == null)
	{
		_exitStopWatch = new Stopwatch();
	}
	if (!_exitStopWatch.IsRunning)
	{
		_exitStopWatch.Start();
	}
	while (_exitStopWatch.IsRunning && _exitStopWatch.Elapsed < TimeSpan.FromSeconds(3))
	{

	}
	if (_exitStopWatch.IsRunning)
	{
		_exitStopWatch.Stop();
	}
	IsBusy = false;
}
else
{
	if (_exitStopWatch != null)
	{
		if (_exitStopWatch.IsRunning)
		{
			_exitStopWatch.Stop();
		}
	}
	IsBusy = false;
}

**Comment by amaitland** [comment]
The `CEF` framework it's self doesn't allow for setting timeouts (I believe this is an actual limitation of `Chromium`).

http://magpcss.org/ceforum/viewtopic.php?f=6&t=13080&p=28392#p28392

Implementing some sort of timer as @Jayman1305 has suggested is likely the best approach :+1:

**Comment by coldicelion** [comment]
Jayman1305, amaitland, thank you so much, guys! i think that is a very good idea!!

**Comment by amaitland** [comment]
@coldicelion Happy to close this?
