### ISSUE TITLE
Crash error in some windows 7

### ISSUE THREAD

**Issue by shirotzu** [cefsharp/CefSharp#1416]
http://fotos.subefotos.com/9760b0de6a4d80fd6219ddc338ddc576o.png

**Comment by Justin-Lopez** [comment]
Can you provide more information about this?

**Comment by jankurianski** [comment]
This is a bug in your application, `Agarium`.  This does not appear to be related to CefSharp.

Also, please read this guide before creating your next issue, as it makes it easier for other people to help you:
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue
