### ISSUE TITLE
Size of screenshot with CefSharp.OffScreen.Example

### ISSUE THREAD

**Issue by Ayorus** [cefsharp/CefSharp#1417]
Hello 

I am using CefSharp.OffScreen.Example in order to take some screenshots. 
Before getting the screenshot, I get the size of the HtmlDocument and update the browser viewport. It works well when the size increases, however, if the next web pages are smaller, the size does not get updated and the resulting image is as big as the previous one.  I added the code I use for taking the screenshot. 

I will appreciate any suggestion or guidance you could provide. 

Thanks 

```c#
     Task tk = LoadPageAsync(browser, URL);
     tk.Wait(25000);
            Task<JavascriptResponse> tAlturaScript = browser.EvaluateScriptAsync("(function() { var body = document.body, html = document.documentElement;  return Math.max( body.scrollHeight, body.offsetHeight, html.clientHeight, html.scrollHeight, html.offsetHeight ); })();");
            tAlturaScript.Wait(2000);

          int  iAltura = 0;

            if (!tAlturaScript.IsFaulted && tAlturaScript.Result.Success && int.TryParse(tAlturaScript.Result.Result.ToString(), out iAltura))
            {
              // here the Size of the viewport, is updated with the new height
                browser.Size = new Size(browser.Size.Width, iAltura);
             // Some free time to let the browser updates itself
                System.Threading.Thread.Sleep(1800);
                Task<Bitmap> tkImg = browser.ScreenshotAsync(true);
                tkImg.Wait();
                return tkImg.Result;
            }
```

###### This is the code I use for creating the browser: 

```c#
  var browserSettings = new BrowserSettings();
            browserSettings.WindowlessFrameRate = 1;

            using (var browser = new ChromiumWebBrowser("", browserSettings))
            {
                 foreach(Datarow r in dtUrls.rows)
                 {
                   // Code to take the screenshot
                 }
            }
```

**Comment by illfang** [comment]
You could try to reset the size before loading a page.
```
browser.Size = new Size(1, 1);
Task tk = LoadPageAsync(browser, URL);
```

**Comment by jankurianski** [comment]
Are you sure this is a CefSharp issue and not a problem with your JavaScript?  Have you debugged your code and confirmed the value for `tAlturaScript` is getting smaller as you expect?

**Comment by amaitland** [comment]
> browserSettings.WindowlessFrameRate = 1;

If you increase the framerate does that help? It may take a few render cycles to register the size change.

**Comment by Ayorus** [comment]
Hello, I tried all the suggestions with the following results: 

``` browser.Size = new Size(1, 1); ```  if I set the size, the process hangs. 

``` browserSettings.WindowlessFrameRate = 1; ```   Does not have any effect 

The returned value from JavaScript (```tAlturaScript```) does indeed not change. However I do not consider it like a JavaScript problem. I think the problem is the browser because it does not update the size of the document.

What do you think?

Moreover, I did notice the following error: 

```[1118/160607:ERROR:gpu_process_transport_factory.cc(581)] Lost UI shared context.
[1118/160608:ERROR:gpu_channel_host.cc(222)] Failed to send GpuChannelMsg_CreateOffscreenCommandBuffer.
[1118/160608:ERROR:webgraphicscontext3d_command_buffer_impl.cc(226)] Failed to initialize command buffer. ```

After the error, the size problem occurs

**Comment by jankurianski** [comment]
> The returned value from JavaScript (tAlturaScript) does indeed not change. However I do not consider it like a JavaScript problem. I think the problem is the browser because it does not update the size of the document.

In the sizing calculation script I wrote in my app, I know it was tricky to get the right height.  I found that `body.clientHeight` returns the maximum of the actual content size and the browser height.  This means if your browser size is enlarged to `1000 px` high, and your content is only `500 px` high, `body.clientHeight` will be `1000 px`.

You can confirm this yourself in `Google Chrome` by loading your web page, resize the browser to be higher than the content, and run your script in the `DevTools` window.  I think it will report the browser height instead of the content height.

The solution I used in my sizing script was to shrink the browser size to `10 x 10 px` each time before running my size calculation script.  I also found that only the `scrollHeight` property was necessary.

**Comment by amaitland** [comment]
@Ayorus To isolate if there is a problem in `CefSharp`, can you try resizing to a fixed size which is smaller than the previous? e.g. start with `1280x768`, then shrink to `1024x786` and see if the resize is correct?

**Comment by amaitland** [comment]
@Ayorus Any follow up on this?

**Comment by Ayorus** [comment]
Hello @amaitland  

Unfortunately, none of the suggestions solved the problem. I am still looking for a reliable solution. 
Do you want to close this issue?

**Comment by amaitland** [comment]
> Do you want to close this issue?

Do you have any follow up questions?

**Comment by amaitland** [comment]
We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask follow up questions there.

**Comment by robyle** [comment]
> Hello
> 
> I am using CefSharp.OffScreen.Example in order to take some screenshots.
> Before getting the screenshot, I get the size of the HtmlDocument and update the browser viewport. It works well when the size increases, however, if the next web pages are smaller, the size does not get updated and the resulting image is as big as the previous one. I added the code I use for taking the screenshot.
> 
> I will appreciate any suggestion or guidance you could provide.
> 
> Thanks
> 
> ```cs
>      Task tk = LoadPageAsync(browser, URL);
>      tk.Wait(25000);
>             Task<JavascriptResponse> tAlturaScript = browser.EvaluateScriptAsync("(function() { var body = document.body, html = document.documentElement;  return Math.max( body.scrollHeight, body.offsetHeight, html.clientHeight, html.scrollHeight, html.offsetHeight ); })();");
>             tAlturaScript.Wait(2000);
> 
>           int  iAltura = 0;
> 
>             if (!tAlturaScript.IsFaulted && tAlturaScript.Result.Success && int.TryParse(tAlturaScript.Result.Result.ToString(), out iAltura))
>             {
>               // here the Size of the viewport, is updated with the new height
>                 browser.Size = new Size(browser.Size.Width, iAltura);
>              // Some free time to let the browser updates itself
>                 System.Threading.Thread.Sleep(1800);
>                 Task<Bitmap> tkImg = browser.ScreenshotAsync(true);
>                 tkImg.Wait();
>                 return tkImg.Result;
>             }
> ```
> 
> ###### This is the code I use for creating the browser:
> ```cs
>   var browserSettings = new BrowserSettings();
>             browserSettings.WindowlessFrameRate = 1;
> 
>             using (var browser = new ChromiumWebBrowser("", browserSettings))
>             {
>                  foreach(Datarow r in dtUrls.rows)
>                  {
>                    // Code to take the screenshot
>                  }
>             }
> ```

@Ayorus  Hello,Do you sloved this problem? I meet the same questions? Can we get screenshoot by element's  id?  it's maybe very useful.

**Comment by Ayorus** [comment]
No Robyle, in fact I gave up with that code and used PhantomJS instead. I recomment you to take a look on: 
 
https://developers.google.com/web/updates/2017/04/headless-chrome
 
It is part of our TODO list already 
 
All the best 
 
-----Original Message-----

**Comment by khurramsaddique** [comment]
i have fixed this issue 
https://stackoverflow.com/questions/39411950/full-page-screenshot-with-cefsharp-in-c-sharp/65719973#65719973
