### ISSUE TITLE
BrowserSubprocess.exe crash on xp sp3

### ISSUE THREAD

**Issue by feliciwithme** [cefsharp/CefSharp#1420]
Application: CefSharp.BrowserSubprocess.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.SEHException
Stack:
   at <Module>.CefExecuteProcess(CefMainArgs*, CefRefPtr<CefApp>*, Void*)
   at CefSharp.CefAppWrapper.Run()
   at CefSharp.BrowserSubprocess.Program.Main(System.String[])

    CefSharp Version: 45 (47)
    Operating System: windows xp sp3
    x86:
    WPF or Winform

**Comment by amaitland** [comment]
See the https://github.com/cefsharp/CefSharp/wiki/Windows-XP--No-Longer-Supported guide for info about `Windows XP`.

It's no longer supported, some users suggest that it works, it is however not officially tested.

**Comment by feliciwithme** [comment]
Thank you very much!

**Comment by rover886** [comment]
@feliciwithme I have tested version 43 on XP SP3 with WIC installed. Make sure VC++ 2012 DLLs are kept in CefSharp executing directory or VC++ Redistributable is installed on system.

**Comment by amaitland** [comment]
> Give it a try for version 45.

`45.0.0` is built using `VC++ 2013`, so there's a chance it will already work. I don't believe you need to specifically use the `v120_xp` toolset, the `v120` should work. (It has been quite some time since I tested this, so I make no guarantees).

**Comment by feliciwithme** [comment]
@amaitland @rover886 xp crash has been fixed, use the v120_xp or v120 toolset, thank you.
