### ISSUE TITLE
Logo for CefSharp project

### ISSUE THREAD

**Issue by hgupta9** [cefsharp/CefSharp#1423]
I've made a logo for CefSharp. Can you see if its okay and if any changes are required? When you are done changing it I will upload all sources (vector, bitmap, etc)

![cefsharp logo 2](https://cloud.githubusercontent.com/assets/6797866/11205967/e9dc5782-8d31-11e5-8f7b-cca80a39e461.png)

**Comment by shirotzu** [comment]
You can change the color of the icon to blue like Chromium

**Comment by hgupta9** [comment]
@amaitland - Are you okay with this? Otherwise I won't bother putting any more effort into it.

**Comment by amaitland** [comment]
Are there other options?

Maybe use the `CEF` logo and replace the `CEF` with `CefSharp`?

http://magpcss.org/ceforum/styles/prosilver/imageset/site_logo.gif

**Comment by hgupta9** [comment]
The CEF logo is okay, but kinda boring, don't you think?

**Comment by jankurianski** [comment]
I think V5 is the best composed logo.  However I am not a fan of the `CEF` font because while it looks cool, the `E` is hard to recognize (more so for non-English speakers).

**Comment by amaitland** [comment]
> I think V5 is the best composed logo. However I am not a fan of the CEF font because while it looks cool, the E is hard to recognize (more so for non-English speakers).

I think `v5` with a cleaner font, also maybe go with `CefSharp` rather than `CEFSHARP` as that's how the project is referenced.

**Comment by hgupta9** [comment]
How about these?

V8.0
![cefsharp logo 8](https://cloud.githubusercontent.com/assets/6797866/11265496/a64dc98c-8ec2-11e5-8a57-8a4d53ca394c.png)

V8.1
![cefsharp logo 8b](https://cloud.githubusercontent.com/assets/6797866/11265499/ab6d325e-8ec2-11e5-84e5-2eba86c4d28d.png)

V8.2
![cefsharp logo 8c](https://cloud.githubusercontent.com/assets/6797866/11265502/af906acc-8ec2-11e5-9fb8-e5f3fcda8cc5.png)

V8.3
![cefsharp logo 8d](https://cloud.githubusercontent.com/assets/6797866/11265507/b4c4d6ae-8ec2-11e5-961c-4d6159c29e76.png)

**Comment by hgupta9** [comment]
@amaitland @jankurianski @shirotzu - Any feedback regarding the logo?

**Comment by amaitland** [comment]
I personally prefer `CefSharp` over `Cef#` (it's the projects name after all).

**Comment by jankurianski** [comment]
I have to agree, while `cef#` looks cooler, it is not really the name of the project.

I like the new font :smile:

**Comment by hgupta9** [comment]
Fine. Try these

9A
![cefsharp logo 9](https://cloud.githubusercontent.com/assets/6797866/11331695/0c1ae69a-91e4-11e5-88b2-8953b21a6814.png)

9B
![cefsharp logo 9a](https://cloud.githubusercontent.com/assets/6797866/11331689/007bf932-91e4-11e5-8748-a32d5efd8773.png)

9C
![cefsharp logo 9b](https://cloud.githubusercontent.com/assets/6797866/11331698/1152c2cc-91e4-11e5-9ce8-1595d1b49288.png)

10
![cefsharp logo 10](https://cloud.githubusercontent.com/assets/6797866/11331700/167d7602-91e4-11e5-9870-f8393479cee3.png)

**Comment by amaitland** [comment]
`10` is the closest, though the `Sharp` font is too much of a contrast.

**Comment by hgupta9** [comment]
@amaitland @jankurianski @shirotzu - Please decide on something guys....

11
![cefsharp logo 11](https://cloud.githubusercontent.com/assets/6797866/11365279/501d85fe-92cb-11e5-9554-bcf96d0c9e81.png)

12
![cefsharp logo 12](https://cloud.githubusercontent.com/assets/6797866/11365281/56545a10-92cb-11e5-9b2c-8d97c55b6ca1.png)

13
![cefsharp logo 13](https://cloud.githubusercontent.com/assets/6797866/11365291/5c9fa212-92cb-11e5-8f48-ea319f1cf870.png)

**Comment by amaitland** [comment]
I know it's plan and boring, I like `11` the best so far :+1:

**Comment by hgupta9** [comment]
@jankurianski @shirotzu - Oh well, thats a pity. Anyways, is this everyone's opinion?

**Comment by krk** [comment]
8.3 seems nice.

**Comment by hgupta9** [comment]
I know, I liked the entire 8 series too, but alex wants CefSharp instead of Cef#.

**Comment by shirotzu** [comment]
@hgupta9 I like the v11

**Comment by hgupta9** [comment]
Okay, fine, I'll use that for now ... until I have time to improve it more.

**Comment by jankurianski** [comment]
I like v11 too.  It pays homage to CEF while looking better than their logo!  Nice work @hgupta9

**Comment by hgupta9** [comment]
@jankurianski - Glad you all like it. Will work on the website now.

**Comment by chillitom** [comment]
Liking v11 also, the website is coming on great too. Nice one guys.

**Comment by hgupta9** [comment]
I'm closing this since we have arrived at a conclusion. Thanks folks.
