### ISSUE TITLE
Including some files in Project

### ISSUE THREAD

**Issue by shirotzu** [cefsharp/CefSharp#1425]
I can reduce the number of files as well as the example of CEFBUILD?
for example, I think that several files were included in cefclient.exe as it weighs 921 KB
while the CefSharp weighs 160 KB
in cefclient.exe there is no cefsharp.browsersubprocess.exe

I can include some files in my project, as cefsharp.browsersubprocess.exe?

http://i.imgur.com/pUzoDtX.png

**Comment by amaitland** [comment]
> I can include some files in my project, as cefsharp.browsersubprocess.exe?

Currently no.

**Comment by shirotzu** [comment]
the best way would then rename, for not be so simply.

**Comment by amaitland** [comment]
Your sentence doesn't make sense.....

**Comment by amaitland** [comment]
See #1432 for one possible solution, read the issue in it's entirety before asking any follow up questions. Please don't make me regret trying to help you!
