### ISSUE TITLE
The cookies that from Cef.GetGlobalCookieManager().VisitAllCookies are different from Chrome browser

### ISSUE THREAD

**Issue by ming526197zhang** [cefsharp/CefSharp#1427]
Hi,
     I use offscreen webbrowser, but I found the cookies that from Cef.GetGlobalCookieManager().VisitAllCookies are different from the cookies show in Chrome browser develop tool. Why? From the attachment image, you can see Chrome browser has "_i", but cefsharp cookies do not have.

The cookies in Visual Studio debug, IsReady is true now
![cefsharp cookie](https://cloud.githubusercontent.com/assets/13885604/11234701/a653b832-8e05-11e5-91eb-38a940150672.png)
The cookies in Chrome browser develop tools
![chrome cookie](https://cloud.githubusercontent.com/assets/13885604/11234700/a6510466-8e05-11e5-9a6d-8644a7a11bb1.png)

```c#
CookieVisitor _cookieVisitor = new CookieVisitor();
CefSharp.OffScreen.ChromiumWebBrowser _offScreenBrowser = new CefSharp.OffScreen.ChromiumWebBrowser("http://ebooking.qunar.com/ebPage/login.html");
_offScreenBrowser.FrameLoadEnd += (sender, e) =>
{
    CefSharp.Cef.GetGlobalCookieManager().VisitAllCookies(_cookieVisitor);
}

public class CookieVisitor : ICookieVisitor
    {
        public CookieVisitor()
        {
            IsReady = true;
        }
        public bool Visit(Cookie cookie, int count, int total, ref bool deleteCookie)
        {
            lock (this)
            {
                if (_cookies.ContainsKey(cookie.Name))
                {
                    _cookies[cookie.Name] = new System.Net.Cookie(cookie.Name, cookie.Value, cookie.Path, cookie.Domain);
                    _cookies[cookie.Name].Name = cookie.Name;
                    _cookies[cookie.Name].Value = cookie.Value;
                    _cookies[cookie.Name].Path = cookie.Path;
                    _cookies[cookie.Name].Domain = cookie.Domain;
                }
                else _cookies.Add(cookie.Name, new System.Net.Cookie(cookie.Name, cookie.Value, cookie.Path, cookie.Domain));
                //fire when complete
                IsReady = count == total - 1;   //
            }
            return true;
        }
        Dictionary<string, System.Net.Cookie> _cookies = new Dictionary<string, System.Net.Cookie>();
        public Dictionary<string, System.Net.Cookie> AllCookies { get { return _cookies; } }
        public bool IsReady { get; set; }
        public System.Net.Cookie this[string name]
        {
            get { return _cookies.ContainsKey(name) ? _cookies[name] : null; }
        }
        ~CookieVisitor()
        {
        }
    }
```

**Comment by amaitland** [comment]
What version are you using?

**Comment by ming526197zhang** [comment]
I use version 43

**Comment by jankurianski** [comment]
Do you have more details about the cookie `_i`?  Is it secure/http-only?

Cookies can be set by JavaScript - perhaps you are not waiting long enough.  `FrameLoadEnd` can be fired before all JavaScript on the page is executed.  Try wrapping your `VisitAllCookies` call in a new `Task` that is called after waiting a few seconds.

**Comment by ming526197zhang** [comment]
In chrome, I find "_i" was created half year ago, I delete this cookie in chrome, and web can work too, and "_i" do not appear. So I think cefsharp is ok, cefsharp cookies do not have "_i".

**Comment by angshuman-agarwal** [comment]
Hi,
I am seeing a similar issue. The cookie domain is empty and cookie path has the cookie domain value. 

But in Chrome browser both domain and path show up correctly. I am using version 57 of cef sharp.

Any idea what I could do differently please ?
