### ISSUE TITLE
What cefsharp library file to include when creating a setup file in Visual Studio?

### ISSUE THREAD

**Issue by ahgan84** [cefsharp/CefSharp#1428]
Hi guys, I have created a application in Visual Studio which showing the cefsharp browser. I've build the setup file for this application too. But it won't run after I install it. When I use debug/release mode in Visual Studio, it can run.

Closer investigation by using trial and error, in my Program.cs file, I have the below:

            static void Main()
        {
            Cef.Initialize(new CefSettings());
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new Form1());
        }

When I take out the line Cef.Initialize(new CefSettings());, and rebuilt the setup file and install again on my pc. My application can run again.

What's wrong with Cef.Initialize? Is it should not declare there in Main()?

Or I have not include some library files in the setup files system when I build the setup? 

Do you know what exactly should I include in the setup files system for CefSharp to run successfully?

**Comment by amaitland** [comment]
There are many topics that cover this subject, try searching for `clickonce`.

https://github.com/cefsharp/CefSharp/search?q=clickonce&type=Issues&utf8=%E2%9C%93

You also have to make sure `VC++ Redist` is installed on your target machines.

https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#6-how-do-i-include-the-visual-studio-c-2012-redistributables-on-the-target-app

You need to install the appropriate version base on the table in https://github.com/cefsharp/CefSharp#version-branches

**Comment by ahgan84** [comment]
Thanks for the suggestion. I will look into it. 
Just feel weird because, I install my app in the same machine as my Visual Studio where i do the coding. How come when I debug or release mode can run, but after installation cannot run?

**Comment by amaitland** [comment]
You need to install `VC++` on client machines, it's installed by default when you install `Visual Studio`.

The `Readme.txt` that's displayed when you install the `Nuget` packages has more information.
https://github.com/cefsharp/CefSharp/blob/cefsharp/43/NuGet/Readme.txt#L19

**Comment by avspeed** [comment]
This one is worth mentioning as well

https://github.com/cefsharp/CefSharp/wiki/Output-files-description-table-(Redistribution)

**Comment by ahgan84** [comment]
avspeed, you mean these files are produced when I compiled in debug or release mode right? Do I need to include these files in the setup file system if I want to create a setup file?

**Comment by avspeed** [comment]
yes you do need to include all the ones that are marked as Yes in the always required column.
They shoudl all be in your output (debug or release) folder anyway, so just include them.

**Comment by ahgan84** [comment]
avspeed, you mean I always have to include it manually every time I want to create a setup file with CefSharp in it?
What if I do this way?
https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#6-how-do-i-include-the-visual-studio-c-2012-redistributables-on-the-target-app
Does it auto include?

**Comment by ahgan84** [comment]
amaitland, you mentioned that I should search for clickonce. Does creating clickonce application same as creating a setup file? What I want to do is creating setup file.

**Comment by avspeed** [comment]
@ahgan84 sorry to interrupt - but clickonce creates a setup file that you publish and can be installed over the web. It is all the same.

**Comment by ahgan84** [comment]
@avspeed, ok. About the question I ask you just now, do I include it manually or I can include it by auto?
And then there this solution. http://stackoverflow.com/questions/22841585/deploying-wpf-application-with-3rd-party-dlls/24287807#24287807
Is it still valid? Do I need to do all the steps?

**Comment by avspeed** [comment]
Al lot of the dependencies are not .NET dlls, so they will never be picked up by your installer ( not sure which one you use but it does not matter ) .. The article refers to wpf dependencies. Some winforms ones are different.
If I were you I would pick the dependencies one by one and add them to your setup and make sure that they get copied to the directory when your executable will reside. It is fairly easy. This does not apply of course to the VC++ dependency .. but every installer gives you the option to bootstrap it, so I am sure that your installer also has that option.

**Comment by ahgan84** [comment]
@avspeed, yes my app finally runs after installation. I have included all the files and folder in the debug/release folder into the setup file system like what you told me.

**Comment by avspeed** [comment]
Great job! Now as you work with cefsharp and if you care about the size of your installer, use this https://github.com/cefsharp/CefSharp/wiki/Output-files-description-table-(Redistribution) to figure out what you really need and what can be ommited.

**Comment by Jayman1305** [comment]
@amaitland Should i write a simple installer than installs all the dependencies and we can just embed it in the project. Should be pretty small and branded as cefsharp dependencies test. If your app doesn't work, drop it in this folder after running the setup. If it works, you missing either the c++ runtimes, the correct .net version on the client. In fact maybe we just need a merge module.

**Comment by ahgan84** [comment]
@avspeed, the method which to include all the files from release folder seems to have a problem when I want to switch between creating a x86 or x64 setup file. At first I'm creating a x64 setup file so I included all the files in the x64 release folder. Now I want to switch to compiling a x86 setup file and there are errors coming out saying the files I included in the setup file system is still x64-bit. I have to manually change the files inside the setup file system to include the files in x86 release folder. Is there any more shortcut way of doing this? I don't want to always change the files on the setup file system everytime I want to compile a setup file with different bit.

**Comment by ahgan84** [comment]
Guys, I have this error when I want to change from creating a x64bit setup file to creating a x32bit setup file:

     Error	1	File 'CefSharp.dll' targeting 'AMD64' is not compatible with the project's target platform 'x86'	C:\Work\Project 2015\myq-io-kiosk\Setup2\Setup2.vdproj	myQ.Kiosk_x32bit-Setup
     Error	3	File 'CefSharp.WinForms.dll' targeting 'AMD64' is not compatible with the project's target platform 'x86'	C:\Work\Project 2015\myq-io-kiosk\Setup2\Setup2.vdproj	myQ.Kiosk_x32bit-Setup
     Error	5	File 'CefSharp.Core.dll' targeting 'AMD64' is not compatible with the project's target platform 'x86'	C:\Work\Project 2015\myq-io-kiosk\Setup2\Setup2.vdproj	myQ.Kiosk_x32bit-Setup

But I have included all the files inside x86 release folder. The files inside this folder should be all run on x32bit right?

**Comment by ahgan84** [comment]
I have solve the above problem by deleting this setup project and recreating again the project setup file.

**Comment by ahgan84** [comment]
I have tried to install my x32bit setup in my pc which is running on x64bit and as normal, my application can run.
I try to install it in another x32bit machine but cannot run. I have installed the Visual C++ Runtime Library 2013 x86bit into that machine but still my app cannot run. 
@amaitland , at the beginning of this topic, you mentioned that CefSharp need VC++ Redist 2012. Now I have installed Visual C++ Runtime Library 2013. Is it that I need a 2012 version only can run? But my visual studio project's prerequisite only have 2013 version to choose from.

**Comment by avspeed** [comment]
If you have gotten cefsharp from the master branch, the vc++ redist 2013 is what you need.
That might not be your problem.. Take a look at the Event Viewer on you machine and see if you can get more info

Version Branches

Branch	CEF Version	VC++ Version	.Net Version	Status
master	        2526	 2013	            4.0	Development
cefsharp/45	2454	2013	            4.0	Pre-Release
cefsharp/43	2357	2012	            4.0	Release
cefsharp/41	2272	2012	            4.0	Unsupported
cefsharp/39	2171	2012	            4.0	Unsupported
cefsharp/37	2062	2012	            4.0	Unsupported

**Comment by ahgan84** [comment]
I've installed the vc++ redist 2012 and it solved the problem.
I'm still using cefsharp/43.

**Comment by amaitland** [comment]
> @amaitland Should i write a simple installer than installs all the dependencies and we can just embed it in the project. Should be pretty small and branded as cefsharp dependencies test. If your app doesn't work, drop it in this folder after running the setup. If it works, you missing either the c++ runtimes, the correct .net version on the client. In fact maybe we just need a merge module.

There is a `DependencyChecker` class that can be used the required dependencies are present.

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp/DependencyChecker.cs#L17

`Cef.Initialize` has an optional `performDependencyCheck` param for which you can enable dependency checking at runtime.
https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.Example/CefExample.cs#L127

As for the `VC++` requirement, there is a rough plan in place as per #1189
