### ISSUE TITLE
Cef.Shutdown() take 10 seconds to close my app.

### ISSUE THREAD

**Issue by ahgan84** [cefsharp/CefSharp#1429]
Hi guys, I've putting the below code to close my app when user press Alt+F4:

        private void Form1_FormClosing(object sender, FormClosingEventArgs e)
        {

            if (Application.MessageLoop)
            {
                Application.Exit();
                Cef.Shutdown();
            }
            else
                Environment.Exit(1);
        }

But it always takes 10 seconds for my app to shut down. Is it normal? 
Anyway to shorten it?

**Comment by amaitland** [comment]
What version are you using? Are you using any of the `javascript` features? Like script script execution or `javascript binding`? If not you can disable the `WCF` service, or you can reduce the `WCF` timeout.

See below
https://github.com/cefsharp/CefSharp/commit/d1ba723bd51c01a926a5fa6209de9358734f795e#diff-047c6ca0a2cf7049f7096299d87a7d7aR32

**Comment by ray007** [comment]
Does it make a difference if you call `Cef.Shutdown();`  before `Application.Exit();`?

**Comment by amaitland** [comment]
If it's exactly 10 seconds (which is the default `WCF` timeout) then see #1304

**Comment by ahgan84** [comment]
I'm creating a winform app not a service so should be can disable it.
How do we disable wcf service?

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.Example/CefExample.cs#L43

**Comment by ahgan84** [comment]
After putting CefSharpSettings.WcfEnabled = false;, I found out that I won't be able to restart my app using below code anymore:

                System.Diagnostics.Process.Start(Application.ExecutablePath);
                Application.Exit();

Any solution @amaitland ?

**Comment by ahgan84** [comment]
Actually I'm calling a C# function in javascript:
     printer.saveXML(data);

saveXML() is a function inside C#:

             public void saveXML(data)
            {
                XmlWriterSettings settings = new XmlWriterSettings();
                settings.Indent = true;
                using (XmlWriter writer = XmlWriter.Create("Config.xml", settings))
                {
                     // writing data into the config.xml filr
                }

                System.Diagnostics.Process.Start(Application.ExecutablePath);
                Application.Exit();
            }
        }
In the saveXML() function I call for restart. It does not work now.

**Comment by coldicelion** [comment]
you should change CefExample.cs file, update the  "settings.LogSeverity = LogSeverity.Verbose;" to "settings.LogSeverity = LogSeverity.Disable;" ; it works for me.

**Comment by amaitland** [comment]
> After putting CefSharpSettings.WcfEnabled = false;, I found out that I won't be able to restart my app using below code anymore:

Shouldn't make any difference.

> In the saveXML() function I call for restart. It does not work now after disabling the WCF. Any idea what's wrong?

As I said, those features won't work.

> IS it that if I disable WCF, I won't be able to call the c# function from javascript?

Correct.

**Comment by amaitland** [comment]
> you should change CefExample.cs file, update the "settings.LogSeverity = LogSeverity.Verbose;" to "settings.LogSeverity = LogSeverity.Disable;" ; it works for me.

Unfortunately that is unlikely to have any affect. The problem lies in the `BrowserSubProcess` not calling close on the `WCF` channel, for which the main process then takes the default `10 second` timeout to close.

If you don't call `Cef.Shutdown` then the timing of things changes slightly. The framework will call shutdown for you. I have had success with just relying on the default behavior

https://github.com/cefsharp/CefSharp/issues/1304#issuecomment-145000297

**Comment by coldicelion** [comment]
Oh I see!

**Comment by ahgan84** [comment]
@amaitland, my problem is that my cefsharp app still runs in the background even though I have closed the app by using Alt+F4. I have tried Application.Exit() to Cef.Shutdown() but no effect. Any idea what to try next?

**Comment by amaitland** [comment]
> If you don't call Cef.Shutdown then the timing of things changes slightly. The framework will call shutdown for you. I have had success with just relying on the default behavior

Remove the call to `Cef.Shutdown`.

**Comment by ahgan84** [comment]
@amaitland , yes... at the beginning, I only put Application.Exit(), but my app still appeared in the processes in task manager. That means it still runs in the background right?
That's why I'm finding other ways and I found this Cef.Shutdown() command, but it does not work also.

**Comment by amaitland** [comment]
Change the `WCF` timeout as I linked to above then.

**Comment by amaitland** [comment]
@ahgan84 How'd you go?

**Comment by amaitland** [comment]
Settings `CefSharpSettings.WcfTimeout = TimeSpan.Zero` is another viable solution. You can then keep calls to `Cef.Shutdown` and `Dispose` of the `browser` instances.
