### ISSUE TITLE
DownloadHander - Hide current browser

### ISSUE THREAD

**Issue by epyweb** [cefsharp/CefSharp#1431]
Hi,

How can I hide the current browser when a "Save as" dialog appears ?

My Code:

 private class DownloadHandler : IDownloadHandler
    {

      public void OnBeforeDownload(IBrowser browser, DownloadItem downloadItem, IBeforeDownloadCallback callback)
      {
        
        if (!callback.IsDisposed)
        {
          using (callback)
          {
            callback.Continue(downloadItem.SuggestedFileName, showDialog: true);
            
            
          }
        }
      }

      public void OnDownloadUpdated(IBrowser browser, DownloadItem downloadItem, IDownloadItemCallback callback)
      {
        if (downloadItem.IsComplete || downloadItem.IsCancelled)
        {
          browser.GetHost().CloseBrowser(true);
        }
      }
    }

**Comment by amaitland** [comment]
There is nothing directly in `CefSharp`, it is only a browser control remember. You would need to pass a reference to your `Form` or `Window`.

**Comment by amaitland** [comment]
@epyweb Any follow up on this one?

**Comment by amaitland** [comment]
Closing due to lack of feedback.
