### ISSUE TITLE
Support Visual Studio 2012

### ISSUE THREAD

**Issue by antoniogarcez** [cefsharp/CefSharp#1433]
Hi,

I want to know if I can run CefSharp in Visual Studio 2012?

**Comment by amaitland** [comment]
> I want to know if I can run CefSharp in Visual Studio 2012?

By run, do you mean install the `Nuget` packages? If so then yes you can use `VS2012`.

**Comment by hgupta9** [comment]
Simple. Just create a VS 2012 WinForms/WPF C# project, add references > add the CefSharp.dll and CefSharp.WinForms.dll (or CefSharp.Wpf.dll if you are using WPF).

Then type this code in your MainForm.cs

       public ChromiumWebBrowser browser;
       public void Init(){
               Cef.Initialize(new CefSettings());
               browser = new ChromiumWebBrowser ("www.google.com");
               this.Controls.Add(browser);
               browser.Dock = DockStyle.Fill;
       }

Test your project (F5) and you will see a browser with Google!

**Comment by hgupta9** [comment]
Of course you can. 

1. Create a WinForms C# project
2. Add references to CefSharp.dll and CefSharp.WinForms.dll
3. Copy all these files into Bin/Debug folder of your project (https://github.com/cefsharp/CefSharp/wiki/Output-files-description-table-(Redistribution))
4. Copy this code in Main.cs

    public ChromiumWebBrowser browser;
    public void Init(){
          browser = new ChromiumWebBrowser("www.google.com");
          this.Controls.Add(browser);
          browser.Dock = DockStyle.Fill;
    } 

5. Press F5 and you will get a browser filling the window with Google!

**Comment by amaitland** [comment]
> Add references to CefSharp.dll and CefSharp.WinForms.dll
> Copy all these files into Bin/Debug folder of your project (https://github.com/cefsharp/CefSharp/wiki/Output-files-description-table-(Redistribution))

If you install the official `Nuget` packages there is no need for either of these steps assuming you target `x86` or `x64` (`AnyCpu` is not supported). The references will be added and the files copied automatically.

**Comment by antoniogarcez** [comment]
Thanks for replies, the purpose of my question is because I read that support for VS2012 was finished.

**Comment by antoniogarcez** [comment]
hgupta9, I make that you said but doesn´t work. In Cef.Initialize, how I can declare Cef variable?

**Comment by amaitland** [comment]
> Thanks for replies, the purpose of my question is because I read that support for VS2012 was finished.

Support for compiling the source code using `VS2012` has been removed. 

@antoniogarcez See the `MinimalExample` project for a working demo.

https://github.com/cefsharp/CefSharp.MinimalExample

**Comment by amaitland** [comment]
Some potentially useful `Tutorials`

`WinForms`
http://www.codeguru.com/columns/dotnet/if-you-like-it-put-an-html5-ui-on-it.html

`WPF`
http://www.codeproject.com/Articles/881315/Display-HTML-in-WPF-and-CefSharp-Tutorial-Part

**Comment by hgupta9** [comment]
@antoniogarcez - Check out the latest codeproject tutorial

http://www.codeproject.com/Articles/1058700/Embedding-Chrome-in-your-Csharp-App-using-CefSharp

Its not the nuget method but I tested it and it works.

**Comment by amaitland** [comment]
> Its not the nuget method but I tested it and it works.

@hgupta9 I believe your doing people a diservice by advising them to `copy and paste` the files.

- What happens when you clean your solution? 
- What happens when you check your solution into source control?
- The links you provide are from an `unofficial` source, you've linked the `45.0.0` packages which haven't been uploaded to `Nuget` as yet, they haven't been tested.

The only official way is to use the `Nuget` packages, I know your trying to help, please **stop** telling people to do things manually, long term it's not a great solution.

**Comment by amaitland** [comment]
@hgupta9 `45.0.0` requires `VC++ 2013 Redist` to run.
