### ISSUE TITLE
Video Stream does not show

### ISSUE THREAD

**Issue by Star-Q** [cefsharp/CefSharp#1434]
#### Issue Summary
What is the expected output? What do you see instead?
Expected Output:
The stream to show

What do I see instead?
http://prntscr.com/94ra7x

This is my code:

    Private WithEvents browser As ChromiumWebBrowser

    Public Sub New()
        InitializeComponent()

        Dim settings As New CefSettings()
        CefSharp.Cef.Initialize(settings)
        browser = New ChromiumWebBrowser("starq.tk/starQ_media/channels/skysports/ss1.html") With {
            .Dock = DockStyle.Fill
        }
        stream.Controls.Add(browser)
        browser.RequestHandler = New Ad_Block

    End Sub

#### Technical details
* CefSharp Version: CefSharp 45.0.0-pre01
* Operating System: Windows 7
* x86/x64: x86
* WinForms/WPF/OffScreen: WinForms

--
I'm trying to make CefSharp to go to a stream and nothing shows.. just a black frame where the video would be..

**Comment by jankurianski** [comment]
Please read this article and add a new comment with the required info to allow others to help you:
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue

Also, let us know what steps you have taken to try and debug the problem on your own, such as using the default CEF client instead of CefSharp:
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

**Comment by Star-Q** [comment]
OK, so I'm trying to link `CefSharp` to a stream that is hosted on a site. In `Firefox/Chrome` the stream shows fine and it shows live. When I debug my app and `CefSharp` is loaded, it justs shows a `black frame` where the stream would be. I'm not sure what `CefSharp` is missing from its files. Would it have to be with `MP4` issues or something?

**Comment by amaitland** [comment]
@Star-Q Think about if you were trying to help someone with a similar problem? What information would you require? You're missing a lot of key information. I have updated your original post using the `Bug Template` provided in the contributing.md document, please edit your issue and post a new comment when done (GitHub doesn't provide a notification when an issue us updated).

(It gets really repetitive asking these questions over and over again, so if you could actually read the links provided that would be great!)

**Comment by Star-Q** [comment]
Updated :page_facing_up:

**Comment by amaitland** [comment]
Is it `HTML5` stream or a `Flash` player? 

When I load your url in `CefSharp.WinForms.Example` I get a player load

If it's `Flash` based then you need `Pepper Flash` to be installed.

**Comment by Star-Q** [comment]
Did the stream show live? Cause it shows like play now and everything but once you pass that and press the close button its just a black frame.

**Comment by amaitland** [comment]
> Is it HTML5 stream or a Flash player?

Any reason you haven't answered this pretty basic question yet? I don't have unlimited time

Does it use `Widevine Content Decryption Module (CDM)`?

https://support.google.com/chrome/answer/6072728?hl=en

> Did the stream show live? Cause it shows like play now and everything but once you pass that and press the close button its just a black frame.

I didn't try, only have a few mins spare at the moment.

**Comment by Star-Q** [comment]
It uses JW Player so I suppose flash..

**Comment by amaitland** [comment]
What version of `Pepper Flash` do you have installed?

**Comment by Star-Q** [comment]
Latest one, I updated it yesterday.

**Comment by amaitland** [comment]
![stream](https://cloud.githubusercontent.com/assets/307872/11313585/b04b2674-9029-11e5-95c5-463a8d183e2d.PNG)

Using Flash 19.0.0.245. You can load `chrome://version` to see if `Flash` is detected and what version.

The content of your stream looks **very** questionable in terms of being legal, so I won't look into this any further.

**Comment by Star-Q** [comment]
Thanks for the help..

**Comment by amaitland** [comment]
@Star-Q Can you post the eventual solution to your problem so that others may benefit?

**Comment by Star-Q** [comment]
Sure why not?..

**Comment by Star-Q** [comment]
@amaitland It seems to work on CefSharp 41 but I don't see the changes of Flash except NPAPI support in CefSharp 45

**Comment by amaitland** [comment]
`Chromium 43` changed to using `PPAPI` as it's default, if you need `NPAPI` in `43` you need to enable it.

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.Example/CefExample.cs#L54
