### ISSUE TITLE
CoreCLR support?

### ISSUE THREAD

**Issue by robertmuehsig** [cefsharp/CefSharp#1435]
I'm not even sure if this is the correct project to ask, but let's see if someone can get me on the right path. 
As you might know with the new CoreCLR it is pretty "easy" to write cross platform server or console apps. But currently there are no plans from Microsoft to bring in any actual UI framework, so my idea is  actual pretty simple:

If we can self host a CoreCLR based ASP.NET 5 application and we could ship a CEF-Host it would be easy to write cross platform apps (targeting Windows, Mac, Linux - whereever the CoreCLR runs).

As far as I know CefSharp only combines WindowsForms/WPF with CEF, so I'm not sure if this project wants to create the actual browser host window or if this is something the CefSharp could do, but I'm pretty sure here are much smarter people than me.

Just to make sure: All I want is a application which hosts CEF and can execute CoreCLR stuff, so no additional WindowsForm/WPF controls - just a "pure" browser window.

**Comment by amaitland** [comment]
`CefSharp` is compiled using `VC++`, so is `Windows` only. You'll likely need a framework that does `P/Invoke` calls, for which there are a few.

https://bitbucket.org/xilium/xilium.cefglue/issues/108/linux-support
https://bitbucket.org/chromiumfx/chromiumfx/issues/9/mono-support

For this sort of question, somewhere like `stackoverflow` is likely a better place to ask :+1:

**Comment by amaitland** [comment]
You may also be better of using just straight `C++`, `CEF` it's self has working demo application what supports `Windows`, `Linux` and `Mac`. It's a little more work to maintain the `UI` specific pieces, though if your just looking for a simple browser, then it should be pretty trivial.

https://bitbucket.org/chromiumembedded/cef/src/c199539747c6dc2c9103c41f2dda0bd07c872461/tests/cefclient/?at=master

**Comment by robertmuehsig** [comment]
That´s the direction I was looking for - thanks!
