### ISSUE TITLE
CefSharp 45

### ISSUE THREAD

**Issue by Spiderpig86** [cefsharp/CefSharp#1436]
I just have a small question about plugins. So I've read that the internal PDF viewer should be working again after being removed in version 43 and that NPAPI is now disabled. Would there still be support for other plugins (Unity for example) if we specify a path or would those plugins not load? Would existing plugins on the system load without specifying a path?

**Comment by amaitland** [comment]
> So I've read that the internal PDF viewer should be working again after being removed in version 43 and that NPAPI is now disabled.

The internal `PDF` version works again, that's correct. `NPAPI` support has been **removed**, it's not disabled.

> Would there still be support for other plugins (Unity for example) if we specify a path or would those plugins not load?

Does `Unity` provide a `PPAPI` based plugin? The older `NPAPI` version will no longer work.

**Comment by Spiderpig86** [comment]
Thank you very much for the clarification. I believe that `Unity` will be working on a `WebGL` based solution since they won't be providing a `PPAPI` based plugin.
