### ISSUE TITLE
ChromiumWebBrowser URL changed event

### ISSUE THREAD

**Issue by xmedeko** [cefsharp/CefSharp#1437]
I would like to have an event to inform for every URL change in `ChromiumWebBrowser`, event for HTTP 302 (and similar redirects). I have tried events `FrameLoadStart`, `FrameLoadEnd`, but they do not pass an URL which results into HTTP 302.

**Comment by amaitland** [comment]
Check out `IRequestHandler`.

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp/IRequestHandler.cs#L146

Also please include which version of `CefSharp` your using.

**Comment by xmedeko** [comment]
I use CefSharp 41. I see the this project develops rapidly. `IRequestHandler.OnBeforeBrowse` did a job. Thanks.

Note: some abstract class implementing IRequestHandler with default behaviour would be handy, when I need override just one method. (I know there is and example).

**Comment by amaitland** [comment]
> I use CefSharp 41. I see the this project develops rapidly.

Yes, `41` is a few versions out of date.

> Note: some abstract class implementing IRequestHandler with default behaviour would be handy, when I need override just one method. (I know there is and example).

Your welcome to submit a `PR` implementing such.
