### ISSUE TITLE
CefSharp 45.0.0 Released

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#1438]
Just an `FYI` for those that are interested. I've pushed the packages to `Nuget.org` they should be indexed and available within the next few hours.

See https://github.com/cefsharp/CefSharp/releases/tag/v45.0.0 for details on the release.

This is a minor upgrade from `43.0.1`, a few upstream `CEF` changes and a couple of minor breaking `API` changes. Should be a trivial upgrade for most.

- Requires **VC++ 2013 Redist**.
- `NPAPI` support has been removed from `Chromium`
- `FFMPEG` is now statically compiled, no more `ffmpegsumo.dll`
- Long awaited `Fullscreen` support has been added.

**Comment by coldicelion** [comment]
nice!!  thanks for your job!!
