### ISSUE TITLE
IMenuHandler rename breaking change

### ISSUE THREAD

**Issue by gigaplex** [cefsharp/CefSharp#1441]
I just upgraded from v43 to v45 of CefSharp.WinForms and noticed some breaking changes that weren't mentioned in the release notes. IMenuHandler was renamed to IContextMenuHandler (with interface changes), and ILifeSpanHandler had an additional method added to the interface. Both required source changes in our project to accommodate. Please update the release notes. Also, a list of breaking changes should feature more prominently in the front page readme, and the readme in the NuGet packages.

**Comment by amaitland** [comment]
> IMenuHandler was renamed to IContextMenuHandler (with interface changes),

This change was made prior to the `43.0.0` release.

https://github.com/cefsharp/CefSharp/commit/29e6bc7571b1f591a950eacb8bbdea4c1258abba

> Also, a list of breaking changes should feature more prominently in the front page readme, and the readme in the NuGet packages.

In general the idea makes sense, I'm just not sure if there is a practical way to implement your suggestion without copy and pasting blocks of text around, keeping that in sync isn't exactly my idea of fun. I'm open to other suggestions if you have any :+1:

**Comment by gigaplex** [comment]
Odd, the copy of 43 that I have must be pre-release then. I'll have to query the developer that originally implemented the integration on this.

As for the copy/pasting, I don't think that should be too much of an issue. I'd be happy with a centralised list of breaking changes that everything links to.

**Comment by amaitland** [comment]
> Odd, the copy of 43 that I have must be pre-release then. I'll have to query the developer that originally implemented the integration on this.

From the commit you can see which tags the change appears in are: `v45.0.0 v45.0.0-pre01 v43.0.1 v43.0.0 v43.0.0-pre02 v43.0.0-pre01`, so the change appears in the first official `-pre` release of version `43`. Not that it really matters.

> As for the copy/pasting, I don't think that should be too much of an issue.

As the sole person creating the releases, I'm less than enthused about adding another manual step to the release process.

Breaking changes are generally included in the `Change Log`. I'm all for adding a more wording about where to find them. Anyone can edit the `Wiki` or you can submit a `PR` with your proposed changes to the `Nuget\Readme.txt` file.

https://github.com/cefsharp/CefSharp/blob/master/NuGet/Readme.txt

It's likely that each release will have at least a handful of breaking changes, we're very much at the mercy of the `upstream` `CEF` project and it changes frequently as does `Chromium`. Adding new methods to an interface wasn't something I previously considered a breaking change, I just rely on `Resharper` to say methods are missing and let it implement the stubs. I guess not everyone works this way. Thanks for the feedback :+1:

**Comment by wdch-nseeley** [comment]
Thank you for the information! I was perplexed about what happened to IMenuHandler. Now I know how to complete my upgrade.

**Comment by amaitland** [comment]
Added a note to `CefSharp 43 Wiki` entry.

https://github.com/cefsharp/CefSharp/wiki/CefSharp-43/_compare/bafd566bf6ad1fa624d6fc618aa2eac50de9cf8e...4d263d3879136247a0deef660d3cc0ad93f26e9e
