### ISSUE TITLE
Is there any way to kill Cefsharp.BrowserSubProcess.exe in task manager?

### ISSUE THREAD

**Issue by coldicelion** [cefsharp/CefSharp#1445]
hi, i have some reason to  open my application twice, but every time when i closed my application, i can always found some Cefsharp.BrowserSubProcess.exe in the task manager, is there any way to kill current application's Cefsharp.BrowserSubProcess.exe process when it closing? just like to send some quite messsage to the process,  thanks a lot ! 

![ff887d306c2f431fbc17dc85f197e5dccf473b62a09e69d9ef pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/6093582/11437500/317ce08a-9529-11e5-8313-ba68c6ebcf9e.jpg)

**Comment by amaitland** [comment]
What version are you using? How are you exiting your application?

**Comment by coldicelion** [comment]
i used the cefsharp 43 2357 release version, i exit my application like the normal way, click the X button on the window.

**Comment by amaitland** [comment]
Something is stopping the clean shutdown. What features do you use? Do you keep any references to any callbacks, `IBrowser` instances or `IBrowserHost` instances?

You may need to explicitly call `Cef.Shutdown` in your case. It needs to be called on your main application thread. (Typically the `UI` thread).

**Comment by amaitland** [comment]
Also if you haven't already upgraded to the `43.0.1` release then there are a lot of bug fixes.

**Comment by coldicelion** [comment]
oh i see, i haven't use the new version of 43.0.1, may be its the reason for my process can not be killed, i'll try it, thanks a lot !!

**Comment by amaitland** [comment]
@coldicelion Any follow up on this?

**Comment by blgnklc** [comment]
I use version 47. but this is the same situation. What can I call when I close the tab ?

**Comment by okatip1** [comment]
I'm using version 47 and have same problem. When i close the tab, the process didnt kill

**Comment by amaitland** [comment]
At what point are you both calling `Dispose` on the `ChromiumWebBrowser` instances.

You need to provide background information as each flavor is different, are you using `WinForms` or `WPF`?

> Do you keep any references to any callbacks, IBrowser instances or IBrowserHost instances?

Answer this question also.

**Comment by okatip1** [comment]
I'm using Wpf. I tried the BrowserTabView --> Unloaded event.

        private void UserControl_Unloaded(object sender, RoutedEventArgs e)
        {
            browser.Dispose();
        }

It is closing the BrowserSubProcess but it is very slow, approximately 3 - 4 seconds pass while disposing the browser.

**Comment by okatip1** [comment]
Ohh my fault. Thank you sir @amaitland 
before My js executed, I tried to close the window. It is my fault. It is runing and closing the exe properly.

**Comment by nguyenducgiap** [comment]
can you use:
this.Invoke(new Action(() =>
                    {
                        panel4.Controls.Clear();
                        ChromeBrower_last.Dispose();
                    }));

will solve all your problems!
