### ISSUE TITLE
Can I use CefSharp just for rendering SVGs?

### ISSUE THREAD

**Issue by EnCey** [cefsharp/CefSharp#1448]
Hi,
I'm looking for a way to convert complex SVG documents (external images and fonts, transparency, filters, ...) to PNG images. There is no .NET library I know of that supports all that. 

I started to look into screenshot services that use a browser to render a website. Transparency is a deal breaker here (the background color, white by default, shines through – I need a transparent PNG as a result).

I don't really need full browser capabilities, only the rendering library / engine. 
Does CefSharp expose these libraries? 
Or would the only way to render an image be to run the browser engine and point the browser at a SVG document and then snag the rendered image from memory? 

Apologize if this is the wrong place to ask!

**Comment by amaitland** [comment]
> Or would the only way to render an image be to run the browser engine and point the browser at a SVG document and then snag the rendered image from memory?

You can use the `OffScreen` project and access the rendered image. The default for the `OffScreen` project is a bitmap, so you might need to create another layer of abstraction.

http://magpcss.org/ceforum/apidocs3/projects/%28default%29/CefRenderHandler.html#OnPaint%28CefRefPtr%3CCefBrowser%3E,PaintElementType,constRectList&,constvoid*,int,int%29

> |buffer| will be |width|*|height|*4 bytes in size and represents a BGRA image with an upper-left origin. 

The output buffer is `BGRA`, so you can `PNG`  should be possible.

Your request is a little unusual and as such I cannot provide you with any definitive answers, so you'll have to investigate more on your own.

**Comment by amaitland** [comment]
@EnCey Any followup on this?

**Comment by EnCey** [comment]
Sorry, got side-tracked. Your answer already helped me a lot, but I'll look into using the underlying libraries themselves and if that doesn't work give the `OffScreen` project a try. 
Thank you for your help!
