### ISSUE TITLE
How do you use OnResourceResponse

### ISSUE THREAD

**Issue by elijahgagne** [cefsharp/CefSharp#1449]
I am working off of [CefSharp.Wpf.Example](https://github.com/cefsharp/CefSharp/tree/master/CefSharp.Wpf.Example). In the View, I am binding the ChromiumWebBrowser's Address to a property in the ViewModel. When the Address is set, I look at the webBrowser object, if not null. Using the webBrowser, I can get the page's source:
```c#
var source = Task.Run(async () => await _webBrowser.GetSourceAsync()).Result;
```
I would also like to get the response headers. It appears that [OnResourceResponse](https://github.com/cefsharp/CefSharp/pull/1300/files#diff-aaf166e702850ed55270d9b58e2c3aa6R188) will do what I need, but I have not figured out how to use it. Can someone provide an example or pointer on how to use OnResourceResponse?

**Comment by amaitland** [comment]
So you can access the response headers in `OnResponseResponse`, through the `response.ResponseHeaders` property.

https://github.com/cefsharp/CefSharp/pull/1300/files#diff-aaf166e702850ed55270d9b58e2c3aa6R188

Think of it like an event that gets called for **every** resource that's loaded. So you'll have to identify the main response.

**Comment by elijahgagne** [comment]
Thank you amaitland, I have figured it out. I took the example [RequestHandler.cs](https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/RequestHandler.cs) and updated the OnResourceResponse function to suit my needs. 

Then in the code-behind I set the RequestHandler like so:

```c#
public partial class MainView : UserControl
{
    public MainView()
    {
        InitializeComponent();
        ChromiumWebBrowser.RequestHandler = new RequestHandler();
    }
}
```
