### ISSUE TITLE
Is mono supported?

### ISSUE THREAD

**Issue by donnyv** [cefsharp/CefSharp#1450]
I'd like to use this as a cross platform UI but couldn't find if it's supported on Mono. I hope it is because its waaaaay easier to setup then CefGlue.

**Comment by jankurianski** [comment]
Here's a similar question asked a couple of weeks ago, with reference to CoreCLR, but the principle is the same:
https://github.com/cefsharp/CefSharp/issues/1435

**Comment by donnyv** [comment]
Boooo, it seems CefGlue isn't supported anymore on Linux. Maybe you guy's could take it on? :-)
https://bitbucket.org/xilium/xilium.cefglue/issues/108/linux-support

**Comment by amaitland** [comment]
> Maybe you guy's could take it on? :-)

Not possible. `CefSharp` uses `Visual C++` to compile it's mixed mode `native/.Net` library, so `Windows` only.

Maybe give `ChromiumFx` a try?

https://bitbucket.org/chromiumfx/chromiumfx/issues/9/mono-support
