### ISSUE TITLE
Browser initializes too quickly

### ISSUE THREAD

**Issue by wdch-nseeley** [cefsharp/CefSharp#1451]
I've used CefSharp up through 41, now trying an upgrade to 43.

My app uses a model-view architecture. Before the view can be tied into the model, the browser has already initialized and JavaScript objects can no longer be registered. The speed is nice, but this breaks the app architecture in a significant way.

The first browser instance is slow enough, but the second on upwards initialize too quickly.

I need a way to defer browser readiness until I'm ready!

A work-around would be appreciated.  Otherwise I'm looking at re-architecting in a view-centric way.

**Comment by amaitland** [comment]
It's a known problem, see #1287 The best solution would be for someone to implement #602

> A work-around would be appreciated.

Nobody has come up with one as yet that I'm aware of. Might be best to see if anyone else as part of #1287 has come up with a solution.

**Comment by wdch-nseeley** [comment]
Hmm, I missed that issue during my search.

Anyways, it seems I've already worked around the problem.  My upgrade is complete.  Next comes 45.  :)

My JS Object is implemented as a mass of UI synchronized events (for every exposed method), so I just register that object within the browser's constructor. Then I assign the event handlers whenever my molasses MV framework gets its game on.

Thanks for your trouble.
