### ISSUE TITLE
Bound object is not defined after some script is executed using ExecuteScriptAsync

### ISSUE THREAD

**Issue by DominikPalo** [cefsharp/CefSharp#1452]
I have bounded C# object to the webpage using `RegisterJsObject`. Until I execute some script using `ExecuteScriptAsync`, it works fine and `bound` is accessible in global JS scope. But after any script is executed (e.g. simple console.log), `bound` is no more accessible - it is "not defined". 

Library version: CefSharp.Wpf 45.0.0-pre01

Simplified examle to replicate my problem:

My chromium control in WPF window:
```
 <cefSharp:ChromiumWebBrowser x:Name="browser" WebBrowser="{Binding WebBrowser, Mode=OneWayToSource}"  Address="http://google.com" />
```

MyWindow.xaml.cs:
```
    public partial class MyWindow : Window
    {
        public MyWindow()
        {
            InitializeComponent();

            var bound = (DataContext as MyWindowViewModel).Bound;
            browser.RegisterJsObject("bound", bound);
        }
    }
```

MyWindowViewModel:
```
using CefSharp;
using CefSharp.Wpf;
using SlidesDrive.Core.ViewModel;
using System;
using System.IO;
using System.Reflection;

namespace MyApp
{
    public class MyWindowViewModel
    {
        private ChromiumWebBrowser _webBrowser;

        public MyWindowViewModel()
        {
            Bound = new BoundObject();
        }

        public WebBrowser WebBrowser
        {
            get { return _webBrowser; }
            set { _webBrowser = value; if (_webBrowser != null) OnBrowserCreated(); }
        }

        public BoundObject Bound
        {
            get; private set;
        }

        private void OnBrowserCreated()
        {
                WebBrowser.ExecuteScriptAsync("console.log('Hello');"); //if this line is commented out, bound is accessible from JavaScript...
         }

    }

    public class BoundObject
    {
        //Bound object body
    }
}
```

**Comment by amaitland** [comment]
> Library version: CefSharp.Wpf 45.0.0-pre01

Does the problem reproduce using the official `45.0.0` release?

> private void OnBrowserCreated() { WebBrowser.ExecuteScriptAsync("console.log('Hello');"); //if this line is commented out, bound is accessible from JavaScript... }

I'd be very surprised if the javascript context had been created at this point. You need to wait for the page to have finished loading before executing `javascript`.

Use either `LoadingStateChanged` or `FrameLoadEnd` for page load notifications.

**Comment by amaitland** [comment]
#1373 may be of interest, though it's just an idea  at this stage.

**Comment by DominikPalo** [comment]
Thanks, moving the `ExecuteScriptAsync` call to the handler of `FrameLoadEnd` solved my problem. But it would be nice to throw an exception if `FrameLoadEnd` is called on not completely loaded page instead of destroying the `bound`JS object without notification.

**Comment by amaitland** [comment]
> But it would be nice to throw an exception if FrameLoadEnd is called on not completely loaded page instead of destroying the boundJS object without notification.

`ExecuteScriptAsync` is just a wrapper method, around the underlying `ExecuteJavaScript` method.

https://github.com/cefsharp/CefSharp/blob/cefsharp/45/CefSharp/WebBrowserExtensions.cs#L245
https://github.com/cefsharp/CefSharp/blob/cefsharp/45/CefSharp.Core/Internals/CefFrameWrapper.cpp#L172

It's not particularly easy to implement any sort of checking in this case.

**Comment by amaitland** [comment]
> destroying the boundJS object without notification.

It's unlikely `destryoing`, more likely an exception occurs in the `Render` process (where javascript is executed) and that exception means the `V8` objects are never registered.
