### ISSUE TITLE
Enable Widevine CDM enabled by default?

### ISSUE THREAD

**Issue by Star-Q** [cefsharp/CefSharp#1453]
I was surfing on the web and found that now some streams use Widevine CDM to protect their streams but streams on Twitch.tv won't work. It's just a black frame with nothing playing, no sound. In CefSharp `41` streams on Twitch.tv would work but after CefSharp `43` it changed. I saw that in CefSharp `45` they've added Widevine CDM support but how can I use this or enable it?

**Comment by amaitland** [comment]
> I was surfing on the web and found that now some streams use Widevine CDM to protect their streams but streams on Twitch.tv won't work.

Unless something has changed `twitch.tv` uses `Flash`. Either install `Pepper Flash` or enable `NPAPI` to use your existing flash. With version `45. `NPAPI` support has been removed, so you must use `Pepper Flash`.

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.Example/CefExample.cs#L54

A quick google for `twitch.tv html 5 stream` brings up https://discuss.dev.twitch.tv/t/html5-embedded-player/150/3

> Widevine CDM support

Is only used for `HTML5` based streams. See https://bitbucket.org/chromiumembedded/cef/issues/1631/add-support-for-widevine-cdm for some more background information.

**Comment by Star-Q** [comment]
And how may I enable 'Pepper Flash' inside of CefSharp '45'?

**Comment by amaitland** [comment]
> And how may I enable 'Pepper Flash' inside of CefSharp '45'?

It's enabled by default

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/CefSettings.h#L33

You need to install `Pepper Flash`. See https://bitbucket.org/chromiumembedded/cef/issues/1586/add-pepper-flash-plugin-support#comment-16898332 for details

**Comment by Star-Q** [comment]
So if the user doesn't have `Pepper Flash` installed they won't be able to watch the streams on Twitch or will I have to provide the installation of `Pepper Flash` within the installer?

**Comment by amaitland** [comment]
> So if the user doesn't have Pepper Flash installed they won't be able to watch the streams on Twitch or will I have to provide the installation of Pepper Flash within the installer?

I'm not really sure that's an **or**.

If the system wide `Pepper Flash` is installed, then it will be used. If not then you need to install it as per the link I provided above.

**Comment by Star-Q** [comment]
An install of `Pepper Flash` seemed to fix the issue with Twitch thanks! I'm still confused about if the user doesn't have `Pepper Flash` will I have to include an install of `Pepper Flash` within the `installer`.

**Comment by amaitland** [comment]
> I'm still confused about if the user doesn't have Pepper Flash will I have to include an install of Pepper Flash within the installer

What exactly is confusing?

**Comment by amaitland** [comment]
http://www.adobe.com/products/players/flash-player-distribution.html

**Comment by Star-Q** [comment]
Nevermind, I just woke up a few hours and I wasn't thinking straight.. Thank you tho
