### ISSUE TITLE
How Load page from Another BrowserForm

### ISSUE THREAD

**Issue by shirotzu** [cefsharp/CefSharp#1456]
I'm clone a BrowserForm.cs for a chat and i want Load a diferent page, because normally open custom:home.html

**Comment by shirotzu** [comment]
Any response?

**Comment by amaitland** [comment]
Stop being lazy, search through the source and work it out for yourself.

**Comment by shirotzu** [comment]
Ok

**Comment by shirotzu** [comment]
My problem is I can not transfer a value of BrowserForm to BrowserTabUserControl.

**Comment by amaitland** [comment]
Generic programming questions should be asked on `StackOverflow`.

**Comment by shirotzu** [comment]
Last ask, it is possible to transfer the code BrowserTabUserControl to BrowserForm without any error?

**Comment by shirotzu** [comment]
This yes is possible i'm done. Thanks
