### ISSUE TITLE
Are tiff images supported in Chromium?

### ISSUE THREAD

**Issue by Amal22** [cefsharp/CefSharp#1461]

**Comment by amaitland** [comment]
Not sure, let us know what you find out.

**Comment by Amal22** [comment]
I integrated a tiff image in a web page and I loaded it on Chromium => the tiff image is not rendered. Chrome Developer Tools console gives this Warning: 'Resource interpreted as Image but transferred with MIME type image/tiff'
I tried to load other image formats (exp: png, gif,...) => the image is loaded correctly on Chromium. 
I think that Chromium doesn't support tiff images.

**Comment by amaitland** [comment]
> I think that Chromium doesn't support tiff images.

Can you convert your images to another format? That seems to be the generic recommendation.

**Comment by Amal22** [comment]
Well, it's a solution for this problem.
Yes, we can convert tiff images to another format supported by Chromium.
