### ISSUE TITLE
Improving the wiki

### ISSUE THREAD

**Issue by hgupta9** [cefsharp/CefSharp#1462]
I've improved the wiki homepage to create a kind of index, grouped by use-case.

https://github.com/cefsharp/CefSharp/wiki

I'm opening this discussion to see which pages on the wiki are outdated, or can be improved / merged / deleted.

Also, are we ever going to create docs? You know the auto generated stuff like JSDoc that everyone uses? Alternatively, like [NodeJS](https://nodejs.org/api/), just use markdown to create one page per class, for the important classes. [Daux](http://daux.io/) is one such tool.

**Comment by amaitland** [comment]
You need to be careful when changing existing pages around. It's easy to break existing links. For example the `XP no longer supported page` has effectively been moved. 

The historic links no longer work e.g. https://github.com/cefsharp/CefSharp/issues/1420#issuecomment-157305687

**Comment by amaitland** [comment]
> Also, are we ever going to create docs? You know the auto generated stuff like JSDoc that everyone uses?

Plan is to use http://www.nudoq.org/, just needs some time to determine what changes are required to the `Nuget` packages.
