### ISSUE TITLE
How come everytime I browsed to index.html, the InitializeComponent() will run again?

### ISSUE THREAD

**Issue by ahgan84** [cefsharp/CefSharp#1467]
Hi guys, I'm building a Winform app to show webpage using CefSharp. It involves sending data to printer via COM port to be printed out. On the html side, user will browse through index.html (1st page), second.html (2nd page), third.html (3rd page) and on the 3rd page, info will be send to printer to be printed out. After that, it will go back to index.html (1st page) and the cycle start again. Below is my code on the C# side:

      public SerialPort PRComm = null;
      public Form1()
        {
            InitializeComponent();

            this.StartPosition = FormStartPosition.Manual;
            this.Location = new Point(0, 0);
            BrowserSettings browserSettings = new BrowserSettings();
            browser = new CefSharp.WinForms.ChromiumWebBrowser("http://192.168.1.10/index.html")
            {
                Dock = DockStyle.Fill,
            };
            this.Controls.Add(browser);
            browser.RegisterJsObject("printer", new PrintTicket());
            browser.BrowserSettings.WebSecurity = CefState.Disabled;
            browser.BrowserSettings.FileAccessFromFileUrls = CefState.Enabled;
            browser.BrowserSettings.UniversalAccessFromFileUrls = CefState.Enabled;

            if (PRComm == null)
            {
                PRComm = new SerialPort("COM1", "9600", Parity.None, 8, StopBits.One);
                try
                {
                    PRComm.DataReceived += new System.IO.Ports.SerialDataReceivedEventHandler(this.PrinterSerialPort_DataReceived);
                    PRComm.Open();
                    Console.WriteLine("Port " + _sPRComm + " opened successfully...");
                    bUnableOpenComm = false;
                }
                catch (Exception ex)
                {
                    Console.WriteLine("First try to open Port " + _sPRComm + " is failed!!");
                    Console.WriteLine(ex.ToString());
                    bUnableOpenComm = true;
                    PRComm = null;
                }
            }
        }

        public void print(string data)
        {
             // Printing function goes here and it's trigger by the 3rd webpage.
        }

Now everytime it goes to the 1st page which is index.html, it will run the code inside Form() which include the InitializeComponent() and will set PRComm to null. Is this a normal behavior?

Then if it runs Form() again, it will try to open the com port again. The PRComm had set to null but the com port is still open. It will produce "Serial Port unauthorized access exception" error because my com port is still open from my previous opening. Is it that I have to detect the time when it goes to index.html and close the com port before it try to open again? Do you know what is the best way to solve this?

If it does not run the Form() everytime it goes to index.html, I won't have such problem because the com port opens for one time only.

**Comment by amaitland** [comment]
> Now everytime it goes to the 1st page which is index.html, it will run the code inside Form() which include the InitializeComponent() and will set PRComm to null. Is this a normal behavior?

Are you sure this is related to `CefSharp`? What happens if you remove the `ChromiumWebBrowser` code? Does your problem persist.

Without seeing how your application flows, it's hard to say anything.

If you still think the problem is with `CefSharp`, then please provide a reproducible example e.g fork `MinimamExample` to demo your problem.

https://github.com/cefsharp/CefSharp.MinimalExample
