### ISSUE TITLE
HTTP2 support?

### ISSUE THREAD

**Issue by katopz** [cefsharp/CefSharp#1468]
Hi guys,

I did try search and can't find any related about CEF and HTTP/2.
So the question is is it support? This should be write on Wiki somehow?

Thanks

**Comment by amaitland** [comment]
For background see http://magpcss.org/ceforum/viewtopic.php?f=10&t=13291&p=27088&hilit=http2

Your likely better asking your question on http://magpcss.org/ceforum/

**Comment by katopz** [comment]
@amaitland Like I said I did search and there's no answer there and I'm talking about HTTP/2 not SPDY

And also I'm focusing on CefSharp not Cef. Let's say if Cef said **yes** but CefSharp said **no**. It mean **no** and I've to ask twice to get answer.

And this is yes/no question. I did expect **yes** or **no** answer.

**Comment by amaitland** [comment]
> Like I said I did search and there's no answer there and I'm talking about HTTP/2 not SPDY

It's relevant as for `Chromium` their implementation is tagged as `spdy4`

https://www.chromium.org/spdy/http2

There is a chance to use it, you have to enable it. Though not all options are supported in `CEF`.

> And also I'm focusing on CefSharp not Cef.

The relevant place to ask is on the `CEF Forum`. `CefSharp` is just a wrapper around `CEF`. If `CEF` supports it, then `CefSharp` can support it.

> And this is yes/no question. I did expect yes or no answer.

It's not the correct place to ask this question. Hence the reason I redirected you.

**Comment by katopz** [comment]
@amaitland Thanks. This should mean no at present, and yes it's possible to enable it. Sorry for bother anyway. I just hate forums ;\

**Comment by amaitland** [comment]
> I just hate forums ;\

`ceforum` is a very handy resource. The `CEF` maintainer is very helpful and will likely answer your question himself.
