### ISSUE TITLE
Basic API docs for CefSharp

### ISSUE THREAD

**Issue by hgupta9** [cefsharp/CefSharp#1470]
I'm just going to start writing some basic API docs for CefSharp. I'll do it on the Wiki, and then anyone who wants can copy it over to whatever newfangled system you like. Alternatively I could write it in the .cs files but that would be more tedious, `PR`'s and all.

So what are the main classes that needs docs?

- `ChromiumWebBrowser`

**Comment by amaitland** [comment]
> I'll do it on the Wiki,

Please don't

> Alternatively I could write it in the .cs files but that would be more tedious, PR's and all.

Having the `API` documentation inline is the preferred place. Your `WIKI` entry will be a nightmare to maintain.

> So what are the main classes that needs docs?

`ChromiumWebBrowser` it's self doesn't have documentation, the `IWebBrowser` interface, for which all three instances inherit does.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp/IWebBrowser.cs

There are tags like `inheritdoc` that exist, I'm just not totally familiar with their usage and which tools provide support.

https://github.com/cefsharp/CefSharp/blob/2153c51d156a9891cfd380554abd2a1263be4f3b/CefSharp.WinForms.Example/Handlers/KeyboardHandler.cs#L9

It would be better to investigate such.

A `PR` in this instance doesn't need to be complicated, see #1399 for an excellent example.

If your not already aware, the `CEF API` documentation is available at the follow:

http://magpcss.org/ceforum/apidocs3/index-all.html

**Comment by amaitland** [comment]
If you have time to investigate why out packages aren't showing up on http://www.nudoq.org/ that would be very much appreciated :+1:

**Comment by amaitland** [comment]
if `NuDoq` is dead (which may well be the case) then finding an alternate solution would be helpful.

**Comment by hgupta9** [comment]
@amaitland - Well what I find complicated is keeping my fork up to date. How do I do that? Since I don't know how I usually delete my fork and re-fork it. Then resync it via Github Windows. Complicated. Is there a button like "overwrite my fork with the master trunk" or something?

**Comment by amaitland** [comment]
> @amaitland - Well what I find complicated is keeping my fork up to date. How do I do that? Since I don't know how I usually delete my fork and re-fork it. Then resync it via Github Windows. Complicated. Is there a button like "overwrite my fork with the master trunk" or something?

Try something like this http://stackoverflow.com/questions/13409531/update-fork-on-github-for-windows

In general terms you'd add an `upstream` remote in `git` then you can merge changes from the `upstream` branch your targeting. 

> What I don't understand in both your dislike for wiki/md code samples and wiki docs is why you think its difficult to "maintain".

Experience with this project. Using other open source projects. It's not uncommon to find code examples that don't even compile, or reference an outdated `API`. I'd prefer to avoid this. (It's happened many times in relation to `CefSharp`.

> Does the API keep changing (names and parameters)?

It has drastically changed recently.

> I thought this wrapper was pretty static.

Where did you get that idea from? The `43.0.0` release was a major rewrite of the framework. If you compare the `41` and `43` branches, you'll see there are **771** commits. 

https://github.com/cefsharp/CefSharp/compare/cefsharp/41...cefsharp/43

The `API` was changed to better reflect the `CEF API`, though it's not `100%` complete, there are still breaking changes that need to be made.

> Why would you need to change stuff anyways?

Up until version `43` the framework didn't have the concept of frames, you could only perform tasks on the main frame. Large parts of the `API` were hidden, and much of the code was duplicated between the three different flavors. Three is still work to be done on improving and simplifying the `API`.

> CEF changes reflect downstream?

`CEF/Chromium` typically introduces breaking changes every second branch (sometimes every branch), these changes we obviously have no control over.

In general, implementing `API` docs in the `Wiki` is just way too much work. It also doesn't draw from the existing xml comments that are in place. 

Consider this scenario, someone contributes a `PR` with a breaking change, this change is accepted as it represents a simplification of the `API` and exposes some new use cases. How would you propose the `Wiki` entry is managed? Wait until the `PR` has been `merged` then kindly ask the user to edit the `Wiki`? This just doesn't seem practical and the burden this falls upon project contributors, for which there are **few**. If we were to self host `API` docs, then I'd look at having a version for each `release` branch.

> And why use stuff like NuDoq? 

`NuDoq` in theory updates every time a new release is pushed to `Nuget`. For a small project like this, automation is a **must**

> A regular documentation generator won't work?

Of course it will. An automated solution is just ideal.

> Or its a pain to keep uploading the latest HTML docs into the website?

It's an extra task, potentially an unnecessary one. If we do self host then it will need to be configured as part of the build process, so when a `Release` is tagged, the documentation is generated and uploaded.

From my perspective, this project is something I contribute to in my spare time, life is busy at the moment and only going to get busier. What time I have to contribute I'd like to be driving the project forward, not spent performing monotonous maintenance tasks. Keeping the project up to date with `CEF` requires constant work.

In general, surely there is a better way that having large blocks of code in a `md` file? Personally I'd rather have a solution of small projects that demo individual features. Just the bare bones code required to implement a specific feature.

- `Custom Scheme`
- `Simple JSB`
- etc

**Comment by amaitland** [comment]
I would also encourage you to answer a few questions on `GitHub` or `Stackoverflow`, get a sense of what the common questions are that people ask, though this you'll likely get a better understanding of the project :+1:

**Comment by amaitland** [comment]
We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Continue followup discussion there.
