### ISSUE TITLE
How execute User Scripts in CEF3 or Add Extensions

### ISSUE THREAD

**Issue by shirotzu** [cefsharp/CefSharp#1472]
I can't add user scripts how tampermonkey with Browser.ExecuteScriptAsync
It possible add user scripts or extension's?

**Comment by rlmcneary2** [comment]
You can interact with the javascript environment two ways:
 - use the [IWebBrowser](https://github.com/cefsharp/CefSharp/blob/master/CefSharp/IWebBrowser.cs) RegisterJsObject or RegisterAsyncJsObject to pass a .Net class into the javascript environment. Once it exists javascript code can access the class's methods. See the wiki for [adding .Net classes](https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#Expose_dotNET).
 - strings of javascript code can be passed to the browser using the [IFrame](https://github.com/cefsharp/CefSharp/blob/master/CefSharp/IFrame.cs) EvaluateScriptAsync method and with a result returned once the code has finished executing. [Call a JS function and get a result](https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#CallJSWithResult).

**Comment by wan766405890** [comment]
Can Render UserControl on WebView？
