### ISSUE TITLE
why my xaml tip cefsharp.core can't load ?

### ISSUE THREAD

**Issue by wangliuzheng** [cefsharp/CefSharp#1473]
#### Issue Summary
What is the expected output? What do you see instead?

#### Steps to Reproduce
1. This is the first step

This is a bug because...
Code sample if relevant

#### Technical details
* CefSharp Version: nuget - master - latest commit:  INSERT COMMIT REF
* Operating System: 
* x86/x64: 
* WinForms/WPF/OffScreen: 

--
System.IO.FileNotFoundException
Could not load file or assembly 'CefSharp.Core, Version=45.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138' or one of its dependencies. 系统找不到指定的文件。
   在 CefSharp.Wpf.ChromiumWebBrowser.Dispose(Boolean isdisposing)
   在 CefSharp.Wpf.ChromiumWebBrowser.Finalize()

**Comment by amaitland** [comment]
@wangliuzheng Please fill in the bug report and post a comment to let us know when your done.

**Comment by amaitland** [comment]
@wangliuzheng Please provide additional information.

**Comment by wangliuzheng** [comment]
@amaitland  thanks , I had resovled it .

**Comment by Neilxzn** [comment]
How can I solve this problem？I have the same problem? plz help me. thx
