### ISSUE TITLE
Trying to improve my retry pinging of TCP port of CefSharp browser.

### ISSUE THREAD

**Issue by ahgan84** [cefsharp/CefSharp#1474]
I'm trying to load two webpage using my cefSharp winform project. The first page sure will display out because it is a local html page. The second page need to do pinging because it is a server website. I need to check whether the server ip and port can be connected first only I redirect to that page. Below is my coding:

    public Form1()
    {
        Console.WriteLine("-------Initialization------");
        InitializeComponent();

        this.StartPosition = FormStartPosition.Manual;
        this.Location = new Point(0, 0);

        BrowserSettings browserSettings = new BrowserSettings();
        Console.WriteLine(AppDomain.CurrentDomain.BaseDirectory + "html\\index.html");
        browser = new CefSharp.WinForms.ChromiumWebBrowser(AppDomain.CurrentDomain.BaseDirectory + "html\\index.html") 
        {// First page.
            Dock = DockStyle.Fill,
        };
        this.Controls.Add(browser);
        browser.BrowserSettings.WebSecurity = CefState.Disabled;
        browser.BrowserSettings.FileAccessFromFileUrls = CefState.Enabled;
        browser.BrowserSettings.UniversalAccessFromFileUrls = CefState.Enabled;

        while (true)
        {
            pSvr = PingServer(ioIP, int.Parse(ioPort));
            if (pSvr == true)
            {
                label3.Text = "Connected to server. Please wait...";
                tmr.Interval = 15000; 
                tmr.Tick += timerHandler;
                tmr.Start();
                break;
            }
            Thread.Sleep(5000);
        }
      }

    public bool PingServer(string _HostIP, int _PortNumber)
    {
        try
        {
            TcpClient client = new TcpClient(_HostIP, _PortNumber);
            Console.WriteLine("Server successfully connected...");
            return true;
        }
        catch
        {
            Console.WriteLine("Error pinging server...");
            return false;
        }
    }

    private void timerHandler(object sender, EventArgs e)
    {
        tmr.Stop();
            browser.Load("http://" + ioIP + ":" + ioPort + "/page2/?1"); // second page
    }

I use a while loop and do a thread.sleep for 5 seconds, to keep retry connect to the server if it failed.

Logically speaking, whether or not I can connect to the second page, I would want the first page to show first, and it will do retry connect to second page in the background. But when I run my code, and when it cannot connect to server, the first page won't come out. Seems like it goes into the while loop and keep retrying to connect to the second page and forget about showing the first page already. Is it the while loop got problem here? Does always showing "Error pinging server..." preventing the first page from displaying? And what do you guys think its the most suitable way for me to do retrying of connecting to server?

**Comment by amaitland** [comment]
> But when I run my code, and when it cannot connect to server, the first page won't come out. Seems like it goes into the while loop and keep retrying to connect to the second page and forget about showing the first page already.

Your executing code in the forms constructor. So your `while loop/Sleep call`will be blocking your `UI` thread. You need to wait for the first page to load.

- Subscribe to `LoadingStateChanged`
- When `IsLoading == false` spawn off a `Task/Thread` to check your server connection.

https://github.com/cefsharp/CefSharp/blob/cefsharp/45/CefSharp/IWebBrowser.cs#L54

Example of checking `IsLoading`
https://github.com/cefsharp/CefSharp/blob/cefsharp/45/CefSharp.OffScreen.Example/Program.cs#L98

> And what do you guys think its the most suitable way for me to do retrying of connecting to server?

Subscribe to the `LoadError` event and call `Load` with the same `URL`. (You can try calling `Reload()` though that sometimes doesn't work).
https://github.com/cefsharp/CefSharp/blob/cefsharp/45/CefSharp/IWebBrowser.cs#L45

**Comment by amaitland** [comment]
@ahgan84 Any followup before closing?
