### ISSUE TITLE
HTMLElement.style.width doesn't match window.getComputedStyle or element.getClientRects()

### ISSUE THREAD

**Issue by tnclark8012** [cefsharp/CefSharp#1475]
_cross post of http://stackoverflow.com/questions/34142996/htmlelement-style-width-doesnt-match-window-getcomputedstyle-or-element-getclie_

**Background**: I'm making the transition from the native WebBrowser control in WinForms to CefSharp. After the transition, I've noticed an interesting regression with a particular DOM element. This element is programmatically re-sized during page load, the later on in response to a click event on another control.

On load: element is display:none, and is sized

```
element.style.width = "5px";
```

On click of a WinForms button, the element is shown and re-sized:

```
element.style.width = "1398px";
```

**Problem**: Somehow, the element's style attribute is not reflected in the rendered HTML. The element is rendered 5px wide.

```
console.log(element.style.width); // "1398px"
console.log(element.getClientRects()[0].width) // 5
console.log(window.getComputedStyle(element))["width"]) // "5px"
console.log(element.style.cssText) // "width: 1398px; height: 24px;"
```

The only time I would expect the above to differ is if there was an !important setting of width via CSS (which is not the case here). If I toggle the element display again via the dev tools console

```
element.style.display = "none";
element.style.display = "";
```

The element is re-rendered properly at 1398px. The issue appears to be intermittent. Any ideas what's going on? Is there any reason to expect this behavior, other than a Cef bug?

**Comment by amaitland** [comment]
> Any ideas what's going on? Is there any reason to expect this behavior, other than a Cef bug?

What version are you using? Sounds like a bug. Other than `upgrading/downgrading` there isn't much that can we done in the context of `CefSharp`.

https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

Have you searched for similar issues in regards to `Chromium`? How does the same code behave when run in an equivalent version of `Google Chrome`?

**Comment by amaitland** [comment]
@tnclark8012 Any follow up on this?

**Comment by tnclark8012** [comment]
Unfortunately, I'm not able to attempt a repro in Chrome as the setup for the issue is quite complicated to setup (requires C# Chrome interop). We haven't tried up/downgradding yet. We're on v45. Sorry!

**Comment by amaitland** [comment]
> I'm not able to attempt a repro in Chrome as the setup for the issue is quite complicated (requires C# Chrome interop)

Can the basic problem be reproduced using plain `html/javascript`? Is it more than just applying style styling using a button click?

> We haven't tried up/downgradding yet.

Version `47.0.0-pre01` is out, might be worth a test if you have time. I expect the official `47.0.0` release to happen in the next two weeks.

> We're on v45

Thanks for confirming :+1:

**Comment by amaitland** [comment]
@tnclark8012 Any follow up on this?
