### ISSUE TITLE
Is there a way to determine whether a page has finish load or fail load?

### ISSUE THREAD

**Issue by ahgan84** [cefsharp/CefSharp#1476]
Hi guys, is there any option for user to know whether the website has fail to load or finish load? Previously i use electron and there's the "did-fail-load" and "did-finish-load" event to tell user the status of the webpage. What i want to do is just to check whether the url user key in is invalid or its reachable or not.

**Comment by amaitland** [comment]
See the `IWebBrowser` interface. All the relevant handlers are listed there.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp/IWebBrowser.cs#L29

**Comment by amaitland** [comment]
@ahgan84 Anything else before closing?
