### ISSUE TITLE
How to rename CefSharp.BrowserSubprocess.exe without error's

### ISSUE THREAD

**Issue by shirotzu** [cefsharp/CefSharp#1478]
I would like to rename the file CefSharp.BrowserSubprocess.exe without errors.

I change it once and did not give me mistakes but some people who needed the VC ++ can't open the browser

what would be the proper way to change the name of this.
I seen Steam since modified his will even put an icon

Sorry for my bad english.

**Comment by jankurianski** [comment]
Having bad english is OK, don't feel bad.  But if you have bad english, you cannot ask a question in this way, because I don't understand what you are asking.  You must use this guide:

https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue

**Comment by amaitland** [comment]
For those wishing to rename the subprocess, it's not possible to implement your own (call it whatever you like). See https://github.com/cefsharp/CefSharp/issues/1149#issuecomment-225547869
