### ISSUE TITLE
Proprietary Codec Support (H264, MP3)

### ISSUE THREAD

**Issue by Feko** [cefsharp/CefSharp#1479]
Hello,

I'm trying to play audio, using <audio> tag and CefSharp. No success so far.
After long searches, seems like I need ffmpegsumo.dll from the same exact version as CEF. (https://github.com/cefsharp/CefSharp/issues/444)
But, I'm using CEF 3.2526.1359, and as described here: https://codereview.chromium.org/1141703002 , CEF3 now statically links ffmpeg... What is "statically link"? What should I do to be able to play audio?

Thanks in advice!

**Comment by Feko** [comment]
Just as a test, I tried another release of CefSharp: Release 43, CEF 3.2357.1287
This time, with ffmpegsumo.dll provided by default. Same issue as described in https://github.com/cefsharp/CefSharp/issues/444 Audio controls appear, but speaker is disabled, and no sound.
Tried downloading CEF release from cefbuilds.com (3.2357.1287.g861c26e_windows32) and using those dlls... same thing. What am I doing wrong?

**Comment by amaitland** [comment]
> What is "statically link"?

The code has been compiled into the `libcef.dll`, so there is no longer a need for a separate dll.

> After long searches, seems like I need ffmpegsumo.dll from the same exact version as CEF. (#444)

Did you try the example `URL` linked in #444? It plays fine for me?

> Just as a test, I tried another release of CefSharp: Release 43, CEF 3.2357.1287

For this release you would require `ffmpegsumo.dll`

> What am I doing wrong?

Are you trying to play audio that requires a proprietary codec? e.g. `mp3`? Licensing restrictions prohibit `CEF/CefSharp` from distributing binary's that provide support.

**Comment by Feko** [comment]
Hi, thanks for your reply :)
Oh sorry, I didn't tried that example, I was working on a test page I've created.
I was trying to play MP3/M4A... After your answer, I tried OGG Vorbis on CefSharp 43 + ffmpegsumo.dll, and it worked just fine!!
But in this project, I really need support to those proprietary formats... How can I achieve that?

Thanks!

**Comment by amaitland** [comment]
> But in this project, I really need support to those proprietary formats... How can I achieve that?

Quite a lot of effort is required. See https://groups.google.com/d/msg/cefsharp/BJLMXl9c204/HMJlp8mZzF0J for a guide (little outdated).

You'd also need to look at acquiring the relevant licenses to use/distribute those codecs.

**Comment by amaitland** [comment]
We now have [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask any follow up questions there.

**Comment by qidongxi2012** [comment]
so good

**Comment by okatip1** [comment]
@amaitland Can you upload to anywhere the libcef.dll for version 47 which supports the mp3 and mp4.

**Comment by blgnklc** [comment]
@amaitland You are the king please make this happen... You are our one of hero here

**Comment by amaitland** [comment]
> @amaitland Can you upload to anywhere the libcef.dll for version 47 which supports the mp3 and mp4.

@okatip1 @blgnklc Sorry, cannot help you there.

**Comment by jankurianski** [comment]
@okatip1 @blgnklc Come on guys, this is free open-source software.  You are behaving extremely poorly. Do not ask anyone personally to do your own work.

**Comment by okatip1** [comment]
@blgnklc @amaitland 

Hi @jankurianski
I don't ask him to compile the libcef.dll for me. I ask him only, "if you have the dll already, please share with me?"

Because I researched and struglled compiling the libcef.dll including the those codes supportings, but I couldn't do this. Don't misunderstand me.

Thnx

**Comment by MalikMurtaza** [comment]
how to compile cefsharp with paid h264?
is there any sample code available or steps defined where we follow to enable the licensed codec.

**Comment by jankurianski** [comment]
With the expiration of the MP3 patent, MP3 codec support is planned to be included by default in Chromium 62.  Therefore it will make its way into CEF and eventually CefSharp (if a contributor is interested in creating a future CefSharp release against 62).

http://magpcss.org/ceforum/viewtopic.php?f=7&t=15066
https://bugs.chromium.org/p/chromium/issues/detail?id=746579

**Comment by perlun** [comment]
Intresting @jankurianski. I have started working with #2203, and can run CefSharp with CEF 62. _But_ it still claims MP3 support is not available when I check http://www.html5test.com

**Comment by jankurianski** [comment]
@perlun looks like even to build you would need to wait for https://bugs.chromium.org/p/chromium/issues/detail?id=787575 to be fixed also (linked issue from original MP3 issue).  May be easier just to wait until official build of CEF 63 rather than fork CEF and deal with all the maintenance and bug fix merging headaches.

**Comment by perlun** [comment]
@jankurianski From what I can tell, that only relates to a couple of tests; I am willing to take the risk of testing the "build your own approach" for now and see if it works. But I agree, the long-term fix is CEF 63.

**Comment by perlun** [comment]
See #2204 for those of you who cannot really wait.

**Comment by perlun** [comment]
Quoting from https://bugs.chromium.org/p/chromium/issues/detail?id=746579:

> As Chris notes in c#10, in M64+ MP4 and MP3 are available in Chromium. While the container will demux and the codec will now play, we're still sorting out the mime-type issues though so canPlayType/isTypeSupported aren't accurate.
>
> There will be no updates to M63 for this.

So, the "proper" solution for this will have to wait until CEF 64 unfortunately. I reopened this now, so we can keep track of this. The schedule for Chromium versions is as follows:

Release | Estimated Week of Stable
-- | --
63 | Dec 5th, 2017 (Dec 12th for Chrome OS)
64 | Jan 23rd, 2018 (Jan 30th for Chrome OS)

So, in a couple of months we should be able to provide the long awaited MP3 support. 🎉

**Comment by perlun** [comment]
Unfortunately, the full support for this has been delayed to Chromium/CEF 65:

> Chromium mp3 support technically exists in M64, in that if you try to play an MP3 via src="your_file.mp3" it will work. 
>
> But <audio>.canPlayType('...') will not report support for mp3 until M65. 
>
> Playback via MSE (and checking for support via isTypeSupported) will not be available in Chromium until M65.

We will ship with whatever is included in M64, believe me, but this means that the _full_ support will not be in CefSharp until 65.0.0. Given the schedule above, I would guess that it is scheduled for February sometime.

**Comment by amaitland** [comment]
`master` has been upgraded to `CEF 3.3282.1731.gfc9a4fa / Chromium 64.0.3282.119`, partial `MP3` support should be included (haven't tested personally yet)

**Comment by amaitland** [comment]
Closing this issue and using  #2322 to track MP3 support.
