### ISSUE TITLE
Include JS scripts that can be executed or evaluated.

### ISSUE THREAD

**Issue by rlmcneary2** [cefsharp/CefSharp#1482]
Over time I've written a few scripts used with EvaluateScriptAsync that seem to be requested fairly regularly by CefSharp users. Perhaps these could be included somewhere in the CefSharp repository for people to use and improve them as needed? I like the idea of having a "Scripts" directory with JS files in it but they could also be included directly in the documentation somewhere.

**Comment by amaitland** [comment]
> I like the idea of having a "Scripts" directory with JS files in it but they could also be included directly in the documentation somewhere.

What about including them in the `Example` project? Can then add a few test pages that demo the code in action

**Comment by rlmcneary2** [comment]
I've started adding some scripts to the example project (currently only invoked in Example.WinForm but the scripts themselves are in Example). The scripts are strings of javascript embedded in the C# code and formatted to be more easily read; not how I do it in our code but probably better for example purposes.

I'm also planning to show how asynchronous "events" can be returned through the use of a class with an "onevent" method that is registered with the browser then invoked by executing / evaluating a code block that reacts to something, say changes in the DOM (like adding or removing elements).

**Comment by amaitland** [comment]
> I'm also planning to show how asynchronous "events" can be returned through the use of a class with an "onevent" method that is registered with the browser then invoked by executing / evaluating a code block that reacts to something, say changes in the DOM (like adding or removing elements).

Excellent thanks :+1:
