### ISSUE TITLE
Feature Request - Update ChromeWidgetMessageInterceptor Example

### ISSUE THREAD

**Issue by nerodark** [cefsharp/CefSharp#1484]
This is it: i have setup a c# winforms project after upgrading to v45 from v43.0.1 in nuget.
I have implemented a few months ago "ChromeWidgetMessageInterceptor.SetupLoop" to intercept window message of CEF, it was working fine until i upgrade. The setup loop still works great for WM_LBUTTONDOWN, WM_RBUTTONDOWN, all other mouse events except WM_MOUSEWHEEL (0x20A). As i say it was working fine (i didnt change anything just upgraded)..

Anybody have a hint on this one? thanks

**Comment by amaitland** [comment]
Likely something has changed in `Chromium` it's self. You'd need to use something like `Spy++` to see what's changed. At a guess they've likely restructured some of the handles.

**Comment by amaitland** [comment]
Currently the default is to use the `MultiThreadedMessage` loop option that `CEF` provides, for which the message pump is run in it's own thread. If you change to calling `Cef.DoMessageLoopWork` manually and `MultiThreadedMessageLoop = false`, you may be able to hook the calls using the handle exposed by the `ChromiumWebBrowser` instance.

I haven't tried this with mouse events, it works for other things. I added a basic working example with commit https://github.com/cefsharp/CefSharp/commit/fe11f2eada542f49e4eef0feed9b2b0978446bbf

**Comment by nerodark** [comment]
Hi,

I spied on the windows and I ended up with looping on another handle "Chrome_WidgetWin_0" using this code :

        public static bool TryFindWidgetHostHandle(ChromiumWebBrowser browser, out IntPtr chromeWidgetHostHandle)
        {
            var browserHandle = browser.Handle;
            var windowHandleInfo = new ChromeWidgetHandleFinder(browserHandle);
            const string chromeWidgetHostClassName = "Chrome_RenderWidgetHostHWND";
            chromeWidgetHostHandle = windowHandleInfo.FindDescendantByClassName(chromeWidgetHostClassName);
            return chromeWidgetHostHandle != IntPtr.Zero;
        }

        public static bool TryFindWidgetWinHandle(ChromiumWebBrowser browser, out IntPtr chromeWidgetWinHandle)
        {
            var browserHandle = browser.Handle;
            var windowHandleInfo = new ChromeWidgetHandleFinder(browserHandle);
            const string chromeWidgetWinClassName = "Chrome_WidgetWin_0";
            chromeWidgetWinHandle = windowHandleInfo.FindDescendantByClassName(chromeWidgetWinClassName);
            return chromeWidgetWinHandle != IntPtr.Zero;
        }

and the SetupLoop looks like this : 

                            IntPtr chromeWidgetHostHandle, chromeWidgetWinHandle;

                            if (ChromeWidgetHandleFinder.TryFindWidgetHostHandle(browser, out chromeWidgetHostHandle))
                            {
                                foundWidget = true;
                                new ChromeWidgetMessageInterceptor(browser, chromeWidgetHostHandle, forwardAction);

                                if (ChromeWidgetHandleFinder.TryFindWidgetWinHandle(browser, out chromeWidgetWinHandle))
                                {
                                    new ChromeWidgetMessageInterceptor(browser, chromeWidgetWinHandle, forwardAction);
                                }
                            }

and everything works fine. WM_MOUSEWHEEL is sent to this new handle

**Comment by amaitland** [comment]
> and everything works fine. WM_MOUSEWHEEL is sent to this new handle

Great, sounds like you have it well in hand :+1:  At some point we should update the example.

**Comment by amaitland** [comment]
Everything appears to be working as expected with `47.0.2`, so closing this now.
