### ISSUE TITLE
CefSharp 45.0.0, WPF, PDF - screen update.

### ISSUE THREAD

**Issue by AlexMakap** [cefsharp/CefSharp#1485]
Hi! 
I'm upgrade our WPF project from 43.0.1 to 45.0.0.
I have trouble with pdf rendering. After loading pdf  the CefSharp control not dispalyed content. If i change  window size - content updated. Scrolling also not refresh control content.
CefSharpWPFExample rendered pdf true.
What changed in CefSharp from 41 to 45 in this context?

**Comment by MarcusSpecht** [comment]
I am having the same problem.

**Comment by amaitland** [comment]
You need to use the `disable-surfaces` command line argument, there's a helper function. See https://github.com/cefsharp/CefSharp/blob/cefsharp/45/CefSharp.Example/CefExample.cs#L85 for an example.

**Comment by AlexMakap** [comment]
@amaitland Thank You!

**Comment by AlexMakap** [comment]
@amaitland is not very clear how this works in the example, because the option disable-surfaсes is off.

**Comment by amaitland** [comment]
The examples uses `settings.EnableInternalPdfViewerOffScreen();`.

https://github.com/cefsharp/CefSharp/blob/cefsharp/45/CefSharp.Example/CefExample.cs#L85
https://github.com/cefsharp/CefSharp/blob/cefsharp/45/CefSharp.Core/CefSettings.h#L264

**Comment by AlexMakap** [comment]
I'm understood, thank you!

**Comment by AlexMakap** [comment]
I understood thanks, and what will disable surface

**Comment by amaitland** [comment]
https://bitbucket.org/chromiumembedded/cef/issues/1689 contains background information.

This should eventually be fixed in `CEF`.

**Comment by AlexMakap** [comment]
Ok!
