### ISSUE TITLE
Reference proglems using nuget (VS2013, VB.Net)

### ISSUE THREAD

**Issue by MrM40** [cefsharp/CefSharp#1487]
When installing cefsharp using nuget all the references (also the the native .net references) are corrupted!
![cef_1](https://cloud.githubusercontent.com/assets/16258063/11750324/0cf00fde-a033-11e5-8562-9d0813893e10.jpg)

![cef_2](https://cloud.githubusercontent.com/assets/16258063/11750323/0cef8b36-a033-11e5-9134-4c45b384946c.jpg)

-Yes, did set my solution to X86, restart, and then install cefsharp using nuget
-Yes, I have  installed Visual C++ Redistributable...2013
-Yes, I am able to run the minimal example of cefsharp
-I am able to install cefsharp manually (manually copying files and manually make the references).
Altough it didn't get the browser to work, but that's another story. At least all the references was OK.

But the nuget package seem to not doing the installation very well. At least not on VS2013 (v5), VB.NET  x86 project :-(

**Comment by amaitland** [comment]
> Yes, I have installed Visual C++ Redistributable...2013

What version are you using exactly?

> But the nuget package seem to not doing the installation very well. At least not on VS2013 (v5), VB.NET x86 project :-(

Do you have the latest version of `Nuget` installed? It's probably worth clearing your `Nuget cache`, then trying to re-download the package.

**Comment by MrM40** [comment]
> What version are you using exactly?

12.0.30501

> Do you have the latest version of Nuget installed? It's probably worth clearing your Nuget cache, then trying to re-download the package.

NuGet Package Manager   2.8.60610.756

Clearing the Nuget cache didn't help, same result.

**Comment by amaitland** [comment]
Looking at your screenshot again, it says your Platform is still `Any CPU`, you'll need to change that to `x86`. The `Configuration Manager` should look something like the follow

![configuration-manager](https://cloud.githubusercontent.com/assets/307872/11859943/83c708d8-a4bb-11e5-9e90-7561b2b0f5ee.PNG)

Quick test and I can install the `Nuget` packages for `45.0.0` in `VB.Net` using `VS2013`

![vb net-vs2013](https://cloud.githubusercontent.com/assets/307872/11859921/5a33fe86-a4bb-11e5-9ca3-7a6074cf7ba8.PNG)

**Comment by MrM40** [comment]
Sorry to ask, where do I find this "Configuration Manager" in VS 2013?
Could it be the same as this one:
![pic1](https://cloud.githubusercontent.com/assets/16258063/11865167/99b45d4e-a4a2-11e5-9d1e-e021046d3646.jpg)

**Comment by MrM40** [comment]
Ahh....found it! :-P
![pic2](https://cloud.githubusercontent.com/assets/16258063/11865272/43e6effc-a4a3-11e5-9704-ff46499ebc91.jpg)
