### ISSUE TITLE
Using CefSharp 3 with an AppDomain

### ISSUE THREAD

**Issue by mgenovese** [cefsharp/CefSharp#1488]
Has anyone found a way to use CefSharp 3 in a C# WinForms process created inside a new AppDomain?  I have been searching for several days and have not found a definitive answer.  This is a deal breaker for my project so any help or direction would be appreciated.

**Comment by amaitland** [comment]
See #351 for the backaground. It's currently not possible out of the box and is unlikely to be resolved as it would require rewriting the framework effectively. There is one possible workaround which is outlined in https://github.com/cefsharp/CefSharp/issues/351#issuecomment-71495187

Also it's probably worth checking out one of the other `CEF` based frameworks that uses `P/Invoke`. See https://github.com/cefsharp/CefSharp#links for their links.

**Comment by mgenovese** [comment]
Thanks Alex for you quick reply.  I have done some research of the CefGlue framework.  It looks like it will be something that will solve our problem.  The hardest part was getting the correct version of the CEF binaries (or else CefGlue will not work).  Thanks for your help.
