### ISSUE TITLE
Not works OnBeforeDownload

### ISSUE THREAD

**Issue by monobogdan** [cefsharp/CefSharp#1489]
I implement interface but method onbeforedownload not works

```
    public class DownloadHandler : IDownloadHandler
        {
               Downloads dwn = new Downloads();
               string sfn, url;
               int percent;
           
          public  void OnBeforeDownload(IBrowser browser, DownloadItem downloadItem, IBeforeDownloadCallback callback)
            {
             
                    dwn.listBox1.Items.Add("Начата загрузка");
                    dwn.Show();
                
            }

         public void OnDownloadUpdated(IBrowser browser, DownloadItem downloadItem, IDownloadItemCallback callback)
            {
                sfn = downloadItem.SuggestedFileName;
                url = downloadItem.Url;
                percent = downloadItem.PercentComplete;
                dwn.Invoke(new MethodInvoker(delegate
                {
                    dwn.listBox1.Items[downloadItem.Id] = (downloadItem.SuggestedFileName + " URL: " + downloadItem.Url + " " + downloadItem.PercentComplete + "%");
                }));
            }
        }
```

**Comment by amaitland** [comment]
What version are you using? Did you assign a new instance of `DownloadHandler` to the `ChromiumWebBrowser` instance?

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.WinForms.Example/BrowserTabUserControl.cs#L35

Does the problem reproduce using one of the `Example` projects?

**Comment by monobogdan** [comment]
Example projects not compilings.I use last verison.Compile with VC#2010 express.If i try change void to bool then compilation error

14.12.2015, 04:03, "Alex Maitland" <notifications@github.com>:

**Comment by monobogdan** [comment]
Works OnDownloadUpdate but OnBeforeDownload not works

14.12.2015, 04:03, "Alex Maitland" <notifications@github.com>:

**Comment by amaitland** [comment]
> Compile with VC#2010 express.

You need at least `VS2012` to compile version `43` and `VS2013` to compile newer versions.

> Works OnDownloadUpdate but OnBeforeDownload not works

Is it just one single `URL` you've tried?

> What version are you using?

Again, what version are you using?

**Comment by monobogdan** [comment]
2012?Hm.In 2012 updated syntax?Okay.I download new version.And test it.Thanks :)

14.12.2015, 10:10, "Alex Maitland" <notifications@github.com>:

**Comment by amaitland** [comment]
Development is done using `Visual Studio 2013 Community edition`, so that's probably the best version to download.

**Comment by monobogdan** [comment]
I use 2012.

15.12.2015, 03:41, "Alex Maitland" <notifications@github.com>:

**Comment by amaitland** [comment]
For newer versions like `45.0.0` support for building with `VS2012` has been removed. You can still build the `cefsharp/43` branch with `VS2012` though.

**Comment by monobogdan** [comment]
On my notebook 2015 lags.May be install 2013 community?

17.12.2015, 01:05, "Alex Maitland" <notifications@github.com>:

**Comment by amaitland** [comment]
> May be install 2013 community?

`VS 2013 Community` is a valid option. (It's the version I use mainly).

**Comment by amaitland** [comment]
@monobogdan Any follow up on this?

**Comment by amaitland** [comment]
Closing due to lack of feedback.

We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask any follow up questions there.

**Comment by ShubhamRout-mitel** [comment]
Hi @amaitland , can you please help me? The OnBeforeDownload event is not being triggered sometimes. It's highly intermittent. I've observed this issue on CefSharp version 129. I encountered this issue once, and after that, once the OnBeforeDownload event stops being called, it doesn't get triggered again until the client is restarted.
