### ISSUE TITLE
Supported OS

### ISSUE THREAD

**Issue by yahorby** [cefsharp/CefSharp#1490]
Hello.

Our company is looking for a suitable Web Browser control to be integrated into our .NET WPF application. What versions of the MS Windows are supported by your WebBrowser (in particular, does it work under Windows XP/Vista)?

Looking forward to your reply.

**Comment by rover886** [comment]
>What versions of the MS Windows are supported by your WebBrowser

`CefSharp` is completely customizable application. You can build **Your** own flavoring browser application over the `CefSharp.  :smile:

@yahorby welcome to `CefSharp`, before starting for anything please have a look on [FAQ](https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions).

As per FAQ, Windows XP is no longer supported, as `nuget` packages are not compatible but you can try to re-compiling from `CefSharp` source code. There are some success story available which are able to run `CefSharp`  on XP-2k3 OS. 

Do not post issue related on Windows XP, Please have look on this https://github.com/cefsharp/CefSharp/wiki/Windows-XP-No-Longer-Supported and search on Google will help you to build it.

**Comment by amaitland** [comment]
> As per FAQ, Windows XP is no longer supported, as nuget packages are not compatible but you can try to re-compiling from CefSharp source code. There are some success story available which are able to run CefSharp on XP-2k3 OS.

With newer versions this may not be strictly required. See https://github.com/cefsharp/CefSharp/issues/849#issuecomment-164448989

`45.0.0` and newer (when there is a newer) target `VC++2013`, so the packages may just work out of the box.

The If you need help with `Windows XP`, then your best bet is to ask someone who's got it working successfully.

**Comment by perlun** [comment]
See #1491 also - I have successfully used this version at least on Windows Server 2003 R2. But like @amaitland states, it's quite likely that v45.0 will work OOTB also.

**Comment by amaitland** [comment]
@yahorby Any further questions?
