### ISSUE TITLE
Active WPF window with ChromiumWebBrowser doesn't handle Window.InputBindings

### ISSUE THREAD

**Issue by DominikPalo** [cefsharp/CefSharp#1493]
I have a window with only one control - ChromiumWebBrowser. Problem is that after window is opened (and is active/has focus), keys defined in `Window.InputBindings` are not handled, until I click somewehere into the area of chromium control. After first-click, keys starts to work. It looks like a bug. I'm also tried to move my key handlers into `ChromiumWebBrowser.InputBindings`, but still same problem.

Example:

```
<Window x:Class="WebWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:cefSharp="clr-namespace:CefSharp.Wpf;assembly=CefSharp.Wpf"
        DataContext="{Binding WebWindow, Source={StaticResource Locator}}">

    <Window.InputBindings>
        <KeyBinding Key="Escape" Command="{Binding Path=HideCommand}" />
        <KeyBinding Key="F5" Command="{Binding RefreshCommand}" />
    </Window.InputBindings>
    <cefSharp:ChromiumWebBrowser
            x:Name="browser" Address="{Binding Address, Mode=TwoWay}" 
            Title="{Binding Title, Mode=OneWayToSource}"
            WebBrowser="{Binding WebBrowser, Mode=OneWayToSource}" />
</Window>
```

Version: 45.0.0

**Comment by amaitland** [comment]
Keyboard handling is done with two parts, see below:

https://github.com/cefsharp/CefSharp/blob/cefsharp/45/CefSharp.Wpf/ChromiumWebBrowser.cs#L959
https://github.com/cefsharp/CefSharp/blob/cefsharp/45/CefSharp.Wpf/ChromiumWebBrowser.cs#L1089

**Comment by DominikPalo** [comment]
How can mentioned code helps me? I only need to enable routing of key press events to the WPF control instantly after webbrowser is rendered in window, instead of after first click into browser area - bacause it seems, that unfocused ChromiumWebBrowser control consumes these key events and don't allow to handle these events by parent control/window.

**Comment by amaitland** [comment]
> How can mentioned code helps me?

So you can debug the problem for yourself?

**Comment by amaitland** [comment]
Tried to reproduce this problem, it appears to be working fine.

Demo is available at https://github.com/cefsharp/CefSharp.MinimalExample/blob/demo/1493/CefSharp.MinimalExample.Wpf/MainWindow.xaml

**Comment by amaitland** [comment]
We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask any follow up questions there.
