### ISSUE TITLE
Unhandled "Cannot access a disposed object" exceptions occurs randomly

### ISSUE THREAD

**Issue by DominikPalo** [cefsharp/CefSharp#1494]
I'm using CefSharp (v45.0.0) in WPF app (WPF Chromium control) and my app sometimes crashes with an exception "Cannot access a disposed object". It happens during creating (opening) a new WPF window with the Chromium control.

```
"Cannot access a disposed object.
Object name: 'CefSharp.Internals.BrowserProcessServiceHost'.    
at System.ServiceModel.Dispatcher.ChannelDispatcherCollection.InsertItem(Int32 index, ChannelDispatcherBase item)   
at System.Collections.Generic.SynchronizedCollection`1.Add(T item)   
at System.ServiceModel.Description.DispatcherBuilder.InitializeServiceHost(ServiceDescription description, ServiceHostBase serviceHost)   
at System.ServiceModel.ServiceHostBase.InitializeRuntime()   
at System.ServiceModel.ServiceHostBase.OnBeginOpen()   
at System.ServiceModel.ServiceHostBase.OnOpen(TimeSpan timeout)   
at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)   
at CefSharp.ManagedCefBrowserAdapter.OnAfterBrowserCreated(Int32 browserId)   
at CefSharp.Internals.ClientAdapter.OnAfterCreated(ClientAdapter* , CefRefPtr<CefBrowser>* browser)"
```

**Comment by amaitland** [comment]
What other information can you provide? What does your code look like? Anything you might be doing slightly out of the ordinary? Ideally we need a way to reproduce the problem.

Do you use `RegisterJsObject`? If not you can disable the `WCF` service and get around the problem.

**Comment by DominikPalo** [comment]
Yes, I'm using `RegisterJsObject` in the constructor of this window (and in 99% of attempts it works without any problem):

        public ChatWindow()
        {
            InitializeComponent();
            Owner = Application.Current.MainWindow;

            Messenger.Default.Register<NotificationMessage>(this, (message) =>
            {
                DispatcherHelper.CheckBeginInvokeOnUI(() =>
                {
                    if (message.Notification == "CloseWindowsBoundToMe" 
                        && message.Sender == DataContext)
                    {
                        Close();
                    }
                });

            });

            if (browser != null)
            {
                var bound = (DataContext as ChatWindowViewModel).Bound;
                browser.RegisterJsObject("bound", bound);
            }
        }

**Comment by amaitland** [comment]
Does `Close` ever get called just after the `Window` has been opened?

**Comment by DominikPalo** [comment]
No, the `Close` event is called from inner JavaScript (it is called using a `Bound` object) after user clicks to a "Close" HTML element on displayed web.

**Comment by amaitland** [comment]
Well somehow your disposing of the `BrowserProcessServiceHost` before it's open
https://github.com/cefsharp/CefSharp/blob/cefsharp/45/CefSharp.Core/ManagedCefBrowserAdapter.cpp#L61

https://github.com/cefsharp/CefSharp/blob/cefsharp/45/CefSharp.Core/ManagedCefBrowserAdapter.h#L103

**Comment by amaitland** [comment]
Added a simple try/catch around the `Open` call. Change will be in `47.0.0` release.

https://github.com/cefsharp/CefSharp/commit/86b5c541e3d71a30216c51b7a1f55a642a4c635d

If you can reproduce with that change then this can be reopened. (Ideally investigate further and submit a `PR` with a proposed solution).
