### ISSUE TITLE
How to edit zh-CN.pak file?Print fonts are not consistent with the display font.

### ISSUE THREAD

**Issue by feliciwithme** [cefsharp/CefSharp#1495]
Only Microsoft YaHei font consistent!
![file1](https://cloud.githubusercontent.com/assets/15883404/11859139/4b4c9ada-a4a3-11e5-84a0-e1ee9da701e7.png)

**Comment by amaitland** [comment]
Please report this problem to `CEF` on their forum.

http://magpcss.org/ceforum/index.php

`CefSharp` simply repackages the `CEF` project, it generates those files.

**Comment by amaitland** [comment]
When you report your problem, please make sure you specify the `CEF` version your using, e.g. `45.0.0` = `CEF 3.2454.1344`

On the off change your using an older version, please try updating to the latest release (`45.0.0`)

**Comment by feliciwithme** [comment]
Updating to the latest release 45.0.0.0 ,CEF 3.2454.1344, the problems still exist.

**Comment by amaitland** [comment]
> Updating to the latest release 45.0.0.0 ,CEF 3.2454.1344, the problems still exist.

Thanks for confirming, you'll need to raise the issue with on the `CEF Forum` as `CefSharp` has no control over how those files are generated.
