### ISSUE TITLE
Authorization for download?

### ISSUE THREAD

**Issue by ray007** [cefsharp/CefSharp#1496]
I'm trying the download a file via a link (a-tag) from the CefSharp application.
Things seem to work unless the download requires authorization, in which case the file just doesn't get saved and nothing else happens.
The request also doesn't appear in the Network window of the developer tools and `IRequestHandler.GetAuthCredentials(...)` doesn't get called.

Using CefSharp 45...

**Comment by amaitland** [comment]
If you open `DevTools` does the console provide any debugging information? Maybe even check the network requests?

Might be one to ask on `ceforum`.

http://magpcss.org/ceforum/index.php

**Comment by ray007** [comment]
Nothing to see in the `Network` tab, no output on the console.
CefSharp Download handler like in `CefSharp.Example`.

I only know about the request and result by running Fiddler and seeing the request there.

**Comment by amaitland** [comment]
Does `GetAuthCredentials` get called when trying to visit a password protected web page?

Might be a bug in `CEF`.

**Comment by ray007** [comment]
Unfortunately `GetAuthCredentials` doesn't get called for the download.

**Comment by amaitland** [comment]
If you try to visit a website that has basic auth enabled does it get called?

**Comment by amaitland** [comment]
> Might be one to ask on ceforum.
> 
> http://magpcss.org/ceforum/index.php

Did you end up asking for clarification?

**Comment by amaitland** [comment]
Please report the issue on http://magpcss.org/ceforum/index.php

Will have to be fixed in `CEF`.
