### ISSUE TITLE
How to call getEventListeners from C#

### ISSUE THREAD

**Issue by krk** [cefsharp/CefSharp#1497]
getEventListeners function is defined in Chrome Developer Tools console. 

In our use case, there is no UI shown to the user. Is there a way to invoke getEventListeners from CefSharp without showing any UI?

https://developer.chrome.com/devtools/docs/commandline-api#geteventlistenersobject

**Comment by amaitland** [comment]
Have a read over the [FAQ](https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions)

In some scenarios it might be worth using `Chrome Driver`, your question is rather nondescript, so it's hard to provide specific guidance.
https://bitbucket.org/chromiumembedded/cef/wiki/UsingChromeDriver.md

**Comment by amaitland** [comment]
We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Continue followup discussion there.
