### ISSUE TITLE
Windows Form application closes when webrtc call ended 

### ISSUE THREAD

**Issue by elherzt** [cefsharp/CefSharp#1498]
I am using  CefSharp in a Windows Form application with vb, the web browser works fine, it opens a url for parking asistance (camera and microphone works fine) and when on the web page (no in windows form application) the call ends, the application closes it by itself and doesn't show any errors, it ends normally with code 0 (0x0). I tried with the test apps of https://cefbuilds.com/ for windows 64 and has the same behaviour. 
I don't know how to handle  this error. I tried the OnBeforeBrowse, OnBeforeResourceLoad and others event handlers.

**Comment by amaitland** [comment]
If you cross post please make sure you provide a link.

http://stackoverflow.com/questions/34346404/cefsharp-windows-form-application-closes-when-webrtc-call-ended

**Comment by amaitland** [comment]
> I tried with the test apps of https://cefbuilds.com/ for windows 64 and has the same behaviour.

What exact version are you using? 

Look at the `ILifeSpanHandler.DoClose`, is that being called?

https://github.com/cefsharp/CefSharp/blob/cefsharp/45/CefSharp/ILifeSpanHandler.cs#L109

**Comment by amaitland** [comment]
In general your issue is a little lite on for detail, please take a read over `Contributing.md` when you get a chance.

https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue

**Comment by amaitland** [comment]
@elherzt Any follow up on this one?

**Comment by amaitland** [comment]
Closing due to lack of feedback.

We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask any follow up questions there.
