### ISSUE TITLE
writing logs using ChromiumWebBrowser ConsoleMessage event

### ISSUE THREAD

**Issue by ortalevi** [cefsharp/CefSharp#1501]
I'm trying to write JS logs to files, using ChromiumWebBrowser ConsoleMessage event:
"public event EventHandler<ConsoleMessageEventArgs> ConsoleMessage;"
but unfortunately, the arrived message log doesn't support string format.
for instance,  when i try to log the following message in my JS code: 
console.log("Application %s send message:\n%s", appId, request);
i get the message in ConsoleMessageEventArgs, but without its arguments. i get it as "Application %s send message:\n%s" 
Has anyone encountered a similar problem?
Perhaps someone has a different way for writing js logs to file?
thanks in advance.

**Comment by amaitland** [comment]
What version are you using? It's quite likely `CEF` doesn't support logging using a string format.

> console.log("Application %s send message:\n%s", appId, request);

What about `console.log("Application " + appId + " send message:\n" + request);`?

**Comment by amaitland** [comment]
You should also check in `DevTools`, see what's output to the console there, see if your messages show up correctly.

**Comment by vulfh** [comment]
Hi.
In dev tools we see it ok, but to the event handler it arrives before the
formatting was applied.
Is there any way to get the console message after the formatting was
applied?
Thank you,
Vulf

**Comment by amaitland** [comment]
> Is there any way to get the console message after the formatting was applied?

Likely a bug in `CEF` that will need to be fixed `upstream`.

You can report it on http://magpcss.org/ceforum/

Likely be a few months before any fix filters it's way into `CefSharp`.

Short term, if you can program around the problem then I'd be doing so.

**Comment by amaitland** [comment]
I'm also aware of one open bug related to console logging, it may actually be related.

https://bitbucket.org/chromiumembedded/cef/issues/324/only-the-first-consolelog-argument-is

**Comment by amaitland** [comment]
Was marked as `WontFix` in `CEF`, as needs to be fixed in `Chromium`.

**Comment by BuslikDrev** [comment]
Вы можете в начале html  или через CefSharp.WebBrowserExtensions.ExecuteScriptAsync() добавить обработку консольных команд.
javascript
```
window.console.logs = window.console.log;
window.console.log = function(...args) {
	window.console.logs.apply(this, args);
};
```
