### ISSUE TITLE
Hide "Paste" context menu when using touch monitors.

### ISSUE THREAD

**Issue by ghost** [cefsharp/CefSharp#1504]
When I use CefSharp on a touch monitor whenever I touch a text field a context menu is displayed next to it with the options "Paste" and "...", the tree little dots don't do anything actually.

I was looking for a way to disable it but so far no luck, I'm using CefSharp 41.0.1.0, any help from you guys is much appreciated.

![kngvy](https://cloud.githubusercontent.com/assets/485653/11944645/c943038c-a82e-11e5-9ba1-e621d672e663.png)

On my browser init code I have:

```
MenuHandler = new MenuHandler(),
DragHandler = new DragHandler(),
```

and then...

```
internal class MenuHandler : IMenuHandler
{
    public bool OnBeforeContextMenu(IWebBrowser browser, IContextMenuParams parameters)
    {            
        return false;
    }        
}

public class DragHandler : IDragHandler
{
    public bool OnDragEnter(IWebBrowser browser, IDragData dragData, DragOperationsMask mask)
    {
        return true;
    }
}
```

**Comment by jankurianski** [comment]
CefSharp is a fairly light wrapper around CEF.  So you should first try reproducing your issue in CEF.

Take a look at our guide on what to do before posting an issue: https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue

**Comment by Paulo-Faustino** [comment]
Thanks man, I downloaded the "Test App" from CEFbuilds.com and the paste menu doesn't show up when I tap on any text box, like Google's search box. 

From Visual Studio if I download the latest CefSharp using NuGet and load google.com tapping on the search box does show the past menu.

I'll keep looking for a way of disabling it, do you think that my best bet is download the C++ source and hack it to build my own CEF binaries?

Thanks

**Comment by amaitland** [comment]
Normally you would cancel the context menu by returning `true`, though I'm unsure what the result is in a `Touch` scenario.

```c#
public bool OnBeforeContextMenu(IWebBrowser browser, IContextMenuParams parameters)
{            
    return true;
}  
```

> I downloaded the "Test App" from CEFbuilds.com and the paste menu doesn't show up when I tap on text boxes, like on Google's search box.

What version did you download?

**Comment by Paulo-Faustino** [comment]
I'll give that a shot by returning true. 
I've downloaded 2015-12-10 - CEF 3.2556.1368.g535c4fb

**Comment by amaitland** [comment]
> I've downloaded 2015-12-10 - CEF 3.2556.1368.g535c4fb

For reference that translates to `Chromium 48`, when your using `41`, so there's likely been a lot of progress since then. `41` is based on the `2272` branch.

The latest release of `CefSharp` is `45.0.0` based on the `2454`

**Comment by Paulo-Faustino** [comment]
Correct, I tried the latest Nuget version based on v45 and the menu is still there.

**Comment by amaitland** [comment]
> Correct, I tried the latest Nuget version based on v45 and the menu is still there.

You get access to a lot more of the underlying `API` in `45.0.0`.

https://github.com/cefsharp/CefSharp/blob/cefsharp/45/CefSharp/IContextMenuHandler.cs#L58

**Comment by amaitland** [comment]
@Paulo-Faustino Did you come up with a working solution?

**Comment by Paulo-Faustino** [comment]
Hi Alex, what I end up doing was to blur() when the control receives the focus, that was the only way to prevent the "touch menu" from appearing but also hides the "blinking cursor".

I forgot to report back here, sorry about that and many thanks for the help.

**Comment by amaitland** [comment]
@Paulo-Faustino Thanks for confirming :+1: 

Next time I have access to a touch screen I'll see what alternate options there are. (Assuming I remember)

**Comment by david-br** [comment]
@Paulo-Faustino
Hi Paul, I have a same problem like you had. I wonder if you can tell the solution for this touch-problem.
I tried to edit textbox by virtual keyboard in touch screen, but the TEXT-SELECTION-HANDLES ruined focus on the CEF browser.

I cannot understand 'blur()' that you said in your comment. Is the blur() C# method? Or Java script?

**Comment by Paul-C-F** [comment]
I don't recall what I did exactly but I think that it was something along this line:

$("input[type=text]:not([type='hidden'])").each(function(a, b) 
{
    $(b).focus(function() {
        $(b).blur();
    });
});

**Comment by david-br** [comment]
@Paulo-Faustino
Thanks for answering my question.

Unfortunately I want to use touch event with editable control except TEXT-SELECTION_HANDLES. blur() kills the focus so when I use the method, then I cannot edit the control on my kiosk app.
Anyway, thanks for quick answer again.

**Comment by mismaiel62** [comment]
Hi, 
I am working on an app which runs in kisok mode on tablet with the ability to exit from kiosk mode by right clicking for 3 times in a secret area but when I press long for right click on tablet "paste  ..." menu appears.

Is there any solution for this?
Thanks in advance.

Regards,
M.Ismaiel

**Comment by amaitland** [comment]
Testing with https://github.com/cefsharp/CefSharp/commit/fd02981fc85664f4521a50c5fc2b91ee9913ac74 and disabling the context menu by implementing by implementing `IContextMenuHandler` works as expected on my `Surface Pro 1` using `Windows 10`.

https://github.com/cefsharp/CefSharp/blob/cefsharp/65/CefSharp.WinForms.Example/Handlers/MenuHandler.cs#L45

```c#
bool IContextMenuHandler.RunContextMenu(IWebBrowser browserControl, IBrowser browser, IFrame frame, IContextMenuParams parameters, IMenuModel model, IRunContextMenuCallback callback)
{
    return true;
}
```

**Comment by amaitland** [comment]
It's important to remember that CefSharp is just one of many chromium embedded framework wrappers. If IContextMenuHandler methods aren't being called for touch screen inputs then CEF will need to be updated to add support. 

CefSharp does little more than forward the method calls https://github.com/cefsharp/CefSharp/blob/cefsharp/94/CefSharp.Core.Runtime/Internals/ClientAdapter.cpp#L778

CEF has it's own support forum at https://magpcss.org/ceforum/index.php if the problem reproduces in the 94-pre release then I'd suggest moving the conversation there.
