### ISSUE TITLE
[ CefSharp/ 45 ] How to Add plugins (flash, video player)

### ISSUE THREAD

**Issue by wangliuzheng** [cefsharp/CefSharp#1505]
How to Add plugins (flash, video player) To ChromiumWebBrowser  ?
ChromiumWebBrowser  can't load video . show a black area. How Can I resovle it ?
Thanks.

**Comment by amaitland** [comment]
Download and install `Pepper Flash` see https://bitbucket.org/chromiumembedded/cef/issues/1586/add-pepper-flash-plugin-support#comment-16898332 for details on where to get a copy.

**Comment by wangliuzheng** [comment]
@amaitland thanks , but I still have some problems,  my video , my mp3 , can't play , how can i do ?

**Comment by amaitland** [comment]
See the change log for details about ffmpeg. Propitiatory formats are not supported due to licensing restrictions.

**Comment by amaitland** [comment]
If flash is sorted then please close this issue. Thanks

**Comment by qidongxi2012** [comment]
so good

**Comment by michal1106** [comment]
You can find **PPAPI** standalone download link 
for windows in this page [https://helpx.adobe.com/flash-player/kb/installation-problems-flash-player-windows.html](https://helpx.adobe.com/flash-player/kb/installation-problems-flash-player-windows.html) search for **Flash Player for Opera and Chromium-based browsers - PPAPI** 
for os x [https://get.adobe.com/flashplayer/download/?installer=FP_17_Mac_for_Opera_and_Chromium_-_PPAPI&standalone=1](https://get.adobe.com/flashplayer/download/?installer=FP_17_Mac_for_Opera_and_Chromium_-_PPAPI&standalone=1) 

After installation on windows go to
C:\Windows\SysWOW64\Macromed\Flash
You should see there **pepflashplayer** dll
You can copy it over to your soltuion and add the following line to your code
`Cef.AddWebPluginPath(@"./pepflashplayer32_21_0_0_197"); // Flash 21.0.0.197`
This how you can verify that whomever using your product would have the appropriate Flash version

p.s. the default "Non-PPAPI" Flash version would display a plugin icon and the message 
**Adobe Flash Player needs your permission to run**

**Comment by amaitland** [comment]
@michal1106 Your post come across as being a requirement, so just clarifying that you can simply install the `PPAPI Flash Player` from `Adobe` and it will be used by default without manual file copying or setting plugin paths.

> for os x https://get.adobe.com/flashplayer/download/?installer=FP_17_Mac_for_Opera_and_Chromium_-_PPAPI&standalone=1

`CefSharp` only runs on `Windows`.

> This how you can verify that whomever using your product would have the appropriate Flash version

This is questionable in terms of licensing as to my knowledge `Adobe` don't provide a license for distributing just the binary, so whilst you can technically do this, make sure you perform due diligence and check the licensing first. Also you then become responsible for providing security updates.

You can also load the `pepflashplayer.dll` that's provided by `Google Chrome`, again I'm not advocating this, it's just technically possible. (Query registry, get `Chrome` location, load manually).

> p.s. the default "Non-PPAPI" Flash version would display a plugin icon and the message
> Adobe Flash Player needs your permission to run

You have control over `Plugin Placeholders`, see https://bitbucket.org/chromiumembedded/cef/issues/1708/add-support-for-plugin-placeholders-and

**FYI** `NPAPI` support has been removed from `Chromium`, so be aware that using the older `NPAPI Flash Plugin` is no longer supported.
