### ISSUE TITLE
The magpcss.org forum registeer, Confirmation of registration, What's  the answer?

### ISSUE THREAD

**Issue by feliciwithme** [cefsharp/CefSharp#1506]
http://magpcss.org/ceforum/ucp.php?mode=register

![register](https://cloud.githubusercontent.com/assets/15883404/11948887/0b6b92c6-a8b4-11e5-8af0-350a351ff308.jpg)

This forum provides support for a specific open source project. Enter the three initials of that project in upper case reverse order without spaces or punctuation.:
This question is a means of preventing automated form submissions by spambots.

**Comment by amaitland** [comment]
It's `CEF` backwards, so `FEC`

**Comment by feliciwithme** [comment]
Registered success, Thank you very much!
