### ISSUE TITLE
Text clipping issue in High resolution screen

### ISSUE THREAD

**Issue by Saravanan04** [cefsharp/CefSharp#1507]
Text clipping problem in high resolution monitor with OS Windows 8.1 or 10

cefsharp version 39.0.0.1

![image](https://cloud.githubusercontent.com/assets/16400410/11954301/707df77e-a875-11e5-9cdc-82be0e97073d.png)

**Comment by amaitland** [comment]
`WinForms` or `WPF`? Does the problem reproduce in the latest release version (`45.0.0`)?

A lot of improvements have been made in regards to `High DPI` support in newer versions.

> cefsharp version 39.0.0.1

This version is no longer supported.

**Comment by Saravanan04** [comment]
WPF platform. I didn't upgrade the version. May i know which version is this issue fixed?

**Comment by amaitland** [comment]
`High DPI` support was rewritten in version `43` (latest on that branch is `43.0.1`). See https://github.com/cefsharp/CefSharp/wiki/CefSharp-43 for tips on upgrading.

**Comment by amaitland** [comment]
Actually, try disabling `DirectWrite` first, see the following for an example.

https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.Example/CefExample.cs#L45

**Comment by amaitland** [comment]
@Saravanan04 Any update on this?

**Comment by Saravanan04** [comment]
Hi @amaitland 

Actually, try disabling DirectWrite first, see the following for an example.

what is the use of disabling this. if i disable the DirectWrite, Is it accept the system text size or the font will be small?

**Comment by Saravanan04** [comment]
Still i have problem in clipping issue. A small clipping at the bottom of the text.

![image](https://cloud.githubusercontent.com/assets/16400410/12029913/b280516e-adc3-11e5-8c4a-ef074f076c37.png)

**Comment by amaitland** [comment]
Can you try `45.0.0`? You can likely use the `MinimalExample` to test

https://github.com/cefsharp/CefSharp.MinimalExample

**Comment by Saravanan04** [comment]
Hi @amaitland 

Yes, i have updated the new version 45.0.0. But still i have clipping problem.

**Comment by Saravanan04** [comment]
Hi @amaitland 

Yes, i have updated the new version 45.0.0. But still i have clipping problem.

**Comment by amaitland** [comment]
> Yes, i have updated the new version 45.0.0. But still i have clipping problem.

Does the problem persist with the `WinForms` example?

Can you provide the steps to reproduce your problem?

**Comment by amaitland** [comment]
Would be helpful to isolate if the problem persists in the `cefclient` reference application.

https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

**Comment by Saravanan04** [comment]
#### Issue Summary
When change the system display setting text not rendering properly.

#### Steps to Reproduce
1. Change the system display setting as 150%
![image](https://cloud.githubusercontent.com/assets/16400410/12109448/0bccc75c-b350-11e5-9550-712db1eeaf10.png)


This is a bug because...
On 100%
![image](https://cloud.githubusercontent.com/assets/16400410/12109455/14ba325a-b350-11e5-9f1d-c342562fa0be.png)
![image](https://cloud.githubusercontent.com/assets/16400410/12109458/1f904246-b350-11e5-8143-141f1ca37bd6.png)

On 150% -> Text clipping and rendering problem
![image](https://cloud.githubusercontent.com/assets/16400410/12109463/2bbae06c-b350-11e5-9cdc-713bfd26a0c6.png)
![Uploading image.png…]()


#### Technical details
* CefSharp Version: 45.0.0.0
* Operating System: Windows 8.1 / Windows 10
* x86/x64: x86/x64
* WinForms/WPF/OffScreen: WPF

**Comment by jankurianski** [comment]
Answers to these 2 previous questions would help too:

> Does the problem persist with the WinForms example?

And...

> Would be helpful to isolate if the problem persists in the cefclient reference application.
> 
> https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

**Comment by Saravanan04** [comment]
I can't reproduce this issue in cefclient reference application application.
I have used the following setting in my application.
 var settings = new CefSettings();
            settings.CefCommandLineArgs.Add("disable-plugins-discovery", "1");
            settings.CefCommandLineArgs.Add("no-proxy-server", "1");
            settings.CefCommandLineArgs.Add("disable-gpu-vsync", "1");
            settings.CefCommandLineArgs.Add("disable-gpu", "1");
            settings.CefCommandLineArgs.Add("disable-direct-write", "1");
            Cef.Initialize(settings);

**Comment by amaitland** [comment]
> I can't reproduce this issue in cefclient reference application application.

Did you use the `--multi-threaded-message-loop --off-screen-rendering-enabled` command line arguments when running `cefclient`?

**Comment by amaitland** [comment]
There was a new method added to `CEF`, which translates to `Cef.EnableHighDPISupport();`, can you try calling that method early on in your app startup? Somewhere in `App.xaml.cs`, like `OnStartup`. 

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf.Example/App.xaml.cs#L12
https://github.com/cefsharp/CefSharp/commit/36b0b95d55849b90346590212f7ea26061fbd705#diff-f142d024925e73816b0fabd620d2f71dR19

It's a long shot, don't have a lot of other options to try at the moment, `High DPI` isn't something that I use.

**Comment by amaitland** [comment]
> settings.CefCommandLineArgs.Add("high-dpi-support", "1");

Another long shot that's worth a try.

**Comment by amaitland** [comment]
@Saravanan04 Any follow up to this?

**Comment by amaitland** [comment]
Closing due to lack of feedback.
