### ISSUE TITLE
 my video MP4 , my mp3 , can't play , how can i do ? 

### ISSUE THREAD

**Issue by wangliuzheng** [cefsharp/CefSharp#1508]
I have some problems, my video MP4 , my mp3 , can't play , how can i do ?   why my cefsharp/45 doesn't contains ffmpegsumo.dll ...is it complied into libcef.dl, ? Need I copy something to bin?
the browser doesn’t support that codec ( H.264/MP4 ) ?

**Comment by amaitland** [comment]
Duplicate of #1479
