### ISSUE TITLE
Calling IFrame.EvaluateScriptAsync when the IFrame.IsValid is false causes the entire application to exit with code 1073741855

### ISSUE THREAD

**Issue by fjch1997** [cefsharp/CefSharp#1509]
I'm using the latest (45) version of CefSharp.Wpf
My app heavily rely on ChromiumWebBrowser.FrameLoadEnd event to handle things and inside the event handler I call e.Frame.EvaluateScriptAsync a lot.

Here is an example of my code
```CSharp
private async void OnLoadEnd(object sender, FrameLoadEndEventArgs e)
{
    var frame = e.Browser.GetFrame(e.Frame.Identifier);
    //e.Frame is dispose (or something) after the first async call (And it shouldn't be the best behavior but I believe the guys who wrote this code have their reason.)
    //So I obtain a reference to the frame locally.
    await frame.EvaluateScriptAsync("...");
    await frame.EvaluateScriptAsync("...");
    await frame.EvaluateScriptAsync("...");
    await frame.EvaluateScriptAsync("...");
    //EvaluateScriptAsync is called multiple time in my code.
    //The problem is, if I spend too much time waiting.
    await Task.Delay(10000);
    //The user or my own code can close the tab or navigate away from this website. And frame.IsValid goes to false.
    //If I now call IFrame.EvaluateScriptAsync(string);
    await frame.EvaluateScriptAsync("...");
    //My whole application exits with code 1073741855 without any exception or error message.
}
```

**Comment by amaitland** [comment]
Firstly a frame represents a managed resource and is only valid until the call goes out of context. If you get a frame reference yourself make sure it's disposed of you'll leak memory. 

If your script were to invalidate a frame, like remove the frame or perform a redirect then you'll get exceptions. Without a reproducible example it's hard to say what's going on. 

If you can fork the MinimalExample then someone will likely take a look. 

Secondly don't block on in any of the event handlers provided as they are called on 'CEF' threads. Spawn a Task if you need to perform more than a trivial operation.

**Comment by fjch1997** [comment]
Thanks, I didn't realize IBrowser.GetFrame(int) create an instance of IFrame and it is my responsibility to dispose it. What i thought is that it simply pulls that frame out of the browser and the browser still owns it. So there is actually a major memory leak in my application. In my view, this should be mentioned on the comments when we press F12 on this method. I check the comments a lot but unfortunately many of them don't even have a comment. Please tell me how I can help to improve this since i'm new to GitHub.

Secondly, I wasn't blocking the CEF thread. All time consuming tasks are asynchronous.

But all this Issue is about is that IFrame.EvaluateScriptAsync shouldn't simply close my application when something's not right. Instead it should throw an exception. I actually wasted a lot of time finding the exact cause of the 1073741855 exit code issue.

**Comment by fjch1997** [comment]
The code I gave above do reproduce the problem, if the user navigates away within the 10 seconds delay.

**Comment by amaitland** [comment]
Every request to 'GetFrame' will create a new wrapper. It's actually rather difficult to keep track of when a frame is no longer valid, so the simplest approach was chosen, users need to manage the object lifecycle. Since the wrappers are lightweight there is little cost in creating one, so the best management strategy is to wrap calls in a using block. 

As for documentation few take the time to contribute. You simply need to fork the project and create a pull request with your proposed changes. If your not familiar then Google will have the answer. 

Ideally CEF would provide nicer handling. To be honest your the first person who's reported a problem. Your use case of waiting 10 seconds isn't what I'd call typical. 

Your code sample isn't complete, I don't have time to be reproducing every problem that's reported, the easier you make it the more likely someone will look into it further.

**Comment by fjch1997** [comment]
To be honest i don't have time too. 
Add this event handler to any ChromiumWebBrowser's FrameLoadEnd can reproduce the problem.
As for why CEF decided to shutdown my application. I don't know. But it should throw an exception anyway.

I guess i'll create a pull request then

**Comment by amaitland** [comment]
The best we can do is put a guard statement in checking IsValid.

The fact CEF uses its own threads and posts tasks around makes it near impossible to catch an exception.
