### ISSUE TITLE
Winform, catch/disable keydown events for the purpose of disable the backspace back function

### ISSUE THREAD

**Issue by Snorvarg** [cefsharp/CefSharp#1512]
Hi, I am trying out CefSharp in VS2015, works great. I have downloaded the CefSharp.MinimalExample and are tweaking around in it. 

I have disabled the backspace buttons default function as 'Back' in the browser by implementing the interface IKeyboardHandler and connect it to the ChromiumWebBrowser.KeyboardHandler property, and return true on any keypress in both OnKeyEvent() and OnPreKeyEvent(). 

This works great, though it effectively kills all keyboard events. 

Is there any better way? I would like to disable most default keyboard shortcuts for the Chrome browser.

**Comment by amaitland** [comment]
> Is there any better way? I would like to disable most default keyboard shortcuts for the Chrome browser.

Nope, that's the easiest way.

**Comment by Snorvarg** [comment]
Thanks for the response @amaitland. 

I tweaked the code to check for the windowsKeyCode == 8, i.e the backspace key, and react only to that key. Now all input forms works as normal. ..except the backspace key, naturally. :) 

Is there any way to send the backspace key event to the browser in such a way that the 'Back' function in the browser is not triggering, but the 'erase' functionality in any active text field is preserved?

**Comment by amaitland** [comment]
See  #608

**Comment by Snorvarg** [comment]
Works like a charm! I guess I should spend some more time reading the forum.. ;)

**Comment by amaitland** [comment]
> EDIT: That thread does not mention how the rest of the functions implemented in IRequestHandler should be treated. I mean, is there any 'default' or 'I don't care, you choose' setting on these functions?

Editing a comment is not recommended as `GitHub` doesn't provide a notification. Generally speaking if your question is unrelated open a new issue. Anyone searching for a similar question would be unlikely to look in a comment for an unrelated post.

> For example, the IRequestHandler::GetAuthCredentials(), it sounds pretty dangerous to just return true, but returning false would cancel the request. Do I need to evaluate and implement each callback function or does it exists some sensible defaults?

`return false` is the default behavior for almost every handler method that returns a `bool`. The example projects demo a number of features. See https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/RequestHandler.cs

For `GetAuthCredentials` the value `return true` simple means you wish to handle the request. You actually need to execute the `callback`.

https://github.com/cefsharp/CefSharp/blob/cefsharp/45/CefSharp/IAuthCallback.cs#L12

**Comment by amaitland** [comment]
Closing this now as the original question has been answered.  We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). If you need to ask a quick question check it out :+1:
