### ISSUE TITLE
Mouse down event hander

### ISSUE THREAD

**Issue by Spiderpig86** [cefsharp/CefSharp#1513]
Hi. I am currently using CefSharp Winforms 41 and I am trying to intercept the mouse down event in order to hide toolstrip menus on the application. I have followed the Winforms example(https://github.com/cefsharp/CefSharp/blob/2153c51d156a9891cfd380554abd2a1263be4f3b/CefSharp.WinForms.Example/BrowserTabUserControl.cs) and the discussion(https://github.com/cefsharp/CefSharp/issues/1098). I am still unable to get it working with VB.

At first I suspected that it was the webcontrol not being initialized, but there is an error no matter when I add the mouse handler.
```

                    ChromeWidgetMessageInterceptor.SetupLoop(WebControl, Function(message)
                                                                             Const WM_MOUSEACTIVATE As Integer = &H21
                                                                             Const WM_NCLBUTTONDOWN As Integer = &HA1
                                                                             If message.Msg = WM_MOUSEACTIVATE Then                 
Dim topLevelWindowHandle As System.IntPtr
                                                                                 Me.Invoke(Sub() topLevelWindowHandle = message.WParam)
                                                                                 Dim lParam As IntPtr
                                                                                 Me.Invoke(Sub() lParam = IntPtr.Zero)
                                                                                 Me.Invoke(Sub() PostMessage(topLevelWindowHandle, WM_NCLBUTTONDOWN, IntPtr.Zero, lParam))
                                                                             End If
                                                                         End Function)
```
Error:
```
Public member 'FindDescendantByClassName' on type 'ChromeWidgetHandleFinder' not found.
```
The winforms example works fine, but it is CefSharp 45. Does this method not work on CefSharp 41?

**Comment by Spiderpig86** [comment]
Never mind. I have solved the issue by explicitly defining the variables to their respective data types. I hope this would help others.

**Comment by vulfh** [comment]
Hi,
Could you please provide some more details regarding your solution, since I
am experiencing the same problem with mouse events.
Thank you,
Vulf
