### ISSUE TITLE
How to restrict the new popup open?

### ISSUE THREAD

**Issue by Saravanan04** [cefsharp/CefSharp#1514]
cefSharp Version : 45.0
Platform : WPF

How to restrict the new popup window in OnBeforePopup?

My Code

```c#
public bool OnBeforePopup(IWebBrowser browserControl, IBrowser browser, IFrame frame, string targetUrl, string targetFrameName, WindowOpenDisposition targetDisposition, bool userGesture, IWindowInfo windowInfo, ref bool noJavascriptAccess, out IWebBrowser newBrowser)
        {
			System.Diagnostics.Process.Start(targetUrl);
            newBrowser = null;
            return false;
        }
```

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/blob/cefsharp/45/CefSharp/ILifeSpanHandler.cs#L25

**Comment by Saravanan04** [comment]
Hi amaitland

I have used like 

public class LifeSpanHandler : ILifeSpanHandler
    {
        public bool DoClose(IWebBrowser browserControl, IBrowser browser)
        {
            return false;
        }

        public void OnAfterCreated(IWebBrowser browserControl, IBrowser browser)
        {
            // DO NOTHING
        }

        public void OnBeforeClose(IWebBrowser browserControl, IBrowser browser)
        {
            // DO NOTHING
        }

        public bool OnBeforePopup(IWebBrowser browserControl, IBrowser browser, IFrame frame, string targetUrl, string targetFrameName, WindowOpenDisposition targetDisposition, bool userGesture, IWindowInfo windowInfo, ref bool noJavascriptAccess, out IWebBrowser newBrowser)
        {
            System.Diagnostics.Process.Start(targetUrl);
            newBrowser = null;
            return false;
        }
    }

In that it's open the chrome browser and also open the new browser window. How can i restrict new window?

**Comment by amaitland** [comment]
If you read the documentation that I linked you'll see that you need to `return true` to cancel popup creation.

**Comment by amaitland** [comment]
On the off chance your trying to handle opening an external application e.g. `mailto` opens the default mail application then see `IRequestHandler.OnProtocolExecution`

https://github.com/cefsharp/CefSharp/blob/cefsharp/45/CefSharp/IRequestHandler.cs#L145

**Comment by Saravanan04** [comment]
Hi @amaitland 

Thanks for your update. it's working fine.
