### ISSUE TITLE
Can't load dailymotion video

### ISSUE THREAD

**Issue by Vialaxy** [cefsharp/CefSharp#1516]
Hello,

I'm trying to watch dailymotion videos (no matter the video), the viewer always display that : https://i.gyazo.com/571ded59de0ca8c3902485312fc8e357.png

I tried everything that came to my mind : disable/enable the cache, gpu acceleration and tested around 20 differents user agents (including 2/3 mobile UA).

And it isn't a plugin issue as dailymotion support html5.

But it always display this result, no matter the cefsharp settings (while it's run well on Chrome & Firefox on my pc)

Do you have an idea how can i load the videos?

Kind regards,
Vialaxy

**Comment by amaitland** [comment]
What version are you using?

> And it isn't a plugin issue as dailymotion support html5.

When I open a random video it appears to load the `Flash` player in both `FireFox` and `Chrome`. Are you use that `html5` is the default?

**Comment by Vialaxy** [comment]
@amaitland : I'm using version 45 from the nugget package (and app use the x86).

From what I've read if there is flash installed it use flash by default and otherwise it use html5.

Just tested on a computer where flash isn't install and it works perfectly.

Anyway thanks for your quick reply :)

**Comment by amaitland** [comment]
> @amaitland : I'm using version 45 from the nugget package (and app use the x86).

For reference if you require `Flash` in version `45` then see https://github.com/cefsharp/CefSharp/issues/1505#issuecomment-166484362

**Comment by Vialaxy** [comment]
@amaitland I know I could use it but I don't want as for the other site I use I should only have html5 enable (+ it will probably use additional resources and cefsharp itself already consume a lot of ram and the computer that will use the webbrowser can't support additional ram usage).

There isn't any way to use it just with html5? I know it works with Firefox & chrome so I don't see why it couldn't work with cefsharp.

**Comment by amaitland** [comment]
> There isn't any way to use it just with html5?

`CefSharp` only support open source video codecs. 

If you open https://www.youtube.com/html5 you can see that `h264` is not supported.

I don't know anything about `dailymotion`, so you'll have to dig deeper to find out what their `html5` implementation actually uses, and potentially how they switch between `Flash` and `html5`.

**Comment by amaitland** [comment]
See https://bitbucket.org/chromiumembedded/cef/issues/1631/add-support-for-widevine-cdm which may be relevant. If it turns out they use `h264` then you'd need to build `CEF` from source, then repackage it for use with `CefSharp`.

You would also have to look at obtaining the relevant licenses.

**Comment by Vialaxy** [comment]
@amaitland Oh thanks for your replies.

I apologize but im a noob when it come to build from source, repackage...

I just downloaded cef_binary_3.2526.1364.gf6bf57b_windows32 from https://cefbuilds.com/ so i presume it's already build. Now how can i repackage it to use it with cefsharp?

**Comment by amaitland** [comment]
> I just downloaded cef_binary_3.2526.1364.gf6bf57b_windows32 from https://cefbuilds.com/ so i presume it's already build. Now how can i repackage it to use it with cefsharp?

The precompiled versions don't include `h264` support. You have to compile `CEF` from source. 

See https://github.com/cefsharp/CefSharp/issues/1479#issuecomment-164395359 for more information.
