### ISSUE TITLE
Blocking other frames and content with OnBeforeResourceLoad

### ISSUE THREAD

**Issue by Spiderpig86** [cefsharp/CefSharp#1517]
Hello. Is it possible to block certain frames from loading by capturing them with OnBeforeResourceLoad on CefSharp Winforms 41? My goal is to be able to block certain frames from loading as well as scripts without having to disable JavaScript globally.

**Comment by amaitland** [comment]
What have you tried so far?

Your options in `41` are somewhat limited. You can check the `request.Url` or the `isMainFrame` param, if that doesn't provide enough information then you'll have to upgrade to a newer version.

**Comment by Spiderpig86** [comment]
That was what I had thought. I was able to detect some of the scripts I wanted to block, but somehow they are still being executed. Is the correct way to handle the event by returning ```CefReturnValue.Cancel``` for non mainframe requests or am I doing something incorrectly? This way seems to slow the webcontrol down considerably.

**Comment by amaitland** [comment]
> Is the correct way to handle the event by returning CefReturnValue.Cancel for non mainframe requests or am I doing something incorrectly?

That's correct. 

> This way seems to slow the webcontrol down considerably.

Have you looked in `DevTools` to see if it gives any clues? Instead of cancelling the requests you could potentially return your own content if that performs better.

**Comment by Spiderpig86** [comment]
I will look into it and reply when I come up with a solution. Thank you.

**Comment by amaitland** [comment]
Great :+1: Please post any solution you come up with.

 We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). If you have any general questions please continue the discussion there.
