### ISSUE TITLE
a very strange cookies problem.

### ISSUE THREAD

**Issue by coldicelion** [cefsharp/CefSharp#1518]
#### Issue Summary
What is the expected output? What do you see instead?

#### Steps to Reproduce
1. This is the first step

This is a bug because...
Code sample if relevant
Does this problem also occur in the `Cef` TestApp from http://cefbuilds.com?

#### Technical details
* CefSharp Version: nuget - master - latest commit:  INSERT COMMIT REF
* Operating System: 
* x86/x64: 
* WinForms/WPF/OffScreen: 

--

hi, when I use OnBeforeResourceLoad in a RequestHandler, i found the headers contain no "Cookie". and Cookie headers are also not shown in the "Network" tab of the Developer Tools but in the Google Chrome, could you please tell me that what the problem is?

**Comment by amaitland** [comment]
@coldicelion Please edit the bug report above and post a comment when your complete to trigger a notification.

**Comment by coldicelion** [comment]
:sob: sorry, check this photo,in Google Chrome:
![image](https://cloud.githubusercontent.com/assets/6093582/12048954/4b9473e0-af1c-11e5-9328-9dafe5302b58.png)

:sob: but in Cefsharp (all versions) ：
![image](https://cloud.githubusercontent.com/assets/6093582/12048989/c04edf90-af1c-11e5-9e9e-687c45f88566.png)

**Comment by amaitland** [comment]
> :sob: but in Cefsharp (all versions) ：

Explicit version please......does it happen on all website? Ideally fill out the bug report...make my life easier please.

**Comment by coldicelion** [comment]
yes, all website,i have tested (October 29, 2015, Chromium 43.0 / CEF 3.2357.1287) and (November 23, 2015, Chromium 45.0 / CEF 3.2454.1344).

**Comment by amaitland** [comment]
> yes, all website,i have tested (October 29, 2015, Chromium 43.0 / CEF 3.2357.1287) and (November 23, 2015, Chromium 45.0 / CEF 3.2454.1344).

Is it seriously that hard to edit the original post like requested?

**Comment by coldicelion** [comment]
i'm very sorry for not doing this, because i'm really not good at to write comment on GITHUB. its so difficult to me....

**Comment by coldicelion** [comment]
i think i need to try it..thanks!

**Comment by amaitland** [comment]
Please report the problem on http://magpcss.org/ceforum/index.php 

If there is an issue it will have to be resolved in `CEF`.
