### ISSUE TITLE
Clipping on Windows Embedded Standard 1360 x 768

### ISSUE THREAD

**Issue by iLearnCEF** [cefsharp/CefSharp#1521]
Hello,

I have clipping problem with showing web app in WPF, I use the latest version of CEF.

Here are the screen shots of the app shown in WPF:
![clipping 1](https://cloud.githubusercontent.com/assets/16489662/12063556/0e09b2fc-afb1-11e5-8f6b-2c0181e40fc9.JPG)
![clipping 2](https://cloud.githubusercontent.com/assets/16489662/12063557/1282d138-afb1-11e5-9d36-3058e9bb2795.JPG)
![clipping 3](https://cloud.githubusercontent.com/assets/16489662/12063559/16365552-afb1-11e5-8f76-e9e5d8e67ee1.JPG)

Here are the screen shots in the Chrome on the same machine:
![no clipping 1](https://cloud.githubusercontent.com/assets/16489662/12063560/1b0ead2c-afb1-11e5-8ba6-deb0f95337c5.JPG)
![no clipping 2](https://cloud.githubusercontent.com/assets/16489662/12063561/1ed3430a-afb1-11e5-821c-cd6b41348f42.JPG)

Do you have any suggestion what might cause this problem?

**Comment by amaitland** [comment]
> I have clipping problem with showing web app in WPF, I use the latest version of CEF.

By latest do you mean `45.0.0`?

> Do you have any suggestion what might cause this problem?

What exactly is the problem?

Does the problem reproduce with the `MinimalExample`?

https://github.com/cefsharp/CefSharp.MinimalExample

**Comment by amaitland** [comment]
We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Continue followup discussion there.

If it does turn out there is a `bug` or when a solution has been devised we can update/reopen this issue.

**Comment by iLearnCEF** [comment]
By the latest I mean 45.0.0

Problem can not be reproduced with Minimal Example.

In application where the bug can be reproduced there is main window. This main window with frame that have resolution that is configurable. Within this frame is shown the page that implements uses CEF to show some web app (and other types of pages).

It seams that the resolution of this frame affect the look of inner page, related not clear presentation.  Playing with this resolution I can come to ideal resolution that looks ok. 

Is there a way to avoid this trial/error setup, if CEF is on Page that is inside the Frame?

**Comment by amaitland** [comment]
Please discuss on `Gitter` as instructed.
