### ISSUE TITLE
ChromiumWebBrowser.Adress not set

### ISSUE THREAD

**Issue by hpposch** [cefsharp/CefSharp#1524]
Hi, 
i was wondering when the property Adress of the ChromiumWebBrowser is set?
When i execute ChromiumWebBrowser.Load(string url) the property is not set.
So in my point of view the adress is not set when you load a new url.
Can this be a bug, or am i missing something?

**Comment by jankurianski** [comment]
As I understand it, the `Address` property is set when CEF fires an `OnAddressChange` event.  It is asyncronous - that is, it is not immediately set in your `Load()` method call.

You can follow the breadcrumbs here:

- https://github.com/cefsharp/CefSharp/blob/c18f951a97a515df112d67775c767d4222f88c23/CefSharp.Wpf/ChromiumWebBrowser.cs#L347
- https://github.com/cefsharp/CefSharp/blob/c18f951a97a515df112d67775c767d4222f88c23/CefSharp.Core/Internals/ClientAdapter.cpp#L262
- https://github.com/cefsharp/CefSharp/blob/77824905132e8b7877926f8ec190c421fa3711b8/CefSharp.Core/Internals/ClientAdapter.h#L136
- http://magpcss.org/ceforum/apidocs3/projects/(default)/CefDisplayHandler.html#OnAddressChange(CefRefPtr<CefBrowser>,CefRefPtr<CefFrame>,constCefString&)


Is this distinction important for you - perhaps you can explain why?

**Comment by hpposch** [comment]
Thank you for your  answer..
My problem ist that when i have my Browser-Control as Content of a TabItem, the OnLoad() Event is fired every time the tab is changed.
I thought OnLoad() will only be fired when i call the Load() method explicit.
But anyway i have found a solution for my specific problem :)

**Comment by amaitland** [comment]
> My problem ist that when i have my Browser-Control as Content of a TabItem, the OnLoad() Event is fired every time the tab is changed.
> I thought OnLoad() will only be fired when i call the Load() method explicit.

That's a behavior of the standard `TabControl`.

For reference we're transitioning to `Gitter` for questions/comments. Jump on and say `hi`, ask basic/quick questions there :smile: 

https://gitter.im/cefsharp/CefSharp#
