### ISSUE TITLE
Can't call Javascript functions in my HTML page from C#

### ISSUE THREAD

**Issue by Zetka** [cefsharp/CefSharp#1527]
Hi folks, I've been using Awesomium for a while and I'm having a go at trying to use Cefsharp instead. I'm currently trying to get my old code working with CefSharp but I'm having a few problems. What I'm currently stuck on is that I have a static HTML page (this loads fine), it has a Javascript functions already stored within the HTML. I used to call these with Awesomium in C# by doing ExecuteJavascript("functionName(parameters);");
I've tried doing the same in CefSharp with ExecuteScriptAsync("functionName(parameters);"); but this doesn't work. 
Doing ExecuteScript("alert('test');") however does work so it's definitely able to execute javascript, but just not the functions I've already created in HTML.

Any ideas would be appreciated, thanks.

**Comment by amaitland** [comment]
We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask your questions there.
