### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by bobpf** [cefsharp/CefSharp#1532]
I am getting the following error on my Windows 10 tablet.  This same code works on my desktop and other identical Windows 10 tablets.  My application was previously working on this same device and now "magically" started to fail.  Any ideas?

When trying to call one my registered JS object methods I get the following error.  I can step through the JS code and everything works up until the point that I call my objects method.  My C# code never gets executed and it appears to be failing inside of the CefSharp C++ code.

Uncaught Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at CefSharp.JavascriptMethodWrapper.Execute(Object[] parameters)
   at CefSharp.JavascriptMethodHandler.Execute(JavascriptMethodHandler* , CefStringBase<CefStringTraitsUTF16>* name, CefRefPtr<CefV8Value>* object, vector<CefRefPtr<CefV8Value>\,std::allocator<CefRefPtr<CefV8Value> > >* arguments, CefRefPtr<CefV8Value>* retval, CefStringBase<CefStringTraitsUTF16>* exception)getDomainUser 
   @ userService.js:50(anonymous function) 
   @ app.js:208invoke 
   @ vendor.js:22005(anonymous function) 
   @ vendor.js:21826forEach 
   @ vendor.js:17822createInjector 
   @ vendor.js:21826doBootstrap 
   @ vendor.js:19158bootstrap 
   @ vendor.js:19179angularInit 
   @ vendor.js:19073(anonymous function) 
   @ vendor.js:46495n.Callbacks.j 
   @ jquery.js:3099n.Callbacks.k.fireWith 
   @ jquery.js:3211n.extend.ready 
   @ jquery.js:3417I @ jquery.js:3433

The c# code that it should be calling...

        public void GetDomainUser(IJavascriptCallback javascriptCallback)
        {
            try
            {
                Log.Debug("Request domain user called.");

                var id = WindowsIdentity.GetCurrent();
                if (id == null)
                {
                    Log.Error("Unable to get domain user.  Not sending to browser");
                    return;
                }
                var du = new DomainUser(id.Name);
                var domainUserJson = JsonConvert.SerializeObject(du);
                Log.Debug($"DOMAIN USER:{id.Name}\t{domainUserJson}");
                javascriptCallback.ExecuteAsync(domainUserJson);
            }
            catch (Exception ex)
            {
                NotifyShellException(ex);
            }
        }

Where the call is being made in JS:
    getDomainUser() {
      var s = this;
      var defer = s._$q.defer();
      var promise = defer.promise;
      s._$log.debug(s.igUtils);
      s._$log.debug(s.igUtils.isExternalFunc("getDomainUser"));
      if (s.igUtils.isExternalFunc("getDomainUser")){
        container.getDomainUser(function(userCred) {
          defer.resolve(angular.fromJson(userCred));
        });
      } else {
        defer.reject();
      }
      return promise;
    }

More code can be provided if needed.

Thanks!

**Comment by bobpf** [comment]
Hmmm....  I was using VS remote debugging and on the off chance I deleted the DLL's from the remote machine and redeployed and everything started working again.  There must have been some type of version mismatch.

**Comment by bobpf** [comment]
Modified:
_webBrowser.RegisterJsObject("container", _cachedDataStore);
To:
_webBrowser.RegisterAsyncJsObject("container", _cachedDataStore);

And everything started working again.

**Comment by amaitland** [comment]
We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask future questions there.
