### ISSUE TITLE
Reload page sended by form

### ISSUE THREAD

**Issue by alissonrubim** [cefsharp/CefSharp#1533]
Hello.
Today i noticed this problem: when i try apply .reload() in a page that was loaded from form action, the CefSharp do nothing.

I tried set all Handlers, to try see if i can get some action inside some handler, but i do not had any success with this method.

**Comment by amaitland** [comment]
We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask your questions there.
