### ISSUE TITLE
unable to save heap snapshot

### ISSUE THREAD

**Issue by dem219** [cefsharp/CefSharp#1534]
I am able to take a heap snapshot using the chrome debug tools.  But the save option does not work (nothing happens when clicked).

I suspect this is a CEF issue, but thought I would also inquire here to see if it is a known cefsharp issue, or if there are any settings that could be used to enable this feature

**Comment by jankurianski** [comment]
We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask your questions there.
