### ISSUE TITLE
Mousewheel event does not send modifier keys

### ISSUE THREAD

**Issue by Sharon98** [cefsharp/CefSharp#1536]
#### Issue Summary
What is the expected output? What do you see instead?
I'm using the mousewheel + ctrl to zoom in and out, but the ctrlkey value for the event is always false even while I'm pressing the ctrl key. It's the same issue for the shift key.

#### Steps to Reproduce
1. To reproduce, add javascript code to your web page to show the event properties during the mousewheel event. (I'm using jquery to bind to event.
2. Observe in the console text that modifier keys are always false for the mousewheel event.

This is a bug because...zooming in and out like Chrome should be supportable
I changed two lines in CefSharp.Wpf/ChromiumWebBrowser.cs to send get the modifiers and send them. That got things working for me. Not sure if there is a good reason to have modified fixed as None.

        protected override void OnMouseWheel(MouseWheelEventArgs e)
        {
            var point = e.GetPosition(this);
      ===> var the_modifiers = e.GetModifiers(); <====
            var browser = GetBrowser();

            if (browser != null)
            {
                browser.SendMouseWheelEvent(
                    (int)point.X,
                    (int)point.Y,
                    deltaX: 0,
                    deltaY: e.Delta,
      ===>       modifiers: the_modifiers);  <====
                //modifiers: CefEventFlags.None);
            }
        }

#### Technical details
* CefSharp Version: nuget - master - latest commit:  INSERT COMMIT REF
* Operating System: Windows 10, building x86
* WinForms/WPF/OffScreen: Using WPF

**Comment by amaitland** [comment]
Please create a `PR` with your proposed changes. (When doing so please follow similar naming conventions e.g. no `_` in variable names, just `var modifiers` would be fine).

**Comment by amaitland** [comment]
Closed with #1538
