### ISSUE TITLE
Bug: Red scroll bars appearing in Cefsharp 45 with PackLoadingDisabled set to true

### ISSUE THREAD

**Issue by mariohebert** [cefsharp/CefSharp#1537]
Broken HTML, JS code, and red scrollbars are visible in the Winform web view of Cefsharp 45 when the PackLoadingDisabled settings is true. Similar to the previous issue: https://github.com/cefsharp/CefSharp/issues/598

![capture](https://cloud.githubusercontent.com/assets/7885009/12184600/377444c8-b564-11e5-8dd6-fda28af5881a.PNG)

If we don't want the dev tools, we are supposed to put this property to true. If we put false, everything is fine. 
The "locales" folder and different .pak file are in the execution path (if we refer on what is listed in the previous link). Can reproduce under X86 and X64. All libraries are coming with a Nuget package link that was set yesterday in VS.

Thanks,

**Comment by amaitland** [comment]
> If we don't want the dev tools, we are supposed to put this property to true. If we put false, everything is fine.

Known limitation of `CEF`, nothing we can control in `CefSharp`. Feel free to raise the issue on the `CEF Forum`.

http://magpcss.org/ceforum/

You should be able to leave out the dev tools resources and any locales your not using without problem.

We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask your questions there before posting on `GitHub`

**Comment by amaitland** [comment]
See also http://magpcss.org/ceforum/viewtopic.php?f=6&t=13149&p=26488

**Comment by mariohebert** [comment]
Perfect, thanks for your reply ;)
