### ISSUE TITLE
Add LoadingStateChanged To CefSharp .NET

### ISSUE THREAD

**Issue by miyakedev** [cefsharp/CefSharp#1539]
I'm Install the package's cefsharp.winforms and cefsharp.common but i don't know how add the loadingstatechanged for load scripts

And if i add the 3 references CefSharp
http://i.imgur.com/UQoBQIM.jpg

I get error : http://i.imgur.com/X3INXRq.png

help please

**Comment by amaitland** [comment]
We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask your questions there.
