### ISSUE TITLE
Render Glitch on Mouse Event WinForms

### ISSUE THREAD

**Issue by szahn** [cefsharp/CefSharp#1541]
The initial page is rendered properly and I can scroll down without any issues. However, the minute my mouse hover or clicks on an actionable form button, I get a render glitch where part of the page is rendered but scaled up.

Note that I'm running this on Windows 8.1 on a Mac laptop with retina display (high DPI).

Below is the code I'm using.

```
[STAThread]
static void Main()
{
    ChromiumLifecycle.InitChromeBrowser();
    Application.EnableVisualStyles();
    Application.SetCompatibleTextRenderingDefault(false);
    Application.Run(new Form1());
    ChromiumLifecycle.DisposeChromeBrowser();
}
```

```
public static ChromiumWebBrowser InstantiateChromeBrowser()
{
    return new ChromiumWebBrowser(sites[0])
    {
        Dock = DockStyle.Fill
    };
}
```

```
private void Form1_Load(object sender, EventArgs e)
{
    chromeBrowser = ChromiumFactory.InstantiateChromeBrowser();
    browserContainer.Controls.Clear();
    browserContainer.Controls.Add(chromeBrowser);
}
```

![2016-01-11_12-35-12](https://cloud.githubusercontent.com/assets/271732/12245816/ce317b6c-b85f-11e5-8d23-ee81ce1b2b74.png)

![2016-01-11_12-35-26](https://cloud.githubusercontent.com/assets/271732/12245817/ce32ea2e-b85f-11e5-905a-f0842a8749dc.png)

**Comment by szahn** [comment]
Had to call the following before Cef.Initialize. I had to crawl through the example code to find this out. It would be helpful to have a wiki article about High DPI issues like this

```
Cef.EnableHighDPISupport();
```

**Comment by amaitland** [comment]
> I had to crawl through the example code to find this out.

It's a relatively new method. The example was only updated days ago. https://github.com/cefsharp/CefSharp/commit/36b0b95d55849b90346590212f7ea26061fbd705

As your probably aware you would typically include an `app.manifest` with the relevant `dpiAware` attribute. Only recently discovered this wasn't working properly with newer versions of `CEF`.

I personally don't own a device with `High DPI` capabilities so testing these scenarios is not practical. If you have a chance to take the latest `CI` build from `MyGet` a spin that would be appreciated.

https://www.myget.org/F/cefsharp/

Switching to calling `Cef.EnableHighDPISupport()` in the `BrowserSubProcess` as well.

> It would be helpful to have a wiki article about High DPI issues like this

Anyone with a `GitHub` account can edit the `Wiki`, so feel free.

**Comment by amaitland** [comment]
@szahn I've had reports that when running `High DPI` the default scale factor is not always set. Was calling `Cef.EnableHighDPISupport();` enough to totally resolve your problem? Does the initial scale look correct?

**Comment by m314** [comment]
I tried `Cef.EnableHighDPISupport()`, and it made the whole browser large scale.  But at least everything is scaled the same; before the browser scale was switching back and forth with mouse events.  However, the new scale doesn't look sharp.

**Comment by m314** [comment]
> Can you reproduce the problem with the `MinimalExample`? 

I believe this is the first time that I've ever posted a question on here, so I'm not sure if you may have me confused with someone else.  I'm happy to try the minimum example, and I appreciate your help.  I was able to have correct scaling of the page using the current version `MinimalExample`.

Separately, I've noticed that high DPI support seems to make png images appear fuzzy (vs. not enabling high DPI support and instead setting a flag to disable GPU).  I'm not sure if this should be a new issue, so I posted about it on Gitter.  Thank you for your help.

**Comment by amaitland** [comment]
> I believe this is the first time that I've ever posted a question on here, so I'm not sure if you may have me confused with someone else. I'm happy to try the minimum example, and I appreciate your help. The current version MinimalExample did fix the scaling issue.

You asked your question on `Gitter`, for which I responded, then you proceeded to post here without testing the `MinimalExample` as requested.

**Comment by m314** [comment]
@amaitland I just registered for `Gitter` today.  I see there's a user in there with a similar name to mine ( `mw515`) that has been asking questions, but that's definitely not me. :)

**Comment by amaitland** [comment]
@m314 My mistake

**Comment by m314** [comment]
@amaitland Thank you.  

Also, thanks to the other Gitter users for responding to my question.  For the sake of completeness, it turns out that the fuzzy png issue is with CEF itself, not with CEFSharp.  (And it's very slight fuzziness, so I'm just going with it for now.)  Thanks for the great work you guys are doing with CEFSharp!
