### ISSUE TITLE
Feature Request - Update WinForms Example to be Per Monitor DPI Aware

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#1543]
https://emoacht.wordpress.com/2013/10/30/per-monitor-dpi-aware-in-windows-forms/
https://msdn.microsoft.com/library/windows/desktop/dn469266.aspx

**Comment by amaitland** [comment]
http://stackoverflow.com/questions/4075802/creating-a-dpi-aware-application

**Comment by amaitland** [comment]
https://gist.github.com/emoacht/468a351c9682c7033eba

**Comment by amaitland** [comment]
Reports suggest that `4k` support with current versions of `Chromium` don't set the correct scale factor.

Look at using command line argument `force-device-scale-factor=[x]`

**Comment by amaitland** [comment]
> http://www.telerik.com/blogs/winforms-scaling-at-large-dpi-settings-is-it-even-possible-

Last section of the `telerik` article has a useful example (zip file)

```c#
protected override void WndProc(ref Message m)
{
	switch (m.Msg)
	{
		//This message is sent when the form is dragged to a different monitor i.e. when
		//the bigger part of its are is on the new monitor. Note that handling the message immediately
		//might change the size of the form so that it no longer overlaps the new monitor in its bigger part
		//which in turn will send again the WM_DPICHANGED message and this might cause misbehavior.
		//Therefore we delay the scaling if the form is being moved and we use the CanPerformScaling method to 
		//check if it is safe to perform the scaling.
		case WM_DPICHANGED:
			oldDpi = currentDpi;
			currentDpi = LOWORD((int)m.WParam);

			if (oldDpi != currentDpi)
			{
				if (this.isMoving)
				{
					shouldScale = true;
				}
				else
				{
					HandleDpiChanged();
				}

				OnDPIChanged();
			}

			break;
	}

	base.WndProc(ref m);
}
```

**Comment by amaitland** [comment]
`EnableWindowsFormsHighDpiAutoResizing` was added in `.Net 4.5.2` see https://www.infoq.com/news/2014/05/DotNet-4-5-2 for details (must be added to `app.config`)

**Comment by merceyz** [comment]
This was recently done in CEF, related resources:
https://bitbucket.org/chromiumembedded/cef/issues/2313/windows-add-per-monitor-dpi-support#comment-43433039

https://bitbucket.org/chromiumembedded/cef/commits/8f26fe059b2337972bc2e6fdba6376565a6361af

**Comment by amaitland** [comment]
WinForms Example is now DPI aware using https://docs.microsoft.com/en-us/dotnet/desktop/winforms/high-dpi-support-in-windows-forms?view=netframeworkdesktop-4.8  There's a mistake in the MS Docs which was already reported at https://github.com/dotnet/docs-desktop/issues/1485
