### ISSUE TITLE
Bug: PDF not redrawing in CefSharp with WPF

### ISSUE THREAD

**Issue by sibrus** [cefsharp/CefSharp#1545]
#### Issue Summary
When I load a PDF using the CefSharp.MinimalExample.Wpf application, I just get a grey screen. If I resize the window, it draws correctly. Then if I try to interact with it (scrolling, selecting text, etc), it looks like nothing happens, and again, resizing causes it to redraw correctly. So it looks like it's working somewhere under the hood, but it's not drawing any updates.

#### Steps to Reproduce
The issue is easily reproducible using CefSharp.MinimalExample.Wpf just by changing the URL to http://www.polyu.edu.hk/iaee/files/pdf-sample.pdf or any other PDF file.

#### Technical details
* CefSharp Version: 45 release, from nuget
* Operating System: Win7x64
* x86/x64: Tried both, issue reproducible in both
* WinForms/WPF/OffScreen: Issue in WPF only, working in WinForms, OffScreen not tested

**Comment by amaitland** [comment]
@sibrus Thanks for the detailed bug report :+1: 

It's a known problem, see https://bitbucket.org/chromiumembedded/cef/issues/1689

Thankfully there's a workaround, just need to pass in the `--disable-surfaces` command line argument. 

There's a helper method that simplifies the call.
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/CefExample.cs#L86

I've updated the `MinimalExample` project see https://github.com/cefsharp/CefSharp.MinimalExample/commit/757b8edf1ef49885df63588b248a74b477bdb892
