### ISSUE TITLE
Change input value with ExecuteJavaScriptAsync dont rendering

### ISSUE THREAD

**Issue by midnait** [cefsharp/CefSharp#1547]
Hi all

CefSharp 45 Nuget, WPF, <input type="text" name="address"> in html page.

public async void OnFrameLoadEnd(object sender, FrameLoadEndEventArgs e)
{
    if (e.Frame.IsMain)
    {
        source = await Browser.GetSourceAsync(); // OK, WORKING
        if (source.IndexOf("name=\"address\"") != -1)  // OK, WORKING TOO
        {
            browser.ExecuteScriptAsync(@"alert(document.getElementsByName('address')[0].value); document.getElementsByName('address')[0].value = 'abcde'; alert(document.getElementsByName('address')[0].value);");
        }
    }
}

This show first empty alert, then show second alert with message 'abcde', but <input type="text" name="address"> still empty in page. What am I doing wrong?

Hugs

**Comment by amaitland** [comment]
We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask your questions there.
