### ISSUE TITLE
How can I clear yellow selections ?

### ISSUE THREAD

**Issue by ismailkocacan** [cefsharp/CefSharp#1548]
I'm searching text that like.
```cs
        void SearchText(string text)
        {
           WebBrowser.Find(0, text, true, false, true);
        }
```
![chrome](https://cloud.githubusercontent.com/assets/3339197/12348033/3f277088-bb6c-11e5-8b56-51061121a74d.PNG)

Is there any command available for clear selections ?
thanks

**Comment by amaitland** [comment]
We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask your questions there.
