### ISSUE TITLE
Saving the resource (jpg,swf) files using OnResourceResponse()

### ISSUE THREAD

**Issue by rover886** [cefsharp/CefSharp#1549]
Currently I am working on `cefsharp/43`. Using CefSharp I am developing an application which will browse an learning website which has interactive content in `swf` files (aprox size 1MB-5MB/swf). Business Idea (requirement) is too avoid downloading of content file every time when user visits to a particular learning lesson, application should only go once to online server and fetch the content file (swf) and once the files get downloaded show it on webpage as well as store that file to an physical location.

So next time if a user (or the same user) visits the same learning lesson then application will check for is that content file is present at physical location, if found then serve that file from local path. This part I have already done using `OnBeforeResourceLoad` but if file is not present in local path then request should go to online server (which will be done automatically if I `return false;` in `OnBeforeResourceLoad`) and after resource/content file loading is completed or response has arrived that content(swf) should get displayed on page as well as application should able to save that swf file to local location (without making second request to resource file on server).

I have checked `cefsharp/45` code which has an method `OnResourceResponse - Called on the CEF IO thread when a resource response is received.` but I didn't get how I can access resource stream from `response` object so that I can save that file, because there is no such method inside [`IResponse`](https://github.com/cefsharp/CefSharp/blob/cefsharp/45/CefSharp/IResponse.cs).

Is there any other way to make this successful or am I missing something?

**Comment by amaitland** [comment]
We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask your questions there.

**Comment by weituotian** [comment]
@amaitland how to do that?
