### ISSUE TITLE
Support for callbacks inside objects

### ISSUE THREAD

**Issue by e-larrambebere** [cefsharp/CefSharp#1550]
On the `BoundObject` class there are examples about how to pass a callback function to a method (`TestCallback`) and also how to pass a complex object (`ComplexParamObject`), however it seems that it is not possible to use callbacks inside complex objects, for example the following JavaScript object:
```javascript
var complex = {
 complete: function() {
    console.log('completed');
 },
 failed: function() {
    console.log('failed');
 }
};
```
Is going to be marshalled into a Dictionary with two elements whose values are both `null` if you call:
```javascript
bound.complexParamObject(complex);
```

Is there currently a way to pass JavaScript object that contains callbacks into a C# method?

**Comment by amaitland** [comment]
> Is there currently a way to pass JavaScript object that contains callbacks into a C# method?

Currently no. You should be able to pass multiple callbacks to the function though.

We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask any follow up questions there.
