### ISSUE TITLE
sending an email using cefsharp

### ISSUE THREAD

**Issue by ortalevi** [cefsharp/CefSharp#1551]
We've encountered the following issue:
While trying to send an email from cef window, the email wasn't sent. 
in addition, we've tried to do the same from cefsharp example and the email wasn't sent from there as well.
we've got the error  "unknown url scheme" presumably because of the "mailto" email-link.
Do you have any possible solution for this issue without upgrading the cef version?
tnx

**Comment by amaitland** [comment]
We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask your questions there. If there's a bug then we'll reopen this issue.
