### ISSUE TITLE
App crashes on some machines after CefSharp was updated to v45

### ISSUE THREAD

**Issue by DominikPalo** [cefsharp/CefSharp#1553]
I've updated CefSharp in our WPF app to the version 45 (I'm also tested it with version 47-prerelease - same problem) and I have an issue - on some machines app crashes after calling of method `Cef.Initialize()` with exception `System.IO.FileNotFoundException` (I found this exception in Windows Event Viewer). It seems that it occurs only on specific configurations - hundreds of our clients uses app without problems, but some of them cannot start app because this problem. This exception occurs in CEF library, so I can't handle it in app. We didn't have this problem with older versions of CefSharp.

**Comment by DominikPalo** [comment]
Oh, I've found that after copying files `msvcp120.dll`, `msvcr120.dll` and `vccorlib120.dll` into my app dir it works on all PC. Why these VC 2013 redistributable files are not part of CefSharp NuGet package?

**Comment by amaitland** [comment]
As per the release notes newer versions use `VC++ 2013`

https://github.com/cefsharp/CefSharp/releases/tag/v45.0.0

There's also a reference in the `Nuget Readme.txt` that appears when you upgrade the packages

https://github.com/cefsharp/CefSharp/blob/cefsharp/45/NuGet/Readme.txt#L15

**Comment by amaitland** [comment]
We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask any follow up questions there.
