### ISSUE TITLE
CefSharp 47.0.0 Released

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#1555]
Just an `FYI` for those that are interested. I've pushed the packages to `Nuget.org` they should be indexed and available within the next few hours.

https://github.com/cefsharp/CefSharp/releases/tag/v47.0.0 for details on the release.

This is a minor upgrade from `45.0.0`, a few upstream `CEF` changes and a couple of minor additions to the `API`. Should be a trivial upgrade for most.

- Requires **VC++ 2013 Redist**.
- Can change preferences at run-time (e.g. proxy settings)
- Notifications added for `OnContextCreated` and `OnFocusedNodeChanged` in the `IRenderProcessMessageHandler` handler, can now hook into `DOMContentLoaded` event
- `WPF` implementation now has a `Touch Scroll` implementation (disabled by default).

**Comment by chris-araman** [comment]
I noticed a 47.0.1 release here on GitHub, but it looks like something's gone wrong generating the corresponding NuGet packages. Is that issue known?

CefSharp.OffScreen 47.0.1 references CefSharp.Common (= 47.0.1**-CI1712**), but that version doesn't exist.
http://www.nuget.org/packages/CefSharp.OffScreen/47.0.1

The 47.0.1 versions of the CefSharp.WinForms and CefSharp.WPF packages don't seem to exist, either.

**Comment by amaitland** [comment]
> I noticed a 47.0.1 release here on GitHub, but it looks like something's gone wrong generating the corresponding NuGet packages. Is that issue known?

Ignore `47.0.1`, there's a problem and it will be replaced by `47.0.2`

> The 47.0.1 versions of the CefSharp.WinForms and CefSharp.WPF packages don't seem to exist, either.

They have been delisted from `Nuget.org`.

**Comment by amaitland** [comment]
`47.0.2` packages should appear on `Nuget.org` shortly. Only relevant to upgrade if you using `Drag and Drop` with the `WPF` control. Anyone else can happily stay on `47.0.0`.

**Comment by chris-araman** [comment]
Understood. Thanks!
