### ISSUE TITLE
Websocket not working in CEFsharp 47

### ISSUE THREAD

**Issue by martijn189** [cefsharp/CefSharp#1558]
Dear reader,

I am trying to get my websocket application to work in a VB.net project that is using CEFSharp. Before 5 minutes ago i was using version 45, now updated to version 47. To be clear, i never got it working, also not with previous version. If i load the HTML page in my chrome browser it works.

I am using socket.io with a YII framework project. I can see 1 difference, the chrome browser sends cookie headers with the request, CEFSharp does not send it. I have read that older versions of CEF did not handle the cookies for websockets, but this would be resolved by now??

Do i need anything to be enabled am i missing something?

**Comment by martijn189** [comment]
I think there is something else wrong here, firefox and Android Chrome browser do also not work.

**Comment by amaitland** [comment]
> I have read that older versions of CEF did not handle the cookies for websockets, but this would be resolved by now??

See https://bitbucket.org/chromiumembedded/cef/issues/1684/add-websocket-ws-wss-as-default-schemes

Follow up questions please ask on [Gitter Chat](https://gitter.im/cefsharp/CefSharp).
