### ISSUE TITLE
OutOfMemoryException with resolution 4000 x 4000

### ISSUE THREAD

**Issue by Cristanov** [cefsharp/CefSharp#1559]
Hi
I'm using cefsharp wpf v. 41.0.1 (win 7, 32 GB ram) and I need to show few web pages on big screen with reslution above 4000 x 4000 but quite often I have 
"System.OutOfMemoryException: Insufficient memory to continue the execution of the program."

Is there some known issues or limitation in cefsharp with so high resolution?

**Comment by amaitland** [comment]
We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask your questions there. If there's a bug then we'll reopen this issue.
