### ISSUE TITLE
Tiny fonts in 47

### ISSUE THREAD

**Issue by jamespearce2006** [cefsharp/CefSharp#1560]
I've just upgraded to CefSharp 47, and I'm seeing a very strange issue with my app. The default font size is miniscule (1px high):

![image](https://cloud.githubusercontent.com/assets/12157851/12610413/8f9197ca-c4df-11e5-8a39-c8bfe7af4650.png)

I don't see this problem in the WPF sample app, but I don't see anything in my own app that would cause this problem (no font settings, DPI settings, or anything like that).

Any ideas what might be causing this?

**Comment by jamespearce2006** [comment]
I found the problem, in case anyone else is seeing the issue. I was missing the locales directory (which I've never needed before).

**Comment by bmuenzenmeyer** [comment]
For anyone encountering this issue - it appears to happen to any CSS properties you size with rem units of measure, in my case, pretty much everything.

**Comment by amaitland** [comment]
> For anyone encountering this issue - to clarify the behavior - it appears to happen to any CSS properties you size with rem units of measure, in my case, pretty much everything.

Sounds like your problem is different to the problem described by the `OP`.

**Comment by AdamDotNet** [comment]
Adding in the locales folder and paks saved my life from 1px tall text too. (WinForms) Thank you!

**Comment by bmuenzenmeyer** [comment]
FYI only. This issue occurred again on update.

![rem_sizing](https://cloud.githubusercontent.com/assets/298435/17743777/932b9dec-646a-11e6-8e33-1b8322d2e9f6.gif)


I still think it has something to do with REM sizing.

Still digging.

**Comment by amaitland** [comment]
> locales/
    Directory containing localized resources used by CEF, Chromium and Blink. A
    .pak file is loaded from this directory based on the CefSettings.locale
    value. Only configured locales need to be distributed. If no locale is
    configured the default locale of "en-US" will be used. Without these files
arbitrary Web components may display incorrectly.

https://github.com/cefsharp/cef-binary/blob/0a9648f40e185904adeda254858607a1ccc3dadf/README.txt#L93

`Locales` are conditionally optional, I recommend at least having the `.pak` for your region and `en-US.pak`. The whole `locales` directory will be copied to the `bin` folder by the `nuget target`.

**Comment by mbrn** [comment]
copying locales solved our problem. Thank you for solution

**Comment by paniclabde** [comment]
Had the same issue today and the locales directory was the problem. Thanks for the solution!

**Comment by Schifer** [comment]
I'am having this issue but locales and paks aren't working too...
