### ISSUE TITLE
Disable pdf viewer, download pdf instead

### ISSUE THREAD

**Issue by Krcmi** [cefsharp/CefSharp#1563]
How can I disable pdf viewer ? I can do this by settings.Plugins = CefState.Disabled; but this will trigger that I cannot download that pdf. 

Thank you 
Petr

**Comment by jankurianski** [comment]
We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask your questions there.

**Comment by amaitland** [comment]
For reference you can use the `disable-pdf-extension` command line argument in versions `45.0.0` and above.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/CefExample.cs#L56
