### ISSUE TITLE
Make CefSharp use Dependencies in custom folder

### ISSUE THREAD

**Issue by khoaakt** [cefsharp/CefSharp#1567]
As the title, t think it would be better to make cefsharp load dependencies in a custom folder (ex: "app_path\cef") because it is easier to update cef-binary when update my web browser.

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/issues/601#issuecomment-93593017

We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask your questions there.
