### ISSUE TITLE
CefSharp 47.0.2 does not support JW Player

### ISSUE THREAD

**Issue by justin-lopez** [cefsharp/CefSharp#1568]
How would I be able to support `JW Player` inside of the latest CefSharp. Back in CefSharp `41` it works perfect and everything loads but when you update it to the latest it provides you with an error.

Error in player:
No playable sources found.

How may I support `JW Player`?

**Comment by amaitland** [comment]
We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask your questions there.
