### ISSUE TITLE
Disposed of e.Frame.IsMain Issue.  Upgrading from CEF 37 to 47

### ISSUE THREAD

**Issue by daveaton** [cefsharp/CefSharp#1569]
I am upgrading from CEF 37 to the latest version of Master 25 Jan 2016 and every time I try to use this line of code  http://screencast.com/t/On08ElLLr   for some reason e.Frame.IsMain is disposed.

Was there an issue on this?  I noticed that none of your examples use this and when I try to add it to the examples it works.  I can't figure out why I have this issue.  If I comment out this line everything works again.  Has anyone else had this issue ?

I am running .Net 4.5 on Windows 10

**Comment by amaitland** [comment]
We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask your questions there.
