### ISSUE TITLE
can support mp3 and  mp4

### ISSUE THREAD

**Issue by qidongxi2012** [cefsharp/CefSharp#1570]
now,  i  have a question 
why  my cef app  can play web page with mp3 or mp4 ,
why why why?
please help me 
thank you

**Comment by qidongxi2012** [comment]
can't

**Comment by amaitland** [comment]
Duplicate of #1479

**Comment by Evgest** [comment]
MP3 is open now - [https://www.iis.fraunhofer.de/en/ff/amm/prod/audiocodec/audiocodecs/mp3.html](https://www.iis.fraunhofer.de/en/ff/amm/prod/audiocodec/audiocodecs/mp3.html) is it possible to include it in cefsharp?

**Comment by jankurianski** [comment]
bq. is it possible to include it in cefsharp by default?
In the future, yes.  We have to wait for Chromium to include it, then CEF to be re-built, and then we need a contributor to make a new CefSharp release.  I have updated #1479 with the details.
