### ISSUE TITLE
Feature Request - Upgrade to .Net 4.5.2

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#1572]
As support for `.Net 4.0` has officially ended, it's time to upgrade.

https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/

Whilst this is a breaking change, I think it's a necessary one.

**Comment by amaitland** [comment]
@perlun @jankurianski @rlmcneary2 Anyone have comments on this?

**Comment by jankurianski** [comment]
So the proposal is to re-target `CefSharp` from `4.0` to `4.5.2`?  Hopefully we don't need to use any `4.5`-specific APIs, so I will be able to re-target to `4.0` for manual builds, so I am happy :smile:

I still have `2%` of customers on `XP` and can't move just yet :cry:  But it does make sense for the project to stay up-to-date. :+1:

**Comment by jankurianski** [comment]
I should clarify that by targetting `.NET 4.5` or higher means that the program will not run on `XP`, because `4.5` and higher will refuse to install on `XP`.  So that changes `XP` status from "unsupported" to "definitely does not work".

**Comment by amaitland** [comment]
> So the proposal is to re-target CefSharp from 4.0 to 4.5.2? Hopefully we don't need to use any 4.5-specific APIs, so I will be able to re-target to 4.0 for manual builds, so I am happy :smile:

No need to change the `API` in the short term. Haven't looked in any detail, I imagine we can change the build script to change the framework target if required.

> I still have 2% of customers on XP and can't move just yet :cry:

I hope your charging them extra!

> I should clarify that by targetting .NET 4.5 or higher means that the program will not run on XP, because 4.5 and higher will refuse to install on XP. So that changes XP status from "unsupported" to "definitely does not work".

It does mean that `XP` support goes away, that doesn't impact me personally. I understand that it will others.

Targeting an unsupported framework doesn't make much sense to me. If the need to stay with `4.0` is high enough then we can leave things be for now. I do think we should set a date though for when the upgrade happens.

**Comment by perlun** [comment]
> Targeting an unsupported framework doesn't make much sense to me. If the need to stay with 4.0 is high enough then we can leave things be for now. I do think we should set a date though for when the upgrade happens.

As for our  use base:

- Some of our customers use a newer version of the target application, which is running on .NET 4.5 (and also pegged to x86, which makes things simple in terms of x86 vs x64).
- Others use an older version, which runs on .NET 4.0. No idea if some of them have 4.5 installed or not (I understand .NET 4 code can run successfully on .NET 4.5 framework installs, in which case this wouldn't really be a biggie)
- The target application is a 3rd party platform, not under our control. So we cannot in this case simply enforce users to update. They would perhaps even have to pay extra money to the ERP vendor in that case (target application = an ERP frontend in this case)
- Many of the users are running it on Windows Server 2003.

So, for us, enforcing an upgrade to 4.5 at this stage would possibly make it hard/impossible to embrace newer CefSharp versions for our use case. Not saying that this should force the restrictions onto the project - it will have to be done sooner or later, it's more a matter of "when" I guess.

**Comment by ray007** [comment]
Talking about ending support for `.NET 4.0` at the same time Microsoft does seems a bit hasty to me.

**Comment by amaitland** [comment]
> Talking about ending support for .NET 4.0 at the same time Microsoft does seems a bit hasty to me.

Maybe, running any business critical application on an unsupported platform/framework is craziness in my opinion.

**Comment by ray007** [comment]
> > Talking about ending support for .NET 4.0 at the same time Microsoft does seems a bit hasty to me.

> Maybe, running any business critical application on an unsupported platform/framework is craziness in my opinion.

I agree with you, but I can't force our customers to upgrade, and I'm sure I'm not the only one with that problem...

**Comment by amaitland** [comment]
`Nuget` does support targeting multiple platforms, if someone was willing to contribute a solution we could potentially provide both options in the one package.

https://docs.nuget.org/create/enforced-package-conventions

**Comment by amaitland** [comment]
http://brian-federici.com/blog/2013/4/17/automatically-target-multiple-frameworks-in-your-nuget-package

**Comment by amaitland** [comment]
As `Chrome` is dropping support for `Windows XP` in `April` I think it's reasonable to follow suite. Soon as the relevant `Chromium` version no longer compiles/builds/runs on `XP` I plan on upgrading to `.Net 4.5.2`

- Anyone wishing to run on `Windows XP` will need to use an older version regardless. 
- Anyone wishing to continue to target `.Net 4.0` will need to contribute time/code to upgrading the `Nuget` packages to support both, and likely `pre-processor` defines. to provide the support your looking for.

https://chrome.googleblog.com/2015/11/updates-to-chrome-platform-support.html

**Comment by jankurianski** [comment]
Sounds reasonable :+1:

**Comment by rlmcneary2** [comment]
> As Chrome is dropping support for Windows XP in April I think it's reasonable to follow suite. Soon as the relevant Chromium version no longer compiles/builds/runs on XP I plan on upgrading to .Net 4.5.2

Agreed.

**Comment by amaitland** [comment]
> Starting with this release branch Windows XP, Windows Vista, and Mac OS X 10.6, 10.7, and 10.8 are no longer supported. See here for the original end-of-support announcement. Supplementary announcements are available here for Windows and here for OS X.

http://magpcss.org/ceforum/viewtopic.php?f=4&t=13995#p30603

Appears as the `Chromium` Devs didn't waste any time removing `Windows XP` support from the code base. The `meta tracking issue` is https://bugs.chromium.org/p/chromium/issues/detail?id=579196

Tagging this as `51` as `49` will be the last version of `CEF` that will actually run on `Windows XP`.

**Comment by amaitland** [comment]
> There are no plans to provide extended support for 2623 branch.

http://magpcss.org/ceforum/viewtopic.php?f=6&t=14132
