### ISSUE TITLE
WinForms process won't exit when browser is used on non main thread

### ISSUE THREAD

**Issue by MihaMarkic** [cefsharp/CefSharp#1573]
So I have this code below. Basically is a simple as it gets MdiContainer with browser hosted in MDI child form. The only difference is that container (and thus child as well) are running in a non-main thread.
The Shutdown is called and method is exited but the process won't die.
If I avoid using arbitrary thread (comment t.Start() and uncomment Run()) then it works just fine.

Any idea what is holding process alive or better, how to solve it?

```
static class Program {
        [STAThread]
        static void Main()
        {
            CefSharpSettings.ShutdownOnExit = false;
            Cef.Initialize();
            ThreadStart tstart = new ThreadStart(Run);
            Thread t = new Thread(tstart);
            t.SetApartmentState(ApartmentState.STA);
            t.Start();
            //Run();
        }

        public static void Run()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new Form2());
            Cef.Shutdown();
        }
    } 
```

.... Form2 (MdiContainer)

```
protected override void OnLoad(EventArgs e)
        {
            if (!DesignMode)
            {
                Form1 f = new Form1();
                f.MdiParent = this;
                f.Show();
            }
            base.OnLoad(e);
        }
```

.... Form1 (mdi child)

```
public Form1()
        {
            InitializeComponent();
            browser = new ChromiumWebBrowser("www.google.com")
            {
                Dock = DockStyle.Fill
            };
            Controls.Add(browser);
        }

        protected override void OnClosed(EventArgs e)
        {
            Controls.Remove(browser);
            browser.Dispose();
            base.OnClosed(e);
        }
``

**Comment by amaitland** [comment]
`Initialize` and `Shutdown` must be called on the same `Thread`.

**Comment by MihaMarkic** [comment]
Ah, right. So, if I call Shutdown on source thread it should work? Will try it immediately.

**Comment by MihaMarkic** [comment]
Dang, silly me. I read it before but then failed to do it on correct thread. Thanks for immediately noticing.

**Comment by MihaMarkic** [comment]
Just another remark. In my case, 

`CefSharpSettings.ShutdownOnExit = false;`

should be set before initialize (or probably just before browser creation). If true, the process will hang.

**Comment by amaitland** [comment]
> should be set before initialize (or probably just before browser creation). If true, the process will hang.

Before creating the first instance of a `ChromiumWebBrowser` should cover it, though before initialize is called is probably an easier guideline to follow :+1:

**Comment by MihaMarkic** [comment]
Yes, that's exactly what I thought :)
