### ISSUE TITLE
WinForms browser has to be removed from Controls before dispose

### ISSUE THREAD

**Issue by MihaMarkic** [cefsharp/CefSharp#1574]
I've found out that when using ChromiumWebBrowser on a (Win)Form, one should remove it from Controls collection before calling browser.Dispose().
If that's not the case then the MDI container or the form (when not a MDI child) will just close. Looks like WM_CLOSE is passed to the main form in such case for some reason. Not sure if this is documented anywhere.

Repro code:

```
        private ChromiumWebBrowser browser;
        public Form1()
        {
            InitializeComponent();
            browser = new ChromiumWebBrowser("www.google.com")
            {
                Dock = DockStyle.Fill
            };
            Controls.Add(browser);
        }

        private void button1_Click(object sender, EventArgs e)
        {
            //Controls.Remove(browser);
            browser.Dispose();
        }
```

**Comment by amaitland** [comment]
By default `CEF` will attempt to close your form, this is known, not sure if it's written down anywhere. You can implement `ILifespanHandler.DoClose` and ask it politely not to (`return true`).

https://github.com/cefsharp/CefSharp/blob/master/CefSharp/ILifeSpanHandler.cs#L109

**Comment by MihaMarkic** [comment]
Hi Alex,

Do you see any differences in the two approaches? Better/safer to use ILifeSpanHandler?

**Comment by amaitland** [comment]
> Do you see any differences in the two approaches? Better/safer to use ILifeSpanHandler?

Either should be fine. Typically I'd remove the control or it's parent, then `Dispose` the control that was removed. e.g. If the `ChromiumWebBrowser` is on a tab control, remove the tab control, then `Dispose` of the tab control, the `ChromiumWebBrowser` instance will be disposed. In general `WinForms` cleans up after it's self pretty well, it will call `Dispose` on everything eventually. Much nicer than `WPF`!

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.WinForms.Example/BrowserForm.cs#L137

The documentation of `DoClose` is long, if you end up running into problems it's worth a read. https://github.com/cefsharp/CefSharp/blob/master/CefSharp/ILifeSpanHandler.cs#L97

**Comment by MihaMarkic** [comment]
Thanks! I'll just clean up normally for now.
