### ISSUE TITLE
Redirecting to Custom Scheme - err_too_many_redirects

### ISSUE THREAD

**Issue by Coul92** [cefsharp/CefSharp#1575]
I am using CefCustomScheme for redirecting requests from https://... to my custom scheme local://... to handle requests and replace responses by local content (also I am using command line arg "allow-running-insecure-content" to allow replace https-content to custom content). When I am using CefSharp.WinForms 45.0, it's ok, but in CefSharp.WinForms 47.0.2 I am getting net::err_too_many_redirects in dev tools console and my images are empty. I tried to disable caching, but it doesn't helps to me. How can I allow redirects?

**Comment by Coul92** [comment]
Maybe there is another way for handling requests and replacing responses?

**Comment by amaitland** [comment]
> CefSharp.WinForms 45.0, it's ok, but in CefSharp.WinForms 47.0.2 I am getting net::err_too_many_redirects in dev tools console and my images are empty. I tried to disable caching, but it doesn't helps to me. How can I allow redirects?

In `CefSharp` terms version `47` is a minor release, only a few things added. It's likely something changed in `CEF` or the `Chromium` version that it's based off.

If you wish to follow this up then searching through the `CEF Issue Tracker` or posting on `ceforum` is likely your next action.

https://bitbucket.org/chromiumembedded/cef
http://magpcss.org/ceforum/index.php

You could also compare the branches if you'd like,the changes are relatively small, would take about 10mins to go through everything that's changed.

See https://github.com/cefsharp/CefSharp/compare/cefsharp/45...cefsharp/47

--
Your easiest solution is likely to ignore redirecting requests to a local scheme, instead implement `IResourceHandlerFactory` and serve your local content on a per request basis (you can intercept any request that's made). See https://github.com/cefsharp/CefSharp/commit/072ca4cc978b157507467bbac916d7b96b4f06c5 for an example.

**Comment by amaitland** [comment]
Any follow up questions please ask them on [Gitter Chat](https://gitter.im/cefsharp/CefSharp).
