### ISSUE TITLE
SSL INFO

### ISSUE THREAD

**Issue by okatip1** [cefsharp/CefSharp#1576]
I want to get **ISslInfo ** information from a valid and geniune https site. How can I get this?

OnCertificateError method is calling only if https site certificate is not valid.

As a result, I want to this by cefsharp without extra httpwebrequest:

                **HttpWebRequest request = (HttpWebRequest)WebRequest.Create(browser.Address);
                HttpWebResponse response = (HttpWebResponse)request.GetResponse();**                                               response.Close();

                X509Certificate cert = request.ServicePoint.Certificate;
                X509Certificate2 cert2 = new X509Certificate2(cert);

                string cn = cert2.GetIssuerName();
                string cedate = cert2.GetExpirationDateString();
                string cpub = cert2.GetPublicKeyString();
                X509Certificate2UI.DisplayCertificate(cert2);

**Comment by amaitland** [comment]
`CEF` currently only exposes SSL information when there's an error. There is no method to retrieve the certificate.

Needs to be implemented in `CEF` before it can be implemented in `CefSharp`.

**Comment by okatip1** [comment]
Thank you @amaitland
