### ISSUE TITLE
GetAuthCredentials doesnt work

### ISSUE THREAD

**Issue by okatip1** [cefsharp/CefSharp#1577]
When I try to enter a ftp site GetAuthCredentials method is not calling.

FTP Site URL: ftp://waws-prod-hk1-013.ftp.azurewebsites.windows.net

When I try the url on chrome or firefox, the browsers show me a prompt box.

How can I solve this?

**Comment by amaitland** [comment]
Again, it's an issue with `CEF` 

https://bitbucket.org/chromiumembedded/cef/issues/1794/ftp-sites-requiring-authentication-do-not

Changes will be in the next version (not sure when that will be). You can upgrade manually if you should choose to build your own version in the short term.

Any follow up questions please ask them on [Gitter Chat](https://gitter.im/cefsharp/CefSharp).

**Comment by okatip1** [comment]
Thank you @amaitland
