### ISSUE TITLE
Use CefSharp on Embedded devices

### ISSUE THREAD

**Issue by galvesribeiro** [cefsharp/CefSharp#1578]
Hello, great job!

We have a small ARM device that runs Linux and Mono. Currently the UI of the device is made by a small C# framework that we developed internally using linux framebuffer as its backend for draw. There is no X window available on the device, we write to libCairo which gives us the byte[] and in turn we write to /dev/fb framebuffer directly.

We are looking to replace this UI Framework with some HTML/CSS/JS based system so it can be broadly used by web developers. 

So my question is: Is there a way to run CefSharp without a X System where we have just a framebuffer? Also does it work on Mono and ARM?

Thanks!

**Comment by amaitland** [comment]
> So my question is: Is there a way to run CefSharp without a X System where we have just a framebuffer? Also does it work on Mono and ARM?

`CefSharp` runs on `Windows` only, it requires `Visual C++` which means their is no support for other platforms (or `Mono`).

Any follow up questions please ask them on [Gitter Chat](https://gitter.im/cefsharp/CefSharp).
