### ISSUE TITLE
CefSharp.Core assembly loading issue

### ISSUE THREAD

**Issue by alexw668** [cefsharp/CefSharp#1579]
Hi,

I developed a WinForm app using CefSharp and it's working in my development machine (running Windows Server 2012 with Visual Studio 2013 installed). I packaged the entire output folder and deployed the package to another machine running the identical OS, but when I ran my app, it crashes with the error "Could load file or assembly 'CefSharp.core.dll' or one of its dependencies. The specified module could not be found". 

In my dev environment, I got the CefSharp package via NuGet (containing cef.redist.x86.3.2526.1362, CefSharp.Common.47.0.0, and CefSharp.WinForms.47.0.0). In my output folder (and package for deployment) all DLL files, exe files, PAK files, BIN files, and icudtl.dat are included. I just can't figure out what dependencies it still requires when running it in a deployed environment. Like I said, both my dev machine and deployment target machine are running the identical OS (Windows Server 2012) with the same .NET installed. Does it require anything from Visual Studio related assemblies (like assemblies in C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework)?

Could any of you be kind enough to shed some light on me how I can get my app running in machines other than my dev machine?

Thanks,
Alex

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/blob/cefsharp/47/NuGet/Readme.txt#L19

We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask your questions there.
