### ISSUE TITLE
Opening cefsharp browser from a external html file or a link

### ISSUE THREAD

**Issue by okatip1** [cefsharp/CefSharp#1580]
It is not about cefsharp maybe, I'm not sure but, I have to ask,

I compiled the cefsharp and did a setup file from it. I installed the my custom browser on my windows 7 64 bit pc and I made my custom browser, the default browser. There is not problem until here. It runs perfectly when I run the browser.exe.

Problem is:

When I clicked a local html file or a link like that this picture(http://4.1m.yt/6GtQvvR.png), The browser.exe run but cannot open, returns error. Error is "It cannot load cefsharp.dll, cefshap.core.dll ..., all cefsharp dlls"

**Comment by amaitland** [comment]
Please ask your questions on [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Ideally only verified bugs will be created on `GitHub`
