### ISSUE TITLE
InternetQueryOption  failed  in ProxyConfig.cs

### ISSUE THREAD

**Issue by lashanchenqi** [cefsharp/CefSharp#1581]
![Uploading 1.jpg…]()

My  Environment   is ：Windows 7  64 bit   using Visual studio 2015 .  

A  Win32Exception is thrown  when I run “CefSharp.WinForms.Example”  which downloaded from this project.

It seems  that  “InternetQueryOption”  execution  failure that  leads to this Win32Exception.
Detail codes are  below,  what causes it  and how to fix it ？  Thank you in advance !

 ==========================code begin=====================
 buffer = Marshal.AllocHGlobal(bufferLength);

 if (InternetQueryOption(IntPtr.Zero, InternetOptionProxy, buffer, ref bufferLength))
  {
        var ipi = (InternetProxyInfo)Marshal.PtrToStructure(buffer, typeof(InternetProxyInfo));
        return ipi;
  }
  {
       throw new Win32Exception();
  }
 ==========================code end=====================

**Comment by amaitland** [comment]
We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask your questions there.
