### ISSUE TITLE
OffScreen Parallel Screenshot Application Crash

### ISSUE THREAD

**Issue by campersau** [cefsharp/CefSharp#1583]
I want to create screenshots from the OffScreen browser. This does work if I use only one `ChromiumWebBrowser` but if I run the code in parallel with multiple `ChromiumWebBrowser`s the application crashes without any exception message.

Here is my test program to reproduce the issue (maybe you have to run it multiple times to crash the application):
https://gist.github.com/campersau/ba64cf30b10e08077b6c#file-program-cs

Here is the output from `windbg.exe`:
https://gist.github.com/campersau/ba64cf30b10e08077b6c#file-windbg-log
(I don't really know how to use it. I just clicked `Open Executeable...`)

The Windows Eventviewer also logs an `Application Error`:
```
Name der fehlerhaften Anwendung: CefSharp.Offscreen.ScreenshotTest.vshost.exe, Version: 14.0.23107.0, Zeitstempel: 0x559b788a
Name des fehlerhaften Moduls: libcef.dll, Version: 3.2526.1362.0, Zeitstempel: 0x56710443
Ausnahmecode: 0xc0000005
Fehleroffset: 0x000f4260
ID des fehlerhaften Prozesses: 0x85f8
Startzeit der fehlerhaften Anwendung: 0x01d162611dcf16b6
Pfad der fehlerhaften Anwendung: P:\CefSharp.Offscreen.ScreenshotTest\bin\x86\Debug\CefSharp.Offscreen.ScreenshotTest.vshost.exe
Pfad des fehlerhaften Moduls: P:\CefSharp.Offscreen.ScreenshotTest\bin\x86\Debug\libcef.dll
Berichtskennung: 79508475-0869-4ae2-a545-5437967def57
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
```

Sometimes I can see the `AccessViolationException` in Visual Studio see:
https://gist.github.com/campersau/ba64cf30b10e08077b6c#file-accessviolationexception

Or maybe I just configured CefSharp wrong?

---

Tested with CefSharp Versions:
- 45 x68
- 45 x64
- 47 x86
- 47 x64.

Environment:
```
> systeminfo
                                                                              
Hostname:                                      xxx
Betriebssystemname:                            Microsoft Windows 10 Pro
Betriebssystemversion:                         10.0.10586 Nicht zutreffend Build 10586
Betriebssystemhersteller:                      Microsoft Corporation
Betriebssystemkonfiguration:                   Mitglied der Domäne/Arbeitsgruppe
Betriebssystem-Buildtyp:                       Multiprocessor Free
Registrierter Benutzer:                        xxx
Registrierte Organisation:
Produkt-ID:                                    00330-80000-00000-AA209
Ursprüngliches Installationsdatum:             14.11.2015, 01:26:19
Systemstartzeit:                               02.02.2016, 09:37:03
Systemhersteller:                              Dell Inc.
Systemmodell:                                  Latitude 6430U
Systemtyp:                                     x64-based PC
Prozessor(en):                                 1 Prozessor(en) installiert.
                                               [01]: Intel64 Family 6 Model 58 Stepping 9 GenuineIntel ~2601 MHz
BIOS-Version:                                  Dell Inc. A10, 21.10.2015
Windows-Verzeichnis:                           C:\WINDOWS
System-Verzeichnis:                            C:\WINDOWS\system32
Startgerät:                                    \Device\HarddiskVolume1
Systemgebietsschema:                           de;Deutsch (Deutschland)
Eingabegebietsschema:                          de;Deutsch (Deutschland)
Zeitzone:                                      (UTC+01:00) Amsterdam, Berlin, Bern, Rom, Stockholm, Wien
Gesamter physischer Speicher:                  16.288 MB
Verfügbarer physischer Speicher:               4.505 MB
Virtueller Arbeitsspeicher: Maximale Größe:    35.360 MB
Virtueller Arbeitsspeicher: Verfügbar:         5.653 MB
Virtueller Arbeitsspeicher: Zurzeit verwendet: 29.707 MB
Auslagerungsdateipfad(e):                      C:\pagefile.sys
Domäne:                                        xxx
Anmeldeserver:                                 \\xxx
Hotfix(es):                                    7 Hotfix(e) installiert.
                                               [01]: KB3105211
                                               [02]: KB3116900
                                               [03]: KB3120677
                                               [04]: KB3124200
                                               [05]: KB3124262
                                               [06]: KB3124263
                                               [07]: KB3133431
Netzwerkkarte(n):                              3 Netzwerkadapter installiert.
                                               [01]: TAP-Windows Adapter V9
                                                     Verbindungsname: Ethernet 3
                                                     Status:          Medien getrennt
                                               [02]: Dell Wireless 1601 802.11 a/g/n Adapter
                                                     Verbindungsname: WiFi
                                                     Status:          Medien getrennt
                                               [03]: Intel(R) 82579LM Gigabit Network Connection
                                                     Verbindungsname: Ethernet
                                                     DHCP aktiviert:  Ja
                                                     DHCP-Server:     x.x.x.x
                                                     IP-Adresse(n)
                                                     [01]: x.x.x.x
                                                     [02]: x:x:x:x:x:x
                                                     [03]: x:x:x:x:x:x
                                                     [04]: x:x:x:x:x:x
Anforderungen für Hyper-V:                     Erweiterungen für den VM-Überwachungsmodus: Ja
                                               Virtualisierung in Firmware aktiviert: Ja
                                               Adressübersetzung der zweiten Ebene: Ja
                                               Datenausführungsverhinderung verfügbar: Ja

```

<sub>Sorry for german logs..</sub>

**Comment by amaitland** [comment]
On an unrelated note your application will never exit cleanly as you never call `Cef.Shutdown()`.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.OffScreen.Example/Program.cs#L38

Without looking into this in any detail your code is unnecessarily complex, it would be worth trying to simplify it, remove the unnecessary `ContinueWith`, just write the image in the task (no benefit for a `ContinueWith`). Is there a reason your trying to set the `ZoomLevel` to `0.0`? It's known to be problematic when there has been no `Url` loaded.

**Comment by campersau** [comment]
Yes, this is intended since this code runs inside of a windows service which should never exit (Server Application).
This would only be possible if the code would run inside of another `AppDomain`. But it currently does not.

We wanted to add CefSharp as an option for taking screenshots of webpages since it uses a newer rendering engine than [`HtmlCapture.Net`](http://www.polestarsoft.com/products/htmlcapture-net/). And I saw that we can set the `ZoomLevel` in CefSharp too, so for demo purposes I just called it with `0.0`.
In the real code we would do something similar with `ContinueWith` since we have multiple rendering engines for taking screenshots. Every rendering engine is in his own class and just implements the `public async Task<Bitmap> CreateImage(string html, Size size)` method.

**Comment by amaitland** [comment]
> Yes, this is intended since this code runs inside of a windows service which should never exit (Server Application).

You should always call `Shutdown`, otherwise the service won't exit cleanly when stopped.

> This would only be possible if the code would run inside of another AppDomain. But it currently does not.

Currently not possible.

**Comment by amaitland** [comment]
> In the real code we would do something similar with ContinueWith since we have multiple rendering engines for taking screenshots.

I'd suggest going with the simpler option in this case, just subscribing to the event and executing the calls, there is unlikely any benefit in `awaiting` that result.

Anyway, the parallel scenario is not one that I've seen or attempted for the `OffScreen` project. You'd be best to try execute your code in the context of the actual `CefSharp` project, you'll get better debugging information. (You may need to download the `CEF` release symbols to get a better stack trace though).

**Comment by campersau** [comment]
Thank you for the information. I will try to do that and make the screenshots non parallel for now.

FYI: running multiple `ChromiumWebBrowser` in parallel and executing javascript does work without exceptions or crashes. It is just the screenshots which are not working.

**Comment by amaitland** [comment]
> Thank you for the information. I will try to do that and make the screenshots non parallel for now.

Keep digging by all means, it's probably something very trivial.

> FYI: running multiple ChromiumWebBrowser in parallel and executing javascript does work without exceptions or crashes. It is just the screenshots which are not working.

Interesting!

**Comment by amaitland** [comment]
If your interested it might be worth trying your code again using the latest `master`. (remember to add `Cef.Shutdown` otherwise it won't exit cleanly).

**Comment by campersau** [comment]
Thank you for the update.
I added `Cef.Shutdown` and pulled the latest `master`. Now it does not crash as often as before. And sometimes even a run with 40 "parallel" browsers did work without crashing.

I will try to debug this more over the weekend.

**Comment by amaitland** [comment]
Just adding a small delay before disposing of the `ChromiumWebBrowser` (just before the closing brace for the `using` statement). Say `100ms`.

**Comment by campersau** [comment]
Wow this works great! No crashes so far. Thank you for that suggestion.

**Comment by nico87** [comment]
I would like to provide a little more information about running the OffscreenBrowser in parallel inside different threads.

I'm using it inside some longrunning Task instances and I can tell that they do work without deadlocks nor crashes. They are **locking each other**, though. Especially when using LoadHtml.
To me, it seems a default behavior of CEF.

If you need to speed up the browser processing, you may disable the unused features passing a custom ``BrowserSettings`` instance to the browser constructor. It worked quite a bit in my case.

**Comment by amaitland** [comment]
> If you need to speed up the browser processing, you may disable the unused features passing a custom BrowserSettings instance to the browser constructor. It worked quite a bit in my case.

Not sure which features your referring to. If you wish total separation then use a unique `RequestContext` for each instance. By default there is a `Global Request Context` which is shared between instances.

**Comment by nico87** [comment]
> Not sure which features your referring to.

I mean the ones that you can disable via the `BrowserSetttings` class, such WebGL. If you don't need it, you may disable to get a faster rendering, at least in my case. Another thing that you may disable is the LocalStorage.

> By default there is a Global Request Context which is shared between instances.

That's interesting. I tought there was a different context for any instance by default. Thank you for your suggestion!

**Comment by amaitland** [comment]
> I mean the ones that you can disable via the BrowserSetttings class, such WebGL. If you don't need it, you may disable to get a faster rendering, at least in my case. Another thing that you may disable is the LocalStorage.

If you don't care about `WebGL` then there are some command line arguments that will speed up performance. 

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/CefExample.cs#L63

**Comment by amaitland** [comment]
> Wow this works great! No crashes so far. Thank you for that suggestion.

Anything else before closing this?

**Comment by campersau** [comment]
No, just want to mention that this also works with version `45.0.0` of CefSharp.
