### ISSUE TITLE
Correct handle oncontextmenu

### ISSUE THREAD

**Issue by DonSleza4e** [cefsharp/CefSharp#1585]
first of all, sorry for bad english, and I will try to explain deeply to make sure you understand my problem

Version 47.0.2, wpf

1) I don't have a control on source html
2) Html page is a chat. User names in chat has own context menus. When I press right mouse button on user name in regular browser like Chrome - page renders own context menu, and Chrome does not show default context menu. But CEF **shows** default context menu (and hiding custom rendered context menu by html page) - this is a problem.

Sample html code:
`private [ <span oncontextmenu="return OpenMenu(event)">UserName</span> ]`

Sample JS code:
```
function OpenMenu(evt){
... rendering custom context menu...
return false;
}
```

3) I tried to manually handle context menus on user names in chat.
I assigned MenuHandler for my wpf webbrowser. When I click somewhere at page, I recieve event IContextMenuHandler.OnBeforeContextMenu as supposed. It's okay.

BUT when I click on username with oncontextmenu=false - I **do not** recieve OnBeforeContextMenu  event, and CEF still **shows** default content menu. So I can't in code handle it

So problem: I can't "ask" CEF do not show it's context menu if there are no "OnBeforeContextMenu" event on object with "oncontextmenu=false" 

Ideally I don't want to see  CEF context menu if oncontextmenu=false
(atleast I checked previous client version under Awesomium, it respects such situation)

sorry again for bad english and lot of useless text

**Comment by amaitland** [comment]
> I don't have a control on source html

You can inject `javascript` to basically do whatever you like, you have complete control if you require it.

Please product a `jsFiddle` or similar to demo your problem.

http://jsfiddle.net/

**Comment by amaitland** [comment]
Also is `IContextMenuHandler.RunContextMenu` called?

https://github.com/cefsharp/CefSharp/blob/master/CefSharp/IContextMenuHandler.cs#L58

**Comment by DonSleza4e** [comment]
working example (i took original code from existing html page and removed indeeded trash)
https://jsfiddle.net/DonSleza4e/ym59mhch/

I used latest CefSharp.Wpf.Example to check
 
Screenshot with Chrome and CefSharp.Wpf.Example
![screenshot](https://cloud.githubusercontent.com/assets/17129596/12912645/9d84b270-cf22-11e5-8c9b-dc0bdbc7d658.png)


Events :
__________
Original CefSharp.Wpf.Example source code
1) Right click on "Right click on me" span
 - no events catched 
2) Right click outside of span
- catched OnBeforeContextMenu, and then RunContextMenu
3) Right  click again outside of span and all other clicks
- no events catched

**Comment by amaitland** [comment]
Thats the `WPF` context menu, if you comment that out what shows up?

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf.Example/Views/BrowserTabView.xaml#L204

**Comment by DonSleza4e** [comment]
Yes, I tried to remove that context menu in BrowserTabView.xaml
But I lose context menu at all in browser
I'd like to keep that context menu

So I'd like to have same behaviour like Chrome do:
Show context menu in browser, and do not show context menu on items with oncontextmenu=false

**Comment by amaitland** [comment]
> Yes, I tried to remove that context menu in BrowserTabView.xaml
> But I lose context menu at all in browser
> I'd like to keep that context menu

That's the `WPF` context menu that's hiding your custom html menu. That context menu will need to be removed. It's up to you to implement your own custom context menu.

You have to implement `IContextMenuHandler.RunContextMenu` show your apps context menu, then hide it when `IContextMenuHandler.OnContextMenuDismissed` is called.

**Comment by DonSleza4e** [comment]
As I mentioned, "RunContextMenu" is NOT fires when I click on object with "oncontextmenu=false". 
So I CAN'T handle that. That's why I'm writing here.

You can verify that in CefSharp.Wpf.Example and https://jsfiddle.net/DonSleza4e/ym59mhch/ by clicking right mousebutton on test span object

**Comment by DonSleza4e** [comment]
As I mentioned, "RunContextMenu" is not fires when I click on object with "oncontextmenu=false". 
It fires only when I press right mouse button outside of that test span object.
So I can't handle that. That's why I'm writing here.

You can verify that in CefSharp.Wpf.Example and https://jsfiddle.net/DonSleza4e/ym59mhch/ by clicking right mousebutton on test span object

![clipboard02](https://cloud.githubusercontent.com/assets/17129596/12939673/bc18e21c-cfca-11e5-82c1-4fc3705f0c09.png)

**Comment by amaitland** [comment]
> As I mentioned, "RunContextMenu" is not fires when I click on object with "oncontextmenu=false". Well, no events fires at all (as it shown in screenshot below)
> It fires only when I press right mouse button outside of that test span object.
> So I can't handle that. That's why I'm writing here.

That would appear to the correct behavior, you've explicitly said that element shouldn't invoke a context menu. 

> You can check it in CefSharp.Wpf.Example and https://jsfiddle.net/DonSleza4e/ym59mhch/ by clicking right mousebutton on test span object

I have, it's as I expected. The `WPF` context menu is hiding the javascript menu, so it needs to be removed.

All the pieces are there to implement your own context menu.

`IContextMenuHandler.RunContextMenu` -  Dynamically populate the `WPF` context menu
`IContextMenuHandler.OnContextMenuDismissed` hide/remove the `WPF` context menu.

It's a little fiddly, it will work though. Just make sure you build your menu model from `IMenuModel` before invoking back onto the `UI` thread with the `Dispatcher`.

**Comment by DonSleza4e** [comment]
> That would appear to the correct behavior, you've explicitly said that element shouldn't invoke a context menu.
Well, I believed it's an issue - WPF menu is shown, and no events fires to handle it

Ok, as I understood, your recomendation is 
1) Remove content menu at https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf.Example/Views/BrowserTabView.xaml#L204
2) Render own menu on RunContextMenu (it does not fires on object with oncontextmenu=false - so my problem will be resolved)

**Comment by amaitland** [comment]
> Well, I believed it's an issue - WPF menu is shown, and no events fires to handle it

The `WPF` context menu will always be shown, it's not linked into the browser based menu in any way currently. It's just a super simple example.

> Render own menu on RunContextMenu (it does not fires on object with oncontextmenu=false - so my problem will be resolved)

Correct. You can cast `IWebBrowser` to `ChromiumWebBrowser` and access the underlying control, populate it's `ContextMenu`.

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/commit/84f7c5dc62272e7a33572954c587cc821892c799 for a basic working example. Not well tested, so if you find any problems please submit a `PR` with your proposed changes :+1:

**Comment by DonSleza4e** [comment]
thank you, this sample is very helpful !

**Comment by DonSleza4e** [comment]
There's a problem in this solution (and I believe, this is global problem, because I tried various ways)
"RunContextMenu" is not fires each time when I click right mouse button.

There are can be various object types on html page. Some of them has own context menu items. It's a text field ("Select All..."), flash object ("About Flash, Settings..."), label with selected text ("Copy")... Plus objects with  oncontextmenu=false - no menu at all.

So when I click various times right mouse and move mouse - Browser shows "wrong" menu for "wrong" objects. I wasn't able to find why it happens, but it always reproduces

**Comment by amaitland** [comment]
`CefSharp` has no control over that. Need to double check the `WinForms` version, confirm if the problem is apparent there.

Most likely this will need to be resolved in `CEF`.

**Comment by amaitland** [comment]
May actually need to call `callback.Cancel()` when the `WPF` menu is hidden.

**Comment by DonSleza4e** [comment]
Indeed, I added  `callback.Cancel();` at RunContextMenu
just before `return true;` (at line 82 in your solution)

working perfect - fires each time I click right mouse button. And I'm not sure I clearly understand _why_ it works - but anyway, it works, atleast in current cef build:)

thank you:+1:

**Comment by DonSleza4e** [comment]
Also, for those who interested
I'm using another way to fill menu - because provided solution by amaitland is not works with  `callback.Cancel();` . BUT, atleast, it fires RunContextMenu event each time and allow to render valid menu
(I'm not sure it's correct solution. May be it's too lazy, but it works for me)

```
        void IContextMenuHandler.OnBeforeContextMenu(IWebBrowser browserControl, IBrowser browser, IFrame frame, IContextMenuParams parameters, IMenuModel model)
        {
            for (int i = 0; i < model.Count; i++)
                if ((int)model.GetCommandIdAt(i) == 234)      //About Adobe Flash
                    model.Clear();  //Kill flash menu                    
        }

        bool IContextMenuHandler.OnContextMenuCommand(IWebBrowser browserControl, IBrowser browser, IFrame frame, IContextMenuParams parameters, CefMenuCommand commandId, CefEventFlags eventFlags)
        {
            return false;
        }

        void IContextMenuHandler.OnContextMenuDismissed(IWebBrowser browserControl, IBrowser browser, IFrame frame)
        {
            var chromiumWebBrowser = (ChromiumWebBrowser)browserControl;

            chromiumWebBrowser.Dispatcher.Invoke(() =>
            {
                chromiumWebBrowser.ContextMenu = null;
            });
        }

        bool IContextMenuHandler.RunContextMenu(IWebBrowser browserControl, IBrowser browser, IFrame frame, IContextMenuParams parameters, IMenuModel model, IRunContextMenuCallback callback)
        {
            if (model.Count == 0) return true;  //No menu if 0 items (flash)

            var chromiumWebBrowser = (ChromiumWebBrowser)browserControl;

            //IMenuModel is only valid in the context of this method, so need to read the values before invoking on the UI thread
            var menuItems = GetMenuItems(model);

            chromiumWebBrowser.Dispatcher.Invoke(() =>
            {
                var menu = new ContextMenu { IsOpen = true };

                //Handle all hotkeys in BrowserTabView.xaml
                menu.Items.Add(new MenuItem { Header = "Back", Command = chromiumWebBrowser.BackCommand, InputGestureText = "Alt+Left" });
                menu.Items.Add(new MenuItem { Header = "Forward", Command = chromiumWebBrowser.ForwardCommand, InputGestureText = "Alt+Right" });
                menu.Items.Add(new MenuItem { Header = "Reload", Command = chromiumWebBrowser.ReloadCommand, InputGestureText = "Ctrl+R" });

                menu.Items.Add(new Separator());

                if (HasMenuCommand(menuItems, CefMenuCommand.Copy))
                    menu.Items.Add(new MenuItem { Header = "Copy", Command = chromiumWebBrowser.CopyCommand, InputGestureText = "Ctrl+C" });

                ...........
               
                chromiumWebBrowser.ContextMenu = menu;
            });

            callback.Cancel();  //This allows to fire RunContextMenu event each time

            return true;
        }

        private static IEnumerable<Tuple<string, CefMenuCommand>> GetMenuItems(IMenuModel model)
        {
            var list = new List<Tuple<string, CefMenuCommand>>();
            for (var i = 0; i < model.Count; i++)
            {
                var header = model.GetLabelAt(i);
                var commandId = model.GetCommandIdAt(i);
                list.Add(new Tuple<string, CefMenuCommand>(header, commandId));
            }

            return list;
        }

        private static bool HasMenuCommand(IEnumerable<Tuple<string, CefMenuCommand>> menuItems, CefMenuCommand command)
        {
            foreach (var item in menuItems)
            {
                if (item.Item2 == command) return true;
            }
            return false;
        }
```

**Comment by amaitland** [comment]
Thanks for posting your updated example :+1: 

I amended my original example with a slightly different solution. Requires an `IsDisposed` property to be exposed on `IRunContextMenuCallback `, so will only be available in the next release.

https://github.com/cefsharp/CefSharp/commit/b89377e630d06fce88efee59793a9b4baff51d32
