### ISSUE TITLE
CefSharp not working on Netflix and Twitter (video playback)

### ISSUE THREAD

**Issue by Spiderpig86** [cefsharp/CefSharp#1588]
I have tested several versions of CefSharp (41 and 45) and I can't seem to find the solution of getting media to play on Netflix and Twitter saying that there was an error or that video was unsupported. I am using the Winforms version and WPF version of CefSharp and it doesn't work on both. Does anyone have a solution to this issue?

**Comment by amaitland** [comment]
See #1479

We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask followup questions there.
