### ISSUE TITLE
IResourceHandler exception catching

### ISSUE THREAD

**Issue by Matthew-Bonner** [cefsharp/CefSharp#1591]
Issue:
I can't see a way in which to catch exceptions which are thrown in a IResourceHandler or to cause exceptions which are thrown to raise the LoadError event.

Scenario:
As a result if I want to show an embedded HTML file as a 404 page and the user requests a resource file using the same scheme (ie res://) but mistypes the address my implementation of IResourceHandler throws an exception. In addition to this the LoadError event isn't raised.

Expected outcome:
I would have expected the LoadError event to be raised but never gets raised.

**Comment by amaitland** [comment]
> I can't see a way in which to catch exceptions which are thrown in a IResourceHandler or to cause exceptions which are thrown to raise the LoadError event.

The simplest option is to execute `callback.Cancel()` that should trigger `LoadError`, with an aborted response code.

Do you need to explicitly set a `404` response code?

> but mistypes the address my implementation of IResourceHandler throws an exception. In addition to this the LoadError event isn't raised.

I'd advise against throwing an exception, in this case the calling code is actually `unmanaged C++`.

**Comment by Matthew-Bonner** [comment]
I would need to set a 404 response code, I figure it is a case of setting the 404 status code in a private variable and then using the private variable to set the 404 status code in the GetResponse but if not please correct me.

Personally I don't find the solution elegant but nevertheless it is a solution, I will add some feedback to #1592 in regards to this. Thanks.

**Comment by amaitland** [comment]
> Personally I don't find the solution elegant but nevertheless it is a solution, I will add some feedback to #1592 in regards to this. Thanks.

Even with the proposed changes in #1592 I don't believe you'd be able to set `404` and trigger `LoadError`, from what I can gather change would be required in `CEF` it's self.

**Comment by Matthew-Bonner** [comment]
I have made it so that the response is set to a simple error message and includes a 404 status code but the problem with this method is that I now have two variants of a 404 error page, one branded which is defined by the project which references the framework wrapping cefsharp and an unbranded error page defined in the cefaharp wrapper framework. I will raise this with cef and see what they say. Thanks.

**Comment by amaitland** [comment]
> I now have two variants of a 404 error page, one branded which is defined by the project

Short term can you perform a redirect to the branded `404` page?

**Comment by Matthew-Bonner** [comment]
I want to keep the layers separate, the cefsharp framework wrapper shouldn't need to know what happens on an error, it should give enough information to the consumer to allow the consumer to decide. In a multithreaded environment where objects are managed by an IoC container I can't store the lat error either. Overloading the class to add an error event makes no sense as the API will then have an inconsistent way to capture when a page failed to load. I will have a think on a solution and then push it to see what you think.

**Comment by amaitland** [comment]
For future reference https://bitbucket.org/chromiumembedded/cef/pull-requests/56/add-ability-to-attach-a-cef-error-code-to/diff#comment-None

**Comment by Matthew-Bonner** [comment]
Sorry I've been ill, if you submitted the pull request I'd just like to say thanks.

**Comment by amaitland** [comment]
> Sorry I've been ill, if you submitted the pull request I'd just like to say thanks.

Nope, not me. Just posting as a reference.

**Comment by amaitland** [comment]
This will be possible in `2704`, additional code is still required (trivial). A `PR` implementing the functionality would be most welcomed.

**Comment by amaitland** [comment]
Resolved with https://github.com/cefsharp/CefSharp/commit/18e3cb77dee8f7a0a5f7a6b6e065f32ca0dbb6ba
