### ISSUE TITLE
MVVM Reload

### ISSUE THREAD

**Issue by GAMP** [cefsharp/CefSharp#1595]
Hi.
I am using the browser control with binding.
My question is how could i cause a browser reload/refresh from within the view model without actually accessing its instance?

**Comment by amaitland** [comment]
The control has `Commands` that can be used in `XAML`.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf/ChromiumWebBrowser.cs#L73

We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask followup questions there.
