### ISSUE TITLE
Get image from browser cache

### ISSUE THREAD

**Issue by cpawelzik** [cefsharp/CefSharp#1598]
Is there a way to get an image (or other resource) from the browser cache?

**Comment by amaitland** [comment]
Unfortunately there is no access to the `Cache`. You may be able to manually access the cache, though that's outside the scope of this project. (`CefSharp` is just a wrapper around `Chromium Embedded Framework`)

We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask followup questions there.
