### ISSUE TITLE
High DPI issues with WPF

### ISSUE THREAD

**Issue by jamespearce2006** [cefsharp/CefSharp#1599]
I'm seeing intermittent problems running CefSharp 47 in a WPF app with high DPI.
Sometimes, the web view will get into a strange state where it doesn't render into the full window extent (or renders outside the extents). When this happens, mouse input also stops working (presumably because cursor coordinates are no longer being mapped properly).

I can reproduce the problem with the Wpf Example (x86 or x64) by doing the following:

1. Open the WPF example app
2. Open a new tab
3. Resize the app
4. Close the newly opened tab

The view returns to the first tab, but it seems to be broken.

![image](https://cloud.githubusercontent.com/assets/12157851/13180423/48a7c818-d720-11e5-9bb2-fa3ee4125df9.png)

**Comment by amaitland** [comment]
Sounds like  #1571

**Comment by jamespearce2006** [comment]
@amaitland yes it does sound identical. However, I can confirm I only see the problem with DPI set to something other than 100%.

**Comment by amaitland** [comment]
> However, I can confirm I only see the problem with DPI set to something other than 100%.

Possibly the missing piece in #1571, was never able to reproduce the problem. Have you been able to reproduce the problem on different hardware?

**Comment by jamespearce2006** [comment]
> Have you been able to reproduce the problem on different hardware?

Unfortunately not, as I don't have access to different hardware currently...

**Comment by amaitland** [comment]
Same problem as #1571 so closing this as duplicate.
