### ISSUE TITLE
Widevine not really supported on 47.0.2?

### ISSUE THREAD

**Issue by cbordeman** [cefsharp/CefSharp#1600]
I'm using the nuget download of CefSharp 47.0.2, the WPF ChromiumWebBrowser control.  Despite Widevine DRM being supported by CefSharp since v45, when I browse to NetFlix and try to watch a stream, I get the same old message that my browser isn't supported.  I'm compiling x64.

I thought Widevine would be all that's necessary.  Is there something additional I need to do?

**Comment by amaitland** [comment]
> If you want to ask a question, first read our FAQ and search this Github repository using the search box at the top.
Once you have done research and not found an answer, visit our Gitter room instead: https://gitter.im/cefsharp/CefSharp

Did the issue template direct you towards `Gitter`?

> I thought Widevine would be all that's necessary. Is there something additional I need to do?

Read https://bitbucket.org/chromiumembedded/cef/issues/1631/add-support-for-widevine-cdm in it's entirety.

Search `Gitter` for a recent report of using `widevine cdm` that maybe useful.
