### ISSUE TITLE
 CefSharp.BrowserSubProcess take 5 to 10 seconds to close in winform version 47

### ISSUE THREAD

**Issue by farrukhpisces** [cefsharp/CefSharp#1601]
I am using CefSharp verison 47 in winform.on closing the form BrowserSubProcess take 5 to 10 seconds to terminate which halt GUI.

**Comment by amaitland** [comment]
> If you want to ask a question, first read our FAQ and search this Github repository using the search box at the top.
Once you have done research and not found an answer, visit our Gitter room instead: https://gitter.im/cefsharp/CefSharp

As per the issue template, please ask your questions on `Gitter`.

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/issues/1429#issuecomment-164612748
