### ISSUE TITLE
IsBrowserInitialized property cannot assign a binding object

### ISSUE THREAD

**Issue by Eido95** [cefsharp/CefSharp#1603]
When writing the following line in `ChromiumWebBrowser` instance which declared in WPF XAML file:
`IsBrowserInitialized="{Binding Path=Initialized, Mode=OneWayToSource}"`
The following error thrown in design time:

> Error: 'IsBrowserInitialized' property is read-only and cannot be set from markup.

After looking for `IsBrowserInitialized` property deceleration in the code, it seems very legitimate exception because `IsBrowserInitialized` _property doesn't have a setter accessor_ which binding object can be assign to.

Would really like you to implement simple `DependencyProperty` setter to expose the property to WPF binding mechanism.

Thanks.

**Comment by amaitland** [comment]
> Would really like you to implement simple DependencyProperty setter to expose the property to WPF binding mechanism.

`IsBrowserInitialized` is set internally, and should **never** be set by any other means as it reflects internal state of the browser.

You should be able to create an `AttachedProperty` to track changes to the `IsBrowserInitializedProperty`.

> If you want to ask a question, first read our FAQ and search this Github repository using the search box at the top.
Once you have done research and not found an answer, visit our Gitter room instead: https://gitter.im/cefsharp/CefSharp

As per the `issue` template, ask your questions on `Gitter` please.
