### ISSUE TITLE
Local Storage gets deleted on app exit

### ISSUE THREAD

**Issue by PhilippCh** [cefsharp/CefSharp#1604]
- **What steps will reproduce the problem?**
I'm trying to get persistent localstorage to work with the following settings for the browser:

`ApplicationCache = CefSharp.CefState.Enabled,
LocalStorage = CefSharp.CefState.Enabled`

as well as for Cef itself:

`CefSettings.CachePath = "data\cache"`

calling `ChromiumWebBrowser.Dispose()` and `Cef.Shutdown()` before I exit my app.

- **What is the expected output? What do you see instead?**
I'm expecting localstorage to persist in "data\cache\localstorage". Cef creates the files for the respective domains, but upon app exit (with or without Cef.Shutdown()) these files get deleted.

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms

- **What version of the product are you using? On what operating system? x86 or x64?**
    - What version are you using? Nuget? CI Nuget? build from a branch? If so which branch?
    NuGet (47.0.2)

    - Win7, Win 8, Win10, etc?
    Win10

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.
    No exception, everything seems to run fine

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
    No relevant information. The only line in my log is `[0222/220526:ERROR:ipc_channel_win.cc(207)] pipe error: 109`

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
    Nothing out of the ordinary, a simple installation.

- **Does this problem also occur in the `Cef` TestApp from http://cefbuilds.com?**
    I can't find a way to reproduce localstorage in the TestApp.

**Comment by amaitland** [comment]
> ApplicationCache = CefSharp.CefState.Enabled, LocalStorage = CefSharp.CefState.Enabled
> 
> as well as for Cef itself:
> 
> CefSettings.CachePath = "data\cache"

Can you provide a `Gist` that shows when you make these calls. Timing is important.

Suggestions are that `LocalStorage` works, I'm not aware of what settings are required.

http://magpcss.org/ceforum/viewtopic.php?f=6&t=13860

**Comment by amaitland** [comment]
@PhilippCh Any follow up on this one?

**Comment by amaitland** [comment]
Closing due to lack of feedback

**Comment by PhilippCh** [comment]
Sorry for not getting back on this, was trying out every possible way to get around this issue.

Turns out it's related to the angular localstorage plugin I'm using (ngStorage) not saving changes properly. When using native localStorage.set/getItem, everything is working fine.

**Comment by amaitland** [comment]
> Turns out it's related to the angular localstorage plugin I'm using (ngStorage) not saving changes properly. When using native localStorage.set/getItem, everything is working fine.

Thanks for confirming :+1:
