### ISSUE TITLE
Disable Mixed content in configuration.

### ISSUE THREAD

**Issue by sebastyan** [cefsharp/CefSharp#1606]
Hi all,
I am not sure if, do we could disable the mixed content by configuration?

I want to call http resource from a https page.

Regards.

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by xiexin36** [comment]
@sebastyan have you resolved this problem?

**Comment by xiexin36** [comment]
@sebastyan  I found it, use CefSetting,
settings.CefCommandLineArgs.Add("allow-running-insecure-content", "1"); //By default, an https page cannot run JavaScript, CSS or plugins from http URLs. This provides an override to get the old insecure behavior. Only available in 47 and above.
