### ISSUE TITLE
Subprocess exe crashing on browserbench.org/JetStream

### ISSUE THREAD

**Issue by okatip1** [cefsharp/CefSharp#1609]
When I try the browser with http://browserbench.org/JetStream/ 

The browser is crashing (subprocess.exe) on the step which is Throughput-->bigfib.cpp

You can try it.

I'm using version 47 and WPF.

Steps:
1- Run cefsharp in debug mode.
2- In first tab, go to the browserbench.org/JetStream url
3- Run the test.

Error 
http://pasteboard.co/1PbHRsOP.png

**Comment by amaitland** [comment]
Next step is to isolate your problem, is it a problem with `CefSharp` or `CEF` it's self?

https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

Also please post the full stack trace, screen shot is not particularly helpful.

**Comment by amaitland** [comment]
Also try running in `x64`

**Comment by okatip1** [comment]
I tried this in cef test app for same version (with the multi threading and off screen params). There is no error in the test app.
-------

In x64 I got error like x86.

I cannot get the full stack trace of the error, because my visual studio have some problems.

**Comment by amaitland** [comment]
> In x64 I got error like x86.

Ran fine in `x64` mode for me. I'm using the `MinimalExample`. Can you try the `WinForms` version, see what happens there?

> I cannot get the full stack trace of the error, because my visual studio have some problems.

Probably best you sort that out. Also download the `release symbols` from `cefbuilds.com` (make sure you match the version exactly), extract the `pdb` in the same folder as the executing program.

**Comment by okatip1** [comment]
I dont get error not every time. I tried winforms got the error again.

Error details:

  Problem Event Name:	APPCRASH
  Application Name:	CefSharp.BrowserSubprocess.exe
  Application Version:	47.0.0.0
  Application Timestamp:	56cf894d
  Fault Module Name:	libcef.dll
  Fault Module Version:	3.2526.1362.0
  Fault Module Timestamp:	56710443
  Exception Code:	c0000005
  Exception Offset:	001ebbc7
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1055
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by amaitland** [comment]
I've tested on two different machines in `x64` and `x86`, both passed successfully.

**Comment by amaitland** [comment]
Try running with the `MinimalExample`

**Comment by amaitland** [comment]
I don't have time to look into this any further. Good luck :+1:

**Comment by amaitland** [comment]
Closing this as no response for over a month. If anyone can reproduce the issue in the next version (`49.0.0`) and has more to offer than just, `It doesn't work` then by all means comment.
