### ISSUE TITLE
How to automatically display which check items and radio item have been selected upon user interaction?

### ISSUE THREAD

**Issue by Matthew-Bonner** [cefsharp/CefSharp#1612]
In commit 110789d there are now options for adding different types of menu commands, upon adding a check item and running the application, when the check item is clicked it isn't automatically checked and there is a similar problem with the radio items whereby clicking a deselected radio item does not select it and deselect the previously selected radio item.

Is it a requirement to manually call the SetChecked method to indicate that the check item and radio item are now selected upon the user clicking them?

I would have expected this to be done automatically.

```cs
using CefSharp;

namespace Company.Product.Example.UserInterface
{
    internal class MenuHandler : IContextMenuHandler
    {
        private const int MenuCommandView = 26500;
        private const int MenuCommandViewLargeIcons = 26501;
        private const int MenuCommandViewMediumIcons = 26502;
        private const int MenuCommandViewSmallIcons = 26503;
        private const int MenuCommandViewAutoArrangeIcons = 26504;
        private const int MenuCommandViewAlignIconsToGrid = 26505;

        void IContextMenuHandler.OnBeforeContextMenu(IWebBrowser browserControl, IBrowser browser, IFrame frame, IContextMenuParams parameters, IMenuModel model)
        {
            model.Clear();

            IMenuModel viewMenu = model.AddSubMenu((CefMenuCommand)MenuCommandView, "View");
            viewMenu.AddRadioItem((CefMenuCommand)MenuCommandViewLargeIcons, "Large icons", 0);
            viewMenu.AddRadioItem((CefMenuCommand)MenuCommandViewMediumIcons, "Medium icons", 0);
            viewMenu.AddRadioItem((CefMenuCommand)MenuCommandViewSmallIcons, "Small icons", 0);

            viewMenu.AddSeparator();

            viewMenu.AddCheckItem((CefMenuCommand)MenuCommandViewAutoArrangeIcons, "Auto arrange icons");
            viewMenu.AddCheckItem((CefMenuCommand)MenuCommandViewAlignIconsToGrid, "Align icons to grid");
        }

        bool IContextMenuHandler.OnContextMenuCommand(IWebBrowser browserControl, IBrowser browser, IFrame frame, IContextMenuParams parameters, CefMenuCommand commandId, CefEventFlags eventFlags)
        {
            return false;
        }

        void IContextMenuHandler.OnContextMenuDismissed(IWebBrowser browserControl, IBrowser browser, IFrame frame)
        {
        }

        bool IContextMenuHandler.RunContextMenu(IWebBrowser browserControl, IBrowser browser, IFrame frame, IContextMenuParams parameters, IMenuModel model, IRunContextMenuCallback callback)
        {
            return false;
        }
    }
}

**Comment by amaitland** [comment]
> Is it a requirement to manually call the SetChecked method to indicate that the check item and radio item are now selected upon the user clicking them?

The methods were only implemented a few days ago. Remember we just wrap them, no control over their behavior. This question would be best asked on http://magpcss.org/ceforum/index.php

**Comment by Matthew-Bonner** [comment]
Thanks once again for a quick response. Can you label this upstream and keep it open while I check on the CEF forums. I'll post an update here once I have one.

**Comment by amaitland** [comment]
> Thanks once again for a quick response. Can you label this upstream and keep it open while I check on the CEF forums. I'll post an update here once I have one.

Done :+1:

**Comment by amaitland** [comment]
Follow up discussion is http://magpcss.org/ceforum/viewtopic.php?f=6&t=13937

@Matthew-Bonner Anything else before closing this?
