### ISSUE TITLE
Where to find Visual Studio C++ 2013 redistributables files for my application?

### ISSUE THREAD

**Issue by newradius** [cefsharp/CefSharp#1613]
I already took a look at the FAQ (https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#Including_vcredist) but I'm not able to find that directory neither the files. I use VS2015.

**Comment by jankurianski** [comment]
This sounds like a question rather than a bug.  Please ask your question on Gitter instead: https://gitter.im/cefsharp/CefSharp
