### ISSUE TITLE
Playing video requires excessive amounts of CPU

### ISSUE THREAD

**Issue by bradley-dotnet** [cefsharp/CefSharp#1615]
- **What steps will reproduce the problem?**
1. Setup a website that plays a video file via an HTML5 video tag. Both WEBM and OGG videos seem to have the same issue.
2. Run on an embedded device.

- **What is the expected output? What do you see instead?**
The video plays, but is slightly choppy and the CPU is 95%+ consistently. The same website using Awesomium runs at about 15%, and Chrome is at 30%.

The expectation is being able to play a video without eating all the CPU on the device.

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What version of the product are you using? On what operating system? x86 or x64?**
Nuget, version 47.0.2 on x86 Windows 7 Embedded

- **Please provide any additional information below.**
The device in question barely has a graphics card. The Disable GPU and Disable GPU Vsync flags appear to have no affect, turning off WebGL helped a little bit. 

Running the CEFClient against the same website/video results in expected CPU usage (10-20%).

**Comment by amaitland** [comment]
> The same website using Awesomium runs at about 15%, and Chrome is at 30%.

Run the `WinForms` version are you'll likely see similar results.

> The device in question barely has a graphics card. The Disable GPU and Disable GPU Vsync flags appear to have no affect, turning off WebGL helped a little bit.

Try `settings.SetOffScreenRenderingBestPerformanceArgs();`

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/CefExample.cs#L70

If that doesn't work then there isn't a whole lot that can be done unfortunately. 

> Running the CEFClient against the same website/video results in expected CPU usage (10-20%).

Did you run it with `--multi-threaded-message-loop --off-screen-rendering-enabled`? Was it the exact same version? `3.2526.1362`

**Comment by amaitland** [comment]
Also try isolating the problem with the `MinimalExample`
https://github.com/cefsharp/CefSharp.MinimalExample

You maybe able to host the `WinForms` version in `WPF`, which will give you a speed boost if it works.

> The video plays, but is slightly choppy and the CPU is 95%+ consistently.

Which process is chewing the `CPU`?

**Comment by bradley-dotnet** [comment]
Thank you for your suggestions, I will try them ASAP. CEF client was run with no special command line arguments, and it was the latest build. 

Primarily, the process chewing the CPU is the one hosting the control (not one of the subprocesses).

**Comment by bradley-dotnet** [comment]
The `settings.SetOffScreenRenderingBestPerformanceArgs();` gave us a small improvement, but using WinForms was equivalent performance to CefClient as you suggested. Hosting that in WPF worked perfectly as well.

Thank you very much for the assistance!
