### ISSUE TITLE
browser subprocess is not closed after closing its parent tab

### ISSUE THREAD

**Issue by farrukhpisces** [cefsharp/CefSharp#1616]
I am using CefSharp 47 and the issue is that, after opening many tabs which in result opens multiple browsersubprocess. but some times when i close all the tabs it still showing many (7 8) sub processes in running state showing in Task Manager, and in the result its freeze application UI.

**Comment by jankurianski** [comment]
If this is meant to be a bug report, then create this issue again, following the template: https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

If you have a question, ask it on Gitter chat: https://gitter.im/cefsharp/CefSharp
