### ISSUE TITLE
browser subprocess is not closed after closing its parent tab and freeze GUI

### ISSUE THREAD

**Issue by farrukhpisces** [cefsharp/CefSharp#1617]
**What steps will reproduce the problem?**
The issue is that, after opening many tabs which in result opens multiple browsersubprocess. but some times when i close all the tabs it still showing many (7 8) sub processes in running state showing in Task Manager, and in the result its freeze application GUI.

**What is the expected output? What do you see instead?**
On closing all tabs, all browser subprocesses should closed.

**Are you using WinForms, WPF or OffScreen?**
 I am using WinForms

**What version of the product are you using? On what operating system? x86 or x64?**
   Using version 47

**What version are you using? Nuget? CI Nuget? build from a branch? If so which branch?**
Nuget

**Win7, Win 8, Win10, etc?**
Windows server 2008

**Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)**
[0302/015024:ERROR:browser_gpu_channel_host_factory.cc(132)] Failed to launch GPU process.

**Does this problem also occur in the Cef TestApp from http://cefbuilds.com?**
no

**Comment by amaitland** [comment]
> The issue is that, after opening many tabs which in result opens multiple browsersubprocess. but some times when i close all the tabs it still showing many (7 8) sub processes in running state showing in Task Manager, and in the result its freeze application GUI.

That doesn't accurately describe how to reproduce the problem. It describes how you've used the control and the problem your having. It doesn't give any detail on how someone might help you.

Can you reproduce the problem with the `CefSharp.WinForms.Example`? Make whatever changes are required to demo your problem and push to your changes to your `GitHub` fork of the project.

**Comment by amaitland** [comment]
Dispose of browser instances when finished, remove them from the `UI` first. See #1574 for background.
