### ISSUE TITLE
is there any work around to support Flash in CefSharp 47

### ISSUE THREAD

**Issue by muhammadsufiyan** [cefsharp/CefSharp#1621]
I have written the following to support flash in CefSharp 47, but it does not seems to works:

     var settings = new CefSettings();
     settings.CefCommandLineArgs.Add("enable-npapi", "1");
     //settings.CefCommandLineArgs.Add("enable-system-flash", "1");
     Cef.Initialize(settings);
     browser = new ChromiumWebBrowser("https://www.whatismybrowser.com/");
     this.panel1.Controls.Add(browser);
     browser.Dock = DockStyle.Fill;

any help or suggestion would be really a great help, thanks in advance.
![cef-issue](https://cloud.githubusercontent.com/assets/5661467/13633805/65a6169e-e617-11e5-8bf0-83f5690ae533.png)

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by amaitland** [comment]
Duplicate of #1505
