### ISSUE TITLE
Disable javascript commandline not working in 47.0.3.

### ISSUE THREAD

**Issue by swagata-daffodil** [cefsharp/CefSharp#1622]
`  var settings = new CefSettings();
            settings.CefCommandLineArgs.Add("renderer-process-limit", "2");
            settings.CefCommandLineArgs.Add("disable-image-loading", "1");
            settings.CefCommandLineArgs.Add("disable-javascript", "1");
            settings.MultiThreadedMessageLoop = true;
            settings.EnableInternalPdfViewerOffScreen();
            Cef.Initialize(settings);
`

I have written the above code to initialize. It prevents images from loading but javascript is not disabling. Kindly help.

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md
