### ISSUE TITLE
custom build cefclient works very slow and automatically redirect to default uri

### ISSUE THREAD

**Issue by muhammadsufiyan** [cefsharp/CefSharp#1623]
I downloaded the `CEF 3.2556.1368.g535c4fb (80MB) ` from `https://cefbuilds.com/` for Windows 32bit then download the latest `CMake 3.5.0`, then:
I edited the `cefclient_win.cc` after extracting it : 

      context->GetRootWindowManager()->CreateRootWindow(
      false,             // Show controls. 
      settings.windowless_rendering_enabled ? true : true,
      CefRect(),        // Use default system size.
      std::string());

only changed Show controls to `false`, then compiled it using `CMake 3.5.0` with success, the output is below:

        The C compiler identification is MSVC 19.0.23506.0
        The CXX compiler identification is MSVC 19.0.23506.0
        Check for working C compiler using: Visual Studio 14 2015
        Check for working C compiler using: Visual Studio 14 2015 -- works
        Detecting C compiler ABI info
        Detecting C compiler ABI info - done
        Check for working CXX compiler using: Visual Studio 14 2015
        Check for working CXX compiler using: Visual Studio 14 2015 -- works
        Detecting CXX compiler ABI info
        Detecting CXX compiler ABI info - done
        Detecting CXX compile features
        Detecting CXX compile features - done
        *** CONFIGURATION SETTINGS ***
        Generator:                    Visual Studio 14 2015
        Platform:                     Windows
        Project architecture:         x86
        CEF Windows sandbox:          OFF
        Visual Studio ATL support:    ON
        Standard libraries:           comctl32.lib;rpcrt4.lib;shlwapi.lib
        Compiler definitions:         __STDC_CONSTANT_MACROS;__STDC_FORMAT_MACROS;WIN32;_WIN32;_WINDOWS;UNICODE;_UNICODE;WINVER=0x0602;_WIN32_WINNT=0x602;NOMINMAX;WIN32_LEAN_AND_MEAN;_HAS_EXCEPTIONS=0;CEF_USE_ATL
        C_FLAGS:                      /MP /Gy /GR- /W4 /WX /wd"4100" /wd"4127" /wd"4244" /wd"4512" /wd"4701" /wd"4702" /wd"4996" /Zi 
        C_FLAGS_DEBUG:                /MTd /RTC1 /Od 
        C_FLAGS_RELEASE:              /MT /O2 /Ob2 /GF /D NDEBUG /D _NDEBUG 
        CXX_FLAGS:                    /MP /Gy /GR- /W4 /WX /wd"4100" /wd"4127" /wd"4244" /wd"4512" /wd"4701" /wd"4702" /wd"4996" /Zi 
        CXX_FLAGS_DEBUG:              /MTd /RTC1 /Od 
        CXX_FLAGS_RELEASE:            /MT /O2 /Ob2 /GF /D NDEBUG /D _NDEBUG 
        EXE_LINKER_FLAGS:              /MANIFEST:NO
        EXE_LINKER_FLAGS_DEBUG:       /DEBUG 
        EXE_LINKER_FLAGS_RELEASE:      
        SHARED_LINKER_FLAGS:           
        SHARED_LINKER_FLAGS_DEBUG:    /DEBUG 
        SHARED_LINKER_FLAGS_RELEASE:   
        CEF Binary files:             d3dcompiler_43.dll;d3dcompiler_47.dll;libcef.dll;libEGL.dll;libGLESv2.dll;natives_blob.bin;snapshot_blob.bin;wow_helper.exe
        CEF Resource files:           cef.pak;cef_100_percent.pak;cef_200_percent.pak;cef_extensions.pak;devtools_resources.pak;icudtl.dat;locales
        Configuring done
        Generating done

after this I got `cef.sln` then I opened it with `vs2015 community edition` and started the `build` after few minutes I got the `Debug` folder with `.exe` files for `cefclient.exe` and `cefsimple.exe` with some other files too.

now when I run `cefclient.exe` it open ups with no controls in it (thats what I want), but after few clicks on the links inside the `cefclient.exe browser` it redirects me to `google.com` same is happening for `cefsimple.exe` too. and the performance is also very bad.

I must say this is not a bug or issue, but might be a problem from my side, because `CefSharp` rocks. Please any one help me what I am doing wrong or missing really some more important steps.
Thanks in advance.

**Comment by amaitland** [comment]
Ask on http://magpcss.org/ceforum/index.php

**Comment by muhammadsufiyan** [comment]
Thanks, isn't there is a release version binary for `cefsimple.exe`, it would be very helpful for me, thanks in advance.

**Comment by amaitland** [comment]
> Thanks, isn't there is a release version binary for cefsimple.exe, it would be very helpful for me, thanks in advance.

Your asking on the incorrect project, that's part of the `CEF` project.

**Comment by muhammadsufiyan** [comment]
thanks and really very sorry, I am disturbing you from the morning today, but last request from you, could you please give me a `release version binary for cefsimple.exe` by compiling it from your side cause my compilation and build gives me very slow performance and some little issue, 

it will be ok, if you are not interested.. I will not force you..

**Comment by amaitland** [comment]
> but last request from you, could you please give me a release version binary for cefsimple.exe by compiling it from your side cause my compilation and build gives me very slow performance and some little issue,

Good luck solving your problem.

> it will be ok, if you are not interested.. I will not force you..

This is an open source project, the only entitlement you have is access to the source code.

> and also make it available with every release of CEF for others too

`cefsimple` is not related to the `CefSharp` project.

**Comment by amaitland** [comment]
I'd also ask that you read https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

Please only open an issue if you have a verified **bug**, not just asking a question, specially one that's not even related to this project.......

**Comment by muhammadsufiyan** [comment]
sure, I will make sure I will not ask any question here except bugs.. thanks a lot :)
