### ISSUE TITLE
cefsharp 45  Could not load file or assembly 'CefSharp.Core.dll"

### ISSUE THREAD

**Issue by webdesus** [cefsharp/CefSharp#1624]
Hi all. We have problem with cefsharp 45 on some pc with windows 7 x64 service pack 1.  "Could not load file or assembly 'CefSharp.Core.dll"  We tried install. reinstall, uninstll and again install VC++ 2012/2013 Redistributable Package x86 and x64. But again get with error on 2 pc, other pc with same os work fine.

**Comment by rlmcneary2** [comment]
This is not a bug. See [issue template](https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md).
Try: https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#Runtime_dependencies

**Comment by webdesus** [comment]
it's not bug cefSharp but it's problem Windows. I don't know how it's happen in two pc. But on this pc not workin c++ 2013 application all. Not only cefSharp. I install, reinstall ,uninstall and again install. Reboots system many times. Using microsoft repair c++ tool, but only reinstall full windows helped me. I think maybe this information It will be useful.

**Comment by amaitland** [comment]
> it's not bug cefSharp but it's problem Windows. I

The request still stands, if you have a problem, first start by asking on `Gitter` before opening an issue. Thanks :+1:
