### ISSUE TITLE
Crash in CookieVisitor::Visit if website sets cookie with invalid DateTime

### ISSUE THREAD

**Issue by YaiEf** [cefsharp/CefSharp#1625]
- **What steps will reproduce the problem?**
Visit website that sets cookie with invalid expiration date.

- **What is the expected output? What do you see instead?**
It crashes hard. I'd expect it not to.

- **Where does the crash happen?**
When trying to create DateTime in:
bool CookieVisitor::Visit(const CefCookie& cefCookie, int count, int total, bool& deleteCookie) 

- **Suggested fix?**
Check if valid DateTime before creating or wrap DateTime creation in try catch.
Alternatively use a container type that supports the invalid dates.

**Comment by rlmcneary2** [comment]
Do you have any example of an invalid date? Far in the past, future? Would be helpful rather than guessing when trying to recreate the problem.

**Comment by amaitland** [comment]
> Check if valid DateTime before creating or wrap DateTime creation in try catch.
> Alternatively use a container type that supports the invalid dates.

@YaiEf If you have time please submit a `PR` with your proposed changes. Thanks :+1:

**Comment by YaiEf** [comment]
"Unfortunately" the problem has since disappeared from that website, so it was probably something transient, as I doubt they have fixed anything in the last two days. Their cookies were generally 1 month / 1 year / 100 years in the future, so not sure what caused the problem.

I have submitted a pull request for the simplest fix. It's my first pull request, so I hope I've done it correctly.

**Comment by amaitland** [comment]
Resolved with #1628
