### ISSUE TITLE
Cefsharp 43 can not get postdata of Request

### ISSUE THREAD

**Issue by lightspear** [cefsharp/CefSharp#1626]
![image](https://cloud.githubusercontent.com/assets/17800168/13723857/b67c087a-e8ac-11e5-89d6-6758e61d19cc.png)
this line find one bug,what i can do

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by amaitland** [comment]
If you have a question start with asking on `Gitter` as per the `Issue Template` linked above.
