### ISSUE TITLE
IsManipulationEnabled appears to break tapping on buttons

### ISSUE THREAD

**Issue by canton7** [cefsharp/CefSharp#1627]
CefSharp 47.0.3, Windows 8.1 (on a tablet), 32-bit, WPF.

I have an application which uses CefSharp, and I've set `IsManipulationEnabled = true` to enable touch-based scrolling (per https://github.com/cefsharp/CefSharp/pull/1418). However I have a user who reports that tapping on HTML buttons no longer works: the button is highlighted, but isn't actually clicked.

Setting `IsManipulationEnabled = false` solves the button-tapping issue, but (of course) breaks touch-based scrolling.

The user has tried the same operations using the CEF Test App for the appropriate CEF version, and is able to both scroll and successfully tap buttons.

Thanks!

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/issues/228#issuecomment-182135705

**Comment by canton7** [comment]
Somehow missed that one, thanks!
