### ISSUE TITLE
HTML5 video fullscreen

### ISSUE THREAD

**Issue by novastream** [cefsharp/CefSharp#1629]
Hi, I'm using cefsharp for my latest project but have some trouble getting a html5 / flash video work in fullscreen.

**Version** 47.0.3 (Winform) via nuget
**OS** Windows 8.1 x64
**Architecture**  x86
**Service** twitch.tv (eg. https://player.twitch.tv/?channel=CHANNEL_NAME)

So, when I click the fullscreen button nothing happends. If I implement DisplayHandler class and perform a throw on the fullscreen change method the program will crash which indicates that the function is triggered.

Is there any guidelines how to place the cef component on the form like docking, allowing the form to be maximized etc?

**Comment by novastream** [comment]
Here's a little something I did, it's kind of working but is this the right approach?

```
public void OnFullscreenModeChange(IWebBrowser browserControl, IBrowser browser, bool fullscreen)
        {
            var control = (Control)browserControl;
            Form test = (Form)control.Parent;

            if (fullscreen == true)
            {                
                if (control.InvokeRequired)
                {
                    control.Invoke(new MethodInvoker(
                        delegate {
                            test.WindowState = FormWindowState.Maximized;
                            test.FormBorderStyle = FormBorderStyle.None;
                            test.TopMost = true;
                        }
                    ));

                }

            }
            else
            {
                if (control.InvokeRequired)
                {
                    control.Invoke(new MethodInvoker(
                        delegate
                        {
                            test.WindowState = FormWindowState.Normal;
                            test.FormBorderStyle = FormBorderStyle.Fixed3D;
                            test.TopMost = false;
                        }
                    ));

                }
            }
        }
```

**Comment by amaitland** [comment]
Firstly read https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md Questions should be asked on `Gitter`.

Secondly, `OnFullscreenModeChange` is just a notification, it's up to you to implement, use whatever approach best suites your applications layout/design.

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/commit/7f1f1c5f214e10c77f3c47740e8ef9ac26830be9 for an example I wrote that demos one possible option.

**Comment by novastream** [comment]
Thanks amaitland =)

You could also use the following if FormWindowState.Maximized isn't covering the taskbar:
`fullScreenForm.Bounds = Screen.FromControl(fullScreenForm).Bounds`

**Comment by amaitland** [comment]
> You could also use the following if FormWindowState.Maximized isn't covering the taskbar:

In what scenario is that required?

**Comment by novastream** [comment]
This seems to be the scenario (just tested on Win 7 and Win 10)

`if (fullscreen)
{
fullScreenForm.WindowState = FormWindowState.Maximized;
}
else 
{
fullScreenForm.WindowState = FormWindowState.Normal;
}`

So if you do it like you did and dispose the form you shouldn't have this problem but if you decide to reuse the fullScreenForm you will notice the second time you try to go fullscreen the taskbar will be visible.

**Comment by amaitland** [comment]
> So if you do it like you did and dispose the form you shouldn't have this problem but if you decide to reuse the fullScreenForm you will notice the second time you try to go fullscreen the taskbar will be visible.

My example is just for demo purposes, something I hacked together in 5mins. By all means contribute a more polished version :+1:

**Comment by andrewjoseofficial** [comment]
+amaitland Can you help my open source web browser https://github.com/flameskyofficial/FlameSky by just doing one small thing. It is based on CefSharp. Can you please help me by making a pull request and enable full screen (such that Youtube fullscreen works). I really need help, please help me Alex.
