### ISSUE TITLE
MethodRunnerQueue can lock UI thread

### ISSUE THREAD

**Issue by dga711** [cefsharp/CefSharp#1630]
Upgrading from v33 to v47 (WPF) the application froze on initializing the browser control.

Turns out that the MethodRunnerQueue ran on the UI-Thread and therefore locked up the UI Thread.

`Task.Factory.StartNew` is used to run the `ConsumeTasks()`-loop. -> https://github.com/cefsharp/CefSharp/blob/master/CefSharp/Internals/MethodRunnerQueue.cs

Depending on where you come from it is then possible that this loop runs on the UI-Thread. Which should not happen ever.

Some information related to this ["Start New is Dangerous"](http://blog.stephencleary.com/2013/08/startnew-is-dangerous.html)

`Task.Factory.StartNew` should not be used here. Instead another method of starting the task async which can never hit the UI thread.

We changed it to this overload `TaskFactory.StartNew-Methode (Action, CancellationToken, TaskCreationOptions, TaskScheduler)` (https://msdn.microsoft.com/de-de/library/dd781658(v=vs.110).aspx) handing over Default-Scheduler

**Comment by amaitland** [comment]
Interesting that nobody else has had a problem, that code has been in the last couple of versions. So I wonder what your doing differently.

Anyways, please submit a `PR` with your proposed changes.

**Comment by dga711** [comment]
I agree. 
Think it has to do with our patterns and how we do things. The control is part of a dialog which gets opened by some Interaction-pattern.

If I understood correctly. Our dialog (interaction) is a Task inside the UI scheduling. 
Now CefSharp comes into play and when `TaskFactory.StartNew` gets called inside that Task, it uses that Task's scheduler (which in this case, is the UI scheduler) and locks it up.

As the MethodRunnerQueue starts a indefinitely running loop, it should really make sure that this can't happen at all.

**Comment by amaitland** [comment]
> As the MethodRunnerQueue starts a indefinitely running loop, it should really make sure that this can't happen at all.

My all means submit a `PR` with your proposed changes :+1:
