### ISSUE TITLE
Wpf ChromiumWebBrowser throws ObjectDisposedException after dispose

### ISSUE THREAD

**Issue by vasiliy-vdovichenko** [cefsharp/CefSharp#1631]
I explicitly dispose ChromiumWebBrowser on UI thread on closing current view (not entire app) 
after this sometimes I get following exception:

```
A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'This instance of CefSharp.IBrowserHost been disposed!'.
   at CefSharp.Internals.CefWrapper.ThrowIfDisposed()
   at CefSharp.Internals.CefBrowserHostWrapper.GetZoomLevelOnUI()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

I never invoke GetZoomLevelOnUI in my code and even not access the control in async.
It looks like ChromiumWebBrowser runs some operations in async mode but doesn't cancel them on dispose.

Environment:

-  CefSharp x86

- Windows 10

Could you please advise me how to work around this issue?

**Comment by amaitland** [comment]
Still some key pieces missing from your bug report, like what version are you using and how to reproduce the problem. Also please markup your code for easier reading.

> Could you please advise me how to work around this issue?

This is not a known issue, so there is no known workaround. Source is there, by all means get out the debugger.

**Comment by vasiliy-vdovichenko** [comment]
My usage of ChromiumWebBrowser  is pretty simple - wpf application has ContentControl which host current screen one of which may be screen with ChromiumWebBrowser.

XAML:
`<cefSharp:ChromiumWebBrowser x:Name="WebBrowser"  Grid.Row="1" Loaded="WebBrowser_OnLoaded"  />`

Code behind:

```
       private void WebBrowser_OnLoaded(object sender, RoutedEventArgs e)
        {
            ...
            if (view != null)
            {
                view.WebBrowser = WebBrowser;
                WebBrowser.RequestHandler = view;             
                WebBrowser.Address = view.HubAddress;
            }
        }
```

where view implement IRequestHandler and just provide credential to site and show login window and when we leave screen (Control.Unload) dispose ChromiumWebBrowser  

```
        protected override void OnDeactivate(bool close)
        {
            if (close)
            {
                if(WebBrowser != null) WebBrowser.Dispose();
            }
        }
```
Exception occurs when I try open new browser screen this causes closing current browser screen and disposing ChromiumWebBrowser  after this sometimes (not always) I have the exception.
So exception occurs accidentally.


I have looked in CefSharp code and found following:
CefBrowserHostWrapper contains following async method which in turned invokes GetZoomLevelOnUI which actually throws the exception 

```
Task<double>^ CefBrowserHostWrapper::GetZoomLevelAsync()
{
    ThrowIfDisposed();

    if (CefCurrentlyOn(TID_UI))
    {
        TaskCompletionSource<double>^ taskSource = gcnew TaskCompletionSource<double>();
        taskSource->SetResult(GetZoomLevelOnUI());
        return taskSource->Task;
    }
    return Cef::UIThreadTaskFactory->StartNew(gcnew Func<double>(this, &CefBrowserHostWrapper::GetZoomLevelOnUI));
}
```

Both GetZoomLevelAsync and GetZoomLevelOnUI check whether the controls is disposed but actually the control may be not disposed when GetZoomLevelAsync  and may be already disposed when during GetZoomLevelOnUI  execution.

I think that Dispose method should cancel all currently running task like GetZoomLevelAsync  or at least gracefully wait until they finished.

About work around until now I just can to decision add Thread.Sleep before calling WebBrowser.Dispose so that wait task in progress.

**Comment by amaitland** [comment]
Please fork [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) to demo your problem (using code snippets to reproduce just takes up way too much time). A reproducible test case is required to test any solution to this.

> Both GetZoomLevelAsync and GetZoomLevelOnUI check whether the controls is disposed but actually the control may be not disposed when GetZoomLevelAsync and may be already disposed when during GetZoomLevelOnUI execution.

`ThrowIfDisposed` should really only be called on those publicly facing methods, it was likely just copied and pasted into all methods. `GetZoomLevelOnUI` should just do nothing if disposed of already.

> I think that Dispose method should cancel all currently running task like GetZoomLevelAsync or at least gracefully wait until they finished.

Adding a `CancellationToken` overload is probably worth doing. I wouldn't be waiting for a graceful finish in a `Dispose` method. (You really could just subclass, `ChromiumWebBrowser` and override `OnIsBrowserInitializedChanged`, you could then avoid the call to `GetZoomLevelAsync`)

If you have time, then please contribute (this issue could easily sit here for 3-6mths otherwise).

**Comment by vasiliy-vdovichenko** [comment]
Test project are here https://github.com/vasiliy-vdovichenko/CefSharp.MinimalExample
Just try quickly click on "Open Browser" button many time but it looks like the bug may be reproducible not in all environment.

Thank you for idea to subclass ChromiumWebBrowser I have done this in following way:
```
        protected override void OnIsBrowserInitializedChanged(bool oldValue, bool newValue)
        {
            if (newValue && !IsDisposed)
            {
                Task<double> task = this.GetZoomLevelAsync();
                task.ContinueWith(previous =>
                {
                    if (previous.Status == TaskStatus.RanToCompletion)
                    {
                        Execute.OnUIThread(() =>
                        {
                            if (!IsDisposed)
                            {
                                SetCurrentValue(ZoomLevelProperty, previous.Result);
                            }
                        });
                    }
                    else if(previous.IsFaulted || previous.IsCanceled)
                    {
                        // Just observe exception
                        var ex = previous.Exception;
                    }
                }, TaskContinuationOptions.ExecuteSynchronously);
            }
        }
```

I have also noticed that in original OnIsBrowserInitializedChanged you are incorrectly  uses Task.IsCompleted:

 ```
        protected virtual void OnIsBrowserInitializedChanged(bool oldValue, bool newValue)
        {
            if (newValue && !IsDisposed)
            { 
                var task = this.GetZoomLevelAsync();
                task.ContinueWith(previous =>
                {
                    if (previous.IsCompleted)
                    {
                       ....
                    }
                    else
                    {
                        throw new InvalidOperationException("Unexpected failure of calling CEF->GetZoomLevelAsync", previous.Exception);
                    }
                }, TaskContinuationOptions.ExecuteSynchronously);
            }
        }
```

Task.IsCompleted means that task was completed or faulted or canceled else statement here will be never executed - instead successful execution should be tests as 
`previous.Status == TaskStatus.RanToCompletion`


>ThrowIfDisposed should really only be called on those publicly facing methods, it was likely just copied and pasted into all methods. GetZoomLevelOnUI should just do nothing if disposed of already.

Yes I think this would be the best way to fix the issue.

**Comment by amaitland** [comment]
> I have also noticed that in original OnIsBrowserInitializedChanged you are incorrectly uses Task.IsCompleted:

What makes you think I added this section of code? I'm not even sure what it's intended purpose was. Original commit was https://github.com/cefsharp/CefSharp/commit/fdd55084671721216c3a7dbce99b0151727a5fb3#diff-bfec65df46ec49f4ed79472147689599

> Task.IsCompleted means that task was completed or faulted or canceled else statement here will be never executed - instead successful execution should be tests as
> previous.Status == TaskStatus.RanToCompletion

As I've said before, rather than make comments about improvements, submit a `PR`.

**Comment by vasiliy-vdovichenko** [comment]
> What makes you think I added this section of code? I'm not even sure what it's intended purpose was. Original commit was fdd5508#diff-bfec65df46ec49f4ed79472147689599

Sorry I did mean personally you I just mean team of contributors in whole. 

Have submitted PR.
