### ISSUE TITLE
WPF, OffScreen GPU Problems

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#1634]
After upgrading to `2623`, there is a noticable rendering problem when `GPU` acceleration is enabled in both the `WPF` and `OffScreen` projects. (You don't physically notice in `OffScreen`, the errors are in the `debug.log` file).

I have raised the issue on http://magpcss.org/ceforum/viewtopic.php?f=6&t=13997

Simply workaround is to use the `--disable-gpu` command line flag (search the source if you require an example of it's usage).

If you experience this problem, please simply post your Windows Version and graphics card make and model.

When I have more information I will post it here. No need to create an issue.

Log entry is:
```
[0318/115339:ERROR:gles2_cmd_decoder.cc(12228)] Context lost because SwapBuffers failed.
[0318/115339:ERROR:gles2_cmd_decoder.cc(4471)] Error: 5 for Command kPostSubBufferCHROMIUM
[0318/115339:ERROR:gpu_command_buffer_stub.cc(1224)] Exiting GPU process because some drivers cannot recover from problems.
[0318/115340:ERROR:gpu_process_transport_factory.cc(652)] Lost UI shared context.
```

#### Update
- For those using `49.0.x` you must disable `GPU` acceleration (example below)
- For those using `51.0.x` see comments about `app.manifest` below, if that doesn't work then disable `GPU` acceleration. This only works on `Windows 10`

 If your seeing Flickering/Flashing/Dissapearing/Redraw on page rendering, that's related to this issue.

For those requiring an example of using the `disable-gpu` command line argument see https://github.com/cefsharp/CefSharp/blob/1e18b55116190ea4e1b0c84dc7e6a2b84ec25eb2/CefSharp.Example/CefExample.cs#L77

**Comment by mtinnes** [comment]
Similar issue using Wpf. Web controls constant flickering to black and reduced app responsiveness. 64bit Win10, with Intel chipset. Disabling gpu did help.

**Comment by amaitland** [comment]
Moving this to the `51.0.0` milestone as `49.0.0` has been released. When the `2704` packages are on `cefbuilds.com` will need to recheck this problem.

**Comment by amaitland** [comment]
For those requiring an example of using the `disable-gpu` command line argument see https://github.com/cefsharp/CefSharp/blob/1e18b55116190ea4e1b0c84dc7e6a2b84ec25eb2/CefSharp.Example/CefExample.cs#L77

**Comment by amaitland** [comment]
Looks like this is resolved in the `CEF` `2704` branch.

**Comment by amaitland** [comment]
`master` has been updated to `2704. `GPU` acceleration appears to be working again. Closing

**Comment by amaitland** [comment]
Look like an `app.manifest` is required, an example can be found https://github.com/cefsharp/CefSharp.MinimalExample/commit/c4d06053077723f308eb722bd35b6fb30dd52c0e

The `compatibility/application` section seems to be the key.

**Comment by amaitland** [comment]
Important to note that I've only tested this on `Windows 10`.

**Comment by AWeeg** [comment]
When is 51.0.0 going to be released? I am seeing a lot of flickering, disabling GPU acceleration doesn't see to make a difference

**Comment by amaitland** [comment]
> I am seeing a lot of flickering, disabling GPU acceleration doesn't seem to make a difference

I'd suggest rolling back to `47.0.4`

> When is 51.0.0 going to be released?

A `-pre` release will be out shortly.

**Comment by amaitland** [comment]
`51.0.0-pre01` has been pushed to `Nuget.org`, see the release notes for full details as this version is build with `.Net 4.5.2`.

If you find the suggestion about adding to your `app.manifest` above doesn't work then either disable `GPU` acceleration or rollback to `47.0.4` are your only other options.

**Comment by AWeeg** [comment]
downloaded the pre release from nuget and added to the app.manifest but i still see the flickering (not as bad) if I add 
 var settings = new CefSharp.CefSettings();
  settings.SetOffScreenRenderingBestPerformanceArgs();
  CefSharp.Cef.Initialize(settings);

it seems to make all the flickering go away, should i just use that instead?

**Comment by amaitland** [comment]
> it seems to make all the flickering go away, should i just use that instead?

@AWeeg Use whatever works for you.

**Comment by amaitland** [comment]
> downloaded the pre release from nuget and added to the app.manifest but i still see the flickering (not as bad)

@AWeeg What `OS` and `Graphics` card are you using?

**Comment by amaitland** [comment]
> @AWeeg What OS and Graphics card are you using?

@AWeeg Can you please confirm what `OS` and `GPU` your using?

**Comment by AWeeg** [comment]
@amaitland  I am using windows 7 enterprise, GPU Intel HD Graphics 4600

**Comment by amaitland** [comment]
`Intel Graphics` cards are the worst affected by this issue, make sure you apply `disable-gpu` for those.

**Comment by amaitland** [comment]
To follow the `upstream` bug use https://bitbucket.org/chromiumembedded/cef/issues/1889/off-screen-webgl-not-working-in-2623

**Comment by AWeeg** [comment]
thank you @amaitland!

**Comment by tylerlong** [comment]
After adding `settings.SetOffScreenRenderingBestPerformanceArgs();` my app has no more flickering issue.

Windows 10 64-bit

**Comment by amaitland** [comment]
@tylerlong Effectively you've just disabled the GPU, be aware that DevTools may not render correctly.

**Comment by tylerlong** [comment]
@amaitland Thank you for the reminder. I don't need advanced features for my app so it's not a problem for me.

**Comment by amaitland** [comment]
More information on the `upstream` problem https://bitbucket.org/chromiumembedded/cef/issues/1933/offscreen-rendering-enable-gpu-without

**Comment by amaitland** [comment]
> Using CEF with Offscreen Rendering and GPU enabled works quite well if direct compositing is available, but is quite unstable if not. "Unstable" here means that the GPU process crashes basically on every buffer swap. (Direct compositing is only always enabled on Windows 10, not supported on Windows 7. Enablement on Windows 8 and 8.1 changed between Chromium revisions.) Direct compositing can be disabled by making Chromium think it's on an older Windows or by passing --disable-direct-composition to the GPU process.

Basically it should work on `Windows 10 if you add the relevant entries to your `app.manifest` using the `51.0.x` based version.

**Comment by amaitland** [comment]
This has been fixed `upstream` and will be part of the `53.0.0` release.

**Comment by amaitland** [comment]
`master` has been upgraded, issue appears to be resolved. Will be part of `53.0.0`, please no questions about when this will be ready, just check https://github.com/cefsharp/CefSharp/releases for yourself.

**Comment by panalgin** [comment]
Whatever I have tried, it persist with the current stable release v51, using and targeting windows 7 64 bit. This problem didnt existed in v47. I just upgraded cefsharp to v49 and boom. Even to v51, again kaboom. I  have an NVIDIA GeForce 430, not bad for showing a simple webpage.

It became 26 days since you wrote, but there is no a release or just a dirty fix for this fix for this. 


Thanks anyway for the effort you guys are putting together, I still love cefsharp even I cant use it now. (PS: I dont want to host winform wrapper in a wpf app)

**Comment by amaitland** [comment]
@panalgin What is the purpose of your comment? There is a fix, as I've already said `master` has been updated. You can of course build it for yourself or use a `CI` build https://github.com/cefsharp/CefSharp#build-status

> It became 26 days since you wrote, but there is no a release

Patience is required, this is not a commercial project.

**Comment by amaitland** [comment]
`53.0.0-pre01` packages are available on `Nuget.org`, first version to include the fix for this issue.
