### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by polymex2016** [cefsharp/CefSharp#1635]
#### Issue Summary
What is the expected output? What do you see instead?

#### Steps to Reproduce
1. This is the first step

This is a bug because...
Code sample if relevant
Does this problem also occur in the `Cef` TestApp from http://cefbuilds.com?

#### Technical details
* CefSharp Version: nuget - master - latest commit:  INSERT COMMIT REF
* Operating System: 
* x86/x64: 
* WinForms/WPF/OffScreen:

**Comment by amaitland** [comment]
@polymex2016 If you have a problem how about jumping on `Gitter` first as requested?

https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md
