### ISSUE TITLE
The status of checkbox can not print in winform,How can I print it?

### ISSUE THREAD

**Issue by ducs** [cefsharp/CefSharp#1636]
Issues are for bug reports only. A simple 'Feature x doesn't appear to be working` is not a bug report!

So you have a question to ask, where can you look for answers?

- Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
- GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
- You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
- You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp
 
**Note: CefSharp is just a wrapper around the Chromium Embedded Project, it's worth searching http://magpcss.org/ceforum/index.php if your problem involves a low level Chromium error message**

We ask that you put in a reasonable amount of effort in searching through the resources listed above. The developers have full time jobs, they have lives, families, the time they have available to contribute this project is a precious resource, make sure you use it wisely! Remember the more time we spend answering the same questions over and over again, less time goes into writing code, adding new features, actually fixing bugs!

Still have a question to ask or unsure where to go next? Start with the Gitter Chat room : https://gitter.im/cefsharp/CefSharp

--
To continue submitting a bug report, delete everything above, and then fill in the details below.

- **What steps will reproduce the problem?**

- **What is the expected output? What do you see instead?**

- **Are you using `WinForms`, `WPF` or `OffScreen`?**

- **What version of the product are you using? On what operating system? x86 or x64?**
    - What version are you using? Nuget? CI Nuget? build from a branch? If so which branch?

    - Win7, Win 8, Win10, etc?

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?

- **Does this problem also occur in the `Cef` TestApp from http://cefbuilds.com?**

**Comment by amaitland** [comment]
> Issues are for bug reports only. A simple 'Feature x doesn't appear to be working` is not a bug report!

@ducs Please actually read the information contained in the template above.

**Comment by sidvishnoi** [comment]
@ducs please contact me at twitter.com/sid_vishnoi
(Sorry to community members, I couldn't find any other method to contact him)
