### ISSUE TITLE
After introducing ReferrerUrl the Referer header is empty

### ISSUE THREAD

**Issue by Scratch-net** [cefsharp/CefSharp#1638]
In v.45 we used request.Headers["Referer"] which is now null after upgrading to v.47. In the changelog I found the new ReferrerUrl property but no sign of removing the header which looks like a bug to me.

**Comment by amaitland** [comment]
> In the changelog I found the new ReferrerUrl property but no sign of removing the header which looks like a bug to me.

A bug in what way?

> Note: CefSharp is just a wrapper around the Chromium Embedded Project, it's worth searching http://magpcss.org/ceforum/index.php if your problem involves a low level Chromium error message

As per https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

`CefSharp` is just a wrapper. Would have been helpful if you referenced the commit your talking about.

**Comment by amaitland** [comment]
`CEF` maintains branches for each version (as `CefSharp` does). If you look at https://bitbucket.org/chromiumembedded/cef/commits/branch/2526

You'll see the referrer changes https://bitbucket.org/chromiumembedded/cef/commits/e7a02fe00fe02faeee6c20369b44004cbaad6c9e?at=2526

**Comment by Scratch-net** [comment]
Yep, sorry, I had no idea it has something to do with the chromium engine

**Comment by amaitland** [comment]
For reference there was also #1464

> Yep, sorry, I had no idea it has something to do with the chromium engine

No problem. In future, jump on https://gitter.im/cefsharp/CefSharp ask for some clarification (also to say `Hi` :smile: ).
