### ISSUE TITLE
Accept-Language not working

### ISSUE THREAD

**Issue by Astimus** [cefsharp/CefSharp#1639]
I need to change browser language to Russian.
Tryed two methods:
1) `CefBrowser.BrowserSettings.AcceptLanguageList = "ru-RU";`
2)
```c#
CefReturnValue IRequestHandler.OnBeforeResourceLoad(IWebBrowser browserControl, IBrowser browser, IFrame frame, IRequest request, IRequestCallback callback)`
{
    var headers = request.Headers;
    headers.Add("Accept-Language", "ru-RU");
    return CefReturnValue.Continue;
}
```
Neither work
All pages render like in English browser.
Using last version of CefSharp.

**Comment by rlmcneary2** [comment]
> Please use [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/cefsharp/CefSharp?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge) as your first point of call for basic/simple questions.

https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md

Already answered here #1200 .

**Comment by amaitland** [comment]
> Using last version of CefSharp.

You need to specify the exact version when posting here, `last version` is relative (and you would be surprised the number of people who say that and turn out to be using a very old version).

I also edited your code markdown as it was incredibly hard to read, please mark down your code for readability in future.

> 1) CefBrowser.BrowserSettings.AcceptLanguageList = "ru-RU";

At what point did you try setting `AcceptLanguageList`? You'll need to set it before the underlying browser is initialized. Quick test with `ru-RU` and loading `google.com` shows localized text, so I believe it's working correctly.

Example
https://github.com/amaitland/CefSharp/commit/96cb6ddebae3f9ed8e7b9317d5445434b8c91466

**Comment by Astimus** [comment]
Thank you for answer. My code was correct and all was fine with cefSHarp. (google.com translated to russian) Problem was in CKeditor - wysiwyg editor. I changed default language in CKeditor config to russian. But i don't understand why in Google Chrome and Mozilla it works correctly. While for CefSharp i hardcoded default language = Russian.

**Comment by amaitland** [comment]
> My code was correct and all was fine with cefSHarp. (google.com translated to russian)

Excellent, closing this now. (Next time please ask on `Gitter` before opening an issue please)
