### ISSUE TITLE
Hi,How to building a version which can run on windows xp sp3 with .Net4.0

### ISSUE THREAD

**Issue by Comup-X** [cefsharp/CefSharp#1640]
wpf and winform both ok
I'm a newer thank your
hope your anwser

**Comment by Comup-X** [comment]
chromium version with 47 thank u

**Comment by rlmcneary2** [comment]
Not a bug.
> Please use [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/cefsharp/CefSharp?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge) as your first point of call for basic/simple questions.

https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md

> Please don't create **new** issues related to `Windows XP`. The following https://github.com/cefsharp/CefSharp/wiki/Windows-XP-No-Longer-Supported `Wiki` page may be useful and can be edited by anyone with a `GitHub` account, so feel free to contribute any information you think may prove useful.

https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#XPSupport
