### ISSUE TITLE
Issue with loading example projects 

### ISSUE THREAD

**Issue by jdc20181** [cefsharp/CefSharp#1642]
Examples are not wanting to work!!!!! 
I opened a new project because I only want to look at the win forms example nothing else...So I go to add, existing project and get a error telling me I need to check and make sure it exists. I have attatched a Screen Shot of the error. 
![screenshot 141](https://cloud.githubusercontent.com/assets/13263110/13991385/545077c2-f0ee-11e5-9de0-d79eb228f2da.png)

**Comment by dga711** [comment]
Just open the CefSharp3 Solution. Set the example project as startup project and hit Run.

As this is not an issue at all, please ask in "gitter" chat next time.

**Comment by amaitland** [comment]
You can use https://github.com/cefsharp/CefSharp.MinimalExample

As stasted please ask your questions on gitter
