### ISSUE TITLE
Pulltorefresh event

### ISSUE THREAD

**Issue by YurdagulP** [cefsharp/CefSharp#1645]
Hi,

In my wpf project, I use 47.0.3.0 version of Cefsharp chromium. Pulltorefresh works when I clicked on two button of mouse at the same time, how can I set it to work with only left button click?

Is there any event to provide only left click instead of "touch-events"?

CefSettings settings = new CefSettings();
settings.CefCommandLineArgs["touch-events"] = "disabled";
Cef.Initialize(settings, true, true);

Thanks.

**Comment by amaitland** [comment]
`WPF` does not have touch support as it's not yet implemented `upstream`, see #228 

> Pulltorefresh works when I clicked on two button of mouse at the same time, how can I set it to work with only left button click?

The `WPF` control doesn't provide any special consideration for `Pull to Refresh` so I'm not really sure what your referring to here.

In general, if you require a **custom** behavior, it's best to search through the source code to see how the current control is implemented.

**Comment by amaitland** [comment]
Closing due to lack of response from `OP`.
