### ISSUE TITLE
based on issue https://github.com/cefsharp/CefSharp/issues/1127

### ISSUE THREAD

**Issue by cybergogic** [cefsharp/CefSharp#1646]
Hi! I'm copy files to system32 and it's starts good.
i tried to Cef.Initialize(new CefSettings()) in separate thread but IIS has been crashed.
Please help me anybody, who got working CefSharp WebService ASP.NET code sample.
I have good samples in WinForms and WPF.
Thanks.

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md
