### ISSUE TITLE
ContextMenuCommand Undo and Redo , CTRL + C,CTRL +Y is not the same.

### ISSUE THREAD

**Issue by feliciwithme** [cefsharp/CefSharp#1647]
The shortcut , contextmenu,ctrl+c, ctrl v, undo rendo,  Content is not synchronized。
Version: CefSharp-49.0.0-pre01 (45.0, 47.03)
OS: WIN 10 64bit

**Comment by amaitland** [comment]
Fill out the issue template please

https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by feliciwithme** [comment]
@amaitland 
I understand. Thanks for your reminding。

**Comment by amaitland** [comment]
> I understand. Thanks for your reminding。

I'm not quite sure you understood. If you submit a genuine issue (not just a question), you must use the issue template. I've updated your original post, please fill in the required information. I have no idea if your referring to `WinForms` or `WPF`, you failed to include steps to reproduce your problem.

**Comment by feliciwithme** [comment]
It's lib_cef bug, google chrome is correct.

**Comment by amaitland** [comment]
> It's lib_cef bug, google chrome is correct.

If there's an open bug it's best if you link to it.

You need to start putting some more detail in your comments, they need more information to be useful.
