### ISSUE TITLE
unexpected windows drawing on resize/minimize mdi child window (WinForms - 64 bit version)

### ISSUE THREAD

**Issue by fsimon21** [cefsharp/CefSharp#1649]
Hello,
i have built a 64 bit Windows form application that has a strange issue when i resize a mdi child window.
it can be clear viewed on the image attached, the window goes under the menu of the mdi parent form and doesn't show the function menu on the right side of the screen (minimize, maximize, close).
This problem happens only on a window where cefsharp is used and the application runs on Windows 8.1, cefSharp 39.0.0.0 version

![cefsharpissue](https://cloud.githubusercontent.com/assets/9480493/14241087/f12369f6-fa49-11e5-9e30-280cd26d0f7c.jpg)

**Comment by amaitland** [comment]
> Windows 8.1, cefSharp 39.0.0.0 version

Does the problem reproduce using the latest stable release? (`47.0.3`). The version you are using is no longer supported.

Also is there a reason you didn't fill out the bug report provided by the issue template? Was the field not pre populated when you created your issue?

https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by fsimon21** [comment]
sorry, i haven't read well how to fill the bug report, i will do it better in future ;-)

ok, i wasn't around for a while, i'll try the new version and let you know if it works

thanks!

**Comment by fsimon21** [comment]
hello again, i still have strange windows drawing issues

**What steps will reproduce the problem?**

Unfortunately seems to be a casual problem,
it happens with 2 or more mdi child forms maximized, and i use a menu item as button to switch between the forms opened and bring one of them to front. i don't do any other operation (no minimize, no close, etc)
i put other details on the screenshot attached

**What is the expected output? What do you see instead?**
forms should remains maximized when i use the switch button to bring one of them in front

**Are you using WinForms, WPF or OffScreen?**
WinForms

**What version of the product are you using? On what operating system? x86 or x64?**
x86 debug, x64 release, but the problem is in both versions


**What version are you using? Nuget? CI Nuget? build from a branch? If so which branch?**
cefsharp/47 branch

**Win7, Win 8, Win10, etc?**
windows 8.1

**Please provide any additional information below.**
none
A stack trace if available, any Exception information.
none
Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
none
Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
none
**Does this problem also occur in the Cef TestApp from http://cefbuilds.com?**
i can't reproduce it with testapp because i can't do the same thing with it

thanks again!

![form](https://cloud.githubusercontent.com/assets/9480493/14381345/06408bd6-fd86-11e5-9f7b-a2ba1a738e32.JPG)

**Comment by amaitland** [comment]
@fsimon21 Can you provide an example that demos your problem? There are no `MDI` examples currently.

**Comment by amaitland** [comment]
> Does the problem reproduce using the latest stable release? (47.0.3). The version you are using is no longer supported.

I'd be upgrading if possible.

**Comment by amaitland** [comment]
Any update on this? Are you able to reproduce using the latest version?

**Comment by fsimon21** [comment]
i haven't been able to reproduce the problem yet because it is too random, you can close this issue and i will open it again when i will find a solution

thanks
