### ISSUE TITLE
IContextMenuHandler.OnBeforeContextMenu is not called when user does rapid right clicks.

### ISSUE THREAD

**Issue by ali-hs** [cefsharp/CefSharp#1652]
I am using cefsharp version 47.0.2 in my app. This app shows couple of options on right click menu. IContextMenuHandler.OnBeforeContextMenu is not called when user does rapid right clicks.

**Comment by amaitland** [comment]
> Issues are for bug reports only. A simple 'Feature x doesn't appear to be working` is not a bug report!

https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by amaitland** [comment]
If you actually with to lodge a bug report then use the template provided.
