### ISSUE TITLE
CefSharp.Common, 49.0.0-pre1, nuget package version dependency error

### ISSUE THREAD

**Issue by skotten** [cefsharp/CefSharp#1654]
CefSharp.Common 49.0.0-pre1 depends on cef.redist.* version == 3.2623.1395.

But cef.redist.* 3.2623.139**5** has been withdrawn and replaced by rev. 139**6** of the cef.redist.* packages.

I understand this is a pre-release, but perhaps the build scripts could be updated to not break depending packages by withdrawing dependencies? By either leaving the old dependency packages available or wait with publishing new depending packages until the whole library 'chain' pass build and can be published together.

**Comment by amaitland** [comment]
Thanks for pointing that out, packages have been delisted from `Nuget.org`. Will release a new set sometime soonish.

**Comment by amaitland** [comment]
> I understand this is a pre-release, but perhaps the build scripts could be updated to not break depending packages by withdrawing dependencies?

It's a human error, not the build scripts fault. It could potentially be improved by querying the packages.config file from the `CefSharp.Core` project to detect which version is currently being used. If you have time, by all means make a contribution :+1: 

> By either leaving the old dependency packages available or wait with publishing new depending packages until the whole library 'chain' pass build and can be published together.

The packages are only generated upon a successful build.

**Comment by amaitland** [comment]
New packages have been released.
