### ISSUE TITLE
BrowserSubprocess crashes

### ISSUE THREAD

**Issue by KrzychuR** [cefsharp/CefSharp#1655]
Hi,

I'm writting dedicated webrowser for some really funy game. From time to time BrowserSubProcess disaperring (crashes propably). Last information from debug.log file is:

```
[0409/181102:INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'de' of undefined", source: https://w1.crownofthegods.com/jsfunctions/game.js?v=1.84 (1)
[0409/181107:INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'de' of undefined", source: https://w1.crownofthegods.com/jsfunctions/game.js?v=1.84 (1)
[0409/181110:INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'de' of undefined", source: https://w1.crownofthegods.com/jsfunctions/game.js?v=1.84 (1)
[0409/181700:INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'getTileX' of null", source: https://w1.crownofthegods.com/jsfunctions/game.js?v=1.84 (1)
[0409/181718:INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'de' of undefined", source: https://w1.crownofthegods.com/jsfunctions/game.js?v=1.84 (1)
```

The game JS files are obfuscated and have bugs, right... but maybe it is someting specific wchich results in subprocess crass?...

If you need more specific debug data - I need some tips how to generate it. The bug is reproducible ony many user machines.

--
Br

**Comment by KrzychuR** [comment]
A Little bit info: it is WPF, .NET 4.5 project and I use 47.0.3 + 3.2526.1362 version of cef.redist.x86 (nuget package)

**Comment by amaitland** [comment]
What other information can you provide? How can the problem be reproduced? Very little information to go by so far.

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#unmanaged-crashes-when-the-process-dies

**Comment by KrzychuR** [comment]
Thanks for the link, I found this in windows event log:

```
Application: CefSharp.BrowserSubprocess.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at <Module>.CefExecuteProcess(CefMainArgs*, CefRefPtr<CefApp>*, Void*)
   at CefSharp.CefAppWrapper.Run()
   at CefSharp.BrowserSubprocess.Program.Main(System.String[])
```

and next:

```
Faulting application name: CefSharp.BrowserSubprocess.exe, version: 47.0.3.0, time stamp: 0x56ce5bf5
Faulting module name: libcef.dll, version: 3.2526.1362.0, time stamp: 0x56710443
Exception code: 0xc0000005
Fault offset: 0x002f30c3
Faulting process id: 0x2134
Faulting application start time: 0x01d192a51121f2d6
Faulting application path: C:\Users\k_rac_000\AppData\Local\Apps\2.0\K1XDLHZY.OQ7\R511BGW0.MLW\cotg..tion_1b11e48c10eda2e0_0000.0007_985656babaf035a2\CefSharp.BrowserSubprocess.exe
Faulting module path: C:\Users\k_rac_000\AppData\Local\Apps\2.0\K1XDLHZY.OQ7\R511BGW0.MLW\cotg..tion_1b11e48c10eda2e0_0000.0007_985656babaf035a2\libcef.dll
Report Id: c61536dc-3443-4f57-8f17-aa9e25c5a765
```

**Comment by KrzychuR** [comment]
Is it possible to run BrowserSubprocess in debug mode? any switches? because it happens quite often...

**Comment by amaitland** [comment]
Try downloading the release symbols as per the last comment in https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#loading-native-symbols-for-easier-diagnosis

**Comment by amaitland** [comment]
> Is it possible to run BrowserSubprocess in debug mode? any switches? because it happens quite often...

Compile the project from source, attach the debugger like the link I posted above suggests.

**Comment by amaitland** [comment]
Next version there will be symbols available through `Nuget`

**Comment by KrzychuR** [comment]
I will try with .pdb file first

**Comment by amaitland** [comment]
> I'm writting dedicated webrowser for some really funy game.

Is the game open source or publicly accessible?

**Comment by KrzychuR** [comment]
Publicly accessible, www.crownofthegods.com
I'm embeded control in WPF app and basically it works great.... except this one :) If DOM structure is massivelly changed then subprocess crashed - it is only my observation of course.

**Comment by KrzychuR** [comment]
And... it is not easy to reproduce... It happens... quite ofter but... I can not provide steps to reproduce it.

**Comment by amaitland** [comment]
If you need performance then you may have better luck running the `WinForms` control hosted in `WPF`.

**Comment by KrzychuR** [comment]
Hmmm I'm not sure if proper version of pdb file is available... because I have libcef.dll version: 3.2526.1362.0 and... I've downloaded this one: CEF 3.2526.1373.gb660893 ...

**Comment by amaitland** [comment]
> because I have libcef.dll version: 3.2526.1362.0 and... I've downloaded this one: CEF 3.2526.1373.gb660893 ...

It is available. Using a different version is not going to work.

**Comment by KrzychuR** [comment]
Hahaha.... right... link 'more'... :) :)

**Comment by KrzychuR** [comment]
Hmm... PDB doesn't help me... 
Any idea how to enable more verbose diagnostics about crashes without running SubProcess under debugger ?

**Comment by KrzychuR** [comment]
More info after use 

`
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at CefExecuteProcess(CefMainArgs* , CefRefPtr<CefApp>* , Void* )
   at CefSharp.CefAppWrapper.Run()
   at CefSharp.BrowserSubprocess.Program.Main(String[] args)
Backtrace:
        (No symbol) [0x0FD630C3]
        (No symbol) [0x118232F1]
        (No symbol) [0x117FE13C]
        (No symbol) [0x103D29F1]
        (No symbol) [0x1002F9DE]
        (No symbol) [0x1002F936]
        (No symbol) [0x1011578B]
        (No symbol) [0x101158C7]
        (No symbol) [0x1010FB96]
        (No symbol) [0x1F863DCD]
        (No symbol) [0x210A0D68]
        (No symbol) [0x2345ADD2]
        (No symbol) [0x2345ADED]
        (No symbol) [0x2D94224E]
        (No symbol) [0x2346BC99]
        (No symbol) [0x1F85C645]
        (No symbol) [0x23D2D401]
        (No symbol) [0x23D29D1F]
        (No symbol) [0x11A0CBC0]
        (No symbol) [0x11A0C566]
        (No symbol) [0x0FECDA83]
        (No symbol) [0x10902B99]
        (No symbol) [0x108409AD]
        (No symbol) [0x108AF408]
        (No symbol) [0x10305B8B]
        (No symbol) [0x103236DF]
        (No symbol) [0x10323AFE]
        (No symbol) [0x102D2A6F]
        (No symbol) [0x1051E11C]
        (No symbol) [0x0FFB2F71]
        (No symbol) [0x0FF91488]
        (No symbol) [0x10CCE802]
        (No symbol) [0x11CE9F47]
        (No symbol) [0x11CEBA70]
        (No symbol) [0x11CEC52A]
        (No symbol) [0x0FC08065]
        (No symbol) [0x10DD5015]
        (No symbol) [0x10DD485D]
        (No symbol) [0x10DD523F]
        (No symbol) [0x0FC08065]
        (No symbol) [0x0FBD636F]
        (No symbol) [0x0FBD5D79]
        (No symbol) [0x0FC09957]
        (No symbol) [0x0FBD6090]
        (No symbol) [0x0FBD604D]
        (No symbol) [0x1209248B]
        (No symbol) [0x113A5C8E]
        (No symbol) [0x113A5B3D]
        (No symbol) [0x113A5293]
        (No symbol) [0x0FB0C484]
        (No symbol) [0x0FADE97D]
        CefSharp::CefAppUnmanagedWrapper::OnFocusedNodeChanged [0x6385DCD9+53009]
        (No symbol) [0x00D8675E]
        (No symbol) [0x00D8663A]
        (No symbol) [0x00D84C30]
        (No symbol) [0x72BA1376]
        (No symbol) [0x72BA366F]
        DllUnregisterServerInternal [0x72BAD376+3746]
        CorExeMain [0x72CD6CC3+4760]
        GetMetaDataPublicInterfaceFromInternal [0x72CBA4BB+28809]
        GetMetaDataPublicInterfaceFromInternal [0x72CBAAE3+30385]
        GetMetaDataPublicInterfaceFromInternal [0x72CBAB89+30551]
`

**Comment by amaitland** [comment]
You downloaded the `Release Symbols`? I'm surprised it says `No Symbol`

> CefSharp::CefAppUnmanagedWrapper::OnFocusedNodeChanged [0x6385DCD9+53009]

Are you using the `IRenderProcessMessageHandler.OnFocusedNodeChanged` feature?

**Comment by KrzychuR** [comment]
Yes, this one: cef_binary_3.2526.1362.g26b3a7a_windows32_release_symbols.7z
Application is compiled in release mode and for x86.

Regarding OnFocusedNodeChanged  - no... 

I'm using interface between JS and C# through ChromiumWebBrowser.RegisterJsObject method. 
The SubProcess always crashes during typical webpage usage, not during activity between JS and C#.

**Comment by amaitland** [comment]
> Application is compiled in release mode and for x86.

It's not actually relevant if your app is compiled in `Release` mode, it will always be the `Release Symbols` even if you compiled in `Debug` as it's the dlls that are shipped in the `Nuget` package that are relevant.

Downloading the source, running from within the debugger with a `Debug` build sounds like your best bet to get more information at the moment.

**Comment by KrzychuR** [comment]
> Downloading the source, running from within the debugger with a Debug build sounds like your best bet to get more information at the moment.

It's takes some time... I'm overloaded this week... but maybe I will try...

**Comment by KrzychuR** [comment]
I've attached debugger to BrowserSubprocesses but I can not find anything... I can not event check callstack... hmmm propably I need to some knowledge how to debug this kind of solutions :(

I found only something like this:

![image](https://cloud.githubusercontent.com/assets/18367771/14413741/91c639a4-ff83-11e5-9643-f8795f420281.png)

**Comment by amaitland** [comment]
Use the `Copy Exception detail to clipboard`, then paste that into `Notepad`, see what information it yields.

**Comment by amaitland** [comment]
If you can provide a method to reproduce the problem that requires 10-15mins I'll take a look sometime.

**Comment by KrzychuR** [comment]
Details are exactly the same like previous:

```
System.AccessViolationException was unhandled
  HResult=-2147467261
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=CefSharp.BrowserSubprocess.Core
  StackTrace:
       at CefExecuteProcess(CefMainArgs* , CefRefPtr<CefApp>* , Void* )
       at CefSharp.CefAppWrapper.Run() in c:\projekty\proitsoft\cotglibs\cotglibs\cefsharp_src\cefsharp-cefsharp-47\cefsharp.browsersubprocess.core\cefappwrapper.cpp:line 21
       at CefSharp.BrowserSubprocess.Program.Main(String[] args) in C:\projekty\ProITSoft\CotGLibs\CotGLibs\CefSharp_Src\CefSharp-cefsharp-47\CefSharp.BrowserSubprocess\Program.cs:line 24
  InnerException: 
```

I trying to run this webpage under included WPF example and hmm... I can not reproduce this exception yet...

**Comment by KrzychuR** [comment]
_focusedNodeChangedEnabled is not accessible after exception... maybe it is some hint for you...

**Comment by amaitland** [comment]
> _focusedNodeChangedEnabled is not accessible after exception... maybe it is some hint for you...

Doesn't mean anything, `VS` debugger doesn't inspect `VC++` code very well in such scenarios.

**Comment by KrzychuR** [comment]
News from today...

```
[0412/085853:FATAL:memory.cc(18)] Out of memory. size=7225344
Backtrace:
	cef_time_to_timet [0x5ABBE177+787415]
	cef_time_to_timet [0x5AB8A1C1+574497]
	TerminateProcessWithoutDump [0x5C77F520+8044720]
	cef_get_min_log_level [0x5BD3455A+1444890]
	cef_get_min_log_level [0x5BD34217+1444055]
	GetHandleVerifier [0x5AE7B107+2830967]
	GetHandleVerifier [0x5AD6E7A4+1730836]
	GetHandleVerifier [0x5AD0C83C+1329580]
	GetHandleVerifier [0x5AD70884+1739252]
	GetHandleVerifier [0x5ADEAEEB+2240603]
	GetHandleVerifier [0x5ADEAFFE+2240878]
	GetHandleVerifier [0x5AD70E4F+1740735]
	GetHandleVerifier [0x5AD251FF+1430383]
	GetHandleVerifier [0x5AD11BB3+1350947]
	GetHandleVerifier [0x5AD10571+1345249]
	GetHandleVerifier [0x5ADB903D+2036141]
	GetHandleVerifier [0x5ADB98B9+2038313]
	GetHandleVerifier [0x5ADBA110+2040448]
	GetHandleVerifier [0x5ADB69D7+2026311]
	TerminateProcessWithoutDump [0x5C7E2FA0+8452912]
	TerminateProcessWithoutDump [0x5C7E32F1+8453761]
	TerminateProcessWithoutDump [0x5C7BE13C+8301772]
	GetHandleVerifier [0x5B3929F1+8170337]
	GetHandleVerifier [0x5AFEF9DE+4356942]
	GetHandleVerifier [0x5AFEF936+4356774]
	GetHandleVerifier [0x5B0D578B+5298427]
	GetHandleVerifier [0x5B0D58C7+5298743]
	GetHandleVerifier [0x5B0CFB96+5274886]

```

I have more than enough memory....

**Comment by amaitland** [comment]
If your using the 32bit version, so how much you have and how much the app can use are different things.

See #1348 for more details.

**Comment by KrzychuR** [comment]
> If your using the 32bit version, then how much you have and how much the app can use are different things.

Memory usage is stable (for BrowserSubprocess) and is about 400-500MB so ...  the problem is not in memory boundary (2GB) for 32 app, is probably connected with my issue :(...

**Comment by amaitland** [comment]
> the problem is not in memory boundary (2GB) for 32 app, is probably connected with my issue :(...

An out of memory exception is very clear. You can apply the `largeaddressaware` flag manually or upgrade to the `49.0.0-pre02` release.

**Comment by KrzychuR** [comment]
> An out of memory exception is very clear. You can apply the largeaddressaware flag manually or upgrade to the 49.0.0-pre02 release.

I've just updated to pre02 :) We will se .... :)

**Comment by amaitland** [comment]
If you stayed with `WPF` then there is a known `GPU` issue, see the Release notes for details.

**Comment by KrzychuR** [comment]
Hmm... after update it works more stable but... now (x64) I have out of memory sometimes..

`[0413/232246:FATAL:memory_win.cc(39)] Out of memory, size = 2179465072
`
for x86 is about 500MB...

**Comment by amaitland** [comment]
You mention both `x64` and `x86`, without really providing clarification on which your using.

Potentially you could look into setting up `Breakpad`, the `Crash Reporter` that `Chrome` uses.

www.magpcss.org/ceforum/viewtopic.php?f=6&t=13847
https://github.com/cztomczak/cefpython/issues/70
https://bitbucket.org/chromiumembedded/cef/issues/1131/add-breakpad-support#comment-16413204

Personally I've never needed it, so never looked into it further.

**Comment by KrzychuR** [comment]
OK.... I'm back...
Today I've done interesting tests... Because your example (WPF) application works perfectly (without any crash) then

1. I've prepared simple x86 app using nuget package. Only browser component, one window and identical configuration like example application - crash every time afer I do certain operation in the game ..... 

2. Then I think a little .... I removed nuget package, remove all compiled binaries and use binaries compiled from you sources (and of course proper CEF bin also) - from example app...

3. Start the game and.... it working stable.....

How came?......

**Comment by amaitland** [comment]
> Then I think a little .... I removed nuget package, remove all compiled binaries and use binaries compiled from you sources (and of course proper CEF bin also) - from example app...

Which `branch` did you use?

**Comment by amaitland** [comment]
For future reference https://bugs.chromium.org/p/v8/issues/detail?id=847#c21

**Comment by amaitland** [comment]
https://developer.chrome.com/devtools/docs/javascript-memory-profiling#identifying-a-memory-problem-with-the-devtools-timeline

https://developer.chrome.com/devtools/docs/heap-profiling

http://dev.chromium.org/developers/deep-memory-profiler

**Comment by amaitland** [comment]
> For future reference https://bugs.chromium.org/p/v8/issues/detail?id=847#c21

https://bugs.chromium.org/p/v8/issues/detail?id=847#c28

**Comment by amaitland** [comment]
More on `--js-flags`

https://www.chromium.org/developers/how-tos/run-chromium-with-flags

**Comment by KrzychuR** [comment]
Hi, look at:
http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=14130

Please do not close this issue... maybe it is some how related ... but it looks like problem with buggy JavaScript code.

**Comment by amaitland** [comment]
I see you finally managed to get a stack trace, based on that this a WPF specific issue,if you change to WinForms it'll likely dissaspear.

**Comment by KrzychuR** [comment]
Why you thinking that is WPF specific? It looks like problem with image resizing, internally in CEF library...

**Comment by KrzychuR** [comment]
I've just wrapped WinForms version in WindowsFormsHost controll in WPF and... we will see... issue from this post disapear...

**Comment by amaitland** [comment]
CefRenderWidgetHostViewOSR is not used by the WinForms implementation.

**Comment by amaitland** [comment]
https://bitbucket.org/chromiumembedded/cef/issues/1894/out-of-memory-exception-in

**Comment by amaitland** [comment]
The `cefsharp/49` branch has been upgraded that includes a branch that I believe fixes this.

https://github.com/cefsharp/CefSharp/commit/995b7d1a262819c852ae9942144a6c227660788b

**Comment by amaitland** [comment]
`49.0.1` has been tagged, if testing goes well packages will be released in the next few days.
