### ISSUE TITLE
PrintToPDFAsync, Setting PageHeight, PageWidth no longer functioning (CEF 2623)

### ISSUE THREAD

**Issue by dandotevans** [cefsharp/CefSharp#1656]
On Win7, 49Pre-release (CEF 2623) Using the [CEFSharp.Wpf.Example](https://github.com/cefsharp/CefSharp/tree/e3c0d8b013d85dc41d4e01a573dd50506943fc7e/CefSharp.Wpf.Example) as the base. modifying the MainWindow PrintToPdfCommandBinding method

from : 

```
var success = await browserViewModel.WebBrowser.PrintToPdfAsync(dialog.FileName, new PdfPrintSettings
                    {
                        MarginType = CefPdfPrintMarginType.Custom,
                        MarginBottom = 10,
                        MarginTop = 0,
                        MarginLeft = 20,
                        MarginRight = 10
                    });
```

to:

```
  var success = await browserViewModel.WebBrowser.PrintToPdfAsync(dialog.FileName, new PdfPrintSettings
                    {
                        MarginType = CefPdfPrintMarginType.Custom,
                        MarginBottom = 10,
                        MarginTop = 0,
                        MarginLeft = 20,
                        MarginRight = 10,
                        PageHeight = 356,
                        PageWidth =  216
                    });
```

results in the method hanging and occasionally crashing the subprocess. 

after running, debug.log contains: 

```
[0408/154906:ERROR:ipc_channel_win.cc(217)] pipe error: 109
[0408/154906:ERROR:ipc_channel_win.cc(217)] pipe error: 109
[0408/154906:WARNING:raw_channel_win.cc(532)] WriteFile: The pipe is being closed. (0xE8)
[0408/154906:WARNING:channel.cc(359)] RawChannel write error

```

An issue has been created [upstream in CEF](https://bitbucket.org/chromiumembedded/cef/issues/1869/cef-2623-printtopdf-issue-when-setting), issue added here for reference.

**Comment by amaitland** [comment]
`master` has been updated to `2704`, please test again if you have a chance.

**Comment by dandotevans** [comment]
Thank you, I will try to dig out some time to test this under 51.

**Comment by dandotevans** [comment]
I have tested this with release 51.0.0 and it is still an issue.

**Comment by dandotevans** [comment]
Still an issue with release 55.0.0

**Comment by amaitland** [comment]
> Output page size in microns.

I believe the issue is in the units of measure your passing in, 216 x 356 is tiny in microns.

The following works fine for me.
```c#
var success = await browserViewModel.WebBrowser.PrintToPdfAsync(dialog.FileName, new PdfPrintSettings
{
	MarginType = CefPdfPrintMarginType.Custom,
	MarginBottom = 10,
	MarginTop = 0,
	MarginLeft = 20,
	MarginRight = 10,
	PageWidth = 210000,
	PageHeight = 297000
});
```

**Comment by dandotevans** [comment]
Thank you for pointing that out - completely missed that. modifying the scale has resolved the issues I've been seeing.  pleased to see we have such high precision on our PDF page sizes :+1:
