### ISSUE TITLE
CefSharp for WPF gives blurry screen

### ISSUE THREAD

**Issue by tronda** [cefsharp/CefSharp#166]
I'm running Windows 8 and have a simple demo project which includes Cef. When starting up Dropbox in Cef I get a blurry screen as shown in the screenshot attached. I've also included the preferences from Display settings in Control Panel. 

I have NVidia graphic card and have NVIDIA Control Panel running, but cannot find any specific settings which should affect this, but I'm no graphics geek. The sample project can be attached if needed.

Running dropbox.com from Windows Forms gives no issues with regards to the display.

![cefwpf_blur](https://f.cloud.github.com/assets/1372151/1121003/8f5654d4-1ab5-11e3-9a99-d0d3ce381193.png)

![display_prefs](https://f.cloud.github.com/assets/1372151/1121010/d66c3bcc-1ab5-11e3-9f21-3ba3b2f167d1.png)

**Comment by CaptainBli** [comment]
Any zoom at all causes the same symptoms with the current stable build of 37.0.0.  Is there a way to tell the renderer to use a larger size canvas on initialization?

**Comment by gengjiawen** [comment]
Win10, 4K resolution has the same issue.

**Comment by tshcherban** [comment]
I've found this is happening when browser gets not rounded coordinate (relative to window, e.g. 10
.5 instead of 10). I fixed it for myself putting browser control on canvas and adding Canvas.SizeChanged event handler:

        private void Canvas_OnSizeChanged(object sender, SizeChangedEventArgs e)
        {
            var canvasPosition = Canvas1.TransformToAncestor(this).Transform(new Point(0, 0));

            var x = Math.Abs(Math.Abs((int)canvasPosition.X - canvasPosition.X));
            var y = Math.Abs(Math.Abs((int)canvasPosition.Y - canvasPosition.Y));

            Canvas.SetLeft(browser, x);
            Canvas.SetTop(browser, y);

            browser.Height = Math.Round(e.NewSize.Height);
            browser.Width = Math.Round(e.NewSize.Width);
        }

**Comment by feinstein** [comment]
I fixed this problem by setting the control XAML tag as:

            <cefsharp:ChromiumWebBrowser RenderOptions.BitmapScalingMode="HighQuality" >

AND using  `UseLayoutRounding="True"` on the root container of my XAML (which is a `Grid`). Without the ` UseLayoutRounding="True"` the image gets a little blurred. 

Keep in min ` UseLayoutRounding="True"` will disable antialiasing for all the code inside it, if you don't want it, try to wrap your control inside multiple grids and change `UseLayoutRounding="True"` to `"False"` accordingly to select which parts of your UI should have antialiasing and which shouldn't.

**Comment by MarcBra** [comment]
I've had issues with blurry page rendering also. Turned out to be caused by setting FontFamily on a TextBox control in the same WPF window. I don't understand why, but it might help to check the fonts if you're experiencing the issues...

**Comment by Ganeshcse** [comment]
> I've found this happens when a browser control gets a non-integer coordinate relative to the window (e.g. 10.5 instead of 10). I fixed it by putting the browser control on a canvas and adding a Canvas.SizeChanged event handler:
> 
> ```
>     private void Canvas_OnSizeChanged(object sender, SizeChangedEventArgs e)
>     {
>         var canvasPosition = Canvas1.TransformToAncestor(Application.Current.MainWindow).Transform(new Point(0, 0));
> 
>         var x = 1 - Math.Abs((int)canvasPosition.X - canvasPosition.X);
>         var y = 1 - Math.Abs((int)canvasPosition.Y - canvasPosition.Y);
> 
>         Canvas.SetLeft(browser, x);
>         Canvas.SetTop(browser, y);
> 
>         browser.Height = Math.Round(e.NewSize.Height);
>         browser.Width = Math.Round(e.NewSize.Width);
>     }
> ```
> 
> maybe we can just add similar trick to control and align rendered image?

I tried this approach, when my window is launched the content of the browser is blurry. But when I tried resizing at certain coordinates the content becomes clear. But is there any way to get this effect on window load. Since my window cannot resize. Its a modal dialog.

I know its been more than 2 years that this thread is in-active.

**Comment by tshcherban** [comment]
@Ganeshcse 
i think you can put this code to 'Loaded' event, maybe via dispatcher with some low priority to wait until content loads. Or (high chance) you'll need to use some htlp DOM's event.
