### ISSUE TITLE
Loading time of browser in WPF is more

### ISSUE THREAD

**Issue by DhivyaLakshmiG** [cefsharp/CefSharp#1661]
We are using cefsharp browser in WPF application. If the HTML content is more, then it takes time to load the result in browser.
Issue reproduce frequently in high resolution system.

We used following code for loading the HTML content in browser.

```c#
 static void OnHtmlChanged(DependencyObject dependencyObject, DependencyPropertyChangedEventArgs e)
        { 
             var webBrowser = dependencyObject as CefSharp.Wpf.ChromiumWebBrowser;
                if (webBrowser != null && e.NewValue != null)
                    if (string.IsNullOrEmpty(e.NewValue.ToString()))
                    {
                        webBrowser.LoadHtml(string.Empty, "http://example/");
                    }
                    else
                    {
                        webBrowser.LoadHtml(e.NewValue as string, "http://example/");

                        HideScriptErrors(webBrowser, true);
                    }
          }
```

Could you please check this and update us any solution for this?

**Comment by amaitland** [comment]
> @DhivyaLakshmiG Implement your own IResourceHandlerFactory, as LoadHtml is just an extension method that registers an IResourceHandler. You can check out the default implementation https://github.com/cefsharp/CefSharp/blob/cefsharp/49/CefSharp/DefaultResourceHandlerFactory.cs
You'll have full control then.

I already responded to your issue on `Gitter`

> Could you please check this and update us any solution for this?

You can debug this yourself by implementing `IResourceHandlerFactory`

**Comment by DhivyaLakshmiG** [comment]
@amaitland Thanks. I will check and update you.

**Comment by DhivyaLakshmiG** [comment]
@amaitland I have a same problem as like in below issue, when the laptop is placed in hypernet/sleep mode with the WPF application opened with some search in browser. 
After few mins, login to the laptop, then if we search anything in wpf application, old update is displaying. If we switch over the tab and come back, the browser refreshed and displays the new update.
 
https://github.com/cefsharp/CefSharp/issues/1571 

Is there any problem in this?

**Comment by DhivyaLakshmiG** [comment]
This issue occurs only in the high resolution laptop with screen resolution 1920X1080.

**Comment by amaitland** [comment]
> @amaitland I have a same problem as like in below issue, when the laptop is placed in hypernet/sleep mode with the WPF application opened with some search in browser.

@DhivyaLakshmiG How does this relate to the issue you posted?

**Comment by DhivyaLakshmiG** [comment]
In the high resolution machine, following issue reproduced.
1. In WPF, there are 5 tabs, each tab is added with the cef browser.
2. Load the html content in 1st tab browser, keep the laptop in sleep mode for some time.
3. Again open the laptop, load the new content in 1st tab browser. old content is displayed.
4. Now switch to 2nd tab, come back to 1st tab, new content is displaying.

Can you understand my problem?

**Comment by amaitland** [comment]
If your referring to #1571 then I haven't got anything to add, you'll have to debug the problem yourself.

Please stay focused on your original issue in this thread.

**Comment by amaitland** [comment]
Have you looked into your original issue further? If it's exactly the same as #1571 then please close this.
