### ISSUE TITLE
The date is not localized when using HeaderFooterEnabled with PrintToPdfAsync

### ISSUE THREAD

**Issue by Xan-Kun** [cefsharp/CefSharp#1662]
Whe using 
> printSettings.HeaderFooterEnabled = true;

and
> cefbrowser.PrintToPdfAsync("filename.pdf", printSettings);

There is a date, the title and pagination (page numbers) in the form "1/2" (i.e. page one of two)

The date is not localized and I can't find a way, to change it manually or configure the generated header and footer.

I already read, that setting printSettings.HeaderFooterTitle doesn't work for unknown reasons (and it only influences the ttile in the top-middle of the page).

**Comment by amaitland** [comment]
> Note: CefSharp is just a wrapper around the Chromium Embedded Project, it's worth searching http://magpcss.org/ceforum/index.php if your problem involves a low level Chromium error message

As per the `Issue Template` you'll need to post on `ceforum`, it's outside of the control of `CefSharp`.

**Comment by Xan-Kun** [comment]
Thanks, I also just found out that it would mean a massive amount to get it implemented as it is not supported in chrome at all. Bummer :-)

**Comment by amaitland** [comment]
> Thanks, I also just found out that it would mean a massive amount of effort to get it implemented as it is not supported in chrome at all.

Do you have a link to the `Chromium` issue tracker?

**Comment by Xan-Kun** [comment]
I am sorry, I do not understand the question.
There are many issues about pagination, @page and other print related
problems in chrome. Which one do you mean exactly?

2016-04-20 3:26 GMT+02:00 Alex Maitland <notifications@github.com>:

**Comment by amaitland** [comment]
> There are many issues about pagination, @page and other print related problems in chrome. Which one do you mean exactly?

It's quite common for there to be an open feature in the `Chromium` issue tracker for feature requests like this. If nothing exists then that's fine.

Closing this issue as it would require changes to `Chromium`.

**Comment by Xan-Kun** [comment]
Absolutely correct. Thanks for closing it and maybe we can spare someone
some searching time :-)

2016-04-20 3:35 GMT+02:00 Alex Maitland <notifications@github.com>:

**Comment by genyx** [comment]
In my case it worked with changing the Initialize() code to:
`Cef.Initialize(new CefSettings {Locale = "de"});`
