### ISSUE TITLE
IContextMenuHandler don't receive Url for image in background

### ISSUE THREAD

**Issue by valhentai** [cefsharp/CefSharp#1663]
When I open a context menu on an image wich is not in a `<img>` tag but is displayed using CSS background-image, inside  the **OnBeforeContextMenu** and **RunContextMenu** fonctions, **HasImageContent** property of  **IContextMenuParams** is true but the **SourceUrl** property is empty.

I could get the url using some javascript with **ExecuteJavaScriptAsync** but it would be easier if the ImageUrl was directly given by **IContextMenuParams**.

I am using the nuget package CefSharp.WPF 47.0.3 in Windows 8.1

**Comment by amaitland** [comment]
> Note: CefSharp is just a wrapper around the Chromium Embedded Project, it's worth searching http://magpcss.org/ceforum/index.php if your problem involves a low level Chromium error message

This would need to be reported and fixed in `CEF`.

**Comment by amaitland** [comment]
> http://www.magpcss.org/ceforum/viewtopic.php?f=7&t=14099
> the functionality would need to be added in Chromium.

@valhentai Are you planning on raising this with `Chromium`? If not, I'll close this.

**Comment by valhentai** [comment]
I am trying to get more info on the API call made to chromium inside CEF to be able to submit the bug to Chromium.

**Comment by amaitland** [comment]
Great :+1:

**Comment by amaitland** [comment]
If `Chromium` ever adds support then we can reopen this. Not possible for now.
