### ISSUE TITLE
In Cefsharp.Wpf.Example devtools not working.

### ISSUE THREAD

**Issue by omanbros** [cefsharp/CefSharp#1666]
When i run this example, the devtools display nothing. But if i click somewhere on blank the html elements can be deteced.
![image](https://cloud.githubusercontent.com/assets/14815777/14701850/fe89bb34-07d9-11e6-9be2-268ba3fac182.png)

**Comment by omanbros** [comment]
Cefsharp.Winform.Example is working fine.

**Comment by amaitland** [comment]
`Pull` the latest `master`, `DevTools` seems to have a problem with `enable-begin-frame-scheduling`, it's been disabled for now. Relevant commit is https://github.com/cefsharp/CefSharp/commit/1e18b55116190ea4e1b0c84dc7e6a2b84ec25eb2

**Comment by omanbros** [comment]
@amaitland Thank you, it's working for me now.
