### ISSUE TITLE
Using Flash questions on Cefsharp

### ISSUE THREAD

**Issue by yongchaohu** [cefsharp/CefSharp#1667]
i use cefsharp/47 winform,I use the following two methods to let the browser supports Flash,
1、I added NPSWF32.dll in Plugins directory , the program is running, 

 2、settings.CefCommandLineArgs.Add("ppapi-flash-path", Path.GetDirectoryName(Application.ExecutablePath) + @"\PepperFlash\pepflashplayer.dll"); //Load a specific pepper flash version (Step 1 of 2)
 settings.CefCommandLineArgs.Add("ppapi-flash-version", "18.0.0.209"); //Load a specific pepper flash version (Step 2 of 2)

But the above two methods when the browser first opens the video site will pop up a Shell window , and instantly disappeared . How to set up a form that allows not pop up, thank you .

**Comment by yongchaohu** [comment]
no sandbox

**Comment by jankurianski** [comment]
According to the following link, this is a CEF issue and not a CefSharp issue.  When I searched "flash" in GitHub, it was the second link:
https://github.com/cefsharp/CefSharp/issues/1259

Did you search before reporting?

**Comment by yongchaohu** [comment]
thanks
