### ISSUE TITLE
microphone problem.

### ISSUE THREAD

**Issue by onelineman** [cefsharp/CefSharp#1668]
so i am new to c# and need the program to use the  microphone on speech to text sites like https://dictation.io/ and https://www.google.com/intl/en/chrome/demos/speech.html

However the microphone doesnt work as expected.It disables itself automatically. What am i doing wrong?
```c#   
      public ChromiumWebBrowser browser;
public void InitBrowser()
        {
            var settings = new CefSettings();
            settings.CefCommandLineArgs.Add("enable-media-stream", "10000");
            settings.CefCommandLineArgs.Add("enable-speech-input", "10000");
            Cef.Initialize(settings);
            browser = new ChromiumWebBrowser("https://dictation.io/");
            this.Controls.Add(browser);
            browser.Dock = DockStyle.Fill;
    
        }
```

**Comment by amaitland** [comment]
> Issues are for bug reports only. A simple 'Feature x doesn't appear to be working` is not a bug report!

https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

Would appreciate if you followed the `Issue Template` and asked your questions on `Gitter` as requested.

> settings.CefCommandLineArgs.Add("enable-media-stream", "10000");

Not sure where you got `10000` from, just use `1` or `0` for enable and disable.
