### ISSUE TITLE
CefSharp.BrowserSubprocess stops working after some time with Access Violation Exception 

### ISSUE THREAD

**Issue by amitppandey** [cefsharp/CefSharp#1669]
Hi,

I am using CefSharp version 47.0.3.0 in a Winforms application on  Windows 7 machines(x64/x86) with Visual Studio 2015.

I am loading a https URL hosted using the mongoose library. The web page basically fetches and displays some logs every 5 seconds.

After running this URL for close to one hour(lesser duration in CefSharp 43), the Browser SubProcess crashes. The Windows Event viewer contains the following error information : 

![cef_crash](https://cloud.githubusercontent.com/assets/18681650/14821385/2c38e2c8-0be8-11e6-946d-49ab191db430.PNG)

![cef_crash_event1](https://cloud.githubusercontent.com/assets/18681650/14821396/3553512c-0be8-11e6-8fc1-21797303e61d.PNG)

I noticed that an access violation exception was raised here previously [#976](https://github.com/cefsharp/CefSharp/issues/976) but raising a new issue since I am not sure if the scenario is the same(I also have the .pak files mentioned in the issue).

Went through the Debug.log with verbose level enabled but not able to make out anything from it.
Below is the Debug log taken when crash happened:
[debug.txt](https://github.com/cefsharp/CefSharp/files/236854/debug.txt)

Below is the Debug log taken before any crash happened:
[debug1.txt](https://github.com/cefsharp/CefSharp/files/236858/debug1.txt)

Other Observations:
1.  The time taken for the process to crash does not decrease even if logs are fetched more frequently.
2. Issue is not reproduced when I simply load the URL and not make any further request for logs.
3. The issue is not reproduced if the server returns some hard-coded string containing all alphabets instead of providing the actual logs. This made me suspect if the crash was triggered due to some special characters present in the logs.
4. Issue is not reproduced when the server returns hard-coded string containing all the UTF-8 characters which means the crash may not be related to special characters.
5. Issue is not reproducible i use a http URL for the same web page and use a web server other than mongoose
6. Issue is not seen if I am simply loading the URL: https://www.google.com.

Any idea what could be causing this issue or what other steps I could possibly take to identify the problem?

**Comment by amaitland** [comment]
General troubleshooting information is at https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#unmanaged-crashes-when-the-process-dies

Your log file has some many gpu errors I'm surprised it works at all! What graphics card are you using?

I'd disable the `GPU` as a first step, it's likely to increase the stability a whole lot. https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#troubleshooting-graphics-video-or-performance-problems

**Comment by amitppandey** [comment]
Hi Alex,
Thanks for  the Quick Response.

I am using the Intel(R)HD Graphics card.

I tried the same after disabling the GPU  but crash still happened like before.Below is the debug log.
[debug_No_GPU_.txt](https://github.com/cefsharp/CefSharp/files/238846/debug_No_GPU_.txt)

I will try the procdump and release symbols suggested in troubleshooting and get back with the details.

**Comment by KrzychuR** [comment]
Hi @amitppandey, look at #1655 I'm still fighting with simmilar problem.

I'm not very experienced with CLI/C++ and... I cannot successfull debug chromium engine.

It will be great to know how to enable more verbose crash-logs in chromium...

@amaitland give me a lot of usefull links (many thanks) but at this moment I do not have time to check it :(

**Comment by amitppandey** [comment]
Hello,
While debugging more , I noticed that the application is crashing after approx. 800kb logs on the page.

Other Observations:
1. While Changing the configuration platform to 64 bit , I didn't find the crash issue.But I can see the hanging problem , Seems like after accumulating lots of logs on page its getting hang.

2. On 32-bit platform after updating the CefSharp (Cefsharp 49.0.0) , the issue is not seen on 64bit machine but still still exist on 32 bit machine.

3.Chrome browser is also crashing when tried to open the address after same 800kb.

Please suggest , 1. Why its crashing on 32bit machine and not on 64 bit machine ?
                           2. What may be possible reason of browser hangs.

Please suggest the way to debug more and resolve it.

**Comment by amaitland** [comment]
> .Chrome browser is also crashing when tried to open the address after same 800kb.

If you can reproduce the problem in `Chrome` then you're best to log a bug with http://crbug.com/new

> 1. Why its crashing on 32bit machine and not on 64 bit machine ?

A `64bit` application can address more memory, likely you've got a memory issue.

> 2. What may be possible reason of browser hangs.

Impossible to speculate, you'd need to provide an example that reproduces the problem.

Some tips on memory diagnostics from `Chrome` 
https://developers.google.com/web/tools/chrome-devtools/profile/memory-problems/memory-diagnosis

> Please suggest the way to debug more and resolve it.

`v49.0.0` has symbols available for download, see #880. Cannot guarantee this is helpful, it may give you a more meaningful stack trace, as it's a crash in `libcef.dll` I hope you've downloaded the `Release symbols` as suggested.

Also there's probably a crash dump, check in your users `AppData\Local\CrashDumps` directory. You can google for tips on how to load a crash dump, make sure you load all the symbols.

**Comment by you-yas55** [comment]
I have similar issue, 
when i tried CefSharp version 41.0.1.
but when i tried all other versions up to the latest i faced some weird rendering issue, not sure why, i tested the app in multiple PC machines but got them all rendering some weird Red color scroll bars, Css text rendered on the page...etc.
the most recent vversion that only worked for me was 41.0.1 but it had a memory leak issue.
Some SubProcesses take more than 800MBs before it hangs.

**Comment by amaitland** [comment]
Red scroll bars means  you're missing Pak files, newer versions include additional files. Search for red scroll bars, it's a known issue.

**Comment by amaitland** [comment]
- Download `libcef.dll.pdb` from `cefbuilds.com` (info as part of troubleshooting guide).
- Extract the `.pdb` into the same folder as `libcef.dll`
- Clone `CEF` to a local folder (from https://bitbucket.org/chromiumembedded/cef)
- Switch to the `CEF Commit Hash` (Forversion `49.0.0` it's `0451528779329dff717e0d50e24b963f648a9231`)
- In VS `Enable native code debugging` (project properties -> debug)
- If the exception occurs within `libcef.dll you will hopefully be prompted to locate the source file, e.g. `browser_host_impl.cc`

**Comment by amaitland** [comment]
The `master` branch has been upgraded to `CEF 2704.1415` which is based on `Chromium` `51.0.2704.63`. Probably worth testing with a newer `Chromium` version

Closing this now as the bug would need to be fixed in `Chromium`. When/if you open a ticket please post the link here for others.
