### ISSUE TITLE
cefsharp/CefSharp Hi Alex, I am working with CEFSharp to display panorama on x86 build of my project, but sometimes on frequent loading of same image or different images the screen goes black and the following errors are recorded on the debug file. [0503/125112:ERROR:gles2_cmd_decoder.cc(14033)] [.Compositor-00614AA0]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name [0503/125112:ERROR:gles2_cmd_decoder.cc(7430)] [.Compositor-00614AA0]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering. [0503/140519:WARNING:dns_config_service_win.cc(673)] Failed to read DnsConfig. [0503/140832:ERROR:ipc_channel_win.cc(465)] pipe error: 995 I am using Cefsharp winform and WPF component and the error is shown in both.Also cefsharp.browsersubprocess.exe stopped running problem is there. Thank you, Nitin Kandpal

### ISSUE THREAD

**Issue by NitinIIRS** [cefsharp/CefSharp#1678]
Issues are for bug reports only. A simple 'Feature x doesn't appear to be working` is not a bug report!

So you have a question to ask, where can you look for answers?

- Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
- GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
- You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
- You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp
 
**Note: CefSharp is just a wrapper around the Chromium Embedded Project, it's worth searching http://magpcss.org/ceforum/index.php if your problem involves a low level Chromium error message**

We ask that you put in a reasonable amount of effort in searching through the resources listed above. The developers have full time jobs, they have lives, families, the time they have available to contribute this project is a precious resource, make sure you use it wisely! Remember the more time we spend answering the same questions over and over again, less time goes into writing code, adding new features, actually fixing bugs!

Still have a question to ask or unsure where to go next? Start with the Gitter Chat room : https://gitter.im/cefsharp/CefSharp

--
To continue submitting a bug report, delete everything above, and then fill in the details below.

- **What steps will reproduce the problem?**

- **What is the expected output? What do you see instead?**

- **Are you using `WinForms`, `WPF` or `OffScreen`?**

- **What version of the product are you using? On what operating system? x86 or x64?**
    - What version are you using? Nuget? CI Nuget? build from a branch? If so which branch?

    - Win7, Win 8, Win10, etc?

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?

- **Does this problem also occur in the `Cef` TestApp from http://cefbuilds.com?**

**Comment by amaitland** [comment]
The description should be short, not contain your whole issue. You appear to have forgotten to fill out the issue template. Is there a reason you created three issues?

**Comment by NitinIIRS** [comment]
What steps will reproduce the problem?
I have created a window form and WPF application using CEFsharp and tried to incorporate WEBGL for displaying panorama.

What is the expected output? What do you see instead?
Sometimes it works normally and sometime on loading of same image or different images the screen goes black and the following errors are recorded on the debug file. 

[0503/125112:ERROR:gles2_cmd_decoder.cc(14033)] [.Compositor-00614AA0]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name [0503/125112:ERROR:gles2_cmd_decoder.cc(7430)]

Are you using WinForms, WPF or OffScreen?
I have tried using WinForms and WPF.

What version of the product are you using? On what operating system? x86 or x64?
X86.

What version are you using? Nuget? CI Nuget? build from a branch? If so which branch?
Nuget

Win7, Win 8, Win10, etc?
Win7

Please provide any additional information below.Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)


[.Compositor-00614AA0]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name [0503/125112:ERROR:gles2_cmd_decoder.cc(7430)] 

[.Compositor-00614AA0]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering. [0503/140519:WARNING:dns_config_service_win.cc(673)]

 Failed to read DnsConfig. [0503/140832:ERROR:ipc_channel_win.cc(465)] pipe error: 995 





Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?

The application is running normally with x64.

Does this problem also occur in the Cef TestApp from http://cefbuilds.com?

**Comment by amaitland** [comment]
> Does this problem also occur in the Cef TestApp from http://cefbuilds.com?
> Yes

Thanks for confirming. Unfortunately this would need to be fixed in `CEF` or `Chromium` if it's reproducible in `cefclient`. (`CefSharp` is just a wrapper for the `CEF` project).

It's probably worth trying the `49.0.0-pre02` release, see if upgrading resolves the issue.

**Comment by NitinIIRS** [comment]
Thanks for your reply Alex,

Yes, the error also popped out when I used cefclient. I will try with 49.0.0-pre02.

**Comment by NitinIIRS** [comment]
Hi Alex,

I tried with new version 49.0.0-pre02 but the error still persist. The debug logfile is still showing the same errors.

[0503/154553:ERROR:gles2_cmd_decoder.cc(14033)] [.Compositor-050FFED8]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name

[0503/154553:ERROR:gles2_cmd_decoder.cc(7430)] [.Compositor-050FFED8]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.

**Comment by amaitland** [comment]
And how'd you go googling those errors? Also how does your page run if you use `Chrome`?

**Comment by NitinIIRS** [comment]
I initialized my chrome browser like this.


using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using CefSharp;
using CefSharp.WinForms;
using WebViewer.Controls;



namespace WebViewer
{

    public partial class WebViewer: Form
    {
        public ChromiumWebBrowser browser;
        
      

        public WebViewer()
        {
// CefSetting are initialized in program.cs
            InitializeComponent();
            
            browser = new ChromiumWebBrowser("http://192.168.19.152/OpenDoc/DocViewer.aspx?sId=Camera-20151009-150222-000000009.jpg|77.26,28.54,167.94,213.9217$Camera-20151009-150222-000000013.jpg|77.26,28.54,168.53,131.18")
            {
                Dock = DockStyle.Fill,
            };
            browser.RegisterJsObject("callbackObj", new CallbackObjectForJs()); 
           
  
            panel1.Controls.Add(browser);
            browser.Dock = DockStyle.Fill;
    
        }

        public void Reload(string url)
        {
           
            browser.Load(url);
        }

        private void Form1_Load(object sender, EventArgs e)
        {
           
        }       



        private void WebViewer_FormClosing(object sender, FormClosingEventArgs e)
        {
            this.Dispose();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            Reload("http://192.168.19.152/OpenDoc/DocViewer.aspx?sId=Camera-20151009-150222-000000009.jpg|77.26,28.54,167.94,213.9217$Camera-20151009-150222-000000013.jpg|77.26,28.54,168.53,131.18");
        }
  
    }

    public delegate void ImageClick();

    public class CallbackObjectForJs
    {
        public static event ImageClick ImgClick;
        public void showMessage(string msg)
        {
            MessageBox.Show(msg);
        }
    }
}

**Comment by NitinIIRS** [comment]
In chrome the page is opening normally. With cefsharp even the page opens normally but with frequent upload the screen goes black and the above reported errors are updated on debug.log

**Comment by NitinIIRS** [comment]
![capture2](https://cloud.githubusercontent.com/assets/19151826/14980731/0ef21256-1148-11e6-9733-ce988423288a.PNG)
![capture1](https://cloud.githubusercontent.com/assets/19151826/14980732/1002c5aa-1148-11e6-9b79-19e9df106848.PNG)

**Comment by amaitland** [comment]
> Unfortunately this would need to be fixed in CEF or Chromium if it's reproducible in cefclient. (CefSharp is just a wrapper for the CEF project).

Other than tweaking command line arguments like disabling the `GPU` there is nothing that can be done from a `CefSharp` perspective. 

> And how'd you go googling those errors?

I asked if you googled your errors, you've since posted example code and screen shots. If you haven't done so, do some additional research.

**Comment by NitinIIRS** [comment]
I have tried diabling my GPU. I have also tried with CefSharp.

I have googled it with different perspectives, I have googled it with WebGL error, I have updated my graphics driver, I have disabled my GPU (then application fully stops working). But the X64 works very fine.

**Comment by amaitland** [comment]
> I have tried diabling my GPU. I have also tried with CefSharp.

https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#troubleshooting-graphics-video-or-performance-problems

> I have googled it with different perspectives

https://bugs.chromium.org/p/chromium/issues/detail?id=481398#c3
Seems the same error applies, doesn't say they fixed it just that it magically went away.

> WARNING: texture bound to texture unit 0 is not renderable.

http://stackoverflow.com/questions/13905652/non-power-of-2-texture-render-warning-in-chrome
Suggests you might need to tweak your `WebGL` rendering.

**Comment by NitinIIRS** [comment]
Thanks a lot Alex, the problem finally resolved with CefSharp.WinForms 49.0.0-pre02.

Actually I was using this windows form where cefsharp was incorporated as plugin in some other application and I missed to update the cefsharp 49.0.0-pre02 dll's there.

**Comment by amaitland** [comment]
> Actually I was using this windows form where cefsharp was incorporated as plugin in some other application and I missed to update the cefsharp 49.0.0-pre02 dll's there.

Great :+1: The `49.0.0` official packages have been pushed to `Nuget.org`, so they should be available in the next few hours. Adding this to the `49.0.0` milestone.
