### ISSUE TITLE
Terrible flashing problem on certain web pages

### ISSUE THREAD

**Issue by neil-119** [cefsharp/CefSharp#1681]
- **What version of the product are you using?**
    - v49.0.0

- **What architecture x86 or x64?**
    - x86

- **On what operating system?**
    - Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
Just navigate to any website using Zopim. (e.g. zopim.com)

- **What is the expected output? What do you see instead?**
Expected: no flashing
Occurring: Terrible white flashes. The page is still navigable.

- **Please provide any additional information below.**
None

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
Nope

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
Nope

- **Does this problem also occur in the `Cef` TestApp from http://cefbuilds.com?**
No.

Here's my code.
[WpfApplication1.zip](https://github.com/cefsharp/CefSharp/files/254149/WpfApplication1.zip)

**Comment by amaitland** [comment]
> Here's my code.

No zip files please (as per https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#help-us-help-you)

> Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
> Nope

I find that hard to believe. 

> Note There is a known graphics issue with WPF and OffScreen versions, see #1634 for details, also see #1666 

As per the release notes there are known graphics issues with the `WPF` version.

https://github.com/cefsharp/CefSharp/releases/tag/v49.0.0

**Comment by neil-119** [comment]
Okay, thank you. I searched and didn't see this particular issue posted, as it only happens on certain pages doing some kind of polling (Zopim was an example) and only on the WPF version, so I thought I'd post the issue to let you guys know.

For other people having this issue, a workaround is to host the WinForms version of the project in WPF through the WinFormsIntegration assembly.

**Comment by fredisko** [comment]
Hello I have same problem with this version. I downgrade version to 47.0.3 and it is working wel
