### ISSUE TITLE
Trying to remove unknown session from cache

### ISSUE THREAD

**Issue by fjhl** [cefsharp/CefSharp#1685]
- **What version of the product are you using?**
    - What version are you using? Nuget? CI Nuget? build from a branch? If so which branch?
CefSharp, v41.0.1.0

- **What architecture x86 or x64?**
Both
- **On what operating system?**
    Win7, Win 8, Win10,

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms
- **What steps will reproduce the problem?**
I can not.
- **What is the expected output? What do you see instead?**

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
Temporaly log file shows error: "Trying to remove unknown session from cache" (i.e. [0512/124231:ERROR:ssl_session_cache_openssl.cc(340)] Trying to remove unknown session from cache: 12208828)
Our application navigates to an URL opening a http connection in a CEF browser. And, after working few hours with the application, thats error is logged (it's invisible to users). I am not able to reproduce that error with the debugging project.
What happens? What can I configure to avoid that error?
    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?

- **Does this problem also occur in the `Cef` TestApp from http://cefbuilds.com?**
Users  are normally connected to a website with a https connection and a certificate while they work with.

**Comment by amaitland** [comment]
Does the problem reproduce using the latest version? The version your using is no longer supported.

Have you googled the error? What research have you done?

**Comment by fjhl** [comment]
I did not use latest version yet. I research widely the web and I only found the reference into the source code of "ssl_session_cache_openssl.cc" (line 340)

**Comment by amaitland** [comment]
Basically it's an error message generated via Chromium, so your best option is to upgrade to a newer version.

**Comment by fjhl** [comment]
Hi, I upgraded to the latest version (cef v49) and I still get some logs: "Trying to remove unknown session from cache".
It happens after using a few hours the application (users did not notice anything).

**Comment by amaitland** [comment]
> It happens after using a few hours the application (users did not notice anything).

If your not seeing any problems then maybe it's safe to ignore? You'll have to ask on http://magpcss.org/ceforum/ for clarification.

**Comment by amaitland** [comment]
(`CefSharp` is just a wrapper, and that's a `Chromium` message your seeing)
