### ISSUE TITLE
i want to change js checked result window.screen.height , what can i do?

### ISSUE THREAD

**Issue by supperlitt** [cefsharp/CefSharp#1686]
because of some website,will be checked window.screen info,
but i don't want to change the physical screen size.
so what can i do to cheat the website. with cefsharp.

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by tonylu81** [comment]
请求这个问题解决了吗？ @supperlitt

**Comment by tonylu81** [comment]
Has the problem been solved? @supperlitt
