### ISSUE TITLE
Holding files after Application.Restart

### ISSUE THREAD

**Issue by MortyMacfly** [cefsharp/CefSharp#1688]
I have an application that should update itself automatically from http server via ClickOnce technology. Updates checked and performed by using ApplicationDeployment class methods. When update is installed I do this:
```
if (form.InvokeRequired) {
    form.Invoke(new Action(() => {
        form.DisposeBrowser();
        Cef.Shutdown();
        Application.Restart();
    }));
}
...
public void DisposeBrowser() {
    Controls.Remove(Browser);
    Browser.Dispose();
}
```
ClickOnce download updated binaries into new directory and start it. After that current version must shut down. The problem is when new version is started I try to delete directory with the previous one. and I can't delete files `CefSharp.dll, CefSharp.Core.dll, CefSharp.WinForms.dll`. Is my disposing performed wrong or something? Thanks.

CefSharp.Common, version="49.0.0" targetFramework="net45"
CefSharp.WinForms, version="49.0.0" targetFramework="net45"
- x86
- Win10
- WinForms

**Comment by amaitland** [comment]
> Is my disposing performed wrong or something?

Based on the limited example everything looks fine. I've never used `Application.Restart` though. In general I avoid `ClickOnce` where possible. In general make sure your not holding onto any references like storing a copy of `IFrame` somewhere without calling `Dispose`. `CEF` is ref counted, so you need to be diligent in releasing every wrapper when your done.

> We'd like to keep issues exclusively for bug reports, so please ask your questions on Gitter

https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

When you created this issue was it pre-populated with text from the link above? In future we'd like to keep issues exclusively for bug reports. Thank you!

**Comment by MortyMacfly** [comment]
I don't see any references that could cause the problem. Here is sample project. Program should be deployed and installed and then it checks for updates at startup.

[SampleHold.zip](https://github.com/cefsharp/CefSharp/files/272443/SampleHold.zip)

Yes, I saw the text. It looks like some cefsharp bug to me. But I'm sorry if it's not though.

**Comment by amaitland** [comment]
> I don't see any references that could cause the problem. Here is sample project. Program should be deployed and installed and then it checks for updates at startup.

I've removed your zip file. As per https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#help-us-help-you no binaries thank you.

I won't be installing a program from an unknown source, nor would I suggest anyone else.

> Yes, I saw the text. It looks like some cefsharp bug to me.

If you believed that to be the case then you could have at least filled out the bug report.

**Comment by MortyMacfly** [comment]
Here is sources of sample [https://github.com/MortyMacfly/CefFileHold](url)

If must be misunderstood. There is no any unknown sources except cefsharp from nuget. The program  should be published from visual studio and installed from compiled binaries.

**Comment by amaitland** [comment]
> The program should be published from visual studio and installed from compiled binaries.

Great that you can reproduce the problem, unfortunately you'll have to troubleshoot the problem yourself (or choose a different `CEF` based wrapper).

**Comment by amaitland** [comment]
(It's important to remember this is an open source project, with very few active contributors, so resources are limited and this isn't a priority).

**Comment by amaitland** [comment]
@MortyMacfly I've had a quick look at your code, and I'd suggest if possible you restructure your code to work around any potential problems, if your update check is relatively quick then check for your update in a `sync` fashion and only load your `Form` once the update check is complete and no updates found.

You can use `Process Explorer` to see if anything else is keeping a lock on those files.

https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx

If there is no further response to this in the next two weeks I'll close this issue.
