### ISSUE TITLE
Taking screenshot after DOM elements are hidden

### ISSUE THREAD

**Issue by smaranh** [cefsharp/CefSharp#1689]
I am using [gist](https://gist.github.com/jankurianski/f3419d4580517516c24b) for capturing screenshot of the browser. It works great.

The only problem is, before I take a screenshot, I wish to hide few of the DOM elements and then take the screenshot. I have tried delay on JS and C# side but to no effect. I also looked at this [sample](https://gist.github.com/amaitland/96ebbfd92454d8bc36df#file-gistfile1-cs-L62) but this shows changes when they are made only on the C# side.

Any suggestions?

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md
