### ISSUE TITLE
How to upload all subfolders and it's files when i choose a folder in WPF with ChromiumWebBrowser ?

### ISSUE THREAD

**Issue by songzheng45** [cefsharp/CefSharp#1692]
When  I choose a folder in webBrowser,I'd like to upload all files which contains subfolders and their subfiles. But now ,I can just only upload the root files,and the subfolder's files are lost , I can't find the implement of 'callBack', how can I fix this?

ex. Address: https://onedrive.live.com
      The upload folder button.

My CEFsharp version:49.0.0

Thank you!

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md
