### ISSUE TITLE
[0522/164851:FATAL:memory_win.cc<39>] Out of memory

### ISSUE THREAD

**Issue by XNemo** [cefsharp/CefSharp#1693]
![main_error](https://cloud.githubusercontent.com/assets/19517106/15454585/00d38e54-2046-11e6-8b23-d4cbb968c8f1.png)
![report1](https://cloud.githubusercontent.com/assets/19517106/15454591/0fdaccdc-2046-11e6-8588-c25a7ab80860.PNG)

**Issue Summary**

I'm using CefSharp.OffScreen version v49.0.0 with console run on win7. Sometimes i get a out of memory error, then the browsersubprocess closed, and main process crash. This appears occasionally,long after the application is running.I cannot find steps to reproduce.

[0522/164851:FATAL:memory_win.cc<39>] Out of memory, size = 645767440

**Technical details**

- CefSharp.OffScreen Version: 49.0.0 
- Operating System: windows 7 x86
- x86:
- Console Application

**My Code**

```javascript
class Program
{
	
	public static void Main(string[] args)
	{
		OpenUrl("http://www.mysite.com");
	}
	public void OpenUrl(string Url)
	{
		try
		{
			if (!Cef.Initialize(CefSets(), shutdownOnProcessExit: true, performDependencyCheck: false) && !Cef.IsInitialized)
			{
				Console.WriteLine("Unable to Initialize Cef");
			}
			try { Cef.AddDisposable(this); } catch (Exception e) { Console.WriteLine(e.Message); }
		}
		catch { }
		RequestContext reqcont = new RequestContext(new PluginHandler());
		try
		{
			CefSharp.OffScreen.ChromiumWebBrowser browser = new CefSharp.OffScreen.ChromiumWebBrowser("", BrSets(), reqcont)
			{
				RequestHandler = new RequestHandler(),
				JsDialogHandler = new JsDialogHandler(),
				LifeSpanHandler = new LifeSpanHandler(),
			};
		}
		catch (Exception e) { Console.WriteLine(e.Message); }
		string URL = Url;
		browser.Size = new System.Drawing.Size(800, 600);
		while (!browser.IsBrowserInitialized)
		{
			Thread.Sleep(100);
		}
		browser.Load(URL);
		Thread.Sleep(20000);
		Cef.Shutdown();
		Environment.Exit(0);
	}
	public static CefSettings CefSets()
	{
		CefSettings settings = new CefSettings();
		settings.SetOffScreenRenderingBestPerformanceArgs();
		settings.LogSeverity = LogSeverity.Error; 
		settings.LogSeverity = LogSeverity.Info; 
		settings.LogSeverity = LogSeverity.Verbose; 
		settings.LogSeverity = LogSeverity.Warning;
		settings.IgnoreCertificateErrors = true; // could be preventing the JRE?
		return settings;
	}
	public static BrowserSettings BrSets()
	{
		BrowserSettings settings = new BrowserSettings();
		settings.JavascriptOpenWindows = CefState.Disabled;
		settings.JavascriptCloseWindows = CefState.Disabled;
		settings.JavascriptDomPaste = CefState.Disabled;
		settings.OffScreenTransparentBackground = true;
		settings.WebSecurity = CefState.Enabled; 
		return settings;
	}
}
```

**Comment by amaitland** [comment]
> try { Cef.AddDisposable(this); } catch (Exception e) { Console.WriteLine(e.Message); }

You shouldn't manually be calling `Cef.AddDisposable`

You'll have to manually debug the problem yourself, you can probably load the `crash dump` that's already been generated (You'll have to `Google` for additional debugging information).
https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#unmanaged-crashes-when-the-process-dies

> [0522/164851:FATAL:memory_win.cc<39>] Out of memory, size = 645767440

Out of memory is usually related to poorly written javascript according to the `CEF` maintainer.

http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=14130&p=30612#p30612

Also you should probably try reverting to `47.0.4`, the `CEF` version that `49.0.0` is based on isn't the most stable as there appears to be some unexpected `Chromium` changes.

**Comment by amaitland** [comment]
> settings.LogSeverity = LogSeverity.Error; settings.LogSeverity = LogSeverity.Info; settings.LogSeverity = LogSeverity.Verbose; settings.LogSeverity = LogSeverity.Warning;

You only need to set `LogSeverity` once.

> CefSharp.OffScreen.ChromiumWebBrowser browser = new CefSharp.OffScreen.ChromiumWebBrowser("", BrSets(), reqcont)

Ideally pass your `URL` into the constructor and avoid the additional `LoadUrl` and remove the while loop + thread sleep.

**Comment by ArtyP** [comment]
I got "Out of memory" in my project after days of working too. The follow solution helped me to find a huge memory leak in application.
You need Visual Studio 2015 **Enterprise** or Visual Studio 2013 **Ultimate** to be installed.
1. Create a dump file (right click in Task Manager on your process)
![dump file](https://cloud.githubusercontent.com/assets/19484832/15471182/056e40b2-20f5-11e6-99a2-20a90c14a4fb.png)
2. Open dump file in Visual Studio and "Debug managed memory".
![debug man memory](https://cloud.githubusercontent.com/assets/19484832/15471354/c7652fd2-20f5-11e6-8478-9bc237683832.png)
3. Analyze the table to see possible memory leaks.

**Comment by amaitland** [comment]
@XNemo Any further comment?

**Comment by XNemo** [comment]
The fact that the program created in the Windows 10. And everything works fine. But when I run it at 7 or Vista, it gives an error. I'm still looking for a solution.

**Comment by amaitland** [comment]
@XNemo Have you loaded a crash dump yet? Downloaded the `Release symbols`? Followed any of the debugging steps listed?

**Comment by XNemo** [comment]
@amaitland  I was try to load dump...it OK. But when I press => Debug Managed Memory, I got error: memory is not available for analysis CLR-version used in this process.

**Comment by amaitland** [comment]
Find the crash dump in your users crash dump folder (don't worry about generating one manually) then use `Debug Mixed`, make sure you've downloaded the `Release Symbols` as outlined in the `Trouble Shooting Guide`

**Comment by XNemo** [comment]
@amaitland I was do it how you say. And has new error: libcef.dll.pdb was not loaded... I doownload libcef.dll.pdb from http://opensource.spotify.com/cefbuilds/index.html#windows32_builds ...but debug say about wrong image...I use Debug Symbols cef_binary_3.2704.1416.g6549316_windows32_debug_symbols.tar.bz2

**Comment by amaitland** [comment]
> libcef.dll.pdb from http://opensource.spotify.com/cefbuilds/index.html#windows32_builds ...but debug say about wrong image...I use Debug Symbols

Firstly, you need `Release Symbols` as they're release builds. Secondly you need to match the version exactly. Older versions come from https://cefbuilds.com/

**Comment by amaitland** [comment]
`51.0.0-pre01` is on `Nuget.org`, might be worth seeing if you can reproduce the problem in that branch.

**Comment by amaitland** [comment]
`51.0.0-pre02` is on `Nuget.org`, it's worth upgrading. If you can provide a sample that reproduces the problem then we can look at reopening this.
