### ISSUE TITLE
no suitable constructor exists to convert from "CefSharp::Internals::CefRequestWrapper ^" to "CefRefPtr<CefRequest>"

### ISSUE THREAD

**Issue by kanggaogang** [cefsharp/CefSharp#1694]
I downloaded this project and I always get the following error once I open the CefFrameWrapper.cpp in visual studio. but I can build the project successfully.  Would you guys help me to explain it? Thanks

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		no suitable constructor exists to convert from "CefSharp::Internals::CefRequestWrapper ^" to "CefRefPtr<CefRequest>"	CefSharp.Core	f:\Download\CefSharp-49.0.0\CefSharp.Core\Internals\CefFrameWrapper.cpp	164

**Comment by amaitland** [comment]
> I downloaded this project and I always get the following error once I open the CefFrameWrapper.cpp in visual studio. but I can build the project successfully. Would you guys help me to explain it? Thanks

Safe to ignore.

In future as per the issue template, please ask your questions on `Gitter`. Issues are for bugs only, thank you!
