### ISSUE TITLE
.dll files changed path?

### ISSUE THREAD

**Issue by ahgan84** [cefsharp/CefSharp#1695]
I'm using visual studio 2013 in win10 to do my cefsharp projects. I've just upgraded my cefsharp version to v49.0.0.

When I try to use setup and deployment to create an x86 installer for my project, there seems to be a problem.

We need to add the files we want to include into the setup in the file system, right? When I add the project output into the application folder under the file system, it will auto include CefSharp.Core.dll, CefSharp.dll and CefSharp.Winforms.dll. These 3 files source path are link to the release folder of my project (which is correct because there really is these 3 files in my release folder). I successfully build my installer at the first time.

But then when I exit my visual studio and enter again, those 3 files' source path had changed making visual can't find the 3 files when I want to build the installer again. Those 3 files'path had been changed to the location of where my project setup file will be at when it build successfully (which is the wrong path because this location only have my setup.exe and setup.msi files). 

So, why is it changed path? There's no such problem when I use CefSharp v47.

**Comment by ahgan84** [comment]
A check on the reference section (which determine the dependencies of primary output) of my project, there seems to be two CefSharp.Core.dll, two CefSharp.dll and two CefSharp.Winforms.dll. One set is the correct ones which link to the release folder. The other set do not have any source path. So, i delete this wrong references. 

But then when I exit visual studio and enter again, these wrong references will appear again. No matter how many time i delete and exit visual studio, it will appear again after I enter visual studio. Any idea what's wrong?

**Comment by ahgan84** [comment]
For the bad reference part, I kinda solve it by deleting both two sets of CefSharp.Core.dll, CefSharp.dll and CefSharp.Winforms.dll and let nuget auto add it every time I enter visual studio.

But those 3 files' still give me wrong path in the file system everytime i enter visual studio like my first question. When I delete the primary output and add again, the 3 file path will be correct again. Don't tell me I need to delete and add the primary output every time I exit visual studio and enter again. This way is troublesome.

**Comment by amaitland** [comment]
Honestly it's not clear what's going on here. The source code is there, your welcome to review any changes that were made. The `Nuget` packages were changed slightly to include `Symbols`, so start checking there first.

**Comment by Evilpaule** [comment]
I have got the same issue on win 10 maschine all dll are found on an win 8 maschine files are not found in processed path.
@ amaitland not everyone has the time to check all sourcecode. As you dont have tips or ideas please leave no comment.

**Comment by amaitland** [comment]
> I have got the same issue on win 10 maschine all dll are found on an win 8 maschine files are not found in processed path.

Specifically related to upgrade in `Visual Studio`?

**Comment by Evilpaule** [comment]
oh i cant say that its in the upgrade from 47 to 49 but i can say it exists in 49.0.0 and 49.0.1. The first version ive started with was 49.0.0. i'll give a try to 47.

**Comment by amaitland** [comment]
> NO. Same issue as i install 47.0.0 cant find one of more dll's in process path

Are you having trouble installing the packages or just deploying to a different computer?

**Comment by Evilpaule** [comment]
I deployed it in my application and my application does it perfect on win7 / win10. On my win8 machine there's a problem.

**Comment by amaitland** [comment]
> I deployed it in my application and my application does it perfect on win7 / win10. On my win8 machine there's a problem.

That's totally unrelated to this issue. 

If you have a question, ask on `Gitter`.

**Comment by amaitland** [comment]
@ahgan84 Any follow up on this? Can you provide some actual technical information? (Less words, more technical facts) Are you running the latest `Nuget`?

**Comment by amaitland** [comment]
Closing due to lack of feedback from `OP`.
