### ISSUE TITLE
Feature Request - Print Handler for PDF reader

### ISSUE THREAD

**Issue by FinPlec** [cefsharp/CefSharp#1696]
I have recently been developing a browser application using CEFSharp. However, I wanted to implement a custom print dialog instead of the simple WinForms one. I have searched every CEF form to no avail. It would be excellent to see something like IPrintHandler or something to cancel the default one and implement a custom one.

**Comment by amaitland** [comment]
> I have searched every CEF form to no avail.

The feature would need to be implemented in `CEF` before it can be implemented here.

Make your request on the [Feature Request](http://magpcss.org/ceforum/viewforum.php?f=7) forum then post a link back here.

I'll leave this open for now, will close depending on the answer you get, likely you'd need to submit a `PR` to `CEF` which implements the feature.

**Comment by amaitland** [comment]
> Implement this interface to handle printing on Linux. The methods of this class will be called on the browser process UI thread. 

http://magpcss.org/ceforum/apidocs3/projects/%28default%29/CefPrintHandler.html

**Comment by FinPlec** [comment]
Ok thanks for the quick response. I am going to submit a feature request to CEF and I'll let you know what happens. I would defiantly want to submit a PR if I could, but I have 0 experience in C++, only .net.

**Comment by amaitland** [comment]
http://magpcss.org/ceforum/viewtopic.php?f=7&t=14196

Based on the response so far I'm expecting it unlikely this will be implemented in `CEF`, at least not any time soon. If that changes we can reopen this.
