### ISSUE TITLE
PDF Viewer in 49.0.1 does not work in WPF application

### ISSUE THREAD

**Issue by ppilev** [cefsharp/CefSharp#1697]
The pdf file is loaded but the viewer does not respond until resize the application's window.

**Comment by amaitland** [comment]
> // Disable Surfaces so internal PDF viewer works for OSR
// https://bitbucket.org/chromiumembedded/cef/issues/1689
//settings.CefCommandLineArgs.Add("disable-surfaces", "1");
settings.EnableInternalPdfViewerOffScreen();

https://github.com/cefsharp/CefSharp/blob/cefsharp/49/CefSharp.Example/CefExample.cs#L95

In future ask your on `Gitter` before opening an issue here please!
