### ISSUE TITLE
JSON 转换问题

### ISSUE THREAD

**Issue by tkggusraqk** [cefsharp/CefSharp#1698]
不支持   JSON.parse() 和JSON.stringify

**Comment by tkggusraqk** [comment]
默认可以直接可以传输json对象

**Comment by amaitland** [comment]
Please take the time to read the issue template, next time you have a question please ask it on `Gitter`. This `Issue Tracker` is for `bug reports` only. Thank you!
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by zhyzhy782** [comment]
Hey,
Just  wanted to show you  something  really interesting,  that was an unexpected surprise for me)) Please take  a look  <http://cover.jonheidorn.com/e7ho/891>

zhyzhy782
