### ISSUE TITLE
HTML5 audio Does not support

### ISSUE THREAD

**Issue by tkggusraqk** [cefsharp/CefSharp#1699]
Your browser does not support the audio element.

test url:http://www.w3school.com.cn/tags/tag_audio.asp

**Comment by amaitland** [comment]
@tkggusraqk I'll say this again, if you have a question then ask it on `Gitter`, as per the `Issue Template`.

https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md
