### ISSUE TITLE
Control disappears and reappears on any DOM document change.

### ISSUE THREAD

**Issue by HTD** [cefsharp/CefSharp#1701]
Version: 49.0.0, 49.0.1 (NuGet)
Operating system: Windows 10
Architectures: x64, x86
Using CefSharp.Wpf
Steps to reproduce problem:
- Open new WPF project.
- Create x64 and x86 configurations, select one of them.
- Add CefSharp.Wpf package.
- Restart Visual Studio.
- Compile project.
- Add xmlns:cef="clr-namespace:CefSharp.Wpf;assembly=CefSharp.Wpf" line to MainWindow.xaml
- Add <cef:ChromiumWebBrowser Address="http://stackoverflow.com"/> to MainWindow.xaml replacing <Grid></Grid>
- Run project.
- Try to highlight a link on the page, making any visual changes in document.
- Retry on any page with dynamic / animated content.

Until version 47.0.4 - page renders correctly, from version 49.0.0 - page redraws completely on any visible change in document. Exact effect is the browser controls disappears and reappears. Redrawing is painfully slow, and should not occur at all.

**Comment by HTD** [comment]
After adding `var cefSettings = new CefSettings();
            cefSettings.SetOffScreenRenderingBestPerformanceArgs();
            Cef.Initialize(cefSettings);` it works. But why?

**Comment by amaitland** [comment]
> Note There is a known graphics issue with WPF and OffScreen versions, see #1634 for details, also see #1666 

As per the release notes there is a known issue with `49.0.x` see https://github.com/cefsharp/CefSharp/releases/tag/v49.0.0
