### ISSUE TITLE
Unable to use CefSharp in a project that is configured to run on AnyCpu

### ISSUE THREAD

**Issue by nagesh2501** [cefsharp/CefSharp#1704]
I am trying to reference a X86/X64 version of CefSharp but it is not letting me do. I understand that it currently does not support AnyCPU settings. But our project is required to be run on any CPU so we cannot change the configurations to a specific platform. Is there any workaround for this?

This is quite urgent for us. A quick turn around would be of great help.

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by amaitland** [comment]
`AnyCPU` is not supported at this time, if you **explicitly** require this then checkout `CefGlue` or `ChromiumFx`

**Comment by amaitland** [comment]
For **advanced** users looking for an **unsupported** and **untested** option you maybe able to remove the `.targets` and `.props` files added by the `Nuget` packages and add the `x86` dependencies manually and copy the `CEF` unmanaged dependencies manually (see the `.targets` files which which files are copied). Mark your project as `Prefer 32-bit`. Use your source control to see which `.targets` and `.props` files are added by the `Nuget` packages.

As I've already stated, there is **no support** for this method and I've **not tested** it, so it's just a theory. If you get it working then by all means provide a definitive guide. Please don't ask follow up questions as this is all the information I have.

**Comment by nagesh2501** [comment]
Hey thank you so much for a detailed explanation. And thanks for your patience too!!
