### ISSUE TITLE
Unable to reference CefSharp dlls in a project that is configured to run on AnyCpu

### ISSUE THREAD

**Issue by nagesh2501** [cefsharp/CefSharp#1706]
I am trying to reference a X86/X64 version of CefSharp but it is not letting me do. I understand that it currently does not support AnyCPU settings. But our project is required to be run on any CPU so we cannot change the configurations to a specific platform. Is there any workaround for this? Some users would be using 32 bit machine and some would be on a 64bit machine.

This is quite urgent for us. A quick turn around would be of great help.

**Comment by amaitland** [comment]
@nagesh2501 Now your just being annoying! Duplicate of #1704
