### ISSUE TITLE
Problem with disabling cache

### ISSUE THREAD

**Issue by hazardland** [cefsharp/CefSharp#1707]
I loaded javascript version 1 inside cef browser then I changed javascript file formally saying to version 2 but browser always loads version 1.

I thought I might disable cache to load next version of javascript but:

```
            CefSettings settings = new CefSettings();
            settings.CachePath = null;
            settings.CefCommandLineArgs.Add ("disable-application-cache", "1");
            Cef.Initialize(settings);
```
None of this have effect while old version of javascript file resides in browser cache.

Any other effective method to disable cache ? Please provide code sample there are not many examples over internet to related subject.

**Comment by hazardland** [comment]
Emm my fault I accidentally was changing javascript in x64 folder while was compiling x86 mode.

: (

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

@hazardland Pleased you sorted the problem, In future please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md
