### ISSUE TITLE
Issue with Getting and Setting Preference value on runtime

### ISSUE THREAD

**Issue by myrnazhou** [cefsharp/CefSharp#1708]
- **What version of the product are you using?**
Master branch 

- **What architecture x86 or x64?**
x64

- **On what operating system?**
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
When calling `requestContext.GetPreference("spellcheck");` it will return `NULL`

- **What is the expected output? What do you see instead?**
It should return the value and it should be editable using `SetPreference`, however 
```
var preferences = requestContext.GetAllPreferences(true);
var spellCheck = (Dictionary<string, object>)preferences["spellcheck"];
```
`spellcheck` variable there will have value

**Comment by amaitland** [comment]
Needs to be reported/fixed in `CEF.

**Comment by amaitland** [comment]
Short term set the preferences individually using `dot` notation

```c#
context.SetPreference("webkit.webprefs.plugins_enabled", true, out errorMessage);
```

Same applies to get preferences, use the specific key and you should be fine.

**Comment by amaitland** [comment]
> Master branch

Just saying `master` is not particularly helpful to anyone who visits this issue in a few months. Best to specify the commit or at least the version of `CEF` that's relevant which in this case is `3.2704.1418`

**Comment by amaitland** [comment]
Also setting `proxy` at runtime using preferences used to work, see http://stackoverflow.com/questions/36095566/cefsharp-3-set-proxy-at-runtime

**Comment by myrnazhou** [comment]
Yes I know that setting some preference will work, one of them is proxy. It's because 
`var proxy =  requestContext.GetPreference("proxy");`
Will return a value, not like "spellcheck" and some other preferences. Here is the full list of preferences and whether or not it can be retrieved using `GetPreference`:
```
Key: apps, Value: 
Key: browser, Value: 
Key: content_settings_window, Value: 
Key: disable_3d_apis, Value: False
Key: enable_a_ping, Value: True
Key: enable_do_not_track, Value: False
Key: enable_referrers, Value: True
Key: extensions, Value: 
Key: fullscreen, Value: 
Key: intl, Value: 
Key: media, Value: 
Key: native_messaging, Value: 
Key: partition, Value: 
Key: plugins, Value: 
Key: printing, Value: 
Key: profile, Value: 
Key: proxy, Value: System.Collections.Generic.Dictionary`2[System.String,System.Object]
Key: settings, Value: 
Key: spellcheck, Value: 
Key: updateclientdata, Value: 
Key: webkit, Value: 
Key: webrtc, Value: 
```

**Comment by amaitland** [comment]
Great, include that in your `CEF` bug report. For now, just use the `dot` notation to set/get the individual key value pairs of  `spellcheck`.

**Comment by amaitland** [comment]
To validate that changing preferences are working as expected, it's always handy to have a visual clue, there are many properties that have an immediate effect e.g.

```c#
requestContext.SetPreference("webkit.webprefs.minimum_font_size", 24, out errorMessage);
```

**Comment by myrnazhou** [comment]
Hi @amaitland,
I've pushed a commit to switching the spellcheck on and off. It's here https://github.com/myrnazhou/CefSharp/commit/614bd7c0d0136a09fbf2777934b9c43dd29e394d.
However it doesn't work, it returns true, but the spellcheck is always on. I checked it by going to this website http://www.wufoo.com/html5/attributes/17-spellcheck.html

PS: I've checked that line to change minimum font size and it works.

**Comment by amaitland** [comment]
> I've pushed a commit to switching the spellcheck on and off. It's here myrnazhou@614bd7c.
> However it doesn't work, it returns true, but the spellcheck is always on. I checked it by going to this website http://www.wufoo.com/html5/attributes/17-spellcheck.html

If it's a bug in `CEF` then I can only reiterate that you need to raise the issue `upstream.`

**Comment by amaitland** [comment]
> A tool for visualizing preferences has been added to cefclient as http://tests/preferences.html. It includes examples of getting/setting spell checking and proxy-related values.

https://bitbucket.org/chromiumembedded/cef/issues/1709/allow-configuration-of-preferences-during#comment-22288899

Probably worth checking the `2704` and `2623` branches to make sure something hasn't broken recently.

**Comment by amaitland** [comment]
> However it doesn't work, it returns true, but the spellcheck is always on.

You did try reloading the page after changing the preference?

**Comment by myrnazhou** [comment]
> You did try reloading the page after changing the preference?

Yes.

**Comment by amaitland** [comment]
> It depends on the preference. HasPreference() will return true when a preference can be set via SetPreference().

Link to the `upstream` issue which has been closed as `wontfix`, you should check using `CanSetPreference` first.

https://bitbucket.org/chromiumembedded/cef/issues/1922/some-preferences-are-not-accessible-using

**Comment by myrnazhou** [comment]
@amaitland 
I've tested in the test app in cef 2623 and 2526, switching spellcheck on and of works. However I can't find the test app for 2704 for windows, where can I get it?

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef
