### ISSUE TITLE
Drag and drop in WPF

### ISSUE THREAD

**Issue by mwisnicki** [cefsharp/CefSharp#171]
Right now it's not supported.

See upstream [bug](http://code.google.com/p/chromiumembedded/issues/detail?id=1032) - it also applies to CEF1.

**Comment by Bodekaer** [comment]
Did anyone look into this?
We'll need this for an upcoming release this month, so I could give it a go if no one is already on it.

**Comment by amaitland** [comment]
@Bodekaer Go for it :+1:

**Comment by Bodekaer** [comment]
Done :)

**Comment by jornh** [comment]
Awesome-sovs! (Whish I had time to take it for a spin ... but sadly not today :cry:)

**Comment by Bodekaer** [comment]
Here :) It works really nicely. And opens up so many new possibilities here, which is amazing.

@myrnazhou, FYI we have drag drop now. Might be useful for native image drag drop at some point (low priority though).

**Comment by amaitland** [comment]
Drag and Drop support has been implemented with #756, it's not 100% feature complete. I'm happy that it covers your typical usage scenario so I'm going to close this.

Great work @Bodekaer :+1:

**Comment by Bodekaer** [comment]
Thanks a bunch. Happy to help.

Yeah, the primary thing that is missing is the ability to drag e.g. image/text *out of* the browser.
You can drag anything into the browser atm. E.g. dropping files/images *into* the browser.

If anyone wants to implement the former, please just let me know and I can help direct to the relevant code and documentation files.

**Comment by ralphmayr** [comment]
Hi @Bodekaer! Could you provide some pointers to what would be necessary to get drag and drop *out of* and *within* the browser working? (So that for example [http://html5demos.com/drag](http://html5demos.com/drag) would work in CefShrp.Wpf)
Thanks!

**Comment by Bodekaer** [comment]
Hey @ralphmayr,
Yes definitely. Would very much like to see this added as well.
I'd recommend checking out the "drag" related issues in CEF3, and then find the relevant revision which adds support for this:
https://code.google.com/p/chromiumembedded/issues/list?can=1&q=drag&colspec=ID+Type+Status+Priority+Milestone+Owner+Summary&cells=tiles

E.g. this issue might provide the relevant input (although related to CEF1 I believe):
https://code.google.com/p/chromiumembedded/issues/detail?id=140&can=1&q=drag

With that, you'll probably see that we need to implement a few C++ methods to support the CEF3 API for dragging within/out of the browser. 
Once you find out what/where to add this, I can help with further directions if needed. 
Usually it's fairly straightforward to implement the API support in CefSharp once we know what to actually do :)

**Comment by amaitland** [comment]
The API docs are also quite handy http://magpcss.org/ceforum/apidocs3/index-all.html

**Comment by amaitland** [comment]
Also the `cefclient` reference app is generally a helpful reference https://bitbucket.org/chromiumembedded/branches-2171-cef3/src/cfa746b389c9b1f77746071bd0ee76412899cb49/tests/cefclient/?at=master
