### ISSUE TITLE
Windows authentication (NTLM)

### ISSUE THREAD

**Issue by ganeshr26** [cefsharp/CefSharp#1711]
I am using the chromiumWebBrowser control for wpf. I created a simple WPF application and included the control inside a grid. I am assigning the Browser.Address to the url to navigate in the code behind. This works like a charm and there are no issues.

The issue is whenever I give an url which requires windows authentication dialog to be popped up for entering the credentials, the browser control does not pop up the dialog. In the normal chrome browser I get the dialog popped up. I searched over the net and found a post which said one has to pass the "allow-cross-origin-auth-prompt" for this to work. So I added the code as part of the cefsttings in the startup. The following is the code I added in the application start up in the app.xaml.cs

 ```c#
 public partial class App : Application
{
	protected override void OnStartup(StartupEventArgs e)
	{
		CefSettings cefsettings = new CefSettings();
		cefsettings.CefCommandLineArgs.Add("allow-cross-origin-auth-prompt", "1");
		CefSharp.Cef.Initialize(cefsettings);                        
	}
 }
```

However this does not solve the issue and the browser control still does not prompt for authentication dialog. 

Could you please give any pointers on how to address this issue?

Thanks,
Ganesh

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, **in future ask it on `Gitter` first.**
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

> I searched over the net and found a post which said one has to pass the "allow-cross-origin-auth-prompt" for this to work.

Not sure where you found that setting, doubt it relates to `NTLM` authentication though. The relevant `upstream` issue is https://bitbucket.org/chromiumembedded/cef/issues/1150/ntlm-authentication-issue **MAKE SURE YOU READ THIS LINK IN FULL**

Here is an example of how to call `SetPreference` https://github.com/cefsharp/CefSharp/blob/cefsharp/49/CefSharp.Example/CefExample.cs#L151

I have no way of testing this myself, you'll have to apply some trial and error testing of your own.

**Comment by amaitland** [comment]
For basic authentication you implement `IRequestHandler.GetAuthCredentials`

https://github.com/cefsharp/CefSharp/blob/cefsharp/49/CefSharp.Example/RequestHandler.cs#L118

**Comment by amaitland** [comment]
As a general reference there are no passwords dialogs or javascript prompts by default, you have to implement those yourself.

**Comment by amaitland** [comment]
May not be possible until https://bitbucket.org/chromiumembedded/cef/pull-requests/63/ is updated and merged.

**Comment by amaitland** [comment]
Maybe possible via command line options after all. 

http://magpcss.org/ceforum/viewtopic.php?f=6&t=11085&p=26108#p26108
