### ISSUE TITLE
Dynamically loading 32bit or 64bit

### ISSUE THREAD

**Issue by NKumarPraveen** [cefsharp/CefSharp#1712]
Hi,

I am using 32 bit dll in my application compiled on x86 platform working fine, I would like to load 64 or 32 bit cef version at run time by identifying platform(Environment.Is64BitProcess). Is this possible to load cef with all dependecies or is there configuration required.

Technical details

Version: Chromium: 45.0.2454.62, CEF: r3.2454.1317.gc22b77d, CefSharp: 45.0.0.0
Windows 7
x86
WinForms *.Net framework :4.5

Thanks

**Comment by amaitland** [comment]
> Is this possible to load cef with all dependecies or is there configuration required.

The libraries are statically compiled to be `x64` or `x86`, if it's possible I'm not aware of a way.

Also, in future ask your questions on [Gitter](https://gitter.im/cefsharp/CefSharp#) as outlined in the issue template.

https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by amaitland** [comment]
I should also note a 64-bit process can only load 64-bit dlls and a 32-bit process can only load 32-bit dlls. Basically what your describing is `AnyCPU`, which is not supported. You can use one of the other `CEF` wrappers, like `CefGlue` or `ChromiumFx`.
