### ISSUE TITLE
.pdb file not loaded

### ISSUE THREAD

**Issue by novisecoder** [cefsharp/CefSharp#1715]
When attempting to debug an application in winforms c#, vs returns an exception of type system.accessviolationexception and cannot load or find cefsharp.core.pdb. I tried deleting the temp files and i tried adding the pdb file manually to the debug folder yet the exception is still thrown. i tried to browse and add the file, a message box shows up saying a matching symbol file was not found in this folder.

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md
