### ISSUE TITLE
Rendering issue when opened popup as new tab.

### ISSUE THREAD

**Issue by appmazic** [cefsharp/CefSharp#1716]
hi Team,

Am trying to open pop up as new tab using **ILifeSpanHandler.OnBeforePopup**, am getting target url like this targetUrl = "https://www.airtel.in/account/AuthApp/GoogleLogin "

but actual url is this: 
https://accounts.google.com/ServiceLogin?passive=1209600&continue=https://accounts.google.com/o/oauth2/auth?scope%3Dhttps://www.googleapis.com/auth/userinfo.profile%2Bhttps://www.googleapis.com/auth/userinfo.email%26response_type%3Dcode%26redirect_uri%3Dhttps://www.airtel.in/account/AuthApp/GoogleLogin%26state%3DapVrtnshDfgEzEPhBewPzBT%26client_id%3D867444784871.apps.googleusercontent.com%26from_login%3D1%26as%3D3ca58c2d706e521b&oauth=1&sarp=1&scc=1#identifier.

the above url will render the page and will show output. 
please help to get the actual url and render the page of popup as new tab. in cefsharp 
what code need to be write in ILifeSpanHandler.OnBeforePopup .

Please help me.

**Comment by amaitland** [comment]
### How do I investigate my issue further?

It's important to remember that `CefSharp` is just a wrapper around the `Chromium Embedded Project (CEF)`, the upstream [`CEF` forum](http://magpcss.org/ceforum/) is a valuable resource. Also `CEF` has it's own [Issue Tracker](https://bitbucket.org/chromiumembedded/cef/issues). Please take the time to research your own problem, including `Googling`, searching on `ceforum`.

--
#### Finding more info
- Have you checked the `Debug.log` file? (Should be located in your apps executing folder by default)
- Have you googled the error message your seeing? (Don't just google the whole thing, try googling just the keywords and possibly add `chromium` as a keyword).
- Are you able to reproduce the problem using `cefclient`? (`cefclient` is the reference implementation provided by `CEF`)
- Need more help debugging? Check the [Troubleshooting Guide](https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting)
- Are you using the latest version? Check the [Release Branches](https://github.com/cefsharp/CefSharp#release-branches) table to determine if the version your using is supported. 

--
#### How do I download `cefclient`?

- Firstly identity which version of `CEF` your actually using, easiest way is to check your `packages.config` file, look for the `cef.redist.x86` package, it's version will be something like `3.2526.1362`, that's the exact version of `CEF` you'll need to download for comparison. You can also open `chrome://version` in the browser to determine the version.
- Open http://cefbuilds.com in a web browser
- Locate the exact `Branch` you require, for the example above the branch is `2526`, all the versions follow a similar pattern
- Locate the `Windows 32bit` or `Windows 64bit` item, if you don't see the exact version, then click `more revisions`
- Download **Test App**
- Are you using `WPF/Offscreen` or `WinForms`? 

**This next part is key**
- To compare with WPF/OffScreen run `cefclient --multi-threaded-message-loop --off-screen-rendering-enabled`
- To compare with WinForms `cefclient --multi-threaded-message-loop`

**Comment by amaitland** [comment]
> Am trying to open pop up as new tab using ILifeSpanHandler.OnBeforePopup, am getting target url like this targetUrl = "https://www.airtel.in/account/AuthApp/GoogleLogin "

Your problem would need to be resolved in `CEF`.

**Comment by appmazic** [comment]
hi team,

am using cefsharp  <package id="cef.redist.x86" version="3.2357.1287" targetFramework="net45" />
in winforms, wpf.

but unable to get display or render the page by using this url  "https://www.airtel.in/account/AuthApp/GoogleLogin "

**Comment by appmazic** [comment]
<package id="cef.redist.x86" version="3.2357.1287" targetFramework="net45" />

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by appmazic** [comment]
Please help me to open a popup as new tab in cefsharp using  ILifeSpanHandler.OnBeforePopup

**Comment by amaitland** [comment]
> am using cefsharp ="cef.redist.x86" version="3.2357.1287" targetFramework="net45"
> in winforms, wpf.

Try upgrading to a newer version, the version your using is outdated. `49.0.1` is the latest.

**Comment by amaitland** [comment]
> Please help me to open a popup as new tab in cefsharp using ILifeSpanHandler.OnBeforePopup

Locking this issue now, please read the instructions you've been provided.
