### ISSUE TITLE
How to Invoke Java script in CefSharp Browser

### ISSUE THREAD

**Issue by Arunkumar-Murugesan** [cefsharp/CefSharp#1718]
Hi All,

I have bind the bulk of comments in CefSharp Browser. Last five comments only I bind initially and then I have added link "Load More" option using Java Script. But I cannot call the method whenever access the "Load More" link through CefSharp browser using java script. The same process I can able to access in web-browser control. Could you please assist as to do the same process in CefSharp Browser?
The below codes are used for WebBrowser Control.

![image](https://cloud.githubusercontent.com/assets/20086495/16261219/cab397b4-3838-11e6-9bea-d57eab69ca63.png)

Thanks in advance.

Best,
Arun

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md
