### ISSUE TITLE
Feature Request - Update BrowserSubProcess to be Per-monitor DPI aware

### ISSUE THREAD

**Issue by Teknica** [cefsharp/CefSharp#1720]
Update **CefSharp.BrowserSubprocess.exe** manifest from "**DPI aware**" to "**Per-monitor DPI aware**", i.e. change \<dpiAware>**true**\</dpiAware> to \<dpiAware>**true/PM**\</dpiAware>

**Ref:** [Developing a Per-Monitor DPI-Aware Applications](https://goo.gl/Jor8Er)

**Comment by amaitland** [comment]
@Teknica Please submit a `PR` with your proposed changed.

**Comment by Teknica** [comment]
Alex,

I am new to GitHub and do not even know what "PR" is. At the same time my
proposed the change is small, though very important - your CEF
implementation does not work right on Windows 10 without that fix, when DPI
scaling is enabled per monitor .

Can you help to push this update through?

Best regards,

Alex Danilychev

**Comment by amaitland** [comment]
> I am new to GitHub and do not even know what "PR" is.

`Pull Request`. If your familiar with `Git` this should be very easy. If not then it's still not that difficult to create a work. Make your changes, test, push to `GitHub` then create a `Pull Request`

https://github.com/cefsharp/CefSharp/wiki/Forking-and-Pull-Requests

> Can you help to push this update through?

I don't have time to test such a change (Also I don't require such a change, so it's a low priority).

**Comment by amaitland** [comment]
@Teknica Are you at least going to have a go at implementing and testing your proposed change? 

Ideally this would be tested on `Windows 7` and `Windows 10` with `DPI > 100%`, make sure it's backwards compatible.

I'll be releasing `51.0.0-pre02` in the next few days, if you can get it done, great. If not then it'll just have to wait. Probably when/if I get around to looking at #1535 and #1543

**Comment by Teknica** [comment]
Alex,

DPI awareness is supported from Windows XP (no DPI virtualization) through
Windows 10. Only Windows 8.1 and Windows 10 are per monitor-DPI aware.
Proposed change to CefSharp.BrowserSubprocess.exe manifest file from "true"
to "true/PM" will be ignored by unsupported OS and interpreted as "true" by
Windows 7 through 8, while Windows 8.1 and Windows 10 work correctly with
per-monitor settings. However if not set, CEF is to be messed-up on these
OS, even if the parent process has an updated manifest file.

Here is Microsoft take on the subject: https://goo.gl/8lcJQf

**Comment by amaitland** [comment]
@Teknica So you believe everything you read on `MSDN` without testing to see that it works? Someone needs to verify that their is no adverse effects on `Windows 7/8` before releasing this change. Sounds reasonable doesn't it?

The thing is, if if make a change on your suggestion, it doesn't work in some scenario, who's the one that people look to for support? Contributing ideas is one thing, code is another and hanging around to provide support and maintenance is something totally different!!!

**Comment by Teknica** [comment]
Alex,

OK, I tested your app on Windows 10. Will Get Windows 7 and 8.1 tested
tonight ;)

**Comment by amaitland** [comment]
> OK, I tested your app on Windows 10. Will Get Windows 7 and 8.1 tested tonight ;)

Great :+1: Once tested I'm happy to merge a `PR` with your proposed changes. I'm sorry but being new to `GitHub` isn't a valid excuse in my book, their was a time I was new also, I wanted access to the zooming api, so I added the methods...everyone has to start somewhere!

**Comment by amaitland** [comment]
> Great :+1: Once tested I'm happy to merge a PR with your proposed changes. I'm sorry but being new to GitHub isn't a valid excuse in my book, their was a time I was new also, I wanted access to the zooming api, so I added the methods...everyone has to start somewhere!

Obviously nothing personal here, the project needs more contributors if it's to survive, no room for excuses.

**Comment by Teknica** [comment]
Alex,

Windows 7 x64 (Build 7601, SP1) confirmed with CEFsharp 51.0.0.0-pre01
using \<dpiAware>true/PM\</dpiAware> in place  of
\<dpiAware>true\</dpiAware>.

CefSharp.BrowserSubprocess.exe manifest file is attached.

**Comment by amaitland** [comment]
> Windows 7 x64 (Build 7601, SP1) confirmed with CEFsharp 51.0.0.0-pre01

Great :+1: 

Please submit a `PR` with your change.
