### ISSUE TITLE
Feature Request - Add IUrlRequest 

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#1721]
Add `Cef.CreateUrlRequest` and the appropriate interfaces/wrappers.

http://magpcss.org/ceforum/apidocs3/projects/(default)/CefURLRequest.html

**Comment by olifantix** [comment]
Not sure if this feature is what I am looking for. 

I want to stream-upload files (up to 1,5 TB) als upload-post chunked and report progress on it. Haven't found anything so far about chunked datatransfer and creating a 

    IFrame frame = browser.GetMainFrame ();
    IRequest request = frame.CreateRequest ();

    request.Url = uploadUrl;
    request.Method = "POST";
    request.Flags = UrlRequestFlags.ReportUploadProgress;
    request.InitializePostData ()
    request.PostData.AddFile (fullPath);
    request.Headers = new NameValueCollection {{ "Content-Type", webFile.MimeType }};
    frame.LoadRequest (request);

did not work at all, where as uploading smaller files 

    byte[] bytes = File.ReadAllBytes (fullPath);
    var dataElement = request.PostData.CreatePostDataElement ();
    dataElement.Bytes = bytes;
    request.PostData.AddElement (dataElement);
    request.Headers = new NameValueCollection {{ "Content-Type", webFile.MimeType }};
    frame.LoadRequest (request);

does work. From the C++ documentation I think I need the `CefURLRequest `+ `CefURLRequestClient` to facilitate upload-progress feedback?

**Comment by amaitland** [comment]
> I want to stream-upload files (up to 1,5 TB) als upload-post chunked and report progress on it

Have you confirmed that `Chrome` supports uploading files that large?

> Haven't found anything so far about chunked datatransfer and creating a

You will have to ask the `CEF` maintainer for clarification, far as I know `CEF` doesn't support chunked data transfers.

> does work. From the C++ documentation I think I need the `CefURLRequest`+ `CefURLRequestClient` to facilitate upload-progress feedback?

In theory yes. I've not tried.

**Comment by davidmi** [comment]
Hi, I've taken a shot at implementing this, please take a look at the related pull request!

**Comment by amaitland** [comment]
With commit https://github.com/cefsharp/CefSharp/commit/ec8d58bceccdf832e5e5e02fc41b659d5f9a03a9 it's now possible to create a `UrlRequest` that's not associated with a `IFrame`.

See the commit for a usage example.
