### ISSUE TITLE
C# winforms popup handler error

### ISSUE THREAD

**Issue by Amandriel** [cefsharp/CefSharp#1726]
Hello, i have problem with LifeSpanHandler in onBeforePopup:
>The out parameter 'newBrowser' must be assigned to before control leaves the current method
I'm newbie and i can't handle it. I read the documentation "/// Called after a new browser is created.", but i can't understand how do this?

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by amaitland** [comment]
Please stop asking the same question over and over again. I've answered it twice already.
