### ISSUE TITLE
Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies.

### ISSUE THREAD

**Issue by brugh** [cefsharp/CefSharp#1727]
- **What version of the product are you using?**
CEFsharp.WinForms v49.0.1, cef.redist.x64 (and x86) v3.2704.1418

    - What version are you using? Nuget? CI Nuget? build from a branch? If so which branch?
Nuget package manager 3.4.4 from Visual Studio 2015 Version 14.0.25421.03 update 3

- **What architecture x86 or x64?**
Tried both, both with same error. 

- **On what operating system?**
Windows 10 

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
Winforms 

- **What steps will reproduce the problem?**
any call to CEF will produce this error. CefSharp.Cef.Initialize() crashes the VSTO plugin i'm building. 

- **What is the expected output? What do you see instead?**
no output available.. i have a Windows Form that needs a browser to an external management page but anywhere i try to initialize CEF it crashes saying it can't find the core.dll or dependency. 

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.
   at poller.ThisAddIn.openPoll(String _action, String data)
   at poller.ThisAddIn.createPoll() in \\SRV\SHR\powerpoint\poller\ThisAddIn.cs:line 378
   at poller.Ribbon1.createButton_Click(Object sender, RibbonControlEventArgs e) in \\SRV\SHR\powerpoint\poller\Ribbon1.cs:line 190
   at Microsoft.Office.Tools.Ribbon.RibbonPropertyStorage.ControlActionRaise(IRibbonControl control)
   at Microsoft.Office.Tools.Ribbon.RibbonPropertyStorage.ButtonClickCallback(RibbonComponentImpl component, Object[] args)
   at Microsoft.Office.Tools.Ribbon.RibbonManagerImpl.Invoke(RibbonComponentCallback callback, Object[] args)
   at Microsoft.Office.Tools.Ribbon.RibbonMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Office.Tools.Ribbon.RibbonManagerImpl.System.Reflection.IReflect.InvokeMember(String name, BindingFlags invokeAttr, Binder binder, Object target, Object[] args, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParameters)

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
i have no log in my BIN dir.. how do i enable that? 

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
Only other addin i have is Auth0. i just installed cefsharp.winforms through the nuget package manager that's built into visual studio, added cef.initialize() and even with that being the only line of CEF in my code, gives the above error. i removed the bin directory completely, rebuilt the app, it starts fine but crashes when i open the form that holds the initialize() line. Files from the bin directory (x86\debug) are looking complete: 
`
21-03-16  10:15            92.720 Auth0.ManagementApi.xml
19-02-15  21:10            21.720 System.Net.Http.Primitives.dll
16-05-16  20:52           412.130 natives_blob.bin
26-05-15  13:36            92.344 Microsoft.Office.Tools.Common.dll
26-05-15  13:40            67.178 Microsoft.VisualStudio.Tools.Applications.Runtime.xml
13-06-16  23:06           523.221 Newtonsoft.Json.xml
16-05-16  20:52           233.072 cef_200_percent.pak
16-05-16  20:52            75.264 libEGL.dll
31-05-16  21:58             4.012 CefSharp.WinForms.xml
31-05-16  21:58            22.528 CefSharp.WinForms.dll
01-08-14  01:17           470.712 Microsoft.SharePoint.Client.dll
19-02-15  21:10               151 System.Net.Http.Primitives.xml
22-04-16  10:09            48.799 Auth0.Core.xml
26-07-12  14:12         1.103.256 Microsoft.IdentityModel.dll
29-06-16  10:33            23.552 Auth0.Windows.dll
22-04-16  10:09            45.056 Auth0.Core.dll
30-06-16  10:33         1.080.320 poller.dll
21-03-16  10:15            44.032 Auth0.ManagementApi.dll
16-05-16  20:52         4.665.083 devtools_resources.pak
01-08-14  01:17            67.208 Microsoft.Office.Client.Education.dll
31-05-16  21:58            28.601 CefSharp.Core.xml
19-02-15  21:10            22.232 System.Net.Http.Extensions.dll
16-05-16  20:52           182.784 widevinecdmadapter.dll
30-06-16  10:09    <DIR>          locales
19-02-15  21:10             5.532 System.Net.Http.Extensions.xml
30-06-16  10:33            85.504 poller.pdb
31-05-16  21:58           320.415 CefSharp.xml
16-05-16  20:52           486.072 snapshot_blob.bin
30-06-16  10:22             1.039 poller.dll.config
01-08-14  01:17           288.968 Microsoft.SharePoint.Client.Runtime.dll
30-06-16  10:33             5.458 poller.vsto
31-05-16  21:58            10.752 CefSharp.BrowserSubprocess.exe
31-05-16  21:58           688.640 CefSharp.BrowserSubprocess.Core.dll
26-05-15  13:40            20.372 Microsoft.Office.Tools.v4.0.Framework.xml
21-03-16  10:15           118.272 Auth0.ManagementApi.pdb
13-06-16  23:06           526.336 Newtonsoft.Json.dll
16-05-16  20:52        48.936.448 libcef.dll
26-05-15  13:40            19.467 Microsoft.Office.Tools.Common.v4.0.Utilities.xml
26-05-15  13:36            83.168 Microsoft.VisualStudio.Tools.Applications.Runtime.dll
16-05-16  20:52         2.106.216 d3dcompiler_43.dll
30-06-16  10:33            36.213 poller.dll.manifest
26-05-15  13:36            32.664 Microsoft.Office.Tools.Common.v4.0.Utilities.dll
26-05-15  13:36            16.048 Microsoft.Office.Tools.dll
31-05-16  21:58         1.029.120 CefSharp.Core.dll
26-05-15  13:40           201.928 Microsoft.Office.Tools.Common.xml
26-05-15  13:36            28.360 Microsoft.Office.Tools.v4.0.Framework.dll
22-04-16  10:09           157.184 Auth0.Core.pdb
16-05-16  20:52         3.709.120 d3dcompiler_47.dll
16-05-16  20:52         4.282.175 cef_extensions.pak
16-05-16  20:52        10.207.936 icudtl.dat
16-05-16  20:52           144.747 cef_100_percent.pak
16-05-16  20:52         2.322.682 cef.pak
16-05-16  20:52         1.665.024 libGLESv2.dll
31-05-16  21:58           157.696 CefSharp.dll
`
- **Does this problem also occur in the `Cef` TestApp from http://cefbuilds.com?**
no, the testapp runs fine!

**Comment by amaitland** [comment]
> any call to CEF will produce this error. CefSharp.Cef.Initialize() crashes the VSTO plugin i'm building

`VSTO` is not supported. You'll need to use `CefGlue` or `ChromiumFx`.

**Comment by amaitland** [comment]
`CefSharp` does not run in multiple `AppDomains` #351
