### ISSUE TITLE
ExecuteScriptAsync with parameters does not handle booleans

### ISSUE THREAD

**Issue by chylex** [cefsharp/CefSharp#1728]
The version and architecture info don't matter, the bug is in the core and still present in master branch.

- **What version of the product are you using?**
49.0.0-pre2 from NuGet

- **What architecture x86 or x64?**
x86

- **On what operating system?**
Win 7

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms

- **What steps will reproduce the problem?**
Using [WebBrowserExtensions.ExecuteScriptAsync(this IWebBrowser browser, string methodName, params object[] args)](https://github.com/cefsharp/CefSharp/blob/master/CefSharp/WebBrowserExtensions.cs#L194) to pass a boolean variable in the *args* converts it to *"True"* or *"False"* which are both truthy strings, therefore passing *false* will always result in *true* on JS side.

- **Please provide any additional information below.**
This would probably need a little bit of special casing, unfortunately adding the bool type to [WebBrowserExtensions.numberTypes](https://github.com/cefsharp/CefSharp/blob/master/CefSharp/WebBrowserExtensions.cs#L15) is not enough because Boolean.ToString capitalizes the first letter and JavaScript doesn't accept True/False despite being case-insensitive. So either special casing booleans or something like:

```
if (!numberTypes.Contains(obj.GetType()))
{
    stringBuilder.Append("'").Append(args[i].ToString()).Append("'");
}
else
{
    stringBuilder.Append(args[i].ToString().ToLowerInvariant());
}
```

**Comment by amaitland** [comment]
@chylex Please submit a `PR` with your proposed changes.

**Comment by chylex** [comment]
Will look into it, I don't have a CefSharp fork setup yet.

**Comment by chylex** [comment]
Turns out there are more issues with the method, calling ToString on a decimal number in most european locales will print it with a decimal comma, not a decimal point. I'll fix that too.

**Comment by amaitland** [comment]
> Turns out there are more issues with the method, calling ToString on a decimal number in most european locales will print it with a decimal comma, not a decimal point. I'll fix that too.

It's only a rough helper method, for anyone wanting full control they can quite easily implement their own.
