### ISSUE TITLE
create interop user control

### ISSUE THREAD

**Issue by Alberttg77** [cefsharp/CefSharp#1730]
hello i need to create an interop user control with visula studio to use cefSharp in a vb6 project.
I've created the control but it crashed in the opening.
Can yoy help me? thanks.

Here is the code:

```
Private Sub InteropUserControl_Load(sender As Object, e As EventArgs) Handles Me.Load
        Dim settings As New CefSettings()
        CefSharp.Cef.Initialize(settings)

        browser = New ChromiumWebBrowser("http://thechriskent.com") With {
                .Dock = DockStyle.Fill
            }
    End Sub
```
Here is attache the error:
![prtscr capture_2](https://cloud.githubusercontent.com/assets/2923353/16529208/da6259c6-3fc1-11e6-8451-7283160465e2.jpg)

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md
