### ISSUE TITLE
Web audio AudioBufferSourceNode "ended" event not fired

### ISSUE THREAD

**Issue by MaitreDede** [cefsharp/CefSharp#1732]
Hi :)

I am trying to use WebAudio, and trigger some actions on sound play end. I am using the "ended" event of AudioBufferSourceNode, but it is not triggered.

- **What version of the product are you using?**

    Nuget version :
```XML
  <package id="cef.redist.x64" version="3.2623.1401" targetFramework="net452" />
  <package id="cef.redist.x86" version="3.2623.1401" targetFramework="net452" />
  <package id="CefSharp.Common" version="49.0.1" targetFramework="net452" />
  <package id="CefSharp.WinForms" version="49.0.1" targetFramework="net452" />
```

- **What architecture x86 or x64?**

x86

- **On what operating system?**

Win7 pro x64

- **Are you using `WinForms`, `WPF` or `OffScreen`?**

Winforms

- **What steps will reproduce the problem?**

Load an audio file, play it with WebAudio, "ended" event is not triggered.

- **What is the expected output? What do you see instead?**

Expected : event fired (seen with a basic console.log)
Instead : nothing

- **Please provide any additional information below.**

Chromium issue : https://bugs.chromium.org/p/chromium/issues/detail?id=403908

Test code : [test.zip](https://github.com/cefsharp/CefSharp/files/345361/test.zip)

- **Does this problem also occur in the `Cef` TestApp from http://cefbuilds.com?**

Don't know how to test

**Comment by MaitreDede** [comment]
Re-hi :)

I have upgraded packages to latest pre-release of Nuget packages :
```XML
  <package id="cef.redist.x64" version="3.2704.1418" targetFramework="net452" />
  <package id="cef.redist.x86" version="3.2704.1418" targetFramework="net452" />
  <package id="CefSharp.Common" version="51.0.0-pre01" targetFramework="net452" />
  <package id="CefSharp.WinForms" version="51.0.0-pre01" targetFramework="net452" />
```

I no longer have the issue.

**Comment by amaitland** [comment]
> I no longer have the issue.

Great :+1: Closing.

**Comment by amaitland** [comment]
> Please no links to binaries, e.g. zip files, either contribute your example as a github project, a gist or another public code sharing service.

https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#help-us-help-you
