### ISSUE TITLE
Wpf crashes on window.parent.close()

### ISSUE THREAD

**Issue by MWFIAE** [cefsharp/CefSharp#1733]
- **What version of the product are you using?**
  - nuget 49.0.1
- **What architecture x86 or x64?**
  x86
- **On what operating system?**
  - Win7
- **Are you using `WinForms`, `WPF` or `OffScreen`?**
  WPF
- **What steps will reproduce the problem?**
  Navigate to a Website containing a Frameset, with a Frame that contains a js call to "window.parent.close();"

frameset.html

```
<frameset>
<frame src="frame.html" name="frame"/>
</frameset>
```

frame.html

```
<script type="text/javascript">
 window.parent.close();
</script>
```
- **What is the expected output? What do you see instead?**
  Expected: Doing nothing. 
  See: Whole Application is crashing. 
- **Please provide any additional information below.**
  - A stack trace if available, any Exception information.
    AccessViolation
    libcef.dll!CefBrowserHostImpl::SetFocus(bool focus) Zeile 552
  - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
    No
  - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
    No
- **Does this problem also occur in the `Cef` TestApp from http://cefbuilds.com?**
  No
  But it occurs in the minimal wpf example.

**Comment by MWFIAE** [comment]
Additional Note:  Implementing ILifeSpanHandler.DoClose and return true;
solves the crashing issue, but the browser freezes, no more executed js, no clickable links etc.

**Comment by srini1978** [comment]
Does this happen on version 57?

**Comment by amaitland** [comment]
Closing as we haven't had a report of this in years. 

If the problem can be reproduced with the current stable version then please provide the following and we can reopen. 

- A fork of https://github.com/cefsharp/CefSharp.MinimalExample that demos the problem 
- A full stack trace see https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#loading-native-symbols-for-easier-diagnosis for details on loading the CEF symbols.
