### ISSUE TITLE
CefSharp.BrowserSubprocess.exe crashed randomly

### ISSUE THREAD

**Issue by skykharkov** [cefsharp/CefSharp#1739]
- **What version of the product are you using?**
    - Chromium  - 51.0.2704.103
    - libcef.dll  - 3.2704.1432.0
    - CefSharp.BrowserSubprocess.exe - 51.0.0.0

- **What architecture x86 or x64?**
    - x86

- **On what operating system?**
    - Win10 Home and Pro, Rus and Eng. Tested on 7 PC

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - WinForrms

- **What steps will reproduce the problem?**
    - Continuously loading and destroying browsers in cycle. Automated test. CefSharp.BrowserSubprocess.exe crashed randomly. Can crash without stack trace.

- **Please provide any additional information below.**
    - Attached windows log event with crash and stack trace

- **Does this problem also occur in the `Cef` TestApp from http://cefbuilds.com?**
    - No

**Comment by amaitland** [comment]
> Please no links to binaries, e.g. zip files, either contribute your example as a github project, a gist or another public code sharing service.

@skykharkov Your zip file has been removed as per https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#help-us-help-you

You will need to debug this yourself. See https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#unmanaged-crashes-when-the-process-dies

> CefSharp.BrowserSubprocess.exe - 51.0.0.0

Assuming your using the `51.0.0-pre02` packages. Please try the `49.0.1` to see if the problem is reproducible.

**Comment by skykharkov** [comment]
Thank you for response. Where I can get debug symbol (release) for 49 version?

**Comment by skykharkov** [comment]
Finish testing with 49.0.2623.110. Problem is reproduced. Randomly crash with stack trace:
System.AccessViolationException
in <Module>.CefExecuteProcess(CefMainArgs*, CefRefPtr<CefApp>*, Void*)
in CefSharp.CefAppWrapper.Run()
in CefSharp.BrowserSubprocess.Program.Main(System.String[])

**Comment by amaitland** [comment]
> Where I can get debug symbol (release) for 49 version?

https://cefbuilds.com/#branch_2623

Make sure you download the release symbols.

> Randomly crash with stack trace:

That's unfortunately not enough to go on. You'll need a stack trace from the `unmanaged` code. Also check your `Debug.log` file.

**Comment by amaitland** [comment]
Closing due to lack of feedback.
