### ISSUE TITLE
Question : Performance of exposed objects

### ISSUE THREAD

**Issue by MaitreDede** [cefsharp/CefSharp#1741]
Hi,

I would like to know if exposed managed objects to javascript have a major overhead when used.

I would like to do some animation on my Winforms form, driven from javascript, but it seams that there is some suttering in the animation.

If I understand well, there is a WPF communication tunnel between my app and the browser process. Am I right if I behave that the calls from javascript to dotnet are queued, so there is only one active method call at a time ?

Is there a way to improve the responsiveness of this feature ?

Thanks :)

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by amaitland** [comment]
> If I understand well, there is a WPF communication tunnel between my app and the browser process. Am I right if I behave that the calls from javascript to dotnet are queued, so there is only one active method call at a time ?

Use the `async` version if performance is important to you.
