### ISSUE TITLE
WinForms CefSharp instance is flashing when in background on OffScreen instance urls are loading

### ISSUE THREAD

**Issue by zeno32167** [cefsharp/CefSharp#1745]
**What version of the product are you using?**

Problem exists in v51.0.0, v49.0.1
It does not exist in v47.0.3

**What architecture x86 or x64?**

x86

**On what operating system?**

Win10

**Are you using WinForms, WPF or OffScreen?**

WinForms and OffScreen

**What steps will reproduce the problem?**

Open winforms instance, in the background run OffScreen instance. On OffScreen instance load Urls. 

**What is the expected output? What do you see instead?**

Expected: no flashing
Occurring: WinForms CefSharp window is flashing when on OffScreen instance urls are loaded.

**Please provide any additional information below.**

Winforms instance is not flashing when in background urls are not loading.
Please see this uploaded 3 minutes movie so you will see how it looks like: [https://youtu.be/4fOZ9xB3fd4](https://youtu.be/4fOZ9xB3fd4)

**Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)**

There are some errors, most common one:
[0718/195026:ERROR:gles2_cmd_decoder.cc(7857)] [.CommandBufferContext.DisplayCompositor-22F66DC8]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
[0718/195026:ERROR:gles2_cmd_decoder.cc(14683)] [.CommandBufferContext.DisplayCompositor-22F66DC8]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name

[debug.txt](https://github.com/cefsharp/CefSharp/files/369949/debug.txt)

**Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?**

Nope

**Does this problem also occur in the Cef TestApp from http://cefbuilds.com?**

Have no idea.

**Comment by amaitland** [comment]
There are known `GPU` issues with version greater than `47`. See #1634 

In future read the release notes, it's listed as a known problem.
