### ISSUE TITLE
The type or namespace name'WinForms' does not exist in the namespace 'CefSharp'?

### ISSUE THREAD

**Issue by ccnucheng** [cefsharp/CefSharp#1747]
--win 10  professional 64bit
--visual studio 2013 ultimate
--download CefSharp.WinForms & CefSharp.Common with NuGet
--include 'CefSharp.Dll'  CefSharp.Core.Dll   CefSharp.WinForms.Dll
--Solution platform : x86

The type or namespace name'WinForms' does not exist in the namespace 'CefSharp'?

![cefsharp](https://cloud.githubusercontent.com/assets/12076754/16936755/da59a32a-4d9b-11e6-8221-6174c7b22223.png)

**Comment by ccnucheng** [comment]
![cefsharp](https://cloud.githubusercontent.com/assets/12076754/16936759/e4f8e642-4d9b-11e6-952b-7e24f1c91007.png)

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by amaitland** [comment]
Make sure your project is targeting at least `.Net 4.5.2` which is the new minimum for `51.0.0`
