### ISSUE TITLE
Handle navigation to new path in same domain

### ISSUE THREAD

**Issue by johnzhu** [cefsharp/CefSharp#1750]
I have used IRequestHandler.OnBeforeBrowse to handle navigation changes (e..g, use external browser to handle certain links). However, it is only called when a full URL changed. If it is just path change, then this is not called. For example, browse to https://github.com/cefsharp/CefSharp/, then click on "issues", the URL address is changed to https://github.com/cefsharp/CefSharp/issues, but IRequestHandler.OnBeforeBrowse is not called.  What is the best way to intercept the URL changes (and potentially use external browser to complete the request)?
Thanks.

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md
