### ISSUE TITLE
Missing assembly reference in WPF application

### ISSUE THREAD

**Issue by Werckmeisterr** [cefsharp/CefSharp#1752]
Hello!

I'm trying to install CefSharp (51.0.0 nuget version) on a WPF application. I followed the Quick Start tutorial on [Codeproject](http://www.codeproject.com/Articles/881315/Display-HTML-in-WPF-and-CefSharp-Tutorial-Part) and everything worked until I tried adding the reference to the XAML file:

`xmlns:cefSharp="clr-namespaceassembly=CefSharp.Wpf"`

Firstly, Visual Studio said the XAML file can't find the reference to CefSharp.Wpf. Again, I tried to rebuild the project, and it worked, the error list was empty. But after trying to run the application I got this error:

> Error	7	The type or namespace name 'CefSharp' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\t0mc0_000\documents\visual studio 2013\Projects\Assistant\Assistant\obj\x64\Debug\MainWindow.g.cs	12	7	Assistant

I tried both x64 and x86, neither of them works. As you can see, the error only occurred in MainWindow.g.cs which (as far as I know) is generated by the XAML file. Strangely, I can reference CefSharp.Wpf in MainWindow.xaml.cs and in the other C# source files. 

I'm using a freshly installed Visual Studio 2013 on Windows 10. 

I tried reopening VS and rebuilding multiple times (also tried deleting the "obj" folder) but nothing happened.

**Comment by SGStino** [comment]
The nuget doesn't seem to be adding any references to the project if the build configuration is "Any Cpu".

Installing the nuget with x64 as platform will give you the references to the CefSharp, CefSharp.Core and CefSharp.Wpf assemblies.

**Comment by Werckmeisterr** [comment]
I didn't use "Any CPU" configuration - as I said, I followed the official [Quick Start guide](http://www.codeproject.com/Articles/881315/Display-HTML-in-WPF-and-CefSharp-Tutorial-Part).

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by gone-phishing** [comment]
I have the same issue, how did you fix it?

**Comment by amaitland** [comment]
Make sure your project targets `.Net 4.5.2`
