### ISSUE TITLE
Can't take screenshot of Flash Page using GDI+ when running by .exe

### ISSUE THREAD

**Issue by freshstudio** [cefsharp/CefSharp#1754]
Info:
Nuget v51
x86
Win 10
WinForms

When I'm taking screenshot of browser using GDI+ it returns me black image. But when I run my code by Visual Studio all is ok.

`public static Bitmap CaptureWindow(IntPtr handle)
        {
            IntPtr hdcSrc = User32.GetWindowDC(handle);

            RECT windowRect = new RECT();
            User32.GetWindowRect(handle, ref windowRect);

            int width = windowRect.right - windowRect.left;
            int height = windowRect.bottom - windowRect.top;

            IntPtr hdcDest = Gdi32.CreateCompatibleDC(hdcSrc);
            IntPtr hBitmap = Gdi32.CreateCompatibleBitmap(hdcSrc, width, height);

            IntPtr hOld = Gdi32.SelectObject(hdcDest, hBitmap);
            Gdi32.BitBlt(hdcDest, 0, 0, width, height, hdcSrc, 0, 0, SRCCOPY);
            Gdi32.SelectObject(hdcDest, hOld);
            Gdi32.DeleteDC(hdcDest);
            User32.ReleaseDC(handle, hdcSrc);

            Bitmap bmp = Image.FromHbitmap(hBitmap);
            Gdi32.DeleteObject(hBitmap);

            return bmp;
        }`

I'm using it that:
`Bitmap screenshot = new Bitmap(.CaptureWindow(Browser.chromiumBrowser.Handle));`

PPAPI Flash

**Comment by amaitland** [comment]
http://stackoverflow.com/questions/38619388/cant-get-screenshot-of-cefsharp-browser-when-running-by-exe
