### ISSUE TITLE
cefsharp 37 winform examples cant set referer https to http url and program crashed

### ISSUE THREAD

**Issue by boorsekala** [cefsharp/CefSharp#1755]
hi im limited to work on one of cefsharp versions that support framework4 because can run on XP,winserver2008 ... then i used cefsharp 37

bool IRequestHandler.OnBeforeResourceLoad(IWebBrowser browserControl, IRequest request, bool isMainFrame  )
        {
 headers["Referer"] ="https://google.com";
....
return false;
}
....

it not work set referer https to none https site but worked http to http
why?

if this problem solved in next .net framework 4 supported cefsharp versions tell me to i downlod that version

thanks.

**Comment by boorsekala** [comment]
i found that we cant set referer to https  for http urls due to security issue .
thanks cefsharp team,

in cefsharp 37 program crashed when we set https referer to http url.
i made some changes in RequestHansler to check if referer set to https but url is not https change it to null to prevent crash:




//cefsharp 37. not needed from cefsharp 39 and new versions
  if (this.referer != null)
            {
                if (this.referer.ToLower().Contains("https"))
                {
                    
                    if (!request.Url.ToLower().ToString().Contains("https"))
                    {
                       this.referer = null; 
                       
                    }
                }
            }

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md
