### ISSUE TITLE
getUserMedia() doesn't work and shows "Permission Denied Error"

### ISSUE THREAD

**Issue by AbdullahDibas** [cefsharp/CefSharp#1756]
- **What version of the product are you using?**
    -  CSharp 3.2623.1401.gb90a3be (Nuget) , Chromium Version : 49.0.2623.110

- **sditecture x86 or x64?**
         x86

- **On what operating system?**
    - Win7

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms

When I'm trying to get access to my webcam using getUserMedia() method its error call back method is executed showing "Permission Denied Error".  I tried to enable media stream on chromium by executing the following commands
(
                CefSettings settings = new CefSettings();
                settings.CefCommandLineArgs.Add("enable-media-stream", "1");
) 
But nothing changes. On the other hand it's working fine if I tried to navigate to my page directly from chrome.
Note: My page is installed in a server on my machine.

**Comment by amaitland** [comment]
http://stackoverflow.com/questions/34197653/getusermedia-in-chrome-47-without-using-https
