### ISSUE TITLE
Black box occupying part of the browser display

### ISSUE THREAD

**Issue by Snorvarg** [cefsharp/CefSharp#1757]
Hi,
I have followed the guide at http://www.codeproject.com/Articles/1058700/Embedding-Chrome-in-your-Csharp-App-using-CefSharp with no modifications. 
I used NuGet, so I skipped the manual steps with the dlls. 

The version string and architecture: "Chromium: 51.0.2704.103, CEF: r3.2704.1432.g60b3718, CefSharp: 51.0.0.0, Environment: x64"

I am using Visual Studio Community 2015 on Windows 10. 

It is a WinForm project.

The problem is a black box on top of the browser's area. Please see screen shot.

![blackborder](https://cloud.githubusercontent.com/assets/1905830/17220745/e8227b7e-54f0-11e6-9c37-98cd9ba269cf.png)

If I downgrade to version 45 using NuGet, the black box disappears.

**Comment by amaitland** [comment]
### How do I investigate my issue further?

It's important to remember that `CefSharp` is just a wrapper around the `Chromium Embedded Project (CEF)`, the upstream [`CEF` forum](http://magpcss.org/ceforum/) is a valuable resource. Also `CEF` has it's own [Issue Tracker](https://bitbucket.org/chromiumembedded/cef/issues). Please take the time to research your own problem, including `Googling`, searching on `ceforum`.

--
#### Finding more info
- Have you checked the `Debug.log` file? (Should be located in your apps executing folder by default)
- Have you googled the error message your seeing? (Don't just google the whole thing, try googling just the keywords and possibly add `chromium` as a keyword).
- Are you able to reproduce the problem using `cefclient`? (`cefclient` is the reference implementation provided by `CEF`)
- Need more help debugging? Check the [Troubleshooting Guide](https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting)
- Are you using the latest version? Check the [Release Branches](https://github.com/cefsharp/CefSharp#release-branches) table to determine if the version your using is supported. 

--
#### How do I download `cefclient`?

- Firstly identity which version of `CEF` your actually using, easiest way is to check your `packages.config` file, look for the `cef.redist.x86` package, it's version will be something like `3.2526.1362`, that's the exact version of `CEF` you'll need to download for comparison. You can also open `chrome://version` in the browser to determine the version.
- Open http://cefbuilds.com in a web browser
- Locate the exact `Branch` you require, for the example above the branch is `2526`, all the versions follow a similar pattern
- Locate the `Windows 32bit` or `Windows 64bit` item, if you don't see the exact version, then click `more revisions`
- Download **Test App**
- Are you using `WPF/Offscreen` or `WinForms`? 

**This next part is key**
- To compare with WPF/OffScreen run `cefclient --multi-threaded-message-loop --off-screen-rendering-enabled`
- To compare with WinForms `cefclient --multi-threaded-message-loop`

**Comment by amaitland** [comment]
Also try https://github.com/cefsharp/CefSharp.MinimalExample

**Comment by GaryFreeman** [comment]
The solution worked for me is Cef.EnableHighDPISupport() before Cef.Initialize()

**Comment by Snorvarg** [comment]
Just wanted to chime in and say that whatever has changed, has fixed the issue. I build CefSharp from source, pulling from github.

I noted that GaryFreemans proposal is at work in the CefSharp.Winforms.Example. I tried to disable the line 
`Cef.EnableHighDPISupport()`
and it still works, no black box.

The version string and architecture: 
"Chromium: 55.0.2883.59, CEF: r3.2883.1539.gd7f087e, CefSharp: 55.0.0.0, Environment: x64"

**Comment by amaitland** [comment]
> I noted that GaryFreemans proposal is at work in the CefSharp.Winforms.Example. I tried to disable the line
> Cef.EnableHighDPISupport()
> and it still works, no black box.

See https://github.com/cefsharp/CefSharp/wiki/General-Usage#high-dpi-displayssupport for more info

**Comment by AqlaSolutions** [comment]
Please include it into the quick start guide, I experienced the same issue. Why it's not enabled by default?

**Comment by mazenkt** [comment]
I had same problem, but this work for me:
Just you need to enable High DPI support "app.manifest"  file to let Windows know your app is High DPI Aware. 
Change the line:
`<dpiAware>false/PM</dpiAware>`
To 
`<dpiAware>true/PM</dpiAware>`

**Comment by bassouma21001** [comment]
For Vb.net 
CefSharp.Cef.EnableHighDPISupport()

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/wiki/General-Usage#high-dpi-displayssupport
