### ISSUE TITLE
User preferences

### ISSUE THREAD

**Issue by Gixy1** [cefsharp/CefSharp#1758]
I am having a problem with cefSharp. I would like to have a Tick box that when a use Ticks it then the browser should not execute a certain code and if the check box is unticked then the browser should run through that. In details, i want the browser to use Tor client when a user doesn't tick the box, meaning Tor would be the default proxy but if the user chooses to surf normally on the internet then the browser should skip Tor execution and start up without it.

In the meantime, every time i want to load the browser without Tor client i have to manually disable Tor in my source code by commenting out the code like this

```
public MainForm()
        {
            InitializeComponent();

            CefSettings settings = new CefSettings();

            settings.CefCommandLineArgs.Add("renderer-process-limit", "1");

            //Set proxy for Tor
            //settings.CefCommandLineArgs.Add("proxy-server", "127.0.0.1:8182");

            //Load pepper flash player 
            settings.CefCommandLineArgs.Add("ppapi-flash-path", appPath + @"PepperFlash\pepflashplayer.dll");
```
this way the browser starts without using chrome. but if i leave it like this then my browser will initiate Tor on startup

```
public MainForm()
        {
            InitializeComponent();

            CefSettings settings = new CefSettings();

            settings.CefCommandLineArgs.Add("renderer-process-limit", "1");

            //Set proxy for Tor
            settings.CefCommandLineArgs.Add("proxy-server", "127.0.0.1:8182");

            //Load pepper flash player 
            settings.CefCommandLineArgs.Add("ppapi-flash-path", appPath + @"PepperFlash\pepflashplayer.dll");
```

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md
