### ISSUE TITLE
Block geolocalization request to wait for user's response

### ISSUE THREAD

**Issue by pwhite77** [cefsharp/CefSharp#1760]
Hello everyone,
I'm implementing, in my **WinForms** CefSharp app, the **IGeolocationHandler**, as explained in the example [here](https://github.com/cefsharp/CefSharp/blob/master/CefSharp.WinForms.Example/Handlers/GeolocationHandler.cs#L12). I would like to display a custom panel to ask the user permission (the reason I don't use MessageBox is that I have to show multiple options), but I can't find a way to make the handler wait for the user response.

Creating a public event in the main form (_Home.vb_) and adding an _AddHandler_ to the handler does not help. Using **TaskCompletionSource** does not work because I can't make **OnRequestGeolocationPermission** async, and polling a public variable causes the handler to always return false.

Does everyone know a way to do it?

Thanks a lot

**Comment by rlmcneary2** [comment]
> So you have a question to ask, where can you look for answers?
> 
> Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> You can see all the CefSharp tagged issues on Stackoverflow, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> You can search the Gitter Chat Channel for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on Gitter first.
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md
