### ISSUE TITLE
App very slow to exit on Cef.ShutDown() call

### ISSUE THREAD

**Issue by SteveV0189** [cefsharp/CefSharp#1765]
- **What version of the product are you using?**
    - What version are you using? Nuget? CI Nuget? build from a branch? If so which branch?
e.g. 51.0.0

- **What architecture x86 or x64?**
x86
- **On what operating system?**
    - Win7

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms
- **What steps will reproduce the problem?**
Create Application & Exit
- **What is the expected output? What do you see instead?**
It should exit immediately, but it takes about 4-5 seconds to actually close.
- **Please provide any additional information below.**
- **Does this problem also occur in the `Cef` TestApp from http://cefbuilds.com?**
No, it doesn't. Tried with the latest branch.

**Comment by amaitland** [comment]
Try the solutions outlined in #1304

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by SteveV0189** [comment]
@amaitland 
The solution that worked was to switch from RegisterJsObject to RegisterAsyncJsObject.

**Comment by amaitland** [comment]
> The solution that worked was to switch from RegisterJsObject to RegisterAsyncJsObject.

Your bug report doesn't mention using `RegisterJsObject`????

#1304 outlines the workarounds for `RegisterJsObject`

**Comment by SteveV0189** [comment]
My apologies, I'm not good with adding every piece of relevant information. I didn't think it could contribute to the problem until I read #1304 which deals solely with RegisterJs. Thanks for your help!
