### ISSUE TITLE
Cross-window messaging

### ISSUE THREAD

**Issue by mikabuka** [cefsharp/CefSharp#1766]
Hi,
I need to develop functionality that known as inter-tab communication/cross-window messaging.

Actually, i need to open some web pages on a secondary screen and enable communication between these pages. 

I found several solutions in the web. 
Some of them are easy and elegant, but some not implemented in several browsers.
Among the suggested solutions:

1. localStore/cache long pooling
2. LocalStorage events
3. Shared web-workers
4. window.postMessage

http://stackoverflow.com/questions/19125823/how-is-it-possible-to-share-single-js-resource-between-browser-tabs/19165781#19165781

Does, this solutions will work with CefSharp container?
Thanks?

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by amaitland** [comment]
> localStore/cache long pooling
> LocalStorage events

If you use a tech that's supported by `Chromium` then it should likely work. I've never tried personally, and never heard of anyone else doing similar. You'll find something that will work I'm sure, may take some trial and error.
