### ISSUE TITLE
On the issue of opening the camera video page flashing

### ISSUE THREAD

**Issue by mayuxian** [cefsharp/CefSharp#1769]
To open the camera video camera 
I have a configuration in CefSharp.Example  as follows
**settings.CefCommandLineArgs.Add("enable-media-stream", "1");**

But he has a strange phenomenon.
I own a Demo page, the page has been flashing. And CefSharp.Wpf.Example runs without this phenomenon. I have a lot of reasons for the investigation of the investigation, and did not find the reason. Trouble you test, if there is such a phenomenon, if not, can give some advice, which will affect this?

**Comment by amaitland** [comment]
Know issue, see the release notes for information.  In future ask questions on Gitter as per the issue template.

**Comment by mayuxian** [comment]
Ok，Thanks
