### ISSUE TITLE
Properly clean browser subprocess

### ISSUE THREAD

**Issue by EdRbt** [cefsharp/CefSharp#1773]
Hi, we are using CefSharp v51 in a WPF application.
I would like to know if there is a good way to clean browser subprocess.
Right now, we dispose the browser in the view's Unloaded event.
I don't think it's the right way to do it, indeed we face some problems when we switch display to a previous view. The browser is null and not reloaded, thus we can't use it.
Does anyone has a clue on this ? I've searched through closed issues, wiki, etc, but couldn't find any answer.

Thank you.

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by amaitland** [comment]
> I don't think it's the right way to do it, indeed we face some problems when we switch display to a previous view. The browser is null and not reloaded, thus we can't use it.

Any solution would be specific to whatever framework your using. Best if you seek guidance from someone familiar with that particular framework.
