### ISSUE TITLE
Zooming Reset Problem

### ISSUE THREAD

**Issue by Saravanan04** [cefsharp/CefSharp#1778]
# 

Zooming Reset Problem

**Version :** 45.0.0
**Architecture :** x86
**Operating System :** Win 8
**Platform :** WPF

**Problem :** 
**Step 1 :** Extract the attached sample project and add the cefshrap wpf 45.0.0 package.
**Step 2 :** Run the project.
**Step 3 :** Right click and Click the Zoom In Browser 1. It's automatically Zoom In on Browser 2.
**Step 4 :** Click the Browser 2 tab and right click. Select Reset. The Browser not reset. If I go to the Browser 1 and click the reset option. It's reset both the browser.

**Expected Output:**
If I Zoom In the Browser 1, The Browser 2 also Zoom In. It's Fine.
If I Reset the Browser 2 The both Browser need to be reset.
And also I have added the Mouse Wheel with Ctrl button Zoom In. It's working fine. But when Zoom In or Out the Scrollbar also moving. The Zoom In and Zoom out only working when we focused the browser not working on mouse over.

**Comment by amaitland** [comment]
Version '45.0.0' is outdated and no longer supported, please attempt to reproduce the problem in the latest release. Also no zip files.

**Comment by Saravanan04** [comment]
Hi,

We are using the version '45.0.0' only. Can you please provide support for this version. And How can I attached the sample project?

**Comment by amaitland** [comment]
> We are using the version '45.0.0' only. Can you please provide support for this version.

Only version `51.0.0` is supported. The source is there of course, so you can resolve the problem yourself.

> And How can I attached the sample project?

Are you able to reproduce the problem with `51.0.0`? If not then a sample is moot.

**Comment by Saravanan04** [comment]
Yes, I can reproduce this issue with version 51.0.0.

**Comment by Saravanan04** [comment]
Do have any workaround solution for this fix?

**Comment by amaitland** [comment]
> Do have any workaround solution for this fix?

Best if you ask on http://magpcss.org/ceforum/viewforum.php?f=6

**Comment by amaitland** [comment]
Looks like it's a bug in `CefSharp`, the property changed handler doesn't fire as `ZoomLevel` is already `0`.  You can call `SetZoomLevel` directly on the `IBrowserHost`, search through the source for an example. 

I don't have time to look into this further, someone else will need to contribute a fix.

**Comment by kthsu** [comment]
Not reproducible in CefSharp 55.

**Comment by merceyz** [comment]
Related to the issue:

1. Load two tabs on the same domain
2. Zoom in more than one time in Tab 1, Tab 2 will also be zoomed in (Expected)
3. Switch to tab 2 and zoom in and it will zoom out to 0,1
