### ISSUE TITLE
CefSettings Duplicate Args exception

### ISSUE THREAD

**Issue by arvigeus** [cefsharp/CefSharp#1780]
`settings.SetOffScreenRenderingBestPerformanceArgs();`
`settings.EnableInternalPdfViewerOffScreen();`

Exception:
`An item with the same key has already been added.`

**Comment by amaitland** [comment]
Look at the source, apply the relevant settings manually if you so choose, those are just helper methods.

**Comment by arvigeus** [comment]
The example is for demonstration purposes only. CefSettings should silently handle this case, instead of throwing an exeption.

**Comment by amaitland** [comment]
> Apparently it tries to add same parameter twice. CefSettings should silently handle this case, instead of throwing an exception.

@arvigeus Your welcome to submit a `PR` with your proposed changes.
