### ISSUE TITLE
How to disable gpu Cef Sharp.wpf Issue with windows 10

### ISSUE THREAD

**Issue by nextolive2016** [cefsharp/CefSharp#1781]
I  have downloaded CefSharp.Wpf 49.0.1 directly from  the nuget and using ChromiumWebBrowser. Please explain how to disable gpu from application. Please suggest, we are facing lots of problem and upset how to  fix this problem.
thanks

**Comment by rlmcneary2** [comment]
@nextolive2016 - issues are for bug reports only; please ask questions on Gitter. Look at the Trouble Shooting section of the Wiki, GPU solutions are there.

**Comment by nextolive2016** [comment]
are you able to provide solution in simple way.

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md
