### ISSUE TITLE
Back Spece key issue with  cef sharp. wpf dll

### ISSUE THREAD

**Issue by nextolive2016** [cefsharp/CefSharp#1783]
<wpf:ChromiumWebBrowser Name="ChromiumWebBrowser1" Address="google.com"></wpf:ChromiumWebBrowser>
We are using modern ui in my project so when we press backspace key in side the ChromiumWebBrowser  then its sending on previous user control of the application. Can I fix this?

thanks

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by amaitland** [comment]
@nextolive2016 Read the issue template, this is not the appropriate forum for asking questions, bug reports only!!!
