### ISSUE TITLE
Make it working with .NET 4.5?

### ISSUE THREAD

**Issue by UweKeim** [cefsharp/CefSharp#1784]
I'm intentionally using .NET 4.5 in my application.

When adding CefSharp it suceeds, but when compiling, a warning occurs:

> The primary reference "CefSharp.WinForms" could not be resolved because it has an indirect dependency on the assembly "CefSharp.Core, Version=51.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138" which was built against the ".NETFramework,Version=v4.5.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5".

**My question:**

Any chance, to get CefSharp working with .NET 4.5 without forcing my some thousand users to upgrade to .NET 4.5.2?

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by amaitland** [comment]
> Any chance, to get CefSharp working with .NET 4.5 without forcing my some thousand users to upgrade to .NET 4.5.2?

Version `49` supports `.Net 4.0`.

`.Net 4.5.2` is the lowest version currently supported by `Microsoft`. You should really be getting your users to upgrade.

**Comment by UweKeim** [comment]
OK, I'll update.

In my opinion, it would still be good to prevent installing the NuGet package in the first place, instead of allowing to install and then fail later during runtime/compile time.

**Comment by amaitland** [comment]
> In my opinion, it would still be good to prevent installing the NuGet package in the first place, instead of allowing to install and then fail later during runtime/compile time.

Sounds like a reasonable suggestion. How exactly is the question? There is no `Minimum .Net` version tag that you can set in the `nuspec` file that I'm aware of.

**Comment by UweKeim** [comment]
In my own packages Im using e.g. `net40-full` or `netstandard1.6`.

According to [this page](http://blog.stephencleary.com/2012/05/framework-profiles-in-net.html) I guess you could give `net452` a try.

**Comment by amaitland** [comment]
> In my own packages Im using e.g. net40-full or netstandard1.6.

Which package is that?

> According to this page (and maybe this page) I guess you could give net452 a try.

We have both `x64` and `x86` versions to include here, something `Nuget` doesn't support particularly well in a single package.

**Comment by amaitland** [comment]
`Pull Requests` are welcome :+1:
