### ISSUE TITLE
unable to render the browser

### ISSUE THREAD

**Issue by kagami3287** [cefsharp/CefSharp#1787]
- Following is my code when the main window in the WPF is loaded.

private void chrome_initialized(object sender, RoutedEventArgs e)
        {
            CefSettings settings = new CefSettings();
            if (Cef.Initialize(settings))
            {
                URL.Text = "https://google.com";
                chrome = new ChromiumWebBrowser();
                chrome.Address = "https://google.com";
                this.browser.Children.Add(chrome);              
            }
 }

But the page data is not getting loaded. Being a newbie I don't even have any experience with cefsharp either. I think it must be a very small issue. please help me out.

the browser object in the "this.browser.children.add(chrome)" is a dockpanel object.
![problem](https://cloud.githubusercontent.com/assets/21317704/18063436/e7a79380-6e65-11e6-9d7f-8f8836c70c71.png)

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp.MinimalExample for a working example.

**Comment by kagami3287** [comment]
Thanks for the Help!!! I some have managed to finish what i wanted to do. But now the problem is with the browser itself. The view looks very bad, as in it keeps displaying black screen very frequently. I am thinking it has something to do with loading the data on the page. any help is appreciated.

**Comment by amaitland** [comment]
> The view looks very bad, as in it keeps displaying black screen very frequently. I am thinking it has something to do with loading the data on the page. any help is appreciated.

See the release notes. Further questions ask on `Gitter` as per above.
