### ISSUE TITLE
How can I get the cookie of a single request?

### ISSUE THREAD

**Issue by leavesgreen** [cefsharp/CefSharp#1794]
Hi All ,

I try use a background webrequest instead of the ajax request in the cefsharp browser, when I use firefox, I can see the whole request to a json url, and can get the request cookie, I copy the cookie to curl , and it works well.

but in cefsharp , first I try to use the requestHandler, but there are no cookie the request header; then I try the CookieVisitor as the document said, but the cookie looks like the cookie of the whole website, not for the json url. and it can not work.

the ajax json url also can not be catched in wb_FrameLoadEnd, so I don't know how to use the VisitUrlCookies() function , even don't know if it works.

so , in my opinion,  cefsharp works well when just use as a browser, that mean in an ajax request to a json url, it do handled the cookie of this request. but looks we can not get the cookie of this request.

any help, thanks you all

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md
