### ISSUE TITLE
Configuring Auth Delegate Whitelist not working

### ISSUE THREAD

**Issue by JordanSinko** [cefsharp/CefSharp#1802]
I am trying start CefSharp with command line arguments to enable Kerberos delegate authentication. I have ran it with chrome and it works, but doesn't when running for CefSharp 39.0.2. Below is my code:

```
CefSettings settings = new CefSettings();
settings.CefCommandLineArgs.Add("auth-server-whitelist", "*");
settings.CefCommandLineArgs.Add("auth-negotiate-delegate-whitelist", "*");
CefSharp.Cef.Initialize(settings);
_browser = new ChromiumWebBrowser("http://mywebsite.intranet.local");
this.Controls.Add(_browser);
```

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by amaitland** [comment]
You should search http://www.magpcss.org/ceforum/index.php and the CEF issue tracker.
