### ISSUE TITLE
WinForms HiDpi Displayed Incorrectly

### ISSUE THREAD

**Issue by pieterdhondt** [cefsharp/CefSharp#1803]
When running the minimal WinForms project I have this issue:

![cefsharpissue](https://cloud.githubusercontent.com/assets/213126/18651718/56467534-7e8a-11e6-917e-d731afb25f32.png)

Only disabling the gpu `settings.CefCommandLineArgs.Add("disable-gpu", "1");` helps, but I can't do this because there is WebGl content that I want to display.

Interesting to note is that in version 43.0.0 this displays correctly.

- **What version of the product are you using?**
    - Every version above 43.0.1

- **What architecture x86 or x64?** x64

- **On what operating system?**
    - Win10

- **System Information**
    - Dell Precision 5510, nVidia Quadro M1000M driver version 369.09, Win10, hi-res display 3840x2160

- **Are you using `WinForms`, `WPF` or `OffScreen`?** WinForms (WPF works, but my application is WinForms)

- **What steps will reproduce the problem?**
    - Using the [MinimalExample] and the WinForms project. 

- **Does this problem also occur in the `Cef` TestApp from http://opensource.spotify.com/cefbuilds/index.html (http://cefbuilds.com for older version)?**
 no, there it displays normally

**Comment by amaitland** [comment]
Have you tried building `master`? Have you Searched github for high DPI issues?

https://github.com/cefsharp/CefSharp/blob/cefsharp/53/CefSharp.WinForms.Example/Program.cs#L47
https://github.com/cefsharp/CefSharp/blob/cefsharp/53/CefSharp.WinForms.Example/app.manifest#L39

If that doesn't work you'll have to dissect cefclient to see what it's doing differently.

**Comment by amaitland** [comment]
> Every version above 43.0.1

If the problem was limited to the latest release then I'd be more inclined to think this was an actual issue. I'm guessing it's likely an environmental/configuration issue at this point.

I've updated the `MinimalExample` see https://github.com/cefsharp/CefSharp.MinimalExample/commit/21f8a90d605238fb9ddf54080e11a737158c287c I haven't tested this yet, just applied the same changes that were made to the other example.

**Comment by pieterdhondt** [comment]
Thanks @amaitland , adding these changes solved the issues I had!

**Comment by jsh-ec** [comment]
I have the same issue.  Build and run a minimal example with Display Settings scaling on Windows 10 set to 100%, all works fine.  Change the scaling to 150% and the display portion of the browser does not fill the window and the remaining area is set to black.  Disable-gpu and all works fine????

**Comment by twofishsoftware** [comment]
I can confirm that @amaitland 's suggestion work for me.  Seems the relevant change is:
```
//For Windows 7 and above, best to include relevant app.manifest entries as well
Cef.EnableHighDPISupport();

//Perform dependency check to make sure all relevant resources are in our output directory.
Cef.Initialize(new CefSettings(), shutdownOnProcessExit:false, performDependencyCheck:true);
```

**Comment by Et3rnal** [comment]
This issue exists on AnyCPU and applying these configurations doesn't solve it

The only work around I found so far is disabling the gpu
settings.CefCommandLineArgs.Add("disable-gpu", "1");
 
Any hints??

**Comment by didimitrie** [comment]
> The only work around I found so far is disabling the gpu
settings.CefCommandLineArgs.Add("disable-gpu", "1");

Thanks for this, was having similar issues. Still not really sure how to make it work (i'm actually using cef pure).

**Comment by danielehrhardt** [comment]
Did someone fixed it?

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/wiki/General-Usage#high-dpi-displayssupport

**Comment by d4nnoyer** [comment]
> 
> 
> This issue exists on AnyCPU and applying these configurations doesn't solve it
> 
> The only work around I found so far is disabling the gpu
> settings.CefCommandLineArgs.Add("disable-gpu", "1");
> 
> Any hints??

Thank you, it helps! 
Unfortunately, Cef.EnableHighDPISupport(); also worked, but ruined layout of all other controls and displayed all text inside them in my WinForm project.

**Comment by amaitland** [comment]
@d4nnoyer See https://github.com/cefsharp/CefSharp/wiki/General-Usage#high-dpi-additional-info

**Comment by davidei1955** [comment]
FWIW, I am seeing this issue in .Net 8.0 Core Winforms on Windows 10 when the display is set to 125% (but not when set to 100%). I don't see it at all on Windows 11. The fix for me was to delete app.manifest, then recreate it in Visual Studio, and uncomment  the

   <application xmlns="urn:schemas-microsoft-com:asm.v3">
       <windowsSettings>
         <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</dpiAware>
        <longPathAware xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">true</longPathAware>
      </windowsSettings>
   </application>

section in the new app.manifest.

**Comment by amaitland** [comment]
This issue is **very old** and the information contained within is largely out of date.

Refer to #2927 instead.
