### ISSUE TITLE
Cefsharp (using WPF)  in Windows 10  have some functions disabled(errors).

### ISSUE THREAD

**Issue by ryu8888** [cefsharp/CefSharp#1804]
We go to web pages use certain Cefsharp component features failures in Windows 10 , but Windows 10 open Chrome directly in the browser the page function is normal.
If you not busy , please try to confirm this requests , thanks a lot.

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md
