### ISSUE TITLE
wired tryancle under all cefsharp after instaling it from nuget

### ISSUE THREAD

**Issue by kessanro** [cefsharp/CefSharp#1805]
i found a yellow tryangle after adding cefsharp on all like .core from nuget
what does it mean and any fixes

**Comment by kessanro** [comment]
fixed it

**Comment by amaitland** [comment]
Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md
