### ISSUE TITLE
IO.Exception when trying to access generated PDF file immediately after Task completes

### ISSUE THREAD

**Issue by santiagoIT** [cefsharp/CefSharp#1807]
Nuget v51.0.0
Win 10 x64
Problem occurs with both the Wpf and Offscreen  ChromiumWebBrowser's.

I use ChromiumWebBrowser to generate PDF files from Html.
However, if I try to access the PDF file directly after the PrintToPDF Task has completed I get the following exception:

{"The process cannot access the file '..\testPDF.pdf' because it is being used by another process."}

This is the simple code to reproduce the problem:
```
private async void GeneratePdf()
    {
      var path = Path.GetDirectoryName(System.Reflection.Assembly.GetEntryAssembly().Location);
      var generatedPdfFile = Path.Combine(path, @"testPDF.pdf");

      var chromeSettings = new PdfPrintSettings();
      var htmlFile = Path.Combine(path, @"Html2\Hacker News.html");
      using(var chromium = GetOffsceenChromium(htmlFile))
      {
        var pdfFileSaved = await chromium.PrintToPdfAsync(generatedPdfFile, chromeSettings);
        if (pdfFileSaved)
        {
          //Thread.Sleep(10);  // <-- uncomment this line and no exception happens
          using (var testStream = new FileStream(generatedPdfFile, FileMode.Open))
          {
             // access the file for read --> exception is thrown. PDF file is still in use by Chromium.
          }
        }
      }
    }
```
It seems to me that the Task<bool> returned by PrintToPDFAsync completes before the generated pdf file is closed/finished processing.

Thank you!!!

**Comment by amaitland** [comment]
> // access the file for read --> exception is thrown. PDF file is still in use by Chromium.

This is the important part to remember here is **Chromium**. `CefSharp` is just a really simple wrapper around `CEF` for the most part. You can investigate further my implement `IPrintToPdfCallback` and use the the `PrintToPdf` method. Look at the source `TaskPrintToPdfCallback` is just a simple class that provides a `Task` wrapper and implements `IPrintToPdfCallback`.

**Comment by santiagoIT** [comment]
I changed the code to use a custom callback class:
```
private void GeneratePdfVersion2()
    {
      var path = Path.GetDirectoryName(System.Reflection.Assembly.GetEntryAssembly().Location);
      var generatedPdfFile = Path.Combine(path, @"testPDF.pdf");

      var chromeSettings = new PdfPrintSettings();
      var htmlFile = Path.Combine(path, @"Html2\Hacker News.html");
      using (var chromium = GetOffsceenChromium(htmlFile))
      {
        var callback = new TestPrintToPdfCallback();
        chromium.GetBrowser().GetHost().PrintToPdf(generatedPdfFile, chromeSettings, callback);
      }
    }
```

Callback-Class:
```
  class TestPrintToPdfCallback : IPrintToPdfCallback
  {
    public void OnPdfPrintFinished(string path, bool ok)
    {
      if (ok)
      {
        using (var testStream = new FileStream(path, FileMode.Open))
        {
        }
      }
    }

    public void Dispose()
    {
    }
  }
```

Using this code the PDF file is not generated. In OnPdfPrintFinished method, the 'ok' argument is set to false.
Any idea what might be wrong?

**Comment by amaitland** [comment]
> Using this code the PDF file is not generated. In OnPdfPrintFinished method, the 'ok' argument is set to false.
> Any idea what might be wrong?

No idea, you can debug the source to see how the current implementation works. Be careful executing `IO` intensive code on `OnPdfPrintFinished`, it's run on a `CEF` thread and can potentially cause your application issues if you block.

**Comment by santiagoIT** [comment]
OK I figured out what was wrong with the GeneratePdfVersion2. 'chromium' variable was Disposed before the PDF file was generated.
Fixed that, and then the PDF file is generated. However exception still ocurss when trying to access the file for read.
So it seems to be a Chromium issue?
I barely know CEF...

**Comment by amaitland** [comment]
> Fixed that, and then the PDF file is generated. However exception still ocurss when trying to access the file for read.

My point is that `CefSharp` has no control over when the file lock is released.  Check if you access the file in `Dispose`, if not then you'll need to discuss your issue in the context of the `CEF` project.

**Comment by santiagoIT** [comment]
If the file is accessed in Dispose no exception is thrown. :-)
I understand your point.
Do you agree however that this is an CEF problem? Meaning that the file lock should be released prior to CEF setting the printToPdf Task as complete?
If so then maybe its worth to make CEF aware of the issue. (I can do this, but in the context of CefSharp).

**Comment by amaitland** [comment]
> If the file is accessed in Dispose no exception is thrown. :-)

Great :+1: 

> Do you agree however that this is an CEF problem? Meaning that the file lock should be released prior to CEF setting the printToPdf Task as complete?

It makes sense the file lock would be released when the callback is executed. In the context of `CEF`, it's when `CefPdfPrintCallback::OnPdfPrintFinished` is executed, `Task` is not relevant.

http://magpcss.org/ceforum/apidocs3/projects/(default)/CefPdfPrintCallback.html

Doesn't hurt to ask on http://magpcss.org/ceforum/index.php see if what your seeing is expected behavior.

**Comment by santiagoIT** [comment]
I've asked the question. :-)
[http://magpcss.org/ceforum/viewtopic.php?f=6&t=14534&p=32383#p32383](http://magpcss.org/ceforum/viewtopic.php?f=6&t=14534&p=32383#p32383)

**Comment by amaitland** [comment]
> I've asked the question. :-)

Great 👍 Anyone interested in this should continue the discussion on `ceforum` as the issue needs to be resolved in `CEF`.
