### ISSUE TITLE
Incorrect margin values

### ISSUE THREAD

**Issue by arvigeus** [cefsharp/CefSharp#1808]
```cs
var settings = new PdfPrintSettings()
{
    BackgroundsEnabled = true,
    MarginType = CefPdfPrintMarginType.Custom,
    MarginTop = 20,
    MarginRight = 20,
    MarginBottom = 20,
    MarginLeft = 20
};
```

Result: [PDF opened with GIMP](http://s12.postimg.org/4ayr3x3lp/Capture.png) - 6.9mm

**Comment by amaitland** [comment]
### How do I investigate my issue further?

It's important to remember that `CefSharp` is just a wrapper around the `Chromium Embedded Project (CEF)`, the upstream [`CEF` forum](http://magpcss.org/ceforum/) is a valuable resource. Also `CEF` has it's own [Issue Tracker](https://bitbucket.org/chromiumembedded/cef/issues). Please take the time to research your own problem, including `Googling`, searching on `ceforum`, etc.

--
#### Finding more info
- Have you checked the `Debug.log` file? (Should be located in your apps executing folder by default)
- Have you googled the error message your seeing? (Don't just google the whole thing, try googling just the keywords and possibly add `chromium` as a keyword).
- Are you able to reproduce the problem using `cefclient`? (`cefclient` is the reference implementation provided by `CEF`)
- Need more help debugging? Check the [Troubleshooting Guide](https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting)
- Are you using the latest version? Check the [Release Branches](https://github.com/cefsharp/CefSharp#release-branches) table to determine if the version your using is supported. 

--
#### How do I download `cefclient`?

- Firstly identity which version of `CEF` your actually using, easiest way is to check your `packages.config` file, look for the `cef.redist.x86` package, it's version will be something like `3.2526.1362`, that's the exact version of `CEF` you'll need to download for comparison. You can also open `chrome://version` in the browser to determine the version.
- Open http://opensource.spotify.com/cefbuilds/index.html (http://cefbuilds.com for older version) in a web browser
- Locate the exact `Branch` you require, for the example above the branch is `2526`, all the versions follow a similar pattern
- Locate the `Windows 32bit` or `Windows 64bit` item, if you don't see the exact version, then click `more revisions`
- Download **Test App**
- Are you using `WPF/Offscreen` or `WinForms`? 

**This next part is key**
- To compare with WPF/OffScreen run `cefclient --multi-threaded-message-loop --off-screen-rendering-enabled`
- To compare with WinForms `cefclient --multi-threaded-message-loop`

**Comment by amaitland** [comment]
@arvigeus Needs to be fixed in `CEF`.
