### ISSUE TITLE
Rendering issue with CEFSharp Browser control - Shows cached page randomly 

### ISSUE THREAD

**Issue by dongawli** [cefsharp/CefSharp#1809]
I am using the CEF Sharp library in my WPF project since long time (v1.25.7). 
On one of the client machine, I am facing issue that CEFSharp browser shows the random page in between continuously. Please see the video for same - https://hub.mangoapps.com/sf/NzMwNzlfMTE2OTA0MA.

This is happening only on one machine. Once application exit and relaunched, its work perfectly. 
I've checked and added debug logs as well to check whether page is getting load or not. But no load, PropertyChanged method get called continuously. 

Thank you!!!

**Comment by amaitland** [comment]
### How do I investigate my issue further?

It's important to remember that `CefSharp` is just a wrapper around the `Chromium Embedded Project (CEF)`, the upstream [`CEF` forum](http://magpcss.org/ceforum/) is a valuable resource. Also `CEF` has it's own [Issue Tracker](https://bitbucket.org/chromiumembedded/cef/issues). Please take the time to research your own problem, including `Googling`, searching on `ceforum`, etc.

--
#### Finding more info
- Have you checked the `Debug.log` file? (Should be located in your apps executing folder by default)
- Have you googled the error message your seeing? (Don't just google the whole thing, try googling just the keywords and possibly add `chromium` as a keyword).
- Are you able to reproduce the problem using `cefclient`? (`cefclient` is the reference implementation provided by `CEF`)
- Need more help debugging? Check the [Troubleshooting Guide](https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting)
- Are you using the latest version? Check the [Release Branches](https://github.com/cefsharp/CefSharp#release-branches) table to determine if the version your using is supported. 

--
#### How do I download `cefclient`?

- Firstly identity which version of `CEF` your actually using, easiest way is to check your `packages.config` file, look for the `cef.redist.x86` package, it's version will be something like `3.2526.1362`, that's the exact version of `CEF` you'll need to download for comparison. You can also open `chrome://version` in the browser to determine the version.
- Open http://opensource.spotify.com/cefbuilds/index.html (http://cefbuilds.com for older version) in a web browser
- Locate the exact `Branch` you require, for the example above the branch is `2526`, all the versions follow a similar pattern
- Locate the `Windows 32bit` or `Windows 64bit` item, if you don't see the exact version, then click `more revisions`
- Download **Test App**
- Are you using `WPF/Offscreen` or `WinForms`? 

**This next part is key**
- To compare with WPF/OffScreen run `cefclient --multi-threaded-message-loop --off-screen-rendering-enabled`
- To compare with WinForms `cefclient --multi-threaded-message-loop`

**Comment by amaitland** [comment]
> I am using the CEF Sharp library in my WPF project since long time (v1.25.7).

@dongawli That version hasn't been supported in years. Latest supported version is `51.0.0`. If you can reproduce the problem you'll need to report it to the `CEF` project.
