### ISSUE TITLE
homepage only loads every seccond time

### ISSUE THREAD

**Issue by kraeppy** [cefsharp/CefSharp#1810]
hello,
my problem is that this page 'www.bdew.de' is correctly rendered every seccond time. the nok-file shows the debug text when the page could not be loaded, the ok file shows the debug text when page could be loaded.

that's how it looks like when it's not correct.
![incomplete_page](https://cloud.githubusercontent.com/assets/13005173/18785686/e52eabce-8199-11e6-9a82-a4d2142500d3.png)

my app automates home page accesses based on configurations (page load and elementinvoke (identify element, perform click and so on). the browser-form containing the browser is initialized in gui thread. the configs are processed in a seperate thread. 

i'm using:
cefsharpversion: 51.0.0.0
cefversion: r3.2704.1432.g60b3718
chromiumversion: 51.0.2704.103
x64 
win7
winforms 

![nok](https://cloud.githubusercontent.com/assets/13005173/18785601/6651ce6c-8199-11e6-8368-e818c35b5b1f.png)
![ok](https://cloud.githubusercontent.com/assets/13005173/18785602/66938dd4-8199-11e6-83dc-8b569bd7ac89.png)

i don't know if my code is helpul. if so, please let me know and i'll post it.

best regards
kraeppy

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by amaitland** [comment]
It's important to note that `CefSharp` is just a wrapper around the `Chromium Embedded Framework (CEF)`. Please use http://magpcss.org/ceforum/index.php for generic **CEF** questions. It is best place for this kind of question. Please search before asking your question, it's highly likely your question has already been answered.
