### ISSUE TITLE
WPF: "http://localhost" redirecting to "data:text/html,chromewebdata"

### ISSUE THREAD

**Issue by Splinti** [cefsharp/CefSharp#1812]
Hello,

yesterday I started to program a WPF application with the CefSharp browser component. Everything worked perfectly as expected but since today the http://localhost redirects me to "data:text/html,chromewebdata" for some reason, without changing something on the code. I first thought it would be the version (Changed from 51.0.0 to 53.0.0-pre01 because of the GPU bug) but I reinstalled the 51.0.0 and it didn't change.

FYI: I am just using
```
browser.Address = "http://localhost"
```
to change the address but also redirecting from another site does nothing else.

Thanks for any help

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by amaitland** [comment]
Look in the Debug.log file that should be in your executing folder.  Make sure your website loads in a different browser also.
