### ISSUE TITLE
different proxy

### ISSUE THREAD

**Issue by AgapovAlexsey** [cefsharp/CefSharp#1813]
Hi. How i can use different proxy for different instances class ChromiumWebBrowser?
I set proxy as shown below:
```c#  
 Cef.UIThreadTaskFactory.StartNew(delegate {
      var rc = chromeBrowser.GetBrowser().GetHost().RequestContext;
      var v = new Dictionary<string, object>();
      v["mode"] = "fixed_servers";
      v["server"] = "socks5://127.0.0.1:9190";
      string error;
      bool success = rc.SetPreference("proxy", v, out error);                
    });      
 ```   
But it changed proxy for all instances ChromiumWebBrowser.

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by amaitland** [comment]
Search on Gitter, topic has been covered a few times. Next time please take the time to read the issue template.

**Comment by amaitland** [comment]
For reference here is an updated example in the context of `WPF` for `SetPreference` on a newly created `RequestContext`, same concept applies for `WinForms`, just create and assign your `RequestContext` then set your preferences on the `CEF UI` thread.

https://github.com/cefsharp/CefSharp/commit/b3a236902b03c8ba9329e28b4f552f0313854edd#diff-670f0330cbeb12f911a2f6f4af481dc2L44

More info related to setting proxies is at http://stackoverflow.com/questions/36095566/cefsharp-3-set-proxy-at-runtime

> If you set the proxy settings through Cef.Initialize, aka command line argument, you won't be able to change them using SetPreference, they'll be fixed. You have to only set them through SetPreference

Additional note for anyone else.

**Comment by DianaArquillos** [comment]
I have this configuration for the browser, but I am getting a blank page in every request:
 _browser = new ChromiumWebBrowser(url, browserSettings, requestContext);
                if (proxyInf != null && proxyInf.url != null)
                    isProxy = true;
                _browser.RequestHandler = new RequestHandler(userAgent, url, isProxy, proxyInf);

                Cef.UIThreadTaskFactory.StartNew(delegate
                {

                    var rc = _browser.GetBrowser().GetHost().RequestContext;
                    var dict = new Dictionary<string, object>();
                    dict.Add("mode", "fixed_servers");
                    dict.Add("server", proxyInf.url);
                    string error;
                    bool success = rc.SetPreference("proxy", dict, out error);
                    
                });
 if I go through a proxy, this proxy needs authentication and I notice I never get into the method of the credential. IRequestHandler.GetAuthCredentials(IWebBrowser browserControl, IBrowser browser, IFrame frame, bool isProxy, string host, int port, string realm, string scheme, IAuthCallback callback)
Any ideas what I have missed?
Thanks

**Comment by ToxaDev** [comment]
> I have this configuration for the browser, but I am getting a blank page in every request:
> 
> ```
> _browser = new ChromiumWebBrowser(url, browserSettings, requestContext);
> if (proxyInf != null && proxyInf.url != null)
>     isProxy = true;
> _browser.RequestHandler = new RequestHandler(userAgent, url, isProxy, proxyInf);
> 
> Cef.UIThreadTaskFactory.StartNew(delegate
> {
> 
>     var rc = _browser.GetBrowser().GetHost().RequestContext;
>     var dict = new Dictionary<string, object>();
>     dict.Add("mode", "fixed_servers");
>     dict.Add("server", proxyInf.url);
>     string error;
>     bool success = rc.SetPreference("proxy", dict, out error);
>     
> });
> ```
> 
> if I go through a proxy, this proxy needs authentication and I notice I never get into the method of the credential.
> `IRequestHandler.GetAuthCredentials(IWebBrowser browserControl, IBrowser browser, IFrame frame, bool isProxy, string host, int port, string realm, string scheme, IAuthCallback callback)`
> Any ideas what I have missed?
> Thanks

I solved this problem like this:
`Task.Factory.StartNew(() =>
            {
                **do
                {
                    Thread.Sleep(100);
                } while (!browser.IsBrowserInitialized);**
 
                Cef.UIThreadTaskFactory.StartNew(delegate
                {
                    var rc = browser.GetBrowser().GetHost().RequestContext;
                    var v = new Dictionary<string, object>();

                    v["mode"] = "fixed_servers";
                    v["server"] = info.ProxySettings.Domain + ":" + info.ProxySettings.Port;

                    string error;
                    bool success = rc.SetPreference("proxy", v, out error);
                });

                browser.Load("myip.ru");
            });`

**Comment by amaitland** [comment]
The browser provides an initialized event,  the WinForms/WPF/OffScreen implementation slightly differs, the relevant docs are.

http://cefsharp.github.io/api/75.1.x/html/E_CefSharp_Wpf_ChromiumWebBrowser_IsBrowserInitializedChanged.htm
http://cefsharp.github.io/api/75.1.x/html/E_CefSharp_OffScreen_ChromiumWebBrowser_BrowserInitialized.htm
http://cefsharp.github.io/api/75.1.x/html/E_CefSharp_WinForms_ChromiumWebBrowser_IsBrowserInitializedChanged.htm

If you have multiple browsers that share the RequestContext then using http://cefsharp.github.io/api/75.1.x/html/M_CefSharp_IRequestContextHandler_OnRequestContextInitialized.htm is the option I'd recommend. See https://github.com/cefsharp/CefSharp/blob/cefsharp/75/CefSharp.Wpf.Example/Handlers/RequestContextHandler.cs#L24 for an example. 

You will have to create a new RequestContext instance to use this method.

SetPreference must be called on the UI thread and only after the RequestContext has been initialized. The browser initialized events are guaranteed to be called after the RequestContext has been initialized. 

If you set the proxy via the command line then you will be unable to modify it using SetPreference. 

Further questions please use one of the support options listed at https://github.com/cefsharp/CefSharp#contact

**Comment by amaitland** [comment]
See also https://github.com/cefsharp/CefSharp/wiki/General-Usage#request-context-browser-isolation
