### ISSUE TITLE
How to pass the result to web page

### ISSUE THREAD

**Issue by DhivyaLakshmiG** [cefsharp/CefSharp#1815]
I have loaded the URL in cef browser initially.
Example:
m_chromeBrowser = new ChromiumWebBrowser("http://TesingPortal/");

When i move to another page in that URL, i need to access the AJAX request in c# code and return the AJAX result back to that website.
Example, I have button and text box in that page, when that button is clicked, i need to pass the result to text box in that page.

Can you please suggest how to do this?

Thanks.

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by amaitland** [comment]
Read the FAQ in particular.
