### ISSUE TITLE
Browser doesn't get updated instantly and disrupts the screen shot

### ISSUE THREAD

**Issue by sadanand8005** [cefsharp/CefSharp#1816]
We are using CEFSharp.OffScreen for drawing few charts using d3, as soon as the charts are drawn we are trying to take a screen shot using ChromiumWebBrowser.ScreenshotOrNull() method.

However we are not getting the appropriate images i.e. the charts are not drawn even though the JavaScript and HTML DOM suggest that they have been loaded and visible. 

We tried many ways few of them are 

1. Delaying ; we try to take a screen shot after some amount of time (usually around 150 ms). However this doesn't guarantee that screen shot will be as expected. Approximately 1/8 times the screen shots are incorrect. Increasing the delay decreases the error rate however it increases the total time as well which is not tolerable.

2. Subscribe to NewScreenshot event and take screen when the events are no longer happening for a period of time (around 150 ms). In other words have time which will reset on each event; and when the even is not longer triggered then the timer takes the screen shot.

3. Invalidating the current screen shot forcing it to redraw, and then take a screen shot.

None of them seem to work as expected.

I would be pleased to know any solution or a workaround.

This issue is similar to #1209 however there isn't any solution on that thread and the issue has been close hence I am creating a new one.

Edit: Let me know if a working example is needed.

**Comment by amaitland** [comment]
@sadanand8005 Rendering is indeterminate, it's a web browser after all and not really geared for taking screen shots. The solution I've had success with is lowering the frame rate, like `< 10`, hook the rendering event and ignore an arbitrary number of frames. If this solution doesn't work for you then you probably need to investigate a different framework non `CEF` based framework.

See the source example for lowering frame rate.

**Comment by amaitland** [comment]
@sadanand8005 Any further comment before closing?

**Comment by sadanand8005** [comment]
@amaitland I did tried keep the framerate low and ignore few frames, however it didn't solve the issue. Since you said the rendering is indeterminate there may not be a clear solution for this. Now I am waiting for a longer period before taking the screenshot and it looks good for now. I will let you know if I get any other solutions. You can close the issue now, thanks.
