### ISSUE TITLE
How to get a websites title 

### ISSUE THREAD

**Issue by klasmic** [cefsharp/CefSharp#1817]
I am creating a web browser and am having some issues whit tabs I want to get the title of a website onto
the tab to replace "newtab" but I don't know what the script would be I assume it would be something like this ` Tcontrol.SelectedTab.Text = ` I don't know what to but after the = sign I though it would be chrome . something (like DocumentTitle) but no luck. and Tcontrol is just my tabcontrols name I'm using CefSharp 51

**Comment by amaitland** [comment]
@klasmic Each implementation has it's own method of obtaining the title. Either search through the source/examples or read the `API` doc at http://cefsharp.github.io/api/51.0.0/

> We'd like to keep issues exclusively for bug reports, so please ask your questions on Gitter

https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md
