### ISSUE TITLE
53+ Crash running x64 build on processors that do not support vmovaps

### ISSUE THREAD

**Issue by JohnGalt1717** [cefsharp/CefSharp#1819]
Just what it says. Absolutely nothing in the log file when it crashes.

I need to use this build because of the major problems with flickering etc. with gpu.

I've tried multiple different locations in the form to set address from loaded, constructor after initilizecomponent and browser_IsBrowserInitializedChanged event and in every case it just crashes to the desktop.

I have a sample app that works with 51 and crashes when upgrading to 53 pre nuget if needed.

**Comment by amaitland** [comment]
Please fork https://github.com/cefsharp/CefSharp.MinimalExample/tree/cefsharp/53 and provide a sample that reproduces your problem.

**Comment by amaitland** [comment]
> https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#loading-native-symbols-for-easier-diagnosis

You can investigate this further, enable native code debugging
https://msdn.microsoft.com/en-us/library/tdw0c6sf(v=vs.100).aspx

Download the matching **Release Symbols** from http://opensource.spotify.com/cefbuilds/index.html the version is **3.2785.1478**

**Comment by amaitland** [comment]
Also next time if you could please fill out the full bug report as per https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report (it should have been pre-populated in description field when you created an issue).

**Comment by amaitland** [comment]
Settings `Address` works fine for me and no other reports from users there is a problem, so I'll release `53.0.0` as planned.

If your using an `x64` build then it's possible https://bitbucket.org/chromiumembedded/cef/issues/1999/windows-2785-crash-running-x64-build-on is related.

**Comment by JohnGalt1717** [comment]
I'm definitely running x64 (I suspect most are now-a-days). Also note that I'm using .NET 4.52.

**Comment by amaitland** [comment]
> I'm definitely running x64 (I suspect most are now-a-days)

`64bit` operating system yes, `x64` build of `CefSharp`, not so many.

Can you please test https://github.com/cefsharp/CefSharp.MinimalExample/tree/cefsharp/53 it's setup for both `x64` and `x86`

**Comment by amaitland** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=654213

**Comment by amaitland** [comment]
Problem affects `WinForms`, `WPF` and `OffScreen`.

**Comment by amaitland** [comment]
`master` has been updated, this appears to be resolved in the `2840` branch. Tagging this as `55.0.0` as it will be resolved in that release. For now build your own version from `master`, use an `x86` version or roll back to `51`.

**Comment by JohnGalt1717** [comment]
That's excellent news!

**Comment by keepWalking** [comment]
> `master` has been updated, this appears to be resolved in the `2840` branch. Tagging this as `55.0.0` as it will be resolved in that release. For now build your own version from `master`, use an `x86` version or roll back to `51`.

This bug is still there with latest version: 67.0 for x64 build, no plan to fix?
