### ISSUE TITLE
VS2015 Unable to build in Debug mode

### ISSUE THREAD

**Issue by kendallb** [cefsharp/CefSharp#1820]
Can't seem to find anything about this but when I loaded the project into VS2015 and did a full build, it fails on CefShare.Core with a bunch of errors like this:

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in AssemblyInfo.obj	CefSharp.Core	C:\src\git\CefSharp\CefSharp.Core\libcef_dll_wrapper.lib(cef_stream_resource_handler.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in AssemblyInfo.obj	CefSharp.Core	C:\src\git\CefSharp\CefSharp.Core\libcef_dll_wrapper.lib(cef_stream_resource_handler.obj)	1	

Doing a Google search I found this article which indicates that this is caused by linking debug binaries with release ones for the C++ code, so I changed to release mode and rebuilt and it worked fine.

Is there some reason the project does not compile properly in debug mode and how do we fix it?

**Comment by amaitland** [comment]
> Can't seem to find anything about this but when I loaded the project into VS2015 and did a full build, it fails on CefShare.Core with a bunch of errors like this:

Official releases are made using `VS2013`, so it's rare that I use `VS2015` for development.

I can confirm there is a problem using `VS2015 Update 2`, about all I have time for at the moment.

**Comment by kendallb** [comment]
Ok thanks. I tried running the samples built with VS2015 and they didn't seem to run properly either, so something is not building right. I don't have VS2013 installed anymore :(

**Comment by amaitland** [comment]
You can use the https://github.com/cefsharp/CefSharp.MinimalExample for testing

**Comment by kendallb** [comment]
Yep, I have been using that.

**Comment by amaitland** [comment]
When `cmake` generates `libcef_dll_wrapper.vcxproj` for `VS2015` it's incorrectly setting `RuntimeLibrary`

```
<RuntimeLibrary>MultiThreadedDLL</RuntimeLibrary>
```

Should be 

```
<RuntimeLibrary>MultiThreadedDebugDLL</RuntimeLibrary>
```

Upgrading to newer `cmake` had no effect. `build.ps` can be updated to work around the problem.

Changes are required to https://github.com/cefsharp/cef-binary/blob/master/build.ps1#L226

Would be best fixed in `CEF` source, though that would take some time before the changes were merged I'm sure.

**Comment by amaitland** [comment]
Relevant changes to `CEF` were https://bitbucket.org/chromiumembedded/cef/commits/b52741d23676a0b6c589ce3aedb2430a21b51c94

Can likely just disable sandbox and our builds will work as expected.

**Comment by amaitland** [comment]
Changes will take effect soon as I upload the next set of packages - should be today sometime.

**Comment by amaitland** [comment]
`master` has been updated.

**Comment by kendallb** [comment]
Awesome
