### ISSUE TITLE
CefSharp.Wpf screen flashes or blinks while loading and for a little after loading

### ISSUE THREAD

**Issue by tpitman** [cefsharp/CefSharp#1823]
- **What version of the product are you using?**
    - 51.0.0

- **What architecture x86 or x64?**
    - x86, but x64 does it too

- **On what operating system?**
    - Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - WPF

- **What steps will reproduce the problem?**
    - Add the CefSharp WebBrowser to a simple WPF page
    - Browse to http://www.msn.com (or any web site with very much on it)

- **What is the expected output? What do you see instead?**
    - Notice that the screen flashes or blinks as it loads and even a little bit after loading

- **Please provide any additional information below.**
    - None available

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
    - No debug.log output

**Comment by amaitland** [comment]
Did you read the `Release Notes`? 

https://github.com/cefsharp/CefSharp/releases/tag/v51.0.0

**Comment by tpitman** [comment]
I am really sorry for not reading the release note. In my defense I did do a search on Issues trying flicker and then flashes and neither one showed any results. I didn't think to look in the release notes when nothing came up on a search of the issue.

Again, sorry and thanks for the work around. I will give it a try.

The release notes said something about giving you information about my graphics card and OS.

I am running Windows 10 on a Macbook Pro with the NVidia 750m (2013 model with retina). I have the latest NVidia driver downloaded from NVidia's web site.

**Comment by raphson93** [comment]
The issue still observe in the latest cefsharp 73.

**Comment by amaitland** [comment]
This issue was `WPF` specific and was resolved some **years** ago, please don't comment on old issues.
