### ISSUE TITLE
Run many Process with Cef  in a while,The Cef will not work

### ISSUE THREAD

**Issue by zhizlm** [cefsharp/CefSharp#1824]
What version of the product are you using?

nuget 51.0.0

What architecture x86 or x64?
x64

On what operating system?
Win7

Are you using WinForms, WPF or OffScreen?
OffScreen

What steps will reproduce the problem?
Run many Process with Cef  in a while,The Cef will not work. May be 5 minutes or 10 minutes cef will failure, All process CPU 0% ..  i dont know why ??

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by amaitland** [comment]
> Run many Process with Cef in a while,The Cef will not work. May be 5 minutes or 10 minutes cef will failure, All process CPU 0% .. i dont know why ??

You can see an example of running multiple instances using `Tasks`, https://github.com/cefsharp/CefSharp/blob/cefsharp/53/CefSharp.OffScreen.Example/Program.cs#L34

Please next time take the time to read the [Issue Template](https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md)
