### ISSUE TITLE
CefSharp.Code.dll Error

### ISSUE THREAD

**Issue by alex-econ** [cefsharp/CefSharp#1827]
I made a program that runs video in the window from web page. I'm using VS 2015. Use this program and other people, but some complain of error associated with CefSharp.Code.dll. They tried to install: Visual C++ Redistributable Packages for Visual Studio 2012\2013\2015. But it didn't help. The error remains. These people use Net Framework is 4.5\4.6

How to fix the error?

**Comment by alex-econ** [comment]
Most interesting is that if people will install VS, then it will work without errors at startup.

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by alex-econ** [comment]
Nuget
WinForm
x86
Windows 7

I have installed VS2015 and program with CefSharp working fine, but some people who have no Visual Studio installed the program does not work and gives an error that CefSharp.Core.dll not found

**Comment by amaitland** [comment]
> I have installed VS2015 and program with CefSharp working fine, but some people who have no Visual Studio installed the program does not work and gives an error that CefSharp.Core.dll not found

See https://github.com/cefsharp/CefSharp#release-branches then read the `FAQ`, 

> Nuget

`Nuget` isn't a version number.

> We'd like to keep issues exclusively for bug reports, so please ask your questions on Gitter

Ask on `Gitter`. This isn't a bug. Please read the `Issue Template` as linked to.
