### ISSUE TITLE
CefSharp.Code.dll not found

### ISSUE THREAD

**Issue by alex-econ** [cefsharp/CefSharp#1828]
Nuget
WinForm
x86
Windows 7

I have installed VS2015 and program with CefSharp working fine, but some people who have no Visual Studio installed the program does not work and gives an error that CefSharp.Core.dll not found

I made a program that runs video in the window from web page. I'm using VS 2015. Use this program and other people, but some complain of error associated with CefSharp.Code.dll. They tried to install: Visual C++ Redistributable Packages for Visual Studio 2012\2013\2015. But it didn't help. The error remains. These people use Net Framework is 4.5\4.6

How to fix the error?

Most interesting is that if people will install VS, then it will work without errors at startup.

**Comment by amaitland** [comment]
@alex-econ Stop opening issues
