### ISSUE TITLE
Error: System.Threading.Tasks.TaskSchedulerException

### ISSUE THREAD

**Issue by zhizlm** [cefsharp/CefSharp#1829]
What version of the product are you using?
nuget 51.0.0

What architecture x86 or x64?
x64

On what operating system?
Win7

Are you using WinForms, WPF or OffScreen?
OffScreen

Run many times in a process appear this error: "System.Threading.Tasks.TaskSchedulerException"

**Comment by amaitland** [comment]
> Run many times in a process appear this error: "System.Threading.Tasks.TaskSchedulerException"

@zhizlm You'll need to provide a `StackTrace` and code that reproduces the problem. You can fork the https://github.com/cefsharp/CefSharp.MinimalExample (No zip files or binaries as per https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#help-us-help-you

**Comment by zhizlm** [comment]
@amaitland  Thx! 

 The Code is : 

`  
public bool OnBeforePopup(IWebBrowser browserControl, IBrowser browser, IFrame frame, string targetUrl, string targetFrameName, WindowOpenDisposition targetDisposition, bool userGesture, IPopupFeatures popupFeatures, IWindowInfo windowInfo, IBrowserSettings browserSettings, ref bool noJavascriptAccess, out IWebBrowser newBrowser)
        {

           **ChromiumWebBrowser temp = new ChromiumWebBrowser(targetUrl, null, null, false);**
            BroForm.popDic.Add(temp.GetHashCode(), temp);
            temp.LifeSpanHandler = this;
            temp.RequestHandler = browserControl.RequestHandler;
            temp.JsDialogHandler = new BrowserJsDialog();

            newBrowser = temp;
            windowInfo.SetAsWindowless(IntPtr.Zero, true);
            return false;
}
`

**Comment by amaitland** [comment]
@zhizlm What does the `stack trace` look like?

If you provide a full example I'll have a look at some point, I don't have time to try and reproduce your problem with a minimal code snippet.

**Comment by zhizlm** [comment]
@amaitland 
Could u give me an example:  How to use OffScreen click some links in new browser or pop some links in new browser , and it can totally close these browsers and free memory..  Thx!!

**Comment by amaitland** [comment]
> Could u give me an example: How to use OffScreen click some links in new browser or pop some links in new browser , and it can totally close these browsers and free memory.. Thx!!

The example is here https://github.com/cefsharp/CefSharp/blob/cefsharp/53/CefSharp.OffScreen.Example/Program.cs

You can use javascript to click links, see the `FAQ`. I don't have time to provide everyone with examples, you'll have to piece it together yourself.

For this bug report to be meaningful you need to provide a `stack trace` and an example of how to reproduce the error.

**Comment by zhizlm** [comment]
@amaitland   Thx!    I use 50 PC with win7 system to Test this problem,but not Every PC appears this Problem. So,I don't know how to provide a stack trace.

 I change a way to ask. If i need many website to load, but I dont want every process to Cef.shutdown(); can it just close itself and  free memory and continue to work?

**Comment by amaitland** [comment]
> So,I don't know how to provide a stack trace.

You need only obtain a stack trace from one. Where is your logging? You should be logging exceptions.

> I change a way to ask. If i need many website to load, but I dont want every process to Cef.shutdown(); can it just close itself and free memory and continue to work?

I have no idea what your asking.

**Comment by zhizlm** [comment]
@amaitland   it still always show this Error:  `Exception: \"System. The Threading. Tasks. TaskSchedulerException\" (located in mscorlib. DLL)`   when OnBeforePopup new browser in sometimes.

**Comment by amaitland** [comment]
Without a `StackTrace` and a way to reproduce the issue there isn't anything I can do. Check the `Troubleshooting guide` in the wiki for some more debugging tips.
