### ISSUE TITLE
When Cef.Shutdown with Popup page will stay forever

### ISSUE THREAD

**Issue by zhizlm** [cefsharp/CefSharp#1830]
What version of the product are you using?
nuget 53.0.0

What architecture x86 or x64?
x64

On what operating system?
Win7

Are you using WinForms, WPF or OffScreen?
OffScreen 53

When Cef.Shutdown with Popup page will stay forever

This Page code is:

function   tt(){window.open("http://github.com")}   

<body onunload="tt()">

**Comment by amaitland** [comment]
@zhizlm As stated in the `Issue Template`, please discuss your problem on `Gitter` before opening an issue.

You have to close all windows before calling `Shutdown`.
