### ISSUE TITLE
Scaling issue when contained in ViewBox on WPF

### ISSUE THREAD

**Issue by OttawaDave** [cefsharp/CefSharp#1831]
**What version of the product are you using?**
53.0.0

**What architecture x86 or x64?**
x86

**On what operating system?**
Win7 and Win10

**Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

**What steps will reproduce the problem?**
We have the ChormiumWebBrowser control contained within a ViewBox.  There are several other Grid panels also contained within this ViewBox.  When initially opening at full screen the rendering in the browser control looks good.  When reducing the size of the application window the text scaling inside the browser but becomes very poor quality and unreadable at some scales.

**What is the expected output? What do you see instead?**
I expect the text to look crisp like the rest of the WPF controls.

**Please provide any additional information below.**
It is not an option for us to remove the control from the ViewBox.  If the control cannot correctly scale the content then an alternative (but not preferred) would be to have a mechanism to not have the control scale at all and provide size changed notifications so that we can rerender is a smaller font.  We are currently using the built in WebBrowser control and do this.  The main purpose of moving to CefSharp is to resolve the air space issue with the built in browser control.

**Comment by amaitland** [comment]
> I expect the text to look crisp like the rest of the WPF controls.

That's a lot to expect. Hosting a `WebBrowser` in a `ViewBox` is really not ideal from a performance perspective, your rendering the frames at a set size then transforming them.

- Long and the short is hosting in a `ViewBox` supported? No
- Is it possible? Maybe
- Are you prepared to investigate further and implement the changes yourself? If not then then please close this issue and continue searching for another solution 👍

**Comment by amaitland** [comment]
Closing due to lack of feedback.

**Comment by royben** [comment]
Do not understand the lack of interest. This is a very useful behavior in my opinion.
