### ISSUE TITLE
Crash in libcef.dll and Win2012R2

### ISSUE THREAD

**Issue by azgorov** [cefsharp/CefSharp#1832]
**What version of the product are you using?**
53.0.0
**What architecture x86 or x64?**
x64
**On what operating system?**
Win2012 and Win2012R2
**Are you using WinForms, WPF or OffScreen?**
OffScreen
**What steps will reproduce the problem?**
Simple code that loads url and takes screenshot. it works flawlessly in my machine - win server 2012 + VS2015. When I tried to deploy to amazon aws - win2012R2 it crashes. Every prerequisite is done – this means that VS2013Redis is installed and every required file – dll,pak etc is deployed. Just for a test every folder have Everyone full control permissions. 
Result is that browser instance is created, enter once in LoadingStateChangedEvent with loading status still true. After this there are 2 exceptions in event viewer :
1.	Faulting application name: w3wp.exe, version: 8.5.9600.16384, time stamp: 0x5215df96 Faulting module name: libcef.dll, version: 3.2785.1482.0, time stamp: 0x57eb5d75 Exception code: 0xc000001d
Fault offset: 0x000000000010055c
2.	Windows cannot access the file  for one of the following reasons: there is a problem with the network connection, the disk that the file is stored on, or the storage drivers installed on this computer; or the disk is missing. Windows closed the program IIS Worker Process because of this error.
What is the expected output? What do you see instead?
Expected – result from loading url. Result – crash.
**Please provide any additional information below.**
Using Flore’s example for using CefSharp with .net appdomain (https://github.com/flole/CefSharp.AppDomain). This worked seems to work on win 2012 but not on Windows 2012R2.

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by amaitland** [comment]
@azgorov Was there a need to create this issue? You asked your question on `Gitter`.

**Comment by amaitland** [comment]
Likely a duplicate of #1819

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/issues/1819#issuecomment-254689818
