### ISSUE TITLE
WPF WindowsFormsHost Touch Screen not working

### ISSUE THREAD

**Issue by ccnucheng** [cefsharp/CefSharp#1833]
- **What version of the product are you using?**
  - 1、Nuget 53
  - 2、build from a branch 49.0.2623
- **What architecture x86 or x64?**
  - x64
- **On what operating system?**
  - Win7
- **Are you using `WinForms`, `WPF` or `OffScreen`?**
  - WPF
- **What steps will reproduce the problem?**
  - Reference ：CefSharp.dll   CefSharp.Core.dll   CefSharp.Winform.dll
  - Use 'WindowsFormsHost' control in my wpf program
  - Create 'ChromiumWebBrowser' and add it to 'WindowsFormsHost'
  - After running, you can display the page, but no Touch effect
- **What is the expected output? What do you see instead?**
  - Can touch scroll and pinch

**Comment by amaitland** [comment]
@ccnucheng Does the `Touch Screen` work when using the native `WinForms` implementation? You can test it using https://github.com/cefsharp/CefSharp.MinimalExample

**Comment by ccnucheng** [comment]
@amaitland 
*- Touch Screen is work when using the native WinForms implementation.*
*- Touch Screen is work when using WindowsFormsHost in WPF with Win10*

**Comment by amaitland** [comment]
Two things to try

- Firstly make sure your app has the relevant compatibility entries in the `app.manifest`. https://github.com/cefsharp/CefSharp.MinimalExample/blob/master/CefSharp.MinimalExample.Wpf/app.manifest#L37
- Secondly you can attempt to run the message loop on your `UI` thread, this often fixes a lot of random problems see https://github.com/cefsharp/CefSharp.MinimalExample/commit/15c4a7a7845452c190f6e44c5b7db41ccb504601

The fact it works in `Win 10` likely means there isn't a whole lot that can be done. `CefSharp` is just a wrapper around `CEF` after all.

**Comment by ccnucheng** [comment]
@amaitland 
- Still can not Touch, when after the App.manifest file modified,
The CefSettings parameter is already the same as in the example

**Comment by amaitland** [comment]
> The CefSettings parameter is already the same as in the example

I find that unlikely, the browser doesn't function without some sort of message loop processing. Check again.

**Comment by ccnucheng** [comment]
@amaitland

>I find that unlikely, the browser doesn't function without some sort of message loop processing. Check again.

**Although still can not touch, but still thank you very mach!**

**Comment by amaitland** [comment]
So you've got the message loop running on the dispatcher? Have you tested on different hardware with Windows 7?

**Comment by ccnucheng** [comment]
Yes,I add`Cef.DoMessageLoopWork()` in window‘s Loaded event,and use `DispatcherTimer` execute it,and test on defferent machine with windows 7!It's still can't touch

**Comment by amaitland** [comment]
You can try CefGlue or ChromiumFx, see if you have better luck with a different framework.

**Comment by szymonmalok** [comment]
For me adding "touch-events=enabled" to command line arguments, when starting CEF fixed simillar issue.

**Comment by ccnucheng** [comment]
@szymonmalok 
Yes,I have added the parameters ,but still can not touch the scrren!

**Comment by softwaretirol** [comment]
We have the same problem. Hosting the WPF Control in a WindowsFormsHost but Touch Events dont work on Windows 7. On Windows 8 or 10 , there is no problem.

**Comment by ccnucheng** [comment]
@softwaretirol  Did you solve it?

**Comment by softwaretirol** [comment]
No - we still have the problem.

**Comment by toprezr** [comment]
![touch](https://cloud.githubusercontent.com/assets/23049356/19805682/2ab83948-9d16-11e6-91f0-6d39abb460ac.gif)
Touching Event is initiated, but does not work as expected, If you happen to click on it so 50 times, sometimes an Event is working, but It's random.

**Comment by ccnucheng** [comment]
Has anyone solved this problem?

**Comment by ccnucheng** [comment]
OK! I solved it.

**Comment by mortalV** [comment]
How did you solved it?

**Comment by ccnucheng** [comment]
@mortalV 

- **Using the open source WmTouchDevice**
  - https://github.com/jaytwo/WmTouchDevice
- **Call MessageTouchDevice.RegisterTouchWindow(IntPtr hWnd) during or after your Window's SourceInitialized event**
  - `System.IntPtr hWnd = new `System.Windows.Interop.WindowInteropHelper(this).Handle;
  - `WmTouchDevice.MessageTouchDevice.RegisterTouchWindow();`
- **Add the CustomControl(WPF) in your project,and inherited from WindowsformsHost**
   `public class CefWindowsFormsHost : WindowsFormsHost`
    `{`
    `     static CefWindowsFormsHost()`
        `{`
            `DefaultStyleKeyProperty.OverrideMetadata(typeof(CefWindowsFormsHost), new FrameworkPropertyMetadata(typeof(CefWindowsFormsHost)));`
       ` }`
       ` protected override IntPtr WndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)`
        `{`
           ` WmTouchDevice.MessageTouchDevice.WndProc(System.Windows.Window.GetWindow(this), msg, wParam, lParam, ref handled);`
          `  return base.WndProc(hwnd, msg, wParam, lParam, ref handled);`
      `  }`
    `}`
- **Use this Custom WFH replace the System.Windows.Forms.Integration.WindowsFormsHost**

**Comment by amaitland** [comment]
Great, sounds like there is a valid workaround 👍 Closing

**Comment by talbotmcinnis** [comment]
@ccnucheng You are a god amongst men.  Great job discovering the fix, and amazing community dedication for sharing it in such detail.

**Comment by lindexi** [comment]
Fix in https://github.com/cefsharp/CefSharp/pull/2745

**Comment by kkwpsv** [comment]
I found another way to solve this problem. Just disbale `Chrome Legacy Window` with `disable-legacy-window`.

Windows 7 won't send `WM_TOUCH` messages to the window when it's a child of a WPF window. So touch won't work. Its window style may be part of the reason. But there's no document about this.

The effect of disabling this window is [here](https://chromium.googlesource.com/chromium/chromium/+/trunk/content/browser/renderer_host/legacy_render_widget_host_win.h).

In some scenarios, I think this solution is better than [disabling RealTimeStylus](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/disable-the-realtimestylus-for-wpf-applications?view=netframeworkdesktop-4.8) and use WmTouchDevice.
