### ISSUE TITLE
Add a Drop-down list (<select>) Handler to allow custom menu

### ISSUE THREAD

**Issue by valhentai** [cefsharp/CefSharp#1834]
In the WPF web browser control, there is no control on how a drop down menu is displayed.
It cause two problem in our application 
- The drop down is not rotated with the browser. It is easyly reproducable in the WPF example by changing the angle.
![chromium_drop_down](https://cloud.githubusercontent.com/assets/13367963/19381330/6b5b45d8-91fb-11e6-890a-8b8159e3dcff.jpg)
- We are developping a touch application so we need to customise the drop list visual to make more touch friendly.

Like the DialogHandler and MenuHandler, we need an handler to provide our own implementation of the drop down list.

**Comment by amaitland** [comment]
This would need to be implemented in `CEF`, post your feature request http://magpcss.org/ceforum/viewforum.php?f=7

**Comment by amaitland** [comment]
If you wish to fix the apparent display issue in the image you've provided, then you can likely apply the same transform to the `Image` that renders the popup as the main control using binding.

https://github.com/cefsharp/CefSharp/blob/cefsharp/53/CefSharp.Wpf/ChromiumWebBrowser.cs#L1539

Just an idea, not something I've tested. By all means submit a `PR` 👍

**Comment by valhentai** [comment]
Thanks. I made a feature request on CEFSharp forum.
[http://magpcss.org/ceforum/viewtopic.php?f=7&t=14583&p=32577#p32577](http://magpcss.org/ceforum/viewtopic.php?f=7&t=14583&p=32577#p32577)

**Comment by amaitland** [comment]
> CEFSharp forum.

Just to clarify, it's `ceforum`, the forum for the `Chromium Embedded Framework`, for which `CefSharp` is just a wrapper. https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-chromium-embedded-frameworkcef

**Comment by valhentai** [comment]
I looked at the code handling the display of a drop down menu.
Now I understand that CEF just give a bitmap which is displayed in a WPF Popup.  
The problem in our application is we can't use the WPF Popup.
So the best solution for us is to fork CEFSharp to modify this part.
I suppose it is not worth offering an interface to provide custom handling of the popup bitmap in CEFSharp just for our very special case.

**Comment by amaitland** [comment]
> I suppose it is not worth offering an interface to provide custom handling of the popup bitmap in CEFSharp just for our very special case.

If you can succinctly add an extension point that allows for your customisation then I've got no problem with that.
