### ISSUE TITLE
how to make ChromiumWebBrowser have standalone cookies

### ISSUE THREAD

**Issue by duoduoxi** [cefsharp/CefSharp#1836]
Hi,all
    I used same ChromiumWebBrowser in my program, now all ChromiumWebBrowser shared the same cookies, Is there any way to make  ChromiumWebBrowser have standalone cookies ?

Thanks.

**Comment by amaitland** [comment]
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by amaitland** [comment]
@duoduoxi Please read the issue template next time.

Isolation is achieved using a `RequestContext`. If you specify a unique cache for each unique `RequestContext` you should have cookie isolation. You can share a `RequestContext` between multiple instances.

```c#
browser.RequestContext = new RequestContext(new RequestContextSettings { CachePath = "cache1" });
```

https://github.com/cefsharp/CefSharp/blob/5248174f894cba94c11bdf4aefe6b74383326d6c/CefSharp.Wpf.Example/Views/BrowserTabView.xaml.cs#L44

**Comment by duoduoxi** [comment]
@amaitland 
Sorry , I am not familiar with github. I will ask question on gitter next time.
Thank you very much.
