### ISSUE TITLE
Handle pop up window on version 53

### ISSUE THREAD

**Issue by khacminh** [cefsharp/CefSharp#1837]
- **What version of the product are you using?**
      Nuget 53.0.0

- **What architecture x86 or x64?**
  x86 

- **On what operating system?**
    Win 10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
   WPF

- **What steps will reproduce the problem?**
    Open Popup

- **Description**
   CefSharp WPF version 53 automatically open popup on a new window. And this causes issue to handle. On previous versions, I can handle the popup by implement the `ILifeSpanHandler.OnBeforePopup` method.
   On version 53, if I set return value of method `ILifeSpanHandler.OnBeforePopup` to **true**, no popup window will be showed. And I can create new `CefSharp.Wpf.ChromiumWebBrowser` object and load the **targetUrl**. However, some popups cannot be loaded in this way. If I set return value of method `ILifeSpanHandler.OnBeforePopup` to **false**, every popup will be opened on new window and everything works fine. But the problem is I cannot handle these windows (for example, set `CefSharp.Wpf.ChromiumWebBrowser` objects to be children of a Grid).

**Comment by amaitland** [comment]
@khacminhThe reference implementation is at https://github.com/cefsharp/CefSharp/blob/cefsharp/53/CefSharp.Wpf.Example/Handlers/LifespanHandler.cs#L20 Download the source, test that to confirm if there's an issue.

**Comment by amaitland** [comment]
The last changes were made at https://github.com/cefsharp/CefSharp/commit/d1d754cf58d94a278ddf497f00dfb233b20ca427#diff-ae22f43defce5876f044e1169a4afe07 compare and update your code.

**Comment by khacminh** [comment]
Hi amaitland,
Thanks for your response. 
I tested with the the source code downloaded from github before post this issue. The method `windowInfo.SetAsWindowless` causes a bug of popup zooming.
Please take a look at [this image](https://drive.google.com/file/d/0B9g9TuLjEWYIY0JtcU5aUHMzdVE/view?usp=sharing), I opened a popup from 9gag page.

**Comment by amaitland** [comment]
> I tested with the the source code downloaded from github before post this issue. The method windowInfo.SetAsWindowless causes a bug of popup zooming.

If your hosting this in `WPF` then it's required.

> Please take a look at this image, I opened a popup from 9gag page.

By all means investigate further, not a priority for me. This feature has always been **EXPERIMENTAL**

Is there a reason you never posted code that demos your problem?

**Comment by khacminh** [comment]
As I said, I follow the example to implement the LifeSpanHandler. You can take a look to [this gist](https://gist.github.com/khacminh/69c06ccc0cb5847227a2d00175cc15ca).

On the previous release, everything works fine. The issue occurs on version 53. 

If I set return value of method `ILifeSpanHandler.OnBeforePopup` to **false**, how can I handle the popup window?

**Comment by amaitland** [comment]
> As I said, I follow the example to implement the LifeSpanHandler. You can take a look to this gist.

If that was implied, it certainly wasn't clear.

> On the previous release, everything works fine. The issue occurs on version 53.

If `51.0.0` worked correctly then you can compare the two branches, if there are any changes in `CefSharp` they should be easy to spot. Could just as easily be a change in `Chromium` that is causing problems.

> If I set return value of method ILifeSpanHandler.OnBeforePopup to false, how can I handle the popup window?

Setting `newBrowser` is the only option, it is however **EXPERIMENTAL** as there has always been issues. If you need this fixed, then get involved, sort it out. This is an open source project, the project is only as good as the people contributing.

If your not interested in contributing then just roll back to a version that worked.

**Comment by amaitland** [comment]
You can use https://github.com/cefsharp/CefSharp/compare/cefsharp/51...cefsharp/53 to compare

**Comment by amaitland** [comment]
Using https://github.com/cefsharp/CefSharp/tree/cefsharp/53 I loaded http://9gag.com/ with the custom popup code in `LifeSpanHandler` https://github.com/cefsharp/CefSharp/blob/cefsharp/53/CefSharp.Wpf.Example/Handlers/LifespanHandler.cs#L20

Works no problem opening popups. Try on some different hardware.

**Comment by khacminh** [comment]
With this code, everything works fine, and the same behavior with default LifeSpanHandler. The popup will be automatically opened on a new window. The problem is I cannot handle the that window and its content (`CefSharp.Wpf.ChromiumWebBrowser` object).

**Comment by amaitland** [comment]
> With this code, everything works fine, and the same behavior with default LifeSpanHandler. The popup will be automatically opened on a new window.

At this point in time it basically feels like you've been **wasting my time**. I asked for code that reproduces the problem, you linked to a `GIST` that is effectively the example solution, which works fine and you've confirmed works fine.  This is **VERY** frustrating. You have yet to provide a means of reproducing your problem.

> The problem is I cannot handle the that window and its content (CefSharp.Wpf.ChromiumWebBrowser object).

I have no idea what that is supposed to mean. The code creates that `Window`, you can do whatever you like with it.

**Comment by khacminh** [comment]
Seriously? Did you take a look to my Gist? The link you give me and the gist are not the same.
This is the method `ILifeSpanHandler.OnBeforePopup` from gist:

```
bool ILifeSpanHandler.OnBeforePopup(IWebBrowser browserControl, IBrowser browser, IFrame frame, string targetUrl, string targetFrameName, WindowOpenDisposition targetDisposition, bool userGesture, IPopupFeatures popupFeatures, IWindowInfo windowInfo, IBrowserSettings browserSettings, ref bool noJavascriptAccess, out IWebBrowser newBrowser)
        {
            ////Set newBrowser to null unless your attempting to host the popup in a new instance of ChromiumWebBrowser
            //newBrowser = null;

            //return false;

            //NOTE: This is experimental
            var chromiumWebBrowser = (ChromiumWebBrowser)browserControl;

            ChromiumWebBrowser chromiumBrowser = null;

            var windowX = (windowInfo.X == int.MinValue) ? double.NaN : windowInfo.X;
            var windowY = (windowInfo.Y == int.MinValue) ? double.NaN : windowInfo.Y;
            var windowWidth = (windowInfo.Width == int.MinValue) ? double.NaN : windowInfo.Width;
            var windowHeight = (windowInfo.Height == int.MinValue) ? double.NaN : windowInfo.Height;

            chromiumWebBrowser.Dispatcher.Invoke(() =>
            {
            	var owner = Window.GetWindow(chromiumWebBrowser);
            	chromiumBrowser = new ChromiumWebBrowser
            	{
            		Address = targetUrl,
            	};

            	chromiumBrowser.SetAsPopup();
            	chromiumBrowser.LifeSpanHandler = this;

            	var popup = new Window
            	{
            		Left = windowX,
            		Top = windowY,
            		Width = windowWidth,
            		Height = windowHeight,
            		Content = chromiumBrowser,
            		Owner = owner,
            		Title = targetFrameName
            	};

            	var windowInteropHelper = new WindowInteropHelper(popup);
            	//Create the handle Window handle (In WPF there's only one handle per window, not per control)
            	var handle = windowInteropHelper.EnsureHandle();

            	//The parentHandle value will be used to identify monitor info and to act as the parent window for dialogs,
            	//context menus, etc. If parentHandle is not provided then the main screen monitor will be used and some
            	//functionality that requires a parent window may not function correctly.
            	windowInfo.SetAsWindowless(handle, true);

            	popup.Closed += (o, e) => 
            	{
            		var w = o as Window;
            		if (w != null && w.Content is IWebBrowser)
            		{
            			(w.Content as IWebBrowser).Dispose();
            			w.Content = null;
            		}
            	};
            });

            newBrowser = chromiumBrowser;

            return true;
        }
```

And from your link, the example:
```
bool ILifeSpanHandler.OnBeforePopup(IWebBrowser browserControl, IBrowser browser, IFrame frame, string targetUrl, string targetFrameName, WindowOpenDisposition targetDisposition, bool userGesture, IPopupFeatures popupFeatures, IWindowInfo windowInfo, IBrowserSettings browserSettings, ref bool noJavascriptAccess, out IWebBrowser newBrowser)
        {
            //Set newBrowser to null unless your attempting to host the popup in a new instance of ChromiumWebBrowser
            newBrowser = null;

            return false;

            //NOTE: This is experimental
            //var chromiumWebBrowser = (ChromiumWebBrowser)browserControl;

            //ChromiumWebBrowser chromiumBrowser = null;

            //var windowX = (windowInfo.X == int.MinValue) ? double.NaN : windowInfo.X;
            //var windowY = (windowInfo.Y == int.MinValue) ? double.NaN : windowInfo.Y;
            //var windowWidth = (windowInfo.Width == int.MinValue) ? double.NaN : windowInfo.Width;
            //var windowHeight = (windowInfo.Height == int.MinValue) ? double.NaN : windowInfo.Height;

            //chromiumWebBrowser.Dispatcher.Invoke(() =>
            //{
            //	var owner = Window.GetWindow(chromiumWebBrowser);
            //	chromiumBrowser = new ChromiumWebBrowser
            //	{
            //		Address = targetUrl,
            //	};

            //	chromiumBrowser.SetAsPopup();
            //	chromiumBrowser.LifeSpanHandler = this;

            //	var popup = new Window
            //	{
            //		Left = windowX,
            //		Top = windowY,
            //		Width = windowWidth,
            //		Height = windowHeight,
            //		Content = chromiumBrowser,
            //		Owner = owner,
            //		Title = targetFrameName
            //	};

            //	var windowInteropHelper = new WindowInteropHelper(popup);
            //	//Create the handle Window handle (In WPF there's only one handle per window, not per control)
            //	var handle = windowInteropHelper.EnsureHandle();

            //	//The parentHandle value will be used to identify monitor info and to act as the parent window for dialogs,
            //	//context menus, etc. If parentHandle is not provided then the main screen monitor will be used and some
            //	//functionality that requires a parent window may not function correctly.
            //	windowInfo.SetAsWindowless(handle, true);

            //	popup.Closed += (o, e) =>
            //	{
            //		var w = o as Window;
            //		if (w != null && w.Content is IWebBrowser)
            //		{
            //			(w.Content as IWebBrowser).Dispose();
            //			w.Content = null;
            //		}
            //	};
            //});

            //newBrowser = chromiumBrowser;

            //return false;
        }
```

**Comment by amaitland** [comment]
> Seriously? Did you take a look to my Gist? The link you give me and the gist are not the same.

Yes seriously. You've uncommented out the example. That's the exact example I've tested with. You've even left the `EXPERIMENTAL` notes in there. Come on.

**Comment by amaitland** [comment]
Notice to all, I am taking a step back from the project and will no longer be providing support/answering questions. I will consider merging `PR's` that fix a reproducible bug.

**Comment by khacminh** [comment]
amaitland,

The issue has not solved yet. It occurs you open the popup on PC having display scale bigger than 100%. I am finding the solution for this.

**Comment by amaitland** [comment]
> The issue has not solved yet. It occurs you open the popup on PC having display scale greater than 100%. I am trying for the solution.

I'm leaving this closed as I'm no longer providing support. Good luck 👍

**Comment by khacminh** [comment]
I don't ask for support. This is a bug report

**Comment by amaitland** [comment]
Create a new bug report that describes the problem in detail, with steps to reproduce. Think about the sort of bug report you'd like from your users.
