### ISSUE TITLE
RequestContext dispose crash. 

### ISSUE THREAD

**Issue by maziart** [cefsharp/CefSharp#1838]
- **What version of the product are you using?**
  - What version are you using? Nuget? CI Nuget? build from a branch? If so which branch?
    e.g. 47.0.3
- **What architecture x86 or x64?**
- **On what operating system?**
  - Win7, Win 8, Win10, etc?
- **Are you using `WinForms`, `WPF` or `OffScreen`?**
- **What steps will reproduce the problem?**
  - Please provide detailed information here, enough for someone else to reprodce your problem.
  - Please no binary (zip, etc) links, fork the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) and push your changes to `GitHub`. (Alternatively use a code sharing service list `Gist` or `Pastebin`).
- **What is the expected output? What do you see instead?**
- **Please provide any additional information below.**
  - A stack trace if available, any Exception information.
  - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
  - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
- **Does this problem also occur in the `Cef` TestApp from http://opensource.spotify.com/cefbuilds/index.html (http://cefbuilds.com for older version)?**
## 

Hi, 
I have been using CefSharp Offscreen for quite a while. With version 53 I'm getting an application crash in disposing the RequestContext object.

Here is the crash dump result:

  Child SP               IP Call Site 
000000b8a7e5e768 00007ffe7e6b1b70 [InlinedCallFrame: 000000b8a7e5e768] .delete(Void_) 
000000b8a7e5e768 00007ffe1512caa5 [InlinedCallFrame: 000000b8a7e5e768] .delete(Void_) 
000000b8a7e5e740 00007ffe1512caa5 DomainBoundILStubClass.IL_STUB_PInvoke(Void_) 
000000b8a7e5e810 00007ffe156392ac .CefStructBase.__vecDelDtor(CefStructBase_, UInt32) 
000000b8a7e5e920 00007ffe747a7fde [InlinedCallFrame: 000000b8a7e5e920]  
000000b8a7e5e920 00007ffe156391d8 [InlinedCallFrame: 000000b8a7e5e920]  
000000b8a7e5e8f0 00007ffe156391d8 CefSharp.RequestContextSettings.!RequestContextSettings() 
000000b8a7e5e9a0 00007ffe15638dd8 CefSharp.RequestContextSettings.Dispose(Boolean) 
000000b8a7e5e9e0 00007ffe15638d8a CefSharp.RequestContextSettings.Dispose() 
000000b8a7e5ea10 00007ffe1513aedb CefSharp.RequestContext.~RequestContext() 
000000b8a7e5ea40 00007ffe1513ae00 CefSharp.RequestContext.Dispose(Boolean) 
000000b8a7e5ea80 00007ffe1513a90a CefSharp.RequestContext.Dispose() 

Thanks.

**Comment by amaitland** [comment]
@maziart Please fill out the bug report above.

**Comment by amaitland** [comment]
Notice to all, I am taking a step back from the project and will no longer be providing support/answering questions. I will consider merging `PR's` that fix a reproducible bug.

**Comment by amaitland** [comment]
Closing due to lack of feedback. A means to reproduce the problem is required (filling out the bug template above also).
