### ISSUE TITLE
Question using CefSharp in an xproj

### ISSUE THREAD

**Issue by MaitreDede** [cefsharp/CefSharp#1840]
Hi,

Since the dotnet core projects (.xproj + project.json) can target the full dotnet framework, I am converting my projects to the new dotnet core project format. But I have a problem doing this with CefSharp, since it add msbuild props and target files.

 - Is it possible to use CefSharp in a dotnet core project targetting the full desktop framework ?
 - If not, is there a possible workaround ?

I don't know if it worth it to start working on it now because of http://ivanz.com/2016/05/17/farewell-project-json-hello-msbuild-and-csproj

**Comment by amaitland** [comment]
@MaitreDede `CefSharp` only produces older style `Nuget` packages currently. I've personally not played around with `xproj`, if it lacks support for `targets` and `props` files then it's not likely to work.

Did you search the topic in general? This issue won't be limited to `CefSharp`.

**Comment by MaitreDede** [comment]
I have not deep searched for this. But I far as I understand, the target and the props are msbuild only. Dotnet core does not behave like msbuild. So no support for taget and props files. So that is why I asked if there can be a workaround. But I think there is no workaround, until someone rewrite the cefsharp nuget integration.

With the article I linked, I don't know how the ```dotnet``` cli tool will behave with the new csproj format. But since I am using Visual Studio, I don't worry until new csproj file format will be out.

**Comment by amaitland** [comment]
> But I think there is no workaround

I'm not aware of a workaround and I've never looked for one as I've not had a need to target `DotNet Core`. 

By all means investigate generating newer style `Nuget` packages.
