### ISSUE TITLE
Is there any version of cefsharp compatible with CEF 3.2357.1291.g47e6d4b ?

### ISSUE THREAD

**Issue by hkjacob** [cefsharp/CefSharp#1842]
What version of the product are you using?
43.0

What architecture x86 or x64?
x86

On what operating system?
Win 7  &  .net 3.5

Are you using WinForms, WPF or OffScreen?
WPF  and WinForms

Description
Is there any version of cefsharp which is compatible with CEF 3.2357.1291.g47e6d4b ?
If no, how could I make my product (C#, .net3.5 WPF) work with CEF 3.2357.1291.g47e6d4b ?

Because of some special reasons , I cannot upgrade the CEF version.

Thanks.

**Comment by jankurianski** [comment]
Github issues are only for reproducible bugs rather than questions - please re-read the issue template.
