### ISSUE TITLE
Popup window scaled on version 53

### ISSUE THREAD

**Issue by khacminh** [cefsharp/CefSharp#1843]
- **What version of the product are you using?**
  Nuget 53.0.0
- **What architecture x86 or x64?**
  Both
- **On what operating system?**
  Win10
- **Are you using `WinForms`, `WPF` or `OffScreen`?**
  WPF
- **What steps will reproduce the problem?**
  - Change display scale greater than 100%, then sign out. On windows 10, you can do it by right click on desktop >> Display settings >> choose Display tab >> drag the slider **Change the size of text, apps, and other items** to value 125% or 150%
  - Open solution downloaded from github. Set project **CefSharp.Wpf.Example** as Start up project
  - Under folder **Handlers**, modify **LifeSpanHandler.cs** like [this](https://gist.github.com/khacminh/d51503a5ad44fdfb61e3be142c2c9697).
  - Run project and try the pop up test (from example window, choose Tests >> Popup Test or Popup Test custom Scheme >> open a popup) 
- **What is the expected output? What do you see instead?**
  - Expected: this [image](https://drive.google.com/open?id=0B9g9TuLjEWYIcERWNkFmTjlwMDA) is a popup window opened when display scale is 100%
  - Unexpected: this [image](https://drive.google.com/open?id=0B9g9TuLjEWYITkdqd3ZxMlpGMkE) is a popup window opened when display scale is 150%

**Comment by khacminh** [comment]
I think I know where the bug comes from. After method `ILifeSpanHandler.OnBeforePopup()` called, the method `renderClientAdapter->CreateBitmapInfo()` (ClientAdapter.cpp) will be called before the event `PresentationSourceChangedHandler` (ChromiumWebBrowser.cs) fires. Therefore, the popup browser will be configured at screen scale 1.0. This will cause the bug when your screen scale is greater than 100%.

In order to overcome this issue, I at the following method to **ChromiumWebBrowser.cs**:

> 
>         public void ParentUpdated()
>         {
>             if (this.Parent != null)
>             {
>                 var windowInteropHelper = new WindowInteropHelper(this.Parent as Window);
>                 //Create the handle Window handle
>                 var handle = windowInteropHelper.EnsureHandle();
> 
>                 source = HwndSource.FromHwnd(handle);
>                 matrix = source.CompositionTarget.TransformToDevice;
>             }
>         }

Then, call it after creating new popup window whose content is the new `ChromiumWebBrowser`

> 
> var popup = new Window
> {
>      Left = windowX,
>      Top = windowY,
>      Width = windowWidth,
>      Height = windowHeight,
>      Content = **chromiumBrowser**,
>      Owner = owner,
>      Title = targetFrameName
> };
> **chromiumBrowser.ParentUpdated();**

Hope this help.

**Comment by amaitland** [comment]
With #2237 `BitmapInfo` has been removed so this is no longer relevant.
