### ISSUE TITLE
LoadingStateChanged is fired multiple times after load

### ISSUE THREAD

**Issue by arvigeus** [cefsharp/CefSharp#1844]
``` cs
private static ChromiumWebBrowser browser;

public static void Main(string[] args)
{
    const string testUrl = "http://varna.studentlife.bg/bg";

    Cef.Initialize(new CefSettings(), performDependencyCheck: true, browserProcessHandler: null);

    browser = new ChromiumWebBrowser(testUrl);

    browser.LoadingStateChanged += BrowserLoadingStateChanged;
    browser.LoadError += BrowserLoadError;

    Console.ReadKey();

    Cef.Shutdown();
}

private static void BrowserLoadError(object sender, LoadErrorEventArgs e)
{
    Console.WriteLine("This is not called");
}

private static void BrowserLoadingStateChanged(object sender, LoadingStateChangedEventArgs e)
{
    if (!e.IsLoading)
    {
        Console.WriteLine("This is called 3 times, why?");
    }
}
```

For some reason this page reports it is loaded 3 times. The only way to stop it is to either remove the event listener, or to call `e.Browser.StopLoad()`. This behavior only happens with that website.

**Comment by amaitland** [comment]
It's important to note that `CefSharp` is just a wrapper around the `Chromium Embedded Framework (CEF)`. Please use http://magpcss.org/ceforum/index.php for generic **CEF** questions. It is best place for this kind of question. Please search before asking your question, it's highly likely your question has already been answered.

**Comment by amaitland** [comment]
Anyone still experiencing this issue should post on http://magpcss.org/ceforum/index.php

The `CEF` event is http://magpcss.org/ceforum/apidocs3/projects/(default)/CefLoadHandler.html#OnLoadingStateChange(CefRefPtr%3CCefBrowser%3E,bool,bool,bool)

To determine which version of CEF your build is running, open `chrome://version` and make note of the `CEF` version. It will look similar to `3.2987.1597.gffc5773`

You'll need to provide a `URL` that reproduces your problem.

Important to remember that `CefSharp` is just a wrapper.

**Comment by samneefs** [comment]
For those interested, I use (a variation of) the following workaround.
I keep track of the number of requests made and only do an action if there is a newer request.
For my case, this seems to work fine. However I can imagine that the browser actually still does something and you would sometimes need to wait for the last time it finishes.

```
`using CefSharp;

class RequestHandler : IRequestHandler
{//left all the irrelevant IRequestHandler methods out of this example code, but you'll need them
    public int NrOfCalls { get; set; }
    public bool OnBeforeBrowse(IWebBrowser chromiumWebBrowser, IBrowser browser, IFrame frame, IRequest request, bool userGesture, bool isRedirect)
    {
        NrOfCalls++;
        return false;
    }
}
public class Handle
{
    private RequestHandler _requestHandler;
    private IWebBrowser _browser;
    private int previousRequestNrWhereLoadingFinished = -1;

    public Handle()
    {
        _requestHandler = new RequestHandler();
        _browser.RequestHandler = _requestHandler;
    }
    private void _browser_LoadingStateChanged(object sender, LoadingStateChangedEventArgs e)
    {
        // Check if page has finished loading
        if (!e.IsLoading)
        {
            //sometimes this is called multiple times for one request, we will only do something if it comes from a newer request than the previous action
            if (previousRequestNrWhereLoadingFinished < _requestHandler.NrOfCalls)
            {
                previousRequestNrWhereLoadingFinished = _requestHandler.NrOfCalls;
                ThisMethodWillOnlyBeCalledOncePerRequest();
            }
        }
    }
}`
```

**Comment by pautnesis** [comment]
thanks samneefs
