### ISSUE TITLE
window.focus() doesn't work

### ISSUE THREAD

**Issue by mschertler** [cefsharp/CefSharp#1845]
- **What version of the product are you using?**
  51.0.0
- **What architecture x86 or x64?**
  x86
- **On what operating system?**
  Win 10
- **Are you using `WinForms`, `WPF` or `OffScreen`?**
  WinForms
- **What steps will reproduce the problem?**

![main-html](https://cloud.githubusercontent.com/assets/7691455/19691819/ee8da94a-9ad5-11e6-9f62-00f0fbcae62b.png)

![popup-html](https://cloud.githubusercontent.com/assets/7691455/19691888/2f28897a-9ad6-11e6-9620-2ac3378d2064.png)

Please see the attached example. It shows a main page that contains a button. When the button is clicked, a popup window is opened and the reference to the window is remembered. When clicking the button for the second time, the focus() method of the popup window is called.

var popup = self.open("...");
popup.focus(); <-- no effect

In all other browsers, including Chromium, calling the focus() function, brings the popup to the front and let's it receive the focus. But inside the ChromiumWebBrowser object of cefsharp, calling focus() has no effect.
- **What is the expected output? What do you see instead?**
  When calling focus(), the popup window should be activated and receive the focus.
  Instead, there is no effect.
- **Please provide any additional information below.**
  Nothing in the debug.log.
- **Does this problem also occur in the `Cef` TestApp from http://opensource.spotify.com/cefbuilds/index.html (http://cefbuilds.com for older version)?**
  Yes, same problem with the test app.

**Comment by amaitland** [comment]
It's important to note that `CefSharp` is just a wrapper around the `Chromium Embedded Framework (CEF)`. Please use http://magpcss.org/ceforum/index.php for generic **CEF** questions. It is best place for this kind of question. Please search before asking your question, it's highly likely your question has already been answered.

**Comment by KhannaB** [comment]
Hi @mschertler  Could you please let me know if you were able to find any solution to this focus observation with child popup window?
I did see some post on CEF forum , but none seemed like a proper solution.

**Comment by amaitland** [comment]
https://bitbucket.org/chromiumembedded/cef/issues/2931/windowfocus-does-not-bring-the-window-to

**Comment by dbuechel** [comment]
We're having the same issue and it does look like there is a pending pull request upstream in CEF; however, no progress has been made there for years. If anyone has any hints or workarounds, sharing them would be greatly appreciated.
