### ISSUE TITLE
Freezing when showing new form

### ISSUE THREAD

**Issue by plhearn** [cefsharp/CefSharp#1846]
- **What version of the product are you using?**
  53.0.0
- **What architecture x86 or x64?**
  x86
- **On what operating system?**
  Win7
- **Are you using `WinForms`, `WPF` or `OffScreen`?**
  WinForms
- **What steps will reproduce the problem?**

Have the same form thats using the browser control try to open another form.
- **What is the expected output? What do you see instead?**

When using the visual studio IE browser control the form displays normally:

http://i.imgur.com/R4YW2kt.png

But when using the cefsharp browser control the form freezes when displayed:

http://i.imgur.com/N0MjDmc.png
- **Please provide any additional information below.**

When the user goes to a certain website it opens a popup window.  This window calls a javascript window.extern call back to the form which opens a new form.  This is working with the default web browser object but the new form freezes for some reason with cefsharp.  I've gone through the FAQ and troubleshooting guide but haven't been able to fix it.  The code I'm using for cefsharp is almost identical to that in the quick start guide.  The only extra thing I'm doing is calling "chromeBrowser.RegisterJsObject("external", this);" to register the form methods.

**Comment by amaitland** [comment]
> Please only open an issue if you have a BUG to report, if you simply have a question or require some assistance keep reading for info. If you do have a BUG to report, please use the Bug Report template below.

Please take the time to read the issue template, if you have a question, ask it on `Gitter`, post on `StackOverflow` or use http://magpcss.org/ceforum/ (for questions specific to `CEF`).

https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

**Comment by amaitland** [comment]
Avoid passing `this` in when you register an object, use a different method. Make sure you open your form on the `UI` thread, not directly in a bound method. Your probably blocking the render process.
