### ISSUE TITLE
Which CefSharp version are compatible with framework 3.5 from nuget?

### ISSUE THREAD

**Issue by RobbiNespu** [cefsharp/CefSharp#1848]
- **What version of the product are you using?**
  - What version are you using? Nuget? CI Nuget? build from a branch? If so which branch?
    I am using nugget
- **What architecture x86 or x64?**
  x86
- **On what operating system?**
  - Win7
- **Are you using `WinForms`, `WPF` or `OffScreen`?**
  Winform
- **What steps will reproduce the problem?**
  I have POS system online and the POS hardware are still using Windows 7. I need CefSharp to work with dot net 3.5

**Comment by rlmcneary2** [comment]
CefSharp currently only supports .Net 4.5.2. There might be older releases out there but I'm not sure if .Net 3.5 was ever supported. You probably need to look at another cef wrapper (ex. cefglue) or make one yourself.

**Comment by amaitland** [comment]
Older versions target `.Net 4.0`, newer `.Net 4.5.2`
