### ISSUE TITLE
CefSharp example does not run on Windows Server 2016

### ISSUE THREAD

**Issue by leonidcan** [cefsharp/CefSharp#1850]
Ver: 53.0
x86 and x64
Windows Server 2016
WinForms and WPF

Built apps in VS2015 and tested them on Windows 10, Windows Server 2012 - all worked
Windows server 2016 nothing happened

Expected to see window with Browser. Nothing happened. App crashed before first line code in the application

debug.log
[1029/144636:ERROR:browser_child_process_host_impl.cc(364)] Terminating child process for bad IPC message of type 786646

**Comment by leonidcan** [comment]
More info: I was able to get access to host machine (my experiment was on Virtual Machine). My sample application works fine on host (through remote desktop), however the problem persists in VM.
My sample applications is minimal web form app with just one browser control on the form. It does work in VM on Windows Server 2012r2. I set dispable-gpu option.

**Comment by leonidcan** [comment]
I managed to run sample in vm. Now I just need to figure out why my app is not running....I will try to update cefsharp  to latest from git (sample from git works)

**Comment by mojinxun** [comment]
do you have some solutions?

**Comment by leonidcan** [comment]
I figured out it does work with the latest version (53 does not work), I was running samples from git/master and my app was using 53 release.

**Comment by mojinxun** [comment]
Have you tried with vm, it doesn't work, crash libcef.dll

**Comment by leonidcan** [comment]
Yes, I can confirm that version from git/master works in 2016 hyper-v VM.

**Comment by mojinxun** [comment]
what about 2012 HVM

**Comment by mojinxun** [comment]
git/master can't run, Cefsharp Library miss cef_base.h

**Comment by leonidcan** [comment]
In 2012 it works with cef release 53, my app was originally worked with 2012 without any problem

🎱 

....zzz went to sleep :)

**Comment by leonidcan** [comment]
Try earlier commits, I am using 7b491fbd3d969f890de65c4a6b7e1e3bc1d41fcb

**Comment by mojinxun** [comment]
thx, I try it

**Comment by mojinxun** [comment]
![8 o6 4 ydy 1gj b2 o243](https://cloud.githubusercontent.com/assets/13127383/20740119/92a9284c-b6fb-11e6-831a-2f6802e955f6.png)

you see, also has the error

**Comment by mojinxun** [comment]
I know, I cant revert the packages...
can you send me the packages ？
