### ISSUE TITLE
issue with calling file dialog through  ExecuteScriptAsync

### ISSUE THREAD

**Issue by zigota** [cefsharp/CefSharp#1851]
Hello everybody, i have an issue with file dialog.
I use CefSharp.Wpf.Example. I opened page which contains file dialog ` <input class="uploader-input" type="file" />`
I tried execute following script in devtools console `$('input.uploader-input').click()` and file dialog are shown.
But when i tried execute this sript through  ExecuteScriptAsync then nothing happened.

**Comment by amaitland** [comment]
> Please only open an issue if you have a BUG to report, if you simply have a question or require some assistance keep reading for info. If you do have a BUG to report, please use the Bug Report template below.

Please take the time to read the issue template, if you have a question, ask it on `Gitter`, post on `StackOverflow` or use http://magpcss.org/ceforum/ (for questions specific to `CEF`).

https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

**Comment by amaitland** [comment]
Your probably executing your JS before the element is available. 

https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#when-can-i-start-executing-javascript

**Comment by wharbi** [comment]
Hi zigota,
I get the same problem.
Have you a solution please ?
Regards,
