### ISSUE TITLE
Subprocess is not killed

### ISSUE THREAD

**Issue by alex-econ** [cefsharp/CefSharp#1852]
At the start of the program is initialize the CefSharp
```
CefSettings settings = new CefSettings();
settings.CefCommandLineArgs.Add("enable-npapi", "1");
Cef.Initialize(settings);
```
Accordingly, when the closing is ShutDown()
`Cef.Shutdown();`

While using the program the user can open one form with CefSharp

```
private ChromiumWebBrowser browser;
private void CreateBrowser()
        {            
            browser = new ChromiumWebBrowser("http://yandex.ru");
            browser.Dock = DockStyle.None;
            browser.Left = 0;
            browser.Top = 0;
            browser.MenuHandler = new MenuHandler();
            this.Controls.Add(browser);
        }
```
When the user closes the form
`browser.Dispose();`

The problem is the number of CefSharp.BrowserSubprocess.exe
When the user runs the program. There is one CefSharp.BrowserSubprocess.
When the user opens a form with a browser, then there is another 2 CefSharp.BrowserSubprocess.
When the user closes the form with your browser, user killed one CefSharp.BrowserSubprocess instead of two.
Why when I open the form it creates two CefSharp.BrowserSubprocess? Not one.
And it depends on which page is loaded. Sometimes it's two CefSharp.BrowserSubprocess, sometimes a one CefSharp.BrowserSubprocess.
Why if create 2 CefSharp.BrowserSubprocess, when close the program killing one?

- **What version of the product are you using?**
    Nuget, 53.0.0

- **What architecture x86 or x64?**
    - x86

- **On what operating system?**
    - Win7 x64

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    -WinForms

- **What steps will reproduce the problem?**
    - Described above

- **What is the expected output? What do you see instead?**
    - I want if create 2 process, killed 2 too

**Comment by amaitland** [comment]
`CEF` uses multiple processes, read https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage#markdown-header-processes
