### ISSUE TITLE
XAML designer Unhandled Exception

### ISSUE THREAD

**Issue by wizcpp** [cefsharp/CefSharp#1853]
- **What version of the product are you using?**
    - NuGet Version: 3.4.4.1321
    - CefSharp.Wpf  53.0.0
    - Visual Studio 2013 update5

- **What architecture x86 or x64?**
   - both x86 and x64 solutions

- **On what operating system?**
    - Win10 64 1607 (OS Build 14393.351)

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - WPF

- **What steps will reproduce the problem?**
    - The Wpf Example [CefSharp.MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) has this issue in my computer.

- **Please provide any additional information below.**
    - An Unhandled Exception has occurred
Click here to reload the designer
Details:
System.IO.FileNotFoundException
Could not load file or assembly 'CefSharp.Core, Version=53.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138' or one of its dependencies. The system cannot find the file specified.
   at CefSharp.Wpf.ChromiumWebBrowser.Dispose(Boolean isDisposing)
   at CefSharp.Wpf.ChromiumWebBrowser.Finalize()

**Comment by amaitland** [comment]
There is no designer support as per https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#Wpf_designer
