### ISSUE TITLE
RegisterJsObject Fail with message "Browser is already initialized..."

### ISSUE THREAD

**Issue by visonjhon** [cefsharp/CefSharp#1856]
Dear Value Team,

I have face a problem with ChromiumWebBrowser RegisterJsObject please help me to check as below :
error message "Browser is already initialized. RegisterJsObject must becalled before the underlying CEF browser is created", while I used CEF Version 53.0.0 with C# Window Form as code below:

```
chromeBrowser = new ChromiumWebBrowser("google.com");
chromeBrowser.Dock = DockStyle.Fill;
chromeBrowser.RegisterJsObject("jsObject", new JsMapInterface());
```

I hope your team can help me with this. Very thanks you in advance!

**Comment by mitchcapper** [comment]
Have you tried moving the register line above the dock.

**Comment by mitchcapper** [comment]
Also if chromeBrowser is instantly bound to a render object try saving it first as a local variable, setting it up, and then setting it to the render object.

**Comment by amaitland** [comment]
> Please only open an issue if you have a BUG to report, if you simply have a question or require some assistance keep reading for info. If you do have a BUG to report, please use the Bug Report template below.

Please take the time to read the issue template, if you have a question, ask it on `Gitter`, post on `StackOverflow` or use http://magpcss.org/ceforum/ (for questions specific to `CEF`).

https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp
