### ISSUE TITLE
RegisterJsObject Fail with message "cannot be used for communication because it is in the Faulted state." 

### ISSUE THREAD

**Issue by visonjhon** [cefsharp/CefSharp#1857]
Dear Value Team,
I have face a problem with ChromiumWebBrowser RegisterJsObject please help me to check as below :
error message is "**The communication object, CefSharp.Internals.BrowserProcessServiceHost, cannot be used for communication because it is in the Faulted state.**", while I used CEF Version 53.0.0 with C# Window Form as code below:
```
CefSettings settings = new CefSettings();
Cef.Initialize(settings);
ChromiumWebBrowser chromeBrowser = new ChromiumWebBrowser("google.com")
{
      Dock = DockStyle.Fill,
};
BoundObject obj = new BoundObject();
chromeBrowser.RegisterJsObject("bound", obj);
```
I hope your team can help me with this. Very thanks you in advance!

**Comment by amaitland** [comment]
Use `RegisterAsyncJsObject` instead, uses native `IPC` instead of `WCF`. Search the code for examples.

In future ask on `Gitter` or `Stackoverflow`.

**Comment by Kazumz** [comment]
Hi @amaitland, I've had the same issue recently.

While I appreciate your explaination here already, could you explain further the differences between WCF and IPC for this particular scenario, and why these do not return the same error?
