### ISSUE TITLE
WPF crashing with open combobox (see original issue #1723)

### ISSUE THREAD

**Issue by skhilliard** [cefsharp/CefSharp#1859]
NOTE: Tried downloading preliminary build that included in commit https://github.com/cefsharp/CefSharp/commit/21b9eb601e3425af10879b2b8619478f059137ca, but the crash still occurs.

What version of the product are you using?
v53
What architecture x86 or x64?
x64
On what operating system?
Windows Server 2012 R2
Are you using WinForms, WPF or OffScreen?
WPF
What steps will reproduce the problem?
Here is a simple html code which will cause the problem in the MinimalExample.WPF. The MinimalExample.Winforms seems to work correctly:
`<html>
<body>

<select>
<option>1</option>
<option>2</option>
<option>3</option>
</select>

</body>
</html>` - Open the combobox on the html page - Move the mouse out of the browser to the windows task bar while the combobox is still open (Moving it to another window also often causes this error) - Move the mouse back to the open combobox - The program crashes with an exception: "An unhandled exception of type 'System.ComponentModel.Win32Exception' occurred in WindowsBase.dll"

**Comment by amaitland** [comment]
Rather than clogging up the issue tracker a simple can this be pleased reopen would have been sufficient.
