### ISSUE TITLE
Browser Control gets white after reconnecting with Remote Desktop

### ISSUE THREAD

**Issue by DanielBretzigheimer** [cefsharp/CefSharp#1861]
- **What version of the product are you using?**
CefSharp.WPF Nuget Package Version 53.0.0

- **What architecture x86 or x64?**
x64

- **On what operating system?**
Windows 10 (Windows 7 works)

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
1. Connect with remote desktop to a Windows 10 PC
2. Open Application with CefSharp Browser Control in foreground and wait until page is loaded (the Minimal Example produces the same error)
3. Close connection to Server
4. Connect again to the same Server
Reproducable with all web pages

- **What is the expected output? What do you see instead?**
Expected: Browser control should show website
Reality: Browser control is completely white

- **Please provide any additional information below.**
A simple resize in any direction will let the control refresh and show the page
The page is sometimes shortly visible after reconnecting and gets blank afterward (maybe some caching from remote desktop)
I also tried setting `disable-gpu-vsync` and `disable-gpu` bot neither helped in this case
CEF debug.log is empty
I found out that sometimes the same problem occurs if I open my application in full screen, but I could not make this reproducable
A workaround for this problem is to change the height and width of the control to a fixed value and afterwards set it back to auto

- **Does this problem also occur in the `Cef` TestApp**
All working in CEF Test Application

**Comment by markmcdowell** [comment]
I have the same issue, tested on Windows 7 and Windows 8 as well. Also tried with 47 and 51 and present in both.

I currently increase the width and height by 1 px and then back again to resolve.

**Comment by amaitland** [comment]
> I currently increase the width and height by 1 px and then back again to resolve.

Try calling `browser.GetHost().Invalidate(PaintElementType.View);` instead.

Someone experiencing this issue will need to download the source, debug and submit a `PR`.

**Comment by DanielBretzigheimer** [comment]
> Try calling browser.GetHost().Invalidate(PaintElementType.View); instead.
Does not work, the problem persists with this line.

**Comment by amaitland** [comment]
> Does not work, the problem persists with this line.

The source is there, good luck 👍

**Comment by umerfaruk** [comment]
My team experienced a similar issue in past with browser getting blank after laptop is docked, un-docked or using remote desktop . 
After investigation we found that the WPF dock panel, hosting the CEF Browser control, was being unloaded and reloaded. Hence browser was never re-drawn in place as it was not in the control hierarchy and a plain background was drawn. We tried to handle the unloaded events on the dock panel and re-add the browser as child item of dock control. It worked nicely.

**Comment by merceyz** [comment]
Tried to reproduce with a Windows Server 2012 R2, instead of getting a blank control the website reloads.

**Comment by AndrewBragdon** [comment]
I am seeing this issue as well.  When you connect to a machine over Remote Desktop that Already Has CefSharp running, all the browsers get detached and become white rectangles.  This is actually a pretty serious issue as it means any RDP connection will kill CefSharp.  Does anyone know why this is happening?

**Comment by AndrewBragdon** [comment]
Thanks for fixing this!  Quick question: when will this fix be available in the stable NuGet release?

**Comment by merceyz** [comment]
See https://github.com/cefsharp/CefSharp/issues/1963#issuecomment-293118852
