### ISSUE TITLE
Events not firing after calling SetAsPopup()

### ISSUE THREAD

**Issue by psowko** [cefsharp/CefSharp#1862]
- **What version of the product are you using?**
53.0.0

- **What architecture x86 or x64?**
x64

- **On what operating system?**
Win7

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms

- **What steps will reproduce the problem?**
When implementing the OnBeforePopup method of ILifeSpanHandler, if I set the newBrowser out parameter to a new ChromiumWebBrowser which has called SetAsPopup() then the events such as LoadingStateChanged no longer fire.  If I comment out the SetAsPopup() call, then events will fire correctly. See code here https://gist.github.com/psowko/038eba175bbcc52a48afddebaf8d9170

- **What is the expected output? What do you see instead?**
The LoadingStateChanged event is not being fired.  I have put a breakpoint inside of the method I have attached to the event.  If I comment out the SetAsPopup() call then the break point is hit.  I expect this breakpoint to be hit when the SetAsPopup() is called

- **Please provide any additional information below.**

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
No

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?

- **Does this problem also occur in the `Cef` TestApp from http://opensource.spotify.com/cefbuilds/index.html (http://cefbuilds.com for older version)?**

**Comment by amaitland** [comment]
Events are not fired for popups, see the source code. Use the relevant handler instead.

**Comment by EricGriffith** [comment]
Please update the documentation on the ChromiumWebBrowser classes and their events to make it clear that events are not fired for popups.

**Comment by szmcdull** [comment]
what handlers to use instead?
