### ISSUE TITLE
Unable to load a specific page in CEFSharp

### ISSUE THREAD

**Issue by Hammerstad** [cefsharp/CefSharp#1866]
Hello
I am unable to load the following URL in CEFSharp: http://strommen.infopunkt.no:5555/#/shopping

- **What version of the product are you using?**
    - 53.0.0 (also tested 37.0.0)

- **What architecture x86 or x64?**
    - Tried both

- **On what operating system?**
    - Win7

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - WPF

- **What steps will reproduce the problem?**
    I have forked the [MinimalExample](https://github.com/Hammerstad/CefSharp.MinimalExample) and [changed the url to a webpage which won't load](https://github.com/Hammerstad/CefSharp.MinimalExample/commit/64fecf896ca14546f70b0aca27feb145fa47230f) (It loads fine using Chrome or Opera). Clone the project and run the WPF example.

- **What is the expected output? What do you see instead?**
I would like to see the web page rendered (http://strommen.infopunkt.no:5555/#/shopping). If you open that page in a web browser (except IE) it renders just fine. Instead I see a completely white page (like about:blank) inside the CEFSharp minimal example.

- **Please provide any additional information below.**
    No stack trace, no log in Debug.log, not doing anything fancy (as far as I know).

- **Does this problem also occur in the `Cef` TestApp from http://opensource.spotify.com/cefbuilds/index.html (http://cefbuilds.com for older version)?**

    Yes. I got an errormessage:

```
Page failed to load.

URL: http://strommen.infopunkt.no:5555/#/shopping
Error: ERR_TOO_MANY_REDIRECTS (-310)
```

**Comment by mitchcapper** [comment]
as this is an issue in the native cefclient you should file the bug there and close this ticket.  The site itself does behave poorly:
Resolving strommen.infopunkt.no (strommen.infopunkt.no)... 78.47.130.150
Connecting to strommen.infopunkt.no (strommen.infopunkt.no)|78.47.130.150|:5555... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /kiosk/set?id=1 [following]
--2016-11-18 14:34:32--  http://strommen.infopunkt.no:5555/kiosk/set?id=1
Reusing existing connection to strommen.infopunkt.no:5555.
HTTP request sent, awaiting response... 302 Found
Location: /kiosk/check-kiosk [following]
--2016-11-18 14:34:32--  http://strommen.infopunkt.no:5555/kiosk/check-kiosk
Reusing existing connection to strommen.infopunkt.no:5555.
HTTP request sent, awaiting response... 302 Found
Location: / [following]
--2016-11-18 14:34:32--  http://strommen.infopunkt.no:5555/
Reusing existing connection to strommen.infopunkt.no:5555.
HTTP request sent, awaiting response... 200 OK

It gives you a 301, then redirects you then sends you back to a permanent redirect page.  For what it is worth it does NOT work in chrome either visiting http://strommen.infopunkt.no:5555/

This is not a CEFSharp issue.
