### ISSUE TITLE
SendKeyEvent problem with "DOT"

### ISSUE THREAD

**Issue by netmaxik** [cefsharp/CefSharp#1869]
- **What version of the product are you using?**
cef.redist.x86.3.2840.1493 , CefSharp.WinForms.55.0.0-CI2064 

- **What architecture x86 or x64?**
x86

- **On what operating system?**
    Win10

- Using WinForms

In my project I need to send string using 
web.GetBrowser().GetHost().SendKeyEvent(keyEvent);

Everything good except on symbol - '.' (dot )
I do following for it :

KeyEvent keyEvent = new KeyEvent();
keyEvent.Type = KeyEventType.KeyDown;
keyEvent.Modifiers = CefEventFlags.IsKeyPad;
keyEvent.WindowsKeyCode = 110;
web.GetBrowser().GetHost().SendKeyEvent(keyEvent);

keyEvent.Type = KeyEventType.Char;
keyEvent.WindowsKeyCode = 46;
web.GetBrowser().GetHost().SendKeyEvent(keyEvent);

keyEvent.Type = KeyEventType.KeyUp;
keyEvent.WindowsKeyCode = 110;
web.GetBrowser().GetHost().SendKeyEvent(keyEvent);

Application.DoEvent();

It types "DOT" and browser freezing after this.
It is not happened every time, but in 80% .

May be I do something wrong?
But I really need to send SendKeyEvent.

**Comment by amaitland** [comment]
It's important to note that `CefSharp` is just a wrapper around the `Chromium Embedded Framework (CEF)`. Please use http://magpcss.org/ceforum/index.php for generic **CEF** questions. It is best place for this kind of question. Please search before asking your question, it's highly likely your question has already been answered.

--
Adding debugging to the `WPF` version and work out what is required to send the key events you require.

I have no idea why you'd be sending a char in between a key down/up combination.

**Comment by juepiezhongren** [comment]
@netmaxik ,hello
Could u show me a demo about using SendKeyEvent?
I am confused with it a lot.
Beg for ur help!

**Comment by netmaxik** [comment]
Hi

You need just procedure ?

I did it for my tasks so may be not suitable for you :)

Regards
Maxim
