### ISSUE TITLE
Browser display simply blank (first step in trying out CefSharp)

### ISSUE THREAD

**Issue by corist** [cefsharp/CefSharp#1870]
Visual Studio Community 2013, 2015 (tried both)
Nuget method and Package Manager console method (both tried)
C# and VB (tried both)
Windows 10 64-bit

I followed all available beginner's examples, all showed blank webbrowser, none worked on my computer -
Create a .NET 4.5 project (also tried 4.5.2)
set the project to x64
when the project is opened, Nuget or PM install CefSharp.WinForms (tried both)
Add a panel to dock in my WinForm
Add code to initialize CEF 
Add code to attach Chrome browser to a panel
Complie and run
But the panel is initially grey, then turned white, and it remained blank forever. 

I have checked that in the output directory all Cef files and the locales sub-directory are there. 
I have inserted a button to activate DevTools which popped up OK but it is also blank. 

Cef initialization seemed to be OK (flag returned OK value)
Browser when adding interrupt handler for finished initializing did generate the correct interrupt (break point inserted)

**Comment by shawty** [comment]
Just to confirm, this also happens on windows 7 64 bit with the current NuGet version.

Set the actuaql build to 64bit and blank to.

However, set the actual build to 32bit and all works correctly as expected.

When running the 64bit build, we do occasionally get a crash box too:

![image](https://cloud.githubusercontent.com/assets/1876454/20644353/3010a4e6-b429-11e6-89d1-692e7f028437.png)

Even when the crash occurs however, CEF still tries to load and initialise

![image](https://cloud.githubusercontent.com/assets/1876454/20644360/98aa7a5e-b429-11e6-9ac0-db23cb9ecb1c.png)

Build is winforms, under Visual Studio 2013.  Previous versions don't exhibit this behavior.

Code is as follows

`    using System.Windows.Forms;
    using CefSharp;
    using CefSharp.WinForms;
    
    namespace CEFSharp_Intercept
    {
      public partial class FrmMainForm : Form
      {
        private ChromiumWebBrowser _chromeBrowser;
    
        public FrmMainForm()
        {
          InitializeComponent();
          InitializeChromium();
        }
    
        private void InitializeChromium()
        {
          CefSettings settings = new CefSettings();
          Cef.Initialize(settings);
    
          //_chromeBrowser = new ChromiumWebBrowser("");
          //_chromeBrowser.LoadHtml("<html><body><h1>Hello world!</h1></body></html>", "http://example/");
    
          _chromeBrowser = new ChromiumWebBrowser("http://localhost/");
    
          PnlBrowser.Controls.Add(_chromeBrowser);
          _chromeBrowser.Dock = DockStyle.Fill;
    
          _chromeBrowser.IsBrowserInitializedChanged += ChromeBrowserIsBrowserInitializedChanged;
        }
    
        void ChromeBrowserIsBrowserInitializedChanged(object sender, IsBrowserInitializedChangedEventArgs e)
        {
          _chromeBrowser.ShowDevTools();
        }
    
        private void FrmMainFormFormClosing(object sender, FormClosingEventArgs e)
        {
          Cef.Shutdown();
        }
    
        private void button1_Click(object sender, System.EventArgs e)
        {
          _chromeBrowser.Load("http://google.co.uk/");
        }
    
      }
    }
`

**Comment by shawty** [comment]
Also looks like this report is the same issue:

http://stackoverflow.com/questions/40553140/cefsharp3-winforms-x64-shows-blank-page-but-x86-works

**Comment by shawty** [comment]
Update:

Trying the same project in VS2015 resulted in exactly the same behavior, however, setting the .NET build to 4.6 rather than 4.6.1 (Which was my default) and changing the CefSharp version from 53 to 51 resolves the issue and allows both X64 and X86 to work as expected.

Iv'e not done any source level analysis yet, and I'm unlikely to get any time to do so, but those are my findings for now.

**Comment by amaitland** [comment]
> **Known Issues**
> -  When running on older CPUs that don't support vmovaps your application will crash. This only affects x64 builds see #1819 for details. Either use an x86 build or rollback to a previous version for now.

https://github.com/cefsharp/CefSharp/releases/tag/v53.0.0

**Comment by shawty** [comment]
Ah, good to know... Thanks.

**Comment by keepWalking** [comment]
Is there any workaround for newer version (eg. v67.0) for x64 build?
