### ISSUE TITLE
ContextMenu can't hiding in the Touch state

### ISSUE THREAD

**Issue by ccnucheng** [cefsharp/CefSharp#1871]
- **What version of the product are you using?**
    - Nuget 49.0.1

- **What architecture x86 or x64?**
    - both

- **On what operating system?**
    - Win7,Win10?

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - WinForms

- **What steps will reproduce the problem?**
    - Run the CefSharp.WinForms.Example
    - Long touch the web page,show the contextmenu
    - touch the other area,the contextmenu can't hiding

**Comment by amaitland** [comment]
Issue raised `upstream` at https://bitbucket.org/chromiumembedded/cef/issues/2059/contextmenu-cant-hiding-in-touch-model

Will need to be fixed in `CEF`.
