### ISSUE TITLE
How to speed up the winform browser controls frist load?

### ISSUE THREAD

**Issue by orange-pig** [cefsharp/CefSharp#1873]
I using the CefSharp with version 51.0.0.0 in my winform application's configration windows , always when I open a configration window frist, the browser load slowly.How to speed up the winform browser controls frist load? Like pre-init or some others...
If the class 'Cef' has a func make cache be invoked on my application loading, it is wonderful I think.

**Comment by amaitland** [comment]
It's important to note that `CefSharp` is just a wrapper around the `Chromium Embedded Framework (CEF)`. Please use http://magpcss.org/ceforum/index.php for generic **CEF** questions. It is best place for this kind of question. Please search before asking your question, it's highly likely your question has already been answered.

**Comment by amaitland** [comment]
> Please only open an issue if you have a BUG to report, if you simply have a question or require some assistance keep reading for info. If you do have a BUG to report, please use the Bug Report template below.

https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md
