### ISSUE TITLE
Force Cefsharp.WPF to render on a larger Viewrect result in empty bitmap

### ISSUE THREAD

**Issue by Yangff** [cefsharp/CefSharp#1874]
1. I'm using WPF version on Winforms (for taking screenshot) 
2. I've changed ViewRect when I taking screenshot so I can get a screenshot of full page.
3. If the page is big (2000px (width) * 10000px (height), it can result in a Bitmap that only have the first screen (I guess) and other area is totally empty (r=g=b=a=0).

That's to say, if I use following code in `Rendering`, I will never get the bitmap. (result/Width(Height) is DPI fixed SIze)
```cs
                if (e.BitmapInfo.Height == resultHeight && e.BitmapInfo.Width == resultWidth)
                {
                    if (bmp != null)
                    {
                        try
                        {
                            if (bmp.GetPixel(resultWidth - 1, resultHeight - 1).A == 255)
                                _snapshotIsComplete.Set();
                        }
                        catch { }
                    }
                }
```

4. I've tried to reduce the height of the page, for example, the Bitmap's height should less than 5000, and under this condition, some page can have correct bitmap captured while some can not.)

**Comment by amaitland** [comment]
Use the OffScrren version to troubleshoot your problem. 

Please read https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by amaitland** [comment]
Closing due to lack of feedback. If there is a problem in `CefSharp` this can be reopened, more likely the issue is with `CEF` handling really large sizes.
