### ISSUE TITLE
Cannot inject script due to CSP (WPF Version)

### ISSUE THREAD

**Issue by Yangff** [cefsharp/CefSharp#1875]
Looks like this happens on WPF version only. 

When injecting script into some website, `EvaluateScriptAsync` returns following error message.

```
"Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: \"script-src assets-cdn.github.com\".\n\n@ undefined:0:0"
```

It's wired why a browser level script have anything to do with the Server-side Security Policy. These check should be ignored.

**Comment by amaitland** [comment]
It's important to remember that `CefSharp` is just a wrapper around the `Chromium Embedded Project (CEF)`. The CSP restrictions only apply if you evaluate your script, if you simply execute JavaScript then the restrictions don't apply. 

A change was made to CEF recently which removes this restriction, changes have already been applied to master
https://bitbucket.org/chromiumembedded/cef/issues/2024/allow-cefv8context-eval-to-bypass-content

**Comment by amaitland** [comment]
Changes will be in `55.0.0`, please consider donating to fund the release, see #1893
