### ISSUE TITLE
Is WebGL supported on Cefsharp.Winform Version

### ISSUE THREAD

**Issue by cugbboy** [cefsharp/CefSharp#1881]
Hi everyone,

I'm a new developer of Cefsharp. As we know,the WegGL is supported in Cefsharp wpf version.But I didn't see any articles discussed how to use it in winform version. I have test an old version of Cersharp Winform and I found WebGL is not supported.

So,the WebGS is it supported in the latest version in Winform the same as in wpf?

Thank you.

**Comment by amaitland** [comment]
> Please only open an issue if you have a BUG to report, if you simply have a question or require some assistance keep reading for info. If you do have a BUG to report, please use the Bug Report template below.

Please take the time to read the issue template, if you have a question, ask it on `Gitter`, post on `StackOverflow` or use http://magpcss.org/ceforum/ (for questions specific to `CEF`).

https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

**Comment by amaitland** [comment]
Yes, WebGl is supported. It should just work unless Chromium doesn't like your graphics card. Check the debug.log file
