### ISSUE TITLE
C# call a js to set a input which type is hidden with a 10M size string，and cefsharp become all white

### ISSUE THREAD

**Issue by DoubleFooker** [cefsharp/CefSharp#1883]
- **What version of the product are you using?**
    - What version are you using? Nuget? CI Nuget? build from a branch? If so which branch?
     e.g. 49  from nuget
 
- **What architecture x86 or x64?**
    x86
- **On what operating system?**
    - Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WinForms
- **What steps will reproduce the problem?**
    - a javascript like that：
```
 function addPic(obj){
document.GetElementById("pic1").value=obj;
document.GetElementById("pic2").value=obj;
document.GetElementById("pic3").value=obj;
document.GetElementById("pic4").value=obj;
document.GetElementById("pic5").value=obj;
}
```
html is that:
```
<html>
<head>
	<title></title>
</head>
<body>
<div>something</div>
<input type="hidden" id="pic1">
<input type="hidden" id="pic2">
<input type="hidden" id="pic3">
<input type="hidden" id="pic4">
<input type="hidden" id="pic5">
</body>
</html>
```

c# call js:
`wb.ExecuteScriptAsync("addPic("+a string with 10Mb size+")"); 
` 
- **What is the expected output? What do you see instead?**
   nothing
- **Please provide any additional information below.**
    -none

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
   -none
    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
   only cefsharp
- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html (http://cefbuilds.com for older version)?**

    - To compare with WPF run cefclient --multi-threaded-message-loop --off-screen-rendering-enabled
    - To compare with WinForms run cefclient --multi-threaded-message-loop
    - If you can reproduce the problem with `cefclient` then you'll need to report the bug on https://bitbucket.org/chromiumembedded/cef/overview there is no point opening an issue here. (Make sure you search before opening an issue)

**Comment by amaitland** [comment]
Your probably crashing the render process. Basically avoid sending such large files as strings. Load your images using a standard request and fulfil them using a `ResourceHandler`. Search the source (or use `Google`) to find examples.
