### ISSUE TITLE
Cef.redist.x64.3.2785.1482 package deploys the x86 version of d3dcompiler_43.dll in x64 builds

### ISSUE THREAD

**Issue by StephenLucas** [cefsharp/CefSharp#1888]
- Nuget 53.0.0
- x64
- Win10
- WPF 

- The x86 version of d3dcompiler_43.dll (2057Kb) is included in both the x86 and the x64 CEF redistributable packages. As I understand it this dll would only get used on 64bit WinXP, so this issue will go unnoticed in most scenarios except when you are actually using d3dcompiler_43.dll in your application and the build order causes the cef.redist package to overwrite the correct x64 version of the dll with it's x86 version.

- The x64 version of d3dcompiler_43.dll (2467Kb) should be included in the 64bit redist (or the dll could be removed entirely if WinXP x64 is not a supported platform for CefSharp?)

**Comment by amaitland** [comment]
Needs to be removed from https://bitbucket.org/chromiumembedded/cef/src/edbfb207b89b098238a72d0314ef71fe86f2b56c/cmake/cef_variables.cmake.in?at=2883&fileviewer=file-view-default#cef_variables.cmake.in-415

The `Nuget` packages simply copies every `dll`, see https://github.com/cefsharp/cef-binary/blob/master/NuGet/cef.redist.nuspec#L18

There is no `Windows XP` support, so it's safe to remove. If it really annoys you then submit a `PR` against https://github.com/cefsharp/cef-binary that excludes the file.
