### ISSUE TITLE
Black Lines when using CefSharp.WinForms in a WPF WindowsFormHost

### ISSUE THREAD

**Issue by RichiCoder1** [cefsharp/CefSharp#1889]
- **What version of the product are you using?**
  - CefSharp.Common, CefSharp.Wpf, CefSharp.WinForms all version 53.

- **What architecture x86 or x64?**
  - x86

- **On what operating system?**
    - Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
  - WinForms & WPF

- **What steps will reproduce the problem?**
  - Forked project here: https://github.com/RichiCoder1/CefSharp.MinimalExample
  - Run CefSharp.WpfAndWinForms
  - Slowly resize the window. Notice the black line at the bottom of the browser window appear and disappear.

- **What is the expected output? What do you see instead?**
  - Expected: ![Expected](http://i.imgur.com/BU01wrm.png)
  - Actual: ![Actual](http://i.imgur.com/Mo8kOs9.png)
Note the black line between the bottom bar and the browser (and ignore the black outlines, that just my terrible screenshotting)

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html (http://cefbuilds.com for older version)?**
  - Honestly not sure how to test this.

I realize this isn't a hugely well supported scenario, but it's the only was to have the browser content be accessibility friendly in WPF. I notice that when I resize the Window, or unload the control containing the browser, there will be a flash of black, so this may just be a flaw or shortcoming of WindowsFormHost. I can't seem to find anyone else using WindowsFormHost having the black outline issue.

**Comment by amaitland** [comment]
How does Chrome behave on your system? What about the WinForms example? You can defer updates until resize has completed if that's preferable. 

Have you tried on different hardware? 

Is this a bug in CefSharp? Probably not, you can always use CefGlue or ChromiumFx for comparison. They're all just wrappers around the Chromium embedded framework.

**Comment by RichiCoder1** [comment]
>How does Chrome behave on your system? 

Chrome behaves perfectly, which is part of the reason I'm baffled.

>What about the WinForms example? You can defer updates until resize has completed if that's preferable.

I thought the WinForms example was fine, but it has the faint black lines when resized to certain sizes too. 

> Is this a bug in CefSharp? Probably not, you can always use CefGlue or ChromiumFx for comparison. They're all just wrappers around the Chromium embedded framework.

I'll pull or throw together a basic test app using one of those and see what I turn up.

**Comment by RichiCoder1** [comment]
>> Have you tried on different hardware?

>Nope, will do that now.
>
>Edit: Pulled it up on my surface, and ran into the same behavior.

And I think that helped me figure it out. Pulling it up on my surface or 4k shows the issue, pulling it up on the unscaled 1080p doesn't. I think it's a scaling issue.

**Comment by amaitland** [comment]
You may need to add https://github.com/RichiCoder1/CefSharp.MinimalExample/blob/master/CefSharp.MinimalExample.WinForms/Program.cs#L16 and restructure your code so it's the very first thing called

**Comment by RichiCoder1** [comment]
No dice. Still getting black outlines.

**Comment by amaitland** [comment]
If cefclient works and the WinForms example has a problem then you'll have to dig through the source.

**Comment by amaitland** [comment]
Running on my Surface Pro at 150% and I get black lines when resizing Chrome as well, pretty much looks exactly the same as running your example. 

Using Windows 10 Pro (10.0.10240 Build 10240)

**Comment by Antonyo** [comment]
I can also recreate it even at 100%, same scenario using an embedded winform browser in WPF. 

_Only if gpu is enabled_, if running with gpu disabled no black lines are visible.

**Comment by RichiCoder1** [comment]
Hmmm. Killing of GPU wouldn't be a huge issue for us since we're mostly rendering lightweight documents, but at least that narrows down where the issue is...

**Comment by merceyz** [comment]
This is most likely because the WPF control uses `double` for its width and height, while WinForms uses `int`.

A workaround would be to have the browser instance always be 1 pixel larger than your `WindowsFormHost`

**Comment by amaitland** [comment]
> This is most likely because the WPF control uses double for its width and height, while WinForms uses int.

Interesting hypothesis!

> This issue is also present in CefSharp.Wpf.Example, instead of black lines you can see the background

`CEF` uses `int` for it's width and height, so there is also some rounding inaccuracies when `double` is cast to `int`.

**Comment by merceyz** [comment]
This issue can't be fixed, a workaround can be found in my comment above https://github.com/cefsharp/CefSharp/issues/1889#issuecomment-281741492
