### ISSUE TITLE
Crash in OnJSDialog

### ISSUE THREAD

**Issue by jeoware** [cefsharp/CefSharp#1891]
OnJSDialog
suppressMessage = true;
return true; // which was my mistake! Should be return false;
causes the following website to crash with an unhandled exception.
http://www.washingtonexaminer.com/report-820000-criminal-illegals-84-with-felonies-serious-misdemeanors/article/2609915
-- Although not a bug, it did take me time to figure that the return was wrong. Exceptions should always be handled. - Windows says "Program has stopped working" with debugger prompt.
-- Seems you have to scroll. When the advertisement changes location to the bottom right, it aborts.

- **What version of the product are you using?**
WinForms 51.0 - also occurs in other versions
    - What version are you using? Nuget? CI Nuget? build from a branch? If so which branch?
e.g. 47.0.3
51.0.0
- **What architecture x86 or x64?**
x86
- **On what operating system?**
    - Win7, Win 8, Win10, etc?
Win10
- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms
- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.
Use this class extension:
public class JsDialogHandler : IJsDialogHandler
        {

        public bool OnJSDialog(IWebBrowser browserControl, IBrowser browser, string originUrl, CefJsDialogType dialogType, string messageText, string defaultPromptText, IJsDialogCallback callback, ref bool suppressMessage)
            {
            suppressMessage = true;
            return true;  // THIS IS THE LINE THAT CAUSES A CRASH. If return false; the problem does not occur.
            }
With return true; go to 
http://www.washingtonexaminer.com/report-820000-criminal-illegals-84-with-felonies-serious-misdemeanors/article/2609915
- Wait for the video to load and scroll down the page. A popup, which is displayed when return false; is not displayed, rather the program aborts.
    
    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)

Debug log -- but it may not really apply.
[1217/212146:ERROR:gpu_video_decode_accelerator.cc(362)] HW video decode not available for profile 11
[1217/212156:ERROR:ipc_channel_win.cc(519)] pipe error: 232

No Exception information. Just a "Program has stopped working"

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html (http://cefbuilds.com for older version)?**

Minimal example does not use this hook.

Thanks. CEF is a very stable, memory leak free application. I found another bug in v53.0.0 of Winforms, where a couple of websites were not formatted properly. I've tested hundreds of news sites, thousands of links.

**Comment by merceyz** [comment]
The crash happens in CEF, not CefSharp.

Take a look at this [issue](https://bitbucket.org/chromiumembedded/cef/issues/2056/memory-access-exception)

**Comment by amaitland** [comment]
Crashing is far from ideal,  did you read the doco? https://github.com/cefsharp/CefSharp/blob/master/CefSharp/IJsDialogHandler.cs#L23

Ideally this would have been fixed in CEF, it appears to have been marked won't fix.

If you feel strongly enough that this needs to be fixed in CefSharp then by all means submit a PR.

For now closing this as upstream.

**Comment by jeoware** [comment]
Leave it as it is, at least there's a way to search for the issue, so others can find it.
