### ISSUE TITLE
How to use GetElementByID?

### ISSUE THREAD

**Issue by PrinceFroggy** [cefsharp/CefSharp#1895]
I have the following code which would be for the normal webBrowser native .net control.

`
        #region Variable

        public HtmlElement SupremeSize;
        public HtmlElement SupremeAddButton;
        public HtmlElement SupremeCart;
        public HtmlElement SupremeCartAddress;
        public HtmlElement SupremeState;
        public mshtml.HTMLSelectElement SupremeCountry;
        public HtmlElement SupremeCartCC;
        public HtmlElement SupremeType;
        public HtmlElement SupremeMonth;
        public HtmlElement SupremeYear;
        public HtmlElementCollection SupremeTerm;
        public HtmlElement SupremeProcessButton;

        #endregion

        private void webBrowser1_DocumentCompleted(object sender, WebBrowserDocumentCompletedEventArgs e)
        {
            try
            {
                SupremeSize = webBrowser1.Document.GetElementById("size");
                SupremeAddButton = webBrowser1.Document.GetElementById("add-remove-buttons");
                SupremeCart = webBrowser1.Document.GetElementById("cart");
                SupremeCartAddress = webBrowser1.Document.GetElementById("cart-address");
                SupremeState = webBrowser1.Document.GetElementById("order_billing_state");
                SupremeCountry = (mshtml.HTMLSelectElement) webBrowser1.Document.GetElementById("order_billing_country").DomElement;
                SupremeCartCC = webBrowser1.Document.GetElementById("cart-cc");
                SupremeType = webBrowser1.Document.GetElementById("credit_card_type");
                SupremeMonth = webBrowser1.Document.GetElementById("credit_card_month");
                SupremeYear = webBrowser1.Document.GetElementById("credit_card_year");
                SupremeTerm = webBrowser1.Document.GetElementsByTagName("div");
                SupremeProcessButton = webBrowser1.Document.GetElementById("pay");
            }
            catch (Exception) { }
        }`

How would I convert this when using the CEFSharp WinForms ChromiumWebBrowser?

Thanks.

**Comment by amaitland** [comment]
> Please only open an issue if you have a BUG to report, if you simply have a question or require some assistance keep reading for info. If you do have a BUG to report, please use the Bug Report template below.

Please take the time to read the issue template, if you have a question, ask it on `Gitter`, post on `StackOverflow` or use http://magpcss.org/ceforum/ (for questions specific to `CEF`).

https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

**Comment by amaitland** [comment]
Posting on http://stackoverflow.com/questions/41249856/cefsharp-winforms-getelementbyid was sufficient.

There is no direct mapping of code, read the `FAQ` for how to execute JavaScript, bind an object. Search `stackoverflow`, others have asked similar questions.
