### ISSUE TITLE
target=_blank does not open in New Tab

### ISSUE THREAD

**Issue by sohaibameen** [cefsharp/CefSharp#1896]
I am working with CEFSharp 49.0.1.0 version to create  a browser.

It has been working fine but now there is some issue while opening links in new tab.

link with [a target="_blank"] does not open in new tab. I have seen a somebody suggested to update the code OnBeforePopup() and provide browserControl.Load(targetUrl);  return true; 

but It opens the link with blank target in the same parent tab. 
How can I work this around to open it into new tab?

I would appreciate your help on it.

Thank you! 
Sohaib

**Comment by joe-williams-cccu** [comment]
I'm not able to replicate this in `53.0.0` or `51.0.0` so perhaps an upgrade is in order?

Here's how I handle new tabs in `CefSharp` using `53.0.0`

I declare my own event in `LifespanHandler` (`public event EventHandler OpenInNewTab;`) then in the `bool ILifeSpanHandler.OnBeforePopup` method I simply invoke the event, like so `OpenInNewTab?.Invoke(this, new NewTabEventArgs(targetUrl));`  `NewTabEventArgs` is a simple class deriving from `EventArgs` with one string property that houses the target URL. Then you just need to hook onto the `OpenInNewTab` event where you instantiate `LifespanHandler`. E.g. `lifespanHandler.OpenInNewTab += LifespanHandler_OpenInNewTab;` 

Obviously this depends on your design, but I hope it helps in some way.
