### ISSUE TITLE
form with target=_blank can not post the fields data in new tab

### ISSUE THREAD

**Issue by sssjmh** [cefsharp/CefSharp#1899]
I am working with CEFSharp 53.0.1.0 version to create a browser.

It has been working fine but now there is some issue while opening links in new tab.

from with target="_blank"  post to a new tab page , in new page can not receive the post fields data

eg:

there is a form with target='_blank' and action='b.aspx' in page a.aspx, after the form submit , in b.aspx can not receive the fields data 
How can I work this in new tab page not new popup window

I would appreciate your help on it.

Thank you!
sssjmh

**Comment by amaitland** [comment]
> Please only open an issue if you have a BUG to report, if you simply have a question or require some assistance keep reading for info. If you do have a BUG to report, please use the Bug Report template below.

Please take the time to read the issue template, if you have a question, ask it on `Gitter`, post on `StackOverflow` or use http://magpcss.org/ceforum/ (for questions specific to `CEF`).

https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

**Comment by amaitland** [comment]
https://gist.github.com/amaitland/aa976285407ba35cf895c67c614ba82c#popups

**Comment by CasperMXP** [comment]
@sssjmh  Has the problem been solved?
