### ISSUE TITLE
Flash content doesn't go "offscreen" when program is minimized (leads to high cpu usage).

### ISSUE THREAD

**Issue by RadarNyan** [cefsharp/CefSharp#1900]
When there's CPU sensitive flash content playing on a web page, the cef subprocess for ppapi would consume a lot cpu usage (which is normal) but if I minimized the program while the flash content is still playing, the cpu usage doesn't drop. (cpu usage would drop if I'm using C# WebBrowser control)

This behavior is described on Adobe's site:

> To optimize CPU and battery usage, Flash Player 10.1 introduces a new feature on related to inactive instances. This feature allows you to limit CPU usage by pausing and resuming the SWF file when content goes off and on the screen. With this feature, Flash Player releases as much memory as possible by removing any objects that can be recreated when the playing of content is resumed. Content is considered offscreen when the entire content is offscreen.
> 
> Two scenarios cause the SWF content to be offscreen:
> 
>     The user scrolls the page and causes the SWF content to move offscreen.
> 
>     In this case, if there is any audio or video playback, content continues to play, but rendering is stopped. If there is no audio or video playing, to ensure that the playback or ActionScript execution is not paused, set the hasPriority HTML parameter to true. However, keep in mind that SWF content rendering is paused when content is offscreen or hidden, regardless of the value of the hasPriority HTML parameter.
> 
>     A tab is opened in the browser, which causes the SWF content to move to the background.
> 
>     In this case, regardless of the value of the hasPriority HTML tag, the SWF content is slowed down, or throttled, to between 2 and 8 fps. Audio and video playback is stopped and no content rendering is processed unless the SWF content becomes visible again.

I've tried to use Google Chrome and it works just fine. Either switching to another tab or minimizing Chrome will reduce cpu usage to a pretty low level.

---

I'm using the latest version of CefSharp.WinForms (at the moment 53.0.1, CEF: 3.2785.1486.g8c4ba9f Chromium: 53.0.2785.116)

I've tried to search for this issue but doesn't seem to find any solution. The phase "offscreen" is not related to CEF but a Flash feature (as I quoted above) I believe this issue is rather easy to reproduce, just create a browser, enable flash, and visit any site with a flash content (may consume a lot cpu, like games) and minimize the program.

**Comment by amaitland** [comment]
### How do I investigate my issue further?

It's important to remember that `CefSharp` is just a wrapper around the `Chromium Embedded Project (CEF)`, the upstream [`CEF` forum](http://magpcss.org/ceforum/) is a valuable resource. Also `CEF` has it's own [Issue Tracker](https://bitbucket.org/chromiumembedded/cef/issues). Please take the time to research your own problem, including `Googling`, searching on `ceforum`, etc.

--
#### Finding more info
- Have you checked the `Debug.log` file? (Should be located in your apps executing folder by default)
- Have you googled the error message your seeing? (Don't just google the whole thing, try googling just the keywords and possibly add `chromium` as a keyword).
- Are you able to reproduce the problem using `cefclient`? (`cefclient` is the reference implementation provided by `CEF`)
- Need more help debugging? Check the [Troubleshooting Guide](https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting)
- Are you using the latest version? Check the [Release Branches](https://github.com/cefsharp/CefSharp#release-branches) table to determine if the version your using is supported. 

--
#### How do I download `cefclient`?

- Firstly identity which version of `CEF` your actually using, easiest way is to check your `packages.config` file, look for the `cef.redist.x86` package, it's version will be something like `3.2526.1362`, that's the exact version of `CEF` you'll need to download for comparison. You can also open `chrome://version` in the browser to determine the version.
- Open http://opensource.spotify.com/cefbuilds/index.html (http://cefbuilds.com for older version) in a web browser
- Locate the exact `Branch` you require, for the example above the branch is `2526`, all the versions follow a similar pattern
- Locate the `Windows 32bit` or `Windows 64bit` item, if you don't see the exact version, then click `more revisions`
- Download **Test App**
- Are you using `WPF/Offscreen` or `WinForms`? 

**This next part is key**
- To compare with WPF/OffScreen run `cefclient --multi-threaded-message-loop --off-screen-rendering-enabled`
- To compare with WinForms `cefclient --multi-threaded-message-loop`

**Comment by RadarNyan** [comment]
@amaitland Thanks for the quick reply, I've added more information on top.

**Comment by amaitland** [comment]
You need to download cefclient and attempt to reproduce the problem. Likely needs to be fixed in CEF. 

Please read the info I've posted in detail.

**Comment by RadarNyan** [comment]
@amaitland I tried cef client 3.2785.1485 (I can't find .1486 so I went with the nearest one) I started it with `--enable-system-flash=1` and tried to visit a flash site, try to minimize the program and cpu usage drops as expected.

I followed the example of CefSharp to create my program, basically like this:
```c#
Browser = new ChromiumWebBrowser(url);
this.SizeAdjuster.Controls.Add(Browser);
Browser.Dock = DockStyle.Fill;
```
(`this.SizeAdjuster = new System.Windows.Forms.Panel();`)

What am I doing wrong?

**Comment by amaitland** [comment]
Test with multi threaded message loop command line argument, it's listed above. 

If it works correctly the you'll have to investigate further as to what's required.

**Comment by RadarNyan** [comment]
@amaitland No it doesn't work correctly, CPU usage stays unchanged when I minimize/restore the program. Also I didin't have to use this argument for cef client and that worked perfectly.

**Comment by amaitland** [comment]
To accurately compare CEF with CefSharp you must use the command line arguments listed above. It's not an accurate comparison otherwise. Also add the system flash argument of course. The instructions above are very specific. 

If cefclient works correctly then it's a CefSharp problem, you can ask on ceforum for some guidance, explain the problem.

**Comment by amaitland** [comment]
Please complete a full bug report see https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Using twitch which streams using Flash and the I'm not seeing anything to be concerned about.

**Comment by RadarNyan** [comment]
@amaitland
I think it has something to do with this very specific site. I tried to use a local webpage with a swf file loaded but not seeing this problem. I'm trying to nail down the cause, will get back to this issue once I figure out what's going on.

**Comment by RadarNyan** [comment]
@amaitland 
It seems I was looking at the wrong direction. Now I've found a way to reproduce this behavior.

1. Just create any program that loads a page with flash.
2. Eveything works as expected.

Now, if I add some code like this:
```c#
// private ChromiumWebBrowser Browser;
Browser.MinimumSize = new Size(800,600);
// Setting Browser.Size won't trigger this behavior, only setting MinimumSize will.
```

Then this behavior will appear: CPU usage is still high even if the program is minimized.

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/blob/cefsharp/53/CefSharp.Core/ManagedCefBrowserAdapter.cpp#L84

**Comment by RadarNyan** [comment]
So basically, `MinimumSize` should never be set?

**Comment by amaitland** [comment]
You can submit a pull request that adds support for those scenarios.

**Comment by amaitland** [comment]
With https://github.com/cefsharp/CefSharp/commit/94820149aecfbe1292b785fce6bbace473577954 you can now manually call the underlying `Resize` method. 

Code would look something like this.
```c#
if (form.WindowState == FormWindowState.Minimized && Browser != null)
{
	var browserAdapter = ((CefSharp.Internals.IWebBrowserInternal)Browser).BrowserAdapter;
	browserAdapter.Resize(0, 0);
}
```

You can of course call `SetWindowPos` manually (just grab the handle using `IBrowserHost.GetWindowHandle()`).

If you absolutely have to set a `MinimumSize` or change to a different `Dock` then you'll have to handle this scenario manually for now.

By all means submit a `PR` that adds support.
