### ISSUE TITLE
CefSharp.BrowserSubprocess.exe - System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by sohaibameen** [cefsharp/CefSharp#1901]
Hi,

I have been developing a browser using Cefsharp V39 for windows XP.

I have done some research to make it work for windows XP with .Net framework 4 client profile.

Following the given link I have installed a nugget for windows XP

https://www.nuget.org/packages/CefSharp.Common.XP/

Problem is It works fine on my local machine but when It comes to windows XP It does not work there and throw some exceptions.

**
Exception Details

Application: CefSharp.BrowserSubprocess.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
Stack:
   at CefSharp.BrowserSubprocess.Program.Main(System.String[])

**

Can anyone suggest how to overcome this issue because I really need to get going further on this project.

Thanks in advance!

Best Regards, 
Sohaib Ameen

**Comment by amaitland** [comment]
> Please only open an issue if you have a BUG to report, if you simply have a question or require some assistance keep reading for info. If you do have a BUG to report, please use the Bug Report template below.

Please take the time to read the issue template, if you have a question, ask it on `Gitter`, post on `StackOverflow` or use http://magpcss.org/ceforum/ (for questions specific to `CEF`).

https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

**Comment by amaitland** [comment]
The last version to support Windows XP was 49, you should use that. There hasn't been support for a very long time.

**Comment by sohaibameen** [comment]
I have tried to customise v49 to use it on windows XP but It does not help me out, still getting the same error.

**Comment by sohaibameen** [comment]
I was talking about the cefsharp solution with V49, which I have downloaded to customise, as I am not building it from scratch.

**Comment by sohaibameen** [comment]
You guys have provided the solution here on this link.

https://github.com/cefsharp/CefSharp/releases/tag/v49.0.0

**Comment by amaitland** [comment]
You should use the NuGet packages. If you build from source make sure you build in Release mode.

**Comment by sohaibameen** [comment]
I have tried many times to build in release mode after but still it gives me the same error in XP.

I would really appreciate that If you can lead me some place where I can get the source code working fine on windows XP.

**Comment by sohaibameen** [comment]
I have created an application from scratch, installed V49 from nugget, implemented the required functionality, built it in release mode with VC++ 2013 installed, works fine on local machine but when It comes to windows XP another error this time.

"

Application: Pyrimont.Browser.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException
Stack:
   at Pyrimont.Browser.BrowserTabUserControl..ctor(System.Action`2<System.String,System.Nullable`1<Int32>>, System.String)
   at Pyrimont.Browser.BrowserForm.AddTab(System.String, System.Nullable`1<Int32>)
   at Pyrimont.Browser.BrowserForm..ctor()
   at Pyrimont.Browser.Program.Main()

"

**Comment by amaitland** [comment]
The issue tracker is for bug reports only.

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/wiki/Windows-XP-No-Longer-Supported
