### ISSUE TITLE
Scaling issue in CefSharp 53.0.1.0

### ISSUE THREAD

**Issue by narvinwilliams** [cefsharp/CefSharp#1902]
Today I have upgraded the CefSharp to version 53.0.1.0 and upon upgrading I have been experiencing issues when scaling the application at windows 150%. The application works fine and looks fine at 100% but the moment I scale up the image below is produced. The black is the browser holder, it also flickers the full content in and out.

[![snippingerror.png](https://s23.postimg.org/6agcew46z/snippingerror.png)](https://postimg.org/image/6n7ql2mgn/)

**Comment by amaitland** [comment]
Fill out the bug report as per the issue template

https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

**Comment by amaitland** [comment]
Test using the Minimumexample project to see if the problem reproduces.

**Comment by narvinwilliams** [comment]
@amaitland Wheres the MinimumExample project located?

**Comment by amaitland** [comment]
My Surface Pro runs at 150% on Windows 10 and everything looks fine. Make sure your app has the appropriate OS compatibility entries also.

https://gist.github.com/amaitland/aa976285407ba35cf895c67c614ba82c#high-dpi-displayssupport

**Comment by FAAAAT** [comment]
amaitland 's reply is very useful!

**Comment by narvinwilliams** [comment]
Cef.EnableHighDPISupport(); didn't work. I'm wondering if the issue occurs because I'm launching CefSharp from a DLL. At the same time, it use to work fine before I updated to the latest version.

**Comment by narvinwilliams** [comment]
Actually it worked, I just need to rebuild the application now to have better HDPI support. Thank you for the documentation.
