### ISSUE TITLE
Does not work if I pass an object which has indexer to RegisterJsObject 

### ISSUE THREAD

**Issue by pradsin** [cefsharp/CefSharp#1903]
I have seen this Issue in case we pass an object which has indexer to RegisterJsObject, cefsharp gives exception in CreateJavaScriptProperty Method of JavascriptObjectRepository class.

It gives error when this statement is executed propertyInfo.GetValue(obj, null); that function is being called with invalid number of arguments.

**Comment by amaitland** [comment]
Please fill out a proper bug report.

https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

**Comment by amaitland** [comment]
Resolved as part of #2247
