### ISSUE TITLE
Fix: Network Graph - "Too many forks to display"

### ISSUE THREAD

**Issue by jdc20181** [cefsharp/CefSharp#1904]
Howdy!
I was looking through the Readme, seen where you link to your network graph here is a quote for reference:
"This is the official CefSharp fork, as maintained by the CefSharp community. You can also view the **entire network of public forks/branches**." - Readme.md

The bolded section is where the link is. 

However, I get the following error:

"too many forks to load" 

So.... 

How can you view them when github doesn't allow it?

**Comment by amaitland** [comment]
You would have to raise the issue with Github, outside of our control. There is no way to view the network.

**Comment by cztomczak** [comment]
You can find all forks using GitHub search: "[cefsharp fork:true](https://github.com/search?utf8=%E2%9C%93&q=cefsharp+fork%3Atrue&type=Repositories&ref=searchresults)"

**Comment by jdc20181** [comment]
The readme should be updated then...

**Comment by amaitland** [comment]
@cztomczak Thanks for the handy tip 👍 

@jdc20181 Pull requests welcome.
