### ISSUE TITLE
Cefsharp - how to open links with target="_blank" in a new tab?

### ISSUE THREAD

**Issue by sohaibameen** [cefsharp/CefSharp#1906]
Hi, 

I have created a multi-tab browser using  Cefsharp 45.0.0.0 and It is working fine but there is some problem when I click on a link with target="_blank", as It is supposed to open it in new  tab but It creates a new popup window.

I want to open it in new tab in current tab control, Is there any way I can do this?
Please suggest!

Thank you.

Best Regards, 
Sohaib Ameen

**Comment by amaitland** [comment]
> Please only open an issue if you have a BUG to report, if you simply have a question or require some assistance keep reading for info. If you do have a BUG to report, please use the Bug Report template below.

Please take the time to read the issue template, if you have a question, ask it on `Gitter`, post on `StackOverflow` or use http://magpcss.org/ceforum/ (for questions specific to `CEF`).

https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

**Comment by amaitland** [comment]
https://gist.github.com/amaitland/aa976285407ba35cf895c67c614ba82c#popups

Please stop opening issues, bug reports only, thank you!
