### ISSUE TITLE
CefSharp(V53) chromium webGL issue in remote desktop environment

### ISSUE THREAD

**Issue by quillchan** [cefsharp/CefSharp#1907]
Hi all, I met an issue that CefSharp(V53.0.0.0) chromium behaves different when using Microsoft Remote Desktop Connection(Windows 7). Let me simplify the issue: Machine A->start My app with CefSharp chromium->load the url "https://threejs.org/examples/?q=cube#webgl_geometry_cube", the cube displays. While use remote desktop: Machine B-> Remote to Machine A and start My app-> load the url "https://threejs.org/examples/?q=cube#webgl_geometry_cube", the cube not display. Please note the webgl example needs hardware acceleration on. If I do the same step with Chrome, the cube displays in Remote desktop.

**Comment by jankurianski** [comment]
Please re-read the new issue template and submit a proper bug report, if you are reporting a bug.

In particular, pay attention to reproducing the problem using the CEF Sample Application.

**Comment by mountgellert** [comment]
This is actually unrelated to cef, and can be reproduced with chrome as well; just you have to make sure you connect through RDP/Citrix before any chrome process ever started. Can be fixed by moving to newer RDP or moving to win10 and/or newest Citrix.

**Comment by quillchan** [comment]
@mountgellert For what you said "just you have to make sure you connect through RDP/Citrix before any chrome process ever started", I tried unchecking "Continue running background apps when Google Chrome is closed" and even restart my PC(also checked there is no chrome.exe running), then remote and open Chrome, the webGL example still works. My Chrome version is V55.0.2883.87, have you tried directly open the WebGL example in your Chrome, not through RDP, does it work?

**Comment by quillchan** [comment]
And my RDP version is 8.1.
