### ISSUE TITLE
Using a proxy doesn't load page (probably times out)

### ISSUE THREAD

**Issue by BucurBogdan** [cefsharp/CefSharp#1908]
Hello,

I have an application which loads some pages and searches for some information and it should retrieve it. The problem is that no page load when I have a proxy set from LAN Settings. Without proxy, it works perfectly fine (as well as when I set the  `settings.CefCommandLineArgs.Add("no-proxy-server", "1");` ).
Could it be an HTTP timeout? I used this code (provided in CefSharp.Example) to detect the connection type:
   ```
switch (proxy.AccessType)
                {
                    case InternetOpenType.Direct:
                        {
                            settings.CefCommandLineArgs.Add("no-proxy-server", "1");
                            break;
                        }
                    case InternetOpenType.Proxy:
                        {
                            settings.CefCommandLineArgs.Add("proxy-server", proxy.ProxyAddress);

                            break;
                        }
                    case InternetOpenType.PreConfig:
                        {
                            settings.CefCommandLineArgs.Add("proxy-auto-detect", "1");
                            break;
                        }
                    default:
                        {
                            settings.CefCommandLineArgs.Add("no-proxy-server", "1");
                            break;
                        }
                }
```
I need to mention that the ProxyAdress is the exact same as the one I set in LAN settings.

**Comment by amaitland** [comment]
> Please only open an issue if you have a BUG to report, if you simply have a question or require some assistance keep reading for info. If you do have a BUG to report, please use the Bug Report template below.

Please take the time to read the issue template, if you have a question, ask it on `Gitter`, post on `StackOverflow` or use http://magpcss.org/ceforum/ (for questions specific to `CEF`).

https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/wiki/General-Usage#proxy-resolution
