### ISSUE TITLE
Application crashes at startup

### ISSUE THREAD

**Issue by ManuelMoeller** [cefsharp/CefSharp#1911]
- **What version of the product are you using?**
    -  53.0.1 nuget

- **What architecture x86 or x64?**
   - x64

- **On what operating system?**
    - Win7

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
   - WPF

- **What steps will reproduce the problem?**
    - Compiled Minimal Example and started it
    - The application crashed with an windows error message: Stopped working
    - Windows comes up with an error in the eventlog
  
- **Please provide any additional information below.**
    - The debug.log is empty with level set to info
    - The eventlog provides the following information:
```
 <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2017-01-12T07:39:27.000000000Z" /> 
  <EventRecordID>10706</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>Win7VM64bit</Computer> 
  <Security /> 
</System>
<EventData>
  <Data>CefSharpTest.exe</Data> 
  <Data>1.0.0.0</Data> 
  <Data>58773d35</Data> 
  <Data>libcef.dll</Data> 
  <Data>3.2785.1486.0</Data> 
  <Data>583a7285</Data> 
  <Data>c000001d</Data> 
  <Data>000000000010078c</Data> 
  <Data>e44</Data> 
  <Data>01d26ca6ffe41324</Data> 
  <Data>C:\Users\admin\Desktop\Debug_CEF\Debug\CefSharpTest.exe</Data> 
  <Data>C:\Users\admin\Desktop\Debug_CEF\Debug\libcef.dll</Data> 
  <Data>3eaeb92e-d89a-11e6-9a81-080027f07176</Data> 
</EventData>
```

    - The bug occured only in one specific virtual machine all others worked well.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
   - Tested with the CefClient but it worked.

**Comment by amaitland** [comment]
Read the release notes under known issues.
