### ISSUE TITLE
x64 does not start on 'another' computer, while x86 does

### ISSUE THREAD

**Issue by Snorvarg** [cefsharp/CefSharp#1912]
Hi, we are using the NuGet-packages to make a simple web-browser, and until recently we have had trouble getting the browser to start on any other computer except the ones where we have visual studio installed. 
The solution was very simple: Compile a release version for x86, zip the release-folder, unzip and run on any computer. 
Can it be something odd with the x64 version of cefsharp, or are we missing something? 

We have tried three different machines, with windows 10, and windows 8. All of them are 64bits machines.  We work with the community edition of visual studio, 2015.

Version of cefsharp:
Chromium: 53.0.2785.116, CEF: r3.2785.1486.g8c4ba9f, CefSharp: 53.0.1.0, Environment: x86

We have installed the vcredist_x64.exe as we read about in another thread, but is it really necessary, especially if we compile x86?

**Comment by amaitland** [comment]
Read the release notes, under know issues.
