### ISSUE TITLE
Right click menu is opened in the left corner

### ISSUE THREAD

**Issue by shenhavba** [cefsharp/CefSharp#1915]
Bug Report

**What version of the product are you using?**

CefSharp.Common, CefSharp.Wpf all version 55

**What version are you using? Nuget? CI Nuget? build from a branch? If so which branch? e.g. 53.0.1
What architecture x86 or x64?**

build from branch 55.0.0-pre01 - x86

**On what operating system?**

windows 10

**Are you using WinForms, WPF or OffScreen?**

wpf

**What steps will reproduce the problem?**

     1. open the browser(not in full size)
     2.right click on the browser page - the menu is opened outside the browser and can't be clolsed.

**Please provide detailed information here, enough for someone else to reprodce your problem.
Please no binary (zip, etc) links, fork the MinimalExample and push your changes to GitHub. (Alternatively use a code sharing service list Gist or Pastebin).
What is the expected output? What do you see instead?**

The expected behavior is that the right click menu will open inside the bowser area and when clicking on the browser again, the menu should be closed.

Its working fine in version 47.

**Does this problem also occur in the CEF Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

No.

**Comment by merceyz** [comment]
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by amaitland** [comment]
The menu unable to be closed is #1795 

In reality you probably need a custom `WPF` context menu to resolve this, which is blocked on #1767 for which someone will actually need to take ownership and see the issue resolved in `CEF`.

**Comment by ashu3011** [comment]
You can see this happening in the CefSharp  minimal example. Basically the offset is taken from the corner of the browser window but the menu is displayed using the same offset from the Monitor top left.

**Comment by amaitland** [comment]
A complete implementation of `CefRenderHandler::GetScreenPoint` is required to fix this. Needs to handle `DPI` scaling as well.

**Comment by amaitland** [comment]
The experimental implementation I had previous commented out is now available for testing on `master`.

https://github.com/cefsharp/CefSharp/commit/ef27fb5cf0165985b1299a8316e49e48742ee576

Testing at different DPIs is required. To dismiss the menu it's important to see #1795
