### ISSUE TITLE
WPF C# CefSharp GetElementByTagName Set Value, Class Button Click & Select ComboBox

### ISSUE THREAD

**Issue by EgoistDeveloper** [cefsharp/CefSharp#1919]
Hi everyone, I was using gecko but I have passed cefsharp because it is not wpf support and it looks pretty good. But I think the business logic is a bit different, I hope you help. I am using WPF and C#. NetFramework 4.5.2.

First of all, I have an entry panel and I have to log in.

**Look at [this](http://stackoverflow.com/questions/41788660/wpf-c-sharp-cefsharp-getelementbytagname-set-value-class-button-click-select) page.**

TagNames: name, pass
Class: button_bu

And finally, how do I choose a combox like the one below?

**Look at [this](http://stackoverflow.com/questions/41788660/wpf-c-sharp-cefsharp-getelementbytagname-set-value-class-button-click-select) page.**

Thanks.

**Comment by merceyz** [comment]
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by amaitland** [comment]
> Please only open an issue if you have a BUG to report, if you simply have a question or require some assistance keep reading for info. If you do have a BUG to report, please use the Bug Report template below.

Please take the time to read the issue template, if you have a question, ask it on `Gitter`, post on `StackOverflow` or use http://magpcss.org/ceforum/ (for questions specific to `CEF`).

https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp
