### ISSUE TITLE
Cefsharp.browsersubprocess.exe detected as Adware.Eorezo.RE virus

### ISSUE THREAD

**Issue by markreyes08** [cefsharp/CefSharp#1922]
Hi ,

I just want to ask why i am getting this issue when i tried to run my sample application using cefsharp. My antivirus detected that Cefsharp.browsersubprocess.exe is an Adware. What will i do to fix this? I am using cefsharp version 53.0.1.0. The location of this Cefsharp.browsersubprocess.exe is under C:\Program Files (x86)\MyFolder.

**Comment by amaitland** [comment]
> I just want to ask why i am getting this issue when i tried to run my sample application using cefsharp

Are you using the official `Nuget` packages? What antivirus are you using? 

`VirusTotal` doesn't appear to have a problem with the `x86` or `x64` version.

https://www.virustotal.com/en/file/38831fa7fb3ea642bf8989b0fd6872bf24b4101836aeefef6613fe71cf03d0c2/analysis/
https://www.virustotal.com/en/file/6f09b60d209acdc5a0d28f797b6119ed57e9350c11f4973f6f0245791257d8bd/analysis/

As with all open source, if your concerned, build the project from source yourself (and analyse the source).

**Comment by markreyes08** [comment]
I'm using ByteFence anti malware.

**Comment by amaitland** [comment]
Try uploading the file to `VirusTotal`, see what result you get.

Make sure your using the official nuget packages.

Not really sure what your expecting as an outcome here? No major antivirus program flags an issue.

**Comment by amaitland** [comment]
You should also consider contacting `ByteFence`, see what they have to say.

**Comment by markreyes08** [comment]
I'm just using the free version of this ByteFence Anti Malware. I'll try install other antivirus like avast or AVG. Anyway thanks for the replies...

**Comment by amaitland** [comment]
Where did you obtain `CefSharp.BrowserSubprocess.exe` from exactly?

**Comment by markreyes08** [comment]
from the nuget package

**Comment by amaitland** [comment]
They should be fine, use `VirusTotal` or similar to confirm. If you contact `ByteFence` and receive any constructive information then report back. 

You can always create your own sub process, or integrate it into your main application, it's less than `50 lines` of `C#` these days, the rest is done in `C++`. Check out the source if this is a very high priority for you. 

Closing this as there really isn't a whole lot that can be done. Not the first time `CefSharp` has been flagged, probably won't be the last. As we have no control over who uses it and for what purpose it's open to abuse.
