### ISSUE TITLE
How to set the initial background of chromium browser?

### ISSUE THREAD

**Issue by markreyes08** [cefsharp/CefSharp#1923]
Hi,

I just want to ask how i can set the initial background image or color of chromium browser while the loading of browser is not yet finish? There is a white flash when i start the application before loading my background. Is there any way to set the default window background color or background image of the chromium browser? By the way i'm using the cefsharp for windows application.

**Comment by amaitland** [comment]
> Please only open an issue if you have a BUG to report, if you simply have a question or require some assistance keep reading for info. If you do have a BUG to report, please use the Bug Report template below.

Please take the time to read the issue template, if you have a question, ask it on `Gitter`, post on `StackOverflow` or use http://magpcss.org/ceforum/ (for questions specific to `CEF`).

https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

**Comment by amaitland** [comment]
Search the source for `BackgroundColor`.

**Comment by markreyes08** [comment]
ok. Tnx,.. Sorry i am new to CefSharp. Tnx for the help.

**Comment by amaitland** [comment]
When creating a new issue it should come pre-populated with the issue template, were you using the website or the app to post this?

**Comment by amaitland** [comment]
> There is a white flash when i start the application before loading my background.

Looks like a white flash is a known issue see https://bitbucket.org/chromiumembedded/cef/issues/1984/momentary-white-flash-with-osr-in#comment-33638061

Will require a newer `CEF` version,

**Comment by markreyes08** [comment]
Hi,

What version of CEF do i need so that i will not encounter this white flash again?

**Comment by amaitland** [comment]
> What version of CEF do i need so that i will not encounter this white flash again?

Any version that includes the fix, see the link for details of which branches the fix was included in.

**Comment by amaitland** [comment]
Just for absolute clarity there is no `CefSharp` version that includes the referenced fix.

**Comment by markreyes08** [comment]
I need the one coming from nuget packages.

**Comment by markreyes08** [comment]
Because i'm using the one coming from the nuget packages.

**Comment by markreyes08** [comment]
I'm using CefSharp version 53.0.1.0.

**Comment by amaitland** [comment]
> I'm using CefSharp version 53.0.1.0.

There is no `CefSharp` version that includes those changes.

**Comment by amaitland** [comment]
`CefSharp` is just a wrapper, see https://github.com/cefsharp/CefSharp/wiki/General-Usage for a full explanation.

**Comment by markreyes08** [comment]
how i will integrate the fix  in my current version of CefSharp?

**Comment by amaitland** [comment]
Actually I'm mistaken, upgrade to `55.0.0` and make sure you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by markreyes08** [comment]
so you mean i just need to update to version 55.0.0 in order to get this fix?

**Comment by amaitland** [comment]
> so you mean i just need to update to version 55.0.0 in order to get this fix?

Upgrade and find out.

**Comment by markreyes08** [comment]
I tried it in CEF version 55.0.0 but it is still the same . There still a white flash before loading my background image.

![white flash](https://cloud.githubusercontent.com/assets/25447921/22674929/8ee12aea-ed1d-11e6-88c2-eda7b083d90b.png)

![mybackgorund](https://cloud.githubusercontent.com/assets/25447921/22674933/932d9688-ed1d-11e6-9dd7-4078fb51b3b7.png)

**Comment by amaitland** [comment]
You should discuss your problem on the CEF issue above, it's not a CefSharp problem.
