### ISSUE TITLE
chrome_elf.dll is not mentioned in Wiki as required, but it is

### ISSUE THREAD

**Issue by ncksol** [cefsharp/CefSharp#1925]
- **What version of the product are you using?**
Nuget 55.0.0

- **What architecture x86 or x64?**
x86

- **On what operating system?**
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
I've updated my app to use the latest 55.0.0 from 47.0.3 and it started to throw "Could not load file or assembly 'CefSharp.Core.dll' " exceptions.

- **Please provide any additional information below.**
After analysing the difference in packages between 47.0.3 and 55.0.0 I have found a new file in Cef redist - chrome_elf.dll. It is not mentioned in the Wiki as required, but the app that uses CefSharp 55.0.0 crashes without it.

**Comment by amaitland** [comment]
It's literally only just been added in this release. Anyone with a Github account can edit the wiki, so by all means add it.

**Comment by chris-araman** [comment]
Fixed.
https://github.com/cefsharp/CefSharp/wiki/Output-files-description-table-(Redistribution)
