### ISSUE TITLE
cookies with encrypted values not loaded

### ISSUE THREAD

**Issue by youzking** [cefsharp/CefSharp#1926]
hello,
I tried to use google chrome cookies file by setting the `StoragePath` of the `GlobalCookieManager` like this (using VB): 

`CefSharp.Cef.GetGlobalCookieManager.SetStoragePath("C:\\Users\\younes\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\", True)`

But when the browser starts it just load the cookies' name (with empty values), i tried to explore the cookies database and i found that the value of the cookies are stored in the column `encrypted_value`, the browser does  not consider `encrypted_value` column.

**Comment by amaitland** [comment]
It's important to note that `CefSharp` is just a wrapper around the `Chromium Embedded Framework (CEF)`. Please use http://magpcss.org/ceforum/index.php for generic **CEF** questions. It is best place for this kind of question.

**Comment by amaitland** [comment]
The follow up is https://bitbucket.org/chromiumembedded/cef/issues/2088/add-support-for-storing-encrypted-cookie
