### ISSUE TITLE
v55 performance issue

### ISSUE THREAD

**Issue by pkhach** [cefsharp/CefSharp#1927]
updated: 

CefSharp.WinForms.Example v55 scrolls large pages much slower than v51

To reproduce the issue open http://beggar-panda-58623.netlify.com in CefSharp.WinForms.Example v55 and v51 (32 bit) and try to scroll page.

A corresponding bug report was posted for CEF Sample Application, bit in C#  version the problem is much more noticeable.

https://bitbucket.org/chromiumembedded/cef/issues/2087/v56-performance-issue

Win 7 and 10 (32 bit)

Thanks!

**Comment by amaitland** [comment]
When filling out a bug report please use the template provided https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report (You can view the raw version at https://raw.githubusercontent.com/cefsharp/CefSharp/master/ISSUE_TEMPLATE.md to copy and paste)


---
### Report Card
Your bug report is **incomplete** ❌ 
- [ ] What version of the product are you using?
- [ ] What architecture `x86` or `x64`?
- [ ] On what operating system?
- [ ] Are you using `WinForms`, `WPF` or `OffScreen`?
- [ ] What steps will reproduce the problem?
- [ ] What is the expected output? What do you see instead?
- [ ] Please provide any additional information below.
- [ ] Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?

#### Comments
Insert comments here

**Comment by pkhach** [comment]
To reproduce the bug, please unzip the attached HTML & CSS files to your web server's http docs directory and navigate to a bug.html in CefSharp.WinForms.Example application

This bug applies to:
- Win 7 & 10
- WinForms & Wpf
- CEF Sample Application v56 (C++) and CefSharp.WinForms.Example v55 (C#). But in C# is much more noticeable.

Thanks!

[bug.zip](https://github.com/cefsharp/CefSharp/files/754468/bug.zip)

**Comment by amaitland** [comment]
Your zip has been removed, no binaries thank you. Please upload to a code sharing site like pastebin

If you can reproduce using cefclient then you should post on ceforum.

**Comment by amaitland** [comment]
Also you should compare the exact same versions for accuracy.

**Comment by amaitland** [comment]
Again please remove the word retarding from your title and description, it's a poor choice of language.

**Comment by amaitland** [comment]
When you've posted on ceforum add a link here for reference

**Comment by pkhach** [comment]
I have updated the original bug report and posted a corresponding bug report to CEF bug tracker:

https://bitbucket.org/chromiumembedded/cef/issues/2087/v56-performance-issue

**Comment by pkhach** [comment]
It looks like a Chromium bug. 
I have posted corresponding bug to the Chromium bug tracker:
https://bugs.chromium.org/p/chromium/issues/detail?id=689373

**Comment by amaitland** [comment]
Closing this now, as the problem reproduces in `Chromium`, will need to be fixed there.

The workarounds would appear to be
- Use the `x64` build
- Rollback to a previous version
