### ISSUE TITLE
V55: VisitUrlCookiesAsync NullReferenceException

### ISSUE THREAD

**Issue by bobahml** [cefsharp/CefSharp#1928]
- **After update to V55 (from Nuget). I see an System.NullReferenceException in my application log**
    - CefSharp.Core/CookieManager.cpp#L107
CefSharp.CookieManager.VisitUrlCookiesAsync(String url, Boolean includeHttpOnly) in c:\projects\cefsharp\cefsharp.core\cookiemanager.cpp:line 107

- **What version of the product are you using?**
    - Nuget v 55.0.0
- **What architecture x86 or x64?**
    - x64
- **On what operating system?**
    - windows 8.1 Pro 
- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - OffScreen
- **Gist for CefSharp.MinimalExample**
    - https://gist.github.com/bobahml/8f963f67e23938d3592da300e7536b31
- **What is the expected output? What do you see instead?**
    - It is expected the correct list of cookies
- **stack trace.**
    - CefSharp.CookieManager.VisitUrlCookiesAsync(String url, Boolean includeHttpOnly) in c:\projects\cefsharp\cefsharp.core\cookiemanager.cpp:line 107

**Comment by amaitland** [comment]
You can easily debug the source now we have gitlink see #1680 

Please submit a PR when you have a proposed solution

**Comment by amaitland** [comment]
Which version does your code work against?

**Comment by amaitland** [comment]
Resolved in `master` with https://github.com/cefsharp/CefSharp/commit/e6bcbe411194466d4c902c32865cb1ed85797fc6

If unable to access the cookies `null` will be returned instead of a `Task`.
