### ISSUE TITLE
Issue with resize in WPF: after window resize browser not resized, and browser freezed

### ISSUE THREAD

**Issue by zigota** [cefsharp/CefSharp#1929]
I tried to resize  the window in v55.0.0 and v53.0.1.
I downloaded sources, and build them on my PC(project built in VS. 2015  for platform x86 and x64
i tried run on windows 8 and 10)
I run CefSharp.Wpf.Example and did the  following steps:

1) Create a few tabs on the browser
2) Change the  windows size by mouse
After that step, browser not resized.
I recorded a video of my actions, you can see it below
![browser](https://cloud.githubusercontent.com/assets/11520214/22738828/15d353be-ee1a-11e6-81bc-28e6600cf5dd.gif)

**Comment by amaitland** [comment]
Looks like a duplicate of #1571
