### ISSUE TITLE
CefSharp OutOfMemoryException

### ISSUE THREAD

**Issue by JackerMinh** [cefsharp/CefSharp#1933]
Hi All.

I have develop app using CefSharp V53.0.1.0 branch release with nuget wpf on Win7 Enterprise X64 Sp1.

When i running app loading website with learge height scroll cefsharp return error as below.

System.OutOfMemoryException : Exception of type
System.OutOfMemoryException was thrown.
at System.String.CtorCharPtr(Char* ptr)
at CefSharp.Internals.Serialization.DeserializeObject<class CefListValue,int> (CefRefPtr<CefListValue>* list, Int32 index, IJavascriptCallbackFactory javascriptCallbackFactory)
at CefSharp.Internals.ClientAdapter.OnProcessMessageReceived(ClientAdapter*, CefRefPtr<CefBrowser>* browser, cef_process_id_t source_process, CefRefPtr<CefProcessMessage>* message)

Please help me ro resolve problem.

Many thanks.

**Comment by amaitland** [comment]
Can you reproduce the problem with version 55? 53 is no longer supported. If you can reproduce the problem then please provide an example of how to reproduce the problem. A stack trace on it's own is pretty meaningless for this type of error. 

Are you using an x64 build?

**Comment by amaitland** [comment]
Also please take the time to read the issue template

https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by JackerMinh** [comment]
I will update to version 55, My application using x86 bit, function loading facebook page with searching keyword and scrolling to end page, objective loading more information of result search.

**Comment by JackerMinh** [comment]
Update file error dump cash when using application

https://drive.google.com/file/d/0B54i1OsLMXGLVnYzcnVMdWd2ZnM/view?usp=sharing

**Comment by amaitland** [comment]
Switch to x64. If you have a technical reason for staying with x86 like referencing another unmanaged library the make sure your setting the LargeAddressAware flag on your exe

Report back when you've got the results of the memory profiling.

**Comment by JackerMinh** [comment]
Many thanks.
