### ISSUE TITLE
WindowOpenDisposition enum doesn't line up with CEF cef_window_open_disposition_t

### ISSUE THREAD

**Issue by mbragg12** [cefsharp/CefSharp#1940]
In CefSharp 55, the CefSharp WindowOpenDisposition enum doesn't line up with CEF cef_window_open_disposition_t enum.  This is causing all the dispositions reported by in IRequestHandler and ILifeSpanHandler to be wrong.

SUPPRESS_OPEN value was removed by this change: https://codereview.chromium.org/2107323004

Current CEF/Chromium enum:
///
// The manner in which a link click should be opened. These constants match
// their equivalents in Chromium's window_open_disposition.h and should not be
// renumbered.
///
typedef enum {
  WOD_UNKNOWN,
  WOD_CURRENT_TAB,
  WOD_SINGLETON_TAB,
  WOD_NEW_FOREGROUND_TAB,
  WOD_NEW_BACKGROUND_TAB,
  WOD_NEW_POPUP,
  WOD_NEW_WINDOW,
  WOD_SAVE_TO_DISK,
  WOD_OFF_THE_RECORD,
  WOD_IGNORE_ACTION
} cef_window_open_disposition_t;

Current CefSharp enum:
    public enum WindowOpenDisposition
    {
        Unknown,
        SuppressOpen,
        CurrentTab,
        SingletonTab,
        NewForegroundTab,
        NewBackgroundTab,
        NewPopup,
        NewWindow,
        SaveToDisk,
        OffTheRecord,
        IgnoreAction
    }

**Comment by mbragg12** [comment]
Put up a pull request for master and branch 55

**Comment by amaitland** [comment]
Great, thanks. Both merged
