### ISSUE TITLE
Cannot drag and drop text in page to other spot in page

### ISSUE THREAD

**Issue by psdao1102** [cefsharp/CefSharp#1944]
I saw that this should have been fixed in 39, but we still seem to be having issues with dragging and dropping text. When I try to drag and drop text i get a big circle with cross in it.

- **What version of the product are you using?**
    - What version are you using? Nuget? CI Nuget? build from a branch? If so which branch?
Nuget: 55

- **What architecture x86 or x64?**
x86
- **On what operating system?**
    - Win7, Win 8, Win10, etc?

Windows 10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.
    - Please no binary (zip, etc) links, fork the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) and push your changes to `GitHub`. (Alternatively use a code sharing service list `Gist` or `Pastebin`).

here the pastebin http://pastebin.com/i2bETQ2T

- **What is the expected output? What do you see instead?**
Should be able to drag and drop text

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?

We build and start our own ASP.net MVC server using IIS and then use the cefsharp app to access it locally.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

    - To compare with WPF run cefclient --multi-threaded-message-loop --off-screen-rendering-enabled
    - To compare with WinForms run cefclient --multi-threaded-message-loop
    - If you can reproduce the problem with `cefclient` then you'll need to report the bug on https://bitbucket.org/chromiumembedded/cef/overview there is no point opening an issue here. (Make sure you search before opening an issue)

**Comment by amaitland** [comment]
See for a description of the command line flag your using, seems like it's Linux related.
http://peter.sh/experiments/chromium-command-line-switches/#touch-devices

Test with `CefSharp.Wpf.Example`, if you can reproduce the problem then provide a list of steps to reproduce the problem, in this case a screen cast would also be helpful.

> To compare with WPF run cefclient --multi-threaded-message-loop --off-screen-rendering-enabled

Download `cefclient`, make sure you test with the command line arguments specified for `WPF`. If it works there then you'll have to dig through the `cefclient` source and find out what piece is missing.

The source is there, you'll have to investigate further on your own 👍

**Comment by amaitland** [comment]
using `CefSharp.Wpf.Example` I can drag text into the google search box when visiting `google.com`. Original issue doesn't provide steps to reproduce the problem so closing due to lack of feedback.
