### ISSUE TITLE
V55 unable to access internet through proxy 

### ISSUE THREAD

**Issue by arvindlloyds** [cefsharp/CefSharp#1948]
I updated to CefSharp 55.0.0. After update I am not able to access internet. All intranet applications are opening fine.

I am behind configured proxy.

if I revert back to 51.0.0 it works. I am using - CefSharp.MinimalExample.Wpf to run my tests.

Here are the details -

**What version of the product are you using?**
55.0.0

**What version are you using? Nuget? CI Nuget? build from a branch? If so which branch? Nuget:** 
55.0.0 and 53.0.0 (works)

**What architecture x86 or x64?** 
x64

**On what operating system?** 
Win7

**Are you using WinForms, WPF or OffScreen?** 
WPF

**What steps will reproduce the problem?** 
I use CefSharp.MinimalExample.Wpf from CefSharp. test it against 55.0.0 and 51.0.0

What is the expected output? What do you see instead? I must be able to internet in both the cases (55 and 53) but I see timeout when I use 55.0.0.

Not opening an issue (https://github.com/cefsharp/CefSharp/issues) before knowing if it can be resolved using a bit of tweak.

**Last Bit -**

I also have tried -

 var proxy = ProxyConfig.GetProxyInformation();
        switch (proxy.AccessType)
        {
            case InternetOpenType.Direct:
                {
                    //Don't use a proxy server, always make direct connections.
                    settings.CefCommandLineArgs.Add("no-proxy-server", "1");
                    break;
                }
            case InternetOpenType.Proxy:
                {
                    settings.CefCommandLineArgs.Add("proxy-server", proxy.ProxyAddress);
                    break;
                }
            case InternetOpenType.PreConfig:
                {
                    settings.CefCommandLineArgs.Add("proxy-auto-detect", "1");
                    break;
                }
        }
        Cef.Initialize(settings, performDependencyCheck: true, browserProcessHandler: null);
        Cef.Initialize(settings, true, true);

**Comment by amaitland** [comment]
### How do I investigate my issue further?

It's important to remember that `CefSharp` is just a wrapper around the `Chromium Embedded Project (CEF)`, the upstream [`CEF` forum](http://magpcss.org/ceforum/) is a valuable resource. Also `CEF` has it's own [Issue Tracker](https://bitbucket.org/chromiumembedded/cef/issues). Please take the time to research your own problem, including `Googling`, searching on `ceforum`, etc.

--
#### Finding more info
- Have you checked the `Debug.log` file? (Should be located in your apps executing folder by default)
- Have you googled the error message your seeing? (Don't just google the whole thing, try googling just the keywords and possibly add `chromium` as a keyword).
- Are you able to reproduce the problem using `cefclient`? (`cefclient` is the reference implementation provided by `CEF`)
- Need more help debugging? Check the [Troubleshooting Guide](https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting)
- Are you using the latest version? Check the [Release Branches](https://github.com/cefsharp/CefSharp#release-branches) table to determine if the version your using is supported. 

--
#### How do I download `cefclient`?

- Firstly identity which version of `CEF` your actually using, easiest way is to check your `packages.config` file, look for the `cef.redist.x86` package, it's version will be something like `3.2526.1362`, that's the exact version of `CEF` you'll need to download for comparison. You can also open `chrome://version` in the browser to determine the version.
- Open http://opensource.spotify.com/cefbuilds/index.html (http://cefbuilds.com for older version) in a web browser
- Locate the exact `Branch` you require, for the example above the branch is `2526`, all the versions follow a similar pattern
- Locate the `Windows 32bit` or `Windows 64bit` item, if you don't see the exact version, then click `more revisions`
- Download **Test App**
- Are you using `WPF/Offscreen` or `WinForms`? 

**This next part is key**
- To compare with WPF/OffScreen run `cefclient --multi-threaded-message-loop --off-screen-rendering-enabled`
- To compare with WinForms `cefclient --multi-threaded-message-loop`

**Comment by amaitland** [comment]
Possibly https://bitbucket.org/chromiumembedded/cef/issues/2066/branch-2883-pac-proxy-not-work

If so you'll have to skip using 55

**Comment by peters** [comment]
I can confirm that there's definitely a bug with PAC script loading in 55 :)

**Comment by amaitland** [comment]
`master` has been upgraded to ` CEF 3.2987.1597.gffc5773` reports suggest this has been resolved. If there's still a problem then discuss at https://bitbucket.org/chromiumembedded/cef/issues/2066/branch-2883-pac-proxy-not-work

**Comment by nikhilagrawaldotnet** [comment]
I had exact problem with v55. Intranet sites worked fine. Non-intranet sites used to work when Fiddler was running in parallel. As per amaitland comment above, that this is fixed, we used 57.0.0-pre01 and this is fixed in that.

**Comment by arvindlloyds** [comment]
Fixed in 57.0.0
