### ISSUE TITLE
awaiting EvaluateScriptAsync() called from clicking an HTML button hangs browser

### ISSUE THREAD

**Issue by Sephizor** [cefsharp/CefSharp#1949]
My use case for this is from an implementation of a custom browser control which currently uses IE11. I am trying to prove the concept of a drop-in solution that provides an implementation of my custom BrowserControl interface in Chromium.

The IE11 browser control allows for evaluating code on the UI thread which I do extensively throughout my application.

- **What version of the product are you using?**
55.0.0 from nuget

- **What architecture x86 or x64?**
x64

- **On what operating system?**
Windows 7, Windows 10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms

- **What steps will reproduce the problem?**
https://github.com/Sephizor/CefSharp-Minimal-EvalTest
Serve the webapp at http://localhost:8080
Start the modified example
Click the "Click Me!" button

- **What is the expected output? What do you see instead?**
Expected: When the button on the webpage is clicked, it should log the result of testEval() to the console ("hello")
Actual: Browser hangs

**Comment by amaitland** [comment]
Please fork the Minimumexample, you've created a new repository. Makes it difficult to see what changes you've made.

**Comment by amaitland** [comment]
> awaiting EvaluateScriptAsync() called from clicking an HTML button hangs browser

You cannot call `EvaluateScriptAsync` from within a bound method. Using `RegisterJsObject` the calls are made in a sync fashion, you'd be blocking the `Render` process. Use a `IJavascriptCallback` instead.

https://github.com/cefsharp/CefSharp/wiki/General-Usage#3-how-do-you-expose-a-net-class-to-javascript
