### ISSUE TITLE
EvaluateScriptAsync hanging

### ISSUE THREAD

**Issue by syrakozz** [cefsharp/CefSharp#1950]
Task<JavascriptResponse> t = this.EvaluateScriptAsync(command);

                 t.Wait();

it freeze plz help

**Comment by amaitland** [comment]
When filling out a bug report please use the template provided https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report (You can view the raw version at https://raw.githubusercontent.com/cefsharp/CefSharp/master/ISSUE_TEMPLATE.md to copy and paste)

**Comment by amaitland** [comment]
You should read https://github.com/cefsharp/CefSharp/wiki/General-Usage#javascript-integration

If you come up with a reproducible bug then update your issue using the `Issue Template`. If you just require some help, then ask your questions on `Gitter` or `Stackoverflow`.
