### ISSUE TITLE
Cefsharp c# Winforms popup

### ISSUE THREAD

**Issue by gen-88** [cefsharp/CefSharp#1951]
Please help. I use cefsharp in c# winforms, project is multitabbed. I have someone code in javascript, like:

```
    <script>
        var data = 'hello';
        var w = window.open("about:blank", "123");
        w.document.write(data);
    </script>
```

End also have code in c# at class LifeSpanHandler:

```
public bool OnBeforePopup(IWebBrowser browserControl, IBrowser browser, IFrame frame, string targetUrl, string targetFrameName, WindowOpenDisposition targetDisposition, bool userGesture, IPopupFeatures popupFeatures, IWindowInfo windowInfo, IBrowserSettings browserSettings, ref bool noJavascriptAccess, out IWebBrowser newBrowser)
    {

        // open popup in new tab!
        newBrowser = myForm.NewPage(targetUrl);

        return true;

    }
```

If return set false, then script create new window and 'hello' is here. But if return set true, create new tab with new browser, code w.document.write(data); in javascript do not work. How can I do so that javascript create new tab and transfer variable data in it?

**Comment by amaitland** [comment]
> Please only open an issue if you have a BUG to report, if you simply have a question or require some assistance keep reading for info. If you do have a BUG to report, please use the Bug Report template below.

Please take the time to read the issue template, if you have a question, ask it on `Gitter`, post on `StackOverflow` or use http://magpcss.org/ceforum/ (for questions specific to `CEF`).

https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

**Comment by amaitland** [comment]
Read the popup section of the general usage guide
