### ISSUE TITLE
Code Cleanup - Improve ChromiumWebBrowser Dispose/Finalise

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#1954]
Revise the `Dispose(bool)` method in the three `ChromiumWebBrowser` classes. As time has gone one the code has been refactored and doesn't quite follow the correct pattern (only dispose of `unmanaged` resources when `disposing = false`).

- Implement a thread safe disposed pattern in all three instances see https://blogs.msdn.microsoft.com/blambert/2009/07/24/a-simple-and-totally-thread-safe-implementation-of-idisposable/ (the `WPF` version differs slightly, better to make them all the same)
- Only dispose of `managed` resources when `disposing = true`. 
- Ordering of disposal is important so keep the ordering the same

Reference: https://msdn.microsoft.com/en-us/library/b1yfkh5e(v=vs.110).aspx

**Comment by amaitland** [comment]
https://referencesource.microsoft.com/#System/net/System/Net/NetworkInformation/ping.cs,135

**Comment by amaitland** [comment]
@DickBaker This issue represents an actionable item that involves cleaning up the `Dispose/Finalize` code, nothing to do with the examples or `Cef.Shutdown`. Not quite sure how this relates to your comment?

> For the WinForms and WPF instances of ChromiumWebBrowser the relevant Application Exit event is hooked and Cef.Shutdown() called by default. Set CefSharpSettings.ShutdownOnExit = false; to disable this behavior. This value needs to be set before the first instance of ChromiumWebBrowser is created as the event handlers are hooked in the static constructor for the ChromiumWebBrowser class.

If you keep reading in https://github.com/cefsharp/CefSharp/wiki/General-Usage#initialize-and-shutdown you'll see that it's optional now, the example just hasn't been updated to reflect that. Admittedly it could made more prominent. Anyone with a `GitHub` account can edit the `Wiki`, so by all means make some improvements.

> May I suggest that App.xaml.cs demo code should include this

Using `OnDeactivated` and your browser would become unresponsive as soon as you `Alt-Tabbed` away and then returned. I'm guessing you mean `OnExit`. If you think this needs clarification in the `MinimalExample`, then please open an issue in the issue tracker there.

If you have questions then please ask on https://gitter.im/cefsharp/CefSharp

**Comment by DickBaker** [comment]
@Alex Thanks for rapid reply.

 

I had supposed that the problem raised by OP may have related to an obligation to unhook on exit

- apologies if my comments in fact unrelated [sure your native expertise will surpass my newbie ignorance!]

 

As simpleton I am reluctant to venture editorial changes (even if actually technically possible) lest I break something

- I will leave crafting any pen-strokes to a better-skilled craftsman

[many monkeys may eventually type Shakespeare, but this old monkey knows just enuff to down his pen!]

 

Thanks also for pointer to that gitter forum, and I will certainly look there for wisdom that I seek for JS/C# interaction

**Comment by amaitland** [comment]
> I had supposed that the problem raised by OP may have related to an obligation to unhook on exit

What problem exactly? What issue are you referring to? What obligation do you have to `unhook` on exit exactly?

**Comment by khalidezzat71** [comment]
What problem exactly?
