### ISSUE TITLE
Is possiable to merge redistribution files into one or two dll?

### ISSUE THREAD

**Issue by SolardiaX** [cefsharp/CefSharp#1955]
Hi there, I used this great solution for my application for a while. I noticed there are some commercial  solutions packaged all CEF runtime resources into few dll files.

So, I just want to know our CefSharp can merge/package/combine all CEF runtime resources together? In that ways, develop an application can be just reference the CefSharp dlls and run will make works more simple and  more easier to redistribution.

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).
