### ISSUE TITLE
JavascriptResponce Result Handle

### ISSUE THREAD

**Issue by aykutmunuk** [cefsharp/CefSharp#1957]
I am using v47 cefsharp, and i am using evaluateScriptAsync method.

But when i call a js function with evaluateScriptAsync, always from this js function return result 'null'.
Successfully i call js function and it work, but responce doesn't return.

Can you help me, please?

C# code:
        public object CallSyncJavascriptSideFunction(string javascriptFunctionName, TimeSpan timeout)
        {
            object result = null;
            var task = _webBrowser.EvaluateScriptAsync(javascriptFunctionName, timeout);
            task.Wait();

            var response = task.Result;
            result = response.Success ? (response.Result ?? "null") : response.Message;

            return result;
        }

JS code:

function abcCount() {
alert("abc");
return "abc";
}

**Comment by amaitland** [comment]
55 is the current supported version, older versions are unsupported. Does the problem reproduce in 55?

For JavaScript usage read the general usage guide. You should avoid using Wait(), use await or a continuation.

**Comment by amaitland** [comment]
Also you need to format your code, it's too hard to read.

**Comment by amaitland** [comment]
Marking this as `invalid`, Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp)
