### ISSUE TITLE
How to change spell check

### ISSUE THREAD

**Issue by aykutmunuk** [cefsharp/CefSharp#1958]
Hi,

I use CefSharp v47.0.2526.80, and i want to change spell check settings.
How to change it, can you help me?

Thank,

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

**Comment by aykutmunuk** [comment]
i investigated and i tried, but it didnot change.
according to me, it is issue.

**Comment by amaitland** [comment]
> I use CefSharp v47.0.2526.80, and i want to change spell check settings.

Firstly your using an **unsupported** version. Secondly you didn't provide an examples of what you've tried already and wasn't working. 

> according to me, it is issue.

If there was an issue, it would need to be fixed in `CEF`, as `CefSharp` is just a wrapper.

**Comment by amaitland** [comment]
You can keep a track of which version is current by looking at https://github.com/cefsharp/CefSharp#release-branches
