### ISSUE TITLE
Console application : System.IO.FileNotFoundException: Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found. File name: 'CefSharp.Core.dll'

### ISSUE THREAD

**Issue by vinodkreddy1** [cefsharp/CefSharp#1959]
I am working with cefSharp.OffScreen to capture the screen shot for a given url, On my local machine when I run the application its working fine. Also I published the app on my local machine and ran the Exe. Then also it working fine.

I copied the entire folder to the server. Here comes the issue. When I run the exe on the server, I am getting above issue. 

I have all the dlls/dat from the package.

My project Setup
I am working with Asp .Net core Console. The EXe is setup to run on X64.

Can any one help out what I am missing when I am moving to server that is not in my local

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).
