### ISSUE TITLE
Yet another Could not load file or assembly CefSharp.Core

### ISSUE THREAD

**Issue by Dainius14** [cefsharp/CefSharp#1964]
- **What version of the product are you using?**
55.0 from NuGet

- **What architecture x86 or x64?**
x86

- **On what operating system?**
Windows 10 x64

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
Simply instantiating CefBrowser

- **What is the expected output? What do you see instead?**

- **Please provide any additional information below.**
     at Twinder.View.BrowserView..ctor()

Cef log:
```
=== Pre-bind state information ===
LOG: DisplayName = CefSharp.Core, Version=55.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138
 (Fully-specified)
LOG: Appbase = file:///.../twinder/bin/x86/Release/
LOG: Initial PrivatePath = NULL
Calling assembly : Twinder, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: ...\twinder\bin\x86\Release\Twinder.vshost.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: CefSharp.Core, Version=55.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138
LOG: Attempting download of new URL file:///...twinder/bin/x86/Release/CefSharp.Core.DLL.
ERR: Failed to complete setup of assembly (hr = 0x8007000b). Probing terminated.
```

Debugging code is fine. Everything works. Shit hits the fan once I try running Release build. I've tried copying many .dlls, I've seen this guide https://github.com/cefsharp/CefSharp/wiki/Output-files-description-table-(Redistribution) , I've looked through many SO threads. I have all VC redistributables installed. Nothing works.

**Comment by amaitland** [comment]
> Please only open an issue if you have a BUG to report, if you simply have a question or require some assistance keep reading for info. If you do have a BUG to report, please use the Bug Report template below.

Is there a reason you didn't post on `StackOverflow`? 

https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#Runtime_dependencies

**Comment by amaitland** [comment]
Attempt to include `VC++` with your app https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#Including_vcredist

**Comment by amaitland** [comment]
For testing purposes use https://github.com/cefsharp/CefSharp.MinimalExample

**Comment by Dainius14** [comment]
Sorry, I didn't see the rule. I'll repost it to SO.

I've tried that already.
