### ISSUE TITLE
Feature Request - PrintToPDf Scaling

### ISSUE THREAD

**Issue by GrabzIt** [cefsharp/CefSharp#1965]
This is not so much a bug report as a feature request. Version 57 of Chromium now allows PDF print scaling, which should overcome some of the bad results when trying to print a webpage as PDF.

Unfortunately CEF has yet to add it to there library I have raised a case about it here: https://bitbucket.org/chromiumembedded/cef/issues/2106/please-add-scaling-to-pdf-printing

Is there any way it could be included in the #1963 release so that the option would be exposed here: https://github.com/cefsharp/CefSharp/blob/11dee93bf331f012dd6416fb2f2162549d9137a3/CefSharp/PdfPrintSettings.cs? I am not really sure if this is possible at this time, I was just excited when I saw the new feature because it is something that would be very useful.

If this case needs sponsorship I would be willing to pay. I am hoping it wouldn't take too much work as is just another attribute for a existing class, I would do it myself. But I don't have the level of c++ skills required.

**Comment by amaitland** [comment]
> But I don't have the level of c++ skills required.

@GrabzIt Even with minimal `C++` experience I think there's a pretty high chance you could implement this yourself.

- Add field to `cef_pdf_print_settings_t` 
- Add field to `CefPdfPrintSettingsTraits::Set`
- Populate `print_settings` dictionary

Here are some relevant links to the `CEF` source
https://bitbucket.org/chromiumembedded/cef/commits/85f8368#Linclude/internal/cef_types.hT2268
https://bitbucket.org/chromiumembedded/cef/commits/85f8368#Llibcef/browser/printing/print_view_manager.ccT51

What I believe is the relevant dictionary key from the `Chromium` source.
https://cs.chromium.org/chromium/src/printing/printing_context.cc?type=cs&l=75

https://bitbucket.org/chromiumembedded/cef/wiki/ContributingWithGit.md#markdown-header-working-with-pull-requests

I'm sure you could ask a few pointers on http://magpcss.org/ceforum/index.php

**Comment by GrabzIt** [comment]
Thanks for the advice! I will look into it :-)

**Comment by GrabzIt** [comment]
I have submitted this pull request to CEF (https://bitbucket.org/chromiumembedded/cef/pull-requests/110) just waiting for it to be accepted and I will submit the pull request for CEFSharp. :-D

**Comment by amaitland** [comment]
> I have submitted this pull request to CEF (https://bitbucket.org/chromiumembedded/cef/pull-requests/110)

Great 👍 

> just waiting for it to be accepted and I will submit the pull request for CEFSharp. :-D

Will need to be merged into the `2987` branch for it to appear in the `57` release.

**Comment by GrabzIt** [comment]
I have requested the change be merged with  2987, hopefully it will be possible.

**Comment by amaitland** [comment]
Looks like your change was merged into `2987` with https://bitbucket.org/chromiumembedded/cef/commits/c2b4638063e34456360cc4baec4cf914df41720c

Should appear next time I upgrade `master`, should be possible to add the property to `PdfPrintSettings` after that.

I was unable to get  `PrintToPdf` working successfully in `2987`, same problem problem reproduces with the `cefclient` example app.

**Comment by GrabzIt** [comment]
Good news about the change being merged. I am just waiting for a new build to appear here: http://opensource.spotify.com/cefbuilds/index.html

You are right the PrintToPDF feature is not working in version CEF 3.2987.1594.g92fba9c which is before my change, so whatever broke it occurred earlier.

**Comment by amaitland** [comment]
> I have raised a critical issue about it: https://bitbucket.org/chromiumembedded/cef/issues/2129/print-to-pdf-broken-in-version-57

Issue has been resolved, I'll upgrade to a version that includes that fix prior to releasing `57.0.0`

Feel free to submit a `PR` that includes the scaling option 👍

**Comment by GrabzIt** [comment]
That's brilliant news!! I am on holiday at the moment but i am coming back tomorrow so i will try to submit a PR, by Sunday.

**Comment by GrabzIt** [comment]
I have added a PR (https://github.com/cefsharp/CefSharp/pull/2012) to tie up the new scaling property, however it doesn't seem to work. So I think the key used in CEF maybe wrong. Unless I have missed something, but I don't think that is the case.

**Comment by GrabzIt** [comment]
However the good news is print to PDF is working again.

**Comment by amaitland** [comment]
> So I think the key used in CEF maybe wrong.

I think the `Key` is correct, though never hurts to double check. Looking a little deeper into the `Chromium` code, and the same key is used deep in their printing system.

https://cs.chromium.org/chromium/src/printing/print_settings_conversion.cc?type=cs&q=kSettingShouldPrintBackgrounds&l=207

There are other settings that don't appear to be working like `backgrounds_enabled`, so I think there might be another problem.

The `CEF` implementation is also hard coded to `GRAY`, so there are a few things that should be tweaked.

**Comment by GrabzIt** [comment]
You are probably right. I may return to this if I have another idea.

**Comment by GrabzIt** [comment]
This has been disabled by Chromium it works in the latest versions.
