### ISSUE TITLE
The page is misplaced in winform

### ISSUE THREAD

**Issue by cafe141** [cefsharp/CefSharp#1971]
![_20170228184904](https://cloud.githubusercontent.com/assets/26085630/23402471/ad7fdd64-fde6-11e6-95ee-127cfb1669c2.png)

Only the display of the page dislocation, the actual location of the control has not changed.

**Comment by merceyz** [comment]
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by jankurianski** [comment]
Please re-read issue template and attempt to identify whether problem is in CefSharp or CEF, as well as all of the other details required.
