### ISSUE TITLE
Why CefSharp can't access to HtmlDocument

### ISSUE THREAD

**Issue by ligui** [cefsharp/CefSharp#1974]
I know CefGule [https://bitbucket.org/xilium/xilium.cefglue](https://bitbucket.org/xilium/xilium.cefglue)    can access to HtmlDocument，but CefSharp can not。
Could you please add this feature to CefSharp?
Thanks!

**Comment by amaitland** [comment]
You can access the `DOM` using `Javascript` see https://github.com/cefsharp/CefSharp/wiki/General-Usage#javascript-integration for more details.

> I know CefGule https://bitbucket.org/xilium/xilium.cefglue can access to HtmlDocument

If there is a feature `CefGlue` provides that `CefSharp` doesn't then either submit a `PR` or simply use `CefGlue`.....
