### ISSUE TITLE
Sound effects not working in cef, but work in Chrome native.

### ISSUE THREAD

**Issue by h5aaimtron** [cefsharp/CefSharp#1975]
https://www.trickstercards.com/home/spades/

If you click play on the top right and start a game, in Chrome, the cards and other actions have sound effects. When run through cefsharp, there are no sound effects. I've enabled flash on the off-chance they were using it (pretty sure they aren't). Didn't see anything via google search on the topic, so putting this out there.

**Comment by amaitland** [comment]
> Due to licensing issues default builds do not support proprietary codecs like H264 and MP3, sites like Netflix/Twitter/Instagram won't play video/audio. See #1479 for more info.

As per the release notes, `CefSharp` does not have `proprietary codec` support included.

You can load http://detectmybrowser.com/ (or similar) to see which codes a browser supports.
