### ISSUE TITLE
Bug when typing in Japanese with WPF CefSharpe 

### ISSUE THREAD

**Issue by amir8985** [cefsharp/CefSharp#1978]
I'm using version 42 but i check it also with the example version 55.
Architecture x64?
Os Win10
WPF

Scenario to reproduce the problem:

- Download CefSharp wpf example
- Run it.
- Open Google page (or any page that you can write into)
- Open Japanese or Korean Keyboard
- Start typing

Problem: There is kind of a input window opened. (This window make a lot of bugs and it not necessary at all)
![3-7-2017 8-59-39 am](https://cloud.githubusercontent.com/assets/26243184/23645856/edef3090-0316-11e7-8b47-7f8963e36845.png)

I found that in the winform example it doesn't happen. Also in other applications like Crome, Outlook and Word this window doesn't open any time I trying to type in Korean.

can you help me? how can i prevent this window from opening?

Thanks, Amir

**Comment by jankurianski** [comment]
What about CEF offscreen?  CefSharp is just a wrapper around CEF.  Please re-read the new issue template, particularly the section about reproducing the problem in the CEF sample application.

**Comment by amaitland** [comment]
`IME` has issues in the `WPF` version, see #1262
