### ISSUE TITLE
CEF3: target=_blank does not work

### ISSUE THREAD

**Issue by perlun** [cefsharp/CefSharp#198]
Unknown exact why. It seems like the page "hangs" a bit when you click on such a link. Reloading the page afterwards work, though, so it's not like CEF or CefSharp completely dies. I suspect we are getting some kind of error value returned from CEF which we don't really handle properly at the moment.

**Comment by amaitland** [comment]
Tested using `37` and this appears to be working fine.

Test URL http://www.htmlcodetutorial.com/linking/_A_TARGET_95y98y108y97y110y107y.html

Closing issue.
