### ISSUE TITLE
Winforms High DPI support without enabling dpiAware in app.manifest

### ISSUE THREAD

**Issue by ShockwaveHF** [cefsharp/CefSharp#1982]
Is it possible to make CefSharp support high dpi without enabling dpiAware in the app.manifest? 

My application is a CefSharp/Winforms hybrid, and enabling dpiAware causes text cutoffs like the following:

With dpiAware: http://i.imgur.com/Bp8l10I.png
Without: http://i.imgur.com/m9MfCr5.png (Yes it's blurry, but i'd prefer this compared to having to make my massive project fully dpi aware)

Yes I have tried Cef.EnableHighDPISupport(); It doesn't seem to work for this issue.

Any help would be appreciated, thanks.

EDIT: Apologies for making this issue, I am quite tired and over worked, didn't read that the issues section is for bugs only, once again I apologise.

**Comment by amaitland** [comment]
> Yes I have tried Cef.EnableHighDPISupport(); It doesn't seem to work for this issue.

Make this the first call in your app if possible, see https://github.com/cefsharp/CefSharp.MinimalExample/blob/master/CefSharp.MinimalExample.WinForms/Program.cs#L16 for an example.

> Is it possible to make CefSharp support high dpi without enabling dpiAware in the app.manifest?

If `Cef.EnableHighDPISupport` isn't working for you then you need to include `dpiAware` in your manifest, this isn't a `CefSharp` requirement, it's a `Chromium` one.

> EDIT: Apologies for making this issue, I am quite tired and over worked, didn't read that the issues section is for bugs only, once again I apologise.

`stackoverflow` is better place to ask your questions. Next time please.

**Comment by amaitland** [comment]
The `CEF` implementation is 
https://bitbucket.org/chromiumembedded/cef/src/54647945f168cb46df034fed5f1c71730be27e4b/libcef/common/base_impl.cc?at=master&fileviewer=file-view-default#base_impl.cc-403

You should compare that to the `Chromium` implementation, see if there are any differences.
https://cs.chromium.org/search/?q=dpiaware+package:%5Echromium$&type=cs
https://cs.chromium.org/chromium/src/chrome/app/chrome_exe_main_win.cc?q=dpiaware+package:%5Echromium$&dr=CSs&l=121

You can look at calling `SetProcessDpiAwareness` manually
https://msdn.microsoft.com/en-us/library/windows/desktop/dn302122(v=vs.85).aspx

http://magpcss.org/ceforum/index.php is the best place to ask `CEF` specific questions.
