### ISSUE TITLE
Blurry texts in ChromiumWebBrowser

### ISSUE THREAD

**Issue by kevinvan44** [cefsharp/CefSharp#1985]
Due to some special reason, I need to use ViewBox to solve the self-adaptation problem of a WPF project. Things work fine in ViewBox in lower resolution, however, the fonts in the ChromiumWebBrowser looks terrible. The picture was shot under the resolution of 1024 X 768.
![aaa](https://cloud.githubusercontent.com/assets/7858425/23932352/5fa6abee-0972-11e7-8ef6-909d587ceb24.PNG)

**Comment by kevinvan44** [comment]
Any ideas?

**Comment by merceyz** [comment]
Please follow the issue template https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/issues/1831#issuecomment-253332896 for my comments on using a `ViewBox`. Scaling the browser is always going to have issues, best to resize the browser and zoom in/out.

In future, issue tracker is for bug reports only, thank you!

If you have a question, ask it on [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp)
