### ISSUE TITLE
Opening the ContextMenu

### ISSUE THREAD

**Issue by MichaelAguilar** [cefsharp/CefSharp#1986]
Sorry to post this here. I tried asking in the Gitter, but received no response. Likewise, I tried asking on StackOverflow, but the question got ignored. 

Is there any method for opening the ContextMenu programmatically? For instance, the first time the context menu is opening on a given page, I need to perform an async operation before displaying one the options (I cache the results after that, so it is only the first time). Ideally, I'd like to prevent the menu from opening (which I'm doing now), then once the async operation finishes, directly call the context menu to open (it only takes about 50ms). I couldn't find any info online as to how to accomplish this.

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

http://stackoverflow.com/questions/42791473/call-winforms-cefsharps-contextmenu-programmatically
