### ISSUE TITLE
Locale in CefSettings seems to be broken in 55

### ISSUE THREAD

**Issue by chylex** [cefsharp/CefSharp#1990]
- **What version of the product are you using?**
    - CefSharp.WinForms 55.0.0

- **What architecture x86 or x64?**
    - x86

- **On what operating system?**
    - Win 7, Win 10

- **What steps will reproduce the problem?**
    - Since 55, it seems that Locale isn't working properly, and always defaults to en-US

![image](https://cloud.githubusercontent.com/assets/3685160/24072202/89596ac6-0be3-11e7-8435-a363f8cd6cb9.png)

---

I haven't changed anything in related code across the two releases on the picture, so the only factor should be the upgrade to latest CefSharp (I know that the default one should be *en-US* and not *en*, I fixed that now but it doesn't make a difference since both examples use locale from the cmd line). The 'locales' folder is present in both cases.

![image](https://cloud.githubusercontent.com/assets/3685160/24072228/3f5b1e46-0be4-11e7-8b06-cef0bf10e5d8.png)

Note: I went to try whether this would happen in CEF alone, but it seems their example app archive is corrupted or something, I can't extract the files properly. If you can't easily determine whether this has something to do with some change in CefSharp, I'll try investigating this further.

**Comment by amaitland** [comment]
> I went to try whether this would happen in CEF alone, but it seems their example app archive is corrupted or something, I can't extract the files properly.

Once you've tested with `cefclient` report back. Very little has changed `CefSharp` wise.

**Comment by amaitland** [comment]
Looks like your seeing https://bitbucket.org/chromiumembedded/cef/issues/2081/windows-2840-cefsettingslocale-does-not

Making this as `upstream` and closing as it's been fixed in the `2987` branch (You can test using the current `master`).
