### ISSUE TITLE
NavStateChangedEventArgs not in version 55

### ISSUE THREAD

**Issue by Paraig** [cefsharp/CefSharp#1992]
I downloaded CefSharp.WPF Version 55.0.0.0 using the Package Manager Console, mirroring the KnowledgeBase sample code and using an x64 build configuration with Windows 7 and Visual Studio 2015. I am evaluating various options for embedded browsers.

When I did this the Browser NavStateChanged event and corresponding NavStateChangedEventArgs are unknown. When I compared this to the KnowledgeBase sample code I noticed it was using version 39.0.0.0 of the CefSharp dlls. When I replaced the v55 dlls with the v39  versions the event and args were recognised, indicating the functionality has been deprecated.

I tried to identify what the new equivalents of the above elements might be but I couldn't see any. As I am just evaluating the solution I am not sure what exact functionality I will require but it is a worry if newer versions no longer support older functionality. Can you please advise which version I should be using and/or what class elements I should be using.

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

**Comment by amaitland** [comment]
> This project is no longer maintained for a working example checkout the CefSharp MinimalExample project

https://github.com/cefsharp/CefSharp.Tutorial#this-project-is-no-longer-maintained-for-a-working-example-checkout-the-cefsharp-minimalexample-project

If your new to the project then you should read https://github.com/cefsharp/CefSharp/wiki/General-Usage

Please don't use the Issue tracker for follow up questions.

**Comment by amaitland** [comment]
> I tried to identify what the new equivalents of the above elements might be but I couldn't see any.

A quick search using the search field above would have got you an answer in a matter of seconds.
https://github.com/cefsharp/CefSharp/search?q=navstatechanged&type=Issues&utf8=%E2%9C%93

**Comment by Paraig** [comment]
Hi Alex,

Thank you for your very quick reply, apologies for not spotting the answer
you highlighted, I did spend some time on Google searches but failed to
find the answer.
Once agin thanks for your reply, fully answers my question.

Paraig
