### ISSUE TITLE
Web page touch event didn't work in cefsharp browser.

### ISSUE THREAD

**Issue by zorc** [cefsharp/CefSharp#1993]
**What version of the product are you using?**
55.0.0

**What architecture x86 or x64?**
Both

**On what operating system?**
Win10 (Surface Pro)

**Are you using WinForms, WPF or OffScreen?**
WPF

**What steps will reproduce the problem?**

step.1
setting.CefCommandLineArgs.Add("touch-events", "enabled");
cefBrowser.IsManipulationEnabled=true;
MainWindow.Content = cefBrowser;

problem：
Can not touch web page content.

step.2
cefBrowser.IsManipulationEnabled=false;

problem：
Can touch web page content，but can not active HTML5 touch event，HTML5 web scroll bar or touch games not work.

example:
http://getbootstrap.com/javascript/#scrollspy

**Comment by amaitland** [comment]
The WPF control does not support touch events yet, see #228
