### ISSUE TITLE
Setting zoom level when chromium browser is initialized

### ISSUE THREAD

**Issue by Koozi** [cefsharp/CefSharp#1995]
Hi,
   I am trying to set the chromium's zoom level after  IsBrowserInitializedChanged event.
   The zoom level is changed, but when the page is loaded the zoom level returns to 0 and i need to set it 
   again, maybe it is not the right event to use when i want to set a starting zoom level?
 
   CefSharp version: 53.0.0.0

   My code looks like this:

   ```
chromiumWebBrowser.IsBrowserInitializedChanged += OnBrowserInitialized;
   private void OnBrowserInitialized(object sender, DependencyPropertyChangedEventArgs e)
   {
            if (chromiumWebBrowser.IsBrowserInitialized)
            {
                chromiumWebBrowser.ZoomLevel = 2;
            }
    }
```

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

**Comment by amaitland** [comment]
If you'd like to know what's going on then look at the source, you'll find your answer there.
