### ISSUE TITLE
Cannot overwrite referer header

### ISSUE THREAD

**Issue by hgupta9** [cefsharp/CefSharp#1997]
I know this is a repeat of #534, #722 and #884 but I still can't do it with CefSharp 51, Win32, .NET 4.5.2. This is my implementation.

		public CefReturnValue OnBeforeResourceLoad(IWebBrowser browserControl, IBrowser browser, IFrame frame, IRequest request, IRequestCallback callback) {

			var tab = myForm.GetTabByBrowser(browserControl);
			if (tab != null && tab.RefererURL != null) {

				var headers = request.Headers;

				// Set referer.
				headers["Referer"] = tab.RefererURL;

				// Update request headers.
				request.Headers = headers;

			}

			return CefSharp.CefReturnValue.Continue;
		}

Since the referer its already part of the headers my code is unable to **overwrite** the header value.

Steps to reproduce:
1. Open google.com
2. Run a search for "http://www.ericgiguere.com/tools/http-header-viewer.html"
3. Click on the first result - and analyse the headers displayed on the page

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

**Comment by amaitland** [comment]
See #1464 
 
http://cefsharp.github.io/api/51.0.0/html/M_CefSharp_IRequest_SetReferrer.htm

Please take the time to read the issue template, instructions are pretty simple
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by lxy789123** [comment]
@amaitland I've try setReferrer method.It didn't work...
and I've also try  request.Heads["referrer"] = "string". It didn't.

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp#contact for a list of options for asking questions.
