### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by zgl0707** [cefsharp/CefSharp#1998]
How to get texture ID，Thank you

**Comment by mountgellert** [comment]
I NEED SOMEBODY, HELP! NOT JUST ANYBODY! HELP! YOU KNOW I NEED SOMEONE! HEEEEEEEEEEELP!

**Comment by zgl0707** [comment]
hello,ls there any way to get texture ID in cefsharp

**Comment by mountgellert** [comment]
WON'T YOU PLEASE PLEASE HELP ME, HELP ME, HELP ME!

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).
