### ISSUE TITLE
Severity Code Description Project File Line Source Suppression State Error Cannot find type System.ServiceModel.ServiceHost in module System.ServiceModel.dll

### ISSUE THREAD

**Issue by llmsjraj** [cefsharp/CefSharp#2000]
I have installed WPF nuget in UWP application while build the solution i am getting this error :

Severity	Code	Description	Project	File	Line	Source	Suppression State
Error		Cannot find type System.ServiceModel.ServiceHost in module System.ServiceModel.dll.

Is it not compatible with UWP ?

**Comment by amaitland** [comment]
> Is it not compatible with UWP ?

No, try `CefGlue` or `ChromiumFx`.

**Comment by amaitland** [comment]
Duplicate of #1192
