### ISSUE TITLE
 Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies.  is not a valid Win32 application. (Exception from HRESULT: 0x800700C1)

### ISSUE THREAD

**Issue by bondib** [cefsharp/CefSharp#2003]
- **What version of the product are you using?**
55.0.0

- **What architecture x86 or x64?**
x64
- **On what operating system?**
 Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
Create an ANY CPU project and try to run it on a Win64 or specifally set it to 64 bit.
When you probe for - CefSharp.Core.Dll it will fail with:

 Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies.  is not a valid Win32 application. (Exception from HRESULT: 0x800700C1)

For some unclear reason, althoguh the WPF app is 64bit, as it gets to CefSharpCore.Dll it for some reason thinks its 32 bit...

- **What is the expected output? What do you see instead?**
Expecting it not to fail and to be able to load the dll

- **Please provide any additional information below.**

![image](https://cloud.githubusercontent.com/assets/16187518/24591480/d02721d6-180a-11e7-82ef-d1146ebedb15.png)

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
No debug.log file.

    - Any other background information that's relevant? Are you doing something out of the ordinary? Trying to work out for it to work with anyCPU - but even when setting directly to just 64bit it doesn't work well.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

Not sure

**Comment by bondib** [comment]
OK, I found it. It has to do with a side effect from sqllite beeing used under the same folder - but with an older .net version... :-( 
Sorry for the disturbance...

**Comment by xrf116** [comment]
@bondib  How did you solve it?

**Comment by Logendran1505** [comment]
I got the same error 
System.BadImageFormatException: 'Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies.  is not a valid Win32 application. (Exception from HRESULT: 0x800700C1)'

any solution for this error?

**Comment by amaitland** [comment]
> System.BadImageFormatException: 'Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. is not a valid Win32 application.

This would suggest you are using a very old unsupported version. I'd suggest you upgrade to the current supported version, version 102 at time of writing. 

If the problem persists after upgrading then open a new discussion. 

https://github.com/cefsharp/CefSharp/discussions
