### ISSUE TITLE
Setting BrowserSubProcessPath in CefSettings causes WPF based ChromiumWebControl not to render

### ISSUE THREAD

**Issue by ashishgupta02** [cefsharp/CefSharp#2005]
I am using visual studio 2015 and Instance of ChromiumWebBrowser does not render when I set BrowserSubprocessPath. I used minimal example and added the below specific CefSettings before window InitialzeComponent is called. What is a correct way of renaming the process name.

Thanks.

           // Initialized and Cef Global Setting Before Main Window Loads
            // It will be auto initialized to default if ChromiumBrowser object is loaded
            if(!Cef.IsInitialized) {
                CefSettings cefSettings = new CefSettings();
                //cefSettings.BrowserSubprocessPath = "ChromiumBrowserControl";
                cefSettings.CachePath = "ChromiumBrowserControlCache";
                cefSettings.IgnoreCertificateErrors = true;
                // Sets following commandline arguments --disable-gpu --disable-gpu-compositing --enable-begin-frame-scheduling
                //cefSettings.SetOffScreenRenderingBestPerformanceArgs();

                // Command Line Arguments
                cefSettings.CefCommandLineArgs.Add("disable-extensions", "1"); //Extension support can be disabled
                cefSettings.CefCommandLineArgs.Add("disable-pdf-extension", "1"); //The PDF extension specifically can be disabled
                // Disables the DirectWrite font rendering system on windows.
                // Possibly useful when experiencing blury fonts.
                cefSettings.CefCommandLineArgs.Add("disable-direct-write", "1");

                // Disable Flash
                cefSettings.CefCommandLineArgs.Add("disable-system-flash", "1");
                
                // Proxy Stuff
                // More Refinement is needed for reaching local IP's
                cefSettings.CefCommandLineArgs.Add("proxy-auto-detect", "1");
                cefSettings.CefCommandLineArgs.Add("winhttp-proxy-resolver", "1");
                Cef.Initialize(cefSettings);
            }

**Comment by merceyz** [comment]
Please follow the issue template.

You'd need to change the name of the sub-process executable then specify the new path to the file

**Comment by ashishgupta02** [comment]
@merceyz Can you please provide me link to issue template or link to example code to change BrowserSubprocess.exe to something else.
Thanks

**Comment by amaitland** [comment]
> What is a correct way of renaming the process name.

You should never rename `CefSharp.BrowserSubprocess.exe`, it's a signed `exe`. You can implement your own version of `CefSharp.BrowserSubprocess.exe`, it's a single `C#` class these days. Look at the project source.

In future, please keep the Issue tracker for bug reports only, thank you!

https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).
