### ISSUE TITLE
XamlParseException on debug

### ISSUE THREAD

**Issue by oddRaven** [cefsharp/CefSharp#2008]
When I try to run an empty project with just a ChromiumWebBrowser element, the application will throw a XamlParseException. It used to work in the past, but I remember getting this error before.

![xamlparseexception](https://cloud.githubusercontent.com/assets/9657411/24758694/6981baa0-1ae3-11e7-978a-e51c0680e699.PNG)

I have reinstalled CefSharp.WPF . Restored the Nuget packages, Removed the target elements from the project file. Rebuild everything. Changed the target platform from x86 to x64 and back.

I feel like I've tried everything. Anyone know what else I could try?

**Comment by amaitland** [comment]
There is no designer support for `WPF` in the current release version. See the [FAQ](https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#Wpf_designer) for details

Minimal support has been added and will be available in the next release see #1963 for details.


Please read over the [Issue Template](https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md), if your going to open an issue then please fill out the bug report next time. Thanks!

**Comment by oddRaven** [comment]
I am sorry for opening an issue on here, I'll keep in mind for next time. 

The problem occured after a SVN revision, in the output log there was an access violation exception in Cefsharp.Core.dll . The solution was to delete the package directory and let Nuget restore the packages.

Not sure what caused the XamlParseException though, I might compare the directories between revisions later today.
