### ISSUE TITLE
Silent Printing

### ISSUE THREAD

**Issue by adilmatech** [cefsharp/CefSharp#2009]
I have seen several post regarding this silent printing but no one give any answer can some tell me that is it possible to print directly to default printer without showing print dialog or option like kiosk???

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/wiki/General-Usage#printing
