### ISSUE TITLE
Simply cannot get cefsharp to input data

### ISSUE THREAD

**Issue by DutchXYZ** [cefsharp/CefSharp#2016]
I'm attempting to auto-login to a website but I cannot get cefsharp to interact with the website at all... I have searched for various solution and none have worked to-do with cefsharp.... I would use webbrowser but the website I'm trying to login too doesn't allow such an old browser to access it.

Lets assume all my Cefsharp staff is set up correctly (trust me I've gone over the tutorial at least 5 times) I am trying to grab the ID of the username field and replace it with what I want but whenever I try It just does not work.. For example:

`chromeBrowser.ExecuteScriptAsync("Document.GetElementById('username').InnerText = 'usernameExample'");`

My cefsharp is set up as follows:

```
`CefSettings settings = new CefSettings();
            // Initialize cef with the provided settings
            Cef.Initialize(settings);
            // Create a browser component
            chromeBrowser = new ChromiumWebBrowser("https://secure.runescape.com/m=world16/a=12/html5/comapp/login?from=%2F");
            // Add it to the form and fill it to the form window.
            this.Controls.Add(chromeBrowser);
            chromeBrowser.Dock = DockStyle.Fill;`
```

Could it be to-do with this error I am getting spammed with? (also cannot find a solution)

WARNING:quota_manager.cc(1833)] Create directory failed for path

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp)

**Comment by amaitland** [comment]
They're only warnings, if you set the CachePath, they should go away

Search the general usage guide for CachePath for more details
