### ISSUE TITLE
Draggable works more slow then another browser

### ISSUE THREAD

**Issue by balkarov** [cefsharp/CefSharp#2017]
- **What version of the product are you using?**
     - CefSharp.WPF v55.0.0 - via nuget
.net 4.5.2

- **What architecture x86 or x64?**
     - both x86 and x64

- **On what operating system?**
    - Win10?

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
   - WPF

- **What steps will reproduce the problem?**
    - Just load this page https://jqueryui.com/draggable/

- **What is the expected output? What do you see instead?**
   - Draggable freeze (I meabn it brakes). You can сompare draggable in Chrome and CefSharp. In Chrome fast work. But in the CefSharp draggable works more slow.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

    - Yes, sample app has the same problem

**Comment by amaitland** [comment]
If you need better performance you'll need to use the `WinForms` version hosted in `WPF`.

To get a better understanding of how the `WPF` control works read https://github.com/cefsharp/CefSharp/wiki/General-Usage#offscreen-rendering-osr

> Yes, sample app has the same problem

`CefSharp` is just a wrapper, performance is limited by the underlying `CEF` framework. 

People are working on improving the performance, you can track their progress at https://bitbucket.org/chromiumembedded/cef/issues/2046/improve-gpu-readback-performance-for-osr
