### ISSUE TITLE
CEFSetting.RegisterExtension causing a rendering error.

### ISSUE THREAD

**Issue by JimWilcox3** [cefsharp/CefSharp#2018]
I was asked to open this bug by @amaitland .  

Up until recently I have been using version 49.0.0 of the Winforms CEFSharp loaded from Nuget.  It was working fine until I updated to version 55.0.0 from Nuget.  At that point, if I use CEFSettings.RegisterExtension to load a javascript extension, it throws a rendering error when it tries to load a web page.  I am running on Windows 10.  The architecture is x64.

You can use the minimal working example and change the startup code as follows:

    [STAThread]
    public static void Main()
    {
        try
        {
            CefSettings settings = new CefSettings();

            settings.RegisterExtension(new CefExtension("showModalDialog", Resources.showModalDialog));

            //Perform dependency check to make sure all relevant resources are in our output directory.
            Cef.Initialize(settings, performDependencyCheck: true, browserProcessHandler: null);

           var browser = new BrowserForm("https://www.google.com");

            Application.Run(browser);
        }
        catch (Exception ex)
        {
            MessageBox.Show(ex.ToString());
        } 
    }

The code for the extension I want to add is as follows:

    (function () {
        absolutePath = function (href) {
            var link = document.createElement("a");
            link.href = href;
            return (link.protocol + "//" + link.host + link.pathname + link.search + link.hash);
        }
        showModalDialog = function (url, arg, opt) {
            url = url || ''; //URL of a dialog
            arg = arg || null; //arguments to a dialog
            opt = opt || 'dialogWidth:300px;dialogHeight:200px'; //options: dialogTop;dialogLeft;dialogWidth;dialogHeight or CSS styles
            var caller = showModalDialog.caller.toString();
            var dialog = document.body.appendChild(document.createElement('dialog'));
            dialog.setAttribute('style', opt.replace(/dialog/gi, ''));
            dialog.innerHTML = '<a href="#" id="dialog-close" style="position: absolute; top: 0; right: 4px; font-size: 20px; color: #000; text-decoration: none; outline: none;">&times;</a><iframe id="dialog-body" name="dialog-body" src="' + absolutePath(url) + '" style="border: 0; width: 100%; height: 100%;"></iframe>';
            //document.getElementById('dialog-body').contentWindow.dialogArguments = arg;
            document.getElementById('dialog-close').addEventListener('click', function (e) {
                e.preventDefault();
                dialog.close();
            });
            document.getElementById('dialog-body').addEventListener('load',     function (e) {
                this.style.height = this.contentWindow.document.body.scrollHeight + 'px';
                this.style.width = this.contentWindow.document.body.scrollWidth + 'px';
                this.contentWindow.close = function () {
                    dialog.close();
                };
                this.contentWindow.dialogArguments = arg;
                this.window = this.contentWindow;
            });

            dialog.showModal();
            //if using yield
            if (caller.indexOf('yield') >= 0) {
                return new Promise(function (resolve, reject) {
                    dialog.addEventListener('close', function () {
                        var returnValue = document.getElementById('dialog-    body').contentWindow.returnValue;
                        document.body.removeChild(dialog);
                        resolve(returnValue);
                    });
                });
            }
            //if using eval
            var isNext = false;
            var nextStmts = caller.split('\n').filter(function (stmt) {
                if (isNext || stmt.indexOf('showModalDialog(') >= 0)
                    return isNext = true;
                return false;
            });

            dialog.addEventListener('close', function () {
                var returnValue = document.getElementById('dialog-body').contentWindow.returnValue;
                document.body.removeChild(dialog);
                //nextStmts[0] = nextStmts[0].replace(/(window\.)?showModalDialog\(.*\)/g, JSON.stringify(returnValue));
                //eval('{\n' + nextStmts.join('\n'));
            });
            throw 'Execution stopped until showModalDialog is closed';
        };
    })();

If you comment out the call to settings.RegisterExtension in the startup code, it works fine.
Let me know if you need more information.

Thanks,
Jim

**Comment by amaitland** [comment]
You seem to have misunderstood, you'll need to open a bug with the CEF project. CefSharp is just a wrapper.

**Comment by JimWilcox3** [comment]
Oops, guess I did misunderstand.  Will they understand my problem if I tell them I am using CEF Sharp?

**Comment by JimWilcox3** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=665391

It's a Chrome thing and they are not going to fix it :(

**Comment by amaitland** [comment]
The CEF issue is still open, so there is a chance someone will fix this in the context of CEF, it's only a small chance though.

Any further comments should be redirected to
https://bitbucket.org/chromiumembedded/cef/issues/1944/js-extension-crashing-disabling-renderer
