### ISSUE TITLE
ChromiumWebBrowser.Dispose() method hang up

### ISSUE THREAD

**Issue by zeno32167** [cefsharp/CefSharp#2020]
This may be related to issue [Feature Request - Improve ChromiumWebBrowser Dispose/Finalise](https://github.com/cefsharp/CefSharp/issues/1954).

I run app with background Tasks. App executes Task every 5 minutes. Each Task creates handler object which is ChromiumWebBrowser from CefSharp.OffScreen (OffscreenChromiumWebBrowser on the screens), this task logic navigates to few www pages for about 30 seconds, and then browser is disposed and task is done. For the first few hours of running app browser is disposing correctly. It closes CefSharpBrowserSubprocess.exe and task is finished gracefully.

However after few hours of running, task hangs on the handler.Dispose() method and never finishes. It results in many tasks and many threads being frozen at handler.Dispose() method(see screens). Also in the task manager there is plenty of CefSharp.BrowserSubprocess.exe processes. 

I believe that if handler.Dispose() method would not hang up, these processes would be gone. I use System.Threading.Tasks.Task to run these Tasks.

Please see screenshots attached and file for processes with included command line.

Dispose method called on OffscreenChromiumWebBrowser. OffscreenChromiumWebBrowser is inherited class after ChromiumWebBrowser of CefSharp.OffScreen but it does not implement it's own Dispose method, it uses ChromiumWebBrowser .Dispose() method.

![1](https://cloud.githubusercontent.com/assets/9673306/25024835/89c6d016-2097-11e7-8fd3-a9a88d3fd2e8.jpg)

Here is exact place in CefSharp code:

![2](https://cloud.githubusercontent.com/assets/9673306/25024833/89c2ad7e-2097-11e7-9368-e71ea5ff2490.jpg)

And here are processes:

![3](https://cloud.githubusercontent.com/assets/9673306/25024834/89c42f96-2097-11e7-99a3-d646e56c0dff.jpg)

And file with command line for each of the processes.
[processes.txt](https://github.com/cefsharp/CefSharp/files/920925/processes.txt)

**Comment by amaitland** [comment]
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Also please fork the https://github.com/cefsharp/CefSharp.MinimalExample project and provide an example that reproduces your problem. 

Each version has it's own branch available at https://github.com/cefsharp/CefSharp/branches/all You can investigate this further on your own.

**Comment by amaitland** [comment]
Closing due to lack of feedback, an example that demonstrates the problem is required to reopen this.
