### ISSUE TITLE
CefSharp 55.0 with Microsoft Word Addin

### ISSUE THREAD

**Issue by arsalanyounus** [cefsharp/CefSharp#2021]
Hi,

Following [this](http://ourcodeworld.com/articles/read/173/how-to-use-cefsharp-chromium-embedded-framework-csharp-in-a-winforms-application) I am adding CefSharp Browser runtime through Nuget. In Windows Forms application it is working perfect but in a Microsoft Word addin project it's library is not being initialized.

[Sample Addin Project - 64 Bit](https://1drv.ms/u/s!AuF2-NvUsKHcdQayfHQ9zazyLFc)

Note: I was using 64 Bit libraries of CefSharp.

**Comment by merceyz** [comment]
Please read over the [Issue Template](https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md), if your going to open an issue then please fill out the bug report next time. Thanks!

**Comment by amaitland** [comment]
There is no support for running as an Office plugin. You should look at CefGlue or ChromiumFx as alternatives.
