### ISSUE TITLE
LoadingStateChange and FrameLoadStart/FrameLoadEnd not accurate

### ISSUE THREAD

**Issue by ZSSchulze** [cefsharp/CefSharp#2024]
- **What is the expected output? What do you see instead?**
Expected this to wait until page is fully loaded with all of the frames and javascript execution included.

It instead does not wait for all frames /javascript to finish loading.

- **Please provide any additional information below.**

Loading a webpage that has javascript that loads and inserts html portions of the website. The mainframe loads but there is still javascript running to create the rest of the webpage. LandingStateChanged triggers before everything is finished loading.

This URL can be used as an example. The button will enable before webpage is completely ready.

```
private readonly ChromiumWebBrowser browser;
browser = new ChromiumWebBrowser("http://services.runescape.com/m=world11/html5/comapp/")
            {
                Dock = DockStyle.Fill,
            };
browser.LoadingStateChanged += OnLoadingStateChanged;
            browser.FrameLoadStart += OnFrameLoadStart;
            browser.FrameLoadEnd += OnFrameLoadEnd;

        private void OnLoadingStateChanged(object sender, LoadingStateChangedEventArgs args)
        {
            this.InvokeOnUiThreadIfRequired(() => setButton(!args.CanReload));
        }
 public void setButton(bool isLoading)
        {
            if (isLoading)
                bStart.Enabled = false;
            else
                bStart.Enabled = true;
        }
````

**Comment by amaitland** [comment]
> Expected this to wait until page is fully loaded with all of the frames and javascript execution included.

`CefSharp` is just a wrapper around `CEF`. Both events are tied to resource loading, not `DOM` loading.

Marking this as` invalid` as we have no control over how `CEF` behaves.

**Comment by amaitland** [comment]
I will point out the event your describing is likely impractical to implement in a general sense. How do you clearly define when `javascript` has finished modifying the `DOM`?  What part of the `javascript API` clearly defines when `loading` is complete? 

I see you've asked on [StackOverflow](http://stackoverflow.com/questions/43477410/cefsharp-detect-when-entire-page-is-loaded), anyone wishing to discuss this further should comment/answer there.
