### ISSUE TITLE
How to configure the use of Localstorage, why my app after the exit, localstorage was emptied?

### ISSUE THREAD

**Issue by SunArlen** [cefsharp/CefSharp#2026]
version：53.0.1
x86
win7

Do not exit the app, just close the page and then open Localstorage will not be emptied, exit app next login, my saved information is cleared。

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

**Comment by amaitland** [comment]
You will need to set a `CachePath` to persist data, see https://github.com/cefsharp/CefSharp/wiki/General-Usage#cefsettings-and-browsersettings (Search the rest of the document if you need a detailed example).

Follow up questions ask on `Stackoverflow` as this issue tracker is for bugs only, thanks.

**Comment by SunArlen** [comment]
sorry，I have not noticed that I can not submit the question here, thank you for your reply。I will try it。

**Comment by amaitland** [comment]
> sorry，I have not noticed that I can not submit the question here

When you created the issue, the first think you saw should have been https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#please-only-open-an-issue-if-you-have-a-bug-to-report-if-you-simply-have-a-question-or-require-some-assistance-keep-reading-for-info-if-you-do-have-a-bug-to-report-please-use-the-bug-report-template-below

**Comment by SunArlen** [comment]
Year, I am very sorry,  I will pay attention。
