### ISSUE TITLE
Use HttpWebRequest cookies

### ISSUE THREAD

**Issue by Herya** [cefsharp/CefSharp#2027]
Hi,

I did not find a special place to ask question so I hope it's ok there. If not I hope you can tell me where to ask.

I do a POST request to be able to login programmatically in C#. So It works, and I get the cookie of my session and the html source code of the page where I'm logged.
As webbrowser is using old internet explorer, I use cefsharp (and soon maybe sharpbrowser) to display the html code with the "LoadHtml()" method.

            using (StreamReader sr = new StreamReader(getResponse.GetResponseStream()))
            {
                string sourceCode = sr.ReadToEnd();
                chromeBrowser.LoadHtml(sourceCode, "http://www.example.com/");
            }

It display my page. But what I want is that if I click any link I'm still logged. Instead when I click I'm redirected to the login page.
How can I give cefsharp the cookie I have so I stay logged in ?

Thanks.

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp).
