### ISSUE TITLE
js invoke AsyncJsObject method not working,once send a big param

### ISSUE THREAD

**Issue by MrSong0607** [cefsharp/CefSharp#2028]
- **What version of the product are you using?**
    - Nuget:55.0.0

- **What architecture x86 or x64?**
	 - x64
- **On what operating system?**
    - Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
	- WinForms
- **What steps will reproduce the problem?**
    hello everyone,there is a problem when i use the RegisterAsyncJsObject method
first i registed a object like follow

```
public class SyncFuncObj
  {
   public void BusinessRegister(string str, IJavascriptCallback javascriptCallback)
        {
        //do nothing
          if (javascriptCallback.CanExecute)
                {
                    javascriptCallback.ExecuteAsync(true);
                }
          }
}

 chromiumWeb.RegisterAsyncJsObject("SmileComObj", new SyncFuncObj(), new BindingOptions { CamelCaseJavascriptNames = false });
```
in js ,i send a json string with guid array  to cefObj.BusinessRegister like this
```
cefObj.BusinessRegister(guidArrJsonStr,function(e){console.log(e)});
```

- **What is the expected output? What do you see instead?**
	- once the length of guidArrJsonStr beyound a specific number ,and then,cefObj will not working,include the callback and other invoke after this

- **What steps will reproduce the problem?**
 
i create a array,which contains 200 guid string, i will upload the Screenshot of my opration,you will see when i first invoke the function,it return true,when i second invoke the function,there has nothing result,and it not enter the breakpoint in my winform project

![Alt text](http://i2.muimg.com/567571/de717d9377eed2d6.png)
[This link](http://i2.muimg.com/567571/de717d9377eed2d6.png)

**Comment by amaitland** [comment]
When filling out a bug report please use the template provided https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report (You can view the raw version at https://raw.githubusercontent.com/cefsharp/CefSharp/master/ISSUE_TEMPLATE.md to copy and paste)

**Comment by MrSong0607** [comment]
@amaitland i changed the report as template

**Comment by amaitland** [comment]
@MrSong0607 Your bug report still lacks detail

- How big a string are you passing?
- How do you actually reproduce the problem? The code you've provided is very generic, really no different to any of the examples.

Like everything there are practical limits to how big a string can be, in this case those limits are imposed by `CEF/Chromium`. It's entirely possible you've surpassed one of those limits.

**Comment by amaitland** [comment]
> - **What steps will reproduce the problem?**
>    - Please provide detailed information here, enough for someone else to reprodce your problem.
>    - Please no binary (zip, etc) links, fork the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) and push your changes to `GitHub`. (Alternatively use a code sharing service list `Gist` or `Pastebin`).

This part of the bug report is very important.

**Comment by MrSong0607** [comment]
@amaitland i uploaded the screenshot of the process

**Comment by amaitland** [comment]
You'll need to provide example code that reproduces the problem. Please follow the instructions provided above, thanks.

**Comment by MrSong0607** [comment]
it seems the big param isn't the reason of the problem,the truth is that i defined a async method which return a Task object , once invoke the method ,all method of the bound object will not working.
i reproduce the problem in a new project , i'll show the problem code as follow:
```
    public class SyncFuncObj
    {
          public async Task BusinessRegister(string str, IJavascriptCallback javascriptCallback)
        {
            //do nothing
            if (javascriptCallback.CanExecute)
            {
                await javascriptCallback.ExecuteAsync(true);
            }
        }
    }
``` @amaitland

**Comment by amaitland** [comment]
You cannot return a Task, the you also don't make your method async. See the general usage guide on the wiki or check the source for working examples. 

Closing this as invalid this isn't a bug.
