### ISSUE TITLE
debug.log is always created, when possible

### ISSUE THREAD

**Issue by mikhail111777** [cefsharp/CefSharp#2029]
Hi!

Thank you for creating this easy to use and well documented library! I think I've found a BUG.

* I am running CefSharp 57.0.0, CEF 3.2987.1601
* Windows 10 x64
* OffScreen

When using two separate processes with these settings:
            var settings = new CefSettings();
            settings.CefCommandLineArgs.Add("disable-gpu", "1");
            settings.CefCommandLineArgs.Add("mute-audio", "1");
            settings.CefCommandLineArgs.Add("disable-renderer-accessibility", "1");
            settings.CefCommandLineArgs.Add("disable-histogram-customizer", "1");
            settings.CefCommandLineArgs.Remove("process-per-tab");

            settings.IgnoreCertificateErrors = true;
            settings.WindowlessRenderingEnabled = true;
            settings.SetOffScreenRenderingBestPerformanceArgs();
            settings.LogFile = Path.Combine(args[1], "browser.log");
            settings.LogSeverity = LogSeverity.Warning;
            settings.CefCommandLineArgs.Add("log-file", settings.LogFile);

            Cef.Initialize(settings, false, null);

When a process can access debug.log, it will do so and write all information to that file. The second, third, etc. process will write to the correct location.

**Comment by amaitland** [comment]
It's important to note that `CefSharp` is just a wrapper around the `Chromium Embedded Framework (CEF)`. Please use http://magpcss.org/ceforum/index.php for generic **CEF** questions. It is best place for this kind of question.

**Comment by amaitland** [comment]
Use `settings.LogFile` or `log-file` command line argument, don't set both.
