### ISSUE TITLE
The invocation of the constructor on type 'CefSharp.Wpf.ChromiumWebBrowser'

### ISSUE THREAD

**Issue by swapnildvdiipl** [cefsharp/CefSharp#2030]
### The invocation of the constructor on type 'CefSharp.Wpf.ChromiumWebBrowser' that matches the specified binding constraints threw an exception.' Line number '358' and line position '14'.
System.Windows.Markup.XamlParseException: 'The invocation of the constructor on type 'CefSharp.Wpf.ChromiumWebBrowser' that matches the specified binding constraints threw an exception.' Line number '358' and line position '14'. ---> System.IO.FileNotFoundException: Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found.

.Net Framework : 4.6.1

- This is working fin on my development machine.
- And when i deploy my application on clients machine with same configuration and required .net framework installed , it is throwing above error.

-What possibly could be wrong ?

**Comment by drewnoakes** [comment]
> System.IO.FileNotFoundException: Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies

Seems like a file is missing. Note that it might not be `CefSharp.Core.dll`, because as the message states it may be a dependency.

**Comment by swapnildvdiipl** [comment]
Thank you for the response.

All the dll's and dependencies are there in folder..Still the same .

**Comment by amaitland** [comment]
Install `VC++ 2013 Redist`, see below:

https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#Runtime_dependencies
https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#6-how-do-i-include-the-visual-studio-c-20122013-redistributables-on-the-target-app

When you installed the `Nuget` packages you would have been presented with the following [Readme.txt](https://github.com/cefsharp/CefSharp/blob/cefsharp/57/NuGet/Readme.txt#L16)

Please read over [Issue Template](https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md) when you have a moment, ideally this issue tracker is used for `bug reports` only, thanks!

**Comment by monicalabbao** [comment]
@amaitland I already installed VC++ 2017 Redist, as my Visual Studio is 2017. However, I am still having the same error on runtime.

**Comment by amaitland** [comment]
This issue tracker is for bug reports only, if you require assistance then see https://github.com/cefsharp/CefSharp#contact
