### ISSUE TITLE
Cannot differentiate between console log vs. error messages

### ISSUE THREAD

**Issue by drewnoakes** [cefsharp/CefSharp#2031]
[`ConsoleMessageEventArgs`](https://github.com/cefsharp/CefSharp/blob/master/CefSharp/Event/ConsoleMessageEventArgs.cs) doesn't provide information to differentiate between messages created in response to `console.log` versus those from `console.error`. Chrome's dev tools highlights and treats these differently.

From 'bug' template:

- feature missing from current master
- all architectures
- using WinForms, but I think this applies generally

It seems that adding some kind of level/severity enum property to the event args would be a non-breaking API change.

If this were something the project was interested in, and simple enough to add, I'd be happy to take a crack at it if someone wouldn't mind fielding the odd question. There's a good chance I would have the time to contribute to the project over the next while.

**Comment by amaitland** [comment]
We are limited by the API CEF provides

http://magpcss.org/ceforum/apidocs3/projects/(default)/CefDisplayHandler.html#OnConsoleMessage(CefRefPtr<CefBrowser>,constCefString&,constCefString&,int)

**Comment by drewnoakes** [comment]
Thanks, I'll refer to that site in future.

Some discussion about this on the ceforum:

http://magpcss.org/ceforum/viewtopic.php?f=6&t=13554

**Comment by amaitland** [comment]
> Some discussion about this on the ceforum:

This has been requested before see #1178
