### ISSUE TITLE
How to use SendKeyEvent to simulate key press?

### ISSUE THREAD

**Issue by juepiezhongren** [cefsharp/CefSharp#2033]
i was using Cefsharp.Wpf, and add a button in xaml and hook a handler to simulate type into the html input. My handler is like below.

        private void Button_Click(object sender, RoutedEventArgs e) {
            var host = wb.GetBrowser().GetHost();
            KeyEvent keyEvent = new KeyEvent();
            keyEvent.Type = KeyEventType.KeyDown;
            keyEvent.Modifiers = CefEventFlags.IsKeyPad;
            keyEvent.WindowsKeyCode = 7;
            host.SendKeyEvent(keyEvent);
        }

when i clicked the button, nothing happened in the html input. Beg for help!!! Have i made some serious mistakes???

**Comment by merceyz** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

**Comment by merceyz** [comment]
You seem to be missing the `NativeKeyCode`

**Comment by juepiezhongren** [comment]
hey,merceyz;
have you got demo to use SendKeyEvent, it's really hard to find one to run and learn.
beg u!!!!!!!!!!!!!

**Comment by juepiezhongren** [comment]
@merceyz 
hey,merceyz;
have you got demo to use SendKeyEvent, it's really hard to find one to run and learn.
beg u!!!!!!!!!!!!!
