### ISSUE TITLE
popup window icon problem

### ISSUE THREAD

**Issue by pyromus** [cefsharp/CefSharp#2037]
Hello 

I try to change icon of popup window but i cant change it. why did you forget this issue . is not it important ? You can try examples from here. Can you update this problem. thanks. 

http://www.javascript-coder.com/window-popup/javascript-window-open.phtml

<img src="http://puu.sh/vEdiQ/05746a088b.png">

**Comment by amaitland** [comment]
> why did you forget this issue . is not it important ?

There has been no oversight. You are responsible for setting the `Icon`. You need to implement `IDisplayHandler.OnFaviconUrlChange`, download the `Favicon` yourself and update the window using native method calls.

http://cefsharp.github.io/api/57.0.0/html/M_CefSharp_IDisplayHandler_OnFaviconUrlChange.htm
http://cefsharp.github.io/api/57.0.0/html/M_CefSharp_IBrowserHost_GetWindowHandle.htm

An example of setting the popup title is https://github.com/cefsharp/CefSharp/blob/8df4ec5342ac921756b598dd87c19ce8597af2e2/CefSharp.Core/Internals/ClientAdapter.cpp#L285
Same concept applies.

Before posting again please read https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md
Issue are for bug reports only, thank you!
