### ISSUE TITLE
IBrowser instance is null. Browser has likely not finished initializing or is in the process of disposing

### ISSUE THREAD

**Issue by AmierCheng** [cefsharp/CefSharp#2039]
version: CefSharp-cefsharp-53

error: 

1. IBrowser instance is null. Browser has likely not finished initializing or is in the process of disposing.   at CefSharp.WebBrowserExtensions.GetMainFrame(IWebBrowser webBrowser)
2.    at CefSharp.WebBrowserExtensions.EvaluateScriptAsync(IWebBrowser browser, String script, Nullable`1 timeout)
3.    at AntennaChat.ViewModel.Talk.PublicTalkMothed.leftGroupShowText(ChromiumWebBrowser cef, ChatMsgReceive msg, List`1 GroupMembers)
4.    at AntennaChat.ViewModel.Talk.TalkGroupViewModel.receiveMsg(Int32 mtp, ChatMsgReceive msg)

**Comment by amaitland** [comment]
Please read https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md before posting again.

That's a valid exception, you cannot execute `JS` at that point in time.
