### ISSUE TITLE
how to download cefsharp dll files

### ISSUE THREAD

**Issue by hlbbs** [cefsharp/CefSharp#2040]
help! how to download about of cefsharp all  dll files. thanks.

**Comment by merceyz** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

**Comment by merceyz** [comment]
https://github.com/cefsharp/CefSharp#releases

**Comment by hlbbs** [comment]
@merceyz thanks
