### ISSUE TITLE
WinForms - Toggle Form.ShowInTaskbar causes browser reload

### ISSUE THREAD

**Issue by sai10rman** [cefsharp/CefSharp#2042]
changing the minimal example with this line
add a menu item that does:
      this.ShowInTaskbar = !this.ShowInTaskbar;
causes the url to reload

Bug Report
using versions 55, 57
x86 + x64 
Win10
using `WinForms`

https://github.com/cefsharp/CefSharp.MinimalExample

**Comment by amaitland** [comment]
@ofersagi What research have you done? 

> Problem is, by the time the Load event fires, that call was already made. It was the CreateWindowEx() call that got the Load event to fire. So Winforms has to do something very nontrivial, it has to destroy the native window and recreate it again, now using a different value for the first argument

http://stackoverflow.com/a/20443430

`ShowInTaskbar` is not a property you can toggle in a trivial fashion. 

If you require advice on handeling this situation then I suggest you ask on [StackOverflow](stackoverflow.com/questions/tagged/cefsharp)

**Comment by amaitland** [comment]
Before posting again please read https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by ofersagi** [comment]
my research is that the same code with webbrowsercontrol (IE embedded) works fine for years without reloading the current url.
it is a legitimate bug even if you decide not to fix it.
the fact that there is an internal explanation for the situation does not cause it not to be a bug.
anyway i'll take into consideration it is not going to be fixed.
thanks.

**Comment by amaitland** [comment]
CEF doesn't provide a method to save and restore state, so you'll have to deal with the handle recreation. As parts of the .Net framework are internal I'm not even sure there is an event suitable. You may have to implement a NativeWindow to receive the relevant messages. 

I don't class this as a bug even if you do, it's a known behavior of .Net, you can likely remove the control and readd after your window has been recreated. 

By all means submit a PR if you can come up with a generic solution.

**Comment by amaitland** [comment]
It may be possible to handle this scenario by reparenting the browser window handle.

http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=10290

`Pull Requests` welcome.

**Comment by mitchcapper** [comment]
I am not sure if winforms is different but for WPF this is easy to work around.  Rather than having the ChromiumWebBrowser initialized in the xaml(the ui) one can simply have a ContentControl and have it's content set to a ChromiumWebBrowser instance in the code behind.      You can then move what this control is the child of (or even remove its parent completely) and it will not reload/refresh when added back to a control, even items like scroll position are saved.

**Comment by amaitland** [comment]
The `WinForms` version will require changes to allow for it to be re-parented when a new handle is created.

**Comment by amaitland** [comment]
Resolved with https://github.com/cefsharp/CefSharp/commit/85e32974ae21ea2f774351c758ba6a75c9c5b555

**Comment by MihaMarkic** [comment]
@amaitland It doesn't see to work for me.
Below is the code from Form1.cs (new Winforms project template) and using 65 pre2 CefSharp.
(I trigger it when user wants to close the form, but the trigger doesn't really matter)
Should I set anything? From looking at source it sounds like it should be done automatically.

Expected: to see browser as it was
Actual: no browser - same as it was in 63


```csharp
protected override void OnLoad(EventArgs e)
{
    if (!DesignMode)
    {
        browserControl = new ChromiumWebBrowser("https://blog.rthand.com/")
        {
            Dock = DockStyle.Fill
        };
        Controls.Add(browserControl);
    }
    base.OnLoad(e);
}

protected override async void OnClosing(CancelEventArgs e)
{
    e.Cancel = true;
    ShowInTaskbar = false;
    WindowState = FormWindowState.Minimized;
    base.OnClosing(e);

    await Task.Delay(1000);
    WindowState = FormWindowState.Normal;
    ShowInTaskbar = true;
}
```

**Comment by amaitland** [comment]
It works with the `CefSharp.WinForms.Example` when using the `Tabbed` control, which is what I would have tested with originally.

When the `ChromiumWebBrowser` is attached directly to the form it doesn't work as expected. At this point I'm not sure what the difference is.

**Comment by amaitland** [comment]
The browser needs to be temporarily re-parented to a new control whilst the handle is destroyed and a new one created.

A workaround would look something like.

```c#
var parent = toolStripContainer.ContentPanel;

var tempControl = new Control();
tempControl.CreateControl();

parent.Controls.Remove(browser);
tempControl.Controls.Add(browser);

ShowInTaskbar = !ShowInTaskbar;

tempControl.Controls.Remove(browser);
parent.Controls.Add(browser);

tempControl.Dispose();
tempControl = null;
```

`WinForms` moves it's controls to a parking window when a handle is being recreated, ideally we'd do the same, unfortunately all the methods required are declared internal.
- https://docs.microsoft.com/en-us/archive/blogs/sburke/flashback-windows-forms-parking-window
- https://stackoverflow.com/questions/20585012/what-are-parking-windows-in-winforms

**Comment by igorkrets** [comment]
this.Visible = !this.Visible;
