### ISSUE TITLE
I want to disable proxy at runtime

### ISSUE THREAD

**Issue by QueryHeaven** [cefsharp/CefSharp#2044]
### I want to disable proxy at runtime.But,I have to find it to modify it .Now,I want to disable it,Can you tell me what to do?

Now, I know how to modify it at runtime

``` 
Cef.UIThreadTaskFactory.StartNew(delegate {
      var rc = chromeBrowser.GetBrowser().GetHost().RequestContext;
      var v = new Dictionary<string, object>();
      v["mode"] = "fixed_servers";
      v["server"] = "scheme://server:port;
      string error;
      bool success = rc.SetPreference("proxy", v, out error);                
    });    
```

I want to implement it like 
```
var cefSettings = new CefSharp.CefSettings();
cefSettings.CefCommandLineArgs.Add("no-proxy-server","1");
```
but, I want to modify at runtime

**Comment by merceyz** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

**Comment by merceyz** [comment]
You can disable the use of proxy by calling
`settings.CefCommandLineArgs.Add("no-proxy-server", "1")`

To use a proxy:
`settings.CefCommandLineArgs.Add("proxy-server", "IP:Port");`

**Comment by amaitland** [comment]
> Set the value associated with preference name. If value is null the preference will be restored to its default value.

https://github.com/cefsharp/CefSharp/blob/cefsharp/57/CefSharp.Core/RequestContext.h#L305

Simply setting the preference to `null` should be sufficient. Please take more time to read the documentation.

**Comment by amaitland** [comment]
http://stackoverflow.com/questions/43927610/in-cefsharp-how-to-disable-the-agent-while-the-program-is-running
