### ISSUE TITLE
cefSharp.Subprocess.exe memory leak

### ISSUE THREAD

**Issue by YurdagulP** [cefsharp/CefSharp#2045]
Hi,
I was using  cef 47.0.0 version in my project and there was a memory leak. I changed cef with latest release version 57.0.0.  But the same problem is going on. For CefSharp.Subprocess.exe memory starts with 50 MB and after navigating pages memory usage reachs to 1.5 GB. 

Is there any solution, could you help me please?

**Comment by merceyz** [comment]
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Fork the https://github.com/cefsharp/CefSharp.MinimalExample project and provide an example that reproduces your problem.

**Comment by amaitland** [comment]
This issue will be closed in 14 days if there is no further feedback. Please read the instructions provided above.

**Comment by YurdagulP** [comment]
I tried with your minimal.example and the problem is not with cefSharp version. There are problems in my project that I called from cef. Thanks for your help.
