### ISSUE TITLE
CefSharp WPF Touch Scroll Issue

### ISSUE THREAD

**Issue by f-mushtaq-intagleo** [cefsharp/CefSharp#2046]
We are using CefSharp WPF version and we are facing problem to enable touch scroll on opened web pages, we are able to make simple touch works on the links and images but we are not able to make the touch scroll, bellow links claim it has been resolved but using the latest version we are not able to make it work, please suggest solution to this problem, its very urgent, Thanks in advance. 

Have used these links but failed. 
https://github.com/cefsharp/CefSharp/issues/975
https://github.com/cefsharp/CefSharp/pull/1418

**Comment by merceyz** [comment]
Please read https://github.com/cefsharp/CefSharp/issues/228#issuecomment-288895960
