### ISSUE TITLE
<Img> tag with a custom protocol and tilde symbol in URI in the source attribute crashes application

### ISSUE THREAD

**Issue by gribunin** [cefsharp/CefSharp#2047]
- **What version of the product are you using?**
Master branch from git, also reproduced in Nuget ver. 57.0.0

- **What architecture x86 or x64?**
Reproduced in x64. The x86 architecture I haven't tested.

- **On what operating system?**
Win7

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms

- **What steps will reproduce the problem?**
I am trying to open HTML file which contains &lt;img&gt; tag with a source attribute, which points to a resource with a custom protocol and URL containing "tilde" symbol (~). Minimal HTML example is the following:

```
<html>
<img src="ns://t~est.html">
</html>
```

- **What is the expected output? What do you see instead?**
Expected the application rendering a broken image if a custom protocol is not registered or calling methods of the registered custom protocol handler if it exists. Instead the application just crashes. 

- **Please provide any additional information below.**
In the log generated by CEF I see only the following message which seems to be related to the problem:
`bad message 1507679 terminating renderer.`
If the application has a registered factory for this custom protocol, its methods are not called before crash for this URL.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
I am not able to reproduce the bug using cefclient. I tested with cef_binary_3.3029.1619

**Comment by merceyz** [comment]
Could you please fork the https://github.com/cefsharp/CefSharp.MinimalExample project and provide an example that reproduces your problem.

**Comment by merceyz** [comment]
> ns://t~est.html

This is not a valid URI

A valid version would be `ns://example/t~est.html`

Adding this `{ "/t~est.html", "Test" }` to the `CefSharpSchemeHandlerFactory` and `<img src="custom://cefsharp/t~est.html">` to any file works
