### ISSUE TITLE
Can't build Winform Example.

### ISSUE THREAD

**Issue by fansollo22** [cefsharp/CefSharp#2049]
What is the expected output? What do you see instead?

It should build but instead i see 90 errors and 11 warning about namespace not found or dll's missing.

What steps will reproduce the problem?

Downloaded the soruce code, executred build.bat, opened cefsharp3.sln, restored nuget's, build and error occures. Tryied both with visual studio 2015 and 2017

Are you using WinForms, WPF or OffScreen?

Winforms

What version of the product are you using? On what operating system? x86 or x64?

Windows 10, 64 bit operating system, last version.

Win7, Win 8, Win10, etc?

Windows 10

Aditional info :

Even the minimalistic examples gives me errors.

Later edit : 
Managed to build the minimalistic examples but the winform example you provided still gives me errors.

Console log here : 

> 1>------ Build started: Project: CefSharp.Core, Configuration: Debug Win32 ------
1>Stdafx.cpp
1>E:\Visual Studio\VC\Tools\MSVC\14.10.25017\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory
1>Done building project "CefSharp.Core.vcxproj" -- FAILED.
2>------ Build started: Project: CefSharp.BrowserSubprocess.Core, Configuration: Debug Win32 ------
3>------ Build started: Project: CefSharp.Example, Configuration: Debug x86 ------
4>------ Build started: Project: CefSharp.Wpf, Configuration: Debug x86 ------
5>------ Build started: Project: CefSharp.WinForms, Configuration: Debug x86 ------
2>Stdafx.cpp
2>E:\Visual Studio\VC\Tools\MSVC\14.10.25017\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory
4>CSC : error CS0006: Metadata file 'C:\Users\Sorin\Desktop\New folder\CefSharp-master\CefSharp.Core\bin\Win32\Debug\CefSharp.Core.dll' could not be found
6>------ Build started: Project: CefSharp.OffScreen, Configuration: Debug x86 ------
6>CSC : error CS0006: Metadata file 'C:\Users\Sorin\Desktop\New folder\CefSharp-master\CefSharp.Core\bin\Win32\Debug\CefSharp.Core.dll' could not be found
5>CSC : error CS0006: Metadata file 'C:\Users\Sorin\Desktop\New folder\CefSharp-master\CefSharp.Core\bin\Win32\Debug\CefSharp.Core.dll' could not be found
2>Done building project "CefSharp.BrowserSubprocess.Core.vcxproj" -- FAILED.
7>------ Build started: Project: CefSharp.BrowserSubprocess, Configuration: Debug x86 ------
7>CSC : error CS0006: Metadata file 'C:\Users\Sorin\Desktop\New folder\CefSharp-master\CefSharp.BrowserSubprocess.Core\bin\Win32\Debug\CefSharp.BrowserSubprocess.Core.dll' could not be found
3>CSC : error CS0006: Metadata file 'C:\Users\Sorin\Desktop\New folder\CefSharp-master\CefSharp.Core\bin\Win32\Debug\CefSharp.Core.dll' could not be found
8>------ Build started: Project: CefSharp.Wpf.Example, Configuration: Debug x86 ------
9>------ Build started: Project: CefSharp.WinForms.Example, Configuration: Debug x86 ------
10>------ Build started: Project: CefSharp.OffScreen.Example, Configuration: Debug x86 ------
10>CSC : error CS0006: Metadata file 'C:\Users\Sorin\Desktop\New folder\CefSharp-master\CefSharp.Core\bin\Win32\Debug\CefSharp.Core.dll' could not be found
10>CSC : error CS0006: Metadata file 'C:\Users\Sorin\Desktop\New folder\CefSharp-master\CefSharp.Example\bin\x86\Debug\CefSharp.Example.dll' could not be found
10>CSC : error CS0006: Metadata file 'C:\Users\Sorin\Desktop\New folder\CefSharp-master\CefSharp.OffScreen\bin\x86\Debug\CefSharp.OffScreen.dll' could not be found
9>CSC : error CS0006: Metadata file 'C:\Users\Sorin\Desktop\New folder\CefSharp-master\CefSharp.Core\bin\Win32\Debug\CefSharp.Core.dll' could not be found
9>CSC : error CS0006: Metadata file 'C:\Users\Sorin\Desktop\New folder\CefSharp-master\CefSharp.Example\bin\x86\Debug\CefSharp.Example.dll' could not be found
9>CSC : error CS0006: Metadata file 'C:\Users\Sorin\Desktop\New folder\CefSharp-master\CefSharp.WinForms\bin\x86\Debug\CefSharp.WinForms.dll' could not be found
8>C:\Users\Sorin\Desktop\New folder\CefSharp-master\CefSharp.Wpf.Example\SimpleMainWindow.xaml(11,10): error MC3074: The tag 'ChromiumWebBrowser' does not exist in XML namespace 'clr-namespace:CefSharp.Wpf;assembly=CefSharp.Wpf'. Line 11 Position 10.
8>C:\Users\Sorin\Desktop\New folder\CefSharp-master\CefSharp.Wpf.Example\Views\BrowserTabView.xaml(419,18): error MC3074: The tag 'ChromiumWebBrowser' does not exist in XML namespace 'clr-namespace:CefSharp.Wpf;assembly=CefSharp.Wpf'. Line 419 Position 18.
========== Build: 0 succeeded, 10 failed, 1 up-to-date, 0 skipped ==========

**Comment by amaitland** [comment]
There is currently no support for building with `VS2017`. Official builds use `VS2013`

You can check https://ci.appveyor.com/project/cefsharp/cefsharp to see what the current build status is at any point (this includes building the example projects contained within the main projects source). It's possible there's a problem with building with `VS2015` with `master`. 

In general you should be using a `Release Branch` for when testing out the project. See https://github.com/cefsharp/CefSharp#release-branches

**Comment by amaitland** [comment]
Overall there was a trivial problem with building `master` with `VS2015` which has been resolved. I would still suggest using the `cefsharp/57` branch (current release branch at time of writing)

If your still having problems then make sure you've got the `C++` development tools installed in `VS`.

This issue has been resolved, for general support ask on `Gitter` or `Stackoverflow`.

**Comment by Jongkeun** [comment]
@amaitland 
I'm curious if it has been fixed for `VS2017` now.
I've also tried to build, but failed with the same errors.

**Comment by amaitland** [comment]
I use `VS2017` on a daily basis, the `CI` builds us `VS2015`. `VS2019` is also supported. You are likely missing the `VC++` development tools.

Unless you are planning on contributing code then testing with https://github.com/cefsharp/CefSharp.MinimalExample is the recommended option.

Further questions please use one of the options listed at https://github.com/cefsharp/CefSharp#contact
