### ISSUE TITLE
Losing injected JS object upon reload

### ISSUE THREAD

**Issue by exinferis** [cefsharp/CefSharp#2050]
We are using Cefsharp (47 & 48) in one of our projects and inject a JS Object to the browser instance in order to interact with the web app running within the browser.

We now have the problem (since 47.0 I think), that upon page (re)load within the browser, the injected JS object gets "lost". The code to inject the js object in the constructor is this:

```
        public void setupJSInterface()
        {
            JSInterface = new JavascriptCEFInterface(Browser);
            CefSharp.BindingOptions JSBindingOpt = new BindingOptions();
            JSBindingOpt.CamelCaseJavascriptNames = false;
            Browser.RegisterJsObject("OutObj", JSInterface, JSBindingOpt);
        }
```

This code has been untouched for a year and a half or so - so I don't think, that this is the problem. Has anyone any idea or solution or even knows what might have changed?

**Comment by amaitland** [comment]
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Also please fork the https://github.com/cefsharp/CefSharp.MinimalExample project and provide an example that reproduces your problem.

**Comment by amaitland** [comment]
There is no version 48, version 57 is the current supported version, anything older is not supported.

**Comment by amaitland** [comment]
Testing with https://github.com/cefsharp/CefSharp/tree/cefsharp/57 and I see no signs of any problems with Reloading or navigating to different pages.

**Comment by amaitland** [comment]
You will need to fork the `MinimalExample` and provide a demo that reproduces this problem.

**Comment by amaitland** [comment]
Closing due to lack of feedback, I've seen no other reports and unable to reproduce.. If you can provide a working example that uses the latest version then this can be reopened. Please fork the `MinimalExample` and use that as the basis of your example.

At time of writing current version is `57.0.0`
