### ISSUE TITLE
Detect Textbox is clicked in HTML Page using CEFSharp and get type of the HTML Control

### ISSUE THREAD

**Issue by f-mushtaq-intagleo** [cefsharp/CefSharp#2051]
We are working on application using CefSharp to browse Web Site which is not hosted on our server. We want to open the windows On Screen keyboard when any textbox control got focused or user click on textbox. Is there any way to track when html textbox control got focused/clicked.

OR 

If anyone can guide us, how we can install some extensions like "Virtual Keyboard" as extension in chrome. Does CEF supports to install extensions concept or not.

Please suggest solution to this problem, thanks in advance.

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp)

**Comment by amaitland** [comment]
http://stackoverflow.com/questions/44021326/detect-textbox-is-clicked-in-html-page-using-cefsharp-and-get-type-of-the-html-c
