### ISSUE TITLE
HTML5 content video playing in background and temp content folder can't be deleted.

### ISSUE THREAD

**Issue by laxmanp** [cefsharp/CefSharp#2054]
Hello, I have integrate CefSharp.WPF in my WPF application for showing html5 content.
I have ContentList.xaml that showing all Html5 content list and Html5Player.xaml that playing all Html5 content. I select content from ContentList.xaml it navigates to Html5Player.xaml window and play Html5 content in that window. After navigating Html5Player.xaml zip file extract to temp location and open index.html file in CefSharp browser control.
I have zip file for each content. Each content have one index.html file, videos and some other files.
My issue is after close Html5Player window or click on back button it navigates to previous ContentList window and delete Html5 temp folder but video sound is playing in background. Again i open that content it throws exception "Access denied" because Html5 temp folder can't be delted and that video is access by MyApp process.
I tried to delete Html temp folder forcefully but that video is access in MyApp process and I kill that process my application is closed.
So how to forcefully close video and after that delete content folder without closing my current application because video open in MyApp.
Please help me, how to do in c#(WPF).

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).
