### ISSUE TITLE
WPF, How set different CachePath for new window with browser

### ISSUE THREAD

**Issue by Spocher** [cefsharp/CefSharp#2055]
Hello.
I'm trying set different CachePath for all new windows with browser in Cefsharp.WPF.
This code work in Cefsharp.Winforms:
`var requestContextSettings = new RequestContextSettings
{
	CachePath = Path
};
var requestContext = new RequestContext(requestContextSettings);
Browser = new ChromiumWebBrowser("https://google.com")
{
	RequestContext = requestContext, 
};`
pnl_Browser.Controls.Add(Browser);
And each new window has its own Cache.
But, when I'm trying to do this in Cefsharp.WPF it doesn't work
`var requestContextSettings =
	new RequestContextSettings {CachePath = PathToCache}; 
var requestContext = new RequestContext(requestContextSettings);
Browser = new ChromiumWebBrowser {RequestContext = requestContext};`

How can i set different CachePath in Cefsharp.WPF?

**Comment by amaitland** [comment]
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Also please fork the https://github.com/cefsharp/CefSharp.MinimalExample project and provide an example that reproduces your problem.

**Comment by amaitland** [comment]
Please fill out the `Bug Report` template provided above. This issue will be closed if no further feedback is provided.

**Comment by A-VORONKIN** [comment]
Same problem. Any fix?

**Comment by nFox18** [comment]
The location where data for the global browser cache will be stored on disk.
In this value is non-empty then it must be an absolute path that is must be either
equal to or a child directory of CefSettings.RootCachePath (if RootCachePath
 is empty it will default to this value).
