### ISSUE TITLE
Windows .Net WinForm Executable Crashes when using CefSharp 53 Release

### ISSUE THREAD

**Issue by pradsin** [cefsharp/CefSharp#2057]
I am Using CefSharp to open Html Pages in WinfowsForm, if used for long time the Application Crashes, on analyzing the crash dump I found that the app crash is in libcef.dll

here is windbg analysis.

----------------------------------------------------------------------------------------------------------------------

Microsoft (R) Windows Debugger Version 10.0.10240.9 X86
Copyright (c) Microsoft Corporation. All rights reserved.

Loading Dump File [E:\Shared\Logs\SGFW-PC-001859\3CLogicClient.exe.7564.dmp]
User Mini Dump File with Full Memory: Only application data is available

************* Symbol Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       symsrv*symsrv.dll*E:\Symbols*E:\PDBs*http://msdl.microsoft.com/download/symbols
Symbol search path is: symsrv*symsrv.dll*E:\Symbols*E:\PDBs*http://msdl.microsoft.com/download/symbols
Executable search path is: 
Windows 7 Version 7601 (Service Pack 1) MP (2 procs) Free x86 compatible
Product: WinNt, suite: SingleUserTS
Machine Name:
Debug session time: Fri May 26 22:10:27.000 2017 (UTC + 5:30)
System Uptime: 10 days 9:07:19.362
Process Uptime: 0 days 1:41:21.000
................................................................
................................................................
................................................................
.....................
Loading unloaded module list
.............................................................
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(1d8c.23a0): Access violation - code c0000005 (first/second chance not available)
No .natvis files found at C:\Program Files (x86)\Windows Kits\10\Debuggers\x86\Visualizers.
eax=00000000 ebx=11c0e610 ecx=00000000 edx=00000000 esi=00000002 edi=00000000
eip=772a016d esp=11c0e5c0 ebp=11c0e65c iopl=0         nv up ei pl zr na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000246
ntdll!NtWaitForMultipleObjects+0x15:
772a016d 83c404          add     esp,4
0:041> !sym noisy
noisy mode - symbol prompts on
0:041> .ecxr
*** WARNING: Unable to verify checksum for libcef.dll
DBGHELP: libcef - private symbols & lines 
        e:\symbols\libcef.dll.pdb\3B59CA910DE940C89844829B608917261\libcef.dll.pdb
eax=595e01dd ebx=00000000 ecx=16ffea90 edx=5936f27c esi=17495b20 edi=09fb9528
eip=20726961 esp=11c0ec44 ebp=11c0ec48 iopl=0         nv up ei pl nz na po nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010202
20726961 ??              ???
0:041> !analyze -v
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************

DBGHELP: kernel32 - public symbols  
        e:\symbols\wkernel32.pdb\A2C03C4BFF06402E8FD5456A786D85AD2\wkernel32.pdb
DBGHELP: E:\Symbols\sos_x86_x86_4.0.30319.36371.dll\57E8D3036a0000\sos_x86_x86_4.0.30319.36371.dll - OK
DBGHELP: E:\Symbols\sos_x86_x86_4.0.30319.36371.dll\57E8D3036a0000\sos_x86_x86_4.0.30319.36371.dll - OK

DBGHELP: clr - public symbols  
        e:\symbols\clr.pdb\B0BF51A79BB44DDF8FEF2E9949892BA42\clr.pdb
*** WARNING: Unable to verify checksum for mscorlib.ni.dll
DBGHELP: mscorlib_ni - public symbols  
        e:\symbols\mscorlib.pdb\6A933D40E86C48FC824A2439146F24191\mscorlib.pdb

DBGHELP: ieframe - public symbols  
        e:\symbols\ieframe.pdb\6B854A000E6F4F73A09A1A44C07E07F52\ieframe.pdb

DBGHELP: user32 - public symbols  
        e:\symbols\wuser32.pdb\2989D28D81D042579DB67AD418C0AF682\wuser32.pdb
SYMSRV:  e:\symbols\ole32.pdb\AE606D8908084496AD3FE118DE6778A02\ole32.pdb - file not found
SYMSRV:  e:\pdbs\ole32.pdb\AE606D8908084496AD3FE118DE6778A02\ole32.pdb - file not found
*** ERROR: HTTP_STATUS_NOT_FOUND
*** ERROR: HTTP_STATUS_NOT_FOUND
*** ERROR: HTTP_STATUS_NOT_FOUND
*** ERROR: HTTP_STATUS_NOT_FOUND
SYMSRV:  e:\symbols\ole32.pdb\AE606D8908084496AD3FE118DE6778A02\ole32.pdb not found
SYMSRV:  e:\pdbs\ole32.pdb\AE606D8908084496AD3FE118DE6778A02\ole32.pdb not found
SYMSRV:  http://msdl.microsoft.com/download/symbols/ole32.pdb/AE606D8908084496AD3FE118DE6778A02/ole32.pdb not found
DBGHELP: ole32.pdb - file not found
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for ole32.dll - 
DBGHELP: ole32 - export symbols

DBGHELP: mscoreei - public symbols  
        e:\symbols\mscoreei.pdb\3AC29AD368224E4188FB7D34B8B50D942\mscoreei.pdb

DBGHELP: mscoree - public symbols  
        e:\symbols\mscoree.pdb\5EB01A03276E4F6BB974E19A522150E12\mscoree.pdb
SYMSRV:  e:\symbols\3CLogicClient.pdb\2E67A33B75C340E9B6E35F69C552F32C1\3CLogicClient.pdb - file not found
SYMSRV:  e:\pdbs\3CLogicClient.pdb\2E67A33B75C340E9B6E35F69C552F32C1\3CLogicClient.pdb - file not found
*** ERROR: HTTP_STATUS_NOT_FOUND

*** ERROR: HTTP_STATUS_NOT_FOUND
*** ERROR: HTTP_STATUS_NOT_FOUND
SYMSRV:  e:\symbols\3CLogicClient.pdb\2E67A33B75C340E9B6E35F69C552F32C1\3CLogicClient.pdb not found
SYMSRV:  e:\pdbs\3CLogicClient.pdb\2E67A33B75C340E9B6E35F69C552F32C1\3CLogicClient.pdb not found
SYMSRV:  http://msdl.microsoft.com/download/symbols/3CLogicClient.pdb/2E67A33B75C340E9B6E35F69C552F32C1/3CLogicClient.pdb not found
DBGHELP: c:\3CLogicSourceCode\webastra_dotnet_client\branches\5.7_Chrome_NoRedis\src\WebAstra\App\WebAstraClient\obj\x86\Release\3CLogicClient.pdb - file not found
*** ERROR: Module load completed but symbols could not be loaded for 3CLogicClient.exe
DBGHELP: 3CLogicClient - no symbols loaded

DBGHELP: mshtml - public symbols  
        e:\symbols\mshtml.pdb\50119843C9884640934634EAFC48426F2\mshtml.pdb

DBGHELP: GdiPlus - public symbols  
        e:\symbols\MicrosoftWindowsGdiPlus-1.1.7601.23721-gdiplus.pdb\249E3AC506F845BABFCD6E15CC463A821\MicrosoftWindowsGdiPlus-1.1.7601.23721-gdiplus.pdb

DBGHELP: rasman - public symbols  
        e:\symbols\rasman.pdb\DF9A860877F94FECBB7A2CF29C7D5EDD2\rasman.pdb
*** WARNING: Unable to verify checksum for System.Windows.Forms.ni.dll
DBGHELP: System_Windows_Forms_ni - public symbols  
        e:\symbols\System.Windows.Forms.pdb\51FC3AABA35945009DECD74632FA22931\System.Windows.Forms.pdb

DBGHELP: MMDevAPI - public symbols  
        e:\symbols\MMDevAPI.pdb\941E45A63E8F457D90CE29CC508C34B92\MMDevAPI.pdb
SYMSRV:  e:\symbols\scriptsn.pdb\6A172A4EE3AC4B4E96F0760487792A7F1\scriptsn.pdb - file not found
SYMSRV:  e:\pdbs\scriptsn.pdb\6A172A4EE3AC4B4E96F0760487792A7F1\scriptsn.pdb - file not found
*** ERROR: HTTP_STATUS_NOT_FOUND

*** ERROR: HTTP_STATUS_NOT_FOUND
*** ERROR: HTTP_STATUS_NOT_FOUND
SYMSRV:  e:\symbols\scriptsn.pdb\6A172A4EE3AC4B4E96F0760487792A7F1\scriptsn.pdb not found
SYMSRV:  e:\pdbs\scriptsn.pdb\6A172A4EE3AC4B4E96F0760487792A7F1\scriptsn.pdb not found
SYMSRV:  http://msdl.microsoft.com/download/symbols/scriptsn.pdb/6A172A4EE3AC4B4E96F0760487792A7F1/scriptsn.pdb not found
DBGHELP: D:\BUILD_669048\BUILD\VSCore\release\scriptsn.pdb - file not found
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for ScriptSn.20170425030411.dll - 
DBGHELP: ScriptSn_20170425030411 - export symbols

DBGHELP: msvcrt - public symbols  
        e:\symbols\msvcrt.pdb\F1D253F9555C46DF8076400A52B3A9292\msvcrt.pdb

DBGHELP: dsound - public symbols  
        e:\symbols\dsound.pdb\F38F478065E247C68EDA699606F56EED2\dsound.pdb

DBGHELP: mswsock - public symbols  
        e:\symbols\mswsock.pdb\4CEC62EEDFD0476B9C7D90DD228AE55A2\mswsock.pdb
*** WARNING: Unable to verify checksum for System.ni.dll
DBGHELP: System_ni - public symbols  
        e:\symbols\System.pdb\83FB6026B59C4A5F80271102FA3FCECF1\System.pdb

CONTEXT:  (.ecxr)
eax=595e01dd ebx=00000000 ecx=16ffea90 edx=5936f27c esi=17495b20 edi=09fb9528
eip=20726961 esp=11c0ec44 ebp=11c0ec48 iopl=0         nv up ei pl nz na po nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010202
20726961 ??              ???
Resetting default scope

FAULTING_IP: 
unknown!printable+0
20726961 ??              ???

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 20726961
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 00000008
   Parameter[1]: 20726961
Attempt to execute non-executable address 20726961

PROCESS_NAME:  3CLogicClient.exe

ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

EXCEPTION_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

EXCEPTION_PARAMETER1:  00000008

EXCEPTION_PARAMETER2:  20726961

WRITE_ADDRESS:  20726961 

FOLLOWUP_IP: 
unknown!printable+0
20726961 ??              ???

FAILED_INSTRUCTION_ADDRESS: 
unknown!printable+0
20726961 ??              ???

NTGLOBALFLAG:  0

APPLICATION_VERIFIER_FLAGS:  0

APP:  3clogicclient.exe

MISSING_CLR_SYMBOL: 0

ANALYSIS_VERSION: 10.0.10240.9 x86fre

MANAGED_CODE: 1

MANAGED_ENGINE_MODULE:  clr

MANAGED_ANALYSIS_PROVIDER:  SOS

MANAGED_THREAD_ID: 23a0

BUGCHECK_STR:  SOFTWARE_NX_FAULT_SEHOP_INVALID

DEFAULT_BUCKET_ID:  SOFTWARE_NX_FAULT_SEHOP_INVALID

PRIMARY_PROBLEM_CLASS:  CPU_CALL_ERROR

LAST_CONTROL_TRANSFER:  from 5903d44a to 20726961

STACK_TEXT:  
WARNING: Frame IP not in any known module. Following frames may be wrong.
11c0ec40 5903d44a 11c0ec58 5852ed0a 16ffec20 0x20726961
11c0ec48 5852ed0a 16ffec20 17598cd8 11c0ec90 libcef!views::HWNDForWidget+0xb
11c0ec58 584e1808 00000001 17491398 09fb9528 libcef!CefBrowserPlatformDelegateNativeWin::SendFocusEvent+0x3e
11c0ec90 584e32ce 00000001 17491398 09fb9528 libcef!CefBrowserHostImpl::OnSetFocus+0xa2
11c0ecc8 58518cca 00000001 11c0f8e8 0000008a libcef!CefBrowserHostImpl::SetFocus+0x87
11c0ecdc 58519cfc 174913ac 174913a8 11c0ed50 libcef!base::internal::RunnableAdapter<void (__thiscall `anonymous namespace'::CefBeforeResourceLoadCallbackImpl::*)(bool)>::Run<scoped_refptr<`anonymous namespace'::CefBeforeResourceLoadCallbackImpl> const &,bool const &>+0x26
11c0ecec 5781630f 17491390 59ab78b0 09ccf648 libcef!base::internal::Invoker<base::internal::BindState<base::internal::RunnableAdapter<void (__thiscall `anonymous namespace'::CefBeforeResourceLoadCallbackImpl::*)(bool)>,`anonymous namespace'::CefBeforeResourceLoadCallbackImpl * const,bool &>,void __cdecl(void)>::Run+0x16
11c0ed50 577be547 598ffd1c 11c0f8e8 ffffffff libcef!base::debug::TaskAnnotator::RunTask+0x16f
11c0f8c4 577bf287 11c0f8e8 00000000 09c993a8 libcef!base::MessageLoop::RunTask+0x347
11c0f9d0 5780987f 00000000 09c993a8 772b4029 libcef!base::MessageLoop::DoWork+0x3e7
11c0fa00 578094a5 11c0fa60 09ccae10 09ccae10 libcef!base::MessagePumpForUI::DoRunLoop+0x5f
11c0fa2c 577fb5f9 09ccae10 00000000 09d7577c libcef!base::MessagePumpWin::Run+0x55
11c0fa58 577d7748 09ccae10 00000000 00000001 libcef!base::RunLoop::Run+0x49
11c0fa7c 577d78f4 09ccae10 09cd6c78 74fe1420 libcef!base::Thread::Run+0x18
11c0fab8 577b2f57 00000000 00000000 09cd6c78 libcef!base::Thread::ThreadMain+0x124
11c0fad8 74fe336a 09cd6c78 11c0fb24 772b9902 libcef!base::`anonymous namespace'::ThreadFunc+0x87
11c0fae4 772b9902 09cd6c78 53ef4683 00000000 kernel32!BaseThreadInitThunk+0xe
11c0fb24 772b98d5 577b2ed0 09cd6c78 00000000 ntdll!__RtlUserThreadStart+0x70
11c0fb3c 00000000 577b2ed0 09cd6c78 00000000 ntdll!_RtlUserThreadStart+0x1b

POSSIBLE_INVALID_CONTROL_TRANSFER:  from 5903d445 to 590393a4

ADDITIONAL_DEBUG_TEXT:  Followup set based on attribute [Is_ChosenCrashFollowupThread] from Frame:[0] on thread:[PSEUDO_THREAD]

SYMBOL_STACK_INDEX:  0

SYMBOL_NAME:  invalid_control_transfer!Unknown

FOLLOWUP_NAME:  MachineOwner

MODULE_NAME: invalid_control_transfer

DEBUG_FLR_IMAGE_TIMESTAMP:  0

STACK_COMMAND:  .ecxr ; kb

BUCKET_ID:  CPU_CALL_ERROR

IMAGE_NAME:  invalid_control_transfer

FAILURE_PROBLEM_CLASS:  SOFTWARE_NX_FAULT_SEHOP_INVALID

FAILURE_EXCEPTION_CODE:  c0000005

FAILURE_IMAGE_NAME:  invalid_control_transfer

FAILURE_FUNCTION_NAME:  Unknown

FAILURE_SYMBOL_NAME:  invalid_control_transfer!Unknown

FAILURE_BUCKET_ID:  SOFTWARE_NX_FAULT_SEHOP_INVALID_c0000005_invalid_control_transfer!Unknown

ANALYSIS_SOURCE:  UM

FAILURE_ID_HASH_STRING:  um:software_nx_fault_sehop_invalid_c0000005_invalid_control_transfer!unknown

FAILURE_ID_HASH:  {7a5c9413-15c8-69b8-432d-71adc18ff1e3}

Followup:     MachineOwner
---------
 *** Possible invalid call from 5903d445 ( libcef!views::HWNDForWidget+0x6 )
 *** Expected target 590393a4 ( libcef!views::Widget::GetNativeWindow+0x0 )

**Comment by amaitland** [comment]
That version is no longer supported, if the problem reproduces in version 57.0.0 this can be reopened.

**Comment by pradsin** [comment]
Thanks for prompt reply, I will try to reproduce it with 57.0.0
