### ISSUE TITLE
Cancel PrintToPdfAsync

### ISSUE THREAD

**Issue by arvigeus** [cefsharp/CefSharp#2058]
For some external reasons pdf printing could take substantial amount of time and CPU. I want to implement timeout functionality, but I am unable to stop the task once it is started.

**Comment by arvigeus** [comment]
```
var task = browser.PrintToPdfAsync(path, null);
task.Wait(ctsToken);
browser.Dispose();
```

**Comment by amaitland** [comment]
You'll need to submit a feature request to http://www.magpcss.org/ceforum/viewforum.php?f=7

Currently CEF provides no way to cancel the method. The example you've provided won't actually do anything as the wrapper is just a TaskCompletionSource

This can be reopened if CEF ever adds the functionality.

**Comment by arvigeus** [comment]
PdfPrint is executed from CefSharp.BrowserSubprocess, isn't it? When printing some troublesome pages the process goes to 25-30% CPU usage. After I call `browser.Dispose()` the process dies peacefully and frees the CPU. In my code snippet I made a mistake: `task.Wait(ctsToken)` must be wrapped in try/catch to reach `browser.Dispose()`.
Are you really sure this won't work?

**Comment by amaitland** [comment]
What your doing isn't cancelling PDF creation it's closing the browser. 

If it meets your requirements then great, if not then you'll need to get changes implemented in CEF. CefSharp is just a wrapper.
