### ISSUE TITLE
How to disable WebRTC (ip leaks)

### ISSUE THREAD

**Issue by xerasy** [cefsharp/CefSharp#2059]
Hi, can you help me, how can i disable WebRTC ? i set proxy in settings, go to whoer.net and find my real ip in WebRTC. I try to disable it, but it doesnt work

```
settings.CefCommandLineArgs.Add("proxy-bypass-list", "127.*,192.168.*,10.10.*,193.9.162.*");
              settings.CefCommandLineArgs.Add("proxy-server", "socks5://189.102.64.13:65000");
          //  settings.CefCommandLineArgs.Add("webrtc.ip_handling_policy", "false");
            settings.CefCommandLineArgs.Add("webrtc.multiple_routes_enabled", "false");
            settings.CefCommandLineArgs.Add("webrtc.nonproxied_udp_enabled", "false");
            settings.CefCommandLineArgs.Add("webrtc.ip_handling_policy", "disable_non_proxied_udp");
            settings.CefCommandLineArgs.Add("enable-media-stream", "0");
            settings.CefCommandLineArgs.Add("enable_webrtc", "0");
  Cef.Initialize(settings);
```

Can you help me ?

**Comment by amaitland** [comment]
It's important to note that `CefSharp` is just a wrapper around the `Chromium Embedded Framework (CEF)`. Please use http://magpcss.org/ceforum/index.php for generic **CEF** questions. It is best place for this kind of question. Please search before asking your question, it's highly likely your question has already been answered.

**Comment by xerasy** [comment]
On that site I also asked the question. I've searched but found no answer, decided to ask you

**Comment by amaitland** [comment]
Ask your question wait for a reply then. This issue tracker is for bug reports only, please read https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md before posting again, thank you.
