### ISSUE TITLE
SendMouseWheelEvent does not work reliable in WPF

### ISSUE THREAD

**Issue by Clemani** [cefsharp/CefSharp#2062]
The SendMouseWheelEvent stops working at some point after scrolling and clicking around.
I have attached a small sample project (only the code files) to re-produce the issue:
- click on "Test SIte 1", wait until the page is loaded
- click on "Start Scroll Timer" and move the mouse into the page, it starts scrolling down and up
- while the page scrolls up and down, click the menu items, for ex. "GREEN INIATIVES" and one of the sub-menu items... it may take some tries to get a sub-menu item successfully clicked... then the SendMouseWheelEvent has no more effect. If this happens, also the physical mouse wheel stops working.

**Comment by merceyz** [comment]
No binary files.

Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Fork the https://github.com/cefsharp/CefSharp.MinimalExample project and provide an example that reproduces your problem.
