### ISSUE TITLE
Scrolling with mouse wheel does not work reliable

### ISSUE THREAD

**Issue by Clemani** [cefsharp/CefSharp#2064]
- **What version of the product are you using?**
57

- **What architecture x86 or x64?**
x64, issue occurs also with x86

- **On what operating system?**
Win 10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF, issue occurs also in WinForms

- **What steps will reproduce the problem?**
o In CefSharp.Wpf.Example.exe, enter the URL http://www.ccmua.org/
o Move the mouse over "DEPATMENTS"
o Scroll down and up with the mouse wheel. While doing this click rpeatedly the left mouse button when over "DEPATMENTS" and the sub menu items... it may take some tries to get a sub-menu item successfully clicked... then the mouse wheel has no more effect

This happens also with CefSharp.WinForms.Example.exe. In the WPF version it's a bit easier to re-produce.

- **What is the expected output? What do you see instead?**
Mouse wheel does no more scroll the page.

- **Please provide any additional information below.**
debug.log:
[0608/195225.873:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain

[0608/195231.486:INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'msie' of undefined", source: http://www.ccmua.org/wp-content/plugins/custom-contact-forms/js/jquery.tools.min.js?ver=4.6.1 (1)

[0608/195231.486:INFO:CONSOLE(5)] "Uncaught TypeError: $ is not a function", source: http://www.ccmua.org/wp-content/themes/avesta/javascript/theme-script.js (5)

[0608/195231.688:INFO:CONSOLE(4)] "Uncaught TypeError: $m(...).datepicker is not a function", source: http://www.ccmua.org/wp-content/plugins/custom-contact-forms/js/custom-contact-forms-datepicker.js?ver=4.6.1 (4)
.....

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
No, tested with cef_binary_3.3029.1619.geeeb5d7_windows64_client
But in cefclient i get the message "cefclient blocks dragging of URLs and files" displayed when i try to re-produce the error the same way as described above.
Maybe this message is related in some way with the described mouse wheel issue?

**Comment by DylanFPS** [comment]
There is a scrolling issue documented in the latest release notes:

> Known Issues
> 
> - WPF/OffScreen PDF Scrolling isn't working properly with the mouse wheel see #1916 for details, needs to be fixed in CEF. Use the WinForms version hosted in WPF as a workaround for now.

Don't know if it is relevant but there you go.

**Comment by merceyz** [comment]
The issue is that you're dragging and dropping a URL, cefclient blocks this so you'll need to handle the dragging and dropping of URLs

**Comment by Clemani** [comment]
This would explain why the mouse wheel does not work one time.
But when this happens, the mouse wheel keeps to be non-working even when i click then links on the page.

DylanFPS: I know, WPF..... maybe it works smoothly in 5 years.
