### ISSUE TITLE
how to embedded the loading Tips?

### ISSUE THREAD

**Issue by linchuanhai** [cefsharp/CefSharp#2065]
because the network is very slowly, So I would like to do some tip features,
just like when the remote page is loading then the browser can load the local tip html code at first.
when the remote page was completed then it can auto show the new content.
and how to do it?

**Comment by merceyz** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).
