### ISSUE TITLE
Basic Header and Customs

### ISSUE THREAD

**Issue by patsadow2** [cefsharp/CefSharp#2068]
Hello, i've got a question. How can i add custom header to ChrominumWebBrowser ?

**Comment by merceyz** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

**Comment by merceyz** [comment]
See https://github.com/cefsharp/CefSharp/issues/534#issuecomment-60694502
