### ISSUE TITLE
Adobe Connect Add ins not work

### ISSUE THREAD

**Issue by Khatami** [cefsharp/CefSharp#2069]
**What version of the product are you using?**
57

**What architecture x86 or x64?**
x64, issue occurs also with x86

**On what operating system?**
Win 10

**Are you using WinForms, WPF or OffScreen?**
WPF, issue occurs also in WinForms

**What steps will reproduce the problem?**

I Installed Adobe Connect add ins on my machine and it works well on Google Chrome.
But Adobe Connect doesn't work on cef csharp project.
Should i enable any setting?

**What is the expected output? What do you see instead?**
I expect it to works on cef csharp too.

**Comment by merceyz** [comment]
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Fork the https://github.com/cefsharp/CefSharp.MinimalExample project and provide an example that reproduces your problem.

**Comment by merceyz** [comment]
See https://github.com/cefsharp/CefSharp/issues/719#issuecomment-68309299

**Comment by Khatami** [comment]
@merceyz  Have you seen adobe connect addins , it's like a software that installed on computer and works on chrome , opera , firefox and .... 
I think it is not extension , it's a software that cef csharp can not access it.
