### ISSUE TITLE
why CPU usage close to reach to 100% when i use ChromiumWebBrowser play webp picture in wpf project

### ISSUE THREAD

**Issue by TinyleLearner** [cefsharp/CefSharp#2070]
why CPU usage close to reach to 100% when i use ChromiumWebBrowser play webp picture in wpf project,use CefSharp.Wpf library,set the ChromeWebBrowser address to webp picture path. But I use CefSharp.WinForms library play webp picture CPU usage at most 60%,I Writing the same code . Is CefSharp.Wpf question ?

**Comment by merceyz** [comment]
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Fork the https://github.com/cefsharp/CefSharp.MinimalExample project and provide an example that reproduces your problem.

**Comment by merceyz** [comment]
Closing due to lack of feedback
