### ISSUE TITLE
Unable to load Azure Video

### ISSUE THREAD

**Issue by fransiskusyoga** [cefsharp/CefSharp#2073]
- **What version of the product are you using?**
    -I am using NuGet CefSharp.wpf 57.0.0 in Visual studio community 2015

- **What architecture x86 or x64?**
   -x64, I run only on x64 setting not for "Any  CPU". 

- **On what operating system?**
    - Win7

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
   -WPF

- **What steps will reproduce the problem?**
    - I run simple program

```
MainWindow.xaml
<Window x:Class="CobaCEFSharp.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:CobaCEFSharp"
        xmlns:cef="clr-namespace:CefSharp.Wpf;assembly=CefSharp.Wpf"
        mc:Ignorable="d"
        Loaded="Windows_Loaded"
        Title="MainWindow" Height="350" Width="525">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition />
            <RowDefinition Height="Auto" />
        </Grid.RowDefinitions>
        <cef:ChromiumWebBrowser Grid.Row="0"
                          x:Name="chromeBrowser"/>
        <StatusBar Grid.Row="1">
            <ProgressBar HorizontalAlignment="Right"
                         IsIndeterminate="{Binding WebBrowser.IsLoading}"
                         Width="100"
                         Height="16"
                         Margin="3" />
            <Separator />
            <!-- TODO: Could show hover link URL here -->
            <TextBlock />
        </StatusBar>
    </Grid>
</Window>
```

```
MainWindow.xaml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using CefSharp;
using CefSharp.Wpf;

namespace CobaCEFSharp
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }
        
        private void Windows_Loaded(object sender, RoutedEventArgs e)
        {
            chromeBrowser.Load("http://myweb01.azurewebsites.net/mvideo01.html");
        }
    }
}
```
> 

- **What is the expected output? What do you see instead?**
  -Stream azure video

- **Please provide any additional information below.**
    - I had install adobe flash. I've test it on ultrasounds.com
    - Instead of playing video, I got "The video playback was aborted due to a corruption problem or because video used feature your browser did not support. (0x20400003)" message
    -the web page load .ism/manifest (not mp4) video run on azure media player

**Comment by fransiskusyoga** [comment]
something left behind
MainWindow.xaml
<Window x:Class="CobaCEFSharp.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:CobaCEFSharp"
        xmlns:cef="clr-namespace:CefSharp.Wpf;assembly=CefSharp.Wpf"
        mc:Ignorable="d"
        Loaded="Windows_Loaded"
        Title="MainWindow" Height="350" Width="525">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition />
            <RowDefinition Height="Auto" />
        </Grid.RowDefinitions>
        <cef:ChromiumWebBrowser Grid.Row="0"
                          x:Name="chromeBrowser"/>
        <StatusBar Grid.Row="1">
            <ProgressBar HorizontalAlignment="Right"
                         IsIndeterminate="{Binding WebBrowser.IsLoading}"
                         Width="100"
                         Height="16"
                         Margin="3" />
            <Separator />
            
            <TextBlock />
        </StatusBar>
    </Grid>
</Window>

**Comment by joe-williams-cccu** [comment]
See issue #1479 

"Are you trying to play audio that requires a proprietary codec? e.g. `mp3`? **Licensing restrictions prohibit `CEF`/`CefSharp` from distributing binary's that provide support.**"
