### ISSUE TITLE
Cefsharp website manipulate help me please

### ISSUE THREAD

**Issue by pheomis** [cefsharp/CefSharp#2075]
Hi,
I'm doing a stock tracking program. My problem is website manipulation sample [this page](http://opensource.spotify.com/cefbuilds/index.html) "Linux 32-bit Builds" I want to make the background of the table red or green.  Help me please...

Thank you

**Comment by merceyz** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).
