### ISSUE TITLE
WinForms can't load local html file

### ISSUE THREAD

**Issue by nickwei-wj** [cefsharp/CefSharp#2076]
when I execute my app I get a white screen, the code like this
```
String page = string.Format(@"{0}\html-resources\html\index.html", Application.StartupPath);
chromeBrowser = new ChromiumWebBrowser(page);
this.Controls.Add(chromeBrowser); 
chromeBrowser.Dock = DockStyle.Fill;
BrowserSettings browserSettings = new BrowserSettings();
browserSettings.FileAccessFromFileUrls = CefState.Enabled;
browserSettings.UniversalAccessFromFileUrls = CefState.Enabled;
chromeBrowser.BrowserSettings = browserSettings;
```
when I change the local html file to url, it looks ok:
`chromeBrowser = new ChromiumWebBrowser("www.github.com");`

The cefSharp version is 57

**Comment by saj51** [comment]
select each files under html-resources folder, then in properties set _Copy to Output Directory_ as **Copy Always**

**Comment by baby-Jie** [comment]
ensure set your index.html  always copy to output

**Comment by aphkyle** [comment]
> ensure set your index.html always copy to output

Thanks it worked
