### ISSUE TITLE
Can this cefsharp SetReferrer Make site referUrl?

### ISSUE THREAD

**Issue by zhizlm** [cefsharp/CefSharp#2079]
Can this cefsharp SetReferrer Make fake site referUrl?

**Comment by merceyz** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).
