### ISSUE TITLE
SSO GetAuthCredentials called everytime on application restart

### ISSUE THREAD

**Issue by arvindlloyds** [cefsharp/CefSharp#2080]
What version of the product are you using?
57.0.0.0, via Nuget in Visual Studio 2015

What architecture x86 or x64?
x64

On what operating system?
Win 7

Are you using WPF ?
WPF 

What steps will reproduce the problem?
1- have a SSO, NTLM enbaled website
2-assign the website's url to Cefbrowser
3-I have RequestHandler : IRequestHandler and the call reaches to GetAuthCredentials asking for entering UserName and Password.
4-Enter user-name and password
5-Url works.

==
problem - Username and password entered once must be stored by Cefsharp and must not be asked again using GetAuthCredentials. i.e. - GetAuthCredentials must not be called on application restart.

Why - Google Chrome and IE behaves in expected mannner.

Possible issues - 
-Cache is not getting set (just a guess)
-What else

Tried using Cef's CefSharp.MinimalExample-master.

Limitations-
I cant send out my SSO urls.

**### Any SSO url does not work first time. On stop and then Refresh (browser.ReloadCommand.Execute(new object())) it works. In IE11 and Google chrome these SSO urls work first time.**

**Comment by jankurianski** [comment]
- Have you tried setting a `CachePath`? Without this, it's like you're using Incognito mode.  See an example here: https://github.com/cefsharp/CefSharp/blob/0067d02360b241073a8f9e02ba360b19bc92430a/CefSharp.Example/CefExample.cs#L58
- Are you sure this is a bug in CefSharp and not a bug in CEF, or not a configuration issue?  What happens with the CEF example program:
-- Go to https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md
-- See the section "Does this problem also occur in the CEF Sample Application from ..."

**Comment by merceyz** [comment]
If the login is saved as a cookie you need to set a cache path.
If the login is saved as a session you need to take care of it yourself.
