### ISSUE TITLE
FrameLoadEnd called multiple times.

### ISSUE THREAD

**Issue by HeeysamH** [cefsharp/CefSharp#2084]
Hello,

IDK if its meant to do this but FrameLoadEnd is called multiple times when a page finishes loading,
My (test)code:

web.FrameLoadEnd += (sender, e) =>
{
switch(stage){
    case 1:
        stage = 2;
        break;
    case 2:
        stage = 3;
        break;
    case 3:
        stage = 4;
        break;
}
}

When FrameLoadEnd is called it goes through all of the 3 cases, and not the first case and then the second case on the second framloadend.

**Comment by merceyz** [comment]
See https://cefsharp.github.io/api/51.0.0/html/E_CefSharp_OffScreen_ChromiumWebBrowser_FrameLoadEnd.htm
