### ISSUE TITLE
Are there any plans to upgrade to. Net standard 2.x?

### ISSUE THREAD

**Issue by milenstack** [cefsharp/CefSharp#2087]
RT:Are there any plans to upgrade to. Net standard 2.x?

**Comment by jankurianski** [comment]
Please ask questions on Gitter: https://gitter.im/cefsharp/CefSharp

GitHub issues are for bug reports only.

https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md
