### ISSUE TITLE
IRequestHandler telling me to implement the hole thing.

### ISSUE THREAD

**Issue by HeeysamH** [cefsharp/CefSharp#2089]
Hello,
i wanted to just use the GetAuthCredentials so i can use my proxys,
but when i make this class:

public class MyRequestHandler : IRequestHandler
    {

        bool IRequestHandler.GetAuthCredentials(IWebBrowser browserControl, IBrowser browser, IFrame frame, bool isProxy, string host, int port, string realm, string scheme, IAuthCallback callback)
        {

            if (isProxy == true)
            {
                callback.Continue("sam", "123");

                return true;
            }

            return false;

        }
}

its telling me to implement all the other stuff with irequesthandler,
how do i fix this?

**Comment by jankurianski** [comment]
Please ask questions on gitter: https://gitter.im/cefsharp/CefSharp

GitHub issues are reserved for bug reports: https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by merceyz** [comment]
#2007 made it possible to just set it with 
`CefSharpSettings.Proxy = new ProxyOptions("127.0.0.1", "8080", "sam", "123");`
