### ISSUE TITLE
Can't GetDefaultCookieManager

### ISSUE THREAD

**Issue by HeeysamH** [cefsharp/CefSharp#2091]
var visitor = new CookieMonster(all_cookies => {
            var sb = new StringBuilder();
            foreach (var nameValue in all_cookies)
                sb.AppendLine(nameValue.Item1 + " = " + nameValue.Item2);
            BeginInvoke(new MethodInvoker(() => {
                MessageBox.Show(sb.ToString());
            }));
        });
        web.RequestContext.GetDefaultCookieManager().VisitAllCookies(visitor);

class CookieMonster : ICookieVisitor
    {
        readonly List<Tuple<string, string>> cookies = new List<Tuple<string, string>>();
        readonly Action<IEnumerable<Tuple<string, string>>> useAllCookies;

        public CookieMonster(Action<IEnumerable<Tuple<string, string>>> useAllCookies)
        {
            this.useAllCookies = useAllCookies;
        }

        public void Dispose()
        {
        }

        public bool Visit(Cookie cookie, int count, int total, ref bool deleteCookie)
        {
            cookies.Add(new Tuple<string, string>(cookie.Name, cookie.Value));

            if (count == total - 1)
                useAllCookies(cookies);

            return true;
        }
    }

this part:
web.RequestContext.GetDefaultCookieManager().VisitAllCookies(visitor);

is giving me an error, tels me to put some callback stuff into the getdefaultcookiemanager parameters, but i don't know what?``

**Comment by HeeysamH** [comment]
And how do i make a question lable?

**Comment by merceyz** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).
