### ISSUE TITLE
WS_EX_COMPOSITED makes it slow and unresponsive

### ISSUE THREAD

**Issue by IvoVargas** [cefsharp/CefSharp#2092]
Hi, when i use a very know method to prevent flikering on winforms, 
cefbrowser do not render until the window resizes and even then it renders very slow. :(

Can someone help me with this. Thanks.

Method to prevent flikering used:
```
protected override CreateParams CreateParams
    {
        get
            {
                CreateParams cp = base.CreateParams;
                cp.ExStyle |= 0x02000000;  // Turn on WS_EX_COMPOSITED
                return cp;
            }
    }
```

**Comment by merceyz** [comment]
I'm guessing winforms doesn't notice a change in the control.
I'm also assuming this is an issue in CEF
