### ISSUE TITLE
open a https url and report load error -165!

### ISSUE THREAD

**Issue by darkread** [cefsharp/CefSharp#2095]
I use this program to open a https://www.google.com is ok.
I use CefSharp.WinForms.Example.exe open a https url（ex: https://192.168.1.5） ,and the it report load error:-165;
The website（https://192.168.1.5 ） use the certificate which don't match the "192.168.1.5"，if I open 192.168.1.5  in IE8 or Chrome(39 and below), it will pop a alert dialog,  I accept the alert, then IE8( or chrome) will open the website(https://192.168.1.5).
 . How can I handler the -165 error in CefSharp.WinForms.Example?  And Always accepting the alert is best.

Cefsharp 37, 39, 57  all report load error -165. The website (https://192.168.1.5) is in our intranet, and I can not show it to you,.

**Comment by DylanFPS** [comment]
When you're initializing CEF, in the `CefSettings` you can set `IgnoreCertificateErrors` to `true`. That should do the trick.

**Comment by darkread** [comment]
I test it in Cefsharp3-49,  CefSharp.WinForms.Example project, but Error -165
in Program.cs line 40, I insert code like below:
`var settings = new CefSettings();
settings.IgnoreCertificateErrors = true;  // I add 
/* Comment or not , Error -165 alway occurred.
/*settings.CefCommandLineArgs.Add("show-cert-link", "1");
settings.CefCommandLineArgs.Add("ignore-certificate-errors", "1");
settings.CefCommandLineArgs.Add("ignore-urlfetcher-cert-requests", "1");
settings.CefCommandLineArgs.Add("show-cert-link", "1");
settings.CefCommandLineArgs.Add("show-cert-link", "1");
*/
Cef.Initialize(settings); `

**Comment by merceyz** [comment]
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/RequestEventHandler/RequestEventHandler.cs#L55-L62
Should probably do the trick
