### ISSUE TITLE
Magnet link not working

### ISSUE THREAD

**Issue by bakkar89** [cefsharp/CefSharp#2096]
Is there a support for Magnet links? because when i clicked a magnet link it just redirected me to an empty page.

Thanks

**Comment by joe-williams-cccu** [comment]
Implement `IRequestHandler` and provide an implementation of `OnProtocolExecution`. 
https://github.com/cefsharp/CefSharp/blob/7ba2de4392b2cf7b349844cf3891a6141f1d8a96/CefSharp.Example/RequestHandler.cs#L192

Ask these sort of questions in the Gitter chat https://gitter.im/cefsharp/CefSharp Remember to specify and provide what `CefSharp` version and flavour you're using (e.g. `57.0.0` and `WinForms` on `Windows 10`).
