### ISSUE TITLE
Set-Cookie header is merged when using custom resource handler, invalidating multiple cookies.

### ISSUE THREAD

**Issue by r3dqu33n** [cefsharp/CefSharp#2097]
I'm using the nuget last release (v57.0.0) x86 arch with WinForms on Win 7/8

- **What steps will reproduce the problem?**
    i'm setting a custom scheme in whose IResourceHandler implementation, i'm setting a bunch of "Set-Cookie" headers (inside GetResponseHeaders method).

The problem i've seen is, that the cookies are being merged (with ',') cause of the NameValueCollection behaviour when called like String^ value = headers[key]; 

The resulting issue is what only the first cookie is being setted in CEF. The others are ignored.

I understand that the spected behaviour (almost in this case) is prevent this kind of merging and put the headers "as is". 
 
The affected function is TypeConversion::ToNative.

**Comment by merceyz** [comment]
Related PR #2099

**Comment by merceyz** [comment]
Fixed in https://github.com/cefsharp/CefSharp/commit/b82ce0787d0fecbe4d6cb3c99d3d46c1fbff4d22
