### ISSUE TITLE
Remove NDEBUG flag in Subprocess.Core

### ISSUE THREAD

**Issue by alphamax** [cefsharp/CefSharp#2098]
- **What version of the product are you using?**
    - V55 but still available in the project file of master

- **What architecture x86 or x64?**
   -Both

- **On what operating system?**
    - Win7, Win 8.1, Win10, Win10 Creator Update

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
   -Offscreen with directX rendering 👍 

- **What steps will reproduce the problem?**
    - Please see below. Even in Release you have the NDEBUG flag in the project. this mean that during my deployment phase some assemblies DEBUG are missing.
![image](https://user-images.githubusercontent.com/10722632/28422758-4ec7152e-6d69-11e7-824d-26752dffac0a.png)

- **What is the expected output? What do you see instead?**
    - Only embed release version of VC++ pack. Kind of DevOps bug no ? 😉

**Comment by merceyz** [comment]
Having that flag in release is normal as it stands for "no debug"

**Comment by alphamax** [comment]
Thanks for reading it but when i keep it (i don't know why) i need to export debug version of VC++ redistributable for my binaries.
