### ISSUE TITLE
Initialization of Browsers fails randomly

### ISSUE THREAD

**Issue by Punishbear** [cefsharp/CefSharp#2104]
- **What version of the product are you using?**
    - Version 45 from NuGet

- **What architecture x86 or x64?**
   - x64

- **On what operating system?**
    - Win10 for development, Win8.1 for release execution

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
  - OffScreen

- **What steps will reproduce the problem?**
    - using something like this https://pastebin.com/1bTRE1Ph the while-loop is already in place to combat the problem, same with the synclock around the init (which actually did help in a small dedicated test case, but didn't help anywhere else)

- **What is the expected output? What do you see instead?**
  - expect: usual OffScreen behavior, what we see: exceptions preventing us from using it

- **Please provide any additional information below.**
My company uses CefSharp to get data from certain websites that require JavaScript to render those sites. We initialize CefSharp, create a bunch of instances of a Browser class, which handles loading, waiting, some events. This happens multithreaded, between 3 to 5 tasks at the same time, usally. We loop over a List\<Task> that has x amount of tasks, once a task is done, a new one is added. After the program is done, CefSharp.Cef.Shutdown() is called. Sometimes a browser fails to initialize and the task gets aborted, and this is where the problem is. It happens completely random. Sometimes a few days pass and an app has not thrown one of those errors, sometimes, like today, we get logfiles that are 2.5 MB big. It doesn't seem to matter if the init is in the task that does the work or outside of it. I tried both ways. We're looking for a solution since CefSharp v45 was fresh and tried a lot of things, which I recall only a few of. Switching to the newest version didn't help either. 
The last big cefsharp.log still has 47 000 lines after I removed the "Running without renderer sandbox" errors, and that's only from today, from one app. It consists mostly of pipe errors, "No browser info matching frame process id x and routing id y" and "Failed to initialize command buffer.". Those seem to be cef related, so I'm not sure if they are relevant here. Anyways, maybe it helps.

Soooo, the big question is, are we doing something wrong with the initialization? Or is it a bug in CefSharp? IIRC, I've seen someone posting a bounty for fixing an issue that seems to be related to this.

**Comment by merceyz** [comment]
V45 is extremely old, I suggest using a newer version.
Another option (since the crashes are random) is to use multiple processes.
One process each task, if it crashes just restart the process.
