### ISSUE TITLE
CEF Crashes Office(Outlook)

### ISSUE THREAD

**Issue by TonyValenti** [cefsharp/CefSharp#2109]
Hi All,
There seems to be a weird bug in CEF when it is loaded as part of an outlook addin extension.  My bug report is below and I prepared a sample app that demonstrates the issue:
https://github.com/TonyValenti/CefCrashesOutlook

Can you take a look and let me know what the issue is?

**What version of the product are you using?**
NUGET with Version 57

**What architecture x86 or x64?**
AnyCPU with CefSharpAnyCpuSupport (doesn't seem to work with 32 or 64 bit either)

**On what operating system?**
Windows 10

**Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

**What steps will reproduce the problem?**
1.  Create a new outlook addin extension with CEF references
2.  Call CEF.Initialize
3.  Outlook hard crashes - the exception cannot even be caugh.
4.  This sample project demonstrates the issue:
https://github.com/TonyValenti/CefCrashesOutlook

**What is the expected output? What do you see instead?**
CEF Initializes and doesn't crash.

**Please provide any additional information below.**
A stack trace if available, any Exception information.
It hard crashes and doesn't give a stacktrace.  However, the debug window does show:
An unhandled exception of type 'System.IO.FileNotFoundException' occurred in Unknown Module.

Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
Nope.  It is a completely empty 0kb file

Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?

**Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
  Most likely not.

**Comment by merceyz** [comment]
See https://github.com/cefsharp/CefSharp/issues/1191#issuecomment-130857148
