### ISSUE TITLE
Issue with Server 2008 R2 + CefSharp 49.0.0.0 version

### ISSUE THREAD

**Issue by Amit-Rajput** [cefsharp/CefSharp#2110]
I am using CefSharp 49.0.0.0 version in my Win Application with embedded HTML pages. On Win 7, 8 and 10 is working fine. on Win Server 2008 R2 and Server 2012 R2 it is failing.  Log contains “Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found.” I do not have any idea why it is failing there.

**Comment by joe-williams-cccu** [comment]
More than likely you need to install `Visual C++ Redistributable Packages for Visual Studio 2013` on your servers.

Double check the FAQ: https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#Runtime_dependencies

Please ask these sort of questions in the chat (https://gitter.im/cefsharp/CefSharp) or if you do open an issue, please follow the issue template (https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md)

**Comment by Amit-Rajput** [comment]
Thanks Joe, installing Visual C++ edistributable Packages for Visual Studio 2013 worked for me.
