### ISSUE TITLE
Application crashed on Could not load file or assembly CefSharp or one of its dependencies in Wix Project

### ISSUE THREAD

**Issue by JackDu1** [cefsharp/CefSharp#2113]
### Bug Report
Delete this line and everything above, and then fill in the details below.

- **What version of the product are you using?**
- CefSharp WinForms 57.0.0.0 via nuget installed
- CefSharp Common 57.0.0.0 via nuget installed
- CefSharp Cef.redist.x86 3.2987.1601 via nuget installed
- CefSharp Cef.redist.x64 3.2987.1601 via nuget installed

- **What architecture x86 or x64?**

- x86

- **On what operating system?**
    - Win10 x64

- **Are you using `WinForms`, `WPF` or `OffScreen`?**

- WinForms

- **What steps will reproduce the problem?**

1. Installed VS 2015 and Wix 3.10.
2. Create a new WinForms project and a new Wix project.
3. Install CefSharp plugin for WinForms Project(Out to Class Library which relied by Wix Project).
4.Rebuild the Wix project and Open the application to display the web site the application crashed on CefSharp ddl dependencies.

- **What is the expected output? What do you see instead?**
No crash
- **Please provide any additional information below.**
    - use the dependencyChecker.AssertAllDependenciesPresent utility to check the Wix and WinForms output folder all dependents are there except libEGL.dll and LibGLESv2.dll are missing.

- Create a new WinForms project(Output to Executable application) and Install CefSharp plugin then Application works perfect without crash.

 

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
No

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
Wix 3.10
- **Does this problem also occur in the `CEF` Sample Application from 
not verified

**Comment by jankurianski** [comment]
What is a Wix project?

Can you publish the source code that reproduces this problem on GitHub?  I personally won't install Wix, but I am happy to look at your source code.

**Comment by JackDu1** [comment]
i unable to publish out source code to there. there is a complex customize UI wix project to install a set of MSI package.
the customize UI written by C# and and the Wix project will refer the UI dll to handle business action. 
Is there anything that i can try and provide to you for investigate?

**Comment by jankurianski** [comment]
Can you provide some documentation on what a Wix project is and how does it run?

**Comment by merceyz** [comment]
See https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#Runtime_dependencies
