### ISSUE TITLE
youtube live streaming issues

### ISSUE THREAD

**Issue by bluethefoxyt** [cefsharp/CefSharp#2115]
when watching a live stream you see this error
![image](https://user-images.githubusercontent.com/21036927/29468660-15881cd2-843d-11e7-87d1-96e0e9ce1217.png)
(im using this stream as a example)
im wondering if this issue can be resolved
by changing up my code
any help would be usefull
thanks for reading this

**Comment by jankurianski** [comment]
Please start by reading our troubleshooting documentation first:
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

If you still have a question, ask on Gitter: https://gitter.im/cefsharp/CefSharp
