### ISSUE TITLE
How to clear cache

### ISSUE THREAD

**Issue by MeiJunZhang** [cefsharp/CefSharp#2118]
I try to close the form when I need to automatically close the browser cache, or manually close the browser cache, like Google browser functions, can you please do?

**Comment by joe-williams-cccu** [comment]
Ask questions like this in the chat (https://gitter.im/cefsharp/CefSharp) or, better yet, consult the wiki (https://github.com/cefsharp/CefSharp/wiki) or Google. `Issues` are for bona fide bug reports.

**Comment by ErcinDedeoglu** [comment]
@joe-williams-cccu there is no information in your links. Please explain how. Dont insert links. Also google redirecting to this issue!

**Comment by joe-williams-cccu** [comment]
My previous comment was quiteclear: Issues are for *bona fide* bug reports that *must* follow the issue template. This issue isn't a bug report and just clogs up the extremely limited resources for this project. If you have a *question* then either use the Gitter chat, StackOverflow or Google.
