### ISSUE TITLE
Program error reporting

### ISSUE THREAD

**Issue by MeiJunZhang** [cefsharp/CefSharp#2119]
CefSharp.WebBrowserExtensions.ThrowExceptionIfBrowserNotInitialized(CefSharp.IWebBrowser) 在 CefSharp.WinForms.ChromiumWebBrowser.GetBrowser() 在 CefSharp.WebBrowserExtensions.GetMainFrame(CefSharp.IWebBrowser) 在 CefSharp.WebBrowserExtensions.ExecuteScriptAsync(CefSharp.IWebBrowser, System.String) 在 SmartSimulatorForCefSharp.Main.Browser_FrameLoadEnd(System.Object, CefSharp.FrameLoadEndEventArgs) 在 SmartSimulatorForCefSharp.Main+<>c__DisplayClass17_0.<AddNewBrowser>b__1(System.Object, CefSharp.FrameLoadEndEventArgs) 在 CefSharp.WinForms.ChromiumWebBrowser.CefSharp.Internals.IWebBrowserInternal.OnFrameLoadEnd(CefSharp.FrameLoadEndEventArgs) 在 <Module>.CefSharp.Internals.ClientAdapter.OnLoadEnd(CefSharp.Internals.ClientAdapter*, CefRefPtr<CefBrowser>*, CefRefPtr<CefFrame>*, Int32)

**Comment by joe-williams-cccu** [comment]
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue
