### ISSUE TITLE
在请求网页的时候，Request Headers提示“Provisional headers are shown”

### ISSUE THREAD

**Issue by MeiJunZhang** [cefsharp/CefSharp#2122]
在请求网页时，开启开发者工具时，切换到NetWork时发现 “Request Headers” 提示“Provisional headers are shown”， 不知道其他人是否遇到这个问题，我尝试像其他人一样添加了跨域访问白名单也不行。不知道是什么问题！其中有一个开发人员提出了这个问题，地址是：
https://github.com/cefsharp/CefSharp/issues/698

**Comment by joe-williams-cccu** [comment]
I appreciate English isn't your first language, but when opening an issue please follow the [Issue Template](https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md)

You'll also get a better response if it is written in English.

**Comment by MeiJunZhang** [comment]
@joe-williams-cccu  Hi,joe-williams-cccu。
First of all, I'm sorry, because I was too anxious to know the answer。The problem I have is The get requests a web page, open the developer tools, switch to the NetWork found "Request Headers" Provisional headers are "that shown", do not know whether other people have this problem, I try to like other people add a cross domain access is not white list.

**Comment by merceyz** [comment]
Duplicate of #2123
