### ISSUE TITLE
The problem I have is The get requests a web page

### ISSUE THREAD

**Issue by MeiJunZhang** [cefsharp/CefSharp#2123]
CefSharp Version 51.0.0
The problem I have is The get requests a web page, open the developer tools, switch to the NetWork found "Request Headers" "Provisional headers are shown", do not know whether other people have this problem,
![image](https://user-images.githubusercontent.com/19337530/29674627-4fdcae10-8925-11e7-91a5-3bf948e5cac5.png)
And switch to the TimeLine in the Console error: "Failed to clear is temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError"
![image](https://user-images.githubusercontent.com/19337530/29674712-8b94e6c0-8925-11e7-97e2-e04591e3930d.png)

**Comment by MeiJunZhang** [comment]
![image](https://user-images.githubusercontent.com/19337530/29674511-fe122aa6-8924-11e7-9062-843e04e17c4a.png)
A detailed error, as shown in the picture above

**Comment by merceyz** [comment]
This is an issue in CEF, see
http://magpcss.org/ceforum/viewtopic.php?f=6&t=14422
https://bitbucket.org/chromiumembedded/cef/issues/2136/devtools-network-inspector-provisional

**Comment by NavizDev** [comment]
add headers: 
`let config = {
        method: "POST",
        headers: {
            'Accept': 'application/json, text/plain, */*',
            'Content-Type': 'application/json'
        },
        body: JSON.stringify(body)
    }`
