### ISSUE TITLE
Example Apps do not work under Win10 and VS2017 wich current Nugets 

### ISSUE THREAD

**Issue by jogibear9988** [cefsharp/CefSharp#2125]
I've pulled your current source Code, changed the Wpf and Winforms Sample (and the dependend example assembly) so that they use the Nuget packages (cause I have no c++ compiler installed).

I could not display any HTML File or Page.

I compiled with VS2017!

Is there a known bug atm?

**Comment by merceyz** [comment]
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Fork the https://github.com/cefsharp/CefSharp.MinimalExample project and provide an example that reproduces your problem.

**Comment by jogibear9988** [comment]
I forgot the following code:


    var settings = new CefSettings();

    // Set BrowserSubProcessPath based on app bitness at runtime
    settings.BrowserSubprocessPath = Path.Combine(AppDomain.CurrentDomain.SetupInformation.ApplicationBase,
                                           Environment.Is64BitProcess ? "x64" : "x86",
                                           "CefSharp.BrowserSubprocess.exe");

    // Make sure you set performDependencyCheck false
    Cef.Initialize(settings, performDependencyCheck: false, browserProcessHandler: null);
