### ISSUE TITLE
WPF - Transparency Rendering Too Dark

### ISSUE THREAD

**Issue by reloadedandrovald** [cefsharp/CefSharp#2127]
- **What version of the product are you using?**
    - CefSharp.Common / CefSharp.Wpf v57.0.0

- **What architecture x86 or x64?**
   - Either / Both

- **On what operating system?**
    - Windows 10 x64

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
   - WPF

- **What steps will reproduce the problem?**
    - Set a white coloured background behind the control
    - Enable OffScreenTransparentBackground
    - Navigate to a page with a 50% white background (body background: rgba(255,255,255,0.5), html background: transparent)

- **What is the expected output? What do you see instead?**
   - Background is gray rather than white.

- **Please provide any additional information below.**
    - No exceptions or error messages occur.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
    - No, but likely doesn't use transparent background.

**Comment by laiglinne-ff** [comment]
![image](https://user-images.githubusercontent.com/20029869/34911320-a53998ae-f90b-11e7-8766-994d081c67bb.png)
This is WPF Windowless Browser


![image](https://user-images.githubusercontent.com/20029869/34911326-ce19016a-f90b-11e7-8119-0800f6e65fa8.png)
Origin Color is this

So, Transparent colors more darken origin color (also 50 Percent darker)

**Comment by laiglinne-ff** [comment]
![image](https://user-images.githubusercontent.com/20029869/34939238-76a8c8c4-fa2e-11e7-8c5a-f97b2c740ac3.png)

set this value correctly viewed color, i think default value RGB 0 0 0.

i think manualy overrided fix default color FF FF FF (White) Fix this problem

**Comment by laiglinne-ff** [comment]
I fixed it, but NOT WPF 

OffScreen Render With Layered WinForm.

![image](https://user-images.githubusercontent.com/20029869/34942981-00aa02f0-fa3d-11e7-8802-8f7fd591a843.png)

I Think, it caused WPF OffScreenWebBrowser

https://github.com/cefsharp/CefSharp/blob/e8b6c0bf9f297f75dfbe1fa9496e4d7ec0e17c23/CefSharp.Wpf/ChromiumWebBrowser.cs#L1665

I wanted fixed this issue.

**Comment by amaitland** [comment]
Closing as this is very old. If the problem can be reproduced in version `65.0.0-pre02` or newer then this can be reopened. A more detailed set of steps to reproduce the problem will be required.

**Comment by maloshuk** [comment]
I work on an application that use CefSharp.Wpf and it needs semi-transparency. There is need to put WPF window with cefSharp browser semi-transparent above another window(s).  Unfortunately when it comes to semi-transparency of the Cef browser, the output is darker that it should be, there is black color component added. 

**What version of the product are you using?**
    CefSharp.Common / CefSharp.Wpf v69.0.0
**What architecture x86 or x64?**
    Either / Both
**On what operating system?**
    Windows 10 x64
**Are you using WinForms, WPF or OffScreen?**
    WPF
**What steps will reproduce the problem?**
Create WPF app project. In XAML code for main window add ChromiumWebBrowser. Set Address to reference any document that will contains  code like:
`<html><body><div style="height:200px; width: 800px; background-image: linear-gradient(to right, transparent, red);"> </div></body></html>`
Or load PNG with transparency. 

**Results with different embeds:**
<img width="594" alt="cefsharptransparencycomp" src="https://user-images.githubusercontent.com/8667063/49451889-313c1400-f7f1-11e8-8b19-cefb28a2bdbd.png">

**I tried without success**
in html document 
  - to not set body background as advised in #2196, to set 'transparent', to rgba(255, 255, 255, 0). No difference.

in xaml: 
 - to set  background for browser control  
'<cefSharp:ChromiumWebBrowser Grid.Row="4" x:Name="ChrWb3" Background="Transparent"/>'
 
in cef: 
  - tried to initialize CEF with BG color setting
`            var set = new CefSettings();
            set.SetOffScreenRenderingBestPerformanceArgs();
            set.BackgroundColor = Cef.ColorSetARGB(0, 255, 255, 255);
            Cef.Initialize(set, performDependencyCheck: true, browserProcessHandler: null);
`
Maybe you could advise anything how to avoid darken?

**Comment by amaitland** [comment]
> Maybe you could advise anything how to avoid darken?

@maloshuk You'll have to debug the issue and determine if `CEF` is correctly rendering the image or if `WPF` is doing something strange to the image. 

`CefSharp` is built with `GitLink`, you can step into the code from your project see https://github.com/GitTools/GitLink#gitlink

Start with:
https://github.com/cefsharp/CefSharp/blob/cefsharp/69/CefSharp.Wpf/ChromiumWebBrowser.cs#L767

`InteropBitmapRenderHandler` is used when `DPI` is `1`
https://github.com/cefsharp/CefSharp/blob/cefsharp/69/CefSharp.Wpf/Rendering/InteropBitmapRenderHandler.cs

`WritableBitmapRenderHandler` is used when `DPI` > `1`
https://github.com/cefsharp/CefSharp/blob/cefsharp/69/CefSharp.Wpf/Rendering/WritableBitmapRenderHandler.cs#L75

> set.SetOffScreenRenderingBestPerformanceArgs();

I'd recommend not using such command line args until you've resolved the issue.
