### ISSUE TITLE
Unable to return array of objects at injected class

### ISSUE THREAD

**Issue by odin3** [cefsharp/CefSharp#2128]
### Bug Report

- **What version of the product are you using?**
    - 57.0.0 - NuGet

- **What architecture x86 or x64?**
 - x64

- **On what operating system?**
    - Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
 - WinForms 

- **What steps will reproduce the problem?**
    - Create a sample class - https://pastebin.com/d2VQfe76
    - Create a async JavaScript binding with method that returns array of objects (`AppManifest[]`)
    - Call method
    - Promise is pending forever

- **What is the expected output? What do you see instead?**
    - Expected:  Array
    - Got: Promise pending forever

- **Please provide any additional information below.**
    - No exception. Regular strings work well. Objects are not passed from Promise.

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
       - No. Just GPU detction messages

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
      - Using Newtonsoft.Json

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

    - To compare with WPF run cefclient --multi-threaded-message-loop --off-screen-rendering-enabled
    - To compare with WinForms run cefclient --multi-threaded-message-loop
    - If you can reproduce the problem with `cefclient` then you'll need to report the bug on https://bitbucket.org/chromiumembedded/cef/overview there is no point opening an issue here. (Make sure you search before opening an issue)
    - Please include the version you tested with e.g. `cef_binary_3.3029.1611.g44e39a8_windows64_client.tar.bz2`

**Comment by merceyz** [comment]
See #2025
