### ISSUE TITLE
Problem Atutentication Login

### ISSUE THREAD

**Issue by troblou** [cefsharp/CefSharp#2129]
I developed a browser using CefSharp v49.0.1.0, but when I log in to some sites it gives me problems, having to log in as to the execution of internal scripts.

I would like some help!

Site that I try to log in and I can not:
Https://go.tu.com/#/
Login: 62998469115
Password: alfa1020

**Comment by GrabzIt** [comment]
Version 49 is no longer supported you need to update to the latest version.

**Comment by troblou** [comment]
Also tried with v57.0.0.0, it also has the same problem.

**Comment by merceyz** [comment]
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Fork the https://github.com/cefsharp/CefSharp.MinimalExample project and provide an example that reproduces your problem.

**Comment by troblou** [comment]
I am using version 57, I downloaded and tested the suggested project but it continues with the problems, I believe it has some limitation to use ajax or httprequest

![image](https://user-images.githubusercontent.com/9358934/29795103-35e6d356-8c21-11e7-9f01-6ff7fc338342.png)
