### ISSUE TITLE
CefSharp IJsDialogHandler

### ISSUE THREAD

**Issue by yangjieshao** [cefsharp/CefSharp#2131]
继承IJsDialogHandler接口后
如果OnJSDialog()方法返回true, 页面会卡主好久。
具体的现象是，我点击一个按钮要alert一个字符串，用OnJSDialog捕获处理后返回true,要过好久我才能再次点击页面上的东西。

**Comment by merceyz** [comment]
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Fork the https://github.com/cefsharp/CefSharp.MinimalExample project and provide an example that reproduces your problem.

**Comment by yangjieshao** [comment]
- **What version of the product are you using?**
   * CefSharp.Wpf  v57.0.0 
- **What architecture x86 or x64?**
   * x64
- **On what operating system?**
   * Windows 10 x64
- **Are you using WinForms, WPF or OffScreen?**
   * WPF
- **What steps will reproduce the problem?**
   * webBrowser.JsDialogHandler =new JsDialogHandler();
   * JsDialogHandler.OnJSDialog()  -> return true
- **What is the expected output? What do you see instead?**
   * 返回true后，要等好久才能点击页面
   * After you return true, you have to wait a long time to click on the page
- **Please provide any additional information below**
   * [example.zip](https://github.com/cefsharp/CefSharp/files/1265601/example.zip)

**Comment by merceyz** [comment]
No binary files

**Comment by yangjieshao** [comment]
[Issues_2131_example_binary_exeOnly.zip](https://github.com/cefsharp/CefSharp/files/1265658/Issues_2131_example_binary_exeOnly.zip)

**Comment by jankurianski** [comment]
@yangjieshao please search "github how to fork" in your language

**Comment by hyblusea** [comment]
please call  "callback.Continue(true);" before you “return true;”
