### ISSUE TITLE
Set command line arguments per browser (GPU enabling)

### ISSUE THREAD

**Issue by valhentai** [cefsharp/CefSharp#2132]
In our application, we need WEBGL capability of the web browser. Unfortunatly, enabling GPU in the WPF web browser cause a slow frame rate. So we are stuck between choosing WEBGL support and getting sluggish web rendering, or having fast rendering but no WEBGL because those settings are set in the Cef Initialisation and can't be changed after.

Having the possibility to set the command line arguments per browser would solve this problem. By default we would disable gpu to have fast rendering and when the user want to display some WEBGL, he would press a button "Enable WebGL" which would recreate a browser with the gpu enabling command line arguments.

I am using CefSharp.Wpf 55

**Comment by amaitland** [comment]
> 3071 branch and newer uses swiftshader to support WebGL with software rendering.

http://magpcss.org/ceforum/viewtopic.php?f=6&t=13997&p=35671#p35671

**Comment by valhentai** [comment]
It will be available in the version 59?

But without gpu, the performance will be horrible for complex 3D scene. 
With gpu, the performance is sluggish but still usable. I fear that software only WEBGL will be unusable.

**Comment by amaitland** [comment]
If someone volunteers to release an updated version it'll be available in 59 or newer. 

I cannot comment on performance as I've not tried it. Your other option is to use the WindowsFormsHost to host the WinForms version. That's the only way to achieve decent performance at this time. 

It's important to note CefSharp is just a wrapper, far as I know Chromium doesn't support command line args per browser instance. If you have follow up questions ask on http://www.magpcss.org/ceforum/index.php

**Comment by amaitland** [comment]
`Swiftshader` is available in the `63.0.0-pre01` release.
