### ISSUE TITLE
WPF: Add support for back and forward mouse buttons

### ISSUE THREAD

**Issue by merceyz** [cefsharp/CefSharp#2133]
The WPF browser currently ignores XButton1 and XButton2.
These are used to navigate forward and backwards in chrome, and should probably do so in CefSharp as well

https://github.com/cefsharp/CefSharp/blob/244aab0408eda646c12ab86c259ae265db17d293/CefSharp.Wpf/ChromiumWebBrowser.cs#L2136-L2140

**Comment by virulentt** [comment]
Could it be possible to disable this feature? Add a boolean to disable these buttons or make the method overriable.

**Comment by amaitland** [comment]
You can already override the behavior, just inherit from ChromiumWebBrowser, override the two methods for mouse up/down and mark them as handled.

**Comment by fvanheeswijk** [comment]
@amaitland That should work indeed, thanks :) Though that does mean that I need to duplicate `browser.GetHost().SendMouseClickEvent((int)point.X, (int)point.Y, (MouseButtonType)e.ChangedButton, mouseUp, e.ClickCount, modifiers);`...

In short, if you change some things in `private void OnMouseButton(MouseButtonEventArgs e)` in the future, then I'll be missing those changes, I'm not sure if that is the best way to go, but for now it solves the issue.

**Comment by amaitland** [comment]
How about setting the eventargs as handled and call the base method? Shouldn't need to duplicate anything

**Comment by fvanheeswijk** [comment]
That means though that `private void OnMouseButton(MouseButtonEventArgs e)` will not execute anything anymore, right? As the guard is `!e.Handled && browser != null`. And I just notice that in `protected override void OnMouseDown(MouseButtonEventArgs e)` I need to duplicate the `Focus()` call too.

To clarify: I still want (most) of the original behavior of `OnMouseUp` and `OnMouseDown`, I just don't want the back/forward navigation using mouse buttons.

**Comment by amaitland** [comment]
> To clarify: I still want (most) of the original behavior of OnMouseUp and OnMouseDown, I just don't want the back/forward navigation using mouse buttons.

That was perfectly clear. 

> And I just notice that in protected override void OnMouseDown(MouseButtonEventArgs e) I need to duplicate the Focus() call too.

For what reason?

`CefSharp` is build with `GitLink`, you can step into the source https://github.com/GitTools/GitLink

**Comment by fvanheeswijk** [comment]
That actually seems to be the solution I was looking for :) Thanks a lot, it is simple and effective.
