### ISSUE TITLE
NRE OnTooltipTimerTick

### ISSUE THREAD

**Issue by xmedeko** [cefsharp/CefSharp#2134]
- **What version of the product are you using?**
 - Nuget CefSharp.Wpf.57.0.0    
- **On what operating system?**
    - Win7, Win 8

We have CefSharp embedded in our app (compiled for 32 bit - x86). On our log server arrived two app crashes by:
```
System.NullReferenceException: Object reference not set to an instance of an object.
at CefSharp.Wpf.ChromiumWebBrowser.OnTooltipTimerTick(Object sender, EventArgs e)
at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

I am sorry I do not have more details, the users has not contacted us. It's occurrence is very rare, so I cannot simulate it.

**Comment by merceyz** [comment]
It seems like a tick happens at the same time as it's disposing, causing `tooltipTimer.Stop();` to fail because it's set to null

**Comment by xmedeko** [comment]
Thanks for quick fix.
Just advice: if you use `Interlocked.CompareExchange` as a bool flag often, you may simplify it by some methods like:
```c#
public static bool InterlockedIsSet(ref int location1)
    => Interlocked.CompareExchange(ref location1, 0, 0) != 0;
```
Or, you may wrap it up in some `struct InterlockedBool` to be even more readable.

**Comment by amaitland** [comment]
> Or, you may wrap it up in some struct InterlockedBool to be even more readable.

Or you should just check `!IsDisposed`

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf/ChromiumWebBrowser.cs#L2286
