### ISSUE TITLE
Feature Request - Expose CefApp::OnRegisterCustomSchemes

### ISSUE THREAD

**Issue by BenWoodford** [cefsharp/CefSharp#2139]
--
### Bug Report
Delete this line and everything above, and then fill in the details below.

- **What version of the product are you using?**
57 from NuGet

- **What architecture x86 or x64?**
x64

- **On what operating system?**
Win 10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
OffScreen

- **What steps will reproduce the problem?**
Create a basic project, setup some `CefSettings` and use `RegisterScheme` to register a custom scheme handler then pass those settings to the init. Shouldn't matter what you actually enter for it. I have the Scheme Name as "addon" FWIW.

Then start up a browser.

- **What is the expected output? What do you see instead?**

It should be passing `--custom-scheme` to the subprocess but doesn't.

Here's the arguments passed to it:

```--browser-subprocess-path=CefSharp.BrowserSubprocess.exe --no-sandbox --lang=en-US --log-file="pathtodebug.log" --enable-system-flash=1 --process-per-tab=1```

- **Please provide any additional information below.**
No errors or anything useful given. It just considers this new scheme to be unknown

EDIT: Updated title to better reflect what's going on.

**Comment by merceyz** [comment]
Testing with the WPF example in master the custom scheme works fine

Please fork the https://github.com/cefsharp/CefSharp.MinimalExample project and provide an example that reproduces your problem.

**Comment by BenWoodford** [comment]
Will do and report back, likely Monday now.

**Comment by BenWoodford** [comment]
Tested with the example and worked, interestingly. It also works in my own project if I just call a basic `new ChromiumWebBrowser("addon://test.html")` and doesn't push out an unrecognised scheme error. The `--custom-scheme` is being sent on my main project to all browser instances, it was just cut off by Task Manager.

I'm doing a bit more involved of a browser creation in my project, which may be why it's causing problems. Rather than auto-creating I'm doing a bunch of stuff [here](https://github.com/Martin-Oehler/SteamVR-Webkit/blob/master/SteamVR-WebKit/WebKitOverlay.cs) to it instead.

None of that strikes me as anything that should mess with the main settings though?

**Comment by BenWoodford** [comment]
I have narrowed it down to whether or not a `RequestContext` is set. I see that `ReuqestContext` does take scheme handlers, though this doesn't strike me as intended behaviour that it would completely ignore the global settings?

**Comment by amaitland** [comment]
> Incidentally, per-browser scheme settings fits my needs better, but I notice you can only pass the scheme name, domain and factory - not the whole CefCustomScheme, so you can't set the IsSecure, etc?

Registering a `Scheme` is done in two parts:

- `CefApp::OnRegisterCustomSchemes` method, where you need to register your schemes in every process (browser and render). This is the part you cannot access directly as it stands
- Call to `CefRegisterSchemeHandlerFactory` which is equivalent to `CefRequestContext::GetGlobalContext()->RegisterSchemeHandlerFactory()`. 

http://magpcss.org/ceforum/apidocs3/projects/(default)/(_globals).html#CefRegisterSchemeHandlerFactory(constCefString&,constCefString&,CefRefPtr%3CCefSchemeHandlerFactory%3E)

So the task here is to provide access to `CefApp::OnRegisterCustomSchemes` and provide a default implementation that allows for backwards compatibility.  I'd like to see `CefSettings.RegisterScheme` removed as it differs greatly from the actual `CEF API`, doubt it will happen though as it's a breaking change.

**Comment by amaitland** [comment]
With #2616 it's now possible to register a custom scheme and separate out the scheme handler factory registration. Just leave `CefCustomScheme.SchemeHandlerFactory` as `null`.

It's now possible to implement `IApp.OnRegisterCustomSchemes` and control the browser process registration, unfortunately schemes must be registered in all processes and we're currently dealing with that by appending a command line argument that is then parsed and custom schemes registered in all render processes. So it's not as completely useful as it could be. 

A few things of note
- We no longer attempt to register `https` and `http` as custom schemes (should never have been the case). 
- `Scheme` registration and `Scheme Handler Factory` registration are two separate tasks in `CEF` and it's now possible to perform them independently in `CefSharp` (previously you were forced to register a scheme handler in the global context for a custom scheme).
 
Closing this now as it's about all the progress I can make without making huge breaking changes. They might come at a later date, see how things go.
