### ISSUE TITLE
Cefsharp.BrowserSubprocess still exists on process list, when main application was closed.

### ISSUE THREAD

**Issue by jacekbartek** [cefsharp/CefSharp#2140]
- **What version of the product are you using?**
    57.0.0.0

- **What architecture x86 or x64?**
    x64
- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WinForms

- **What steps will reproduce the problem?**
    Problem exists in specific steps:
    1. Load ' www.wp.pl '.
    2. Click on the top bar ' TV WP ' link.
    3. Click some link to video.
    4. When video will be playing. Close application.
    Now application process was closed, but 'Cefsharp.BrowserSubprocess' still exists on process list.
    (Problem occurs in MinimalExample application, too)

![problemrecover](https://user-images.githubusercontent.com/21197802/30268483-24f4bdea-96e6-11e7-801a-2f8114c0297f.gif)

- **What is the expected output? What do you see instead?**
  Process 'Cefsharp.BrowserSubprocess' should be closed.

- **Please provide any additional information below.**
Binary file removed

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
   CefSharp.MinimalExample-master

**Comment by jankurianski** [comment]
Does this problem also occur in the CEF Sample Application from http://opensource.spotify.com/cefbuilds/index.html?

Download the `cefclient` program and run `cefclient --multi-threaded-message-loop`

Please include the version you tested with e.g. cef_binary_3.3029.1611.g44e39a8_windows64_client.tar.bz2

**Comment by jacekbartek** [comment]
I tested cef_binary_3.3112.1659.gfef43e0_windows64_client.tar.bz2. Problem does not exists. Application correctly frees the resources.

Problem is reproduces in CefSharp.MinimalExample https://github.com/cefsharp/CefSharp.MinimalExample/tree/master/CefSharp.MinimalExample.WinForms

It looks like a problem in Cef wrapper.

**Comment by jacekbartek** [comment]
Hi!
Is there a chance to fix this problem ?

**Comment by developer-variety** [comment]
I would suggest that you close all processes that matches the process name on FormClosing or FormClosed events.

**Comment by perlun** [comment]
@jacekbartek Thanks for the bug report. Could you check with some other web page, like www.google.com - does it also exhibit the same behavior or is it _specifically_ with this web page? Is it the same with other web pages playing video, like YouTube?

**Comment by amaitland** [comment]
> When video will be playing. Close application.
> Now application process was closed, but 'Cefsharp.BrowserSubprocess' still exists on process list.

@jacekbartek Try using the `File -> Exit` menu option

**Comment by merceyz** [comment]
I'm not able to reproduce this issue (Latest commit https://github.com/cefsharp/CefSharp/commit/7802653fb161e9238c19f829435f575d78d33832)
Note: The advert plays fine but the video is in a permanent loading state, all processes closes.

Closing due to lack of feedback
