### ISSUE TITLE
"Output files description table" lists cef.pak as not required, but it is

### ISSUE THREAD

**Issue by bruzkovsky** [cefsharp/CefSharp#2141]
- **What version of the product are you using?**
    - What version are you using? Nuget? CI Nuget? build from a branch? If so which branch?
57.0.1

- **What architecture x86 or x64?**
x86

- **On what operating system?**
    - Win7, Win 8, Win10, etc?
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.
    - Please no binary (zip, etc) links, fork the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) and push your changes to `GitHub`. (Alternatively use a code sharing service list `Gist` or `Pastebin`).
- Create a wpf application with a ChromiumWebBrowser component, run it.
- Go to bin\ and delete cef.pak.
- Try to run the .exe again, it will crash as soon as the ChromiumWebBrowser component and with it the libcef.dll loads.

- **What is the expected output? What do you see instead?**
As cef.pak is not required, the application should not crash.

- **Please provide any additional information below.**
The program 'xyz.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
Sorry for not testing this, but I think I made my point.

**Comment by jankurianski** [comment]
Thanks for spotting this.  Could you please edit the wiki page and correct it (everyone has permission to do this)?

**Comment by bruzkovsky** [comment]
I updated the wiki page.

No problem, I just wanted to share because I lost a whole day searching for this and I hope to save someone the trouble.

**Comment by jankurianski** [comment]
Thank you @bruzkovsky 👍
