### ISSUE TITLE
RegisterAsyncJsObject works incorrectly when "renderer-process-limit" command line argument is set.

### ISSUE THREAD

**Issue by igor-eremyashev** [cefsharp/CefSharp#2142]
- **What version of the product are you using?**
Latest master branch (v. 58). This issue can also be reproduced in previous versions. 

- **What architecture x86 or x64?**
x86

- **On what operating system?**
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
Use CefSharp.Wpf.Example to reproduce the problem.
Limit max number of render processes to 1 by using
settings.CefCommandLineArgs.Add("renderer-process-limit", "1");
Then replace code behind of SpawnBrowsersWindow.xaml with [this code](https://gist.github.com/igor-eremyashev/af73b1dda28bbd7fdb6e375dd4f4722e#file-spawnbrowserswindow-xaml-cs) and specify this view as StartupUri in App.xaml.

- **What is the expected output? What do you see instead?**
Expected output - no JS errors in console. Actual output - "Uncaught (in promise) " error in JS console.

- **Please provide any additional information below.**
The reason behind this issue is the fact that CefAppUnmanagedWrapper is not thread safe.
More specifically, _javascriptAsyncRootObject variable is used to pass information about JS object registration between OnProcessMessageReceived(kJavascriptRootObjectRequest) and OnContextCreated calls. This work great as long as each renderer is running in its own process. But when all renderers are executed in the same process this approach stops working. Rendrers receive objects that doesn't below to them and when a JS method is executed it can be dispatched to a wrong object - in this case JavascriptObjectRepository.TryCallMethod doesn't execute it.

**Comment by amaitland** [comment]
If you wish to add support for that scenario then by all means submit a `PR`.

This issue can be reopened if someone wants to add support.
