### ISSUE TITLE
How to Read and Write a Cookie in CefOffline?

### ISSUE THREAD

**Issue by zhizlm** [cefsharp/CefSharp#2144]
i find everywhere ,can't find how to use Cookie in CefOffline,dose it has any explain?

**Comment by jankurianski** [comment]
GitHub issues are for bug reports only.  Please ask questions on StackOverflow (http://stackoverflow.com/questions/tagged/cefsharp) or Gitter (https://gitter.im/cefsharp/CefSharp).
