### ISSUE TITLE
My app crashes while exiting and fault module is libcef.dll

### ISSUE THREAD

**Issue by naveenbezawada** [cefsharp/CefSharp#2147]
While exiting my app it crashes. I am using chromium browser, it is embedded in my windows form application. 
fault module: libcef.dll
ExceptionCode: 4000001f

I am using version 55.

**Comment by jankurianski** [comment]
That version is no longer supported.  Please try to reproduce the problem in version 57 and then this issue can be re-opened.

Please see #944 for tips on debugging this problem yourself to get more information about the error.
