### ISSUE TITLE
Proxy  lead to FrameLoadEnd Error

### ISSUE THREAD

**Issue by czllfy** [cefsharp/CefSharp#2148]
Hi
    I need to crawler some data from the page ,but the website using anti-crawling strategy.So I set the proxy。Now the FrameLoadEnd  was trigger but the page is not ready .The Code is 

            cfsettings.CefCommandLineArgs.Add("proxy-server", proxyAddr);
            Cef.Initialize(cfsettings, true, true);

            browser.RequestHandler = new ZARequesthandler(pageTimeoutTimer, () =>
            {
                browser.GetMainFrame().LoadUrl("https://www.baidu.com");
                browser.FrameLoadEnd += Browser_FrameLoadEnd;
            });
            browser.FrameLoadEnd += Browser_FrameLoadEnd;

   private void Browser_FrameLoadEnd(object sender, FrameLoadEndEventArgs e)
        {
            if (browser.IsBrowserInitialized && e.Frame.IsMain && e.Frame.Url.StartsWith("https://www.baidu.com"))
            {
                browser.GetMainFrame().LoadUrl("https://www.jd.com");
            }
            else if (browser.IsBrowserInitialized && e.Frame.IsMain && e.Frame.Url.IndexOf("chexian.zhongan.com/index") >= 0)
            {
                browser.FrameLoadEnd -= Browser_FrameLoadEnd;
	    }
      }

**Comment by GrabzIt** [comment]
Questions like this needed to be asked on gitter: https://gitter.im/cefsharp/CefSharp
