### ISSUE TITLE
jwplayer  not work on cefsharp

### ISSUE THREAD

**Issue by lun3xcoder** [cefsharp/CefSharp#2149]
jwplayer  not work on cefsharp :) 
the error when i run 
jwplayer error loading player no playable sources found

but its work on google chrome

**Comment by developer-variety** [comment]
It is because they have removed NPAPI from CefSharp. For this to work you would need to install Flash onto your computer, and if you distribute you also need to tell the clients to download Flash.

#1505

**Comment by perlun** [comment]
Workaround exists, closing.
