### ISSUE TITLE
Wrong displaying the HTML combobox and selecting items when angle transformation applied to browser.

### ISSUE THREAD

**Issue by TouchRu** [cefsharp/CefSharp#2151]
- What version are you using? Nuget? CI Nuget? build from a branch? If so which branch?
e.g. 59.0.0 (3.3071.1649)

- **What architecture x86 or x64?**
x86

- **On what operating system?**
    - Win7, Win 8, Win10, etc?
Win10
- **Are you using `WinForms`, `WPF` or `OffScreen`?**
Wpf
- **What steps will reproduce the problem?**
Open page with Combobox, rotate browser by Angle slider, click on combobox, try to select items.
- **What is the expected output? What do you see instead?**
Items List stay vertically, but itmes selection possible in rotated rect.
![image](https://user-images.githubusercontent.com/1888594/30913244-32255966-a398-11e7-9bac-757729e8a2a1.png)

**Comment by amaitland** [comment]
The `Popup` used to host the drop down list content didn't have the transform bound, had to dig through the source to find that the popup needs to allow transparency for the transform to work property.

If you have time please download `master` and report back if this is still a problem.

Long term it might be better to remove the `Popup` and just overlay one image over the other for which I've created #2239
