### ISSUE TITLE
cefsharp wpf Appear white screen occasionally

### ISSUE THREAD

**Issue by stonezhu870** [cefsharp/CefSharp#2152]
dear all:

   I use cefsharp.wpf version49, web browser appear white screen occasionally, please help me.

   Initialize cef:
                 var settings = new CefSettings();
                settings.EnableInternalPdfViewerOffScreen();
                // Disable GPU in WPF and Offscreen examples until #1634 has been resolved
                settings.CefCommandLineArgs.Add("disable-gpu", "1");
                settings.CachePath = "cache";
                settings.Locale = "zh-CN";
                settings.IgnoreCertificateErrors = true;
                settings.MultiThreadedMessageLoop = true;
               Cef.Initialize(settings, shutdownOnProcessExit: true, performDependencyCheck: false);

   I use the code to show content:
            var factory = (DefaultResourceHandlerFactory)(wbMain.ResourceHandlerFactory);
            html = "<html><body>" + html + "</body></html>";
            var response = ResourceHandler.FromString(html);
            if (factory != null)
            {
                wbMain.Address = TestUnicodeResourceUrl;
                factory.RegisterHandler(TestUnicodeResourceUrl, response);
            }

**Comment by merceyz** [comment]
Version 49 is no longer supported, try with a newer version.

Your issue is probably https://bitbucket.org/chromiumembedded/cef/issues/1984/momentary-white-flash-with-osr-in

**Comment by stonezhu870** [comment]
Thank you for your answer.
Because I want to support the XP users, so the maximum can only be upgraded to 49 version. Do you have any other way to resolve or improve this issue, except for the upgraded version.
