### ISSUE TITLE
Cookie Manager is not returning cookies

### ISSUE THREAD

**Issue by cryo75** [cefsharp/CefSharp#2153]
I have multiple browser instances created as:

`CefSettings settings = new CefSettings();
settings.CefCommandLineArgs.Add("enable-npapi", "1");

Cef.Initialize(settings);

var contextSettings = new RequestContextSettings();
contextSettings.CachePath = cachePath;

var browser = new ChromiumWebBrowser(urlStr)
{
    BrowserSettings = new BrowserSettings()
    {
        Javascript = CefState.Enabled,
        Plugins = CefState.Enabled,
    },
    RequestContext = new RequestContext(contextSettings),
    RequestHandler = new CustomRequestHandler,
};

And to get the cookies:

`var cookies = await Cef.GetGlobalCookieManager().VisitAllCookiesAsync();`
`

Cookies is always empty.

**Comment by GrabzIt** [comment]
Questions like this need to be asked in: https://gitter.im/cefsharp/CefSharp

**Comment by Huochengyan** [comment]
hello, Multiple instances of cookie isolation, and access to Cookie how to solve?

**Comment by jankurianski** [comment]
@Huochengyan ask questions on stackoverflow or gitter
