### ISSUE TITLE
Buggy and difficult to test AsyncExtensions 

### ISSUE THREAD

**Issue by alfein** [cefsharp/CefSharp#2154]
- **What version of the product are you using?**
    - What version are you using? Nuget? CI Nuget? build from a branch? If so which branch?  Nuget 57.0.0

- **What architecture x86 or x64?** x64

- **On what operating system?** Win7

- **Are you using `WinForms`, `WPF` or `OffScreen`?**  WPF

- **What steps will reproduce the problem?**
AsyncExtensions class is a static class that implements in C# some of the async functions that used to be part of the  ICookieManager interface. 

If ICookieManager.SetCookie or ICookieManager.DeleteCookies or ICookieManager.VisitAllCookies or ICookieManager.FlushStore returns false the AsyncExtensions functions return null.  This violates expecteations because if our code uses await on the async methods, the await throws nullref.  You should return a Task<false> instead.

The Task...Callback wrappers

* TaskCompletionCallback
* TaskDeleteCookiesCallback
* TaskCookieVisitor
* TaskSetCookieCallback

all use your TrySetResultAsync extension method  method instead of TrySetResult, and you drop the async task itself.  This prevents us from completing the task synchronously during unit tests!  We used to be able to to this, becuase we could mock the actual async methods on the interface, but now, the only thing we can mock is the SetCookie method on CookieManager:

            _cookieManager.SetCookie(Arg.Any<string>(), Arg.Any<CefSharp.Cookie>(), Arg.Any<ISetCookieCallback>()).Returns(ci =>
            {
                var callback = (ISetCookieCallback)ci[2];

                var tcs = (TaskCompletionSource<bool>) typeof(TaskSetCookieCallback).GetField("taskCompletionSource", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance).GetValue(callback);
                tcs.SetResult(true);
                callback.OnComplete(true);
                return true;
            });

And we have to do reflection as above to force the task completion to be synchrounous.  You can make OnComplete return a Task which we can await it?

**Comment by amaitland** [comment]
> If ICookieManager.SetCookie or ICookieManager.DeleteCookies or ICookieManager.VisitAllCookies or ICookieManager.FlushStore returns false the AsyncExtensions functions return null. This violates expecteations becuase if our code uses await on the async methods, the await throws nullref. 

That's a fair point, you should submit a `PR`.

**Comment by alfein** [comment]
Done

**Comment by alfein** [comment]
Btw, somewhat unrelated, but what's the plan for newer chromium versions like 62?

**Comment by amaitland** [comment]
Incorrect behavior of returning null was fixed in the commit linked above.
