### ISSUE TITLE
CEF winforms causes crash to dt with unreachable exception

### ISSUE THREAD

**Issue by jf0772256** [cefsharp/CefSharp#2162]
NuGet CefSharp V-57.0.0 Master
Arch: X64
OS: Windows 10 Build15063.rs2_release170317-1834 <running VBox Instance
Winforms 

I have the initializing as a dialog (as it is a dialog of a larger project), the first open it works just great. I close the form, and when i reopen the same form the whole application crashes. When i run in debugger i get no errors, I set breakpoints and found that the issue seems to be at Cef.Initialize(settings); line, ill post more of the code in a minute... but I wrapped the line in a try catch, set my exception settings to catch on all exceptions, and it states that there is an exception, but the the PDB file is missing so I cant troubleshoot it further. 

Some of the promised code:
the button code to open the browser:

```c#
            try
            {
                MaterialIdentification matID = new MaterialIdentification();
                matID.ShowDialog();
            }
            catch (Exception ex)
            {
//my debug log didn't catch the error which is what is happening in this line
                ErrorLogClass iErr = new ErrorLogClass(ex, "SearchBTN_Click()", "TPO-FormMain");
            }
```

The initialization code:

```c#
            BrowserSettings bs = new BrowserSettings();
            CefSettings settings = new CefSettings();
            try
            {
//this is where the issue happens but only on the second open attempt it works fine on the first
                Cef.Initialize();
            }
            catch (Exception)
            {
                throw;
            }
            wb = new ChromiumWebBrowser(pbc.GetDefaultPath(PathSelection.AppPathWeb) +"\\MatId\\index.html");
            wb.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Right;
            wb.Top = 0;
            wb.Left = 0;
            wb.Width = Width;
            wb.Height = OKButton.Top - 10;
            Controls.Add(wb);
            bs.ApplicationCache = CefState.Enabled;
            bs.Databases = CefState.Enabled;
            bs.FileAccessFromFileUrls = CefState.Enabled;
            bs.ImageLoading = CefState.Enabled;
            bs.Javascript = CefState.Enabled;
            bs.LocalStorage = CefState.Enabled;
            bs.UniversalAccessFromFileUrls = CefState.Enabled;
            wb.BrowserSettings = bs;
```

The form closing event method has:
` Cef.Shutdown();`

I think the debug log has relevant information but I don't really know what to make of it though:
"[1010/152526.796:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain"

Nothing running but file explorer and VS2017 community edition is running...

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
No everything worked there with out issue... 
I also verified that all the files in the test app matched the ones in my /bin/X64/Debug folder and seems only the d3dcompiler_43.dll file is not there but I have the d3dcompiler_47.dll...
tested with: 
cef_binary_3.3163.1671.g700dc25_windows64_client.tar.bz2

**Comment by amaitland** [comment]
You can only call `Cef.Initialize` and `Cef.Shutdown` one per process. See https://github.com/cefsharp/CefSharp/wiki/General-Usage#initialize-and-shutdown for details.
