### ISSUE TITLE
How can I find current focused UI element in cefsharp wpf chromiumwebbrowser

### ISSUE THREAD

**Issue by mm4707** [cefsharp/CefSharp#2163]
Hi,
I'm using cefsharp wpf chromiumwebbrowser in my app.
 I need to find current focused element in web page( like a textbox).
I just use this
<cefSharp:ChromiumWebBrowser Grid.Row="1" Name="Chro" Address="http://127.0.0.1/reports/report/Tutorial/Sales%20Orders" Cursor="Hand"  />
Nothing else
and current page like this

![default](https://user-images.githubusercontent.com/27001532/31429940-5d9dae14-aeaa-11e7-8d30-9c58ec08271d.JPG)

How can I get value and set value in textbox??

**Comment by derrohrbach** [comment]
You could check using a little javascript like this:

```csharp
var result = webBrowser.EvaluateScriptAsync("(() => { var element = document.activeElement; return element.localName; })();");
```

This finds the current active element and returns its name, but you could also return the value of the textbox etc.

**Comment by mm4707** [comment]
I'm sorry I can't understand..
`<asp:TextBox id="TxtUser" style="Z-INDEX: 104; LEFT: 296px; POSITION: absolute; TOP: 152px" runat="server" tabIndex="1" Width="160px" meta:resourcekey="TxtUserResource1"></asp:TextBox>`

`<cefSharp:ChromiumWebBrowser Grid.Row="1" Name="Chro" Address="http://127.0.0.1/reports/report/Tutorial/Sales%20Orders" Cursor="Hand" />`

I just put in behind code like this. but it makes exception error
![default](https://user-images.githubusercontent.com/27001532/31474571-a354f426-af36-11e7-9bbe-80fefd8b2990.JPG)
 
how and where should I insert your code??
and which code should I change more??
please explain with a screenshot if you can
Sorry, I'm just starting 3days in cefsharp chromium
Thanks

**Comment by mm4707** [comment]
It works like this
![ccccccclele](https://user-images.githubusercontent.com/27001532/31590830-3f0159d2-b252-11e7-8f7c-c0ae63394489.JPG)

**Comment by socialpixe** [comment]
And what if i need to get the value from the HTML Element input field. Any idea ?
