### ISSUE TITLE
cef wpf chromium

### ISSUE THREAD

**Issue by mm4707** [cefsharp/CefSharp#2164]
Hi,
I just download CefSharp-master and running process CefSharp.Wpf.Example

My question is
How Can I put Korean in this block??(Black Box)
![ccccccclele](https://user-images.githubusercontent.com/27001532/31600942-2b294cc6-b293-11e7-8280-b623bafccf57.JPG)
If I typed Korean
It's over there(Red Box),
And Nothing Changes

**Comment by developer-variety** [comment]
I don't think this is a CefSharp issue. You have to set the Google preferences to Korean.

**Comment by GrabzIt** [comment]
Please ask support questions in gist.
