### ISSUE TITLE
Can't get out of control on touch screen

### ISSUE THREAD

**Issue by klandry79** [cefsharp/CefSharp#2165]
Version 53.0.1 of the Nuget package (newer versions have different bugs)
x64
Windows 10 Pro
Winforms

I have an app with videos being played (Bosch API) and a the chromium browser beside them.  If I touch click a few times in the browser, I can't touch click on any other user control on the form unless I mouse click out of it.  It appears that the focus is stuck inside.  Hitting the windows key or tabbing out resolves this as well but this is not an acceptable solution.

I suspect it has something to do with touch events so I tried disabling multiple settings but none work so far.
            settings.CefCommandLineArgs["ash-disable-touch-exploration-mode"] = "1";
            settings.CefCommandLineArgs["disable-pinch"] = "1";
            settings.CefCommandLineArgs["disable-touch-adjustment"] = "1";
            settings.CefCommandLineArgs["disable-touch-drag-drop"] = "1";
            settings.CefCommandLineArgs["enable-touch-drag-drop"] = "0";
            settings.CefCommandLineArgs["enable-touchpad-three-finger-click"] = "0";
            settings.CefCommandLineArgs["enable-touchview"] = "1";
            settings.CefCommandLineArgs["touch-noise-filtering"] = "1";

I see no exceptions being called.  Any help on this would be much appreciated.

*Update*
I compiled the latest v59.0 build and ran the winforms example project.  Once you scroll in the main window with the touch screen, I can no longer touch any other control (move form around) unless I use the mouse to get it out of the browser object.

**Comment by amaitland** [comment]
### How do I investigate my issue further?

It's important to remember that `CefSharp` is just a wrapper around the `Chromium Embedded Project (CEF)`, the upstream [`CEF` forum](http://magpcss.org/ceforum/) is a valuable resource. Also `CEF` has it's own [Issue Tracker](https://bitbucket.org/chromiumembedded/cef/issues). Please take the time to research your own problem, including `Googling`, searching on `ceforum`, etc.

--
#### Finding more info
- Have you checked the `Debug.log` file? (Should be located in your apps executing folder by default)
- Have you googled the error message your seeing? (Don't just google the whole thing, try googling just the keywords and possibly add `chromium` as a keyword).
- Are you able to reproduce the problem using `cefclient`? (`cefclient` is the reference implementation provided by `CEF`)
- Need more help debugging? Check the [Troubleshooting Guide](https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting)
- Are you using the latest version? Check the [Release Branches](https://github.com/cefsharp/CefSharp#release-branches) table to determine if the version your using is supported. 

--
#### How do I download `cefclient`?

- Firstly identity which version of `CEF` your actually using, easiest way is to check your `packages.config` file, look for the `cef.redist.x86` package, it's version will be something like `3.2526.1362`, that's the exact version of `CEF` you'll need to download for comparison. You can also open `chrome://version` in the browser to determine the version.
- Open http://opensource.spotify.com/cefbuilds/index.html (http://cefbuilds.com for older version) in a web browser
- Locate the exact `Branch` you require, for the example above the branch is `2526`, all the versions follow a similar pattern
- Locate the `Windows 32bit` or `Windows 64bit` item, if you don't see the exact version, then click `more revisions`
- Download **Test App**
- Are you using `WPF/Offscreen` or `WinForms`? 

**This next part is key**
- To compare with WPF/OffScreen run `cefclient --multi-threaded-message-loop --off-screen-rendering-enabled`
- To compare with WinForms `cefclient --multi-threaded-message-loop`

**Comment by amaitland** [comment]
Closing due to lack of feedback.
