### ISSUE TITLE
RegisterAsyncJsObject - returning structs is broken

### ISSUE THREAD

**Issue by igor-eremyashev** [cefsharp/CefSharp#2167]
- **What version of the product are you using?**
Latest master branch build (v.59).

- **What architecture x86 or x64?**
x64

- **On what operating system?**
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
Write a class that has a method returning a struct, i.e.
`
public JsObject Object()
{
     return new JsObject { Value = "Item" };        
}
`
Try to call this method from JS. This test can be done using CefSharp.Wpf.Example - it already has the `JsObject` struct.

- **What is the expected output? What do you see instead?**
NotSupportedException("Complex types cannot be serialized to Cef lists") is thrown. The reason for this behavior is a mismatch between how structs are treated by `JavascriptObjectRepository.IsComplexType` and `SerializeV8SimpleObject`. 
`JavascriptObjectRepository.IsComplexType` returns true for structs and a `JavascriptObject` wrapper is created. When `SerializeV8SimpleObject `checks the following condition:
`type->IsValueType && !type->IsPrimitive && !type->IsEnum` 
it checks the properties of the` JavascriptObject` type, not the properties of the struct type. That's why the serialization fails.  

- **Please provide any additional information below.**
To fix the issue the following logic can be used:
`
private static bool IsComplexType(Type type)
{
...
	if (baseType.IsValueType && !baseType.IsPrimitive && !baseType.IsEnum)
	{
		return false;
	}
...
}`

**Comment by jankurianski** [comment]
Based on #1981 it looks like there is a test for returning arrays of structs in `CefSharp.Example/Resources/BindingTest.html`.  Could you run this test and see if it is also broken?

Could you write a PR that fixes this bug and adds a new test?  Thank you.

**Comment by igor-eremyashev** [comment]
@jankurianski I created PR #2171. The code works for arrays, there is a separate condition for them in JavascriptObjectRepository:
`if (baseType == null || baseType.IsArray || baseType.Namespace.StartsWith("System"))
{
     return false;
}`

**Comment by jankurianski** [comment]
Thanks @igor-eremyashev I have merged the PR.
