### ISSUE TITLE
Cannot print a single page of multi-paged PDF file - Printer status stuck on spooling

### ISSUE THREAD

**Issue by pyotr09** [cefsharp/CefSharp#2173]
- **What version of the product are you using?**

51.0.0.0

- **What architecture x86 or x64?**
x64

- **On what operating system?**
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms

- **What steps will reproduce the problem?**
View a PDF with 3+ pages in the ChromiumWebBrowser. Click the print icon. Under "Page Range" select "Pages" and type the number 2 into the text box. -- It fails when doing any page range that isn't the entire file and doesn't include the first page.

- **What is the expected output? What do you see instead?**
Expect the selected pages to print.
Instead, the document status sticks on "Spooling" in the printer queue

- **Please provide any additional information below.**
 No stack trace or exception
debug.log is empty

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
Cannot re-create in sample app, tested with cef_binary_3.3203.1674.g2a991c4_windows64_client.tar.bz2`

![image](https://user-images.githubusercontent.com/17440457/32016330-e3cd21f0-b980-11e7-8792-3e0df78ffb59.png)
![image](https://user-images.githubusercontent.com/17440457/32016359-fad9b746-b980-11e7-8ac1-8f7406edbad9.png)

**Comment by jankurianski** [comment]
Sorry but version `51` is unsupported.

With regards to re-creating the problem in the CEF sample app, the version you chose is so recent that there is no equivalent CefSharp version.  The equivalent CEF sample app version that corresponds to `51` is CEF `2704`.

Can you try again with version `57` and the complementary CEF sample app version `2987`?  See the table under the heading "Release Branches" on this repository's main README.md file for where these version numbers come from.

**Comment by amaitland** [comment]
It's important to note that `CefSharp` is just a wrapper around the `Chromium Embedded Framework (CEF)`.

> Cannot re-create in sample app, tested with cef_binary_3.3203.1674.g2a991c4_windows64_client.tar.bz2`

You can test with the `62.0.0-pre01` packages that are on `Nuget`. `CefSharp` has no control over printing, so any bugs need to be fixed in `CEF` and you need to wait for a new version basically.
