### ISSUE TITLE
Touch screen tap input blue bubble crash

### ISSUE THREAD

**Issue by Krzem0** [cefsharp/CefSharp#2174]
- **What version of the product are you using?**
Chromium: 57.0.2987.133. CEF: r3.2987.1601.gf035232, CefSharp: 57.0.0.0
Branch 57

- **What architecture x86 or x64?**
x64

- **On what operating system?**
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms

- **What steps will reproduce the problem?**
1. Run CefSharp.WinForms.Example from Visual Studio.
2. Open website with html input text, e.g. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
3. In the first input type for example numbers: 123123123123123
4. Tap inside input to appear blue bubble.
[How it look right now](https://i.imgur.com/N6zvmam.png)
5. Tap on blue bubble.
6. Application crash.
[Crash screen](https://i.imgur.com/pmepNyK.png)

- **What is the expected output? What do you see instead?**
No crash

- **Please provide any additional information below.**
In my other application in similar scenario (tap on blue bubble under text input) there is also crash.
[Other crash screen](https://i.imgur.com/vIYc8s3.png)
   
- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
Dont know yet.

**Comment by jankurianski** [comment]
This is most likely a CEF issue.  Please try to reproduce using the CEF sample application for the same CEF version that CefSharp uses (`2987`) and then try newer CEF versions to see if the problem is fixed.

**Comment by Krzem0** [comment]
It turned out that problem occurs on branch 57, but 55 and master is ok. At this moment I downgraded CefSharp dlls and dependencies in my project, but looking forward to new stable release :)
