### ISSUE TITLE
The browser does not support the list attribute of the input tag in the Web page

### ISSUE THREAD

**Issue by SunArlen** [cefsharp/CefSharp#2176]
53.0.1
x86/x64
Win7, Win10

code:
 <input type="search" id="searchipt" placeholder="" spellcheck="false" maxlength="256" autocomplete="off"  list=“test"/>
        <datalist id="test">
            <option value="123">
            <option value="456">
            <option value="789">
            <option value="ABC">
        </datalist> 
Cef can not appear drop-down options

**Comment by jankurianski** [comment]
Version `53` not supported.

Please reproduce in `57` and then reproduce in sample CEF client `cefclient` version `2987`.  For instructions on how to do this, read section "Does this problem also occur in the CEF Sample Application from ..." in the [issue template](https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md).

**Comment by amaitland** [comment]
It's important to note that `CefSharp` is just a wrapper around the `Chromium Embedded Framework (CEF)`. Closing this as `upstream` and `wontfix` as changes need to be made in `CEF`. 

The `CEF` project has it's own issue tracker located at https://bitbucket.org/chromiumembedded/cef 

Before opening a new issue you should:

- Search open/closed issues to determine if the problem you are seeing has already been reported
- Test with a newer version if available, see https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-chromium-embedded-frameworkcef for details on testing with the `cefclient` reference application.

If you do find an existing issue that matches this one or create a new one then post a link here for others to follow.
