### ISSUE TITLE
cefsharp 57.0.0.0 textbox mouse click / touch down event in wpf

### ISSUE THREAD

**Issue by ajaythakare** [cefsharp/CefSharp#2177]
I am using cefsharp 57.0.0.0 in WPF. I want a textbox mouse click / touch down event. When user clicks inside any text box of any website then this event should fire. If website has multiple text boxes then each time users clicks inside the text box then this event should fire. Please let me know how to achieve this task?

**Comment by jankurianski** [comment]
Github issues are for bug reports only.  Please ask questions on StackOverflow (use the CefSharp tag) or our Gitter.
