### ISSUE TITLE
Request: Update Cef.Redist.* more often

### ISSUE THREAD

**Issue by AndrewBragdon** [cefsharp/CefSharp#2180]
Currently, Cef.Redist is updated very infrequently - much less frequently than Chrome itself is updated.  This means that applications that use CefSharp are often behind on Chrome version numbers, causing wierd fallback behaviors for popular web apps, such as Gmail.

For example, it is October 29, 2017.  The last time Cef.Redist was updated was in April, 2017.

Is there a way to update Cef.Redist more often?  Perhaps by setting up CI/CD?  

Alternatively, updating Cef.Redist.* at least once a quarter would already be a huge improvement.

**Comment by japj** [comment]
Hi, I also submitted this to the cef-binary repo at https://github.com/cefsharp/cef-binary/issues/51

Note though that newer cef versions migh need additional work on integrating in cefsharp.

And indeed there actually is a showstopper #1203 that currently prevents any release post cef 57 to happen as far as I understand it.

**Comment by perlun** [comment]
I think we'll close this, since it's more relevant in the `cef-binary` repo (which "owns" the Cef.Redist  binaries.) Will write more details in the linked issue there.
