### ISSUE TITLE
Custom SchemeHandler not always working

### ISSUE THREAD

**Issue by ray007** [cefsharp/CefSharp#2181]
I have a custom scheme handler returning some (cached) data to the JS application.
It's just an xml file I'm routing through with `ResourceHandler.FromFilePath(...)`.
This works fine in my standalone application, but not when my view-class is used as addin in a larger application. In that case I get a `ProgressEvent` with a single property `isTrusted = true` as error.

Anybody an idea what's going wrong here?

- **What version of the product are you using?**
    - Version 57, self-built for codec support

- **What architecture x86 or x64?**
   - x86

- **On what operating system?**
    - Win7

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - WPF

**Comment by perlun** [comment]
> I have a custom scheme handler returning some (cached) data to the JS application.
> It's just an xml file I'm routing through with ResourceHandler.FromFilePath(...).
> This works fine in my standalone application, but not when my view-class is used as addin in a larger application. In that case I get a ProgressEvent with a single property isTrusted = true as error.

Nothing immediate comes to mind. The `ProgressEvent` you're talking about, is that on the JS side?

**Comment by ray007** [comment]
The `ProgressEvent` was on the JS side, but I tracked it down to a non-existent file.

**Comment by perlun** [comment]
Thanks for reporting back! It might help someone else sometime.
