### ISSUE TITLE
WebGL software rendering is broken in CefSharp 57

### ISSUE THREAD

**Issue by engate** [cefsharp/CefSharp#2182]
I'm running Windows Server 2016 x64 in Virtualbox.The test app runs the latest Cefsharp.

Howerver when I check chrome://gpu I get the following:
WebGL: Unavailable
WebGL2: Unavailable

It does work If I install the quest additions. But I'm not the only one having this issue on windows 8 also.

If I install Firefox or Chrome on the server WebGL works without installing quest additions.
So seems like something is missing(?) and not sure what.

Thanks for the help.

**Comment by perlun** [comment]
CefSharp builds on top of CEF, which in turns builds on top of Chromium - the open source code base that is the basis for Chrome. _However_, it's not 100% the same thing as Chrome (it's compiled using slightly different settings, because of legal and perhaps other reasons as well.)

If I put it like this: is it a _problem_ for you to install the guest additions? That's the way you're normally "expected" to do it if you want to have accelerated graphics in a VM.

**Comment by merceyz** [comment]
"Latest Cefsharp" This is relative and means nothing, please include version (follow the issue template).

Based on the date I'm assuming this is
https://bitbucket.org/chromiumembedded/cef/issues/2291/windows-software-rendered-webgl-does-not

**Comment by perlun** [comment]
Nice find @merceyz! @engate, please try again with the latest `master` version of CefSharp, it should give you CEF 62 which should have this fix.

**Comment by merceyz** [comment]
@perlun cef-binary needs to include the `swiftshader` folder to fix this issue (if my assumption is correct)

**Comment by perlun** [comment]
@merceyz 

> @perlun cef-binary needs to include the swiftshader folder to fix this issue (if my assumption is correct)

I think you are; good point. Would you like to give it a look?

**Comment by amaitland** [comment]
`swiftshader` binaries will be part of the `63.0.0-pre01` release, the `nuget` packages were restructured to include the additional `swiftshader` folder. It's important to note that `CEF` has no `GPU` blacklist feature like `Chromium`, so you'll have to implement this yourself if you wish to disable `GPU` acceleration based on `GPU`. 

Example of disabling `GPU` via command line arg.

```c#
settings.CefCommandLineArgs.Add("disable-gpu", "1");
```

If your still experiencing a problem with `63.0.0-pre01` then please download the `Sample Application` from http://opensource.spotify.com/cefbuilds/index.html
