### ISSUE TITLE
reddit login only works when the debugger is open

### ISSUE THREAD

**Issue by CarbonMan** [cefsharp/CefSharp#2184]
I am loading reddit into cefsharp. Everything loads, however, I can only log in when devtools is open! If devtools is closed the login attempt says "incorrect username or password".

I am really not sure on how to proceed with this one.

If I bring up the debugger after failing a login there aren't any particular messages that indicate what's going on. Then I press the login button while the debugger is open and it logs in.

From that point on reddit works fine regardless of whether devtools is open or not. Any ideas? I am lost.

EDIT: By turning on caching I have been able to stay logged in across sessions but it doesn't sort out the initial login problem for new users.

**Comment by jankurianski** [comment]
Please ask questions on gitter or stackoverflow.  Github is just for bug reports.  If you meant to enter this as a bug, please fill out the bug report template: https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

I would recommend you reproduce this issue in `cefclient` first, as this removes CefSharp from the equation, and it is easier to figure out which versions of CEF have the problem.

**Comment by perlun** [comment]
Closing because of lack of feedback from OP. (and, **please** follow @jankurianski 's great advice; it makes life easier for everybody. Maintaining takes a _lot_ of work from several individuals, so please help us be as efficient as we can be.)
