### ISSUE TITLE
Infinite loop problem

### ISSUE THREAD

**Issue by SturmCoder** [cefsharp/CefSharp#2186]
Hi I come from GeckoFX  mozilla wrapper from bitbucket since version 10 and I passed trough many bugs there and fixed some critical a long time ago. Cause it is a single-threaded apartment build, everything is much much slower when all is on single thread.

I am using custom MDI Tab Control to spawn new tabs. Each tab is another same form.
I found an infinite loop that causes crash after some small amount of time executed like:

http://www.quackit.com/html/codes/html_close_window_code.cfm
https://www.codeproject.com/News.aspx?ntag=19837497577736552&_z=9716591

And there is more probably as I noticed it happens when page has many items on it but not really sure yet cause I started few days ago using it.

Page starts loading and when it finish (LoadingStateChanged event with  if (!args.IsLoading) is about to fire to check for document completed) it starts firing it forever along with quick focus change from new browser back to spawned(i saw very quick changes between forms and it blinks badly when switching focuses, you cant focus to other open programs) and it happens on clear form without any events attached.
By visiting www.quackit.com above you will notice very quick changes between arrow pointer icon and hand when pointer is above any link(hand pointer). If try to close window when that loop is happening, whole program crashes very badly, but if it is navigate to etc. google browser returns to working mode and form can be closed safely.

Also settings.MultiThreadedMessageLoop = false; is not working at all, to try that option too. Forms is spawned without browser rendering anything, blank page and navigation is not possible further.
I am using regular Invoke(new MethodInvoker(() => to update controls from another thread.

Sorry I cant provide more detailed info I just started learning.

I am not sure if there is something else I missed about threads probably, but it does not looks as normal behavior.

Is there any way to stop browser repaint/resize/invalidate when focused?
Actually when I switch from one tab to another browser invalidates itself at any time it happens(Resize event is fired every time tab is switched).
This cause flicker and slowdown on large pages, when using tabs and it is just too slow for browser with that speed.

Thanks all for reading,
Wish you best regards,
Very great work, I will contribute as much as I can.
Here is screenshot of browser.
![untitled](https://user-images.githubusercontent.com/33391787/32418860-6f8954ea-c271-11e7-86b7-a623d37e5f2a.png)

**Comment by jankurianski** [comment]
Hi, sorry but GitHub issues are for bug reports only.  For general guidance and questions please ask on Gitter (CefSharp channel) or StackOverflow (tag with "cef" and "cefsharp").

**Comment by SturmCoder** [comment]
Ok my bad and thanks for info, will do it again more properly.
