### ISSUE TITLE
Kind of infinite loop

### ISSUE THREAD

**Issue by SturmCoder** [cefsharp/CefSharp#2187]
I found an infinite loop bug that happens on some specific pages and it causes crash after some short period of time executed like:

http://www.quackit.com/html/codes/html_close_window_code.cfm
https://www.codeproject.com/News.aspx?ntag=19837497577736552&_z=9716591

And there is more probably, I noticed it happens when page has many items on it but not really sure yet what causing this.
Page loads and LoadingStateChanged event with args.IsLoading parameter after loading page is set to false. it continue firing it forever along with quick focus change from new browser back to any open random tab, also saw very quick change between forms and it blinks) and it happens on clear form without any events attached.
If window is closed when that loop is active, whole program crashes, but if user navigate to etc. google browser returns to working state and form can be closed safely or used again.

I am unable to focus to any other open/minimised app during this event.

**Comment by mitchcapper** [comment]
Do you have your code repo online to look at reproducing this? The app demo you showed was not the default one.

**Comment by SturmCoder** [comment]
Well, I downloaded it via nuget package manager in Visual Studio 2017 and separate whole source code online in worst case (you do it yourself) scenario, like always. The demo you saw was from previous geckofx 45 mozilla xul browser, being rewritten for cefsharp now, still in progress. Once I done everything needed, I will post project of course here on github. I using blank form with only LoadingStateChanged event now. Any ideas about loop?

**Comment by mitchcapper** [comment]
the first site does not load for me:
```
--2017-11-05 19:13:38--  http://www.quackit.com/html/codes/html_close_window_code.cfm
Resolving www.quackit.com (www.quackit.com)... 162.253.124.228
Connecting to www.quackit.com (www.quackit.com)|162.253.124.228|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.quackit.com/html/codes/html_close_window_code.cfm [following]
--2017-11-05 19:13:38--  https://www.quackit.com/html/codes/html_close_window_code.cfm
Connecting to www.quackit.com (www.quackit.com)|162.253.124.228|:443... connected.
Unable to establish SSL connection.
```
The second site: https://www.codeproject.com/News.aspx?ntag=19837497577736552&_z=9716591 redirects to a news site (if that is your goal post the direct link?).

It loads and stays loaded for me.

You are going to either need to put your code up on your GitHub, or repro these issues in the sample code.

**Comment by SturmCoder** [comment]
Thanks for answer.
Hmm that is interesting, second one I copied from inbox directly it is redirecting to:

http://www.dailyherald.com/business/20171022/apprenticeships-are-coming-to-white-collar-office-work

Here is video of what happens on that site. It happens on blank form also on other machines with windows 7 and 10 too. I didnt modified any source code at all so there is still nothing to reproduce only if you want whole project like it is now to give it try.

See how it behaves:
https://www.youtube.com/watch?v=69c7R4EDsoI

This must be done in any way.

**Comment by perlun** [comment]
Closing this for now, since we haven't heard anything in three weeks. @SturmCoder - **please post sample code** that reproduces it, and we'll happily look into it.
