### ISSUE TITLE
wait for async js function to return value

### ISSUE THREAD

**Issue by flyingfish2016** [cefsharp/CefSharp#2188]
I'm trying to wait for one async javascript funtion to return, but I could not get it to work. The async JS function seems not being waited before return.

js side
async function dotNetBridgeInvoker(stringArgs) {
    
    var result = await myClass.instance.invoke(stringArgs);
    return result;
}

C# side

 public object InvokeJavaScript(string s)
        {
            object result = null;
            try
            {
                var task = this.WebBrowser.EvaluateScriptAsync(
                    new TimeSpan(0, 3, 0), "dotNetBridgeInvoker", s);
                var complete = task.ContinueWith(t =>
                {
                    if (!t.IsFaulted)
                    {
                        var response = t.Result;
                        result = response.Success ? (response.Result ?? "null") : response.Message;
                    }
                }, TaskScheduler.Default);
                complete.Wait();
            }
            catch (Exception e)
            {
                MessageBox.Show("Error while executing Javascript: " + e.Message, "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
            return result;
        }

**Comment by mitchcapper** [comment]
EvaluateScriptAsync is not for executing async functions but rather to return the result of a javascript function asynchronously.   Your best bet would be to bind an object and have the JS function callback to the bound object when done.

**Comment by amaitland** [comment]
Whilst it would be a nice feature to have, unfortunately `CEF` doesn't support `Promose` as a return type, so it's not possible to implement this.

> Your best bet would be to bind an object and have the JS function callback to the bound object when done.

As @mitchcapper suggests this is the easiest option. see https://github.com/cefsharp/CefSharp/wiki/General-Usage#3-how-do-you-expose-a-net-class-to-javascript for more details.
