### ISSUE TITLE
Unable to use own ICookieManager implementation due to bug?

### ISSUE THREAD

**Issue by mitchcapper** [cefsharp/CefSharp#2189]
- **What version of the product are you using?**
57 (although master looks the same)
- **What architecture x86 or x64?**
x64
- **On what operating system?**
    - Win7, Win 8, Win10, etc?
Win10
- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF
- **What steps will reproduce the problem?**
1. Implement ICookieManager
2. Implement IRequestContextHandler to return your own ICookieManager
3. Initialize CEFSharp with this ContextHandler
4. Start app
- **What is the expected output? What do you see instead?**
Expected? Should work. Actual? Crash due to error of custom ICookieManager cannot be cast to CEFSharp.CookieManager.

- **Please provide any additional information below.**
I am not building cefSharp from source due to the lack of #2179  however looking at the source I think I found the problem lines:
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Cef.h#L376,L379
It gets the ICookieManager and then if it exists it tries to new up a CEFSharp.CookieManager from it, however CEFSharp.CookieManager expects its concrete implementation and not the interface to the constructor.

I could not find any examples of implementing cookie manager to cross check but think I have the interface down.

**Comment by perlun** [comment]
Thanks, this seems indeed to be a bug (or should we say "not fully implemented functionality".) #2179 has now been resolved, so CefSharp should be compilable on VS2017 with VS2015 tooling - would you have a chance to see if you can fix the underlying bug? We are happy to accept a PR that fixes this.

**Comment by mitchcapper** [comment]
@perlun started to look at this.   My initial pass is that it tries to get a native version of the cefcookiemanager and then wrap it in the cefsharp CookieManager managed wrapper.  If the user specifies there own cookie manager however than gets returned rather than the native cefcookiemanager.  I think if we test if cookieManager  implements the interface we can then avoid wrapping it to solve the problem.      Will give it a shot and setup a PR if so.

**Comment by amaitland** [comment]
I wouldn't be wasting too much time on this, CEF doesn't support providing your own implementation of CefCookieManager. ICookieManager isn't an interface you can implement yourself, will always be a CookieManager, the type should be checked and a clear exception thrown. 

CefCookieManager does have virtual methods, which is a little misleading. By all means ask on ceforum for an official response.

**Comment by mitchcapper** [comment]
@amaitland thanks:)  For my own use case I had already figured out a work around so I was just doing it to finish the implementation for cefsharp.

**Comment by amaitland** [comment]
Throwing a descriptive exception would likely help others, improve the doc also

**Comment by mitchcapper** [comment]
Sure, do you want a compiler warning for classes inheriting from the interface?
