### ISSUE TITLE
Want to release cefsharp client program just for Windows

### ISSUE THREAD

**Issue by abhargav7** [cefsharp/CefSharp#2190]
~154 Mb is the size of cefsharp dll's in our installer
Our client program user will be just on windows any clue how can we decrease this 154 Mb size and we can use chromiumwebbrowzer without any issue?

**Comment by jankurianski** [comment]
Github is for bug reports only.  If you have a question ask it on stackoverflow or gitter.

https://github.com/cefsharp/CefSharp/wiki/Output-files-description-table-%28Redistribution%29
