### ISSUE TITLE
Chromium browser version

### ISSUE THREAD

**Issue by MearTechnology** [cefsharp/CefSharp#2191]
I am trying to embed a third party web app into a win forms app using c#, although the latest version of chrome I can get is 57 and I needed at least 60.

Any way of updating it?

I've tried other frameworks but still having similar issues.

Can you guys please help?

Regards

**Comment by mitchcapper** [comment]
@MearTechnology GH is for bugs, not requests for updates try gitter.  With that said merges have been coming for v60 so just wait and it should be out sometime soon I believe:)

**Comment by MearTechnology** [comment]
@mitchcapper  Thanks for your reply.

**Comment by mitchcapper** [comment]
If you can close the bug it would be good,  also some sites sometimes require a newer version of chrome without actually requiring a specific feature it has (stupid but true).  You could try using a newer UA and see if that works for your application.

**Comment by MearTechnology** [comment]
Hi @mitchcapper , 
Yes sorry I've forgotten to close the issue. 

Just before, how do I use a newer UA? 

Regards

**Comment by pedoc** [comment]
wait for update

**Comment by jankurianski** [comment]
@MearTechnology example of setting custom `UserAgent`: https://github.com/cefsharp/CefSharp/blob/0067d02360b241073a8f9e02ba360b19bc92430a/CefSharp.Example/CefExample.cs#L59

**Comment by MearTechnology** [comment]
@jankurianski 
I think the issue I am experiencing is related to the rendering of the app on Chrome57.

Something on that page requires version 60+ to render properly.

Anyway, I will try that and let you know if it works.
