### ISSUE TITLE
How to use callback in C# from JavaScript?

### ISSUE THREAD

**Issue by mamayadesu** [cefsharp/CefSharp#2194]
I have a method in my class which called `AddEvent` with `string eventName` and `??? callback`.
![default](https://user-images.githubusercontent.com/7975470/32722771-c596fde4-c88c-11e7-8779-b9ac2f06b645.png)
I've set some primitive type for callback, I've called `AddEvent` in JavaScript and got exception
![default](https://user-images.githubusercontent.com/7975470/32722818-f5b5e2b0-c88c-11e7-857d-b4db3e4a2985.png)

Ok. It is unable to convert `System.String` to `CefSharp.Internals.JavascriptCallbackProxy`, but...
![default](https://user-images.githubusercontent.com/7975470/32722899-5091b88a-c88d-11e7-9a94-f20ff4da93dd.png)
Where is `JavascriptCallbackProxy`?

Or what right way to use Javascript callback in C#?

I haven't found helpful documentation.

**Comment by Atvaark** [comment]
Callback parameters use the interface `CefSharp.IJavascriptCallback`. This should work for your use case.

```
public void AddEvent(string eventName, CefSharp.IJavascriptCallback callback)
{
	...
	callback.ExecuteAsync('arg1', 'arg2');
}
```

**Comment by mamayadesu** [comment]
Thank you!
