### ISSUE TITLE
CefSharp requires unpublished cef sdk version

### ISSUE THREAD

**Issue by Maci125** [cefsharp/CefSharp#2195]
The latest CefSharp requires cef sdk version 3.3112.1657 which is not available and cannot be downloaded neither by nuget nor at their website.

**Comment by BrantDna** [comment]
https://www.myget.org/feed/cefsharp/package/nuget/cef.sdk

**Comment by perlun** [comment]
I think this should be fine now. https://www.nuget.org/packages/cef.sdk/ now has version 3.3202.1686, which is the version we're using as of #2203. Closing.
