### ISSUE TITLE
Popup default size is too small - doesn't take window borders into account

### ISSUE THREAD

**Issue by Thorarin** [cefsharp/CefSharp#2199]
- **What version of the product are you using?**
57.0.0 (NuGet)

- **What architecture x86 or x64?**
x86

- **On what operating system?**
Windows 7

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
Run this script in any page:
`window.open("", "", "width=500,height=500");`

- **What is the expected output? What do you see instead?**
Normal browser behavior (Chrome/IE/FF/etc) is to open a popup with 500x500 pixels of space for whatever webpage is being displayed. CefSharp opens up a popup that is exactly 500x500 pixels border to border. The actual usable space on my particular system is about 484x460 pixels or so. For optimal compatibility, CefSharp should mimic the browser behavior more closely.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
No, it reserves extra space for the window borders and its crappy toolbar 🙂

**Comment by Thorarin** [comment]
Note: I have some hope that I'll be able to override this behavior (I'm only just getting started using CefSharp), but that's kind of beside the point. The default behavior should be better.

**Comment by mitchcapper** [comment]
Yes you can certainly override the behavior for all popup / new tab requests. checkout
```
IRequestHandler.OnOpenUrlFromTab
ILifeSpanHandler.OnBeforePopup
```

**Comment by nuttaone** [comment]
Implement your own handler by implementing ILifespanHandler interface to your custom class to control popups.

See here:
https://github.com/cefsharp/CefSharp/blob/b77878e2fdfd12a409a07248847a790617b63eab/CefSharp.Wpf.Example/Views/BrowserTabView.xaml.cs#L41

And here: examplehttps://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf.Example/Handlers/LifespanHandler.cs

**Comment by perlun** [comment]
@Thorarin You may be right, this could be a bug. Please add some screenshots also proving the point.

Pull requests that improve this area are welcome. For now, I consider this issue resolved, since information has been provided on how to work around it - closing.
