### ISSUE TITLE
 a tag doesn't show properly

### ISSUE THREAD

**Issue by loyalto** [cefsharp/CefSharp#2202]
My problem is that the a tag doesn't show properly. Like this
![image](https://user-images.githubusercontent.com/7401364/33205736-fe45e150-d142-11e7-884a-0586d3350917.png)

, the CEF version is 51.0.0.0, WinForm, win10, and the CefSharp.WinForms.Example is normally displayed. What do I need to set?

**Comment by mitchcapper** [comment]
@loyalto please see the https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md for details on the testing you should do first.  For example does it happen in the CEF Test App client? If so a bug needs to be filed with them.

**Comment by loyalto** [comment]
@mitchcapper I don't have this problem with the latest version
