### ISSUE TITLE
How to read Image in a web page?

### ISSUE THREAD

**Issue by tiydotcn** [cefsharp/CefSharp#2205]
How to read Image in a web page?

**Comment by mitchcapper** [comment]
Per the submission guidelines: https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md
please do not ask questions on github but use gitter instead.  Please also include more detail when you do.

**Comment by merceyz** [comment]
See https://github.com/cefsharp/CefSharp/issues/1389#issuecomment-152319996
