### ISSUE TITLE
WinForms, cant add UserControl in design mode

### ISSUE THREAD

**Issue by ilbarzo** [cefsharp/CefSharp#2206]
I try to add a UserControl browser in a form. By adding it on code behind, I have no problem.
I can Build and use it without problem.
If I try to add the UserControl in design mode, by dragging the UC from toolbox I have this error:
![2017-12-07_10-56-04](https://user-images.githubusercontent.com/2872864/33709483-d4f5680c-db3d-11e7-9582-73be4451f1d7.jpg)

Environment:
Windows 10 x64
Visual Studio 2015
C++ redistributable installed from 2005 to 2015, both x86 and x64
CefSharp from NuGet master 57

Any idea?

**Comment by avspeed** [comment]
I am not sure if that is fully implemented yet
Take a look at this issue
https://github.com/cefsharp/CefSharp/pull/1946

**Comment by merceyz** [comment]
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Fork the https://github.com/cefsharp/CefSharp.MinimalExample project and provide an example that reproduces your problem.

**Comment by mitchcapper** [comment]
The other thing you can do is fire up procmon and see where it is looking for the cefsharp dll's (maybe the project folder if not the output folder) and manually copy them there.

**Comment by merceyz** [comment]
That isn't the problem in this case.
It's not supposed to load those files while in designer mode.

I tested and also got the same error so something has changed since the PR that fixed this

**Comment by ilbarzo** [comment]
Hi @merceyz , I have forked the MinimalExample as suggested, added a winform and a usercontrol to reproduce the issue.
committed here: [https://github.com/ilbarzo/CefSharp.MinimalExample/commit/1029c87c7eb64bfee524b308fbef3e0cd94e7646](url)

tnx for support

**Comment by amaitland** [comment]
Adding the `ChromiumWebBrowser` control using the designer is working fine for me. @merceyz Are you seeing problems with the control or adding a `User Control`?

> committed here: https://github.com/ilbarzo/CefSharp.MinimalExample/commit/1029c87c7eb64bfee524b308fbef3e0cd94e7646

@ilbarzo Your example has references to classes from `CefSharp.Core` for which you basically have three options for:

- Move all references to classes `CefSharp.Core` outside of any control that will be used by the designer
- Add `Design Mode` checks (the `CefSharp.WinForms.ChromiumWebBrowser` control has similar checks, combined with `NoInlining` methods so the `unmanaged` resources aren't loaded)
- Remove the following code block, it's only required if you actually need to specify some settings.

```c#
CefSettings settings = new CefSettings();
Cef.Initialize(settings);
```

**Comment by merceyz** [comment]
@amaitland I don't know what I did in the past but here are my results now. 

Using 
```
Microsoft Visual Studio Community 2017
Version 15.5.5
VisualStudio.15.Release/15.5.5+27130.2026
Microsoft .NET Framework
Version 4.6.01590
```
With commit https://github.com/cefsharp/CefSharp/commit/bfbd30cce571aa1dbabbe00dd0452ccc20fb987d

Adding the `ChromiumWebBrowser` to the form in the designer works fine.
Close the designer and open it again or restart Visual Studio and the designer shows an error with this call stack:

```
at cef_string_utf8_to_utf16(SByte* , UInt32 , _cef_string_utf16_t* )
at CefStringTraitsUTF16.from_string(basic_string\,std::allocator >* str, _cef_string_utf16_t* s) in e:\cefsharp\packages\cef.sdk.3.3239.1723\cef\include\internal\cef_string_wrappers.h:line 223
at CefStringBase.FromString(CefStringBase* , basic_string\,std::allocator >* str) in e:\cefsharp\packages\cef.sdk.3.3239.1723\cef\include\internal\cef_string_wrappers.h:line 579
at CefStringBase.{ctor}(CefStringBase* , SByte* src) in e:\cefsharp\packages\cef.sdk.3.3239.1723\cef\include\internal\cef_string_wrappers.h:line 316
at ?A0x732eed7f.??__E?A0x732eed7f@kEvaluateJavascriptRequest@Messaging@Internals@CefSharp@@YMXXZ() in e:\cefsharp\cefsharp.core\internals\messaging\messages.h:line 18
at _initterm_m((fnptr)* pfbegin, (fnptr)* pfend) in f:\dd\vctools\crt\crtw32\msilcrt\puremsilcode.cpp:line 214
at .LanguageSupport.InitializePerProcess(LanguageSupport* ) in f:\dd\vctools\crt\crtw32\msilcrt\mstartup.cpp:line 384
at .LanguageSupport._Initialize(LanguageSupport* ) in f:\dd\vctools\crt\crtw32\msilcrt\mstartup.cpp:line 603
at .LanguageSupport.Initialize(LanguageSupport* ) in f:\dd\vctools\crt\crtw32\msilcrt\mstartup.cpp:line 809 
```

Clicking `Ignore and Continue` lets me see the form again.

**Comment by merceyz** [comment]
I did some testing and found a solution to the problem, will create a PR later.
WPF works fine

**Comment by merceyz** [comment]
I just had a look at your code and it's really clear why it crashes.

Here you try to initialize CEF, the designer can't do this
https://github.com/ilbarzo/CefSharp.MinimalExample/commit/1029c87c7eb64bfee524b308fbef3e0cd94e7646#diff-67a139483c4a2935ebb6dec04aa42213R27

Here you're using the "not designer friendly" constructor
https://github.com/ilbarzo/CefSharp.MinimalExample/commit/1029c87c7eb64bfee524b308fbef3e0cd94e7646#diff-67a139483c4a2935ebb6dec04aa42213R29
https://github.com/ilbarzo/CefSharp.MinimalExample/commit/1029c87c7eb64bfee524b308fbef3e0cd94e7646#diff-8f1d90e0c8445b055c8989b4b7e1591aR20

This issue is not related to CefSharp but rather your control
