### ISSUE TITLE
AppVeyor: Enforce whitespace sanity 

### ISSUE THREAD

**Issue by perlun** [cefsharp/CefSharp#2208]
While going through the list of commits for the upcoming 62.0.0 prerelease, I noted that there were a few commits in there that dealt with sanitizing whitespace.

We should:

- [x] Convert the whole codebase to use spaces instead of tabs. This **must** be done in one or more separate PRs from functional changes, to make it reviewable. (#2504)
- [ ] Add automatic checking on AppVeyor to ensure the whitespace is sane. I don't know what tools are good for this in the C++ and C# world; in Ruby we have the (in)famous Rubocop. Is there anything similar for C++ and C#? I looked briefly and https://github.com/oclint/oclint might be one tool. Don't know if it deals with whitespace or only other issues.

Ideally, a PR which introduces whitespace errors should fail the build on AppVeyor so we can ensure consistency in an automated manner. You shouldn't really have to sit and check these kind of things manually; this is what computers are good for IMO.

If anyone want to work on this, please just write a note here saying that you're doing it so we know. But apart from that, feel free to dig in!

**Comment by amaitland** [comment]
Will look at adding a clang format file when VS 2017 15.7 is out

https://blogs.msdn.microsoft.com/vcblog/2018/03/13/clangformat-support-in-visual-studio-2017-15-7-preview-1/

**Comment by perlun** [comment]
@amaitland Nice! Does it support C++/CLI also?

**Comment by merceyz** [comment]
Part one was done in #2504 (updated OP to show this)

As long as people use an editor that supports EditorConfig then there should be no more tabs, this was added in #2514.
This should also fix formatting issues as long as people actually trigger a format before they commit.

**Comment by amaitland** [comment]
Editorconfig has pretty much eliminated the whitespace inconsistencies. 

Closing now as I don't see a great return in spending more time on this.
