### ISSUE TITLE
 launching .exe from browser closed automatically  after calling dispose on chromium browser

### ISSUE THREAD

**Issue by shashiprakashmishra** [cefsharp/CefSharp#2209]
I am using  WPF chromium browser in my application. I  launched  the  .exe using WPF chromium Browser(System.Diaogonistics.Process.Start(@ processname)). Exe is launched sucessfully. but  after calling browser dispose function  exe closed automatally. In my application chromium browser initialize two times.
Is there any work around that exe should keep on running even user has called wpf chromium bowser dispose function?

--

- **What version of the product are you using?**
    - What version are you using? Nuget? CI Nuget? build from a branch? If so which branch?
e.g. 53.0.1
    - Please only create an issue if you can reproduce the problem with the latest version.

- **What architecture x86 or x64?**

- **On what operating system?**
    - Win7, Win 8, Win10, etc?

- **Are you using `WinForms`, `WPF` or `OffScreen`?**

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.
    - Please no binary (zip, etc) links, fork the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) and push your changes to `GitHub`. (Alternatively use a code sharing service list `Gist` or `Pastebin`).

- **What is the expected output? What do you see instead?**

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?

**Comment by merceyz** [comment]
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Fork the https://github.com/cefsharp/CefSharp.MinimalExample project and provide an example that reproduces your problem.

**Comment by amaitland** [comment]
@shashiprakashmishra Please update your issue and fill out the bug report (I've copied and pasted the template, please use it).

**Comment by amaitland** [comment]
Closing due to lack of feedback.
