### ISSUE TITLE
Error In setup

### ISSUE THREAD

**Issue by Jaswant0039** [cefsharp/CefSharp#2210]
Hello Sir,

I am used CefSharp in winform its giving error when after creating setup when run the setup.

System.IO.FileNotFoundException: Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found. File name: 'CefSharp.Core.dll' at CefSharp.WinForms.ChromiumWebBrowser.InitializeFieldsAndCefIfRequired() at CefSharp.WinForms.ChromiumWebBrowser..ctor(String address) at OSMMap.ShowMap.ShowMap_Load(Object sender, EventArgs e) at System.Windows.Forms.Form.OnLoad(EventArgs e)

**Comment by AgapovAlexsey** [comment]
See [Wiki](https://github.com/cefsharp/CefSharp/wiki/Output-files-description-table-(Redistribution))
