### ISSUE TITLE
Will CefSharp display "out of date" message? 

### ISSUE THREAD

**Issue by flyingfish2016** [cefsharp/CefSharp#2212]
Sometimes there’s an error/status that appears in the Chrome web control if it’s out of date, something like this:
http://forum.ucweb.com/data/attachment/forum/201605/25/070622pr194pmqkp9tsuqz.png

I'm not sure who does the work to detect if the browser is out of date. Is it the website server? Or is it the browser provider?  Will the user get this message if she/he installs the cefsharp and doesn't update it at all?

We are trying to have the cefsharp only navigate to our single website. I thought this "out of date" is rendered from the website itself. Am I right?

Thanks,

**Comment by jankurianski** [comment]
Please ask questions on gitter or StackOverflow as instructed in the new issue template.  This isn't a bug in Cef or CefSharp and is instead related to the website you are visiting.
