### ISSUE TITLE
cannot create dump file when app crashing using crash_reporter.cfg

### ISSUE THREAD

**Issue by vincentshow** [cefsharp/CefSharp#2214]
CefSharp.WinForms 57.0.0 x64 in win7, installed by nuget.

Follow the instruction of https://bitbucket.org/chromiumembedded/cef/wiki/CrashReporting.md
1. Create crash_reporter.cfg file in bin folder, and the content is:
    [Config]
    ProductName=cef 
    ProductVersion=57.0
    
    RateLimitEnabled=false
    MaxUploadsPerDay=0
    
    [CrashKeys]
    testkey1=small
    testkey2=medium
    testkey3=large

2. Open CefSharp.MinimalExample.WinForms.exe, give me an error window said CefSharp.MinimalExample.WinForms has been stopped working.

3. Copy same file into cefclient.exe folder, then open cefclient.exe, it's working ok.

What's more, after clicking close button in the error window, the minimalexample is working. But crashed after loading chrome://inducebrowsercrashforrealz without dump file created in C:\Users\administrator\AppData\Local\CEF\User Data\Crashpad\reports, while the cefclient created one in the folder above.

What I need are:
1. Application can be started successfully with crash_reporter.cfg file in it's folder
2. Cef can create dump file in the specified path

Any suggestion, budy? Thanks a lot.

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf.Example/crash_reporter.cfg for an example. You need to specify the external handler

**Comment by vincentshow** [comment]
Bingo, thanks a lot. I'll close this issue after testing upload dump files to server tomorrow.

**Comment by amaitland** [comment]
> I'll close this issue after testing upload dump files to server tomorrow.

If you have further questions please ask them on http://magpcss.org/ceforum/viewforum.php?f=6 (and post a link back here for reference). Generic `CEF` questions are best asked there.
