### ISSUE TITLE
popup issues with custom window creation in lifespan handler

### ISSUE THREAD

**Issue by mitchcapper** [cefsharp/CefSharp#2216]
so master points to chrome 63, which is a bit broken for popups right now due to:
https://bitbucket.org/chromiumembedded/cef/issues/2330/regression-creating-a-window-in-javascript
so this is branched from 1d0c231 right before the update.

I uncommented the sample ILifespanHandler and then made some minor tweaks to make it work:
https://github.com/mitchcapper/CefSharp/commit/58a2af63030ddde9915c24d32d0cefd096bab135

Mainly don't call SetAsPopup until the browser is initialized (use a sleep hack for now) or else it just doesn't work.   Doing that allows URL's to open fine (IE: https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_win_open is fine).  Also show the window.

I remember seeing that the code actually does the exact same thing as SetAsPopup in ClientAdapter once OnBeforePopup returns so it wasn't calling SetAsPopup after initialized that really mattered(as it just toggles a bool) but rather that it has to get past:
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf/ChromiumWebBrowser.cs#L1663-L1666

in the initalization process before HasParent is set.   That is the only location a WPF browser instance is actually created and once HasParent is set it never will.

For reference if you don't call SetAsWindowless CEF will pop another window open, so it must be used if you are not returning true (to completely cancel out the popup).

So some samples:
https://www.w3schools.com/code/tryit.asp?filename=FMODJ1VNIR9G
works perfect with returning false right away in the function,  but having the lifespan handler create the window it opens, a handle is returned, but the initial write fails.   (Hitting close will say no P elements found).  Oddly if you then manually close the window and then just hit open window again nothing happens, no window is opened but when you hit close window button now it works.

For more fun:
https://www.w3schools.com/code/tryit.asp?filename=FMOEFBH6OGT0
hitting close will write one element into it and then alert only one (should alert two).  I thought maybe it was trying to write to the window too fast but no sleeping on either thread fixed it.  

Have not had a chance to dig too much more into it but some initial test cases and findings.

**Comment by amaitland** [comment]
> I uncommented the sample ILifespanHandler and then made some minor tweaks to make it work:

@mitchcapper Was there a reason you only uncommented part of the code? Your missing created and close handling

**Comment by mitchcapper** [comment]
@amaitland, sorry that was some late night idiocy on my part and sorry for the time waste.   Was originally trying to figure out the new crash (cef has patched it now) and started from scratch to make sure I had as few as possible sample changes. In digging deeper into CEF I can see also how it gets initialized if setup as popup and the code does work unmodified (minus the function signature change).

The two custom w3c samples still don't work but it does remove my previous initialization requirements.

**Comment by amaitland** [comment]
> sorry that was some late night idiocy on my part and sorry for the time waste

@mitchcapper No problem, I've been there 😄 

I see there's a couple of patches including the popup one that made it through today, so will build a new  set of `cef-binary` packages when a build is avalaible

> The two custom w3c samples still don't work but it does remove my previous initialization requirements.

There are still quite a few `CEF` bugs that need to be fixed for `OSR` popups to work properly, see #1267 for details on one of those issues, there are others from memory, I don't have links

**Comment by mitchcapper** [comment]
it looks like the upstream bug for #1267 got closed as he was returning true (rather than false) from the function call.  Although that doesn't solve the issue.  The ticket is likely right though that forking the cef client sample with custom windows is probably the best way to have them take it more seriously.  I will see if I can do that.  It is slightly interesting here that if you don't write the window right away it works, for example:
https://www.w3schools.com/code/tryit.asp?filename=FMPZHC7FD8Q7
click button one then click button two and something will appear in the window.

**Comment by amaitland** [comment]
`master` has been upgraded to `CEF 3.3239.1709.g093cae4 / Chromium 63.0.3239.109` so the popup issue that you reported should be resolved.

**Comment by amaitland** [comment]
Far as I know this was resolved `upstream`, so closing this. If changes are required in `CefSharp` this can be reopened.

**Comment by amaitland** [comment]
Closing as this was resolved upstream. 

https://bitbucket.org/chromiumembedded/cef/issues/2330/regression-creating-a-window-in-javascript#comment-42077288
