### ISSUE TITLE
FileResourceHandler  throws System.AccessViolationException if file doesn't exist

### ISSUE THREAD

**Issue by srini1978** [cefsharp/CefSharp#2217]
- **What version of the product are you using?**
   version 57
   
- **What architecture x86 or x64?**
x86
- **On what operating system?**
Win 10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF
- **What steps will reproduce the problem?**

- **What is the expected output? What do you see instead?**

The application containing the CEF browser window crashes and we see a crash report in the Event viewer. 2 event viewer events are created 

1. Description of the event viewer event says : The process was terminated due to an unhandled exception,.

Exception info :System.AccessViolationException
at <Module> .CefStreamResourcehandler ....
at <Module>.CefSharp.Internals.ClientAdapter.GetResourcehandler

**Comment by mitchcapper** [comment]
You skipped over the steps to reproduce. Does this happen with the CEF client itself?  Please see the rest of the submission guidelines:  https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by srini1978** [comment]
Hi ,
Steps to reproduce.
1. I forked the GitHub minimal example for WPF application and made changes. 

[https://github.com/srini1978/CefSharp.MinimalExample  ](url)

2. run the WPF application
3. I am getting the attached error
[stacktrace.txt]

(https://github.com/cefsharp/CefSharp/files/1585379/stacktrace.txt)

**Comment by amaitland** [comment]
@srini1978 Thanks

Without looking into it in any great detail there are two different `ResourceHandler` implementations used, so will have to debug which is causing the problem. 

The `CEF Unmanaged` implementation is very unforgiving if files don't exist on disk, so I've added a quick check, see commit https://github.com/cefsharp/CefSharp/commit/d8f86c6a2bb87f89bcad8fc74f9b997064e7c815

The next potential problem is that `ByteArrayResourceHandler` isn't pinning the `managed` memory which is an oversight on my part that should be fixed.

**Comment by srini1978** [comment]
Thanks @amaitland  
From the stacktrace, it looks like the second Resourchandler is throwing this exception. the first one is loading from the File while the second one is loading . I looked through the second resourcehandler code and it is calling ByteArrayResourcehandler , that is same method you have mentioned above.

Is the fix that you are planning for Byteresourcehandler something that I can try from my end as well?

The exception details below.
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at CefStreamResourceHandler.{ctor}(CefStreamResourceHandler* , CefStringBase<CefStringTraitsUTF16>* , scoped_refptr<CefStreamReader>* , Int32 )
   at CefSharp.Internals.ClientAdapter.GetResourceHandler(ClientAdapter* , scoped_refptr<CefResourceHandler>* , scoped_refptr<CefBrowser>* browser, scoped_refptr<CefFrame>* frame, scoped_refptr<CefRequest>* request) in c:\projects\cefsharp\cefsharp.core\internals\clientadapter.cpp:line 708
The thread 0x5808 has exited with code 0 (0x0).
The program '[26288] CefSharp.MinimalExample.Wpf.exe: Program Trace' has exited with code 0 (0x0).
The program '[26288] CefSharp.MinimalExample.Wpf.exe' has exited with code 0 (0x0).

**Comment by srini1978** [comment]
Hello @mitchcapper , @amaitland 
Found the issue in our code.  The resource handler was trying to load a .min.js file which was never there in the local disk.  Hence the accessviolationexception was being thrown.

**Comment by amaitland** [comment]
> The resource handler was trying to load a .min.js file which was never there in the local disk. Hence the accessviolationexception was being thrown.

@srini1978 Great, thanks for confirming 👍 That should be handled by https://github.com/cefsharp/CefSharp/commit/d8f86c6a2bb87f89bcad8fc74f9b997064e7c815

Leaving this open as there's still the other possible case that should be fixed.

**Comment by amaitland** [comment]
Closing this as the issue should be resolved, will track the other improvement in #2238
