### ISSUE TITLE
can not Analog mobile device using ChromiumWebBrowser

### ISSUE THREAD

**Issue by mkc-renhuozhu** [cefsharp/CefSharp#2221]
hi 
i have install the  CEF ,version is 51.0.0.0
i want to analog mobile device using ChromiumWebBrowser control,
so i change the user Agent to mobile user Agent, e.g (iphone6 plus)
but i can't to view the mobile website like a mobile device.
how can i do for this? 
 i help to analog mobile device just like chrome device mode.

**Comment by vwmberry95** [comment]
First thing you need to do is update to the stable version and try again.

**Comment by mitchcapper** [comment]
Try gitter for questions, not bug reports.  Mobile versions can be determined by more than UA like the window size as well.

**Comment by amaitland** [comment]
See https://bitbucket.org/chromiumembedded/cef/issues/1992/devtools-device-emulation-mode-missing-in
