### ISSUE TITLE
Adding settings breaks code.

### ISSUE THREAD

**Issue by TheConsciousness** [cefsharp/CefSharp#2222]
Currently I would like the ability to work with local storage, so I read a post about adding settings to the browser like so:

![image](https://user-images.githubusercontent.com/14192161/34445617-eb11e720-eca2-11e7-8446-238f278f1cb8.png)

However, the moment I fill in the **ourSettings** variable, everything below this area breaks. Anything to do with defining variables breaks the whole solution. 

The semicolon next to "cache" says "'}' expected. The ending semicolon says that it isn't needed.
Everything else says "does not exist in the current context"

Has anyone had any experience with this?

**Comment by mitchcapper** [comment]
@TheConsciousness   You are applying settings to a struct,class in c#.  The proper method to do so is a comma not a semi colon.  This is a c# coding question (maybe try stackoverflow or similar) not CEFSharp related.
