### ISSUE TITLE
Make AppVeyor output the test run output

### ISSUE THREAD

**Issue by perlun** [cefsharp/CefSharp#2227]
As discussed in #2219:

> Regarding the test runs - would it make sense if we added the test output to AppVeyor, so we could more easily see results of tests (without having to download the branch and test it locally)?

**Comment by amaitland** [comment]
See https://www.appveyor.com/docs/running-tests/#xunit-2x

**Comment by amaitland** [comment]
Thanks to @campersau this has been resolved in #3065
