### ISSUE TITLE
your browser does not currently recognize any of the video formats available

### ISSUE THREAD

**Issue by yuzemre** [cefsharp/CefSharp#2229]
### Bug Report

- **What version of the product are you using?**
   57

- **What architecture x86 or x64?**
x64
- **On what operating system?**
    -windows10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms
- **What steps will reproduce the problem?**
    I try to embed a youtube video. But video doesn't play it says your browser does not currently recognize any of the video formats available. If happnes only live streams. Youtube says h264 doesn't supported.

            CefSettings settings = new CefSettings();
            Cef.Initialize(settings);
            chrome = new ChromiumWebBrowser("https://www.youtube.com/watch?v=RtU_mdL2vBM");
            chrome.Dock = DockStyle.Fill;
            this.panel1.Controls.Add(chrome);

**Comment by mitchcapper** [comment]
h264 is proprietary codec it is not supported by the open source CEF with the default compile.  You would need to compile from scratch cef,cef-binary,cefsharp to support it.   MP3 is also not supported currently but will be in C65 (several months).

**Comment by amaitland** [comment]
See #1479 for details

**Comment by derekantrican** [comment]
Just to double-check (since it's been over a year) is the solution here still to "self-build" cefsharp?

**Comment by mitchcapper** [comment]
@derekantrican  correct however there is now a more automated way to build cefsharp: https://github.com/mitchcapper/CefSharpDockerfiles

**Comment by derekantrican** [comment]
Ok. It seems that YouTube thinks CefSharp should be fully supported (when browsing to https://www.youtube.com/supported_browsers ) but when trying to play one of the videos, still shows the "error": ![screen](https://i.imgur.com/3Z8QFRC.gif)
