### ISSUE TITLE
when exit appliction, occasionally, an exception occurs

### ISSUE THREAD

**Issue by stonezhu870** [cefsharp/CefSharp#2235]
### Bug Report
-Win7 sp1, x86
-cefsharp 49 / winform

When I exit appliction, occasionally, an exception occurs. This problem can not be reproduced every time.I can see the following log in the windows event viewer.

![image](https://user-images.githubusercontent.com/3832691/35034723-1227dbc4-fbaa-11e7-9d45-9bf7ea239961.png)
![image](https://user-images.githubusercontent.com/3832691/35034766-385fad08-fbaa-11e7-9161-45b0baf1d561.png)

My app exit code  is:
![image](https://user-images.githubusercontent.com/3832691/35034836-7132a90a-fbaa-11e7-8c4d-6265e8ebb83a.png)

please help me

**Comment by amaitland** [comment]
> -cefsharp 49 / winform

`49` is a very old unsupported version, as the error is originating from `libcef.dll`, to actually resolve this you'd probably have to debug the `CEF/Chromium` code and fix it yourself.

In reality this is likely to be closed as `wontfix` as there is no `upstream` support for old version.

**Comment by amaitland** [comment]
`57.0.0` is the current release, with version `63.0.0` to be released fairly soon, so if you can, upgrade to a newer version (If your using `49` because of `Windows XP` support then unfortunately there is no option to upgrade).
