### ISSUE TITLE
Blank page when loading  html string embedded jpag decoded 64base 

### ISSUE THREAD

**Issue by lirboy** [cefsharp/CefSharp#2236]
I have a WPF project and i use the chrome web browser control.
I receive  html string with embedded  picture from third system and i need to display it in my app.
the string is encoded in base 64 and i decode it successfully but all i get is empty page
other html string without embedded picture are displayed  successfully.
has anyone encountered/familiar this issue and how to resolve it?

**Comment by amaitland** [comment]
When filling out a bug report please use the template provided https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report (You can view the raw version at https://raw.githubusercontent.com/cefsharp/CefSharp/master/ISSUE_TEMPLATE.md to copy and paste)

**Comment by merceyz** [comment]
Closing due to lack of feedback
