### ISSUE TITLE
Localstorage Loading problem

### ISSUE THREAD

**Issue by micro-bean** [cefsharp/CefSharp#2243]
### Bug Report
- **v49.0.1**
- **x86**
- **Win7**
- **WinForms**

Using complete code：
```c#
string stmp = System.Reflection.Assembly.GetExecutingAssembly().Location;
stmp = stmp.Substring(0, stmp.LastIndexOf('\\'));

var setting = new CefSharp.CefSettings()
{
                CachePath = stmp + @"\Cache",
};
CefSharp.Cef.Initialize(setting);

ChromiumWebBrowser chromiumWebBrowser = new ChromiumWebBrowser("xxxx");
Controls.Add(chromiumWebBrowser);
```

html code:
```html
< input id='text' type='text'>
    < button onclick="save()">save</ button>
    <script>
      var value=localStorage.getItem('text');
      if(value && value!=""){
        document.getElementById('text').value=value;
      }

      function save(){
        var _value=document.getElementById('text').value;
        localStorage.setItem('text',_value);
      }
    </script>
```

The web address is a simple text box. The data entered in the text box is stored in Localstorage. If you open the interface and input text box data, you need to wait for more than a minute to shut down the program to open it again to see the cached data.

Thank you for the reply！

**Comment by amaitland** [comment]
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Also please fork the https://github.com/cefsharp/CefSharp.MinimalExample project and provide an example that reproduces your problem.

**Comment by micro-bean** [comment]
Revise the description of the problem. Please reply. Thanks.

**Comment by amaitland** [comment]
Unfortunately you're using an old unsupported version so upgrading is likely the only option.

**Comment by micro-bean** [comment]
I'm sorry, I tried to change the latest version of V63.0.0-pre01 to have the same problem

**Comment by amaitland** [comment]
Sounds like you're experiencing https://bitbucket.org/chromiumembedded/cef/issues/2063/add-api-for-programmatically-flushing

Try explicitly calling Cef.Shutdown before your application exits. 

It's important to remember that CefSharp is just a wrapper around the Chromium Embedded Framework

**Comment by amaitland** [comment]
If the problem reproduces with the latest version then someone will need to test with `cefclient`, see https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-chromium-embedded-frameworkcef for details.

**Comment by amaitland** [comment]
A workaround might be to try The enable-aggressive-domstorage-flushing command line arg

https://cs.chromium.org/chromium/src/content/public/common/content_switches.cc?q=kEnableAggressiveDOMStorageFlushing&sq=package:chromium&type=cs&l=958
