### ISSUE TITLE
WPF touch works just by enabling touch-events cefcommandlineargument!

### ISSUE THREAD

**Issue by Sanbala** [cefsharp/CefSharp#2245]
- **What version of the product are you using?**
  CEF 3.2987.1601(Chromium 57.0.2987.133)
    - What version are you using? Nuget? CI Nuget? build from a branch? If so which branch?
Chromium 57.0
    - Please only create an issue if you can reproduce the problem with the latest version.
Yes! tried with latest version 63.0.0-pre01. Same behaviour
- **What architecture x86 or x64?**
x86
- **On what operating system?**
    - Win7, Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF
- **What steps will reproduce the problem?**
 Enable touch in laptop
Run the sample WPF application [here ](https://github.com/Sanbala/Cefsharp-WPF)
touch/multi touch works perfectly
- **What is the expected output? What do you see instead?**
How does touch works without any work around? According to this link, "https://bitbucket.org/chromiumembedded/cef/pull-requests/104/touch-processing-for-osr-different-api/diff" touch is not supported yet. I would like to understand what was the problem that creates the issue so that it wouldn't affect me after release!
- **Please provide any additional information below.**
  Touch scrolling / multi touch works as expected in this application. Tried with 49,57 and 63. Works well in all versions

**Comment by amaitland** [comment]
@Sanbala Thanks for taking the time to fill out the bug report, we really like to keep issues for bug reports only and this feels more like a question. Quick questions you should as on https://gitter.im/cefsharp/CefSharp



> Enable touch in laptop
> Run the sample WPF application here
> touch/multi touch works perfectly

The `WinForms` version has touch support, which is what your demo is using https://github.com/Sanbala/Cefsharp-WPF/blob/master/CefSharpSample/packages.config#L6 Other than the name you've chosen everything else appears to be a standard `WinForms` project. For testing purposes you can use https://github.com/cefsharp/CefSharp.MinimalExample

If you do require touch screen support for `WPF` it's suggested that you use the `WinForms` version in a `WindowsFormsHost`.
