### ISSUE TITLE
 CefSharp.BrowserSubprocess does not like multiple windows sessions

### ISSUE THREAD

**Issue by BruceBoc** [cefsharp/CefSharp#2249]
- **What version of the product are you using?**
57
- **What architecture x86 or x64?**
X86
- **On what operating system?**
 Win7
- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms with VB.net

- **What steps will reproduce the problem?**
My application works correctly when it is launched once or even several times at the same time on the same windows session. However, if a windows session remained connected to my application, I can not start it from another session. I have a windows message "CefSharp.BrowserSubprocess.exe has stopped working".
This is problematic because at my work computers are used by many users, who often forget to log out of their session.
The only solutions are either to restart the PC to no longer have open sessions open, or to launch my application from a second installation of it.
Application is on intranet local network.

- **What is the expected output? What do you see instead?**
CefSharp.BrowserSubprocess.exe has stopped working
Nothing in "debug.log"

**Comment by amaitland** [comment]
What does your Cef.Initialize code look like?

**Comment by BruceBoc** [comment]
Public Class Form1

    Public WithEvents chromeBrowser As ChromiumWebBrowser

    Public Sub New()
        CefInit()
    End Sub

    Protected Overrides Sub Finalize()
        chromeBrowser.Dispose()
        MyBase.Finalize()
    End Sub

    'Initialise le navigateur internet
    Private Sub CefInit()

        InitializeComponent()

        Dim settings As New CefSettings()
        settings.CachePath = "C:\Users\" + Environment.UserName + "\Documents\Prefs raccourcis\data\cache"
        End If

        settings.LogFile = "logsfiles\" + Environment.UserName + ".log"
        settings.LogSeverity = LogSeverity.Error

        CefSharp.Cef.Initialize(settings)

        chromeBrowser = New ChromiumWebBrowser("file:///./Raccourcis/Raccourcis.html") With {
            .Dock = DockStyle.Fill
        }

        Panel1.Controls.Add(chromeBrowser)

        Dim BrowserSettings As New BrowserSettings()
        BrowserSettings.FileAccessFromFileUrls = CefState.Enabled
        BrowserSettings.UniversalAccessFromFileUrls = CefState.Enabled
        chromeBrowser.BrowserSettings = BrowserSettings

        chromeBrowser.RegisterJsObject("cefCustomObject", New CefCustomObject(chromeBrowser, Me))

    End Sub


I have tried on my home computer with 2 sessions, no problems. Probably intranet problem.

**Comment by amaitland** [comment]
> I have tried on my home computer with 2 sessions, no problems.

What exactly are you classing as a `session`?

For reference `Chromium` only allows one process to access the `Cache`, so to run multiple processes for the one `User` they need separate `Cache` paths.

Do you have a `stacktrace` for the crash your seeing? If not you can enable `Crashpad` and capture the crash dump. See https://bitbucket.org/chromiumembedded/cef/wiki/CrashReporting.md for details (make sure you specify the handler as described in #2214)

**Comment by BruceBoc** [comment]
Per session I mean user account. 

On my program, cache path is different per user : 
settings.CachePath = "C:\Users\" + Environment.UserName + "\Documents\Prefs raccourcis\data\cache".

But may be you are right, because one user could connect to 2 computer with the same account as the same time.

I can't doing test for the moment, but i will retry next month.

thanks

**Comment by amaitland** [comment]
> Per session I mean user account.

Are you talking `Terminal Services`, `Citrix` or something else?

**Comment by BruceBoc** [comment]
No, just simple windows session user.
Like this : [https://www.malekal.com/wp-content/uploads/Demarrer_mode_sans_echec_Windows7_2.png](https://www.malekal.com/wp-content/uploads/Demarrer_mode_sans_echec_Windows7_2.png)

**Comment by BruceBoc** [comment]
I tried to connect two users at the same time on the program and on the same pc, and the problem did not reappear. Moreover, since I modified the program so that it copies itself and launches in c: / user / public, I have no more crash. I therefore close this thread.

Thanks

**Comment by jankurianski** [comment]
@BruceBoc thanks for letting us know the workaround 👍
