### ISSUE TITLE
SendProcessMessage message not recieved after process switch

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#2250]
After upgrading to the `3239` branch (`63`) `IPC` process messages sent from the `Render` process from `OnContextCreated` are no longer being received successfully when a `render process switch` occurs (`cross-site navigation` causes process switch).

Have discussed the issue at http://magpcss.org/ceforum/viewtopic.php?f=6&t=15677

Have yet to open a `Bug` on the `CEF` issue tracker.

`IRenderProcessMessageHandler.OnContextCreated` will no longer be reliably called in `3239`, removing the `CanExecuteJavascriptInMainFrame` checks for now.

**Comment by AgapovAlexsey** [comment]
@amaitland Is this a bug in CefSharp or Cef? I found only one related problem https://bitbucket.org/chromiumembmbed/cef/issues/2325/problem-with-sendprocessmessage-on-branch

**Comment by amaitland** [comment]
It's probably a chance in Chromium that causes the problem.  I haven't tested in a recent branch to see if it's been resolved. 

The bitbucket link just shows a 404 For me.

**Comment by AgapovAlexsey** [comment]
Update link

I think the problem is in CefSharp, otherwise there would be a lot of complaints about this in Cef.
Most likely something broke just after solving this problem. Even in time coincides.

**Comment by amaitland** [comment]
Very unlikely a problem in CefSharp.  It's only the last message sent from a render process as it's  closing that never arrives, so it's only going to affect a very small number of users would ever be effected by this. It's likely Chromium exiting the process in an unclean fashion for performance reasons that causes the issue.

**Comment by amaitland** [comment]
The link you have posted was for an issue that was fixed long ago, totally unrelated to this issue.  It was for sending messages from the browser process on a non UI thread, this issue is sending a message from the render process. 

What exactly is your interest in this issue?

**Comment by amaitland** [comment]
> It's only the last message sent from a render process as it's closing that never arrives, so it's only going to affect a very small number of users would ever be effected by this. 

My mistake,  I should have reread my own notes. It's the first message. 

The whole chromium navigation subsystem has been rewritten since this was created.  So by all means test again to see if it's resolved

**Comment by amaitland** [comment]
Still reproduces with current `master` at commit https://github.com/cefsharp/CefSharp/commit/72ee102bcf67c2ec293c5ab0e98044d83c3bb65f

Should be pretty trivial to modify `cefclient` to reproduce the issue. 

I don't currently have any plans to look into this further. By all means continue your own research and report back.

**Comment by AgapovAlexsey** [comment]
@amaitland Can I financially support the project so that you have an interest in solving this problem?

**Comment by amaitland** [comment]
@AgapovAlexsey What is it you are trying to do? Maybe there is a workaround.

Fixing this is likely a non trivial task, not really sure how feasible it is at this stage.

**Comment by AgapovAlexsey** [comment]
@amaitland 
1) I need to synchronously execute js code in OnContextCreated in each frame. And for different instances of the browser it will be different.
Why synchronous? Because otherwise, scripts that are stored in the cache run faster.
2) In order to switch to Binding v2, you will have to make a lot of important changes, which can seriously disrupt the program.

The first problem can of course be solved with crutches. Make for example your own branch and come up with a mechanism for how to inject js right into the rendering process. And on the second, to steal a lot of time and nerves of users, but rewrite under v2, but I think that it is necessary to deal with this bug. It will be more useful for both CefSharp and me. After all, a bug that we do not know how to fix is ​​a problem that we do not understand. And it is not clear what else it can wag now and what will affect in the future.

**Comment by amaitland** [comment]
> 1. I need to synchronously execute js code in OnContextCreated in each frame. And for different instances of the browser it will be different.

Sending a message from the `Render` process does not enable `synchronous` execution of javascript, there is quite simply no way to do that from the browser process using the `async IPC mechanism` that is provided by `CEF`. The only way to do this would be to execute the code directly in the `CefRenderProcessHandler::OnContextCreated` method in the render process.

In reality the difference in timing between `OnContextCreated` and `FrameLoadStart` is pretty trivial when executed in the `Browser Process`.

> 2\. In order to switch to Binding v2, you will have to make a lot of important changes, which can seriously disrupt the program.

In most cases the changes are very minimal, the objects themselves are `100%` compatible, only the way they are bound changes. If you provide an example that you need help migrating over then I can help you.

> The first problem can of course be solved with crutches. Make for example your own branch and come up with a mechanism for how to inject js right into the rendering process

Adding the wrappers required to implement a custom `subprocess` with support for `CefRenderProcessHandler` is possible, if this is something you wish to sponsor development of then we can discuss that further. This is the only way you will get `sync` execution (other than hacking something together yourself, which is totally up to you).

> After all, a bug that we do not know how to fix is ​​a problem that we do not understand. And it is not clear what else it can wag now and what will affect in the future.

Having a reliable `OnContextCreated` in the browser process would certainly be great to have. Providing a patch for the `cefclient` example application should be fairly trivial, I believe reproducing this in `CEF` will be fairly easy. I'll see if I can find time to create one. If the issue reproduces in `cefclient`, then it will need to be raised with the `CEF` project, if I'm unable reproduce it then it is something I can look into further in the context of `CefSharp`.

**Comment by AgapovAlexsey** [comment]
> Sending a message from the Render process does not enable synchronous execution of javascript, there is quite simply no way to do that from the browser process using the async IPC mechanism that is provided by 

I used the built-in IPc and ManualResetEvent and it could work if all the messages came

> Adding the wrappers required to implement a custom subprocess with support for CefRenderProcessHandler is possible, if this is something you wish to sponsor development of then we can discuss that further

Will it also provide direct access to Dom and V8Context? If so, be sure to support.

> If you provide an example that you need help migrating over then I can help you.

I agree that it is not difficult. I just have a lot of places where it is needed. And I worry that it is possible to get some new errors.

>  I'll see if I can find time to create one. If the issue reproduces in cefclient, then it will need to be raised with the CEF project, if I'm unable reproduce it then it is something I can look into further in the context of CefSharp.

I will be happy to help financially the project so that you can find time and solve this problem for everyone.

Please send me an email to discuss this: helperut1@mail.ru

**Comment by AgapovAlexsey** [comment]
@amaitland ?

**Comment by amaitland** [comment]
Sorry, will come back with a detailed answer when I have time.

At the moment working on releasing a new version to resolve #2677

**Comment by amaitland** [comment]
https://bitbucket.org/chromiumembedded/cef/issues/2644/process-messages-sent-from was closed with the report that this issue will be fixed in 
https://bitbucket.org/chromiumembedded/cef/issues/2498/add-support-for-site-per-process

The proposed change of moving `SendProcessMessage` from `CefBrowser` to `CefFrame` will require a substantial rewrite. This is a breaking change, though no changes to the `CefSharp`  public facing `API` are expected.

**Comment by amaitland** [comment]
https://bitbucket.org/chromiumembedded/cef/commits/241941a44a260885f6455e5618189c45ffb0ed40 has been merged moving `SendProcessMessage` to `CefFrame`, waiting to see which branch the change is included in.

**Comment by amaitland** [comment]
Initial tests are promising,  the changes moving SendProcessMessage from CefBrowser to CefFrame are included in https://github.com/cefsharp/CefSharp/pull/2809

Relevant commits are 
https://github.com/cefsharp/CefSharp/pull/2809/commits/a73e56d4d936fbd6f20f3d9d0666169066c1b9b1
https://github.com/cefsharp/CefSharp/pull/2809/commits/df617c1a474c302fe3059ee227f927a1385eca3a

There are a number of other changes bundled together unfortunately,  so many CEF API changes made it impossible to split the initial set of changes out.

**Comment by amaitland** [comment]
The `upstream` issue appears to be resolved.
