### ISSUE TITLE
Mouse events & scroll not working in WPF application only in touch screen laptop

### ISSUE THREAD

**Issue by Sanbala** [cefsharp/CefSharp#2251]
- **What version of the product are you using?**
CEF 3.2987.1601(Chromium 57.0.2987.133)
    - **What version are you using? Nuget? CI Nuget? build from a branch? If so which branch?
57.0.0
    - Please only create an issue if you can reproduce the problem with the latest version.
yes! could reproduce in 63.0.0-pre01
- **What architecture x86 or x64?**
x86
- **On what operating system?**
    - Win7, Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF
- **What steps will reproduce the problem?**
  Run the application
  Try to click any buttons,dropdowns and try to scroll down the page

- **What is the expected output? What do you see instead?**
button click should trigger a event and work 
scrolling should work
- **Please provide any additional information below.**
    This problem exists only in touch screen laptop. i don't want touch facility since WPF doesn't support touch! I just want the mouse click events and scroll to work!.

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
no abnormalities traced in log

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
WPF application which opens a EXTJS sencha application using cefsharp. Everthing works perfect in regular laptop. Only in Touch screen laptop, facing this page freezing issue. I can't ask all users to disable touch. I should handle this within code to make this work in all laptop. There may be some conflicts in handling mouse events in touch screen laptop which you may aware of.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
No

**Comment by jankurianski** [comment]
Does this problem also occur with the `MinimalExample` app, or is the problem unique to your application?

**Comment by Sanbala** [comment]
It doesn't occur in minimal example! It is unique to my application.

**Comment by jankurianski** [comment]
Can you fork `MinimalExample` to reproduce the problem?

**Comment by Sanbala** [comment]
I didn't face this issue in MinimalExample also in other sample applications that i created. I not sure what is wrong with my main application. Would this be because of any local event handling or something? or any solution on this behaviour?

**Comment by jankurianski** [comment]
I don't personally use WPF or touch screens so I can't help.

You will need to make a small reproducible example in order to demonstrate the bug, and during this process you might find the part of your program causing the problem.

**Comment by amaitland** [comment]
Closing due to lack of feedback. Can be reopened if a sample that reproduces the problem is provided.

**Comment by amaitland** [comment]
The `RoutedEvent` is marked as `Handled` to resolve #2422

You will need to use `UIElement.AddHandler` to subscribe to the event see https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/routed-events-overview#the-concept-of-handled

**Comment by igor-eremyashev** [comment]
Thanks, it worked. The code is
`browser.AddHandler(UIElement.MouseWheelEvent, new MouseWheelEventHandler(BrowserOnMouseWheel), true);
`
