### ISSUE TITLE
HTTPS proxy supporting?

### ISSUE THREAD

**Issue by Troodi** [cefsharp/CefSharp#2252]
I trying to set https proxy but this not working.

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).
