### ISSUE TITLE
cefsharp WPF how to get current url ?

### ISSUE THREAD

**Issue by bavly** [cefsharp/CefSharp#2254]
- **What version of the product are you using?**
     Nuget version 57  
- **What architecture x86 or x64?**
86
- **On what operating system?**
     server Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

That is a question did not find my answer in Minmal Example 
I see that it is working with Winforms
like that 
 browser.AddressChanged += OnBrowserAddressChanged;
But tired it on wpf it is not working

**Comment by jankurianski** [comment]
This is not a bug.  Please ask questions on Stackoverflow or Gitter chat.
