### ISSUE TITLE
Chromium browser fails to load https url of AWS cloudfront

### ISSUE THREAD

**Issue by YogeshPD** [cefsharp/CefSharp#2257]
When I try to open a url https://******.cloudfront.net in Chromium, I see a blank page. Same url loads just fine in Google Chrome however I see a warning 

"The SSL certificate used to load resources from https://********.cloudfront.net will be distrusted in M70. Once distrusted, users will be prevented from loading these resources"

Has Chromium already distrusted https urls from AWS's cloudfront?

**Comment by amaitland** [comment]
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

**Comment by amaitland** [comment]
Closing due to lack of feedback. The `63.0.0-pre03` set of packages are out, you should test with those. If you are still seeing a problem then read https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-chromium-embedded-frameworkcef

**Comment by xmedeko** [comment]
Hi, we have same issue with 57.0, upgrading to 63.0.3 has fixed that. But the upgrade requires some code and some testing before we can release that.
@amaitland I just wonder: CefSharp does not use the Windows certificate store? If so, why 57 refuses the new cloudfrond certificate while 63 accepts it? Thanks for the explanation.
