### ISSUE TITLE
WPF Improve Scrollbar/Scroll Drag Usability

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#2258]
Follow up to #2060

It should be possible to capture the mouse outside of the control to improve usability.

Need to capture mouse and then release the capture.

Possibly `Mouse.PreviewMouseUpOutsideCapturedElement` attached event might be usable here.

 https://msdn.microsoft.com/en-us/library/system.windows.input.mouse.previewmouseupoutsidecapturedelement(v=vs.110).aspx

**Comment by amaitland** [comment]
First attempt at fixing this see commit https://github.com/cefsharp/CefSharp/commit/c843317e338e572fb485b31b6ec3c9c7a517ca53

**Comment by amaitland** [comment]
Changes reverted, seems when leaving the `Window` forces `Capture` to be lost. Appears to be a limitation of `WPF`, can possibly deal with this behaviour and capture scroll when staying within `Window`. To capture when leaving the `Window` might require some `Win32 API` calls.

**Comment by amaitland** [comment]
> Changes reverted, seems when leaving the `Window` forces `Capture` to be lost

For clarity, this behaviour reintroduces #2060, detailed steps to reproduce in https://github.com/cefsharp/CefSharp/pull/2871#issuecomment-524189434

**Comment by amaitland** [comment]
Looking at the `WPF` source it looks like a standard [SetCapture](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setcapture) with a [ReleaseCapture](https://docs.microsoft.com/en-gb/windows/win32/api/winuser/nf-winuser-releasecapture)

https://referencesource.microsoft.com/#WindowsBase/Shared/MS/Win32/SafeNativeMethodsCLR.cs,486
https://referencesource.microsoft.com/#WindowsBase/Shared/MS/Win32/SafeNativeMethodsCLR.cs,272

So it's actually likely the `WPF Window` has the capture, it's just not forwarding the messages onto our control, probably because it's outside the window. More digging through the source required to verify this.

**Comment by amaitland** [comment]
Thanks to the excellent detective work of @mol  it appears the Capture related issues are only if the machine has a touch screen. Described roghly in https://github.com/dotnet/wpf/issues/1323 (I was having issues way before `1809` was released, the workaround proposed resolves the issues, so assuming it's the same).

https://github.com/dotnet/wpf/issues/1323#issuecomment-528183423 suggests there is a fix in the pipeline and should arrive early next month. It's not clear which versions of `.Net` this fix will apply to as yet.

There is a PR in the works at #2871

**Comment by amaitland** [comment]
Based on #2871 I've added `ChromiumWebBrowserWithMouseCapture` in https://github.com/cefsharp/CefSharp/commit/08b6c052253fc42416b265824b82326f2cdb39da this change is only in the `cefsharp/75` branch and will be part of the upcoming `75.1.142` release. Anyone wanting to test this out please report back here. Hopefully the `WPF` issue is resolved shortly and we'll have a permanent fix in the `77` release.

Example of using `DisableStylusAndTouchSupport` in https://github.com/cefsharp/CefSharp/commit/bb5b60b51264a0148592a1359d2367cea4b481d2

**Comment by rladuca** [comment]
@amaitland The fix for dotnet/wpf#1323 is in the OS input stack and will therefore affect all .NET versions.

**Comment by amaitland** [comment]
> The fix for [dotnet/wpf#1323](https://github.com/dotnet/wpf/issues/1323) is in the OS input stack and will therefore affect all .NET versions.

@rladuca Thanks for the clarification 👍 Do you have a link that provides more detail? Which `Windows 10 Feature` updates will the fix be targeting?
