### ISSUE TITLE
OnPreKeyEvent for IKeyboardHandler InvalidAsynchronousStateException

### ISSUE THREAD

**Issue by PR4GM4** [cefsharp/CefSharp#2259]
- **What version of the product are you using?**
    Latest Nuget Stable.

- **What architecture x86 or x64?**
    x86 but running on x64 and x86 by some users.

- **On what operating system?**
    Win 10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WinForms

- **What steps will reproduce the problem?**
    I have no idea what caused this, it occured by a user on my app.

- **What is the expected output? What do you see instead?**
   I expected it to get the returnvalue and continue operation but instead the Invoke caused an Exceptiom/

- **Please provide any additional information below.**
```
System.ComponentModel.InvalidAsynchronousStateException: Wystąpił błąd podczas wywoływania metody. Wątek docelowy już nie istnieje.
   w System.Windows.Forms.Control.WaitForWaitHandle(WaitHandle waitHandle)
   w System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   w System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   w System.Windows.Forms.Control.Invoke(Delegate method)
   w #=zrluxWEztJPxiBxUFvw==.OnPreKeyEvent(IWebBrowser #=z1bWgEc0=, IBrowser #=zglsSRKc=, KeyType #=zUiOjqik=, Int32 #=zGSaRV4zsiQH9, Int32 #=zrp2zbZqpvL0v, CefEventFlags #=zipQZ8wA=, Boolean #=z3hG1z43qmGZV, Boolean& #=zHdlKvpVoJ4Fr)
   w CefSharp.Internals.ClientAdapter.OnPreKeyEvent(ClientAdapter* , scoped_refptr<CefBrowser>* browser, CefStructBase<CefKeyEventTraits>* event, tagMSG* os_event, Boolean* is_keyboard_shortcut)
```

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

    Im unable to test.

**Comment by PR4GM4** [comment]
This is the area of code it seems to occur at:
https://i.imgur.com/QdrCx3b.png

Which is a pure copy paste from the source code on GitHub.

**Comment by amaitland** [comment]
> What version of the product are you using?
> Latest Nuget Stable.

Next time please be specific, e.g. `57.0.0`, `Latest Nuget Stable` is relative and won't mean the same thing in a few months time.

> This is the area of code it seems to occur at:
> https://i.imgur.com/QdrCx3b.png
> 
> Which is a pure copy paste from the source code on GitHub.

A link to the code would have been better, thanks.

If you look at the `.Net Reference Source` it says that your `UI` thread is in an `Invalid` state

https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/Control.cs,4399

`Stackoverflow` does a better job of explaining than I can see https://stackoverflow.com/questions/6360876/understanding-invalidasynchronousstateexception-occurrences

I've never seen the problem reproduce in the example, never used that code in production myself. It's not really a bug in `CefSharp`, you are welcome to contribute to improving the example.

You can switch to integrating `CEF` into your apps message loop and do away with the `KeyboardHandler`, see https://github.com/cefsharp/CefSharp/wiki/General-Usage#multithreadedmessageloop

**Comment by amaitland** [comment]
A simple try catch will handle the exception. See https://stackoverflow.com/questions/20684366/ui-an-error-occurred-invoking-the-method-the-destination-thread-no-longer-exis for a discussion related to Cefglue. 

By all means submit a PR that improves the example.

**Comment by amaitland** [comment]
https://stackoverflow.com/questions/6360876/understanding-invalidasynchronousstateexception-occurrences/6362388#6362388
