### ISSUE TITLE
win10  输入法  bug  中文备选框弹出的位置不是靠近输入窗。

### ISSUE THREAD

**Issue by CJXHZY** [cefsharp/CefSharp#2268]
win10  输入法 
 中文备选框弹出的位置不是靠近输入窗。

**Comment by perlun** [comment]
Please don't post issues in Chinese. For those of us not reading it, it's very hard to be able to help you.

**Comment by CJXHZY** [comment]
Sorry，Win10 system input method, the position of the Chinese standby box is not close to the input window.

**Comment by perlun** [comment]
Please follow the issue template; **do not delete the text**. We need much more feedback to be able to investigate your problem.
