### ISSUE TITLE
d3dcompiler_47.dll is preventing uninstall of client application

### ISSUE THREAD

**Issue by abhargav7** [cefsharp/CefSharp#2271]
CefSharp version **55.0.0**
architecture x86 or x64

operating system Win10 enterprise, issue not on win7.

Are you using WinForms, WPF or OffScreen?
WPF

d3dcompiler_47.dll is locked and installer could not delete this file on uninstall.
Also the web browser instance was disposed properly & was not running.
ChromiumWebBrowser.Dispose();

**Comment by amaitland** [comment]
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Also please fork the https://github.com/cefsharp/CefSharp.MinimalExample project and provide an example that reproduces your problem.

**Comment by abhargav7** [comment]
CefSharp version **55.0.0**
architecture x86 or x64

operating system Win10 enterprise, issue not on win7.

Are you using WinForms, WPF or OffScreen?
WPF

**Comment by amaitland** [comment]
Does the problem reproduce with version 63.0.0? Version you are using is old and unsupported. 

Make sure you are calling Cef.Shutdown, read the General Usage Guide on wiki if you need more information.

**Comment by amaitland** [comment]
Closing due to lack of feedback.
