### ISSUE TITLE
JavascriptObjectRepository.ResolveObject is not raised unless any object has been registered

### ISSUE THREAD

**Issue by mkosieradzki** [cefsharp/CefSharp#2273]
Version 63.0.0, x86, win10, winforms

`JavascriptObjectRepository.ResolveObject` event is not raised when calling `CefSharp.BindObjectAsync("obj1")` unless any object has been registered using `JavascriptObjectRepository.Register`

If I register any object first, then everything works as expected.

**Comment by amaitland** [comment]
Thanks, should be a trivial fix. 

For my own reference https://github.com/cefsharp/CefSharp/blob/38be769f9666611916e361fd0fcd7f0d6ed2a0e3/CefSharp.Core/Internals/ClientAdapter.cpp#L1142
