### ISSUE TITLE
Black flickering after upgrade to 63.0.0

### ISSUE THREAD

**Issue by mkosieradzki** [cefsharp/CefSharp#2274]
63.0.0, x86, Win10, WinForms

I am experiencing Windows Forms flickering (black flashes in the area of the Cef window) after recent upgrade from 55 to 63.

adding an option:
`CefCommandLineArgs = { { "disable-gpu", "1" } } `
or
`CefCommandLineArgs = { { "disable-gpu-compositing", "1" } }`

makes the problem go away.

**Comment by merceyz** [comment]
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Fork the https://github.com/cefsharp/CefSharp.MinimalExample project and provide an example that reproduces your problem.

**Comment by mkosieradzki** [comment]
@merceyz thanks for the instructions

I thought it will be a simple repro, because it looked like a regression, but when I tried to reproduce it using minimal example, it's not appearing...

I will try to do this, but expect it will take a lot of time to create a standalone repro ;-(. It might have to do with 3rd party component library used and their approach to paint windows..

**Comment by cztomczak** [comment]
@mkosieradzki Load `chrome://gpu` url and check for errors after the issue occured. Also check debug.log file for warnings/errors (set CefSettings.log_severity appropriately). If found try googling these error messages.

**Comment by mkosieradzki** [comment]
@cztomczak I have a working theory I need to validate - it's that a window higher in hierarchy is stealing WM_PAINT events. I am going to validate it right now.

**Comment by mkosieradzki** [comment]
@cztomczak @merceyz I found the root cause.
Window higher in hierarchy was stealing WM_PAINT.

I will leave this for others here:
If you are using DevExpress components you need to override `protected override bool SupportAdvancedTitlePainting => false;` as described for example here: https://www.devexpress.com/Support/Center/Question/Details/T588705/the-grid-is-painted-incorrectly-when-it-s-used-in-an-mdi-child-form-and-the-directx-mode

**Comment by maojsm** [comment]
I use version 63.0.0.0 of CEF Windows Forms and I do not have this problem. Just to contribute.
