### ISSUE TITLE
CefFileDialogMode should probably not have [Flags]

### ISSUE THREAD

**Issue by fuzzykiller** [cefsharp/CefSharp#2277]
- **What version of the product are you using?**
master at be50b75648eb75c4dfda38b3fa5c2b7ffcf93ca6

- **What architecture x86 or x64?**
x86

- **On what operating system?**
Windows 10 1709 x64

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
Try to use `CefFileDialogMode` enum (see [CefFileDialogMode.cs](https://github.com/cefsharp/CefSharp/blob/be50b75648eb75c4dfda38b3fa5c2b7ffcf93ca6/CefSharp/Enums/CefFileDialogMode.cs#L12))

- **What is the expected output? What do you see instead?**
Due to how the enum is structured, I expect it to be a regular enum. However, it is marked as a flag enum.

- **Please provide any additional information below.**
See below.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
Not applicable

---

The `CefFileDialogMode` enum has (since [ef21c492b67438cc100af09554ee6da717af7389](https://github.com/cefsharp/CefSharp/commit/ef21c492b67438cc100af09554ee6da717af7389#diff-e71583cdc041117b3d4197ea35cfb86d)) the `[Flags]` attribute. However, when looking at the values, that can’t be right. Here’s what a decompiler produces:

```csharp
[Flags]
public enum CefFileDialogMode
{
  Open = 0,
  OpenMultiple = 1,
  OpenFolder = 2,
  Save = OpenFolder | OpenMultiple, // 0x00000003
  TypeMask = 255, // 0x000000FF
  OverwritePrompt = 16777216, // 0x01000000
  HideReadOnly = 33554432, // 0x02000000
}
```

Surely, `Save` is not a combination of `OpenMultiple` and `OpenFolder`.

It appears the enum is somehow a mix of flags and non-flag values. While that may be appropriate in native code, I don’t think it is in .NET.

I’ll provide a pull request on this topic this weekend if that’s acceptable.

**Comment by amaitland** [comment]
Removing flags sounds reasonable, thought I haven't checked the CEF/Chromium source as yet.
