### ISSUE TITLE
Set up proxy at runtime with authentication

### ISSUE THREAD

**Issue by DianaArquillos** [cefsharp/CefSharp#2278]
I have this configuration for the browser as it was said, but I am getting a blank page in every request:
```
_browser = new ChromiumWebBrowser(url, browserSettings, requestContext);
if (proxyInf != null && proxyInf.url != null)
    isProxy = true;
_browser.RequestHandler = new RequestHandler(userAgent, url, isProxy, proxyInf);

Cef.UIThreadTaskFactory.StartNew(delegate
{

    var rc = _browser.GetBrowser().GetHost().RequestContext;
    var dict = new Dictionary<string, object>();
    dict.Add("mode", "fixed_servers");
    dict.Add("server", proxyInf.url);
    string error;
    bool success = rc.SetPreference("proxy", dict, out error);
    
});
```
if I go through a proxy, this proxy needs authentication and I notice I never get into the method of the credential. 
`IRequestHandler.GetAuthCredentials(IWebBrowser browserControl, IBrowser browser, IFrame frame, bool isProxy, string host, int port, string realm, string scheme, IAuthCallback callback)`
Any ideas?

**Comment by amaitland** [comment]
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

**Comment by DianaArquillos** [comment]
What version of the product are you using?

v63.0.1
What architecture x86 or x64?
x64
On what operating system?

Win10
Are you using WinForms, WPF or OffScreen?
OffScreen
What steps will reproduce the problem?

Please provide detailed information here, enough for someone else to reprodce your problem.
I have no permission to push an create a branch

Please provide any additional information below.

I get empty source back, I have made the updates using the minimalExample and I am still getting the same issue, and I didnt get through the get credential either

Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)

Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?

public class Program
    {
        private static ChromiumWebBrowser browser;

        public static void Main(string[] args)
        {
            const string testUrl = "https://www.whatismyip.com/";

            Console.WriteLine("This example application will load {0}, take a screenshot, and save it to your desktop.", testUrl);
            Console.WriteLine("You may see Chromium debugging output, please wait...");
            Console.WriteLine();

            var settings = new CefSettings()
            {
                //By default CefSharp will use an in-memory cache, you need to specify a Cache Folder to persist data
                CachePath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "CefSharp\\Cache")
            };
            //settings.CefCommandLineArgs.Add("proxy-server", "http://proxy.crawlera.com:8010");
            //Perform dependency check to make sure all relevant resources are in our output directory.
            Cef.Initialize(settings, performDependencyCheck: true, browserProcessHandler: null);

            // Create the offscreen Chromium browser.
            browser = new ChromiumWebBrowser(testUrl);

            Cef.UIThreadTaskFactory.StartNew(delegate
           {
               browser.RequestHandler = new ProxyHandler("8584dcaf4c5d4a58b4c71d7e7ebffdc4", String.Empty);
               var rc = browser.GetBrowser().GetHost().RequestContext;
               rc.GetAllPreferences(true);
               var dict = new Dictionary<string, object>();
               dict.Add("mode", "fixed_servers");
               dict.Add("server", "http://proxy.crawlera.com:8010");
               string error2;
               bool success = rc.SetPreference("proxy", dict, out error2);
               if (!success)
               {
                   Console.WriteLine("something happen with the prerence set up" + error2);
               }
           });
           
            // An event that is fired when the first page is finished loading.
            // This returns to us from another thread.
            browser.LoadingStateChanged += BrowserLoadingStateChanged;

            // We have to wait for something, otherwise the process will exit too soon.
            Console.ReadKey();

            // Clean up Chromium objects.  You need to call this in your application otherwise
            // you will get a crash when closing.
            Cef.Shutdown();
        }

        private static void BrowserLoadingStateChanged(object sender, LoadingStateChangedEventArgs e)
        {
            // Check to see if loading is complete - this event is called twice, one when loading starts
            // second time when it's finished
            // (rather than an iframe within the main frame).
            if (!e.IsLoading)
            {
                // Remove the load event handler, because we only want one snapshot of the initial page.
                browser.LoadingStateChanged -= BrowserLoadingStateChanged;

                var scriptTask = browser.EvaluateScriptAsync("document.getElementById('lst-ib').value = 'CefSharp Was Here!'");

                scriptTask.ContinueWith(t =>
                {
                    //Give the browser a little time to render
                    Thread.Sleep(500);
                    // Wait for the screenshot to be taken.
                    var task = browser.GetSourceAsync();

                    Console.WriteLine(task.Result);
                    task.ContinueWith(x =>
                    {
                        // Make a file to save it to (e.g. C:\Users\jan\Desktop\CefSharp screenshot.png)
                       // var screenshotPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), "CefSharp screenshot.png");

                       // Console.WriteLine();
                        //Console.WriteLine("Screenshot ready. Saving to {0}", screenshotPath);

                        // Save the Bitmap to the path.
                        // The image type is auto-detected via the ".png" extension.
                        //task.Result.Save(screenshotPath);

                        // We no longer need the Bitmap.
                        // Dispose it to avoid keeping the memory alive.  Especially important in 32-bit applications.
                        //task.Result.Dispose();

                        Console.WriteLine("Screenshot saved.  Launching your default image viewer...");

                        // Tell Windows to launch the saved image.
                        //Process.Start(screenshotPath);
                        
                        Console.WriteLine("Image viewer launched.  Press any key to exit.");			
                    }, TaskScheduler.Default);
                });
            }
        }
    }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CefSharp.MinimalExample.OffScreen
{
    using System.Security.Cryptography.X509Certificates;
    using CefSharp;

        public class ProxyHandler : IRequestHandler
        {
            private string userName;
            private string password;

            public ProxyHandler(string userName, string password)
            {
                this.userName = userName;
                this.password = password;
            }


            bool IRequestHandler.OnBeforeBrowse(IWebBrowser browserControl, IBrowser browser, IFrame frame, IRequest request, bool isRedirect)
            {
                return false;
            }

            bool IRequestHandler.OnOpenUrlFromTab(IWebBrowser browserControl, IBrowser browser, IFrame frame, string targetUrl, WindowOpenDisposition targetDisposition, bool userGesture)
            {
                return OnOpenUrlFromTab(browserControl, browser, frame, targetUrl, targetDisposition, userGesture);
            }

            protected virtual bool OnOpenUrlFromTab(IWebBrowser browserControl, IBrowser browser, IFrame frame, string targetUrl, WindowOpenDisposition targetDisposition, bool userGesture)
            {
                return false;
            }

            bool IRequestHandler.OnCertificateError(IWebBrowser browserControl, IBrowser browser, CefErrorCode errorCode, string requestUrl, ISslInfo sslInfo, IRequestCallback callback)
            {
                //NOTE: If you do not wish to implement this method returning false is the default behaviour
                // We also suggest you explicitly Dispose of the callback as it wraps an unmanaged resource.
                //callback.Dispose();
                //return false;

                //NOTE: When executing the callback in an async fashion need to check to see if it's disposed
                //if (!callback.IsDisposed)
                //{
                //    using (callback)
                //    {
                //        //To allow certificate
                //        //callback.Continue(true);
                //        //return true;
                //    }
                //}

                return false;
            }

            void IRequestHandler.OnPluginCrashed(IWebBrowser browserControl, IBrowser browser, string pluginPath)
            {
                // TODO: Add your own code here for handling scenarios where a plugin crashed, for one reason or another.
            }

            CefReturnValue IRequestHandler.OnBeforeResourceLoad(IWebBrowser browserControl, IBrowser browser, IFrame frame, IRequest request, IRequestCallback callback)
            {
                //Example of how to set Referer
                // Same should work when setting any header

                // For this example only set Referer when using our custom scheme
                //var url = new Uri(request.Url);
                //if (url.Scheme == CefSharpSchemeHandlerFactory.SchemeName)
                //{
                //    //Referrer is now set using it's own method (was previously set in headers before)
                //    request.SetReferrer("http://google.com", ReferrerPolicy.Default);
                //}

                //Example of setting User-Agent in every request.
                //var headers = request.Headers;

                //var userAgent = headers["User-Agent"];
                //headers["User-Agent"] = userAgent + " CefSharp";

                //request.Headers = headers;

                //NOTE: If you do not wish to implement this method returning false is the default behaviour
                // We also suggest you explicitly Dispose of the callback as it wraps an unmanaged resource.
                //callback.Dispose();
                //return false;

                //NOTE: When executing the callback in an async fashion need to check to see if it's disposed
                //if (!callback.IsDisposed)
                //{
                //    using (callback)
                //    {
                //        if (request.Method == "POST")
                //        {
                //            using (var postData = request.PostData)
                //            {
                //                if (postData != null)
                //                {
                //                    var elements = postData.Elements;

                //                    var charSet = request.GetCharSet();

                //                    foreach (var element in elements)
                //                    {
                //                        if (element.Type == PostDataElementType.Bytes)
                //                        {
                //                            var body = element.GetBody(charSet);
                //                        }
                //                    }
                //                }
                //            }
                //        }

                //        //Note to Redirect simply set the request Url
                //        //if (request.Url.StartsWith("https://www.google.com", StringComparison.OrdinalIgnoreCase))
                //        //{
                //        //    request.Url = "https://github.com/";
                //        //}

                //        //Callback in async fashion
                //        //callback.Continue(true);
                //        //return CefReturnValue.ContinueAsync;
                //    }
                //}

                return CefReturnValue.Continue;
            }

            bool IRequestHandler.GetAuthCredentials(IWebBrowser browserControl, IBrowser browser, IFrame frame, bool isProxy, string host, int port, string realm, string scheme, IAuthCallback callback)
            {
                //NOTE: If you do not wish to implement this method returning false is the default behaviour
                // We also suggest you explicitly Dispose of the callback as it wraps an unmanaged resource.
                if (isProxy == true)
                {
                    //throw new NotImplementedException();

                    callback.Continue(userName, password);

                    return true;
                }

                return false;
            }

            public bool OnSelectClientCertificate(IWebBrowser browserControl, IBrowser browser, bool isProxy, string host, int port,
                X509Certificate2Collection certificates, ISelectClientCertificateCallback callback)
            {
                throw new System.NotImplementedException();
            }

            void IRequestHandler.OnRenderProcessTerminated(IWebBrowser browserControl, IBrowser browser, CefTerminationStatus status)
            {
                // TODO: Add your own code here for handling scenarios where the Render Process terminated for one reason or another.
                //  browserControl.Load(CefExample.RenderProcessCrashedUrl);
            }

            bool IRequestHandler.OnQuotaRequest(IWebBrowser browserControl, IBrowser browser, string originUrl, long newSize, IRequestCallback callback)
            {
                //NOTE: If you do not wish to implement this method returning false is the default behaviour
                // We also suggest you explicitly Dispose of the callback as it wraps an unmanaged resource.
                //callback.Dispose();
                //return false;

                //NOTE: When executing the callback in an async fashion need to check to see if it's disposed
                //if (!callback.IsDisposed)
                //{
                //    using (callback)
                //    {
                //        //Accept Request to raise Quota
                //        //callback.Continue(true);
                //        //return true;
                //    }
                //}

                return false;
            }

            public void OnResourceRedirect(IWebBrowser browserControl, IBrowser browser, IFrame frame, IRequest request,
                IResponse response, ref string newUrl)
            {
                throw new System.NotImplementedException();
            }



            bool IRequestHandler.OnProtocolExecution(IWebBrowser browserControl, IBrowser browser, string url)
            {
                return url.StartsWith("mailto");
            }

            void IRequestHandler.OnRenderViewReady(IWebBrowser browserControl, IBrowser browser)
            {

            }

            bool IRequestHandler.OnResourceResponse(IWebBrowser browserControl, IBrowser browser, IFrame frame, IRequest request, IResponse response)
            {
                //NOTE: You cannot modify the response, only the request
                // You can now access the headers
                //var headers = response.ResponseHeaders;

                return false;
            }

            IResponseFilter IRequestHandler.GetResourceResponseFilter(IWebBrowser browserControl, IBrowser browser, IFrame frame, IRequest request, IResponse response)
            {
                //var url = new Uri(request.Url);
                //if (url.Scheme == CefSharpSchemeHandlerFactory.SchemeName)
                //{
                //    if (request.Url.Equals(CefExample.ResponseFilterTestUrl, StringComparison.OrdinalIgnoreCase))
                //    {
                //        return new FindReplaceResponseFilter("REPLACE_THIS_STRING", "This is the replaced string!");
                //    }

                //    if (request.Url.Equals("custom://cefsharp/assets/js/jquery.js", StringComparison.OrdinalIgnoreCase))
                //    {
                //        return new AppendResponseFilter(System.Environment.NewLine + "//CefSharp Appended this comment.");
                //    }

                //    return new PassThruResponseFilter();
                //}

                return null;
            }

            void IRequestHandler.OnResourceLoadComplete(IWebBrowser browserControl, IBrowser browser, IFrame frame, IRequest request, IResponse response, UrlRequestStatus status, long receivedContentLength)
            {

            }
        }
    
}

**Comment by amaitland** [comment]
Your not waiting for the context to actually initialize before trying to set the proxy. Wait for the browser to initialize or use code similar to https://github.com/cefsharp/CefSharp/blob/cefsharp/63/CefSharp.Example/Handlers/BrowserProcessHandler.cs#L72

**Comment by amaitland** [comment]
Make sure you check the debug.log file

**Comment by amaitland** [comment]
In case it's relevant Chromium doesn't support socks with authentication

http://magpcss.org/ceforum/viewtopic.php?f=6&t=15814

**Comment by amaitland** [comment]
If you don't need to change the proxy dynamically then you can use the built in helper see https://github.com/cefsharp/CefSharp/commit/fb374c0f941bc295ba53666ad8d80f017c12a5af

Closing as this is unlikely an actual bug in CefSharp.
