### ISSUE TITLE
JavaScript Binding Error: Failed to identify BrowserWrapper in OnContextCreated BrowserId

### ISSUE THREAD

**Issue by GrabzIt** [cefsharp/CefSharp#2279]
- 63.0.1
- x86
- Win10
- OffScreen
- **What steps will reproduce the problem?**

Great job with the new version, I only noticed one minor issue. If you specify a different browser process name using the BrowserSubprocessPath setting you will receive the Failed to identify BrowserWrapper in OnContextCreated BrowserId error.

- **What is the expected output? What do you see instead?**

It should bind the objects correctly.

**Comment by amaitland** [comment]
Are you using any command line args?

**Comment by GrabzIt** [comment]
Sorry, it was a false alarm. I think it was caused by the renderer-process-limit being 1.
