### ISSUE TITLE
Procedure imported by CefSharp.Core.Dll could not be loaded

### ISSUE THREAD

**Issue by jasonumd** [cefsharp/CefSharp#2284]
- **What version of the product are you using?**
    - What version are you using? Nuget? CI Nuget? build from a branch? If so which branch? Please include the exact version number you are using (no ambiguous statements like `Latest from Nuget`)
e.g. 57.0.0 or 63.0.0-pre01
    - Please only create an issue if you can reproduce the problem with the latest version. (If you are using the latest stable release please check to see if there is a newer `-pre` release and test with that also).
NuGet v63.0.1
- **What architecture x86 or x64?**
x86
- **On what operating system?**
    - Win7, Win 8, Win10, etc?
Win10
- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms
- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.
    - Please no binary (zip, etc) links, fork the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) and push your changes to `GitHub`. (Alternatively use a code sharing service list `Gist` or `Pastebin`).
CefSettings settings = new CefSettings();
Cef.Initialize(settings);
String page = string.Format(@"{0}\data\ogma\test.html", Application.StartupPath);
chromeBrowser = new ChromiumWebBrowser(page);
this.Controls.Add(chromeBrowser);
- **What is the expected output? What do you see instead?**
Browser should load in a form. I get "Procedure imported by CefSharp.Core.Dll could not be loaded".
![image](https://user-images.githubusercontent.com/1220913/36489067-10f64808-16f3-11e8-9d5d-2eccb1ede711.png)

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
I have VC++ Redistributable 2017 installed. Seems 2015 is needed, but waiting for an Admin to install that. Tested on another machine and 2015 didn't seem to change anything.
- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

    - To compare with WPF run cefclient --multi-threaded-message-loop --off-screen-rendering-enabled
    - To compare with WinForms run cefclient --multi-threaded-message-loop
    - If you can reproduce the problem with `cefclient` then you'll need to report the bug on https://bitbucket.org/chromiumembedded/cef/overview there is no point opening an issue here. (Make sure you search before opening an issue)
    - Please include the version you tested with e.g. `cef_binary_3.3029.1611.g44e39a8_windows64_client.tar.bz2`

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/blob/cefsharp/63/NuGet/Readme.txt#L27
Also look at the FAQ

**Comment by amaitland** [comment]
Closing as this is unlikely an actual bug in CefSharp.

**Comment by godrose** [comment]
Still happens with the latest version.
OS: Windows 7, Target: AnyCPU
@amaitland
