### ISSUE TITLE
problem , other response when i call click() ??

### ISSUE THREAD

**Issue by saidaniwael** [cefsharp/CefSharp#2285]
form code of website:
`<form method="POST" completion-event="Logins Attempted" novalidate="novalidate">
      <div class="form-group">
        <div class="form-row">
          <input class="valid" type="email" name="username" id="username" placeholder="username" required="" aria-required="true" aria-invalid="false"><label id="username-error" class="error" for="username" style="display: inline;"></label>
        </div>
        <div class="form-row">
          <input class="error" type="password" name="password" id="password" placeholder="password" required="" aria-required="true">
        </div>
        <input type="hidden" name="state" value="">
        <input type="hidden" name="client_id" value="starbucks-alexa-skill">
        <input type="hidden" name="response_type" value="code">
        <input type="hidden" name="redirect_uri" value="">
        <div class="form-row btn-row">
          <button class="btn gold" type="submit">Sign In</button>
          <a class="btn cancel close" href="javascript:window.close()">Cancel</a>
        </div>
      </div>
    </form>`
in the ChromiumWebBrowser when i click manually its work and get Sign In Error
but when i use
browser.ExecuteScriptAsync("document.getElementsByClassName(\"btn gold\")[0].click()");
i get other response : 'Unauthorized'
please what i should do , is there solution to submit with other way?

**Comment by jankurianski** [comment]
Please ask questions on Stackoverflow or Gitter.  Github is for bug reports only.
