### ISSUE TITLE
Update Nuget x86/x64 error message

### ISSUE THREAD

**Issue by Cloudmersive** [cefsharp/CefSharp#2287]
- **What version of the product are you using?**

64.02

    - What version are you using? 

NuGet

Stable

- **What architecture x86 or x64?**

x64

- **On what operating system?**

Windows 10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**

WPF and OffScreen both show this behavior

- **What steps will reproduce the problem?**

- Download Visual Studio 2017
- Create a new WPF project
- Add CefSharp.WPF using NuGet
- Set build configuration to x64
- Try to build

- **What is the expected output? What do you see instead?**

Builds

- **Please provide any additional information below.**

AppName\packages\CefSharp.Common.63.0.1\build\CefSharp.Common.targets(4,5): error : CefSharp.Common will work out of the box if you specify platform (x86 / x64). For AnyCPU Support see https://github.com/cefsharp/CefSharp/issues/1714

**Comment by Cloudmersive** [comment]
If I suppress this and run the project, I get this runtime error:

An unhandled exception of type 'System.IO.FileNotFoundException' occurred in mscorlib.dll

Additional information: Could not load file or assembly 'CefSharp.Core, Version=55.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138' or one of its dependencies. The system cannot find the file specified.

**Comment by amaitland** [comment]
You have to set the target at the solution level. Setting at just the project level is not enough.

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp.MinimalExample for a working example.

**Comment by Cloudmersive** [comment]
OK that works.  You might want to change the error message to mention both project and solution level for clarity.

**Comment by Cloudmersive** [comment]
Thanks

**Comment by amaitland** [comment]
Sounds reasonable, renamed issue and will update message for clarity.
