### ISSUE TITLE
Cef loads multiple images to crash in larger memory pages

### ISSUE THREAD

**Issue by niuwa28** [cefsharp/CefSharp#2288]
English:CefSharp loads multiple images to crash in larger memory pages.Can you tell me why and how to resolve this issue?
Chinese:CefSharp加载多图片并且占存较大的页面时会进程崩溃，请问这是什么原因及如何解决这个问题？

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage
