### ISSUE TITLE
Scroll issue in WPF

### ISSUE THREAD

**Issue by AltmanWong** [cefsharp/CefSharp#2290]
### Bug Report

- **What version of the product are you using?**
Build from branch, CefSharp 63.0.1 Release

- **What architecture x86 or x64?**
x86

- **On what operating system?**
Windows 7 Professional Service Pack 1

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
1. Run CefSharp.Wpf.Example
2. Direct to "http://www.google.com"
3. Make a search
4. Scroll down

- **What is the expected output? What do you see instead?**
Expected Result: A smooth scroll to the bottom of the page
Issue: The scroll stops at a random point which nears the end of the scroll bar

**Comment by amaitland** [comment]
How are you scrolling? Keyboard, mouse wheel, scroll bar? 

Did you test with the CEF sample application? As per the issue template. Also try the MinimalExample

Also see https://bitbucket.org/chromiumembedded/cef/issues/2214/osr-scroll-is-erratic-after-using-mouse

This could easily be an upstream issue.

**Comment by AltmanWong** [comment]
Oh this is exactly what I want, everything goes normal when I enable disable-smooth-scrolling. Thanks a lot @amaitland ! I will close this issue now.
