### ISSUE TITLE
CEFSHARP Get Input Value When User Clicks Inside HTML

### ISSUE THREAD

**Issue by socialpixe** [cefsharp/CefSharp#2294]
Hello,

I am running a web application using CEFSHARP, and all things are successfully running. Now i need to work something which is i am unable to find, its like:

When a user clicks a specific Button on HTML, i need to detect in my C# CEFSHARP and run a C# function instant.

Example: <a href="javascript:;" id="clicked">Click Me</a>    <input field="text" id="textname"> , if user clicks "#clicked" this link i have to run a C# function instantly, where i need the text input field "#textname" value.

If its possible please let me know. 

Thanks.

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage
