### ISSUE TITLE
Please fix CefSharp 63.0.1

### ISSUE THREAD

**Issue by mohamedosama914** [cefsharp/CefSharp#2297]
![1](https://user-images.githubusercontent.com/12082147/36968325-2d71e6d4-205a-11e8-9c34-e18854ad95fa.PNG)
![capture 63 0 1](https://user-images.githubusercontent.com/12082147/36968326-2de2a9e6-205a-11e8-839f-af64ae768377.PNG)
![capture now 63 0 1](https://user-images.githubusercontent.com/12082147/36968328-2ed0f560-205a-11e8-9315-8b772d1d90e3.PNG)

**Comment by amaitland** [comment]
Please edit your issue and complete the bug report if you have an actual bug to report. The screenshots mean nothing without an explanation.

**Comment by mohamedosama914** [comment]
add CefCustomObject 
The emergence of a problem
Is not compatible with  CefSharp 63.01

**Comment by amaitland** [comment]
Please fill out the bug report. Your description means nothing to me.

**Comment by amaitland** [comment]
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Without a full bug report this will be closed.

**Comment by amaitland** [comment]
I can only assume you are having problems with the JavaScript binding, for which much has changed. Read the documentation at https://github.com/cefsharp/CefSharp/issues/2246
