### ISSUE TITLE
pass Array from c# to javascript

### ISSUE THREAD

**Issue by habilasabila** [cefsharp/CefSharp#2298]
How to pass an **Array of objects**  from C# to javascript?

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
Have a look at BindingTest.html in the source for examples of the current features.
