### ISSUE TITLE
Strange forms focus/behaviour after tooltip on title attribute

### ISSUE THREAD

**Issue by a-carvallo** [cefsharp/CefSharp#2299]
Hello, I have a little issue with forms focus/behaviour whenever I mouse over an element with a `title` attribute in a CefSharp browser form:

- **What version of the product are you using?**
    - Nuget 63.0.1

- **What architecture x86 or x64?**
   - x64 (also happens with x86 build)

- **On what operating system?**
    - Win7, Win 8.1, but **not** Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
   - WinForms

- **What steps will reproduce the problem?**
    - Based on my fork : https://github.com/a-carvallo/CefSharp.MinimalExample
    - When launching click the 2 buttons, one opens a blank form, the other opens the BrowserForm on google.com:
![image](https://user-images.githubusercontent.com/9554119/37022849-7ec52eb8-2124-11e8-9df9-89c56f42bec3.png)

    - Place the blank form over the main form, you can click on its title bar then on the main form (the one with the 2 buttons) and the focus will behave correctly
   - Then in the browser form, place your mouse over the apps icon: 
![image](https://user-images.githubusercontent.com/9554119/37021226-25fae534-211f-11e8-9d86-85a5ffa0b26f.png)
   - The `title` attribute of the element will show the tooltip as "Google apps"
   - Now repeat the step from before, click the title bar of the blank form, the main form will be placed over it, and when clicking it the blank form will come back in front, and so on...

- **What is the expected output? What do you see instead?**
   - The blank form shouldn't go behind the main form when clicking its title bar, and clicking in the main form shouldn't bring the blank form in front of it.

- **Please provide any additional information below.**
    - This happens as soon as you mouse over an element with a `title` attribute (even if the tooltip isn't shown when `Microsoft.Windows.Common-Controls` isn't in the app.manifest)

- Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
  - Nope

- Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
  - Not really I think

- **Does this problem also occur in the `CEF` Sample Application from**
    - Didn't reproduce with popup/new window (but it's not exactly the same case as the one in my CefSharp forked example)
   - Tested with cef_binary_3.3282.1742.g96f907e_windows64_client.tar.bz2

**Comment by amaitland** [comment]
What happens if you set `browser.FocusHandler = null;`?

**Comment by a-carvallo** [comment]
Hi, thanks for the answer, unfortunately this doesn't solve the problem, I don't see a different behaviour compared to before.

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/wiki/General-Usage#multithreadedmessageloop

It's not uncommon for there to be a disconnect between the browser control during to it's message loop. Might be worth trying. 

Past that I have no idea.

**Comment by amaitland** [comment]
Closing due to lack of feedback. As this works correctly on `Win10`, it seems unlikely that it's a issue with `CefSharp`.

**Comment by a-carvallo** [comment]
Hey !

I recently upgraded to version 71.0 (yes I should have upgraded more often), and it seems to have fixed the issue !
Also potentially fixed another issue I had with a `EvaluateScriptAsync` task which would stay with the status `WaitingForActivation` (could have been a deadlock).

So thank you for your work !
