### ISSUE TITLE
How to download when the picture file is open，WinForms

### ISSUE THREAD

**Issue by JackChen1866** [cefsharp/CefSharp#2304]
Hello, How to download when the picture file is open

What version of the product are you using?

Nuget 63.0
What architecture x86 or x64?

x64 (also happens with x86 build)
On what operating system?

Win7, Win 8.1, but not Win10
Are you using WinForms, WPF or OffScreen?

WinForms
What steps will reproduce the problem?

**Comment by merceyz** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).
