### ISSUE TITLE
Deploy Error on some machines

### ISSUE THREAD

**Issue by crisleiria** [cefsharp/CefSharp#2310]
I have made some tests with no problems on my developer machine.
I have tried to deploy on 5 windows 10 machines ( This error is the Example app ), and on 4 of them I have 2 errors on windows events:

> Nome da aplicação com falha: BrowserApp.exe, versão: 1.0.0.0, carimbo de data/hora: 0x5aa11d08
Nome do módulo com falha: KERNELBASE.dll, versão: 10.0.16299.248, carimbo de data/hora: 0x13ae3814
Código de exceção: 0xe0434352
Desvio de falha: 0x001008c2
ID do processo com falha: 0x2060
Hora de início da aplicação com falha: 0x01d3b9e64ce83ffd
Caminho da aplicação com falha: C:\PPSV3\BrowserApp.exe
Caminho do módulo com falha: C:\WINDOWS\System32\KERNELBASE.dll
ID do Relatório: 9473ee53-7adc-4d8f-a1f0-cfeae4e8e58c
Nome completo do pacote com falha: 
ID da aplicação relativa ao pacote com falha: 

> Aplicação: BrowserApp.exe
Versão do Framework: v4.0.30319
Descrição: O processo foi terminado devido a uma excepção não processada.
Informações da Excepção: System.IO.FileNotFoundException
   em BrowserApp.App.OnStartup(System.Windows.StartupEventArgs)
   em System.Windows.Application.<.ctor>b__1_0(System.Object)
   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   em System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   em System.Windows.Threading.DispatcherOperation.InvokeImpl()
   em System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   em System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   em System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   em System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   em MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   em System.Windows.Threading.DispatcherOperation.Invoke()
   em System.Windows.Threading.Dispatcher.ProcessQueue()
   em System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   em MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   em MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   em System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   em System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   em MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   em MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   em System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   em System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   em System.Windows.Application.RunDispatcher(System.Object)
   em System.Windows.Application.RunInternal(System.Windows.Window)
   em System.Windows.Application.Run(System.Windows.Window)
   em System.Windows.Application.Run()
   em BrowserApp.App.Main()

Application fails to start. It seems that some requirement is missing... But I do not know that is... What I need to have installed on win 10 machine?
On my devepoler machine no problems (Visual Studio 2017 installed).

The error is the same of this link:
[https://social.msdn.microsoft.com/Forums/vstudio/en-US/ab64b530-7606-4da1-a737-271a7f36876f/wpf-application-crashing-on-startup-on-some-computers-but-not-all?forum=wpf](url)

Anyone with the same problem?

**Comment by merceyz** [comment]
Give this a read https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#Runtime_dependencies

**Comment by crisleiria** [comment]
Thanks,
VC++ 2013 x86 fixed the problem.
