### ISSUE TITLE
CefSharp Get Cookies for Multiple Instances

### ISSUE THREAD

**Issue by stkj235** [cefsharp/CefSharp#2312]
I have a C# application where I open up many cefsharp.offscreen browser instances and after a specific event occurs in that browser instance, I need to use the cookies from that browser in a visible browser in another programming language/use them in a visible browser in C# (I usually do this by writing the cookies to a file).

I have looked at using settings.CachePath and getting the cookies from there but that appears to only have 1 cookie file, whereas I would need the cookies for specific instances but at multiple occasions.

I also tried:

```
class webview_cookies : ICookieVisitor
    {
        public bool Visit(Cookie cookie, int count, int total, ref bool deleteCookie)
        {
            Console.WriteLine(cookie.Name +" = " +  cookie.Value);
            return true;
        }
    }
```

But I got the error "'webview_cookies' does not implement interface member 'IDisposable.Dispose()'"

I have looked through all the other questions on GitHub and StackOverflow and tried the code from there but all of them threw similar errors. I saw a few promising articles on magpcss.org/ceforum/ however their website appears to be down.

Please let me know if what I am trying to do is possible (in other languages it is very simple and can be done in 1 line!). Thanks

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/wiki/General-Usage#request-context-browser-isolation

There are extension methods that make dealing with cookies easier see http://cefsharp.github.io/api/63.0.0/html/T_CefSharp_CookieManager.htm
