### ISSUE TITLE
schemehandler request headers

### ISSUE THREAD

**Issue by ray007** [cefsharp/CefSharp#2313]
I'm using a scheme handler to serve my js app to the browser control, but unfortunately the Request headers do not include `Accept-Encoding`. So I can't serve `.jsz` or `.cssz` files.
Is this not supported or did I miss a setting?

**Comment by amaitland** [comment]
I've not seen any setting, best to ask on http://magpcss.org/ceforum/index.php

**Comment by cztomczak** [comment]
I guess Accept-encoding is a header specific to HTTP protocol (along with POST type request etc). When using scheme handler you won't get features of HTTP protocol. If you need it to behave like a HTTP protocol then you should instead use CefRequestHandler::GetResourceHandler and serve requests from a custom domain.

**Comment by amaitland** [comment]
Official response is that gzip is not supported. 

http://magpcss.org/ceforum/viewtopic.php?f=6&t=10967#p37770
