### ISSUE TITLE
Form.Activated event never fired again

### ISSUE THREAD

**Issue by lowph** [cefsharp/CefSharp#2314]
hi, I find a bug in winform.
My English is not good,SORRY!
step:
1. add ChromiumWebBrowser in a form. then form named  Form1
2. add "Form1.Controls.Clear()" code in Form1.Deactivate event.
3. open Form1 as Modeless in Form2.
4. then,click Form2.( Form2 Active, form1 Deactivate)
5. No matter how I do it, Form1.Activated event never fired again.

**Comment by merceyz** [comment]
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Fork the https://github.com/cefsharp/CefSharp.MinimalExample project and provide an example that reproduces your problem.

**Comment by amaitland** [comment]
Closing due to lack of feedback.
