### ISSUE TITLE
BindingTestSingle.html missing in 63 branch

### ISSUE THREAD

**Issue by trivalik** [cefsharp/CefSharp#2315]
In branch 63 is the file "CefSharp.Example/Resources/BindingTestSingle.html" missing.

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/blob/cefsharp/63/CefSharp.Example/Resources/BindingTestSingle.html

The automated build is passing, perhaps you have an invalid checkout?

Closing as I see no signs of a problem.
