### ISSUE TITLE
Initialize freezes 

### ISSUE THREAD

**Issue by DawgZilla** [cefsharp/CefSharp#2316]
Hello,

I have a problem with the cefsharp package,

Everything´s working good in debug mode... But when I create a build to install and launch the application, it will freeze with no error message...

```
public Form1()
{
    Instance = this;
    InitializeComponent();
    MessageBox.Show(Cef.Initialize(new CefSettings()).ToString());
}
```

this is how I initialize the client.
libcef, libEGL, libGLESv2 and icudtl.dat are included into my project...
I have experienced same issues with geckofx. 

Neither x86 nor x64 fix this issue and I can´t find a way to this issue.
Any suggestions?

*
Windows 10
VcRedist 2013 x64/x86 installed
visual studio 2017
offscreen

Thanks in advance

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/wiki/Output-files-description-table-%28Redistribution%29

Please read https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage
