### ISSUE TITLE
Cannot keep the persistent data (navigator.storage.persist) and the quota can't be increased

### ISSUE THREAD

**Issue by egeozcan** [cefsharp/CefSharp#2317]
- **What version of the product are you using?**
v63.0.2

- **What architecture x86 or x64?**
x86

- **On what operating system?**
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms

- **What steps will reproduce the problem?**
Implement IRequestHandler.OnQuotaRequest and accept the requests by calling the callback with true asynchronously and return true, register the handler, from js call navigator.storage.persist.then(console.log). It logs "false". Also trying the request quota (navigator.webkitPersistentStorage.requestQuota) seems to grant the quota (returns max 10GB but that's enough, and the callback is called) but in the "Clear storage" section of the application tab under the dev tools, the quota is not increased (stays at ~100 MB)

- **What is the expected output? What do you see instead?**
I'd expect the quota to be increased

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
navigator.webkitPersistentStorage.requestQuota(10 * 100000000 * 999999, console.log) logs 0. So, yes.

Tested with http://opensource.spotify.com/cefbuilds/cef_binary_3.3325.1746.ge81cdf2_windows32_client.tar.bz2

**Comment by amaitland** [comment]
> If you can reproduce the problem with cefclient then you'll need to report the bug on https://bitbucket.org/chromiumembedded/cef/overview there is no point opening an issue here. (Make sure you search before opening an issue)

Similar report at http://magpcss.org/ceforum/viewtopic.php?f=6&t=15327
You'll have to follow up with the CEF project.

**Comment by goldengrisha** [comment]
Have you had any luck ?

**Comment by egeozcan** [comment]
@goldengrisha no, I stayed in the previous version (57) which didn't have this issue

**Comment by memarko** [comment]
It is still the same problem in 98.1.19

**Comment by amaitland** [comment]
If you have correctly set a CachePath then you'll need to follow up on the ceforum post linked above.
