### ISSUE TITLE
DoModal() - Keyboard input does not work

### ISSUE THREAD

**Issue by danielh1989** [cefsharp/CefSharp#2318]
- **What version of the product are you using?**
Nuget 63.0.2

- **What architecture x86 or x64?**
Tried both x86 and x64

- **On what operating system?**
Win7, Win10,

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
I hosted the WPF control inside a CView. This CView is part of a CDialog which is displayed with DoModal(). Call a index.html with a input-filed with "Text" prefilled. I can use the backspace to remove "Text" but I can not type-in any other character.

- **What is the expected output? What do you see instead?**
Expected: I can type-in character into a input field.
Instead: Charcters are not printed in input-filed
- **Please provide any additional information below.**
I implemented my own IKeyboardHandler for dbugging. When I hit the backspace, only OnPreKeyEvent is called. When I hit any other character, the OnKeyEvent is called

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
Yes

**Comment by amaitland** [comment]
Unlikely this is a bug in CefSharp. Modal dialogues behave differently when it comes to message loop handling. See https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/sharing-message-loops-between-win32-and-wpf

I'm assuming you are using an MFC application. This that isn't a  typical use case for the WPF control and SS such is not tested during development. 

For background see https://github.com/cefsharp/CefSharp/wiki/General-Usage#wpf-1
Keyboard events are forwarded using https://github.com/cefsharp/CefSharp/blob/cefsharp/63/CefSharp.Wpf/Internals/WpfKeyboardHandler.cs

**Comment by amaitland** [comment]
Closing due to lack of feedback.
