### ISSUE TITLE
build.ps1 

### ISSUE THREAD

**Issue by trivalik** [cefsharp/CefSharp#2319]
In file "build.ps1" is the assembly version for every branch not properly updated. Means if you build with the build batch, version number is just 63.0.0 instead of 63.0.2
Also I found no way to give the "-File" argument the version number. I changed for me local to "-Command" to make it work.

**Comment by amaitland** [comment]
> In file "build.ps1" is the assembly version for every branch not properly updated. Means if you build with the build batch, version number is just 63.0.0 instead of 63.0.2

The official builds are done via `AppVeyor` and the version number is set based on the tag. You will have to manually specify the number.

> Also I found no way to give the "-File" argument the version number. I changed for me local to "-Command" to make it work.

Run `.\build.ps1 -Version 63.0.2` from a powershell command prompt. The `build.bat` file was added by someone else and isn't actively used in the project. Your welcome to submit a `PR` and improve it.

In future please ask your questions on https://gitter.im/cefsharp/CefSharp#
