### ISSUE TITLE
Why in cefsharp, ajax not carry cookies

### ISSUE THREAD

**Issue by MiyamuraMiyako** [cefsharp/CefSharp#2320]
- **What version of the product are you using?**
NUGET,lastest ver.

- **What architecture x86 or x64?**
x86

- **On what operating system?**
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForm and WPF.

**Comment by MiyamuraMiyako** [comment]
console show ```Provisional headers are shown```

**Comment by jankurianski** [comment]
GitHub issues for bugs only, please ask questions on StackOverflow or Gitter.
