### ISSUE TITLE
Support MP3 Audio

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#2322]
With the expiration of the MP3 patent, MP3 codec support is planned to be included by default in Chromium 65. Therefore it will make its way into CEF. See https://bugs.chromium.org/p/chromium/issues/detail?id=746579 for details.

**Comment by amaitland** [comment]
Tested with `3.3325.1751.ge5b78a5 / Chromium 65.0.3325.181` using http://www.html5test.com/ and the browser now identifies it's self as being able to play `MP3`.

**Comment by vwmberry95** [comment]
65 has nothing to do with H264 codec support, only MP3 audio support.

**Comment by shahv14** [comment]
Thank You. I am going to build using instructions provided in below link (posted in 2015). Please refer to other blog/doc if its not valid.
https://groups.google.com/forum/#!msg/cefsharp/BJLMXl9c204/HMJlp8mZzF0J 

Thanks again.
