### ISSUE TITLE
memory increased to 2 GB and hanged browzer in some scenarios.

### ISSUE THREAD

**Issue by abhargav7** [cefsharp/CefSharp#2327]
I used minimal example for WPF and hosted a localhost:1000
I used latest version 63.0.0 OS win7 .net4.6.2 cannot downgrade it
also added
	settings.CefCommandLineArgs.Add("disable-application-cache", "1");
	settings.CefCommandLineArgs.Add("disable-session-storage", "1");
no help.
I also used Google chrome to open localhost:1000 no issue was there.

**Comment by amaitland** [comment]
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

**Comment by amaitland** [comment]
Closing due to lack of feedback. Please use the bug report template next time.
