### ISSUE TITLE
Support browser_gpu_channel_host_factory.cc(120) Failed to launch GPU process

### ISSUE THREAD

**Issue by mohamedosama914** [cefsharp/CefSharp#2329]
# CefSharp Chromium 65 
![cefsharp](https://user-images.githubusercontent.com/12082147/37758178-e9647928-2db7-11e8-810a-9c887573b809.PNG)
***

# :point_up_2: CefSharp Chromium 65.0.0-CI2547  :point_up_2:
##### `[0322/095553.493:ERROR:browser_gpu_channel_host_factory.cc(120)] Failed to launch GPU process.`
***
![browser_gpu_channel_host_factory cc capture](https://user-images.githubusercontent.com/12082147/37758087-a97ab570-2db7-11e8-957f-66199ef7af53.PNG)

**Comment by amaitland** [comment]
You will have to report your problem to the CEF project.

**Comment by amaitland** [comment]
### How do I investigate my issue further?

It's important to remember that `CefSharp` is just a wrapper around the `Chromium Embedded Project (CEF)`, the upstream [`CEF` forum](http://magpcss.org/ceforum/) is a valuable resource. Also `CEF` has it's own [Issue Tracker](https://bitbucket.org/chromiumembedded/cef/issues). Please take the time to research your own problem, including `Googling`, searching on `ceforum`, etc.

--
#### Finding more info
- Have you checked the `Debug.log` file? (Should be located in your apps executing folder by default)
- Have you googled the error message your seeing? (Don't just google the whole thing, try googling just the keywords and possibly add `chromium` as a keyword).
- Are you able to reproduce the problem using `cefclient`? (`cefclient` is the reference implementation provided by `CEF`)
- Need more help debugging? Check the [Troubleshooting Guide](https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting)
- Are you using the latest version? Check the [Release Branches](https://github.com/cefsharp/CefSharp#release-branches) table to determine if the version your using is supported. 

--
#### How do I download `cefclient`?

- Firstly identity which version of `CEF` your actually using, easiest way is to check your `packages.config` file, look for the `cef.redist.x86` package, it's version will be something like `3.2526.1362`, that's the exact version of `CEF` you'll need to download for comparison. You can also open `chrome://version` in the browser to determine the version.
- Open http://opensource.spotify.com/cefbuilds/index.html (http://cefbuilds.com for older version) in a web browser
- Locate the exact `Branch` you require, for the example above the branch is `2526`, all the versions follow a similar pattern
- Locate the `Windows 32bit` or `Windows 64bit` item, if you don't see the exact version, then click `more revisions`
- Download **Test App**
- Are you using `WPF/Offscreen` or `WinForms`? 

**This next part is key**
- To compare with WPF/OffScreen run `cefclient --multi-threaded-message-loop --off-screen-rendering-enabled`
- To compare with WinForms `cefclient --multi-threaded-message-loop`

**Comment by mohamedosama914** [comment]
(http://cefbuilds.com for older version) in a web browser

This site can’t be reached
cefbuilds.com took too long to respond.
Try:
Checking the connection
Checking the proxy and the firewall >chrome-error://chromewebdata/#buttons
Running Windows Network Diagnostics > javascript:diagnoseErrors()
ERR_CONNECTION_TIMED_OUT

**Comment by mohamedosama914** [comment]
How to use This next part is key CefSharp WinForm
To compare with WinForms cefclient --multi-threaded-message-loop
