### ISSUE TITLE
Could not load file or assembly 'CefSharp.Core.dll

### ISSUE THREAD

**Issue by preslyel** [cefsharp/CefSharp#2330]
Hello, I've got an error 
Could not load file or assembly 'CefSharp.Core.dll
when starting CefSharp.Wpf.Example (Any CPU pode) on machine

Version of the product: 63.0.2
Architecture: 64-bit
Operating system: Windows 7 Professional 64-bit (6.1, Build 7601) Service Pack 1 (7601.win7sp1_rtm.101119-1850)
Using: WPF,
Framework: 4.6.2

I've installed Microsoft Visual C++ 2017(x64), 2015(x64,x86) but still get the error.
I've tried to put libs for x64 from "Microsoft.VC140.CRT" folder into the project folder (in the root and both x64, x86 folders) and this didn't bring any results.
on Win8 machines running fine.

**Comment by amaitland** [comment]
You need VC++ 2013
