### ISSUE TITLE
Please Support Fix Any CPU  WinForm CefSharp 65 and 51 ( Failed to launch GPU process )

### ISSUE THREAD

**Issue by mohamedosama914** [cefsharp/CefSharp#2331]
Please Support Fix only open 
Any CPU `(X64-Bit) - (X32-Bit)`
Chromium WinForm CefSharp 65 and 51 
`Support Any CPU WinForm CefSharp 65 and 51`
2329  [ browser_gpu_channel_host_factory.cc(120) ] Failed to launch GPU process 
![failed to launch child process](https://user-images.githubusercontent.com/12082147/37772320-e66cef90-2de2-11e8-941b-8e644248e076.PNG)

`[0322/095553.493:ERROR:browser_gpu_channel_host_factory.cc(120)] Failed to launch GPU process.`

**Comment by amaitland** [comment]
> 2329 [ browser_gpu_channel_host_factory.cc(120) ] Failed to launch GPU process

This is a `Chromium` error and will need to be raised on `ceforum` after  testing with the `Sample Application. You've already been provided with detailed information on how to perform that testing.

> Chromium WinForm CefSharp 65 and 51

This makes no sense? The current supported version is `63.0.2`. You can test with the `MinimalExample`.
https://github.com/cefsharp/CefSharp.MinimalExample/tree/demo/anycpu
https://github.com/cefsharp/CefSharp.MinimalExample/tree/demo/anycpuprefer32bit

Without a proper bug report this will be closed.

**Comment by mohamedosama914** [comment]
Please Support Fix only open  I Am use x32-Bit
Chromium WinForm CefSharp 65.0.0-CI2547 Support  x32-Bit Perform 

[0330/152048.096:ERROR:browser_gpu_channel_host_factory.cc(120)] Failed to launch GPU process.
[0330/152051.218:ERROR:browser_gpu_channel_host_factory.cc(120)] Failed to launch GPU process.
[0330/152051.234:ERROR:gpu_process_transport_factory.cc(1029)] Lost UI shared context.
[0330/152057.430:ERROR:service_manager_context.cc(252)] 
Attempting to run unsupported native service: 
E:\Program Files\Git\bin\Projects\ChromiumApplication\32-Bit Debug\content_renderer.service.exe

**Comment by mohamedosama914** [comment]
Please Support Perform Failed to launch GPU process  service_manager_context.cc(252)]
Attempting to run unsupported native service: content_renderer.service.exe

**Comment by mohamedosama914** [comment]
CefSharp 63.0.3 (32-bit)

Perform Please Support fix
[0331/132238.281:INFO:chrome_scheme_handler.cc(536)] 
Reguest for unknown chrome resource: chrome://invalid/

[0331/132244.240:WARNING:extension_protocols.cc(477)] 
Failed to GetPathForExtension: invalid

[0331/132244.255:WARNING:url_request_job_manager.cc(90)] 
Failed to map: chrome-extension://invalid/

**Comment by amaitland** [comment]
It's important to note that `CefSharp` is just a wrapper around the `Chromium Embedded Framework (CEF)`. Closing this as `upstream` and `wontfix` as changes need to be made in `CEF`. 

The `CEF` project has it's own issue tracker located at https://bitbucket.org/chromiumembedded/cef 

Before opening a new issue you should:

- Search open/closed issues to determine if the problem you are seeing has already been reported
- Test with a newer version if available, see https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-chromium-embedded-frameworkcef for details on testing with the `cefclient` reference application
