### ISSUE TITLE
By installing CefSharp.WinForms via `nuget` **all** referenced assemblies become invalid

### ISSUE THREAD

**Issue by al1b** [cefsharp/CefSharp#2335]
- **What version of the product are you using?**
63.0.2

- **What architecture x86 or x64?**
I tested on **AnyCPU**, **x86** and **x64**
- **On what operating system?**
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
CefSharp.WinForms

- **What steps will reproduce the problem?**
By installing CefSharp.WinForms via `nuget` **all** referenced assemblies become invalid.

**Comment by al1b** [comment]
My target framework was set to `4.6.1`. I've changed it to `4.5.2` and it seems it does not have that problem any more.

Why it doesn't work with **4.6.x** ?

**Comment by amaitland** [comment]
What version of `.Net` are you targeting?

What version of `Visual Studio` are you using?

**Comment by al1b** [comment]
@amaitland 
I was targeting `4.6.1` , I think CefSharp is now only works with `4.5.2`, am I wrong?
Because by re-targeting the project to `4.5.2` everything works fine.

`Visual Studio` Version:
Visual Studio 2017 **15.5.4**

**Comment by amaitland** [comment]
> I was targeting 4.6.1 , I think CefSharp is now only works with 4.5.2, am I wrong?

It does target `4.5.2`, that means you can use any higher `.NET` version though. So that shouldn't be a problem.

Switching to the newer `Nuget` restore method usually solves most of the package related problems http://www.xavierdecoster.com/migrate-away-from-msbuild-based-nuget-package-restore

**Comment by al1b** [comment]
I will give it a try and I will let you know

**Comment by Dj-rEPKa** [comment]
As they told in ReadMe, u need to re-open VS and ur project!
"After installing the `Nuget` package we recommend closing Visual Studio completely and then reopening (This ensures your references show up and you have full intellisense)."

**Comment by MaBo20** [comment]
I had the same issue as al1b described before...

I could solve it with the following steps:
- Set target framework to `.NET Framework 4.5.2`
- install CefSharp Version 39.0.0 by using the Package Manager with this command: `Install-Package CefSharp.Wpf -Version 39.0.0` 
- Set platform target to `x64`
- close the solution
- open the solution
- rebuild
- upgrade to latest version
- rebuild

I am using VS2013 and CefSharp.WPF

**Comment by amaitland** [comment]
Using a very old version and upgrading should be totally unnecessary. Just use the newer Nuget restore method. Closing and reopening the solution may also help. 

Make sure you have the latest Nuget version installed and visual studio is patched. 

It's possible to make further improvements to the Nuget packages, this would however require targeting Nuget 3.0 and effectively remove support for VS2013. In my experience this isn't a show stopper and is usually pretty easy to resolve, so leaving as is for now.
