### ISSUE TITLE
Crash on method OnBeforeCommandLineProcessing() when there is Switch parameters without value

### ISSUE THREAD

**Issue by shayOH** [cefsharp/CefSharp#2341]
- **What version of the product are you using?**
    CefSharp-master
     
- **What architecture x86 or x64?**
x86
- **On what operating system?**
  Win10
- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms/ OffScreen
- **What steps will reproduce the problem?**
CefSharp crash on method 
_"virtual void OnBeforeCommandLineProcessing(const CefString& process_type, CefRefPtr<CefCommandLine> command_line)"_

on line " commandLine->AppendSwitchWithValue(name, value);"

When the argument is "Swith" (without value).
In this case the value parameter is null.

We configure the CefSettings value for switch as: String.Empty 
when calling Cef.Initialize(settings, false, new BrowserProcessHandler()))

On the released versions 63.2,63.3 this problem is not reproduced and it seems that the default value is 1 in case of the parameter is switch.

   
- **What is the expected output? What do you see instead?**

- **Please provide any additional information below.**
    
    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
No
    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

**Comment by amaitland** [comment]
`Pulls Requests` welcome 👍 Seems like a excellent candidate for the newly added `Good First Issue` label
