### ISSUE TITLE
CefSharp 63.0.3 (32-bit) Perform Please Support fix   chrome://invalid/

### ISSUE THREAD

**Issue by mohamedosama914** [cefsharp/CefSharp#2343]
:sob: :sob: :sob:  
# Perform Please Support fix

## Failed to map: chrome-extension://invalid/

#1745 #1512 #2341  #1803

**Comment by amaitland** [comment]
It's important to note that `CefSharp` is just a wrapper around the `Chromium Embedded Framework (CEF)`. Closing this as `upstream` and `wontfix` as changes need to be made in `CEF`. 

The `CEF` project has it's own issue tracker located at https://bitbucket.org/chromiumembedded/cef 

Before opening a new issue you should:

- Search open/closed issues to determine if the problem you are seeing has already been reported
- Test with a newer version if available, see https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-chromium-embedded-frameworkcef for details on testing with the `cefclient` reference application.

If you do find an existing issue that matches this one or create a new one then post a link here for others to follow.
