### ISSUE TITLE
Websocket Handle (WSS)

### ISSUE THREAD

**Issue by wurucu** [cefsharp/CefSharp#2346]
How i can handle websocket ?
I need to send and receive packet from c# code behind.
Thank you. Sorry my english.

**Comment by amaitland** [comment]
There is no specific functionality in `CEF`, see http://magpcss.org/ceforum/viewtopic.php?f=6&t=15034

This issue tracker is for bug reports only, thank you!

**Comment by sanjaykulkarni04** [comment]
@amaitland  **OnBeforeResourceLoad** unfortunately is not raised/called for WebSocket requests in custom ResourceRequestHandler. Can anyone please assist me? here is the sample code - 

`private sealed class BearerAuthResourceRequestHandler : ResourceRequestHandler
        {
            readonly IAuthenticationCredentials credentials;

            public BearerAuthResourceRequestHandler(IAuthenticationCredentials credentials)
            {
                this.credentials = credentials;
            }

            protected override CefReturnValue OnBeforeResourceLoad(IWebBrowser chromiumWebBrowser, IBrowser browser, IFrame frame, IRequest request, IRequestCallback callback)
            {
                if (!string.IsNullOrEmpty(credentials.AccessToken))
                {
                    var headers = request.Headers;
                    headers["Authorization"] = $"Bearer {credentials.AccessToken}";
                    request.Headers = headers;
                    //request
                    return CefReturnValue.Continue;
                }

                return base.OnBeforeResourceLoad(chromiumWebBrowser, browser, frame, request, callback);
            }
        }`

**Comment by amaitland** [comment]
> **OnBeforeResourceLoad** unfortunately is not raised/called for WebSocket requests in custom ResourceRequestHandler

Intercepting `Websocket Requests` is not currently supported via `ResourceRequestHandler`.

In theory you can access at least some of the `WebSocket` data via `DevTools` protocol.

https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-webSocketClosed

This is not something I've tested, not do I have an example. Generic details on using `DevTools` directly are at https://github.com/cefsharp/CefSharp/issues/3165

**Comment by sanjaykulkarni04** [comment]
Thank you @amaitland. Will see and try.

My requirement is, I would like to inject the **JWT token** (received from the identity server) in the header and pass the same to graphql server to authenticate the request.
