### ISSUE TITLE
Content not rendering & Browser not initialized in CefSharp WPF in 63.0.0 Version

### ISSUE THREAD

**Issue by Arunkumar-Murugesan** [cefsharp/CefSharp#2347]
Hi Team,

I have upgraded the CefSharp version from 45.0.0 to 63.0.0 to avoid the High DPI rendering issue into WPF project. After upgraded, the content was not rendering in the browser. It showing as empty and the browser not being initialized.

Please find the configuration details,

WPF .Net framework version | 4.5.2
-- | --
Machine resolution | 1920 * 1080
CefSharp Version | 63.0.0
Package | Nuget
Platform Architecture | X86
Operating System | Win 10

**Issue Details**

- I have created simple sample with button and CefBrowser in the window. When we click "Load", the HTML content loaded in the same window. It is working fine.

![image](https://user-images.githubusercontent.com/20086495/38419651-e2077fb4-39be-11e8-9a6c-6d1ccd7e9050.png)

But whenever we try to load the HTML event in another window, the browser not being initialized and the content not rendering.

**Sample Steps**

1. Keep the "Load" button in one window
2. Keep the CefBrowser in another window
3. If we click "Load" from the first window, the HTML content should be loaded in the second window. Here the browser not being initialized and the content not rendering

I have created and committed the sample in the repository. Could you please check this sample and suggest me how we have to resolve the issue? Is there any other reason for content not rendering? Even sometimes the browser has been initialized but content not rendering in the browser.

How could we initialized the browser. Some times only it comes true.

**Branch Name :** CefSharp_WpfSample_63.0.0

![image](https://user-images.githubusercontent.com/20086495/38419926-d06f7dbe-39bf-11e8-9401-52963698f7b7.png)

Could you please provide us the solution to resolve this problem?

Please let me know the concerns if any.

Regards,
Arunkumar Murugesan

**Comment by amaitland** [comment]
Please stop opening issues for this, your attached property implementation is incorrect, I've **already** provided an example of what the attached property should look like. 

Dulicate of https://github.com/cefsharp/CefSharp/issues/2260

**Comment by amaitland** [comment]
Please don't open another issue, ask your questions on Gitter.

**Comment by amaitland** [comment]
If you need help with the data binding/xaml aspect of programming the ask on https://stackoverflow.com/questions/tagged/cefsharp

**Comment by Arunkumar-Murugesan** [comment]
@amaitland : This sample binding property working fine only. I made mistakes in binding for this issue task only https://github.com/cefsharp/CefSharp/issues/2260. But this sample, the binding working fine with normal text block. In CefBrowser only it is not binding. Did you checked this sample?

**Comment by amaitland** [comment]
I've looked at your example and it doesn't handle the browser initializing correctly, as I've already suggested you should use https://gist.github.com/amaitland/ddf0905072b00ebbe29e1c0e1031c4c6

**Comment by Arunkumar-Murugesan** [comment]
@amaitland : I have applied the codes you given. But still it is not loading. I just put the break point under the IsBrowserInitialized codes. But IsBrowserInitialized not comes in true. I have committed this changes also in the sample.

![image](https://user-images.githubusercontent.com/20086495/38554485-670a69aa-3ce0-11e8-8dbe-38a6d55ec2b5.png)

Is there anything I need to change? Could you please check this case?

**Comment by Arunkumar-Murugesan** [comment]
@amaitland : Could you please check this issue in this sample?

**Comment by Arunkumar-Murugesan** [comment]
Could you please anyone check this issue and update us? Let us know if anything we made it wrong. We used the same method as you given. But still it is work. Please check with this.

**Comment by amaitland** [comment]
@Arunkumar-Murugesan Is it really necessary to post every day? This behavior is **extremely** annoying.

The `ChromiumWebBrowser` control will only initialize the underlying browser when both it's `ActualWidth` and `ActualHeight` are greater than `0`. Your example fails to meet this condition. In your case specifying ` HorizontalAlignment="Center"` without setting an explicit `Width` will result in an `ActualWidth` of `0`.

**Comment by xiangzLL** [comment]
hi Arunkumar Murugesan， is this issue has any solve methods? i also meet up this issue
