### ISSUE TITLE
Is it possible to use a CEF UI thread per browser instance?

### ISSUE THREAD

**Issue by fvanheeswijk** [cefsharp/CefSharp#2348]
In our application we are migrating from the .NET WebBrowser control to this ChromiumWebBrowser control and we have existing functionality that blocks during the execution of event handlers. This worked fine for us, even when multiple webbrowsers were open in the same application.

Now when implementing the ChromiumWebBrowser we found that all events from all webbrowsers share the same thread that executes the webbrowser events. This is not what we are looking for as we want to decouple the webbrowser instances such that they cannot influence eachother and we would also like to have the ability to execute blocking code in the event handlers, just as it used to be.

Now I have found your documentation on https://cefsharp.github.io/api/63.0.0/html/E_CefSharp_Wpf_ChromiumWebBrowser_LoadingStateChanged.htm which mentions that "It's important to note this event is fired on a CEF UI thread, which by default is not the same as your application UI thread.".

My question is: Is it possible to have multiple CEF UI threads? I'm asking this because in the documentation it is mentioned that it will be executed on "a thread" and not "the (only) thread", so I'm having some hope that there are possibilities. Ideally we'd want a CEF UI thread per webbrowser instance.

I'm more than happy to provide additional information if required, but I hope that I have shared enough information such that you can answer this question.

**Comment by amaitland** [comment]
https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage#markdown-header-threads

No it's not possible. You also cannot write blocking code without blocking the browser, it's designed to be asynchronous. 

CEF has it's own forum at http://magpcss.org/ceforum/index.php

CefSharp is just a wrapper.
