### ISSUE TITLE
Cannot download gifs by javascript using CefSharp

### ISSUE THREAD

**Issue by raulfmiranda** [cefsharp/CefSharp#2351]
I am using CefSharp to get some data (text, images, files) from a web application that is a messenger. I am already getting text and downloading images (from a blob url contained inside the img tag src) correctly but I couldn't download gifs. The difference between the process of downloading an image and the process of download a gif is that the image is loaded automaticaly on the page and gif is not. A gif is a video tag that has a blob url inside the src attribute only after be loaded, so if it is not clicked to be loaded it doesn't have this blob url information. So, to download the gif I must click on the gif html element by javascript and after that I run a script to download that gif, while images needs only to be downloaded by the script (without a previous click) because they are already loaded on the page. But some process is stopping the gif loading because the scripts clicks on gif element, it starts to be loaded but after a while this process is stopped. **Is CefSharp stopping this gif loading process?** 

Script to click on the gifs nodes:

```
document.querySelectorAll('._19mFZ')
	.forEach(function (node){
		node.click();
	});
```

Script to download the gif:

```
function addElement(blobID, fileName) {
	var p = document.getElementsByTagName('body')[0];
	var newElement = document.createElement('a');
	newElement.setAttribute('href', blobURL + blobID);
	newElement.setAttribute('download', fileName);
	newElement.setAttribute('id', blobID);
	p.appendChild(newElement);
}

function removeElement(blobID) {
	var element = document.getElementById(blobID);
	element.parentNode.removeChild(element);
}

function downloadBlob(blobID, fileName) {
	addElement(blobID, fileName);
	var el = document.getElementById(blobID);
	el.click();
	removeElement(blobID);
}
```

**Comment by amaitland** [comment]
How does Chrome behave? Unlikely this is a bug in CefSharp, it's just a wrapper.

**Comment by raulfmiranda** [comment]
The script worked correctly with Chrome, but it didn't work with CefSharp. The gifs are automatically loaded with Chrome so I don't need to click on them. But it doesn't work with CefSharp. The behave is different. Is CefSharp using a different Chrome version or anything like that? Can I change the CefSharp browser?

**Comment by amaitland** [comment]
What version of Chrome did you use?

**Comment by jankurianski** [comment]
Can you create a reproducible example that can be tested with `cefclient`, which is pure CEF (closer to Chromium than CefSharp)? (Read the issue template to find out how to download and runit.)

**Comment by amaitland** [comment]
Obviously you are comparing two different versions. As @jankurianski says you should test with cefclien. Unlikely this is a CefSharp bug as it's just a wrapper. 

https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-chromium-embedded-frameworkcef

**Comment by amaitland** [comment]
If this works in `cefclient` and not in `CefSharp` (with exactly the same version), then this can be reopened. Marking as `upstream` as likely needs to be fixed in `CEF`  (Upgrading to a newer version may resolve the problem).
