### ISSUE TITLE
Cross-origin plugin content from  must have a visible size larger than 400 x 300 pixels, or it will be blocked. Invisible content is always blocked.

### ISSUE THREAD

**Issue by x2031** [cefsharp/CefSharp#2352]
Hello there
   I found a problem when using the demo builder.
How can I make the browser display the blocked flash?

-====The URL for the problem is http://mgc.qq.com/====
-----------------------------------------------
**I see other people ask but there is no solution available**
https://stackoverflow.com/questions/47364531/chrome-cross-origin-plugin-content-from-must-have-a-visible-size-larger-than-40

**Comment by amaitland** [comment]
Issue tracker for bug reports only, thank you!

**Comment by amaitland** [comment]
As a final comment, as this is a Chromium behavior you'd be best to ask the Chromium developers for advice.
