### ISSUE TITLE
Please how to Get Getting Cefsharp winforms TabControl

### ISSUE THREAD

**Issue by mohamedosama914** [cefsharp/CefSharp#2355]
# NET Framework Version = v4.7
# How to Add - How to Get
***
### Please Now How to Add And How to Get C# Cefsharp Winforms TabControl
c# Cefsharp Winforms TabControl - how to get popup - Popup Windows New 
c# Cefsharp Winforms TabControl - how to get favicon of visited site - favicon.ico  
##### c# Cefsharp winforms TabControl - how to get  Add New Tab Button (+) & how to get Add Cancel Tab Button (X)
c# Cefsharp winforms TabControl -  how to get Loading of visited site
c# Cefsharp winforms TabControl -  how to get BookmarksForm
c# Cefsharp winforms TabControl - how to get Add Bookmark
***
 c# Cefsharp winforms - how to get SystemMenu
 c# Cefsharp winforms - how to get ChromeDevToolsSystemMenu

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp)

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage
