### ISSUE TITLE
Please Now

### ISSUE THREAD

**Issue by mohamedosama914** [cefsharp/CefSharp#2356]
# Please Now

c# Cefsharp Winforms TabControl - how to get popup - Popup Windows New
c# Cefsharp Winforms TabControl - how to get favicon of visited site - favicon.ico
##### c# Cefsharp winforms TabControl - how to get Add New Tab Button (+) | Add Cancel Tab Button (X)
c# Cefsharp winforms TabControl - how to get Loading of visited site
c# Cefsharp winforms TabControl - how to get BookmarksForm + Add link Bookmark
c# Cefsharp winforms - how to get Cookie + CachePath
c# Cefsharp winforms - how to get SystemMenu + ChromeDevToolsSystemMenu

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
@mohamedosama914 Please stop opening issues, thank you!
