### ISSUE TITLE
chromeBrowser.Focus() is not worked and Didn't set focus on textBox using javaScript in Windows Form with CefSharp.WinForms.63.0.3

### ISSUE THREAD

**Issue by llmsjraj** [cefsharp/CefSharp#2357]
I have tried to set focus using `chromeBrowser.Focus(); ` But it didn't work.

```
bool isFocused = chromeBrowser.Focused;
                if (!isFocused)
                {
                    chromeBrowser.Focus();
                }
                isFocused = chromeBrowser.Focused; // Still false...
```
Even this i have tried to execute the JavaScript to focus on text box. it's also didn't work.

```
var setFocusScript = $"setTimeout(function() {{ document.getElementById('{emailId}').focus(); }},100);";

var re = await chromeBrowser.EvaluateScriptAsync(setFocusScript);

as well as 

chromeBrowser.ExecuteScriptAsync(setFocusScript);
```

I want to set focus on textbox. Please help me to get this done. @amaitland @perlun @ataranto

**Comment by amaitland** [comment]
Calling `Focus` will trigger `OnGotFocus` which will only set the actual focus if the underlying `CefBrowser` is initialized, it's not possible to set the focus until we have access to the `CefBrowserHost` instance (which is accessible through the `CefBrowser`)

https://github.com/cefsharp/CefSharp/blob/cefsharp/63/CefSharp.WinForms/ChromiumWebBrowser.cs#L856

Short version call `Focus()` in the `IsBrowserInitializedChanged` event (horrible name I know), make sure you check `args.IsBrowserInitialized == true`.

This is assuming you are using `MultiThreadedMessageLoop = true` which is the default.

In future, issue tracker is for bug reports only, thank you! See https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md for details.
