### ISSUE TITLE
how to Add c# Cefsharp winforms TabControl & Save As Downloading image

### ISSUE THREAD

**Issue by mohamedosama914** [cefsharp/CefSharp#2358]
Save As Download image  how to Add c# Cefsharp winforms TabControl & Save As Downloading image

[StackOverflow C# Cefsharp Winforms TabControl - how to get Save As Download image](https://stackoverflow.com/questions/49817310/how-to-add-c-sharp-cefsharp-winforms-tabcontrol-save-as-downloading-image)

Please Now

c# Cefsharp Winforms TabControl - how to get popup - Popup Windows New
c# Cefsharp Winforms TabControl - how to get favicon of visited site - favicon.ico
c# Cefsharp winforms TabControl - how to get Add New Tab Button (+) &|& Add Cancel Tab Button (X)
c# Cefsharp winforms TabControl - how to get Loading of visited site
c# Cefsharp winforms TabControl - how to get BookmarksForm + Add link Bookmark
c# Cefsharp winforms - how to get Cookie + CachePath

Custom System Menu | MyCustomChromeDevToolsSystemMenu
c# Cefsharp winforms - how to get SystemMenu + ChromeDevToolsSystemMenu

Custom Menu Handler | MyCustomMenuHandler
c# Cefsharp Winforms TabControl - how to get Save Download image + Save As Downloading image

**Comment by vwmberry95** [comment]
You need to stop asking questions and start searching.  This is a place for posting issues.
