### ISSUE TITLE
getting favicon c# winforms Add icons to web browser tabs

### ISSUE THREAD

**Issue by mohamedosama914** [cefsharp/CefSharp#2360]
TabControl
how to get favicon of visited site

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
Download the source and search for favicon. 

Please **stop** creating issues, your inability to follow simple instructions is annoying!
