### ISSUE TITLE
Good How to Add

### ISSUE THREAD

**Issue by mohamedosama914** [cefsharp/CefSharp#2361]
@Application Chromium Browser Desktop CefSharp 63.0.3 

![1](https://user-images.githubusercontent.com/12082147/38754620-e54e30d8-3f62-11e8-95ba-bba106a6c026.PNG)

> Good How to Add

c# Cefsharp Winforms TabControl - how to get popup - Popup Windows New
c# Cefsharp Winforms TabControl - how to get favicon of visited site - favicon.ico
c# Cefsharp winforms TabControl - how to get Add New Tab Button (+) &|& Add Cancel Tab Button (X)
c# Cefsharp winforms TabControl - how to get Loading of visited site
c# Cefsharp winforms TabControl - how to get BookmarksForm + Add link Bookmark
c# Cefsharp winforms - how to get Cookie + CachePath

Custom Menu Handler | MyCustomMenuHandler
c# Cefsharp Winforms TabControl - how to get Save Download image + Save As Downloading image

Custom System Menu | MyCustomChromeDevToolsSystemMenu
c# Cefsharp winforms - how to get SystemMenu + ChromeDevToolsSystemMenu

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage
