### ISSUE TITLE
Application crashes if it is launched from Windows Task Scheduler

### ISSUE THREAD

**Issue by HeiVask** [cefsharp/CefSharp#2365]
- **What version of the product are you using?**
    - Nuget (v63.0.3.0)

- **What architecture x86 or x64?**
    - x86

- **On what operating system?**
    - Windows 10, Windows Server 2016

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - WinForms

- **What steps will reproduce the problem?**
    - Running the application from the Task Scheduler (testable also with the Minimal Example).

- **What is the expected output? What do you see instead?**
    - Expected: Normal behaviour
    - Instead: The Task Manager shows the application still running, but it is freezed, with no log from the own application.

- **Please provide any additional information below.**
    - The Event Viewer shows an unhandled exception:

> Aplicación: CefSharp.BrowserSubprocess.exe
> Versión de Framework: v4.0.30319
> Descripción: el proceso terminó debido a una excepción no controlada.
> Información de la excepción: System.ArgumentException
>    en System.ThrowHelper.ThrowArgumentException(System.ExceptionResource)
>    en System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Insert(System.__Canon, System.__Canon, Boolean)
>    en System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Add(System.__Canon, System.__Canon)
>    en <Module>.CefSharp.CefAppUnmanagedWrapper.OnProcessMessageReceived(CefSharp.CefAppUnmanagedWrapper*, scoped_refptr<CefBrowser>*, cef_process_id_t, scoped_refptr<CefProcessMessage>*)
>    en <Module>.CefExecuteProcess(CefMainArgs*, scoped_refptr<CefApp>*, Void*)
>    en CefSharp.BrowserSubprocess.SubProcess.Run()
>    en CefSharp.BrowserSubprocess.Program.Main(System.String[])

- **Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)**
    - debug.log is empty

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
    - No, it doesn't. Tested with `cef_binary_3.3325.1758.g9aea513_windows32_client`

**Comment by amaitland** [comment]
How exactly is task scheduler relevant in this case? 

It's quite hard to read the stack trace, if I had to guess I'd say this is a duplicate of #2301

**Comment by HeiVask** [comment]
Sincerely I have no idea. It's relevant because executing the application directly it works (double clicking on it), but if it's executed by the task scheduler it doesn't. I've tested also with the minimal example, launched from the task scheduler it doesn't open. It runs and appears on the task manager but it's freezed.

Sorry but there is no more information than that stack trace. Not sure also if it could be a duplicate of #2301. In this case there is only one execution with one instance of a browser. I tested it on two machines with win10 and one with winserver2016 with the same result.

**Comment by amaitland** [comment]
Did you by chance happen to compare the two stack traces? There are two dictionary adds in that section of code and only one can cause that exception. Is the stack trace provided relevant to the problem you've reported?

Since your app works when run directly it's unlikely a bug in CefSharp, more likely an environment/configuration issue. Have you confirmed that the exception is generated every time?

I expect task scheduler to cause problems, mostly stemming from the current director not being set correctly, if you log Environment.CurrentDirectory what do you get?

https://stackoverflow.com/questions/447774/specifying-the-running-directory-for-scheduled-tasks-using-schtasks-exe

**Comment by HeiVask** [comment]
Effectively it was an environment configuration issue. Putting the start directory in the task window (as the so link indicates) solves the issue, so it is not a CefSharp bug. Sorry for the inconvenience and thank you very much.
