### ISSUE TITLE
When closing DevTools causes DoClose call in LifeSpanHandler in 57.0.0

### ISSUE THREAD

**Issue by arvindlloyds** [cefsharp/CefSharp#2366]
- **What version of the product are you using?**
    - 57.0.0 Nuget

- **What architecture x86 or x64?**
x64

- **On what operating system?**
    - Win7

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
In minimal example use Browser.LifeSpanHandler = new LifeSpanHandler();
Open DevTools, by clicking a button or whatever.
Close DevTools

- **What is the expected output? What do you see instead?**
 Output - Closing DevTools causes DoClose called in LifeSpanHandler
 Expected - DoClose must be called only on browser close not on DevTools.
  
  There is no way inside DoClose to differentiate whether Browser was closed or DevTools.

- **Please provide any additional information below.**
N/A

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
None

- **Does this problem also occur in the `CEF` Sample Application from 
Did not try

**Comment by amaitland** [comment]
That's the default CEF behavior. You can inspect the browser URL to determine if it's devtools.

**Comment by arvindlloyds** [comment]
url is same in both the cases, devtools or real browser.

**Comment by amaitland** [comment]
What does your code look like? The URL for devtools is definitely unique and can be checked reliably. 

See https://github.com/cefsharp/CefSharp/blob/master/CefSharp.WinForms.Example/Handlers/LifeSpanHandler.cs#L74 for an example

**Comment by arvindlloyds** [comment]
public bool DoClose(IWebBrowser browserControl, IBrowser browser)
            {

                Application.Current.Dispatcher.BeginInvoke((Action) (() =>
                {
                    var address = browserControl.Address;
                }));
                    return true;
            }
Address values are same when closing DevTools or closing main browser.

**Comment by arvindlloyds** [comment]
resolved, thank you for the help.
