### ISSUE TITLE
CefSharp not woking on Windows 7 32 bit, even if all prerequisites are installed.

### ISSUE THREAD

**Issue by anant-verma** [cefsharp/CefSharp#2368]
Hi Team,

I have downloaded cefsharp3 63 version from  GitHUb, compiled on windows 10 64 bit development machine, in release mode for win 32 and x64 configuration. It runs on my development machine without any error.

When the same is run on windows 7, 32 bit and 64 bit version, it fails. 

I have 
.Net framework 4.5.1
.Net framework 4.5.2 
Microsoft VC++ 2010 redisrtributable (resp. for 32 and 64 bit)
Microsoft VC++ 2012 redisrtributable(resp. for 32 and 64 bit)
Microsoft VC++ 2013 redisrtributable(resp. for 32 and 64 bit)
Microsoft VC++ 2015 redisrtributable(resp. for 32 and 64 bit)

But still not getting the run the cefsarp.Winforms.Example exe. PLease help its really urgent. I have read mostly all the articles related the Kernelbase.dll error. As this is the error which gets logged in windows eventvierwer.

**Comment by amaitland** [comment]
Building from `source` is not recommended, you should use https://github.com/cefsharp/CefSharp.MinimalExample for testing purposes.

If you are using the `master` branch then it will have different requirements, the examples there require `.Net 4.6.2`, the core project will still remain as `.Net 4.5.2` for now though.
