### ISSUE TITLE
SerializeV8SimpleObject performance question

### ISSUE THREAD

**Issue by drewnoakes** [cefsharp/CefSharp#2370]
Looking at the current master (9eb19756ac8791f3bc716629d9a01a0f8d6c5990):

https://github.com/cefsharp/CefSharp/blob/9eb19756ac8791f3bc716629d9a01a0f8d6c5990/CefSharp.Core/Internals/Serialization/V8Serialization.cpp#L28-L36

Here a `Stack` is used to (presumably) prevent infinite loops when object graphs contain cycles. via the `seen` parameter.

The only operations called on this type are `Push` and `Contains`.

A `HashSet` would have better performance here, swapping O(N) for O(1) on the `Contains` test.

**Comment by amaitland** [comment]
Sounds reasonable :+1:

**Comment by drewnoakes** [comment]
I missed a usage of `Stack.Pop` at the end of the `SerializeV8SimpleObject` method. This means that the stack should only contain the current object and its ancestors. So unless there are very deep object graphs, the N should be so low that changing from `Stack` to `HashSet` probably has no real world impact.

Created a PR all the same.
