### ISSUE TITLE
How to get Cefsharp Cookies as string ?

### ISSUE THREAD

**Issue by EezeSolutions** [cefsharp/CefSharp#2371]
Is there a way we can simply get all the cookies as string like we normally do in a Webrowser or Watin brwoser ?

Thank you

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp)

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/blob/1b00c277b8ebecefec96d887fdee38f995dca2a8/CefSharp.Example/Handlers/BrowserProcessHandler.cs#L49 for one example.

The API doc is http://cefsharp.github.io/api/63.0.0/html/T_CefSharp_CookieManager.htm
