### ISSUE TITLE
What are the ways to make CefSharp support proprietary audio and video formats?

### ISSUE THREAD

**Issue by raulfmiranda** [cefsharp/CefSharp#2374]
I am trying to see videos (.mp4) that are shown by a video html5 tag. I've found this information: _[CefSharp is based on CEF which is based on Chromium. Chromium does not support proprietary audio and video formats only Google Chrome does_. _If you need proprietary codec support you need to build CEF/Chromium on your own. There are no plugins/extensions which enable this functionality](https://stackoverflow.com/questions/49141848/cefsharp-browser-video-wont-play?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)_.

**What are other ways to make CefSharp support proprietary audio and video formats? Is there any nuget package to help me?**

**Comment by mitchcapper** [comment]
@raulfmiranda you must compile on your own due to legal restrictions.  https://github.com/mitchcapper/CefSharpDockerfiles I put together to try and make custom compiling easier.  Please support cefsharp! https://salt.bountysource.com/teams/cefsharp
