### ISSUE TITLE
Adding enable-auth-negotiate-port to CefCommandLineArgs has no effect

### ISSUE THREAD

**Issue by damonwildercarr** [cefsharp/CefSharp#2377]
In order for me to load our apps in Chromium it's critical we set enable-auth-negotiate-port to 1 (true). 

I use the following code to set this up:

            CefSettings cefsettings = new CefSettings();
            cefsettings.CefCommandLineArgs.Add("enable-auth-negotiate-port", "1");
            Cef.Initialize(cefsettings);

Unfortunately it does not have any impact.

Is there a way to set Chromium to use this setting via CefSharp? I'm using the following packages:

  <package id="cef.redist.x64" version="3.3239.1723" targetFramework="net45" />
  <package id="cef.redist.x86" version="3.3239.1723" targetFramework="net45" />
  <package id="CefSharp.Common" version="63.0.3" targetFramework="net45" />
  <package id="CefSharp.Wpf" version="63.0.3" targetFramework="net45" />

There is some discussion that this startup argument has been removed in favor of 'policy usage'. I'm not sure how that is exposed in CefSharp.

I've also tried the following with no luck:

            String error;
            var globalRequestContext = Cef.GetGlobalRequestContext();
            globalRequestContext.SetPreference("auth.enable_negotiate_port", true, out error);

and hooking the IsBrowserInitializedChanged:

webBrowser.IsBrowserInitializedChanged += WebBrowserOnIsBrowserInitializedChanged;

        private void WebBrowserOnIsBrowserInitializedChanged(object sender, DependencyPropertyChangedEventArgs dependencyPropertyChangedEventArgs)
        {

            var browser = webBrowser.GetBrowser();

           
            IRequestContext item;

            if (browser != null)
            {
                var browserHost = browser.GetHost();
                item = browserHost.RequestContext;
                
            }
            else
            {
                return;
            }

            string error;
            if (item != null)
                item.SetPreference("auth.enable_negotiate_port", true, out error);
        }

Thanks,
Damon Carr

**Comment by amaitland** [comment]
I've never heard of that preference before, so the question is does `CEF` actually have support for it? A very quick look and it seems unlikely that it does. Other somewhat related preferences were added in 
https://bitbucket.org/chromiumembedded/cef/commits/7190ce8 so you can likely use that as a reference and search the `Chromium` code to fill in the missing pieces. See https://cs.chromium.org/chromium/src/chrome/browser/io_thread.cc?type=cs&sq=package:chromium&l=615 for where I think it's registered, you'll have to do more analysis on your own to figure out the rest.

http://magpcss.org/ceforum/index.php would be the place for any further discussion, `CefSharp` is just a wrapper.

For reference the earliest place you can set a `Preference` is https://github.com/cefsharp/CefSharp/blob/cefsharp/63/CefSharp.Example/Handlers/BrowserProcessHandler.cs#L72

You can use code like below to confirm that preferences are being set correctly, you'll see the minimum font size increase.

```c#
//Use this to check that settings preferences are working in your code
//success = requestContext.SetPreference("webkit.webprefs.minimum_font_size", 24, out errorMessage);
```

I'll leave this open for a little bit, though it's likely to be closed as it seems unlikely that `CefSharp` will need any changes to support this once it's added to `CEF`.

Before opening any further issues I'd ask that you read https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md Thanks

**Comment by damonwildercarr** [comment]
Thank you - much appreciated.

**Comment by amaitland** [comment]
I see you've created https://bitbucket.org/chromiumembedded/cef/issues/2430/add-support-for-authenable-auth-negotiate

Closing this now, anyone interested can track the progress there.
