### ISSUE TITLE
Unprocessed System Exception

### ISSUE THREAD

**Issue by wangkenping** [cefsharp/CefSharp#2379]
version : CefSharp.WinForms 63.0.3  x64
os:windows server 2012 r2
error messages:
Unprocessed System.Exception
The unhandled exception of Message: "System.Exception" type occurs in CefSharp.Core.dll.
Other information: The underlying frame is no longer valid - please check the IsValid IsValid check!

**Comment by amaitland** [comment]
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Also please fork the https://github.com/cefsharp/CefSharp.MinimalExample project and provide an example that reproduces your problem.

**Comment by amaitland** [comment]
If this is still an issue then please fill out the bug report template.

**Comment by amaitland** [comment]
Closing due to lack of feedback.
