### ISSUE TITLE
Memory Leak of the C# process which uses CefSharp - Related to Display Driver

### ISSUE THREAD

**Issue by TomOfekKafka** [cefsharp/CefSharp#2380]
- **What version of the product are you using?**
    63.0.3 from Nuget.

- **What architecture x86 or x64?**
   x86

- **On what operating system?**
    Win7, Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
  WPF

- **What steps will reproduce the problem?**
 I use my Win10 laptop. I disable my display driver from the device manager. In my application I run Cef Control which plays a youtube video. I am creating the control and closing it many times. I see that my process memory consumption is growing without cleanning, probably some leak in libcef.dll.

- **Please provide any additional information below.**
When not disabling the display adapter, everything seems to work ok. It looks like it has something to do with WDDM (Windows Display Driver Model) version. The problem occured also in Win7 where the display adapter was enabled, but the WDDM version was 1.1. 

Running DxDiag, with the following parameters there is no leak: 

![image](https://user-images.githubusercontent.com/28560698/39674629-58181b82-5157-11e8-9065-1c49bdc0396b.png)

When using a machine with these parameters, the leak happens (same code!):

![image](https://user-images.githubusercontent.com/28560698/39674640-83fbf304-5157-11e8-8e81-c887d04448df.png)

I've also found this issue: https://github.com/cefsharp/CefSharp/issues/902 Which can be somehow related.

Any clues, is there some prerequisite I am missing? 

Thank you in advance.

**Comment by amaitland** [comment]
`CefSharp` is just a wrapper, test with the latest `65.0.0-pre01` release, if you still can reproduce the problem then look at https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-chromium-embedded-frameworkcef

If you can reproduce the problem in the `CEF Sample Application` then you'll have to report the problem at http://magpcss.org/ceforum/index.php

Make sure your using the latest drivers.
