### ISSUE TITLE
Disable New windows(tab) from SefSharp(ChromiumWebBrowser)

### ISSUE THREAD

**Issue by HaseenAhmad** [cefsharp/CefSharp#2381]
namespace BrowserTest_For_WS801
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            InitBrowser();
        }
        public ChromiumWebBrowser browser;
        public void InitBrowser()
        {
            Cef.Initialize(new CefSettings());
            browser = new ChromiumWebBrowser("www.wasairobot.com");
            panel1.Controls.Add(browser);
            browser.Dock = DockStyle.Fill;
        }
    }
}

This my Source Code when I run my program then its will Execute and open website but I want to disable New windows tab when I click any link from opened website

Please help me anyone how to handle it......

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp)

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
If you are referring to opening a `Popup` then see #600 for a basic example.
