### ISSUE TITLE
CefSharp sometimes prints only images

### ISSUE THREAD

**Issue by abid76** [cefsharp/CefSharp#2382]
Using CefSharp 63.0.3 WPF on Windows 10.

I experience issues when printing. Sometimes only images of a web page are being printed. Is it a bug or is there any configuration missing?

Please run CefSharp.MinimalExample.Wpf in https://github.com/abid76/CefSharp.MinimalExample and print the initially displayed page to reproduce this issue. You will notice that the page is not printed as displayed in the browser but only the images (one per page) are printed.

**Comment by jankurianski** [comment]
Please ask questions in the CefSharp channel on Gitter.

**Comment by amaitland** [comment]
You should read https://github.com/cefsharp/CefSharp/wiki/General-Usage#file-uri-file
