### ISSUE TITLE
BrowserSubprocess.exe crash

### ISSUE THREAD

**Issue by harshalisingh** [cefsharp/CefSharp#2384]
- **What version of the product are you using?**
63.0.0

- **What architecture x86 or x64?**
x64

- **On what operating system?**
Windows Server 2012 R2

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
OffScreen

- **Please provide any additional information below.**
Application: CefSharp.BrowserSubprocess.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.SEHException
   at <Module>.CefExecuteProcess(CefMainArgs*, scoped_refptr<CefApp>*, Void*)
   at CefSharp.BrowserSubprocess.SubProcess.Run()
   at CefSharp.BrowserSubprocess.Program.Main(System.String[])

**Comment by jankurianski** [comment]
Can you provide the source code to reproduce the crash?

Ideally you would fork https://github.com/cefsharp/CefSharp.MinimalExample and modify the code inside `CefSharp.MinimalExample.OffScreen` so it causes the crash.

**Comment by amaitland** [comment]
> What version of the product are you using?
> 63.0.0

The `65.0.0-pre01` release is out, you should test again with that.

**Comment by amaitland** [comment]
Any follow up on this? Will be closed if there is no response in 14 days.

**Comment by amaitland** [comment]
Closing due to lack of feedback.
