### ISSUE TITLE
BackCommand

### ISSUE THREAD

**Issue by RedBomb1811** [cefsharp/CefSharp#2389]
How I can set the Command property for a button like Command = "{Binding WebBrowser.BackCommand, ElementName = browser}", but through C #, not XAML?

**Comment by amaitland** [comment]
This issue tracker is for bug reports only thank you!

**Comment by amaitland** [comment]
You can directly call Back and CanGoBack. 

http://cefsharp.github.io/api/63.0.0/html/M_CefSharp_WebBrowserExtensions_Back.htm

If you specifically need to bind for some reason then https://msdn.microsoft.com/en-us/library/ms742863(v=vs.100).aspx

Again, in future please don't ask questions on this issue tracker.
