### ISSUE TITLE
Multiple installed certificates in combination with a smartcard

### ISSUE THREAD

**Issue by jornvl90** [cefsharp/CefSharp#2391]
- **What version of the product are you using?**
    - CefSharp.Winforms 63.0.0
CefSharp.Common 63.0.0
cef.redist.x86 3.3239.1723
cef.redist.x64 3.3239.1723

- **What architecture x86 or x64?**   
    - x86

- **On what operating system?**
    - Win7, Win 8, Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - WinForms

- **What steps will reproduce the problem?**
    - The smartcard uses Certificate Propagation Service to install certificates automatically. By doing this, multiple certificates can be installed on the machine. When I try to log in on a website with my smartcard, CEF seems to select the first certificate it can find. This can be different from the inserted smartcard, and as a consequence the login process fails. 

- **What is the expected output? What do you see instead?**
    - A popup to select the right certificate

**Comment by jankurianski** [comment]
I did some Googling and found this StackOverflow question/answer: https://stackoverflow.com/questions/38251873/how-to-re-order-the-client-certificates

That lead me to this PR: https://bitbucket.org/chromiumembedded/cef/pull-requests/89/allow-cef-consumers-to-show-a-custom/diff

The PR mentions:
> Add OnSelectClientCertificate callback in CefRequestHandler to allow selecting the client certificate to use for SSL authentication

So I searched the CefSharp GitHub repository and found this example of `OnSelectClientCertificate` being used:

https://github.com/cefsharp/CefSharp/blob/464dd14b6f88ebe1614cca61c2092d9d67c8efbb/CefSharp.WinForms.Example/Handlers/WinFormsRequestHandler.cs#L39

Next time before entering a bug please ask your question on https://gitter.im/cefsharp/CefSharp
