### ISSUE TITLE
Are ResourceHandler instances supposed to be disposed when unregistering them?

### ISSUE THREAD

**Issue by fvanheeswijk** [cefsharp/CefSharp#2394]
I'm a bit confused by the implementation of resource handlers.

ResourceHandler has an AutoDisposeStream property, only then the stream is disposed when the ResourceHandler is disposed, but I cannot figure out when the Dispose method of the ResourceHandler instance is being called by the DefaultResourceHandlerFactory instance.

I would expect the Dispose method to be called when having used a one-time use resource handler and when unregistering a resource handler, does that make sense?

Otherwise having an AutoDisposeStream property doesn't seem to make much sense to me.

**Comment by jankurianski** [comment]
Please ask questions on https://gitter.im/cefsharp/CefSharp

GitHub issues are for reproducible bug reports only.

**Comment by amaitland** [comment]
It raises an interesting question and as @jankurianski says we prefer to keep this issue tracker for bug reports only (as outlined in https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md)

I'll answer here as I think there are some additional params that should be added.

I'll first point out that features like `LoadHtml` actually use `ByteArrayResourceHandler` which doesn't use a `Stream`, just a `byte[]` array.

> but I cannot figure out when the Dispose method of the ResourceHandler instance is being called by the DefaultResourceHandlerFactory instance.

It's not called by `DefaultResourceHandlerFactory`. The `ResourceHandler` instances within `DefaultResourceHandlerFactory` are reused for simplicity. `IResourceHandler.Dispose` is actually called every time the `unmanaged` `CefResourceHandler` implementation has finished with the stream. Should you wish to reuse a `ResourceHandler` you must keep the stream open.

> I would expect the Dispose method to be called when having used a one-time use resource handler and when unregistering a resource handler, does that make sense?

For one time use, you would be `Disposing` of the `Stream` before the request was fulfilled. When unregistered, in some cases it might make sense, it depends if you wish to reuse the `Stream` or the `ResourceHandler`. 

The `DefaultResourceHandlerFactory` was really only intended to store in memory data, if you pass in a `FileStream` then you will be relying on the `GC` to take care of closing the `Stream`. If that's what you require then best to provide your own implementation.

> Otherwise having an AutoDisposeStream property doesn't seem to make much sense to me.

I admit it should be easier to set, so I've made a small change,  see commit https://github.com/cefsharp/CefSharp/commit/5adff7014b2de86d6afbf9e2b0707283336f02c1 and see https://github.com/cefsharp/CefSharp/commit/7f3a31b758290768864ab08b75673b5a48e51988 for an example

At some point it might be worth rewriting `DefaultResourceHandlerFactory` to store data as `byte[]` and return a new `ResourceHandler` for every `GetResourceHandler` call. That would better represent it's designed purpose of storing in memory data.
