### ISSUE TITLE
Is v8_context_snapshot.bin required?

### ISSUE THREAD

**Issue by pfeigl** [cefsharp/CefSharp#2399]
- **What version of the product are you using?**
65.0.0-pre01

- **What architecture x86 or x64?**
x86

- **On what operating system?**
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms hosted in `WindowsFormsHost` within an WPF application

After updating to 65.0.0-pre01 I saw there is a new file "v8_context_snapshot.bin". It is mentioned in https://github.com/cefsharp/cef-binary/blob/master/README.txt as required, but not in https://github.com/cefsharp/CefSharp/wiki/Output-files-description-table-(Redistribution)

Now I'm unsure whether I have to package this file into the our installer?

**Comment by amaitland** [comment]
It's required, feel free to update the wiki. PR to update the dependency checker is welcome.

**Comment by pfeigl** [comment]
PR is there, also updated the Wiki. Thanks for the fast info!

**Comment by amaitland** [comment]
> PR is there, also updated the Wiki.

Nice one, thanks 👍
