### ISSUE TITLE
Draggable region

### ISSUE THREAD

**Issue by Zneiat** [cefsharp/CefSharp#2403]
Hello,
Could you tell me if CefSharp has a function similar to electronjs `-webkit-app-region:drag`? https://electronjs.org/docs/api/frameless-window#draggable-region
Thanks!

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp)

**Comment by amaitland** [comment]
Draggable regions are supported

https://github.com/cefsharp/CefSharp/search?utf8=✓&q=draggable+region&type=

**Comment by qwqcode** [comment]
I dit it!!!

![](https://user-images.githubusercontent.com/22412567/50545691-67d04780-0c54-11e9-85d1-d91ee3f8a2d9.gif)

[https://github.com/qwqcode/CefSharpDraggableRegion](https://github.com/qwqcode/CefSharpDraggableRegion)

This you can specify `-webkit-app-region: drag` in CSS to tell CefSharp which regions are draggable (like the OS's standard titlebar).
