### ISSUE TITLE
Javascript : window.speechSynthesis.getVoices() returns an empty array

### ISSUE THREAD

**Issue by BigPino67** [cefsharp/CefSharp#2404]
**What version of the product are you using?**
63.0.3 via NuGet.

**What architecture x86 or x64?**
x86 platform in build configuration.

**On what operating system?**
Windows 10

**Are you using WinForms, WPF or OffScreen?**
WinForms

**What steps will reproduce the problem?**
Go to https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/speechsynthesis/

The dropdown list of voices is empty! Supposed to be full.

Or, open a remote dev console for cefSharp project, and type window.speechSynthesis.getVoices(). The array is empty! Supposed to be an array of 20 SpeechSynthesisVoice objects.

**What is the expected output? What do you see instead?**
Suppose to have at least 20  SpeechSynthesisVoice objects in an array, mine is empty. No crash

The browser is suppose to support Speech Synthesis

**Results with CefSharp :**
![image](https://user-images.githubusercontent.com/15323780/40743899-d4e93c64-6420-11e8-9fc7-7ee60ffcbe88.png)

**Wanted (as chrome) :**
![image](https://user-images.githubusercontent.com/15323780/40743805-84d6c80e-6420-11e8-8bfa-6eb8282d6eb3.png)

**Comment by amaitland** [comment]
### How do I investigate my issue further?

It's important to remember that `CefSharp` is just a wrapper around the `Chromium Embedded Project (CEF)`, the upstream [`CEF` forum](http://magpcss.org/ceforum/) is a valuable resource. Also `CEF` has it's own [Issue Tracker](https://bitbucket.org/chromiumembedded/cef/issues). Please take the time to research your own problem, including `Googling`, searching on `ceforum`, etc.

--
#### Finding more info
- Have you checked the `Debug.log` file? (Should be located in your apps executing folder by default)
- Have you googled the error message your seeing? (Don't just google the whole thing, try googling just the keywords and possibly add `chromium` as a keyword).
- Are you able to reproduce the problem using `cefclient`? (`cefclient` is the reference implementation provided by `CEF`)
- Need more help debugging? Check the [Troubleshooting Guide](https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting)
- Are you using the latest version? Check the [Release Branches](https://github.com/cefsharp/CefSharp#release-branches) table to determine if the version your using is supported. 

--
#### How do I download `cefclient`?

- Firstly identity which version of `CEF` your actually using, easiest way is to check your `packages.config` file, look for the `cef.redist.x86` package, it's version will be something like `3.2526.1362`, that's the exact version of `CEF` you'll need to download for comparison. You can also open `chrome://version` in the browser to determine the version.
- Open http://opensource.spotify.com/cefbuilds/index.html in a web browser
- Locate the exact `Branch` you require, for the example above the branch is `2526`, all the versions follow a similar pattern
- Locate the `Windows 32bit` or `Windows 64bit` item, if you don't see the exact version, then click `more revisions`
- Download **Test App**
- Are you using `WPF/Offscreen` or `WinForms`? 

**This next part is key**
- To compare with WPF/OffScreen run `cefclient --multi-threaded-message-loop --off-screen-rendering-enabled`
- To compare with WinForms `cefclient --multi-threaded-message-loop`

**Comment by amaitland** [comment]
See http://magpcss.org/ceforum/viewtopic.php?f=6&t=11570

If you need further clarification best to ask on http://magpcss.org/ceforum/index.php as I've never used the API.
