### ISSUE TITLE
Can't play audio from cross domain

### ISSUE THREAD

**Issue by BigPino67** [cefsharp/CefSharp#2405]
**What version of the product are you using?**
63.0.3 via NuGet.

**What architecture x86 or x64?**
x86 platform in build configuration.

**On what operating system?**
Windows 10

**Are you using WinForms, WPF or OffScreen?**
WinForms

**What steps will reproduce the problem?**
Create an HTML file with this code : 
`<html><head>
<script>
function play(){
	audio = new Audio();
	audio.src = "https://www.bing.com/tspeak?&format=audio/mp3&language=en-ca&options=male&text=Hello%20my%20friend";
	audio.play();
}
</script>
</head>
<body>
<button onclick="play()">Play me</button>

</body>
</html>`

Run it in Chrome, click "Play me" button. You'll ear a sound. Now, copy the file URL and use it to start a broswer with CefSharp. Then, click "Play me" button ... no sound!

**Remote console error :** 
Uncaught (in promise) DOMException: Failed to load because no supported source was found.

**Comment by amaitland** [comment]
See #2322
