### ISSUE TITLE
issues about ChromiumWebBrowser.Load(url)

### ISSUE THREAD

**Issue by baby-Jie** [cefsharp/CefSharp#2406]
my code:
            browser.Load(url);
            if (!url.Equals("about:blank"))
            {
                browser.Load(url);
                browser.BringToFront();
            }

      switch url betweeen "about:blank" and "www.baidu.com" some times
     i find it cannot turn to "www.baidu.com" from "about:blank"

Notes: When the page is in the about:blank state,  Load(url) twice , it will go wrong

**Comment by amaitland** [comment]
### How do I investigate my issue further?

It's important to remember that `CefSharp` is just a wrapper around the `Chromium Embedded Project (CEF)`, the upstream [`CEF` forum](http://magpcss.org/ceforum/) is a valuable resource. Also `CEF` has it's own [Issue Tracker](https://bitbucket.org/chromiumembedded/cef/issues). Please take the time to research your own problem, including `Googling`, searching on `ceforum`, etc.

--
#### Finding more info
- Have you checked the `Debug.log` file? (Should be located in your apps executing folder by default)
- Have you googled the error message your seeing? (Don't just google the whole thing, try googling just the keywords and possibly add `chromium` as a keyword).
- Are you able to reproduce the problem using `cefclient`? (`cefclient` is the reference implementation provided by `CEF`)
- Need more help debugging? Check the [Troubleshooting Guide](https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting)
- Are you using the latest version? Check the [Release Branches](https://github.com/cefsharp/CefSharp#release-branches) table to determine if the version your using is supported. 

--
#### How do I download `cefclient`?

- Firstly identity which version of `CEF` your actually using, easiest way is to check your `packages.config` file, look for the `cef.redist.x86` package, it's version will be something like `3.2526.1362`, that's the exact version of `CEF` you'll need to download for comparison. You can also open `chrome://version` in the browser to determine the version.
- Open http://opensource.spotify.com/cefbuilds/index.html in a web browser
- Locate the exact `Branch` you require, for the example above the branch is `2526`, all the versions follow a similar pattern
- Locate the `Windows 32bit` or `Windows 64bit` item, if you don't see the exact version, then click `more revisions`
- Download **Test App**
- Are you using `WPF/Offscreen` or `WinForms`? 

**This next part is key**
- To compare with WPF/OffScreen run `cefclient --multi-threaded-message-loop --off-screen-rendering-enabled`
- To compare with WinForms `cefclient --multi-threaded-message-loop`

**Comment by baby-Jie** [comment]
@amaitland hello amaitland, i am using WinForms.The verision i am using is "3.3239.1723"(63.0.3).
it's simple in my code:
 private void btnGo_Click(object sender, EventArgs e)
        {
            string url = textBox1.Text.Trim();
            browser.Load(url);
            //Thread.Sleep(30);
            browser.Load(url);
        }
change the url:  
  1,"www.google.com" -> "about:blank"
  2, "about:blank" -> "www.google.com"
it does not work at step 2, it also at the page of "about:blank", but if i use Thread.Sleep between Load(Url), it will work properly.

there is no useful information in debug.log. it only write dome warning when the browser start like this:
[0605/095707.569:WARNING:angle_platform_impl.cc(51)] rx::HLSLCompiler::compileToBinary(228): 
C:\fakepath(30,8-58): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
C:\fakepath(35,8-28): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them

[0605/095708.579:WARNING:angle_platform_impl.cc(51)] rx::HLSLCompiler::compileToBinary(228): 
C:\fakepath(48,8-58): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
C:\fakepath(53,8-28): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them

can you give me some suggestions about how to deal with it?

**Comment by amaitland** [comment]
about:blank is treated as a special case by Chromium, in newer version I don't believe it triggers a navigation. 

http://magpcss.org/ceforum/viewtopic.php?f=6&t=15989&p=38465&hilit=about%3Ablank#p38465
http://magpcss.org/ceforum/viewtopic.php?f=10&t=15950&p=38246&hilit=about%3Ablank#p38246

From a CefSharp point of view this is unlikely a bug. You should test with cefclient if you wish to confirm, see above for details. 

You can always use a data encoded uri, see https://github.com/cefsharp/CefSharp/wiki/General-Usage#loading-htmlcssjavascriptetc-from-diskdatabaseembedded-resourcestream for an example, it's at the bottom of that section 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs

**Comment by baby-Jie** [comment]
@amaitland  it's ok, thanks a lot

**Comment by amaitland** [comment]
You can try with 65.0.0-pre01 and see if it behaves differently, in general I suggest avoiding using about:blank

**Comment by baby-Jie** [comment]
@amaitland  hello, i find another problem.
first:
 browser.Load(blankHtmlFilePath);
second:
//browser.Load("www.google.com");
//browser.Load("www.google.com");
browser.Load(testHtmlFilePath);
browser.Load(testHtmlFilePath);

At the second part, it does not work. If i load "www.google.com", it is ok.
if i use data encoded uri at the first step, suach as :
                const string html = "<html><head><title>Test</title></head><body></body></html>";
                var base64EncodedHtml = Convert.ToBase64String(Encoding.UTF8.GetBytes(html));
                browser.Load("data:text/html;base64," + base64EncodedHtml);
testhtml will not load completely, i need refresh the browser.

**Comment by baby-Jie** [comment]
@amaitland  I try it in cefclient. It also exists this problem.
