### ISSUE TITLE
When a PC has multiple cameras, how to set a default caller like Chrome

### ISSUE THREAD

**Issue by AimuTran** [cefsharp/CefSharp#2407]
### When a PC has multiple cameras, how to set a default caller like Chrome

![qq 20180601191911](https://user-images.githubusercontent.com/4810539/40838454-dd9a81fe-65d0-11e8-9750-06815e84c495.jpg)
![qq 20180601191935](https://user-images.githubusercontent.com/4810539/40838455-ddff1a4c-65d0-11e8-89cd-8c119f2ae424.jpg)

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

**Comment by amaitland** [comment]
CEF does not provide an APi for directly selecting camera or microphone, you can use JavaScript to change the camera see https://simpl.info/getusermedia/sources/

.
