### ISSUE TITLE
Dotted / dashed lines in a PDF file are printed too small

### ISSUE THREAD

**Issue by jidel** [cefsharp/CefSharp#2409]
### Bug Report
- **What version of the product are you using?**
Nuget version 63.0.3 but also occurs with 65.0.0-pre01

- **What architecture x86 or x64?**
 x64
- **On what operating system?**
Win7

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF
- **What steps will reproduce the problem?**
    - Open a PDF file containing dashed/dotted lines (e.g. [this](https://www.superteacherworksheets.com/alphabet/alphabet-book-test.pdf))
    - Print the PDF by using the Cef-provided print button (using XPS Printer or any installed printer)
- **What is the expected output? What do you see instead?**
  - The expected result would be a printed document that looks like the one displayed in CefSharp or any other PDF viewer.
   - Result: the dashed lines are printed too small and appear at the wrong position. 
![image](https://user-images.githubusercontent.com/6048968/40922770-518e374c-6813-11e8-9a24-2e1e88fdaca3.png)

- **Please provide any additional information below.**
  - Also occurs in the [sample application](https://github.com/cefsharp/CefSharp.MinimalExample) that uses the NuGet packages 63.0.3
  - There is no exception message or any entry in the [debug.log](https://github.com/cefsharp/CefSharp/files/2068637/debug.log)
   - Downloading the PDF and printing it over a PDF viewer (e.g. Adobe) works as expected.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
No, tried with cef 3.3239.1723_windows64 sample application and the command `cefclient --multi-threaded-message-loop --off-screen-rendering-enabled`

**Comment by amaitland** [comment]
If it works in cefclient then compare the directory structure and make sure all the files are present in your CefSharp based app. It's possible that a new resource has been added that we don't yet include in the packages.

**Comment by jidel** [comment]
The following components seem to be missing from the CefSharp application's output directory:
- d3dcompiler_43.dll (I am guessing this would only be relevant for XP)
- the pak.info files in _locale_ folder

Also, the cefclient's files seem to be a bit newer. Apart from that, I can not see any differences

**Comment by amaitland** [comment]
> d3dcompiler_43.dll (I am guessing this would only be relevant for XP)

Yes, `XP` only which is no longer supported.

> the pak.info files in locale folder

They're not required and won't be in newer versions of `CEF` see https://bitbucket.org/chromiumembedded/cef/issues/2375

> Apart from that, I can not see any differences

 Someone will have to compare the `cefclient` implementation.

**Comment by amaitland** [comment]
master has been upgraded to CEF 3.3396.1777.g636f29b / Chromium 67.0.3396.79 might be worth testing again

**Comment by jidel** [comment]
Sadly no change regarding the printing of dotted lines. However, the application crashes when hovering over the print button in PDF view.

**Comment by amaitland** [comment]
Appears there are know issues with PDF printing in the 3396 branch

https://bitbucket.org/chromiumembedded/cef/issues/2463/save-and-print-pdf-buttons-not-working

**Comment by amaitland** [comment]
> Appears there are know issues with PDF printing in the 3396 branch
> 
> https://bitbucket.org/chromiumembedded/cef/issues/2463/save-and-print-pdf-buttons-not-working

Has been fixed with https://bitbucket.org/chromiumembedded/cef/commits/185623100e6710bd7ab5f83a531a1d5fc0245e02?at=3396

Waiting for `CEF` to upgrade to a newer `Chromium` version before `master` is updated.

**Comment by amaitland** [comment]
> Has been fixed with https://bitbucket.org/chromiumembedded/cef/commits/185623100e6710bd7ab5f83a531a1d5fc0245e02?at=3396

Appears to still be an issue when testing with `cefclient --multi-threaded-message-loop --off-screen-rendering-enabled` (only crashes with `Offscreen Rendering enabled`) using version `cef_binary_3.3396.1786.gd3e36d0`

**Comment by amaitland** [comment]
https://bitbucket.org/chromiumembedded/cef/issues/2757/radio-buttons-checkboxes-and-buttons-not

**Comment by amaitland** [comment]
Closing as `upstream` subscribe to https://bitbucket.org/chromiumembedded/cef/issues/2757/radio-buttons-checkboxes-and-buttons-not for further notifications.

Reproduces with `cefclient --no-sandbox`. `CefSharp` doesn't support the `Sandbox` as it's not possible to statically compile the `.lib` file into a `managed exe`.

**Comment by amaitland** [comment]
With commit https://bitbucket.org/chromiumembedded/cef/commits/33b89e9389b1c792f3b2090f86fd543943bcc373 There will be changes to how no sandbox is handled as detailed at https://magpcss.org/ceforum/viewtopic.php?f=7&t=17430

There is a small chance this problem will be resolved in CEF,  I'm only speculating at this point. Version 81 will be the first to include the change.
