### ISSUE TITLE
CEF3: Consider dropping the WinForms control

### ISSUE THREAD

**Issue by perlun** [cefsharp/CefSharp#241]
This isn't as controversial as it seems; it's [quite easy](http://msdn.microsoft.com/en-us/library/ms742215%28v=vs.110%29.aspx) to host WPF controls in a Windows Forms app. However, I do feel that with the current level of stability, and maturity of the example app (for example), the Windows Forms control doesn't really do CefSharp3 justice. It would be better (IMHO) to just drop it, and instead recommend people to just use WPF. If they must use it in a WinForms application, the link in this issue would be the solution.

What does the rest of you feel about this? Good idea or bad?

I think the alternative would be for someone to really dig into the WinForms code, try to make it good and so on (a little bit like I've been doing with the WPF one), but this hasn't really happened thus far. I don't use WinForms personally, frankly I hate it. :smiley: So it's very unlikely that I will take some of my small amount of time and dedicate it on something like that.

**Comment by cwaldron** [comment]
Keep Winforms.  There are many developers that have never programmed WPF and never needed to.  The reason why is many of these application are enterprise apps and never required fancy rendering.  Chromium does its own off screen rendering.  Winforms merely provided a host environment and its far easier to use than WPF.  The main issue Winforms developers have with WPF is XAML and this will impeded the adoption of CEFSharp.

In addition, you have no portability story with WPF.  At least Mono (Xamarin) supports WinForms and will make it easier to port to Linux & Mac a Winforms based application.  So with WinForms you have a consistent hosting environment and a portability story.

**Comment by amaitland** [comment]
@cwaldron Your two **years** late to the party here.....

**Comment by mortalV** [comment]
Just my 2 cents...
WinForms must live until WPF version will works with D3DImage,
because today with bitmap copy it's less smoother animation and more CPU eating specially for WebGL application and 60 FPS.

**Comment by amaitland** [comment]
@mortalV This issue was closed almost two **years** ago, it's not relevant!!!

I'm going to lock this now, hopefully that gives everyone gets the message.
