### ISSUE TITLE
Getting latest version?

### ISSUE THREAD

**Issue by DjSt3rios** [cefsharp/CefSharp#2412]
Hello everybody, I have the latest CefSharp for WinForms from Nuget. However, it seems like some things are missing, like the LifespanHandler. I downloaded the solution from git, and the LifespanHandler does exist in WinForms project! So I decided to take the DLLs myself from the release version and replace my old ones from Nuget. For some weird reason, when I try to access the LifespanHandler it's still not there! It's like my DLLs are not updated correctly. I placed both x86 and x64 DLLs. How can I get all latest features?

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
There is no LifeSpanHandler implementation as part of the official release. The **example** projects contain versions you are welcome to copy and paste into your application.
