### ISSUE TITLE
ChromiumWebBrowser is not garbage collected after Dispose();

### ISSUE THREAD

**Issue by henrihs** [cefsharp/CefSharp#2414]
- **What version of the product are you using?**
63.0.3

- **What architecture x86 or x64?**
x86

- **On what operating system?**
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
Running `ChromiumWebBrowser.Dispose()` (without closing the application)

- **What is the expected output? What do you see instead?**
After the ChromiumWebBrowser has been disposed, it should be ready for garbage collection. However, because the EventHandlers `WindowStateChanged` and `OnWindowLocationChanged` isn't unsubscribed from their respective events, the instance lives on in the memory.

- **Please provide any additional information below.**
The issue was identified using .Net Memory Profiler (https://memprofiler.com/) - which tells me that ```This instance is disposed and still directly rooted by an EventHandler.```

My application is using a global context, and within a given context the views/viewmodels stays in memory until the user makes a change of context. Switching context should close all context specific views, and dispose their references.
A snapshot was taken after a view including a ChromiumWebBrowser was show, and another snapshot taken after a change of context, i.e. after the ChromiumWebBrowser is disposed. The diff between these snapshots show that the instance is disposed, but not garbage collected. 

I've tested the following solution to successfully solving the issue in `CefSharp.Wpf.ChromiumWebBrowser`:
```diff
private void PresentationSourceChangedHandler(object sender, SourceChangedEventArgs args)
{
[...]
    var window = source.RootVisual as Window;
    if(window != null)
    {
+        _sourceWindow = window;
        window.StateChanged += WindowStateChanged;
        window.LocationChanged += OnWindowLocationChanged;
    }
```

```diff
protected virtual void Dispose(bool isDisposing)
{
[...]
    PresentationSource.RemoveSourceChangedHandler(this, PresentationSourceChangedHandler);
+    if (_sourceWindow != null)
+    {
+        _sourceWindow.StateChanged -= WindowStateChanged;
+        _sourceWindow.LocationChanged -= OnWindowLocationChanged;
+    }
```

#### Workaround
To temporarily work around this problem , I've used `Reflection` to manage to unsubscribe to these events in my code-behind:
```c#
public ChromiumWebBrowserWrapperView()
{
    InitializeComponent();
    PresentationSource.AddSourceChangedHandler(this, SourceChangedHandler);

}

private void SourceChangedHandler(object sender, SourceChangedEventArgs e)
{
    if (e.NewSource is HwndSource source)
    {
        m_source = source;
    }
}

public void Dispose()
{
    // TODO: Remove when https://github.com/cefsharp/CefSharp/issues/2414 is resolved and we're using CefSharp with bugfix
    // Fooling ChromiumWebBrowser to unsubscribe to window events
    var presentationSourceChangedHandler = chromiumWebBrowser.GetType().GetMethod(
        "PresentationSourceChangedHandler",
        BindingFlags.NonPublic | BindingFlags.Instance);
    var eventArgs = new SourceChangedEventArgs(oldSource: m_source, newSource: null);
    presentationSourceChangedHandler?.Invoke(chromiumWebBrowser, new object[]{ this, eventArgs });
```

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
Not applicable

**Comment by amaitland** [comment]
By all means submit a PR.

**Comment by henrihs** [comment]
I just tried reproducing the issue in the Wpf.ExampleApp, but I couldn’t; the PresentationSourceChangedHandler is called each time a tab is closed, and the events are thus unsubscribed. 

Something in our wrapper must be set up differently than in the example app, I’ll look into it first thing tomorrow morning.

**Comment by amaitland** [comment]
The tabs are removed from the parent tabcontrol before they're disposed

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf.Example/MainWindow.xaml.cs#L46

**Comment by henrihs** [comment]
It seems like we were disposing the `ChromiumWebBrowser` prematurely. We've hooked the `CleanupElement` to our wrapper view instance, in addition to calling `ChromiumWebBrowser.Dispose()` from our viewmodel. This caused the `PresentationSourceChangedHandler` to be unsubscribed prior the the final `PresentationSourceChangeEvent` firing. I removed the "manual" call to Dispose, and the memory leak was gone.

I'll submit a PR anyways, making sure that Dispose cleans up regardless of the sequence. What do you think @amaitland?

**Comment by amaitland** [comment]
> I'll submit a PR anyways, making sure that Dispose cleans up regardless of the sequence

Sounds reasonable to me 👍

**Comment by henrihs** [comment]
[](https://github.com/cefsharp/CefSharp/pull/2416/commits/45c0cc2a1f2a06d3f271d03ada8c29c84daa34f0)

**Comment by amaitland** [comment]
Merged into `cefsharp/65` with  https://github.com/cefsharp/CefSharp/commit/80327e5f35f528212c2e906994923fca67bfb11c

For minor follow up see commit https://github.com/cefsharp/CefSharp/commit/5193d4a2ac37fa81028962fc77a133e6c8c416f4
