### ISSUE TITLE
i am not able to select single 'f' in richtextbox. while using shift+left arrow.

### ISSUE THREAD

**Issue by kasifNawaz** [cefsharp/CefSharp#2417]
![image](https://user-images.githubusercontent.com/8176840/41296901-9735a3fc-6e7b-11e8-8306-0e8f3f27f239.png)

**Comment by amaitland** [comment]
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Also please fork the https://github.com/cefsharp/CefSharp.MinimalExample project and provide an example that reproduces your problem.

**Comment by amaitland** [comment]
Closing due to lack of feedback
