### ISSUE TITLE
while pressing ctril+c and ctrl+v for long time.few words are highlighted with light blue color and few are with dark blue color in richtextbox

### ISSUE THREAD

**Issue by kasifNawaz** [cefsharp/CefSharp#2418]
![image](https://user-images.githubusercontent.com/8176840/41297128-185ed160-6e7c-11e8-9246-1ca81a4eb8a1.png)

**Comment by amaitland** [comment]
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Also please fork the https://github.com/cefsharp/CefSharp.MinimalExample project and provide an example that reproduces your problem.

**Comment by amaitland** [comment]
Closing due to lack of feedback.
