### ISSUE TITLE
WinForms with CEFSharp full page screenshot

### ISSUE THREAD

**Issue by AleksRoth** [cefsharp/CefSharp#2421]
I'm trying to write a program that takes a screenshot on the web - page.
I use CefSharp (chromium embedded framework c#) in a Winforms application.
My program works and open web-page.

I'm trying to migrate
CefSharp.MinimalExample.OffScreen: https://github.com/cefsharp/CefSharp.MinimalExample/blob/master/CefSharp.MinimalExample.OffScreen/Program.cs
is in my program but I have a problem with driver designation: private static ChromiumWebBrowser browser;   
Can anyone help me with this problem? I'm new to C # please help.

Programm.cs

	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Threading.Tasks;
	using System.Windows.Forms;
	using System.Drawing;
	using System.Drawing.Imaging;
	using System.Threading;
	using System.Runtime.InteropServices;
	namespace WindowsFormsApplication1
	{
		class Program
		{
			[STAThread]
			static void Main()
			{
				Application.EnableVisualStyles();
				Application.SetCompatibleTextRenderingDefault(false);
				Application.Run(new Form1());
			}
	  }
	}

Form1.cs

	using System;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.Data;
	using System.Drawing;
	using System.Linq;
	using System.Text;
	using System.Threading.Tasks;
	using System.Windows.Forms;
	using CefSharp;
	using CefSharp.WinForms;

	namespace WindowsFormsApplication1
	{
		public partial class Form1 : Form
		{
			public ChromiumWebBrowser chromeBrowser;
			public Form1()
			{
				InitializeComponent();
				InitializeChromium();
			}
			private void Form1_Load(object sender, EventArgs e)
			{
			}
			private void InitializeChromium()
			{ 
				CefSettings settings = new CefSettings();
				Cef.Initialize(settings);
				chromeBrowser = new ChromiumWebBrowser("https://www.google.com/");
				this.Controls.Add(chromeBrowser);
				chromeBrowser.Dock = DockStyle.Fill;
			}
			private void Form1_FormClosing(object sender, FormClosingEventArgs e)
			{
				Cef.Shutdown();
			}
		}
	}

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp)

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage
