### ISSUE TITLE
Redirect links don't refresh Url, but update Title

### ISSUE THREAD

**Issue by Tesla7D** [cefsharp/CefSharp#2423]
- **What version of the product are you using?**
    - Nuget - 63.0.3

- **What architecture x86 or x64?**
    - x64

- **On what operating system?**
    - Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - WPF

- **What is the problem?**
    - Using auth pages with redirect causes FrameLoadEnd to get "chrome-error://chromewebdata/". This causes browser Url to not update, even though Title gets new value. **New as of v57. Cef v55 doesn't have the issue**

    - Version 63.0.3 example: ![cef1](https://user-images.githubusercontent.com/9098226/41620188-f30779a2-73d6-11e8-9863-6858f4a48b65.png)
    - Version 55 example: ![cef2](https://user-images.githubusercontent.com/9098226/41620233-0d31a1cc-73d7-11e8-9fa5-b0b9fc1670d1.png)

- **What steps will reproduce the problem?**
    - Get [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample)
    - Try doing auth with redirect (ex. Microsoft, Google)
    - Notice Url staying the same and Title changing to correct url.

- **What is the expected output? What do you see instead?**
    - Redirects should trigger FrameLoadEnd  with proper Url.
    - Title and Url should match (except if Title is set to custom value)

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.
        - No exception

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
        - The only line: [0619/143356.895:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
        - Just the default Minimal application

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

    - Tested with cef_binary_3.3396.1779.g36f9eab_windows64_minimal

**Comment by amaitland** [comment]
You'll have to test with the latest CEF version, for which there currently isn't a build of CefSharp ( master will be upgraded hopefully this week ). 

If it reproduce with the latest CEF version you'll have to raise the issue upstream, CefSharp is just a wrapper. http://magpcss.org/ceforum/index.php

**Comment by amaitland** [comment]
`master` has been upgraded to `CEF 3.3396.1777.g636f29b / Chromium 67.0.3396.79`

If you can reproduce the problem using `master` then you should raise the issue with the `CEF` project

**Comment by amaitland** [comment]
Make sure you test with cefclient, the CEF sample application

**Comment by Tesla7D** [comment]
We did some extra testing for CefSharp and Cef and here is what we found:

- CefSharp v55 uses Cef 3.2883.1552
- CefSharp v63.0.3 uses Cef 3.3239.1723
- After testing same URLs on both versions of Cef (using CEF Sample Application) we didn't see any differences in behavior. Both versions behaved exactly the same.

Since newer versions of CefSharp have different behaviors and Cef doesn't, it suggests that the problem is actually in the CefSharp wrapper.

Here is the result both versions of Cef had:
![cef_both_versions](https://user-images.githubusercontent.com/9098226/42096768-47690696-7b84-11e8-84a5-429835e24609.jpg)

**Comment by amaitland** [comment]
> Try doing auth with redirect (ex. Microsoft, Google)
> Notice Url staying the same and Title changing to correct url.

Is there a reason your redirecting to a `host` that is refusing connections? Your steps to reproduce say load `Microsoft` or `Google`, yet your screen shots show `localhost`. The list of steps to reproduce are very vague. 

> New as of v57. Cef v55 doesn't have the issue

Seems unlikely this is a regression from a `CefSharp` point of view. 

> Since newer versions of CefSharp have different behaviors and Cef doesn't, it suggests that the problem is actually in the CefSharp wrapper.

Based on your last screen shot which shows your redirecting to a page that is refusing connecting, this doesn't appear to be a problem with `CefSharp`. `cefclient` handles `LoadError` and generates the page you are seeing. You will need to implement something similar. 

The main repository contains a very basic example, see https://github.com/cefsharp/CefSharp/blob/cefsharp/65/CefSharp.Wpf.Example/Views/BrowserTabView.xaml.cs#L123
