### ISSUE TITLE
Cef Browser not loading after deployment using wix ( CefSharp.BrowserSubprocess not getting started )

### ISSUE THREAD

**Issue by Arshad8464** [cefsharp/CefSharp#2426]
Hi I am new to CEF .

I develop a winform which contains CEF browser and its working perfectly when running from visual studio 2017 .
But after the deployment using wix installer when running the same  browser is not loading and i found **CefSharp.BrowserSubprocess not getting started  in Tassk manager**

I have all the file from debug into the active folder.But still browser not loading .
Am i missing any thing ?

Arshad

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp)

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
https://stackoverflow.com/questions/50946164/cefbrowser-not-loading-after-deployment-using-wix
