### ISSUE TITLE
Application Hangs when property grid throws validation error

### ISSUE THREAD

**Issue by wewake4** [cefsharp/CefSharp#2429]
Version : 57.0.0.0
Reproducable in Latest Version
x64
Win10
WinForms

In CefSharp.WinForms.Example.csproj to the screen add a windows propertygrid. Add this class
```
class PropertyGridSimpleDemoClass2
    {
      int m_DisplayInt = 50;
      [Description("sample hint1")]
      [Category("Category1")]
      [DisplayName("Int for Displaying")]
      public int DisplayInt
      {
        get { return m_DisplayInt; }
        set { m_DisplayInt = value; }
      }
    }
```
and add these below the InitializeComponent();

```
PropertyGridSimpleDemoClass2 pgdc = new PropertyGridSimpleDemoClass2();
propertyGrid1.SelectedObject = pgdc;
```

I am running the application in x86 mode. First we need to delete the 50 value from property grid and click on cefsharp.
property grid produces a validation message that 'int is not valid' and Application freezes. Not able to close the message box. It happens only when clicked on cefsharp browser.

Thanks.

**Comment by amaitland** [comment]
You can try integrating `CEF` into your applications existing message loop, that would be where I'd start, see https://github.com/cefsharp/CefSharp/wiki/General-Usage#multithreadedmessageloop for some information.

Change `const bool multiThreadedMessageLoop = true;` to `const bool multiThreadedMessageLoop = false;` and rerun your tests.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.WinForms.Example/Program.cs#L62

**Comment by amaitland** [comment]
Closing due to lack of feedback.
