### ISSUE TITLE
Exception: Unable to expand length of this stream beyond its capacity

### ISSUE THREAD

**Issue by juongithub** [cefsharp/CefSharp#2433]
- **What version of the product are you using?** 
Current Master - last commit: https://github.com/cefsharp/CefSharp/commit/2899112843f372790c16b9cf847853488d3d6ca3

- **What architecture x86 or x64?** 
x64

- **On what operating system?** 
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?** 
WinForms, I'm actually using the example CefSharp.WinForms.Example

- **What steps will reproduce the problem?**
1. In CefSharp.Example\Handlers\RequestHandler.cs change `GetResourceResponseFilter` to 

```
public override IResponseFilter GetResourceResponseFilter(IWebBrowser browserControl, IBrowser browser, IFrame frame, IRequest request, IResponse response)
{
    var dataFilter = new MemoryStreamResponseFilter();
    responseDictionary.Add(request.Identifier, dataFilter);
    return dataFilter;
}
```

2. Run CefSharp.WinForms.Example in debug mode (x64) and navigate (for example) to https://www.wired.com/

- **What is the expected output? What do you see instead?**
Navigation without exceptions and/or errors. Instead the following exception is thrown:

```
System.NotSupportedException was unhandled
  HResult=-2146233067
  Message=Unable to expand length of this stream beyond its capacity.
  Source=mscorlib
  StackTrace:
       at System.IO.UnmanagedMemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
       at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
       at System.IO.Stream.CopyTo(Stream destination)
       at CefSharp.Example.Filters.MemoryStreamResponseFilter.CefSharp.IResponseFilter.Filter(Stream dataIn, Int64& dataInRead, Stream dataOut, Int64& dataOutWritten) in CefSharp\CefSharp.Example\Filters\MemoryStreamResponseFilter.cs:line 38
       at CefSharp.Internals.CefResponseFilterAdapter.Filter(CefResponseFilterAdapter* , Void* dataIn, UInt32 dataInSize, UInt32* dataInRead, Void* dataOut, UInt32 dataOutSize, UInt32* dataOutWritten) in cefsharp\cefsharp.core\internals\cefresponsefilteradapter.h:line 69
  InnerException: 

```

**Comment by amaitland** [comment]
The filters are only part of the `Example` project as they aren't tested in a `Production` environment, they're just there to get you started. Data is typically split into `32kb` chunks.

The `upstream` documentation is http://magpcss.org/ceforum/apidocs3/projects/(default)/CefResponseFilter.html#Filter(void*,size_t,size_t&,void*,size_t,size_t&)

The `upstream` examples are https://bitbucket.org/chromiumembedded/cef/src/669e8673ce5dadee035eed19920fe3538492ccd2/tests/cefclient/browser/response_filter_test.cc?at=master&fileviewer=file-view-default

`Pull Requests` welcome.

**Comment by amaitland** [comment]
Follow up I actually think is is a bug in `CEF`, it doesn't seem logical for `data_in_size` to be greater than `data_out_size` in this context.

**Comment by juongithub** [comment]
I agree with you probably it is a bug in libcef.dll

**Comment by amaitland** [comment]
Not totally related, though posting just as a reference. There appears to be problems with the `Responsefilter` implementation see https://bitbucket.org/chromiumembedded/cef/issues/2282/cefrequestfilter-filter-should-be-called

**Comment by honestabelink** [comment]
As per the documentation - 

> https://magpcss.org/ceforum/apidocs3/projects/(default)/CefResponseFilter.html <br> "Expected usage is as follows: A. Read input data from |data_in| and set |data_in_read| to the number of bytes that were read up to a maximum of |data_in_size|... B. Write filtered output data to |data_out| and set |data_out_written| to the number of bytes that were written up to a maximum of |data_out_size|... C. Return RESPONSE_FILTER_DONE if all output data was written or RESPONSE_FILTER_NEED_MORE_DATA if output data is still pending."

The example filter [MemoryStreamResponseFilter](https://github.com/cefsharp/CefSharp/blob/a10a5ef897ce4c8aac5baf7bf024c6b2f82e3c2a/CefSharp.Example/Filters/MemoryStreamResponseFilter.cs#L32) does not accurately follow documentation.

1. if the `data_out` buffer is too small, ie  `data_in_size` > `data_out_size` , applications should return `RESPONSE_FILTER_NEED_MORE_DATA` and copy `data_size_out` bytes from `data_in` to `data_out`.
2. Set `data_in_read` equal to the number of bytes read from `data_in`.
3. Set `data_out_written` equal to the number of bytes written from `data_in` to `data_out`.

The main takeaways are `dataInRead` should just be the number of bytes read from `dataIn`. And not the length of the input buffer as you have done currently. And obviously don't overflow the `dataOut` buffer :)

In cases where, `dataIn.Length > dataOut.Length`,  the overflow will happen.

Resolves this issue for me :
```c#
FilterStatus IResponseFilter.Filter(Stream dataIn, out long dataInRead, Stream dataOut, out long dataOutWritten)
{
    if (dataIn == null)
    {
        dataInRead     = 0;
        dataOutWritten = 0;
        return FilterStatus.Done;
    }

    dataOutWritten = Math.Min(dataIn.Length, dataOut.Length);
    dataInRead     = dataOutWritten;

    byte[] readBytes = new byte[dataOutWritten];
    dataIn.Read  (readBytes, 0, (int)dataOutWritten);
    dataOut.Write(readBytes, 0, (int)dataOutWritten);

    //copy data to filter memory stream
    memoryStream.Write(readBytes, 0, (int)dataOutWritten);

    if (dataOutWritten < dataIn.Length)
        return FilterStatus.NeedMoreData;
    else
        return FilterStatus.Done;
}
```

**Comment by amaitland** [comment]
@honestabelink In my opinion you shouldn't need to ask for more data in a pass thru type scenario, the cefclient upstream example has similar code see https://bitbucket.org/chromiumembedded/cef/src/07f57223a87f634dbb7ba6b3960251225413b9ac/tests/cefclient/browser/response_filter_test.cc#lines-177

It just isn't logical and should be discussed on https://magpcss.org/ceforum/viewforum.php?f=6 to see guidance from the CEF maintainer. 

Thanks for the example, it's always been possible to work around the issue, I personally have had no need to rewrite the example. By all means submit a PR, additional code comments should be added to describe what's happening in detail.

**Comment by amaitland** [comment]
@honestabelink Please don't edit your posts to add new detail, edits are not included in the email notifications. 

Looking at the link you've added, short term the example should be updated. Possibly the CEF pass thru example should also be updated.

**Comment by amaitland** [comment]
The examples have been updated, minimal tested has been performed. Remember these filters are only provided as a rough example to get you started. If you experience further problems you should 
 read the `CEF API Doc` at https://magpcss.org/ceforum/apidocs3/projects/(default)/CefResponseFilter.html

If you need help implementing a responsefilter for a specific scenario then you should ask questions on https://magpcss.org/ceforum/index.php

`PR's` with further improvements are welcome.
