### ISSUE TITLE
ERROR 6000: renderer not avaible

### ISSUE THREAD

**Issue by pinkcake** [cefsharp/CefSharp#2435]
Hey today I wanted to integrate movie from youtube or twitch on my APP from CefSharp latest version, but I have big problem...

I got this error "6000: renderer not avaible", I don't understand I use pepflashplayer.dll...

**Here is my source code:**
```csharp
            settings.CefCommandLineArgs.Add("enable-npapi", "1");

            settings.CefCommandLineArgs.Add("ppapi-flash-path", @"C:\Windows\SysWOW64\Macromed\Flash\FlashUtil_ActiveX.dll");

            settings.CefCommandLineArgs.Add("ppapi-flash-version", "28.0.0.161");

            browser = new ChromiumWebBrowser("https://www.twitch.tv/");
```

Best regards, and sorry for my english ;/

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/wiki/General-Usage#adobe-flash-player-pepper-flash

Your command line arguments are incorrect for pepper flash.
