### ISSUE TITLE
Support .Net Core

### ISSUE THREAD

**Issue by naster01** [cefsharp/CefSharp#2438]
I will open this up for ideas of how to port this to .Net Core. My personal need is the headless portion of CEF for .Net Core.

**Comment by amaitland** [comment]
> There is no .Net Core version - .Net Core lacks C++/CLI support see https://github.com/dotnet/coreclr/issues/659#issuecomment-91341753

https://github.com/cefsharp/CefSharp/wiki/General-Usage#need-to-knowlimitations

Check out `CefGlue` or `ChromiumFx` as alternatives.

**Comment by amaitland** [comment]
> There is no .Net Core version - Microsoft has started implementing C++/CLI as part of .Net Core you can track the issue https://github.com/dotnet/coreclr/issues/18013 They are only adding support for Windows initially. See also https://github.com/dotnet/coreclr/issues/659

`.Net Core` will support mixed mode assemblies on **Windows Only**, when this is has been implemented we will reconsider adding `.Net Core` support.

**Comment by amaitland** [comment]
Subscribe to  #2796 to track the progress.
