### ISSUE TITLE
How can i do.. change TitleChanged event when i after set  SetAsChild the Popup 

### ISSUE THREAD

**Issue by AtlantisDe** [cefsharp/CefSharp#2439]
> PS. excuse my English...i only know a little English.... 

> i  want to do  like  this...

`ChromiumBrowser control = new ChromiumBrowser(url);
 control.TitleChanged += OnBrowserTitleChanged;`

> Current i do the thing..

>  public bool OnBeforePopup(IWebBrowser browserControl, IBrowser browser, IFrame frame, string targetUrl, string targetFrameName, WindowOpenDisposition targetDisposition, bool userGesture, IPopupFeatures popupFeatures, IWindowInfo windowInfo, IBrowserSettings browserSettings, ref bool noJavascriptAccess, out IWebBrowser newBrowser)
 {
//here i set the new popup to my tab 
//

if (owner != null)
{
var control = new Control { Dock = DockStyle.Fill  };
control.CreateControl();
owner.AddTab(control, targetUrl);
var rect = control.ClientRectangle;
windowInfo.SetAsChild(control.Handle, rect.Left, rect.Top, rect.Right, rect.Bottom);
}

}

> after..popup...
i  get the  object is CefBrowserWindow .. object type is 'CefBrowserWindow'
so  the object is not  a ChromiumBrowser , so  i can not  write the  TitleChanged event...

> i need your help 
any help is  welcome   Thanks very much...

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
See http://cefsharp.github.io/api/63.0.0/html/T_CefSharp_IDisplayHandler.htm

**Comment by artem-voropaev** [comment]
The question is still actual!!
When handle popus like windowInfo.SetAsChild(..) there is no way to get popup title, IDisplayHandler operates parent CromiumWebBrowserControl and TitleChangedEventArgs in OnTitleChanged method doesn't have IBrowser. 
How to solve this?

**Comment by amaitland** [comment]
As stated above this is not a support forum, if you have a question please ask it on https://stackoverflow.com/questions/tagged/cefsharp

**Comment by amaitland** [comment]
@artem-voropaev Please open a new issue, please use the template provided https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report

Commenting on old closed threads is discouraged.

**Comment by amaitland** [comment]
I have created #3185 to track adding the `IBrowser` to the EventArgs.
