### ISSUE TITLE
CamelCaseJavascriptNames not working for returned objects.

### ISSUE THREAD

**Issue by frederikstonge** [cefsharp/CefSharp#2442]
- **What version of the product are you using?**
 63.0.0

- **What architecture x86 or x64?**
x86

- **On what operating system?**
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What is the expected output? What do you see instead?**
Registered objects using CamelCaseJavascriptNames options set to true in BindingOptions doesn't apply to objects returned by methods. (properties of complex objects).

 I was expecting objects marshalled to the javascript to follow the same pattern.

**Comment by amaitland** [comment]
It's been that way for a long time and unfortunately changing the behaviour would be a subtle breaking change for upgrading users.

**Comment by amaitland** [comment]
**This only applies to the `Async Javascript Binding`**

For compatibility reasons the standard naming is still the default. To have returned object names camcel cased you simply have to use the new `CefSharp.JavascriptBinding.CamelCaseJavascriptNameConverter`.

```c#
JavascriptObjectRepository.NameConverter = new CefSharp.JavascriptBinding.CamelCaseJavascriptNameConverter ();

//Before
objectRepository.Register("myObject", new MyObject(), new BindingOptions { CamelCaseJavascriptNames = true});

//After
objectRepository.NameConverter = new CefSharp.JavascriptBinding.CamelCaseJavascriptNameConverter ();
objectRepository.Register("myObject", new MyObject(), new BindingOptions { });
```

You can also implement the `IJavascriptNameConverter` interface and implement your own naming conversion

**Comment by jmarkyston** [comment]
My `ChromiumWebBrowser` instance's `JavascriptObjectRepository` object doesn't have a `NameConverter` property. What am I missing? Is this not yet released to Nuget? Is there a pre-release version I can download from there somehow or anything? I would really like to access this feature.

**Comment by amaitland** [comment]
If you look at the milestone you'll see this will be in version 85. There is no pre release yet.

**Comment by amaitland** [comment]
You can subscribe to release only notifications to be notified when a new version is available https://docs.github.com/en/github/managing-subscriptions-and-notifications-on-github/viewing-your-subscriptions#configuring-your-watch-settings-for-an-individual-repository
