### ISSUE TITLE
how can i  get the IBrowser browser object after windowInfo.SetAsChild()

### ISSUE THREAD

**Issue by AtlantisDe** [cefsharp/CefSharp#2444]
i in here  onBeforePopup  do this 
 

public bool OnBeforePopup(IWebBrowser browserControl, IBrowser browser, IFrame frame, string targetUrl, string targetFrameName, WindowOpenDisposition targetDisposition, bool userGesture, IPopupFeatures popupFeatures, IWindowInfo windowInfo, IBrowserSettings browserSettings, ref bool noJavascriptAccess, out IWebBrowser newBrowser)
{
//here i set the new popup to my tab
//

if (owner != null)
{
var control = new Control { Dock = DockStyle.Fill };
control.CreateControl();
owner.AddTab(control, targetUrl);
var rect = control.ClientRectangle;
windowInfo.SetAsChild(control.Handle, rect.Left, rect.Top, rect.Right, rect.Bottom);
}

}

then....

i want  in  
var control = new Control
 
the  control ' object ...  get  the browser  object

how can i  do  that  

i need your help
any help is welcome Thanks very much...
PS. excuse my English...i only know a little English....

the  about link : How can i do.. change TitleChanged event when i after set SetAsChild the Popup
https://github.com/cefsharp/CefSharp/issues/2439

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage
