### ISSUE TITLE
Null Pointer exception in JavascriptAsyncMethodHandler::Execute when refresh from DevTools

### ISSUE THREAD

**Issue by Michael-Tajmajer-Emrsn** [cefsharp/CefSharp#2445]
- **What version of the product are you using?**
65.0.0.pre02

- **What architecture x86 or x64?**
x86

- **On what operating system?**
win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**

winforms.
 
- **What steps will reproduce the problem?**

Here is the tough part, we are calling an async bridge function, and somebody presses f5 in the debugging tools.

In CefSharp.BrowserSubprocess.Core/Async/JavascriptAsyncMethodHandler.cpp:

The call to:
//this will create a promise and give us the reject/resolve functions {p: Promise, res: resolve(), rej: reject()}
                auto promiseData = promiseCreator->ExecuteFunctionWithContext(context, nullptr, CefV8ValueList());

promiseData comes back as null -- this tears down the whole process.

we added this to the code, which isn't perfect, but keeps the process from crashing.

                //this will create a promise and give us the reject/resolve functions {p: Promise, res: resolve(), rej: reject()}
                auto promiseData = promiseCreator->ExecuteFunctionWithContext(context, nullptr, CefV8ValueList());
				//when refreshing the browser this is sometimes null, in this case return false and get out
				if(nullptr == promiseData) return false;

**Comment by amaitland** [comment]
PR welcome

**Comment by amaitland** [comment]
Also please update the title to more descriptive.

**Comment by amaitland** [comment]
Changes from #2446 have been merged into `master` and `cefsharp/65`
