### ISSUE TITLE
how to update settings or finalize and restart CefSharp.Cef?

### ISSUE THREAD

**Issue by JamesMaxwel** [cefsharp/CefSharp#2447]
is it possible to update the settings after cef has been initialized? I need to change the proxy for each page the user visits.

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage
