### ISSUE TITLE
"Browser is already initialized" error when calling "RegisterJsObject " and running mutliple instances of the program

### ISSUE THREAD

**Issue by gfox1984** [cefsharp/CefSharp#2452]
- **What version of the product are you using?**
    - 63.0.3

- **What architecture x86 or x64?**
    - x86

- **On what operating system?**
    - Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - OffScreen

- **What steps will reproduce the problem?**

When I run several instances of my application simultaneously, I usually receive the following error:

> Browser is already initialized. RegisterJsObject must becalled before the underlying CEF browser is created.

However, I believe that I am registering my JS object as soon as it can possibly be registered. The code looks like this:

```
CefSettings settings = new CefSettings()
{
  BrowserSubprocessPath = @"x86\CefSharp.BrowserSubprocess.exe"
};
Cef.Initialize(settings, performDependencyCheck: false, browserProcessHandler: null);

CefSharpSettings.LegacyJavascriptBindingEnabled = true;

ChromiumWebBrowser chromium = new ChromiumWebBrowser();
chromium.RegisterJsObject("external", myObject, new BindingOptions { CamelCaseJavascriptNames = false });
```

- **What is the expected output? What do you see instead?**

I'm expecting the object to be registered without error, as it is the case when I run a single instance of my application. Instead I'm getting the error reported below.

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information
      - System.Exception: Browser is already initialized. RegisterJsObject must becalled before the underlying CEF browser is created.
   at CefSharp.OffScreen.ChromiumWebBrowser.RegisterJsObject(String name, Object objectToBind, BindingOptions options) in c:\projects\cefsharp\CefSharp.OffScreen\ChromiumWebBrowser.cs:line 593

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
      - No

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
      -  Running about 10 instances on the same URL and take screenshots. Each instance of my application uses one instance of ChromiumWebBrowser.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

    - n/a

**Comment by amaitland** [comment]
The default behaviour is to automatically create the browser. You should defer creation of the browser by setting `automaticallyCreateBrowser = false` for the browser constructor then create the browser after you've finished registering your options. The browser is created in an `async` fashion. The exception you are seeing is expected if the browser has been created, which you will need to control yourself.

http://cefsharp.github.io/api/63.0.0/html/M_CefSharp_OffScreen_ChromiumWebBrowser__ctor.htm
http://cefsharp.github.io/api/63.0.0/html/M_CefSharp_OffScreen_ChromiumWebBrowser_CreateBrowser.htm

**Comment by gfox1984** [comment]
Thanks @amaitland , using the `automaticallyCreateBrowser = false` parameter and calling `CreateBrowser `method after `RegisterJsObject` solved the problem. 

Shame I didn't know about this option and sorry for the hassle.

**Comment by amaitland** [comment]
Added an additional comment in commit https://github.com/cefsharp/CefSharp/commit/b779d2b56769fc4c2a9b0074d322fc1e76c4d24d that hopefully clarifies.
