### ISSUE TITLE
Feature Request - Investigate LargeAddressAware nuget package

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#2453]
https://www.nuget.org/packages/LargeAddressAware
https://github.com/KirillOsenkov/LargeAddressAware

**Comment by chris-araman** [comment]
If it helps: This is only useful on .EXEs, not .DLLs, and only when the .EXE wasn't linked with `/LARGEADDRESSAWARE` in the first place.

**Comment by amaitland** [comment]
Should suite our requirements just fine 👍

**Comment by amaitland** [comment]
As we are using `editbin` to also set `/TSAWARE` I'm going to just leave things are they are.
