### ISSUE TITLE
How Do I Disable cef Asking for Keychain Access? 

### ISSUE THREAD

**Issue by zhizlm** [cefsharp/CefSharp#2454]
[0713/165952:ERROR:transport_security_state.cc(707)] Rejecting public key chain
for domain doubleclick.net. Validated chain: sha1/rbEPbbIA8BIRaHzbePO6LvCMF/w=,s

How to allow this?

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
Start with http://cefsharp.github.io/api/63.0.0/html/M_CefSharp_IRequestHandler_OnCertificateError.htm

If you require further assistance ask on http://magpcss.org/ceforum/index.php

**Comment by zhizlm** [comment]
errorCode:SslPinnedKeyNotInCertChain

**Comment by amaitland** [comment]
You should ask on ceforum

**Comment by zhizlm** [comment]
OK,thx! I asked on chatting room.
