### ISSUE TITLE
OnOpenUrlFromTab still opens blank tab window

### ISSUE THREAD

**Issue by imPRAGMA** [cefsharp/CefSharp#2457]
- **What version of the product are you using?**
    v63

- **What architecture x86 or x64?**
    x86

- **On what operating system?**
    - Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WinForms

- **What steps will reproduce the problem?**
    Just click a target="_blank" href, it will cause it to occur.

- **What is the expected output? What do you see instead?**
   If you return true, im expecting nothing to show.

- **Please provide any additional information below.**
    Override OnOpenUrlFromTab(), and simply return true and it occurs. A workaround would be to do: frame.Browser.CloseBrowser(true); but it still flashes onscreen.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

    Not 100% sure, but probably does.

**Comment by amaitland** [comment]
Will need to be fixed in CEF, likely related to https://bitbucket.org/chromiumembedded/cef/issues/2028/cefrequesthandler-onopenurlfromtab-gets

Closing as upstream
