### ISSUE TITLE
Background rendering for offscreen giving blue background in version 65.0.0

### ISSUE THREAD

**Issue by GrabzIt** [cefsharp/CefSharp#2459]
- **What version of the product are you using?**
    65.0.0 Nuget

- **What architecture x86 or x64?**
   x86

- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
   Offscreen

- **What steps will reproduce the problem?**
    Set a background color like 0255255255 and visit a website were the background color hasn't been set like http://news.bbc.co.uk and it will appear bright blue

- **What is the expected output? What do you see instead?**
   A normal white background

**Comment by amaitland** [comment]
I believe this was supposed to have been fixed in https://bitbucket.org/chromiumembedded/cef/issues/2369/setting-the-background-color-for-osr

Will have a look when I'm in front of a computer

**Comment by amaitland** [comment]
The `CEF` changes are definitely included in the build that version `65` is based off

https://bitbucket.org/chromiumembedded/cef/commits/branch/3325

**Comment by GrabzIt** [comment]
That is strange. I have double checked all of the DLL's come from the new nugget release.

**Comment by amaitland** [comment]
It may not have been fixed in all cases. Which class are you using to set the background color?

**Comment by GrabzIt** [comment]
I was doing:

BrowserSettings settings = new BrowserSettings();
settings.BackgroundColor = 0255255255;

And it was working in previous versions, I just tried:

BrowserSettings settings = new BrowserSettings();
settings.BackgroundColor = 0xFFFFFFFF;

and it worked! Thanks for your help ;-D Weird how defining colours changed though.
