### ISSUE TITLE
How to forbid image loading from the network

### ISSUE THREAD

**Issue by ysh512** [cefsharp/CefSharp#2462]
I use the code below to disable image loading，but it did not work，
_browser.BrowserSettings.ImageLoading = CefState.Disabled;

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
> _browser.BrowserSettings.ImageLoading = CefState.Disabled;

Make sure you set the value immediately after you create the `ChromiumWebBrowser` instance. You cannot change the value dynamically using this method.
