### ISSUE TITLE
js can call async c# function only once

### ISSUE THREAD

**Issue by humanww** [cefsharp/CefSharp#2465]
I try  js callback with async c# function ,  it is success on the first time , but it do not work while click button to trigger function..

**Comment by humanww** [comment]
js function :
 test(){
      JsObj.showTest("alert", (msg)=>{
        console.log("js :"+msg)
        console.log(JsObj)
      })
    },
main window:
 public MainWindow()
        {
            InitializeComponent();
            browser.Address = @"http://localhost:8080/#/";
            CefSharpSettings.LegacyJavascriptBindingEnabled = true;
            browser.RegisterAsyncJsObject("JsObj", this);

            
        }
c# function :
public async Task ShowTest(string msg, IJavascriptCallback Success)
        {

            MessageBox.Show(msg);
            await Success.ExecuteAsync(msg);
        }

**Comment by amaitland** [comment]
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Also please fork the https://github.com/cefsharp/CefSharp.MinimalExample project and provide an example that reproduces your problem.

**Comment by amaitland** [comment]
Your code needs formatting, see https://guides.github.com/features/mastering-markdown/

**Comment by amaitland** [comment]
> DO NOT REGISTER YOUR FORM/WINDOW/CONTROL. Create a class and proxy calls if required.

https://github.com/cefsharp/CefSharp/wiki/General-Usage#binding-an-object-in-javascript

You should never bind your `Window` object, it's got all sorts of methods that should never be exposed in `JS`.

**Comment by amaitland** [comment]
If there is no further response in another week this will be closed.

**Comment by amaitland** [comment]
Closing due to lack of feedback. To reopen you will need to provide a complete example that reproduces your problem, see above for instructions.
