### ISSUE TITLE
CefSharp.Offscreen does not run inside a Docker container

### ISSUE THREAD

**Issue by gfox1984** [cefsharp/CefSharp#2469]
- **What version of the product are you using?**
    - Sources from cefsharp/63 branch

- **What architecture x86 or x64?**
    - x86

- **On what operating system?**
    - Microsoft Windows Server 2016 Datacenter (this is inside a Docker container)

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - Offscreen

- **What steps will reproduce the problem?**
    - Build the project called CefSharp.OffScreen.Example
    - Copy the binaries to your docker container + the redistributable DLLs from Visual Studio
    - Run CefSharp.OffScreen.Example.exe from the command line

- **What is the expected output? What do you see instead?**
    - The following error occurs: ![error](https://user-images.githubusercontent.com/14998184/43077807-d5b121d8-8e88-11e8-85e4-2dff9bb9b7ae.png)

- **Please provide any additional information below.**
    - No log, the crash occurs before initialization
    - See system info: ![sysinfo](https://user-images.githubusercontent.com/14998184/43077958-392ded18-8e89-11e8-9126-b4af270d64e3.png)
    - The example runs fine when not in a docker container. We're using CefSharp to take screenshots on the server and are migrating towards Docker so we need a solution or understanding of the problem.

**Comment by jankurianski** [comment]
It appears to be a problem with C# not being able to look up one of the native resources linked to by CefSharp.  This happens in other contexts too.  There could be several reasons for the error:
https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#Runtime_dependencies

**Comment by gfox1984** [comment]
Hi,

I have double checked the FAQ:

  4.1 => done
  4.2 => files are present, except for CefSharp.Wpf.dll and CefSharp.WinForms.dll, but we're using the OffScreen example here, so there's not needed.
  4.3 => n/a
  4.4 => done

A few more precisions:

- we're compiling in Release mode
- the compiled binaries run fine on our server (Windows Server 2016), but it does not run inside the server inside the Docker container (Windows Server 2016 Datacenter)
- the server inside the Docker container is **without UI**
- the error logged seems to point to KERNELBASE.dll

Is there more DLLs than documented required to be present on the system to run CefSharp Offscreen?

**Comment by jankurianski** [comment]
The key part of the error for me is:
`FileNotFoundException: Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found.`
indicating that .NET cannot locate a required dependency.

Have you set the working directory of Docker to the directory that contains your exe and all the dependencies?

I thought I should mention that this may be the first time anyone has tried using CefSharp in a Docker container.  I wouldn't expect it to work.

Why not get a simpler example working first, for example, a .NET Console application that relies on another C# DLL in the same directory.  If that works, add a dependency on a C++/CLI DLL that loads a native C DLL.  In that way, you're re-creating the complexity of CefSharp's dependencies and proving that it should work in Docker.

**Comment by fuzzykiller** [comment]
CefSharp 63 requires The Visual C++ Runtime 2013. Are you sure that is installed inside your container?

**Comment by gfox1984** [comment]
The Visual C++ Runtime 2013 redistributable DLLs are copied next to CefSharp DLLs.

**Comment by fuzzykiller** [comment]
Ah, wait. You mentioned you used the sources. That means you need the Visual C++ Runtime matching the compiler you used. If it’s a Windows Core installation inside the Docker container, important DLLs (GDI, DirectX and whatnot) may be missing, too. Check with Dependency Walker what CefSharp.Core requires and verify those libraries are available inside the container.

To diagnose binding errors, the fusion log could help, but I don’t know how to deal with it inside a Docker container.

**Comment by gfox1984** [comment]
Sorry I didn't not compile CefSharp itself from the sources. I compiled the CefSharp.OffScreen.Example project from the sources which uses the nuget packages:

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="cef.redist.x64" version="3.3239.1723" targetFramework="net452" />
  <package id="cef.redist.x86" version="3.3239.1723" targetFramework="net452" />
</packages>
```

Note that the compiled OffScreen example runs fine on the other server we have (the one without Docker) when we include the Visual C++ Runtime 2013 redistributable DLLs (it doesn't work without them).

We'll try to do more investigations in the coming days. We checked the dependencies, but there are many. We need to allocate some time to check them all.

**Comment by gfox1984** [comment]
@jankurianski this is to let you know that I ran this simple program on Docker: https://stackoverflow.com/a/14967825/1010492

It does load some native libraries, and it runs OK.

I also tried setting the working directory to the directory of the assembly in CefSharp.OffScreen.Example but it made no difference (still the same error):

```
string exeDir = System.IO.Path.GetDirectoryName(Assembly.GetEntryAssembly().Location);
Directory.SetCurrentDirectory(exeDir);
```

**Comment by gfox1984** [comment]
@fuzzykiller: you were right, I needed the redistributables for Visual C++ Runtime 2017 too (I compiled with Visual Studio 2017)... The OffScreen example works on the Docket container with them.

You can close the issue :)

**Comment by amaitland** [comment]
> I needed the redistributables for Visual C++ Runtime 2017 too

If you built with `VS2017` then you will only need the `VC++2017` runtime (technically it's compatible with the `VC++2015` runtime so you should be able to swap.

Closing this as `invalid`, in future please use https://github.com/cefsharp/CefSharp.MinimalExample for testing as it uses the `Nuget` packages.

**Comment by gfox1984** [comment]
For reference, I would like to mention that the Offscreen minimal example does not work on the current Windows Server 2019 images on Docker.

See https://github.com/Microsoft/aspnet-docker/issues/170 and https://github.com/docker/for-win/issues/3438.
