### ISSUE TITLE
WPF/LifeSpanHandler : PopUp also closes when DevTools is closed

### ISSUE THREAD

**Issue by angshuman-agarwal** [cefsharp/CefSharp#2472]
- **What version of the product are you using?**
v63.0.3 NuGet

- **What architecture x86 or x64?**
 x64 and x86 both places it is reproducible

- **On what operating system?**
 Win7

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**

**Short Version:**
Copy paste the [LifeSpanHandler](https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf.Example/Handlers/LifespanHandler.cs) and associate with CefSharp browser. Now run the Project and `right click ShowDevTools`. Now close the `DevTools`. PopUp window also closes. Only `DevTools` should have **closed**.

**Long version:**
I have implemented [LifeSpanHandler ](https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf.Example/Handlers/LifespanHandler.cs)to handle `PopUps`. It works fine **until** I launch `DevTools` via `Context Menu` or `F12` and try to close it. Once I close `Dev Tools`, it closes the entire PopUp window i.e. `ILifeSpanHandler.DoClose` is called which returns false which in turn would raise `WM_CLOSE` and then `ILifeSpanHandler.OnBeforeClose` is called where the condition gets satisfied and it closes the Entire PopUp.

But, if I add this piece of code in `ILifeSpanHandler.OnBeforeClose`, then DevTools get closed (because of `DoClose` I think), but, this stops the PopUp window from closing as I `return;` in the code with this piece of fence -  
```

            if (browser.MainFrame.Url.Equals("chrome-devtools://devtools/inspector.html"))
            {
                return ;
            }

```

**but** the problem now is that, if, I manually try to close the `PopUp window` (which is a `WPF window`) then `DoClose` and `OnBeforeClose` will not be raised i.e. it loses the LifeSpan cycle only when DevTools is associated.

**Till I do not launch DevTools, everything works as expected**

- **What is the expected output? What do you see instead?**
Expected Outut - Only DevTools is supposed to Close when I close DevTools
What I see - It closes the entire PopUp which launched the DevTools.

- **Please provide any additional information below.**
    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
No. Nothing observed in logs except `console.log` messages from the App.

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
NA

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

No; I tested by running `cefclient --multi-threaded-message-loop --off-screen-rendering-enabled`
And then visiting pages which have PopUps. It works fine when I right click `ShowDevTools` and on closing DevTools, it only closes the DevTools and not the entire PopUp window.

**Comment by amaitland** [comment]
So your using the code that's marked as **experimental**?

**Comment by angshuman-agarwal** [comment]
Yes.

**Comment by angshuman-agarwal** [comment]
Thanks Alex. I tried putting that fence (if statement with dev tools). But that just prevents closing of pop up and next time when I try to close pop up, the life cycle is lost. Works fine till dev tools is not launched.

Why doea dev tools also think I am the same.pop up ?

If you can give any clues here ?

**Comment by angshuman-agarwal** [comment]
Thanks.
OK - I see here - what you mean : https://bitbucket.org/chromiumembedded/cef/issues/1949/
So, is it an [upstream issue](https://github.com/amaitland) as this entire feature is [experimental](https://github.com/amaitland) in `CEF` itself ?

**Comment by amaitland** [comment]
> Copy paste the LifeSpanHandler and associate with CefSharp browser. Now run the Project and right click ShowDevTools. Now close the DevTools. PopUp window also closes. Only DevTools should have closed.

How did a `Popup Window` get opened? When providing a list of steps to reproduce please provide them in bullet point form, forget about the long and short versions, detail is important.

**Comment by amaitland** [comment]
I have updated the **NOTE** to make it clearer that the example code is incomplete see https://github.com/cefsharp/CefSharp/commit/0f240f9510ed2af0f6347968739d1059ccb39202

**Comment by angshuman-agarwal** [comment]
>How did a Popup Window get opened?

*Used the existing LifeSpanHandler code.*

This [code](https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf.Example/Handlers/LifespanHandler.cs#L45) creates the PopUp window

This code [opens](https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf.Example/Handlers/LifespanHandler.cs#L98) the PopUp Window

> If you would like to make improvements then please submit a PR including a test case

Thank you for the Note. In the note you have mentioned this line. Does it means the LifeSpanHandler in the *.Net version* has to be improved or is it an upstream requirement (i.e. from the native side - CEF project) ?

**Comment by angshuman-agarwal** [comment]
> Is Devtools being opened in a wpf window ?

DevTools is opened via `ShowDevTools` call via the PopUp Window. I hook `F12` Key on the `PopUp window` and in the handler, I directly call Api the on the IWebBrowser which opens the DevTools - (https://github.com/cefsharp/CefSharp/blob/cd934267c65f494ceb9ee75995cd2a1ca0954543/CefSharp.Wpf.Example/MainWindow.xaml.cs#L113)

**Comment by amaitland** [comment]
Where in your list of steps does it say open a popup window? As I've already asked provide a step by step list in bullet point form.

As per the issue template fork https://github.com/cefsharp/CefSharp.MinimalExample to provide an example of your code.

**Comment by angshuman-agarwal** [comment]
Thank you. I will do that. I am outside at the moment, typing from my Phone.

**Comment by angshuman-agarwal** [comment]
> As per the issue template fork https://github.com/cefsharp/CefSharp.MinimalExample to provide an example of your code.

**Here it is :** https://github.com/angshuman-agarwal/CefSharp.MinimalExample

Have modified the WPF project. Added 2 Html files for testing and the [LifeSpanHandler](https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf.Example/Handlers/LifespanHandler.cs) code. Also modified MainWindow.xaml.cs to set the Browser's `Address` to the Main Html Page.

**Comment by amaitland** [comment]
Where are the list of steps to reproduce? This is the third time I have asked, I won't ask again. 

Please squash all your commits into one so it's easier to review.
