### ISSUE TITLE
Bug Captcha: TabForm: CefSharp.BrowserSubprocess.exe + EvaluateScriptAsync + Google Recaptcha

### ISSUE THREAD

**Issue by dquirino** [cefsharp/CefSharp#2473]
### Bug Report
- **Version 67.0.0.0
- **Win10, x86, WinForms

- **What steps will reproduce the problem?**
Test Link: https://www.google.com/recaptcha/api2/demo
  
1-Google Recaptcha only works on minimal version or MinimalBrowserForm because:
1.1-settings.BrowserSubprocessPath = "MyApp.exe";
1.2-//const bool multiThreadedMessageLoop = true;  IS NOT USED.

When you try using this page on TabBrowerForm (BrowerForm.cs) that uses:
-settings.BrowserSubprocessPath = "CefSharp.BrowserSubprocess.exe"; 
-settings.Cache="cache"; (I think its a problem too, must be commented to  work), 
the google captha become so slow and do not pass on correct choices.

When you chance TabBrowerForm to use settings.BrowserSubprocessPath = "MyApp.exe" and comment 
settings.Cache, the google captcha works and pass.

2-But if you change TabBrowerForm to work with recaptha, the EvaluateScriptAsync freeze and stop work because it need to be configured as  settings.BrowserSubprocessPath = "CefSharp.BrowserSubprocess.exe" to work; 

- **Does this problem also occur in the `CEF` Sample Application http://opensource.spotify.com/cefbuilds/index.html?** 
R: No, because this example has only simple browser, single process.

So, I the conclusion is that is impossible in this version to run google recaptcha and javascript in sabe application. 

Is it possible fix this bug at initialization (best option) or release a method to change settings.BrowserSubprocessPath settings in runtime (temporary workaround)?

Thanks

**Comment by amaitland** [comment]
> 2-But if you change TabBrowerForm to work with recaptha, the EvaluateScriptAsync freeze and stop work because it need to be configured as settings.BrowserSubprocessPath = "CefSharp.BrowserSubprocess.exe" to work;

`EvaluateScriptAsync ` requires functionality implemented in `CefSharp.BrowserSubprocess.exe`, it's not possible to use this method without using `CefSharp.BrowserSubprocess.exe`.

> Is it possible fix this bug at initialization (best option)

What bug?

> release a method to change settings.BrowserSubprocessPath settings in runtime (temporary workaround)?

`CEF` does not support changing subprocesses at runtime. So this is not an option.


> the google captha become so slow and do not pass on correct choices.

Many people have created bots using `CefSharp`, and `Google` have basically blacklisted `CefSharp`. `Recaptcha` being very difficult to solve is a known issue and as we have no control of how `Recaptcha` functions is not something we can easily fix.

You can build your own version of `CefSharp` from source and strip out all the functionality that you don't need from `CefSharp.BrowserSubprocess` and see if you can make it work. This is not a supported approach. 

If you have further questions please ask them on https://gitter.im/cefsharp/CefSharp

**Comment by amaitland** [comment]
For the last discussion on `Recaptcha` you should see #1999
