### ISSUE TITLE
I get an issue OnGotFocus when using FATabStrip SharpTab

### ISSUE THREAD

**Issue by Daszbinn** [cefsharp/CefSharp#2476]
What version of the product are you using?
v67.0.0-CI2695 Myget
https://www.myget.org/feed/cefsharp/package/nuget/CefSharp.WinForms/67.0.0-CI2695

What architecture x86 or x64?
x86

On what operating system?
All versions of Windows from Win7 to Win10

Are you using WinForms, WPF or OffScreen?
Winforms

What steps will reproduce the problem?

`// Code Begins
private SharpTab AddNewBrowser(FATabStripItem tabStrip, String url)
{
if (url == "") url = NewTabURL;
ChromiumWebBrowser browser = new ChromiumWebBrowser(url);

        // set config
        ConfigureBrowser(browser);

        // set layout

        browser.Dock = DockStyle.Fill;
        tabStrip.Controls.Add(browser);
        browser.BringToFront();

        // add events
        browser.StatusMessage += Browser_StatusMessage;
        browser.LoadingStateChanged += Browser_LoadingStateChanged;
        browser.TitleChanged += Browser_TitleChanged;
        browser.LoadError += Browser_LoadError;
        browser.AddressChanged += Browser_URLChanged;
        browser.DownloadHandler = dHandler;
        browser.MenuHandler = mHandler;
        browser.LifeSpanHandler = lHandler;
        browser.KeyboardHandler = kHandler;
        browser.RequestHandler = rHandler;

        // new tab obj
        SharpTab tab = new SharpTab
        {
            IsOpen = true,
            Browser = browser,
            Tab = tabStrip,
            OrigURL = url,
            CurURL = url,
            Title = "New Tab",
            DateCreated = DateTime.Now
        };

        // save tab obj in tabstrip
        tabStrip.Tag = tab;

        if (url.StartsWith("codernut:"))
        {
            browser.RegisterAsyncJsObject("host", host);
        }
        return tab;
    }
// Code Ends`

here is the exception image
https://www.dropbox.com/s/9k51ydscozw7e5g/Screenshot%20%2835%29.png?dl=0

**Comment by amaitland** [comment]
Please read http://idownvotedbecau.se/imageofanexception/

**Comment by amaitland** [comment]
Please also format your code see https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

**Comment by amaitland** [comment]
Closing due to lack of feedback.

Enough information to reproduce the problem will be required for this to be reopened.
