### ISSUE TITLE
Initialize multiple instances of CefSharp

### ISSUE THREAD

**Issue by eurus1** [cefsharp/CefSharp#2478]
hi, i using CefSharp 65
i need initialize cef.initialize  multiple because my project use multi browser loading and i need to load multi user agent and multi path for each browser,Is there a way to solve this problem?

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage
