### ISSUE TITLE
SendMouseClickEvent sends click to another instance

### ISSUE THREAD

**Issue by JutGreg** [cefsharp/CefSharp#2479]
- **What version of the product are you using?**

CEFSharp 65.0.0

- **What architecture x86 or x64?**

x64

- **On what operating system?**

Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**

WinForms

- **What steps will reproduce the problem?**

- Create a simple browser with a SendMouseClickEvent, that sends a mouse click some time.
- Compile the files, and copy them to two separate folders
- Start the executable of the browser in both folders

- **What is the expected output? What do you see instead?**

The mouse click happens on the browser, which was opened the second time, although the first opened instance sends it. The clicks should happen on the their own instances.

- **Please provide any additional information below.**

I can't see any output, and the reason why it's causing this.

**Comment by amaitland** [comment]
> It's also reportant to remember that CefSharp is just a wrapper around the Chromium Embedded Framework(CEF), a lot of questions people have aren't actually CefSharp specific, they're generic to CEF and for those CEF has it's own support forum at http://magpcss.org/ceforum/index.php and issue tracker at https://bitbucket.org/chromiumembedded/cef

As the disclaimer that appears in so many places states, `CefSharp` is just a wrapper. Closing this as `upstream` as `SendMouseClickEvent` is just a very basic wrapper see https://github.com/cefsharp/CefSharp/blob/cefsharp/65/CefSharp.Core/Internals/CefBrowserHostWrapper.cpp#L370 the `CEF API` is http://magpcss.org/ceforum/apidocs3/projects/(default)/CefBrowserHost.html#SendMouseClickEvent(constCefMouseEvent&,MouseButtonType,bool,int) as a reference.

> The mouse click happens on the browser, which was opened the second time, although the first opened instance sends it. The clicks should happen on the their own instances.

You should ask on http://magpcss.org/ceforum/index.php though I don't think you'll get very far, I'm pretty sure `CEF` is just wrapping part of the `Chromium API` in this instance.

Your best bet is probably to add some checks in your own code to make sure the window has focus or similar (whatever works for your use case).
