### ISSUE TITLE
Please support Xamarin.Mac

### ISSUE THREAD

**Issue by juepiezhongren** [cefsharp/CefSharp#2481]

**Comment by amaitland** [comment]
`CefSharp` is built with `VC++` and will only run on `Windows`. https://github.com/cefsharp/CefSharp/wiki/General-Usage#software-requirements

Try `CefGlue` or `ChromiumFx`.

**Comment by juepiezhongren** [comment]
@amaitland  i know it's based on vc++, but it is possible to port it for mac

**Comment by amaitland** [comment]
> but it is possible to port it for mac

Based on what exactly? Last I checked `VC++` wasn't included in `.Net Core` see https://github.com/dotnet/coreclr/issues/659#issuecomment-91341753
