### ISSUE TITLE
FrameLoadEnd sometimes throws "The underlying frame is no longer valid - please check the IsValid property before calling"

### ISSUE THREAD

**Issue by GrabzIt** [cefsharp/CefSharp#2486]
- **What version of the product are you using?**
    65.0.0

- **What architecture x86 or x64?**
   x86

- **On what operating system?**
    Windows 2008 R2, Windows 2012

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
   Offscreen

- **What steps will reproduce the problem?**
This seems to happen intermittently and I am not sure exactly why. However it happened in version 63,0.0 as well and seems to be originating from the OnLoadEnd event in c++ so I don't think it is to do with the order methods etc is called by my code. The stacktrace of the error is shown below.

- **What is the expected output? What do you see instead?**

  Always successfully fire LoadEnd event

- **Please provide any additional information below.**

The underlying frame is no longer valid - please check the IsValid property before calling!
   at CefSharp.Internals.CefFrameWrapper.ThrowIfFrameInvalid()
   at CefSharp.Internals.CefFrameWrapper.get_Url()
   at CefSharp.Internals.ClientAdapter.OnLoadEnd(ClientAdapter* , scoped_refptr<CefBrowser>* browser, scoped_refptr<CefFrame>* frame, Int32 httpStatusCode)

**Comment by amaitland** [comment]
> This seems to happen intermittently and I am not sure exactly why. However it happened in version 63,0.0 as well and seems to be originating from the OnLoadEnd event in c++ so I don't think it is to do with the order methods etc is called by my code. The stacktrace of the error is shown below.

Strange that this has never been a problem before, I wonder under what circumstance `frame.IsValid` is `false`. 

Change merged into `cefsharp/67` branch with https://github.com/cefsharp/CefSharp/commit/64aec8f5b3ce665698a8507f643a20d7c77672fc

Pretty sure this should be resolved.

**Comment by amaitland** [comment]
@GrabzIt If this is a show stopping bug for you then let me know and I can look at releasing a `65.0.1` bug fix release.

**Comment by GrabzIt** [comment]
Thanks for the fix :-D It's not a show stopper, but thanks for the offer of a new release!

**Comment by GrabzIt** [comment]
Actually we have just checked our logs and it seems to have happened quite a lot in the last 24 hours alone. It would be great if you could do a bug fix release of version 65 for this, if it is not too much trouble.

Thanks for all your help as always.

**Comment by amaitland** [comment]
Packages are building now see https://ci.appveyor.com/project/cefsharp/cefsharp/build/65.0.0-CI2735

Will give them a quick test and push them to `Nuget.org` hopefully later today.

**Comment by GrabzIt** [comment]
Awesome, thanks!
