### ISSUE TITLE
Cef.ShutDown method closed my parent process  mainwindow

### ISSUE THREAD

**Issue by Tearies** [cefsharp/CefSharp#2487]
- **What version of the product are you using?**
      I used the  ver (65.0.0 and 59.0.0) from Nuget 
- **What architecture x86 or x64?**
     x64
- **On what operating system?**
     Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
      WPF and winfroms
- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.
       1. create a WPF Application with System.Addin .
       2. in the addin create a FrameworkElement to retrun a Visual.
       3. host addin visual to WPF Application.
       4. add some CefSharp.WinForms.ChromiumWebBrowser control  into the step 2 's control.
       5. call CefSharp.Cef.Shutdown(); at addin dispose method.
       6. you will see WPF application will be Closed! 
    - Please no binary (zip, etc) links, fork the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) and push your changes to `GitHub`. (Alternatively use a code sharing service list `Gist` or `Pastebin`).

- **What is the expected output? What do you see instead?**
        I Close the Addin process, My Application will not Closed.

**Comment by amaitland** [comment]
You cannot call `CefShutdown` (the underlying `unmanaged` method) until the browser instances have been disposed of. The `Cef.Shutdown` method will dispose of them to ensure a clean shutdown. To avoid the behaviour you are seeing you must `Dispose` of all your `ChromiumWebBrowser` instances before calling `Cef.Shutdown`. Best that you remove them from their `Parent` before doing so.

There is http://cefsharp.github.io/api/63.0.0/html/M_CefSharp_Cef_ShutdownWithoutChecks.htm though I don't recommend using this method. The simply calls `CefShutdown`, if you still have references to `unmangaed` resources then it will cause a crash.

http://magpcss.org/ceforum/apidocs3/projects/(default)/(_globals).html#CefShutdown()

In general you don't need to explicitly call `Cef.Shutdown`, it will be called when your application exists. See https://github.com/cefsharp/CefSharp/wiki/General-Usage#initialize-and-shutdown

**Comment by amaitland** [comment]
If you require further assistance please ask your questions on https://gitter.im/cefsharp/CefSharp

**Comment by Tearies** [comment]
Plugins and hosts are two different processes

**Comment by amaitland** [comment]
Did you follow the recommendation i gave? Are you Disposing of the browser instances before calling Cef.Shutdown?

 The source code is there you can use the debuger to get a better understanding of what's going on.

Make sure you are calling Cef.Shutdown in the correct process. 

You can use Cef.ShutdownWithoutChecks if you need total control over shutdown.

**Comment by Tearies** [comment]
OK I'll try it, thanks!
