### ISSUE TITLE
WPF - Tooltip goes out of the screen (Monitor) and not visible fully

### ISSUE THREAD

**Issue by arvindlloyds** [cefsharp/CefSharp#2488]
[CodeArvindlloyds.txt](https://github.com/cefsharp/CefSharp/files/2293402/CodeArvindlloyds.txt)
**What version of the product are you using?**
v57.0.0 NuGet

**What architecture x86 or x64?**
x64 

**On what operating system?**
Win7

**Are you using WinForms, WPF or OffScreen?**
WPF

**What steps will reproduce the problem?**
1-Open url - https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_tooltip
2-when opened, broswer screen must be divided in two panels
3-paste text in attached file (CodeArvindlloyds.txt) to left side of the screen
4-press run
5-take your mouse to right side and hover over 'Hover HERE'

**What is the expected output? What do you see instead?**
Expected Outut - all tooltip text must be visible (div title)
What I see - it does not wrap-up as it goes out of monitor screen

Please provide any additional information below.

**Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?**
NA

**Does this problem also occur in the CEF Minimal Application **
yes

**Additional**
This works fine in Chrome and IE. The text wraps up.

**Comment by amaitland** [comment]
For reference https://github.com/cefsharp/CefSharp/blob/cefsharp/67/CefSharp.Wpf/ChromiumWebBrowser.cs#L463

Pull requests welcome.

**Comment by amaitland** [comment]
I've made a minor change that improves long tooltips, see https://github.com/cefsharp/CefSharp/commit/d97d896ac54b0e7bb3e9f72bf40e2215ca3ee017

**Comment by joaompneves** [comment]
I don't see why the CefSharp browser should be different from any other WPF regular control - simply don't wrap. This change makes harder for anyone customizing their tooltips appearance. Usually tooltips contain a string with some text, but now CefSharp browser has a TextBlock.
At least can you make this behavior overridable? I'm having hard time to get rid of the TextBlock.

**Comment by amaitland** [comment]
> I don't see why the CefSharp browser should be different from any other WPF regular control - simply don't wrap.

You are welcome to revert the change and test for yourself, you'll see the problem, no wrapping is applied by default.

> At least can you make this behavior overridable?

If **you** require an overridable behaviour then you are welcome to submit a `PR`. Make sure you test using the example provided above.

**Comment by amaitland** [comment]
If no style is applied then we'll apply a `TextBlock` with wrapping to make sure long text is visible by default. If a style is set then it's up to the user to apply wrapping.
