### ISSUE TITLE
Error: "CefSharp.Common contains unmanaged resoures, set your project and solution platform to x86 or x64"

### ISSUE THREAD

**Issue by fandrei** [cefsharp/CefSharp#2489]
- **What version of the product are you using?**

67.0.0-pre01 installed via NuGet

- **What architecture x86 or x64?**

x64

- **On what operating system?**

Win7 x64 SP1

- **Are you using `WinForms`, `WPF` or `OffScreen`?**

WinForms

- **What steps will reproduce the problem?**

-Create a new WinForms project in VS2017 (15.8.0, .NET 4.7.2)
-Switch platform target to x64
-`install-package CefSharp.WinForms -pre`
-try to compile
`CefSharpTest\packages\CefSharp.Common.67.0.0-pre01\build\CefSharp.Common.targets(4,5): error : CefSharp.Common contains unmanaged resoures, set your project and solution platform to x86 or x64. Alternatively for AnyCPU Support see https://github.com/cefsharp/CefSharp/issues/1714`

Sample app: https://github.com/fandrei/CefSharpTest

**Comment by fandrei** [comment]
Actually, this looks like a bug in VS2017 (project files are messed up, even though they compile)

**Comment by kaleidocore** [comment]
Visual Studio Configuration Manager is absolute crap and buggy as hell. I had the same problem and eventually solved it by restarting VS2017 a million times while mucking about with the configuration manager settings.

**Comment by amaitland** [comment]
The error message was revised in #2287

You must set the project and solution platform.

**Comment by eddamzp** [comment]
> ![capture](https://user-images.githubusercontent.com/43579286/46398695-14526a00-c6f6-11e8-8115-db2c1ff16634.PNG)

This solved my issue instantaneously! thanks!
