### ISSUE TITLE
Error: "Failed to load toolbox item 'ChromiumWebBrowser'.  It will be removed from the toolbox."

### ISSUE THREAD

**Issue by fandrei** [cefsharp/CefSharp#2490]
- **What version of the product are you using?**

67.0.0-pre01 installed via NuGet

- **What architecture x86 or x64?**

x64

- **On what operating system?**

Win7 x64 SP1

- **Are you using `WinForms`, `WPF` or `OffScreen`?**

WinForms

- **What steps will reproduce the problem?**

Sample app: https://github.com/fandrei/CefSharpTest
Open in VS2017 v15.8.0
Try to add the ChromiumWebBrowser control to the form; getting the following error:

```
---------------------------
Microsoft Visual Studio
---------------------------
Failed to load toolbox item 'ChromiumWebBrowser'.  It will be removed from the toolbox.
---------------------------
OK   
---------------------------
```

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/wiki/General-Usage#need-to-knowlimitations
https://stackoverflow.com/a/5379908/4583726

The designer only supports x86 or AnyCpu as targets this is a visual studio limitation.

**Comment by fandrei** [comment]
@amaitland how to use the control, then? The constructor issues a warning: `warning CS0618: 'ChromiumWebBrowser.ChromiumWebBrowser()' is obsolete: 'Should only be used by the designer'`

**Comment by amaitland** [comment]
Use http://cefsharp.github.io/api/63.0.0/html/M_CefSharp_WinForms_ChromiumWebBrowser__ctor_1.htm

See https://github.com/cefsharp/CefSharp.MinimalExample for a working example.

**Comment by fandrei** [comment]
@amaitland thanks. The warning message is wrong and should be fixed, though.

**Comment by amaitland** [comment]
Why is it wrong? It could be more descriptive. It's technically accurate

**Comment by fandrei** [comment]
@amaitland it says "Should **only** be used by the designer"

**Comment by amaitland** [comment]
That is correct, that constructor should only be used by the designer. 

I've made a minor improvement in https://github.com/cefsharp/CefSharp/commit/ce870405bd531ad7e2c95c1a1416c5633c7932a0

**Comment by fandrei** [comment]
@amaitland why? The parameterless constructor seems to be working fine, too.

**Comment by amaitland** [comment]
As the comment says **Should** only be used by the designer. Not all fields will be initialised, and as such it's not supported or recommended. 

This will work
```c#
browser = new ChromiumWebBrowser("www.google.com");
browser.JavascriptObjectRepository.Register("bound", new BoundObject());
```

The following will throw a `NullReferenceException`, as the `paramaterless` constructor doesn't initialise properties.
```c#
browser = new ChromiumWebBrowser();
browser.JavascriptObjectRepository.Register("bound", new BoundObject());
```

There are many other examples that will cause problems.

If you have further questions please ask them on https://gitter.im/cefsharp/CefSharp

**Comment by fandrei** [comment]
@amaitland thanks
