### ISSUE TITLE
Cant' deploy CefSharp 65.0

### ISSUE THREAD

**Issue by piao217** [cefsharp/CefSharp#2491]
I know that this is kind of an old issue but decided to create a new one after all trial.

I downloaded branch 65.0 and built as Release.
I was interested in CefSharp.Winform and it runs very well. (CefSharp.Winform.Example.exe)

But when I copy this folder to a new test pc (Win7x64, Win8x64, Win10x64 all tested) it crashes.
According to event viewer :

Application: CefSharp.WinForms.Example.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at CefSharp.WinForms.Example.Program.Main(System.String[])

Faulting application name: CefSharp.WinForms.Example.exe, version: 65.0.0.0, time stamp: 0x5b767da8
Faulting module name: KERNELBASE.dll, version: 10.0.16299.611, time stamp: 0x966d0f68
Exception code: 0xe0434352
Fault offset: 0x00104172
Faulting process id: 0x20cc
Faulting application start time: 0x01d435feb9aeead3
Faulting application path: C:\Users\PBG\Documents\Release\CefSharp.WinForms.Example.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 3290549f-e3aa-4161-b377-46f4fd135a82
Faulting package full name: 
Faulting package-relative application ID: 

What I tried:
1) Install Visual C++ Redistributable for Visual Studio 2017 
   (Because I compiled it on VS2017)
2) Copy all the relevant files as follows.
![2018-08-17_15h42_30](https://user-images.githubusercontent.com/34410700/44254036-2a829480-a234-11e8-8038-9b78acb46ab4.png)

Actually I spent several days finding a way to resolve this but no luck.
Hope anybody helps me.

Thanks.

**Comment by amaitland** [comment]
Use [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) for testing, using the `Nuget` packages is the only supported method. Building from source is not recommended.

- Compile the `MinimalExample` in `x86`
- Deploy to your target machine
- `Install VC++ 2015 x86` (You **must** install the `x86` version if you've build the project for `x86`)
- Make sure you have at least `.Net 4.5.2` installed.

Read https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#4-why-do-i-get-an-error-about-could-not-load-file-or-assembly-cefsharpcoredll-or-one-of-its-dependencies-the-specified-module-could-not-be-found-when-trying-to-run-my-cefsharp-based-application-it-compiles-successfully-but-does-not-run-it-runs-on-my-developer-machine-though-throws-an-exception-when-i-copy-it-to-another-computer

This issue tracker is for **bug reports only**, it seems very unlikely this is a bug.

**Comment by piao217** [comment]
I tried MinimalExample too. but no luck.

**Comment by piao217** [comment]
Hi, amaitland.
Thanks for your reply.
I tried Minimal Example and it works.
But I should rebuild CefSharp because the standard one does not support MP4 video codec.
After some googling, I recognized that I need to rebuild CEF with proprietary codec option and rebuild CefSharp based on it.

Please help me.
I think this case is common (who would use a browser without video streaming?) and there must be a solution. 
If you know any links helpful, you could lead me there.

Thanks in advance.

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/wiki/General-Usage#multimedia-audiovideo
