### ISSUE TITLE
allow camera ??

### ISSUE THREAD

**Issue by kittipon2311** [cefsharp/CefSharp#2493]
![image](https://user-images.githubusercontent.com/25154073/44300826-59cdfa00-a337-11e8-85c6-4a364b4fac65.png)

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
You need to enable webrtc see https://github.com/cefsharp/CefSharp.MinimalExample/commit/726c328f6a268f5eb13a28d758ed183a853f05bb for an example

**Comment by awdwad45456** [comment]
this does not work anymore at webcamtoy.com
