### ISSUE TITLE
PDF embedded viewer appears when it must not

### ISSUE THREAD

**Issue by jonathand1** [cefsharp/CefSharp#2494]
Hi everyone !

I'm having an issue with **CefSharp WPF**. I would like to handle links ending by **".pdf"** to open them using another application. It works well (by implementing the **IRequestHandler** and using it for the cefBrowser.
For this case, I return **CefReturnValue.Cancel** to prevent embedded viewer being loaded with the pdf. 

The problem is the window still appears when I click on the PDF link (with no name, just a blank window).

Thank for your help !

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) 

https://gitter.im/cefsharp/CefSharp?at=5b7c42bfc53ee54c1882349e
