### ISSUE TITLE
Cannot pass a GCHandle across AppDomains

### ISSUE THREAD

**Issue by vegas2ny** [cefsharp/CefSharp#2496]
Hello,

I am encountering a bug when attempting to run cef sharp with in a separate app domain, when i initialize cefsharp in separate app domain other than default. I am receiving error "Cannot pass a GCHandle across AppDomains". It would be nice if multiple app domain support can be implemented, i am willing to pay whoever can do this.

Thanks

**Comment by amaitland** [comment]
Closing as duplicate of #351 

There are some workarounds listed there. Honestly just use `CefGlue` or `ChromiumFx`.
