### ISSUE TITLE
Feature Request - Add Chrome Extension Support

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#2497]
`CEF` added support for extensions in https://bitbucket.org/chromiumembedded/cef/issues/1947/add-support-for-chrome-extensions

Only some of the built in `API's` are exposed, load `chrome://extensions-support` in the browser to see which `API's` are supported.

There are quite a few methods and handlers that need to be added (not a complete list)

http://magpcss.org/ceforum/apidocs3/projects/(default)/CefRequestContext.html#LoadExtension(constCefString&,CefRefPtr%3CCefDictionaryValue%3E,CefRefPtr%3CCefExtensionHandler%3E)
http://magpcss.org/ceforum/apidocs3/projects/(default)/CefExtensionHandler.html

- [x] LoadExtension must be called on CEF UI thread, as no result is returned post the method call to the correct thread.

**Comment by Spiderpig86** [comment]
Great news!

**Comment by davisford** [comment]
Anyone gauge what it will take to get this working?  I might be interested in submitting a PR.  I *really* need this soon.

**Comment by amaitland** [comment]
> Only some of the built in `API's` are exposed, load `chrome://extensions-support` in the browser to see which `API's` are supported.

@davisford If you haven't already I'd recommend confirming that `CEF` implements all the `Extension APIs`  you require. If something is missing then you'd need to have it implemented in `CEF` first. A nice compact example of adding an `Extension API` to `CEF` is https://bitbucket.org/chromiumembedded/cef/commits/dddfce4

**Comment by davisford** [comment]
@amaitland yes, I aim to fire up and look at chrome://extensions-support but I'm currently just using a background script with a fairly simple content script, so I'm pretty sure what I'm doing would work.  Looks like support for extensions has been in CEF for quite some time now, but need .NET apis wrappers to install the extension?  I'm mainly interested in installing an unpacked extension in developer mode.

**Comment by amaitland** [comment]
> Looks like support for extensions has been in CEF for quite some time now

It has, though I don't see a lot of support requests on https://magpcss.org/ceforum/index.php for it, so it either works flawlessly or it's not that well used. (Just an observation, I have yet to try the `API`).

There are quite a few pieces that need to be implemented to expose the full `API`, a `PR` containing a partial implementation is probably acceptable if the core functionality is present.

**Comment by amaitland** [comment]
Basic plumbing has been implemented in #2613

**Comment by amaitland** [comment]
#2613 has been merged, it's now possible to load a `Chrome Extension`, remembering that `CEF` only supports a subset of the `Chrome Extension APIs` at this time. The `WinForms.Example` project contains a working example.

Only outstanding task is to marshal `LoadExtension` on the `CEF UI` thread, I had an implementation that compiled successfully in `VS2017`, failed using `VS2015`, so it was reverted for now. Will look at implementing before official `71.0.0` release, I will release `71.0.0-pre01` as is, it's pretty trivial to manually marshal the call onto the `CEF UI` thread.

**Comment by amaitland** [comment]
> The `WinForms.Example` project contains a working example.

@ahvahsky2008 Look through #2613 and you will see there is an example.

**Comment by ahvahsky2008** [comment]
@amaitland i mean - how add crx extension

**Comment by ahvahsky2008** [comment]
@amaitland thx for reply) i have extension. Unzip it. two js files.
https://pastebin.com/i1QxxNdL background.js
https://pastebin.com/Q0dax7Qy content.js

I load it, but i think browser not see this code

```
void IExtensionHandler.OnExtensionLoaded(IExtension extension)
        {
            //var manifest = extension.Manifest;
            //var browserAction = manifest["browser_action"].GetDictionary();
            //if (browserAction.ContainsKey("default_popup"))
            //{
            //    var popupUrl = browserAction["default_popup"].GetString();

            //    popupUrl = "chrome-extension://" + extension.Identifier + "/" + popupUrl;

            //    LoadExtensionPopup?.Invoke(popupUrl);
            //}

                var popupUrl = "chrome-extension://" + extension.Identifier + "/";

                LoadExtensionPopup?.Invoke(popupUrl);
        }
```

extension url https://chrome.google.com/webstore/detail/%D1%80%D0%B0%D1%81%D1%88%D0%B8%D1%80%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B4%D0%BB%D1%8F-%D0%BF%D0%BB%D0%B0%D0%B3%D0%B8%D0%BD%D0%B0-%D0%B3%D0%BE/pbefkdcndngodfeigfdgiodgnmbgcfha?hl=ru&authuser=1

**Comment by amaitland** [comment]
@ahvahsky2008 download the example extension provided, confirm that it loads and you can get it working. As stated above CEF only supports a small set of the Chrome extension APIs, only a very limited set of extensions will work at this time.

**Comment by ahvahsky2008** [comment]
@amaitland i downloaded it, but its not working

**Comment by amaitland** [comment]
A few notes when loading extensions

- `crx` files must be extracted to disk before they can be loaded (same behaviour as `Chrome`, a `crx` file is installed into `C:\Users\%USERNAME%\AppData\Local\Google\Chrome\User Data\Default\Extensions\`)
- For extensions that display popup windows you must query the `manifest` and manually open the resulting `url` in a new `ChromiumWebBrowser` instance. The example has an demos a very basic implementation of this.
- The `CEF Sample Application(cefclient)` can be used for testing of extensions, you can use

```
#Test with the built in example
cefclient --load-extension=set_page_color

#Load extension from disk
cefclient --load-extension=c:\path\to\my\extension
```

 The `Sample Application` can be downloaded from http://opensource.spotify.com/cefbuilds/index.html

**Comment by amaitland** [comment]
> Is there any plan to do which api first? I notice that only four APIs are currently supported. How about runtime and desktopCapture? I really need these two APIs.

@mcsnb When `CEF` adds support for those `API's` then they will become available in `CefSharp`. You can track the `upstream` progress at https://bitbucket.org/chromiumembedded/cef/issues/1947/add-support-for-chrome-extensions

This issue is purely to track the progress of exposing the relevant `API` methods, and will be closed shortly as it's `99%` complete.

**Comment by mcsnb** [comment]
> > Is there any plan to do which api first? I notice that only four APIs are currently supported. How about runtime and desktopCapture? I really need these two APIs.
> 
> @mcsnb When `CEF` adds support for those `API's` then they will become available in `CefSharp`. You can track the `upstream` progress at https://bitbucket.org/chromiumembedded/cef/issues/1947/add-support-for-chrome-extensions
> 
> This issue is purely to track the progress of exposing the relevant `API` methods, and will be closed shortly as it's `99%` complete.

@amaitland Thx. It seems that the progress is very slow. T_T

**Comment by amaitland** [comment]
`LoadExtension` will now post onto the `CEF UI` thread automatically. 

Other methods like `DidLoadExtension` still need to be explicitly called on the `UI` thread.

Closing this issue as the `API` is now complete from a `CefSharp` point of view.

**Comment by MrinaliMangal** [comment]
Does anyone have working example of loading chrome extension on chromium browser(Cefsharp)  in winforms. I am not able to find a correct one.

**Comment by amaitland** [comment]
The `WPF` example how has a demo of loading the same extension as the `WinForms` example, added in commit https://github.com/cefsharp/CefSharp/commit/d6ca2531eb2d3502a865973e24c64b44fe274821

**Comment by amaitland** [comment]
If you require assistance then please ask questions on the [Chromium Embedded Framework(CEF) Forum](https://magpcss.org/ceforum/index.php). 

You **MUST** confirm that `CEF` supports the `Extension API's` required by your `Extension. If it does not then you will be unable to load the `Extension.

Details for testing with the `CEF Sample Application` are listed above in https://github.com/cefsharp/CefSharp/issues/2497#issuecomment-452505255
