### ISSUE TITLE
LogSeverity in ConsoleMessageEventArgs is Info on console.trace()

### ISSUE THREAD

**Issue by nicky1038** [cefsharp/CefSharp#2500]
**What version of the product are you using?**
67.0.0

**What architecture x86 or x64?**
Occurs on both architectures.

**On what operating system?**
Win10

**What steps will reproduce the problem?**

-  Subscribe to ```ConsoleMessage``` event of ```WebBrowser```, and print ```ConsoleMessageEventArgs```' ```LogSeverity``` when this event occurs.
- Create some page where ```console.info()``` and ```console.trace()``` will be invoked.
- Navigate to that page.

**What is the expected output? What do you see instead?**
Expected output is ```Info``` for ```console.info()``` and something different for ```console.trace()``` - such as ```Verbose``` or ```Trace```.
Instead ```LogSeverity``` is ```Info``` in both cases.

**Comment by amaitland** [comment]
Thanks for filling out the bug report 👍 

`CEF` currently only maps console messages to `Info`, `Warning` and `Error`. See https://bitbucket.org/chromiumembedded/cef/src/d3e36d052cbc530cbe1bde4d74d45da075e07d47/libcef/browser/browser_host_impl.cc?at=3396&fileviewer=file-view-default#browser_host_impl.cc-2297

When `LogLevel` was added in `CEF`, no additional values were added to the `LogSeverity` enum, see https://bitbucket.org/chromiumembedded/cef/commits/d97b3f5 and https://bitbucket.org/chromiumembedded/cef/issues/2234/log-level-of-console-messages-not

There is nothing that can be done in `CefSharp`. Closing as `upstream` as this needs to be changed in `CEF`.

**Comment by amaitland** [comment]
If `CEF` does add an additional `LogLevel` then this can be reopened.

**Comment by nicky1038** [comment]
@amaitland Thank you for the quick response. I've reopened this issue here.
https://bitbucket.org/chromiumembedded/cef/issues/2499/consoletrace-log-level-is-info

**Comment by amaitland** [comment]
Needs to be fixed in `Chromium` see https://bitbucket.org/chromiumembedded/cef/issues/2499/consoletrace-log-level-is-info#comment-47969513 for official response.
