### ISSUE TITLE
Resource Handler Stream Is Null

### ISSUE THREAD

**Issue by vegas2ny** [cefsharp/CefSharp#2501]
Hello,

I have configured a resource handler, after making the request, the call back methods are called, for example "GetReponse" and "GetResponseHeaders" The problem is after "ProcessRequestAsync" is called, no request is actually made and the response is always empty, also the response headers collection count is always 0. I have double checked this by looking in fiddler and confirmed that a request is never being made after ProcessRequestAsync is called. My ProcessRequestAsync method contents are below. I really appreciate any help on this. Thank you.

     public virtual bool ProcessRequestAsync(IRequest request, ICallback callback)
        {
            callback.Continue();

            return true;
        }

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

You have already asked this question at https://gitter.im/cefsharp/CefSharp?at=5b8ff09158a3797aa308ccbc
