### ISSUE TITLE
SetAsPopup doesn't allow chromiumbrowser to be added to a Popup window

### ISSUE THREAD

**Issue by AmrSubZero** [cefsharp/CefSharp#2503]
### Bug Report

- **What version of the product are you using?**
(Latest from Nuget) v3.3396.1786

- **What architecture x86 or x64?**
x86
- **On what operating system?**
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms

- **What is the expected output? What do you see instead?**
When i set `chromiumbrowser.SetAsPopup()` the Popup window appears as a blank and the `chromiumbrowser` is never been added to it. when i remove it, the `chromiumbrowser` appears on the Popup.
[See a screenshot here.](https://image.ibb.co/kounPp/popup.png)

- **Please provide any additional information below.**

**Straight to the point :**

I'm trying to Handle the Popups, But it's always failing because of : `SetAsPopup()`
When i remove it, it works.

But if i add it like : 
```
chromiumBrowser = new ChromiumWebBrowser(targetUrl);
chromiumBrowser.SetAsPopup();
```

it doesn't add the `chromiumBrowser` into the Popup.
it won't show any browser it's just a blank popup with a title "_NEW"
i'm using  :  `popup.Controls.Add(chromiumBrowser)` see my code below.
    
    // Initializeing the CefSharp Chromium Browser
    public static ChromiumWebBrowser chromeBrowser;

    CefSettings settings = new CefSettings();
    settings.RemoteDebuggingPort = 8088;
    Cef.Initialize(settings);
    chromeBrowser = new ChromiumWebBrowser(browserUrl.Text);
    chromeBrowserWrapper.Controls.Add(chromeBrowser);
    chromeBrowser.Dock = DockStyle.Fill;
    chromeBrowser.LifeSpanHandler = new LifespanHandler();

    // OnBeforePop up ILifeSpanHandler Handler

    public bool OnBeforePopup(IWebBrowser browserControl, IBrowser browser, IFrame frame, string targetUrl, string targetFrameName, WindowOpenDisposition targetDisposition, bool userGesture, IPopupFeatures popupFeatures, IWindowInfo windowInfo, IBrowserSettings browserSettings, ref bool noJavascriptAccess, out IWebBrowser newBrowser)
    {
        var chromiumWebBrowser = (ChromiumWebBrowser)browserControl;
        ChromiumWebBrowser chromiumBrowser = null;

        var windowX = windowInfo.X;
        var windowY = windowInfo.Y;
        var windowWidth = (windowInfo.Width == int.MinValue) ? 600 : windowInfo.Width;
        var windowHeight = (windowInfo.Height == int.MinValue) ? 800 : windowInfo.Height;

        chromiumWebBrowser.Invoke(new Action(() =>
        {
            var owner = chromiumWebBrowser.FindForm();

            Form popup = new Form
            {
                Left = windowX,
                Top = windowY,
                Width = windowWidth,
                Height = windowHeight,
                Text = targetFrameName
            };

            popup.CreateControl();

            owner.AddOwnedForm(popup);

            chromiumBrowser = new ChromiumWebBrowser(targetUrl);
            chromiumBrowser.LifeSpanHandler = this;
            chromiumBrowser.SetAsPopup();

            var control = new Control();
            control.Dock = DockStyle.Fill;
            control.CreateControl();

            popup.Controls.Add(chromiumBrowser);

            popup.ShowInTaskbar = false;
            popup.StartPosition = FormStartPosition.CenterScreen;
            popup.ShowIcon = false;
            popup.MaximizeBox = false;
            popup.MinimizeBox = false;

            var rect = control.ClientRectangle;

            windowInfo.SetAsChild(chromiumBrowser.Handle, rect.Left, rect.Top, rect.Right, rect.Bottom);
            popup.Show();
        }));

        newBrowser = chromiumBrowser;

        return true;
    }

- **What is my point to still use `SetAsPopup()`?**
I need the new chromium browser that is being added to the popup to be as a child from the parent browser, like it is a normal popup from the website, because the website i'm working on have some functions running at the time i click button and that button opens the popup, removing `SetAsPopup()` when i click the button and the popup opens then website loads but it's like a very new browser the parent functions that was supposed to run to the popup window when i click the button, simply doesn't work. seems to be a new browser opened.
i need it to be a child of the parent browser (A Popup) that continue `send/recieve/sync/communicate` or anything with the parent browser.

I don't understand why `SetAsPopup()` doesn't work? i've tried every single word of code on the internet to fix this problem, every page on stackoverflow/github/etc. but didn't find a solution.
so i'm truly feeling this is a bug.

I hope my explaining was clear, Thanks!

**Comment by amaitland** [comment]
You are incorrectly returning true which cancels popup creation. You must return false when using newBrowser param. 

The example which uses newBrowser was removed ages ago and the code hasn't been tested so there are no guarantees that any of of it works. It's still an experimental feature and not one that's being activity maintained. https://github.com/cefsharp/CefSharp/blob/cefsharp/67/CefSharp/Handler/ILifeSpanHandler.cs#L30

The source contains an example for hosting the popup as a tab see 
https://github.com/cefsharp/CefSharp/blob/cefsharp/67/CefSharp.WinForms.Example/Handlers/LifeSpanHandler.cs

**Comment by AmrSubZero** [comment]
If i didn't prevent the original popup from being created what is the point of creating a custom popup?
i will be having two popups (original & custom) if i `return false`.

if that code example i'm using is ages years old like you say?

please give me a helping hand and give me an example for what i'm looking for (A code example of creating custom popup that is parent of the owner browser).

if not, i'm ok to have the popup as a new tab. but how could i do that? the example that you provided me is non-understandable (for me, i'm lost there). i had a half of a my document with errors after implementing the code in your example page.

like `BrowserForm` i don't have that in my project.
also the google search results about `CefSharp New Tab` is rare. even `stackoverflow`

I only want to handle the original popups to (custom popup it) or (open it in a new tab).
is that possible?

Thanks.

**Comment by amaitland** [comment]
As it stands this will be closed as `Invalid` as `SetAsPopup` appears to be working as expected.

**Comment by AmrSubZero** [comment]
I've got this working.
you were right, i had to `return false` with `SetAsPopup()` but i wasn't even implementing `OnAfterCreated` method like this : 

    void ILifeSpanHandler.OnAfterCreated(IWebBrowser browserControl, IBrowser browser)
    {
        var chromiumWebBrowser = (ChromiumWebBrowser)browserControl;

        chromiumWebBrowser.Invoke(new Action(() =>
        {
            var owner = chromiumWebBrowser.FindForm();

            if (owner != null && owner.FindForm() == browserControl)
            {
                owner.Show();
            }
        }));
    }

and set `owner` to the popup form like this : 

    var owner = chromiumWebBrowser.FindForm();
    Form popup = new Form
    {
        Owner = owner
        /......
    };

It's now working, but how do i implement `ILifeSpanHandler.DoClose()` and `ILifeSpanHandler.OnBeforeClose()` what is the best way to handle these methods to close the popup when `javascript` `window.close()` function called?

the only code that i found over more than 50 pages i searched, is this : 

    popup.Closed += (o, e) =>
    {
        var w = o as Form;
        if (w != null && w.FindForm() is IWebBrowser)
        {
            (w.FindForm() as IWebBrowser).Dispose();
            w = null;
        }
    };

it's not working though.
i have a button that should open popup window then waits 15sec and calling `window.close()`

when i click this button using my mouse. it opens the popup and closing it after 15sec. (normally) without any problems.

but when i `trigger` the click event on that button by `javascript/jquery` like `button.click();` or `$('button').trigger('click')` it opens the popup but never closes it even after the 15sec. the `window.close()` event doesn't fire.

here's my `javascript` code : 

    var popupWindow;

    // Open the popup window when the button clicked
    $('.button').click(function(){
        popupWindow = window.open(some,arguments,.....);
    });
    
    // (trigger) Click the button
    $('.button').click();

    // Close the popup window after 15sec
    setTimeout(function(){
        popupwindow.close();
    }, 15000); // 15sec

That's weird, why when i click the button by myself (click using mouse) the `window.close()` closes after 15sec. but when i trigger the `click` event to the button. it never being closed.

    bool ILifeSpanHandler.DoClose(IWebBrowser browserControl, IBrowser browser)
    { return false; }

    void ILifeSpanHandler.OnBeforeClose(IWebBrowser browserControl, IBrowser browser)
    {
        if (!browser.IsDisposed && browser.IsPopup)
        {
                browser.Dispose();
        }
    }

i hoping you can help me with this issue, it's about 3 days searching and did not find anything.

Thanks alot amaitland.

**Comment by amaitland** [comment]
> but i wasn't even implementing `OnAfterCreated` method like this : 

You appear to be mixing and matching code from different unrelated examples. The old example is at https://github.com/cefsharp/CefSharp/blob/cefsharp/57/CefSharp.WinForms.Example/Handlers/LifeSpanHandler.cs

> That's weird, why when i click the button by myself (click using mouse) the `window.close()` closes after 15sec. but when i trigger the `click` event to the button. it never being closed.

Does it work in `Chrome`? Remember that `Chromium` has security restrictions in place to stop people doing exactly what you are attempting. I'd be surprised if it's possible to close a window without user interaction.

**Comment by AmrSubZero** [comment]
Yes, correct.
It's the security restrictions which has prevented the `window.close()` without user interaction.
Fine, thanks alot amaitland for your kind help, appreciate it alot.
Things are clear now, you can close the issue if you want.
Greetings.
