### ISSUE TITLE
unsafely-treat-insecure-origin-as-secure  can not working

### ISSUE THREAD

**Issue by linchuanhai** [cefsharp/CefSharp#2506]
I have a site like :"http://192.1681.158:8855/Test2.html" .  and  I want to use the getUserMedia to visit the web camera on this page.  I know it will be prevent by security policy.  So in the Cefsharp(WindowsForm)  Init method.
I add the  code :
 CefSetting.CefCommandLineArgs.Add("unsafely-treat-insecure-origin-as-secure", "http://192.1681.158:8855");
  CefSetting.CefCommandLineArgs.Add("enable-media-stream", "1");
But I  found that it can not working.

I try to set this commandLine args on the chrome.exe  shortcut, and it can normal open the webcamera.

so how can i process it?

**Comment by amaitland** [comment]
`CEF` does not support that command line argument yet, there is an open `PR`, see https://bitbucket.org/chromiumembedded/cef/pull-requests/166/add-support-for-unsafely-treat-insecure/diff

When it's implemented in `CEF` it will eventually be available in `CefSharp`.

> so how can i process it?

You should ask for help on http://magpcss.org/ceforum/index.php

**Comment by amaitland** [comment]
Support was merged in https://bitbucket.org/chromiumembedded/cef/commits/7ecc5d31ea0e64091ab4ee0720f9c7837befb00b?at=3683 and will be available in the `73` release.
