### ISSUE TITLE
ScreenshotAsync stalling

### ISSUE THREAD

**Issue by IvanPong** [cefsharp/CefSharp#2507]
- I'm using The latest Nuget Cefsharp windowless version 67, downloaded four days ago.
- x64
- Windows 10
- OffScreen
- I am calling Cefsharp using the following call inside a program:
```
            var browserSettings = new BrowserSettings();
            //Reduce rendering speed to one frame per second so it's easier to take screen shots
            browserSettings.WindowlessFrameRate = 1;
            var requestContextSettings = new RequestContextSettings { CachePath = "cahcehe1" };

            // RequestContext can be shared between browser instances and allows for custom settings
            // e.g. CachePath
            using (var requestContext = new RequestContext(requestContextSettings))
            using (var browser = new ChromiumWebBrowser("https://www.google.com/", browserSettings))
            {
                
                while (m_ReceivedObjects.Any() && currentImageToBeProcessed.IsRendered == false)
                {
                    currentImageToBeProcessed = m_ReceivedObjects.Dequeue();

                    //await LoadPageAsync(browser, currentImageToBeProcessed.filePath, currentImageToBeProcessed.rawHtml);
                    Thread.Sleep(1000);
                    currentImageToBeProcessed.IsRendered = true;

                    browser.Load("https://www.google.com/");
                    Thread.Sleep(2000);
                    var task = browser.ScreenshotAsync();//.ContinueWith(processHTML);
                    Thread.Sleep(1000);
                    task.Wait();
                    Thread.Sleep(1000);
                    processHTML(task);
                }
            }
```

The expected output is a bitmap which is extracted by processHTML. Instead the program hangs indefinitely inside task.wait. I've also tried this using the await/async operators with the same result.

There are no exceptions, nothing gets called. I've also varied the input to ScreenshotAsync, with the result that it returns, but the bitmap is null.

Due to the ease of the cefsharp interface, c++/cli is calling it, i don't believe this is affecting the program in any significant way though.

Most recent Nuget Cef windowless build.

**Comment by jankurianski** [comment]
On the face of it I can't see anything specifically wrong with your code.

Can you please fork https://github.com/cefsharp/CefSharp.MinimalExample and modify the `CefSharp.MinimalExample.OffScreen` example so it reproduces the bug?

**Comment by IvanPong** [comment]
Hi, thanks for the response. I did find an issue with my code.
I had something like 

CefBrowser  = new browser();

...

if(! Cef.IsInitialized)
     Cef.Initialize()
...

var task = browser.ScreenshotAsync();
task.wait();


It never gave an error. Not initializing Cef appears to work fine until we actually require a result from it.

Thanks though.

**Comment by KoalaBear84** [comment]
Just for future reference for others.

Hmm, in another application I had the WindowlessFrameRate part, and in a new application I tested it and it sometimes just hangs, as also others are getting [here](https://github.com/puppeteer/puppeteer/issues/7507) (not CefSharp).

It now works always, and 3 or 5 is better than 1 as it takes a lot longer with 1 somehow. Maybe the `CaptureScreenshotAsync` (newer method call) is waiting for something like a requestAnimationFrame in the background.

```csharp
// Reduce rendering speed to one frame per second so it's easier to take screenshots
browserSettings.WindowlessFrameRate = 5;
```
