### ISSUE TITLE
 Language setting does not work

### ISSUE THREAD

**Issue by connie61** [cefsharp/CefSharp#2512]
x86 cefsharp67 winform win10

After setting the language to Chinese, there are still controls displayed in English, but there is no problem with Google Chrome.

settings.Locale = "zh-CN";
settings.AcceptLanguageList = "zh-CN";

NameValueCollection headers = request.Headers;
headers.Add("Accept-Language", "zh-CN");
request.Headers=headers;
![image](https://user-images.githubusercontent.com/33438415/45478393-69920000-b776-11e8-9b06-a3ae948380dd.png)

**Comment by amaitland** [comment]
It's important to note that `CefSharp` is just a wrapper around the `Chromium Embedded Framework (CEF)`. Closing this as `upstream` and `wontfix` as changes need to be made in `CEF`. 

The `CEF` project has it's own issue tracker located at https://bitbucket.org/chromiumembedded/cef 

Before opening a new issue you should:

- Search open/closed issues to determine if the problem you are seeing has already been reported
- Test with a newer version if available, see https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-chromium-embedded-frameworkcef for details on testing with the `cefclient` reference application.

If you do find an existing issue that matches this one or create a new one then post a link here for others to follow.
