### ISSUE TITLE
 Prohibit new window popup,post request link failed to load

### ISSUE THREAD

**Issue by connie61** [cefsharp/CefSharp#2513]
x86 cefsharp67 winform win10

Prohibit new window popup, open new tabs,the link of the get request can be loaded successfully，but post request link failed to load.

        public bool OnBeforePopup(IWebBrowser browserControl, IBrowser browser, IFrame frame, string targetUrl, string targetFrameName, WindowOpenDisposition targetDisposition, bool userGesture, IPopupFeatures popupFeatures, IWindowInfo windowInfo, IBrowserSettings browserSettings, ref bool noJavascriptAccess, out IWebBrowser newBrowser)
        {
            //【1】添加tab和panel，一一对应
            //【2】当前panel添加browser
            myForm.AddNewTab();
            newBrowser = myForm.AddNewBrowser(targetUrl);//...直接调用
            // open popup in new tab!
            return true;//为true时不弹出新窗口
        }

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
You have to `return false` to maintain the popup relationship. The` newBrowser` feature is experimental and not being maintained.

See https://github.com/cefsharp/CefSharp/blob/cefsharp/67/CefSharp.WinForms.Example/Handlers/LifeSpanHandler.cs for an example of opening in a `tab`.

Please ask your questions on https://gitter.im/cefsharp/CefSharp before opening any further issues.

**Comment by amaitland** [comment]
> when return true,how to open a link with a post request？

You cannot, it doesn't work that way. `return true` always cancels popup creation.

**Comment by connie61** [comment]
Thank you very much.
