### ISSUE TITLE
Resizing iframe stop capturing mouse wheel

### ISSUE THREAD

**Issue by osasseville** [cefsharp/CefSharp#2515]
### Bug Report

- Version: CefSharp.WPF v67.0.0 (x86) Nuget Package
- OS: Windows 10
- Problem: resizing iframe stop capturing mouse wheel
- Steps to reproduce:
    - Go to [this code pen](https://codepen.io/osasseville/full/xaJdXL/) in a ChromiumWebBrowser from CefSharp.Wpf v67.0.0 nuget package.
    - Drag the gray horizontal row in the middle of the page up then down to resize the iframes
    - Scrolling in the iframes using the mouse wheel does not work anymore
- This works well with chrome 67.0.3396.79 and CEF 3.3396.1785.ga27bbfa / Chromium 67.0.3396.79 Sample application ([download here](http://opensource.spotify.com/cefbuilds/cef_binary_3.3396.1785.ga27bbfa_windows32_client.tar.bz2))

**Comment by amaitland** [comment]
What command line args did you load cefclient with?

**Comment by osasseville** [comment]
I did not use any. I use the default constructor of CefSettings.

Olivier Sasseville
TermLynx

________________________________

**Comment by amaitland** [comment]
> * This works well with chrome 67.0.3396.79 and CEF 3.3396.1785.ga27bbfa / Chromium 67.0.3396.79 Sample application ([download here](http://opensource.spotify.com/cefbuilds/cef_binary_3.3396.1785.ga27bbfa_windows32_client.tar.bz2))

When testing `CEF` you need to use the following command line args `cefclient --multi-threaded-message-loop --off-screen-rendering-enabled`

**Comment by amaitland** [comment]
I expect what your seeing is related to https://bitbucket.org/chromiumembedded/cef/issues/2214/osr-scroll-is-erratic-after-using-mouse and will be resolved in version `69`.

Testing with https://github.com/cefsharp/CefSharp/commit/05b37ab61583cbc3c7aa2ce6dce42bf83bbce945 and everything works as expected.

**Comment by amaitland** [comment]
Using the WinForms version is the equivalent. 

Closing as this has been resolved and will be fixed in the 69 release.
