### ISSUE TITLE
win 8.1 X64      Failed to load file or assembly CefSharp.Core.dll （version:67）

### ISSUE THREAD

**Issue by usandchina** [cefsharp/CefSharp#2516]
Hello,
We are using the CefSharp.dll version ( https://github.com/cefsharp/CefSharp ) in our  window/desktop app. We are using .net framework 4.5 along with the 64 bit version of the CefSharp version  67.0.0

then，in win7 X32 & X64, win8 X32 & X64, win8.1 X32, win10 X32 & X64 run is very well.

but in  win8.1 X64 not work，display " Failed to load file or assembly CefSharp.Core.dll "... i can't solve it.

Thanks

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp)
If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage
