### ISSUE TITLE
WinForm how to display MP4 video

### ISSUE THREAD

**Issue by szyxc** [cefsharp/CefSharp#2518]
WinForm how to display MP4 video？

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp)

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/wiki/General-Usage#multimedia-audiovideo

**Comment by szyxc** [comment]
Thank you. I'll try.
