### ISSUE TITLE
BrowserProcess stays open ever since updating to v67

### ISSUE THREAD

**Issue by imPRAGMA** [cefsharp/CefSharp#2520]
- **What version of the product are you using?**
    - v67 NuGet

- **What architecture x86 or x64?**
    - x86

- **On what operating system?**
    - Win10, occurs on all afaik

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - WinForms

- **What steps will reproduce the problem?**
    Run it and close it. Simple as.

- **What is the expected output? What do you see instead?**
    Should auto end process but it stays open using 20-30% cpu infinitely.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
    Im unable to test

**Comment by imPRAGMA** [comment]
It actually seems to occur if you get it to do a long operation with JSAsyncExecute thing.

This is a result of this:
https://i.imgur.com/WJkKrRg.gifv

an example long operation is to do 50k+ DOM Operations in 1 JSAsyncExecute.
Close the app after sending and it will happen. Kinda odd

**Comment by amaitland** [comment]
Please fork https://github.com/cefsharp/CefSharp.MinimalExample and provide an example that demonstrates the problem. 

There is no CefSharp method called JSAsyncExecute please provide technically accurate information, there are two methods with similar names.

**Comment by imPRAGMA** [comment]
browser.ExecuteScriptAsync is what im on about.
Literally use the minimal, and foreach and StringBuild a huge Table DOM like the following:
`"var r=document.createElement('tr');r.className='ARow';r.insertCell(0).innerHTML='Cell1';r.insertCell(1).innerHTML='Cell2';r.insertCell(2).innerHTML='Cell3';document.getElementById('tableElementBody').appendChild(r);"`
Foreach that 100 thousand times, where it adds to a stringbuilder and once all 100k are built, execute it with browser.ExecuteScriptAsync then immediately close your application.
Take a look in Task Manager, and it will be open eating CPU.

**Comment by amaitland** [comment]
> browser.ExecuteScriptAsync is what im on about.

That's just a wrapper around http://magpcss.org/ceforum/apidocs3/projects/(default)/CefFrame.html#ExecuteJavaScript(constCefString&,constCefString&,int)

No changes were made in `67` to this method. Probably `Chromium` changes something in the `JS Engine`, it's very common they change something that adversely affects performance or memory usage.

> Foreach that 100 thousand times, where it adds to a stringbuilder and once all 100k are built, execute it with browser.ExecuteScriptAsync then immediately close your application.

That's a huge amount of code to execute. You should generate the code and execute in the same version of `Chrome` using `DevTools` to see how it behaves.

Making this as `upstream`, likely will be closed as `wontfix` as `CefSharp` is just a wrapper and has no control over the `JS Engine`.

You can use http://cefsharp.github.io/api/67.0.0/html/P_CefSharp_CefSharpSettings_SubprocessExitIfParentProcessClosed.htm to force close subprocesses on exit.

**Comment by imPRAGMA** [comment]
Is that API not set to on by default? If not it really should be.
Since ExecuteScriptAsync is a wrapper for another method, should I even be using it since it would probably end up deprecated in the future? Is there benefits to directly using the normal method?

Anyway yeah I understand its a lot of code, but theres nothing better I can do in my case. I have all the variables and such as small as I possibly could so the overall code size would be as small as possible but not much else I can do about it. In total its about 8,430,499 characters in total after the foreach o.o

I did what you said about running it through Console manually and it did the same thing, 30% CPU usage in memory after main process is closed. Ill have to attempt this with the Exit API.

**Comment by imPRAGMA** [comment]
The issue is resolved as soon as I enabled CefSharpSettings.SubprocessExitIfParentProcessClosed.
But I dont like the fact that it would be constantly checking if the process is alive or not (possibly wasting CPU execution ticks) so ill probably instead go the route of manually shutting down the process every time when my application closes with FormClosing.

**Comment by bddckr** [comment]
>that it would be constantly checking if the process is alive or not
It doesn't: https://github.com/cefsharp/CefSharp/blob/30ee538ce0e0d1d33ed838665758ec2061165224/CefSharp.BrowserSubprocess/Program.cs#L57-L75

**Comment by amaitland** [comment]
> Is that API not set to on by default? If not it really should be.

If your referring to `CefSharpSettings.SubprocessExitIfParentProcessClosed`, it's a new feature and will be enabled by default at some point in the future.

> Since ExecuteScriptAsync is a wrapper for another method, should I even be using it since it would probably end up deprecated in the future? Is there benefits to directly using the normal method?

The point I'm making is that all `CefSharp` does it call the underlying `C++` method. For executing a script that doesn't not return a result then `ExecuteScriptAsync` is the best method. There are no plans to remove it.

> I did what you said about running it through Console manually and it did the same thing, 30% CPU usage in memory after main process is closed. Ill have to attempt this with the Exit API.

Thanks for confirming, closing this as `wontfix`. There really isn't anything we can do about how the `V8 Engine` behaves. If it worked in previous versions and you can provide code to reproduce then you might have some luck creating an issue with the `Chromium` project.
