### ISSUE TITLE
Feature Request - Add CefRenderHandler::OnAcceleratedPaint

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#2527]
`CEF` has added support for shared textures on `Windows` using `D3D11` (and only `D3D11`). See commit https://bitbucket.org/chromiumembedded/cef/commits/713eebcafcd7799d4e0eb58b8c2ab58d03ab9b65 for full details.

These changes have been merged into the `CEF master` branch and will be available in version `71` (`CEF` builds will be roughly available sometime in early December).

- [ ] Add `IWindowInfo.SharedTextureEnabled`
- [ ] Add `IRenderHandler.OnAcceleratedPaint`
- [ ] Add `IWindowInfo.ExternalBeginFrameEnabled`
- [ ] Add `IBrowserHost.SendExternalBeginFrame`

Actually implementing `D3D` rendering in `CefSharp` is outside the scope of this issue. This issue reflects work to be done exposing the relevant `CEF API` methods/handlers.

Just for reference `Microsoft` have an open source project for enabling `D3D11` support, see https://github.com/Microsoft/WPFDXInterop

**Comment by amaitland** [comment]
There is one known issue with shared textures and `PDF` rendering currently, https://bitbucket.org/chromiumembedded/cef/issues/2516/windows-osr-pdf-viewer-does-not-render

I expect there will be quite a few issues that will need to be addressed. Others are reporting issues on the original `PR` see https://bitbucket.org/chromiumembedded/cef/pull-requests/158/support-external-textures-in-osr-mode/ for details.

I expect it will take a while before this feature is production ready.

**Comment by mitchcapper** [comment]
It seems the pdf shared textures is fixed in master so by 71 time will not be an issue, but there still are some others that seem relevant.

**Comment by amaitland** [comment]
Another issue https://bitbucket.org/chromiumembedded/cef/issues/2538/windows-osr-with-shared-textures-renders

**Comment by mcdis** [comment]
Any progress? IWindowInfo.SharedTextureEnabled?

**Comment by amaitland** [comment]
When progress has been made this issue will be updated. `Chrome` hasn't even released a stable `71` build yet.

**Comment by amaitland** [comment]
`cefclient` example added in commit https://bitbucket.org/chromiumembedded/cef/commits/1e6b870af0117a675014cc559c1ad9141733226b?at=3578

**Comment by amaitland** [comment]
`OnAcceleratedPaint` has been added to `master`. Some refactoring of the `OffScreen` and `WPF` browsers was required. I have yet to test `OnAcceleratedPaint`

- `WPF` inherit from `ChromiumWebBrowser` and override `CreateOffscreenBrowserWindowInfo`, you can access `IWindowInfo` and change `SharedTextureEnabled`
- `OffScreen` create the `ChromiumWebBrowser` instance and set `automaticallyCreateBrowser = false` in the constructor. Then call `CreateBrowser` passing in an instance of `WindowInfo` with the relevant properties set.

**Comment by amaitland** [comment]
In `WPF/OffScreen` you will need to implement `IRenderHandler` and provide an implementation of `OnAcceleratedPaint`.

**Comment by EladBahar** [comment]
hey,
will you implement WPF/Offsccreen demo with OnAcceleratedPaint  ?

**Comment by amaitland** [comment]
I have no experience with `DirectX` and it's unclear if `WPF` only supporting `DirectX 9` can be made to work with `OnAcceleratedPaint` that requires `DirectX 11`.

At a later point I will experiment with adding a demo to the `WPF` example (there's no generic use-case for the `OffScreen` project). Pull requests are welcome to add a demo in the short term.

If a stable `WPF` implementation can be developed then a new `CefSharp.Wpf.DirectX` project/nuget package can be created (I expect a new package will be required `SharpDx` or `WPFDxInterop`, so we'll isolate that dependency from the main `WPF` project).

**Comment by amaitland** [comment]
`Chrome` changes will break `OnAcceleratedPaint` in newer version of `CEF`, see https://bitbucket.org/chromiumembedded/cef/issues/2559/cefclientexe-shared-texture-enabled-off for details.

**Comment by vwmberry95** [comment]
Issue is closed yet it's listed in the v71.0.0-pre01 release?

**Comment by amaitland** [comment]
> Issue is closed yet it's listed in the v71.0.0-pre01 release?

@vwmberry95 What do you mean? The `API` has been added, this issue has been closed.

**Comment by AliFlux** [comment]
Hi. Any update on this issue? I'm using the latest WPF nuget package and the rendering is still kinda slow.

**Comment by amaitland** [comment]
Performance improvements are outside the scope of this issue.
