### ISSUE TITLE
CanSetPreference("proxy") always false

### ISSUE THREAD

**Issue by lukakostic** [cefsharp/CefSharp#2531]
//NuGet winforms 67.0.0 x86 debug (On windows 10 Pro x64)
//Browser is started with a proxy with cefsettings on initialization
//But when i try to change it during runtime (5 sec after it started) it doesnt work

            await Cef.UIThreadTaskFactory.StartNew(delegate {
                var rc = a.browser.GetBrowser().GetHost().RequestContext;
                if (rc.CanSetPreference("proxy"))
                {
                   //never gets to this point, always prints cant set proxy
                }
                else Console.WriteLine("Cant set proxy!");
            });

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
> As one example preferences set via the command-line usually cannot be modified.

As per http://cefsharp.github.io/api/67.0.0/html/M_CefSharp_RequestContext_CanSetPreference.htm

> //Browser is started with a proxy with cefsettings on initialization

You cannot do this and change the proxy at runtime.
