### ISSUE TITLE
Handle Click To Main Form

### ISSUE THREAD

**Issue by 84pennies** [cefsharp/CefSharp#2534]
Trying to do something very simple. Want to handle clicks to the winforms application window. This is for a feature that requires the user to interact with the window to stop an alert sound from playing in a health care environment. Everything else is working perfectly, but the click handler just doesn't take. Handling other events like Activated, Deactivated etc. work well.

Have tried a million one half and the other things but no luck so far.

Here's the basic idea:

```
namespace M2.Desktop
{
    public partial class BrowserForm : Form
    {
        private readonly ChromiumWebBrowser browser;

        public BrowserForm()
        {
            InitializeComponent();

            this.Click += (S, E) {
                MessageBox.Show("Hello, world!");
            };
            //the rest of the application spins up here...
        }
    }
}
```

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/wiki/General-Usage#multithreadedmessageloop
