### ISSUE TITLE
WinForms - ChromiumWebBrowser.LoadUrlWithPostData not works (67.0.0)

### ISSUE THREAD

**Issue by Gorebar** [cefsharp/CefSharp#2537]
> - **What version of the product are you using?**

     I'm using 67.0.0 version from NuGet. Aparently is the last stable version.

> - **What architecture x86 or x64?**

     Architecture x64. Win 10

> - **Are you using `WinForms`, `WPF` or `OffScreen`?**

     WinForms on Visual Studio 2017

> - **What steps will reproduce the problem?**

    I was using version 63.0.3.  I have updated to version 67.0.0 today. In my application I need to navigate to a website sending post data. For this, I was using "ChromiumWebBrowser.LoadUrlWithPostData", works good in 63.0.3 but now.. not works in 67.0.0. 
My question, **Has anything changed in this function that I should modify?**

Nothing works, no post data is sending to my website. Any suggestions?

> - **Please provide any additional information below.**

    NOTE: Is my website too so... i can test all what you need to test. 
    - A stack trace if available, any Exception information.

**Comment by amaitland** [comment]
> * What steps will reproduce the problem?

> Please provide detailed information here, enough for someone else to reprodce your problem.
> Please no binary (zip, etc) links, fork the MinimalExample and push your changes to GitHub. (Alternatively use a code sharing service list Gist or Pastebin).

As per the issue template please fork https://github.com/cefsharp/CefSharp.MinimalExample and provide an example that reproduces your problem. Saying you've upgraded and now it doesn't work doesn't help someone else reproduce the problem, you need to provide an example. 

`LoadUrlWithPostData ` is a simple extension method, nothing has changed for quite some time see https://github.com/cefsharp/CefSharp/blob/cefsharp/67/CefSharp/WebBrowserExtensions.cs#L240

The full git history is there should you wish to review.

**Comment by amaitland** [comment]
The following works as expected

```c#
var postData = System.Text.Encoding.Default.GetBytes("test=123&data=456");

browser.LoadUrlWithPostData("https://httpbin.org/post", postData);
```

I suspect you are initially loading `about:blank`, which no longer spawns a render process, see https://magpcss.org/ceforum/viewtopic.php?f=6&t=16058&p=38563&hilit=LoadRequest#p38559 

You can load a `Data URI` initially to create a render process.

See also #2451

**Comment by Gorebar** [comment]
> > * What steps will reproduce the problem?
> 
> > Please provide detailed information here, enough for someone else to reprodce your problem.
> > Please no binary (zip, etc) links, fork the MinimalExample and push your changes to GitHub. (Alternatively use a code sharing service list Gist or Pastebin).
> 
> As per the issue template please fork https://github.com/cefsharp/CefSharp.MinimalExample and provide an example that reproduces your problem. Saying you've upgraded and now it doesn't work doesn't help someone else reproduce the problem, you need to provide an example.
> 
> `LoadUrlWithPostData` is a simple extension method, nothing has changed for quite some time see https://github.com/cefsharp/CefSharp/blob/cefsharp/67/CefSharp/WebBrowserExtensions.cs#L240
> 
> The full git history is there should you wish to review.

You are right with details, it was my first report, sorry for this. 

**Details**

I have a website to load several inputs and I have an C# app which should send this inputs data.

`mywebsite.com/loadData/firstInput=dataFI&secondInput=dataSI`

This example should be the final URL.

On 63.0.3 version I receive without problem this data but now in 67.0.0 version the server/website is not receiving anything. When I receive this data I load the website with the text on this inputs, on 67.0.0, appear my website but only load `mywebsite.com/loadData/` without data and empty inputs.

**Code**

I have a Dictionary with all data

```
Dictionary<string, string> paramsPost = new Dictionary<string, string>();
paramsPost .Add("first","Data for the first Input");
paramsPost .Add("second", "Data for the second Input");
paramsPost .Add("third", "Data for the third Input");

ChromiumWebBrowser browser = new ChromiumWebBrowser()

string paramsString = string.Join("&", paramsPost.Select(x => x.Key + "=" + x.Value).ToArray());
byte[] bytes = System.Text.Encoding.UTF8.GetBytes(paramsString);

//url = mywebsite.com/loadData
browser.LoadUrlWithPostData(url, bytes);

```

Thanks for your time.

**Comment by amaitland** [comment]
> I have a website to load several inputs and I have an C# app which should send this inputs data.
> 
> `mywebsite.com/loadData/firstInput=dataFI&secondInput=dataSI`

This is a `GET` request, not a `POST` request which `LoadUrlWithPostData ` uses, you won't see any data in the query string.

> When I receive this data I load the website with the text on this inputs, on 67.0.0, appear my website but only load `mywebsite.com/loadData/`

Having just the `URL` and no data is expected for a `POST` request.

To use `LoadUrlWithPostData` you must first load a website so the render process loads, then load your website. If all you need is a `GET` request then you can build the `query string` yourself and append that to your url, avoiding `LoadUrlWithPostData` all together.

**Comment by amaitland** [comment]
Also please don't edit the title, I've changed it for a reason. If it turns out that my analysis is incorrect, I will edit it then.

**Comment by Gorebar** [comment]
> Also please don't edit the title, I've changed it for a reason. If it turns out that my analysis is incorrect, I will edit it then.

Okay, again... sorry. 

Noob here... =(

**Comment by Gorebar** [comment]
> > I have a website to load several inputs and I have an C# app which should send this inputs data.
> > `mywebsite.com/loadData/firstInput=dataFI&secondInput=dataSI`
> 
> This is a `GET` request, not a `POST` request which `LoadUrlWithPostData` uses, you won't see any data in the query string.
> 
> > When I receive this data I load the website with the text on this inputs, on 67.0.0, appear my website but only load `mywebsite.com/loadData/`
> 
> Having just the `URL` and no data is expected for a `POST` request.
> 
> To use `LoadUrlWithPostData` you must first load a website so the render process loads, then load your website. If all you need is a `GET` request then you can build the `query string` yourself and append that to your url, avoiding `LoadUrlWithPostData` all together.

No, I don't need a `GET` request... it was an example. I need a `POST` one. Using the same code what I posted before, works in 63.0.3. The code I provide you with dictionary and bytes.

The website is always rendered so is not this problem. Is not an `about:blank` page. All rendered process are finished before send post data.

**Comment by amaitland** [comment]
> I think that your title is wrong, I still think it's an error. Is not an `about:blank` page, load my website with no problem but no post has been sent

That's perfectly fine, for now please leave it.

As I've said a few times, you will have to provide an example that reproduces your problem. It works as expected for me, so it's unlikely a bug in `CefSharp`, which is just a wrapper.

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp.MinimalExample/commit/0f873c7ecc46d1d7d4e13b6036d533661a06d2d2 for a working example which basically rules out any bugs in `CefSharp`.

**Comment by Gorebar** [comment]
> See [cefsharp/CefSharp.MinimalExample@0f873c7](https://github.com/cefsharp/CefSharp.MinimalExample/commit/0f873c7ecc46d1d7d4e13b6036d533661a06d2d2) for a working example which basically rules out any bugs in `CefSharp`.

I'm checking all on this example. I'll write you again once I done
