### ISSUE TITLE
Feature Request Fix WinForms - IDownloadHandler not works (67.0.3396.79)

### ISSUE THREAD

**Issue by mohamedosama914** [cefsharp/CefSharp#2538]
Feature Request WinForms - ChromiumWebBrowser.IDownloadHandler not works (67.0.3396.79)
***ChromiumWebBrowser***

![hicapture](https://user-images.githubusercontent.com/12082147/47019955-8dbb7500-d158-11e8-8a29-09180ad828b8.PNG)
`
![chromium67 0 3396 79capture](https://user-images.githubusercontent.com/12082147/47019954-8dbb7500-d158-11e8-9e5c-0c0025367e96.PNG)

      public class DownloadHandler : IDownloadHandler
         {
             public event EventHandler<DownloadItem> OnBeforeDownloadFired;

             public event EventHandler<DownloadItem> OnDownloadUpdatedFired;

             public void OnBeforeDownload(IBrowser browser, DownloadItem downloadItem, IBeforeDownloadCallback callback)
             {
                 var handler = OnBeforeDownloadFired;

                 if (handler != null)
                 {
                     handler(this, downloadItem);
                 }

                 if (!callback.IsDisposed)
                 {
                     using (callback)
                     {
                         callback.Continue(downloadItem.SuggestedFileName, showDialog: true);

                     }
                 }
             }

             public void OnDownloadUpdated(IBrowser browser, DownloadItem downloadItem, IDownloadItemCallback callback)
             {

         //        if (downloadItem.IsComplete || downloadItem.IsCancelled)   {   do stuff   }

                 var handler = OnDownloadUpdatedFired;
                 if (handler != null)
                 {
                     handler(this, downloadItem);

      }     }   }   }
`

**Comment by mohamedosama914** [comment]
DownloadHandler not works (67.0.3396.79)
![5capture](https://user-images.githubusercontent.com/12082147/47020364-7df06080-d159-11e8-8d82-c53d0f59211a.PNG)

**Comment by mohamedosama914** [comment]
## ` CefSharp.WinForms | Download not works (67.0.3396.79)`

### `Feature Request` - IDownloadHandler Add IWebBrowser Fix 
`IDownloadHandler` is inconsistent with the other handlers as it doesn't expose access to the underlying `IWebBrowser` interface (the `ChromiumWebBrowser` instance).




![1](https://user-images.githubusercontent.com/12082147/47023529-21dd0a80-d160-11e8-99ab-be4b98a0d49e.png)
![2](https://user-images.githubusercontent.com/12082147/47023530-21dd0a80-d160-11e8-96ec-60002948c239.png)
![3](https://user-images.githubusercontent.com/12082147/47023531-21dd0a80-d160-11e8-90c8-173285e0865e.png)

**Comment by amaitland** [comment]
As per #2470 the `IWebBrowser` param as added to each method of the `IDownloadHandler` interface and example is available at 
https://github.com/cefsharp/CefSharp/blob/cefsharp/67/CefSharp.Example/DownloadHandler.cs
