### ISSUE TITLE
Unable to play youtube videos in build 69.0.0-CI2804

### ISSUE THREAD

**Issue by Daszbinn** [cefsharp/CefSharp#2540]
I am running Cefsharp for winforms the version 69.0.0-CI2804 32 bit whenever I go on youtube no videos are working or able to view this. I'm just reporting the bugs because with version 69.0.0-CI2803 worked on youtube but not 69.0.0-CI2804

**Comment by amaitland** [comment]
Using https://github.com/cefsharp/CefSharp/commit/5396f7023200744c431976a631cbc193c287bbf3 and attempting to play https://www.youtube.com/watch?v=fOzBVy-sDbM in `CefSharp.WinForms.Example` and it works as expected

If a `youtube` video is only available in `H264` encoding then it won't play in `CefSharp`, see https://magpcss.org/ceforum/viewtopic.php?f=6&t=16274

**Comment by KernelLeak** [comment]
Is it possible that you tried/reported this in the middle of YouTube's big outage earlier today?

**Comment by amaitland** [comment]
> Is it possible that you tried/reported this in the middle of YouTube's big outage earlier today?

@KernelLeak Thanks for the info 👍 

`Youtube` have confirmed the outage and that it was resolved https://twitter.com/TeamYouTube/status/1052393799815589889

Closing this as `invalid`, the only difference between the two versions is some xml doc.
