### ISSUE TITLE
How can I open a Silverlight page with CefSharp?

### ISSUE THREAD

**Issue by yuriburk** [cefsharp/CefSharp#2541]
Hello, I'm trying to use CefSharp to open a silverlight page in my application, but it only shows to download the plugin and never loads the page. How can I do to make it work? Is there any way to install the plugin in the build or is there a version that doesn't need a plugin...? Thanks.

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
`Chrome` stopped supporting silverlight long ago, there is no workaround.

https://support.microsoft.com/en-au/help/3058254/microsoft-silverlight-may-not-work-in-recent-versions-of-google-chrome

**Comment by yuriburk** [comment]
> `Chrome` stopped supporting silverlight long ago, there is no workaround.
> 
> https://support.microsoft.com/en-au/help/3058254/microsoft-silverlight-may-not-work-in-recent-versions-of-google-chrome

Isn't there any cefsharp that use chrome in version 42-44?

**Comment by amaitland** [comment]
My comments relate to the current supported version. If you choose to use an old unsupported version that is up to you.
