### ISSUE TITLE
Flashplayer is not the latest version

### ISSUE THREAD

**Issue by ytukids** [cefsharp/CefSharp#2543]
First,thanks for your work about cefsharp.  I got cefsharp.winform 67.0.0.0 release from nuget. I tried to enable flashplayer using code like  following:
            var settings = new CefSettings();
            settings.CefCommandLineArgs.Add("plugin-policy", "allow");
            settings.CefCommandLineArgs.Add("ppapi-flash-path", pluginPath);
            settings.CefCommandLineArgs.Add("ppapi-flash-version", "29.0.0.113");
But when I try to  open url needs flashplayer it noticed that flashplayer is not the latest version . How can i do about this? thanks

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/wiki/General-Usage#adobe-flash-player-pepper-flash

**Comment by amaitland** [comment]
Question asked https://gitter.im/cefsharp/CefSharp?at=5bcc211864cfc273f9fe21f3
