### ISSUE TITLE
CefSharp.WinForms  "Dock =DockStyle.Fill" no effect, black edge. 

### ISSUE THREAD

**Issue by wyqlib** [cefsharp/CefSharp#2544]
```
public partial class TBForm : Form
    {
        private readonly ChromiumWebBrowser browser;
        public TBForm()
        {
            InitializeComponent();
            browser = new ChromiumWebBrowser("www.baidu.com")
            {
                 Dock =DockStyle.Fill,
            };

            this.Controls.Add(browser);
            
        }
    }
```
<img width="491" alt="formtb" src="https://user-images.githubusercontent.com/39260969/47264493-de611280-d54a-11e8-9ba8-682dcad10d0b.PNG">

CefSharp.WinForms
"Dock =DockStyle.Fill" no effect, black edge.

how to make  the ChromiumWebBrowser  fill the TBForm?

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
Asked at https://stackoverflow.com/questions/52913442/cefsharp-winforms-dock-dockstyle-fill-no-effect-black-edge-how-to-make-the-c
