### ISSUE TITLE
Draggable borderless window C# WinForms

### ISSUE THREAD

**Issue by Xhonor** [cefsharp/CefSharp#2549]
Hello. I can not figure it out.
I have borderless form. How can I make it so that I can move the window (by holding the mouse) for a some div?
Sry for bad english :)

This dont work...
```
	.title-area 
	{
		-webkit-user-select: none;
		-webkit-app-region: drag;
		-moz-user-select: none;
		user-select: none;	
	}
        <div class='title-area' style="min-width: 100%; height: 40px; background: red;"></div>
```

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
See #1593 for some suggestions

**Comment by qwqcode** [comment]
I dit it!!!

![](https://user-images.githubusercontent.com/22412567/50545691-67d04780-0c54-11e9-85d1-d91ee3f8a2d9.gif)

[https://github.com/qwqcode/CefSharpDraggableRegion](https://github.com/qwqcode/CefSharpDraggableRegion)

This you can specify `-webkit-app-region: drag` in CSS to tell CefSharp which regions are draggable (like the OS's standard titlebar).

**Comment by ly303550688** [comment]
how can id resize the window?
