### ISSUE TITLE
WebView Dispose CefSharp.Wpf 1.25.7

### ISSUE THREAD

**Issue by manager666** [cefsharp/CefSharp#255]
Hi!

I would like to report a problem with method Dispose() on WebView in CefSharp.Wpf.
It does not matter when I call Dispose(), it it´s 98% chance that the application will crash.

When I call Dipose(), I get C++ Runtime error with message "pure virtual function call".

Can someone tell me where is a problem or fix it? On the other hand I simply need to know how to safely release (when app is closing) unmanaged resources which CefSharp or CehSharp.Wpf (WebView) is using.

Thank you very much.
I replaced IE WPF component with this awesome one but I need stability.

**Comment by Bodekaer** [comment]
I experience this issue when closing the application, and running CEF Shutdown.
It's happening randomly, and hard to reproduce.

Any advice on what I should look for and where to try and fix this?
Some info that might help, as it looks like it might be something in our dispose calls: http://stackoverflow.com/questions/99552/where-do-pure-virtual-function-call-crashes-come-from

**Comment by amaitland** [comment]
@Bodekaer Are you using `CefSharp1`?

**Comment by Bodekaer** [comment]
Using `CEF3`. Didn't realize this issue was for `CefSharp1`.
I see #585 already discusses the issue I experience. I'll comment there instead.

**Comment by amaitland** [comment]
@Bodekaer No probs :+1:
