### ISSUE TITLE
Not work Incogneto

### ISSUE THREAD

**Issue by AgapovAlexsey** [cefsharp/CefSharp#2550]
- **What version of the product are you using?**
build from "master" branch. Latest commit 23b905d

- **What architecture x86 or x64?**
x86 

- **On what operating system?**
   Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
    delete "settings.CachePath = "cache";" in CefExample.cs and Run CefSharp.Wpf.Example. Go any site with authorization and log in. Restart application. Your cookies is save. 

- **What is the expected output? What do you see instead?**
 clear session

- **Does this problem also occur in the CEF Sample Application**
I can not build it now

**Comment by amaitland** [comment]
> * **Does this problem also occur in the CEF Sample Application**
>   I can not build it now

You should test with the `CEF Sample Application`, you do not need to build anything, it's a simple download. See https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-chromium-embedded-frameworkcef for instructions

`CefSharp` has no control over caching, this will likely be closed as `upstream`. Please test with the `CEF Sample Application`.

**Comment by amaitland** [comment]
Looking this further and I'm closing as `invalid`.

The `WPF` and `WinForms` example both set an explicit storage path for the cookie store (to demo that feature). Cookies are still persisted when using those examples.

https://github.com/cefsharp/CefSharp/blob/cefsharp/69/CefSharp.Example/Handlers/BrowserProcessHandler.cs#L23

In general you should always perform testing using https://github.com/cefsharp/CefSharp.MinimalExample

`master` is the development branch
