### ISSUE TITLE
CefSharp.Wpf  at high resolution is slow ,is not fix?

### ISSUE THREAD

**Issue by ourplan9000** [cefsharp/CefSharp#2555]
_Originally posted by @ourplan9000 in https://github.com/cefsharp/CefSharp/issues/1058#issuecomment-434249373_

**Comment by ourplan9000** [comment]
CefSharp.Wpf at 8k   is very slow

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp)

**Comment by amaitland** [comment]
Try the command line args listed in #1058, if that doesn't work then you can use the `WinForms` version in `WPF` to obtain better performance. 

It will be possible to implement `DirectX` rendering once #2527 has been resolved (not that I say implement, not use, as it will require additional code changes).
