### ISSUE TITLE
Feature Request - Get list of current Tabs / Windows

### ISSUE THREAD

**Issue by Herya** [cefsharp/CefSharp#2556]
I looked for a way to call a function to get a list of current tabs and windows opened, but I can't find it.

It could be usefull for some tabs which self opened on click and that ilifespanhandler can't handle (the onpopup is not raised).

Thanks

**Comment by amaitland** [comment]
It's important to note that `CefSharp` is just a wrapper around the `Chromium Embedded Framework (CEF)`. Closing this as `upstream` and as changes need to be made in `CEF`. 

The `CEF` project has it's own forum at https://magpcss.org/ceforum/viewforum.php?f=7

**Comment by amaitland** [comment]
If you are successful in getting changes made to CEF this can be reopened.

**Comment by amaitland** [comment]
> ilifespanhandler can't handle (the onpopup is not raised).

If you can reproduce this then you should post on https://magpcss.org/ceforum/viewforum.php?f=6
The `CEF` class is https://magpcss.org/ceforum/apidocs3/projects/(default)/CefLifeSpanHandler.html
