### ISSUE TITLE
JavaScript uses "use strict"ChromiumWebBrowser can't interpret and refresh the page automatically

### ISSUE THREAD

**Issue by BigHelix** [cefsharp/CefSharp#2564]
When JavaScript uses "use strict" and has multiple definitions of an attribute, ChromiumWebBrowser can't interpret and refresh the page automatically. How do you force to ignore the "use strict" mode or intercept the JavaScript content returned by Get/post to remove the "use strict" character and return it to Chromium Web Browser for execution? http://video.tudou.com/v/XMzc1NDEyMDQ3Ng==.html

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage
