### ISSUE TITLE
CefSharp not closed after closing the app

### ISSUE THREAD

**Issue by Nitin-Rathore** [cefsharp/CefSharp#2565]
Hi Team,

I am using CefSharp WPF version 67.0.0 (Runtime Version v4.0.30319).
Sometimes CefSharp.BrowserSubprocess.exe not closed even after the app is closed.
It frequently occurs if the frames are loading meanwhile we closed the app or more than one instances of Chromium web browser are opened in the app.

I am closing all the instances at the time of app closing but sometimes the CefSharp.BrowserSubprocess.exe running in the windows task manager.

Thanks,
Nitin Rathore

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
See http://cefsharp.github.io/api/67.0.0/html/P_CefSharp_CefSharpSettings_SubprocessExitIfParentProcessClosed.htm
