### ISSUE TITLE
Application freezing on shutdown

### ISSUE THREAD

**Issue by rshkhz** [cefsharp/CefSharp#2566]
I create and initialize in new thread (background property = true). Then this thread call `Cef.Shutdown()`. Sometimes it cause deadlock. Help me please to find out what is the problem

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by rshkhz** [comment]
But I called `Cef.Initialize` and `Cef.Shutdown` in one new thread in console application

**Comment by amaitland** [comment]
Bug reports only thank you!
