### ISSUE TITLE
Application/x-mpegURL Not supported

### ISSUE THREAD

**Issue by semiem** [cefsharp/CefSharp#2567]
***Media type not supported by this browser (Application/x-mpegURL).***
- samples:
Floyd Player - JW Player - ...
every hls player!

**Comment by amaitland** [comment]
Only free `audio` and `video` codecs are supported see https://github.com/cefsharp/CefSharp/wiki/General-Usage#multimedia-audiovideo

It's also important to remember that `CefSharp` is just a wrapper, if support for a particular technology is missing then you should discuss it on https://magpcss.org/ceforum/index.php
