### ISSUE TITLE
Blank Popups when downloading

### ISSUE THREAD

**Issue by plumlee001** [cefsharp/CefSharp#2568]
When clicking on a link to download a file, some websites open a popup to service that request. The popup ends up being blank.

Chrome will automatically close these popup windows once the download is complete. How might I do this in CefSharp? Obviously, I know from the download handler when the download is done, but I'm not sure how to reconcile the download with the window I need to close.
I considered just returning true from the OnBeforePopup call, but this prevents the download occurring altogether.

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
The topic has been covered many times already.

https://magpcss.org/ceforum/viewtopic.php?f=6&t=15010
https://magpcss.org/ceforum/viewtopic.php?f=6&t=6037
https://github.com/cefsharp/CefSharp/pull/1033/files
