### ISSUE TITLE
Opening web pages on the win10 tablet is slow to load, as is opening local HTML

### ISSUE THREAD

**Issue by GanZhiXiong** [cefsharp/CefSharp#2570]

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by GanZhiXiong** [comment]
I have solved this problem, it is related to win10 system, I update to the latest win10 system will not appear
