### ISSUE TITLE
It like ConsoleMessage event not spport console.log with more than one parameters

### ISSUE THREAD

**Issue by hzexe** [cefsharp/CefSharp#2571]
CefSharp version 67
website:
`
console.log('a','b','c')
`
Will be output a b c in console，but only a in cefsharp

**Comment by amaitland** [comment]
Closing as `upstream`, see https://bitbucket.org/chromiumembedded/cef/issues/324/only-the-first-consolelog-argument-is

**Comment by BuslikDrev** [comment]
Вы можете в начале html  или через CefSharp.WebBrowserExtensions.ExecuteScriptAsync() добавить обработку консольных команд.
javascript
```
window.console.logs = window.console.log;
window.console.log = function(...args) {
	window.console.logs.apply(this, args);
};
```
