### ISSUE TITLE
Cefsharp69 failed to run on win7 32

### ISSUE THREAD

**Issue by connie61** [cefsharp/CefSharp#2572]
cefsharp 69
win7 X86
Running failed，and error is as follows.But low version is working fine.
![clipboard](https://user-images.githubusercontent.com/33438415/48683050-3c365800-ebe6-11e8-8040-6883fd0e3a17.png)

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
As per the release notes you will need `VC++ 2015`

https://github.com/cefsharp/CefSharp/releases/tag/v69.0.0-pre01

**Comment by connie61** [comment]
VC++ 2015 X86 installed,still reporting this error

**Comment by amaitland** [comment]
Seems unlikely this is a bug in `CefSharp`. The package structure hasn't changed.

An image of an exception that contains no stack trace, no detail is completely unhelpful, please read http://idownvotedbecau.se/imageofanexception/

**Comment by amaitland** [comment]
There are plenty of debugging tools available, like https://docs.microsoft.com/en-us/sysinternals/downloads/procmon that you can use.

**Comment by amaitland** [comment]
For testing purposes you should use the `MinimalExample` see https://github.com/cefsharp/CefSharp.MinimalExample/tree/cefsharp/69 for the `69` branch.

If it's working on other machines then it's not a bug and something about your environment. You've not provided enough information for me to help you.

**Comment by connie61** [comment]
OK,I will try again,thank you very much!

**Comment by amaitland** [comment]
If you require further assistance please ask on https://gitter.im/cefsharp/CefSharp

**Comment by connie61** [comment]
OK,thank you very much.

**Comment by amaitland** [comment]
Using a `Win7 x86 IE11` virtual machine downloaded from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ and the official `69.0.0` release as part of https://github.com/cefsharp/CefSharp.MinimalExample and it works as expected in `Win7`.

There is no functional difference between `69.0.0-pre01` and `69.0.0`, just a few fixes to some xml documentation, so using the `pre01` should yield the exact same result.
