### ISSUE TITLE
Add New Cookies In CefSharp Vb.net

### ISSUE THREAD

**Issue by seby1302** [cefsharp/CefSharp#2573]
Hello I use CefSharp V69,0 in VB.net, and have the following problem.

I want to Add new cookies But.

 CefCookieManager.Global.SetCookie (CefCookieManager) Is a friend and not in this Context not available.

And 
 cef.SetCookie (Cef) is not is not a member of SetCookie.

Wie kann ich neue cookies Add?

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/blob/cefsharp/69/CefSharp.Example/Handlers/BrowserProcessHandler.cs#L25 for an example of setting a cookie.
