### ISSUE TITLE
Form filling (saving state fields)

### ISSUE THREAD

**Issue by MikhailMelnikovNsk** [cefsharp/CefSharp#2574]
**What version of the product are you using?**

69.0.0

**What architecture x86 or x64?**

x86

**On what operating system?**

Win10

**Are you using WinForms, WPF or OffScreen?**

WinForms

**My code:**

```c#
private Task SetForm(string email)
{
	var tcs = new TaskCompletionSource<bool>();

	EventHandler<LoadingStateChangedEventArgs> handler = null;

	handler += (sender, args) =>
	{
		if (args.IsLoading == false)
		{
			_browser.LoadingStateChanged -= handler;

			string login = email.Split('@')[0];

			string script = string.Format("$('input[name=login]').val('" + login + "'); $('button').click();");

			_browser.EvaluateScriptAsync(script).ContinueWith(taskLogin =>
			{
				if (taskLogin.Result.Success)
				{
					_browser.GetSourceAsync().ContinueWith(taskHtml =>
					{
						if (!taskHtml.IsFaulted)
						{
							string html = taskHtml.Result;

							...

							tcs.TrySetResult(true);
						}
					});
				}
			});
		}
	};

	_browser.LoadingStateChanged += handler;

	_browser.Load(@"https://site.com/auth/");

	return tcs.Task;
}
```

**My question:**

string script = string.Format("$('input[name=login]').val('" + login + "'); $('button').click();");

In this example **$('button').click();** - form responded successfully.

But **$('input[name=login]').val('" + login + "');** - the field "login" is not filled.

If without $('button').click(); - the field "login" filled.

Only the state of the last script is fixed in form. How to make all states persist?

**Example:**

![example](https://user-images.githubusercontent.com/40119987/48825847-3afa5c00-ed9b-11e8-9337-15a1ef8f9e25.jpg)

**Comment by amaitland** [comment]
> But **$('input[name=login]').val('" + login + "');** - the field "login" is not filled.
> 
> If without $('button').click(); - the field "login" filled.

This makes no sense to me, please explain in detail.

> Only the state of the last script is fixed in form. How to make all states persist?

What state are you talking about? What is the last script exactly? As stated in the bug report template it's best if you fork https://github.com/cefsharp/CefSharp.MinimalExample and provide a an example of your problem.

**Comment by MikhailMelnikovNsk** [comment]
Oh, sorry my english...

string script = string.Format("$('input[name=login]').val('" + login + "'); **$('button').click();**");

![example-1](https://user-images.githubusercontent.com/40119987/48882202-ae5ba680-ee4b-11e8-88bd-d3a660bca900.jpg)

string script = string.Format("$('input[name=login]').val('" + login + "');");

without **part** of script: $('button').click();

![example-2](https://user-images.githubusercontent.com/40119987/48882213-bb789580-ee4b-11e8-8dff-168ce8acbf85.jpg)

I need to fill a web form and submit it with CefSharp.

**Comment by amaitland** [comment]
I still don't understand, doesn't sound like a bug thought. Did you try executing your JavaScript in devtools?

Some forms have validation that gets in the way. I also recommend wrapping code in anon closure. 

Please only open an issue if you have a bug to report.

**Comment by MikhailMelnikovNsk** [comment]
Ok. I will check different ways.

**Comment by amaitland** [comment]
As a final comment I'll point out calling `EvaluateScriptAsync` and then immediately calling `GetSourceAsync` won't get you the source of the post request (`GetSourceAsync` is a little problematic as it is, it's a `CEF` issue and nothing I can do, sometimes adding a small delay of say `500ms` helps).

If you require further assistance please ask on https://stackoverflow.com/questions/tagged/cefsharp

**Comment by MikhailMelnikovNsk** [comment]
Thanks for advice. The error is really somewhere in loading. I rewrote the code for testing.

While loading the method "InitializeChromium" a warning appears:

**INFO:CONSOLE(51)] "chrome.loadTimes() is deprecated, instead use standardized API: Paint Timing. https://www.chromestatus.com/features/5637885046816768.", source: https://yastatic.net/passport-frontend/0.2.98-12/public/js/react.registration.vendor.js (51)**

I think the page is not fully loaded. But I don’t know if it’s a bug or I’m doing something wrong.

**Source code:**

using System;
using CefSharp;
using CefSharp.WinForms;
using System.Windows.Forms;
using System.Threading.Tasks;

namespace Checker
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            InitializeChromium();
        }

        private ChromiumWebBrowser _browser;

        private void InitializeChromium()
        {
            CefSettings settings = new CefSettings();

            Cef.Initialize(settings);

            _browser = new ChromiumWebBrowser(@"https://passport.yandex.ru/registration/");

            Controls.Add(_browser);

            _browser.Dock = DockStyle.Fill;
        }

        private void Form1_FormClosing(object sender, FormClosingEventArgs e)
        {
            Cef.Shutdown();
        }

        private async void buttonCheck_ClickAsync(object sender, EventArgs e)
        {
            string login = "nsknsk";

            await SetLoginAsync(login);

            await ClickButtonAsync();
        }

        private Task SetLoginAsync(string login)
        {
            var tcs = new TaskCompletionSource<bool>();

            string script = string.Format("$('input[name=login]').val('" + login + "');");

            _browser.EvaluateScriptAsync(script).ContinueWith(task =>
            {
                if (task.Result.Success)
                {
                    tcs.TrySetResult(true);
                }
            });

            return tcs.Task;
        }

        private Task ClickButtonAsync()
        {
            var tcs = new TaskCompletionSource<bool>();

            string script = "$('button').click();";

            _browser.EvaluateScriptAsync(script).ContinueWith(task =>
            {
                if (task.Result.Success)
                {
                    tcs.TrySetResult(true);
                }
            });

            return tcs.Task;
        }
    }
}
