### ISSUE TITLE
How to find DownloadItem in the cache

### ISSUE THREAD

**Issue by AzuresSunday** [cefsharp/CefSharp#2575]
Hi guys.
i want show DownloadItem information anytime in my Downloads page.
like Google Downloads page.
How do I achieve?
谢谢 ：）

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
The `CEF API` currently only exposes `CefDownloadHandler` which has two methods see https://magpcss.org/ceforum/apidocs3/projects/(default)/CefDownloadHandler.html

The feature request forum is https://magpcss.org/ceforum/viewforum.php?f=7
