### ISSUE TITLE
Message interceptor no longer intercepts WinForms messages

### ISSUE THREAD

**Issue by SirIntellegence** [cefsharp/CefSharp#2579]
- **What version of the product are you using?**
    - What version are you using? Nuget 69.0.0

- **What architecture x86 or x64?** x64 (possibly happens with x86, but I haven't tested it)

- **On what operating system?**
    - Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?** `WinForms`

- **What steps will reproduce the problem?**
Using `CefSharp.WinForms.Example`:  Build and run the example project
Navigate to "google.com" (or pretty much any other address)
After the page has finished loading open the "Zoom Level" menu and then click in the browser area.

- **What is the expected output? What do you see instead?**
Expected: Menu closes since you clicked elsewhere
Result: Menu stays open

- **Please provide any additional information below.**
    - Does the cef log provide any relevant information? Doesn't look like it.

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls? Nope

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
Nope (cef_binary_3.3538.1852.gcb937fc_windows64_client.tar.bz2)

Note: I have noticed that the following logic does not get hit in the broken state:
https://github.com/cefsharp/CefSharp/blob/485297bb7f149a708480165130b3319382f7846e/CefSharp.WinForms.Example/BrowserTabUserControl.cs#L250

**Comment by amaitland** [comment]
Integrate `CEF` into your existing message loop, see https://github.com/cefsharp/CefSharp/wiki/General-Usage#multithreadedmessageloop

If the `Message Interceptor` example no longer works, `Chromium` has probably changed it's `handle` structure, the example may need to be removed (It's only there as a rough guide anyway). You can use `Spy++` to determine which handle is currently being used by `Chromium`.

**Comment by amaitland** [comment]
> * Using `CefSharp.WinForms.Example`:  Build and run the example project
>   Navigate to "google.com" (or pretty much any other address)
>   After the page has finished loading open the "Zoom Level" menu and then click in the browser area.

This makes it sounds like it never works, where it actually does if you don't navigate to `Google`. It appears the handle is being destroyed (it's sent a `WM_DESTROY` message) when a render process switch happens (instigated by the navigation to a different domain).

It should be possible to release the `NativeWindow` when `WM_DESTROY` is received and then find the newly created handle. 

By all means submit a `PR` that improves the code.
