### ISSUE TITLE
clear memory cache with out restarting program.

### ISSUE THREAD

**Issue by majorlinkPeter** [cefsharp/CefSharp#2580]
i would like to ask is there are any method to clear memory cache with out restarting program?

because i would like to make a public kiosk that clear all cache or data if back to home page.

Please help

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
Duplicate of #1234
