### ISSUE TITLE
(System.NullReferenceException)  error

### ISSUE THREAD

**Issue by magicstorm2018** [cefsharp/CefSharp#2586]
i got error (System.NullReferenceException)  on :

        public Form1()
        {
             InitializeComponent();
            chrome.LoadingStateChanged += OnLoadingStateChanged;
        } 
i hope to solve

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
You can use https://github.com/cefsharp/CefSharp.MinimalExample to get started and testing purposes. If you require further assistance please use one of the options above.
