### ISSUE TITLE
How i can translate this syntax to execute on cefsharp

### ISSUE THREAD

**Issue by magicstorm2018** [cefsharp/CefSharp#2587]
How i can translate this syntax to execute on cefsharp
 this.webBrowser1.DocumentCompleted += new System.Windows.Forms.WebBrowserDocumentCompletedEventHandler(this.webBrowser1_DocumentCompleted_1);

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
Read https://github.com/cefsharp/CefSharp/wiki/General-Usage#handlers if you require further assistance then use one of the options listed above.
