### ISSUE TITLE
There is no implementation of the previous page or the next page of the call method?

### ISSUE THREAD

**Issue by GanZhiXiong** [cefsharp/CefSharp#2601]
I want to slide left on the tablet to show the previous page, right to show the next page, and I don't know how to do that.Thank you very much for your reply.

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
To my knowledge `CEF` does not currently support gestures. 

It does have a `Feature Request Forum` at https://magpcss.org/ceforum/index.php

**Comment by GanZhiXiong** [comment]
Ok, thank you very much for your reply!
