### ISSUE TITLE
mailto: url omits local part

### ISSUE THREAD

**Issue by centreboard** [cefsharp/CefSharp#2602]
- **What version of the product are you using?**
    69.0.0.0

- **What architecture x86 or x64?**
   Reproduced on both x86 and x64
- **On what operating system?**
    Win10 (1803)

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
  WinForms

- **What steps will reproduce the problem?**
   Example https://github.com/centreboard/cefsharp_mailto_example
   Register a custom scheme handler for `mailto`
   Navigate to a site with hyperlink `<a href='mailto:test@other.com'>test@other.com</a>` and click it

- **What is the expected output? What do you see instead?**
  Expected (worked with version 57): The resource handler receives the url `mailto:test@other.com` and creates windows can open your default email client to the address.
  Actual: The resource handler receives `mailto://other.com`, i.e. the local part is missing

- **Please provide any additional information below.**
    Can reproduce with arbitrary scheme name, the url received drops everything before the @ 

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
Nothing in the log

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
  Not aware of any, can reproduce reliably on both minimal example and when navigating to sites in embedded browser.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
    Trying cef_binary_3.3538.1852.gcb937fc_windows64_client
It doesn't implement "mailto:" scheme but dumping the trace does show the full url for mailto: links

{"pid":15432,"tid":10480,"ts":5700100251,"ph":"X","cat":"navigation","name":"RenderFrameHostImpl::BeginNavigation","args":{"frame_tree_node":32,"url":"mailto:test@other.com"},"dur":1246,"tdur":1004,"tts":11664081},
{"pid":15432,"tid":10480,"ts":5700100282,"ph":"S","cat":"navigation","name":"NavigationRequest","args":{"frame_tree_node":32,"url":"test@other.com"},"tts":11664111,"id":"0xaf6004a505778057"},

**Comment by amaitland** [comment]
@centreboard Thank you for taking the time to fill out the bug report and recreating an example that reproduces your problem.  It's very unlikely this is a bug in `CefSharp` as it's just a wrapper. 

I should point out that the expected method of handling a `mailto` is to implement `OnProtocolExecution`, `return true` to allow the default `OS` handler to execute.

http://cefsharp.github.io/api/67.0.0/html/M_CefSharp_IRequestHandler_OnProtocolExecution.htm

**Comment by amaitland** [comment]
Closing as `wontfix` as we don't do anything with the `Url` (other than wrap the native string).

https://github.com/cefsharp/CefSharp/blob/cefsharp/69/CefSharp.Core/Internals/CefRequestWrapper.cpp#L33
