### ISSUE TITLE
Update Dependency Check 

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#2603]
Look at updating depency check to validate dependencies relative to the BrowserSubProcess.

**Comment by amaitland** [comment]
> Gets the pathname of the base directory that the assembly resolver uses to probe for assemblies.

https://docs.microsoft.com/en-us/dotnet/api/system.appcontext.basedirectory?view=netframework-4.7.2

Look into `AppContext.BaseDirectory`

**Comment by amaitland** [comment]
> https://docs.microsoft.com/en-us/dotnet/api/system.appcontext.basedirectory?view=netframework-4.7.2
> 
> Look into `AppContext.BaseDirectory`

Is only available in `.Net 4.6` and above, so we cannot use this option.

**Comment by amaitland** [comment]
`DependencyChecker` should now work correctly when using `AnyCPU` support with an assembly resolver.

**Comment by FlorianObermayer** [comment]
@amaitland Following up to [here](https://github.com/cefsharp/CefSharp/commit/416c4d7f9f3d758f5991efc3eefb053c11530661#r31931987):

> This line is throwing a `System.UriFormatException` when `browserSubProcessPath` is the default value ("CefSharp.BrowserSubProcess.exe")

>> Please comment on #2603 instead.
>> 
>> The default is no longer `CefSharp.BrowserSubProcess.exe`, please clarify what you mean. Are you manually setting the value to `CefSharp.BrowserSubProcess.exe`?

I am calling `DependencyChecker.AssertAllDependenciesPresent()` (without arguments) and run into mentioned exception.

> The default is no longer `CefSharp.BrowserSubProcess.exe`

 Am I missing something? [Line 175](https://github.com/cefsharp/CefSharp/commit/416c4d7f9f3d758f5991efc3eefb053c11530661#diff-930decd517f24ab2799462b74a96cd0fL175) still has it as the default value and it remains untouched until [Line 179](https://github.com/cefsharp/CefSharp/commit/416c4d7f9f3d758f5991efc3eefb053c11530661#diff-930decd517f24ab2799462b74a96cd0fR179).

Maybe use: [Uri.TryCreate(...)](https://docs.microsoft.com/en-us/dotnet/api/system.uri.trycreate?redirectedfrom=MSDN&view=netframework-4.7.2#System_Uri_TryCreate_System_String_System_UriKind_System_Uri__) instead, or did you intend to combine the default value somehow with the `path` variable?

**Comment by amaitland** [comment]
> I am calling `DependencyChecker.AssertAllDependenciesPresent()` (without arguments) and run into mentioned exception.

@FlorianObermayer Thank you, I totally missed that use case.

Switching to` Uri.TryCreate` is much better option, change made in https://github.com/cefsharp/CefSharp/commit/bbfe998ffa823cc070aa3f9e1b159b8bd7e7b69e
