### ISSUE TITLE
How Can I Replace website url javascript to my local files??

### ISSUE THREAD

**Issue by wzhs** [cefsharp/CefSharp#2609]
How Can I Replace website url javascript to my local files??

for example 
the website page is 
`<script src="/bundles/aggsite.js?v=DQ7gMkQYPgVxeTONynmeD-nGopAp4nxeNZLgQqIdh1A1" type="text/javascript"></script>`

replace to 
`<script src="c://test.js" type="text/javascript"></script>`

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage
