### ISSUE TITLE
CefSharp.Core.dll fails to load with error 0x80070716 on Win 10 1809 if UMCI is enabled

### ISSUE THREAD

**Issue by bburky** [cefsharp/CefSharp#2610]
- **What version of the product are you using?** 69.0.0 Nuget in CefSharp.MinimalExample
- **What architecture x86 or x64?** x64
- **On what operating system?** Win 10 Pro 1809
- **Are you using `WinForms`, `WPF` or `OffScreen`?** WPF (affects all I think)
- **What steps will reproduce the problem?**

    1. Download the [Device Guard and Credential Guard hardware readiness tool](https://www.microsoft.com/en-us/download/details.aspx?id=53337) and in an elevated PowerShell window run: 

        ```powershell
        .\DG_Readiness_Tool_v3.6.ps1 -Enable
        ```

        This enables Credential Guard and Hypervisor Code Integrity (HVCI). A code integrity policy is also installed. The audit-only code integrity policy used by the readiness tool also enables User Mode Code Integrity (UMCI).

    2.  Attempt to build CefSharp.MinimalExample or run any program using CefSharp. Windows does not allow CefSharp.Core.dll to be loaded, crashing the program or causing a build error. Attempting the build gives the following error:

        ```
        1>------ Build started: Project: CefSharp.MinimalExample.Wpf, Configuration: Release x86 ------
        1>C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.WinFx.targets(268,9): error MC1000: Unknown build error, 'Could not load file or assembly 'file:///C:\Users\Blake\Code\CefSharp.MinimalExample\packages\CefSharp.Common.69.0.0\CefSharp\x86\CefSharp.Core.dll' or one of its dependencies. The specified resource name cannot be found in the image file. (Exception from HRESULT: 0x80070716)' 
        ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
        ```

- **What is the expected output? What do you see instead?** CefSharp should run with Credential Guard, Hypervisor Code Integrity and User Mode Code Integrity enabled.

- **Please provide any additional information below.**

    CefSharp will work again after either of the following commands:

    ```powershell
    .\DG_Readiness_Tool_v3.6.ps1 -Disable
    rm C:\Windows\System32\CodeIntegrity\SIPolicy.p7b
    ```

    I managed isolate the cause of this bug by Googleing "0x80070716" and "1809". I discovered this [fourm thread about the same issue affecting CefSharp in Power BI](https://community.powerbi.com/t5/Desktop/Cannot-Start-Power-BI-desktop-64-or-32-bit/td-p/537491). That thread looks to have the same error I found. That thread claims:

    >This is related to Windows Defender settings. This issue affects all customers who are using WDAC with User Mode Code Integrity enabled (in audit or enforced mode). We believe it is also limited to Windows 10 RS5 (October update)
    >
    >so if you are running WDAC and have windows 1809 installed Power BI wont work. Disabeling WDAC will make power BI start.

    Which mostly matches what I found. I never isolated the cause to be UMCI specifically, but it was part of the code integrity policy I applied. (I would try to isolate the issue to UMCI specifically, but I can't figure out if Device Guard is supported on Win 10 Pro or only on Enterprise. The tools to create a custom policy refuses to run on Pro.)

    I discovered this issue because I had run the readiness tool and later tried to run the program [Playnite](https://github.com/JosefNemec/Playnite) which uses CefSharp. After lots of debugging this issue (https://github.com/JosefNemec/Playnite/issues/849) I isolated the cause.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

    cefclient works correctly and launches. Tested with cef_binary_3.3578.1860.g36610bd_windows32_client.tar.bz2 and cef_binary_3.3578.1860.g36610bd_windows64_client.tar.bz2

**Comment by amaitland** [comment]
@bburky Thanks for the detailed bug report 👍 

> * cefclient works correctly and launches. Tested with cef_binary_3.3578.1860.g36610bd_windows32_client.tar.bz2 and cef_binary_3.3578.1860.g36610bd_windows64_client.tar.bz2

You are testing with `CEF 3.3578.1860.g36610bd / Chromium 71.0.3578.80`, which is what the current `master` is based on. If you have time testing with `master` would be helpful though I'm not really expecting anything to change.

I'm unable to upgrade past `1709` due to hardware comparability reasons, so I have no means of testing this at the moment. Might be worth reaching out to someone on the `Power BI` team and asking what changes were required.

**Comment by FlorianObermayer** [comment]
Apparently Microsoft fixed the issue. After installing [KB4487044](https://support.microsoft.com/de-de/help/4487044) (Build `17763.316` from 12. Februar 2019), the problem disappeared.

**Comment by amaitland** [comment]
Link to English version https://support.microsoft.com/en-us/help/4487044/windows-10-update-kb4487044

Closing as there is now a fix.

**Comment by bburky** [comment]
I can confirm the issue appears to be resolved. I can now start applications using CefSharp while it is enabled.
