### ISSUE TITLE
Support .Net Core 3.0

### ISSUE THREAD

**Issue by AsValeO** [cefsharp/CefSharp#2611]
After WPF project migrated to .NET Core 3.0 CEFSharp cannot resolved some dependencies in runtime.
Target platform is x64 only.
```
Could not load file or assembly 'CefSharp.Core, Version=69.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138'. An attempt was made to load a program with an incorrect format.
An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B) 
```

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by AsValeO** [comment]
It is a kind of bug. CefSharp.**WPF** doesn't work on a new kind of **WPF** application.

**Comment by amaitland** [comment]
Duplicate of #2438

**Comment by amaitland** [comment]
Subscribe to  #2796 to track the progress.
