### ISSUE TITLE
how to through disable javascript to reducing CPU usage

### ISSUE THREAD

**Issue by leosx** [cefsharp/CefSharp#2618]
- **What version of the product are you using?**
    - CEF : 3.3538.1852.gcb937fc & Chromium : 70.0.3538.102

- **What architecture x86 or x64?**
   - x64

- **On what operating system?**
    - Win7 & Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - Only WinForm

- **What is the expected output? What do you see instead?**
    - In my WinForm App, I created multiple ChromiumWebBrowser Instance, In some web page, It's CPU Usage is very high, I want to disable all  browsers JavaScript that are not displayed to customers, i find **ChromiumWebBrowser.BrowserSettings.Javascript** can control it. when i set it to **CefState.Disabled**, it's not work. CPU usage has not declined, and JavaScript continues to be executed. How i can do ?

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
    NO

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage
