### ISSUE TITLE
Integrate CefSharp into "WPF Browser App"?

### ISSUE THREAD

**Issue by vnlevanduoc** [cefsharp/CefSharp#2621]
I am using **"WPF Browser App"** for my project
Can I integrate CefSharp into **"WPF Browser App"**?

I tried it but haven't had a friend, please try this case

Thank you

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
Not supported see #2410
