### ISSUE TITLE
SOS！怎么下载HTTPS安全证书

### ISSUE THREAD

**Issue by easton2011** [cefsharp/CefSharp#2622]
目前需要确定谷歌浏览器访问HTTPS站点的时候，证书无法下载获取的问题困扰了很久，请各位帮帮忙解答一下

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage
