### ISSUE TITLE
CefSharp.Wpf not render even app compiles successfully

### ISSUE THREAD

**Issue by redplane** [cefsharp/CefSharp#2623]
Hi,

I'm using `CefSharp.WPF` for my personal project which is being done using **WPF**.
Everything seems to be fine with `Any CPU` configuration.
My app can run and compile.
But there is one more thing I am facing with is : 
- The `Cef.WPF` does not render in my application.

Here is the screenshot:

![The CEF.WPF control can still be rendered in design mode](https://user-images.githubusercontent.com/7974095/51254717-9da75700-19dc-11e9-89b6-903ad0c28fb1.png)
 

This is the code behind to load a page:

```
public partial class Login : Page
    {
        public Login()
        {
            InitializeComponent();
        }

        private void ChromiumWebBrowser_OnIsBrowserInitializedChanged(object sender, DependencyPropertyChangedEventArgs e)
        {
            var chromiumWebBrowser = (ChromiumWebBrowser) sender;
            if (chromiumWebBrowser == null)
                return;

            if (!chromiumWebBrowser.IsBrowserInitialized)
                return;

            chromiumWebBrowser.Load("https://www.google.com");
        }
    }
```

And this is the result I got when the app ran:

![cef-2](https://user-images.githubusercontent.com/7974095/51255073-79984580-19dd-11e9-8183-53c618664f74.png)

There is no **ChromiumWebBrowser** rendered in my application.

Am I doing anything wrong ?
I have read the [FAQ](https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions), but foud nothing.

This is my [REPO](https://bitbucket.org/Redplane/wpf-structure/src/master/) in case you need to take a look at the source code.

Thank you,

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
The `MinimalExample` contains working examples of `AnyCPU`. You can use one of those as a reference.

https://github.com/cefsharp/CefSharp.MinimalExample/branches/all?utf8=%E2%9C%93&query=anycpu

**Comment by amaitland** [comment]
The `AnyCPU` documentation is https://github.com/cefsharp/CefSharp/issues/1714

You have likely forgotten something, all steps are **important**!

**Comment by redplane** [comment]
Hi @amaitland ,
I had read the [AnyCPU document](https://github.com/cefsharp/CefSharp/issues/1714)

I followed option 1. But got stuck at this step:

```
[STAThread]
public static void Main()
{
    var settings = new CefSettings();
    settings.BrowserSubprocessPath = @"x86\CefSharp.BrowserSubprocess.exe";

    Cef.Initialize(settings, performDependencyCheck: false, browserProcessHandler: null);

    var browser = new BrowserForm();
    Application.Run(browser);
}
```

```BrowserForm``` not found in ```Cef.WPF```

**Comment by redplane** [comment]
Ah, I have made the solution 1 works for WPF app.

Instead of changing ```App.xaml``` from ```ApplicationDefintion``` to ```Page```.
I just override the `Startup` method with the below code:

```
public partial class App : Application
    {
        protected override void OnStartup(StartupEventArgs e)
        {
            var settings = new CefSettings();
            settings.BrowserSubprocessPath = @"x86\CefSharp.BrowserSubprocess.exe";

            Cef.Initialize(settings, performDependencyCheck: false, browserProcessHandler: null);
            base.OnStartup(e);
        }
    }
```

And finally, it worked.
