### ISSUE TITLE
How to create a WebUI page via CefSharp?

### ISSUE THREAD

**Issue by litouphone** [cefsharp/CefSharp#2624]
Hi, Recently I'm using the CefSharp to develop a tab web browser, and need a settings page.  I hope to be done like chrome://settings in chrome by version of 49. I found that chromium can be done by WebUI (http://www.chromium.org/developers/webui)，it said we add a class implemented by WebUIController to handle request to url  to explan the placeholder "i18n-content" , then javascript call "chrome.send" to callback. But I cannot find any resource about making a WebUI page via CefSharp。

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage
