### ISSUE TITLE
Feature Request - Add Support for compiling with VS2019

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#2628]
When `Visual Studio 2019` is released we can look at adding support for compiling `CefSharp`.

Research needs to be done into what `VC++` changes were made and if the version number has been bumped.

This is only required to compile `CefSharp` from source. There are no plans to change from targeting `VC++ 2015` as the default just yet.

- [ ] Remove `VS2013` support, this will allow for simplification as newer versions support targeting multiple platform toolsets.
- [x] Upgrade `CefSharp.props` to support `VS2019`.
- [ ] Add new `VS2019` target to `build.ps1`

**Comment by amaitland** [comment]
`VS2019` is out, as per https://visualstudio.microsoft.com/vs2019-launch/

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.props should be initially updated to support compiling in `VS2019` using the `VS2017` toolset.

**Comment by bennewi** [comment]
waiting for VS2019 support? I'm getting a 

Error		Error HRESULT E_FAIL has been returned from a call to a COM component.				

when installing with the "manage NuGet packages" within VS2019

**Comment by amaitland** [comment]
> Error Error HRESULT E_FAIL has been returned from a call to a COM component.

@bennewi  How exactly does this relate to compiling `CefSharp` from source?  

A very quick search and the error seems fairly common

- https://developercommunity.visualstudio.com/content/problem/260196/add-a-reference-raise-error-error-hresult-e-fail-h.html
- https://stackoverflow.com/questions/46683212/nuget-error-hresult-e-fail-has-been-returned-from-a-call-to-a-com-component?rq=1

If you are still having problems then I'd suggest you search/ask on `stackoverflow`

**Comment by amaitland** [comment]
The current requirements for **compiling from source** using `VS2019` are:

- `Windows 8.1 SDK`
- `VS2017 VC++ Build Tools`

We can look at adding `WindowsTargetPlatformVersion` to the `CefSharp.props` file in the `VS2019` section to remove the `Windows 8.1 SDK`  requirements. Example below.

```xml
<WindowsTargetPlatformVersion>10.0.17763.0</WindowsTargetPlatformVersion>
```

**Comment by amaitland** [comment]
https://devblogs.microsoft.com/setup/configure-visual-studio-across-your-organization-with-vsconfig/

We can add a vsconfig file to specify the build requirements in VS2019

**Comment by amaitland** [comment]
`.vsconfig` added in https://github.com/cefsharp/CefSharp/commit/ee06759c08b9a748720be372bf27964f04875062

Switched to using `v142` and specifying a newer `Windows 10 SDK`.

`VS2019` should warn you of any missing components now.
