### ISSUE TITLE
Reduce NuGet package size

### ISSUE THREAD

**Issue by gtaylor1981** [cefsharp/CefSharp#2630]
The CefSharp.Common nuget package includes the source and PDBs. As I have to check in NuGet packages, I notice these extra ~350 files and ~25MB size.

Would it be possible to create another 'lightweight' version of the NuGet package, excluding these extra files please?

**Comment by amaitland** [comment]
The `CefSharp.Common.71.0.0.nupkg` file for is only 6.9MB. It appears your trying to check in the uncompresses package which I really wouldn't recommend. 

- Check in the uncompressed source, add some entries to your `.gitignore` file or whatever source control you are using. I really don't recommend this (not sure that anyone does).
- Only checkin the `nupkg` files. If you must include binary files in your repository this is better.
- Create your own local `Nuget Repositoy`, this can be as simple as a folder that includes all your `.nuget` packages. Store it somewhere on your local network.

> Would it be possible to create another 'lightweight' version of the NuGet package, excluding these extra files please?

This might sound like a trivial task it would require quite a lot of effort, from my point of view the `pdb's` are must have, specially as `CefSharp` uses `GitLink`, so you can step straight into the source. The source is a leftover from when we used `Symbol Source` packages, they can in theory be removed. Though will likely be readded as `Microsoft` are adding a `Symbol Source Server` directly to `Nuget.org` (See https://blog.nuget.org/20180501/Welcoming-SymbolSource-to-Dot-Net-Foundation.html).

Closing as `wontfix` as the `cost-benefit` doesn't justify the work required.

**Comment by gtaylor1981** [comment]
Understood. Thank you for your comprehensive answer and work on the project.
