### ISSUE TITLE
Can't Play Vimeo Videos

### ISSUE THREAD

**Issue by TomOfekKafka** [cefsharp/CefSharp#2631]
**What version of the product are you using?**
    Nuget 71.0 (latest)

- What architecture x86 or x64?**
Both

- **On what operating system?**
    Win 10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.
    - Please no binary (zip, etc) links, fork the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) and push your changes to `GitHub`. (Alternatively use a code sharing service list `Gist` or `Pastebin`).

- **What is the expected output? What do you see instead?**
Cannot play Vimeo videos. When trying to play the same video from chrome, it plays. But when launching from CefSharp, I receive "Player error" in vimeo, with message "The player is having trouble. We'll have it back up and running as soon as possible". 

![image](https://user-images.githubusercontent.com/28560698/51801054-5ffac780-2241-11e9-94f3-f3564aecc4a2.png)

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/wiki/General-Usage#multimedia-audiovideo
