### ISSUE TITLE
Is there any reliable instructions for use

### ISSUE THREAD

**Issue by yh371174229** [cefsharp/CefSharp#2632]
Version:latest
I fllow this[ url ](https://ourcodeworld.com/articles/read/173/how-to-use-cefsharp-chromium-embedded-framework-csharp-in-a-winforms-application)  ,step to step do it ,but I can't success.
1. I use nuget install CefSharp.WinForms
2. I change the Main winform project property, check `prefer32- bit`
3. I close the vs,then I change` the myproject.csproj `file ,add it `<CefSharpAnyCpuSupport>true</CefSharpAnyCpuSupport>` with notepad++.
4. I reopen the vs project,I edit the app.config,I add the following code
```
<runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
        <probing privatePath="x86"/>
    </assemblyBinding>
</runtime>
```
I have not succeeded so far，very crazy，use it need a big heart.
Then I do the following steps like(B. CefSharp version 49 and older (x86 or x64)),
But I still failed，It's too complicated，not easy to use it。

![1](https://user-images.githubusercontent.com/5948456/51892118-e0edc680-23db-11e9-84e6-93789dc33d3b.png)

Is there any reliable instructions for use?
Forgive my poor English，Any help wiil appreciated！

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage
