### ISSUE TITLE
How to post json data to aspx page

### ISSUE THREAD

**Issue by mohitonet** [cefsharp/CefSharp#2633]
Hi,

I am opening a webpage in the cefsharp browser and trying to send a set of JSON data to my website's .aspx page along with query string. While the query string is not an issue but sending the JSON data to the same URL is what I am trying to fix. Earlier I was using Window's native WebBrowser control's Navigate method where I was passing the URL along with query string as well as a byte array. But, I don't find any such method to post the data. Various discussion and posts regarding the same don't work for me. Can you provide a sample code/example to show how to achieve that?

**Comment by amaitland** [comment]
Asked at https://stackoverflow.com/questions/54421719/json-data-post-to-the-url-opened-in-cefsharp-browser-with-example
