### ISSUE TITLE
Winforms references results in issues while opening other files

### ISSUE THREAD

**Issue by jeroenc89** [cefsharp/CefSharp#2634]
Hi all

We currently are having a very weird issue after adding CefSharp references to our Winforms project.

**Specifications**
 - CefSharp version 71.0.0.0 (Nuget).
 - x86 build 
 - Winforms application
 - Windows 10
 - .NET Framework 4.7

**Issue**
First off all: CefSharp is working without any issues.
The actual issues pops up when we are executing automated test with TestAutomation (TestComplete).

Some part of our code creates a txt file (e.g. File.WriteAllText("test", "file.txt")) and opens the file by using System.Diagnostics.Process.Start("file.txt").

This does result in an error in notepad: 
"file name, directory name or volume label syntax is incorrect"

This same error occurs if we try to start a exe, pdf, ... 
This issue occurs even if we haven't called the method which adds the webbrowser control in a Form, so I think it has something to do with the references...

If we don't add the required CefSharp files in the folder of our application, everything works like charm.

Does anyone have any clue what the CefSharp dlls have to do with System.Diagnostics.Process.Start?

Thanks in advance!

**Comment by amaitland** [comment]
Using Process.Start with CefSharp is a fairly common scenario.  Have you attempted to isolate the issue outside of your project?  You can use https://github.com/cefsharp/CefSharp.MinimalExample for testing. 

Have you tried an absolute path?

Have you tried using procmon or similar to see what paths are being used? https://docs.microsoft.com/en-us/sysinternals/downloads/procmon

Without an example that reproduces the problem there isn't really anything I can add here.

**Comment by jeroenc89** [comment]
Thanks for the quick response

That was the next step I'm going to test next week. I was hoping this issue occurred before :)

I'll keep you up to date!

**Comment by amaitland** [comment]
@jeroenc89 Were you able to reproduce your problem with the Minimal Example?

**Comment by amaitland** [comment]
Closing due to lack of feedback.
