### ISSUE TITLE
Devexpress docking library gives problems

### ISSUE THREAD

**Issue by Harm73** [cefsharp/CefSharp#2635]
- **What version of the product are you using?**
     - 71.0.0 Nuget
- **What architecture x86 or x64?**
     - x64
- **On what operating system?**
    - Win10 Pro 1803
- **Are you using `WinForms`, `WPF` or `OffScreen`?**
     - WinForms
- **What steps will reproduce the problem?**

The problem comes from the combination between CefSharp and the devexpress library. (https://www.devexpress.com/)
The library devexpress can be used for docking screens.

If the cefsharp browser is docked left, right, up and down, it works as expected
When the cefsharp browser is docked full screen, the browser crashes and the (possibly opened) developer tools disappear. Then it is also no longer possible to open the developer tools.
The entire browser has crashed and is not responding anymore.

      string webPage = "https://www.google.com";
      Browser = new ChromiumWebBrowser(webPage) { Dock = DockStyle.Fill };
      parent.Controls.Add(Browser);

- **What is the expected output? What do you see instead?**
the expected behavior is that there is no crash

- **Please provide any additional information below.**
     - No stack trace available, no exceptions

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
     - No information in de debug.log

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
    - We use the devexpress library (https://www.devexpress.com/)

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
The 
example is not used in the devexpress library
In the zip file is an example video about the problem

[2019-01-30 11-53-27.zip](https://github.com/cefsharp/CefSharp/files/2812204/2019-01-30.11-53-27.zip)

**Comment by amaitland** [comment]
You say it crashes yet there is no stack trace,  does crash accurately describe the problem? 

As per the issue template no zip files please. If the video relevant then upload it to a video sharing service like YouTube. 

You'll likely have to debug this yourself as I don't have devexpress installed.

**Comment by amaitland** [comment]
The title of this issue still needs work,  gives problems is too vague a description

**Comment by JavierCanon** [comment]
Do you try resizing manually the browser control, and not using DockStyle.Fill? set x=0, y=0 and with and height of parent container?

**Comment by amaitland** [comment]
Closing due to lack of feedback.  If someone wants to take charge of debugging this then say so and it can be reopened.
