### ISSUE TITLE
CORB error after upgrading to CefSharp-71

### ISSUE THREAD

**Issue by ray007** [cefsharp/CefSharp#2644]
- **What version of the product are you using?**
  CefSharp-71, self-compiled with self-compiled CEF
- **What architecture x86 or x64?**
  x86
- **On what operating system?**
   Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
  WPF
- **What steps will reproduce the problem?**
  My application requests some data from webservices returning JSON secured with basic auth.
  After the CefSharp upgrade, those data-requests returned an empty response and on the developer console I found an error:
```
Cross-Origin Read Blocking (CORB) blocked cross-origin response http://192.168.29.121/json_data/ with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```
  The same application in cefclient or normal chrome browser served from `http` does not have this problem. Only difference I'm aware of here is the webapp in the CefSharp app being served through a custom scheme.

Following the link from the error message, I tried to solve the problem with additional settings:
```
settings.CefCommandLineArgs.Add("disable-features", "CrossSiteDocumentBlockingAlways,CrossSiteDocumentBlockingIfIsolating");
```
but the problem still did persist. After some more research and advise from stackoverflow I added
```
settings.CefCommandLineArgs.Add("disable-site-isolation-trials", "true");
```
but still no good.

Only with
```
settings.CefCommandLineArgs.Add("disable-web-security", "true");
```
do I get the response data into my js-app again.

Completely disabling web-security does not sound like a smart idea in the long run - did I miss some other option to help here?

**Comment by amaitland** [comment]
What makes this a bug in `CefSharp` exactly? If you use `disable-web-security` and it works then it seems unlikely.

> Only difference I'm aware of here is the webapp in the CefSharp app being served through a custom scheme.

Seems like using a `custom scheme` is the root cause of the problem. Did you register your scheme with `CORS` enabled and add a `Cross Origin WhiteList entry`?

**Comment by ray007** [comment]
The bug is that [according to documentation](https://www.chromium.org/Home/chromium-security/corb-for-developers)
```
settings.CefCommandLineArgs.Add("disable-features", "CrossSiteDocumentBlockingAlways,CrossSiteDocumentBlockingIfIsolating");
```
should have done the trick.

I also don't understand why it works in chrome/cefclient with the application served from http, und not in my CefSharp program with the application served by custom scheme handler.

Why would I need to enable CORS for my custom scheme, when the problem is with the `http`/`https` calls?

Did I miss something?

**Comment by amaitland** [comment]
> The bug is that [according to documentation](https://www.chromium.org/Home/chromium-security/corb-for-developers)

Load `chrome://version/` in the browser, if `disable-features` appears in the `Command Line:` section then `CefSharp` has done it's job. The command line arg may only work for `http/https` schemes currently.

> Why would I need to enable CORS for my custom scheme, when the problem is with the `http`/`https` calls?

Where exactly does it say that? Do you believe that a 3rd party could take the description you provided an accurately reproduce your problem on first attempt?

> I also don't understand why it works in chrome/cefclient with the application served from http, und not in my CefSharp program with the application served by custom scheme handler.

If `Chromium` added a new flag/setting in relation to scheme registration then `CEF` would have to do likewise. Historically there were lots of cases where `CEF's` custom scheme implementation didn't match that of the built in schemes. `Fetch` support for instance was only added a few days ago (https://bitbucket.org/chromiumembedded/cef/commits/68189dc459de5632db521196ba9e21e157f1a330)

> Did I miss something?

- Try adding a cross origin whitelist entry. There is a method in the `Cef` class for this.
- Switch to using a `http/https` scheme and registering your handler for a specific domain.

**Comment by amaitland** [comment]
Testing with `custom://cefsharp/SchemeTest.html` in the `WinForms` or `WPF` example and the ``AJAX` request is made successfully, even when I change it to `https://httpbin.org/post`, I get the response as expected (minor change required to output the actual data).

Seems very unlikely this is a bug in `CefSharp`.

**Comment by ray007** [comment]
Hmm, strange, with the wpf example program it does work.
My program is still a bit simpler than that, since I started off with the example of about 6 years ago, so I'll need to investigate what different.
And I'm still on VS 2015, but that shouldn't make a difference, right?
