### ISSUE TITLE
blob_storage and GPUCache created next to Shortcuts

### ISSUE THREAD

**Issue by imPRAGMA** [cefsharp/CefSharp#2646]
- **What version of the product are you using?**
    v71 from Nuget

- **What architecture x86 or x64?**
    x64

- **On what operating system?**
    Win10 Home 64Bit

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WinForms

- **What steps will reproduce the problem?**
    Create a shortcut to the .exe (I personally have mine in C:/Program Files) and place it somewhere convenient like the Desktop and simply open the exe using the shortcut.

- **What is the expected output? What do you see instead?**
    I expected the folders to be made next to the .exe, its possible this is occuring due to C:/Program Files requiring Admin Permission for Write. Perhaps there is a feature to store these in AppData instead?

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
    Yes

![Heres an Image showing it occuring](https://i.imgur.com/Hn2Utvm.gif)
GPUCache will appear here too after the Form loads up but I didnt capture this in the Gif

**Comment by jankurianski** [comment]
I found this related CEF issue: https://bitbucket.org/chromiumembedded/cef/issues/2289/cefclient-creates-permanent-cache

Could you try setting `CefSettings.CachePath` when calling `Cef.Initialize()` and see if that changes where the directories are created?

**Comment by imPRAGMA** [comment]
[Screenshot](https://i.imgur.com/h2C6yMR.png)

It does but as you can see it also stores some general cache like cookies and stuff which I PURPOSELY do not want.

**Comment by amaitland** [comment]
> If you can reproduce the problem with cefclient then you'll need to report the bug on https://bitbucket.org/chromiumembedded/cef/overview there is no point opening an issue here. (Make sure you search before opening an issue)

I know it might be tempting to post here, if you can reproduce the issue with `cefclient` then in future please use the `CEF Issue Tracker`, search for an existing issue first of course.

> It does but as you can see it also stores some general cache like cookies and stuff which I PURPOSELY do not want.

You can try the `disable-gpu-shader-disk-cache` command line arg, though that might only work in older versions. Issue https://bitbucket.org/chromiumembedded/cef/issues/2289/cefclient-creates-permanent-cache needs to be resolved `upstream`.

> * I expected the folders to be made next to the .exe, its possible this is occuring due to C:/Program Files requiring Admin Permission for Write.

More likely the shortcut you are using is defaulting the working directory to the location of the actual shortcut. What is the `Start In` property of your shortcut set to?

**Comment by amaitland** [comment]
Closing this as `upstream`, if changes are required to `CefSharp` when https://bitbucket.org/chromiumembedded/cef/issues/2289/cefclient-creates-permanent-cache has been resolved this can be reopened.

**Comment by amaitland** [comment]
This has been resolved in https://bitbucket.org/chromiumembedded/cef/commits/e6986dc6773be9c9715fd526da2fdb0676336cb0

**Comment by KBojan** [comment]
I am using the version 73.1.130 and while the "blob_storage" folder was not being created anymore, this was not the case with "GPUCache". I needed to add the following command line argument to make it work:

```
var settings = new CefSettings
{
	CefCommandLineArgs = {["disable-gpu-shader-disk-cache"] = "1"}
};

Cef.Initialize(settings, false, browserProcessHandler: null);
```

**Comment by amaitland** [comment]
You should report the issue upstream.
