### ISSUE TITLE
How set  Window's property When  A new WPF window Opened

### ISSUE THREAD

**Issue by JnChristmas** [cefsharp/CefSharp#2648]
I want to set new window's property such as showIntaskbar==false in WPF ，and I have implemented the interface of ILifeSpanHandler here is my code ;

public bool OnBeforePopup(IWebBrowser chromiumWebBrowser, IBrowser browser, IFrame frame, string targetUrl, string targetFrameName, WindowOpenDisposition targetDisposition, bool userGesture, IPopupFeatures popupFeatures, IWindowInfo windowInfo, IBrowserSettings browserSettings, ref bool noJavascriptAccess, out IWebBrowser newBrowser)
        {
            newBrowser = null;
            Window newWindow = (Window)HwndSource.FromHwnd(windowInfo.WindowHandle).RootVisual;
            newWindow.ShowInTaskbar = false;
            return false; 
        }

but I get a error ,the windowinfo.WindowHandle's  value awalys 0x0000000 
please help me.

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage
