### ISSUE TITLE
IBrowserProcess is null, unable to bind object external

### ISSUE THREAD

**Issue by huanwang111** [cefsharp/CefSharp#2650]
- **What version of the product are you using?** : 67.0.0
    - **What architecture x86 or x64?**: X64

- **On what operating system?**
    - Win7 SP1.

- **Are you using `WinForms`, `WPF` or `OffScreen`?** : 'WPF'

- **What steps will reproduce the problem?**
    The binding sample code is listed below.  The bonded object is not called. And the index.html rendering fails because of the function calling fails.
    On most of the machine the bind object is called correctly. The issue only happens on some of the machine, and the failed machine is on Win7 SP1.
```
            CefSharpSettings.LegacyJavascriptBindingEnabled = true;
            var bindClass  = new ScriptableClass(this);
            BindingOptions options = new BindingOptions();
            this.chromiumBrowser.RequestHandler = new RequestHandler();
            this.chromiumBrowser.MenuHandler = new CustomMenuHandler();
            options.CamelCaseJavascriptNames = false;
            this.chromiumBrowser.RegisterJsObject("external", bindClass, options);
            this.chromiumBrowser.Address = @"file:///./index.html";
```
- **What is the expected output? What do you see instead?**
    - The external should be bounded correctly, and the function should be called.

- **Please provide any additional information below.**
    - The issue only happens on some of the machine. On most of the machine the bind object is called correctly. 
    - The Visual Studio 2015 C++ Run time is installed correctly the machine.
    - Debug log says "[0212/110601.004:ERROR:JavascriptRootObjectWrapper.cpp(34)] IBrowserProcess is null, unable to bind object external"
    - Checked the background process "CefSharp.BrowserSubprocess" is running normally on the machine, and no error for the process in window system event viewer.

**Comment by amaitland** [comment]
Have a read of  #915, check if any other WCF services are running. 

Build your own version and add some logging to https://github.com/cefsharp/CefSharp/blob/cefsharp/67/CefSharp.BrowserSubprocess.Core/WcfEnabledSubProcess.cpp#L46

Seems likely the WCF service failed to connect,  you'll have to confirm that yourself  though. 

As always I recommend using the asynchronous binding,  it's faster and more reliable. 

In future please only open an issue if you've tested with the latest version as per the issue template. The current version is 71.0.0
