### ISSUE TITLE
How to Prevent CEF from accessing system windows resources

### ISSUE THREAD

**Issue by rajihappy123** [cefsharp/CefSharp#2655]
Hi,
I have created wpf windows browser application using CEFSharp 69.0 and chromium version 3.3497.1841.0
It is working fine and able to access websites and popups also enabled.
This CEF Application is working in a secured environment access to system resources need to be blocked.
Please let me know is there any way to block accessing system windows resources from CEF web application.

For example some websites have a print button. On clicking that it will get navigated to system windows printer. 
Need a way to restrict this behavior.

please help me on this.

Thanks in advance

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage
