### ISSUE TITLE
Navigation away from certain site pages failing on Cef WPF

### ISSUE THREAD

**Issue by ThatCanadianGuy** [cefsharp/CefSharp#2656]
- **What version of the product are you using?**
    Release 71.0.0.0, Chromium 71.0.3578.98, CEF r3.3578.1863.gbf8cff2

- **What architecture x86 or x64?**
x64 only. Doesn't occur in x86

- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
    Simply adding an arbitrary button to the nav bar of the minimal example for WPF, setting the configuration to x64 and having this as your mainwindows.xaml.cs:
```
namespace CefSharp.MinimalExample.Wpf
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            WebBrowser.Load("https://www.slack.com");
        }

        private void Butt_Click(object sender, RoutedEventArgs e)
        {
            WebBrowser.Load("https://www.google.com");
        }
    }
}
```
Start the solution, click "Sign in" on the slack page, enter a valid team name (we won't be logging in) then click continue. Once on the login credentials page, attempt to click the arbitrary button added to the nav bar beforehand.

- **What is the expected output? What do you see instead?**
Normally would expect the button to cause a working redirect to the google homepage. As seen using the x86 configuration. Instead, on x64, the page fails to navigate. It does not load, and after a moment displays an empty white page.

- **Please provide any additional information below.**
The debug log output of this test did not, to my eyes, provide any relevant information. Just seems like regular logging and messaging from the slack website. Navigation to the google homepage using the added button works from other pages, including the slack homepage and the page asking for the user to define the team.

**Comment by amaitland** [comment]
Did you test with the CEF Sample application?

**Comment by ThatCanadianGuy** [comment]
I attempted to get the same behaviour out of the "cef_binary_3.3626.1891.g52be333_windows64_client" sample application at http://opensource.spotify.com/cefbuilds/index.html with the "--multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu" parameters but was not able to reproduce. My apologies, I omitted that part of the template.

**Comment by amaitland** [comment]
Please test again with version 3.3578.1863.gbf8cff2.

**Comment by ThatCanadianGuy** [comment]
I tried with that version of cef (cef_binary_3.3578.1863.gbf8cff2_windows64_client) and was able to reproduce the issue. Also confirmed it doesn't occur in the x86 version of that same binary. Looks like an underlying Cef issue and not specific to CefSharp. It also appears to be fixed in later Cef versions so I imagine it will trickle down to CefSharp down the line. I'll close this issue. Thanks for the help.

**Comment by mol** [comment]
@ThatCanadianGuy is this the error you were seeing? Could you point me towards the issue in Cef that appears to have been fixed please?

![Annotation 2019-07-15 125908](https://user-images.githubusercontent.com/317217/61211666-7c5fc300-a700-11e9-82b5-e8302911b0a4.jpg)

**Comment by amaitland** [comment]
@mol Can you confirm the version you are using and provide a list of steps to reproduce the issue?  Possibly network service related.

**Comment by mol** [comment]
@amaitland I tested some more and it definitely seems like an issue in CefSharp. Full details here (as it must then be a different issue to this :)):
https://github.com/cefsharp/CefSharp/issues/2837
