### ISSUE TITLE
ERROR:broker_win.cc(57) Error reading broker pipe: The pipe has been ended. (0x6D)

### ISSUE THREAD

**Issue by sshhzz2003** [cefsharp/CefSharp#2661]
Description:
while using the cefsharp, this error occurred and shown in CEF.log and then the app quit.

Steps to reproduce:
The issue occurred occasionally and I have no idea how to reproduce it .

Debug logs:
[0213/110440.227:ERROR:broker_win.cc(57)] Error reading broker pipe: The pipe has been ended. (0x6D)

CefSharp version: 67.0.0
window version: win10

**Comment by amaitland** [comment]
> Debug logs:
> [0213/110440.227:ERROR:broker_win.cc(57)] Error reading broker pipe: The pipe has been ended. (0x6D)

https://magpcss.org/ceforum/viewtopic.php?f=6&t=15412

Closing as `upstream`, others are porting the same issue with using `CEF` directly. So not a `CefSharp` bug.

> CefSharp version: 67.0.0

The current version is `71.0.0`, you are using an old unsupported version.
