### ISSUE TITLE
Feature Request - Add IBrowserHost.SendTouchEvent

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#2663]
`CEF` has added `MultiTouch` support in https://bitbucket.org/chromiumembedded/cef/commits/5f615a95bc9bd1b1d73fa921d142866038c75c38

This issue will track adding the relevant `method/enum/struct`.

The changes were only merged into `CEF master`, so won't be available until version `75`.

This issue does not track adding a `WPF` implementation, it simply tracks exposing the relevant `CEF API`.

**Comment by TouchRu** [comment]
@amaitland, also in 73.0.0  [](https://bitbucket.org/chromiumembedded/cef/commits/52d535a6dc4b8ec55c3aa7d6b6820e24f12516e8)

**Comment by amaitland** [comment]
@TouchRu Thanks, that commit hadn't been made when I initially checked

**Comment by TouchRu** [comment]
@amaitland , I tried to make changes in my branch, but by mistake I sent it to the main one. Sorry.
https://github.com/cefsharp/CefSharp/pull/2672

**Comment by amaitland** [comment]
Pen support added in https://bitbucket.org/chromiumembedded/cef/commits/7b5d30e9a92bacdcb81c60de19f1712aaf53ff74

A seperate issue will be created to track this as it's only in the master branch currently

**Comment by amaitland** [comment]
`WM_Pointer` example `PR` for `CEF` is https://bitbucket.org/chromiumembedded/cef/pull-requests/214/cefclient-win-pointer-events/diff
