### ISSUE TITLE
Why this javascript code does not work?

### ISSUE THREAD

**Issue by BetaPlays3** [cefsharp/CefSharp#2664]
- I'm using Last version CefSharp 71.0.0.0

- My version Windows: Windows 10 64 bits

WinForms

After execute this code:
                            `frame.ExecuteJavaScriptAsync("document.addEventListener('click', handler, true); function handler(e){e.stopPropagation(); e.preventDefault()}", null);
`

In the Google Chrome browser, it blocks all click events on the page. In the CefSharp browser nothing happens

No error in debug.log, the code works normal in Google Chrome

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
You should read https://github.com/cefsharp/CefSharp/wiki/General-Usage#when-can-i-start-executing-javascript

You have access to DevTools for debugging purposes.

Further questions please use one of the options listed above.
