### ISSUE TITLE
Blank page at different times

### ISSUE THREAD

**Issue by BetaPlays3** [cefsharp/CefSharp#2666]
- **What version of the product are you using?**
    - 71.0.0.0

- **What architecture x86 or x64?**
  - x64

- **On what operating system?**
    - Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
- WinForms

- **What steps will reproduce the problem?**
It happens when I refresh the page after a while with the program running in minimized mode (did not test being in focus)

- **What is the expected output? What do you see instead?**
That the normal page appeared

- **Please provide any additional information below.**
The application does not crash. And when I see the white page's HTML source is empty, with no line of code.

In Debug.log:
```
[0227/163108.581:WARNING:spdy_session.cc(3144)] Received HEADERS for invalid stream 125
[0227/163108.927:INFO:CONSOLE(23)] "A parser-blocking, cross site (i.e. different eTLD+1) script, https://www.google.com/uds/api/visualization/1.1/cc5d8333ad9d2dca8ea31ac15ed4e2df/webfontloader,format+en,default+en,ui+en,corechart+en.I.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.", source: https://www.google.com/jsapi?autoload={%27modules%27:[{%27name%27:%27visualization%27,%27version%27:%271.1%27,%27packages%27:[%27corechart%27]}]} (23)
[0227/163109.437:INFO:CONSOLE(1)] "Active resource loading counts reached a per-frame limit while the tab was in background. Network requests will be delayed until a previous loading finishes, or the tab is brought to the foreground. See https://www.chromestatus.com/feature/5527160148197376 for more details", source: https://www.google.com/recaptcha/api2/anchor?ar=1&k=6LeGfGIUAAAAAEyUovGUehv82L-IdNRusaYFEm5b&co=aHR0cHM6Ly9mcmVlYml0Y28uaW46NDQz&hl=en&v=v1550471573786&size=normal&cb=pcmdr6o0c49x (1)
```

   - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
No.

**Comment by amaitland** [comment]
Did you test with the CEF Sample application? Make sure you test with the exact same version. Based on the log message it seems unlikely this is a bug in CefSharp,  it's just a wrapper remember. 

It's not clear how to reproduce this.  Have you tried on a different computer?

**Comment by BetaPlays3** [comment]
I tested with my application. And it's in version 71.0.0.0. Before giving reload, I remove the proxy and then put another proxy or the same, and it happens every hour in a loop. I do not know if the problem is in the proxy that got no response from the site, because I remove it before the reload site

My code:

```
        private void InitializeBrowser()
        {
            CefSettings settings = new CefSettings();
            string path = Environment.CurrentDirectory + "\cache"
            settings.CachePath = path;
            Cef.Initialize(settings);

            browser = new ChromiumWebBrowser("URL");
            var rcs = new RequestContextSettings();
            rcs.CachePath = path;
            var rc = new RequestContext(rcs);
            browser.RequestContext = rc;

            browser.Dock = DockStyle.Fill;
            Controls.Add(browser);
        }
```

```
 public async void run()
        {

            await Cef.UIThreadTaskFactory.StartNew(delegate
            {
                var rc = browser.GetBrowser().GetHost().RequestContext;
                var v = new Dictionary<string, object>();
                v["mode"] = "direct";
                v["server"] = "";
                string error;
                bool success = rc.SetPreference("proxy", v, out error);
            });

            browser.Reload();

            var taskcheckdocument = frame.EvaluateScriptAsync("(function(){return (document.readyState === 'ready' || document.readyState === 'complete')})();", null);
            await taskcheckdocument.ContinueWith(async check =>
            {
                if (check.Result != null && check.Result.Result != null && check.Result.Result.ToString().Equals("True"))
                {
                    await Cef.UIThreadTaskFactory.StartNew(delegate
                    {
                        var rc = this.browser.GetBrowser().GetHost().RequestContext;
                        var v = new Dictionary<string, object>();
                        v["mode"] = "fixed_servers";
                        v["server"] = proxy;
                        string error;
                        bool success = rc.SetPreference("proxy", v, out error);
                    });
                    //execute my code
                }
            }, TaskScheduler.FromCurrentSynchronizationContext());
        }
```


I remove the proxy because I think the problem is in it, but it still gives white screen

**Comment by amaitland** [comment]
Did you read https://www.chromestatus.com/feature/5527160148197376 as per your log? Seems likely your page has been throttled. This is a relatively new feature,  CEF may not fully support it in all cases. Performing tasks on minimized browsers probably isn't well tested and performing certain actions may not be supported. 

You should repeat your tests with the browser in an active/visible state. Also test with a simpler website,  say google or something equally as basic. 

I don't believe this is a bug in CefSharp, you can test with a newer build of CEF to see if it behaves differently. See https://github.com/cefsharp/CefSharp#releases-1

CEF has it's own support forum at https://magpcss.org/ceforum/index.php

I'll leave this open for now,  there really isn't anything more I can add from a CefSharp point of view.

**Comment by BetaPlays3** [comment]
The page is very simple, does not contain anything too much. Throttled would not be caused by lack of memory etc ...? Because it has to spare even with several applications. So the solutions would be to try a new cefsharp build or put the application in focus?

**Comment by amaitland** [comment]
> Because it has to spare even with several applications

No idea what you mean here. Having the application `minimised` will be the same as running a `background tab`. Read over https://www.chromestatus.com/feature/5527160148197376 again.

> So the solutions would be to try a new cefsharp build or put the application in focus?

Test with the application running in the foreground first. Then see if a newer version fixes it. The `Background Tab Resource Load Throttling` was only enabled by default in version `69`, so testing with version `67` is probably worthwhile also if it still reproduces with the first two.

You can use the `MinimalExample` for testing purposes, there are branches for older version, see https://github.com/cefsharp/CefSharp.MinimalExample/branches/all?utf8=%E2%9C%93&query=cefsharp
