### ISSUE TITLE
WinForms - Call to Load/LoadHtml has no effect when called in the IsBrowserInitializedChanged event handler

### ISSUE THREAD

**Issue by EvilCoincoin** [cefsharp/CefSharp#2668]
- **What version of the product are you using?**
nuget 71.0.0 with redist 3.3578.1863

- **What architecture x86 or x64?**
x64

- **On what operating system?**
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms

- **What steps will reproduce the problem?**
Any call to 'Load()' or 'LoadHtml()' while 'IsBrowserInitializedChanged' is being handled has no effect.

- **Minimal code to reproduce**
https://gist.github.com/EvilCoincoin/0ef953d4e5e3b83eb64b101b17e02a7e

- **What is the expected output? What do you see instead?**
The requested URL/HTML should be displayed, instead, it is still loading the URL that was provided before 'IsBrowserInitializedChanged' was raised.
A Load() before 'IsBrowserInitializedChanged' works. A 'Load()' after 'IsBrowserInitializedChanged' also works.
Please note this was working in 69.0.0. It's easy to work around once you know the problem.

- **Please provide any additional information below.**
The log is empty. No exception.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
N/A. It's an embed issue.

**Comment by amaitland** [comment]
> * Please note this was working in 69.0.0. It's easy to work around once you know the problem.

The behaviour was changed inhttps://github.com/cefsharp/CefSharp/commit/821a44fecc9aa1e103027323defea7b1d4c0bf82#diff-f81cf6df3af1093f674f5729017b960e

Now the initial `url` is passed to the `CefBrowserHost::CreateBrowser` method where previously an empty string was passed. If you pass in an empty string instead of `about:blank` you should get exactly the same behaviour as before from a `CefSharp` point of view. Any other change in behaviour is a change in how `CEF/Chromium` operates and is outside of my control.

**Comment by amaitland** [comment]
Improvements to the documentation and examples are certainly welcome. Anyone with a `GitHub` account can edit the `Wiki` and `Pull Requests` with improvements to the `xml doc` would certainly be welcome.

**Comment by amaitland** [comment]
I've added a new constructor to the `WinForms` implementation that takes a new `CefSharp.Web.HtmlString` class, simplify passing a html string directly to the browser (performs the data Uri encoding), `LoadHtml(string)` now uses `HtmlString` internally and some code duplication was removed internally.

An example should look like (using the implicit conversion)
```c#
new ChromiumWebBrowser((CefSharp.Web.HtmlString)"<html><body style='background:red;'>Data Uri Test</body></html>");
```

This should simplify loading a html string directly and eliminate the need to call `LoadHtml` in `IsBrowserInitializedChanged`. Will be available in version `75`

**Comment by adellieux** [comment]
Some feedback about this new feature:
- i load an html document with js scripts activated, but scripts refuse to be executed
- accented characters are not displayed correctly.
when i load using LoadString they display correctly
- remote debugging sometimes does not work (Chrome display an error message about the server being inaccessible)
but ShowDevTools was working
i have got this problem once
the second launch, remote debugging was working
@amaitland , i have some screenshots if you want
could this be related to security parameters ?

**Comment by amaitland** [comment]
It is not a new feature,  it's a simple convenience to convert a string into a Data Uri, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs if you are unfamiliar. 

Any limitations and/or restrictions are inherited from CEF/Chromium and are outside of our control. Remote debugging not working is likely a bug in CEF,  you should discuss the problem on https://magpcss.org/ceforum/index.php
