### ISSUE TITLE
WPF - CefSharp.BrowserSubprocess not closing when browser Disposed

### ISSUE THREAD

**Issue by mtinnes** [cefsharp/CefSharp#2673]
- **What version of the product are you using?**
72

- **What architecture x86 or x64?**
x64

- **On what operating system?**
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
Our application requires continuous creating and releasing of CefSharp.Wpf.ChromiumWebBrowser. To do this we have a custom control using a template XAML form containing ChromiumWebBrowser. Our app instantiates the custom control and releases/disposes it in roughly 10 second intervals.

- **What is the expected output? What do you see instead?**
Expected to consume memory for only the currently instantiated browser. Instead, we see continuous growth of the number of BrowserSubprocess processes which results in a low or even out of memory condition.

- **Please provide any additional information below.**
No stack trace since the issue does not necessary crash until OOM.

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
No out of the ordinary log activity.

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
No

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
Does not have the same type of cyclic functionality.

**Comment by amaitland** [comment]
> * **What version of the product are you using?**
>   72

The current supported version is `71`, are you using a development build? If so for what reason?

> * Our app instantiates the custom control and releases/disposes it in roughly 10 second intervals.

How does it behave it you dispose of the control after a longer period of time, say `30 seconds`?

**Comment by mtinnes** [comment]
Thanks for the quick reply Alex.

We are using the current master branch. We build the project locally due to some minor code tweaks we are making to the JavaObjectRepository.

Tried bumping the cycle to 30 seconds and same result. We get a new subprocess every 30 seconds. We are disposing the browser manually in the control dispose method.

**Comment by mtinnes** [comment]
I've noticed the WPF example has the same issue when adding/closing tabs. The subprocess remains after tab close. I've just build the 71 branch and the WPF example seems to work as expected.

**Comment by amaitland** [comment]
> I've noticed the WPF example has the same issue when adding/closing tabs. The subprocess remains after tab close. I've just build the 71 branch and the WPF example seems to work as expected.

Thanks for testing. `master` is just for `development/testing`, if you can  it would be best to use the `cefsharp/71` release branch.

You can compare `master` to `cefsharp/71`, a quick glance and I don't see anything that stands out. Obviously it's using a different version of `CEF`.

https://github.com/cefsharp/CefSharp/compare/cefsharp/71...master

Added this to the `73` milestone, will come back and test when `master` has been updated to `3683`, could be a `CEF` problem.

**Comment by amaitland** [comment]
Merging https://github.com/cefsharp/CefSharp/commit/13970fe55c0691d564ab3b9d20a6acdf7edec42b and https://github.com/cefsharp/CefSharp/commit/111439c98e5a0fa88ac80959a3cf757273b29781 into `cefsharp/71` branch and everything works as expected. So it looks like a change specific to `CefSharp` and not a `CEF/Chromium` change that's broken things.

**Comment by amaitland** [comment]
Resolved by #2651
