### ISSUE TITLE
Click on div with Javascript not open the FileDialog

### ISSUE THREAD

**Issue by Yosifz8** [cefsharp/CefSharp#2679]
Environment
CefSharp Version 67.0.0
WinForms
Framework 4.5.2

Description
I am developing an application that make some Javascript methods on a website. One of the things i do is to make a click on div - that popup a file dialog and i choose the file on `FileDialogHandler`.

This is how init the browser:

```
ChromiumWebBrowser browser = new ChromiumWebBrowser(url);
var requestContextSettings = new RequestContextSettings { CachePath = UsersManager.GetFullCachePath(userName) };
browser.RequestContext = new RequestContext(requestContextSettings, new CustomRequestContextHandler());

Dictionary<String, String> settings = UsersManager.GetUserSettings(userName);
if (settings != null && settings["proxy"].Equals("true"))
            browser.RequestHandler = new ProxyRequestHandler(settings["proxy_user"], settings["proxy_password"]);

browser.DialogHandler = new FileDialogHandler();

browser.Dock = DockStyle.Fill;
browser.FrameLoadEnd += webViewFrameLoadEnd;
browser.LoadError += getFromBrowser_LoadError;

browser.JsDialogHandler = new JsDialogHandler();
BrowserPanel.Controls.Add(browser);
```

This is the JavaScript code that click the div:
```
String js = @"var script = document.createElement('script');
             script.type = 'text/javascript';
            script.text = function StartNewUpload() { 
                        var aTags = document.getElementsByClassName('class')[0];
                        aTags.click();
                        return '1';
            };
            document.getElementsByTagName('head')[0].appendChild(script);";
wv.ExecuteScriptAsync(js);

wv.EvaluateScriptAsync("StartNewUpload();").ContinueWith(x =>
{
            var response = x.Result;
});
```

This is the `FileDialogHandler` class:
```
class FileDialogHandler : IDialogHandler
{
        public bool OnFileDialog(IWebBrowser chromiumWebBrowser, IBrowser browser, CefFileDialogMode mode, CefFileDialogFlags flags, string title, string defaultFilePath, List<string> acceptFilters, int selectedAcceptFilter, IFileDialogCallback callback)
        {
                List<String> i = new List<string>();
                i.Add(myfilepath);

                callback.Continue(0, i);
                return true;
        }
}
```

I'm getting `1` from the JavaScript methods so it's working fine, The `FileDialogHandler` also working because when i click the div by my self it's select the file as needed.

I call the JavaScript method 10 seconds after the page loads, so this is not the problem.

This code was copied from another application that was built for Mac OSX application, There it's working perfect.

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
You can only open a `File Dialog` as the direct result of a user interaction, you cannot open it through javascript alone. See https://stackoverflow.com/a/51689034/4583726

**Comment by Yosifz8** [comment]
Is this a CefSharp issue?

**Comment by amaitland** [comment]
No

**Comment by amaitland** [comment]
https://mariusschulz.com/blog/programmatically-opening-a-file-dialog-with-javascript
