### ISSUE TITLE
warning MSB3061 and MSB3026 when rebuilding solution with cefsharp nuget package

### ISSUE THREAD

**Issue by mkblr** [cefsharp/CefSharp#2680]
- **What version of the product are you using?**
    - 71.0.1

- **What architecture x86 or x64?**
    - x64

- **On what operating system?**
    - Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - WPF

- **What steps will reproduce the problem?**
    - Solution with multiple projects (in my test case more than 20). One project adds and use CefSharp nuget package. The other projects add this project as reference.
    - Rebuild the solution

- **What is the expected output? What do you see instead?**
    - Expected: Clean rebuild without warnings or errors
    - `warning MSB3061: Unable to delete file "...\build\x64\Debug\locales\gu.pak". Access to the path '...\build\x64\Debug\locales\gu.pak' is denied.` (with different cefsharp files) 
    - `warning MSB3026: Could not copy "...\packages\cef.redist.x64.3.3578.1863\CEF\locales\nl.pak" to "..\build\x64\Debug\\locales\nl.pak". Beginning retry 1 in 1000ms. The process cannot access the file '..\build\x64\Debug\\locales\nl.pak' because it is being used by another process.` (with different cefsharp files) 
    - Sometimes also the error: `error MSB3030: Could not copy the file "...\build\x64\Debug\CefSharp.Wpf.dll" because it was not found.` appears (with different cefsharp files) 

- **Please provide any additional information below.**
    - Sometimes the problem only appears when rebuilding the solution a few times
    - After removing the build folder and rebuild the solution the problem doesn't appears
    - When maximum number of parallel projects builds (Visual Studio: Options>Projects and Solutions> Build and Run) is set to "1" the problem doesn't appears
    - The problem appears since version 62.0.0

**Comment by amaitland** [comment]
What version of `Visual Studio` are you running? What version of `Nuget`?

> * `warning MSB3026: Could not copy "...\packages\cef.redist.x64.3.3578.1863\CEF\locales\nl.pak" to "..\build\x64\Debug\\locales\nl.pak". Beginning retry 1 in 1000ms. The process cannot access the file '..\build\x64\Debug\\locales\nl.pak' because it is being used by another process.` (with different cefsharp files)

What program/process has the file open? You can use https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer to see what's in use.

> * Sometimes also the error: `error MSB3030: Could not copy the file "...\build\x64\Debug\CefSharp.Wpf.dll" because it was not found.` appears (with different cefsharp files)

Not something I've seen before and without a list of steps reproduce there's no way to look into it.

> **What steps will reproduce the problem?**
> 
> * Solution with multiple projects (in my test case more than 20). One project adds and use CefSharp nuget package. The other projects add this project as reference.
> * Rebuild the solution

Unfortunately I get way too many issues that describe the problem, it's just not practical for me to try and reproduce the problem myself.

The `Nuget` files are in https://github.com/cefsharp/CefSharp/tree/master/NuGet

Suggestions/pull requests welcome.

> * When maximum number of parallel projects builds (Visual Studio: Options>Projects and Solutions> Build and Run) is set to "1" the problem doesn't appears

At least you have a workaround 👍 This also hints that `MSBuild` probably isn't behaving as it should.

**Comment by mkblr** [comment]
I'm using Visual Studio Enterprise 2017 with NuGet Package Manager version 4.6.0.
As I could see just "MSBuild.exe" has the file open.
The problem appears since CefSharp is using a .props file instead of an .targets file.

**Comment by amaitland** [comment]
> As I could see just "MSBuild.exe" has the file open.

Sounds like a problem with `VS` then.

> The problem appears since CefSharp is using a .props file instead of an .targets file.

What are you basing this statement on? Please provide a link.

**Comment by amaitland** [comment]
> Im using Visual Studio Enterprise 2017 with NuGet Package Manager version 4.6.0.

This version is quite out of date, `4.9.3` is the version I'm using

Do you have any `xcopy` or custom `<ItemGroups/>` for copying `CefSharp` files?

**Comment by amaitland** [comment]
Marking this `unable-to-reproduce` as yet no example that reproduces the problem has been provided.

**Comment by mkblr** [comment]
I have created a test solution where these warnings and the error appears, 
when I rebuild the solution at least two times in a row.
In this solution a have no `xcopy` or custom `<ItemCroups/>`.
[CefSharpTest.zip](https://github.com/cefsharp/CefSharp/files/2951683/CefSharpTest.zip)

**Comment by amaitland** [comment]
Thanks, can you please push it to GitHub or similar, no zip files please.

Have you tried upgrading to a newer version of visual studio?

**Comment by mkblr** [comment]
https://github.com/mkblr/CefSharpTestSolution

I have the newest version of visual studio 2017.

**Comment by amaitland** [comment]
> https://github.com/mkblr/CefSharpTestSolution

Thanks 👍 I never would have been able to recreate this as there are pieces missing from your original bug report.

- Parallel project builds enabled
- All projects share a common output folder (this part is key)
- Multiple projects that reference `CefSharp` directly or indirectly (doubt it makes a difference)

> I have the newest version of visual studio 2017.

Please confirm the **exact version** you are using.

Using `VS 2017 Community 15.9.8` I have yet to see `MSB3061/MSB3026`. Using the default `4` maximum number of parallel project builds. Having a faster machine may make the issue more reproducible, I'm using a very old `Surface Pro 1st generation`. I ran `Rebuild Solution` 6 times in a row without seeing either of those errors

In theory I understand why the error could be happening, having parallel `MSBuild` instances copying files simultaneously could easily be a problem.

> error MSB3030: Could not copy the file "...\build\x64\Debug\CefSharp.Wpf.dll" because it was not found

I did see a single `MSB3030` error, I really don't have a way to debug this any further, possibly you'll need to contact someone at `Microsoft`.


Please confirm you can reproduce the issue with `VS 2017 15.9.8` or newer.

**Comment by mkblr** [comment]
Yes, I'm also using VS 2017 15.9.8.
It seems like I have to find another solution for this problem.
Thanks a lot for your efforts.

**Comment by amaitland** [comment]
> Yes, I'm also using VS 2017 15.9.8.

Thanks 👍 Maybe having faster hardware exacerbates the problem.

As a possible solution, the `<None/>` entries have `CopyToOutputDirectory` specified, which will copy to the project output directory and that of projects directly referencing the project that contains the `<None/>` entries. We could make this configurable with `PreserveNewest` being the default and you could override this with `Never`, you would then have to copy the files manually. In theory this should solve the problem.

https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items?view=vs-2017#none

Additionally you should be able to change the structure of your projects to workaround this, the `<None/>` entries will only copy the project directly referencing the project that contains the `CefSharp` Nuget packages. If you add another layer inbetween, for the sake of your example add a `ClassLibrary` that has the `Nuget` packages installed, then add that as a reference to the `CefSharpTest` it should only copy a single time. Not sure how viable this is for your actual project structure.

**Comment by amaitland** [comment]
With commit https://github.com/cefsharp/CefSharp/commit/27c53ea5136c30ce03dfa032c6fd4ad67fbb018b I've added the `MSBuild` property `CefSharpBuildAction` which can you set to `NoAction` for projects you don't want copying file to automatically.

Add the following to a `PropertyGroup` in your `proj` file before the `.targets` entries (which are at the bottom).
```xml
<CefSharpBuildAction>NoAction</CefSharpBuildAction>
```

This change will be in version `87`. You can set this in every project except one and this should workaround the issue (if it still exists). This is the best I think we can do from a `CefSharp` point of view as it's actually `MSBuild` that does the copying.

**Comment by d-dantte** [comment]
I encountered something similar to problem recently - but without the CefSharp nuget. In my case, simply setting "parallel builds" to 1 solved the problem. I believe building in parallel messes with the project dependencies.
