### ISSUE TITLE
Freeze/Hang on Shutdown when using PKI login with certificates stored on a smart card

### ISSUE THREAD

**Issue by darbid** [cefsharp/CefSharp#2692]
- **What version of the product are you using?**
  CefSharp 71.0.2

- **What architecture x86 or x64?**
x64 (Only)

- **On what operating system?**
    - Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
- WinForms

- **What steps will reproduce the problem?**
    
1. run winforms version of the CefSharp.Minimal.Example 
2. navigate to a website that requires PKI login with certificates stored on a smart card
3. successfully login
4. close the application by pressing the Minimal.Example's X 
5. Main application does not close down.

- **What is the expected output? What do you see instead?**
The main application process ends.

- **Please provide any additional information below.**
  
- 32 bit works, this is only a 64 bit issue
- have tested the exact same steps as above with cef_binary_3.3683.1920.g9f41a27_windows64_client and the main process closes down
- The browsersubprocesses close down, only the main application process is left hanging

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
I dont see anything of interest in the log.

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
This is being done on freshly downloaded version of CEF and CEFSharp no tweaks..

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?** 
No it does not. It has been tested.

    - To compare with WinForms run cefclient --multi-threaded-message-loop
 I am surprised about this but running cefclient does not produce the same issue.

**Comment by amaitland** [comment]
> * have tested the exact same steps as above with cef_binary_3.3683.1920.g9f41a27_windows64_client and the main process closes down

Please test with `3.3578.1870.gc974488 / Chromium 71.0.3578.98`. You are comparing different versions.

**Comment by amaitland** [comment]
If the `x86` version works then this is unlikely a `CefSharp` issue. Marking this as `upstream` as that seems likely.

**Comment by darbid** [comment]
Downloaded and ran 3.3578.1870.gc974488 with --multi-threaded-message-loop and I can not reproduce the issue.

Doing the steps above Cefsharp will not close every time.

**Comment by darbid** [comment]
so that makes it an interesting situation. I have an issue with the CEFSharp application not closing down. But it is apparently not an issue with CefSharp, However it is not producible upstream.

**Comment by darbid** [comment]
No idea what I am doing but I possibly have worked out how to work a memory profiler.

Here are few dump comparisons from before logging in to after the application window is closed.


![cef1](https://user-images.githubusercontent.com/3191525/54475004-6abaed00-47ec-11e9-9607-0ee25ca1b9e4.PNG)
![cef2](https://user-images.githubusercontent.com/3191525/54475005-6abaed00-47ec-11e9-8abd-2871830078b5.PNG)
![cef3](https://user-images.githubusercontent.com/3191525/54475006-6abaed00-47ec-11e9-855a-fe6fb7bd661f.PNG)
![cef4](https://user-images.githubusercontent.com/3191525/54475007-6b538380-47ec-11e9-953f-2381bbf80edc.PNG)
![cef5](https://user-images.githubusercontent.com/3191525/54475008-6b538380-47ec-11e9-852d-86a274c4a1fb.PNG)

**Comment by amaitland** [comment]
By all means submit a PR for any memory leaks you find.

I don't have a smart card reader so this is not something I can debug. 

As it only happens for x64 it doesn't seem likely the memory leaks would have an impact,  they should be the same in both.

You'll have to debug this yourself.

**Comment by darbid** [comment]
I have been doing some very general tests and found (in my opinion a FANTASTIC feature) of CefSharp that CEF Client and Google Chrome does not have.  To log into a secure website you need;

1. Smart card inserted
2. Initiate the login
3. A dialog appears where you enter your password for the private key of a certificate stored on the smart card.
4. you get logged on.

The great thing about CefSharp is that I only have to do steps 1-4 once.  

For Cef Client and Google Chrome if I close the application and then restart then I will be required to do steps 1-4 again.

With CEFSharp I don't even need the smart card inserted.  I simply restart the app, point it to the website and I am automatically logged in.  I can even log out of the webapp, and if I simply point CefSharp back to the website it will automatically log me back in.

Of course there would be some IT people who would call this a major security issue. I love it.  But I suspect it has something to do with the issue. Unfortunately this "feature" happens with WPF/WinForms and on 32/64 bit versions.

Can you point me to something or anything you can think of that is caching, or holding onto such information.

**Comment by darbid** [comment]
CEF Testing = is with 3.3578.1870.gc974488
CEFSharp testing = is with current code master Winforms example. (Ive removed the cookie code in the process handler so that the login is required each time now.)

The reason I am still writing here is that I cannot get this to error in CEF.  

I have narrowed down the event visually that causes the problem. It is when this dialog (windows controlled) appears. You enter a password which is to your private key which is stored in a certificate on a smart card attached to your PC.
<img width="352" alt="pkiwindow" src="https://user-images.githubusercontent.com/3191525/54545087-3ccad980-49a1-11e9-8fce-4e0093983e74.PNG">

When the above dialog appears and a password is entered on my PC a 3rd party program writes a log file with nothing in the log file of importance . This is a unique thing to my PC. This log file is only written for x64 bit browsers, thus the log file is written when I log in with Google Chrome, with Cef Client and with CefSharp. 

This 3rd party program uses NSpring.dll for logging. When the dialog appears the dll is loaded and a thread is spun up within the browsers' process. When CefClient and Google close down so too does this thread, but using CefSharp the thread remains alive.  It is this thread which prevents the close down.

The introduction of the words 3rd Party means that I have to track down who owns it, however I am still stuck with the situation that the problem only exists in combination with CefSharp. 

At this stage are far as I am concerned CefSharp is performing differently to Cef Client and thus the problem exists, there must be something CefSharp sets or does not set causing the difference.

Any ideas?

**Comment by darbid** [comment]
One small difference which, I don't understand and cannot reliably say what happens is with respect to thread handling and processes. Using VS I am attaching to CefClient's processes.

CEFClient's main process has many threads alive at login time (when the above dialog is showing) with smartcard named threads (in my opinion looks good) but does not have the above NSpring.dll. CefSharp on the other hand has the NSpring.dll thread in its main process but none of the other threads.

After the dialog is removed CefClient then has the NSpring.dll thread in its main process.

**Comment by amaitland** [comment]
Thanks for the updates, removing the `upstream` label.

Might be worth testing with `CefGlue` or `ChomiumFx` to see if the problem is specific to `CefSharp` or is a problem with loading whatever dlls into a `.Net Application`.

Best of luck.

**Comment by darbid** [comment]
You can not only remove the upstream but you can close this completely.

The problem is with the Smart Card driver software for the smart card reader from Atos Card OS. It does not shut down its threads properly. If you are having similar issues with a smart card reader then my band-aid (I would not call it a solution or even a workaround) is to call Environment.Exit(exitCode) in the Application.Exit event.

For anyone reading above and needing more info on my conclusions;

- It appears the smart card software has a x64 only problem which is the reason it is seen in a x64 web browser application.
- It appears that Cef Client and Chrome also have to put up with this as well when they are run as x64 bit applications however I was unable to profile these applications and for example Google Chrome does not like Visual Studio attaching to its process, but then seems to work. The issues with attaching to the process were the reason why I thought that I could not reproduce this with them as I could with CefSharp.
- There is still one difference and that is that Cef Client and Google seem to more forcibly shut down. I am not sure if this is because a C written program is not effected by .Net or whether for other reasons they force a shutdown.  See above I now call Environment.Exit(exitCode).
