### ISSUE TITLE
Application hung on touch operation

### ISSUE THREAD

**Issue by mortalV** [cefsharp/CefSharp#2698]
- **What version of the product are you using?**
    - just clone minimal example from git so v71.0.2

- **What architecture x86 or x64?**
    - x64
- **On what operating system?**
    - Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**

    - WinForms

- **What steps will reproduce the problem?**
    - You need multitouch device
    - Open url https://threejs.org/examples/#misc_controls_orbit
    - With two hands make zoom very-very-very quickly sometimes get of hands from screen and immediately put hands on screen. I think main goal is very fast produce touch end and touch start-move. 

- **What is the expected output? What do you see instead?**

    - Expected - all must works.
    - In fact - CefSharp process start constantly consume CPU around 25-33% and all freezes. In the same time CefSharp.BrowserSubprocess.exe have no CPU consume

- **Please provide any additional information below.**
    - No exception. Even if pause in debug  you can see in Task Manager that main process continue consume CPU. 

    - Debug log have no errors. 

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

     - Sorry but I can't download CEF Sample Application - Access denied.

**Comment by amaitland** [comment]
> **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
> 
> * Sorry but I can't download CEF Sample Application - Access denied.

Are you able to download from another network?

The `WinForms` touch support is implemented entirely in `Chromium/CEF`, so testing with the `CEF Sample` application is a vital debugging step in this instance.  Testing with `cefclient` is this instance is a must.

**Comment by mortalV** [comment]
I just repeat the same behaviour on usual Chrome. 
I have found https://bugs.chromium.org/p/chromium/issues/detail?id=931369&can=2&q=931369
Workaround for this problem is --disable-features=PointerEventsForTouch
I have test and now all is OK.
So sorry for wrong report but for another users I think this workaround will be usefull.
Thanks.

**Comment by amaitland** [comment]
Thanks for posting a workaround. Have tagged this as `known-issue`
