### ISSUE TITLE
Remove WebBrowserExtensions.LoadUrlWithPostData

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#2705]
The underlying `LoadRequest` method has become unreliable. It no longer sends `Cookie` with requests. You can also only call it after the browser has successfully loaded a `Url`.

> LoadRequest bypasses the normal navigation pipeline

https://magpcss.org/ceforum/viewtopic.php?f=6&t=16592&p=41067#p41074

As a result we'll remove `WebBrowserExtensions.LoadUrlWithPostData`

- [x] Mark `WebBrowserExtensions.LoadUrlWithPostData` as `Obsolete`
- [ ] Remove `WebBrowserExtensions.LoadUrlWithPostData`
- [ ] Add additional xml doc to `LoadRequest` making it clear it's not reliable.

**Comment by amaitland** [comment]
The only reliable method is to use `OnBeforeResourceLoad`, you can append `Post Data` through this method.

**Comment by amaitland** [comment]
It maybe possible to still send cookies see https://magpcss.org/ceforum/viewtopic.php?f=6&t=16650#p41343

**Comment by amaitland** [comment]
>  If set user name, password, and cookies may be sent with the request, and cookies may be saved from the response.

Setting `UrlRequestFlags.AllowCachedCredentials` is reported to send cookies, which makes sense based on the flag comment.

Changes made to `master` and `cefsharp/73` branch. If this provides to be successful then we'll remove the `Obsolete` attribute and keep the method.

**Comment by 1448376744** [comment]
Cookie

**Comment by amaitland** [comment]
Will defer this change until we see the impact of the new `Network Service` (#2743)

**Comment by amaitland** [comment]
No further reports of problems,  will leave the code as is for now.

**Comment by ajcoll5** [comment]
> 
> 
> No further reports of problems, will leave the code as is for now.

The method is still marked as obsolete with a message stating it will be removed in version 75. Since this issue is closed and the method is being kept, should this message be removed?

**Comment by amaitland** [comment]
You are welcome to submit a pull request.
