### ISSUE TITLE
Speech recognition does not work in cefsharp. 

### ISSUE THREAD

**Issue by ervishal89** [cefsharp/CefSharp#2707]
Hi, 

Google speech recognition does not seems to be working with cefsharp. 

I use this URL for address and it just does not work. 
https://www.google.com/intl/en/chrome/demos/speech.html

Any advise would be appreciated.

**Comment by amaitland** [comment]
https://magpcss.org/ceforum/viewtopic.php?f=6&t=15623&p=36791
