### ISSUE TITLE
Feature Request - Add boolean property for enabling Proprietary Codecs

### ISSUE THREAD

**Issue by Red-Rover** [cefsharp/CefSharp#2709]
Compile the core CEF libraries with proprietary codecs but have them disabled by default.  The developer would be required to enable this feature and assume rights for obtaining necessary licenses.  A simple Boolean property or function call to enable.

This is similar to what Essential Objects is doing with their paid version of their Chromium wrapper.

**I can contribute today to get this feature implemented.**

The problem with manually compiling the build yourself is the amount of time it takes, occasional failures, operating system requirements, hardware requirements, etc...  And when a new version of CEFSharp is available, another 1/2 day of recompiling is required.

**Comment by amaitland** [comment]
I get the requirement, the reality is not that clear cut. Without consulting a lawyer it's not clear simply saying you assume all responsibility would make it legal for me to distribute software that contains patented tech. It probably differs greatly depending on where an individual is based, if I was in Europe then it might be different.

There is then the task of patching Chromium, then maintaining those patches. 

Then there's the paid build infrastructure that would have recurring costs. All builds currently are sourced from http://opensource.spotify.com/cefbuilds/index.html

Providing a build with proprietary codecs enabled would probably have to be offered as a paid offering. 

From an open source project point of view it makes more sense to contribute time and effort to https://github.com/mitchcapper/CefSharpDockerfiles

**Comment by amaitland** [comment]
Alternative if your country/region allows you can offer a paid version that includes your proposed changes, the cost could then offset your time and effort. If you go down this path I'm happy to include a link to your builds/payment page from the main project page.

**Comment by Red-Rover** [comment]
Completely understand.  Thank you for the quick replies!
