### ISSUE TITLE
C# How Fix in Supported CefSharp WinForms Debug

### ISSUE THREAD

**Issue by MohamedOsama239** [cefsharp/CefSharp#2711]
> ## `C# How Fix in Supported CefSharp WinForms `

> # CefSharp Browser Version 71.0.2
> ## Chromium Browser Version 71.0.3578.98`

# Debug.Log How Fix CefSharp WinForms
## I How use CefSharp WinForms in Supported Chrome Extensions APIs

> # How Fix
> 1 - Lost UI shared context
 2 - Could not get the download directory
3 - 08A28600: set chrome proxy config service to 0BC46A60
4 - Error in dxva_video_decode_accelerator_win.cc on line 511
5 -  WARNING: Unsupported cookie scheme: chrome

[How Fix CefSharp WinForms Debug.Log.txt](https://github.com/cefsharp/CefSharp/files/3023527/How.Fix.CefSharp.WinForms.Debug.Log.txt)

**Comment by amaitland** [comment]
Please stop opening issues.
