### ISSUE TITLE
Fullscreen in window

### ISSUE THREAD

**Issue by WatermelonPL** [cefsharp/CefSharp#2712]
x86, WinForms, Win 10
Steps to reproduce:
Open video on Youtube, and click fullscreen.
Youtube should go fullscreen in window, not on entire screen.
Source code: https://www.mediafire.com/file/6hpn8sypom1tkjx/Internet_Exploder.rar/file

**Comment by amaitland** [comment]
See https://stackoverflow.com/questions/36264609/cefsharp-flash-player-fullscreen?rq=1
