### ISSUE TITLE
Flash render (animation) very slowly

### ISSUE THREAD

**Issue by Mr-MaCaLLaN** [cefsharp/CefSharp#2717]
Hi,  I try to open flash game in Cef Browser (wpf project), but flash animation very slowly. In Chrome Browser this game work very well. Please help me with settings.

**Comment by Mr-MaCaLLaN** [comment]
CefSettings s = new CefSettings();
 s.CachePath = "cashe";
 s.DisableGpuAcceleration();
 s.SetOffScreenRenderingBestPerformanceArgs();
 s.WindowlessRenderingEnabled = true;  
 Cef.EnableHighDPISupport();
Cef.Initialize(s);

Not work!!

**Comment by amaitland** [comment]
If you need performance then you'll need to use the `WinForms` version hosted in `WPF`.
