### ISSUE TITLE
Page never loads.

### ISSUE THREAD

**Issue by gogolon** [cefsharp/CefSharp#2719]
In the following code:
`           
            
            ChromiumWebBrowser[] chromium = new ChromiumWebBrowser[offersLinks.Count()];                     
            for(int i = 0; i < offersLinks.Count(); ++i)
            {
                Debug.WriteLine("Page " + (i + 1) + "/" + offersLinks.Count());
                chromium[i] = new ChromiumWebBrowser(offersLinks[i]);
                chromium[i].FrameLoadEnd += async (sender, args) =>
                {
                    //Wait for the MainFrame to finish loading
                    if (args.Frame.IsMain)
                    {
                        Debug.WriteLine("Loaded.");
                        if (chromium[i].CanExecuteJavascriptInMainFrame)
                        {
                            JavascriptResponse response = await chromium[i].EvaluateScriptAsync(javascript);

                            if (response.Result != null)
                            {
                                Debug.WriteLine(response.Message);
                            }
                        }

                        chromium[i].ViewSource();
                        string html = await chromium[i].GetSourceAsync();
                    }
                };
            }
`

The FrameLoadEnd event is never triggered. This is probably an issue.

**Comment by amaitland** [comment]
Asked at https://stackoverflow.com/questions/55592848/cefsharp-chromium-page-loading-never-completes
