### ISSUE TITLE
I can't see DownloadHandler in CefSharp

### ISSUE THREAD

**Issue by ByErdem** [cefsharp/CefSharp#2724]
### Bug Report
- ** What version of the product are you using?
v71.0.2 via NuGet
https://www.nuget.org/packages/CefSharp.WinForms/

- ** What architecture x86 or x64?
x64

- ** On what operating system?
Windows 10

- ** Are you using WinForms, WPF or OffScreen?
WinForms

- ** What steps will reproduce the problem?
I can't see the DownloadHandler property in ChromiumWebBrowser.

- ** What is the expected output? What do you see instead?

Firstly, I added DownloadHandler class as follows:

    public class DownloadHandler : IDownloadHandler
    {
        public event EventHandler<DownloadItem> OnBeforeDownloadFired;

        public event EventHandler<DownloadItem> OnDownloadUpdatedFired;

        public void OnBeforeDownload(IWebBrowser chromiumWebBrowser, IBrowser browser, DownloadItem downloadItem, IBeforeDownloadCallback callback)
        {
            OnBeforeDownloadFired?.Invoke(this, downloadItem);

            if (!callback.IsDisposed)
            {
                using (callback)
                {
                    callback.Continue(downloadItem.SuggestedFileName, showDialog: true);
                }
            }
        }

        public void OnDownloadUpdated(IWebBrowser chromiumWebBrowser, IBrowser browser, DownloadItem downloadItem, IDownloadItemCallback callback)
        {
            OnDownloadUpdatedFired?.Invoke(this, downloadItem);
        }
    }

```
browser = new CefSharp.WinForms.ChromiumWebBrowser(Clipboard.GetText())
{
     //here I tried add DownloadHandler but I can’t see this property.
};

//And here I tried the add DownloadHandler, again I can’t see the property. 
//Can you show me solution of this?
```

- **Please provide any additional information below.
- Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
Just I'm using cefsharp, I don't use another 3rd party controls.

**Comment by amaitland** [comment]
http://cefsharp.github.io/api/71.0.0/html/P_CefSharp_WinForms_ChromiumWebBrowser_DownloadHandler.htm
https://github.com/cefsharp/CefSharp/blob/cefsharp/71/CefSharp.WinForms/ChromiumWebBrowser.cs#L167
https://github.com/cefsharp/CefSharp/blob/cefsharp/71/CefSharp.WinForms.Example/BrowserTabUserControl.cs#L43

If by see the property you are referring to IntelliSense then ignore it and type it in manually.

**Comment by amaitland** [comment]
Closing as invalid as this isn't a bug in CefSharp.

**Comment by amaitland** [comment]
In future please ask your question on on https://gitter.im/cefsharp/CefSharp before opening an issue,  thanks.

**Comment by ByErdem** [comment]
But I can't see this property on nuget version.

**Comment by amaitland** [comment]
Every release is tagged, see https://github.com/cefsharp/CefSharp/tags tagging of a release triggers a build. 

You can browser the tag at https://github.com/cefsharp/CefSharp/tree/v71.0.2 the exact commit for the release is available from https://github.com/cefsharp/CefSharp/tags
You can download the source or browser it online. The build log is at https://ci.appveyor.com/project/cefsharp/cefsharp/builds/22945484 the exact commit is https://github.com/cefsharp/CefSharp/commit/7d24861e7af79fc4721eb498bb8417b5aa6cad97

You can compare the commit hash. Browser the source and confirm the code is there.  What you are suggesting quite simply isn't possible.  A problem with your dev environment is quite possible,  not a bug in CefSharp. 

You can use https://github.com/cefsharp/CefSharp.MinimalExample for testing.
