### ISSUE TITLE
Drop down box (select element) closes after mouse wheel with OSR

### ISSUE THREAD

**Issue by nurhat** [cefsharp/CefSharp#2726]
Steps
Run cefclient with --off-screen-rendering-enabled
Go to https://www.w3schools.com/code/tryit.asp?filename=FX82IWA41O2F and click Run.
Open drop down box and hover over the options.
Wheel mouse just once and wait for a second or two.
Drop down box closes automatically.
Expected: Drop down box stays open.

Version: cef_binary_3.3538.1850.ge710be4_windows32_client, Windows 10 64bit

3325 seems fine, 3497 & 3538 have the issue.

Chrome seems fine (it doesn't use OSR.)

@reference from https://bitbucket.org/chromiumembedded/cef/issues/2547/drop-down-box-select-element-closes-after

**Comment by amaitland** [comment]
Closing as `upstream`. Anyone wishing to track this issue should follow https://bitbucket.org/chromiumembedded/cef/issues/2547/drop-down-box-select-element-closes-after
