### ISSUE TITLE
ChromiumWebBrowser not filling winform when windows zoom is >100%

### ISSUE THREAD

**Issue by Johan81S** [cefsharp/CefSharp#2733]
- **What version of the product are you using?**
    - 71.02 = latest from NuGet

- **What architecture x86 or x64?**
  - x64

- **On what operating system?** 
  -   Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
   - WinForms

- **What steps will reproduce the problem?**
    - Create new Winforms application. 
     - Add Cefsharp from Nuget.
     - Use this code as main form as defined below for Form1
     - Run application 
     - Browser filled the whole mainform. --> correct!
     - Change WindowsZoom to a value >100%.
     - Run application again --> **the browser not filled the form but leaves a space on top and leftside of the browser.** 
     - See next zipfile with 3 screencapture-movies for the problem.
     [movies.zip](https://github.com/cefsharp/CefSharp/files/3098258/movies.zip)

> public partial class Form1 : Form
> 	{
> 		public ChromiumWebBrowser Browser { get; set; }
> 
> 		public Form1()
> 		{
> 			InitializeComponent();
> 			Initialize();
> 		}
> 
> 		private void Initialize()
> 		{
> 			string webPage = "http://www.google.nl";
> 			Browser = new ChromiumWebBrowser(webPage) { Dock = DockStyle.Fill };
> 			Controls.Add(Browser);
> 		}
> }

Is there a setting that i'm not aware of, or is this a bug in the ChromiumWebBrowser component??

 
- **What is the expected output? What do you see instead?** 
     - The browser filling the form completely at any windowszoom.

- **Please provide any additional information below.**

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
      - Nope.

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
      - Nope.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

**Comment by amaitland** [comment]
What DPI are you running? Is your app DPI aware?

Please use https://github.com/cefsharp/CefSharp.MinimalExample for testing purposes,  it's DPI aware. 

As per the issue template,  no binary attachments,  this included zip.

**Comment by amaitland** [comment]
Did you test with the CEF Sample application?  If not then please do so

**Comment by Johan81S** [comment]
> What DPI are you running? Is your app DPI aware?
> 
> Please use https://github.com/cefsharp/CefSharp.MinimalExample for testing purposes, it's DPI aware.
> 
> As per the issue template, no binary attachments, this included zip.

Dear amaitland.

After evaluation of this example, in this behaviour does not occur, i managed to solve this problem. It looked like i wasn't aware of the setting: Cef.EnableHighDPISupport. Enabling this setting solves this behaviour. 

This issue can be closed and many thanks for your support!
