### ISSUE TITLE
Adding a LoadUntilEnd(url) and a SendCredentials(user, password)

### ISSUE THREAD

**Issue by crazyfroggy** [cefsharp/CefSharp#2736]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by crazyfroggy** [comment]
Just to avoid re-inventing the wheel and the hot water, every time I want to take a shower when riding a bike, including when the bike is padlocked at a street lamp.

**Comment by amaitland** [comment]
@crazyfroggy Is there a reason you haven't filled out the template?  Where is the technical description?  Are you actually using CefSharp currently?  What problem are you trying to solve? 

What does LoadUntilEnd to exactly?  No blocking methods will be added, only asynchronous ones. 

SendCredentials is likely impractical to implement. We are limited by the CEF API. 

Please stop wasting our time with comments about reinventing the wheel and hot water,  focus your efforts on providing accurate technical information.
