### ISSUE TITLE
Bad <a> link doesn't respond with 404.

### ISSUE THREAD

**Issue by bhartman-livewire** [cefsharp/CefSharp#2738]
CEFSharp.WinForms: 71.0.2
cef.redist.x86 and x64: 3.3578.1820
Obtained from Nuget

Architecture:
Running as x86 on a 64-bit machine

Operating System:
Win10

WinForms

Steps to Reproduce:
1. A windows form contains a ChromiumWebBrowser
2. Initialize ChromiumWebBrowser with a localhost url (local webpage served by IIS)
3. The local webpage contains the following tag: `<a href="http://localhost/badlink/badlink.html"></a>`
4. When this <a> link is clicked, the LoadError event is always fired and has _Aborted_ as the **CefErrorCode**
5. However, if the ChromiumWebBrowser's **Load( )** method tries to load the same bad link, the **OnFrameLoadEnd** event is called with a 404.

I expect the **OnFrameLoadEnd** event to fire with an http status code of 404. That is what happens if the ChromiumWebBrowser's **Load( )** method tries to load the same bad link

I would like to be able to handle a 404 or similar error if a bad link is clicked.

This is written to the debug.log file whenever the bad <a> link is clicked:
```
[0422/114808.864:WARNING:angle_platform_impl.cc(52)] compileToBinary(232): 
C:\fakepath(54,8-58): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
C:\fakepath(62,8-28): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
```

**Comment by amaitland** [comment]
It's important to note that `CefSharp` is just a wrapper around the `Chromium Embedded Framework (CEF)`. Closing this as `upstream` and as changes need to be made in `CEF`. 

The `CEF` project has it's own issue tracker located at https://bitbucket.org/chromiumembedded/cef 

Before opening a new issue you should:

- Search open/closed issues to determine if the problem you are seeing has already been reported
- Test with a newer version if available, see https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-chromium-embedded-frameworkcef for details on testing with the `cefclient` reference application.

If you do find an existing issue that matches this one or create a new one then post a link here for others to follow.
