### ISSUE TITLE
OnBeforeResourceLoad doesn't get called for service worker >= v73.1.120-pre01

### ISSUE THREAD

**Issue by GieltjE** [cefsharp/CefSharp#2740]
### Bug Report
Delete this line and everything above, and then fill in the details below.

- Version: v73.1.120-pre01, nuget
- Win10 X64
- Winforms
- Reproduce/information: 
  - Set some headers using OnBeforeResourceLoad 
  - Open a webpage that uses a service worker which requires those custom headers
  - The first request enters OnBeforeResourceLoad without a hitch
  - Use the debug console to soft refresh (F5 only) the page, it breaks, OnBeforeResourceLoad isn't entered
  - Use the debug console to hard refresh (ctrl+F5) it works again because OnBeforeResourceLoad  is entered

The previous nuget package always enters OnBeforeResourceLoad thus not having a problem.

**Comment by amaitland** [comment]
It's important to note that `CefSharp` is just a wrapper around the `Chromium Embedded Framework (CEF)`. Closing this as `upstream` and as changes need to be made in `CEF`. 

The `CEF` project has it's own issue tracker located at https://bitbucket.org/chromiumembedded/cef it is recommended you ask on https://magpcss.org/ceforum/index.php before opening an issue on the CEF issue tracker. The behavior you are seeing may be the expected default.

Before opening a new issue you should:

- Search open/closed issues to determine if the problem you are seeing has already been reported
- Test with a newer version if available, see https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-chromium-embedded-frameworkcef for details on testing with the `cefclient` reference application.

If you do find an existing issue that matches this one or create a new one then post a link here for others to follow.

**Comment by GieltjE** [comment]
I've searched all mentioned places beforehand, there is nothing relevant to be found.

We are unable to use the sample application as we need quite a bit of custom handling.

**Comment by amaitland** [comment]
From a `CefSharp` point of view the code for `OnBeforeResourceLoad` hasn't changed since version `51` (We're talking almost 3 years).

https://github.com/cefsharp/CefSharp/blob/cefsharp/51/CefSharp.Core/Internals/ClientAdapter.cpp#L697
https://github.com/cefsharp/CefSharp/blob/cefsharp/73/CefSharp.Core/Internals/ClientAdapter.cpp#L810

You'll have to raise your issue upstream or wait for a `CEF` update and hope that it's resolved with in `Chromium`.

**Comment by GieltjE** [comment]
The forums denied my post, can't open a bug report as we don't have the required expertiese to fix a proper c++ demo, so I guess were are bound to waiting as there is no other posibility.

**Comment by amaitland** [comment]
> I'm surprised that OnBeforeResourceLoad was ever called for service workers. The capability will be officially supported starting with https://bitbucket.org/chromiumembedded/cef/issues/2622. You can star that issue to receive updates.

Forum post was successful, see https://magpcss.org/ceforum/viewtopic.php?f=6&t=16725

So `CEF` officially doesn't support `Service Worker` yet. Will be supported at some point though.

**Comment by edobnet** [comment]
not supported on 115
