### ISSUE TITLE
Add the ability to enable dark mode for Cefsharp 74

### ISSUE THREAD

**Issue by Daszbin** [cefsharp/CefSharp#2741]
**Is your feature request related to a problem? Please describe.**
No it’s not a problem it’s just a suggestion since chrome 74 has add the ability to enable dark mode so should cefsharp

**Describe the solution you'd like**
Well for Winforms or wpf when you enable dark mode flags then the whole the controls containing the cefbrowser get dark mode too meaning the whole program gets darkened. Maybe create a handler for something like that.

**Describe alternatives you've considered**
Well I can’t really make dark mode work on Cefsharp only could darken the Winforms app controls but nothing else.

**Comment by amaitland** [comment]
> the controls containing the cefbrowser get dark mode too meaning the whole program gets darkened

Does dark mode change the web browser at all? Doesn't appear so to me. Just changes the surrounding buttons, address bar, none of which `CefSharp` actually provides, so that's your responsibility to implement.

What change does dark mode have on the `Browser`? Which is all that `CefSharp` is.

@Daszbin Please discuss your ideas for features on https://gitter.im/cefsharp/CefSharp before opening any more issues, thank you.

**Comment by chris-kruining** [comment]
@amaitland CSS now supports the `prefers-color-scheme` media query, so it would be benificial if cef would copy the OS setting in this regard (I have no clue as to how this is implemented, I just know Chrome does it, and it would amazing to have in cef#)

Documentation :: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by amaitland** [comment]
You can download the Sample application from http://opensource.spotify.com/cefbuilds/index.html

If it works great, it'll be available in the next major release, if not you'd need to make your request at https://magpcss.org/ceforum/viewforum.php?f=7 as CEF would need to add support. 

Post a link back here if you do post on ceforum. 

CefSharp is just one of many wrappers around https://bitbucket.org/chromiumembedded/cef/src/master/README.md

**Comment by amaitland** [comment]
https://bitbucket.org/chromiumembedded/cef/issues/2824/support-prefers-color-scheme-media-query

**Comment by amaitland** [comment]
CEF has added support https://bitbucket.org/chromiumembedded/cef/commits/f2c0c3f8fbf3

Support has only been added to the beta branch of CEF so won't land in CefSharp until version 86/87.
