### ISSUE TITLE
How to specify network card send network requests?

### ISSUE THREAD

**Issue by qinxg** [cefsharp/CefSharp#2746]
My computer has multiple network CARDS and ips. 
How do I specify a network card to send network requests?

like use HttpWebRequest

configurator.ServicePoint.BindIPEndPointDelegate =
                        (servicePoint, remoteEndPoint, retryCount) => new IPEndPoint(ip, 0);

**Comment by amaitland** [comment]
Search/ask on https://magpcss.org/ceforum/index.php

**Comment by amaitland** [comment]
https://magpcss.org/ceforum/viewtopic.php?f=6&t=16730
