### ISSUE TITLE
CefSharp.Winform duplicate input keyboard key while sending to web form input control

### ISSUE THREAD

**Issue by slavenl** [cefsharp/CefSharp#2752]
63.0.0-pre01 (older version also affected)
x64, Win10, WinForms

I use CefSharp.WinForm to "host" simple Angular app with few input controls. Because of need to map some keyboard keys to some another I use IKeyboardHandler (OnPreKeyEvent).

When I return "true" from OnPreKeyEvent (bool) I am able to suppress initially pressed key BUT instead of returning just one "transformed" value he returns duplicated new value to web input control.

Simple e.g.
1. I press "a" in input control
2.  MyKeyHandler which implement IKeyHandler (OnPreKeyEvent) method enter his codebehind

For sending new key I use KeySend(Sys.Win.Form.SendKeys):

KeySend.SendWait("{s}") 

or InputSimulatorPro Nuget package:

InputSimulator sim = new InputSimulator();
sim.Keyboard.KeyDown(WindowsInput.Native.VirtualKeyCode.VK_S);

3. Input control gets 2 values od "s" character.

I tried SendKey Flush / Thread.Sleep combinations but nothing has impact - I always get **2 values OUT**.

ANY help/workaround/bugfix would be greatly appreciated.

**Comment by amaitland** [comment]
Asked at https://stackoverflow.com/questions/55903672/cefsharp-winform-duplicate-input-keyboard-key-while-sending-to-web-form-input

My only suggestion would be to integrate CEF into your existing message loop see https://github.com/cefsharp/CefSharp/wiki/General-Usage#multithreadedmessageloop

Keyboard handling for the WinForms versions is handled entirely at the CEF/Chromium level. T

**Comment by amaitland** [comment]
Also version 63 is very old and unsupported.
