### ISSUE TITLE
CefSharp.BrowserSubprocess.exe over 1GB memory use

### ISSUE THREAD

**Issue by zdomokos** [cefsharp/CefSharp#2753]
on Win10, using 73.1.120.0 browsing HTML 5 page like tradingview.com or apache guacamole client. Memory usage goes above 1GB in 2 minutes. Is there a settings that would limit the amount of memory used?
![image](https://user-images.githubusercontent.com/2656974/56918346-c59e6000-6a8b-11e9-8184-7dee677a43cc.png)

**Comment by amaitland** [comment]
1gb of memory usage for a web browser isn't out of ordinary. Memory allocation is controlled entirely at the Chromium level.

**Comment by zdomokos** [comment]
For the same page IE uses 95MB. Something must not be right.
![image](https://user-images.githubusercontent.com/2656974/56929536-de1c7380-6aa7-11e9-892f-67887c75dc81.png)

**Comment by amaitland** [comment]
And the read you are testing with IE and not Chrome is? If Chrome memory usage at the exact same version is different then test with the CEF Sample application as outlined in the bug report https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

CefSharp is just a wrapper as detailed in https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by zdomokos** [comment]
I see similar memory usage in chrome. 
![image](https://user-images.githubusercontent.com/2656974/57029995-5a7e9600-6c11-11e9-8a8e-c4991a0e011c.png)
