### ISSUE TITLE
Could not load file or assembly 'CefSharp.WinForms, Version=71.0.2.0

### ISSUE THREAD

**Issue by GlennIM** [cefsharp/CefSharp#2754]
I used Package Manager Console and installed  "Install-Package CefSharp.WinForms -Version 71.0.2" from github and am using AnyCPU and followed all the steps to use AnyCPU at https://ourcodeworld.com/articles/read/173/how-to-use-cefsharp-chromium-embedded-framework-csharp-in-a-winforms-application.

Then I installed Visual C++ Redistributable Packages for Visual Studio 2013 (**x64 version**). My application compiles/links OK but get the following error message when trying to display the browser in my form... 

System.BadImageFormatException
  HResult=0x8007000B
  Message=Could not load file or assembly 'CefSharp.WinForms, Version=71.0.2.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138' or one of its dependencies. An attempt was made to load a program with an incorrect format.

PLEASE HELP!

**Comment by amaitland** [comment]
The official AnyCpu #1714 guide is, follow it instead. The article you linked wasn't written by me.

VC++ 2015 is required as per https://github.com/cefsharp/CefSharp/blob/cefsharp/71/NuGet/Readme.txt#L32
