### ISSUE TITLE
Headless automated file upload

### ISSUE THREAD

**Issue by samneefs** [cefsharp/CefSharp#2760]
**Is your feature request related to a problem? Please describe.**
I want to automate a file upload.

I want to run a headless process, where a file is uploaded to a website.
I implemented the IDialogHandler to return the correct file.
When clicking the upload button manually; the correct file is selected.
When clicking the upload button via javascript, which I manually entered in the devTools console; the correct file is selected.

The problem is when I execute the javascript automatically; then the focus is set to the upload button, but the real click doesn't happen (also don't get errors).

**Describe the solution you'd like**
I know this is blocked in Chrome for security reasons, however I don't see the problem to be able to enable it in CefSharp; either per request, per url/domain or for a specific control.

**Describe alternatives you've considered**
I'm aware that a possible workaround would be running it in a WinForms process and using C# to click on the button, however I want it to run headless (without user interaction on a server).

I know that a file upload could be done by constructing a XMLHttpRequest. 
However, it's not a simple form; 
- then I would have to be able to get the security token from somewhere
- and make sure the response gets inserted in the (Angular) application correctly, since the way the webapplication handles the response is crucial for the rest of the application to work.
- the webapplication might change; then me and my colleagues should also be able to change this process (fast). Changing the code to find the correct element by ID isn't hard to do/explain, but rebuilding the XMLHttpRequest would take more time

**Comment by amaitland** [comment]
> I know this is blocked in Chrome for security reasons, however I don't see the problem to be able to enable it in CefSharp; either per request, per url/domain or for a specific control.

Ultimately `CefSharp` is just a wrapper, the `Feature Request` template needs updating to clearly outline this. `CEF` would need to add support for this, the project has it's own feature request forum at https://magpcss.org/ceforum/viewforum.php?f=7&sid=5a95cf588cd7bcc8d0d43b875aeae049

See https://github.com/cefsharp/CefSharp/wiki/General-Usage for background.

> The problem is when I execute the javascript automatically; then the focus is set to the upload button, but the real click doesn't happen (also don't get errors).

You can send a key press or mouse down/up combinations as it stands currently. There are a few `stackoverflow` issues that already cover this topic (there are more if you go looking)

https://stackoverflow.com/questions/44736904/issue-with-cefsharp-browser-sendkeys
https://stackoverflow.com/a/27684756/4583726

Closing this as it's not possible to workaround `Chrome` security restrictions with `CEF` adding support. If you do post a feature request then post a link back here and this can be reopened once it's implemented.
