### ISSUE TITLE
Duplicated content in *How do you expose a .NET class to JavaScript?* at the *General Usage* wiki

### ISSUE THREAD

**Issue by kiewic** [cefsharp/CefSharp#2763]
The *General Usage* wiki page, in the section *How do you expose a .NET class to JavaScript?*, has everything between:

```
The simple workflow would look like:
```

And:

```
When a `CefSharp.BindObjectAsync` call is made, the ...
```

duplicated.

However, both chunks have differences, so, it is hard to say which one is the correct one.

**Comment by kiewic** [comment]
In addition, it seems the documentation samples do not work. For example, see the following fragments taken from the wiki:

```csharp
public class BoundObject
{
    public class AsyncBoundObject
    {
    	//We expect an exception here, so tell VS to ignore
        [DebuggerHidden]
        public void Error()
        {
            throw new Exception("This is an exception coming from C#");
        }
	
        //We expect an exception here, so tell VS to ignore
        [DebuggerHidden]
        public int Div(int dividend, int divisor)
        {
            return dividend / divisor;
        }
    }
}
```

> Do I really need two nested classes here? `BoundObject` and `AsyncBoundObject`?

```html
<script type="text/javascript">
(async function()
{
	await CefSharp.BindObjectAsync("boundAsync");
	
	boundAsync.div(16, 2).then(function (actualResult)
	{
		const expectedResult = 8
		assert.equal(expectedResult, actualResult, "Divide 16 / 2 resulted in " + expectedResult);
	});
	
	boundAsync.error().catch(function (e)
    	{
        	var msg = "Error: " + e + "(" + Date() + ")";
    	});
})();
// ...
```

```csharp
//For async object registration (equivalent to the old RegisterAsyncJsObject)
browser.JavascriptObjectRepository.Register("boundAsync", new BoundObject(), true, options);
```

When running this sample, I get the following error in the console:

```
Uncaught (in promise) TypeError: boundAsync.div is not a function
    at index.html:85
```

**Comment by amaitland** [comment]
> Do I really need two nested classes here? `BoundObject` and `AsyncBoundObject`?

No, that's a mistake, thanks.

I will review the rest shortly.

**Comment by kiewic** [comment]
I removed the nested class.

**Comment by amaitland** [comment]
There are two sections specifically:

https://github.com/cefsharp/CefSharp/wiki/General-Usage#async-javascript-binding-jsb
https://github.com/cefsharp/CefSharp/wiki/General-Usage#sync-javascript-binding-jsb

Some of the formatting needs to be improved to make it clearer there's two different options.

**Comment by amaitland** [comment]
The `Binding API` methods have been moved to their own wiki page at
