### ISSUE TITLE
load html5 touchstart not work

### ISSUE THREAD

**Issue by xcmonline** [cefsharp/CefSharp#2768]
use CEFSharp.wpf 73.1.130
load html5 touchstart not work

           var settings = new CefSettings
            {
                BrowserSubprocessPath = "CefSharp.BrowserSubprocess.exe"
            };
            //settings.CefCommandLineArgs["touch-events"] = "enabled";
            settings.CefCommandLineArgs.Add("touch-events", "1");
            Cef.Initialize(settings);
            ChromiumWebBrowser browser = new ChromiumWebBrowser();
            browser.Address = Environment.CurrentDirectory + "\\html5\\index.html";
            //gWeb.IsManipulationEnabled = true;
            gWeb.Children.Add(browser);

$(".navbar").on("touchstart",function(){
  alert("test ok");
})

**Comment by amaitland** [comment]
Duplicate #228
