### ISSUE TITLE
javascript bound object register failed sometimes 

### ISSUE THREAD

**Issue by benbenfa** [cefsharp/CefSharp#2772]
What version of the product are you using?
above 71.0.0 but not only since 71.0.0

What architecture x86 or x64?
both x86 and x64

On what operating system?
Win10

Are you using WinForms, WPF or OffScreen?
WinForms

What steps will reproduce the problem?
first you can build and run CefSharp.WinForms.Example there is a tab is opened ,then you can click "file"->"show dev tools " you can see the dev tools select the “Console Tab” input "bound" the bound object is exist  ,it's very good ,but when you open a new tab by click "file"->"New Tab",when you open current "dev tools" select console tab input bound found that "bound is not defined",i feel there is a bug ,when you reload the current tab the bound object is can be found too 

Please provide detailed information here, enough for someone else to reprodce your problem.
see above can reproduce

Please no binary (zip, etc) links, fork the MinimalExample and push your changes to GitHub. (Alternatively use a code sharing service list Gist or Pastebin).

What is the expected output? What do you see instead?
bond is aways defined
Please provide any additional information below.
no
A stack trace if available, any Exception information.
no
Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
no
Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
no
Does this problem also occur in the CEF Sample Application from 
no

**Comment by amaitland** [comment]
If you have a bug to report then you will need to use the `Bug Report Template` at https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report Please edit your issue and use the bug report provided in the link.

Please include a clear list of steps to reproduce your problem. The list of steps provided is incomplete.
