### ISSUE TITLE
When I input in the browser , ime in the top left corner.

### ISSUE THREAD

**Issue by wlan121** [cefsharp/CefSharp#2773]
- **What version of the product are you using?**
    - CefSharp.WPF 73.1.1.130
    - IDE：VS2017

- **What architecture x86 or x64?**
    -  AnyCpu , First use x86
- **On what operating system?**
    - Win10
- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - WPF

**Comment by amaitland** [comment]
Duplicate #1262

Please review all open issues before creating a new one next time, thanks.
