### ISSUE TITLE
Feature Request - Add Javascript CefSharp.PostMessage

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#2775]
There are lots of cases when you don't need to explicitly bind an object, you just wish to pass some message data back to the browser. This will be added to every `V8Context`, so will be immediately available for javascript execution.

- [x] Add `.Net` event
- [x] Add `CefSharp.PostMessage` javascript method.
- [ ] Add detailed example to this issue

```javascript
CefSharp.PostMessage(message);
```

I'm thinking we won't impose a strict message structure, will use the current conversion from `Javascript->C#` so whatever data types you can transfer now will be supported.

**Comment by amaitland** [comment]
Use Cases:
- For simple cases there's no need to bind an object to get communication up and running
- An easy way to handle events/button clicks etc

Details:

- Accepts only a single param, this can be a primitive type like `int`, `string` or a complex object
- `IJavascriptCallback` is supported (javascript function pointer)
- You can use `dynamic` in `c#` for complex objects or use the built in `Model Binder` via the `JavascriptMessageReceivedEventArgs .ConvertMessageTo<T>()` method to convert to a complex object

```js
//In Javascript you call CefSharp.PostMessage or cefSharp.PostMessage
//Either case is supported
CefSharp.PostMessage({ "Type": "Update", Data: { "Property": 123 }, "Callback": responseFunc });
```

```c#
browser.JavascriptMessageReceived += OnBrowserJavascriptMessageReceived;

private void OnBrowserJavascriptMessageReceived(object sender, JavascriptMessageReceivedEventArgs e)
{
	//Complext objects are initially expresses as IDicionary
	//You can use dynamic to access properties (the IDicionary is an ExpandoObject)
	//dynamic msg = e.Message;
	//Alternatively you can use the built in Model Binder to convert to a custom model
	var msg = e.ConvertMessageTo<PostMessageExample>();
	var callback = msg.Callback;
	var type = msg.Type;
	var property = msg.Data.Property;

	//Call a javascript function with your response data
	callback.ExecuteAsync(type);
}
```

**Comment by amaitland** [comment]
The [How do you handle a Javascript event in C#?](https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#13-how-do-you-handle-a-javascript-event-in-c) of the `FAQ` has been updated to use `PostMessage`.

**Comment by woth2k3** [comment]
Hi! Could you please give me a hint about the reason of this error?

![image](https://user-images.githubusercontent.com/21021805/82141727-76ff6780-9840-11ea-94e9-fc2a0086c0b5.png)

**Comment by amaitland** [comment]
> Could you please give me a hint about the reason of this error?

@woth2k3 Please no images of code, see https://github.com/cefsharp/CefSharp/wiki/Questions-&-Support#no-images-of-code

I'd suggest you try casting `msg.Callback` to `IJavascriptCallback` before attempting to call `ExecuteAsync`. If that doesn't work then I'd need to see the `PostMessage` javascript.

**Comment by woth2k3** [comment]
Sorry for the image. I've edited the message and made it as it's supposed to be.

Worked like a charm with casting.  Many thanks!

**Comment by gf21T** [comment]
javascript:webkit.messageHandlers.errorPageManager.postMessage(%7Burl:%20%22http://localhost:12054/ErrorPage/serverUntrust?currentUrl=https://afflnk.microsoft.com/c/1239701/439077/7811?sharedid%3DEMMX_RURU_NTP_TOPSITES&badcert=MIIIPDCCBiSgAwIBAgITewAOsXgEoveN0gGNggAAAA6xeDANBgkqhkiG9w0BAQsFADCBizELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEVMBMGA1UECxMMTWljcm9zb2Z0IElUMR4wHAYDVQQDExVNaWNyb3NvZnQgSVQgVExTIENBIDEwHhcNMjAwMTE1MTkxMDEyWhcNMjIwMTE1MTkxMDEyWjAfMR0wGwYDVQQDExRhZmZsbmsubWljcm9zb2Z0LmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAI87ffow9H0e81art4Pi4w2GaWRtFNyn0m2lmWRKSpjAJB9QOeQF6Vs5hqlfTFDO7T7R0fiK5VUH3E99lv5FuHxAQziV8e+TXsaIj4iWsaoyQgqokFfmMJFpQ3R1zSAhFiKP4t2E01wlAyIVAR/wT4FHFgt/RXu47YzdwiLJ0B70+yAx6XJ87RckhJGWMDn/ECSNAlc2O+Z5WUTarNKNXVdnWcruawyCtTx9Ym7IYbRwLXm8hEPj0Zz3YZhSDQPmkmLIXN/zP+WgrdR2qXZ2zxyc06XSawfATa91yYCpCMN2Z16RNRxAZDuB6zFsv3D0bxGIb0eLVM0foKLnjaC+NNUCAwEAAaOCBAIwggP+MIIBfgYKKwYBBAHWeQIEAgSCAW4EggFqAWgAdgBGpVXrdfqRIDC1oolp9PN9ESxBdL79SbiFq/L8cP5tRwAAAW+qpi+BAAAEAwBHMEUCIED+HQRgsbzSD5QE324+58uTOkAFd27E6aDgVRWxQVqZAiEA7i5Y1jut/XcPbFkrmfyHfKm4bYx1GLHt7CYqHDJ4x2cAdgBByMqx3yJGShDGoToJQodeTjGLGwPr60vHaPCQYpYG9gAAAW+qpi86AAAEAwBHMEUCIQCt6rK5XwAv0PBgFxRLHE1E8FlHBDFYGoCJTkkLYH5w9gIgK3KxzETX8BwnKWNCtdayaSIizYltD0TsSA3I7O0PS5oAdgCkuQmQtBhYFIe7E6LMZ3AKPDWYBPkb37jjd80OyA3cEAAAAW+qpi8yAAAEAwBHMEUCIGlTshi9QqYZvcmVvPPtslJRZT+vuFYfUofHB5YKGVEdAiEA22XfcOc0QHazHHHz2/0/QW3zi9Abaq2dMwM1RMHnNyEwJwYJKwYBBAGCNxUKBBowGDAKBggrBgEFBQcDAjAKBggrBgEFBQcDATA+BgkrBgEEAYI3FQcEMTAvBicrBgEEAYI3FQiH2oZ1g+7ZAYLJhRuBtZ5hhfTrYIFdhNLfQoLnk3oCAWQCAR0wgYUGCCsGAQUFBwEBBHkwdzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraS9tc2NvcnAvTWljcm9zb2Z0JTIwSVQlMjBUTFMlMjBDQSUyMDEuY3J0MCIGCCsGAQUFBzABhhZodHRwOi8vb2NzcC5tc29jc3AuY29tMB0GA1UdDgQWBBQb0J5NIHlmEO7SrR+4CVggq5lAuDALBgNVHQ8EBAMCBLAwHwYDVR0RBBgwFoIUYWZmbG5rLm1pY3Jvc29mdC5jb20wgawGA1UdHwSBpDCBoTCBnqCBm6CBmIZLaHR0cDovL21zY3JsLm1pY3Jvc29mdC5jb20vcGtpL21zY29ycC9jcmwvTWljcm9zb2Z0JTIwSVQlMjBUTFMlMjBDQSUyMDEuY3JshklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL21zY29ycC9jcmwvTWljcm9zb2Z0JTIwSVQlMjBUTFMlMjBDQSUyMDEuY3JsME0GA1UdIARGMEQwQgYJKwYBBAGCNyoBMDUwMwYIKwYBBQUHAgEWJ2h0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvbXNjb3JwL2NwczAfBgNVHSMEGDAWgBRYiJ/W3JxIIrcUPv+EiOjmhf/6fTAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDQYJKoZIhvcNAQELBQADggIBAAlBgpsUCOk3dw7IA8rWbH0tAQstIHYzqYydBSzVLVT3UCrfR6aRFv8K8NpXE0wo3nIgIKk+/I/njnVdc1pc1Lcae4EvRUThuRN6KmKm9mQfB1qBFjIcr1b3GV98owl6Zh7si7nB+pgwbSY1Nja0HoKz4PDP/c4V3TCLo3ce5qGnBPnmoqHsg3i8heLk4BmHZyaEDVo7MKfCPiJd48rNFEMc69E4UZ48hg57FyaRR4/6FFR9IoJyPE3KBGGhR2V/Y1DAPn3ngbYxAQ6dtu0qoeFKGaAVDupNQzeTZatfq+6LebH4n0XCwbkU+kphwc9l94ss4mDFORjEXwcYWMPSP+wmqsLw4v3+KJD8RUsNw21OrQjiKv1sYGb8/zjEp2efgejkctHd3/xDJA7iL9dSEkQbLcCC91EBD/pHBm1kPCoFa9zSyOM32crREYT8IkpaMS3pL6T8pAWt0hnry1JaINflz74EMcFv9grvREeT2bBr8IKbOFLXLgHi6Ze3UXDWAOaWLSd0MaPnRHzxlBW9QT1YB46PIRa3LGxjvnvBSh70cBXyrI5OS48w02vqBJmgFk/rj6m74z4medD8PrOYv03Cw5ZtLVcde1tjvWjlLmgs7Wf3vDWQLTQ/KxGQ6ivFHCXtpwKW31ihha6mu39yYynkBTuy1bjq+j9Bz55MWFpf%22%7D)

**Comment by amaitland** [comment]
@gf21T You don't appear to be using CefSharp.PostMessage, I'd suggest you ask for help on stackoverflow.

**Comment by BuslikDrev** [comment]
Предлагаю добавить ещё в таком стиле написания функцию "CefSharp.PostMessage" => "CefSharp.postMessage"
