### ISSUE TITLE
WinForms - Initial Touch Activation Not Working

### ISSUE THREAD

**Issue by dbuechel** [cefsharp/CefSharp#2776]
- **What version of the product are you using?**
73.1.130

- **What architecture x86 or x64?**
x86

- **On what operating system?**
Windows 10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms (in a WPF application, using WindowsFormsHost)

- **What steps will reproduce the problem?**
1. Activate tablet mode in Windows 10
2. Run the WinForms minimal example
3. Tap the Google search field
4. The on-screen keyboard of Windows should pop up
5. Try to enter something with the on-screen keyboard

- **What is the expected output? What do you see instead?**
Expected: The text entered with the on-screen keyboard should appear in the search field.
Actual: No text appears in the search field, even though it looks activated with a blinking cursor.

- **Please provide any additional information below.**
This appears to be a regression introduced by #1811.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
No, it does not. Tested with CEF 73.1.13+g6e3c989+chromium-73.0.3683.75 / Chromium 73.0.3683.75

**Comment by amaitland** [comment]
For anyone experiencing this you can remove the `WS_EX_NOACTIVATE` as described in https://github.com/cefsharp/CefSharp/issues/1811#issuecomment-475074847 and revert to the old behaviour.

**Comment by amaitland** [comment]
The `CEF Sample Application(cefclient)` also has `WS_EX_NOACTIVATE` set as the default, the difference being that in our `FocusHandler` implementation we're returning `true` to cancel `Focus` when `CefFocusSource.FocusSourceNavigation` is specified as the source.

https://github.com/cefsharp/CefSharp/blob/cefsharp/73/CefSharp.WinForms/Internals/DefaultFocusHandler.cs#L97

**Comment by dbuechel** [comment]
Aha, I see. I think it would be great if the `WS_EX_NOACTIVATE` window style were configurable, as I have noticed a related strange touch behavior with the CEF sample application, where the focus somehow remains on the address bar even after activating the Google search field, and I highly suspect that it pertains to the same root cause.

**Comment by amaitland** [comment]
> I think it would be great if the `WS_EX_NOACTIVATE` window style were configurable

It's already configurable, you just have to inherit from `ChromiumWebBrowser` and `override CreateBrowserWindowInfo` as I've detailed in the link above.

**Comment by amaitland** [comment]
With commit https://github.com/cefsharp/CefSharp/commit/f725ab3907487e1cac34b2b407d2c4535a8edba7 the behaviour when `WS_EX_NOACTIVATE` is set is to allow the browser to take focus on initial `Load`. I've only done limited testing at this stage and my tablet touch screen is working as expected.

**Comment by amaitland** [comment]
Final double check and everything appears to be working as expected. I only have a single touch screen, so my testing is limited to a single device.

If the problem is still reproducible with version `75.1.141` then we can reopen this.

**Comment by dbuechel** [comment]
Thank you very much. I finally had the time to re-test the issue with the new version, it now works like expected. Sorry for the late reply...

**Comment by dbuechel** [comment]
After further testing, I realized this really only works for the very first touch activation. If I set the focus to another element of the application (like a button of the window which embeds the browser control) and then try to re-focus the input field within the browser via touch, the bug as described above still persists. I guess I'll just have to leave the custom window style on the browser control...

**Comment by dbuechel** [comment]
Okay, the problem persists even with the window style applied. Maybe this is a bug in Chromium itself. I have found word on the internet which implies that touch focus in Chromium on Windows always had issues.

**Comment by amaitland** [comment]
@dbuechel If you have a link to the chromium touch focus issue could you post it please. 

Reopening, I'll have another look when time permits.

**Comment by dbuechel** [comment]
Great, thanks a lot. It was a while back when I investigated the problem, but I think it was this issue here: https://bitbucket.org/chromiumembedded/cef/issues/1797/windows-touch-does-not-return-focus-to-the

**Comment by amaitland** [comment]
To match the cefclient reference implementation we should remove WS_EX_NOACTIVATE on initial page load.

https://github.com/chromiumembedded/cef/blob/9df4a54308a88fd80c5774d91c62da35afb5fd1b/tests/cefclient/browser/root_window_win.cc#L1088

**Comment by amaitland** [comment]
Restored `FocusHandler` to previous behaviour in https://github.com/cefsharp/CefSharp/commit/917480da3b36cb64d8ba77eb7825d078a848561c

`WS_EX_NOACTIVATE` is now removed on initial navigation, see commit https://github.com/cefsharp/CefSharp/commit/defc2c3af6ec418c3221acfc0bdca3e06d5b89f2

**Comment by dbuechel** [comment]
Thanks for the info. Does that mean that the issue is now fixed by default in CEF itself?

**Comment by amaitland** [comment]
The CefSharp implementation now matches the cefclient reference implementation.

> Does that mean that the issue is now fixed by default in CEF itself?

No
