### ISSUE TITLE
mp4 file not playing in CEFSharp 71.0.2

### ISSUE THREAD

**Issue by kumarkpandey** [cefsharp/CefSharp#2777]
- **What version of the product are you using?**
    -  CefSharp.winforms 71.0.2
- **What architecture x86 or x64?**
     - x86
- **On what operating system?**
    - Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
     Winform in wpf
- **What steps will reproduce the problem?**
    - Launching SCORM course which having .mp4 video, and that video could not launch.
    
- **What is the expected output? What do you see instead?**
     - SCORM course video should be play which having .mp4 video.
- **Please provide any additional information below.**
    
- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

    No, not checked.

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/wiki/General-Usage#multimedia-audiovideo
