### ISSUE TITLE
navigator.mediaDevices.getDisplayMedia support?

### ISSUE THREAD

**Issue by terius** [cefsharp/CefSharp#2781]
I need to add screen sharing function in my web project, I write the code:
 try {
    captureStream = await navigator.mediaDevices.getDisplayMedia(displayMediaOptions);
  } catch(err) {
    console.error("Error: " + err);
  }
in my web site,but it do not work in cefSharp(verison:73.1.13),it works in chrome(version: 74.0.3729.157).
even I write code :
 settings.CefCommandLineArgs.Add("enable-media-stream", "1");
            settings.CefCommandLineArgs.Add("enable-p2papi", "1");
            settings.CefCommandLineArgs.Add("allow-running-insecure-content", "1");
            settings.CefCommandLineArgs.Add("enable-usermedia-screen-capturing", "1");
            settings.CefCommandLineArgs.Add("enable-speech-input", "1");
            settings.CefCommandLineArgs.Add("enable-experimental-web-platform-features", "1");
            settings.CefCommandLineArgs.Add("allow-file-access-from-files", "1");
            settings.CefCommandLineArgs.Add("allow-http-screen-capture", "1");
              settings.CefCommandLineArgs.Add("unsafely-treat-insecure-origin-as-secure", "http://localhost:8080/"); 
in cefSharp project(App.xaml.cs),But It is still not working，it show error："Uncaught (in promise) NotAllowedError: Permission denied" 

so how can i process it?TKS。

**Comment by amaitland** [comment]
CEF has it's own support forum search there.

https://magpcss.org/ceforum/index.php

**Comment by amaitland** [comment]
`navigator.mediaDevices.getDisplayMedia` has yet to be added in `CEF`, see 
https://bitbucket.org/chromiumembedded/cef/pull-requests/193/wip-media-access-handling/diff#comment-92698076 (`Watch this pull request` on `PR` for notifications).

**Comment by poplark** [comment]
I found a post about it, but not test on it.

[https://gitter.im/cefsharp/CefSharp?at=5c536de18aa5ca5abf6383d1](https://gitter.im/cefsharp/CefSharp?at=5c536de18aa5ca5abf6383d1)

add these command args in Cef.Initialize:
`
enable-media-stream,
enable-experimental-web-platform-features,
enable-usermedia-screen-capturing,
use-fake-ui-for-media-stream
`
