### ISSUE TITLE
WinForms - Remove EditorBrowsableState.Never

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#2784]
A number of the properties have the `EditorBrowsable(EditorBrowsableState.Never)` attribute specified. Looks like this actually hides them from `Intellisense` which isn't the actual intended behaviour, only hiding them from the `WinForms Designer` is required.

> The following sample demonstrates how to hide a property of a class from IntelliSense by setting the appropriate value for the EditorBrowsableAttribute attribute.

https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.editorbrowsableattribute?view=netframework-4.8

https://stackoverflow.com/a/2598754/4583726 suggests we might actually need to use `DesignerSerializationVisibility`

**Comment by amaitland** [comment]
@merceyz Planning on removing `EditorBrowsable` and replacing with `DesignerSerializationVisibility`, let me know if you have any thoughts/objections.

**Comment by merceyz** [comment]
@amaitland No objections here, go ahead :+1:
