### ISSUE TITLE
Enable GitHub Sponsors for this project

### ISSUE THREAD

**Issue by Sankra** [cefsharp/CefSharp#2785]
This project is a perfect fit for the soon to be GitHub Sponsors. 

https://github.com/sponsors

**Comment by amaitland** [comment]
Thanks for the interesting suggestion, looks like it's a closed beta at the moment.  When it's available I'll check it out :+1:

**Comment by Exouxas** [comment]
I believe this issue can be closed now

**Comment by Sankra** [comment]
Indeed it can 🥳

**Comment by amaitland** [comment]
For anyone interested my [GitHub Sponsors](https://github.com/sponsors/amaitland) page is now live.
