### ISSUE TITLE
The css hover caton,time waiting for main thread is too long

### ISSUE THREAD

**Issue by wlan121** [cefsharp/CefSharp#2786]
- **What version of the product are you using?**
    -  Nuget
    - 73.1.130

- **What architecture x86 or x64?**
    -  both
- **On what operating system?**
    - Win10,

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF
- **What steps will reproduce the problem?**
  Mouse Move
Total Time
5.29 s
Self Time
0
Time Waiting for Main Thread
5.17 s

**Comment by wlan121** [comment]
![image](https://user-images.githubusercontent.com/50567348/58258694-cafa7c00-7da5-11e9-92a8-063b0147042b.png)

**Comment by amaitland** [comment]
Did you test with the CEF Sample application?  

Steps to reproduce are missing a url that can be used for testing.

**Comment by wlan121** [comment]
i use cefsharp.winform to reslove this problem

**Comment by amaitland** [comment]
To look into this further a url that reproduces the problem and a step by step list of instructions is required. If those are provided this can be reopened.
