### ISSUE TITLE
LoadHtml(largeHtml) not working

### ISSUE THREAD

**Issue by SongPing** [cefsharp/CefSharp#2788]
- **What version of the product are you using?**
v73.1.13 using Nuget

- **What architecture x86 or x64?**
x64

- **On what operating system?**
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
Winforms

- **What steps will reproduce the problem?**
chromiumWebBrowser.LoadHtml(largeHtml) ; // largeHtml is a large html string
LoadString produces similar error.

- **What is the expected output? What do you see instead?**
Expected output: No Error.
System.UriFormatException: 'Invalid URI: The Uri string is too long.'
It seems that only input up to 2000 character can be handled.

I like to display large on the fly generated textual information in the browser control.
Is there an other possibility to load large data into the control?

**Comment by SongPing** [comment]
Hi support,
thanks for your fast answer.
But I think this issue is either a bug or, if this behavior is by design, the the issue is a feature request.
To set a html page (even a larger one) is a very basic functionality of a web control.

**Comment by amaitland** [comment]
Those limits are imposed by Chromium, nothing we can do about it.

Please read https://github.com/cefsharp/CefSharp/wiki/General-Usage#request-handling and ask any follow up questions on one of the support options listed above. There are plenty of options already available.

**Comment by SongPing** [comment]
Thanks for the reply!
I wrote 2 convenient classes, in the case the webcontrol is only used to display large content and no other initialization is needed: 
```
public class CefSharpSchemeHandlerFactory : ISchemeHandlerFactory {
    public const string SchemeName = "largehtml";
    public string Html { get; set; } = "";

    public IResourceHandler Create(IBrowser browser, IFrame frame, string schemeName, IRequest request) {
        return ResourceHandler.FromString(Html, "html");
    }
}
public static class ChromiumWebBrowserExtensions {
    public static Dictionary<ChromiumWebBrowser, CefSharpSchemeHandlerFactory> dict =
        new Dictionary<ChromiumWebBrowser, CefSharpSchemeHandlerFactory>();
    public static void InitLargeHtml(this ChromiumWebBrowser chromiumWebBrowser) {
        CefSharpSchemeHandlerFactory shf = new CefSharpSchemeHandlerFactory();

        var settings = new CefSettings();
        settings.RegisterScheme(new CefCustomScheme {
            SchemeName = CefSharpSchemeHandlerFactory.SchemeName,
            SchemeHandlerFactory = shf
        });
        Cef.Initialize(settings);
        dict.Add(chromiumWebBrowser, shf);
    }
    public static void LoadLargeHtml(this ChromiumWebBrowser chromiumWebBrowser, string html) {
        if (dict.ContainsKey(chromiumWebBrowser)) {
            CefSharpSchemeHandlerFactory shf = dict[chromiumWebBrowser];
            shf.Html = html;
            chromiumWebBrowser.Load("largehtml://x");
        }
    }
}

//Usages
chromiumWebBrowser.InitLargeHtml();
chromiumWebBrowser.IsBrowserInitializedChanged += delegate (object sender, IsBrowserInitializedChangedEventArgs e) {
    chromiumWebBrowser.LoadHtml(html);
};

```

Thanks for the great CefSharp project!

**Comment by maj-o** [comment]
Thank You for the workaround !  Great work !

**Comment by amaitland** [comment]
The example provided above will throw an exception if you created the ChromiumWebBrowser instance in code as creating a ChromiumWebBrowser instance in code will Initialize CEF if you haven't already. As detailed in https://github.com/cefsharp/CefSharp/wiki/General-Usage#initialize-and-shutdown

The link I provided above has many sections,  admittedly the markdown header styling doesn't quite make that super clear.

https://github.com/cefsharp/CefSharp/wiki/General-Usage#loading-htmlcssjavascriptetc-from-diskdatabaseembedded-resourcestream

There are three other extension methods you can use, the first being the simplest. The subtle difference being a ResourceHandler is used to fulfill the request if you provide a URL.
http://cefsharp.github.io/api/75.1.x/html/M_CefSharp_WebBrowserExtensions_LoadHtml_2.htm
http://cefsharp.github.io/api/75.1.x/html/M_CefSharp_WebBrowserExtensions_RegisterResourceHandler.htm
http://cefsharp.github.io/api/75.1.x/html/M_CefSharp_WebBrowserExtensions_UnRegisterResourceHandler.htm

**Comment by maj-o** [comment]
@amaitland: Thank You also.

RegisterResource is a bit strange to use with changing content. But works also and seems to be faster - GREAT !!

Here is my implementation, where browser is a CefSharp.WinForms.ChromiumWebBrowser

~~~~csharp
const string resourcename = "http://mypage.html";

...

void load(string html) {
    System.IO.MemoryStream memorystream = new System.IO.MemoryStream(System.Text.Encoding.UTF8.GetBytes(html));
    browser.RegisterResourceHandler(resourcename, memorystream);
    browser.Load(resourcename);
    browser.UnRegisterResourceHandler(resourcename);
}
~~~~

LoadHtml does not work for content > 2k. This is why this bug is reported. So we have two working workarounds. I would suggest to obsolete LoadHtml as long as it does not work or to make it work for instance using one of this two working workarounds.

**Comment by amaitland** [comment]
@maj-o Please read my previous comment again, the LoadHtml method I linked to uses RegisterResourceHandler. Both LoadHtml and RegisterResourceHandler have a oneTimeUse parameter as detailed in the API doc. There are four overloads of LoadHtml currently you can view them all at http://cefsharp.github.io/api/75.1.x/html/Overload_CefSharp_WebBrowserExtensions_LoadHtml.htm the sourceis available should you wish to review it.

Deprecating the data uri based LoadHtml makes no sense, it's used by lots of people successfully.

**Comment by Starrlightz** [comment]
How can you make @SongPing 's implementation work for multiple browsers

**Comment by thbiela** [comment]
Unfortunately, the fixes from @maj-o and @SongPing don't work in my application. I have updated cefsharp from 73.1.130 to 75.1.141 and the LoadHtml Method stopped working. The screen stays white (WPF).

I have created a user control and in my constructor I run this code

```cs
            Content = Chromium = new ChromiumWebBrowser() {
                Address = "about:blank",
                MenuHandler = new CustomMenuHandler(),
                RequestContext = new RequestContext(new RequestContextSettings { }),
            };

            Chromium.IsBrowserInitializedChanged += async (sender, e) => {
                await Task.Delay(1000);
                // Chromium.WebBrowser.Load("https://google.de"); // works!
                Chromium.LoadHtml("<h1>Test</h1>", "http://local"); // does not work since 75.1.141
            };
```
I initialize CefSharp in App.xaml with the following code:

 ```cs
           // Assigning file paths to variables
            var dir = Environment.Is64BitProcess ? "x64" : "x86";
            var lib = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"resources\" + dir + @"\libcef.dll");
            var browser = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"resources\" + dir + @"\CefSharp.BrowserSubprocess.exe");
            var locales = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"resources\" + dir + @"\locales\");
            var res = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"resources\" + dir);

            var settings = new CefSettings {
                BrowserSubprocessPath = browser,
                LocalesDirPath = locales,
                ResourcesDirPath = res,
                LogSeverity = LogSeverity.Disable,
                CachePath = Caching.cachepath + "cef-cache"
            };
            settings.CefCommandLineArgs.Add("allow-running-insecure-content", "1");
            settings.SetOffScreenRenderingBestPerformanceArgs();
            settings.CefCommandLineArgs.Add("disable-direct-write", "1");
            var libraryLoader = new CefLibraryHandle(lib);
            Console.WriteLine(dir + $" Library is valid: {!libraryLoader.IsInvalid}");
            Cef.Initialize(settings, performDependencyCheck: false, browserProcessHandler: null);

```
Any help is appreciated.

**Comment by amaitland** [comment]
> Unfortunately, the fixes from @maj-o and @SongPing don't work in my application. I have updated cefsharp from 73.1.130 to 75.1.141 and the LoadHtml Method stopped working. The screen stays white (WPF).

@thbiela This particular issue represents a problem with attempting to Load a large html string as a data uri. Whilst your code calls `LoadHtml`, it is unrelated to this issue. The problem you are seeing is likely an actual bug, please create a new issue making sure to use the [Bug Report](https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). You can skip the testing with `Does this problem also occur in the CEF Sample Application` section in this case.

**Comment by thbiela** [comment]
@amaitland thanks for your reply. I fixed my problem by converting the html string into a base64 string.

```cs
var base64EncodedHtml = Convert.ToBase64String(Encoding.UTF8.GetBytes(html));
Chromium.Load("data:text/html;base64," + base64EncodedHtml);
```

It works even with large HTML.

**Comment by amaitland** [comment]
> I fixed my problem by converting the html string into a base64 string.

@thbiela As I linked previously there are 4 overloads for `LoadHtml` see http://cefsharp.github.io/api/75.1.x/html/Overload_CefSharp_WebBrowserExtensions_LoadHtml.htm

Specifically call [LoadHtml(this IWebBrowser browser, string html, bool base64Encode = false)](http://cefsharp.github.io/api/75.1.x/html/M_CefSharp_WebBrowserExtensions_LoadHtml_1.htm) and `base64Encode:true`.

Anyone else, please please read the links I've provided before commenting.

**Comment by amaitland** [comment]
> The problem you are seeing is likely an actual bug, please create a new issue

@thbiela I've created #2872 to track the issue you have reported. There is a workaround listed there.
