### ISSUE TITLE
PDF named destinations

### ISSUE THREAD

**Issue by Andi1982** [cefsharp/CefSharp#2790]
PDF named destinations are not working in the pdf viewer.

TestUrl1: http://greenbytes.de/tech/webdav/rfc2616.pdf#GET
TestUrl2: https://greenbytes.de/tech/webdav/rfc2616.pdf#nameddest=GET

What steps will reproduce the problem?
Navigate to URI´s above.

What is the expected result?
Should navigate to section about "GET"

What happens instead?
It does not.

**Comment by amaitland** [comment]
It's important to note that `CefSharp` is just a wrapper around the `Chromium Embedded Framework (CEF)`. Closing this as `upstream` and as changes need to be made in `CEF`. 

The `CEF` project has it's own issue tracker located at https://bitbucket.org/chromiumembedded/cef it is recommended you ask on https://magpcss.org/ceforum/index.php before opening an issue on the CEF issue tracker. The behavior you are seeing may be the expected default.

Before opening a new issue you should:

- Search open/closed issues to determine if the problem you are seeing has already been reported
- Test with a newer version if available, see https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-chromium-embedded-frameworkcef for details on testing with the `cefclient` reference application.

If you do find an existing issue that matches this one or create a new one then post a link here for others to follow.
