### ISSUE TITLE
OffScreen Chinese Input

### ISSUE THREAD

**Issue by bolindou** [cefsharp/CefSharp#2791]
What version of the product are you using?
Nuget 73.1.130

What architecture x86 or x64?
x64

On what operating system?
Win10

Are you using WinForms, WPF or OffScreen?
OffScreen

What steps will reproduce the problem?
Focus on text editor box, can not change to chinese ime. Press on keyboard, can only input numbers or alphabet, but not chinese text.

What is the expected output? What do you see instead?
can input chinese text with chinese  ime

Please provide any additional information below.
N/A

Does this problem also occur in the CEF Sample Application from 
N/A

**Comment by bolindou** [comment]
I had only called "IBrowserHost.SendKeyEvent()" in my codes to deal keyboard event. Is it right to do it ?  Have any example to deal text inputing with offscreen?

**Comment by nocanstillbb** [comment]
> 我在代码中只调用了“IBrowserHost.SendKeyEvent（）”来处理键盘事件。这样做是对的吗？有任何例子来处理文本输入与屏幕外？

我想知道你是否已经修复此问题,我目前使用的方式十分丑陋但真实有效.

**Comment by bolindou** [comment]
@nocanstillbb 此问题没有直接解决，目前采用的是通过外部控制输入文本再传递到Browser中的方案。你的“真是有效”的具体做法是？

**Comment by nocanstillbb** [comment]
> @nocanstillbb 此问题没有直接解决，目前采用的是通过外部控制输入文本再传递到Browser中的方案。你的“真是有效”的具体做法是？

on  got Key board Focus use uiDispatch.invoke do:
show a window which top = -9999 , left = -9999, width =1,hight=1
and hidden it .

**Comment by bolindou** [comment]
inexplicable
