### ISSUE TITLE
Async JavaScript Binding - Long running method response incorrectly resolves promise after navigation 

### ISSUE THREAD

**Issue by selmernoid** [cefsharp/CefSharp#2792]
### Bug Report
Delete this line and everything above, and then fill in the details below.

- **What version of the product are you using?**
    - What version are you using? Nuget? CI Nuget? build from a branch? If so which branch? Nuget: 71.0.0 & 73.1.130. at least those versions
- ** Architecture **
    - x64
- **Operating system**
    - Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - WinForms
- **What steps will reproduce the problem?**
    - Here are 2 pages with boundAsync bindings
    - Each of them makes a different request at the beginning:
            -   boundAsync.method1().then(result => console.log("1: " + result));
            -   boundAsync.method2().then(result => console.log("2: " + result));
    - The method1 executed in async way and require a long time to evaluate a result
    - So now, we load the page 1 which execute method1.
    - Immediately (a response from method1 was not processed) go to page 2 which execute method2

- **What is the expected output? What do you see instead?**
    - page 2 in method2 handler processed with a response for method2 from .NET
Instead of this:
    - page 2 in method2 handler processed a response from previous page for method1
- **Please provide any additional information below.**
    - A .NET methods will be executed one by one with correct results, but in reason, that previous handler has removed a response will be processed by incorrect handler on front-end.

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
    - No, there is the only information about incorrect response parsing.

**Comment by amaitland** [comment]
As requested in the bug report template please provide an example that reproduces the problem,  it is not sufficient to roughly describe the problem.

**Comment by selmernoid** [comment]
Please, overview this example https://github.com/selmernoid/CefSharp.MinimalExample

To reproduce correct behavior:
- Press button "Go to 2"
- Wait the result (5 seconds delay)
- Press button "Go to 1"
- See that all is good: 1st page get response from 1st method and 2nd page from 2nd method.

Now, try to see the bug:
- Press button "Go to 2"
- Don't wait 5 seconds and fast press the button "Go to 1"
- See that 1st page display a response for 2nd page.

**Comment by amaitland** [comment]
Please remove CefSharpSettings.LegacyJavascriptBindingEnabled and register your object with the JavaScript object repository directly.  You aren't using Legacy JavaScript Binding,  it shouldn't be enabled.

**Comment by selmernoid** [comment]
@amaitland, It's done. The changes were pushed. 
The bug still reproducing.

**Comment by amaitland** [comment]
Thanks for confirming,  in theory I understand the problem,  will need to run some tests to confirm. Thanks for the example.

**Comment by amaitland** [comment]
The simplest solution is to make `_lastCallback` static so the `Id` is unique to the process, it's an `int64` so it's sufficiently large that we won't run out of Id's anytime soon.

https://github.com/cefsharp/CefSharp/blob/cefsharp/73/CefSharp.BrowserSubprocess.Core/JavascriptRootObjectWrapper.h#L30

Should also double check the message that's sent from the original callback is safely ignored. Ideally we wouldn't send the message, that might be possible once we upgrade to a version of `CEF` that includes https://bitbucket.org/chromiumembedded/cef/commits/241941a44a260885f6455e5618189c45ffb0ed40 Hopefully the frame Id's will be unique (they're not currently, Frame Id only increments for the main frame when there is a process switch).

Assigned this to the `75` milestone.

**Comment by amaitland** [comment]
Fixed in https://github.com/cefsharp/CefSharp/commit/7da18cae4c55f2d68d67b88be67abda55760c06e

Still should run some final tests before closing.

**Comment by amaitland** [comment]
Additional checks for frame validity added in https://github.com/cefsharp/CefSharp/commit/9766360de7a54e1ee95b537645e6831d849515f5

That should be the last piece in resolving this issue.
