### ISSUE TITLE
Assembly references listed as invalid after installing CefSharp.WPF

### ISSUE THREAD

**Issue by lauxjpn** [cefsharp/CefSharp#2793]
**Steps to reproduce:**
1. Create a new Wpf App project in Visual Studio.
2. Add CefSharp.WPF from nuget to the project.
3. Notice that no references appear to be added.
4. Reload the project.
5. Notice that all references (also the default System references) are being invalid.

**Issue:**
It appears that the following two lines are being added twice in the project file (at the beginning and at the end):
``` xml
<Import Project="..\packages\CefSharp.Common.73.1.130\build\CefSharp.Common.targets" Condition="Exists('..\packages\CefSharp.Common.73.1.130\build\CefSharp.Common.targets')" />
<Import Project="..\packages\CefSharp.Wpf.73.1.130\build\CefSharp.Wpf.targets" Condition="Exists('..\packages\CefSharp.Wpf.73.1.130\build\CefSharp.Wpf.targets')" />
```
Removing the two redundant instances at the end of the project file loads the references correctly again.

But even after that, there are no x86 and x64 folders in the executable folder and therefore the necessary assemblies to load CefSharp cannot be resolved at runtime.
Interestingly, I could not get this to work with any of the 6x versions either. Maybe an incompatibility with the current VS version?

Visual Studio 15.9.12

**Comment by amaitland** [comment]
There are .targets and .props files, removing the targets files and no files will be copied.

It's not clear you've followed the post installation steps listed at https://github.com/cefsharp/CefSharp/blob/cefsharp/73/NuGet/Readme.txt#L10 confirm which architecture you are targeting,  if you are using AnyCpu make sure you follow the exact instructions. 

Also please confirm if you are using packages.config or PackageReference.

**Comment by amaitland** [comment]
There are working examples provided at https://github.com/cefsharp/CefSharp.MinimalExample there are branches that demo AnyCpu.  After you restore the Nuget packages it's likely you will have to close and reopen the solution (only required for VS2017 and above)

**Comment by amaitland** [comment]
Next time please use the bug report template provided at https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report

**Comment by amaitland** [comment]
There is at least one regression in `VS2017` that effects `CefSharp`, see https://github.com/dotnet/project-system/issues/4158

**Comment by lauxjpn** [comment]
My mistake. I followed the AnyCPU instructions from https://github.com/cefsharp/CefSharp/issues/1714
I went straight to Option 3, but did not apply the second paragraph of the introduction:

> You must add ```<CefSharpAnyCpuSupport>true</CefSharpAnyCpuSupport>``` to the first ```<PropertyGroup>``` in your project (e.g. .csproj file) and pick one of the two options below.

It works fine after following the guidelines in full.
