### ISSUE TITLE
WPF runs out of memory on the 3200 x 2400 screen after opening several browsers

### ISSUE THREAD

**Issue by lidongguo** [cefsharp/CefSharp#2797]
Issue Summary
I use WPF version 73. Net4.6, open multiple browser forms at the same time, size 3400*2400 form after memory overflow
Technical details

CefSharp Version: 73
Operating System: windows10
x86:
WPF

**Comment by amaitland** [comment]
Please use the template provided at https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report

Please include the full stack trace (not an image of the exception, copy the exception details to clipboard).

Personally I don't have access to a monitor capable of that resolution,  so this is not something I personally will be looking into. The source is there, and pull requests with improvements are welcome. 

Using the WinForms versions hosted in WPF will likely be your best best at a workaround.
