### ISSUE TITLE
Memory leak when using EvaluateScriptAsync

### ISSUE THREAD

**Issue by fiantsev** [cefsharp/CefSharp#2798]
- **What version of the product are you using?**
74.1.13

- **What architecture x86 or x64?**
x86 and x64

- **On what operating system?**
    Win 10.0.17134 Build 17134

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms

- **What steps will reproduce the problem?**
1. git clone forked version https://github.com/fiantsev/CefSharp
2. switch to branch bug/memory-leaks
3. run project CefSharp.WinForms.Example
4. open windows Task Manager and watch at CefSharp.BrowserSubprocess.exe Memory usage

   

- **What is the expected output? What do you see instead?**
expected: CefSharp.BrowserSubprocess should not grow more than some limit of memory
actual: memory is never released - when i leave my app running over weekends - it have eaten 5gb

- **Please provide any additional information below.**
I have an app that polling browser every 50ms by executing EvaluateScriptAsync. For me, it looks like: EvaluateScriptAsync has some problem with GC'ing resources.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
i dont use `CEF` Sample Application

**Comment by amaitland** [comment]
Run your script every 500ms and see if you get a different result,  every 50ms doesn't give the v8 garbage collector much time to run, if any.

Open Devtools and look at the memory profile,  if you see the memory growing there then this isn't a bug in CefSharp. It is very rare that this sort of issue is actually a bug in CefSharp.  Remember it's just a wrapper,  which is why we ask you to test with the CEF sample application.

**Comment by fiantsev** [comment]
@amaitland 

confirm that 500ms solve the problem somehow.

but what i can do if my use case is < 50ms - how to handle this particular situation - do you know any way to limit mem usage or force garbage collection at specific time?

**Comment by amaitland** [comment]
> do you know any way to limit mem usage or force garbage collection at specific time?

You can probably just pause execution every so often to allow for the `GC` to run. Every `10000` iterations pause for a few hundred `milliseconds` etc.

I've not seen any way to force `GC`, do your own research though, see if you can find something that I'm not aware of.

**Comment by amaitland** [comment]
> I've not seen any way to force `GC`, do your own research though, see if you can find something that I'm not aware of.

Someone kindly reminded me there is `window.gc()`, though I'd rule it out as last I tried it wasn't working, reports are that it is now though I've not tested. You have to explicitly enable it.

Set `--expose-gc` using
http://cefsharp.github.io/api/73.1.x/html/P_CefSharp_AbstractCefSettings_JavascriptFlags.htm or alternatively directly through using the `--js-flags="--expose-gc"` command line arg.

Again, I've not tested this and you'll have to experiment do your own research to see if this works/helps in your use case.

**Comment by fiantsev** [comment]
i have tried window.gc() - it didn't help me. Memory leak is outside of JS domain, as i see.
Thank you for the help - i will try pause execution
