### ISSUE TITLE
large memory leaks on WPF with 73.1.130 x64

### ISSUE THREAD

**Issue by yt2100** [cefsharp/CefSharp#2802]
- **What version of the product are you using?**
CefSharp-73.1.130

- **What architecture x86 or x64?**
x64

- **On what operating system?**
Win10 x64

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms, WPF, OffScreen

- **What steps will reproduce the problem?**

i was clone https://github.com/cefsharp/CefSharp.MinimalExample.git
on my local disk, nuget install all package. build it and run.
i use https://www.vsynctester.com/ for test.

when i use CefSharp.MinimalExample.Wpf.exe open, the menory growth quickly;
i use JetBrains.dotTrace to see what happen.
i found much ummanaged memory growth quickly;
and i found The same probleme with CefSharp.MinimalExample.OffScreen.exe
![Image of wpf](https://raw.githubusercontent.com/yt2100/tool/master/wpf.jpg)

But, when i test CefSharp.MinimalExample.WinForms.exe
The ummanaged memory is normal.
![Image of winform](https://raw.githubusercontent.com/yt2100/tool/master/winform.jpg)

so, i thank There may be different differences in the 3 projects.
Can the official fix it?

**Comment by yt2100** [comment]
After repeated testing,
Especially the page contains video playback or js animation.
The wpf and offscreen versions have grown rapidly, I have tried to grow to nearly 20gb in 8 minutes.
The same version of cefclient.exe and winform are normal.
Is it related to their respective ChromiumWebBrowser.cs?

**Comment by amaitland** [comment]
You must test cefclient with the command line arguments listed in https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

This sounds like a problem with CEF.

**Comment by yt2100** [comment]
it's too sad
i use "cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu" to test some cef version.
cef_binary_73.1.3+g46cf800+chromium-73.0.3683.75
cef_binary_73.1.5+g4a68f1d+chromium-73.0.3683.75
cef_binary_73.1.11+ge6986dc+chromium-73.0.3683.75
cef_binary_73.1.12+gee4b49f+chromium-73.0.3683.75
cef_binary_73.1.13+g6e3c989+chromium-73.0.3683.75
cef_binary_74.1.13+g98f22d3+chromium-74.0.3729.108
cef_binary_74.1.14+g50c3c5c+chromium-74.0.3729.131
cef_binary_74.1.16+ge20b240+chromium-74.0.3729.131
cef_binary_74.1.19+gb62bacf+chromium-74.0.3729.157
These versions have the same problem, it looks like cef bugs.

**Comment by amaitland** [comment]
Try using the `--disable-gpu-compositing` command line arg and test with `cefclient` again.

**Comment by yt2100** [comment]
It is very useful!
I tried these cef versions, their cefclinet.exe memory is normal.

**Comment by amaitland** [comment]
It's probably still worth raising an issue at https://bitbucket.org/chromiumembedded/cef/issues/new so that someone looks into the problem.

If you do then please post a link back here.
