### ISSUE TITLE
WPF - Reassign Browser to new Parent Crashes application

### ISSUE THREAD

**Issue by oysteingl** [cefsharp/CefSharp#2803]
- **What version of the product are you using?**
  "CefSharp.Wpf" version="73.1.130"

- **What architecture x86 or x64?**
x64

- **On what operating system?**
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
Wpf
- **What steps will reproduce the problem?**
Minimal example provided here: https://github.com/oysteingl/CefSharp.MinimalExample
In my example, I have created a user control that just contains a ChromiumWebBrowser control, and in the main window, it works just fine. What I want to achieve is to move the browser window from the main window to a new window. 
Clicking the "Open in new window" button will immediately crash the application without any exception or other information.

- **What is the expected output? What do you see instead?**
I expect to see the browser opened in a new window, instead the app crashes.

- **Please provide any additional information below.**
   No stack trace. Debug.log is empty

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
No

**Comment by oysteingl** [comment]
Found a workaround: https://github.com/oysteingl/CefSharp.MinimalExample/tree/workaround
Adding a hidden button next to the ChromiumWebBrowser prevented the crash 🤣 
I hope there is a more elegant solution, as adding hidden buttons to my user controls feels quite hacky.

**Comment by amaitland** [comment]
Removing the control then adding it to a new parent is working for me. This is the workflow that I would be expecting, `Remove` then `Add`, not `Add` then `Remove` 

```c#
BrowserWindow.Parent.RemoveChild(BrowserWindow);

var window = new Window { Content = BrowserWindow };

window.Show();
```

**Comment by oysteingl** [comment]
I tried the exact same code as you, and it worked one time, but when I ran the project again, the crash happened again, and it crashed on every run after that. With the workaround it works everytime.

**Comment by amaitland** [comment]
It works every time for me, I've run it multiple times. Please test again using the exact code I posted, thanks.

**Comment by oysteingl** [comment]
Sorry, I missed that you were setting the content to BrowserWindow, not BrowserWindow.Content. Now it works everytime here as well. Thanks!

**Comment by amaitland** [comment]
Great, thanks for confirming 👍
