### ISSUE TITLE
How to enforce TSL1.2 on CefSharp?

### ISSUE THREAD

**Issue by ervishal89** [cefsharp/CefSharp#2805]
Hi Guys,

I am wondering how we can enforce TSL1.2 on CefSharp for WPF? Is there any settings available?

TIA!

**Comment by amaitland** [comment]
Start with https://bitbucket.org/chromiumembedded/cef/issues/2451/tls-min-and-max-version-command-line

**Comment by amaitland** [comment]
Additional it suggests that it won't be supported until https://bitbucket.org/chromiumembedded/cef/issues/2622/implement-support-for-networkservice is resolved for which you can track the `CefSharp` adaptation of those changes as part of #2743
