### ISSUE TITLE
Feature Request - Add IAudioHandler Example

### ISSUE THREAD

**Issue by yt2100** [cefsharp/CefSharp#2806]
**Describe the solution you'd like**
Can Add AudioHandler Sample?

**Describe alternatives you've considered**

**Additional context**
i create AudioHandler implement IAudioHandler,

on IAudioHandler.OnAudioStreamStarted
i found channels:2 channelLayout:LayoutStereo sampleRate:48000 framesPerBuffer:960
and make vars:
this.BufferSize = 4 * framesPerBuffer * channels;
this.Buffer = new byte[BufferSize];

on IAudioHandler.OnAudioStreamPacket
the comment tips: <param name="data">is an array representing the raw PCM data as a floating point type, i.e. 4-byte value(s)</param>
so i use code copy data:
lock (Lock){ Marshal.Copy(data, Buffer, 0, BufferSize); }
and write stream to file.

it's wrong, the data not pcm; becuse i use texteditor see the file;
i see some ascii word, like url, namespace; 
maybe i read IntPtr data is not ok?
so please, can official to write a correct AudioHandler implementation.

**Checklist:**
i was search with keyword "AudioHandler" in google,  it's less msg.
and i see on cef forum, the same less msg.

**Comment by amaitland** [comment]
> so please, can official to write a correct AudioHandler implementation.

No, sorry. Your welcome to contribute one if you work it out. I've not used the `API` and no example was provided in the actual `Unit Tests` provided by `CEF`.

https://bitbucket.org/chromiumembedded/cef/commits/9f41a27e586a6b557fc171d2f03b332c1338e8d2?at=3683 has all the information that I have on the subject.

> and i see on cef forum, the same less msg.

You can ask on https://magpcss.org/ceforum/index.php post a link back here if you do. That is your best option.

**Comment by amaitland** [comment]
For reference there is an `upstream` bug that will potentially crash when using the `Audio Handler`, see https://bitbucket.org/chromiumembedded/cef/issues/2713/crash-triggered-by

Someone else asked for an example on `ceforum`, see https://magpcss.org/ceforum/viewtopic.php?f=10&t=16798#p41953
There's no response as yet.

**Comment by amaitland** [comment]
Potentially also relevant see https://magpcss.org/ceforum/viewtopic.php?f=10&t=16803

**Comment by amaitland** [comment]
`CEF` has removed audio mirroring support, there is an open issue to re-implement it see https://bitbucket.org/chromiumembedded/cef/issues/2755/reimplement-audio-mirroring-for

If it's ever re-added we can reopen this.

**Comment by amaitland** [comment]
Support has been re-added (https://github.com/cefsharp/CefSharp/issues/3152) and will be available in version `85`.

If anyone has the time to contribute an example (possibly using `NAudio`) then that would be greatly appreciated.

**Comment by amaitland** [comment]
For future reference

https://bitbucket.org/chromiumembedded/cef/commits/04d461e032dfe36d0252a95b6c3d76f7272f54e2#Llibcef/browser/audio_capturer.ccT108

The `data` param is `IntPtr` which represents the following:
```
const float** data
```

**Comment by Scalibq** [comment]
The IAudioHandler interface for OnAudioStreamPacket() confused me a bit as well.
For others who want to use it, the IntPtr data parameter is indeed a float** type.
So it is an array of float arrays (basically: float[nrOfChannels]*).
The sample data is stored linearly per channel. So each array represents one channel.
The way you can use it with eg NAudio, which expects the samples interleaved, and floats packed into a byte-array is like this:
`                unsafe
                {
                    float** channelData = (float**)data.ToPointer();
                    int size = _channels * noOfFrames * 4;
                    byte[] samples = new byte[size];
                    fixed (byte* pDestByte = samples)
                    {
                        float* pDest = (float*)pDestByte;

                        for (int i = 0; i < noOfFrames; i++)
                            for (int c = 0; c < _channels; c++)
                                *pDest++ = channelData[c][i];
                    }
                }`

Hopefully that makes it clear how people can use the audio interface.

One thing that may make it easier to use though, is if IAudioRenderer would also implement IDisposable, like IRenderHandler does.
The Disposable interface makes it easier to handle deinitialization of audio once the browser is closed.

**Comment by amaitland** [comment]
`IAudioHandler` now implements `IDisposable` (issue #3598), will be included in the `91` release. This is a breaking change, everyone `IAudioHandler` implementation will have to implement `IDisposable`. 

If someone has time to submit a `PR` that includes an example that would be greatly appreciated.

**Comment by ValentinNikin** [comment]
Hello. I created PR to update AudioHandler example. Example of @Scalibq very helpfull for me, and I think it's maybe helpfull for other users, so I integrated him code to AudioHandler example.

**Comment by amaitland** [comment]
Thanks to @Scalibq and @ValentinNikin 

Example was added in #3724
