### ISSUE TITLE
HTML5 audio/video not seekable

### ISSUE THREAD

**Issue by vlasgeorge** [cefsharp/CefSharp#2807]
I am using Nuget cef.redist.x64 73.1.13.

Architecture: x86

Operating System: Win7, Win 8, Win 10 

I am using WPF.

I have built a WPF app that uses the CeFSharp.WPF browser in conjuction with an internal server (localhost) which is part of the app. The problem is that HTML5 audio/video is not seekable. Specifically when I click on the thumb either on the video player or the audio player of the browser and drag it nothing happens. Video and audio plays as it should but is just not seekable.

Using CefClient with the same version as my CeFSharp.WPF browser in conjuction with xampp the problem does not occur.

There is a relevant issue here:
https://bitbucket.org/chromiumembedded/cef/issues/1742/html5-audio-video-not-seekable-using
but I'm not sure if it's the same as I'm facing

**Comment by amaitland** [comment]
What command line args did you use for testing cefclient? 

In future please use the bug report template provided at https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report

**Comment by amaitland** [comment]
Using https://github.com/cefsharp/CefSharp.MinimalExample I can seek `youtube` videos no problem.

**Comment by vlasgeorge** [comment]
Yes I know that. I didn't use any line args. I built CEF following these instructions:
https://bitbucket.org/chromiumembedded/cef/wiki/MasterBuildQuickStart.md#markdown-header-windows-setup. and used CefClient from that build.
Maybe it has something to do with the internal server that I'm using Because when I'm running my app in conjuction with xampp (instead of localost) the videos are seekable. But when I am using the default WPF WebBrowser, instead of CeFSharp.WPF browser,  and the localhost in my app then they are seekable.

**Comment by amaitland** [comment]
> I didn't use any line args

As per the issue template you must test with a specific set of command line arguments, I've listed them below. `cefclient` that matches the `CefSharp` build for `73.1.130` can be downloaded from http://opensource.spotify.com/cefbuilds/cef_binary_73.1.13%2Bg6e3c989%2Bchromium-73.0.3683.75_windows32_client.tar.bz2

> To compare with WPF run cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu

https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report

**Comment by vlasgeorge** [comment]
Ok so I did just that. I ran cefclient from the above link with the specific set of command line arguments using my server this time and the problem persists. For clarification the app is used only to display ePub content which is stored locally and that contnet is served through the internal server.
On the other hand I will say again that video/audio seek capability works if I use the default WPF browser in my app instead of the CeFSharp.WPF browser.,

**Comment by amaitland** [comment]
> I ran cefclient from the above link with the specific set of command line arguments using my server this time and the problem persists

Closing as `upstream` as the issue needs to be fixed in `CEF`. Sounds like you've already tracked down the relevant issue. You can ask on https://magpcss.org/ceforum/index.php for clarification (post a link back here if you do).

**Comment by vlasgeorge** [comment]
I have reported the issue at https://bitbucket.org/chromiumembedded/cef/overview and they answered: Bugs that reproduce with Google Chrome should be found/filed at https://crbug.com.

I reported the issue there as well:
https://bugs.chromium.org/p/chromium/issues/detail?id=973357
