### ISSUE TITLE
Can not Input Chinese Char with OffScreen

### ISSUE THREAD

**Issue by bolindou** [cefsharp/CefSharp#2808]
- **What version of the product are you using?**
   Nuget 73.1.130
- **What architecture x86 or x64?**
   x64
- **On what operating system?**
   Win10
- **Are you using `WinForms`, `WPF` or `OffScreen`?**
   OffScreen
- **What steps will reproduce the problem?**
    PreFilterMessage（ref Message m）
    {
        switch(m.Msg)
        {
              case WM_KEYDOWN:
              case WM_KEYUP:
              case WM_CHAR:
              case WM_SYKEYDOWN:
              case WM_SYSKEYUP:
              case WM_IME_CHAR:
              case WM_IME_KYEDOWN:
              case WM_IME_KEYUP:
              case WM_SYSCHAR:
                      Browser.GetBrowser().GetHost().SendKeyEvent(m.Msg,(int)m.WParam.ToInt64(),(int)m.LParam.ToInt64());
        }
     }
- **What is the expected output? What do you see instead?**
      Input Chinese String
- **Please provide any additional information below.**
      IME can not change

**Comment by amaitland** [comment]
IME is not supported using that particular SendKey overload and there are no plans to add it as the method will at some point be removed. 

https://github.com/cefsharp/CefSharp/blob/cefsharp/73/CefSharp.Core/Internals/CefBrowserHostWrapper.cpp#L268

You must use http://cefsharp.github.io/api/73.1.x/html/M_CefSharp_IBrowserHost_SendKeyEvent.htm instead. 

Please stop opening issues asking for help implementing IME using OffScreen,  it as stated previously has no direct user input, it's up to you to implement.
