### ISSUE TITLE
Change flash player quality not working

### ISSUE THREAD

**Issue by hiagocmendes** [cefsharp/CefSharp#2810]
This bug is very simple to understand.
If you click on the flash object and select "Quality" and try to switch to "low", the flash object will not change the quality.

**This problem started after version 41.x**

Example: http://prntscr.com/o1decr

**Comment by amaitland** [comment]
It's important to note that `CefSharp` is just a wrapper around the `Chromium Embedded Framework (CEF)`. Closing this as `upstream` and as changes need to be made in `CEF`. 

The `CEF` project has it's own issue tracker located at https://bitbucket.org/chromiumembedded/cef it is recommended you ask on https://magpcss.org/ceforum/index.php before opening an issue on the CEF issue tracker. The behavior you are seeing may be the expected default.

Before opening a new issue you should:

- Search open/closed issues to determine if the problem you are seeing has already been reported
- Test with a newer version if available, see https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-chromium-embedded-frameworkcef for details on testing with the `cefclient` reference application.

If you do find an existing issue that matches this one or create a new one then post a link here for others to follow.
