### ISSUE TITLE
WPF Glitchy Rendering

### ISSUE THREAD

**Issue by AlaaAlHallaq** [cefsharp/CefSharp#2811]
Using CefSharp.WPF.Example to open web page with transparent background result in 2 things
1. Glitchy rendering.
2. Slow Scrolling.

please try opening the html 5 video test page from wpf sample: 
https://tekeye.uk/html/html5-video-test-page

Thanks

**Comment by amaitland** [comment]
It's important to note that `CefSharp` is just a wrapper around the `Chromium Embedded Framework (CEF)`. Closing this as `upstream` and as changes need to be made in `CEF`. 

The `CEF` project has it's own issue tracker located at https://bitbucket.org/chromiumembedded/cef it is recommended you ask on https://magpcss.org/ceforum/index.php before opening an issue on the CEF issue tracker. The behavior you are seeing may be the expected default.

Before opening a new issue you should:

- Search open/closed issues to determine if the problem you are seeing has already been reported
- Test with a newer version if available, see https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-chromium-embedded-frameworkcef for details on testing with the `cefclient` reference application.

If you do find an existing issue that matches this one or create a new one then post a link here for others to follow.

**Comment by amaitland** [comment]
The OffScreen rendering engine is being rewritten you can track the progress at https://bitbucket.org/chromiumembedded/cef/issues/2575/viz-implementation-for-osr

**Comment by AlaaAlHallaq** [comment]
@amaitland  The issue is only appearing in CefSharp.WPF & CefSharp.WPF.Exmaple, neither CefSharp.WinForms.Example doen't have this issue, nor CEF samples (CefClient,CefSample).

**Comment by amaitland** [comment]
WinForms uses native rendering,  entirely different. cefsimple doesn't support OffScreen rendering,  so it's not an accurate comparison. 

You didn't use the bug report template provided at https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report No mention of testing performed. No reference to cefclient being tested. As a result you get a saved response. This issue in all likelihood is still going to be a problem with CEF and it's OSR implementation. 

You must test with cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu Making sure to compare the **exact** same version of cefclient. 

If the issue only reproduces with a transparent background then you'll have to factor that into your testing of cefclient.

**Comment by amaitland** [comment]
Testing with http://opensource.spotify.com/cefbuilds/cef_binary_75.0.6%2Bg90ecd35%2Bchromium-75.0.3770.80_windows32_client.tar.bz2 using `cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu ` and I see that scrolling is problematic and there's problems rendering the videos. 

Adding `--disable-gpu-compositing` (as I've suggested in other cases like https://github.com/cefsharp/CefSharp/issues/2802#issuecomment-498933250) and rendering greatly improves.

Best to report the issue on https://bitbucket.org/chromiumembedded/cef

**Comment by ilkayayas** [comment]
Here is the solution I used;

        public App()
        {
            CefSettings settings = new CefSettings();
            settings.SetOffScreenRenderingBestPerformanceArgs();

            Cef.Initialize(settings);
        }

**Comment by kani-rifluxyss** [comment]
This one did NOT work for me, 
```
settings.SetOffScreenRenderingBestPerformanceArgs();
```

 used these 2 lines and it is working!

```
cefSettings.CefCommandLineArgs.Add("disable-gpu", "1");
cefSettings.CefCommandLineArgs.Add("disable-gpu-compositing", "1");
```
