### ISSUE TITLE
Site content is not displayed

### ISSUE THREAD

**Issue by LFDCC** [cefsharp/CefSharp#2813]
```csharp
<WindowsFormsHost>
        <cefSharpWPF:ChromiumWebBrowser x:Name="cefsharp" />
</WindowsFormsHost>
```
This is the code
When I set the property AllowsTransparency to true
It works fine on Windows 10 computers
Other systems, such as Windows 7 WindowsServer2008, do not display it

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
Please ask your question on stackoverflow

**Comment by LFDCC** [comment]
So I wonder if the property AllowTransparency is set to true, doesn't it display?

**Comment by LFDCC** [comment]
> Please ask your question on stackoverflow

So I wonder if the property AllowTransparency is set to true, doesn't it display?

**Comment by amaitland** [comment]
What research did you do before opening this?
What testing did you perform? Which other `WinForms` controls did you test with? Which ones are working?
What makes this `CefSharp` specific?

Last I checked `AllowTransparency` was not supported with `WindowsFormsHost`. Maybe `Microsoft` added some basic support to `Windows 10` specifically, not something I've tested. Best if you ask on **stackoverflow** as you'll get a winder audience, someone might have some insight.

https://stackoverflow.com/questions/4108531/wpf-windowsformshost-is-not-visible-when-allowstransparency-true
https://social.msdn.microsoft.com/Forums/vstudio/en-US/55b9d7f7-8177-4a3c-9fbc-6c7b1608733f/windowsformshost-is-not-visible-allowstransparencytrue?forum=wpf
https://social.msdn.microsoft.com/Forums/azure/en-US/41088e8f-800d-4a29-a693-d9edf1682c0f/c-wpf-winforms-web-browser-styling?forum=wpf
https://www.neowin.net/forum/topic/646970-c-wpf-window-with-transparency-makes-windowsformshost-disappear/

**Comment by LFDCC** [comment]
> What research did you do before opening this?
> What testing did you perform? Which other `WinForms` controls did you test with? Which ones are working?
> What makes this `CefSharp` specific?
> 
> Last I checked `AllowTransparency` was not supported with `WindowsFormsHost`. Maybe `Microsoft` added some basic support to `Windows 10` specifically, not something I've tested. Best if you ask on **stackoverflow** as you'll get a winder audience, someone might have some insight.
> 
> https://stackoverflow.com/questions/4108531/wpf-windowsformshost-is-not-visible-when-allowstransparency-true
> https://social.msdn.microsoft.com/Forums/vstudio/en-US/55b9d7f7-8177-4a3c-9fbc-6c7b1608733f/windowsformshost-is-not-visible-allowstransparencytrue?forum=wpf
> https://social.msdn.microsoft.com/Forums/azure/en-US/41088e8f-800d-4a29-a693-d9edf1682c0f/c-wpf-winforms-web-browser-styling?forum=wpf
> https://www.neowin.net/forum/topic/646970-c-wpf-window-with-transparency-makes-windowsformshost-disappear/

I tried using Wpf's cefsharp and set AllowTransparency to true, which allows displaying web content, but some html5 properties such as canvas drawing will be delayed. Is there any solution?

**Comment by LFDCC** [comment]
```csharp
<UserControl x:Class="WpfHost.View.Browser.CefWebBowser"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:cefSharpWPF="clr-namespace:CefSharp.Wpf;assembly=CefSharp.Wpf"
             mc:Ignorable="d"
             d:DesignHeight="450" d:DesignWidth="800">
    <cefSharpWPF:ChromiumWebBrowser x:Name="cefsharp" />
</UserControl>
```

**Comment by amaitland** [comment]
You can try the `--disable-gpu-compositing` command line argument. #2770 will need to be implemented to greatly improve the performance.

https://github.com/cefsharp/CefSharp/blob/fe98124c9be900a80472cdacd0eab537ab452022/CefSharp.Example/CefExample.cs#L94

Further questions ask them on `Gitter` or `Stackoverflow` please.

**Comment by LFDCC** [comment]
> You can try the `--disable-gpu-compositing` command line argument. #2770 will need to be implemented to greatly improve the performance.
> 
> https://github.com/cefsharp/CefSharp/blob/fe98124c9be900a80472cdacd0eab537ab452022/CefSharp.Example/CefExample.cs#L94
> 
> Further questions ask them on `Gitter` or `Stackoverflow` please.

Thank you very much. Problem solved
