### ISSUE TITLE
Got a error and my wpf system crash exit. Please help me!

### ISSUE THREAD

**Issue by chenfield** [cefsharp/CefSharp#2818]
[0626/170919.670:INFO:SkBitmap.h(515)] ../..\third_party/skia/include/core/SkBitmap.h(515): fatal error: "assert(this->tryAllocPixels(info, rowBytes))"

**Comment by ErikLeeOlson** [comment]
I'm having this issue too, after updating to version 73

**Comment by ErikLeeOlson** [comment]
This is the fix: https://stackoverflow.com/questions/2597790/can-i-set-largeaddressaware-from-within-visual-studio

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/wiki/General-Usage#win32-out-of-memory
