### ISSUE TITLE
Application quit without indication of a problem, excpetion 0x4000001f in libcef.dll 

### ISSUE THREAD

**Issue by FionaYuanWei** [cefsharp/CefSharp#2823]
We have a WPF ThinUI application, using CEF to run front-end on desktop. For several times we met the issue that the application exit without any indication. From the user guide, we have enabled large address aware, but this exception still occur randomly. 
From the event log, 
Faulting application name: ControlFLASH_Plus.exe, version: 3.0.0.123, time stamp: 0x5d14f772
Faulting module name: libcef.dll, version: 73.1.13.0, time stamp: 0x5c8499d0
Exception code: 0x4000001f
Fault offset: 0x00b0b927
Faulting process id: 0xe68
Faulting application start time: 0x01d52d4d1c143d6b
Faulting application path: C:\Program Files (x86)\ControlFLASH Plus\ControlFLASH_Plus.exe
Faulting module path: C:\Program Files (x86)\ControlFLASH Plus\libcef.dll
Report Id: ffc4dd16-0fb5-42d3-9ae5-6aed3e88e183

The dump file has been attached. Also There is a similar issue https://github.com/cefsharp/CefSharp/issues/944, which has been closed.

How can I get more details about this error or catch libcef.dll exceptions directly in app to avoid crash of entire app?

[CEFDump.zip](https://github.com/cefsharp/CefSharp/files/3337857/CEFDump.zip)

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#crash-reporting

**Comment by FionaYuanWei** [comment]
Thanks, we got the pdb and found the root cause. We configured the CEF log file to our application folder, but it turns out that CEF might not have write access to that folder. When there is no log file then trying to write to the log will cause crashing.

**Comment by amaitland** [comment]
I'd suggest you post on http://magpcss.org/ceforum/ including the details you've provided and a stack trace,  see if CEF can handle this scenario in a more graceful fashion.

**Comment by amaitland** [comment]
Removing support label and closing as upstream.
