### ISSUE TITLE
SchemeHandler is not processing the GetFileIcon

### ISSUE THREAD

**Issue by Daszbin** [cefsharp/CefSharp#2827]
### Please only open an issue if you have a BUG to report, if you simply have a question or require some assistance keep reading for info. If you do have a BUG to report, please use the Bug Report template below.

So you have a question to ask, where can you look for answers? Read on. Think you've found a bug? Please take the time to fill out the bug report below, provide as much information as you can, make sure you provide information for every heading. Thank you! We'd like to keep issues exclusively for **bug reports**, so please ask your questions on `Gitter`

- Start by reading the General Usage guide, it answers all the common questions https://github.com/cefsharp/CefSharp/wiki/General-Usage
- Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
- GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
- You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
- You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Still have a question? Great, ask it on `Gitter`. https://gitter.im/cefsharp/CefSharp

**Note: CefSharp is just a wrapper around the Chromium Embedded Project, it's worth searching http://magpcss.org/ceforum/index.php if your problem involves a low level Chromium error message**

We ask that you put in a reasonable amount of effort in searching through the resources listed above. The developers have full time jobs, they have lives, families, the time they have available to contribute this project is a precious resource, make sure you use it wisely! Remember the more time we spend answering the same questions over and over again, less time goes into writing code, adding new features, actually fixing bugs!

Still have a question to ask or unsure where to go next? Start with the Gitter Chat room : https://gitter.im/cefsharp/CefSharp

--
### Bug Report
Delete this line and everything above, and then fill in the details below.

- **What version of the product are you using?**
    - What version are you using? Nuget? CI Nuget? build from a branch? If so which branch? Please include the exact version number you are using (no ambiguous statements like `Latest from Nuget`)
75.0.110-CI3184 from MyGet
    - Please only create an issue if you can reproduce the problem with the latest version. (If you are using the latest stable release please check to see if there is a newer `-pre` release and test with that also).

- **What architecture x86 or x64?**
x86
- **On what operating system?**
    - Win7, Win 8, Win10, etc?
Win10
- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms
- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.

The problem is that the new schemehandler has changed the way I can access the file icons of the downloaded items from the downloadhandler. Here is my code from CefSharp 74
//
public MemoryStream GetFileIcon(string name, IconReader.IconSize size)
        {
            Icon icon = IconReader.GetFileIcon(name, size, false);
            using (icon)
            {
                Bitmap bmp = icon.ToBitmap();
                MemoryStream ms = new MemoryStream();
                bmp.Save(ms, System.Drawing.Imaging.ImageFormat.Png);
                ms.Seek(0, SeekOrigin.Begin);
                return ms;
            }
        }

        public bool ProcessRequest(IRequest request, ICallback callback)
        {
            Uri uri = new Uri(request.Url);
            string fileName = uri.AbsolutePath;

            if (uri.Host == "storage")
            {
                fileName = appPath + uri.Host + fileName;
                if (File.Exists(fileName))
                {
                    Task.Factory.StartNew(() =>
                    {
                        using (callback)
                        {
                            //var bytes = Encoding.UTF8.GetBytes(resource);
                            //stream = new MemoryStream(bytes);
                            FileStream fStream = new FileStream(fileName, FileMode.Open, FileAccess.Read);
                            mimeType = ResourceHandler.GetMimeType(Path.GetExtension(fileName));
                            stream = fStream;
                            callback.Continue();
                        }
                    });

                    return true;
                }
            }

            if (uri.Host == "fileicon")
            {
                Task.Factory.StartNew(() =>
                {
                    using (callback)
                    {
                        stream = GetFileIcon(fileName, IconReader.IconSize.Large);
                        mimeType = ResourceHandler.GetMimeType(".png");
                        callback.Continue();
                    }
                });
                return true;
            }

            return false;
        }
//
But you have discontinued the processrequest in favor of the new one async so how would I go about implementing this in the async because my downloads don't have a icon anymore on my application.

- **What is the expected output? What do you see instead?**
The expected outcome would be to have my downloaded items to have their icon displayed like before CefSharp 75. I see that it's not showing up at all.
- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
No

**Comment by amaitland** [comment]
When the API was changed the examples were also updated see https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/FlashResourceHandler.cs for an example. 

Any further questions please ask them on stackoverflow or Gitter, this is not a bug.
