### ISSUE TITLE
WPF rendering at 4k monitor generate 100% CPU

### ISSUE THREAD

**Issue by dhoerner2412** [cefsharp/CefSharp#2830]
- **What version of the product are you using?**
 Nuget 73.1.130

- **What architecture x86 or x64?**
x86

- **On what operating system?**
 Win 10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
Starting a WPF browser control at a 4K Monitor   

- **What is the expected output? What do you see instead?**
Expected: See the WPF Browser window, but see that CPU generates about 100% and the Browser windows needs about 20 seconds to load
- **Please provide any additional information below.**
Starting the same app at a "normal" Full HD monitor wors as expected

**Comment by ekalchev** [comment]
I think this is expected with WPF control. That is why most ppl use WinForms control inside WPF applications.

**Comment by amaitland** [comment]
@dhoerner2412 Did you test with the `CEF Sample application` as requested in the `Issue Template`? Seems you have totally omitted the last section of the bug report.

Download http://opensource.spotify.com/cefbuilds/cef_binary_73.1.13%2Bg6e3c989%2Bchromium-73.0.3683.75_windows32_client.tar.bz2

Test with  `cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu`
