### ISSUE TITLE
Feature Request - Change property name that Cefsharp injects to window

### ISSUE THREAD

**Issue by cppish** [cefsharp/CefSharp#2831]
Can I change the property name that Cefsharp injects to window to hide from anti-robot detecting code?
Now it is `CefSharp`, used in `CefSharp.BindObjectAsync`

**Comment by amaitland** [comment]
It's not currently configurable, you are welcome to submit a `PR` for consideration, there's a upper and lower case instance to consider.

https://github.com/cefsharp/CefSharp/blob/cefsharp/75/CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.cpp#L121

**Comment by amaitland** [comment]
Resolved with #3126
