### ISSUE TITLE
Missing Notification && ServiceWorkerRegistration.prototype.showNotification

### ISSUE THREAD

**Issue by keradus** [cefsharp/CefSharp#2836]
I am trying to run a website that is using Firebase Cloud Messaging ( https://firebase.google.com/docs/cloud-messaging/js/client ) under CefSharp, yet I cannot make it run, while it runs properly on Chrome. The integration is purely on website side with JavaScript (nothing in C# code).

when I run the page under CefSharp, FCM is complaining about missing APIs:
> Messaging: This browser doesn't support the API's required to use the firebase SDK. (messaging/unsupported-browser).

ref https://github.com/firebase/firebase-js-sdk/blob/d97b62c7ef7632174af651dc3ab49c321835b00e/packages/messaging/index.ts#L87

When I use chrome directly, i have `Notification` and `ServiceWorkerRegistration.prototype.showNotification` defined, but they are missing under CefSharp.

Can you help, please?

**Comment by jankurianski** [comment]
CefSharp is a C# wrapper around CEF, which is another project.

Please follow the instructions in the issue template regarding reproducing your issue in CEF:
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

> Does this problem also occur in the CEF Sample Application from http://opensource.spotify.com/cefbuilds/index.html?

If the issue occurs in CEF then it is not due to CefSharp - ask the question in the CEF forums: http://magpcss.org/ceforum/index.php

**Comment by amaitland** [comment]
> When I use chrome directly, i have `Notification` and

`CEF` does not support the `Notification API`, far as I know there are no plans to add it either see https://bitbucket.org/chromiumembedded/cef/issues/173/add-support-for-the-notification-api
https://magpcss.org/ceforum/viewtopic.php?f=6&t=10849
https://magpcss.org/ceforum/viewtopic.php?f=6&t=16009

> `ServiceWorkerRegistration.prototype.showNotification` defined

I'm not specifically aware of this one, though I expect it's the same. You can ask for clarification on https://magpcss.org/ceforum/index.php (post a link back here if you do for reference).
