### ISSUE TITLE
NetworkService - 403 Error when attempting Slack signin

### ISSUE THREAD

**Issue by mol** [cefsharp/CefSharp#2837]
- **What version of the product are you using?**
Latest master head e3fcc90c2dd99a561d5c17ef046e47153af81eb6

- **What architecture x86 or x64?**
x64.

- **On what operating system?**
Windows 10.

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
Tested using both WinForms and WPF.

- **What steps will reproduce the problem?**
Go to Slack.com, click 'Sign in' at the top. Write 'oracle' in the text box and click on 'Continue'.

- **What is the expected output? What do you see instead?**
An email address and password sign in page should appear. A 403 error page saying bad request appears instead. See below for image and screencast.

- **Please provide any additional information below.**
No exceptions thrown but log contains some data.
[debug.log](https://github.com/cefsharp/CefSharp/files/3397929/debug.log)

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
I tried the x64 CEF 3.3578.1863.gbf8cff2 version with '--multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu' and it worked. No error.

![Annotation 2019-07-15 125908](https://user-images.githubusercontent.com/317217/61309243-1e130d00-a7f2-11e9-920c-095085a3a770.jpg)

Screencast:
https://www.screencast.com/t/T0DocwdH3rSg

**Comment by amaitland** [comment]
> * I tried the x64 CEF 3.3578.1863.gbf8cff2 version with '--multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu' and it worked. No error.

Testing with `75.0.13+g2c92fcd+chromium-75.0.3770.100` and I can reproduce the problem.

Using `cefclient --multi-threaded-message-loop --off-screen-rendering-enabled` and I get the same error.
Using `cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --disable-features=NetworkService,VizDisplayCompositor` and it works as expected.

So it's `Network Service` related problem. There were a number of commits to the `3770` branch today, couple of network service related ones, whilst I don't think they'll fix the problem I'll double check when a build lands on http://opensource.spotify.com/cefbuilds/index.html

If the problem reproduces then we'll need to create an issue on https://bitbucket.org/chromiumembedded/cef/issues?status=new&status=open

**Comment by amaitland** [comment]
To disable the `Network Service in the `CefSharp` examples uncomment the relevant line in https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/CefExample.cs#L112

**Comment by mol** [comment]
Great, thanks - if I disable that then Slack works.

**Comment by amaitland** [comment]
This appears to be resolved by upgrading to `75.1.4` (commit https://github.com/cefsharp/CefSharp/commit/51b21f7fcace5f519221784d5b4d66bc1d97ed02)
