### ISSUE TITLE
Is it possible to define the file path when we print?

### ISSUE THREAD

**Issue by c2msis** [cefsharp/CefSharp#2838]
I know that with the IDownloadHandler we can modify which file path the download dialog will open but when i do:
`ExecuteScriptAsync("print()");` 
it doesn't trigger the downloadHandler.

Is there any way which i can modify the printing path?

**PS:** I know i can use PrintToPdfAsync but i want it to show the Dialog

**Comment by amaitland** [comment]
> Is there any way which i can modify the printing path?

Currently no.

**Comment by amaitland** [comment]
CEF has a feature request forum at https://magpcss.org/ceforum/viewforum.php?f=7
