### ISSUE TITLE
Winforms - Browser disappears when floating form to new window.

### ISSUE THREAD

**Issue by HankDitko** [cefsharp/CefSharp#2840]
- **What version of the product are you using?**
Nuget 73.1.130

- **What architecture x86 or x64?**
x64

- **On what operating system?**
Windows 10 Home 1903

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms

- **What steps will reproduce the problem?**
I originally encountered the issue trying to float forms using the DevExpress XtraTabbedMdiManager and DocumentManager. For an easier to reproduce example, I was able to recreate the problem using [DockPanelSuite](https://github.com/dockpanelsuite/dockpanelsuite) in [a fork of the MinimalExample](https://github.com/HankDitko/CefSharp.MinimalExample).

To recreate, just open a couple browser tabs and drag one out of the window.

- **What is the expected output? What do you see instead?**
The expected output is the browser window retaining its current state in the floating window. Instead, the browser content disappears.

- **Please provide any additional information below.**
No exceptions, no log output.

Happens with DockPanelSuite and DevExpress XtraTabbedMdiManager and DocumentManager.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
Not applicable

**Comment by HankDitko** [comment]
Here's a GIF of the issue.
![image](https://user-images.githubusercontent.com/9745133/61495912-77ad4000-a988-11e9-90ef-d29211ae992b.png)

**Comment by amaitland** [comment]
Is the ChromiumWebBrowser controls handle recreated during the process?

**Comment by HankDitko** [comment]
Yes. The HandleDestroyed and HandleCreated events both get triggered after the form is undocked.

**Comment by amaitland** [comment]
Unfortunately that's not a supported use case at the moment. I have previously attempted to add support without success. Relevant commit is https://github.com/cefsharp/CefSharp/commit/85e32974ae21ea2f774351c758ba6a75c9c5b555 though only works if the ChromiumWebBrowser is hosted within a tabcontrol.

I did a little digging through the .Net source and from memory the tabcontrol uses a hidden form to temp store the control until the new parent is ready. Don't quote me on this though. 

I don't have time to look into this further at the moment,  the source is there and pull request that adds support would be welcomed.

**Comment by rLindorfer** [comment]
Unfortunately, I have the same problem. Is there any bugfix or solution for this problem?

**Comment by amaitland** [comment]
The browser needs to be moved to a temporary parent whilst the handle is being destroyed and a new one is created.

You can create a class inheriting from `ChromiumWebBrowser` and try something like

```c#
private Control tempParent;

protected override void CreateHandle()
{
	var recreating = RecreatingHandle;

	base.CreateHandle();

	if (recreating)
	{
		var host = this.GetBrowserHost();
		var hwnd = host.GetWindowHandle();

		NativeMethodWrapper.SetWindowParent(hwnd, Handle);

		tempParent.Dispose();
		tempParent = null;
	}
}

protected override void DestroyHandle()
{
	if (RecreatingHandle)
	{
		tempParent = new Control();
		tempParent.CreateControl();

		var host = this.GetBrowserHost();
		var hwnd = host.GetWindowHandle();

		NativeMethodWrapper.SetWindowParent(hwnd, tempParent.Handle);
	}

	base.DestroyHandle();
}
```

**Comment by rLindorfer** [comment]
Thank you very much for your reply.

Unfortunately your solution did not work for me, because the RecreatingHandle property was always false and the DestroyHandle method was not called.

But after some testing, I could fix this bug by subscribing to the HandleDestroyed event. 
When this event is called, I can move the browser to a temporary parent. And when the CreateHandle is called again, I re-use this temporary handle.

**Comment by amaitland** [comment]
> Unfortunately your solution did not work for me, because the RecreatingHandle property was always **false** (which is very strange for me, maybe the recreating process is not implemented correctly) and the DestroyHandle method was **not called**.

What framework are you using to handle your window/forms? 

> But after some testing, I could fix this bug by subscribing to the **HandleDestroyed** event.
> When this event is called, I can move the browser to a temporary parent. And when the CreateHandle method is called again, I re-use this temporary handle.

@rLindorfer Great, please post an example for reference to others.

**Comment by rLindorfer** [comment]
I use the [DockPanelSuite (v3.0.6)](https://github.com/dockpanelsuite/dockpanelsuite) for handling my windows.

Example implementation:

```
public class MyChromiumWebBrowser : ChromiumWebBrowser
{
    private Control mTempParent;
    private bool mIsRecreating = false;

    public MyChromiumWebBrowser (string url, IRequestContext requestContext = null) : base(url, requestContext)
    {
        this.HandleDestroyed += MyChromiumWebBrowser_HandleDestroyed;
    }

    private void MyChromiumWebBrowser_HandleDestroyed(object sender, EventArgs e)
    { 
        mTempParent = new Control();
        mTempParent.CreateControl();

        // set the temporary control element as parent
        var host = this.GetBrowserHost();
        var windowHandle = host.GetWindowHandle();
        NativeMethodWrapper.SetWindowParent(windowHandle, mTempParent.Handle);

        // indicate that the handle should be recreated
        mIsRecreating = true;
    }

    protected override void CreateHandle()
    {
        base.CreateHandle();

        // check if the handle should be re-created
        if (mIsRecreating == true)
        {
            // set the new window parent
            var host = this.GetBrowserHost();
            var windowHandle = host.GetWindowHandle();
            NativeMethodWrapper.SetWindowParent(windowHandle, Handle);

            // dispose the temporary parent
            mTempParent.Dispose();
            mTempParent = null;

            // handle has been recreated
            mIsRecreating = false;
        }
    }
}
```

**Comment by amaitland** [comment]
> I use the [DockPanelSuite (v3.0.6)](https://github.com/dockpanelsuite/dockpanelsuite) for handling my windows.

I'm not familiar with `DockPanelSuite`, perhaps you can contact the maintainers and ask for comment.

> Example implementation:

Thanks. Your example might work, I don't believe it's strictly correct, the `HandleDestroyed` event should also fire when the control is `Disposed`, you'll likely be moving the browser to a new parent even when the control isn't going to be recreated. The `Dispose` method should hopefully still cleanup the browser correctly, I've not tested, so cannot guarantee that it does.

As it stands I think we'll only assign the browser to a temp parent  when `RecreatingHandle = true` as that's the expected behaviour

**Comment by amaitland** [comment]
A very quick look at the `DockPanelSuite` issue tracker and it looks like https://github.com/dockpanelsuite/dockpanelsuite/issues/304#issuecomment-265884782 describes the problem and it may not be in their control to fix. Looks like their suggestion is to handle the scenario manually which is what you've done.

The [Form.MdiParentInternal](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/Form.cs,1925) source suggests child controls aren't parked, so it's always going to be recreating the handle.

**Comment by rLindorfer** [comment]
Yes, I have already found this issue too. But it was closed years ago.
I updated my example, the temporary control element will now be disposed correctly.

Nevertheless, when should be the RecreatingHandle set to true?
In my tests when docking around the browser, this property never gets true, but the content of the browser disappears (i.e. the MainFrame gets disposed)...

**Comment by amaitland** [comment]
> But it was closed years ago.

What makes you think it's closed exactly? It looks inactive though still open to me.

> Nevertheless, when should be the RecreatingHandle set to true?

See https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.recreatehandle?view=netframework-4.8

> In my tests when docking around the browser, this property never gets true

If the `DockPanelSuite` is using `MdiParent` then it will never be set to `true` as it implements it's own custom handling. From what I can tell it forces recreation of all controls, it doesn't park them as you'd expect. It would be interesting to try the `.Net WebBrowser` control to see how it behaves, perhaps they've added some special handling.

The `TabControl` has special handling for recreation of it's children, it's using `internal` methods that aren't available to us though.

> but the content of the browser disappears (i.e. the MainFrame gets disposed)...

A new browser should be created when a new handle is created (and not recreating), this will be fixed in #3090

**Comment by rLindorfer** [comment]
> > But it was closed years ago.
> 
> What makes you think it's closed exactly? It looks inactive though still open to me.
> 
Yes, I meant the issue is inactive.

Many thanks for your efforts to solve this problem!

**Comment by amaitland** [comment]
I've added a new `ParkControlOnHandleDestroyed` property when when true will always use a parking control when the `ChromiumWebBrowser` handle is destroyed. Relevant commit is https://github.com/cefsharp/CefSharp/commit/4cac03bb936c3d84a397f96673804cb86d13a6ee

You have to `opt in` to this feature.

Further improvements may be possible, anyone is welcome to submit a `PR` for review.
