### ISSUE TITLE
OffScreen 73.1.130 on Windows 8.1: System.IO.FileNotFoundException "Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found."

### ISSUE THREAD

**Issue by kiewic** [cefsharp/CefSharp#2841]
- **What version of the product are you using?**

Branch/Tag: v73.1.130
Commit: d3d7e2646a70d218af95856979b47dc2d7d467e1
Nuget package: cef.redist.x86.73.1.13

- **What architecture x86 or x64?**

x86 (and x64)

- **On what operating system?**

Win 8.1 

- **Are you using `WinForms`, `WPF` or `OffScreen`?**

OffScreen

- **What steps will reproduce the problem?**

1. Build CefSharp.Offscreen.Example project from the CefSharp repo, tag v73.1.130
    * Make sure cef.redist.x86 package is set to version 73.1.13
2. Execute on a Windows 8.1 machine
3. App crashes and brings up debugger.

This is not a dev machine, but I made sure to install *vc_redist.x86.exe* (Microsoft Visual C++ 2015 Redist).

"Generate serialization assembly" is set to "Off"

- **What is the expected output? What do you see instead?**

App should not crash.

The *CefSharp.WinForms.Example* runs fine.

*CefSharp.OffScreen.Example* runs fine in Windows 10.

Same example built with v69.0.0 works fine in the same machine.

- **Please provide any additional information below.**

```
0:000> !PrintException
PDB symbol for clr.dll not loaded
Exception object: 02382468
Exception type:   System.IO.FileNotFoundException
Message:          Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found.
InnerException:   <none>
StackTrace (generated):
    SP       IP       Function
    00000000 00000001 CefSharp_OffScreen_Example!CefSharp.OffScreen.Example.Program.Main(System.String[])+0x2

StackTraceString: <none>
HResult: 8007007e
```
Debug.log doesn't get created.

Nothing out of the ordinary.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

This problem does not occur with `cef_binary_73.1.13+g6e3c989+chromium-73.0.3683.75_windows32_client.tar.bz2`

I ran `cefclient --multi-threaded-message-loop` and it works fine.

OH! If I run `cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu` the app does not crash, but I cannot see Google's home page. **However**, the cef sample app version 75.1.4 does not work either, but CefSharp master branch with same ceflib.dll works fine. So, this may not be related.

**Comment by amaitland** [comment]
Please test with https://github.com/cefsharp/CefSharp.MinimalExample

**Comment by git-net** [comment]
I got same error   in designer .

**Comment by kiewic** [comment]
CefSharp.MinimalExample.OffScreen with CefSharp.OffScreen.nupak 73.1.130 works fine. Any idea what it has that the DLLs built from https://github.com/cefsharp/CefSharp.git may not have?

**Comment by amaitland** [comment]
Did you accidentally deploy a debug build to a non developer machine?

**Comment by kiewic** [comment]
It looks like that could be the issue (thought, running the release version gave me a different error: ` Error in dxva_video_decode_accelerator_win.cc on line 511`).

What is the difference between the debug and the release versions??

**Comment by amaitland** [comment]
> When building from source make sure you compile in Release mode when deploying to machines that don't have Visual Studio installed. Visual C++ uses a different set of run-time libraries for Debug and Release builds. The Debug run-time libraries are only installed with Visual Studio. If you use the official Nuget packages they're already built in Release mode and you can subsequently build your app in debug mode as only the Visual C++ projects need to be compiled in Release mode.

As per the note in https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#Including_vcredist

Unfortunately this is a somewhat poorly documented Visual C++ behaviour. 

The WPF and WinForms examples will display a message box to warn you
https://github.com/cefsharp/CefSharp/blob/cefsharp/75/CefSharp.Wpf.Example/App.xaml.cs#L16
https://github.com/cefsharp/CefSharp/blob/cefsharp/75/CefSharp.WinForms.Example/Program.cs#L36

It's not so easy to do this in the OffScreen version.

If you are testing in a virtual machine you might have to disable you acceleration.

**Comment by amaitland** [comment]
> thought, running the release version gave me a different error: ` Error in dxva_video_decode_accelerator_win.cc on line 511`).

@kiewic Can you clarify if you are seeing this with the `MinimalExample`? Or just your own compiled version.

**Comment by kiewic** [comment]
Thanks for the pointers! As a workaround, I am including some of the debug versions of VC++ libraries with my Debug version installed in a non-developer machine (a test machine). In my case, I needed *vcruntime140d.dll*, *msvcp140d.dll* and *ucrtbased.dll*. Dependency walker is the tool to use to find missing dependencies.

![Viewing missing VC++ dependencies with Dependency Walker](https://user-images.githubusercontent.com/874134/61647628-96e6ee80-ac62-11e9-9e7d-b77d97bba8a2.png)

About `Error in dxva_video_decode_accelerator_win.cc on line 511`, I get the error with both examples, *CefSharp.MinimalExample.OffScreen.exe* and locally compiled *CefSharp.OffScreen.Example.exe* Release version. However, they seem to work fine. The difference is that the MinimalExample works fine, but other example does not work. This is not an issue for me anymore, since I got my test working fine now.

Thanks a lot for your help!

**Comment by amaitland** [comment]
@git-net Your issue is unrelated to this one, please follow upon https://gitter.im/cefsharp/CefSharp?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge it's not clear if what you are seeing is a bug or a known limitation . Attempting to target x64 and use the designer is a known limitation of visual studio.
