### ISSUE TITLE
Application crash at SynchronizeVisualProperties

### ISSUE THREAD

**Issue by FionaYuanWei** [cefsharp/CefSharp#2845]
We have an WPF application running on windows, and embedded CEF to serve UI. We use CEFSharp release v73.1.130. 
The crash happened when we running application on windows 10 and switch windows DPI, or running application on windows 7 and remote from another machine. We have configured the crash_report in another host. But no information in the CEF log file. We also downloaded the PDB file, and located the issue at SynchronizeVisualProperties. A windbg snapshot is attached.
From the history, there are two similar issues which have been fixed in chromium. But seems it still exist in CEFSharp v73.
[#issue 2600](https://bitbucket.org/chromiumembedded/cef/issues/2600/crash-when-dragging-cefclient-from-one) is [fixed ](https://bitbucket.org/chromiumembedded/cef/pull-requests/204/fixed-crash-when-display-dpi-changes-issue/diff).
[#issue 2614](https://bitbucket.org/chromiumembedded/cef/issues/2614/osr-resizing-issue-surface-invariants) is [fixed](https://bitbucket.org/chromiumembedded/cef/issues/2614/osr-resizing-issue-surface-invariants).

**Comment by FionaYuanWei** [comment]
![CefCrash](https://user-images.githubusercontent.com/24949121/61792880-52b94100-ae50-11e9-8b00-dcdf1d6bb23a.PNG)

**Comment by amaitland** [comment]
An issue was raised at https://bugs.chromium.org/p/chromium/issues/detail?id=983862

Closing as upstream as the issue needs to be fixed in CEF/Chromium.
