### ISSUE TITLE
Amazon Prime Video/Music no longer working

### ISSUE THREAD

**Issue by Honskiful** [cefsharp/CefSharp#2847]
- **What version of the product are you using?**
    - I've tried Stable (73.1.130) and the 75 Pre-Release

- **What architecture x86 or x64?**
    - x86

- **On what operating system?**
    - Win10 1809 x64

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - Winforms

- **What steps will reproduce the problem?**
    - Trying to play any movie (tv shows work fine I think) or music causes a popup to appear that tells me to update my browser.

- **What is the expected output? What do you see instead?**
    - Video/Music playing

- **Please provide any additional information below.**
    - The same thing happened ~6 weeks ago and an updated version of Widevine fixed it. Other websites (netflix, different test websites) using Widevine are working fine. I've tried the latest version from today's Chrome Dev Release, but it doesn't seem to change anything. Opera, Chromium Edge and Chrome work fine with the same Widevine version. The Brave Browser (also using Chromium) had the same issue and somehow managed to resolve it [by updating their rust library](https://community.brave.com/t/amazon-saying-browser-doesnt-support-hd-streaming/68302/11).

**Comment by amaitland** [comment]
Did you test with the CEF Sample application?  The details were included in the bug report template.

**Comment by amaitland** [comment]
https://magpcss.org/ceforum/viewtopic.php?f=6&t=16938
