### ISSUE TITLE
login www.taobao.com error

### ISSUE THREAD

**Issue by as4234426** [cefsharp/CefSharp#2848]
login www.taobao.com

Slide Verification Code error

version 63 is ok

**Comment by amaitland** [comment]
Realistically this is probably a bug in `CEF`. as you haven't filled out the issue template I've got no way of telling so this is flagged as `Support`. See https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report

Start with the `Does this problem also occur in the CEF Sample Application from` section then post on https://magpcss.org/ceforum/index.php if you can reproduce the problem. **MAKE SURE YOU USE THE COMMAND LINE ARGUMENTS LISTED**

**Comment by Zahar661** [comment]
@as4234426 Hello! Did you solve the problem? Same behavior on Aliexpress in both CefSharp and GekoFX. Most likely some option is not included.
![image](https://user-images.githubusercontent.com/26430136/62676201-09720100-b9bb-11e9-8a48-0dadd5168808.png)

**Comment by as4234426** [comment]
> @as4234426 Hello! Did you solve the problem? Same behavior on Aliexpress in both CefSharp and GekoFX. Most likely some option is not included.
> ![image](https://user-images.githubusercontent.com/26430136/62676201-09720100-b9bb-11e9-8a48-0dadd5168808.png)

hello，unfortunately, did not solve

<= version 63 is ok

> version 63 error
