### ISSUE TITLE
.net class conversion JavaScript object does not read correctly

### ISSUE THREAD

**Issue by crud-boy** [cefsharp/CefSharp#2851]
The variables in this object can be read normally, that is, they cannot be written.
```
 var resp = await e.Frame.EvaluateScriptAsync(plugin.scriptCode);
                        if(resp.Success)
                        {
                            var func = resp.Result as IJavascriptCallback;
                            await func.ExecuteAsync(ui);
                            plugin.execute = true;
                        }
```

The following code can be loaded synchronously to see the variable name in the ui object. When asynchronously loaded, the plugins variable cannot be read normally, which will cause an error. The previous ExecuteAsync method can be read normally.

```
class Plugin
{
  public string xx = {get;set;} = "";
}
class Ui:
{
public ObservableCollection<Plugin> plugins { get; set; } = new ObservableCollection<Plugin>() { };
}

browserControl.JavascriptObjectRepository.Register("ui", ui, false);
```

**Comment by amaitland** [comment]
Please read https://github.com/cefsharp/CefSharp/wiki/General-Usage#async-javascript-binding-jsb

Only methods are supported for Async binding as it's not possible to access a property in an asynchronous fashion.
