### ISSUE TITLE
HTML Tooltip not showing without Common Controls

### ISSUE THREAD

**Issue by carlovecchiato** [cefsharp/CefSharp#2854]
Hi there,
I have a winform application without the Microsoft.Windows.Common-Controls; its use is denied by system architect. 
when I open a webpage containing tooltips (html title attribute), these tooltips are not shown.

Is this a bug?
Is it possible to see these tooltips without using CommonControls?

Cheers,
Carlo

**Comment by amaitland** [comment]
It's not a bug, it's a Chromium requirement.

**Comment by amaitland** [comment]
For reference I'm not aware of any workaround, the http://cefsharp.github.io/api/73.1.x/html/M_CefSharp_IDisplayHandler_OnTooltipChanged.htm method is only called for `OSR` rendering (basically only called in `WPF/OffScreen` versions).

There is `upstream` issue https://bitbucket.org/chromiumembedded/cef/issues/783 which has been open forever.

You can ask on https://magpcss.org/ceforum/index.php for a second opinion.

**Comment by sayaniHalderMphasis** [comment]
So in this case, we need to generate an app.manifest for the project. The way:

In Visual Studio 2010, 2012, 2013, 2015 and 2017 you can add the manifest file to your project. Right-click your project file on the Solution Explorer, select Add, then New item (or CTRL+SHIFT+A). There you can find Application Manifest File. The file name is app.manifest.

after app.manifest is generated uncomment this part:

 <dependency>
        <dependentAssembly>
          <assemblyIdentity
              type="win32"
              name="Microsoft.Windows.Common-Controls"
              version="6.0.0.0"
              processorArchitecture="*"
              publicKeyToken="6595b64144ccf1df"
              language="*"
            />
    </dependentAssembly>
  </dependency>
once done, build the project, you can see the HTML tooltips in your chromium embedded framework c# in a Winforms application.

I hope this will fix your issue.
