### ISSUE TITLE
WPF - Content appears blurry when the system dpi changes on a per monitor dpi aware app

### ISSUE THREAD

**Issue by mathallsl** [cefsharp/CefSharp#2856]
- **What version of the product are you using?** 73.1.130
- **What architecture x86 or x64?** x86
- **On what operating system?** Win 10
- **Are you using `WinForms`, `WPF` or `OffScreen`?** WPF
- **What steps will reproduce the problem?**
I have modified the minimal example [here](https://github.com/mathallsl/CefSharp.MinimalExample) to use the [sample](https://code.msdn.microsoft.com/windowsdesktop/Per-Monitor-Aware-WPF-e43cde33) from Microsoft that makes windows per-monitor DPI aware. It works fairly well but I have found a problem:

   - Have two monitors plugged in, at different dpis to each other
  - Open the minimal example and keep it on the primary monitor
  - Unplug the primary monitor

- **What is the expected output? What do you see instead?**
The app should move to the secondary monitor and account for the dpi change. The normal controls (buttons) in the app scale correctly, however the content in the cefsharp control becomes blurry. [Screenshots](https://imgur.com/a/LeFGeVR)

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information. 
None

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
No

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
Just the per monitor dpi sample, as mentioned above. Moving the app between monitors manually when they're both plugged in works as expected - the UI elements scale, as does the web content. It is only when the primary monitor is unplugged does the problem occur

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
No

**Comment by amaitland** [comment]
Changing the DPI whilst the browser is running is not automatically handled currently,  you can manually hook the relevant WPF event and update the DPI manually. 

http://cefsharp.github.io/api/73.1.x/html/P_CefSharp_Wpf_ChromiumWebBrowser_DpiScaleFactor.htm

http://cefsharp.github.io/api/73.1.x/html/M_CefSharp_IBrowserHost_NotifyScreenInfoChanged.htm

**Comment by mathallsl** [comment]
Thanks for your prompt reply. When I do this the bluriness goes away, however the content does not take up the full screen and is instead in the bottom left quandrant. The canvas of the webview does take up the full area, it is only the image that is sized incorrectly. Is there a way to trigger a resize? I saw [this|http://cefsharp.github.io/api/73.1.x/html/M_CefSharp_IBrowserHost_WasResized.htm] but it didn't make a difference

**Comment by amaitland** [comment]
Add breakpoint to 

https://github.com/cefsharp/CefSharp/blob/cefsharp/73/CefSharp.Wpf/ChromiumWebBrowser.cs#L749
https://github.com/cefsharp/CefSharp/blob/cefsharp/73/CefSharp.Wpf/ChromiumWebBrowser.cs#L898

See what you get for width and height. Note in OnPaint the values will be prescaled. 

WasResized should trigger a call to GetViewRect. Project is built with GitLink so you can step into the source and add some breakpoints. See https://github.com/GitTools/GitLink/blob/develop/README.md

I'm assuming by webview you mean ChromiumWebBrowser.

**Comment by amaitland** [comment]
When you tested with the CEF Sample application what command line args did you use?  Did you test with cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu

Also please confirm you tested with http://opensource.spotify.com/cefbuilds/cef_binary_73.1.13%2Bg6e3c989%2Bchromium-73.0.3683.75_windows32_client.tar.bz2

**Comment by mathallsl** [comment]
When I start the app on a 1.5x scaled monitor the ActualWidth and ActualHeight from GetViewRect are 1/1.5 that of width and height on OnPaint. The RenderSize for both the ChromiumWebBrowser, the canvas and the image are the same. After moving the app to a 1x screen and changing the dpi scaling to 1x there are a lot of fluctuations but the final values I got were the same in GetViewRect and OnPaint. However, the ChromiumWebBrowser and canvas elecments had the correct RenderSize, but the image was 1/1.5 that of the canvas. (was in the bottom left corner)

I can confirm that running the cefclient from the file you linked with those flags handles dpi scaling without blurriness. Perhaps interestingly if you change dpi there is a brief period where the web content only appears in the bottom left corner. It quickly fixes itself however.

**Comment by amaitland** [comment]
Thanks for confirming the cefclient details. 

It occurred to me that the Render Handler also needs to be updated. 

https://github.com/cefsharp/CefSharp/blob/cefsharp/75/CefSharp.Wpf/ChromiumWebBrowser.cs#L1720

Just set a new instance with the updated scale and hopefully that is the last piece. I don't have two monitors setup so I cannot debug this.

**Comment by mathallsl** [comment]
Thanks for all your help, that worked :)

**Comment by amaitland** [comment]
We can look at extract the change DPI code into a public method to simplify this.
