### ISSUE TITLE
Example code/documentation for CefCommandLineArgs usage is misleading

### ISSUE THREAD

**Issue by ben-wallis** [cefsharp/CefSharp#2858]
Throughout the CefSharp documentation and example code there are examples of enabling Chromium command-line switches like this:

`settings.CefCommandLineArgs.Add("disable-gpu", "1");`

While this does work, it also would logically lead you to think that if you wanted to programatically enable/disable a flag you could use a zero instead:

`settings.CefCommandLineArgs.Add("disable-gpu", "0");`

However, this is incorrect. As `disable-gpu` (and indeed, almost all of the CEF command-line arguments) are switchless, the "0" is ignored and the `--disable-gpu` flag takes effect. This can easily be reproduced by navigating to chrome://gpu and noting that hardware acceleration is disabled with both of the above lines of code, but if the argument is not added at all, hardware acceleration is enabled.

I would suggest that examples are re-written to use `string.Empty` as the second parameter to make it clear that in the case of switchless parameters it is the presence of the dictionary key alone that toggles the flag, not any particular value of the dictionary value.

`settings.CefCommandLineArgs.Add("disable-gpu", string.Empty);`

Some examples of documentation/code that has this issue:

https://github.com/cefsharp/CefSharp/wiki/General-Usage#cefsettings-and-browsersettings

https://github.com/cefsharp/CefSharp/blob/cdca99c548a641a5d3b7294e6fcbc5840d134508/CefSharp.Example/CefExample.cs
https://github.com/cefsharp/CefSharp/blob/b2acd4ad760e870556b67f51271ce4251f0847ac/CefSharp.OffScreen/CefSettings.cs
https://github.com/cefsharp/CefSharp/blob/c9203c93101e722c30a8c6151d4737eb943ba4d1/CefSharp.Wpf/CefSettings.cs
https://github.com/cefsharp/CefSharp/blob/23b905dbdaba194f3e4261272adb20e42ab0cbf9/CefSharp.Example/Resources/Home.html

- [ ] Update `Wiki` to use new `Add(string)` method.

**Comment by amaitland** [comment]
Pull requests welcome.

**Comment by miller45** [comment]
@ben-wallis I made a fork for correcting the missleading documenation and code examples into https://github.com/miller45/CefSharp and I already changed the parts you pointed out (string.Empty) instead of "1". (Man I spent days with confusion about why setting (or unsetting via 0) these switches does not have any effect)
I have to search for some other occurences now...
FYI: I will only change documenation and examples to keep the pullrequest topic "documenation only"

**Comment by miller45** [comment]
After thinking this through I decided to not use string.Empty instead of "1". It would too much inconsistencies with the rest of the codeline and documenation that has been spread out. 
But I added a note in the wiki and the examples about that.

**Comment by amaitland** [comment]
> After thinking this through I decided to not use string.Empty instead of "1". It would too much inconsistencies with the rest of the codeline and documenation that has been spread out.
> But I added a note in the wiki and the examples about that.

@miller45 Thanks for making an attempt, I'm going to take a different approach.

---

Using a dictionary for command line args is clunky, unfortunately the code has been around `~5years` so it's difficult make too many changes without creating a support nightmare. I'd love to remove it all together and have command line args directly applied to a wrapper around `CefCommandLine` (the `C++` class), unfortunately I still haven't dreamt up a way of cleanly transitioning to such a wrapper.

So for now I'll go with adding a custom `Dictionary` that includes an `Add(string)` method that appends `string.Empty` as the value. Changes made in https://github.com/cefsharp/CefSharp/commit/f088a7c169576564d5e3d396504d3404ca95c7b7 I've updated the examples in the project source. Once version `77` is released the `Wiki` can be updated.

As a side note I do find it interesting that in the 5 years I've been involved in the project I cannot remember a reported confusion, and then there is two in a month!

**Comment by miller45** [comment]
Thanks for caring...Usually confusion in understanding examples is a thing you take for granted.
But with in our company multiple people were wasting hours, finding the right settings for a vmware-view/thin-client gpu/wpf-embedded-browser nightmare. We were trying to find the settings by experimentation (read: permutation of commandline switches) and were scratching our heads why the effects were so unpredictable.

**Comment by amaitland** [comment]
Version `79.1.350` is out which includes an `CefCommandLineArgs.Add(string)` method.

I've updated the references I could find in the `Wiki`. 

- https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting/_compare/3b87e2d449d99417698e34c413cc227737a9be23...62daf323b528d1477348333d89a1e9dff7e1aab0
- https://github.com/cefsharp/CefSharp/wiki/General-Usage/_compare/24f442ef451b35b37701172c1e9511533ce9ea83...46df70e814f91d6481d42e6859da3ff26fe97ee3

Obviously there's a chance I missed something, if anyone finds an example that needs updating then please
- Edit the `Wiki` (anyone with a github account can)
- Submit a `PR`.
- Post a link to the example.

**Comment by zelpnir** [comment]
So now it is recommended to use settings.CefCommandLineArgs.Add("disable-gpu"); instad of settings.CefCommandLineArgs.Add("disable-gpu", "1"); or do both work the same?

**Comment by amaitland** [comment]
> recommended to use settings.CefCommandLineArgs.Add("disable-gpu");

Recommended.

> instad of settings.CefCommandLineArgs.Add("disable-gpu", "1");

Historically this has worked. Prefer without second arg.
