### ISSUE TITLE
An event when finished rendering in the form

### ISSUE THREAD

**Issue by anmarin** [cefsharp/CefSharp#2860]
Hi, could an event be executed that runs when the control has finished rendering on the form, please.

Thank you.

**Comment by amaitland** [comment]
`CEF` does not provide such an event.

**Comment by amaitland** [comment]
In future please use https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/feature_request.md when opening a `Feature Request`.
