### ISSUE TITLE
API-MS-WIN-* libraries missing

### ISSUE THREAD

**Issue by Pospelove** [cefsharp/CefSharp#2862]
Hi. I am using CefSharp.Offscreen from C++ CLI.
These lines work fine on my Windows 8.1 system but crash on another machine with Windows 10:
```c++
class CefSharpBrowser {
  CefSharpBrowser();
};

CefSharpBrowser::CefSharpBrowser() {
  CefSettings ^settings = gcnew CefSettings;
}
```
[Dependency Walker](http://www.dependencywalker.com/) says `CefSharp.Core.dll` has dependency on `API-MS-WIN-*.DLL` files. They present on my computer but missing on Windows 10 machine.

What should I do?
Thank you.

**Comment by amaitland** [comment]
Those files are part of the Universal CRT, if you haven't already please read the following. 

https://devblogs.microsoft.com/cppblog/introducing-the-universal-crt/
https://docs.microsoft.com/en-us/cpp/windows/universal-crt-deployment?view=vs-2019

Please ask any further questions on stackoverflow.
