### ISSUE TITLE
select's dropdown list will auto closed

### ISSUE THREAD

**Issue by nocanstillbb** [cefsharp/CefSharp#2863]
- **What version of the product are you using?**
    75.1.140 preview

- **What architecture x86 or x64?**
    anycpu

- **On what operating system?**
    win10 17763

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WPF

- **What steps will reproduce the problem?**
    1.click select h5 element
    2.wheeled mouse mid button
    3.dropdown list will be coloed
    ![cefbug](https://user-images.githubusercontent.com/22405678/63206560-6707fb00-c0e9-11e9-8059-1903571fd333.gif)

DEMO:https://github.com/nocanstillbb/CefSharp.MinimalExample

- **What is the expected output? What do you see instead?**
  dropdown list not be closed

- **Please provide any additional information below.**
    -without exception

**Comment by amaitland** [comment]
Closing as upstream. Please test with the CEF sample application before opening an issue next time.

https://bitbucket.org/chromiumembedded/cef/issues/2547/drop-down-box-select-element-closes-after

**Comment by nocanstillbb** [comment]
> Closing as upstream. Please test with the CEF sample application before opening an issue next time.
> 
> https://bitbucket.org/chromiumembedded/cef/issues/2547/drop-down-box-select-element-closes-after

ok,thanks . i will

**Comment by amaitland** [comment]
@nocanstillbb It's an upstream issue as I've already linked, please don't open any further issues.

**Comment by nocanstillbb** [comment]
> @nocanstillbb It's an upstream issue as I've already linked, please don't open any further issues.

![image](https://user-images.githubusercontent.com/22405678/63209533-a8fa6680-c114-11e9-837a-937088eacb9c.png)
sorry, I thought you asked me to test it with the cef test program, and then reopen it if I ruled out problems that weren't cef.  i test it use cefclient already

**Comment by nocanstillbb** [comment]
![cefnormal](https://user-images.githubusercontent.com/22405678/63209576-4e153f00-c115-11e9-9d61-ee5347f207aa.gif)

**Comment by amaitland** [comment]
> Please test with the CEF sample application before opening an issue next time.

Next time would imply that any issue you would create in the future. 

> To compare with WPF run cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu

As per the the instructions you **MUST** test with the command line arg listed.

> Please include the version you tested with e.g. cef_binary_3.3029.1611.g44e39a8_windows64_client.tar.bz2. It's important to you test with the same version that CefSharp is based on. Check the release notes to determine the version (https://github.com/cefsharp/CefSharp/releases) or load chrome://version in the browser.

Additionally you must test with the **EXACT** same version of `CEF` as `CefSharp` is based for an accurate comparison.

Testing with version `cef_binary_75.1.14+gc81164e+chromium-75.0.3770.100_windows32_client` and using `cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu` I get the **EXACT** same behaviour as you are reporting. I also tested with `cef_binary_76.1.9+g2cf916e+chromium-76.0.3809.87_windows32_client` and it behaves slightly differently, though still closes unexpectedly.

This is an `upstream` issue. Please follow the very specific instructions outlined in the issue template next time, thanks.

**Comment by nocanstillbb** [comment]
> > 请在下次打开问题之前使用CEF示例应用程序进行测试。
> 
> 下次将暗示您将来会创建的任何问题。
> 
> > 与WPF比较运行cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu
> 
> 根据说明，您**必须**使用列出的命令行arg进行测试。
> 
> > 请包括您测试的版本，例如cef_binary_3.3029.1611.g44e39a8_windows64_client.tar.bz2。使用与CefSharp相同的版本进行测试非常重要。检查发行说明以确定版本（https://github.com/cefsharp/CefSharp/releases）或在浏览器中加载chrome：//版本。
> 
> 此外，你必须与测试**EXACT**相同版本的`CEF`作为`CefSharp`是基于一个准确的比较。
> 
> 与测试版本`cef_binary_75.1.14+gc81164e+chromium-75.0.3770.100_windows32_client`，并使用`cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu`我得到**精确**相同的行为，你的报告。我也测试过`cef_binary_76.1.9+g2cf916e+chromium-76.0.3809.87_windows32_client`，它的行为略有不同，但仍然意外关闭。
> 
> 这是一个`upstream`问题。请按照下次问题模板中列出的非常具体的说明进行操作，谢谢。



> > Please test with the CEF sample application before opening an issue next time.
> 
> Next time would imply that any issue you would create in the future.
> 
> > To compare with WPF run cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu
> 
> As per the the instructions you **MUST** test with the command line arg listed.
> 
> > Please include the version you tested with e.g. cef_binary_3.3029.1611.g44e39a8_windows64_client.tar.bz2. It's important to you test with the same version that CefSharp is based on. Check the release notes to determine the version (https://github.com/cefsharp/CefSharp/releases) or load chrome://version in the browser.
> 
> Additionally you must test with the **EXACT** same version of `CEF` as `CefSharp` is based for an accurate comparison.
> 
> Testing with version `cef_binary_75.1.14+gc81164e+chromium-75.0.3770.100_windows32_client` and using `cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu` I get the **EXACT** same behaviour as you are reporting. I also tested with `cef_binary_76.1.9+g2cf916e+chromium-76.0.3809.87_windows32_client` and it behaves slightly differently, though still closes unexpectedly.
> 
> This is an `upstream` issue. Please follow the very specific instructions outlined in the issue template next time, thanks.

Thank you for your patience
