### ISSUE TITLE
When printing to PDF with CefPdfPrintMarginType.Custom margins are 0

### ISSUE THREAD

**Issue by abelykh0** [cefsharp/CefSharp#2865]
- **What version of the product are you using?**
Nuget 75.1.14

- **What architecture x86 or x64?**
x64

- **On what operating system?**
Windows 10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
OffScreen
- **What steps will reproduce the problem?**
```csharp
// ...
PdfPrintSettings settings = new PdfPrintSettings();
settings.HeaderFooterEnabled = false;
settings.BackgroundsEnabled = true;
settings.MarginType = CefPdfPrintMarginType.Custom;
settings.MarginLeft = 36;
settings.MarginTop = 36;
settings.MarginRight = 36;
settings.MarginBottom = 36;
await browser.PrintToPdfAsync(@"C:\Temp\out.pdf", settings);
```

- **What is the expected output? What do you see instead?**
Expected 36 margins, instead 0 margins

- **Please provide any additional information below.**
Upstream bug: https://bitbucket.org/chromiumembedded/cef/issues/2694

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
No, this is the debug.log:
```
[0819/125737.625:WARNING:ipc_message_attachment_set.cc(49)] MessageAttachmentSet destroyed with unconsumed attachments: 0/1
```

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
No

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
Yes, if you modify it like in replication steps

Can you please influence the upstream so they fix the issue?

**Comment by amaitland** [comment]
Closing as upstream https://bitbucket.org/chromiumembedded/cef/issues/2694/pdf_print_margin_custom-settings-are

> If you can reproduce the problem with cefclient then you'll need to report the bug on https://bitbucket.org/chromiumembedded/cef/overview there is no point opening an issue here. (Make sure you search before opening an issue)

In future if you can reproduce the problem with cefclient then please use the CEF issue tracker instead of opening an issue here.

I have no influence over the upstream CEF project.

**Comment by GrabzIt** [comment]
Hopefully they will fix it soon. We can't upgrade until they do as we rely on setting custom margins.

**Comment by GrabzIt** [comment]
I already have up voted it.
