### ISSUE TITLE
WPF cefsharp 75.1.14 IgnoreCertificateErrors = true , invalid

### ISSUE THREAD

**Issue by godpit** [cefsharp/CefSharp#2868]
There is a invalid setting with IgnoreCertificateErrors = true , which in the lastest version(75.1.14 ) of cefsharp .wpf .

It work well within other version, such as 73.

How to solve it?

**Comment by godpit** [comment]
var settings = new CefSettings();

            // Set BrowserSubProcessPath based on app bitness at runtime
            settings.BrowserSubprocessPath = Path.Combine(AppDomain.CurrentDomain.SetupInformation.ApplicationBase,
                                                   Environment.Is64BitProcess ? "x64" : "x86",
                                                   "CefSharp.BrowserSubprocess.exe");
            settings.Locale = "zh-CN";
            settings.CefCommandLineArgs.Add("enable-media-stream", "1");
            settings.CefCommandLineArgs.Add("disable-gpu", "1"); 
            settings.CefCommandLineArgs.Add("disable-web-security", "1"); 
            settings.IgnoreCertificateErrors = true;
            // Make sure you set performDependencyCheck false
            Cef.Initialize(settings, performDependencyCheck: false, browserProcessHandler: null);

**Comment by amaitland** [comment]
It's important to note that `CefSharp` is just a wrapper around the `Chromium Embedded Framework (CEF)`. Closing this as `upstream` and as changes need to be made in `CEF`. 

The `CEF` project has it's own issue tracker located at https://bitbucket.org/chromiumembedded/cef it is recommended you ask on https://magpcss.org/ceforum/index.php before opening an issue on the CEF issue tracker.

**Comment by amaitland** [comment]
As per the release notes CEF has had a major rewrite, the issue you are seeing is likely a result of the new network service changes which are detailed in https://bitbucket.org/chromiumembedded/cef/issues/2622/implement-support-for-networkservice

**Comment by godpit** [comment]
settings.CefCommandLineArgs.Add("ignore-certificate-errors", "1")

It works well by adding the command line.

**Comment by amaitland** [comment]
You should report the problem on https://bitbucket.org/chromiumembedded/cef/issues?status=new&status=open

**Comment by godpit** [comment]
Thanks a lot
