### ISSUE TITLE
IOException in ResourceHandler.FromFilePath

### ISSUE THREAD

**Issue by ray007** [cefsharp/CefSharp#2869]
- **What version of the product are you using?**
CefSharp 73 build with media codecs

- **What architecture x86 or x64?**
x86

- **On what operating system?**
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

I have a custom scheme handler which very rarely produces an IOExeption:
```
An unhandled exception of type 'System.IO.IOException' occurred in mscorlib.dll

Additional information: The process cannot access the file 'C:\...\assets\71\716ECBDA65AD692046023BA1A47734A4F538AE59.bin' because it is being used by another process.
```

The stacktrace is coming down from `CefSharp.dll!CefSharp.ResourceHandler.FromFilePath(string filePath, string mimeType, bool autoDisposeStream)`.

The first line in `ResourceHandler.FromFilePath` is
```
var stream = File.OpenRead(filePath);
```
If you replace that with
```
var stream = File.Open(fileName, FileMode.Open, FileAccess.Read, FileShare.Read);
```
things should be fine. At least I couldn't trigger the problem since, but then it only happened very rarely in the first place...

**Comment by amaitland** [comment]
Sounds reasonable, please submit a `PR` that targets `master`.

**Comment by amaitland** [comment]
Looking at this closer and `MSDN` suggests the proposed change is functionally equivalent to the code we already have.

https://docs.microsoft.com/en-us/dotnet/api/system.io.file.openread?view=netframework-4.8#remarks
https://referencesource.microsoft.com/#mscorlib/system/io/file.cs,769
https://referencesource.microsoft.com/#mscorlib/system/io/file.cs,479

**Comment by amaitland** [comment]
Are you attempting to write to the file while your application is running? That seems like the most likely cause of this exception. You'd need to open the file in [FileShare.ReadWrite](https://docs.microsoft.com/en-us/dotnet/api/system.io.fileshare?view=netframework-4.8#fields) if that was the case.
