### ISSUE TITLE
Wpf and WinForms versions in the same process no longer work together if window has transparency

### ISSUE THREAD

**Issue by PlamenTTotev** [cefsharp/CefSharp#2876]
- **What version of the product are you using?**
    - Nuget version 75.1.141 both for WInForms and WPF

- **What architecture x86 or x64?**
 - Both

- **On what operating system?**
    - Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
 - WinForms, WPF

- **What steps will reproduce the problem?**
    - I am using WinForms and WPF versions in the same application. I do that because in some cases I need transparency (supported by the WPF version) or I need multi-touch (supported by the WinForms version). This worked great in 71.0.2 version. Starting from 73.1.130 if I host WPF and WinForms in the same application and I turn on the transparency - only one of the controls loads correctly.

1.  Create a WPF window with  
2. AllowsTransparency="True" Background="Transparent" WindowStyle="None"
3. Add WPF ChromiumBrowser
4. Add WinForms ChromiumBrowser hosted in a WindowsFormsHost control.
5. Load any website into both browsers.
6. Only one of the browsers actually works.
7.. Remove AllowsTransparency="True" Background="Transparent" WindowStyle="None"   and all is working fine.

- **Code sample**
https://github.com/PlamenTTotev/CefSharp.MinimalExample
Run the CefSharp.MinimalExample.Wpf and only WPF browser works. If you modify the window to not allow transparency, both browsers will load. This is working fine in 71.0.2.

- **What is the expected output? What do you see instead?**
Both WiForms and WPF should load correctly.

**Comment by amaitland** [comment]
> * I am using WinForms and WPF versions in the same application. I do that because in some cases I need transparency (supported by the WPF version) or I need multi-touch (supported by the WinForms version). This worked great in 71.0.2 version. Starting from 73.1.130 if I host WPF and WinForms in the same application and I turn on the transparency - only one of the controls loads correctly.

How does it behave if you remove the `CefSharp.Wpf` packages and just use the `WinForms` version?

> * https://github.com/PlamenTTotev/CefSharp.MinimalExample
>   Run the CefSharp.MinimalExample.Wpf and only WPF browser works. If you modify the window to not allow transparency, both browsers will load. This is working fine in 71.0.2.

Thanks for taking the time to provide an example 👍 The reality is this may not be something we can support in the future (wasn't an explicitly tested/supported previously). If you are lucky it's just that `WinForms` won't load with `Viz Compositor` disabled, which is required by `WPF` to function in version `73,75`, should be resolved in version `77`. This is a `CEF` requirement, not something we have any control over.If it's some other subtle change in the `CEF/Chromium` implementation, there isn't a whole lot we can do.

> * or I need multi-touch (supported by the WinForms version).

There is `Experimental` support for touch in `WPF` currently, use http://cefsharp.github.io/api/75.1.x/html/T_CefSharp_Wpf_Experimental_ChromiumWebBrowserWithTouchSupport.htm

If you have time to test it out report back on #228 (more testing the sooner it will be enabled by default)

**Comment by PlamenTTotev** [comment]
I tried the experimental version and so far looks promising. Thanks !

**Comment by ekalchev** [comment]
I am using WinForms control from version 60 and it never worked with Transparency = True. I believe native window style (that comes with AllowTransparency = "True") is not compatible with opengl rendering of the browser.

**Comment by nocanstillbb** [comment]
windowsformshost can only use in the case Transparency = false,
not matter it host what

**Comment by amaitland** [comment]
The [79.1.310-pre](https://github.com/cefsharp/CefSharp/releases/tag/v79.1.310-pre) release is now out, the `WPF` version supports the `Viz Compositor`, previously it was disabled and this is likely the reason the `WinForms` wasn't displaying.
