### ISSUE TITLE
Is there a way to save the state of the chromium Web Browser?

### ISSUE THREAD

**Issue by Jeremy-Busuttil** [cefsharp/CefSharp#2878]
Hello Everyone

I'm new to WPF C# and using CefSharp. I was working on an application that opens multiple instances on the Microsoft Teams web app in one application. I need a way to be able to save the save the list of browsers I have open when the user decides to exit.

I researched a bit on Serialization and attempted to serialize the list I have. However I found out that CefSharp.Wpf.ChromiumWebBrowser cannot be Serialized. I was wondering if there is any other way in which I can save the browsers when I exit in a similar way to Serialization so that I can load them up when the app is opened again.

Thanks in advance for any help :D

**Comment by amaitland** [comment]
CEF provides no means of saving/restoring state
