### ISSUE TITLE
WPF CefSharp: Session restoring does not work

### ISSUE THREAD

**Issue by PonomariovEvgeniy** [cefsharp/CefSharp#2884]
Hi, dear Cef team!
I have a question.

I develop a **WPF** application using CefSharp **v75.1.141** from NuGet.
The application contains several instances of ChromiumWebBrowser with separate containers cookie cache, etc. where each instance is authorized on the site https://web.whatsapp.com/ under different account. On other sites, session are saved and restored successfully, but not at WhatsApp.

Browser Initialization Code on app startup:
`var settings = new CefSettings();`
`settings.RootCachePath = "Cache";`
`// For FHD+`
`Cef.EnableHighDPISupport();`
`// Initialize cef with the provided settings`
`Cef.Initialize(settings);`

Browser instance setup:
`if (UID == null)`
`UID = Guid.NewGuid().ToString();`
`var requestContextSettings = new RequestContextSettings`
`{`
`                CachePath = Path.Combine("Cache", UID),`
`                PersistSessionCookies = true,`
`                PersistUserPreferences = true`
`};`
`Browser = new ChromiumWebBrowser("https://web.whatsapp.com/);`
`Browser.RequestContext = new RequestContext(requestContextSettings);`

WhatsApp, as I understand it, uses cookies, local storage and file system for authorization. 

All this seems to be saved on disk, but authorization is always required after a restart.
I tried many configuration options for Cef, but nothing worked.
But if you use Cef in normal mode (without separate storage), everything works fine.

I really need your help. Ty.

**Comment by amaitland** [comment]
Please read the known issues section of the release notes https://github.com/cefsharp/CefSharp/releases/tag/v75.1.141

There is an upstream problem setting the RootCachePath, try downgrading to version 73. 

If you still have problems then ask on ceforum.

**Comment by amaitland** [comment]
Looks like this was ask on https://stackoverflow.com/questions/57777287/wpf-cefsharp-session-restoring-does-not-work

Please don't cross post, just ask on stackoverflow and wait for a response there.
