### ISSUE TITLE
Feature Request - Add push notification support

### ISSUE THREAD

**Issue by luiscla27** [cefsharp/CefSharp#2890]
Push notifications are now used on all platforms (mobile, Web and desktop). When developing a cross-platform application, the main goal is to bring a shared set of features to all users whatever the platform they are using.

The easiest way to send and receive notifications is to use Firebase Cloud Messaging (FCM), which provides integrations for Android, iOS and Web.

Unfortunately, if you’re to build a desktop application, you can’t receive push notifications sent through FCM.
----
There's an open source project called [push-receiver](https://github.com/MatthieuLemoine/push-receiver) (more details [here](https://medium.com/@MatthieuLemoine/my-journey-to-bring-web-push-support-to-node-and-electron-ce70eea1c0b0)), is CefSharp capable of implementing [a wrapper](https://github.com/MatthieuLemoine/electron-push-receiver) like they did with [Electron](https://electronjs.org/)?

**Comment by amaitland** [comment]
> is CefSharp capable of implementing [a wrapper](https://github.com/MatthieuLemoine/electron-push-receiver) like they did with [Electron](https://electronjs.org/)?

The real question is the [Chromium Embedded Framework(CEF)](https://bitbucket.org/chromiumembedded/cef/) capable of implementing such a wrapper? You might have better luck asking on https://magpcss.org/ceforum/index.php possibly someone else working with `CEF` has tried? I've got no idea.

If your new to `CefSharp` please read the first few paragraphs of https://github.com/cefsharp/CefSharp/wiki/General-Usage

This isn't something I plan to take on personally, I've already got way too many things to do without adding this to the list. If it's something you wish to take ownership of then happy to create a subproject under https://github.com/cefsharp/ to host your project.

**Comment by amaitland** [comment]
Closing for now, can be reopened if required.
