### ISSUE TITLE
Issue - When use Proxy the ChromiumWebBrowser will return blank page

### ISSUE THREAD

**Issue by kochiya2002** [cefsharp/CefSharp#2893]
Hi, 

My problem is using proxy server the Browser will return a blank page.
When I remove set proxy server the script, the browser will no problem.

P.S. I confirm the proxy server is no problem because I tried to use this proxy on chrome.
My VS version is 2005, CEFSharp uses NuGet to install, the version is 75.1.141. And Chromium Web Browser version is 75.0.3770.100

Can you help me solve this problem? Because use more time to try different ways to set the proxy server, but the result as same as a blank page.

below my script on the Form_Load
---------------------------------------------------------------
            const string testUrl = "http://www.google.com";
            CefSharp.CefSharpSettings.Proxy = new CefSharp.ProxyOptions("123.1.170.138", "3128");
            CefSettings cfsettings = new CefSettings();
            Console.WriteLine(Cef.ChromiumVersion);
            Cef.Initialize(cfsettings);
            browser = new ChromiumWebBrowser(testUrl);
            this.Controls.Add(browser);
            browser.Dock = DockStyle.Fill;
---------------------------------------------------------------

below is the result when use proxy server
---------------------------------------------------------------
`<html><head></head><body></body></html>`
---------------------------------------------------------------

**Comment by amaitland** [comment]
https://stackoverflow.com/questions/57830349/issue-using-cefsharp-winform-will-return-blank-page-when-use-proxy
