### ISSUE TITLE
One Question.

### ISSUE THREAD

**Issue by jsec1912** [cefsharp/CefSharp#2897]
Hi Developers!
I have one problem.
if I use Cefsharp browser with proxy server, google search doesn't work.
it's reCaptcha .
Of course I used elite private proxy server.
How can I solve this problem?
Please teach me.

**Comment by amaitland** [comment]
Ask on ceforum

**Comment by amaitland** [comment]
https://stackoverflow.com/questions/57843731/how-to-solve-google-recaptcha-when-using-cefsharp-with-proxy-server
