### ISSUE TITLE
How send post data

### ISSUE THREAD

**Issue by DevReportOne** [cefsharp/CefSharp#2898]
Hello,
I want to set up in a WPF project, a modal that when opened opens a web page with a request in post (for example, login to a login page with login / pass transmitted by the app).
While searching on google, I came across these links:

- [https://stackoverflow.com/questions/42449289/send-post-data-to-url-with-cefsharp-c-sharp](https://stackoverflow.com/questions/42449289/send-post-data-to-url-with-cefsharp-c-sharp)
- [https://stackoverflow.com/questions/49889185/working-cefsharp-post-example?rq=1](https://stackoverflow.com/questions/49889185/working-cefsharp-post-example?rq=1)
- [https://github.com/cefsharp/CefSharp/issues/912](https://stackoverflow.com/questions/49889185/working-cefsharp-post-example?rq=1)

I followed the examples of the first 2 links, but when I open my modal, nothing happens.
Can you help me please ?

**Comment by amaitland** [comment]
https://stackoverflow.com/questions/57854081/how-send-post-data-with-cefsharp
