### ISSUE TITLE
Unable to run CefSharp.OffScreen from tests

### ISSUE THREAD

**Issue by rabejens** [cefsharp/CefSharp#2900]
- **What version of the product are you using?**

75.1.142.0    

- **What architecture x86 or x64?**

Both

- **On what operating system?**

Windows 10 x64

- **Are you using `WinForms`, `WPF` or `OffScreen`?**

OffScreen

- **What steps will reproduce the problem?**

1. Create a library targeting .net Framework 4.7.2
2. Set it to compile for `x86` or `x64`
3. Add `CefSharp.OffScreen`
4. Add this small class:

```csharp
using System;
using System.IO;
using CefSharp;
using CefSharp.OffScreen;

namespace Crash {

    public static class ReproduceCrash {

        public static void Reproduce() {
            CefSharpSettings.SubprocessExitIfParentProcessClosed = true;
            var settings = new CefSettings {
                BrowserSubprocessPath = Path.Combine(AppDomain.CurrentDomain.SetupInformation.ApplicationBase, "CefSharp.BrowserSubprocess.exe")
            };
            Cef.Initialize(settings, performDependencyCheck: true, browserProcessHandler: null);
        }
    }
}
```

5. Create a *Console Application* for .net 4.7.2
6. Add the `XUnit` dependencies:
```
coverlet.collector
Microsoft.NET.Test.Sdk
xunit
xunit.runner.visualstudio
```
7. Create a class which contains this unit test:
```csharp
[Fact]
public void Crashes() {
    ReproduceCrash.Reproduce();
}
```
8. Add `ReproduceCrash.Reproduce();` to `Program.cs`
9. Set a breakpoint on the `ReproduceCrash.Reproduce()` method
10. Run the test in `Debug` mode
11. Run the main program `Program.cs`

- **What is the expected output? What do you see instead?**

When running the test, I expect that I can single-step through the method without any problems, but when it comes to the line

```csharp
Cef.Initialize(settings, performDependencyCheck: true, browserProcessHandler: null);
```

I get this:

```
System.ArgumentException: 'Cannot pass a GCHandle across AppDomains.
Parameter name: handle'
```

When running the `Program.cs` directly, it works.

**Comment by amaitland** [comment]
Duplicate #351 

This is a limitation of Visual C++

**Comment by jankurianski** [comment]
Nunit's console runner works using `--domain=None --inprocess`.  See my comment here: https://github.com/cefsharp/CefSharp/issues/700#issuecomment-297209620

**Comment by rabejens** [comment]
The funny thing is, when I use the NETCore3 version, it works from xUnit tests. Unfortunately I can't use it in my case, because the website I need to remote control includes a file upload which I have to automate using UIAutomation.

**Comment by amaitland** [comment]
.Net Core doesn't support creating additional AppDomains as per https://docs.microsoft.com/en-us/dotnet/core/porting/net-framework-tech-unavailable#appdomains

Any test framework that supports .Net Core should be usable with CefSharp when run from .Net Core.

**Comment by captainjono** [comment]
I have patched Nunit v2 to run unit tests in a single app-domain to make it compatible with CEF & Test Explorer. No console runner required, make sure CEF .dlls copy to output dir.

Feel free to use it or use its code to patch an existing runner. No warrenty.
[Janison.Nunit.TestAdapter.zip](https://github.com/cefsharp/CefSharp/files/4353159/Janison.Nunit.TestAdapter.zip)

**Comment by amaitland** [comment]
It's possible to use `XUnit 2` without modification, even with the `VS2017/2019` test runners.

The [CefSharp.Test](https://github.com/cefsharp/CefSharp/tree/master/CefSharp.Test) project was recently updated to demo this. A few custom classes are required, all `UI` tests must be part of the same `Collection`.

Additional Libraries used
- https://github.com/StephenCleary/AsyncEx/wiki/AsyncContext#asynccontextthread-api
- https://github.com/AArnott/Xunit.StaFact

Code links with `CefSharp.Test` project.
- https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Test/CefSharpXunitTestFramework.cs#L8
- https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Test/app.config#L7
- https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Test/CefSharpFixture.cs
- https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Test/OffScreen/OffScreenBrowserBasicFacts.cs#L17

**Comment by captainjono** [comment]
Good to know! This info should be part of an intro guide to help others. No integrated testing was a deal-breaker for me.

**Comment by amaitland** [comment]
> Feel free to use it or use its code to patch an existing runner. No warrenty.
> [Janison.Nunit.TestAdapter.zip](https://github.com/cefsharp/CefSharp/files/4353159/Janison.Nunit.TestAdapter.zip)

A link to your `GitHub` fork would be better, you can upload a binary to the releases section. Just a link to a binary saying no warranty isn't very reassuring, it's not something I'd consider download. How am I supposed to fix any bugs with only a zip file?

It's something others might also be interested in contributing to, maintaining an active fork and keeping up to date.

> This info should be part of an intro guide to help others

Anyone with a `GitHub` account can edit the `Wiki`. I am actively trying to improve the documentation, contributions from users like yourself are required to cover the vast array of topics involved.

**Comment by captainjono** [comment]
I turned a dead-end into an option for someone. Now with your contribution, thats 2 options.

Sounds like I have done my part to further the community. This is how communities used to work before enterprises took over.
