### ISSUE TITLE
ResourceHandler - Reset Stream.Position when CanSeek

### ISSUE THREAD

**Issue by jpespartero** [cefsharp/CefSharp#2903]
- **What version of the product are you using?**
Nuget 75.1.142

- **What architecture x86 or x64?**
x64

- **On what operating system?**
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms

- **What steps will reproduce the problem?**
A custom ResourceHandler implementation that provides local memory images to the browser has stopped working correctly from the version 75.1.141.

The image is not displayed in the browser, but the ResourceHandler is providing the image stream.

The same code works fine up to version 73.1.30. Note that the interface has been updated to return a CefReturnValue instead of a bool.

` public override CefReturnValue ProcessRequestAsync(IRequest request, ICallback callback){

            var uri = new Uri(request.Url);
            string url = System.Net.WebUtility.UrlDecode(request.Url);
            Bitmap image = ...// Some code to get the image from memory
           
            if (image != null)
            {
                Stream = new MemoryStream();
                image.Save(Stream, ImageFormat.Png);
                MimeType = ResourceHandler.GetMimeType(".png");
            }

            callback.Continue();
            //return true;   // Up to version v73.1.30
            return CefReturnValue.Continue;   // From v75.1.141
        }`

- **What is the expected output? What do you see instead?**
Image displayed in the browser

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.
No exception is shown

    - Does the cef log provide any relevant information? 
No

**Comment by amaitland** [comment]
Testing with https://github.com/cefsharp/CefSharp/commit/58c9585894906930a80f8eaaad0b2026a79c8167 and loading https://cefsharp.example/logo.png in either the `WinForms` and `WPF` example and the `PNG` file loads correctly. If you look at https://github.com/cefsharp/CefSharp/releases/tag/v75.1.142 you will see there is exactly one commit to the `cefsharp/75` branch (the one referenced above).

I suspect what you are seeing is a subtle change in behaviour as part of the new `Network Service` changes, see #2743 

> Please no binary (zip, etc) links, fork the MinimalExample and push your changes to GitHub. (Alternatively use a code sharing service list Gist or Pastebin).

As per  https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report please provide an example that reproduces the problem, and incomplete code snippet is not sufficient.

**Comment by TKGNET** [comment]
I have the same issue as above: using a custom Request/ResourceRequestHandlerRIResonseFilter to access the Response payload. 
I used the CefSharp.Winforms.Example with the MemoryStreamFilter implementation with no url filtering. Debugging show following workflow

1.  ExampleResourceRequestHandler->GetResourceResponseFilter returns the MemoryStreamFilter and adds it to the dictionary.


1.

**Comment by amaitland** [comment]
@TKGNET Please fork the minimum example and push your changes to GitHub please.  Make sure to squash everything into a single commit,  thanks. 

What you are describing sounds like a bug in CEF.

**Comment by TKGNET** [comment]
OK, done. Hope its useful :  [Demo](https://github.com/TKGNET/CefSharp.MinimalExample)

**Comment by amaitland** [comment]
@TKGNET Where exactly in your code are you using a **ResourceHandler** to load an image?

**Comment by TKGNET** [comment]
JUst following the same procedure as in CefSharp-master.CefSharp.WinForms.Example:
1. `browser.settings.RequestHandler=new CustomRequestHandler` defines `customRequestHandler`
2. `CustomRequestHandler.GetResourceRequestHandler` returns `CustomResourceRequestHandler`
3. `CustomResourceRequestHandler.GetResourceResponseFilter` returns a MemoryStreamResponseFilter which is added to the dictionary. 
4. this filter copies data from the incoming stream to the internal memorystream. `bytes() memoryStream.Data=memoryStream.ToArray()` returns the byte array of the response payload, once the data has been loaded completed.
4. I would normally use `CustomResourceRequestHandler.OnResourceLoadComplete` to convert this data to either an image or text , depending an the `response.content-type`

What is wrong about this process ?

**Comment by amaitland** [comment]
> Where exactly in your code are you using a **ResourceHandler** to load an image?

@TKGNET I asked this because I'm after an example that reproduces this issue. Your code doesn't actually do that. You are using a `IResponseFilter` which is actually unrelated to this issue specifically. You need to make changes to adapt to the new `NetworkService` implementation, see https://github.com/cefsharp/CefSharp/issues/2743#issuecomment-536514264

**Comment by jpespartero** [comment]
sorry for the delay in the answer @amaitland. I have prepared an example project based on the WinForms minimal example.

https://github.com/jpespartero/CefSharp.MinimalExample

The ImageMemorySchemeHandler implemented contains a Dictionary with in-memory images and handles an url image request to provide the Stream and MimeType in the custom implementation of the ProcessRequestAsync method.

Maybe, I'm doing something wrong, but if load the image from a file in the Stream the image is displayed properly.

`{`
`byte[] bytes = File.ReadAllBytes(file);`
`Stream = new MemoryStream(bytes);`
`var fileExtension = Path.GetExtension(file);`
`MimeType = GetMimeType(fileExtension);`
`}`
`callback.Continue();`
`return CefReturnValue.Continue;`

**Comment by amaitland** [comment]
Thanks for the example 👍 

You need to reset the `Stream.Position = 0;` after you've saved the image to the `MemoryStream`. 

This is a regression in `CefSharp` and a `PR` would to reset the `Position` would be welcome.

Generally speaking it's best to reset `Stream.Position` after you've written to it, specially before you hand the stream over to a 3rd party library.

**Comment by jpespartero** [comment]
Thanks a lot for the quick response and the solution provided!
Yes, reseting the stream position solves the issue and the image is loaded properly. It is not a problem to do it once the image is saved, so from our side it is solved.
