### ISSUE TITLE
JSB - Invoke Method with UInt param throws InvalidOperationException

### ISSUE THREAD

**Issue by Reyien** [cefsharp/CefSharp#2906]
- **What version of the product are you using?** 
    Nuget 75.1.142
-  **What architecture x86 or x64?**
    x64
-    **On what operating system?**
    Windows 10 Home 1903
-    **Are you using WinForms, WPF or OffScreen?**
    WinForms
- **What steps will reproduce the problem?**
   Bind a .Net class with a method with uint parameter(s). Called bound function.
![image](https://user-images.githubusercontent.com/43173268/65584508-4b620100-df81-11e9-80ca-82e83bf71d09.png)

**Comment by amaitland** [comment]
Please no images of stack-traces, it's hard to read specially on a small screen, I cannot copy and paste either. In general no images of exceptions, see http://idownvotedbecau.se/imageofanexception/ for further details on the subject.

**Comment by Reyien** [comment]
Sorry for that. The exception is : System.ArgumentException: Unable to cast object of type 'System.Int32' to type 'System.UInt32'.

For instance I have a function like `uint Add(uint a, uint b)`, I bind a class with this method and when I call it in Javascript I have this exception.

**Comment by amaitland** [comment]
Much better, thanks 👍 

In `JavaScript` there is no specific support for `UInt` that I'm aware of. Reference being https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types

`CEF` does support `UInt` partly via [CefV8Value::IsUInt](https://magpcss.org/ceforum/apidocs3/projects/(default)/CefV8Value.html#IsUInt()). Unfortunately there is no support for `UInt` in the `IPC` implementation that's used to pass values from the render process to the browser process. For reference see https://magpcss.org/ceforum/apidocs3/projects/(default)/CefListValue.html

Even if we added an `IsUInt` check there's no way to get a `UInt` out of the render process without adding some hacks and potentially breaking existing code. So I'm ruling this out as an option.

The default method invocation performs no specific type conversions, just whatever `.Net` performs implicitly. For performance reasons this is unlikely to change.

You can use an `IBinder` to perform type conversions, there's a default implementation. The only caveat is that the binder is only called for lists/dictionaries/objects.

http://cefsharp.github.io/api/75.1.x/html/T_CefSharp_ModelBinding_DefaultBinder.htm
http://cefsharp.github.io/api/75.1.x/html/P_CefSharp_BindingOptions_Binder.htm

You can change your code to look roughly like

```c#
browser.RegisterJsObject("myObject", new BoundObject(), options: BindingOptions.DefaultBinder);

public class AddRequest
{
  public uint A {get;set;}
  public uint B {get;set;}
}

public class BoundObject
{
  public uint Add(AddRequest request)
  {
    var a = request.A;
    var b = request.B;
  }
}
```

```js
myObject.Add({ A: 1234, B: 1234 });
```

**Comment by Reyien** [comment]
Thanks for all the infos.

I tried your last suggestion code with `JavascriptObjectRepository.Register` and it gives me another Exception : 
> System.ArgumentNullException : value cannot be null.
> at System.Linq.Enumerable.ElementAtOrDefault[TSource](IEnumerable`1 source, Int32 index)
>at CefSharp.ModelBinding.DefaultBinder.Bind(Object obj, Type modelType) dans C:\projects\cefsharp\CefSharp\ModelBinding\DefaultBinder.cs:ligne 114
>at CefSharp.Internals.JavascriptObjectRepository.TryCallMethod(Int64 objectId, String name, Object[] parameters, Object& result, String& exception)
It appears that the binder "misguess" type and try to retrieve values from a List whereas it appears to be a Dictionary.

**Comment by amaitland** [comment]
> It appears that the binder "misguess" type and try to retrieve values from a List whereas it appears to be a Dictionary.

There's no guessing, it takes the types it's given. Error would suggest you are passing in a list(array) instead of an object.

Added an example in https://github.com/cefsharp/CefSharp/commit/6ead2b33f830066caca2192f2883fdb35aad0bb2 and it works as expected.

**Comment by amaitland** [comment]
With the changes in #2908 it'll be possible to use a binder to perform the conversion without having to specify a complex model. A demo of both was added to `master` in https://github.com/cefsharp/CefSharp/commit/e438e22741a790071761bba085fb8395868ad21c

Changes will be in version `77`
