### ISSUE TITLE
cannot compile latest stable code in VS 2019

### ISSUE THREAD

**Issue by billwoo** [cefsharp/CefSharp#2912]
https://www.dropbox.com/s/6cruq3oycn2wvx5/CEF_build_error.jpg?dl=0

Presents dialog demanding FW 4.6.1 even though this is installed. After re-installing the 4.6.1 dev pack: presents dialog to upgrade C libraries.

Unusable.

**Comment by amaitland** [comment]
Duplicate of #2628

**Comment by amaitland** [comment]
For testing purposes use https://github.com/cefsharp/CefSharp.MinimalExample
