### ISSUE TITLE
by not warning CEF is not usable with VS 2019 and closing bug-reports

### ISSUE THREAD

**Issue by billwoo** [cefsharp/CefSharp#2913]
issue #2912, opened today, was closed, and I was referred to another issue dating back to January.

You not only waste the time of those who took the trouble to file a bug-report, you also condemn other future users who will reasonably assume the project can be used in VS 2019 to waste their time.

How about putting specific compile directions on the project home page ?

**Comment by amaitland** [comment]
If you are having problems with building with VS2019 then you can discuss the issue on https://github.com/cefsharp/CefSharp/issues/2628

This issue will be deleted as it adds no value.
