### ISSUE TITLE
CEF WinForm installed from NuGet not usable iin VS 2019

### ISSUE THREAD

**Issue by billwoo** [cefsharp/CefSharp#2914]
> Error: CefSharp.Common contains unmanaged resoures, set your project and solution platform to x86 or x64. Alternatively for AnyCPU Support see https://github.com/cefsharp/CefSharp/issues/1714	CEFTest		

I have tried setting the Project/Solution to  both x64, and x86: I continue to get this message.

Note that in VS 2019 you cannot set the Solution build to x86: the only choices are x64 and 'AnyCPU.	

I have read the ancient manuscript 1714 in closed bugs: it is unclear what it means today.

Once again, CEF is unusable.

**Comment by Geevo** [comment]
Hi, I run all my projects in VS2019 without a hitch. 
Are you sure you correctly configured the Platform in configuration manager within your project?

Keep in mind you have to configure these yourself when you create a new project.

![image](https://user-images.githubusercontent.com/14214341/65871631-bf801880-e376-11e9-8760-d76bccf290e9.png)

**Comment by amaitland** [comment]
> I have tried setting the Project/Solution to both x64, and x86: I continue to get this message.

You must change the `Active Solution Platform` to either `x86` or `x64` as detailed in https://docs.microsoft.com/en-us/visualstudio/ide/how-to-configure-projects-to-target-platforms?view=vs-2019#target-platforms-with-the-configuration-manager.

Seems most likely you've only changed the `project` target, not the solution target. (Yes this is a limitation of the current package structure)

> Note that in VS 2019 you cannot set the Solution build to x86: the only choices are x64 and 'AnyCPU

I believe this is incorrect, you just need to create a new `x86` platform using the `New Solution Platform` dialog as detailed in the link above.

> I have read the ancient manuscript 1714 in closed bugs: it is unclear what it means today.

Not sure why you think age is relevant here. There are three options listed, choose whichever one suites your requirements. 

If you have any further questions please ask them on https://gitter.im/cefsharp/CefSharp or post on https://stackoverflow.com/questions/tagged/cefsharp
