### ISSUE TITLE
White screen on https pages without valid certificate

### ISSUE THREAD

**Issue by hanbogdan1** [cefsharp/CefSharp#2920]
- **What version of the product are you using?**
    CefSharp.Wpf version 75.1.142.0 - Nuget on VS 2017

- **What architecture x86 or x64?**
    x64

- **On what operating system?**
    - Win7, Win 8, Win10, etc?

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WPF

- **What steps will reproduce the problem?**
    
   I'm using browser.Address = url;
   where the url is https without a valid certificate

- **What is the expected output? What do you see instead?**
   The browser page is white.

- **Please provide any additional information below.**

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
      No info there.

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
     No.

**Comment by amaitland** [comment]
This is not a bug, if the certificate is invalid displaying an error page is up to you.

See https://github.com/cefsharp/CefSharp/blob/cefsharp/75/CefSharp.Wpf.Example/Views/BrowserTabView.xaml.cs#L132 for a rough example.
