### ISSUE TITLE
Certain site (like youtube.com) has a high likelyhood of causing the render process to crash (upstream issue)

### ISSUE THREAD

**Issue by mitchcapper** [cefsharp/CefSharp#2921]
Just navigating to sites like https://www.youtube.com/ can cause the render process to crash.   It seems like it started in v76.
https://bitbucket.org/chromiumembedded/cef/issues/2742/cefclient-basic-tests-get-source-and-get

Interestingly reloading the instance with the old context will then work.
Mainly posting here as a known issue, as I assume others will hit once stable is updated.

**Comment by amaitland** [comment]
Similar reports

- https://bitbucket.org/chromiumembedded/cef/issues/2781/strange-behaviour-in-cefsimple-when
- https://bitbucket.org/chromiumembedded/cef/issues/2779/http-x-frame-options-deny-header-makes-the

**Comment by mitchcapper** [comment]
Ugh! Well thanks.   After reviewing all the bugs the issue just lies in the cefclient sample and the code I was using.  Stupidly next to my code I had a comment of `//maybe see: https://github.com/cefsharp/CefSharp/commit/6f6ca94ea9bc12b332e6fdb96c5b40b95b50dff5`  just turns out I was too slow to do so.   Moral of the story is to use the new LoadHtml per cefsharp samples for errors.

**Comment by amaitland** [comment]
For reference `CEF` has removed `CefFrame::LoadString` in https://bitbucket.org/chromiumembedded/cef/commits/18b5f727017ba0d5816687536cbeefe4b640c9ef

So `IFrame.LoadStringForUrl` will be removed once we upgrade to version `78`.
