### ISSUE TITLE
Open the animation-containing web page, WPF version and WinForm version CPU difference is very large, I locally same page WPF version CPU is twice as used as Winform

### ISSUE THREAD

**Issue by icelee1987** [cefsharp/CefSharp#2926]
### Bug Report

- **What version of the product are you using?**
    - v75.1.142
    - downloaded from https://github.com/cefsharp/CefSharp/releases/tag/v75.1.142

- **What architecture x86 or x64?**
   - x86

- **On what operating system?**
    - Win7, Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
  - `WinForms`, `WPF`

- **What steps will reproduce the problem?**
    - Open the high cpu web page (such as ：www.ezcarry.com) with the WPF version and the WinForm version, respectively, and compare the CPU usage to see that the wpf version CPU is more than twice as large as winform.

- **What is the expected output? What do you see instead?**
  - Wpf version CPU occupancy, can achieve the Winform effect

**Comment by amaitland** [comment]
You can try the `--disable-gpu-compositing` command line argument. #2770 will need to be implemented to greatly improve the performance.

For background see https://github.com/cefsharp/CefSharp/wiki/General-Usage#offscreen-rendering-osr

**Comment by amaitland** [comment]
Looks like version `75` already has [disable-gpu-compositing](https://github.com/cefsharp/CefSharp/blob/cefsharp/75/CefSharp.Wpf/CefSettings.cs#L29) set by default
