### ISSUE TITLE
Feature Request - Add BrowserSubProcess DpiAwareness Option

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#2927]
Currently the default `DPI Awareness` is `true/PM`, this won't suite everyone.

- [ ] ~~Add `CefSharpSettings` option to allow for a new command line arg to be appended~~
- [x] Change default to `PerMonitorV2`???

- Both browser process and `GPU` process (`Chrome` doesn't appear to worry about `render` processes) must have a matching awareness.
- `app.manifest` setting takes priority over `Cef.EnableHighDPISupport();`
- `Chrome` defaults to `PerMonitorV2`, we currently use `PerMonitor`

https://docs.microsoft.com/en-us/windows/win32/hidpi/high-dpi-desktop-application-development-on-windows

**UPDATE** 
`Chromium` now sets the `DPI Awareness` to `PermonitorV2` by default. You can override this via `app.manifest` or via programmatic call. #4410

**Comment by amaitland** [comment]
Should also add note that `DPI Awareness` for a process can be viewed in `Task Manager` on `Win10`

**Comment by amaitland** [comment]
It might make sense to default the browsersubprocess DPI awareness to that of the main application,  see how feasible that is.

**Comment by amaitland** [comment]
https://github.com/microsoft/Windows-classic-samples/blob/master/Samples/DPIAwarenessPerWindow/client/DpiAwarenessContext.cpp

**Comment by amaitland** [comment]
Bumping this to the `81` milestone as it would be a stretch to adequately test.

As a short-term workaround use the `--disable-gpu-compositing` command line arg and the `DPI Settings` of your main application process will be used instead of the `DPI Awareness` specified by the `GPU Process`.

**Comment by amaitland** [comment]
`Chromium` only enables `DPI Awareness` for the main process and `GPU` process
https://cs.chromium.org/chromium/src/chrome/app/chrome_exe_main_win.cc?type=cs&q=base::win::EnableHighDPISupport&sq=package:chromium&g=0&l=225

https://cs.chromium.org/chromium/src/base/win/win_util.cc?type=cs&q=base::win::EnableHighDPISupport&sq=package:chromium&g=0&l=703

**Comment by amaitland** [comment]
Documentation rewrite add reference to https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/mt846517(v%3Dvs.85)#setting-default-awareness-with-the-application-manifest

**Comment by amaitland** [comment]
The `General Usage Guide` has been updated see https://github.com/cefsharp/CefSharp/wiki/General-Usage/_compare/69741e80118da403d7c086695965427869164f1e...592d4fae743f567a30126e6f03c5f92faf9c6f59

Once this feature has been complete additional details will need to be added.

**Comment by cwollenhaupt** [comment]
FYI, I fixed this issue for my projects by modifying the manifest in CefSharp.BrowserSubprocess.EXE to match my main applications DPI awareness. I gave the EXE a different name and set the BrowserSubprocessPath property accordingly.

**Comment by amaitland** [comment]
Be careful copying the Browsersubprocess and renaming it as I've seen previous cases where antivirus software have flagged the exe as suspicious. Much safer to create your own exe or self host the browser sub process using https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/BrowserSubprocess/SelfHost.cs#L22

Same code can be used to create own exe.

**Comment by cwollenhaupt** [comment]
Good to know, thanks for the heads up!

**Comment by amaitland** [comment]
Changes in `Chromium` (#4410) mean that the `Browser` and `GPU` processes will now be `PerMonitorV2` by default, 

You can override the `Chromium` default via setting the awareness in your `app.manifest` or programmatically.

The `BrowserSubProcess` will use the `Chromium` defaults starting from `M111` (commit https://github.com/cefsharp/CefSharp/commit/b17cd2a1b23df786c1051c7c66947f6d52239510)

The interesting side-effect of this change is that it would appear that when set **programmatically** then the `GPU` process will mirror the awareness of the browser process (by default this is your application).

So starting in `M111` you should be able to [PInvoke](https://www.nuget.org/packages/PInvoke.SHCore) the awareness in your application and `Chromium` should respect your awareness.

```c#
SHCore.SetProcessDpiAwareness(PROCESS_DPI_AWARENESS.PROCESS_DPI_UNAWARE);
```

Only seems to work when set **programmatically**. If for some reason this doesn't work then `Self Hosting` the `BrowserSubProcess` will allow complete control.

There are new more detailed instructions at https://github.com/cefsharp/CefSharp/wiki/SelfHost-BrowserSubProcess

**Comment by amaitland** [comment]
Setting `PerMonitorV2` using [PInvoke.User32](https://www.nuget.org/packages/PInvoke.User32) should look something like:

```c#
User32.SetThreadDpiAwarenessContext(User32.DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2);
```

**Comment by davidei1955** [comment]
FWIW, I am seeing this issue in .Net 8.0 Core Winforms on Windows 10 when the display is set to 125% (but not when set to 100%). I don't see it at all on Windows 11. The fix for me was to delete app.manifest, then recreate it in Visual Studio, and uncomment  the

   <application xmlns="urn:schemas-microsoft-com:asm.v3">
       <windowsSettings>
         <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</dpiAware>
        <longPathAware xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">true</longPathAware>
      </windowsSettings>
   </application>

section in the new app.manifest

**Comment by amaitland** [comment]
> You can override the Chromium default via setting the awareness in your app.manifest or programmatically.

To revise this statement in the context of **WinForms**. Setting `DPI Awareness` via `app.manifest` is no longer recommended when using  `.Net 4.8` or greater (this includes newer versions including `.Net 8.0`).

See https://learn.microsoft.com/en-us/dotnet/desktop/winforms/wfdev-diagnostics/wfac010?view=netdesktop-8.0 for Microsoft guidance regarding the compiler warning that will be raised.

Starting in `.Net Core 3.0` you can use the WinForms specific API. Some examples (refer to the Microsoft documentation for more details)

```c#
Application.SetHighDpiMode(HighDpiMode.DpiUnaware);
Application.SetHighDpiMode(HighDpiMode.DpiUnawareGdiScaled);
Application.SetHighDpiMode(HighDpiMode.SystemAware);
Application.SetHighDpiMode(HighDpiMode.PerMonitor);
Application.SetHighDpiMode(HighDpiMode.PerMonitorV2);
```

https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.application.sethighdpimode?view=windowsdesktop-8.0

**Comment by davidei1955** [comment]
I was just hunting down down the compiler warning when I saw your post. Adding
`Application.SetHighDpiMode(HighDpiMode.SystemAware);`
 To may main() also resolved the issue.
