### ISSUE TITLE
Loading the page error or displaying the specified error html prompt when there is no network, the network normal after clicking Reload did not respond, hoping to successfully load the page

### ISSUE THREAD

**Issue by icelee1987** [cefsharp/CefSharp#2931]
- What version of the product are you using?

75.1.142

-Are you using WinForms, WPF or OffScreen?

WPF

- On what operating system?

Win7, Win10

- What steps will reproduce the problem?
I open a web page when I don't have an Internet network, The WebBrowser.LoadError event is triggered, the browser will load the specified html prompt information, when the network is normal, I click the Reload button, reload the page, but still show the html information when the previous loading error, can not load the specified website properly;

I just modified the following code in CefSharp.Wpf.Example.Views.BrowserTabView.cs: I'll code "args. Frame.LoadHtml (errorBody, base64Encode: true); Replaced with "browser. LoadHtml (errorBody, args.) Failed Url);

How can i do this. Thanks over much

**Comment by icelee1987** [comment]
> 👋 @icelee1987, we use the issue tracker exclusively for bug reports and feature requests. However, this issue appears to be a support request. Please use our support channels to get help with the project. 
> If you have a question, ask it on [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`). 
> If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage 
> If you feel this was closed in error then you **must** edit your original issue and complete the [Bug Report Template](https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report) then post a comment asking for a review.

I don't understand the result of this treatment, do you mean this needs cef to provide this support? Thank you

**Comment by amaitland** [comment]
> How can i do this.

You have asked a **question**, which is fine. This just isn't the place to ask it. This issue tracker is for `CefSharp` **specific** bugs. 

> or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

There are many wrappers around the [Chromium Embedded Framework](https://bitbucket.org/chromiumembedded/cef/overview). Having each wrapper provide a `forum/issue tracker` for users to ask support questions is impractical.

Dealing with transitioning between `offline` and `online` is not `CefSharp` specific. There's a high chance the question has been asked on https://magpcss.org/ceforum/index.php If you cannot find an answer then ask your question there.

**Comment by amaitland** [comment]
> Replaced with "browser. LoadHtml (errorBody, args.) Failed Url);

A very quick review of your modification and it's incorrect, for every subsequent navigation to `args.FailedUrl` you will have `errorBody` displayed. You should use the following instead. Only the first `navigation` will load `errorBody` as `oneTimeUse` is `true`, subsiquent navigations will attempt a normal network load.

```c#
browser.LoadHtml(errorBody, args.FailedUrl, System.Text.Encoding.UTF8, oneTimeUse: true);
```

http://cefsharp.github.io/api/75.1.x/html/M_CefSharp_WebBrowserExtensions_LoadHtml_3.htm

In future if you have a question please ask on one of the options listed above.

**Comment by icelee1987** [comment]
> > Replaced with "browser. LoadHtml (errorBody, args.) Failed Url);
> 
> A very quick review of your modification and it's incorrect, for every subsequent navigation to `args.FailedUrl` you will have `errorBody` displayed. You should use the following instead. Only the first `navigation` will load `errorBody` as `oneTimeUse` is `true`, subsiquent navigations will attempt a normal network load.
> 
> ```cs
> browser.LoadHtml(errorBody, args.FailedUrl, System.Text.Encoding.UTF8, oneTimeUse: true);
> ```
> 
> http://cefsharp.github.io/api/75.1.x/html/M_CefSharp_WebBrowserExtensions_LoadHtml_3.htm
> 
> In future if you have a question please ask on one of the options listed above.

Thank you very much.
