### ISSUE TITLE
Loading CefSharp into a Winforms C# project via NuGet corrupts project

### ISSUE THREAD

**Issue by SimonKravis** [cefsharp/CefSharp#2934]
- **What version of the product are you using?**
    -The version of Cfesharp.Winforms available on Nuget. 75.11.42

- **What architecture x86 or x64?**
x64

- **On what operating system?**
  Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms

- **What steps will reproduce the problem?**
    Click on Install CefSharp.Winforms from Nuget. Visual Studio 2013 appears to install a number of components then crashes.
- **What is the expected output? What do you see instead?**
When I restarted the project I expect that some references will be added to the project reference list. Instead, all references except those in the solution have a yellow triangle added to them. No forms can be viewed in design mode.

- **Please provide any additional information below.**
  
    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

**Comment by amaitland** [comment]
Try with https://github.com/cefsharp/CefSharp.MinimalExample

Seems more likely a problem with your environment, I've never heard of Visual Studio crashing before. 

Also make sure you follow the post build instructions https://github.com/cefsharp/CefSharp/blob/master/NuGet/Readme.txt#L10

**Comment by SimonKravis** [comment]
The Nuget installer for CefSharp does not add any references to the project when I add it on another system under VS 2017.

**Comment by amaitland** [comment]
Please confirm you've followed the post installation instructions linked above. If you are targeting AnyCpu which is the default you'll need to follow those specific instructions. 

Restarting Visual Studio is also often required https://github.com/cefsharp/CefSharp/blob/master/NuGet/Readme.txt#L12

**Comment by SimonKravis** [comment]
Yes, I didn't restart VS as per the instructions. When I did that the Minimal Example project for Winforms worked OK after upgrading to VS 2019. However - I have a new problem - embedded videos in html files used as Chromium Web Browser parameters don't show up.  The html file Tom.html contains the following:
` <html>
<body>
<video controls width="500" controls Autoplay=autoplay>

    <source src="file:///C:/Users/Simon/Pictures/Videos/Tom.MOV"
            type="video/mp4">

    Sorry, your browser doesn't support embedded videos.
</video><br />
Caption
<body>
</html>`
This file an be opened by Chrome on the desktop and the video appears OK. However, try and view it with C# in a WinForms project in the Minimal example with the line 
`browser = new ChromiumWebBrowser("file:///C:/Users/Simon/Pictures/Videos/Tom.html")`
The video does not appear - just a black rectangle with unresponsive controls. The word "Caption" appears OK.

**Comment by amaitland** [comment]
Only freely available audio and video codecs are supported see https://github.com/cefsharp/CefSharp/wiki/General-Usage#multimedia-audiovideo

If you have further questions please use one of the options listed at https://github.com/cefsharp/CefSharp#contact
