### ISSUE TITLE
What are the ways or changes to make CefSharp support to play mp4 file?

### ISSUE THREAD

**Issue by Balrammca** [cefsharp/CefSharp#2935]
Currently my product using CefSharp version 71.0.20.0. It is working fine for play mp3 file but mp4 file is not working.
In the multiple sites, it is mentioned that need to propriety codec support and build Cef. Can anyone tell me what are the steps and changes to reuired for play mp4 file.

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/wiki/General-Usage#multimedia-audiovideo
