### ISSUE TITLE
mp4 file not playing in CEF

### ISSUE THREAD

**Issue by Balrammca** [cefsharp/CefSharp#2936]
- **What version of the product are you using?**
    - What version are you using? 	**71.0.2.0**
    - Nuget? CI Nuget? build from a branch?  **Nuget**
  
- **What architecture x86 or x64?**
      - **x86**
- **On what operating system?**
    - **Win10**

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
     - **WPF**
- **What steps will reproduce the problem?**
    - Download any release from https://github.com/cefsharp/CefSharp/releases Or CEF application or cefclient windows and enter the URL https://file-examples.com/wp-content/uploads/2017/04/file_example_MP4_480_1_5MG.mp4.File is not playing in CEF but if you hit in the browser It is playing

- **What is the expected output? What do you see instead?**
     - It should play successfully.
- **Please provide any additional information below.**
    - [1018/145353.649:ERROR:render_media_log.cc(27)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"FFmpegDemuxer: no supported streams"}
    - [1018/145353.663:ERROR:render_media_log.cc(27)] MediaEvent: PIPELINE_ERROR DEMUXER_ERROR_NO_SUPPORTED_STREAMS

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

    - Yes, It is reproducible in all the version of CEF.
    -Tested version  : cef_binary_77.1.13+g676b147+chromium-77.0.3865.90_windows64_client

**Comment by amaitland** [comment]
As stated in https://github.com/cefsharp/CefSharp/wiki/General-Usage#multimedia-audiovideo only freely available codecs are supported. 

Please stop opening issues. This is not a bug.
