### ISSUE TITLE
Discord stuck on RTC Connecting

### ISSUE THREAD

**Issue by JarHeadgamer** [cefsharp/CefSharp#2938]
Whenever I try to join a voice call in discord on my CefSharp browser it gets stuck on RTC Connecting. Is this a known bug? Is there any way to fix it?

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp.MinimalExample/blob/master/CefSharp.MinimalExample.WinForms/Program.cs#L32 4an example of enabling WebRTC.

**Comment by K0nfy** [comment]
Same problem on modern Chrome browser. Resolved with extension "WebRTC Control" -> off leak protection.

**Comment by JosephPall** [comment]
If <a href="  [fontbots.com/discord-font-generator/](https://fontbots.com/discord-font-generator/) " >discord</a> is stuck on "RTC Connecting," it indicates an issue with the voice connection. Here are a few steps you can try to resolve the problem:

Check your internet connection: Ensure that you have a stable internet connection by visiting other websites or using other online services.

Restart Discord: Close the Discord application completely and relaunch it. Sometimes, this simple step can resolve temporary connection issues.

Check Discord's server status: Visit the Discord Status website (status.discord.com) to check if there are any ongoing server issues or outages that may be causing the problem. If there is an issue on Discord's end, you may need to wait until it's resolved.

Update Discord: Make sure you have the latest version of Discord installed on your device. Outdated versions may have compatibility issues or bugs that can cause connection problems.
