### ISSUE TITLE
CefSharp.Wpf.Example rendering issue on window resizing

### ISSUE THREAD

**Issue by janghaksang** [cefsharp/CefSharp#2939]
### Bug Report
Delete this line and everything above, and then fill in the details below.

- **What version of the product are you using?**
    - What version are you using? Nuget? CI Nuget? build from a branch? If so which branch? Please include the exact version number you are using (no ambiguous statements like `Latest from Nuget`)
e.g. 57.0.0 or 63.0.0-pre01
    - Please only create an issue if you can reproduce the problem with the latest version. (If you are using the latest stable release please check to see if there is a newer `-pre` release and test with that also).

master branch (2019/10/21 18:48:22) 441e8bc8cb9204576065f231ed483bca7fed95a3 [441e8bc]

- **What architecture x86 or x64?**
x64
vs2017 15.9.16
NET Framework 4.5.2
winsdk 10.0.18362.0 (installed, but not applied in project)

- **On what operating system?**
    - Win7, Win 8, Win10, etc?
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF (default wpf example)

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.
    - Please no binary (zip, etc) links, fork the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) and push your changes to `GitHub`. (Alternatively use a code sharing service list `Gist` or `Pastebin`).
1. execute
2. window resize (size down)

- **What is the expected output? What do you see instead?**
![image](https://user-images.githubusercontent.com/19608894/67260589-150f9700-f4d7-11e9-840b-a5892afaf6fb.png)

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

    - To compare with WPF run cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu
    - To compare with WinForms run cefclient --multi-threaded-message-loop
    - If you can reproduce the problem with `cefclient` then you'll need to report the bug on https://bitbucket.org/chromiumembedded/cef/overview there is no point opening an issue here. (Make sure you search before opening an issue)
    - Please include the version you tested with e.g. `cef_binary_3.3029.1611.g44e39a8_windows64_client.tar.bz2`. It's important to you test with the same version that `CefSharp` is based on. Check the release notes to determine the version (https://github.com/cefsharp/CefSharp/releases) or load `chrome://version` in the browser.

**Comment by amaitland** [comment]
Closing as upstream see https://bitbucket.org/chromiumembedded/cef/issues/2733/viz-osr-might-be-causing-some-graphic

Please test with the CEF Sample application before opening issues in future please.

**Comment by amaitland** [comment]
There are also lots of other upstream rendering issues currently,  see #2925
