### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by 29683747** [cefsharp/CefSharp#2941]
What's the solution to this problem when the JS object registered after I finished "Controls.Add(browser)" is always undefined on the web page? The code is as follows:

            browser.RegisterJsObject("obj1", new obj1(), new BindingOptions()
            {
                CamelCaseJavascriptNames = false
            });
            this.Controls.Add(browser);

            browser.RegisterJsObject("obj2", new obj2(), new BindingOptions()
            {
                CamelCaseJavascriptNames = false
            });

**Comment by amaitland** [comment]
Please read https://github.com/cefsharp/CefSharp/wiki/General-Usage#3-how-do-you-expose-a-net-class-to-javascript

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp.MinimalExample/commit/2febd683b9e9f08e19aab68b575bae8b349c0ba5 for a working set of examples.
