### ISSUE TITLE
DLL files from v49 release

### ISSUE THREAD

**Issue by sirjo66** [cefsharp/CefSharp#2942]
Hello,

I would like to use `CefSharp v49` since I need to use your package with `.NET 4.0`. When I download it I have all the source code but it is not compiled (e.g., I need the `.dll` files). How do I obtain these files?

Thanks,
Sergio

**Comment by amaitland** [comment]
Every CefSharp release is available on Nuget.org even older versions. 

https://www.nuget.org/profiles/amaitland

Using such an old version is not supported,  I would suggest you look at other options. 

I believe CefGlue targets .Net 4.0 still, that would be my recommendation https://gitlab.com/xiliumhq/chromiumembedded/cefglue

If you have to use CefSharp then there is an unofficial fork at https://github.com/emisgroup/CefSharp.Net40

**Comment by sirjo66** [comment]
Many thanks.
.... but I can't found it  :-(
I find many package, also old version, but I can't find a package with DLL inside, only source code.
I use VB.NET, so I can't compile a C#/C++ package

**Comment by amaitland** [comment]
Install the relevant WinForms/WPF/OffScreen package using the Nuget package manager. Follow the post installation instructions outlined in the Readme.txt  that's opened post installation. 

Please ask any further questions on stackoverflow as that's the appropriate support channel.
