### ISSUE TITLE
Not able to play WebRTC based video

### ISSUE THREAD

**Issue by rameedev** [cefsharp/CefSharp#2943]
### I am using Ant media Server and it publishes WebRTC uri's for consumption by clients.The browser control is not able to play this video

I have tested this url in all the browsers (Edge,FireFox and Chrome) and they all are able to play this.

Not sure if this has anything to do with how Ant Media server publishes the url. It in-turn uses flowplayer for playing the video.

Use the following url for your testing and re-produce the error -- https://demos.flowplayer.com/plugins/hlsjs.html.

![Chromium_Error](https://user-images.githubusercontent.com/9818433/67556187-52229600-f730-11e9-92e8-2aa199bcb043.png)

If this needs to go under new feature then let me know. i will post it there.

**Comment by amaitland** [comment]
Only freely available audio/video formats are supported see https://github.com/cefsharp/CefSharp/wiki/General-Usage#multimedia-audiovideo
