### ISSUE TITLE
Win10 does not execute the OnImeCompositionRangeChanged method

### ISSUE THREAD

**Issue by haotongxuehs17952** [cefsharp/CefSharp#2945]
Win10 does not execute the OnImeCompositionRangeChanged method on CefSharp75 for wpf.
Win7 is OK!

**Comment by amaitland** [comment]
Please fill out the bug report template provided at https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report

**Comment by amaitland** [comment]
Upstream issue  https://bitbucket.org/chromiumembedded/cef/issues/2845/wrong-ime-window-position-in-osr-mode-with
