### ISSUE TITLE
WPF - Input control title displays incorrectly

### ISSUE THREAD

**Issue by ghudspith** [cefsharp/CefSharp#2950]
We have recently upgraded CefSharp v57.0.0 to v75.1.142 for WPF

Now, input controls do not correctly display the tooltip
<input type="image" id="id1" value="id1" class="toolimage" src="img/id1.png" title="id1 tooltip">

Instead they display "System.Windows.Controls.TextBlock"

Looking at the issues list, it appears WinForms have a similar issue but adding a manifest file does not appear to make any difference
Any help appreciated

Thanks

**Comment by amaitland** [comment]
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

**Comment by ghudspith** [comment]
Apologies for not using the bug template previously

**What version of the product are you using?**
v75.1.142

**What architecture x86 or x64?**
x86

**On what operating system?**
Win10

**Are you using WinForms, WPF or OffScreen?**
WPF

**What steps will reproduce the problem?**
Display an input control with a title property and hover over the control

**What is the expected output? What do you see instead?**
Tooltip should display value in title.  Instead always see "System.Windows.Controls.TextBlock"

**Please provide any additional information below.**
Tooltips do display correctly when using v57.0.0

**Does this problem also occur in the CEF Sample Application from**
No (no tooltips are displayed at all in the CEF Sample application)

**Comment by amaitland** [comment]
Please test with https://github.com/cefsharp/CefSharp.MinimalExample

I suspect your application is changing the default WPF tooltips style

**Comment by amaitland** [comment]
Loading https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_global_title in https://github.com/cefsharp/CefSharp.MinimalExample using commit https://github.com/cefsharp/CefSharp.MinimalExample/commit/c03e51151deb6ab31e84163635609583087220d7

The tooltip (title) displays as expected.

**Comment by ghudspith** [comment]
Hi
Many thanks for your help.  Yes, my WPF app does change the default tooltip style and removing this does allow the title value to be displayed correctly.
One final question, using a changed default tooltip style was working up to V67.0.0, is there are reason this is was changed?

**Comment by amaitland** [comment]
#2488 is the relevant issue, ideally the tooltip would be styled in xaml. Pull request with improvements welcome.
