### ISSUE TITLE
Memory Increase after loading script

### ISSUE THREAD

**Issue by bbday** [cefsharp/CefSharp#2951]
CefSharp.OffScreen.75.1.142 x64 

just loading this html then memory usage go until 4gb then crash, on chrome/firefox no issue.

######
string html = @"<html><head><script src='https://ea-api.arkoselabs.com/fc/api/?onload=loadFunCaptcha' async defer></script></head>
<body>
<script type = 'text/javascript'>
     var blob = 'm7++bOFGILKX5bMF.omV4SaqF8mPsFkpNsaKC6uVPcVujQn9YgXU1Hj92Af0MVRATmtDanPlr8AAiIORhQxTSD9+bw+iXq0ld19QOrn/q/QheQ4PAs8GPjLmrUmM+K1gXIjnaDaVf2uwsa5v717XkkcR0MHz+rpUWbXaOlgREoMU2/trbkYAvNlTQvyDVeEDzmPJ4NdiVp6qJlY1ktKfDnK0BBwBHoFiHeM7jHhW93CdFdW1A1Xn/fFt0pxVLeT6g7VmBBGufEaNYDNI=';
            var key = 'A4EECF77-AC87-8C8D-5754-BF882F72063B';

            function loadFunCaptcha()
            {
                new FunCaptcha({
            'public_key': key,
			'data': { 'blob':blob},
			'language': 'en',
            'callback': captchaCompletedCallback,          
        });
    }

    //Only When succeffuly
    function captchaCompletedCallback()
    {
        var t = document.getElementById('FunCaptcha-Token').value
        console.log(t);
    }
</script><div id='funcaptcha'></div></body></html>";
 _browser.LoadHtml(html);
####

**Comment by amaitland** [comment]
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Also please fork the https://github.com/cefsharp/CefSharp.MinimalExample project and provide an example that reproduces your problem.

Please make sure you test with the `CEF Sample Application`, use the command line args listed for testing `WPF` please.

**Comment by amaitland** [comment]
Also please provide a more meaningful title.

**Comment by bbday** [comment]
I tried also with minimal example, same issue. To reproduce it easy:


```
static async Task Main(string[] args)
        {
            CefSettings settings = new CefSettings()
            {
                LogSeverity = LogSeverity.Disable,
            };

            settings.CefCommandLineArgs.Add("disable-renderer-accessibility", "1");
            settings.CefCommandLineArgs.Add("disable-histogram-customizer", "1");
            settings.CefCommandLineArgs.Add("disable-gpu-shader-disk-cache", "1");
            CefSharpSettings.SubprocessExitIfParentProcessClosed = true;
            Cef.Initialize(settings);

            var requestContextSettings = new RequestContextSettings { CachePath = Path.Combine(Program.AssemblyPath, Program.SessionPath) };
            var requestContext = new RequestContext(requestContextSettings);
            var _browser = new ChromiumWebBrowser("about:blank", null, requestContext);
            string html = @"<script src='https://ea-api.arkoselabs.com/fc/api/?onload=loadFunCaptcha' async defer></script>
<script type = 'text/javascript'> var blob = 'm7++bOFGILKX5bMF.omV4SaqF8mPsFkpNsaKC6uVPcVujQn9YgXU1Hj92Af0MVRATmtDanPlr8AAiIORhQxTSD9+bw+iXq0ld19QOrn/q/QheQ4PAs8GPjLmrUmM+K1gXIjnaDaVf2uwsa5v717XkkcR0MHz+rpUWbXaOlgREoMU2/trbkYAvNlTQvyDVeEDzmPJ4NdiVp6qJlY1ktKfDnK0BBwBHoFiHeM7jHhW93CdFdW1A1Xn/fFt0pxVLeT6g7VmBBGufEaNYDNI='; var key = 'A4EECF77-AC87-8C8D-5754-BF882F72063B';

        function loadFunCaptcha()
        {
            new FunCaptcha({
        'public_key': key,
		'data': { 'blob':blob},
		'language': 'en',
        'callback': captchaCompletedCallback,          
    });
}

//Only When succeffuly
function captchaCompletedCallback()
{
    var t = document.getElementById('FunCaptcha-Token').value
    console.log(t);
}

</script>
";
            SpinWait.SpinUntil(() => _browser.IsBrowserInitialized);
            _browser.LoadHtml(html);

            Console.ReadKey();
        }
```

**Comment by amaitland** [comment]
You will need to test with the `CEF Sample Application`, the details are in the bug report. This is very unlike to be a `CefSharp` bug, more likely a `CEF/Chromium` issue.
