### ISSUE TITLE
Feature Request - Add RequestContext.ClearHttpAuthCredentials

### ISSUE THREAD

**Issue by vwmberry95** [cefsharp/CefSharp#2957]
Add a wrapper method around CefRequestContext.ClearHttpAuthCredentials():

[https://github.com/chromiumembedded/cef/commit/3f1ebebde5c806f1c3933281ae1ce44e43a79a3b#diff-33f2548a1a111926f69150f5b6153bbb](https://github.com/chromiumembedded/cef/commit/3f1ebebde5c806f1c3933281ae1ce44e43a79a3b#diff-33f2548a1a111926f69150f5b6153bbb)

**Comment by amaitland** [comment]
Follow up commit https://github.com/cefsharp/CefSharp/commit/47e2d211a8bd4b0661ff0c8d8ed7fb180de1efc5
- Added `IRequestContext.ClearHttpAuthCredentialsAsync` extension method 
- Added default value for `IRequestContext.ClearHttpAuthCredentials` interface, now possible to call without passing in callback

Testing with `ClearHttpAuthCredentials()` (no callback) and there's a crash, appears to be a bug in `CEF`, works as expected when passing in the callback. Issue will need to be reported upstream most likely.

Added menu item to `CefSharp.Wpf.Example` in https://github.com/cefsharp/CefSharp/commit/7b599bb18826dbc2917498c3f37965a67c12e8da

**Comment by amaitland** [comment]
> Testing with `ClearHttpAuthCredentials()` (no callback) and there's a crash, appears to be a bug in `CEF`, works as expected when passing in the callback. Issue will need to be reported upstream most likely.

Added a `NOOP` callback that's used when no callback is provided in commit https://github.com/cefsharp/CefSharp/commit/f9c9c7fce5858719af48fbcdbbffdf881ca5d9ba

The issue should be reported `upstream`, it will likely take months to fix as it's such a low priority, so we'll just workaround it for now.
