### ISSUE TITLE
Feature Request - FindElement in build system inherit from selenium web driver 

### ISSUE THREAD

**Issue by rajesh-smartwebtech** [cefsharp/CefSharp#2969]
It is possible to merge code of  selenium web driver  from html page interaction all kind of operation . 
selenium web driver has may be .net html page layer of operation so i think 
i like if  selenium web driver html operation model , it become most popular 

i think you understood ?

**Comment by amaitland** [comment]
In future please use the feature request template provide at https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/feature_request.md

Using any framework/tool that supports the DevTools remote debugging protocol is already possible, see https://bitbucket.org/chromiumembedded/cef/wiki/UsingChromeDriver.md for general instructions on using selenium with CEF.

Personally I think the Puppeteer API is much nicer than selenium, you can quite easily use PuppeteerSharp with CefSharp, see https://gist.github.com/amaitland/52831ce341f65554540d91eba951bebe for a slightly outdated example.

Closing as I have no plans to implement this as it's impractical. There are plenty of .Net libraries that can be used with CefSharp.

https://github.com/kblok/puppeteer-sharp
https://github.com/MasterDevs/ChromeDevTools
https://chromedriver.chromium.org/
