### ISSUE TITLE
OffScreen mouse action is too slow

### ISSUE THREAD

**Issue by Dustray** [cefsharp/CefSharp#2970]
### Bug Report
I use the CefSharp.OffScreen to make a transparency browser, but now I have a problem. 

- **What version of the product are you using?**
    - 75.1.143  CefSharp.OffScreen

- **What architecture x86 or x64?**
    - x64
- **On what operating system?**
    - Win10 Interprise

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - OffScreen
- **What steps will reproduce the problem?**
    - Use this method: ```chromiumBrowser.Paint=xxx; ```, and then mouse action is too slow, but in version 57.0.0 ```chromiumBrowser.NewScreenShot=xxx``` have no this problem，fluent. 
    - And I override these Mouse Method to response mouse:
```
        protected override void OnMouseDown(MouseEventArgs e)
        {
            if (!chromiumBrowser.IsBrowserInitialized) return;
            var which = this.ConvertMouseButton(e.Button);
            if (which == -1) return;
            this.GetHost().SendMouseClickEvent(e.X, e.Y, (MouseButtonType)which, false, e.Clicks, CefEventFlags.None);
        }
        protected override void OnMouseUp(MouseEventArgs e)
        {
            if (!chromiumBrowser.IsBrowserInitialized) return;
            var which = this.ConvertMouseButton(e.Button);
            if (which == -1) return;
            this.GetHost().SendMouseClickEvent(e.X, e.Y, (MouseButtonType)which, true, e.Clicks, CefEventFlags.None);
        }
        protected override void OnMouseMove(MouseEventArgs e)
        {
            if (!chromiumBrowser.IsBrowserInitialized) return;
            this.GetHost().SendMouseMoveEvent(e.X, e.Y, false, CefEventFlags.None);
        }
```

- **What is the expected output? What do you see instead?**
    - Just slow.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
    - No. Sample Application is only a screenshot model.
 

##Thanks, everyone.

**Comment by Dustray** [comment]
![GI4F](https://user-images.githubusercontent.com/19183422/68678288-a8992c80-0598-11ea-86c4-7012326b4009.gif)
This a gif

**Comment by amaitland** [comment]
Try disable the GPU compositor, ultimately performance is limited by the CEF/Chromium version, other than tweaking a few command line args we have absolutely no control.

Disable using settings.CefCommandLineArgs.Add("disable-gpu-compositing", string.Empty);

The mouse action being slow as you've described it is likely just a lower frame rate.

**Comment by Dustray** [comment]
> Try disable the GPU compositor, ultimately performance is limited by the CEF/Chromium version, other than tweaking a few command line args we have absolutely no control.
> 
> Disable using settings.CefCommandLineArgs.Add("disable-gpu-compositing", string.Empty);
> 
> The mouse action being slow as you've described it is likely just a lower frame rate.

## But disabling gpu will make something unavailable... Is there any other  way? Thank you.

**Comment by amaitland** [comment]
Disabling the GPU compositor is not the same as disabling the GPU, no features will be unavailable.

**Comment by amaitland** [comment]
Closing as `upstream`. Rendering performance is limited by the `CEF/Chromium` version.
