### ISSUE TITLE
How to import existing cookies CefSharp ?

### ISSUE THREAD

**Issue by snez1990** [cefsharp/CefSharp#2972]
I am trying in many ways to import cookies from a particular site but not succeeded in some easy way to do this? :)

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/blob/cefsharp/75/CefSharp.Example/Handlers/BrowserProcessHandler.cs#L28 for an example on how to set a cookie.

You need to specify a `CachePath` to persist cookies to disk, see https://github.com/cefsharp/CefSharp.MinimalExample/blob/cefsharp/75/CefSharp.MinimalExample.WinForms/Program.cs#L27

Further questions please use one of the options listed above. We use this issue tracker for bug reports and features requests, not questions, thanks.
