### ISSUE TITLE
C# Modify URL to add my custom query string is not working?

### ISSUE THREAD

**Issue by salamander-mh** [cefsharp/CefSharp#2974]
CEF version `75.1.143`
here is my code:
```
public class CustomResourceRequestHandler : ResourceRequestHandler
{
    protected override CefReturnValue OnBeforeResourceLoad(IWebBrowser chromiumWebBrowser, IBrowser browser, IFrame frame, IRequest request, IRequestCallback callback)
    {
        request.Url = request.Url + "?name=foo";

        return CefReturnValue.Continue;
    }
}
```
the browser showed a empty page, is my way correct?

**Comment by amaitland** [comment]
Many many changes were made to support the Chromium network service,  I'd suggest you start by reading https://bitbucket.org/chromiumembedded/cef/issues/2622/implement-support-for-networkservice in detail.

Modifying the request in OnBeforeResourceLoad causes a redirect,  perhaps you are creating a loop, review the log file.

**Comment by salamander-mh** [comment]
@amaitland  your opinion is right. And how to add my custom query params before sending request? any advice?

**Comment by amaitland** [comment]
Asked https://stackoverflow.com/questions/tagged/cefsharp

**Comment by salamander-mh** [comment]
@amaitland  thks.
