### ISSUE TITLE
Focus not setting inside WPF Sample App in latest Master

### ISSUE THREAD

**Issue by piyush349** [cefsharp/CefSharp#2975]
- **What version of the product are you using?**
    I have taken the latest master cefsharp code from the below location:
             https://github.com/cefsharp/CefSharp and build it for the for x86 ennvironment.  And Run 
             CefSharp.Wpf.Example project.  Found that Not able to setfocus is not in the for the Iframe. 

- **What architecture x86 or x64?**
  x86
- **On what operating system?**
    -Win10, etc?

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
  Build the CefSharp.Wpf.Example project.
  Run the Executable from Release\x86
  In the HTML section Write HelloWorld and press run button.
  Output will be displayed. Try to select/copy the output HelloWorld from outputwindow.  Same thing was working in the release 76 Build. 
 
- **What is the expected output? What do you see instead?**
    We should able to select and copy the string. 

- **Please provide any additional information below.**
    - Not Required.

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?

- **Does this problem also occur in the `CEF` Sample Application from 
     Yes. 

    - To compare with WPF/OffScreen run cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu
    - To compare with WinForms run cefclient --multi-threaded-message-loop
    - If you can reproduce the problem with `cefclient` then you'll need to report the bug on https://bitbucket.org/chromiumembedded/cef/overview there is no point opening an issue here. (Make sure you search before opening an issue)
    - Please include the version you tested with e.g. `cef_binary_3.3029.1611.g44e39a8_windows64_client.tar.bz2`. It's important to you test with the same version that `CefSharp` is based on. Check the release notes to determine the version (https://github.com/cefsharp/CefSharp/releases) or load `chrome://version` in the browser.

**Comment by amaitland** [comment]
As per the issue template,  if you can reproduce the issue with cefclient then you need to report the issue at https://bitbucket.org/chromiumembedded/cef/issues?status=new&status=open

Post a link back here for reference.

**Comment by piyush349** [comment]
**What steps will reproduce the problem?**
Build the CefSharp.Wpf.Example project.
Run the Executable from Release\x86 and open https://jsfiddle.net/
In the HTML section Write HelloWorld and press run button.
Output will be displayed. Try to select/copy the output HelloWorld from outputwindow. Same thing was working in the release 76 Build.

oes this problem also occur in the CEF Sample Application from
No. This problem reproducible with CefSharp.Wpf.Example.

**Comment by piyush349** [comment]
@amaitland   please reopen the bug.

**Comment by amaitland** [comment]
Please edit your original issue and complete the Does this problem also occur in the CEF Sample Application section,  list the version and command line args used for testing.

**Comment by piyush349** [comment]
I have updated the issue. It works with cefclient.exe.

**Comment by amaitland** [comment]
Please include the cefclient version and command line args you used for testing.  

Seems very unlikely this is a bug in CefSharp.

**Comment by piyush349** [comment]
I have taken the latest master build from https://github.com/cefsharp/CefSharp .  
CefSharp version is 76.1.90.0. 
Below is the steps I follow:
1. Build the CefSharp.Wpf.Example project. from master:
2. Run the Executable from Release\x86.
3. Load the url : https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe
4. You can see that you can scroll the iframe output fine.
5. Now change src of iframe to https://example.com and click Run.
6. You can see scroll in iframe is not working.

**Comment by amaitland** [comment]
Thank you for the detailed list of steps to reproduce. It's actually **very important** you test with the `CEF Sample Application` and follow the steps exactly, it's the reason I've asked multiple times for you to confirm the version and command line args you used. 

I have completed the steps and can confirm this is an **upstream** issue and will need to be reported on the `CEF Issue Tracker` as linked to above.

>  **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

 >  - To compare with WPF/OffScreen run cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu
 >    - To compare with WinForms run cefclient --multi-threaded-message-loop
 >    - If you can reproduce the problem with `cefclient` then you'll need to report the bug on https://bitbucket.org/chromiumembedded/cef/overview there is no point opening an issue here. (Make sure you search before opening an issue)
 >    - Please include the version you tested with e.g. `cef_binary_3.3029.1611.g44e39a8_windows64_client.tar.bz2`. It's important to you test with the same version that `CefSharp` is based on. Check the release notes to determine the version (https://github.com/cefsharp/CefSharp/releases) or load `chrome://version` in the browser.

1. Load `chrome://version` in the `ChromiumWebBrowser` to determine the version you are using. (In this case it's `78.3.1+g8819d2e+chromium-78.0.3904.87`)
2. Download http://opensource.spotify.com/cefbuilds/cef_binary_78.3.1%2Bg8819d2e%2Bchromium-78.0.3904.87_windows32_client.tar.bz2
3. Start `cefclient` with the `WPF` set of command line args listed in the template

```
cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu
```
4. Test with instructions from https://github.com/cefsharp/CefSharp/issues/2975#issuecomment-557648358
5. Confirm issue **exists**

I've also tested with `78.3.4+ge17bba6+chromium-78.0.3904.108` and can confirm the issue also exists in that version.

**Comment by amaitland** [comment]
A quick test with the `disable-site-isolation-trials` command line arg and it appears to work around the problem.

**Comment by amaitland** [comment]
Looks like this has already been reported at https://bitbucket.org/chromiumembedded/cef/issues/2789/osr-branch-3904-iframes-doesnt-handle
