### ISSUE TITLE
Broken Link in "General Usage Documentation"

### ISSUE THREAD

**Issue by kevalkothari** [cefsharp/CefSharp#2976]
Hey there,

On this URL: https://github.com/cefsharp/CefSharp/wiki/General-Usage

Under Screenshot section example link for "Capture full page using scrolling" is broken showing 404 error.

https://github.com/joe-williams-cccu/OSIRTv2/blob/3e60d3ce908a1d25a7b4633dc9afdd53256cbb4f/OSIRT/Browser/MainBrowser.cs#L300

Thanks,
Keval

**Comment by amaitland** [comment]
Thanks, fixed.
