### ISSUE TITLE
PDF save , not properly working same as html page

### ISSUE THREAD

**Issue by rajesh-smartwebtech** [cefsharp/CefSharp#2978]
Hi @ataranto  

There are not working save pdf actual look of html page view in browser 

This is browser screenshot 
![Screenshot_1](https://user-images.githubusercontent.com/35251001/69536444-fc960f00-0fa3-11ea-9a04-de18a0fd0698.jpg)

This is pdf file save from cefsharp 
[UK.pdf](https://github.com/cefsharp/CefSharp/files/3886342/UK.pdf)

I am using following code for generate pdf 
```
public void PageToPDF( string path )
{
    //wait untill command exported pdf
    browser.PrintToPdfAsync(path).Wait();
}
```

i am using vs 2015 community
and cefsharp winform  v75.1.141
OS win 10

so how can i save pdf same as html look in browser 

Thank you for support

**Comment by amaitland** [comment]
It's important to note that `CefSharp` is just a wrapper around the `Chromium Embedded Framework (CEF)`. Closing this as `upstream` and as changes need to be made in `CEF`. 

The `CEF` project has it's own issue tracker located at https://bitbucket.org/chromiumembedded/cef it is recommended you ask on https://magpcss.org/ceforum/index.php before opening an issue on the CEF issue tracker. The behavior you are seeing may be the expected default.

Before opening a new issue you should:

- Search open/closed issues to determine if the problem you are seeing has already been reported
- Test with a newer version if available, see https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-chromium-embedded-frameworkcef for details on testing with the `cefclient` reference application.

If you do find an existing issue that matches this one or create a new one then post a link here for others to follow.
