### ISSUE TITLE
Add support for favicons in the WPF Example

### ISSUE THREAD

**Issue by perlun** [cefsharp/CefSharp#298]
This one is really, *really* silly but why not try to support favicons in the tabbed browser? I.e. so that we display a little icon next to the page title in the tab...

Unfortunately, it doesn't seem all-easy to implement until [this issue](https://code.google.com/p/chromiumembedded/issues/detail?id=964) has been fixed on the CEF side of life.

**Comment by amaitland** [comment]
FYI Looks like the Upstream `Cef` issue will be resolved shortly.

**Comment by amaitland** [comment]
Support was merged into trunk (2271)
https://code.google.com/p/chromiumembedded/source/detail?r=1965

**Comment by amaitland** [comment]
Interface is exposed by #1011
