### ISSUE TITLE
WinForms - InvokeOnUiThreadIfRequired incorrectly invokes on current thread

### ISSUE THREAD

**Issue by ekalchev** [cefsharp/CefSharp#2980]
- **What version of the product are you using?**
    77
- **What architecture x86 or x64?**
x86
- **On what operating system?**
    - Win7, Win 8, Win10, etc?
win10
- **Are you using `WinForms`, `WPF` or `OffScreen`?**
Winforms in WPF application

Our application is submitting crash reports and I consitently see crash reports with call stacks that involves calls to InvokeOnUiThreadIfRequired. It is rare and cannot be reproduced at our machines but the exception from the crash reports are 

`System.InvalidOperationException: 'The calling thread cannot access this object because a different thread owns it.'`

Looking at the memory dumps call stack, I can seethis is comming from InvokeOnUiThreadIfRequired lambda passed to 

```
browser.InvokeOnUiThreadIfRequired(() =>
{
        // some code
});
```
I can see the code in the lambda that throws the exception is not executing on the main thread (The browser control is created on the main thread) and that is the cause of the exception. The question is how this happens since the code of InvokeOnUiThreadIfRequired look pretty straightforward

```
public static void InvokeOnUiThreadIfRequired(this Control control, Action action)
{
       if (control.InvokeRequired)
       {
             control.BeginInvoke(action);
       }
       else
       {
             action.Invoke();
       }
}
```
Looking at the documentation for InvokeRequired
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.invokerequired?view=netframework-4.8

InvokeRequired can return false if Invoke is not required (the call occurs on the same thread), **or if the control was created on a different thread but the control's handle has not yet been created**.

Our browser control is created on the main thread but the event OnFrameLoad that make the call to InvokeOnUiThreadIfRequired is from Cef worker thread. I think in rare occasion the window handle for the browser control is not yet created and that makes InvokeRequired to return false from a worker thread. I think in this case the code makes false assumption not to use BeginInvoke and the lambda is executed on the worker thread.

I think most of the time the handle for browser control is created before the calls to InvokeOnUiThreadIfRequired and everything works but in rare occasions main thread has not yet created the control handle when you start getting OnFrameLoad events which calls InvokeOnUiThreadIfRequired and that is the reason for the exceptions. Thoughts?

**Comment by amaitland** [comment]
Are you using `InvokeOnUiThreadIfRequired` in **your** code? It's part of the `CefSharp.WinForms.Internals` namespace and really not intended for use as part of the public `API`.

> I think most of the time the handle for browser control is created before the calls to InvokeOnUiThreadIfRequired and everything works but in rare occasions main thread has not yet created the control handle when you start getting OnFrameLoad events which calls InvokeOnUiThreadIfRequired and that is the reason for the exceptions

Unlikely. 

The underlying `CefBrowser` is created in the `OnHandleCreated` override, so all the events like `FrameLoadEnd` should only ever occur after there's a valid handle. See https://github.com/cefsharp/CefSharp/blob/cefsharp/73/CefSharp.WinForms/ChromiumWebBrowser.cs#L574

I suspect the `ChromiumWebBrowser` instance has been `Disposed` or your attempting to change it's parent or another operation that destroys/recreates it's handle. 

I'd suggest reading https://stackoverflow.com/questions/1874728/avoid-calling-invoke-when-the-control-is-disposed and creating your own extension method/helper function. If the calls are happening internal to `CefSharp` then we can look at improving it's implementation. Providing `InvokeOnUiThreadIfRequired` is kinda outside the scope of the project, it should probably be `internal` not `public`.

**Comment by ekalchev** [comment]
Yes, we use InvokeOnUiThreadIfRequired in our code and those exceptions are coming from our code that uses InvokeOnUiThreadIfRequired.

**Comment by amaitland** [comment]
> inside InvokeOnUiThreadIfRequired? Even if this method was internal, nothing guarantees that BeginInvoke won't be called after a control was disposed.

Additional checks were added in https://github.com/cefsharp/CefSharp/commit/0c060263717bf7b6c90da872fed4741f870c2a2f

**Comment by ekalchev** [comment]
Thanks, I am closing this as resolved.

**Comment by ekalchev** [comment]
> > inside InvokeOnUiThreadIfRequired? Even if this method was internal, nothing guarantees that BeginInvoke won't be called after a control was disposed.
> 
> Additional checks were added in [0c06026](https://github.com/cefsharp/CefSharp/commit/0c060263717bf7b6c90da872fed4741f870c2a2f)

I belive this is slightly better implementation even though it is not 100% thread safe.

```

public static void InvokeOnUiThreadIfRequired(this Control control, Action action)
        {
            //No action
            if (control.IsDisposed || !control.IsHandleCreated)
            {
                return;
            }

            if (control.InvokeRequired)
            {
                control.BeginInvoke(() => {

                    if (control.IsDisposed || !control.IsHandleCreated)
                    {
                        return;
                    }

                    action();
                });
            }
            else
            {
                action.Invoke();
            }
        }
```

**Comment by amaitland** [comment]
Method is now internal (#2983)

Just a word of warning, there's likely no one size fits all solution. Properties like [Label.Text](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.label.text?view=netframework-4.8) must be updated on the `UI Thread`, though don't require a valid handle. Using the updated `InvokeOnUiThreadIfRequired` in a user/custom control **constructor** will no longer update your `Label.Text` as the `IsHandleCreated` will prevent execution. This is just one example. If anyone using code like above experiences issues I'd suggest adding some logging/debugging before the `return;` statements, it's possible the code will have unintended side effects.
