### ISSUE TITLE
WinForms - Make CefSharp.WinForms.Internals.ControlExtensions.InvokeOnUiThreadIfRequired internal

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#2983]
The method wasn't intended to be part of the public `API`, it was made public for use with the example projects.

**Comment by amaitland** [comment]
If you require an example of how to implement such a method see https://github.com/cefsharp/CefSharp/issues/2980#issuecomment-560310222 or look at the project source.

See also https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.begininvoke?view=netframework-4.8

**Comment by shawty** [comment]
I don't know if it's any help, but this is how I usually achieve cross thread UI in winforms:

Assuming I have a "label" called "label1" on my form, I'd use the following method to update it

```C#
void UpdateLabel(string labelText)
{
  if(label1.InvokeRequired)
  {
    label1.Invoke(new Action(() => { UpdateLabel(labelText); }));
    return;
  }
  label1.Text = labelText;
}
```

'label1' can be substituted for any control you need to update, you can even attach it to the form, then update multiple controls in the form in one go if you need too.

If your familiar with extension methods, then it can also be added to the "Control" class as an extension and updated for different properties.

**Comment by amaitland** [comment]
The exact code used in version 75 is https://github.com/cefsharp/CefSharp/blob/cefsharp/75/CefSharp.WinForms/Internals/ControlExtensions.cs#L20
