### ISSUE TITLE
Feature Request - Get Render Process Id

### ISSUE THREAD

**Issue by bbday** [cefsharp/CefSharp#2984]
Is it possible get Process ID of chrome process? I ask it cause i need to look ram usage of chrome subprocess and if more than X value i need to unload and reload instance. I running many ChromiumWebBrowser than i can't find the right process to unload then reload.
I use Offscreen version, i tried with GetBrowser().Identifier and GetBrowserHost().GetWindowHandle() but is not their purpose.

Thanks

**Comment by amaitland** [comment]
In future please use the [Feature Request Template](https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/feature_request.md)

To my knowledge `CEF` doesn't provide an `API` that can be used to obtain the render process id.

Maybe it's possible to hack something where the render process gets it's own process Id and sends a message to the browser process using [SendProcessMessage](https://magpcss.org/ceforum/apidocs3/projects/(default)/CefFrame.html#SendProcessMessage(CefProcessId,CefRefPtr%3CCefProcessMessage%3E)). No idea how reliable this would actually be with `Chrome` changing render processes at will.

If you can get something working you are welcome to submit a `PR` for review.

**Comment by shawty** [comment]
If it's any help, I can think of a way of doing this, that's not specific to CefSharp.

If the OP knows the name the process he/she is working with as it appears in task manager, then they can use the "System.Process" class to run the command line tool "pslist" with the name as a parameter to get the process ID's reported back to them.

![image](https://user-images.githubusercontent.com/1876454/72393424-b8fd8d00-372a-11ea-93c4-123f3f4e5078.png)

I've used this same method myself in other scenarios, and if your creating the threads that are hosting the cef process yourself, then you can actually set a unique name in "Thread.Name" for your thread, that you can then match up in code and look for.

I know it's not a built in CEF sharp solution, but sometimes simple approaches like this work very well :-)

**Comment by amaitland** [comment]
If `CEF` ever implements such a feature this can be reopened.

The reality is you can probably just `kill` the offending process and reload the `Url` in [OnRenderProcessTerminated](http://cefsharp.github.io/api/79.1.x/html/M_CefSharp_IRequestHandler_OnRenderProcessTerminated.htm)

```c#
protected override void OnRenderProcessTerminated(IWebBrowser chromiumWebBrowser, IBrowser browser, CefTerminationStatus status)
{
	//Load the previous url on crash
	var url = browser.MainFrame.Url;
	browser.MainFrame.LoadUrl(url);
}
```

**Comment by amaitland** [comment]
Reopning as I have an idea on something that might be workable.

We can add a javascript function that gets the current render process Id.

You can then use `EvaluateScriptAsync` to get the Id. Obviously `CEF` adding a method would be nicer. This would have a low cost to implement as would use the existing `IPC` handling.

Some naming options.

```
CefSharp.GetProcessId()
CefSharp.GetRenderProcessId()
```

**Comment by amaitland** [comment]
Two new javascript properties have been added (use whichever suites your naming convention)

```
CefSharp.RenderProcessId
cefSharp.renderProcessId
```

It was easier to add a property than a function.

For anyone concerned about security you can change the naming of the `CefSharp/cefSharp` objects that are created in javascript see #2831 for details.

At this point there's no option to disable creation of this property (you can execute some javascript to override it).

**Comment by bbday** [comment]
I try to change naming of CefSharp i read thread but i dont find property:
CefSharpSettings.JavascriptBindingPropertyName
or
var settings = browser.JavascriptObjectRepository.Settings;
settings.JavascriptBindingApiGlobalObjectName = "customApi";

Miss something? i use stable version offscreen.

Thanks

**Comment by amaitland** [comment]
If you look at the milestone you'll see it's version 85 which isn't released yet.

**Comment by amaitland** [comment]
A more detailed example might look something like the following:

**NOTE** Chromium will switch processes when performing cross origin navigations and you will end up with a different render process hosting your website.

```c#
browser.LoadingStateChanged += OnLoadingStateChanged;

private async void OnLoadingStateChanged(object sender, LoadingStateChangedEventArgs args)
{
	if (!args.IsLoading)
	{
		var response = await args.Browser.MainFrame.EvaluateScriptAsync("cefSharp.renderProcessId");
		if (response.Success)
		{
			var renderProcessId = (int)response.Result;
			var process = Process.GetProcessById(renderProcessId);
			var processName = process.ProcessName;
		}
	}
}
```

**Comment by stevenboeren** [comment]
For its says Process doesn't exist in current context

**Comment by amaitland** [comment]
> NOTE Chromium will switch processes when performing cross origin navigations and you will end up with a different render process hosting your website.

Cross origin navigation will cause a process switch with the old process being terminated. Obtaining the process ID immediately before obtaining a reference to the process is a must.

**Comment by amaitland** [comment]
If you are prepared to rely on a CEF implementation detail which is subject to change without notice (unlikely to change admittedly) you can try the option discussed at https://magpcss.org/ceforum/viewtopic.php?f=6&t=18072

http://cefsharp.github.io/api/90.6.x/html/P_CefSharp_IFrame_Identifier.htm

I have not tested this approach.
