### ISSUE TITLE
GetVisibleNavigationEntry always returns null

### ISSUE THREAD

**Issue by Pethical** [cefsharp/CefSharp#2986]
- **What version of the product are you using?**

NuGet 75.1.143

- **What architecture x86 or x64?**

x64 & x86

- **On what operating system?**

Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**

WPF & WinForms

- **What steps will reproduce the problem?**

1. Load a valid website into the browser
2. Execute the next statement:

```csharp
var entry = browser.GetBrowserHost().GetVisibleNavigationEntry();
```
- **What is the expected output? What do you see instead?**

Current: `null` returned
Expected: return the current visible entry

- Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)

No

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

Not acceptable / can't test with the sample

---

Regards,
 Peter

**Comment by amaitland** [comment]
Please provide a more detailed example.  When and on what thread are you calling the method?

**Comment by Pethical** [comment]
Hi,
Thank you for response!
Here is an example:
https://github.com/Pethical/CefSharp.MinimalExample/blob/362befd55337578086c56f2904b78cc52a51bc35/CefSharp.MinimalExample.WinForms/BrowserForm.cs#L180

On the main thread. On menu item click.

**Comment by amaitland** [comment]
As per the documentation you can only call GetVisibleNavigationEntry on the CEF UI thread. 

http://cefsharp.github.io/api/75.1.x/html/M_CefSharp_IBrowserHost_GetVisibleNavigationEntry.htm

You can use http://cefsharp.github.io/api/75.1.x/html/P_CefSharp_Cef_UIThreadTaskFactory.htm to access the CEF UI thread.

**Comment by amaitland** [comment]
An exception will now be throw when calling from the incorrect thread, relevant commit https://github.com/cefsharp/CefSharp/commit/99c177aa3000706618d4c7f90444f0ee755e5ac4

**Comment by Pethical** [comment]
Thank you!
