### ISSUE TITLE
Feature Request - Add StreamResponseFilter

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#2988]
- [x] Move StreamResponseFilter from the example into the main project
- [x] Update example project

**Comment by amaitland** [comment]
`CefSharp.ResponseFilter.StreamResponseFilter` is now part of the library itself (previously existed in the example project only).

See commit https://github.com/cefsharp/CefSharp/commit/a9d39d7965e9f140630950daa6062432b82ba236

**Comment by amaitland** [comment]
Example as part of the source is at https://github.com/cefsharp/CefSharp/blob/a9d39d7965e9f140630950daa6062432b82ba236/CefSharp.Example/Handlers/ExampleResourceRequestHandler.cs

**Comment by tateisu** [comment]
I use similar to example,
Visual Studio shows waring like as "memoryStream is disposable but this class is not disposable".
but after I add dispose method and close memoryStream in it , sometime the exception raised that like as "write to already closed stream".

**Comment by amaitland** [comment]
[MemoryStream.Dispose](https://referencesource.microsoft.com/#mscorlib/system/io/memorystream.cs,147) doesn't actually do much more than set a few flags, so it's not like other streams where it's releasing  a file handle. I don't believe calling `Dispose` changes how the garbage handler deals with the object.

> but after I add dispose method and close memoryStream in it , sometime the exception raised that like as "write to already closed stream".

Without seeing your code I can only speculate where you've called `Dispose`. Please provide a code example.
