### ISSUE TITLE
Cefsharp browser sometime not return source of updated page html 

### ISSUE THREAD

**Issue by rajesh-smartwebtech** [cefsharp/CefSharp#2989]
Hi sir

i am using cefsharp win form 75.1.141 version 
i am using following code for get source of html 

```
                browser.InvokeOnUiThreadIfRequired(() => {
                    
                    Thread t2 = new Thread(delegate () {
                        try
                        {
                            browser.GetSourceAsync().ContinueWith(taskHtml =>
                            {
                                pageHTMLsource = taskHtml.Result;
                            }).Wait();
                        }
                        catch (Exception ttt) { }
                    });
                    t2.Start();
                    t2.Join();//wait

                });
```
first time source of html is updated then
some java script update elements attributes on page 

then i call same code for updated page source but it is not return sometime return

**Comment by amaitland** [comment]
It's hard to say if this is a CEF bug or a bug in your code. JavaScript takes a little while to update the DOM, changes aren't instant. Your sample code doesn't show when your code is being used in relation to JavaScript execution.

CefSharp does little more than wrap the CefStringVisitor with a TaskCompletionSource.
https://github.com/cefsharp/CefSharp/blob/cefsharp/75/CefSharp/WebBrowserExtensions.cs#L232
https://github.com/cefsharp/CefSharp/blob/cefsharp/75/CefSharp.Core/Internals/CefFrameWrapper.cpp#L142
https://github.com/cefsharp/CefSharp/blob/cefsharp/75/CefSharp.Core/Internals/StringVisitor.cpp#L12
https://github.com/cefsharp/CefSharp/blob/cefsharp/75/CefSharp/Visitor/TaskStringVisitor.cs#L33

Closing as invalid as this you are getting html as a string then CefSharp has done it's job, the rest is up to CEF and timing. It wouldn't surprise me if this is a bug in CEF.

Your code has numerous issues itself though. 
  - Blocks the UI thread
  - Unnessicary uses a thread for which it blocks the calling thread
  - Thread is abandoned every time you run your code.

I'd suggest you ask on stackoverflow and hopefully someone can help you straighten out your code before you persue this on https://magpcss.org/ceforum/index.php

**Comment by rajesh-smartwebtech** [comment]
Thank you @amaitland
