### ISSUE TITLE
Remove CefSharp.WebBrowserExtensions.RegisterJsObject/RegisterAsyncJsObject

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#2990]
Firstly this is only a minor change to allow for some upcoming changes, the changes to your code are fairly simple.

The methods have been removed to page the way for Legacy Binding being available on a per object basis rather than a per browser basis. See #2977 for details on that change (hopefully be available in the next major release).

For those upgrading here are updated examples.

**RegisterJsObject**
```c#
//Old method
browser.RegisterJsObject("bound", new BoundObject(), options: BindingOptions.DefaultBinder);

//Replaced with
CefSharpSettings.LegacyJavascriptBindingEnabled = true;
CefSharpSettings.WcfEnabled = true;
browser.JavascriptObjectRepository.Register("bound", new BoundObject(), isAsync:false, options: BindingOptions.DefaultBinder);
```

**RegisterAsyncJsObject**
```c#
//Old Method
browser.RegisterAsyncJsObject("boundAsync", new AsyncBoundObject(), options: BindingOptions.DefaultBinder);

//Replaced with
CefSharpSettings.LegacyJavascriptBindingEnabled = true;
browser.JavascriptObjectRepository.Register("boundAsync", new AsyncBoundObject(), isAsync: true, options: BindingOptions.DefaultBinder);
```

**Comment by amaitland** [comment]
Slight change of plans, I'll revert the removal

- [ ] Mark the methods `Obsolete`
- [ ] Throw exception to provide better communication for users on how to migrate their code (method won't do anything effectively)

**Comment by amaitland** [comment]
The methods now throw an exception that links to this issue, there are code examples above for code migration.

**Comment by tropa** [comment]
How to use it I cannot understand???

**Comment by JohnRambo90** [comment]
Why CefSharpSettings.WcfEnabled = true; is needed?

**Comment by khiemnd777** [comment]
Why does it not work? or it needs more config than you post?

**Comment by amaitland** [comment]
You can review the code that was removed at https://github.com/cefsharp/CefSharp/commit/ffaff5d15140da3ac6857e9c40f14a835d868eb5#diff-7ac45247db5707eecab6fe1290834329L56

**Comment by zornflute** [comment]
> Why does it not work? or it needs more config than you post?

It's need to set porperty named CamelCaseJavascriptNames as false.

**Comment by zornflute** [comment]
> Firstly this is only a minor change to allow for some upcoming changes, the changes to your code are fairly simple.
> 
> The methods have been removed to page the way for Legacy Binding being available on a per object basis rather than a per browser basis. See #2977 for details on that change (hopefully be available in the next major release).
> 
> For those upgrading here are updated examples.
> 
> **RegisterJsObject**
> 
> ```cs
> //Old method
> browser.RegisterJsObject("bound", new BoundObject(), options: BindingOptions.DefaultBinder);
> 
> //Replaced with
> CefSharpSettings.LegacyJavascriptBindingEnabled = true;
> CefSharpSettings.WcfEnabled = true;
> browser.JavascriptObjectRepository.Register("bound", new BoundObject(), isAsync:false, options: BindingOptions.DefaultBinder);
> ```
> 
> **RegisterAsyncJsObject**
> 
> ```cs
> //Old Method
> browser.RegisterAsyncJsObject("boundAsync", new AsyncBoundObject(), options: BindingOptions.DefaultBinder);
> 
> //Replaced with
> CefSharpSettings.LegacyJavascriptBindingEnabled = true;
> browser.JavascriptObjectRepository.Register("boundAsync", new AsyncBoundObject(), isAsync: true, options: BindingOptions.DefaultBinder);
> ```

why can't visit members, only methods?

**Comment by amaitland** [comment]
No functionality changes were made. If you have an example that uses one of the two removed methods then you will need to post code. Off-topic questions won't be answered. Statements saying it doesn't work cannot be answered unless accompanied by code that you are having trouble with.

**Comment by mridah** [comment]
@amaitland @khiemnd777  I'm using the following code to receive a JS event in the C# application but it isn't working:

    public class CEFEventListener
    {
          public void performLogin(string eventName, object eventData)
          {
                MessageBox.Show("Login!!!");
                Console.WriteLine("got");
          }
    }

**In Main:**

    CEFEventListener _cefListener = new CEFEventListener();
     xBrowser.JavascriptObjectRepository.Register("CSBINDINGS", _cefListener, isAsync: false, options: BindingOptions.DefaultBinder);

**JS Code:**

    window.CSBINDINGS.performLogin('click', JSON.stringify({
            data1: 'foo',
            data2: 'bar'
     }));

But it's not working. What am I doing wrong ?

**Comment by amaitland** [comment]
@mridah Are you upgrading from an older version?  What did your  RegisterJsObject/RegisterAsyncJsObject call look like?

**Comment by tropa** [comment]
1.

`myChromiumWebBrowser.JavascriptObjectRepository.ResolveObject += (sender, e) =>
            {
                var repo = e.ObjectRepository;
                if (e.ObjectName == "Foo")
                {
                    BindingOptions bindingOptions = null; 
                    bindingOptions = BindingOptions.DefaultBinder;

                    bindingOptions = new BindingOptions { CamelCaseJavascriptNames = false};
                    repo.Register("Foo", this.ApiChrome, isAsync: true, options: bindingOptions);
                }
            };`

`(async function() { await CefSharp.BindObjectAsync('Foo'); })(); "` in your js

When js starts, it binds Foo to CefSHarp, the handler above intercept binding call in async style and write it to storage

**Comment by fandrei** [comment]
I'm trying to use the callbacks like this:
```
			CefSharpSettings.LegacyJavascriptBindingEnabled = true;
			CefSharpSettings.WcfEnabled = true;
			_browser.JavascriptObjectRepository.Register("Callback", new CallbackFromJs(), false, BindingOptions.DefaultBinder);

// .......

	class CallbackFromJs
	{
		public void OnMessageClicked(string eventName, object eventData)
		{
			Debugger.Break();
		}
	}
```

```
window.Callback.OnMessageClicked('Name', 'Data');
```

But getting this error message: `Uncaught TypeError: window.Callback.OnMessageClicked is not a function`
Any ideas what's wrong?

**Comment by amaitland** [comment]
@fandrei Please use one of the options listed at https://github.com/cefsharp/CefSharp#contact as your question is unrelated to the removal of CefSharp.WebBrowserExtensions.RegisterJsObject/RegisterAsyncJsObject

Everyone please only post here if you are migrating from CefSharp.WebBrowserExtensions.RegisterJsObject/RegisterAsyncJsObject

**Comment by fandrei** [comment]
@amaitland it's directly related to the sample in the top comment, but ok.

**Comment by amaitland** [comment]
@fandrei What does your RegisterJsObject/RegisterAsyncJsObject code look like? What version are you upgrading from?

**Comment by amaitland** [comment]
For those migrating 
from CefSharp.WebBrowserExtensions.RegisterJsObject/RegisterAsyncJsObject please include the following when posting a comment here:

- Version you are upgrading from
- A code example that shows your current RegisterJsObject/RegisterAsyncJsObject usage

Please keep comments on topic (migrating from an older version where you used one of the two methods listed above)

---

> Method names are transformed to CamelCase (the first letter is transformed to lowercase, MyFunction becomes myFunction) by default. This is configurable by setting BindingOptions.CamelCaseJavascriptNames when you register your object, example below.

For those of you seeing an error similar to `Uncaught TypeError MyFunction is not a function`. Please read  https://github.com/cefsharp/Questions-and-Support/issues/40#issuecomment-693742478 and post a comment there if you require assistance.

**Comment by AndersBillLinden** [comment]
Problems migrating to the new function is reported at 

https://stackoverflow.com/questions/65291697/switching-from-chromebrowser-registerasyncjsobject-to-chromebrowser-javascriptob

(Function calls from js to the cef container application where never delivered).

**Comment by DominikPalo** [comment]
It would be nice to update also the [WcfEnabled](http://cefsharp.github.io/api/89.0.x/html/P_CefSharp_CefSharpSettings_WcfEnabled.htm) documentation - it still refers to the old way (`browser.RegisterJsObject` and `browser.AsyncRegisterJsObject`) instead of the new way which is recommended now `browser.JavascriptObjectRepository.Register`:

> WCF is used by **RegisterJsObject** feature for Javascript Binding It's reccomended that anyone developing a new application use the **RegisterAsyncJsObject** version which communicates using native Chromium IPC.

**Comment by AndersBillLinden** [comment]
> As the exception states you've attempted to change the property after the browser has been created. It's too late. You need to set it earlier.
> 

How would you set it earlier?

**Comment by iuy6tf57765fsegh5yhw45yuh8g4** [comment]
I am using .Net 4.5.2 in my project I am getting the 

`
 'CefSettings' does not contain a definition for 'WcfEnabled' and no accessible extension method 'WcfEnabled' accepting a first argument of type 'CefSettings' could be found (are you missing a using directive or an assembly reference?)
`

error.

**Comment by rajnithin** [comment]
how to call object and its method  in javascript after registering?

**Comment by Robot37** [comment]
> how to call object and its method in javascript after registering?

First you must create a class in Visual Studio with a method that you will call from JavaScript. Thus
```
public class BoundObject{

     public void sm(string str){
     MessageBox.Show(str); //display a message
     }
}
```
The creator of this thread probably forgot to write this because he thought it was too obvious. But in fact, not everyone understands this.
And inside the JavaScript you need to write like this
`  bound.sm("hello world");`

**Comment by Robot37** [comment]
It seems I have discovered a flaw. The object is added to the MainFrame only. In ChildFrames the object is missing and does not work.

**Comment by amaitland** [comment]
> Further questions please use https://github.com/cefsharp/CefSharp/discussions

As per above, please use discussions.
