### ISSUE TITLE
Feature Request - My Feature

### ISSUE THREAD

**Issue by etheaven** [cefsharp/CefSharp#2991]
`CefSharp` is a wrapper around the [Chromium Embedded Framework](https://bitbucket.org/chromiumembedded/cef/overview) in a lot of cases a feature must be added to `CEF` first before it can be used in `CefSharp`. `CEF` has it's own `Feature Request Forum` at https://magpcss.org/ceforum/viewforum.php?f=7

--- 

**Describe the solution you'd like**
Touchscreen support in default cefbrowser

**Additional context**
I somehow managed to open another window of cef and there the touchscreen support was working, but not in the CefSharp.MinimalExample originally when browsing google ferrari for example

**Checklist:**
- [x] I have reviewed the [CEF API](https://magpcss.org/ceforum/apidocs3/index-all.html) and have confirmed the feature I'm requesting is possible.
- [ ] The Feature I'm requesting is an improvement to Async Javascript Binding (No new feature are being added to the Sync Javascript binding)
- [ ] An open `PR` exists on the [CEF Pull Requests](https://bitbucket.org/chromiumembedded/cef/pull-requests/) and I'd like to propose this feature is added to `CefSharp` when/if it's merged.

**Comment by amaitland** [comment]
The WPF version will get touch screen support shortly, that's tracked by #228 

The WinForms version the touch support is entirely implemented in Chromium,  there are a few activation issues, in general it works fine. 

Closing as there is nothing actionable detailed in this feature request.
