### ISSUE TITLE
Feature Request - Updated documentation

### ISSUE THREAD

**Issue by IamKayrox** [cefsharp/CefSharp#2992]
Documentation is completely obsolete. Recomended reads are outdated and currently useless

**Comment by amaitland** [comment]
Please provide specific examples and some actionable items. This as it stands is too vaigue,  please be specific,  thanks. 

https://github.com/cefsharp/CefSharp/wiki/General-Usage is the best source of information currently.

**Comment by IamKayrox** [comment]
Recomended reads don't mention anything about the assemblies that need to be declared private to be loaded into the project, recomended read is either incomplete with some of the screenshots missing or using a deprecated method of JavaScript object binding.

**Comment by IamKayrox** [comment]
Also, Quick Start Page is the big issue, it should be removed

**Comment by IamKayrox** [comment]
Update, binding method in the link you sent is unclear. More an example project would be better

**Comment by amaitland** [comment]
What is a declared private assembly exactly?  

The quick start section should have a disclaimer added regarding the age of the content and a warning that it's not up to date.

Please articulate what exactly is unclear about the JavaScript Binding section?  I need details,  specifics, what questions do you have? 

It's clear to me as I understand and wrote the documentation,  I need actual feedback to make things clearer. Anyone with a GitHub account can edit the wiki to make improvements. 

There is already a demo linked at the bottom of the Async section,  I have no plans to provide a sync version as that's a legacy feature and I have no plans to further it's development. 

To be realistic either one of two things needs to happen 
- More people need to contribute their time to improving the documentation (people like yourself)
- People/Companies need to contribute additional funding see https://github.com/cefsharp/CefSharp/tree/cefsharp/75#financial-support
