### ISSUE TITLE
cant call a function located in a jsfile

### ISSUE THREAD

**Issue by fironalia** [cefsharp/CefSharp#2993]
in my html file i have a script tag with src ="example.js";
how can i execute a function written in this js file from .net ?
the function ExecuteScriptAsync("alert(''")") works. but if i write the name of a function written in example.js it does now work;
the console says FunctionName  is not defined.

**Comment by amaitland** [comment]
You are likely executing your script too early,  please read https://github.com/cefsharp/CefSharp/wiki/General-Usage#when-can-i-start-executing-javascript

Further questions please use one of the support options listed above.
