### ISSUE TITLE
Low framerate on WebRTC camera

### ISSUE THREAD

**Issue by etheaven** [cefsharp/CefSharp#2994]
- **What version of the product are you using?**
   75.1.143

- **What architecture x86 or x64?**
x86

- **On what operating system?**
    - Win7, Win 8, Win10, etc?
win10
- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF
- **What steps will reproduce the problem?**
- open https://appr.tc/ on a computer using CefSharp.Minimal, then open another instance with another computer or VM
- you can see on one of the clients that the other one is lagging very much, this doesn't happen in official Chrome or cefsharp 71

- **What is the expected output? What do you see instead?**
at least 30fps video but I see like 5fps video
- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

    - To compare with WPF/OffScreen run cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu
    - To compare with WinForms run cefclient --multi-threaded-message-loop
    - If you can reproduce the problem with `cefclient` then you'll need to report the bug on https://bitbucket.org/chromiumembedded/cef/overview there is no point opening an issue here. (Make sure you search before opening an issue)
    - Please include the version you tested with e.g. `cef_binary_3.3029.1611.g44e39a8_windows64_client.tar.bz2`. It's important to you test with the same version that `CefSharp` is based on. Check the release notes to determine the version (https://github.com/cefsharp/CefSharp/releases) or load `chrome://version` in the browser.

**Comment by amaitland** [comment]
Did you test with the CEF Sample application as listed above? Make sure you use the command line args listed above for the WPF version and download the exact same version of CEF.  There's nothing here that would indicate a bug in CefSharp. 

Performance is almost entirely dictated by the CEF/chromium version. 

If you need performance similar to Chrome then you'll have to use the WinForms versions.

**Comment by etheaven** [comment]
Well the thing is, it worked on 71.0 and since I updated to the latest because I needed the touchscreen support, it never is smooth. and yes, the parameters make no change, I think it is even worse. 
I tried as well to do `Browser.BrowserSettings.WindowlessFrameRate = 60;` and in app startup I tried various mix of parameters:
```

            cefSettings.CefCommandLineArgs.Add("enable-gpu", "1");
            cefSettings.CefCommandLineArgs.Add("enable-webgl", "1");
            cefSettings.CefCommandLineArgs.Add("enable-begin-frame-scheduling", "1");
            cefSettings.CefCommandLineArgs.Add("--off-screen-frame-rate", "60");
            cefSettings.CefCommandLineArgs.Add("enable-media-stream", "1");
            cefSettings.CefCommandLineArgs.Add("off-screen-rendering-enabled", "1");
            cefSettings.CefCommandLineArgs.Add("enable-gpu", "1");
            cefSettings.CefCommandLineArgs.Add("multi-threaded-message-loop", "1");
```

and there was no change at all

**Comment by amaitland** [comment]
Please test with cefclient as requested.

**Comment by etheaven** [comment]
I don't have linux and there are only tar.gz items, I can't test it..

**Comment by etheaven** [comment]
apprantly I found the executable, in cefclient it fails to even start mediastream with error notallowed.

**Comment by etheaven** [comment]
but I'm sure it is worknig because 71.0 works, I can record a proof with 71.0 vs upstream

**Comment by etheaven** [comment]
what details exactly do you need? I can provide anything

**Comment by amaitland** [comment]
The point of the exercise is for you to see that the CEF Sample application has the same performance characteristics. More often than not people don't follow the instructions exactly and end up saying their problem doesn't reproduce with cefclient,  they either test with a newer version,  don't use the command line args for testing WPF and quite often both.

In version 75 specifically for WPF the gpu compositor is also disabled by default,  you would also need to use this command line args as well see https://github.com/cefsharp/CefSharp/blob/cefsharp/75/CefSharp.Wpf/CefSettings.cs#L25

Slower performance is not something we can fix in CefSharp directly,  each upgraded version of CEF brings it's own unique set of performance characteristics. 

Closing as upstream as there quite simply isn't a piece of CefSharp code that can be changed to fix this. Upgrading to a newer version of CEF may prove beneficial,  you can subscribe to release notifications here on GitHub to be notified of the next release.

**Comment by etheaven** [comment]
I disabled it but it was useless again. Something broke the lib completely since 73, sadly.. I'll fix it myself then, sounds like nobody trusts a stranger here.

**Comment by amaitland** [comment]
It's the Chromium Viz compositor that's brought about all the problems with the OSR implementation in CEF. 

CEF has it's own source repository and issue tracker https://bitbucket.org/chromiumembedded/cef/
