### ISSUE TITLE
Core3: Could not load file or assembly 'System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.'

### ISSUE THREAD

**Issue by gurgen1982** [cefsharp/CefSharp#2995]
I Created Core3 project with  CefSharp.Wpf 75.1.143. 

Made some changes in .csproj file
  <Reference Update="CefSharp">
      <Private>true</Private>
    </Reference>
    <Reference Update="CefSharp.Core">
      <Private>true</Private>
    </Reference>
    <Reference Update="CefSharp.Wpf">
      <Private>true</Private>
    </Reference>

Project runs, until I use this code:

  Browser.RegisterJsObject("dotnet", new SomeObject());

I get this error at runtime: Could not load file or assembly 'System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.'

As I understand System.ServiceModel was replaced in core3 with another dll ?

**Comment by amaitland** [comment]
Sync JavaScript Binding is not supported in .Net Core as Microsoft has chosen not to port WCF . There is no drop in replacement as you are suggesting.
