### ISSUE TITLE
TypeLoadException while binding

### ISSUE THREAD

**Issue by IamKayrox** [cefsharp/CefSharp#2996]
- **What version of the product are you using?**
    -75.1.143 from Visual Studio Nuget Manager
- **What architecture x86 or x64?**
    -Both
- **On what operating system?**
    -Win7

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
     -WinForms
- **What steps will reproduce the problem?**
     -https://pastebin.com/tpaPM5dz
     -https://pastebin.com/L9Sty4SD

- **What is the expected output? What do you see instead?**
     the app runing and stoping when pressing the button on the page

- **Please provide any additional information below.**
    Exception thrown: 'System.TypeLoadException' in CefSharp.Core.dll
    An unhandled exception of type 'System.TypeLoadException' occurred in CefSharp.Core.dll
    Could not load type 'System.ServiceModel.ServiceHost' from assembly 'System.ServiceModel, 
   Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
    - Does the cef log provide any relevant information? 
     Not at all

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
    -Just trying to set up a basic HTML UI

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
-No, it doesn't

**Comment by amaitland** [comment]
What version of .Net are you targeting?  If you are using .Net Core 3 then you can only use the asynchronous binding. The synchronous version uses WCF which is not supported under .Net Core.

**Comment by amaitland** [comment]
When you call register set isAsync to true http://cefsharp.github.io/api/75.1.x/html/M_CefSharp_IJavascriptObjectRepository_Register.htm

**Comment by IamKayrox** [comment]
As far as I read, the sync register is not supported. Why is it the default option?

**Comment by amaitland** [comment]
Please confirm your issue has been resolved.

**Comment by amaitland** [comment]
Please also confirm you are targeting. Net Core.

**Comment by IamKayrox** [comment]
Using net core 3.1
The issue have been resolved. Mention of this on the documentation would be appreciated.

**Comment by amaitland** [comment]
The error message will be improved as part of #2796 

As for the documentation you are welcome to edit the wiki and contribute improvements.
