### ISSUE TITLE
Dev tools shows up as an MDI window on the desktop

### ISSUE THREAD

**Issue by succeun** [cefsharp/CefSharp#2997]
**What version of the product are you using?** `75.1.143`

**What architecture x86 or x64?** `x64`

**On what operating system?** `Win7` & `Win10`

**Are you using `WinForms`, `WPF` or `OffScreen`?** `WPF`

**What steps will reproduce the problem?**

Show Dev Tools
```c#
browser.ShowDevTools();
```
Minimize Dev Tools

> Doesn't minimize to the taskbar it minimizes as an MDI child of the desktop

Restore Dev Tools

> Always on top
> Cannot Alt+Tab to it

Same Problem & Solution : 
[https://github.com/adobe/brackets/issues/7668](https://github.com/adobe/brackets/issues/7668)

**Comment by amaitland** [comment]
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

For some reason you've chosen to use the feature request template.

**Comment by amaitland** [comment]
Link is also broken

**Comment by succeun** [comment]
I am sorry and updated issue.

next image is issue screenshot.

![mini](https://user-images.githubusercontent.com/4233100/71626635-9733de80-2c31-11ea-9640-292b7bc19b53.png)

**Comment by amaitland** [comment]
> Same Problem & Solution :
> [adobe/brackets#7668](https://github.com/adobe/brackets/issues/7668)

@succeun Have you confirmed the solution you are proposing actually works?

The complete `CEF API` is exposed for [ShowDevTools](http://cefsharp.github.io/api/75.1.x/html/M_CefSharp_IBrowserHost_ShowDevTools.htm) you can use [WindowInfo](http://cefsharp.github.io/api/75.1.x/html/T_CefSharp_WindowInfo.htm) to customise the behaviour however you like.

**Comment by amaitland** [comment]
Passing `NULL` as parent `HWND` appears to change the `DevTools` behaviour.

It's still possible to revert to the previous behaviour, the code would look something like.

```c#
var host = browser.GetBrowserHost();

var windowInfo = new WindowInfo();
windowInfo.SetAsPopup(host.GetWindowHandle(), "DevTools");

browser.ShowDevTools(windowInfo);
```

**Comment by anton-martynyuk** [comment]
After the release of version 79.1.350 DevTools can't be closed in the WPF application

**Comment by amaitland** [comment]
Testing with the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) using `CefSharp.MinimalExample.Wpf` 

Opening `DevTools` using the following:

```c#
private void Browser_IsBrowserInitializedChanged(object sender, DependencyPropertyChangedEventArgs e)
{
	if ((bool)e.NewValue)
	{
		Browser.GetBrowserHost().ShowDevTools();
	}
}
```

Everything is working as expected. You can revert to the previous behaviour using the sample above for testing purposes.

**Comment by anton-martynyuk** [comment]
> Testing with the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) using `CefSharp.MinimalExample.Wpf`
> 
> Opening `DevTools` using the following:
> 
> ```cs
> private void Browser_IsBrowserInitializedChanged(object sender, DependencyPropertyChangedEventArgs e)
> {
> 	if ((bool)e.NewValue)
> 	{
> 		Browser.GetBrowserHost().ShowDevTools();
> 	}
> }
> ```
> 
> Everything is working as expected. You can revert to the previous behaviour using the sample above for testing purposes.

Yes, it works in the MinimalExample. Very strange why it doesn't work in my App.
I open DevTools on pressing F12.
I will find out what is causing DevTools from not being closed

**Comment by anton-martynyuk** [comment]
@amaitland my implementation of ILifeSpanHandler caused the problem.
I was returning true in DoClose method. I changed it to false and now the DevTools are being closed
