### ISSUE TITLE
CEF Sharp Broken on Surface Pro X

### ISSUE THREAD

**Issue by TonyValenti** [cefsharp/CefSharp#2999]
Hi All,
1.  I'm not using the latest version of CEF Sharp but I'm getting this error on all Microsoft Surface Pro X devices:
Faulting application name: FasterSuite.Windows.x32.exe, version: 19.11.27.0, time stamp: 0x925792eb
Faulting module name: libcef.dll, version: 3.3396.1786.0, time stamp: 0x5b51a393
Exception code: 0xc0000409
Fault offset: 0x0428370b
Faulting process id: 0x2de4
Faulting application start time: 0x01d5b8420aed0e50
Faulting application path: C:\Users\rejgo\AppData\Local\Clio\app-19.11.27\FasterSuite.Windows.x32.exe
Faulting module path: C:\Users\rejgo\AppData\Local\Clio\app-19.11.27\x86\libcef.dll
Report Id: 132452e0-07c6-468f-b272-2ee764ecda30
Faulting package full name: 
Faulting package-relative application ID: 

Has anyone tested on these?  Is the latest build compatible?

The error code seems to indicate it is a buffer overrun error.

**Comment by amaitland** [comment]
You can download and build https://github.com/cefsharp/CefSharp.MinimalExample to quickly test the latest version on your machines.
