### ISSUE TITLE
CefSharp is an undeclared prefix

### ISSUE THREAD

**Issue by Tenodec** [cefsharp/CefSharp#3002]
**window: win10 x64
.net core: 3.1
WPF version: 75.1.143**

**MainWindow.xaml**

`        <CefSharp:ChromiumWebBrowser Grid.Row="1" Name="MyChrom" Address="https://www.google.com/"/>
`
**xxx.csproj**
`  <PropertyGroup>
    <Platform>x86</Platform>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>MyNetCoreApp</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CefSharp.Wpf" Version="75.1.143" />
  </ItemGroup>`

**output** 
 error MC3000: “'CefSharp' is an undeclared prefix. Line 18, position 10.”XML 无效。

I already add CefSharp.Wpf  ,but I can't find it on my work directory

**Comment by amaitland** [comment]
.Net Core support is still a work in progress,  see #2796

There'sa working example at https://github.com/cefsharp/CefSharp.MinimalExample#net-core-support
