### ISSUE TITLE
WPF - Wrong IME Window Position

### ISSUE THREAD

**Issue by kkwpsv** [cefsharp/CefSharp#3004]
- **What version of the product are you using?**
    - lateset

- **What architecture x86 or x64?**
    - Any

- **On what operating system?**
    - Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
   - WPF

- **What steps will reproduce the problem?**
    - Use WpfImeKeyboardHandler
    - Use Chinese input method to input anything.

- **What is the expected output? What do you see instead?**
    - The position of IME window is wrong as below.
       ![wrong](https://user-images.githubusercontent.com/11524048/71499470-a1558600-289b-11ea-9200-46f6792303bf.png)
    - It shoule be like this.
       ![correct](https://user-images.githubusercontent.com/11524048/71499538-e4175e00-289b-11ea-9279-c3d979dbdde9.png)

- **Please provide any additional information below.**
    - Ime window position should be provide by `IRenderWebBrowser.OnImeCompositionRangeChanged`, but this method is never called in win10 
    - It works fine in win7, but wrong in win10.
    - #2945 has mentioned this problem.

- **Does this problem also occur in the `CEF` Sample Application**
    - Yes

**Comment by amaitland** [comment]
As per the issue template if you can reproduce the problem with the CEF Sample application then you should report the problem on the CEF issue tracker. https://bitbucket.org/chromiumembedded/cef/issues?status=new&status=open make sure you search open issues 

Closing as upstream. If you open an issue then post a link back here.

**Comment by kkwpsv** [comment]
Upstream issue: https://bitbucket.org/chromiumembedded/cef/issues/2845/wrong-ime-window-position-in-osr-mode-with

**Comment by kkwpsv** [comment]
@amaitland I have investigated this issue, it's not of upstream.  This issue should be reopened. 

IME should be implemented in both cef sample application and CefSharp.WPF. And upstream can't help us with this issue.

The direct cause of this issues is `Sogou Pinyin input method`'s irregular behavior. But the input method is widely used in China. `Chrome` has adapted its behavior, and I think `CefSharp` also should. 

I'm trying to fix it in `WpfIMEKeyboardHandler`. But it may be not easy.

**Comment by nocanstillbb** [comment]
> @amaitland我已经调查了这个问题，这不是上游的问题。此问题应重新打开。
> 
> 在cef示例应用程序和CefSharp.WPF中都应实现IME。上游无法帮助我们解决这个问题。
> 
> 造成此问题的直接原因是`Sogou Pinyin input method`行为不规范。但是输入法在中国被广泛使用。`Chrome`已经适应了它的行为，我认为`CefSharp`也应该如此。
> 
> 我正在尝试将其修复`WpfIMEKeyboardHandler`。但这可能并不容易。

我目前的做法是在写了一个static 的窗口,left = -9999;top =-9999，每次获得键盘焦点时让这个窗口show()然后hide();这时输入法会重新加载，这个办法不是长久之计，但可能暂时应对一下

**Comment by amaitland** [comment]
If anyone would like to take ownership of this issue then let me know and it can be reopened.

I don't use `IME` so unable to assist

**Comment by tmoonlight** [comment]
> > @amaitland我已经调查了这个问题，这不是上游的问题。此问题应重新打开。
> 
> > 
> 
> > 在cef示例应用程序和CefSharp.WPF中都应实现IME。上游无法帮助我们解决这个问题。
> 
> > 
> 
> > 造成此问题的直接原因是`Sogou Pinyin input method`行为不规范。但是输入法在中国被广泛使用。`Chrome`已经适应了它的行为，我认为`CefSharp`也应该如此。
> 
> > 
> 
> > 我正在尝试将其修复`WpfIMEKeyboardHandler`。但这可能并不容易。
> 
> 
> 
> 我目前的做法是在写了一个static 的窗口,left = -9999;top =-9999，每次获得键盘焦点时让这个窗口show()然后hide();这时输入法会重新加载，这个办法不是长久之计，但可能暂时应对一下

通过比较一些原生开源的wpf文本控件的行为， 我尝试解决了此问题， 并且提交了PR，使用中文输入法的同仁们可以验证一下。

**Comment by Cocoa-550123** [comment]
@tmoonlight thx, Win10 Microsoft Pinyin works fine
