### ISSUE TITLE
Failed to execute 'addTransceiver' on 'RTCPeerConnection':

### ISSUE THREAD

**Issue by salamander-mh** [cefsharp/CefSharp#3007]
it seems `addTransceiver` is not supported in CefSharp.
My CefSharp Version: `75.1.143`

**Comment by amaitland** [comment]
It's important to note that `CefSharp` is just a wrapper around the `Chromium Embedded Framework (CEF)`. Closing this as `upstream` and as changes need to be made in `CEF`. 

The `CEF` project has it's own issue tracker located at https://bitbucket.org/chromiumembedded/cef it is recommended you ask on https://magpcss.org/ceforum/index.php before opening an issue on the CEF issue tracker.
