### ISSUE TITLE
ScreenshotAsync does always return 'null' as a Result after a 'No Network'-Based Error which occured before

### ISSUE THREAD

**Issue by Snickbrack** [cefsharp/CefSharp#3008]
- **What version of the product are you using?**
    - I am using the following Setup:
    - CefSharp.OffScreen (75.1.143), CefSharp.Common (75.1.143), cef.redist.x86 and cef.redist.x64 (75.1.14)

    - As this is a little bit of a tapping in the dark (because of no Error been thrown or any indication that anything isn't working as expected)
    - I didn't change anything inside the Code so I think there is a state or a value saved anywhere which is preventing CefSharp or the underlying Chrome from successfully taking a screenshot

- **What architecture x86 or x64?**
x64 with 'x64' as active platform for the whole Project Solution
- **On what operating system?**
    - Win7

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
Offscreen
- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.
    - Please no binary (zip, etc) links, fork the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) and push your changes to `GitHub`. (Alternatively use a code sharing service list `Gist` or `Pastebin`).

I am using the Minimal-Example with no real changes inside the Process of taking the Screenshot.

- **What is the expected output? What do you see instead?**
Expected Result: A Task<Bitmap> with a Bitmap as Result returned by ScreenshotAsync
Actual Result: A Task<Bitmap> with a null-Value as Result returned by ScreenshotAsync

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.
No Error thrown...

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)

> [0105/135535.606:INFO:CONSOLE(0)] "The connection used to load resources from https://localhost used TLS 1.0 or TLS 1.1, which are deprecated and will be disabled in the future. Once disabled, users will be prevented from loading these resources. The server should enable TLS 1.2 or later. See https://www.chromestatus.com/feature/5654791610957824 for more information.", source: https://localhost/path/to/function?minusdays=20 (0)

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
I am not using any third party control for the browser or screenshot part. All other controls are used after the Screenshot is saved.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
I have opened my Page inside the Sample Application and it did shows up as it should. But I can't take a screenshot with the sample application...

    - To compare with WPF/OffScreen run cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu
Same as above...
    - To compare with WinForms run cefclient --multi-threaded-message-loop
Same as above...
    - Please include the version you tested with e.g. `cef_binary_3.3029.1611.g44e39a8_windows64_client.tar.bz2`. It's important to you test with the same version that `CefSharp` is based on. Check the release notes to determine the version (https://github.com/cefsharp/CefSharp/releases) or load `chrome://version` in the browser.
Used Version: cef_binary_79.0.10+ge866a07+chromium-79.0.3945.88_windows64_client

**Comment by Snickbrack** [comment]
I have now created a new Project with the Minimal-Example which doesn't work either on the same Machine.

If I run both programs on another system there is no issue with the ScreenshotAsync-Task...

As I stated before I think that the CefSharp-Structure saves some Data which is used by Cef and which may contains some broken data.

Is there any location outside of the project structure in which any runtime data is stored? I have removed and reinstalled all the CefSharp-Files via Nuget and cleared the 'bin' and 'obj' Directories before running the application. But this doesn't seem to help...

**Comment by Spocher** [comment]
Hello!
Did you manage to solve the problem with taking a screenshot?
I checked, and my screenshot is taken in the version of CefSharp.OffScreen.69.0.0
In version 75.1.143 a screenshot cannot be taken

**Comment by Spocher** [comment]
I added WindowlessRenderingEnabled = true in CefSettings. And the screenshot was successfully taken

**Comment by amaitland** [comment]
There is an issue where `ScreenshotAsync` incorrectly returns `null` which is fixed in https://github.com/cefsharp/CefSharp/commit/67c05da691b8f6afe19c01caa92e252dfab372f2#diff-2ecfdb174bf6b80d52f7840086accb73

---

> ScreenshotAsync does always return 'null' as a Result after a 'No Network'-Based Error which occured before

What is a `No Network`- based error? I've no idea what you mean by this.

> * What version of the product are you using?

Please just include the version in this section.

> I am using the Minimal-Example with no real changes inside the Process of taking the Screenshot.

Please provide a clear list of steps to reproduce the issue. `No real changes`, implies you made changes.

> [0105/135535.606:INFO:CONSOLE(0)] "The connection used to load resources from https://localhost used TLS 1.0 or TLS 1.1, which are deprecated and will be disabled in the future. Once disabled, users will be prevented from loading these resources. The server should enable TLS 1.2 or later.

This would imply you've made a change to the `MinimalExample` as it doesn't' load `localhost` by default.

> * **What is the expected output? What do you see instead?**
>   Expected Result: A Task with a Bitmap as Result returned by ScreenshotAsync
>   Actual Result: A Task with a null-Value as Result returned by ScreenshotAsync

If the web page fails to load, then the expected result is `null`. Subscribe to [LoadError](http://cefsharp.github.io/api/75.1.x/html/E_CefSharp_OffScreen_ChromiumWebBrowser_LoadError.htm) and see if an error occurs.

> As I stated before I think that the CefSharp-Structure saves some Data which is used by Cef and which may contains some broken data.

`CefSharp` doesn't save any data.

> Is there any location outside of the project structure in which any runtime data is stored? I have removed and reinstalled all the CefSharp-Files via Nuget and cleared the 'bin' and 'obj' Directories before running the application.

The `CEF` default is to use an `In Memory` cache, nothing is persisted to disk unless you provide a `CachePath`, if you set `CachePath` then data will be persisted to that folder. The MinimalExample uses https://github.com/cefsharp/CefSharp.MinimalExample/blob/master/CefSharp.MinimalExample.OffScreen/Program.cs#L29 for it's `CachePath`.
