### ISSUE TITLE
Allow flash plugin

### ISSUE THREAD

**Issue by SimonTheCat** [cefsharp/CefSharp#3012]
Allow plugin policy not work for flash
CefSettings.CefCommandLineArgs.Add("plugin-policy", "allow");
or
```
        public bool OnBeforePluginLoad(string mimeType, string url, bool isMainFrame, string topOriginUrl, WebPluginInfo pluginInfo, ref PluginPolicy pluginPolicy)
        {
            pluginPolicy = PluginPolicy.Allow;
            return true;
        }
```
CEF 79 dev WindowForm Win10

**Comment by amaitland** [comment]
It's important to note that `CefSharp` is just a wrapper around the `Chromium Embedded Framework (CEF)`. Closing this as `upstream` and as changes need to be made in `CEF`. 

The `CEF` project has it's own issue tracker located at https://bitbucket.org/chromiumembedded/cef it is recommended you ask on https://magpcss.org/ceforum/index.php before opening an issue on the CEF issue tracker.

**Comment by amaitland** [comment]
Looks like there's already https://bitbucket.org/chromiumembedded/cef/issues/2768/allow-flash-to-play-without-user and https://magpcss.org/ceforum/viewtopic.php?f=7&t=17068

Please search the CEF issue tracker and forum before opening any further issues.

**Comment by SimonTheCat** [comment]
Thank you!
solution for issue

```
CefSettings.CefCommandLineArgs.Add("plugin-policy", "allow");
...
var contx = Cef.GetGlobalRequestContext();
Cef.UIThreadTaskFactory.StartNew(delegate
{
  contx.SetPreference("profile.default_content_setting_values.plugins", 1, out string err);
});
```
