### ISSUE TITLE
Blurry screen in CefSharp.MinimalExample.WPF

### ISSUE THREAD

**Issue by msschl** [cefsharp/CefSharp#3017]
- **What version of the product are you using?**
 CefSharp.Wpf: 75.1.143.0
Chromium: 75.0.3770.100
CEF: r75.1.14+gc81164e+chromium-75.0.3770.100

- **What architecture x86 or x64?**
x64

- **On what operating system?**
win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF; Precisely the latest clone of the CefSharp.MinimalExample repo on branch master

- **What steps will reproduce the problem?**
Running the sample on an Monitor with 2560 x 1440px and an nvidia gpu gtx 1080

- **What is the expected output? What do you see instead?**
The wpf example is burry. The WinForms example not.
Nothing was changed on the code of the examples. 

- **Please provide any additional information below.**

![image](https://user-images.githubusercontent.com/5054780/72828728-936a0980-3c7d-11ea-8875-a679c3b0a7a9.png)

**Comment by amaitland** [comment]
What exactly is blurry about the image you've provided? What `DPI` are you using? What `Windows 10` build?

> * Precisely the latest clone of the CefSharp.MinimalExample repo on branch master

In future please specify the exact commit, as `latest clone` won't be accurate as time passes.

**Comment by msschl** [comment]
It seems like the fonts are a bit blurry. I am having a scale of 125%
Windows 10 10.0.18362 Build 18362
CefSharp.MinimalExample sha [b956db678180de020a2722c5871b0a6b6e302d30](https://github.com/cefsharp/CefSharp.MinimalExample/commit/b956db678180de020a2722c5871b0a6b6e302d30)

**Comment by msschl** [comment]
![image](https://user-images.githubusercontent.com/5054780/72888746-72052e00-3d0e-11ea-92c5-6b4e58445cab.png)

WPF
![image](https://user-images.githubusercontent.com/5054780/72888868-bd1f4100-3d0e-11ea-9d70-0cf0c10da812.png)

**Comment by msschl** [comment]
Chrome:
![image](https://user-images.githubusercontent.com/5054780/72888942-e6d86800-3d0e-11ea-98e2-09ac6f8532ef.png)

**Comment by amaitland** [comment]
Are your images supposed to look blurry?  They look fine on my Android tablet.

**Comment by msschl** [comment]
Its minimal on the pictures. But on the actual monitor it is far more blurry.

**Comment by amaitland** [comment]
Testing with https://github.com/cefsharp/CefSharp.MinimalExample/commit/bb86d45f1dc0084c5aa80db7686e600eed449f83 (The latest `79-pre` release) and everything looks fine loading https://devblogs.microsoft.com/dotnet/net-core-january-2020/

Windows 10 x64 1903
DPI 150%
Surface Pro 1st Generation
1920x1080

Blurry rendering in `WPF` is fairly common as detailed in https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#15-wpf-blurry-rendering

The `MinimalExample` is `DpiAware` and is aligned to the whole pixel so shouldn't have any problems.

I've not had any other reports in relation to the `MinimalExample` and cannot reproduce this myself, so not a while lot I can do.

**Comment by amaitland** [comment]
As a long shot you can try setting [SnapsToDevicePixels](https://docs.microsoft.com/en-us/dotnet/api/system.windows.uielement.snapstodevicepixels?view=netframework-4.8) to true on the `ChromiumWebBrowser` xaml element.

**Comment by msschl** [comment]
Same result

**Comment by ekalchev** [comment]
Its always been blurry. Try changing BitmapScalingMode to improve it but it still won't look good as WinForms control. This is not the only issue with WPF control, soon you'll notice that CPU load increase with resolution and framerate. On 4k monitors is not usable.

**Comment by loonylins** [comment]
字体模糊可以尝试修改这个参数(我从73.1.130版本开始一直使用这个方法)：
browser.BrowserSettings.BackgroundColor = Cef.ColorSetARGB(255, 255, 255, 255);

另外，WPF控件本身也可能存在模糊问题，可以尝试在Window/Page中添加如下属性：
UseLayoutRounding="True" SnapsToDevicePixels="True"

**Comment by loonylins** [comment]
WPF很多时候没必要跑在60帧下，我们可以减少动画默认帧数，以缓解CPU资源消耗：
Timeline.DesiredFrameRateProperty.OverrideMetadata(typeof(Timeline), new FrameworkPropertyMetadata { DefaultValue = 10 });
@ekalchev

**Comment by amaitland** [comment]
English only please.

**Comment by shadiaoha** [comment]
Add this sentence to resolve WPF ambiguity, thank you, effective

**Comment by shadiaoha** [comment]
UseLayoutRounding="True" SnapsToDevicePixels="True"

**Comment by amaitland** [comment]
For what it's worth UseLayoutRounding should already default to true. It is inherited so container controls may also need to have the property set.

- https://github.com/cefsharp/CefSharp/blob/cefsharp/103/CefSharp.Wpf/ChromiumWebBrowser.cs#L569
- https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.uselayoutrounding?view=windowsdesktop-6.0#remarks

**Comment by shadiaoha** [comment]
Thanks, but VS2022 created Border, which is based on Net6 and is not on by default, plus (uselayoutre ="True") did solve my problem
(中文)谢谢,但vs2022创建的Border,.基于net6,默认是不开启的,加上(UseLayoutRounding="True")确实解决了我的问题

**Comment by shadiaoha** [comment]
> 对于它的价值，UseLayoutRounding 应该已经默认为 true。它是继承的，因此容器控件可能还需要设置属性。
> 
> * https://github.com/cefsharp/CefSharp/blob/cefsharp/103/CefSharp.Wpf/ChromiumWebBrowser.cs#L569
> * https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.uselayoutrounding?view=windowsdesktop-6.0#remarks

Thanks, but VS2022 created Border, which is based on Net6 and is not on by default, plus (uselayoutre ="True") did solve my problem
(中文)谢谢,但vs2022创建的Border,.基于net6,默认是不开启的,加上(UseLayoutRounding="True")确实解决了我的问题

**Comment by shadiaoha** [comment]
> For what it's worth UseLayoutRounding should already default to true. It is inherited so container controls may also need to have the property set.
> 
> * https://github.com/cefsharp/CefSharp/blob/cefsharp/103/CefSharp.Wpf/ChromiumWebBrowser.cs#L569
> * https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.uselayoutrounding?view=windowsdesktop-6.0#remarks


Thanks, but VS2022 created Border, which is based on Net6 and is not on by default, plus (uselayoutre ="True") did solve my problem
(chinese)谢谢，但是VS2022创建了边界，它是基于Net6的，并没有默认打开，加上(uselayoute ="True")确实解决了我的问题

**Comment by amaitland** [comment]
> You should set [UseLayoutRounding](https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.uselayoutrounding?view=windowsdesktop-6.0) to true on the root element. The layout system adds child coordinates to the parent coordinates; therefore, if the parent coordinates are not on a pixel boundary, the child coordinates are also not on a pixel boundary. If [UseLayoutRounding](https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.uselayoutrounding?view=windowsdesktop-6.0) cannot be set at the root, set [SnapsToDevicePixels](https://docs.microsoft.com/en-us/dotnet/api/system.windows.uielement.snapstodevicepixels?view=windowsdesktop-6.0) on the child to obtain the effect that you want.

As per https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.uselayoutrounding?view=windowsdesktop-6.0#remarks

Setting UseLayoutRounding on the root element is preferable if possible. 

> Thanks, but VS2022 created Border, which is based on Net6 and is not on by default, plus (uselayoutre ="True") did solve my problem

My point being CefSharp sets the property to true by default, if the property is being overridden then it's up to the user to manually set.
