### ISSUE TITLE
WinForms - Update xml doc to reflect default Dock = DockStyle.Fill when control created in code

### ISSUE THREAD

**Issue by fandrei** [cefsharp/CefSharp#3019]
- **What version of the product are you using?**

75.1.14

- **What architecture x86 or x64?**

x64

- **On what operating system?**
    
Win7

- **Are you using `WinForms`, `WPF` or `OffScreen`?**

WinForms

```
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

using CefSharp;
using CefSharp.WinForms;

namespace CefSharpTest
{
	public class Form1 : Form
	{
		public Form1()
		{
			AutoScaleMode = AutoScaleMode.Font;
			WindowState = FormWindowState.Maximized;
			Text = "CefSharpTest";

			_layoutPanel = new FlowLayoutPanel
			{
				Dock = DockStyle.Fill,
				FlowDirection = FlowDirection.TopDown,
			};
			Controls.Add(_layoutPanel);

			var button = new Button
			{
				Text = "Load",
			};
			_layoutPanel.Controls.Add(button);

			_browser = new ChromiumWebBrowser("")
			{
				//Dock = DockStyle.Fill, // doesn't work
			};
			_layoutPanel.Controls.Add(_browser);
		}

		protected override void OnSizeChanged(EventArgs e)
		{
			base.OnSizeChanged(e);

			_browser.Width = _layoutPanel.ClientRectangle.Width; // doesn't work
			_browser.Height = 100;
			Trace.WriteLine(_browser.Width);
		}

		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
			_browser?.Dispose();
		}

		FlowLayoutPanel _layoutPanel;
		ChromiumWebBrowser _browser;
	}
}
```

**Comment by amaitland** [comment]
> Dock and Width don't work properly

Please provide a detailed description please, just saying it doesn't work and a few short comments in your code doesn't really tell me what's going on.

Also please provide a detailed list of steps to reproduce the problem.

What is the expected output? What do you see instead?

If there's a visual component then please provide a screen shot.

`ChromiumWebBrowser` defaults to `Dock = DockStyle.Fill`, I've had no other reports of issues, so possibly something related specifically to `FlowLayoutPanel`, it's not something I've ever tested.

In future please complete all sections of the [Bug Report Template](https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report)

**Comment by fandrei** [comment]
@amaitland that means that Dock.Fill doesn't really make the browser fill the parent, and setting Width doesn't really set the width to the specified value. Steps: build the code and run it.
By the way, making Dock.Fill the default value is very atypical as other controls in WinForms use Dock.None as default.

>  I've had no other reports of issues, so possibly something related specifically to FlowLayoutPanel

Very possible.

**Comment by amaitland** [comment]
Please provide a list of steps to reproduce and screenshots to illustrate the problem. 

Just saying build the code and run it isn't a list of steps to reproduce,  some window resizing must be involved.

**Comment by fandrei** [comment]
@amaitland no extra steps were required in my environment, just run it and check the position and size of the browser control.

**Comment by amaitland** [comment]
Changing your example to load `www.google.com.au` and I get basically what's expected. A `75x100` browser control. [ButtonBase.DefaultSize](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/ButtonBase.cs,189) is `75x23`.

> Set the Dock property of the second button to Fill.
>  **Note**
> The second button assumes the same width as the first button. It does not stretch across the width of the FlowLayoutPanel control.

As per [How to: Anchor and Dock Child Controls in a FlowLayoutPanel Control](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/how-to-anchor-and-dock-child-controls-in-a-flowlayoutpanel-control) the `button` width (which was added first) dictates the `ChromiumWebBrowser` width.

If you change to `Dock = DockStyle.None` then you'll get a full width, `100px` height browser.

Happy to add a comment to the two constructor overloads that default `DockStyle.Fill` to make it clearer that's the default behaviour. We should also look at overriding `Control.DefaultSize` so when no height is specified the browser will draw (currently it's height is 0 as there is no default in that scenario).

I make no claims that I'm an expert on `FlowLayoutPanel`, this to me looks more like a misunderstanding of how the controls are sized combined with an unexpected default `DockStyle.Fill`.
