### ISSUE TITLE
show Error AllocateAndMapSharedMemory failed

### ISSUE THREAD

**Issue by maxcsmsu** [cefsharp/CefSharp#3020]
What version of the product are you using?

75.1.143

    What architecture x86 or x64?

x84

    On what operating system?

Windows10 Enterprise 2016 LTSB

    Are you using WinForms, WPF or OffScreen?

WinForms

CefSharp  have show Error 
```

broker_win.cc(55)] Error reading broker pipe: The pipe has been ended. (0x6D)
command_buffer_proxy_impl.cc(94)] ContextResult::kFatalFailure: AllocateAndMapSharedMemory failed
```
I need a solution to this problem.

**Comment by amaitland** [comment]
Make sure your application is large address aware see https://github.com/cefsharp/CefSharp/wiki/General-Usage#win32-out-of-memory

If you can reproduce the problem with [v79.1.310-pre](https://github.com/cefsharp/CefSharp/releases/tag/v79.1.310-pre) then you should ask on https://magpcss.org/ceforum/index.php as you are seeing a low level chromium error which is not specific to `CefSharp`.
