### ISSUE TITLE
CanExecuteJavascriptInMainFrame incorrectly false after loading page with different origin

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#3021]
- **What version of the product are you using?**

79.1.310-pre

- **What architecture x86 or x64?**

Both

- **On what operating system?**

Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**

WinForms/WPF/OffScreen

- **What steps will reproduce the problem?**
   - Open the WPF or WinForms example projects
   - Attach debugger breakpoint at https://github.com/cefsharp/CefSharp/blob/cefsharp/79/CefSharp.Core/Internals/ClientAdapter.cpp#L1049
   - Attach debugger breakpoint at https://github.com/cefsharp/CefSharp/blob/cefsharp/79/CefSharp.Core/Internals/ClientAdapter.cpp#L1073
   - Wait for google.com to load
   - Load a second web page with a different origin e.g. github.com

- **What is the expected output? What do you see instead?**

**Expected**
After loading google.com
SetCanExecuteJavascriptOnMainFrame(true)
After loading github.com
SetCanExecuteJavascriptOnMainFrame(true)
SetCanExecuteJavascriptOnMainFrame(false)

**Actual**
After loading google.com
SetCanExecuteJavascriptOnMainFrame(true);
After loading github.com
SetCanExecuteJavascriptOnMainFrame(false;
SetCanExecuteJavascriptOnMainFrame(true);

The order of the process messages from the render process is sent in a different order than expected after a render process switch.

**Comment by amaitland** [comment]
The options at this stage are

1. Remove CanExecuteJavascriptInMainFrame 
2. Set CanExecuteJavascriptInMainFrame  via a combination of FrameLoadStart/FrameLoadEnd/LoadingStateChanged

**Comment by amaitland** [comment]
The checks are only used in the extension methods, you can directly call the relevant `IFrame` methods and no checks will be performed.
- http://cefsharp.github.io/api/79.1.x/html/M_CefSharp_IFrame_EvaluateScriptAsync.htm
- http://cefsharp.github.io/api/79.1.x/html/M_CefSharp_IFrame_ExecuteJavaScriptAsync.htm

The extension methods execute on the main frame, call [ChromiumWebBrowser.GetMainFrame()](http://cefsharp.github.io/api/79.1.x/html/M_CefSharp_WebBrowserExtensions_GetMainFrame.htm) which will return an `IFrame` instance.

**Comment by amaitland** [comment]
From memory the frame identifier changes on render process switch,  we might be able to use this to discard the second message.

**Comment by JogyBlack** [comment]
We have a similar issue, and a workaround that we implemented is to force a reload of the browser if CanExecuteJavascriptInMainFrame is false:

```
...
browser.LoadingStateChanged += Browser_LoadingStateChanged;
...
private void Browser_LoadingStateChanged(object sender, LoadingStateChangedEventArgs e)
{
  if (!e.IsLoading)
  {
    if (!browser.CanExecuteJavascriptInMainFrame)
      browser.Reload();
  }
}
```

The immediate reloading of the page is not very noticeable, and when the reloading finishes, CanExecuteJavascriptInMainFrame is true and we can execute JS on the page.

**Comment by amaitland** [comment]
- [ ] Ignore OnContextReleased that arrives after OnContextCreated when the `frameId` is greater.
- [ ] Add unit tests.

**Comment by amaitland** [comment]
The [v81.3.20-pre](https://github.com/cefsharp/CefSharp/releases/tag/v81.3.20-pre) packages are now on `Nuget.org` for anyone interested in testing this.

**Comment by Cloudmersive** [comment]
This was never fixed

**Comment by amaitland** [comment]
The test case added in commit https://github.com/cefsharp/CefSharp/commit/2a62f97392810760c3766f3afb2f2ebd4ba70195 passes successfully. If you are having problems please provide a failing test case (Please create a pull request).
