### ISSUE TITLE
CefSharp.BrowserSubprocess.exe crashes when getting disposed using a non-existing url

### ISSUE THREAD

**Issue by buddde** [cefsharp/CefSharp#3022]
### Bug Report

- **System environment**
    - cef.redist.x86 75.1.14 and CefSharp.WinForms 75.1.143 on .NET 4.6.1
    - Windows 10 1909 x64
    - WinForms using a WindowsFormsHost in a WPF-app (x86)

- **What steps will reproduce the problem?**
    - I start a `"WinForms" ChromiumWebBrowser` using a non-existing url https://www.spoegel.de, hosting it in a `WindowsFormsHost`
    - When I dispose the `ChromiumWebBrowser`, the whole app crashes
    - Please provide detailed information here, enough for someone else to reprodce your problem.
    - Please no binary (zip, etc) links, fork the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) and push your changes to `GitHub`. (Alternatively use a code sharing service list `Gist` or `Pastebin`).

- **Expected**
    - I expect that only a single `CefSharp.BrowserSubprocess.exe` gets killed, not all `CefSharp.BrowserSubprocess.exe`s and the whole app
    - When using an existing url https://www.spiegel.de, everything works as expected

- **Additional information**
    - No stack trace available, no exceptions
    - The cef log provides no relevant information?
    - No other 3rd party controls?
    - The Windows event viewer is empty as well

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

    - Short answer: no
    - Long answer:
    - I used the `cef_binary_79.1.31+gfc9ef34+chromium-79.0.3945.117_windows64_client` an started it running cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu
    - I opened Tests / New window, typed in the non-existing url https://www.spoegel.de, hit enter, waited a few seconds and finally closed the window; the app did not crash
    - `chrome://version`
        - CEF | 79.1.31+gfc9ef34+chromium-79.0.3945.117
        - Chromium | 79.0.3945.117
        - WebKit | 537.36 (@04f0a055010adab4484f7497fbfdbf312c307f1d)
        - JavaScript | 7.9.317.32
[Chrome.zip](https://github.com/cefsharp/CefSharp/files/4107158/Chrome.zip)

**Comment by amaitland** [comment]
> Please only create an issue if you can reproduce the problem with the latest version. (If you are using the latest stable release please check to see if there is a newer -pre release and test with that also).

As part the [Bug Report](https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report) please try with [v79.1.310-pre](https://github.com/cefsharp/CefSharp/releases/tag/v79.1.310-pre)

> * Please no binary (zip, etc) links, fork the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) and push your changes to `GitHub`. (Alternatively use a code sharing service list `Gist` or `Pastebin`).

Please provide an example that reproduces your problem. preferably a form of the `MinimalExample`.

> * I used the `cef_binary_79.1.31+gfc9ef34+chromium-79.0.3945.117_windows64_client` an started it running cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu

As per the [Bug Report](https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report)  **It's important to you test with the same version that CefSharp is based on.** 

In future please test with the exact same version of `CEF`, which in this case would be `75.1.14`

> * Chrome.zip

I have no idea what this zip file is, as stated above please no binaries (includes zip).

**Comment by buddde** [comment]
I tried v79.1.310-pre, no changes. App still crashes.

I made an example here: https://github.com/buddde/CefSharp.MinimalExample

**Comment by amaitland** [comment]
> I made an example here: https://github.com/buddde/CefSharp.MinimalExample

Thank you for the example. I'm not seeing any exception, both close buttons work as expected. Both browser instances load valid websites. A non-existant website also closes correctly.

What is the exception you are seeing exactly? No images of exceptions please.

If the error occurs in `libcef.dll` then you can download the `libcef.dll.pdb` from http://opensource.spotify.com/cefbuilds/cef_binary_79.1.31%2Bgfc9ef34%2Bchromium-79.0.3945.117_windows32_release_symbols.tar.bz2 and extract it next to `libcef.dll` in the `bin` folder to get a more meaningful exception.

**Comment by buddde** [comment]
You are right. It crashes on me dev-machine all the time but at home, everything works as expected.

**Comment by amaitland** [comment]
Try a clean checkout on your work machine. Will need a stack trace.

**Comment by buddde** [comment]
I have no stacktrace so i will close this issue and the behavior is different on different machines.

Thank you for all.
