### ISSUE TITLE
WM_TOUCH not longer received on cefWidgetWindow

### ISSUE THREAD

**Issue by ekalchev** [cefsharp/CefSharp#3023]
### Bug Report
WM_TOUCH not longer received on cefWidgetWindow

- **What version of the product are you using?**
   CefSharp 73

- **What architecture x86 or x64?**
x86
- **On what operating system?**
Windows10

We have a code that listen for WM_TOUCH event on the chrome widget window. Recently we found that after CefSharp 73 upgrade we no longer receive this window message. @amaitland can you remember a change done in CefSharp or upstream that might be related to this issue?

**Comment by amaitland** [comment]
> WM_TOUCH not longer received on cefWidgetWindow

Assuming you mean `Chrome_RenderWidgetHostHWND`

> * **What version of the product are you using?**
>   CefSharp 73

This is an old unsupported version. 

> Please only create an issue if you can reproduce the problem with the latest version. (If you are using the latest stable release please check to see if there is a newer -pre release and test with that also).

As per the [Bug Report](https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report) please test with the current version before opening future issues. You can test with [v79.1.310-pre](https://github.com/cefsharp/CefSharp/releases/tag/v79.1.310-pre) which is based on the current supported `CEF` version. The official release should be out in a week or so.

> We have a code that listen for WM_TOUCH event on the chrome widget window. Recently we found that after CefSharp 73 upgrade we no longer receive this window message

`WM_TOUCH` is very old, maybe they migrated to `WM_POINTER`?

The reality is you are relying on an implementation detail on the inner workings on `Chromium`. It's not part of the official `API` and could change at any time, we have no control over that.

Closing as `upstream` as we have absolutely no control over this behaviour.

**Comment by ekalchev** [comment]
It seems WM_TOUCH is no longer sent to Chrome_RenderWidgetHostHWND and I can see WM_POINTERUPDATE messages are being sent. Thanks for the hint. Yes, I am aware I rely on inner implementation but when there is no API, that is the only way .
