### ISSUE TITLE
Debugger Sources Tab is missing Code Highlighting for .js files

### ISSUE THREAD

**Issue by JohnRambo90** [cefsharp/CefSharp#3029]
Hi,

I'm facing currently a weird problem that the code highlighting is missing after updating to the latest cefsharp version.

How it should look:
![image](https://user-images.githubusercontent.com/16563143/73451893-e7a17780-4368-11ea-8552-746b7b496b02.png)

How it looks currently:
![image](https://user-images.githubusercontent.com/16563143/73451823-ca6ca900-4368-11ea-83c5-0b2a19d013e5.png)

* Chromium Version: Chrome/79.0.3945.130 
* CEFSHarp Verison: 
![image](https://user-images.githubusercontent.com/16563143/73451993-3c44f280-4369-11ea-94db-c862ef3f6b06.png)

I found something that may relates to that issue: https://github.com/brave/brave-browser/issues/7424

Kind Regards

John

**Comment by amaitland** [comment]
It's important to note that `CefSharp` is just a wrapper around the `Chromium Embedded Framework (CEF)`. Closing this as `upstream` and as changes need to be made in `CEF`. 

The `CEF` project has it's own issue tracker located at https://bitbucket.org/chromiumembedded/cef it is recommended you ask on https://magpcss.org/ceforum/index.php before opening an issue on the CEF issue tracker. 

If you do find an existing issue that matches this one or create a new one then post a link here for others to follow.

**Comment by amaitland** [comment]
Looks like you created https://bitbucket.org/chromiumembedded/cef/issues/2870/debugger-sources-tab-is-missing-code

In future please use the [Bug Report Template](https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report).
