### ISSUE TITLE
Unittest / CI

### ISSUE THREAD

**Issue by JanEggers** [cefsharp/CefSharp#303]
I want to enable unittests again 

i already migrated to xunit in a private branch as discussed with @perlun somewhere.

so one of my next tasks would be to create a cherrypick pr for that changes and then
create a Project at TeamCity.CodeBetter.com.

any thoughts on teamcity / preferences in another direction ?

**Comment by perlun** [comment]
This has been stale for a looooong time. Do we have any unit tests running on AppVeyor now, can we close this @jornh and/or @JanEggers?

**Comment by JanEggers** [comment]
ill close the issue i dont have any clue whats the current state of the codebase.
