### ISSUE TITLE
WPF - Change IsBrowserInitialized from DependencyProperty to standard get property.

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#3033]
There are instances when it's necessary to check `IsBrowserInitialized`, currently in `WPF` this can only be done on the `UI` thread.

Related issue https://github.com/cefsharp/CefSharp/issues/3032 (changes from this issue should be reverted once `IsBrowserInitialized ` is a regular property).

The only downside is you cannot bind to `IsBrowserInitialized`, not sure how many people actually do this.

**Comment by jtorjo** [comment]
Just as a heads-up - we're counting on IsBrwoserInitialized, in our app, to be a dependency property

**Comment by amaitland** [comment]
What is your use case? There are many cases that a dependency property is unworkable.

There is nothing stopping you from adding your own attached property and subscribing to the event.

**Comment by amaitland** [comment]
I've added `IWebBrowser.IsBrowserInitialized` explicit interface implementation in https://github.com/cefsharp/CefSharp/commit/3ba029067660cb4c6c18887c394fec99e71ddd83

I haven't tested this property yet, and it will still depend on #3082 to determine if this approach is viable for reducing code duplication.

**Comment by amaitland** [comment]
With #3082 it's now possible to move all the internal checks into a partial class, no need to rely on extension methods. 

With commit https://github.com/cefsharp/CefSharp/commit/71773424dcbb4ec9373d6e1efb8279fb7adc8c59 the code has been simplified, will leave the `DependencyProperty` as is for now.

For those wishing to check `ISbrowserInitialized` on a `non UI Thread` in `WPF` can use the explicit interface implementation (`IWebBrowser.IsBrowserInitialized`).
