### ISSUE TITLE
Chromium not printing all PDF page.

### ISSUE THREAD

**Issue by Aadithan** [cefsharp/CefSharp#3035]
**- What version of the product are you using?**   75.1.142
 
**- What architecture?** x86 
 
**- On what operating system?**  Win10
 
**- Are you using `WinForms`, `WPF` or `OffScreen`?**  WinForms
 
**- What steps will reproduce the problem?**
   When printing PDF (1-3) pages it works fine. If PDF is more 4 pages it shows up in system printer queue with status of spooling and disappears within seconds and this happens only in version 75 and 79. When I had 55 version it was working fine. 

**- Does this problem also occur in the `CEF` Sample Application from :** 

Its not happening in sample application also it is not happening in google chrome.

**Comment by amaitland** [comment]
Please confirm which version of cefclient you tested with and the command line args you used to test with.

Please include a step by step list of instructions to reproduce this issue.

**Comment by amaitland** [comment]
Also add the --no-sandbox command line when testing cefclient and Chrome. There are other instance where pdfs don't behave correctly when the sandbox is disabled.  Sandbox requires statically linking a lib which is not supported in .Net.

**Comment by Aadithan** [comment]
I am using CefSharp.MinimalExample.WinForms.exe  version 79 but I am not able to replicate the issue in your sample app. I am able to replicate only from application WebBrowserExtensions.Print().

**Comment by amaitland** [comment]
> I am able to replicate only from application when i click print icon on right hand side corner of chromium browser.

What `application` are you referring? What `print icon`? Are you referring to the `Toolbar` in the top right? Please be specific, more detail makes for a better bug report. 

As the `MinimalExample` works correctly it's more likely a problem in your application. A sample that reproduces the issue (fork is the `MinimalExample`) and step by step list of instructions is required.

This sort of issue is rarely a bug in `CefSharp`, it has no control over priting, just sends the command off to `CEF/Chromium`.
