### ISSUE TITLE
WPF - NullReferenceException when Dispose called before IBrowser created

### ISSUE THREAD

**Issue by timaiv** [cefsharp/CefSharp#3037]
- What version of the product are you using? 79
- Are you using WinForms, WPF or OffScreen? Wpf

- What steps will reproduce the problem?
Dispose() before OnAfterBrowserCreated.

In 75 version dispose didn't contain this code:
//Stop rendering immediately so later on when we dispose of the
//RenderHandler no further OnPaint calls take place
**browser.GetHost**().WasHidden(true);

**Comment by amaitland** [comment]
> * What steps will reproduce the problem?
>   Dispose() before OnAfterBrowserCreated.

Please provide the stack trace and a code example that reproduces the problem.

**Comment by timaiv** [comment]
![image](https://user-images.githubusercontent.com/36565658/73590468-51498f00-44eb-11ea-8313-8c74241b6c22.png)

**Comment by timaiv** [comment]
Minimal code example that reproduces the problem:
new ChromiumWebBrowser().Dispose();

**Comment by amaitland** [comment]
In future please post the stack trace as text, you can use the `copy to clipboard` feature in visual studio.
