### ISSUE TITLE
WPF unable to load Cefsharp.Core or one of it's dependicies

### ISSUE THREAD

**Issue by minecraftchest1** [cefsharp/CefSharp#3039]
### Please only open an issue if you have a BUG to report, if you simply have a question or require some assistance keep reading for info. If you do have a BUG to report, please use the Bug Report template below.

So you have a question to ask, where can you look for answers? Read on. Think you've found a bug? Please take the time to fill out the bug report below, provide as much information as you can, make sure you provide information for every heading. Thank you! We'd like to keep issues exclusively for **bug reports**, so please ask your questions on `Gitter`

- Start by reading the General Usage guide, it answers all the common questions https://github.com/cefsharp/CefSharp/wiki/General-Usage
- Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
- GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
- You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
- You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Still have a question? Great, ask it on `Gitter`. https://gitter.im/cefsharp/CefSharp

**Note: CefSharp is just a wrapper around the Chromium Embedded Project, it's worth searching http://magpcss.org/ceforum/index.php if your problem involves a low level Chromium error message**

We ask that you put in a reasonable amount of effort in searching through the resources listed above. The developers have full time jobs, they have lives, families, the time they have available to contribute this project is a precious resource, make sure you use it wisely! Remember the more time we spend answering the same questions over and over again, less time goes into writing code, adding new features, actually fixing bugs!

Still have a question to ask or unsure where to go next? Start with the Gitter Chat room : https://gitter.im/cefsharp/CefSharp

--
### Bug Report
Delete this line and everything above, and then fill in the details below.

- **What version of the product are you using?**
    - What version are you using? Nuget? CI Nuget? build from a branch? If so please link to the relevant commit.
	- Please include the exact version number you are using e.g. 79.1.350 (no ambiguous statements like `Latest from Nuget`)
    - Please only create an issue if you can reproduce the problem with version 79.1.350 or greater.

- **What architecture x86 or x64?**
    <x86/x64>
- **On what operating system?**
    <Win7/Win8.1/Win10>

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    <WinForms/WPF/OffScreen>
- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.
    - Please no binary (zip, etc) links, fork the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) and push your changes to `GitHub`. (Alternatively use a code sharing service list `Gist` or `Pastebin`).

- **What is the expected output? What do you see instead?**

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?

- **Does this problem also occur in the `CEF` Sample Application**
    - Download one of the following:
	    - For x86 download http://opensource.spotify.com/cefbuilds/cef_binary_79.1.35%2Bgfebbb4a%2Bchromium-79.0.3945.130_windows32_client.tar.bz2
	    - For x64 download http://opensource.spotify.com/cefbuilds/cef_binary_79.1.35%2Bgfebbb4a%2Bchromium-79.0.3945.130_windows64_client.tar.bz2
	- If you are using WPF/OffScreen run cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu
    - If you are using WinForms run cefclient --multi-threaded-message-loop
	- **MAKE SURE TO TEST WITH THE COMMAND LINE ARGS LISTED ABOVE**
    - If you can reproduce the problem with `cefclient` then you'll need to report the bug on https://bitbucket.org/chromiumembedded/cef/overview there is no point opening an issue here. (Make sure you search before opening an issue)

**Comment by minecraftchest1** [comment]
Submitted before I wanted it to.

**Comment by amaitland** [comment]
This is unlikely a bug, read the FAQ https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#Runtime_dependencies

If you are using .Net Core then read #2796 for additional steps required.

Further questions please use one of the support options listed above.

**Comment by minecraftchest1** [comment]
Updated the issue to how I wanted it to be originally.

**Comment by amaitland** [comment]
> What version of the product are you using?

Please specify which version you are using. You've left the default text from the template.

> Please provide detailed information here, enough for someone else to reprodce your problem.
> Please no binary (zip, etc) links, fork the MinimalExample and push your changes to GitHub. (Alternatively use a code sharing service list Gist or Pastebin).

An example that reproduces the problem is required. Preferably fork the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) and push your changes to `GitHub` (squash your changes into a single commit please). If you are unable to reproduce the problem with the `MinimalExample` then you should compare it to your project as a reference.

Please make sure you've read the [Post Installation Instructions](https://github.com/cefsharp/CefSharp/blob/cefsharp/79/NuGet/Readme.txt#L7) that were displayed when you installed the `Nuget` packages.

> When I run my own test application through VisualStudio, built in the same project as CefSharp, it gives me the error "Unable to load Cefsharp.core or one of its dependencies."

This doesn't help anyone who doesn't have access to your solution reproduce the problem.

> Output from visual studio: [https://github.com/minecraftchest1/me/blob/master/2-4-2020%20VsOutput](url)

The link is broken. In any case `output from visual studio` isn't a substitute for a full stack trace.

---
As it stands there is insufficient information to reopen this issue. I suspect it's problem with your project configuration.

**Comment by minecraftchest1** [comment]
I am not sure how to find the version number. I am creating an empty wpf application and adding only the cefsharp browser control. This error also occured when trying to build and run the provided wpf test application. Sorry about putting this together piecemeal.

**Comment by minecraftchest1** [comment]
@amaitland  Have you tried copying and pasting the link? The file exists so I don't think thas is a problem.

**Comment by pmuessig** [comment]
@minecraftchest1 If you are using netcore3.1 i ran into this issue and was able to fix it.

The solution is demonstrated here to ensure the correct dependencies are loaded by the coreclr at runtime: https://github.com/cefsharp/CefSharp.MinimalExample/blob/898eb755c6bb7f504f9b5bdc889ff9142e105848/CefSharp.MinimalExample.Wpf/CefSharp.MinimalExample.Wpf.netcore.csproj#L19

this will most likely be unnecessary as the netcore3.1 support matures.

**Comment by minecraftchest1** [comment]
@pmuessig I will give that a try.

**Comment by minecraftchest1** [comment]
@pmuessig Still giving me the same problem. Thanks for the help though.
