### ISSUE TITLE
Problem with PDF and layer

### ISSUE THREAD

**Issue by piotrwl** [cefsharp/CefSharp#3040]
Hello!
I have a problem in a project that uses CEF.
The page it loads has support for certain functions on the layer launched from JavaScript.
When the PDF document is open underneath, the elements of the layer above the document are inactive, while the PDF underneath is activated.
This functionality works properly in IE, Chrome and Firefox.
What could be wrong?

Attached is my example (simplified of course).
There is a format and the bottom has a PDF file loaded.
The user clicks on the function that shows the layer with the format loaded. Part of the form above the PDF is inactive in CEF - it works in Chrome.
Unfortunately, this is an old application and I cannot change its code.

Windows 10, Cefsharp
![screen](https://user-images.githubusercontent.com/19430577/73726027-f011fd80-472e-11ea-803c-4d256b80e749.jpg)

[sample.zip](https://github.com/cefsharp/CefSharp/files/4152056/sample.zip)

**Comment by piotrwl** [comment]
Please review and reopen

**Comment by amaitland** [comment]
What command line args did you use when testing the `CEF Sample Application`?

The command line args listed in the bug report are.
```
cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu
```

If you have trouble resizing the browser then use
```
cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu --disable-gpu --disable-gpu-compositing
```

**Comment by piotrwl** [comment]
If I run

`cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu`

the problem also occurs

**Comment by amaitland** [comment]
It's a bug in `CEF`. In future please use the command line args listed in the bug report.

Looks like you've discussed your problem at https://magpcss.org/ceforum/viewtopic.php?f=6&t=17333&start=10#p44573 anyone else experiencing this problem should continue the conversation there.

**Comment by piotrwl** [comment]
I checked that the problem is set to --off-screen-rendering-enabled.
Can it be turned off in WPF version?

**Comment by amaitland** [comment]
No

**Comment by amaitland** [comment]
You can host the WinForms version in WPF using a WindowsFormsHost.

**Comment by piotrwl** [comment]
Thank you
