### ISSUE TITLE
InvokeOnUiThreadIfRequired now internal

### ISSUE THREAD

**Issue by daphonk** [cefsharp/CefSharp#3042]
Hi, I read in the new release InvokeOnUiThreadIfRequired is now internal.

How to I now realise this code:

this.InvokeOnUiThreadIfRequired(() => outputLabel.Text = output);

**Comment by amaitland** [comment]
Duplicate of #2983 

Implement your own version,  the code is in the source.

**Comment by amaitland** [comment]
See also #2980 which contains background information and an example
