### ISSUE TITLE
Unable to add CefSharp.WinForms.ChromiumWebBrowser using designer

### ISSUE THREAD

**Issue by Ninjastorm380** [cefsharp/CefSharp#3044]
- **What version of the product are you using?** 
Using CefSharp Version 79.1.350
Using Nuget from Package Manager console in Visual Studio 2019
Project targets X64
Environment is Windows 10 Professional
Using CefSharp.WinForms

Steps to reproduce this problem:
- Create a new WinForms project
- Use Nuget from the Package Manager to install CefSharp version 79.1.350
- Once Nuget completes, attempt to add a new ChromiumWebBrowser
- The designer will complain about being unable to load the selected component and that the component will be removed from the toolbox

Expected Result:
- I expect to be able to add a new ChromiumWebBrowser from the toolbox.

Designer provides no stack trace information
was able to add via code and run it successfully

CefClient fails to execute, debug.log doesn't exist

**Comment by amaitland** [comment]
As @Geevo has pointed out x64 is not supported by the design.

**Comment by amaitland** [comment]
https://developercommunity.visualstudio.com/comments/514701/view.html

**Comment by amaitland** [comment]
Same goes for the WPF version https://developercommunity.visualstudio.com/content/problem/603258/vs-2019-wpf-designer-x64-app-configuration-bug-doe.html
