### ISSUE TITLE
Font Glyphs no longer rendering

### ISSUE THREAD

**Issue by GrabzIt** [cefsharp/CefSharp#3045]
I know this is a upstream issue but I thought I better mention it here so everyone is aware as this is quite a serious issue. The current version (79.1.350) does not render font glyphs anymore which can mess up a lot of websites. I have raised a case here: https://bitbucket.org/chromiumembedded/cef/issues/2877/font-glyphs-no-longer-rendering

I had to cancel the upgrade because of it. Hopefully they will release a fix soon.

**Comment by amaitland** [comment]
@GrabzIt Based on your comment at https://bitbucket.org/chromiumembedded/cef/issues/2877/font-glyphs-no-longer-rendering#comment-56096797 I created http://cefsharp.github.io/demo/robotofont.html for testing purposes.

Testing with the newly created [cefsharp/83](https://github.com/cefsharp/CefSharp/tree/cefsharp/83) branch and the glyphs look the same as in `Chrome` now.

Closing as problem appears to be resolved `upstream`. If you can reproduce the problem with version `83` please let me know.

See #3139 for details on the upcoming `83` release.

**Comment by GrabzIt** [comment]
That's awesome thanks!!
