### ISSUE TITLE
CEFSharp is not blocking Adobe Flash Player

### ISSUE THREAD

**Issue by kylindebug** [cefsharp/CefSharp#3046]
- **What version of the product are you using?**
    Version 79.1.350 from NuGet.

- **What architecture x86 or x64?**
    x64

- **On what operating system?**
    Windows 10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WPF

- **What steps will reproduce the problem?**
    Load the test site of adobe flash player  https://www.ultrasounds.com/  through ChromiumWebBrowser, it will display "This plugin is not supported", but the result will be different when accessed via google chrome, it will display "Adobe Flash Player is blocked".
      The settings under blow have been applied but didn't work.
            cefSettings.CefCommandLineArgs["enable-system-flash"] = "0";
            cefSettings.CefCommandLineArgs.Add("--disable-bundled-ppapi-flash");
            cefSettings.CefCommandLineArgs.Add("--disable-internal-flash");
            cefSettings.CefCommandLineArgs.Add("--disable-plugins-discovery");

- **What is the expected output? What do you see instead?**
   Different results mean that the website has detected ChromiumWebBrowser and can take steps to block it.
   Adobe will stop the support of Flash after 2020, may we put the matter of solving this problem on the list.

**Comment by amaitland** [comment]
Disabling `Flash` by default seems reasonable, I've created #3048 to track that.

> * cefSettings.CefCommandLineArgs["enable-system-flash"] = "0";

This is incorrect. You have to remove `enable-system-flash` from the collection. 

> * it will display "This plugin is not supported", but the result will be different when accessed via google chrome, it will display "Adobe Flash Player is blocked".

This needs to be changed in `CEF` . You should ask on http://magpcss.org/ceforum/index.php (post a link back here). Last I checked `CEF` wasn't planning on fixing any `Flash` Related issues (https://bitbucket.org/chromiumembedded/cef/issues/2768/allow-flash-to-play-without-user#comment-54073974) so it's unlikely you'll get this changed.

> - **Does this problem also occur in the `CEF` Sample Application**
>     - Download one of the following:
> 	    - For x86 download http://opensource.spotify.com/cefbuilds/cef_binary_79.1.35%2Bgfebbb4a%2Bchromium-79.0.3945.130_windows32_client.tar.bz2
> 	    - For x64 download http://opensource.spotify.com/cefbuilds/cef_binary_79.1.35%2Bgfebbb4a%2Bchromium-79.0.3945.130_windows64_client.tar.bz2
> 	- If you are using WPF/OffScreen run cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu
>     - If you are using WinForms run cefclient --multi-threaded-message-loop
> 	- **MAKE SURE TO TEST WITH THE COMMAND LINE ARGS LISTED ABOVE**
>     - If you can reproduce the problem with `cefclient` then you'll need to report the bug on https://bitbucket.org/chromiumembedded/cef/overview there is no point opening an issue here. (Make sure you search before opening an issue)

Please complete this section in the future, it's important you test with the `CEF Sample Application`.

Closing as `upstream` as any changes need to be made in `CEF`.
