### ISSUE TITLE
Disable Adobe Flash By Default

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#3048]
`Chrome` has disabled it, we should as well (remove the `enable-system-flash` command line arg from `CefSettings`).

https://www.chromium.org/flash-roadmap#TOC-Flash-Disabled-by-Default-Target:-Chrome-76---July-2019-

It can still be enabled for a limited time.

- [x] Remove `enable-system-flash` command line arg
- [x] Add example of adding `enable-system-flash` 
- [x] Update https://github.com/cefsharp/CefSharp/wiki/General-Usage#adobe-flash-player-pepper-flash

**Comment by Wizard13** [comment]
I have a created a winforms browser for the purpose of executing many flash files that are stored locally in my web server and I use:
```
settings.CefCommandLineArgs.Add("ppapi-flash-path", "pepflashplayer64_32_0_0_321.dll");
settings.CefCommandLineArgs.Add("ppapi-flash-version", "32.0.0.321");
settings.CefCommandLineArgs.Add("disable-plugins-discovery", "1");
```
I plan to keep the last cefsharp version that will execute flash files. Will this still work for the time being for v81?

**Comment by amaitland** [comment]
All I can say is the command line args is going to be removed by default. 

CEF is not actively supporting flash anymore so it could stop working any time. https://bitbucket.org/chromiumembedded/cef/issues/2768/allow-flash-to-play-without-user#comment-54073974

**Comment by amaitland** [comment]
Anyone interested in the status of `Flash` support in `Chromium` should check https://www.chromium.org/flash-roadmap#TOC-Upcoming-Changes periodicly.

It is possible to enable the system wide flash using.
This will probably work for the next few releases though there are no gurantees.
```c#
// Specify Global Settings and Command Line Arguments
var settings = new CefSettings();

// For a limited time you can still enable flash
// Enable System Wide Flash Installation
settings.CefCommandLineArgs.Add("enable-system-flash");

Cef.Initialize(settings);
```

Previously this command line arg was set by default, it was removed in https://github.com/cefsharp/CefSharp/commit/d1279810ff1f9c9b60c0cda37776c449c6e29106

This is the **only** change from a `CefSharp` point of view.

If `Flash` stops working for whatever reason then you will have to revert to a previous version as `CEF` is no longer supporting `Flash`.
