### ISSUE TITLE
Debug console is not woking since using Chrome v80

### ISSUE THREAD

**Issue by Charge71** [cefsharp/CefSharp#3049]
- **What version of the product are you using?**
    - What version are you using? Nuget? CI Nuget? build from a branch? If so please link to the relevant commit.
	 79.1.350 NugetCI
- **What architecture x86 or x64?**
    both x86 and x64
- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WPF
- **What steps will reproduce the problem?**
    - Activate debugging from code using "RemoteDebuggingPort"
   - launch application
   - open localhost:8088 (or the port you defined in RemoteDebuggingPort)
   - see list of open cef browser instances
   - click on one item to see detail
   - you get a blank screen and console has the following error
`document.registerElement is not a function`

![Annotazione 2020-02-10 115915](https://user-images.githubusercontent.com/20799552/74145216-901fc900-4bfe-11ea-9ca8-a953cec83dbf.png)

- **What is the expected output? What do you see instead?**
  - debug console should open like it used to with previous Chrome versions

**Comment by amaitland** [comment]
`CefSharp` is just one of many wrappers around the [Chromium Embedded Framework (CEF)](https://bitbucket.org/chromiumembedded/cef/)

The `CEF` project has it's own [Issue Tracker](https://bitbucket.org/chromiumembedded/cef/issues). It is recommended you ask on the [CEF Forum](https://magpcss.org/ceforum/index.php) before opening an issue.

Closing this as `upstream` and as changes/fixes need to be made in `CEF`.

**Comment by amaitland** [comment]
Using https://github.com/cefsharp/CefSharp.MinimalExample and Testing with `Chrome Version 80.0.3987.87 (Official Build) (64-bit)` and I can connect and everythign appears to be working as expected. `document.registerElement` is defined as a native function.

<img width="952" alt="remotedebugging" src="https://user-images.githubusercontent.com/307872/74147739-968a6100-4c4f-11ea-824b-b037f1dbca82.PNG">

> Does this problem also occur in the CEF Sample Application
> 
> Download one of the following:
> For x86 download http://opensource.spotify.com/cefbuilds/cef_binary_79.1.35%2Bgfebbb4a%2Bchromium-79.0.3945.130_windows32_client.tar.bz2
> For x64 download http://opensource.spotify.com/cefbuilds/cef_binary_79.1.35%2Bgfebbb4a%2Bchromium-79.0.3945.130_windows64_client.tar.bz2
> If you are using WPF/OffScreen run cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu
> If you are using WinForms run cefclient --multi-threaded-message-loop
> MAKE SURE TO TEST WITH THE COMMAND LINE ARGS LISTED ABOVE
> If you can reproduce the problem with cefclient then you'll need to report the bug on https://bitbucket.org/chromiumembedded/cef/overview there is no point opening an issue here. (Make sure you search before opening an issue)

Please complete the testing specified in the **Does this problem also occur in the CEF Sample Application** of the [Bug Report Template](https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report) (You committed this section from your bug report). Remote debugging is configurable with the [remote-debugging-port](https://peter.sh/experiments/chromium-command-line-switches/#remote-debugging-port) command line arg as specified in the documentation in [CefSettings.RemoteDebuggingPort](http://cefsharp.github.io/api/79.1.x/html/P_CefSharp_AbstractCefSettings_RemoteDebuggingPort.htm)

As stated above, `CefSharp` is just a wrapper., the `Chromium Embedded Framework(CEF)` provides the `Chromium` implementation.

**Comment by amaitland** [comment]
https://bitbucket.org/chromiumembedded/cef/issues/2879/debug-console-error

**Comment by Charge71** [comment]
> https://bitbucket.org/chromiumembedded/cef/issues/2879/debug-console-error

We have opened that issue following your suggestion.

Thank you for your help.

**Comment by amaitland** [comment]
Can you reproduce the issue with [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample)

Personally I cannot, seems like a problem with your application or the steps you've included are incomplete. Your issue on the `CEF` issue tracker includes very little detail, no steps to reproduce, no version, no indication you've tested with the `CEF Sample Application`.

**Comment by Charge71** [comment]
It ended up being a problem with some older libraries linked to the project that caused the version not being correctly updated.

Thank you again for your help.
