### ISSUE TITLE
CefSharp can't render video 

### ISSUE THREAD

**Issue by jeansusgodney** [cefsharp/CefSharp#3055]
Hi there, 

I have opened the website with several browsers and the video on my website plays just fine.

But when I open the page with WPF I can only see blank canvas on the video section. Here's the HTML code btw

`<video autoplay="autoplay" muted="" playsinline="" loop="">
					<source type="video/mp4" src="/fileadmin/videos/video.mp4">
				</video>`

**Comment by amaitland** [comment]
Mp4 is not supported see https://github.com/cefsharp/CefSharp/wiki/General-Usage#multimedia-audiovideo
