### ISSUE TITLE
Cant watch Videos

### ISSUE THREAD

**Issue by L30N-G** [cefsharp/CefSharp#3061]
Hey Guys, 
I use it for a ticket system and when a video is attached I cannot watch it.
I can open the link and then I get this error:

"Your Browser does not currently recognize any of the video formats aviable."

How can I fix it?

**Comment by amaitland** [comment]
As detailed in https://github.com/cefsharp/CefSharp/wiki/General-Usage#multimedia-audiovideo only freely available audio and video codecs are supported.
