### ISSUE TITLE
DeleteCookies by RequestContext returns true but is not getting deleted

### ISSUE THREAD

**Issue by pipiscrew** [cefsharp/CefSharp#3063]
**nuget DLLs** - v79.1.360.0

hi all,

so, I made a tabbed application, when the time came to handle the cookies : 
```
ICookieManager cookie_del = Cef.GetGlobalRequestContext().GetCookieManager(null);
bool f = cookie_del.DeleteCookies(url, name_value);
Console.WriteLine(f);
return f;
```
this returns **true**, but the cookie didnt get deleted.

@amaitland - check https://bit.ly/2wKLqq9

**Comment by amaitland** [comment]
Cookies are deleted asynchronous,  you'll need to provide a callback to be notified when they are deleted if you are trying to perform an action after they've been deleted. 

http://cefsharp.github.io/api/79.1.x/html/M_CefSharp_ICookieManager_DeleteCookies.htm
http://cefsharp.github.io/api/79.1.x/html/T_CefSharp_IDeleteCookiesCallback.htm

You can use the http://cefsharp.github.io/api/79.1.x/html/T_CefSharp_TaskDeleteCookiesCallback.htm implement and await the Task property,  the Task result will contain the number of cookies deleted. -1 indicates some sort of failure. 

You may also be accessing the  CefCookieManager before it's ready, pass in a callback to make sure http://cefsharp.github.io/api/79.1.x/html/M_CefSharp_IRequestContext_GetCookieManager.htm you can use http://cefsharp.github.io/api/79.1.x/html/T_CefSharp_TaskCompletionCallback.htm

There's nothing here that would indicate a bug in CefSharp,  please ask further questions using one of the options listed by the support bot.

**Comment by pipiscrew** [comment]
hi,

finally, solve it like this : 

```
private readonly ChromiumWebBrowser chrome;
.
.

//base
if (chrome.RequestContext == null)
{
	return Cef.GetGlobalCookieManager().DeleteCookies(url, name_value);
}
else
{ //RequestContext

	ICookieManager cookie_del = chrome.RequestContext.GetCookieManager(null);
	return cookie_del.DeleteCookies(url, name_value);
}
```
