### ISSUE TITLE
Custom cursor is not enlarged with High DPI and Display Scale 225% in WPF

### ISSUE THREAD

**Issue by jianping2010** [cefsharp/CefSharp#3071]
In #606, custom cursor is supported in WPF. But the custom cursor is not enlarged with High DPI and Display Scale 225%. 
The issue can be reproduced with the Wpf Example (x64) by doing the following:
1. Open the WPF example app
2. Open http://html5advent2011.digitpaint.nl/3/index.html and hover over Custom Cursor box. 
The custom cursor is not enlarged to Display Scale. The buildin cursor can be enlarged.
And custom cursor can also be enlarged with the Winform example app.

I am using WIN 10 x64, VS 2017，Nuget CefSharp.WPF version 79.1.360.

**Comment by amaitland** [comment]
`CefSharp` is just one of many wrappers around the [Chromium Embedded Framework (CEF)](https://bitbucket.org/chromiumembedded/cef/)

The `CEF` project has it's own [Issue Tracker](https://bitbucket.org/chromiumembedded/cef/issues). It is recommended you ask on the [CEF Forum](https://magpcss.org/ceforum/index.php) before opening an issue.

Before opening a new issue you should:

- Search open/closed issues to determine if the problem you are seeing has already been reported
- Test with a newer version if available, see https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-chromium-embedded-frameworkcef for details on testing with the `cefclient` sample application.

If you do find an existing issue that matches this one or create a new one then post a link here for others to follow.

Closing this as `upstream` and as changes/fixes need to be made in `CEF`.

**Comment by amaitland** [comment]
This was already reported as https://bitbucket.org/chromiumembedded/cef/issues/2850/osr-custom-cursor-is-not-scaled-for-high

In future please use the bug report template provided at https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report

**Comment by jianping2010** [comment]
@amaitland Thanks for replying and sorry for your inconvenience.
