### ISSUE TITLE
Needed files from cef?

### ISSUE THREAD

**Issue by nucombo** [cefsharp/CefSharp#3073]
Hi there,

I would like to know if there is a comprehensive list of files needed by cefsharp if I compile my own cef?

Best regards.

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/wiki/Output-files-description-table-%28Redistribution%29

**Comment by nucombo** [comment]
@amaitland thanks for the reply, one last question, do I need to compile cef in release mode and also compile cefsharp against the compiled cef files for it to work(using branch 3945 chrominium v79 cef v79 Nov 2019) or simple copiling cef in debug or release and dropping the files in the directory it should be, does the trick? Right now I tried with debug files but it doesn't seem to open at all.

Thanks for this amazing project!
