### ISSUE TITLE
Crash Only Seen on Surface Pro X

### ISSUE THREAD

**Issue by TonyValenti** [cefsharp/CefSharp#3077]
When trying to use CEF on a Surface Pro X, the following errors occur.  What can be done to resolve them?

Faulting application name: CefSharp.BrowserSubprocess.exe, version: 79.1.350.0, time stamp: 0x5e30e1c7
Faulting module name: KERNELBASE.dll, version: 10.0.18362.387, time stamp: 0xfe0f5f59
Exception code: 0xe0000008
Fault offset: 0x0026bc20
Faulting process id: 0x1330
Faulting application start time: 0x01d5f325b624e0eb
Faulting application path: C:\Users\aklma\AppData\Local\Clio\app-20.2.28\x86\CefSharp.BrowserSubprocess.exe
Faulting module path: C:\windows\System32\KERNELBASE.dll
Report Id: de141cf8-4856-47dc-9183-c49fbe9d8450
Faulting package full name: 
Faulting package-relative application ID: 

Faulting application name: CefSharp.BrowserSubprocess.exe, version: 79.1.350.0, time stamp: 0x5e30e1c7
Faulting module name: KERNELBASE.dll, version: 10.0.18362.387, time stamp: 0xfe0f5f59
Exception code: 0xe0000008
Fault offset: 0x0026bc20
Faulting process id: 0x1330
Faulting application start time: 0x01d5f325b624e0eb
Faulting application path: C:\Users\aklma\AppData\Local\Clio\app-20.2.28\x86\CefSharp.BrowserSubprocess.exe
Faulting module path: C:\windows\System32\KERNELBASE.dll
Report Id: de141cf8-4856-47dc-9183-c49fbe9d8450
Faulting package full name: 
Faulting package-relative application ID:

**Comment by amaitland** [comment]
The bug report template has lots troubleshooting steps, testing with the CEF Sample application is an absolute must for problems like this.
If cefclient crashes then ask on http://magpcss.org/ceforum/

The Surface Pro X uses an ARM64 processor,  running an x86 app in comparability mode is always likely to have problems. Raising a support request with Microsoft maybe your best bet.

**Comment by amaitland** [comment]
Asked here https://magpcss.org/ceforum/viewtopic.php?f=6&t=17441

**Comment by TonyValenti** [comment]
Hi @amaitland -
Is there a bounty that I can fund toward resolving this issue?  I don't know enough about everything ya'll need in order to get the right info but I have a dedicated device that can recreate the issue.  I would really like to get this resolved.
