### ISSUE TITLE
WPF - Browser Disposed when moved in Visual Tree

### ISSUE THREAD

**Issue by ml-ast** [cefsharp/CefSharp#3078]
## What version of the product are you using?

v79.1.360 from NuGet

## What architecture x86 or x64?

x86

## On what operating system?

Win10

## Are you using WinForms, WPF or OffScreen?

WPF

## What steps will reproduce the problem?

The usage scenario is integration of Chromium into Visual Studio. The attached example project can be used to reproduce the issue:

* Start experimental Visual Studio with the extension
* Open the "ToolWindow1"
* Move the Window pane into a separate Window
* Restart experimental instance -> The browser should still show up in a separate window
* Dock browser to main window -> FREEZE

* **What is the expected output? What do you see instead?**

* Browser should not freeze

## Findings

When CefSharp.Wpf.ChromiumBrowser is added to the Visual Tree ```OnLoaded``` is called. If no ```CleanupElement``` is set the method sets the containing windows as ```CleanupElement```. This in turn registers the callback ```OnCleanupElementUnloaded``` with the windows` ```Unload``` event.

If the browser-control is now moved to another window it will be disposed which in turn frees all allocated resources and freezes the view. As simple workaround is to set new ```Control``` that is not attached to any tree as ```CleanupElement```

**Comment by amaitland** [comment]
Please complete the [Bug Report](https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report)

**Comment by amaitland** [comment]
> - **What steps will reproduce the problem?**
>    - Please provide detailed information here, enough for someone else to reprodce your problem. 
>    - Does the problem reproduce using the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample)?
>    - If code is required to reproduce your problem then please provide one of the following
>      - Fork the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) and push your changes to `GitHub` (this is the preferred option).
>      - Use a code sharing service list `Gist` or `Pastebin`
>      - Paste your **formatted code as part of this issue** (only do this for small amounts of code and make sure you **format the code so it's reabily**)
>      - Please no binary attachments (zip, 7z, etc), code needs to be easily reviewed in a web browser.

Please fork the `MinimalExample` and provide an example that reproduces your problem. 

> he attached example project can be used to reproduce the issue:

There is no attached example. Please no binary attachments (zip, 7z, etc), code needs to be easily reviewed in a web browser.
