### ISSUE TITLE
WPF - Unable to select more than one word, and context menu won't go away when page is clicked.

### ISSUE THREAD

**Issue by polar-zhang** [cefsharp/CefSharp#3079]
- **What version of the product are you using?**
Nuget 79.1.360

- **What architecture x86 or x64?**
x64
- **On what operating system?**
    - Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
    - Run the browser on a WPF Window.
    - Open a web page with text which can be selected.
    - Long press the text, one word is selected, and "Copy" context menu appears.
    - Try to change the selected zone, or click anywhere on the page other than the menu itselft.

- **What is the expected output? What do you see instead?**
   The highlighted selected word should has two 'buttons' at both end, which allow us to drag the buttons to different direction to change the selected text range (Try select text on normal browser, you will get it.)
    The context menu "Copy" should go away, if click anywhere on the page.

- **What do you see instead?**
  Unable to select more than one word, because there is no "buttons" to change the selected text range.
  Context menu "Copy" won't disappear unless the menu is clicked.

**Comment by amaitland** [comment]
As per the [Bug Report Template](https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report) you need to test with the CEF Sample application.
