### ISSUE TITLE
BUG Wpf ERRORS shared CachePath

### ISSUE THREAD

**Issue by theonlyavengerreal** [cefsharp/CefSharp#3080]
- **What version of the product are you using?**
    79.1.360

- **What architecture x86 or x64?**
    x86
    
- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WPF
    
- **What steps will reproduce the problem?**
    - Reproduces using the [MinimalExample]
        * set CachePath eg to a folder inside LocalApplicationData
        1. start and  login to a website that stores login data (eg https://www.chrono.gg/ , youtube doesn't support the browser, others website should work also, but not GitHub for login)
        2. open a second new window (EXE), load the same website
          - see if slow initial load
          - check if still logged in
    - Not required to reproduce: set LogSeverity to Error
      - https://github.com/theonlyavengerreal/CefSharp.MinimalExample/commit/3b5030f36589f8be131d51e94570c0bf3ba8af97

- **What is the expected output? What do you see instead?**
    Expected
    - No error in debug.log
    - No slowdown on initial load
    - Login remembered

- **Please provide any additional information below.**
    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
[0309/115526.401:ERROR:cache_util_win.cc(21)] Unable to move the cache: Access is denied. (0x5)
[0309/115526.402:ERROR:cache_util.cc(141)] Unable to move cache folder C:\Users\\%username%\AppData\Local\Zaprefy\CefCache\Cache to C:\Users\\%username%\AppData\Local\Zaprefy\CefCache\old_Cache_000
[0309/115526.402:ERROR:disk_cache.cc(178)] Unable to create cache
    - Log error not present in MinimalExample
[0309/115527.397:ERROR:service_worker_storage.cc(2207)] Failed to delete the database: Database IO error 
    - More relevant information, special steps, or 3rd party controls?
	   No.

- **Does this problem also occur in the `CEF` Sample Application**
	    - Doesn't occur for x86 download http://opensource.spotify.com/cefbuilds/cef_binary_79.1.36%2Bg90301bd%2Bchromium-79.0.3945.130_windows32_client.tar.bz2 and WPF run using: cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu
	   1. debug.log no such error
	   2. no perceivable slow down
	   3. menu "Tests>New Window" the login is remembered
(doesn't seem to have CachePath set, no login even after restarting the window, CefSharp works correctly in this case)

**Comment by theonlyavengerreal** [comment]
Is anything missing or wrong?
What can I provide to make it valid?

**Comment by amaitland** [comment]
Two separate process instances cannot share the same CachePath. Each process must have it's own unique cache. This is how chromium is designed. 

Most web browsers for example use a single application process. When you attempt to launch the web browser a second time it delegates the request to the already existing process. This is how chromium is designed.

**Comment by amaitland** [comment]
What you are seeing is the expected behaviour.

**Comment by amaitland** [comment]
The cefclient sample application uses an in memory cache by default,  you need to specify --cache-path=pathtocache for data to be persisted to disk, you'll get the exact same error.

**Comment by theonlyavengerreal** [comment]
I tested and you are correct.
Thank you!
