### ISSUE TITLE
 WinForms - In windows remote app when doing alt + tab cefsharp windows hangs

### ISSUE THREAD

**Issue by alher93** [cefsharp/CefSharp#3081]
- **What version of the product are you using?**
Nuget 79.1.360

- **environment description where the bug is reproduced**
There is a desktop application made in winforms in which several angular.js applications are embedded, which run on cefsharp and are called through windows from the main application; this application was installed on a **Windows Server 2012 R2 Datacenter** machine recently and it was published as remoteapp to be accessed from various clients through an rdp file. The remoteapp is accessed from a **windows 10 client** and everything seems to be working fine, but; when you have a cefsharp window open and do alt + tab the cefsharp window crashes which causes the entire application to crash.

- **On what operating system?**
Windows Server 2012 R2 DataCenter, x64 
Windows 10, x64

- **Are you using WinForms, WPF or OffScreen?**
Winforms

- **What steps will reproduce the problem?**
1. Execute rdp file from client machine 
2. the application will open
3. open a cefsharp window
4. do alt + tab to the main application
5. do alt + tab to the cefsharp window
6. the cefsharp window crash

**Comment by amaitland** [comment]
> * **Windows Server 2012 R2 Datacenter** machine recently and it was published as remoteapp to be accessed from various clients through an rdp file

Is your application [TSAWARE](https://docs.microsoft.com/en-us/cpp/build/reference/tsaware-create-terminal-server-aware-application?view=vs-2019)?

> * but; when you have a cefsharp window open and do alt + tab the cefsharp window crashes which causes the entire application to crash.

Just saying it crashed is largely meaningless, you need to provide details of the actual exception.

You'll need to get a symbolised stacktrace. See https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#unmanaged-crashes-when-the-process-dies for some information.

> Does this problem also occur in the CEF Sample Application

You have skipped this section, you'll need to find a way to test with the `CEF Sample Application` as detailed in the [Bug Report Template](https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report). Publish `cefclient` without any command line args would be a useful start.

**Comment by amaitland** [comment]
> Is your application [TSAWARE](https://docs.microsoft.com/en-us/cpp/build/reference/tsaware-create-terminal-server-aware-application?view=vs-2019)?

It's hopefully enabled by default, you should double check using `Dumpbin`

**Comment by alher93** [comment]
> Is your application [TSAWARE](https://docs.microsoft.com/en-us/cpp/build/reference/tsaware-create-terminal-server-aware-application?view=vs-2019)?

yes, the application is TSAWARE

> Just saying it crashed is largely meaningless, you need to provide details of the actual exception.

Sorry, I did not explain myself well in the description of the problem; the application is not crashed in fact it hangs because it does not generate any exceptions; no exceptions are logged in the Debug.log file.
Additionally, a dump file of the cefsharp.browsersubprocess process was generated and parsed with windbg; and, before and after the problem occurs, it displays the same information. Dump information is shown below

` 0  Id: 2638.1e28 Suspend: 0 Teb: 00007ff5`ff31d000 Unfrozen
 # Child-SP          RetAddr           Call Site
00 000000e8`5d60dcf8 00007ffb`fb111118 ntdll!NtWaitForSingleObject+0xa
*** WARNING: Unable to verify checksum for libcef.dll
01 000000e8`5d60dd00 00007ffb`b7d4c670 KERNELBASE!WaitForSingleObjectEx+0x94
02 000000e8`5d60dda0 00007ffb`b896689a libcef!cef_string_utf16_to_upper+0x646e3
03 000000e8`5d60de50 00007ffb`b8974e23 libcef!cef_time_delta+0x2f5b2
04 000000e8`5d60ded0 00007ffb`b7d38aee libcef!cef_time_delta+0x3db3b
05 000000e8`5d60df30 00007ffb`b88f354a libcef!cef_string_utf16_to_upper+0x50b61
06 000000e8`5d60dfd0 00007ffb`b7ae6169 libcef!IsSandboxedProcess+0x6be0ed
07 000000e8`5d60e170 00007ffb`b8440fa8 libcef!CrashForExceptionInNonABICompliantCodeRange+0x611ca9
08 000000e8`5d60e210 00007ffb`b84415d0 libcef!IsSandboxedProcess+0x20bb4b
09 000000e8`5d60e4c0 00007ffb`b7ae585a libcef!IsSandboxedProcess+0x20c173
0a 000000e8`5d60e500 00007ffb`b7cbe03a libcef!CrashForExceptionInNonABICompliantCodeRange+0x61139a
0b 000000e8`5d60e590 00007ffb`b5d71137 libcef!CrashForExceptionInNonABICompliantCodeRange+0x7e9b7a
0c 000000e8`5d60e790 00007ffb`e7967581 libcef!cef_execute_process+0x57
0d 000000e8`5d60e800 00007ffb`92259839 CefSharp_BrowserSubprocess_Core+0x27581
0e 000000e8`5d60e850 00007ffb`922595f4 0x00007ffb`92259839
0f 000000e8`5d60e920 00007ffb`922574af 0x00007ffb`922595f4
10 000000e8`5d60e990 00007ffb`92257360 0x00007ffb`922574af
11 000000e8`5d60ea00 00007ffb`f1786cb3 0x00007ffb`92257360
12 000000e8`5d60eab0 00007ffb`f1786bc8 clr!CallDescrWorkerInternal+0x83
13 000000e8`5d60eaf0 00007ffb`f1787430 clr!CallDescrWorkerWithHandler+0x4e
14 000000e8`5d60eb30 00007ffb`f1907059 clr!MethodDescCallSite::CallTargetWorker+0x102
15 000000e8`5d60ec30 00007ffb`f1907a13 clr!RunMain+0x266
16 000000e8`5d60ee10 00007ffb`f19078c7 clr!Assembly::ExecuteMainMethod+0xb7
17 000000e8`5d60f100 00007ffb`f1907213 clr!SystemDomain::ExecuteMainMethod+0x643
18 000000e8`5d60f700 00007ffb`f1907191 clr!ExecuteEXE+0x3f
19 000000e8`5d60f770 00007ffb`f1908604 clr!_CorExeMainInternal+0xb2
1a 000000e8`5d60f800 00007ffb`f22d8c01 clr!CorExeMain+0x14
1b 000000e8`5d60f840 00007ffb`f238ea5b mscoreei!CorExeMain+0x112
1c 000000e8`5d60f8a0 00007ffb`fbd713d2 mscoree!CorExeMain_Exported+0xcb
1d 000000e8`5d60f8d0 00007ffb`fdbb54f4 kernel32!BaseThreadInitThunk+0x22
1e 000000e8`5d60f900 00000000`00000000 ntdll!RtlUserThreadStart+0x34

   1  Id: 2638.1754 Suspend: 0 Teb: 00007ff5`ff31b000 Unfrozen
 # Child-SP          RetAddr           Call Site
00 000000e8`5f5bf9f8 00007ffb`fb1113ed ntdll!NtWaitForMultipleObjects+0xa
01 000000e8`5f5bfa00 00007ffb`f1905f5f KERNELBASE!WaitForMultipleObjectsEx+0xe1
02 000000e8`5f5bfce0 00007ffb`f1905e7b clr!DebuggerRCThread::MainLoop+0xc9
03 000000e8`5f5bfda0 00007ffb`f1905d71 clr!DebuggerRCThread::ThreadProc+0xda
04 000000e8`5f5bfdf0 00007ffb`fbd713d2 clr!DebuggerRCThread::ThreadProcStatic+0x41
05 000000e8`5f5bfe40 00007ffb`fdbb54f4 kernel32!BaseThreadInitThunk+0x22
06 000000e8`5f5bfe70 00000000`00000000 ntdll!RtlUserThreadStart+0x34

   2  Id: 2638.1a9c Suspend: 0 Teb: 00007ff5`ff319000 Unfrozen
 # Child-SP          RetAddr           Call Site
00 000000e8`77e4f8d8 00007ffb`fb1113ed ntdll!NtWaitForMultipleObjects+0xa
01 000000e8`77e4f8e0 00007ffb`f1824447 KERNELBASE!WaitForMultipleObjectsEx+0xe1
02 000000e8`77e4fbc0 00007ffb`f18224f3 clr!FinalizerThread::WaitForFinalizerEvent+0xa7
03 000000e8`77e4fc00 00007ffb`f17882e0 clr!FinalizerThread::FinalizerThreadWorker+0x53
04 000000e8`77e4fc50 00007ffb`f1788253 clr!ManagedThreadBase_DispatchInner+0x40
05 000000e8`77e4fc90 00007ffb`f1788192 clr!ManagedThreadBase_DispatchMiddle+0x6c
06 000000e8`77e4fd90 00007ffb`f18f3736 clr!ManagedThreadBase_DispatchOuter+0x4c
07 000000e8`77e4fe00 00007ffb`f178b665 clr!FinalizerThread::FinalizerThreadStart+0x116
08 000000e8`77e4fea0 00007ffb`fbd713d2 clr!Thread::intermediateThreadProc+0x8b
09 000000e8`77e4ff60 00007ffb`fdbb54f4 kernel32!BaseThreadInitThunk+0x22
0a 000000e8`77e4ff90 00000000`00000000 ntdll!RtlUserThreadStart+0x34

   3  Id: 2638.2020 Suspend: 0 Teb: 00007ff5`ff13e000 Unfrozen
 # Child-SP          RetAddr           Call Site
00 000000e8`7971e988 00007ffb`fb1113ed ntdll!NtWaitForMultipleObjects+0xa
01 000000e8`7971e990 00007ffb`f1967ca7 KERNELBASE!WaitForMultipleObjectsEx+0xe1
02 000000e8`7971ec70 00007ffb`f1967b2c clr!WaitForMultipleObjectsEx_SO_TOLERANT+0x62
03 000000e8`7971ecd0 00007ffb`f19678b9 clr!Thread::DoAppropriateWaitWorker+0x205
04 000000e8`7971edd0 00007ffb`f1968421 clr!Thread::DoAppropriateWait+0x7d
*** WARNING: Unable to verify checksum for mscorlib.ni.dll
05 000000e8`7971ee50 00007ffb`f04f9cec clr!WaitHandleNative::CorWaitOneNative+0x161
06 000000e8`7971f080 00007ffb`f04f9cbf mscorlib_ni+0x5c9cec
*** WARNING: Unable to verify checksum for System.ni.dll
07 000000e8`7971f0b0 00007ffb`ef5808f5 mscorlib_ni+0x5c9cbf
08 000000e8`7971f0f0 00007ffb`92258119 System_ni+0x2c08f5
09 000000e8`7971f150 00007ffb`92257e60 0x00007ffb`92258119
0a 000000e8`7971f190 00007ffb`922579ae 0x00007ffb`92257e60
0b 000000e8`7971f240 00007ffb`f052af47 0x00007ffb`922579ae
0c 000000e8`7971f2d0 00007ffb`f04bdf12 mscorlib_ni+0x5faf47
0d 000000e8`7971f310 00007ffb`f04bdd95 mscorlib_ni+0x58df12
0e 000000e8`7971f3e0 00007ffb`f052b201 mscorlib_ni+0x58dd95
0f 000000e8`7971f410 00007ffb`f052a8e1 mscorlib_ni+0x5fb201
10 000000e8`7971f4c0 00007ffb`f04bdf12 mscorlib_ni+0x5fa8e1
11 000000e8`7971f500 00007ffb`f04bdd95 mscorlib_ni+0x58df12
12 000000e8`7971f5d0 00007ffb`f04bdd65 mscorlib_ni+0x58dd95
13 000000e8`7971f600 00007ffb`f0e65c80 mscorlib_ni+0x58dd65
14 000000e8`7971f650 00007ffb`f1786cb3 mscorlib_ni+0xf35c80
15 000000e8`7971f690 00007ffb`f1786bc8 clr!CallDescrWorkerInternal+0x83
16 000000e8`7971f6d0 00007ffb`f1787430 clr!CallDescrWorkerWithHandler+0x4e
17 000000e8`7971f710 00007ffb`f193e6af clr!MethodDescCallSite::CallTargetWorker+0x102
18 000000e8`7971f810 00007ffb`f17882e0 clr!ThreadNative::KickOffThread_Worker+0xffffffff`fffff01f
19 000000e8`7971fa70 00007ffb`f1788253 clr!ManagedThreadBase_DispatchInner+0x40
1a 000000e8`7971fab0 00007ffb`f1788192 clr!ManagedThreadBase_DispatchMiddle+0x6c
1b 000000e8`7971fbb0 00007ffb`f178836f clr!ManagedThreadBase_DispatchOuter+0x4c
1c 000000e8`7971fc20 00007ffb`f193e599 clr!ManagedThreadBase_FullTransitionWithAD+0x2f
1d 000000e8`7971fc80 00007ffb`f178b665 clr!ThreadNative::KickOffThread+0xe6
1e 000000e8`7971fd60 00007ffb`fbd713d2 clr!Thread::intermediateThreadProc+0x8b
1f 000000e8`7971fea0 00007ffb`fdbb54f4 kernel32!BaseThreadInitThunk+0x22
20 000000e8`7971fed0 00000000`00000000 ntdll!RtlUserThreadStart+0x34

   4  Id: 2638.226c Suspend: 0 Teb: 00007ff5`ff13c000 Unfrozen
 # Child-SP          RetAddr           Call Site
00 000000e8`7b22f738 00007ffb`fb114943 ntdll!NtRemoveIoCompletion+0xa
01 000000e8`7b22f740 00007ffb`b8e996e4 KERNELBASE!GetQueuedCompletionStatus+0x3f
02 000000e8`7b22f7a0 00007ffb`fbd713d2 libcef!GetHandleVerifier+0x51b934
03 000000e8`7b22f8f0 00007ffb`fdbb54f4 kernel32!BaseThreadInitThunk+0x22
04 000000e8`7b22f920 00000000`00000000 ntdll!RtlUserThreadStart+0x34

   5  Id: 2638.1a1c Suspend: 0 Teb: 00007ff5`ff13a000 Unfrozen
 # Child-SP          RetAddr           Call Site
00 000000e8`7b72f358 00007ffb`fb111118 ntdll!NtWaitForSingleObject+0xa
01 000000e8`7b72f360 00007ffb`b7d4c670 KERNELBASE!WaitForSingleObjectEx+0x94
02 000000e8`7b72f400 00007ffb`b896689a libcef!cef_string_utf16_to_upper+0x646e3
03 000000e8`7b72f4b0 00007ffb`b8974e23 libcef!cef_time_delta+0x2f5b2
04 000000e8`7b72f530 00007ffb`b7d38aee libcef!cef_time_delta+0x3db3b
05 000000e8`7b72f590 00007ffb`b97a0e30 libcef!cef_string_utf16_to_upper+0x50b61
06 000000e8`7b72f630 00007ffb`b7d60926 libcef!GetHandleVerifier+0xe23080
07 000000e8`7b72f670 00007ffb`b7d5e28d libcef!cef_string_utf16_to_upper+0x78999
08 000000e8`7b72f6f0 00007ffb`fbd713d2 libcef!cef_string_utf16_to_upper+0x76300
09 000000e8`7b72f770 00007ffb`fdbb54f4 kernel32!BaseThreadInitThunk+0x22
0a 000000e8`7b72f7a0 00000000`00000000 ntdll!RtlUserThreadStart+0x34

   6  Id: 2638.2358 Suspend: 0 Teb: 00007ff5`ff136000 Unfrozen
 # Child-SP          RetAddr           Call Site
00 000000e8`7bf2faf8 00007ffb`fb111118 ntdll!NtWaitForSingleObject+0xa
01 000000e8`7bf2fb00 00007ffb`b7d4c670 KERNELBASE!WaitForSingleObjectEx+0x94
02 000000e8`7bf2fba0 00007ffb`ba25694a libcef!cef_string_utf16_to_upper+0x646e3
03 000000e8`7bf2fc50 00007ffb`ba25734f libcef!GetHandleVerifier+0x18d8b9a
04 000000e8`7bf2fc90 00007ffb`ba256ea0 libcef!GetHandleVerifier+0x18d959f
05 000000e8`7bf2fd90 00007ffb`b7d5e28d libcef!GetHandleVerifier+0x18d90f0
06 000000e8`7bf2fdd0 00007ffb`fbd713d2 libcef!cef_string_utf16_to_upper+0x76300
07 000000e8`7bf2fe50 00007ffb`fdbb54f4 kernel32!BaseThreadInitThunk+0x22
08 000000e8`7bf2fe80 00000000`00000000 ntdll!RtlUserThreadStart+0x34

   7  Id: 2638.2458 Suspend: 0 Teb: 00007ff5`ff134000 Unfrozen
 # Child-SP          RetAddr           Call Site
00 000000e8`7c32f468 00007ffb`fb114943 ntdll!NtRemoveIoCompletion+0xa
01 000000e8`7c32f470 00007ffb`b7d1f66f KERNELBASE!GetQueuedCompletionStatus+0x3f
02 000000e8`7c32f4d0 00007ffb`b7d1f524 libcef!cef_string_utf16_to_upper+0x376e2
03 000000e8`7c32f550 00007ffb`b7d1d9fe libcef!cef_string_utf16_to_upper+0x37597
04 000000e8`7c32f5d0 00007ffb`b8974e23 libcef!cef_string_utf16_to_upper+0x35a71
05 000000e8`7c32f620 00007ffb`b7d38aee libcef!cef_time_delta+0x3db3b
06 000000e8`7c32f680 00007ffb`b7d60926 libcef!cef_string_utf16_to_upper+0x50b61
07 000000e8`7c32f720 00007ffb`b7d5e28d libcef!cef_string_utf16_to_upper+0x78999
08 000000e8`7c32f7a0 00007ffb`fbd713d2 libcef!cef_string_utf16_to_upper+0x76300
09 000000e8`7c32f820 00007ffb`fdbb54f4 kernel32!BaseThreadInitThunk+0x22
0a 000000e8`7c32f850 00000000`00000000 ntdll!RtlUserThreadStart+0x34

   8  Id: 2638.1e5c Suspend: 0 Teb: 00007ff5`ff132000 Unfrozen
 # Child-SP          RetAddr           Call Site
00 000000e8`7c72f818 00007ffb`fdbd9156 ntdll!NtWaitForWorkViaWorkerFactory+0xa
01 000000e8`7c72f820 00007ffb`fbd713d2 ntdll!TppWorkerThread+0x746
02 000000e8`7c72fc00 00007ffb`fdbb54f4 kernel32!BaseThreadInitThunk+0x22
03 000000e8`7c72fc30 00000000`00000000 ntdll!RtlUserThreadStart+0x34

   9  Id: 2638.9ec Suspend: 0 Teb: 00007ff5`ff130000 Unfrozen
 # Child-SP          RetAddr           Call Site
00 000000e8`7cb2f798 00007ffb`fb111118 ntdll!NtWaitForSingleObject+0xa
01 000000e8`7cb2f7a0 00007ffb`b7d4c4d4 KERNELBASE!WaitForSingleObjectEx+0x94
02 000000e8`7cb2f840 00007ffb`b89668df libcef!cef_string_utf16_to_upper+0x64547
03 000000e8`7cb2f8c0 00007ffb`b8974e23 libcef!cef_time_delta+0x2f5f7
04 000000e8`7cb2f940 00007ffb`b7d38aee libcef!cef_time_delta+0x3db3b
05 000000e8`7cb2f9a0 00007ffb`b7d60926 libcef!cef_string_utf16_to_upper+0x50b61
06 000000e8`7cb2fa40 00007ffb`b7d5e28d libcef!cef_string_utf16_to_upper+0x78999
07 000000e8`7cb2fac0 00007ffb`fbd713d2 libcef!cef_string_utf16_to_upper+0x76300
08 000000e8`7cb2fb40 00007ffb`fdbb54f4 kernel32!BaseThreadInitThunk+0x22
09 000000e8`7cb2fb70 00000000`00000000 ntdll!RtlUserThreadStart+0x34

  10  Id: 2638.564 Suspend: 0 Teb: 00007ff5`ff12e000 Unfrozen
 # Child-SP          RetAddr           Call Site
00 000000e8`7d12fae8 00007ffb`fb111118 ntdll!NtWaitForSingleObject+0xa
01 000000e8`7d12faf0 00007ffb`b7d4c4d4 KERNELBASE!WaitForSingleObjectEx+0x94
02 000000e8`7d12fb90 00007ffb`b89668df libcef!cef_string_utf16_to_upper+0x64547
03 000000e8`7d12fc10 00007ffb`b8974e23 libcef!cef_time_delta+0x2f5f7
04 000000e8`7d12fc90 00007ffb`b7d38aee libcef!cef_time_delta+0x3db3b
05 000000e8`7d12fcf0 00007ffb`b79b8172 libcef!cef_string_utf16_to_upper+0x50b61
06 000000e8`7d12fd90 00007ffb`b7d5e28d libcef!CrashForExceptionInNonABICompliantCodeRange+0x4e3cb2
07 000000e8`7d12fe30 00007ffb`fbd713d2 libcef!cef_string_utf16_to_upper+0x76300
08 000000e8`7d12feb0 00007ffb`fdbb54f4 kernel32!BaseThreadInitThunk+0x22
09 000000e8`7d12fee0 00000000`00000000 ntdll!RtlUserThreadStart+0x34

  11  Id: 2638.f5c Suspend: 0 Teb: 00007ff5`ff12c000 Unfrozen
 # Child-SP          RetAddr           Call Site
00 000000e8`7d52f938 00007ffb`fb111118 ntdll!NtWaitForSingleObject+0xa
01 000000e8`7d52f940 00007ffb`b7d4c4d4 KERNELBASE!WaitForSingleObjectEx+0x94
02 000000e8`7d52f9e0 00007ffb`ba25693b libcef!cef_string_utf16_to_upper+0x64547
03 000000e8`7d52fa60 00007ffb`ba257177 libcef!GetHandleVerifier+0x18d8b8b
04 000000e8`7d52faa0 00007ffb`ba257020 libcef!GetHandleVerifier+0x18d93c7
05 000000e8`7d52fba0 00007ffb`b7d5e28d libcef!GetHandleVerifier+0x18d9270
06 000000e8`7d52fbe0 00007ffb`fbd713d2 libcef!cef_string_utf16_to_upper+0x76300
07 000000e8`7d52fc60 00007ffb`fdbb54f4 kernel32!BaseThreadInitThunk+0x22
08 000000e8`7d52fc90 00000000`00000000 ntdll!RtlUserThreadStart+0x34

  12  Id: 2638.279c Suspend: 0 Teb: 00007ff5`ff12a000 Unfrozen
 # Child-SP          RetAddr           Call Site
00 000000e8`7d92fb58 00007ffb`fdc1e6fc ntdll!NtWaitForAlertByThreadId+0xa
01 000000e8`7d92fb60 00007ffb`fb1895d8 ntdll!RtlSleepConditionVariableSRW+0xec
02 000000e8`7d92fbd0 00007ffb`b7d4c254 KERNELBASE!SleepConditionVariableSRW+0x28
03 000000e8`7d92fc10 00007ffb`ba1683b4 libcef!cef_string_utf16_to_upper+0x642c7
04 000000e8`7d92fc70 00007ffb`b7d5e28d libcef!GetHandleVerifier+0x17ea604
05 000000e8`7d92fcc0 00007ffb`fbd713d2 libcef!cef_string_utf16_to_upper+0x76300
06 000000e8`7d92fd40 00007ffb`fdbb54f4 kernel32!BaseThreadInitThunk+0x22
07 000000e8`7d92fd70 00000000`00000000 ntdll!RtlUserThreadStart+0x34

  13  Id: 2638.14f4 Suspend: 0 Teb: 00007ff5`ff128000 Unfrozen
 # Child-SP          RetAddr           Call Site
00 000000e8`7dd2f818 00007ffb`fdc1e6fc ntdll!NtWaitForAlertByThreadId+0xa
01 000000e8`7dd2f820 00007ffb`fb1895d8 ntdll!RtlSleepConditionVariableSRW+0xec
02 000000e8`7dd2f890 00007ffb`b7d4c254 KERNELBASE!SleepConditionVariableSRW+0x28
03 000000e8`7dd2f8d0 00007ffb`ba1683b4 libcef!cef_string_utf16_to_upper+0x642c7
04 000000e8`7dd2f930 00007ffb`b7d5e28d libcef!GetHandleVerifier+0x17ea604
05 000000e8`7dd2f980 00007ffb`fbd713d2 libcef!cef_string_utf16_to_upper+0x76300
06 000000e8`7dd2fa00 00007ffb`fdbb54f4 kernel32!BaseThreadInitThunk+0x22
07 000000e8`7dd2fa30 00000000`00000000 ntdll!RtlUserThreadStart+0x34

  14  Id: 2638.c34 Suspend: 0 Teb: 00007ff5`ff126000 Unfrozen
 # Child-SP          RetAddr           Call Site
00 000000e8`7e12fa58 00007ffb`fdc1e6fc ntdll!NtWaitForAlertByThreadId+0xa
01 000000e8`7e12fa60 00007ffb`fb1895d8 ntdll!RtlSleepConditionVariableSRW+0xec
02 000000e8`7e12fad0 00007ffb`b7d4c254 KERNELBASE!SleepConditionVariableSRW+0x28
03 000000e8`7e12fb10 00007ffb`ba1683b4 libcef!cef_string_utf16_to_upper+0x642c7
04 000000e8`7e12fb70 00007ffb`b7d5e28d libcef!GetHandleVerifier+0x17ea604
05 000000e8`7e12fbc0 00007ffb`fbd713d2 libcef!cef_string_utf16_to_upper+0x76300
06 000000e8`7e12fc40 00007ffb`fdbb54f4 kernel32!BaseThreadInitThunk+0x22
07 000000e8`7e12fc70 00000000`00000000 ntdll!RtlUserThreadStart+0x34

  15  Id: 2638.2044 Suspend: 0 Teb: 00007ff5`ff124000 Unfrozen
 # Child-SP          RetAddr           Call Site
00 000000e8`7e52f898 00007ffb`fb111118 ntdll!NtWaitForSingleObject+0xa
01 000000e8`7e52f8a0 00007ffb`b7d4c670 KERNELBASE!WaitForSingleObjectEx+0x94
02 000000e8`7e52f940 00007ffb`ba25694a libcef!cef_string_utf16_to_upper+0x646e3
03 000000e8`7e52f9f0 00007ffb`ba25734f libcef!GetHandleVerifier+0x18d8b9a
04 000000e8`7e52fa30 00007ffb`ba256fe0 libcef!GetHandleVerifier+0x18d959f
05 000000e8`7e52fb30 00007ffb`b7d5e28d libcef!GetHandleVerifier+0x18d9230
06 000000e8`7e52fb70 00007ffb`fbd713d2 libcef!cef_string_utf16_to_upper+0x76300
07 000000e8`7e52fbf0 00007ffb`fdbb54f4 kernel32!BaseThreadInitThunk+0x22
08 000000e8`7e52fc20 00000000`00000000 ntdll!RtlUserThreadStart+0x34`

> You have skipped this section, you'll need to find a way to test with the CEF Sample Application as detailed in the Bug Report Template. Publish cefclient without any command line args would be a useful start.

I have not yet been able to perform this test because the problem occurs in production and I have not yet been given a test environment where I can perform such tests.

**Comment by amaitland** [comment]
Your title and description says windows crashes and your application crashes, please edit your original issue and provide a clearer description. 

What exactly is your dump of? Your main application? 

The only issue that I remember that sounds remotely similar is #1822
