### ISSUE TITLE
Download progress control

### ISSUE THREAD

**Issue by 2821840032** [cefsharp/CefSharp#3084]
There seems to be no download start and pause feature.
But there is an ID field in downloaditem. Can I control its download and pause?

**Comment by amaitland** [comment]
Please don't use the feature request template for asking questions. 

See http://cefsharp.github.io/api/79.1.x/html/M_CefSharp_IDownloadHandler_OnDownloadUpdated.htm which provides a callback that can be used to pause a download. 

Further questions please use one of the options listed above.

**Comment by 2821840032** [comment]
> 请不要使用功能请求模板来提问。
> 
> 请参阅http://cefsharp.github.io/api/79.1.x/html/M_CefSharp_IDownloadHandler_OnDownloadUpdated.htm，其中提供了可用于暂停下载的回调。
> 
> 如有其他疑问，请使用上面列出的选项之一。

Thank you

**Comment by jianxiaofei** [comment]
can i use javascript code control download progress control???
