### ISSUE TITLE
Flash can not auto play with version 76+ 

### ISSUE THREAD

**Issue by hjj28810** [cefsharp/CefSharp#3088]
### Bug Report
Flash can not auto play with version 76+ 

- **What version of the product are you using?**
79.1.360 from nuget  32bit
   
    
- **On what operating system?**
win 10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    wpf
    
- **What steps will reproduce the problem?**
  when i upgrade version to 79.1.360, flash can not be autoplayed，must be right-click to run

**Comment by amaitland** [comment]
Duplicate of #3012
