### ISSUE TITLE
Unable  to load Live videos

### ISSUE THREAD

**Issue by erfan132** [cefsharp/CefSharp#3092]
hi 
i try to load live video on cef sharp but is not load 
i think have problem with some in htm5
plz take a look
https://gofile.io/?c=7qG610

**Comment by amaitland** [comment]
If your website requires WebRTC you must explicitly enable it see https://github.com/cefsharp/CefSharp.MinimalExample/blob/cefsharp/79/CefSharp.MinimalExample.WinForms/Program.cs#L28

Only free audio and video codecs are supported. 

Please ask any further questions on stackoverflow.
