### ISSUE TITLE
Error BadImageFormatException when compressing libcef.dll using UPX

### ISSUE THREAD

**Issue by adierebel** [cefsharp/CefSharp#3094]
- **What version of the product are you using?**
    Nuget cefsharp/79

- **What architecture x86 or x64?**
    x86 using x86 build profile not Any CPU
    
- **On what operating system?**
    Win7

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WinForms
    
- **What steps will reproduce the problem?**
    Compress libcef.dll using UPX (https://github.com/upx/upx)

- **Please provide any additional information below.**
    ```
    System.BadImageFormatException
    HResult=0x800703E6
    Message=Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. Invalid access to memory location. (Exception from HRESULT: 0x800703E6)
    Source=MyAPP
    ```

**Comment by amaitland** [comment]
Try manually calling LoadLibrary via pinvoke before any attempt is made to access CefSharp.Core. Does you libcef.dll load successfully without any reference to CefSharp? Try with a new console application without any reference to CefSharp. 

What testing have you done? 

You can use https://github.com/cefsharp/CefSharp/blob/cefsharp/79/CefSharp/CefLibraryHandle.cs as a reference to pinvoke. 

The recommendation is to compress CEF as part of your installer or zip up the files and manually extract them on first run.

**Comment by amaitland** [comment]
> - **Does this problem also occur in the `CEF` Sample Application**
    - Download one of the following:
	    - For x86 download http://opensource.spotify.com/cefbuilds/cef_binary_79.1.36%2Bg90301bd%2Bchromium-79.0.3945.130_windows32_client.tar.bz2
	    - For x64 download http://opensource.spotify.com/cefbuilds/cef_binary_79.1.36%2Bg90301bd%2Bchromium-79.0.3945.130_windows64_client.tar.bz2
	- If you are using WPF/OffScreen run cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu
    - If you are using WinForms run cefclient --multi-threaded-message-loop
	- **MAKE SURE TO TEST WITH THE COMMAND LINE ARGS LISTED ABOVE**
    - If you can reproduce the problem with `cefclient` then you'll need to report the bug on https://bitbucket.org/chromiumembedded/cef/overview there is no point opening an issue here. (Make sure you search before opening an issue)

As per the [Bug Report Template](https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report) did you test with the `CEF Sample Application`?

**Comment by adierebel** [comment]
been trying using pinvoke with compressed libcef.dll, but the handle result is still invalid.
I think the problem is from UPX that can't compress libcef.dll correctly.
Thanks

**Comment by amaitland** [comment]
A quick test with `cefclient` and it appears `upx` generates an `invalid` dll for `x86` version of `libcef.dll`. The `x64` version of `libcef.dll` loads as expected.
