### ISSUE TITLE
Windows 10 firewall reports CefSharp.BrowserSubprocess

### ISSUE THREAD

**Issue by LightRay2** [cefsharp/CefSharp#3096]
I have the firewall asking me for permissions when navigating to some url. To give you some clues:
- Permissions are asked, but behind the window the page is rendered correctly (probably some part of CEF works correctly and some part not without firewall permissions)
- I removed version 79 and tried version 69 - everything works fine, no permission request.

**Comment by amaitland** [comment]
Duplicate of #3075
