### ISSUE TITLE
Incorrect list of files to distribute

### ISSUE THREAD

**Issue by jc92250** [cefsharp/CefSharp#3097]
Issue is on this page:
https://github.com/cefsharp/CefSharp/wiki/Output-files-description-table-(Redistribution)

Looks like there are 2 bugs in this "Output files description table (Redistribution)" page:
1) snapshot_blob.bin is reported twice
2) v8_context_snapshot.bin is missing

**Comment by amaitland** [comment]
Thanks for the report. It's really just a single mistake,  the second snapshot_blob.bin should be replaced with v8_context_snapshot.bin

Anyone with a GitHub account can edit the wiki.

**Comment by amaitland** [comment]
Fixed in https://github.com/cefsharp/CefSharp/wiki/Output-files-description-table-(Redistribution)/_compare/9bf6238fbc9bd9643ecbd6a082330dabab484e00...82ae7ad4f19800ca158cfe94173315e4888251e0
