### ISSUE TITLE
WebRTC Breaks Low-Level Keyboard Interception

### ISSUE THREAD

**Issue by dbuechel** [cefsharp/CefSharp#3099]
- **What version of the product are you using?**
Nuget version 79.1.360

- **What architecture x86 or x64?**
x64
    
- **On what operating system?**
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms
    
- **What steps will reproduce the problem?**
1. Fork the CefSharp [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample).
2. Replace the code in file "Program.cs" with the code listed here: [https://gist.github.com/dbuechel/139a93746f3b012bb241ec281a2e23c5](https://gist.github.com/dbuechel/139a93746f3b012bb241ec281a2e23c5)
3. Run the minimal example application.
4. For every keystroke on the keyboard, a message like `KEYBOARD EVENT: 0, 256, 662186224664` should appear in the Visual Studio output window.
5. Navigate to [https://test.webrtc.org](https://test.webrtc.org).
6. As soon as the WebRTC test page loads, the keyboard interception stops working and thus no more events appear in the Visual Studio output window.

- **What is the expected output? What do you see instead?**
I expect the low-level keyboard interception to continue working, even with WebRTC enabled and running. Instead, as soon as WebRTC is started in the browser, the low-level keyboard interception stops working.

- **Please provide any additional information below.**
There are two browser messages logged when loading the WebRTC test page:

`[0416/135021.182:INFO:CONSOLE(1)] "document.registerElement is deprecated and will be removed in M80, around February 2020. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.", source: https://test.webrtc.org/main.js (1)`

`[0416/135022.177:INFO:user_input_monitor_win.cc(170)] RegisterRawInputDevices() failed for RIDEV_REMOVE: Wrong Parameter. (0x57)`

- **Does this problem also occur in the `CEF` Sample Application**
I can't test it with the CEF sample application as I do not have the required C++ skills to implement the same code directly with CEF.

**Comment by amaitland** [comment]
Closing as upstream as CEF requires changes to support the use of a keyboard hook when WebRTC is used.

https://bitbucket.org/chromiumembedded/cef/issues/2609/chomium-windows-when-using-own-low-level
