### ISSUE TITLE
Ensure CefSettings.CachePath and RequestContextSettings.CachePath are absolute

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#3102]
> The cache path must be an absolute path. It was never intended to work with relative paths.

As per https://bitbucket.org/chromiumembedded/cef/issues/2916/not-persisting-in-local-stoage-when-using#comment-56993126 the `CachePath` must be absolute.

- [x] throw Exception if paths are non absolute

Related issue #3074

**Comment by amaitland** [comment]
Another option would be to validate the path provided and throw an exception. This may be the slightly less user friendly option, it would avoid any potential issues where the `Path.GetFullPath` was to resolve incorrectly. 

https://docs.microsoft.com/en-us/dotnet/api/system.io.path.ispathrooted?view=netframework-4.8

**Comment by amaitland** [comment]
Browsersubprocess must also be absolute now

https://bitbucket.org/chromiumembedded/cef/commits/dede95c5866fee73db7fb0e5f2077fb2135db6ac

**Comment by amaitland** [comment]
The exception in https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Cef.h#L204 should be updated to make it clear an absolute path is required also.

**Comment by amaitland** [comment]
Test failing https://mail.google.com/mail/u/0/#inbox/WhctKJVqwxWsFHNFMfdFXqxKNvhWtzKTpWdbfhkprLGPxWRZSjlPhdGGVJcVJDggLnvZzZv

**Comment by amaitland** [comment]
Resolved in https://github.com/cefsharp/CefSharp/commit/98b7abeeea96399d1b3421b668c51623ab9dc252

**Comment by terry-alphasoftware** [comment]
The absolute path check on Windows is incorrect in both Chromium and the matching code in CefSharp. A path does not need to start with a drive letter on Windows. A UNC path is a valid absolute path. See [System.Path.IsPathFullyQualified()](https://learn.microsoft.com/en-us/dotnet/api/system.io.path.ispathfullyqualified?view=net-9.0#system-io-path-ispathfullyqualified(system-string)). 

My use of CefSharp was using the user's profile path as the cache location. System.Environment.GetFolderPath(System.Environment.SpecialFolder.MyDocuments) returns a UNC path on one of our customer's machine, which then triggers the absolute path exception. 

I am able to work around this problem, but am writing this here for future reference.
