### ISSUE TITLE
.NET Core 3.1 Class Library use ChromiumWebBrowser AnyCPU

### ISSUE THREAD

**Issue by Sybren-** [cefsharp/CefSharp#3103]
I'm trying use ChromiumWebBrowser in an NET Core 3.1 Class Library.
I have modified the .csproj according to the netcore .csproj here: https://github.com/cefsharp/CefSharp.MinimalExample/tree/master/CefSharp.MinimalExample.Wpf

But the BrowserSubProcess and other initialization has to be done from a Main method (Program.netcore.cs in the example) 

A a Class Library has no Program.cs, how to start the BrowserSubProcess and do the initialization?
Also, I want to target AnyCPU but therefore is also an App or a Program class required which I don't have in a Class Library. AnyCPU examples: https://github.com/cefsharp/CefSharp/issues/1714

Or do I have to do the initialization in my WinExe project and can the Class Library use the BrowserSubProcess from the WinExe project?

An example of how the two .csrpoj files need to look + initiliazation code would be helpful.

**Comment by amaitland** [comment]
.Net Core support is still a work in progress, in this instance you can ask your questions on #2796

**Comment by Sybren-** [comment]
I asked my question on #2796
