### ISSUE TITLE
Intercept calls GET POST

### ISSUE THREAD

**Issue by totti240282** [cefsharp/CefSharp#3108]
I am using cefsharp to make automatic clicks on an application, I would like to know if it is possible to intercept the calls made by the application and read the results, as if I were reading them from the devtools tab network.

Thanks.

**Comment by amaitland** [comment]
Please ask questions on https://stackoverflow.com/questions/tagged/cefsharp

**Comment by totti240282** [comment]
I apologize I tried all day yesterday without finding a solution that really worked.

**Comment by amaitland** [comment]
You are welcome to ask a question,  please use one of the options listed at https://github.com/cefsharp/CefSharp#contact
