### ISSUE TITLE
File not found with CefSettings.BrowserSubProcessPath 

### ISSUE THREAD

**Issue by Baljitsingh2** [cefsharp/CefSharp#3112]
- What version of the product are you using?

        79.1.360 nuget

    -What architecture x86 or x64?
        x64

    -On what operating system?
        Win 10 build 19041

    -Are you using WinForms, WPF or OffScreen?
        WPF as desktop bridge app.

    -What steps will reproduce the problem?
        create WPF app with the Desktop Bridge.
        Add CefSharp:ChromiumWebBrowser.
        Create a store package and then install it.
        **App crashes on startup with file not found saying  CefSettings.BrowserSubProcessPath not found.**

    -Please provide any additional information below.
       **This issue does not happen on every machine from some reason** 
       It started happening around when I added following code. 
                 var settings = new CefSettings()
                {
                    AcceptLanguageList = LanguageUtil.GetSupportedLanguageCodeForHPID()
                };
                if (!Cef.Initialize(settings, true, (IApp)null))
                {
                    OMENEventSource.Log.Error("CEF Initializeation failed");
                }
        Do I need to sent the BrowserSubProcessPath manually, I double check the exe is in the same location as app?

**Comment by amaitland** [comment]
Set the path manually using an absolute path.

**Comment by Baljitsingh2** [comment]
@amaitland  thanks, that what I was thinking of doing.
