### ISSUE TITLE
CefSharp Winforms has different outcome than CEF and CefSharp WPF starting Teams videocall

### ISSUE THREAD

**Issue by karstennilsen** [cefsharp/CefSharp#3113]
When opening an Teams meeting URL like e.g. https://teams.microsoft.com/l/meetup-join/19%3ameeting_YWQ1ZTlkZWQtNmFjZS00NjNlLWEzZDctMjYwMzJkMjBkZWJj%40thread.v2/0?context=%7b%22Tid%22%3a%226cc7185e-802a-416b-9249-9409da9cd7aa%22%2c%22Oid%22%3a%226b7977a8-9017-443c-a812-b366db0f759f%22%7d using CefSharp Winforms you will get an error 'Sorry, we couldn't connect you.'. When using the Cef Sample Client or CefSharp WPF it works without any problem. Something in CefSharp Winforms is causing different behaviour.

- CefSharp Winforms 79.1.36 (Nuget package manager)
- both x86 and x64 result have the same issue
- Windows 10
- Winforms

1. Start the latest CefSharp Winforms MinimalExample (you can disable enable-media-stream if you want to rule this out, same result)
2. In MinimalExample browse to https://teams.microsoft.com/l/meetup-join/19%3ameeting_YWQ1ZTlkZWQtNmFjZS00NjNlLWEzZDctMjYwMzJkMjBkZWJj%40thread.v2/0?context=%7b%22Tid%22%3a%226cc7185e-802a-416b-9249-9409da9cd7aa%22%2c%22Oid%22%3a%226b7977a8-9017-443c-a812-b366db0f759f%22%7d
3. Click Join on the web instead
4. Click Join now
5. You get a mesage: 'Sorry, we couldn't connect you.'

CefSharp WPF, CefClient (with or without multi-threaded-message-loop off-screen-rendering-enabled enable-gpu) and Google Chrome don't have this problem and get the right result: You are in the queue for the meeting and get a message: 'Someone in the meeting should let you in soon'

I tried finding analyzing debug.log from both WPF and WinForms but I couldn't find anything with my level of Cef knowledge.

**Comment by amaitland** [comment]
Already ask at https://stackoverflow.com/questions/61480885/cefsharp-cant-join-a-teams-video-meeting

**Comment by karstennilsen** [comment]
I indeed already asked it there, but after further research and bit of help I found out Winforms doesn't work in this use case but WPF and CefClient do. Isn't that a bug?

**Comment by amaitland** [comment]
> I indeed already asked it there,

I had already replied there, there is no need for a duplicate. Please show some patience.

> Isn't that a bug?

If it turns out this is a bug then this can be reopened. It's actually unlikely though, more like the configuration is different.

**Comment by amaitland** [comment]
Testing with http://opensource.spotify.com/cefbuilds/cef_binary_79.1.36%2Bg90301bd%2Bchromium-79.0.3945.130_windows64_client.tar.bz2 using the following command line args

```
cefclient.exe --multi-threaded-message-loop --no-sandbox --disable-site-isolation-trials --enable-media-stream
```

I can reproduce the problem you are seeing, so this is not a bug in `CefSharp`.

Adding `disable-gpu-compositing` which is used in the `WPF` example and it says someone will let me into the meeting soon.

```
cefclient.exe --multi-threaded-message-loop --no-sandbox --disable-site-isolation-trials --enable-media-stream --disable-gpu-compositing
```

Testing with `cef_binary_81.2.17+gb382c62+chromium-81.0.4044.113_windows64_client` (not the latest, but a much newer version` and it works without `disable-gpu-compositing`, at least as far as I can test.

**Comment by amaitland** [comment]
In future please use the [Bug Report Template](https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report), this problem easily reproduces with the `CEF Sample Application` using the steps detailed in the `Does this problem also occur in the CEF Sample Application` section.
