### ISSUE TITLE
WPF - Resize Glitches (Image glitches during resize)

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#3114]
- **What version of the product are you using?**
    81.3.100

- **What architecture x86 or x64?**
  Both
    
- **On what operating system?**
  Win 10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
  WPF
    
- **What steps will reproduce the problem?**
  - Open CefSharp.Wpf.Example
  - Change window state to normal    
  - Resize the browser fairly aggressively

- **What is the expected output? What do you see instead?**
  There are some glitches when resizing that aren't present when testing with `cefclient`

- **Please provide any additional information below.**
    DPI scale 150%

- **Does this problem also occur in the `CEF` Sample Application**
   No. The CEF Sample application isn't perfect when resizing, there's plenty of times the outer border is blank waiting for the image to resize correctly. The glitches aren't present to the same degree though.

**Comment by amaitland** [comment]
Use the `disable-gpu-compositing` command line arg should workaround the issue in the short term.

**Comment by amaitland** [comment]
Integrating `CEF` into the `WPF` message loop also appears to eliminate the glitches. Further debugging required.

Set `multiThreadedMessageLoop = false` in the example at https://github.com/cefsharp/CefSharp/blob/cefsharp/83/CefSharp.Wpf.Example/App.xaml.cs#L28

**Comment by rstedman** [comment]
Any update on this bug? I've found that CefSharp 79+ causes significant rendering artifacts when resizing a window. I get the same behavior with or without the --disable-gpu-compositing flag. example:

![resize_artifacts](https://user-images.githubusercontent.com/5440997/96156167-c7a5ea00-0ede-11eb-9c55-5d99767e601a.gif)

I can confirm that integrating cef into the wpf message loop gets rid of the rendering issues, but I am unable to do that in my usage of cefsharp as it causes some other issues.

I am able to update my application to 75.1.143 (from 67.0.0) without experiencing this rendering issue. Any higher version and this issue starts occurring.

I would really like to take the latest cefsharp version, as it has a fix for a css grid layout bug that occurs when viewing a page using cefsharp that doesn't occur in browsers (https://bugs.chromium.org/p/chromium/issues/detail?id=1051039). This resize bug is the only issue currently blocking me from taking latest.

**Comment by amaitland** [comment]
How does the CEF Sample application behave on your computer? See https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-chromium-embedded-frameworkcef

**Comment by rstedman** [comment]
no issue with the cefclient
![cefclient_resize](https://user-images.githubusercontent.com/5440997/96261846-f54a6c00-0f8e-11eb-8b71-8abb329a3ca3.gif)

A coworker has also tested both the cefsharp wpf sample and the cefclient on their PC. They are seeing the same behavior as I am - render glitches in the cefsharp example and no issue with the cefclient.

**Comment by amaitland** [comment]
What command line args did you tested with?

The second animated gif where the scroll bar disappears and a black box occurs is more than likely a problem with the CEF OSR implementation,  we're simplify rendering every frame we're given. Dumping each frame to disk in OnPaint and you should get a better understanding of what the output is.

I don't have any insight into what is causing the initial glitching, the rendering implementation hasn't changed in a long time, something changed in CEF/Chromium. 

Resolving whatever issues you have integrating CEF into your apps existing message is possibly the simplest option. Though if you have time by all means have a go at debugging.

**Comment by amaitland** [comment]
You can view the cefclient source on GitHub. 
https://github.com/chromiumembedded/cef/blob/8a055593d694b386f46530f81f53ed8b7c5ea284/tests/cefclient/browser/osr_renderer.cc#L280

The CefSharp rendering implentations are in https://github.com/cefsharp/CefSharp/tree/master/CefSharp.Wpf/Rendering
InteropBitmapRenderHandler is used when DPI is 100%
WritableBitmapRenderHandler is used when DPI is greater than 100%
DirectWritableBitmapRenderHandler is used when CEF is integrated into existing message loop.
There are some experiments You can try if you have time.

**Comment by rstedman** [comment]
I was using the command line args for the wpf/offscreen settings. I'll give debugging a shot.

**Comment by rstedman** [comment]
I've confirmed that this isn't a rendering issue in cef. I updated InteropBitmapRenderHandler to dump each frame to disk. Looking at the images that it output, they had no visual artifacts even though I was seeing the same tearing in the app while resizing.

I also found that forcing the ChromiumWebBrowser to use either the WriteableBitmapRenderHandler or the CompositionTargetRenderHandler under experiments would render without any visual artifacts when resizing.

Looking at the history of InteropBitmapRenderHandler, I found that this resize issue was introduced in [this commit](https://github.com/cefsharp/CefSharp/commit/b1bd7499e578f2486ad1c49f0b4bdc93c63d790f#diff-10ce38e86ac5782d06a15b191dc6216fd098f3e23fe1fa88b3711761d8944055) - an optimization to only create a new memory mapped file if the current file is smaller than the space needed. I've found that if I change
```csharp
if (viewAccessor == null || viewAccessor.Capacity < numberOfBytes)
{
    ReleaseMemoryMappedView(ref mappedFile, ref viewAccessor);

    mappedFile = MemoryMappedFile.CreateNew(null, numberOfBytes, MemoryMappedFileAccess.ReadWrite);

    viewAccessor = mappedFile.CreateViewAccessor();
}
```
to
```csharp
if (viewAccessor == null || viewAccessor.Capacity < numberOfBytes || currentSize.Width != width)
{
    ReleaseMemoryMappedView(ref mappedFile, ref viewAccessor);

    mappedFile = MemoryMappedFile.CreateNew(null, numberOfBytes, MemoryMappedFileAccess.ReadWrite);

    viewAccessor = mappedFile.CreateViewAccessor();
}
```
it resolves the issue.

before:
![before](https://user-images.githubusercontent.com/5440997/97325440-5ef92e80-1849-11eb-83ec-0bf512d95486.gif)

after:
![after](https://user-images.githubusercontent.com/5440997/97325452-63bde280-1849-11eb-82b3-f64ad6f5565b.gif)


I've spent a fair amount of time trying to figure out why reusing the larger memory mapped file for a smaller image is causing this tearing when the width of the image changes, but I'm at a loss.

**Comment by amaitland** [comment]
Thanks for the feedback,  greatly appreciated. 👍 

I was planning on removing InteropBitmapRenderHandler. Will change the default.

**Comment by amaitland** [comment]
> Looking at the history of InteropBitmapRenderHandler, I found that this resize issue was introduced in [this commit](https://github.com/cefsharp/CefSharp/commit/b1bd7499e578f2486ad1c49f0b4bdc93c63d790f#diff-10ce38e86ac5782d06a15b191dc6216fd098f3e23fe1fa88b3711761d8944055) - an optimization to only create a new memory mapped file if the current file is smaller than the space needed. I've found that if I change

Reverted in commit https://github.com/cefsharp/CefSharp/commit/a8119cc1458c9e497aae7fda0619b8eb8c9227dc a new buffer will be created for every resize (as was previously done)

Subsequently commit https://github.com/cefsharp/CefSharp/commit/59b8e7fbdd24faebacb3f4f48f46acafab18cc24 removes the use of `InteropBitmapRenderHandler ` and defaults to `WritableBitmapRenderHandler` for `MultiThreadedMessageLoop = true (the default)`. At some point I'll add support for notifying an `IRenderHandler` of a `DPI` change, so this was something I had planned.

`InteropBitmapRenderHandler ` still exists and can be specified by the user if required.

> I've spent a fair amount of time trying to figure out why reusing the larger memory mapped file for a smaller image is causing this tearing when the width of the image changes, but I'm at a loss.

Interestingly I did a quick check at `100% DPI` and saw only very very rare glitching with `disable-gpu-compositing` set (default) nothing like the image you have provided, so there's likely some other environmental factors that exacerbate the problem.

When I remove `disable-gpu-compositing` I still see glitching until I set `WritableBitmapRenderHandler` to create a new buffer on each resize (effectively reverting https://github.com/cefsharp/CefSharp/commit/b1bd7499e578f2486ad1c49f0b4bdc93c63d790f).

Doesn't make sense yet, at least it gives some further avenues of investigation. Thanks for your help @rstedman

**Comment by amaitland** [comment]
Copying the data directly into the BackBuffer instead of calling `WritePixels` still has the same glitching.
```c#
// Update whole bitmap
var sourceRect = new Int32Rect(0, 0, width, height);

bitmap.Lock();
NativeMethodWrapper.MemoryCopy(bitmap.BackBuffer, sourceBuffer.DangerousGetHandle(), noOfBytes);
bitmap.AddDirtyRect(sourceRect);
bitmap.Unlock();
```

**Comment by amaitland** [comment]
In version `86` we'll default to WritableBitmapRenderHandler and leave `GPU Compositing` disabled. InteropBitmapRenderHandler will create a new buffer on resize relevant commits https://github.com/cefsharp/CefSharp/commit/c04c20fc441711db5570e41699539cc3dee4c4e2 and https://github.com/cefsharp/CefSharp/commit/da918d6b754a8c80a02d8194718f8ce99675e11c

Commit https://github.com/cefsharp/CefSharp/commit/fb289d49d8f4e0b3f17c757d57eb7c0e79dff1bb switches to using `Marshal.AllocHGlobal` instead of `MemoryMappedFile` which appears to resolve the issue. A sample size of one isn't very conclusive so I've enabled by default and will try to test on a few different machines before release. The user can switch to the original `WritableBitmapRenderHandler` if there are any problems.

**Comment by timaiv** [comment]
@amaitland 
I think its better to create buffer on updates with 1.5..2 scaled size, like in lists.

**Comment by amaitland** [comment]
@timaiv For what reason?

**Comment by timaiv** [comment]
@amaitland To reduce count of allocates with width\height increasing.

**Comment by amaitland** [comment]
If I understand correctly it sounds like you'd be holding reference to memory unnecessarily, perhaps I'm not understanding correctly. You are welcome to submit a PR for review.

The current plan for DPI scaling is to reuse the same buffer regardless of scale. If you need a fine level of control over memory allocations then you can of course implement  IRenderHandler

**Comment by timaiv** [comment]
@amaitland [example in List class](https://referencesource.microsoft.com/#mscorlib/system/collections/generic/list.cs,405)

**Comment by amaitland** [comment]
@timaiv I have no idea how that relates to different DPI scales. Be better if you submit a PR with a working example.

**Comment by timaiv** [comment]
@amaitland Found reason of bug.
I assumed that second CreateOrUpdateBitmap can be raised after first Dispatcher operation is processed.
Now mmf contains new (2nd data), but dispatcher operation uses captured by lambda old parameters (in my case dirty rect).
After i programmatically found this reason (by ids) as i thought i saved image and it was i expected.
![image](https://user-images.githubusercontent.com/36565658/97504310-4e4ad480-197f-11eb-8ae4-aa835b064534.png)

**Comment by amaitland** [comment]
>  Now mmf contains new (2nd data), but dispatcher operation uses captured by lambda old parameters (in my case dirty rect).

Thanks for the feedback,  makes sense. That should be easily fixable. 

> Also, my suggestion about scaled increasing does not apply in any way for "dpi", only reducing of allocates.

@timaiv I'll be honest I find your comments in general very cryptic and lacking in details. I mean no offence by this, I'd just really appreciate it if you'd add more detail. Input is welcomed, it would make my life easier if you'd submit a pull request with your proposed changes, then we have something concrete to discuss.

**Comment by rstedman** [comment]
> Now mmf contains new (2nd data), but dispatcher operation uses captured by lambda old parameters (in my case dirty rect).

This occurred to me as well. However, I tried making the dispatch synchronous (dispatcher.Invoke instead of dispatcher.BeginInvoke) as a quick test, but I still experienced the resize issue.

**Comment by amaitland** [comment]
This should now be resolved in commit https://github.com/cefsharp/CefSharp/commit/839e6ceee4039a779f0a2b1d2b5cc984ba1b7c40

Version 86 branch has only the `WritableBitmapRenderHandler/InteropBitmapRenderHandler` specific changes (commit  https://github.com/cefsharp/CefSharp/commit/a83dbc23a1c45bf8f39d53ae6fa81181ab60ed3b)

The `disable-gpu-compositing` command line arg has now been removed.

`BeginInvoke` calls will now check the size and the call will be ignored if it doesn't match, this should result in slightly improved performance.

If anyone would like to test this out you can download a nightly build from https://www.myget.org/feed/cefsharp/package/nuget/CefSharp.Wpf
