### ISSUE TITLE
Cef 81 not save all cookie data

### ISSUE THREAD

**Issue by bbday** [cefsharp/CefSharp#3120]
I used Cef WPF minimal example with current stable version v79 and work great, i update cef to beta version 81.3.10-CI3509 and not working.
I tested also cefclient v81 (with cache path parameter) and it work, then i think is issue with cefsharp client.

The issue is example loading this web address https://www.easports.com/fifa/ultimate-team/web-app/ on response it must setup 2 cookie on cache, in fact it will setup just one (dont know why look like not rember cookie with parameter Max-Age=7178) then when you reload app and load data from cache path dont rember all cookies.

**Comment by amaitland** [comment]
Please fill out the [Bug Report Template](https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report)

> then i think is issue with cefsharp client.

To be honest that's quite unlikely. Cookies are entirely managed by `CEF/Chromium`. 

> I tested also cefclient v81 (with cache path parameter) and it work,

What version did you test with? What command line args did you use?

**Comment by bbday** [comment]
Cef WPF minimal example, i didnt use any arg just loaded app and use fiddler with stable cefsharp wpf v79 (last) then i switchet to 81.3.10-CI3509 that have this issue.

About cefclient i used  CEF 81.3.1+gb2b49f1+chromium-81.0.4044.113 x64 --proxy-server=myproxy:port --cache-path=myFolder and it work without issue only with cefsharp v81 i have this issue before i dont know why.

**Comment by amaitland** [comment]
> Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)

Did you check the log file to see if any errors are listed?

>If you are using WPF/OffScreen run
 cefclient.exe --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu --disable-gpu-compositing --no-sandbox --disable-site-isolation-trials
> MAKE SURE TO TEST WITH THE COMMAND LINE ARGS LISTED ABOVE

As per the [Bug Report Template](https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report) you need to use the command line args as listed in the template for an accurate comparison with `CefSharp`. Add the cache and proxy command line args as well of course.

**Comment by bbday** [comment]
- On debug.log no info or error 
- I tried with your args and working like expect (it save all cookie then in next session rember them)

**Comment by amaitland** [comment]
If you haven't already please try deleting the cache. Issue https://bitbucket.org/chromiumembedded/cef/issues/2890/all-the-cookies-are-deleted-automatically may require an empty cache to start from.

**Comment by shimengkeji** [comment]
> If you haven't already please try deleting the cache. Issue https://bitbucket.org/chromiumembedded/cef/issues/2890/all-the-cookies-are-deleted-automatically may require an empty cache to start from.

I try it, But it doesn't work. Page didn't work as expected. 79.1.360 does not have this problem

**Comment by amaitland** [comment]
It's **unclear** how to reproduce this problem. The https://www.easports.com/fifa/ultimate-team/web-app/ page is full of `debugger;` statements in it's JavaScript so is unusable for testing purposes. A vague paragraph containing a few lines about the problem is insufficient

What I require is:

- A detailed set of clear instructions of how to reproduce the problem using **DevTools** for debugging
  - Dot point list is preferred
  - Details on expected result and the actual result in terms of cookies 
- A **minimal** example url that can easily be used to reproduce the problem using `DevTools`.
  - Ideally the url has minimal javascript and css to allow for easy analysis
- The https://github.com/cefsharp/CefSharp.MinimalExample/tree/cefsharp/81 branch has been updated with the `81.3.20-pre` release and should be used for testing.

If someone can provide sufficient details then I will have look.

**Comment by shimengkeji** [comment]
> It's **unclear** how to reproduce this problem. The https://www.easports.com/fifa/ultimate-team/web-app/ page is full of `debugger;` statements in it's JavaScript so is unusable for testing purposes. A vague paragraph containing a few lines about the problem is insufficient
> 
> What I require is:
> 
> * A detailed set of clear instructions of how to reproduce the problem using **DevTools** for debugging
>   
>   * Dot point list is preferred
>   * Details on expected result and the actual result in terms of cookies
> * A **minimal** example url that can easily be used to reproduce the problem using `DevTools`.
>   
>   * Ideally the url has minimal javascript and css to allow for easy analysis
> * The https://github.com/cefsharp/CefSharp.MinimalExample/tree/cefsharp/81 branch has been updated with the `81.3.20-pre` release and should be used for testing.
> 
> If someone can provide sufficient details then I will have look.

I try 81.3.20-pre on https://www.w3school.com.cn/tiy/t.asp?f=js_cookie_username,Relaunch soft username don't save.And i guess the cookies set by JavaScript can't be saved. You can repeat this question through the test website I provided. Thank you

**Comment by shimengkeji** [comment]
> It's **unclear** how to reproduce this problem. The https://www.easports.com/fifa/ultimate-team/web-app/ page is full of `debugger;` statements in it's JavaScript so is unusable for testing purposes. A vague paragraph containing a few lines about the problem is insufficient
> 
> What I require is:
> 
> * A detailed set of clear instructions of how to reproduce the problem using **DevTools** for debugging
>   
>   * Dot point list is preferred
>   * Details on expected result and the actual result in terms of cookies
> * A **minimal** example url that can easily be used to reproduce the problem using `DevTools`.
>   
>   * Ideally the url has minimal javascript and css to allow for easy analysis
> * The https://github.com/cefsharp/CefSharp.MinimalExample/tree/cefsharp/81 branch has been updated with the `81.3.20-pre` release and should be used for testing.
> 
> If someone can provide sufficient details then I will have look.

I try 81.3.20-pre on https://www.w3school.com.cn/tiy/t.asp?f=js_cookie_username
I relaunch soft but username don't save.
And i guess the cookies set by JavaScript can't be saved. 
You can repeat this question through the test website I provided. 
Thank you

**Comment by amaitland** [comment]
@shimengkeji Have you confirmed that cookies are persisted using Chrome for the url you linked? Session cookies aren't persisted by default in any browser that I'm aware of.

Cookies set by JavaScript can be saved.

**Comment by shimengkeji** [comment]
> @shimengkeji Have you confirmed that cookies are persisted using Chrome for the url you linked? Session cookies aren't persisted by default in any browser that I'm aware of.
> 
> Cookies set by JavaScript can be saved.

Okay,I give an example of a mistake. It's true that it's on 79.1.360, and it won't be saved

**Comment by shimengkeji** [comment]
> @shimengkeji Have you confirmed that cookies are persisted using Chrome for the url you linked? Session cookies aren't persisted by default in any browser that I'm aware of.
> 
> Cookies set by JavaScript can be saved.

Let me give you an example of my decision to compare the next two cefsharp versions of cookies. Let's see which cookies have not been saved

**Comment by amaitland** [comment]
> Let me give you an example of my decision to compare the next two cefsharp versions of cookies. Let's see which cookies have not been saved

@shimengkeji I have absolutely no idea what you mean by this. What does `the next two cefsharp versions of cookies` mean exactly?

**Comment by shimengkeji** [comment]
> > Let me give you an example of my decision to compare the next two cefsharp versions of cookies. Let's see which cookies have not been saved
> 
> @shimengkeji I have absolutely no idea what you mean by this. What does `the next two cefsharp versions of cookies` mean exactly?

I compared the 79 and 81 versions of cefsharp and opened their devtools. The cefsharp 79 version and cef_binary_81.3.10 + gb223419 + chromium-81.0.4044.138_windows64_client.tar.bz2 show the same number of cookies as cefclient, but cefsharp version 81 cookies are missing some cookies. I don't know if it will help you

**Comment by amaitland** [comment]
> I try 81.3.20-pre on https://www.w3school.com.cn/tiy/t.asp?f=js_cookie_username

This url has text in what i presume is Chinese. I only speak English. I have no idea what the dialog is asking for.

What I've asked for is a **dot point** list of **steps** used to reproduce the problem. Please provide clear and concise steps.

An example of the sort of detail that is **required**:

Using https://github.com/cefsharp/CefSharp.MinimalExample/tree/cefsharp/81 for testing.

- Launch `CefSharp.MinimalExample.WinForms` (using `x64` build)
- Navigate to http://cefsharp.github.io/demo/cookiereadwrite.html
- Click the `Set` link that appears on each row (4 links to be clicked).
- Click `Update` and confirm the cookie data is displayed.
- Open `DevTools` (File -> Show DevTools)
- Select the `Application` tab.
- On the left hand side select Storage -> Cookies
- Expand the cookies option and select http://cefsharp.github.io
- Confirm the four cookies are present.
- Close DevTools
- Exit the application (File -> Exit)
- Launch `CefSharp.MinimalExample.WinForms` (using `x64` build)
- Navigate to http://cefsharp.github.io/demo/cookiereadwrite.html
- Open `DevTools` (File -> Show DevTools)
- Select the `Application` tab.
- On the left hand side select Storage -> Cookies
- Expand the cookies option and select http://cefsharp.github.io
- Confirm the four cookies are present.

Cookies are persisted as expected. Subsequently launching CefSharp.MinimalExample.Wpf and navigating to  http://cefsharp.github.io/demo/cookiereadwrite.html shows
the cookie output

Please **make sure** to use https://github.com/cefsharp/CefSharp.MinimalExample/tree/cefsharp/81 for testing so I have a baseline for comparison.

> I don't know if it will help you

Unfortunately no it doesn't help me at all. Saying you have confirmed the output doesn't provide me with a means to reproduce the testing that you have done.

**Comment by amaitland** [comment]
Can someone please load `chrome://version` in both `cefclient` and the `CefSharp.MinimalExample` and **copy and paste** the content here so I can compare the details, cachepath, commandline args etc.

Thanks.

**Comment by shimengkeji** [comment]
> Can someone please load `chrome://version` in both `cefclient` and the `CefSharp.MinimalExample` and **copy and paste** the content here so I can compare the details, cachepath, commandline args etc.
> 
> Thanks.

This is trickier than I thought, because I do n’t understand how to set PersistSessionCookies in CefClient

**Comment by shimengkeji** [comment]
Use CefSharp.MinimalExample.WinForms,I got the results I want! I will compare the settings to see what went wrong

**Comment by shimengkeji** [comment]
Hello，CefSettings class set CachePath have a  LocalPrefs.json file.
But RequestContextSettings set CachePath not.
So some cookies don't resume.
Hope this helps you!

**Comment by shimengkeji** [comment]
Hello, CefSettings class use CachePath have a LocalPrefs.json file.
But RequestContextSettings use CachePath not.
So some cookies don't resume.
Hope this helps you!

**Comment by amaitland** [comment]
@shimengkeji Please read https://bitbucket.org/chromiumembedded/cef/issues/2890/all-the-cookies-are-deleted-automatically

**Comment by shimengkeji** [comment]
> @shimengkeji Please read https://bitbucket.org/chromiumembedded/cef/issues/2890/all-the-cookies-are-deleted-automatically

I have seen this page many times, but I do n’t understand what you mean.  Do you mean that this is an upstream problem that cannot be solved for the time being?  There are still answers to fix problems?thanks

**Comment by shimengkeji** [comment]
I submitted my suggestion to https://bitbucket.org/chromiumembedded, Thank you for your help

**Comment by amaitland** [comment]
> If non-empty this must be either equal to or a child directory of CefSettings.RootCachePath.

@shimengkeji  As per http://cefsharp.github.io/api/79.1.x/html/P_CefSharp_RequestContextSettings_CachePath.htm
This has been the documented behaviour for quite some time. It may have worked previously where cache paths were in different folders. You **must** comply with this requirement now. Cookies won't work otherwise.

**Comment by shimengkeji** [comment]
> > If non-empty this must be either equal to or a child directory of CefSettings.RootCachePath.
> 
> @shimengkeji As per http://cefsharp.github.io/api/79.1.x/html/P_CefSharp_RequestContextSettings_CachePath.htm
> This has been the documented behaviour for quite some time. It may have worked previously where cache paths were in different folders. You **must** comply with this requirement now. Cookies won't work otherwise.

Thanks, I will give it a try
