### ISSUE TITLE
Feature Request - SSL

### ISSUE THREAD

**Issue by mcneb10** [cefsharp/CefSharp#3121]
Please ask your questions on https://stackoverflow.com/questions/tagged/cefsharp

---

`CefSharp` is a wrapper around the [Chromium Embedded Framework](https://bitbucket.org/chromiumembedded/cef/overview) in a lot of cases a feature must be added to `CEF` first before it can be used in `CefSharp`. `CEF` has it's own `Feature Request Forum` at https://magpcss.org/ceforum/viewforum.php?f=7

--- 

**Describe the solution you'd like**
SSL Support if it doesnt have it

**Describe alternatives you've considered**
None

**Additional context**
Some websites such as google will not allow you to sign in
https://i.imgur.com/jiDajtB.png
**Checklist:**
- [ ] I have reviewed the [CEF API](https://magpcss.org/ceforum/apidocs3/index-all.html) and have confirmed the feature I'm requesting is possible.
- [ ] The Feature I'm requesting is an improvement to Async Javascript Binding (No new feature are being added to the Sync Javascript binding)
- [ ] An open `PR` exists on the [CEF Pull Requests](https://bitbucket.org/chromiumembedded/cef/pull-requests/) and I'd like to propose this feature is added to `CefSharp` when/if it's merged.

**Comment by amaitland** [comment]
SSL is already supported,  the message you are seeing is entirely unrelated. 

Google is no longer allowing logins from embedded browsers as detailed at https://security.googleblog.com/2019/04/better-protection-against-man-in-middle.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed:+GoogleOnlineSecurityBlog+(Google+Online+Security+Blog)&m=1

Further discussion at https://magpcss.org/ceforum/viewtopic.php?f=10&t=16764

**Comment by amaitland** [comment]
Additionally 
- https://magpcss.org/ceforum/viewtopic.php?f=10&t=16717
- https://magpcss.org/ceforum/viewtopic.php?f=10&t=17457

Please participate in the conversation on https://magpcss.org/ceforum/index.php rather than ask questions here.
