### ISSUE TITLE
RequestHandler can't catch all the incoming request

### ISSUE THREAD

**Issue by peguine** [cefsharp/CefSharp#3122]
- **What version of the product are you using?**
  both 79.1.360 and 75.1.143

- **What architecture x86 or x64?**
    x86
    
- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WinForms
    
- **What steps will reproduce the problem?**
 The browser accessed Twitter and automatically scrolled to the bottom to load new posts. There should be many requests, but the Function GetResourceRequestHandler didn't capture any requests, and the function wasn't called at all. Using the same class to capture Pinterest, requests can be captured, including XHR. 
The link to visit Twitter is https://twitter.com/HanamuraAsuka You can see many XHR requests in chrome's develop tool, such as https://api.twitter.com/2/timeline/media/

```
chrome.RequestHandler = New TwitterRequestHandler
```
```
Public Class TwitterRequestHandler

    Inherits RequestHandler

    Protected Overrides Function GetResourceRequestHandler(chromiumWebBrowser As IWebBrowser, browser As IBrowser, frame As IFrame, request As IRequest, isNavigation As Boolean, isDownload As Boolean, requestInitiator As String, ByRef disableDefaultHandling As Boolean) As IResourceRequestHandler

        If request.Url.Contains("/timeline/media/") Or request.Url.Contains("/timeline/profile/") Then
            Return New TwitterResourceRequestHandler
        End If
        Return Nothing
    End Function
End Class
```
after add code below, and in TwitterRequestContextHandler， Overrides Function GetResourceRequestHandler, the TwitterRequestHandler can capture all the requests.
```
chrome.RequestContext = new RequestContext(new TwitterRequestContextHandler)
```

- **What is the expected output? What do you see instead?**
RequestHandler.GetResourceRequestHandler should capture requests. but instead not. and it has some confusing relationship with RequestContextHandler.

**Comment by amaitland** [comment]
`CefSharp` is just one of many wrappers around the [Chromium Embedded Framework (CEF)](https://bitbucket.org/chromiumembedded/cef/)

The `CEF` project has it's own [Issue Tracker](https://bitbucket.org/chromiumembedded/cef/issues). It is recommended you ask on the [CEF Forum](https://magpcss.org/ceforum/index.php) before opening an issue.

Closing this as `upstream` and as changes/fixes need to be made in `CEF`.
