### ISSUE TITLE
Unintentional breaking changes when upgrading from 73.1.* to 79.1.*

### ISSUE THREAD

**Issue by florin-szilagyi** [cefsharp/CefSharp#3123]
### Bug Report
Delete this line and everything above, and then fill in the details below.

- **What version of the product are you using?**
    - What version are you using? Nuget? CI Nuget? build from a branch? If so please link to the relevant commit.
	- Version 79.1.36 from nuget.org

- **What architecture x86 or x64?**
   x86
    
- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WPF
    
- **What steps will reproduce the problem?**
   - upgrade from older version (like 73.1.130)
   - Call CefSharpSettings.CefCommandLineArgs.Add(" .. ")

- **What is the expected output? What do you see instead?**

  - Code with method call should work after upgrading, but instead it breaks: 
```
System.MissingMethodException: Method not found: 'System.Collections.Generic.IDictionary<System.String, System.String> CefSharp.AbstractCefSettings.get_CefCommandLineArgs()
```
- **Please provide any additional information below.**
Upgrade of property `CefSettings.CefCommandLineArgs` caused breaking changes
I suspect it's because the type for `CefCommandLineArgs` was changed from `IDictionary<string, string>` to `CommandLineArgDictionary` that inherits `Dictionary<string,string>`

**Comment by amaitland** [comment]
What is an actual example? It's not clear to me what your problem is. Please provide more information

**Comment by amaitland** [comment]
> * I suspect it's because the type for `CefCommandLineArgs` was changed from `IDictionary<string, string>` to `CommandLineArgDictionary` that inherits `Dictionary<string,string>`

For background this is a very deliberate change to resolve #2858
