### ISSUE TITLE
Remove DefaultRequestHandler

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#3124]
The `DefaultRequestHandler` class has been obsolete for a while and is replaced with [ResourceHandler](http://cefsharp.github.io/api/84.4.x/html/T_CefSharp_ResourceHandler.htm)

The primary difference is the methods are `protected` instead of `public`.

Example of using `ResourceHandler` is 

```c#
public class ExampleRequestHandler : RequestHandler
{
	protected override bool OnBeforeBrowse(IWebBrowser chromiumWebBrowser, IBrowser browser, IFrame frame, IRequest request, bool userGesture, bool isRedirect)
	{
		return false;
	}
}
```

Changing the base class and the methods from `public` to `protected` should be sufficient.

**Comment by Antonz0** [comment]
You probably wanted to mention [RequestHandler](http://cefsharp.github.io/api/84.4.x/html/T_CefSharp_Handler_RequestHandler.htm) class link.
