### ISSUE TITLE
System.Exception after executing javascript and closing

### ISSUE THREAD

**Issue by c2msis** [cefsharp/CefSharp#3127]
In the newest version, when i execute javascript:

```
ChromiumWebBrowser chrome;
chrome.ExecuteScriptAsync(@"window.location.href = 'https://google.pt'");

```
and close the cefsharp i get the following error:

> 
> System.Exception
>   HResult=0x80131500
>   Message=Unable to execute javascript at this time, scripts can only be executed within a V8Context. Use the IWebBrowser.CanExecuteJavascriptInMainFrame property to guard against this exception. See https://github.com/cefsharp/CefSharp/wiki/General-Usage#when-can-i-start-executing-javascript for more details on when you can execute javascript. For frames that do not contain Javascript then no V8Context will be created. Executing a script once the frame has loaded it's possible to create a V8Context. You can use browser.GetMainFrame().ExecuteJavaScriptAsync(script) or browser.GetMainFrame().EvaluateScriptAsync to bypass these checks (advanced users only).
>   Source=CefSharp
>   StackTrace:
>    at CefSharp.WebBrowserExtensions.ExecuteScriptAsync(IWebBrowser browser, String script)
>    at CefSharp.WebBrowserExtensions.<>c__DisplayClass17_1.<ExecuteScriptAsyncWhenPageLoaded>b__0(Object sender, LoadingStateChangedEventArgs args)
>    at CefSharp.WinForms.ChromiumWebBrowser.CefSharp.Internals.IWebBrowserInternal.SetLoadingStateChange(LoadingStateChangedEventArgs args)
>    at CefSharp.Internals.ClientAdapter.OnLoadingStateChange(ClientAdapter* , scoped_refptr<CefBrowser>* browser, Boolean isLoading, Boolean canGoBack, Boolean canGoForward)
>

**Comment by amaitland** [comment]
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Edit your original issue and post a comment when your done, thanks 👍 

Also please fork the https://github.com/cefsharp/CefSharp.MinimalExample project and provide an example that reproduces your problem.

**Comment by amaitland** [comment]
You can skip the does the problem reproduce with the CEF Sample application section.
