### ISSUE TITLE
BrowserSubprocess Crash After a long time running

### ISSUE THREAD

**Issue by junzai1225** [cefsharp/CefSharp#3128]
Recently, I use cefsharp in my c# winform application, the cefsharp version is 71.0.2.0-32bit, My operation system is window7-64bit, my .net framework is 4.5.2, my IDE is vs2017-64bit.

In my winform application, the code is:
##############################
var cefSettings = new CefSettings();
cefSettings.LogSeverity = LogSeverity.Default;
Cef.Initialize(cefSettings, performDependencyCheck: true, browserProcessHandler: null);

string serverUrl = "http://localhost:8080/access/desktop.html#/";
ChromiumWebBrowser cwb = new ChromiumWebBrowser(serverUrl);
this.pnlMain.Controls.Add(cwb);
cwb.Dock = DockStyle.Fill;
##############################

The serverUrl is a  web application, provider the result for ChromiumWebBrowser.

When running a long time (about 2 days), the cefsharp will crash, the ChromiumWebBrowser will be a whole whitepage of nothing. At this time, I have a button in the main form, this button will fire 
 cwb.Reload() event, after this event, the page will ok, but after 2 days will repeat the result, and so on.

When cefsharp crash, I got the windows event log, it like this:
##############################
application: CefSharp.BrowserSubprocess.exe
Framework version: v4.0.30319
note: because unhandled exception, the process termined.
exception info: System.Runtime.InteropServices.SEHException
stack:
   in <Module>.CefExecuteProcess(CefMainArgs*, scoped_refptr<CefApp>*, Void*)
   in  CefSharp.BrowserSubprocess.SubProcess.Run()
   in CefSharp.BrowserSubprocess.Program.Main(System.String[])
##############################

My winfrom application can't catch these exceptions. So, how can I catch these exception, If I can catch these exceptions, I can handle them. Or have other solution for this problem?

Thanks a lot!

**Comment by amaitland** [comment]
Try upgrading to a supported version see https://github.com/cefsharp/CefSharp#release-branches

It's not possible to catch these exceptions as it's a separate process,  we could add an option to suppress the exception,  you can open a feature request for that.

**Comment by amaitland** [comment]
> we could add an option to suppress the exception,

I've created #3130 to track adding this feature.
