### ISSUE TITLE
DefaultBinder InvalidOperationException when binding [1,2,3,1.23] to double[]

### ISSUE THREAD

**Issue by zhou881117** [cefsharp/CefSharp#3129]
error: Uncaught (in promise) System.InvalidOperationException: Could not execute method
System.Collections.Generic.List`1[System.Object], True, 0, 9, 15, 20, -30, 10, 25000, 1)  ---> System.ArgumentException: 值“10”不是“System.Double”类型，不能在此泛型集合中使用。

the DefaultBinder should  improve:
this function: protected virtual object BindCollection(Type targetType, Type objType, object obj)
line:126
change to:
 if (valueType != genericType)
                        {
                            val = TypeHepler.ChangeType(val, genericType);
                        }
                        model.Add(val);

public static object ChangeType(object value, Type type)
        {
            if (value == null && type.IsGenericType) return Activator.CreateInstance(type);
            if (value == null) return null;
            if (type == value.GetType()) return value;
            if (type.IsEnum)
            {
                if (value is string)
                    return Enum.Parse(type, value as string);
                else
                    return Enum.ToObject(type, value);
            }
            if (!type.IsInterface && type.IsGenericType)
            {
                Type innerType = type.GetGenericArguments()[0];
                object innerValue = ChangeType(value, innerType);
                return Activator.CreateInstance(type, new object[] { innerValue });
            }
            if (value is string && type == typeof(Guid)) return new Guid(value as string);
            if (value is string && type == typeof(Version)) return new Version(value as string);
            if (!(value is IConvertible)) return value;
            return Convert.ChangeType(value, type);
        }

**Comment by amaitland** [comment]
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

If you have code improvements then submit a `PR`.

**Comment by amaitland** [comment]
The `DefaultBinder` UnitTests are in https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Test/Framework/BinderFacts.cs please include a test case.

**Comment by amaitland** [comment]
The title needs improving as it doesn't describe the exception you are seeing.

**Comment by zhou881117** [comment]
- **version 79.1.360 by nuget**   .

- **architecture x86 **
    
- **Win10**

- **`WinForms`**
  
- **step**
   js:  bound.Calculate(info);
        info is a js array,example [1,2,3,1.23]
  c#: public void Calculate(double[] info)

- **error**
      error: Uncaught (in promise) System.InvalidOperationException: Could not execute method
System.Collections.Generic.List`1[System.Object], True, 0, 9, 15, 20, -30, 10, 25000, 1) ---> System.ArgumentException: 值“10”不是“System.Double”类型，不能在此泛型集合中使用。

- **c# UnitTests **
      var binder = new DefaultBinder();
       var obj = new List<object> { 10, 20, 1.23 };
       var result = binder.Bind(obj, typeof(double[]));

- **try solve**
https://github.com/cefsharp/CefSharp/blob/798b2bb62e4c2f446acf294c3d66910197fa61e4/CefSharp/ModelBinding/DefaultBinder.cs
DefaultBinder.cs
this function: protected virtual object BindCollection(Type targetType, Type objType, object obj)
line:126
edit to:
if (valueType != genericType)
{
val = TypeHepler.ChangeType(val, genericType);
}
model.Add(val);

public static object ChangeType(object value, Type type)
{
if (value == null && type.IsGenericType) return Activator.CreateInstance(type);
if (value == null) return null;
if (type == value.GetType()) return value;
if (type.IsEnum)
{
if (value is string)
return Enum.Parse(type, value as string);
else
return Enum.ToObject(type, value);
}
if (!type.IsInterface && type.IsGenericType)
{
Type innerType = type.GetGenericArguments()[0];
object innerValue = ChangeType(value, innerType);
return Activator.CreateInstance(type, new object[] { innerValue });
}
if (value is string && type == typeof(Guid)) return new Guid(value as string);
if (value is string && type == typeof(Version)) return new Version(value as string);
if (!(value is IConvertible)) return value;
return Convert.ChangeType(value, type);
}

**Comment by amaitland** [comment]
> * **c# UnitTests **

Thanks, your code doesn't actually compile, I get the idea though.

> * this function: protected virtual object BindCollection(Type targetType, Type objType, object obj)
>   line:126

Code changes are only accepted in the form of a `Pull Request`.

As for your proposed solution, the `Bind` method already perform type conversion, so we just need to call `Bind` for all array elements. It's intended to be used recursively. See https://github.com/cefsharp/CefSharp/commit/ef590444b4b4ae465c8b8189ec9ef8c87dfcdd66 for details on the changes I made. Additional Unit Tests were added.

> if (value is string && type == typeof(Guid)) return new Guid(value as string);
> if (value is string && type == typeof(Version)) return new Version(value as string);

`Guid` has a `GuidConverter` so I'm surprised that's not converted. Looks like we need to change from calling `TypeDescriptor.GetConverter(objType)` to `TypeDescriptor.GetConverter(targetType)` and calling `CanConvertFrom/ConvertFrom` to support this.

https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.guidconverter?view=netframework-4.5.2

Please open a new `Feature Request` to track adding support for additional system type conversion.

**Comment by amaitland** [comment]
I've created #3137 to track improving the `DefaultBinder`.
