### ISSUE TITLE
Feature Request - Add option to suppress BrowserSubprocess exceptions

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#3130]
There are some cases where `Chromium` doesn't handle it's exceptions and the `BrowserSubprocess` will crash, add an option to suppress these exceptions.

- [ ] Add `CefSharpSettings.SuppressBrowserSubprocessExceptions`
- [ ] Send command line arg on subprocess creation
- [ ] Add try catch block, throw exception i

This will be an opt in feature. Adding a `try catch` doesn't nessicary mean we'll catch every exception, it should work for most. (We won't be able to catch exceptions from worker threads, e.g. those used by `WebWorker`, and potentially any others that are created by `CEF/Chromium`).

**Comment by michaelkhalsa** [comment]
This would be a sweet addition. I like the CefSharpSettings option to suppress browser subprocess exceptions.
Another possibility is an option to marshal it out of the sub process and throw a new exception of a type just for this that can be caught and handled.

That allows appropriate action to be taken, For example, if a browser instance is being used for say a help topic, html preview, etc, these are non-critical. While if in the same app, there is also an instance used to host say a payment form to receive a card token, then intelligent action needs to be taken to recover.

In any case, a long running app, going through several sleep cycles, needs to be guarded against mysterious vanishing moments or freezes from a sub process throwing an exception. (please excuse if there are things i am missing or not understanding).

Thanks!

**Comment by amaitland** [comment]
Crash reporting should catch all CEF/Chromium exceptions, this should be sufficient for most cases.

- https://bitbucket.org/chromiumembedded/cef/wiki/CrashReporting.md
- Example config at https://github.com/cefsharp/CefSharp.MinimalExample/search?l=INI&q=crash

I will check to see if managed exceptions are caught, hopefully they are.

Alternatively setting https://docs.microsoft.com/en-us/windows/win32/api/errhandlingapi/nf-errhandlingapi-seterrormode in the application process should hopefully be inherited by the sub processes depending on how chromium is creating them.

If SetErrorMode works as expected then it's unlikely I'll add any additional error handler, just better documentation. 

> Another possibility is an option to marshal it out of the sub process and throw a new exception of a type just for this that can be caught and handled.

@michaelkhalsa Do you have a reference on how to implement this?

> then intelligent action needs to be taken to recover

CEF currently provides http://cefsharp.github.io/api/81.3.x/html/M_CefSharp_IRequestHandler_OnRenderProcessTerminated.htm

Are you experiencing cases where this isn't being called for a crash?

**Comment by amaitland** [comment]
Revisiting this and I think that enabling `Crash Reporting` and having `Chromium` generate the crash dumps is actually the best option here.

There's also the option of `Self Hosting` the `BrowserSubProcess` (using your main application executable instead of `CefSharp.BrowserSubprocess.exe`), you could add a `try catch` or call `SetErrorMode` on a per process basis. Starting with version `87.1.130-pre` this is actually pretty simple.

The `WinForms Example` demos self hosting (disabled by default, change selfHostSubProcess if you wish to test).
https://github.com/cefsharp/CefSharp/blob/01d775a46d2e3fb4644ce43e5c1e122606c780d5/CefSharp.WinForms.Example/Program.cs#L26


Closing this for now, if anything experiencing an unhandled crash dialog with `Crash Reporting` enabled then please comment and we can re-evaluate.
