### ISSUE TITLE
Feature Request - Resource Network Timing

### ISSUE THREAD

**Issue by sinanbuyukbayrak** [cefsharp/CefSharp#3133]
I think it would be nice feature if there was a method where we can see the timing values (like DNS Lookup,  SSL, Request Waiting Time etc.) of the resources.

There is a tab related to resource timing in Chrome DevTools. (Network -> Select resource -> Timing Tab)

Example Request;

![image](https://user-images.githubusercontent.com/12663405/82254422-7a3b4600-995b-11ea-9a5a-717df515b5bc.png)

**Comment by amaitland** [comment]
Is this tab not present in the current Devtools? You can open DevTools programatically see https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#javascript-debugging

**Comment by amaitland** [comment]
You skipped over the feature request template, please read https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/feature_request.md

We cannot implement this in CefSharp, it needs to be implemented in the Chromium embedded framework (If it's not already).

**Comment by sinanbuyukbayrak** [comment]
As you said, as far as I know there is no such a feature/pr in cef.
I would like to ask a question based on your last reply, independent of the title.

I'm trying to use this in CefSharp.OffScreen. When I use ShowDevTools(), it was opening new gui form. But I want to run command on devTools in the background. Is there a method to run devtools in the background?

**Comment by amaitland** [comment]
Closing as upstream,  you'll need to make your request at https://magpcss.org/ceforum/viewforum.php?f=7

Post a link back here for reference. 

You can enable remote debugging and use puppeteer, selenium, send commands directly etc.

Further questions please use one of the options listed at https://github.com/cefsharp/CefSharp#contact

**Comment by amaitland** [comment]
Testing with [v81.3.20-pre](https://github.com/cefsharp/CefSharp/releases/tag/v81.3.20-pre) and the `Timing` tab in `DevTools` looks as it does in `Chrome` to me (ignoring difference in colour scheme)

<img width="954" alt="devtoolsnetworktiming" src="https://user-images.githubusercontent.com/307872/82285091-eeb6c900-99dd-11ea-9eba-8899b8878596.PNG">
