### ISSUE TITLE
Global Cache - Instance Cookie Data

### ISSUE THREAD

**Issue by bbday** [cefsharp/CefSharp#3134]
Should be possible use global cache folder and use other folders specific for instace to store cookies

Atm you can setup  new CefSettings() {  CachePath = GlobalCache } and RequestContextSettings { CachePath = InstanceCacheFolder } but each instance that use RequestContext will use a different folder then each time will download again same data.

My issue cause i use a target website with multiple login at sametime i need to separate process with RequestContent (CachePath must be setup to rember cookie of session next time) but cause many part of web app are the same like imgs should be good if i can use just a global cache path then i'll save so much bandwitch and time without download again same files.

**Comment by amaitland** [comment]
That feature was removed in `CEF`. I very much doubt that it will be re-added.

You can make your request at https://magpcss.org/ceforum/viewforum.php?f=7

**Comment by amaitland** [comment]
See https://bitbucket.org/chromiumembedded/cef/issues/2622/implement-support-for-networkservice#comment-51303489 for background. 

Please remember that `CefSharp` is just a `Chromium Embedded Framework(CEF)` wrapper, the [CEF API](https://magpcss.org/ceforum/apidocs3/index-all.html) is what we have to work with.

In future please make sure to use the [Feature Request Tempalte](https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/feature_request.md)
