### ISSUE TITLE
CefSharp.winform runnable in winform Class Library?

### ISSUE THREAD

**Issue by softboy99** [cefsharp/CefSharp#3135]
a winform class libray allow form in it? i found CefSharp.winform lib cannot run in in winform Class Library? which are correct in .exe. I have a exe (only include MDI main form ) and many dlls(mdi children form) , I wrote a form using CefSharp.winform as a Common.dll which are shared to many dlls.
i see that `https://github.com/cefsharp/CefSharp/issues/199` are closed. Do i need to use OffScreen package if i want to use it in winform Class Library? Otherwise, we must use it in .exe.

**Comment by amaitland** [comment]
Yes you can. 

Please ask question on http://stackoverflow.com/questions/tagged/cefsharp

**Comment by softboy99** [comment]
> Yes you can.
> 
> Please ask question on http://stackoverflow.com/questions/tagged/cefsharp

@amaitland ， Do you mean we can use the browser form in class libray？ I try it but get blank page showed
