### ISSUE TITLE
Feature Request -  Provide a new option to the OnBeforePopup function

### ISSUE THREAD

**Issue by shimengkeji** [cefsharp/CefSharp#3136]
In the OnBeforePopup function, provide an option to make the new page always load in this browser .

I always encounter targetUrl = "about: blank", which prevents me from loading a new page in the current browser window. But the pop-up window works fine, it will jump to the correct page from "about: blank" .

Thanks !

**Comment by amaitland** [comment]
> `CefSharp` is a wrapper around the [Chromium Embedded Framework](https://bitbucket.org/chromiumembedded/cef/overview) in a lot of cases a feature must be added to `CEF` first before it can be used in `CefSharp`. `CEF` has it's own `Feature Request Forum` at https://magpcss.org/ceforum/viewforum.php?f=7

As per the [Feature Request Template](https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/feature_request.md)

Closing as this needs to be implemented in CEF. If CEF adds support and an API change is required then this can be reopened.
