### ISSUE TITLE
When the latest version of address is booted to some URLs, it will be blurred. If 71.0.1 is used, it will not

### ISSUE THREAD

**Issue by batsword** [cefsharp/CefSharp#3146]
When the latest version of address is booted to some URLs, it will be blurred. If 71.0.1 is used, it will not

**Comment by amaitland** [comment]
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Edit your original issue and fill out the required details.

**Comment by batsword** [comment]
x86,netframework4.6.1,when i used 71.0.1,it's normal。

**Comment by amaitland** [comment]
Please fill out the template.

> 81.3.100 will be blurred.

No idea what this means.

**Comment by batsword** [comment]
it may be dpi's problem.
