### ISSUE TITLE
Two browsers with request contexts - cannot change accept-language

### ISSUE THREAD

**Issue by tropa** [cefsharp/CefSharp#3147]
CefSharp  WPF 79, win 10, x86

MAIN PROBLEM: **the second browser window overwrites the context settings of the first one.**

I created two instances of ChromiumWebBrowser.
Each instance gets immediately after InitializeComponent ()
new RequestContext:

`this.сhrome.RequestContext = new RequestContext (contextSettings);`

Next, I set the proxy, user agent, and other settings for each browser, like WebRTC and they are applied on the fly inside of Cef.UIThreadTaskFactory as in the manual.

But when I try to set the locale in the same way, something strange happens. The locale is always set to en-GB.  Not en-US as it should be by default in case of incorrect configuration or its absence.
 
Further, if I try to change the headers in the IResourceRequestHandler, then the request headers that the OnBeforeResourceLoad method receives are set to those that I set when I try to set the locale, but then they change to en-GB.

The next oddity. If I create the context of the first browser, I create it like this:
`this.сhrome.RequestContext = new RequestContext(Cef.GetGlobalRequestContext(), new RequestContextHandler1());` then in this browser the locale settings begin to apply!  If I do exactly the same in the second browser, then the locale settings in both stop working. Always en-GB.

PS Now I see that proxy also not applied...

RequestContext.SetPreference returns true.

I will supplement it. I found out a little what was happening: the second window overwrites the context settings of the first window.

**Comment by tropa** [comment]
I have found the problem: same cachePath...
But what to do if I want browsers share cookies?

**Comment by amaitland** [comment]
Does the problem reproduce with version 81.3.100?

If it does then you'll need to move the conversation over to https://magpcss.org/ceforum/viewforum.php?f=6

Please post a link back here for reference. 

CefSharp is just one of many Chromium Embedded Framework(CEF) wrappers. How RequestContexts behave is entirely implemented in CEF. 

Closing as upstream.
