### ISSUE TITLE
Feature Request - Add support for direct DevTools protocol messaging

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#3158]
`CEF` has added support for Direct DevTools protocol messaging.

See https://bitbucket.org/chromiumembedded/cef/issues/2961/add-support-for-direct-communication-over

- [x] Add IBrowserHost.SendDevToolsMessage
- [x] Add IBrowserHost.ExecuteDevToolsMethod
- [x] Add IBrowserHost.AddDevToolsMessageObserver

**Comment by amaitland** [comment]
In theory this should open up a lot of different possabilities

- [Network.clearBrowserCache](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-clearBrowserCache) to clear the cache at runtime.
- Clearing of localStorage
- Screenshots

**Comment by amaitland** [comment]
Added to `master` in commit https://github.com/cefsharp/CefSharp/commit/49ee24912d9136b6cec437d9354241366f9d5949

**Comment by amaitland** [comment]
An example of taking a screenshot is available see https://github.com/cefsharp/CefSharp/commit/eee134c70fa1e2df94b07b57a8ef60aede89494d

**Comment by amaitland** [comment]
`IBrowserHost.ExecuteDevToolsMethodAsync` has been added to allow for execution without having to marshal the call onto the `CEF UI` thread.

These changes have now been merged into the `cefsharp/83` branch.

I'll look at adding a nicer `API` on top of the `CEF API` as a subsequent issue.

**Comment by A-BlackMoon** [comment]
Are there any way to target the DevTools Protocol Event ? I want to count the amount of data transferred over network .  but  nothing can target the Devtool Protocol Network Event in https://chromedevtools.github.io/devtools-protocol/1-3/Network/

I have use the cefsharp example of   DevToolsExtensions.CaptureScreenShotAsPng

https://stackoverflow.com/questions/62869744/whether-the-cefsharp-can-get-the-amount-of-data-transferred-like-devtools

**Comment by amaitland** [comment]
For Network/Page and any other domain that exposes events there are enable/disable methods. 

> Network.enable
> Enables network tracking, network events will now be delivered to the client.

https://chromedevtools.github.io/devtools-protocol/1-3/Network/#method-enable

> Network.disable
> Disables network tracking, prevents network events from being sent to the client.

https://chromedevtools.github.io/devtools-protocol/1-3/Network/#method-disable
