### ISSUE TITLE
IME in chinese status position

### ISSUE THREAD

**Issue by GaoJones** [cefsharp/CefSharp#3160]
Hi, i am using the CefSharp 81.3.100.0,  when i input  chinese  the input box position always to the top left corner of the screen, is fix it in new version,  as far as i know previous versions have had this problem all the time.

**Comment by amaitland** [comment]
Duplicate of #1262

Please report the problem you are having there.

**Comment by amaitland** [comment]
Possibly fixed by #3163

**Comment by amaitland** [comment]
Try upgrading to `83.4.20`

**Comment by Pursue00** [comment]
However, this problem still exists

**Comment by Pursue00** [comment]
> Try upgrading to `83.4.20`

However, this problem still exists

**Comment by amaitland** [comment]
If you can reproduce the problem with version 91 then you should add detailed steps to reproduce the problem at https://github.com/cefsharp/CefSharp/issues/1262

**Comment by Pursue00** [comment]
> If you can reproduce the problem with version 91 then you should add detailed steps to reproduce the problem at #1262

Do you mean that this problem has been resolved in the latest version?
