### ISSUE TITLE
Enhancement - Add DevToolsClient (Direct Devtools Protocol)

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#3165]
Follow up to #3158

A nicer `API` build on top of the `CEF API` to make it easier to send/receive messages from `DevTools`.

The `API` is generated on top of the `DevTools` protocol to create a set of model classes to simplify executing `DevTools` commands.

- [x] Add Strongly typed DevTools Domain classes
- [x] Deprecated methods are not generated
- [x] Only methods (no strongly typed events yet, a new issue should be created for that.)

The `CefSharp.DevTools.DevToolsClient` class is the primary method of accessing the different domains. Each `DevTools Domain` has it's own namespace that contains `enums` and strongly typed return classes.

[Network](https://chromedevtools.github.io/devtools-protocol/tot/Network/) `Domain` is part of the `CefSharp.DevTools.Network` namespace. The methods are accessibly though the `DevToolsClient` class.

Some basic examples look like (extract from the unit tests)

```c#
using (var browser = new ChromiumWebBrowser("www.google.com"))
{
	await browser.LoadPageAsync();

	using (var devToolsClient = browser.GetDevToolsClient())
	{
		var response = await devToolsClient.Network.SetCookieAsync(name, value, domain: domain, sameSite: sameSite);
	}
}

using (var browser = new ChromiumWebBrowser("www.google.com"))
{
	await browser.LoadPageAsync();

	using (var devToolsClient = browser.GetDevToolsClient())
	{
		var response = await devToolsClient.Browser.GetVersionAsync();
		var jsVersion = response.JsVersion;
		var revision = response.Revision;
	}
}
```

**Comment by amaitland** [comment]
`CEF` doesn't support every aspect of `DevTools`, the generated `API` is based of the protocol definition which can be downloaded from the browser at runtime and is used for code generation. If you find a method that `CEF` doesn't support please post here and I will at some point update the generator to remove those methods.

TO BE REMOVED:
- [ ] [Page.printToPdf](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF) is only accessibly when using `Headless Chromium` and not supported.

**Comment by amaitland** [comment]
Developing features like this takes considerably time and effort, if you use `CefSharp` in a commercial application then please consider sponsoring me https://github.com/cefsharp/CefSharp#financial-support

**Comment by amaitland** [comment]
Example of changing User Agent at runtime at https://stackoverflow.com/a/64543667/4583726

**Comment by totti240282** [comment]
With GetDevToolsClient is possible capture traffic in network tab ?

**Comment by amaitland** [comment]
Yes. You can subscribe to http://cefsharp.github.io/api/85.3.x/html/F_CefSharp_DevTools_DevToolsClient_DevToolsEvent.htm

As per https://github.com/cefsharp/CefSharp/issues/3158#issuecomment-657752330 you must call enable/disable for the specific domain.

**Comment by amaitland** [comment]
For .Net core it might be worth generating some nicer code in relation to the JSON parsing involved here. Using https://docs.microsoft.com/en-us/dotnet/api/system.text.json?view=net-5.0 should be feasible.

**Comment by amaitland** [comment]
See https://gist.github.com/amaitland/eabb42a191c4943610f2407196b0e03a for an example of changing tge user agent at runtime using the DevTools protocol.
