### ISSUE TITLE
Incosistent Javascript API when loading both CEFSharp and CEF in same application

### ISSUE THREAD

**Issue by lmartorella** [cefsharp/CefSharp#3170]
Hello,
I've found a possible inconsistency in the Javascript API when both CefSharp and native CEF are used at the same time in the same application. For example, when the Windows desktop application uses both .NET and native Win32/MFC components, and each technology creates Chromium instances.

The issue is that calling the Javascript function `window.CefSharp.BindObjectAsync` from the web page directly created using the CEF C API (then not through CefSharp), the promise will never return.

- **What version of the product are you using?**
    - Tested with latest v83.4.20, but still there on 79

- **What architecture x86 or x64?**
    Both
    
- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WinForms
    
- **What steps will reproduce the problem?**
   You can check this forked branch: https://github.com/iongroup/CefSharp/tree/mfc_83
   Once regularly built, launching the `CefSharp.Winform.Example`, a second floating window will be created for each tab.
   This window is implemented with the separate minimal MFC VC project (to have more readable code than bare Win32, but the issue should still be there).
   Both the tab and the MFC instance will load the same simple debug page, available as regular resource in the Example project. However, the MFC browser instance will wait indefinitely calling the JS function `window.CefSharp.BindObjectAsync` (the returned promise never returns).
  You should see something like that: ![Capture](https://user-images.githubusercontent.com/747421/86478691-ef67ac80-bd4a-11ea-982a-d2997526c1ba.PNG)

- **What is the expected output? What do you see instead?**
   We expect the Javascript `window.CefSharp` property not be there if the CEF browser was started from the CEF native API.
   Or, alternatively, that the `window.CefSharp.BindObjectAsync` call will return a promise that will be eventually resolved.

Thanks, L

**Comment by amaitland** [comment]
> I've found a possible inconsistency in the Javascript API when both CefSharp and native CEF are used at the same time in the same application. For example, when the Windows desktop application uses both .NET and native Win32/MFC components, and each technology creates Chromium instances.

If you are using `CefSharp.BrowserSubprocess.exe` (which is the default when you use `Cef.Initialize/CefSettings` provided by `CefSharp`) then what you are describing is basically as I'd expect.

> * We expect the Javascript `window.CefSharp` property not be there if the CEF browser was started from the CEF native API.

The `CefSharp.BrowserSubprocess` creates the `window.CefSharp` object for every `V8Context`. See
https://github.com/cefsharp/CefSharp/blob/cefsharp/83/CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.cpp#L101

There is currently no option to disable this. You are welcome to submit a `PR`.

> * Or, alternatively, that the `window.CefSharp.BindObjectAsync` call will return a promise that will be eventually resolved.

That's entirely up to you to implement this functionality for your `CefBrowser` instances. The `IPC` messages are sent on a per `CefFrame` level, so you have to provide the relevant response for any `CefBrowser` instance you created. It should be fairly trivial for you to respond to the message. You can start by looking at https://github.com/cefsharp/CefSharp/blob/cefsharp/83/CefSharp.BrowserSubprocess.Core/BindObjectAsyncHandler.h#L200
