### ISSUE TITLE
WinForms Example - Onscreen keyboard issue in touch screen devices

### ISSUE THREAD

**Issue by ajmal-ahmed** [cefsharp/CefSharp#3171]
On touch screen devices when we switch to tablet mode if we close onscreen keyboard that keyboard area becomes black. I've attached images below

Environment
-cefsharp version - latest & 71
-x86
-Win10
-WinForms
-Touch screen devices only

Steps to reproduce
-run Winforms example on above environment
-switch to tablet mode
-click on input field
-close the keyboard using the button on onscreen keyboard

![prior](https://user-images.githubusercontent.com/38724656/86509607-dc1a1700-be06-11ea-9fcf-e9c4f9e27bdc.png)

![black](https://user-images.githubusercontent.com/38724656/86509605-d91f2680-be06-11ea-8a43-5c82c3e406bd.png)

**Comment by amaitland** [comment]
Did you  test with the CEF Sample application? Details are in the bug report temple https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report

**Comment by ajmal-ahmed** [comment]
It works on CEF Sample application.
It seems i'm missing something regarding the focus handling of application.Application need to be resized to original size once keyboard is dismissed.
sorry for the trouble.

**Comment by ajmal-ahmed** [comment]
The windows forms application has the a above mentioned bug.
It works on CEF Sample Application.(Is the CEF Sample Application built on WPF?)
Steps to reproduce 
-run Winforms minimal example on touch screen device
-switch to tablet mode
-click on input field
-close the keyboard using the button on onscreen keyboard

**Comment by amaitland** [comment]
> Is the CEF Sample Application built on WPF?

No, it is a native `Win32` application.

> Steps to reproduce
> -run Winforms minimal example on touch screen device
> -switch to tablet mode
> -click on input field
> -close the keyboard using the button on onscreen keyboard

Have you tested this in isolation? This appears to be totally unrelated to `CefSharp`. If I create a `.Net 4.5.2` `WinForms` app with just a textbox I can reproduce a similar behaviour using `Windows 10 1903`. 

I'm inclined to close this as it appears to be a problem with `WinForms` and or `Windows 10`

**Comment by ajmal-ahmed** [comment]
>Have you tested this in isolation? This appears to be totally unrelated to CefSharp. If I create a .Net 4.5.2 WinForms app with just a textbox I can reproduce a similar behaviour using Windows 10 1903.

> I'm inclined to close this as it appears to be a problem with `WinForms` and or `Windows 10`

you're right, it seems to be a bug with Winforms and Windows 10 touch screen combination
