### ISSUE TITLE
WPF - Mouse click on a button triggers a mouse move event

### ISSUE THREAD

**Issue by alexgoaga** [cefsharp/CefSharp#3174]
Hi,

If you run the following code in cef browser 83.4.2 and google chrome(tested version 83.0.4103.116) you will notice that clicking on the button will trigger the following events

1. Cef Browser Mouse Move, Mouse Up, Mouse Move
2. Google Chrome. Mouse Up

This is working with cef version 75.1.14. After this version is broken.

Please find below the html to check this issue.

```html
<!DOCTYPE html>
<html>
<body>

<h2>test mouse move and up</h2>

<p>When clicking on the below button only mouse up event should be called, but mouse move is called as well</p>

<div>
<button id="myBtn" data-selectionelement="true">Click here to check move event(check console)</button>
<span data-selectionelement="true" data-resizeknob="true" />
</div>

<p id="demo"></p>

<script>
  function setMouseUp(e) {
    let current_date = new Date()
    let cms = current_date.getMilliseconds()
    console.log("Mouse Up. Time:" + cms)
  }

  function setMouseMove(e) {
    let current_date = new Date()
    let cms = current_date.getMilliseconds()
    console.log("Mouse Move. Time:" + cms)
  }

document.getElementById("myBtn").addEventListener("click", displayDate);
document.body.onmouseup = setMouseUp;
document.body.onmousemove = setMouseMove;

function displayDate() {

}
</script>

</body>
</html> 
```

Thanks,
Alex.

**Comment by amaitland** [comment]
Please fill out the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

**Comment by alexgoaga** [comment]
What version of the product are you using?
83.4.2
What architecture x86 or x64?
x64
On what operating system?
Win10,
Are you using WinForms, WPF or OffScreen?
WPF
What steps will reproduce the problem?

Run the below script and check the console. 

What is the expected output? What do you see instead?

**I expect to get. This is what I get in google chrome 83.0.4103.116** 
Mouse Down.
Mouse Up.
**while in In Cef Sharp:**
Mouse Down.
Mouse Move.
Mouse Up.
Mouse Move.
**and Cefclient**
Mouse Down.
Mouse Up.
Mouse Move.


Please provide any additional information below.?

Please run the script below.
There is still a problem with cef client, but cef sharp adds an extra Mouse Move between mouse down and Mouse Up. I am not sure this is a bug or a side effect of the cef bug. What I definitely know is that it adds an extra mouse move as compared to cef between mouse down and mouse up.

Does this problem also occur in the CEF Sample Application from http://opensource.spotify.com/cefbuilds/index.html?

Yes, but it in cefclient is different. As described above,  in cefclient I get 
Mouse Down.
Mouse Up.
Mouse Move.

while in cefsharp

Mouse Down.
Mouse Move.
Mouse Up.
Mouse Move.

cefclient details

CEF | 83.4.2+gc8d4f85+chromium-83.0.4103.106
-- | --
Chromium | 83.0.4103.106
OS | Windows
WebKit | 537.36 (@ce7134bb3d95141cd18f1e65772a4247f282d950)
JavaScript | 8.3.110.13
Flash |  
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36
Command Line | cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu --lang=en-US --log-file="C:\Release\debug.log" --disable-features=OutOfBlinkCors --enable-features=CastMediaRouteProvider --disable-gpu-shader-disk-cache


 ```html

<!DOCTYPE html>
<html>
<body>

<h2>test mouse move and up</h2>

<p>When clicking on the below button only mouse up event should be called, but mouse move is called as well</p>

<div>
<button id="myBtn" data-selectionelement="true">Click here to check move event(check console)</button>
<span data-selectionelement="true" data-resizeknob="true" />
</div>

<p id="demo"></p>

<script>
  function setMouseUp(e) {
    let current_date = new Date()
    let cms = current_date.getMilliseconds()
    console.log("Mouse Up. Time:" + cms)
  }

  function setMouseDown(e) {
    let current_date = new Date()
    let cms = current_date.getMilliseconds()
    console.log("Mouse Down. Time:" + cms)
  }

  function setMouseMove(e) {
    let current_date = new Date()
    let cms = current_date.getMilliseconds()
    console.log("Mouse Move. Time:" + cms)
  }

document.body.onmouseup = setMouseUp;
document.body.onmousemove = setMouseMove;
document.body.onmousedown = setMouseDown;

</script>

</body>
</html> 

```

As I said above, I am not sure whether this is a bug or a side effect of the cef bug.

Thanks,
Alex.

**Comment by amaitland** [comment]
I see you've created https://bitbucket.org/chromiumembedded/cef/issues/2982/mouse-click-on-a-button-triggers-a-mouse

I expect this needs to be fixed in CEF.

**Comment by amaitland** [comment]
You can add some debugging and see if the WPF events have changed dramatically. 
https://github.com/cefsharp/CefSharp/blob/cefsharp/83/CefSharp.Wpf/ChromiumWebBrowser.cs#L2461
https://github.com/cefsharp/CefSharp/blob/cefsharp/75/CefSharp.Wpf/ChromiumWebBrowser.cs#L2251

There have been some changes related to touch support and mouse capture. Nothing that jumps out.

**Comment by alexgoaga** [comment]
I have tried both versions, 83 and 75. this is the output
85
[0711/084455.528:INFO:CONSOLE(26)] "Mouse Down. Time:527", source: http://localhost:3000/test.html (26)
**!!!!!!!!!!!!!CefSharp Mouse move!!!!**
[0711/084455.544:INFO:CONSOLE(32)] "Mouse Move. Time:544", source: http://localhost:3000/test.html (32)
**!!!!!!!!!!!!!CefSharp Mouse move!!!!**
[0711/084455.745:INFO:CONSOLE(20)] "Mouse Up. Time:744", source: http://localhost:3000/test.html (20)
[0711/084455.777:INFO:CONSOLE(32)] "Mouse Move. Time:777", source: http://localhost:3000/test.html (32)

75
[0711/090123.255:INFO:CONSOLE(26)] "Mouse Down. Time:251", source: http://localhost:3000/test.html (26)
[0711/090123.468:INFO:CONSOLE(20)] "Mouse Up. Time:466", source: http://localhost:3000/test.html (20)

this is after changing protected override void OnMouseMove(MouseEventArgs e)
if (!e.Handled && browser != null && e.StylusDevice == null)
            {
                Debug.WriteLine("!!!!!!!!!!!!!CefSharp Mouse move!!!!");
                var point = e.GetPosition(this);
in both versions.

It looks like that with version 85 we get 2 extra mouse move events in ChromiumWebBrowser OnMouseMove as highlighted in bold.

Something

**Comment by amaitland** [comment]
You are welcome to submit a PR with proposed changes

**Comment by alexgoaga** [comment]
The problem looks like is with Chromium 
https://bugs.chromium.org/p/chromium/issues/detail?id=721341

It worked with version 73. All versions after that have a bug. 
The work around is to listen on mouse down, move, up and set a flag movedBy based on the movement of the mouse and if the mouse doesn't move just ignore the mouse move event.

Maybe a better approach is to handle the issue in the js code until the issue is fixed in chromium.

**Comment by alexgoaga** [comment]
Also, the fix can be as simple as adding the following code to mouse move

 if (!e.Handled && browser != null && e.StylusDevice == null)
            {
                var point = e.GetPosition(this);
                **if (oldMousePosition == point)
                {
                    return;
                }
                oldMousePosition = point;**
                var modifiers = e.GetModifiers();

                browser.GetHost().SendMouseMoveEvent((int)point.X, (int)point.Y, false, modifiers);
            }

and this to mouse down
if (e.StylusDevice == null)
{
    **oldMousePosition = e.GetPosition(this);**

There might be some edge cases that I have not considered in this code, but for my use case it works as expected.

Alex.

**Comment by amaitland** [comment]
https://bitbucket.org/chromiumembedded/cef/issues/2982/mouse-click-on-a-button-triggers-a-mouse#comment-58427544 reports that issue should ideally be fixed in chromium. 

As all the mouse events in WPF are protected virtual anyone should be able to implement the own workaround without modifying the source. 

Closing as upstream. Can be reopened if it's deemed nessicary that we need to make changes. https://bugs.chromium.org/p/chromium/issues/detail?id=721341#c38 suggests that chromium should filter these out at some point.
