### ISSUE TITLE
WPF - keydown event shows lowercase while pressing shift key 

### ISSUE THREAD

**Issue by EMJagadeesh** [cefsharp/CefSharp#3177]
Hi,

I've found a possible inconsistency in cef sharp 79.1.360 in our application, the issue is when we press shift with an alphabets event key shown lower case letters in the keydown events.

**What version of the product are you using?**
79.1.360

**What architecture x86 or x64?**
Both

**On what operating system?**
Win10

**Are you using WinForms, WPF or OffScreen?**
WPF

**What steps will reproduce the problem?**

**Reproducible Sample:** 
[SampleApp.zip](https://github.com/cefsharp/CefSharp/files/4898945/SampleApp.zip)

1. Start the sample
2. Type lower and upper case letters
3. Issue will replicate

**What is the expected output? What do you see instead?**

**Expected Output:**
We expect the shift with a key, keydown  event key will return uppercase letter and without using shift event key will return lower case letter.(**propertyName:** event.key)

**Actual Output:**
Lowercase are return in event key for both uppercase and lower case key(**propertyName:** event.key)

![image](https://user-images.githubusercontent.com/64392941/87054440-bc2c8e00-c220-11ea-9eda-d38b911944d1.png)

```html
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
</head>
<style>
    #kinput {
        font-size: 150%;
        box-sizing: border-box;
        width: 65%;
    }

    #area {
        width: 65%;
        box-sizing: border-box;
        height: 250px;
        border: 1px solid black;
        display: block;
    }

    form label {
        display: inline;
        white-space: nowrap;
    }
</style>
<body>
    <form id="form" onsubmit="return false">
        <p>Focus on the input field and press a key.</p>
        <input type="text" placeholder="Press keys here" id="kinput">
        <textarea id="area"></textarea>
        <input type="button" value="Clear" onclick="area.value = ''" />
    </form>
    <script>
        var input = document.getElementById("kinput");
        input.addEventListener("keydown", (e) => {
            var text = e.type +
                ' key=' + e.key +
                ' code=' + e.code +
                (e.shiftKey ? ' shiftKey' : '') +
                (e.ctrlKey ? ' ctrlKey' : '') +
                (e.altKey ? ' altKey' : '') +
                (e.metaKey ? ' metaKey' : '') +
                (e.repeat ? ' (repeat)' : '') +
                "\n";
            area.value += text;
        })
    </script>
</body>
</html>
```
Thanks,
Jagadeesh

**Comment by amaitland** [comment]
> Please only create an issue if you can reproduce the problem with version 83.4.20 or greater.

As per https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report have you confirmed the issue is present in version 83.4.20?

Please no binary attachments (zip, 7z, etc), code needs to be easily reviewed in a web browser. (Again this is stated in the bug report temple)

Did you test with the CEF Sample application? You seem to have omitted that section of the template.

**Comment by amaitland** [comment]
If this reproduces with the CEF Sample application then this is issue https://bitbucket.org/chromiumembedded/cef/issues/2597/windows-windowless-keyboard-handling
