### ISSUE TITLE
WPF - Transparent background not work at 83.4.20 version

### ISSUE THREAD

**Issue by h82258652** [cefsharp/CefSharp#3178]
- **What version of the product are you using?**
83.4.20

- **What architecture x86 or x64?**
x86
    
- **On what operating system?**
Windows 10 Home 1903 

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
1. create a ```Window```.
2. set ```Background``` to ```Transparent```.
3. set ```AllowsTransparency``` to ```True```.
4. set ```WindowStyle``` to ```None```.
5. load a simple HTML by ```ChromiumWebBrowser```.

- **What is the expected output? What do you see instead?**
In 81.3.100 version, the window will be transparent, but in 83.4.20, the window will be with a white background.

- **Please provide any additional information below.**
I create a simple repo here: https://github.com/h82258652/CefSharpTransparentBugDemo

**Comment by amaitland** [comment]
This is a known issue, I've added a link to the release notes.

Needs to be fixed in `CEF` you can subscribe to https://bitbucket.org/chromiumembedded/cef/issues/2938/osr-transparent-background-broken-since to track the progress.

Closing as `upstream`.

**Comment by h82258652** [comment]
@amaitland Thanks for the response.
