### ISSUE TITLE
Remove CefSettings.RegisterExtension

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#3184]
CEF changes in the upcoming 85 branch mean we'll likely have to remove this method see https://bitbucket.org/chromiumembedded/cef/commits/280c9127c1fcec485a53bd3ef44e581655a4ab7b

Look at replacing with a script that's executed on the create of each V8Context which is registered at the ChromiumWebBrowser level. 

Details to follow.

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/blob/ec4d4a4eab5f477d943db2e5d693bfb35340df9f/CefSharp.Core/Internals/CefSharpApp.h#L193

**Comment by amaitland** [comment]
We can either implement our own or use DevTools addScriptToEvaluateOnNewDocument

https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-addScriptToEvaluateOnNewDocument

**Comment by amaitland** [comment]
Adding an extension method for addScriptToEvaluateOnNewDocument is a quick win so we'll add that for a starter.

**Comment by darbid** [comment]
If I understand this correctly it is similar to adding the content scripts from an extension.

It would be really useful to have an event that fires for each frame at a point in time when JavaScript could be injected. [https://developer.chrome.com/extensions/content_scripts#run_time](url) shows also something interesting, the scripts can be injected at different times, not sure if CEF exposes this stuff.

**Comment by amaitland** [comment]
You are probably thinking of a Chrome extension, this the V8Extension which is different to a chrome extension.  The current implementation calls https://magpcss.org/ceforum/apidocs3/projects/(default)/(_globals).html#CefRegisterExtension(constCefString&,constCefString&,CefRefPtr%3CCefV8Handler%3E) in the render process. 

> It would be really useful to have an event that fires for each frame at a point in time when JavaScript could be injected.

This already exists in the form of IRenderProcessMessageHandler.OnContextCreated which is fired when the V8Context is created.

https://github.com/cefsharp/CefSharp/wiki/General-Usage#when-can-i-start-executing-javascript

We currently expose all the events that CEF has to offer.

> https://developer.chrome.com/extensions/content_scripts#run_time shows also something interesting, the scripts can be injected at different times, not sure if CEF exposes this stuff

These are related to Chrome extensions and should already be supported to a limited degree. Again not related to a V8Extension.

**Comment by amaitland** [comment]
It is now only possible to register a `V8Extension` directly in the `Render Process`. You can implement `IRenderProcessHandler.OnWebKitInitialized` (from within your own custom BrowserSubProcess implementation) to register the same extension. This is for those who **absolutely** have to use a `V8Extension`.

With #3229 it will be easy to call `DevTools` protocol commands. The [Page.AddScriptToEvaluateOnNewDocument](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-addScriptToEvaluateOnNewDocument) method is the suggested replacement.

```c#
using (var devToolsClient = browser.GetDevToolsClient())
{
	//Evaluates given script in every frame upon creation (before loading frame's scripts).
	var response = await devToolsClient.Page.AddScriptToEvaluateOnNewDocumentAsync();
	var scriptIentifier = response.Identifier;

	//You can remove a script at a later point
	await devToolsClient.Page.RemoveScriptToEvaluateOnNewDocumentAsync(scriptIentifier);
}
```
