### ISSUE TITLE
Core - Add IBrowser reference to TitleChangedEventArgs/ConsoleMessageEventArgs

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#3185]
It's not currently possible to distinguish between a title change/console message from the main browser and the popups.

- [x] Add IBrowser property to TitleChangedEventArgs
- [x] Add IBrowser property to ConsoleMessageEventArgs

**Comment by amaitland** [comment]
Resolved in commit https://github.com/cefsharp/CefSharp/commit/282e25c8fda81e9514cb708c1586094dbcd02b60

**Comment by artem-voropaev** [comment]
@amaitland thx a lot. Waiting for realese!

**Comment by amaitland** [comment]
Reopening as reminder to cherry pick commit into upcoming release branch
