### ISSUE TITLE
OnCertificateError not called for redirect requests

### ISSUE THREAD

**Issue by AndreasKorn** [cefsharp/CefSharp#3202]
- **What version of the product are you using?**
    CefSharp.WinForms 83.4.20 from nuget.org

- **What architecture x86 or x64?**
    x86 and x64
    
- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WinForms
    
- **What steps will reproduce the problem?**
    I have a login page with a form our some server with usually a self signed certificate.
    The submit action makes a POST request to the server, which returns a redirect response (302) with location header.
    The redirect location points to localhost (https://127.0.0.1:20001/oauth2/client?code=1e8402e0-de0d-4b61-86b4-413cc204c688&state=f38c5323-cb4a-41b4-886f-e5824826dc7a).

    For the requests to the actual login page the OnCertificateError handler is called and I can handle it fine.
    For the request to the redirect url no handler is called at all, not even OnBeforeBrowse.
    The log file contains an ssl error about this though: [0731/133748.207:ERROR:ssl_client_socket_impl.cc(959)] handshake failed; returned -1, SSL error code 1, net_error -202

    This all works fine if I set the "ignore-certificate-errors" commandline option, but that's not really an option for production. The OnCertificateError  handler is also called for "normal" requests to localhost or 127.0.0.1, just not for redirect requests as it seems.

**Comment by amaitland** [comment]
`CefSharp` is just one of many wrappers around the [Chromium Embedded Framework (CEF)](https://bitbucket.org/chromiumembedded/cef/)

The `CEF` project has it's own [Issue Tracker](https://bitbucket.org/chromiumembedded/cef/issues).

If you do find an existing issue that matches this one or create a new one then post a link here for others. 

Closing this as `upstream` and as changes/fixes need to be made in `CEF`.

**Comment by AndreasKorn** [comment]
https://bitbucket.org/chromiumembedded/cef/issues/2996/oncertificateerror-not-called-for-redirect
