### ISSUE TITLE
CefSharp authentication cookie is missing required information about Azure workplace join

### ISSUE THREAD

**Issue by bucmic** [cefsharp/CefSharp#3206]
I'm not sure if this is properly described from a detailed technical POV but let's have a try:

Let's assume your company is using Azure and MFA is configured to be required on unmanaged devices (e.g. personal device). When you're trying to sign in to a web page like Azure DevOps Services using your Microsoft Work Account on a managed device, MFA will come up. According to our AAD admin this is because CefSharp's authentication cookie doesn't contain information that the device is managed, that means the Azure Workplace Join has been applied and the device is hence registred in company's Azure tenant.

Maybe this can be fixed in one of the next releases?

**Comment by amaitland** [comment]
Please ask your question on https://magpcss.org/ceforum/index.php (post a link back here for reference). CefSharp itself doesn't implement any of this functionality itself. 

Closing as CefSharp is just one of many Chromium Embedded Framework. Please read the first few paragraphs of https://github.com/cefsharp/CefSharp/wiki/General-Usage for basic overview.
