### ISSUE TITLE
Core - Update IBrowserHost.Find xml doc

### ISSUE THREAD

**Issue by thphan75** [cefsharp/CefSharp#3210]
- **What version of the product are you using?**
79.1.360.0

- **What architecture x86 or x64?**
x64

- **On what operating system?**
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms

- **What steps will reproduce the problem?**
    browser = new ChromiumWebBrowser("");
    browser.FindHandler = new CefFindHandler();        

Using the most basic function:
    browser.Find(1, "FindText", true, false, false);

- **What is the expected output? What do you see instead?**
The OnFindResult was supposed to return the identifier passed but, instead, it's returning an incremented number regardless if I'm doing a Find First, Previous, Next, or Last.

In addition, while the count and activeMatchOrdinal is correct, it appears to be connected to the last First/Last find, not necessarily associated with the identifier.

For example, if I did this and the result reports 20, the next and previous works fine and provides the correct count/activeMatchOrdinal.
    browser.Find(1, "FindText", true, false, false);

If I did this and the result reports 30, the next and previous works fine and provides the correct count/activeMatchOrdinal as well, however, it will report off of the new search only.
    browser.Find(2, "FindText2", true, false, false);

If I did a Find Previous or Next, the count/activeMatchOrdinal returns information from the browser.Find(2,.... instead, until a browser.Find(1,... was used in conjunction with a First or Last, which will then reset and provide the correct info.
    browser.Find(1, "FindText", false, false, true);
    browser.Find(1, "FindText", true, false, true);

The output that's expected should be associated with the identifier that's passed and the identifier passed should be the value that's returned rather than an incremented number.

**Comment by amaitland** [comment]
The `Chromium Embedded Framework (CEF)` project has it's own [Issue Tracker](https://bitbucket.org/chromiumembedded/cef/issues), please report this issue there. `CefSharp` is just one of many wrappers around the [Chromium Embedded Framework (CEF)](https://bitbucket.org/chromiumembedded/cef/)

If you do find an existing issue that matches this one or create a new one then post a link here for others. 

Closing this as `upstream` as changes/fixes need to be made in `CEF`.

**Comment by amaitland** [comment]
CefSharp simply passes the values we get from CEF to the IFindHandler.OnFindResult

https://github.com/cefsharp/CefSharp/blob/cefsharp/83/CefSharp.Core/Internals/ClientAdapter.cpp#L982
https://magpcss.org/ceforum/apidocs3/projects/(default)/CefFindHandler.html

**Comment by thphan75** [comment]
Thank you for the reference, I was able to find this piece of code, which explains why the identifier was incrementing.  In other words, CefSharp's documentation or definition might need to be updated.

void CefBrowserPlatformDelegateAlloy::Find(int identifier,
                                           const CefString& searchText,
                                           bool forward,
                                           bool matchCase,
                                           bool findNext) {
  if (!web_contents_)
    return;

  // Every find request must have a unique ID and these IDs must strictly
  // increase so that newer requests always have greater IDs than older
  // requests.
  if (identifier <= find_request_id_counter_)
    identifier = ++find_request_id_counter_;
  else
    find_request_id_counter_ = identifier;

  auto options = blink::mojom::FindOptions::New();
  options->forward = forward;
  options->match_case = matchCase;
  options->find_next_if_selection_matches = findNext;
  web_contents_->Find(identifier, searchText, std::move(options));
}

**Comment by amaitland** [comment]
The document does appear to have been changed, as the code is hand written any changes made upstream must be manually tracked. 

- https://bitbucket.org/chromiumembedded/cef/src/ec3e9ed7fecc0d9f37a96951ba1bb26fd4f64dc7/include/cef_browser.h#lines-483
- http://cefsharp.github.io/api/83.4.x/html/M_CefSharp_IBrowserHost_Find.htm

Reopening as we should update IBrowserHost.Find xml doc based on the updated comments. 

https://bitbucket.org/chromiumembedded/cef/src/304e0155097a4576429fa27c8fa5a4c736f17d4b/include/cef_browser.h#lines-481

You are welcome to submit a PR.
