### ISSUE TITLE
WPF Example - Migrate from MVVMLight

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#3215]
MVVMLight is from what I can tell no longer being actively maintained, we should migrate to something else, our requirements are quite simple.

Some options are

- https://github.com/reactiveui/ReactiveUI
- https://github.com/PrismLibrary/Prism

**Comment by campersau** [comment]
Or just remove MVVMLight https://github.com/cefsharp/CefSharp/compare/master...campersau:remove_mvvm since only two features (`INotifyPropertyChanged` and `RelayCommand`) are used?

**Comment by amaitland** [comment]
Thanks. That's certainly a valid option.  I'd like to checkout ReactiveUI in particular, so this is a chance to do that. If it doesn't look like it's worth it then we'll go with your option 👍

**Comment by amaitland** [comment]
I haven't found time to look into `ReactiveUI` so just going with the commit proposed by @campersau 

Resolved in commit https://github.com/cefsharp/CefSharp/commit/8ad0c76f1b8c2f0a8e79c9805b12075416129f63
