### ISSUE TITLE
CefSettings no longer implements IDisposable

### ISSUE THREAD

**Issue by DominikPalo** [cefsharp/CefSharp#3220]
The [`CefSettings`](https://cefsharp.github.io/api/51.0.0/html/T_CefSharp_CefSettings.htm) class implements `IDispodable`, therefore settings instances should be always disposed (either by calling `settings.Dispose()` or by decorating the initialization block with `using (var settings = new CefSettings())`). 

If you look at the [official  WPF example](https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf.Example/App.xaml.cs), you can see that the `settings` object is not disposed.

```
protected override void OnStartup(StartupEventArgs e)
{
    // ...

    var settings = new CefSettings();
    settings.MultiThreadedMessageLoop = multiThreadedMessageLoop;
    settings.ExternalMessagePump = !multiThreadedMessageLoop;

    CefExample.Init(settings, browserProcessHandler: browserProcessHandler);

    base.OnStartup(e);
}
```

Not only it is a bad practice (I think it can cause memory leaks), but also Visual Studio shows a warning:

![image](https://user-images.githubusercontent.com/1623257/90871776-e33bbb00-e39b-11ea-9129-e25f0d7e055f.png)

**Comment by amaitland** [comment]
> I think it can cause memory leaks

Just to add some detail to this, it's rare for an application to have a more than one `CefSettings` instance, the base class also implements a finalizer so the `GC` will collect the resource eventually. 

Again, pull requests are welcome. I have higher priorities at the moment.

**Comment by mzboray** [comment]
A question on this. It was my observation that disposing the CefSettings with a using like proposed is actually bad because it will dispose some resource that is being used by CEF/CefSharp internally. One would need to move the settings into a field and dispose after Cef is shutdown. Is my understanding correct?

**Comment by amaitland** [comment]
@mzboray Yes, at least for versions 86 and below. With the next release (87) the CefSettings classes will no longer implement IDisposable, the internal resources will be freed after they are no longer used.

**Comment by mzboray** [comment]
Ok thanks. I'll keep an eye out when upgrading to the next version.
