### ISSUE TITLE
WinForms - Browser will not load page on form created in a new desktop

### ISSUE THREAD

**Issue by jasonc-forerunnersw** [cefsharp/CefSharp#3227]
Nuget 84.4.10
x86
Win10
WinForms

We start a program in the current desktop and then create a new desktop using:

 hOldDesktop = WinAPI.GetThreadDesktop(WinAPI.GetCurrentThreadId());
 hNewDesktop = WinAPI.CreateDesktop("WFHSecure", IntPtr.Zero, IntPtr.Zero, 0, WinAPI.DESKTOP_ALL, IntPtr.Zero);
WinAPI.SetThreadDesktop(hNewDesktop);

We start the application in the new desktop and load the form.  

Application.Run(Form1);

WinAPI.SwitchDesktop(hNewDesktop);

When the form loads all other controls work, but the browser does not load.  It is very hard to debug since VS is in the first desktop.  The control is not returning any errors, but seems to stay in the not initialed state.

debug.log is empty.  

If we run the exact same code, but do not create the new desktop everything works as expected.  All of the calls are only from controls on the form or though invoke on the form..

**Comment by amaitland** [comment]
Your welcome to debug and submit a PR. 

I don't have time to look into this. Perhaps two monitors would make debugging easier. 

I'd also suggest modifying the CEF Sample application and make sure it actually works (after confirming cefclient unmodified runs on the new desktop).

In future please use the bug report temple (keeping the headers and listing and 3rd party libraries you are using).

**Comment by amaitland** [comment]
The standard distribution available for download from http://opensource.spotify.com/cefbuilds/index.html contains the source for cefclient. You'll need cmake to generate the project files.

**Comment by jasonc-forerunnersw** [comment]
Thank you, we modified the winforms sample with the same results.  Multiple monitors does not help with debugging a separate desktop unless you know how to have one desktop in one monitor and the other in a different monitor.

After looking at a lot of the code, it is likely that CEF is creating a new UI thread for the control.  Assuming this is the case, I think this thread would need to be moved to the new desktop as the application was created on the old desktop.

Does this seem correct to you?

**Comment by amaitland** [comment]
> we modified the winforms sample with the same results

The `CEF Sample Application(cefclient)` is a native `C++` app, it can be downloaded from the spotify link above. Not the same as the `WinForms` example.

> Multiple monitors does not help with debugging a separate desktop unless you know how to have one desktop in one monitor and the other in a different monitor.

From the little I know you can have a app show on all desktops, see https://superuser.com/a/1299300

> After looking at a lot of the code, it is likely that CEF is creating a new UI thread for the control. Assuming this is the case, I think this thread would need to be moved to the new desktop as the application was created on the old desktop.

By default `CEF` will create it's own `UI Thread`. You can integrate `CEF` into the `WinForms` message loop, see https://github.com/cefsharp/CefSharp/wiki/General-Usage#multithreadedmessageloop

https://github.com/cefsharp/CefSharp/blob/cefsharp/84/CefSharp.WinForms.Example/Program.cs#L63

I'd still suggest you download the `cefclient` and modify it, confirm it works before doing anything else.

**Comment by amaitland** [comment]
Closing due to lack of feedback. 

I suspect this is just a matter of switching the CEF UI thread over to the new desktop or integrate CEF into your apps existing message loop.
