### ISSUE TITLE
Feature Request - NotifyDpiChange support in ChromiumWebBrowser for WinForms

### ISSUE THREAD

**Issue by jozefizso** [cefsharp/CefSharp#3238]
**Describe the solution you'd like**
We need to notify the ChromiumWebBrowser for WinForms about the DPI scaling change manually. I could not find a method similar to `ChromiumWebBrowser.NotifyDpiChange()` in the WPF version of CefSharp.

**Describe alternatives you've considered**
We are using the `--disable-gpu-compositing` flag to disable GPU composition which fixes some bugs which may occur when Chromium is hosted inside a task pane.

One notable bug is when the Chromium renders the content outside of UserControl which is hosted in the task pane. This can be mitigated by disabling the GPU composition.

**Additional context**
We are hosting the ChromiumWebBrowser inside a task pane (the task pane hosts a UserControl which includes the  ChromiumWebBrowser) in the Microsoft Office add-in. Because of the design of MS Office, the Office application will not propagate the DPI awareness into the COM addins and task panes.

Office Addin developers must manually set the DPI awareness context in their threads and this context is always reset on Office side. See [Handle high DPI and DPI scaling in your Office solution
](https://docs.microsoft.com/en-us/office/client-developer/ddpi/handle-high-dpi-and-dpi-scaling-in-your-office-solution) for more information.

Office applications will also cause the `GetProcessDpiAwareness()` method to always return `PROCESS_SYSTEM_DPI_AWARE` even though the process is running in the `PROCESS_PER_MONITOR_DPI_AWARE` mode.
Because of this we cannot use the `Cef.EnableHighDPISupport()` to enable the support for HighDPI scaling and notifications about changes to DPI are not received by the task pane nor ChromiumWebBrowser.

We can detect the change to DPI scaling using the `WM_SIZE` message and notify the ChromiumWebBrowser manually if WinForms implementation would support `NotifyDpiChange()` method.

**Checklist:**
- [ ] I have reviewed the [CEF API](https://magpcss.org/ceforum/apidocs3/index-all.html) and have confirmed the feature I'm requesting is possible.
- [ ] The Feature I'm requesting is an improvement to Async Javascript Binding (No new feature are being added to the Sync Javascript binding)
- [ ] An open `PR` exists on the [CEF Pull Requests](https://bitbucket.org/chromiumembedded/cef/pull-requests/) and I'd like to propose this feature is added to `CefSharp` when/if it's merged.

**Comment by amaitland** [comment]
> manually if WinForms implementation would support `NotifyDpiChange()` method.

There's no `CEF API` that would allow for this. Perhaps there is a low level message you can send to the handle, I'm not aware of any though.

Please move the discussion to https://magpcss.org/ceforum/index.php (post a link back here).

Closing as it's not possible to support this currently, if CEF adds support we can reopen.

**Comment by amaitland** [comment]
> Office applications will also cause the `GetProcessDpiAwareness()` method to always return `PROCESS_SYSTEM_DPI_AWARE` even though the process is running in the `PROCESS_PER_MONITOR_DPI_AWARE` mode.

See #2927 for discussion on configuring the `GPU` process awareness.

**Comment by amaitland** [comment]
https://source.chromium.org/chromium/chromium/src/+/master:ui/views/win/hwnd_message_handler.cc;l=1693;bpv=1;bpt=1?q=Dpichange&ss=chromium

You can try manually sending [wm-dpichanged](https://docs.microsoft.com/en-us/windows/win32/hidpi/wm-dpichanged) to http://cefsharp.github.io/api/84.4.x/html/M_CefSharp_IBrowserHost_GetWindowHandle.htm

If that doesn't work then asking on ceforum is the go.

**Comment by jozefizso** [comment]
> You can try manually sending [wm-dpichanged](https://docs.microsoft.com/en-us/windows/win32/hidpi/wm-dpichanged) to http://cefsharp.github.io/api/84.4.x/html/M_CefSharp_IBrowserHost_GetWindowHandle.htm

I tried to send the `WM_DPICHANGED` manually to `webView.Handle` and it did not work. I did not realize I need to use the Chromium handle. I will try `IBrowserHost.GetWindowHandle()`.

Thanks a lot for the hint! 🥇

**Comment by amaitland** [comment]
Spy++ should give you some insight into the window structure.
