### ISSUE TITLE
Feature Request - WPF Add Toggle Audio Mute Command

### ISSUE THREAD

**Issue by ChristinaKochan** [cefsharp/CefSharp#3247]
**Describe the solution you'd like**
I would like to be able to utilize the SetAudioMuted feature in CEF from the WPF browser using a bindable dependency property.

**Describe alternatives you've considered**
For our implementation we need to be able to mute per browser and not just overall, so there isn't really an alternative.

**Additional context**
We have had this feature working on our own branch for two years and I've finally had some time to update my branch and get a pull request prepared.

**Checklist:**
- [X] I have reviewed the [CEF API](https://magpcss.org/ceforum/apidocs3/index-all.html) and have confirmed the feature I'm requesting is possible.
- [ ] The Feature I'm requesting is an improvement to Async Javascript Binding (No new feature are being added to the Sync Javascript binding)
- [X] An open `PR` exists on the [CEF Pull Requests](https://bitbucket.org/chromiumembedded/cef/pull-requests/) and I'd like to propose this feature is added to `CefSharp` when/if it's merged.

**Comment by amaitland** [comment]
> I would like to be able to utilize the SetAudioMuted feature in CEF from the WPF browser using a bindable dependency property.

Just to be clear you can implement an attached property to implement this sort of behaviour without needing to modify the `CefSharp.Wpf.ChromiumWebBrowser` source. 

> For our implementation we need to be able to mute per browser and not just overall, so there isn't really an alternative.

The `CEF API` for muting the browser was added over a year ago, so the ability to implement your own attached property has existed for a long time.
