### ISSUE TITLE
Feature Request  - Create Nuget symbol packages

### ISSUE THREAD

**Issue by SachinAmbokar** [cefsharp/CefSharp#3256]
I was trying to push Cefsharp.WPF nuget package in my organization nuget server. 
This nuget server was configured to ignore symbols packages (Wont able to change configuration of it). Hence I am not able to push them in private nuget server. When I extracted nupkg file for Cefsharp.WPF, symbol files were present. For that matter, TFS build is getting failed as nuget package was not available in private nuget gallary.
It will be great, if we can have **CefSharp.WPF.nupkg** (without symbol) and **CefSharp.WPF.snupkg** (with symbol) as two different packages.

**Comment by amaitland** [comment]
As I understand it to use the Nuget.org symbol server portable pdbs are required which requires VS2017. We currently still use VS2015, upgrading would change the VC++ version, at least with how the current scripts are designed. I have no short term plans to upgrade to VS2017.

https://devblogs.microsoft.com/nuget/improved-package-debugging-experience-with-the-nuget-org-symbol-server/

You are welcome to do your own research and submit a PR for review.

**Comment by amaitland** [comment]
> The portable PDB format can be created and consumed for any .NET application provided that the consuming client is on .NET 4.7.1 or later.

Limiting users to `.Net 4.7.1` isn't really practical as we only require a minimum of `.Net 4.5.2`.

It seems infeasible to implement this currently, closing for now. If something changes we can reopen.
