### ISSUE TITLE
Downloading any file from trusted domain is downloaded as untrusted file.

### ISSUE THREAD

**Issue by KalpeshMJain88** [cefsharp/CefSharp#3258]
Downloading any file from trusted domain is downloaded as untrusted file.
This is reproducible by downloading any file and then do the right click and click on properties.
You can see following highlighted message as per SS.

![image](https://user-images.githubusercontent.com/58659728/96222822-91ce3780-0faa-11eb-8a77-f159b961a08b.png)

CEF Version - 79
OS -Win10.

Even tried setting ApplicationClientIdForFileScanning with GUID during CEF intialization, but still no luck

**Comment by amaitland** [comment]
Already asked at https://stackoverflow.com/questions/64228783/downloading-a-trusted-file-is-downloaded-as-untrused-file-in-cef-browser-control

As I've already suggested you will need to ask on https://magpcss.org/ceforum/index.php
