### ISSUE TITLE
input type number allows for multiple periods

### ISSUE THREAD

**Issue by bmmpt** [cefsharp/CefSharp#3262]
- **What version of the product are you using?**
    - 85.3.121

- **What architecture x86 or x64?**
    x86
    
- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WinForms
    
- **What steps will reproduce the problem?**
    - Create an input where type="number"
    - Enter more than one period, eg. 111.22.33

- **What is the expected output? What do you see instead?**
    - Chrome browser doesn't render more than 1 period. Only the first period in the example above would render: 111.2233

**Comment by amaitland** [comment]
Please test with the CEF Sample application as requested in the bug report temple. 

https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report

**Comment by bmmpt** [comment]
I logged a bug here https://bitbucket.org/chromiumembedded/cef/overview and it has not shown up. 

I added the bug in a feedback option on this page https://bitbucket.org/chromiumembedded/cef/jira?statuses=new&statuses=indeterminate&sort=-updated&page=1.
I'm not even sure to be the right way, since it doesn't even ask for an email of the person posting the issue. But I could not fine any other way to log a bug.

**Comment by amaitland** [comment]
https://bitbucket.org/chromiumembedded/cef/issues/3035/input-type-number-allows-for-multiple

The suggestion is that the bug is fixed in version 86. You can subscribe to release only notifications to be notified when a new version is available.

**Comment by bmmpt** [comment]
Thanks @amaitland, I will definitely keep an eye out for M86.
