### ISSUE TITLE
Core - Improve IPopupFeatures mapping and xml doc 

### ISSUE THREAD

**Issue by SirIntellegence** [cefsharp/CefSharp#3270]
In [`IPopupFeatures`](https://github.com/cefsharp/CefSharp/blob/57f00e0627332f8632fcd4245b7893d321291a10/CefSharp/IPopupFeatures.cs#L1), there are some properties that match the pattern of "*Set". The documentation for these items are terrible since they are ints instead of bools due to [this commit](https://bitbucket.org/chromiumembedded/cef/commits/72660c6fed539ff8e901825aca890bea195ad31d). If they were bools, that would have been easy to figure out, but they are not and I had to dig around and found this [lucky file](https://magpcss.org/ceforum/apidocs/projects/(default)/cef_types.h.html) to see that they were bools. Also, not all of the fields are accounted for (for reference). Could you change those to bools or give them proper documentation?

- **What version of the product are you using?**
    - Nuget: 85.3.130.0
- **What architecture x86 or x64?**
    Both, but that likely doesn't matter since since this is compile time
    
- **On what operating system?**
   Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WinForms

**Comment by amaitland** [comment]
Your welcome to submit a PR. 

Just change the interface and https://github.com/cefsharp/CefSharp/blob/76c7918b83c2485f9ab664f343399b71368fa0bf/CefSharp.Core/PopupFeatures.h

**Comment by amaitland** [comment]
See https://github.com/chromiumembedded/cef/blob/4240/include/internal/cef_types.h#L2077 for M86 branch header. 

As CEF doesn't document what the fields are actually for it's very difficult to provide accurate documentation. 

Looking a little closer and the references you've provided are all outdated. Should the set properties be Boolean? I have no idea.

**Comment by amaitland** [comment]
A quick look through the CEF source and the `Set` properties should probably be removed and the `x,y,width,height` properties changed to `Nullable<int>`

https://github.com/chromiumembedded/cef/blob/cae194f493328a9890b27533ce1dc661e0d4b042/libcef/browser/browser_info_manager.cc#L36

**Comment by SirIntellegence** [comment]
From what I could tell, they were bools, but they were changed to ints to be compatible with another compiler. C++ does implicit casts to bool, so it wasn't a problem for them, but C# does not. I will see if I can make a pull request.

**Comment by SirIntellegence** [comment]
I am tempted to turn those into nullable ints. Would that be ok to do?

**Comment by amaitland** [comment]
https://github.com/chromiumembedded/cef/blob/cae194f493328a9890b27533ce1dc661e0d4b042/libcef/browser/browser_info_manager.cc#L162 suggests they are used as bool.

I think nullable int makes sense as the set properties are used to tell if a value was specified.

**Comment by SirIntellegence** [comment]
Ok. Do you have any convention for branches for given issues (like "bug-<issuenumber>" or "<CEF-issuenumber>")?

**Comment by amaitland** [comment]
Whatever you choose will be fine.
