### ISSUE TITLE
Feature Request - Get Windows Process ID

### ISSUE THREAD

**Issue by PixelDevelopers** [cefsharp/CefSharp#3271]
I've been through the documentation and attempted various methods and can't seem to get a reliable answer.

I am using the offscreen ChromiumWebBrowser to load specific urls and pull the html for analysis as part of my project. To aid speed, this is multi threaded, so I am creating an instance on each thread and need to be able to ensure the process is killed off after the fact. Occasionally, this does not work and one remains active despite dispose calls and using statements. It then keeps growing in memory and uses a big amount of CPU.

In order to ensure each one is closed, I was wondering if I can get to the windows process id for the browser instance?

**Comment by amaitland** [comment]
Duplicate #2984
