### ISSUE TITLE
CefSharp.CefMenuCommand enum There are duplicate values

### ISSUE THREAD

**Issue by AtlantisDe** [cefsharp/CefSharp#3276]
## There are duplicate values
```c#
//CefSharp, Version=85.3.130.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138
SpellCheckSuggestion4 = 204,
SpellCheckLastSuggestion = 204,
```

![alt](https://img-bbs.csdn.net/upload/202011/08/1604824253_972775.png)

**Comment by amaitland** [comment]
Thanks,  this isn't a mistake. It matches the CEF enum.

https://github.com/cefsharp/CefSharp/blob/bef5dd37c4617714729042855120724279501f80/CefSharp/Enums/CefMenuCommand.cs#L37
https://github.com/chromiumembedded/cef/blob/master/include/internal/cef_types.h#L1667
