### ISSUE TITLE
WPF - cannot redraw page on Intel 11th Core  Iris Xe Integration graphic card

### ISSUE THREAD

**Issue by LMing123** [cefsharp/CefSharp#3280]
- **What version of the product are you using?**
    - Nuget v85.3.130

- **What architecture x86 or x64?**
    x64
    
- **On what operating system?**
    Win10 20H2

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WPF
    
- **What steps will reproduce the problem?**
  1. use [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) complied  CefSharp.MinimalExample.Wpf 
  2. open WPF example on 11th Intel Core cpu whit Iris Xe graphics.
  3. the web page don't auto redraw unless manual resize window.
 

- **What is the expected output? What do you see instead?**
 it's not any expected output, just this page doesn't redraw.

- **Please provide any additional information below.**
CefSharp.WPF dosen't have this problem. just WPF have.
use this code disable WPF hardware acceleration, everything  seem normal.
```
protected override void OnSourceInitialized(EventArgs e)
        {
            base.OnSourceInitialized(e);
            HwndSource source = PresentationSource.FromVisual(this) as HwndSource;
            if (source != null)
                source.CompositionTarget.RenderMode = RenderMode.SoftwareOnly;
        }
```

- **Does this problem also occur in the `CEF` Sample Application**
  NO, only occur in CefSharp.WPF.

**Comment by amaitland** [comment]
Thanks for the workaround 👍 Have you reported the issue with the `WPF` team?

Making this as `known-issue`.

As this doesn't appear to be anything actionable from a `CefSharp` point of view I'm going to close this.

**Comment by LMing123** [comment]
> Thanks for the workaround 👍 Have you reported the issue with the `WPF` team?
> 
> Making this as `known-issue`.
> 
> As this doesn't appear to be anything actionable from a `CefSharp` point of view I'm going to close this.

okay,  thanks for you reply.

I haven't reported this to the WPF Team,  now that I'll report the issue to WPF team.

**Comment by amaitland** [comment]
Intel reportedly have an updated driver available for download 
https://www.intel.com/content/www/us/en/support/articles/000058136/graphics/graphics-for-11th-generation-intel-processors.html
