### ISSUE TITLE
Serial port prompt does not appear (Serial API)

### ISSUE THREAD

**Issue by Jonas-Axelsson** [cefsharp/CefSharp#3303]
- **System Information**
    - CefSharp (WPF) NuGet package v.85.3.130.
    - Windows 10 x64
    
- **Steps to reproduce the problem**
    (Tested in the 'Minimal Example' application (https://github.com/cefsharp/CefSharp.MinimalExample)).
    - Add 'enable-experimental-web-platform-features' flags via command line before initializing.
    - Open Dev Tools console window.
    - Enter 'await navigator.serial.requestPort()' in console to prompt user for choice regarding serial port to use.
    - BUG: No prompt is displayed and the console command returns error: 'Uncaught DOMException: No port selected by the user.'.

- **Expected output versus actual output**
    The user should receive a popup prompting the user to select a serial port, something like below:
	
    ![image](https://user-images.githubusercontent.com/74181480/101020985-90af9480-356f-11eb-85c9-08672a84f54d.png)

    Instead no prompt of any kind is shown, with the following error:
	
    ![image](https://user-images.githubusercontent.com/74181480/101021052-afae2680-356f-11eb-83fe-918576f85fa4.png)

    Perhaps there is simply no support for the relatively new Serial API yet? 
    (It has also crossed my mind that the action to open such a prompt is something that developers must implement themselves, I have however failed to find any information supporting this in my search).

- **Additional information**
    - Tried to run the CEF 'Sample Application' (with the recommended command lines plus 'enable-experimental-web-platform-features') to try and replicate it there, but sadly the application crashes when trying to open the Dev Tools console via right click.

**Comment by amaitland** [comment]
The serial API is not yet support by CEF. CEF has a feature request forum at https://magpcss.org/ceforum/viewforum.php?f=7 where you can discuss your request. 

There's nothing I can do until CEF adds support.

**Comment by Jonas-Axelsson** [comment]
Alright, good to know!

Thanks for the fast response!
