### ISSUE TITLE
Print pdf artifacts

### ISSUE THREAD

**Issue by flyfix** [cefsharp/CefSharp#3313]
What version of the product are you using?
**86.0.241**

What architecture x86 or x64?
**x86**

On what operating system?
**Win10**

Are you using WinForms, WPF, or OffScreen?
**WPF**

What steps will reproduce the problem?
1.Download and run CefSharp  MinimalExample from
[https://github.com/cefsharp/CefSharp.MinimalExample]

2.
In web browser from minimal example use the path to sample pdf and open preview
[PdfToOpen.pdf](https://github.com/cefsharp/CefSharp/files/5671587/PdfToOpen.pdf)

3.Click on the printer icon and try to "Save as Pdf" or print

4.The printed document contains artifacts like in this file
[PrintedPdf.pdf](https://github.com/cefsharp/CefSharp/files/5671586/PrintedPdf.pdf)

Looks like some pdf tags are not supported by the CefSharp print feature. I did the same workflow from google chrome and everything seems to be fine.
The problem is with chart background color:
![image](https://user-images.githubusercontent.com/5718844/101752819-3a43d800-3ad2-11eb-844f-376cd9d4e229.png)

I did this test in version 83 of CefSharp and the issue is the same.

**Comment by amaitland** [comment]
@flyfix Did you test with the `CEF Sample Application(cefclient)`?

> If you can reproduce the problem with cefclient then you'll need to report the bug on https://bitbucket.org/chromiumembedded/cef/overview there is no point opening an issue here. (Make sure you search before opening an issue)

As per https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report

Please test with the `CEF Sample application`.

**Comment by amaitland** [comment]
> If you can reproduce the problem with cefclient then you'll need to report the bug on https://bitbucket.org/chromiumembedded/cef/overview there is no point opening an issue here. (Make sure you search before opening an issue)

To clarify the point I'm trying to make is that features like the PDF viewer are implemented at the CEF/Chromium level. There is is not something I can fix directly.

See https://bitbucket.org/chromiumembedded/cef/issues/3048/proposal-remove-pdf-viewer-print-preview for discussion about the PDF viewer, hopefully chromium changes to which layer the PDF viewer is implemented will resolve the numerous outstanding issues.

**Comment by flyfix** [comment]
I was able to reproduce this in chromiem.
I've created issue in their system
https://bitbucket.org/chromiumembedded/cef/issues/3063/artefacts-in-pdf-document-after-print

Thanks for fast response !

**Comment by amaitland** [comment]
Closing as upstream as the problem reproduces with the CEF Sample application. If code changes are required then this can be reopened.
