### ISSUE TITLE
Feature Request - Block send data by specific url

### ISSUE THREAD

**Issue by bbday** [cefsharp/CefSharp#3318]
I would like to block send data by specific url example
Post/Put for url X - Y
I thought was GetResourceRequestHandler() : IResourceRequestHandlerFactory but look like not catch this specific PUT (this call return http error 460 and look like is not catch by this function when have this return code (when is 200 work), should be possible block call before it send it??? cause also if return http error data was sent)

Is there other function to do it?
Thanks

**Comment by bbday** [comment]
fixed

**Comment by amaitland** [comment]
Please ask your question in the https://github.com/cefsharp/CefSharp/discussions section please.
