### ISSUE TITLE
Nuget Package Restructure

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#3319]
### Summary
To resolve a few long standing issues and to better support `.Net Core` going forward I'm restructuring the `Nuget Packages`, this includes the inclusion of `CefSharp.Core.Runtime.dll`, this is actually the current `CefSharp.Core.dll` with a new managed dll called `CefSharp.Core.dll` which allows me to switch (at least mostly) to having `CefSharp.Core.runtime.dll` as a runtime only dependency.

**UPDATE**
Whilst it is no longer necessary to close `Visual Studio` for the references to show up (https://github.com/dotnet/project-system/issues/4158) the runtime dependencies, `libcef.dll` etc still aren't copied until the project is closed/reopened when using `packages.config` style projects. Using `PackageReference` works correctly and is the recommended option. Please note you can use `PackageReference` with older `non SDK Style` projects (ones that would typically have used `packages.config`) under `VS2017/2019`.

**CefSharp.Core.Runtime.dll** will need to be distributed with your application.

### Breaking Changes
- The following arch specific (`x86/x64`) dlls have been converted to `AnyCPU`:
  - `CefSharp.dll`
  - `CefSharp.WinForms.dll`
  - `CefSharp.Wpf.dll`
  - `CefSharp.OffScreen.dll`

Specifying `$(CefSharpTargetDir)` in `MSBuild` will no longer move these files to a sub folder as they are now included in the `lib\net452` folder within the `Nuget` package (this is the standard). Moving `libcef.dll` and it's many other resources is still possible.

### Details
- Better support `.Net Core/5.0`
- `CefSharp.Core.dll` is now written in `C#` with `CefSharp.Core.Runtime.dll` being the runtime dependency that provides the `Mixed Mode CLI/C++` implementation. 
- Simplify `AnyCPU` targeting 
- Resolves issue with `pacakges.config` based projects having to reload the solution for the dependencies to show up (https://github.com/dotnet/project-system/issues/4158)
- Remove requirement for package consumers having to change `$(Platform)` at the **solution** level ($PlatformTarget) at project level is now sufficient
- Greater control over how `libcef.dll` is loaded.
- Potential to add additional runtime checks like validating `VC++` is installed.
- Upgraded `GitLink`

### Changes:
  
- Rename `CefSharp.Core.dll` to `CefSharp.Core.Runtime.dll`
  - No longer directly referenced by client applications
  - All the `Public API` methods it exposes are hidden from `Visual Studio Intellisense`
  - Used indirectly through new `CefSharp.Core.dll` (`AnyCPU` class library).
    
- Add `CefSharp.Core.dll`
  - Managed (`AnyCPU`) dll that provides the public `API`
  - In `.Net Core` there will be a `CLR Module Initializer` to load `libcef.dll` from the relevant location where required
  - Additional runtime checks can be added to validate if say `VC++` is installed
  - Generally give more control over loading of the unmanaged resources and setting the relevant paths e.g. BrowserSubProcessPath

### Known Issues:

~~Specifying `<CefSharpTargetDir/>` in `MSBuild` doesn't currently copy `CefSharp.dll` to the subfolder which is required by the `BrowserSubProcess`.~~

~~Temp workaround is to copy `$(CefSharpCommonManagedDlls)` to the subfolder via a custom `AfterBuild Target`.~~

### Additional

`.csproj.nuget.g.props` files in the `obj` directory have a `$(NuGetProjectStyle)` which might be better than the current `'$(UsingMicrosoftNETSdk)' != 'true'` check to determine if a `SDK Style(PackageReference`) project.

```
<NuGetProjectStyle Condition=" '$(NuGetProjectStyle)' == '' ">PackageReference</NuGetProjectStyle>
```
      
PR #3311

**Comment by amaitland** [comment]
The `Ref` Assemblies don't appear to be build correctly on `AppVeyor`.

https://ci.appveyor.com/project/cefsharp/cefsharp/builds/36859715/job/lmn6djbvfijk3fui#L591

**Comment by amaitland** [comment]
> Whilst it is no longer necessary to close `Visual Studio` for the references to show up ([dotnet/project-system#4158](https://github.com/dotnet/project-system/issues/4158)) the runtime dependencies, `libcef.dll` etc still aren't copied until the project is closed/reopened when using `packages.config` style projects. Using `PackageReference` this isn't a problem and is the recommended project structure.

It might be possible to hack something together where a `Target` copies the files when using `packages.config` and they don't appear in the output folder.

**Comment by amaitland** [comment]
> It might be possible to hack something together where a `Target` copies the files when using `packages.config` and they don't appear in the output folder

Limited testing suggests adding a PropertyGroup is enough to get the files copied, commit https://github.com/cefsharp/CefSharp/commit/a29a1df41480222796f7cffbc1a067023cc52de7

I've added code to copy the files via a Target, it's currently commented out and can be enabled after more testing if required.

**Comment by amaitland** [comment]
To better support `ClickOnce` I've added the option to switch from using the `<None/>` entries to `<Content/>`  this should allow support via a single configuration setting in the `proj` file.

Add the following to a `PropertyGroup` in your `proj` file before the `.targets` entries (which are at the bottom).
```xml
<CefSharpBuildAction>Content</CefSharpBuildAction>
```

This is included in version `87.1.130-pre`. I'd appreciate anyone using `ClickOnce` test this change and report back.

**Comment by amaitland** [comment]
The first set of `-pre` release packages are now on `Nuget.org`

- https://www.nuget.org/packages/CefSharp.WinForms/87.1.130-pre
- https://www.nuget.org/packages/CefSharp.Wpf/87.1.130-pre
- https://www.nuget.org/packages/CefSharp.OffScreen/87.1.130-pre

The rest of the changes related to updating the documentation will be tracked as part of #3343

**Comment by amaitland** [comment]
Testing with https://github.com/cefsharp/CefSharp.MinimalExample/tree/cefsharp/87

Specifying `BrowserSettings` in the `.Net 4.5.2` example using the older style `pacakges.config` option is generating the following error which I'll need to resolve.

```
The type 'BrowserSettings' is defined in an assembly that is not referenced. You must add a reference to assembly 'CefSharp.Core.Runtime, Version=87.1.130.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138'.	CefSharp.MinimalExample.WinForms
```

I might need
- Refactor `BrowserSettings` out so it's a decorator (will be the same problem for `RequestContext` and all the other public types, so this might not actually work as I'd hoped).
- Dynamically add the `CefSharp.Core.Runtime` dll reference (I was hoping to avoid this, though it looks the most likely option at least for the `packages.config` option, I can add a `ref` assembly for the `PackageReference` includes)

**Comment by mzuvin** [comment]
Thanks my problem solved. @amaitland

**Comment by mzuvin** [comment]
CefSharp TargetDir ". \" relative path in `build\CefSharp.Common.targets` file causes clickonce app to fail.

**Comment by amaitland** [comment]
> CefSharp TargetDir ". " relative path in build\CefSharp.Common.targets file causes clickonce app to fail.

What do you mean?  Please provide more detail.

**Comment by mzuvin** [comment]
> > CefSharp TargetDir ". " relative path in build\CefSharp.Common.targets file causes clickonce app to fail.
> 
> What do you mean? Please provide more detail.


The relative path (. \) Is in the file names section of the Application Files window. That's the problem. I can't find the setup error log file in ClickOnce. Maybe it's because I'm using VS2015.

https://github.com/cefsharp/CefSharp/blob/cefsharp/87/NuGet/CefSharp.Common.targets#L238 

It has to be like this:
```
<Link>%(RecursiveDir)%(FileName)%(Extension)</Link>
```

**Comment by amaitland** [comment]
> The relative path ` .\` Is in the file names section of the Application Files window. That's the problem. I can't find the setup error log file in ClickOnce. Maybe it's because I'm using VS2015.
> 
> https://github.com/cefsharp/CefSharp/blob/cefsharp/87/NuGet/CefSharp.Common.targets#L238

@mzuvin The `.` is the default when you don't specify your own https://github.com/cefsharp/CefSharp/blob/cefsharp/87/NuGet/CefSharp.Common.targets#L34 
The property exists so you can specify a subfolder for the `CefSharp` files to be copied into (optional)

My suggestion would be to move the `CefSharp` files to a subfolder, utilising the `CefSharpTargetDir` feature.

Add the following to your `proj` file in a `<PropertyGroup/>` (example for `x86`, use `x64` if you target is different)

```xml
<CefSharpTargetDir>x86</CefSharpTargetDir>
```

Add the following to your `app.config` as detailed in https://msdn.microsoft.com/en-us/library/4191fzwb.aspx

```xml
<runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
        <probing privatePath="x86"/>
    </assemblyBinding>
</runtime>
```

**Comment by amaitland** [comment]
> Specifying `BrowserSettings` in the `.Net 4.5.2` example using the older style `pacakges.config` option is generating the following error which I'll need to resolve.

The simplest option is to change from directly creating the types and have a factory method for each type (`CefSharp.Core.ObjectFactory` has methods to create public api types). This unfortunately would be a major breaking change.

I did  look at some other options previously which were unsuccessful, having each class implement the interface and include a inner reference (basically a decorator) with an explicit operator, unfortunately this only worked in a few limited scenarios, example class:

```c#
public class PostData : IPostData
{
	private CefSharp.Core.PostData postData = new CefSharp.Core.PostData();

	/// <inheritdoc/>
	public IList<IPostDataElement> Elements
	{
		get { return postData.Elements; }
	}

	/// <inheritdoc/>
	public bool IsReadOnly
	{
		get { return postData.IsReadOnly; }
	}

	/// <inheritdoc/>
	public bool IsDisposed
	{
		get { return postData.IsDisposed; }
	}

	/// <inheritdoc/>
	public bool HasExcludedElements
	{
		get { return postData.HasExcludedElements; }
	}

	/// <inheritdoc/>
	public bool AddElement(IPostDataElement element)
	{
		return postData.AddElement(element);
	}

	/// <inheritdoc/>
	public IPostDataElement CreatePostDataElement()
	{
		return new CefSharp.Core.PostDataElement();
	}

	/// <inheritdoc/>
	public void Dispose()
	{
		postData.Dispose();
	}

	/// <inheritdoc/>
	public bool RemoveElement(IPostDataElement element)
	{
		return postData.RemoveElement(element);
	}

	/// <inheritdoc/>
	public void RemoveElements()
	{
		postData.RemoveElements();
	}

	public static explicit operator CefSharp.Core.PostData(PostData postData)
	{
		return postData.postData;
	}

	public static IPostData Create()
	{
		return new CefSharp.Core.PostData();
	}
}
```

A variation on this, the option I've gone with is to add an `UnWrap` method to the interfaces and provide a similar implementation to that provided above, just not relying on the explicit operator, calling `UnWrap` to get a reference to the inner type. The `CefSharp.Core.Runtime` implementations also implement `UnWrap` and just return a reference to themselves. This has an unfortunate overhead, I think the benefits outweigh the cost though, having `CefSharp.Core.Runtime` as purely a runtime requirement with no direct reference is a big win and greatly simplifies packing the library. 

If I can come up with a better way in the future (or someone has a workable suggestion) then we can change this would having to change the public API. There's a small chance I've missed a call or two that requires an `UnWrap`, instead of creating the object directly using the factory methods should workaround the problem until it's been resolved.

**Comment by ryantm** [comment]
Hello.

Thanks for improving the ClickOnce situation! I tried testing this out on my .Net Framework 4.7.2 WinForms project, which is still on Visual Studio Express 2017. I am using the PackageReference format for Nuget Packages.

```
    <PackageReference Include="CefSharp.Common">
      <Version>87.1.130-pre</Version>
    </PackageReference>
    <PackageReference Include="CefSharp.WinForms">
      <Version>87.1.130-pre</Version>
    </PackageReference>
``` 

I added this property group before any targets in my csproj file:

```
  <PropertyGroup>
    <CefSharpBuildAction>Content</CefSharpBuildAction>
  </PropertyGroup>
```
and when I try to build my application I get this compiler error:

```
error CS0012: The type 'BrowserSettings' is defined in an assembly that is not referenced. You must add a reference to assembly 'CefSharp.Core.Runtime, Version=87.1.130.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138'.
```

on the second line here:
```
emailHtmlViewer = new CefSharp.WinForms.ChromiumWebBrowser("");
emailHtmlViewer.BrowserSettings = (CefSharp.IBrowserSettings)new CefSharp.BrowserSettings()
```

Looks related to (or exactly the same as) the issue you mentioned in https://github.com/cefsharp/CefSharp/issues/3319#issuecomment-757580537

**Comment by amaitland** [comment]
> The relative path ` .\` Is in the file names section of the Application Files window. That's the problem. I can't find the setup error log file in ClickOnce. Maybe it's because I'm using VS2015.

@mzuvin Commit https://github.com/cefsharp/CefSharp/commit/dd17a9d67ce183892dfd5dc1e69e2911b71bc402 removes the slash and appends one if required to `CefSharpTargetDir`, hopefully this resolves your issue.

> I added this property group before any targets in my csproj file:

@ryantm For new `SdkStyle` projects (`PackageReference`), I'm changing the default to `Content` so hopefully this won't be required in the next `-pre` release.

> Looks related to (or exactly the same as) the issue you mentioned in [#3319 (comment)](https://github.com/cefsharp/CefSharp/issues/3319#issuecomment-757580537)

Yes, same problem as I've detailed above. I've merged a fix, I'd like to add a few more unit tests before rolling out another `-pre` release in the next day or so.

**Comment by amaitland** [comment]
The `87.1.131-pre` packages are now on `Nuget.org` ready for additional testing.

**Comment by ryantm** [comment]
@amaitland Thanks again!

I tried `87.1.131-pre` and now it compiles okay.

When I deploy with ClickOnce and run, it I get this error:

```
Could not load file or assembly 'CefSharp.Core.Runtime.dll' or one of its dependencies. The specified module could not be found.
```

The only CefSharp-related files I see in my ClickOnce Application Files folder are:
- CefSharp.WinForms.dll
- CefSharp.dll
- CefSharp.Core.Runtime.dll
- CefSharp.Core.dll

I'm not sure what files in https://github.com/cefsharp/CefSharp/wiki/Output-files-description-table-(Redistribution) are still required in the new version, but a lot of them are missing.

This is all without referencing https://www.nuget.org/packages/cef.redist.x86/ . Is it necessary to reference that package (or 64bit) anymore?

**Comment by amaitland** [comment]
> I tried `87.1.131-pre` and now it compiles okay.

@ryantm Does it run successfully under `Visual Studio`?

> I'm not sure what files in https://github.com/cefsharp/CefSharp/wiki/Output-files-description-table-(Redistribution) are still required in the new version, but a lot of them are missing.

All of them with the addition of the new `CefSharp.Core.Runtime.dll`

> This is all without referencing https://www.nuget.org/packages/cef.redist.x86/ . Is it necessary to reference that package (or 64bit) anymore?

If you are using `PacakgeReference` then only the top level package reference is required, the others will be included as transitive dependencies.

https://github.com/cefsharp/CefSharp.MinimalExample/blob/cefsharp/87/CefSharp.MinimalExample.WinForms/CefSharp.MinimalExample.WinForms.net472.csproj is the example I am testing with.

> I tried testing this out on my .Net Framework 4.7.2 WinForms project, which is still on Visual Studio Express 2017

I didn't know they still made `Visual Studio Express` versions. I'm testing with `VS 2019 Community` and when I do a simple `Publish` to a folder the expected files are included and runs without issue.

**Comment by amaitland** [comment]
> I didn't know they still made `Visual Studio Express` versions. I'm testing with `VS 2019 Community` and when I do a simple `Publish` to a folder the expected files are included and runs without issue.

I've subsiquently published using `ClickOnce` for a `packages.config` project and installed the resulting package on a virtual machine successfully. 

>Add the following to a PropertyGroup in your proj file before the .targets entries (which are at the bottom).
> ```
> <CefSharpBuildAction>Content</CefSharpBuildAction>
> ```

Setting the above property was all that was required.

**Comment by amaitland** [comment]
> It might be possible to hack something together where a `Target` copies the files when using `packages.config` and they don't appear in the output folder.

Unfortunately this was not possible, testing with `VS2017` and it failed to pickup the `.props` files so whilst the `Target` ran it didn't actually copy anything. For now I'm just displaying a message to the build output. Most of the time `VS2019` works as expected, so it's really just `VS2017` that's consistently a problem (closing and reopening the project/solution fixes the problem as expected).

**Comment by amaitland** [comment]
All changes are done, the `87.1.132` packages are now available, see https://github.com/cefsharp/CefSharp/issues/3343#issuecomment-772129820 for details.

**Comment by amaitland** [comment]
> I've subsequently published using `ClickOnce` for a `packages.config` project and installed the resulting package on a virtual machine successfully.

This works when the `PlatformTarget` is `x86/x64`. Unfortunately `AnyCPU` is not working as `MSBuild` includes an extra copy of `CefSharp.Core.Runtime.dll` in the `bin` folder. We don't explicitly specify, it just tries to be helpful and copies the `x86` version when ideally it shouldn't copy any file. The `.targets` file deletes this extra copy under normal circumstances. When publishing I have yet to find a way to exclude this file from the `ClickOnce` installer.

**Comment by hlipsey23** [comment]
> Unfortunately `AnyCPU` is not working as `MSBuild` includes an extra copy of `CefSharp.Core.Runtime.dll` in the `bin` folder. We don't explicitly copy this file, it would appear that `MSBuild` is trying to be helpful and copies the `x86` version when ideally it shouldn't copy any file. The `.targets` file deletes this extra copy under normal circumstances. When publishing I have yet to find a way to exclude this file from the `ClickOnce` installer.
> 
> I'm not aware of any workaround at this stage. I've tried a few options to exclude this file:
> 
> * https://sitecore.stackexchange.com/questions/9363/excluding-files-like-web-config-when-using-publishing-in-vs-2017
> * [dotnet/sdk#7861](https://github.com/dotnet/sdk/issues/7861)
> 
> If anyone has a suggestion on how to workaround this then please let me know.

Our solution for this that seems to be working so far is to Exclude CefSharp.Core.Runtime.dll in the ClickOnce Application Files pop up. We also had to include CefSharp.dll and CefSharp.Core.dll in our targets file to copy those to the x86 and x64 folders, the BrowserSubprocess was crashing on launch otherwise.

**Comment by amaitland** [comment]
> UPDATE: I've only been testing with VS2019, reports suggest that VS2017 isn't working and you'll need to use one of the solutions from #1314

In the upcoming version 88 release VS2017 should work as expected with `x86/x64` PlatformTarget as the extra copy of CefSharp.Core.Runtime.dll has been excluded https://github.com/cefsharp/CefSharp/blob/cefsharp/88/NuGet/CefSharp.Common.targets#L17

> Unfortunately AnyCPU is not working as MSBuild includes an extra copy of CefSharp.Core.Runtime.dll in the bin folder.

In version 88, the extra copy should be removed with https://github.com/cefsharp/CefSharp/blob/cefsharp/88/NuGet/CefSharp.Common.targets#L32

The x64 folder is missing a copy of CefSharp.dll, the x86 folder has the file as expected. Seems to be a quirk we'll have to workaround. 

> We also had to include CefSharp.dll and CefSharp.Core.dll in our targets file to copy those to the x86 and x64 folders, the BrowserSubprocess was crashing on launch otherwise.

@hlipsey23 Can you please provide an example as a reference to others. You should only need CefSharp.dll for the Browsersubprocess, it shouldn't require CefSharp.Core.dll

**Comment by hlipsey23** [comment]
@amaitland Sure thing. Calling `Cef.Initialize` with `performDependencyCheck` set to true threw an exception saying that both CefSharp and CefSharp.Core were missing, so I'm copying both over to be safe. This is the full .targets file, mostly taken from another user in a related issue. The two `Content` tags that reference the packages folder are the modifications I made to copy those two dlls.

`<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Condition="'$(Platform)' == 'x64'">
    <Content Include="@(CefRedist64)">
      <Link>x64\%(RecursiveDir)%(FileName)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <PublishState>Include</PublishState>
      <Visible>false</Visible>
    </Content>
    <Content Include="@(CefSharpCommonBinaries64)">
      <Link>x64\%(RecursiveDir)%(FileName)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <PublishState>Include</PublishState>
      <Visible>false</Visible>
    </Content>
    <Content Include="@(CefSharpWinFormsBinaries64)">
      <Link>x64\%(RecursiveDir)%(FileName)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <PublishState>Include</PublishState>
      <Visible>false</Visible>
    </Content>
	  <Content Include="..\packages\CefSharp.Common.87.1.132\lib\net452\*.dll">
		  <Link>x64\%(FileName)%(Extension)</Link>
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <PublishState>Include</PublishState>
		  <Visible>false</Visible>
	  </Content>
  </ItemGroup>
  <ItemGroup Condition="'$(Platform)' != 'x64'">
    <Content Include="@(CefRedist32)">
      <Link>x86\%(RecursiveDir)%(FileName)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <PublishState>Include</PublishState>
      <Visible>false</Visible>
    </Content>
    <Content Include="@(CefSharpCommonBinaries32)">
      <Link>x86\%(RecursiveDir)%(FileName)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <PublishState>Include</PublishState>
      <Visible>false</Visible>
    </Content>
    <Content Include="@(CefSharpWinFormsBinaries32)">
      <Link>x86\%(RecursiveDir)%(FileName)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <PublishState>Include</PublishState>
      <Visible>false</Visible>
    </Content>
	  <Content Include="..\packages\CefSharp.Common.87.1.132\lib\net452\*.dll">
		  <Link>x86\%(FileName)%(Extension)</Link>
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <PublishState>Include</PublishState>
		  <Visible>false</Visible>
	  </Content>
  </ItemGroup>
</Project>`

**Comment by amaitland** [comment]
@hlipsey23 Are you using AnyCPU with Prefer32bit = true? If you are then in version 88 you can set CefSharpPlatformTargetOverride to x86 in your project file and only the x86 libs will be copied, no x86/x64 folders, your installer will be smaller. Making sure you've also set CefSharpBuildAction as per https://github.com/cefsharp/CefSharp/issues/3319#issuecomment-769578780

https://github.com/cefsharp/CefSharp/blob/cefsharp/88/NuGet/CefSharp.Common.targets#L102

The 88 release will happen sometime in the next week.

**Comment by hlipsey23** [comment]
@amaitland Thanks, we actually release in either x86 or x64 due to some other dependencies - so our libraries are all AnyCPU (one of which uses CefSharp), while the executables will be one or the other. So the `ItemGroup`s with conditions to check the build platforms is working perfectly here.

**Comment by amaitland** [comment]
@hlipsey23 once you upgrade to 88 or higher I'd suggest you review the targets file I linked, Platform is no longer used to determine which files to copy, PlatformTarget is. Your solution can and should be simplified. Set CefSharpTargetDir to Platform to have the files copied to a subprocess folder.

**Comment by MarkusWolf87** [comment]
Hi,

I tried Version 88 with VS 2015 and VS 2019.

I added the following in the project file:

 <PropertyGroup>
    <CefSharpBuildAction>Content</CefSharpBuildAction>
  </PropertyGroup>

Starting the app from the bin folder release or debug is working.

But If I deploy it with clickone deployment I always get the error: assembly CefSharp.Core.Runtime.dll is missing.

**Comment by amaitland** [comment]
For anyone publishing using `ClickOnce` you will need a minimum of version `88.2.90` which I've just released. See https://github.com/cefsharp/CefSharp/issues/3389#issuecomment-791070701 for release details.

I don't have `VS2015` installed, so no testing has been done on that version.

---

Developing/Maintaining this project takes a significant amount of my time. If you are using `CefSharp` in commercial software please considering supporting me via [GitHub Sponsors](https://github.com/sponsors/amaitland). I need your support to continue developing/maintaining the project.

**Comment by MarkusWolf87** [comment]
Thanks.
I have tested 88.2.90 with VS 2015 and .net 4.6.
It is working with X64.

Any CPU is not working. Do you have any workaround for this? Thanks.

**Comment by amaitland** [comment]
> Any CPU is not working.

For `ClickOnce` only `x86` and `x64` are currently working. `AnyCPU` still behaves strangely, the `x64` folder is missing a copy of `CefSharp.dll` which is required by the `BrowserSubprocess`. The file is copied correctly when the projects builds normally, so there's some quirk of the `Publish` process. 

I'm not sure what is causing this and don't currently have a workaround. Try one of the solutions from https://github.com/cefsharp/CefSharp/issues/1314 and see how you go.

If anyone has insight into what's happening during `Publish` please let me know.

**Comment by jozefizso** [comment]
Is the `<CefSharpAnyCpuSupport>` still supported in the `.csproj` files? Or do we need to change how we build and package the CefSharp libraries when upgrading to v88 in a solution which uses AnyCPU platform?

**Comment by amaitland** [comment]
> Is the <CefSharpAnyCpuSupport> still supported in the .csproj files?

Yes

> Or do we need to change how we build and package the CefSharp libraries when upgrading to v88 in a solution which uses AnyCPU platform?

There are new options and some simplifications that are yet to be documented. **Upgrading** users shouldn't need to make any changes to their project file or code.

**Comment by amaitland** [comment]
> The specified module could not be found.' (see details here ) is related to differing Product version numbers on CefSharp.dll and 2 other files (version 88.2.90.0) and CefSharp.Core.Runtime.dll (version 88.2.90)

The difference in version number is safe to ignore. Whilst they might be slightly different this won't cause any problems as they are compiled with references to those version numbers. This has nothing to do with any problem you are seeing. 

>  It may be (also) related to the version numbers appearing on the NuGet Package manager - it is 88.2.9 for Cef.redist.x86 and 88.2.90 for CefSharp.Common and CefSharp.WinForms.

The version numbers for the packages are correct. 

There are working examples available at https://github.com/cefsharp/CefSharp.MinimalExample

@u-netanel Please use https://github.com/cefsharp/CefSharp/discussions/3436 to discuss the problem you are seeing. 

If there is a problem then I will update everyone here.

**Comment by ensign-nemo** [comment]
> I think the issue of runtime System.IO.FileNotFoundException: 'Could not load file or assembly 'CefSharp.Core.Runtime.dll' or one of its dependencies. The specified module could not be found.' (see details here ) is....
> snip
I get the message if I try to run a 'minimal' application on a Win10 machine which does not have VC++ 15 redistributable installed on it. I created a vanilla Win10 Azure VM and then just copied my app binary over to it, and get that result.

As an experiment, I copied VC++ binaries vcruntime140.dll, vcruntime140_1.dll and msvcp140.dll from my dev workstation's VC++ installation into the x64 subfolder and all now appears to work as expected (though with _very_ limited testing thus far).

**Comment by amaitland** [comment]
Version `87.1.132` added support for buildTransitive, the `.targets` and `.props` files will flow through to consuming projects when using `Nuget 5.0+` and `PackageReference` as detailed at https://github.com/NuGet/Home/wiki/Allow-package--authors-to-define-build-assets-transitive-behavior

[Controlling dependency assets](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets) details how you can control how assets are included/flow through to other projects.

For those targeting `AnyCPU` and now seeing your consuming projects display the error generated using the  [CefSharpPlatformCheck](https://github.com/cefsharp/CefSharp/blob/cefsharp/89/NuGet/CefSharp.Common.targets#L363) target you can add a [Directory.Build.props](
https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019#directorybuildprops-example) file which includes the `<CefSharpAnyCpuSupport/>` property.

> Prior to MSBuild version 15, if you wanted to provide a new, custom property to projects in your solution, you had to manually add a reference to that property to every project file in the solution. Or, you had to define the property in a .props file and then explicitly import the .props file in every project in the solution, among other things.

> However, now you can add a new property to every project in one step by defining it in a single file called Directory.Build.props in the root folder that contains your source. When MSBuild runs, Microsoft.Common.props searches your directory structure for the Directory.Build.props file (and Microsoft.Common.targets looks for Directory.Build.targets). If it finds one, it imports the property. Directory.Build.props is a user-defined file that provides customizations to projects under a directory.

Add `<CefSharpAnyCpuSupport>true</CefSharpAnyCpuSupport>` to your `Directory.Build.props` file to suppress this error on a solution wide basis. See [Search Scope](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019#search-scope) to determine where to put the `Directory.Build.props` file.

**Comment by amaitland** [comment]
> Version `87.1.132` added support for buildTransitive, the `.targets` and `.props` files will flow through to consuming projects when using `Nuget 5.0+` and `PackageReference` as detailed at https://github.com/NuGet/Home/wiki/Allow-package--authors-to-define-build-assets-transitive-behavior

For those wishing to revert to the pre 87 behaviour you can set `<CefSharpBuildAction/>` to `None` and change `PrivateAssets` of the `PackageReference` to disable `buildTransitive`. This will copy the files to a directly referencing project as prior to version `87`.

A `WinForms` example would look like the following (The same will work for `WPF/OffScreen` packages).

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <Platforms>x86</Platforms>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup>
    <CefSharpBuildAction>None</CefSharpBuildAction>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="CefSharp.WinForms" Version="89.0.170">
        <PrivateAssets>buildTransitive</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```

**Comment by Yahasana** [comment]
i don't know whether should i file a new bug. when i create new project with `CefSharp` name and just inject `ChromiumWebBrowser` for simplest test.
```xml
<PackageReference Include="CefSharp.WinForms.NETCore" Version="98.1.210" />
```

build it and run, then crash with nothing tips.

i think the reason should be that the output dll `CefSharp.dll` conflict with the one in `runtimes\win-x64\native\CefSharp.dll`.

when i change the project name to other name, it works like a charm

**Comment by amaitland** [comment]
> when i create new project with CefSharp

Please don't open a bug. You will need to give your project a unique name. This is not something I can fix.

**Comment by Xan-Kun** [comment]
Hello and thanks for the awesome library!
Sorry in advance if this isn't the right place to ask, I will delete/edit/move it gladly to a better place.

Does the above explained also include the file `libGLESv2.dll` or is that different somehow? Either way, it doesn't get put in a subfolder and just seems to 'resist' 😄 
I have great problems with that file (Memory Access Violations) when it is in the build-root, together with the app.

Thx again.
