### ISSUE TITLE
Click & mousedown events not working on WinForms

### ISSUE THREAD

**Issue by goodwin74** [cefsharp/CefSharp#3340]
WinForms \ VS2019 \ C# \ CefSharp 86

` ChromiumWebBrowser br= new ChromiumWebBrowser("");
            br.Click += (obj, ev) =>
            {
                Console.WriteLine("test");
            };`

This code does not respond to a click. If you use MouseDown, nothing happens either.
How is it possible to track the click on the ChromiumWebBrowser control?

**Comment by amaitland** [comment]
This is expected as chromium swallows all mouse/touch/keyboard events. 

You can hook the low level hwnd to get the raw events. 

https://github.com/cefsharp/CefSharp/issues/1098
https://github.com/cefsharp/CefSharp/issues/1269

Closing as there is nothing actionable.

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/blob/cefsharp/86/CefSharp.WinForms.Example/BrowserTabUserControl.cs#L308 for example in the project source.
