### ISSUE TITLE
System.IO.FileNotFoundException HResult=0x80070002 Message=Could not load file or assembly 'System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. 系统找不到指定的文件。 Source=CefSharp.Core StackTrace: at CefSharp.ManagedCefBrowserAdapter.InitializeBrowserProcessServiceHost(IBrowser browser) at CefSharp.ManagedCefBrowserAdapter.OnAfterBrowserCreated(IBrowser browser) at CefSharp.Internals.ClientAdapter.OnAfterCreated(ClientAdapter* , scoped_refptr<CefBrowser>* browser)

### ISSUE THREAD

**Issue by zhw19930811** [cefsharp/CefSharp#3347]
I get  a .net core 3.1 projetct ,when i use cefsharp86.0.241, it have exception handling 
it is my code :
cefsharp.Address = @"http://localhost:8082/"; //网址
            CefSharpSettings.LegacyJavascriptBindingEnabled = true;
            CefSharpSettings.WcfEnabled = true;
            cefsharp.JavascriptObjectRepository.Register("JsObj", new CallbackObjectForJs(), isAsync: false,options: BindingOptions.DefaultBinder);

please help me , thanks

**Comment by amaitland** [comment]
You can only use Async JavaScript Binding implementation in .Net Core. The older synchronous version uses WCF which isn't included in .Net Core.

This is a known limitation. The isAsync parameter has been removed from the .Net Core implementation which the first -pre release is now available. 

https://www.nuget.org/packages?q=Cefsharp+netcore
