### ISSUE TITLE
problem with user agent

### ISSUE THREAD

**Issue by KairoMartins18** [cefsharp/CefSharp#3348]
I performed some procedures for the user agent to work. more when I enter the website (What is my browser) it returns Chrome 86

#code

  public partial class Form1 : Form
    {
        ChromiumWebBrowser chromiumBrowser;
        public Form1()
        {
            InitializeComponent();

            CefSettings settings = new CefSettings();

            settings.UserAgent = "Mozilla/5.0 (SMART-TV; Linux; Tizen 2.4.0) AppleWebkit/538.1 (KHTML, like Gecko) SamsungBrowser/1.1 TV Safari/538.1";

            chromiumBrowser = new CefSharp.WinForms.ChromiumWebBrowser("https://www.whatsmybrowser.org/")
            {
                Dock = DockStyle.Fill,

            };
            panel2.Controls.Add(chromiumBrowser);
        }

**Comment by amaitland** [comment]
You have to call [Cef.Initialize](http://cefsharp.github.io/api/86.0.x/html/Overload_CefSharp_Cef_Initialize.htm) passing in your CefSettings instance.

See https://github.com/cefsharp/CefSharp/wiki/General-Usage#initialize-and-shutdown for an example. 

---

In future please use the discussions section to ask questions. 

https://github.com/cefsharp/CefSharp/discussions

**Comment by amaitland** [comment]
I've updated https://github.com/cefsharp/CefSharp/wiki/General-Usage#useragent to include more detailed examples.

**Comment by KairoMartins18** [comment]
error when initializing CEF. (WPF)

**Comment by KairoMartins18** [comment]
when debugging the application there, pf generates an exception here Cef.Initialize (settings);

**Comment by KairoMartins18** [comment]
**error!!** CEF can only be initialized once per process. This is a limitation of the underlying CEF/Chromium framework. You can change many (not all) settings at runtime through RequestContext.SetPreference. See https://github.com/cefsharp/CefSharp/wiki/General-Usage#request-context-browser-isolation
