### ISSUE TITLE
Chrome ignoring CSS font-weight property

### ISSUE THREAD

**Issue by Swamy571** [cefsharp/CefSharp#3383]
I am using font-family 'Proxima Nova'. Chrome seems to be using `font-weight: lighter`; as default?, 

I am using 'font-weight: normal' and 'color: black' for a grid, but text in the column still looks like not full black color. It showing lighter color, but I want full black color.

@font-face {
  font-family: 'ProximaNova-Regular';
  src: url("fonts/ProximaNova-Regular.eot?#iefix") format("embedded-opentype"), url("fonts/ProximaNova-Regular.woff") format("woff"), url("fonts/ProximaNova-Regular.ttf") format("truetype");
  font-weight: normal;
  font-style: normal;
}

.k-grid{
    color: black !important;
    border-width: 0px;
    font-family: 'ProximaNova-Regular' !important;
  }

![image](https://user-images.githubusercontent.com/78414794/106593952-71d17c80-6577-11eb-9b9c-830172bd0511.png)

**Comment by arcanisgk** [comment]
i think you have the blurry problem: 

Cef.EnableHighDPISupport();
