### ISSUE TITLE
Every project with transitive reference to CefSharp now needs CefSharpAnyCpuSupport property set.

### ISSUE THREAD

**Issue by deonberlin** [cefsharp/CefSharp#3390]
- **What version of the product are you using?**
    Using Nuget version 87.1.132

- **What architecture x86 or x64?**
    AnyCPU
    
- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WPF/OffScreen
    
- **What steps will reproduce the problem?**
I have the following project structure (all projects using the new SDK project style):
_Project UI_ ---> references _Project Browser_ --> references CefSharp packages (OffScreen and WPF)
Both projects have CefSharpAnyCpuSupport set to true
_Project UI Extensions_ ---> references _Project UI_ ---> transitive reference to CefSharp
Project has not set CefSharpAnyCpuSupport

When building, the TransformXML task in CefSharpCommonAnyCPUConfigTransform target raises errors about missing source parameter for all projects which have not set CefSharpAnyCpuSupport and target AnyCPU with a transitive reference to CepSharp.

- **What is the expected output? What do you see instead?**
I would have expected that the build raises no errors, like it was in versions before 87.

Currently my workaround is to set the CefSharpAnyCpuSupport property in Directory.Build.props for the whole solution.

**Comment by amaitland** [comment]
PackageReference assets are controllable on a per package basis. See https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets

Specifically via setting privateAssets in this instance. 

> I would have expected that the build raises no errors, like it was in versions before 87.

If I remove the targets file from the buildTransative folder then there's no way to have it as transitive. If I leave it as is then transitive references should work properly and the user can configure the behaviour.

I'm not aware of a way to tell if the targets file is being used as a transitive reference and adjust the check,  I did look. If you can find a way a PR would be most welcomed. The error message can be improved to include details of how to control assets.

**Comment by amaitland** [comment]
Additionally if you create a CefSharpBuildAction property in your project file and set the value to None (case  sensitive) and tweaking the assets you should hopefully get a similar behaviour.

**Comment by deonberlin** [comment]
Okay, the actual problem was, that the libraries with transitive references did not had an app.config file, so the Source for the target was empty. It could be resolved by adding an additional condition to the build target which checks if ther was an App config file copied by checking '@(AppConfigWithTargetPath).

`<Target Name="CefSharpCommonAnyCPUConfigTransform" AfterTargets="_CopyAppConfigFile" Condition="Exists('$(CefSharpTransformXmlDllPath)') AND '$(PlatformTarget)' == 'AnyCPU' AND '$(CefSharpAnyCpuSupport)' == '' AND '@(AppConfigWithTargetPath)' != ''">`

Should I create a PR for that or could you simply add that by yourself.

**Comment by deonberlin** [comment]
Actually I've discovered another problem when `CefSharpAnyCpuSupport` is set to true, it actually breaks AnyCPU support, because in that case the binding redirects to `CefSharp.Core.Runtime.dll` are not added to the app.config and result in a FileNotFoundException.

If `CefSharpAnyCpuSupport` is removed, AnyCPU works out of the box without any manual dependency resolving. That was the intention, right? So the reference to assembly resolving in https://github.com/cefsharp/CefSharp/issues/1714 seams obsolete.

The `CefSharp.Common.targets` should be adjusted accordingly, to properly create the binding redirects for the AnyCPU build like this.

    <UsingTask TaskName="TransformXml" AssemblyFile="$(CefSharpTransformXmlDllPath)" Condition="Exists('$(CefSharpTransformXmlDllPath)') AND '$(PlatformTarget)' == 'AnyCPU' AND '$(CefSharpAnyCpuSupport)' == 'true'" />
    
    <Target Name="CefSharpCommonAnyCPUConfigTransform" AfterTargets="_CopyAppConfigFile" Condition="Exists('$(CefSharpTransformXmlDllPath)') AND '$(PlatformTarget)' == 'AnyCPU' AND '$(CefSharpAnyCpuSupport)' == 'true' AND '@(AppConfigWithTargetPath)' != ''">
  	<TransformXml Source="@(AppConfigWithTargetPath->'$(OutDir)%(TargetPath)')" Transform="$(MSBuildThisFileDirectory)..\build\app.config.x86.transform" Destination="@(AppConfigWithTargetPath->'$(OutDir)%(TargetPath)')"/>
      <TransformXml Source="@(AppConfigWithTargetPath->'$(OutDir)%(TargetPath)')" Transform="$(MSBuildThisFileDirectory)..\build\app.config.x64.transform" Destination="@(AppConfigWithTargetPath->'$(OutDir)%(TargetPath)')"/>
    </Target>

**Comment by amaitland** [comment]
> Okay, the actual problem was, that the libraries with transitive references did not had an app.config file

Thanks,  that's a bug and we should fix that. If you have time a PR would be welcome.

> Actually I've discovered another problem when CefSharpAnyCpuSupport is set to true, it actually breaks AnyCPU support, because in that case the binding redirects to CefSharp.Core.Runtime.dll are not added to the app.config and result in a FileNotFoundException.

The intention is that the transformation is applied when CefSharpAnyCpuSupport is not set. For upgrading users that already have an AnyCpu solution in place there should be no transformation applied.

> If CefSharpAnyCpuSupport is removed, AnyCPU works out of the box without any manual dependency resolving. Getting rid of the "manual" dependeny resolving was the intention, right? So the reference to assembly resolving in #1714 seams obsolete.

The reference to #1714 is a fallback, the issue needs to be updated which I'll do at some point in the future. For cases like you just pointed out a manual approach would be required. 

> The CefSharp.Common.targets should be adjusted accordingly, to properly create the binding redirects for the AnyCPU build like this if CefSharpAnyCpuSupport is set true.

That would likely cause problems for upgrading users.

In your case setting buildTransative as a private asset and applying CefSharpBuildAction will hopefully resolve the problem.

There are a huge number of variables to account for here and it will take a little while to get all the edge cases.
