### ISSUE TITLE
WindowInfo default constructor does not work anymore in v87

### ISSUE THREAD

**Issue by Scalibq** [cefsharp/CefSharp#3399]
In CefSharp versions 86 and lower, I would create my own WindowInfo, and set SharedTextureEnabled to enable acceleration, before passing it to CreateBrowser(), like so:
WindowInfo windowInfo = new WindowInfo();

In CefSharp 87, the constructor is still accessible, but it no longer works correctly, as there is no specific implementation of it.
Due to the refactoring that was done in this version, WindowInfo is no longer a subclass of CefSharp.Core.WindowInfo. Instead, it wraps around an internal instance of a CefSharp.Core.WindowInfo object, which it stores in its windowInfo private member.
As such, the correct way to instantiate a valid WindowInfo object is now:
IWindowInfo windowInfo = WindowInfo.Create();

Since the old code still compiles, but the resulting browser is not instantiated correctly, it is rather difficult to track down this bug.
My suggestion is to either make the WindowInfo() construction private, so the code fails to compile, or to explicitly make it call WindowInfo.Create() to instantiate its private windowInfo member, so the code will work as it did in versiosn 86 and below.

**Comment by amaitland** [comment]
In future please use the bug report temple. https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report

> explicitly make it call WindowInfo.Create() to instantiate its private windowInfo member, so the code will work as it did in versiosn 86 and below.

They're functionally the same thing. That wouldn't change anything. 

I'm hoping to avoid the breaking change if possible. Please provide a code example that demos the .

**Comment by Scalibq** [comment]
"They're functionally the same thing. That wouldn't change anything."

They aren't.
You have CefSharp.WindowInfo, which is the publicly accessible version, which can be instantiated by my code. You also have CefSharp.Core.WindowInfo, which is an internal class, which cannot be instantiated by my code. The CefSharp.WindowInfo.Create() method is a way to instantiate a CefSharp.Core.WindowInfo object, and expose it to the outside world, via the IWindowInfo interface.

However, if you do new CefSharp.WindowInfo(), you get an instance of CefSharp.WindowInfo where its private member of type CefSharp.Core.WindowInfo windowInfo is not set, and as such, the object fails when passed to CreateBrowser(windowInfo).

So code like this works in CefSharp 86 and below (I'm using the Offscreen version):
            WindowInfo windowInfo = new CefSharp.WindowInfo();
            windowInfo.SetAsWindowless(IntPtr.Zero);
            windowInfo.WindowlessRenderingEnabled = true;
            windowInfo.SharedTextureEnabled = accelerate;

            CreateBrowser(windowInfo, new BrowserSettings());

In CefSharp 87, it compiles, but CreateBrowser() silently fails, and it never renders any page or triggers any events.

Instead in CefSharp 87 the code should be:
            IWindowInfo windowInfo = WindowInfo.Create();
            windowInfo.SetAsWindowless(IntPtr.Zero);
            windowInfo.SharedTextureEnabled = accelerate;

            CreateBrowser(windowInfo, new BrowserSettings());

Or alternatively: IWindowInfo windowInfo = CefSharp.Core.ObjectFactory.CreateWindowInfo();

So the problem here is that the refactoring of CefSharp.WindowInfo made its WindowInfo() constructor no longer work.
Previously CefSharp.WindowInfo was a subclass of CefSharp.Core.WindowInfo, and as such the constructor would initialize it to a valid object, because its base class was implicitly constructed as well.
Now, CefSharp.WindowInfo is no longer a subclass of CefSharp.Core.WindowInfo, and instead it has a member variable that must be initialized.
So the behaviour of CefSharp.WindowInfo has changed, but it is not immediately apparent, because the default constructor is not explicitly blocked from use by eg making it private.

**Comment by amaitland** [comment]
> explicitly make it call WindowInfo.Create() to instantiate its private windowInfo member

Using `WindowInfo.Create()` to initialise `private CefSharp.Core.WindowInfo windowInfo` won't change anything. Your welcome to build the project from source and try it.

> In CefSharp 87, it compiles, but CreateBrowser() silently fails, a

You should be getting a type cast exception.

> So the behaviour of CefSharp.WindowInfo has changed, but it is not immediately apparent, because the default constructor is not explicitly blocked from use by eg making it private.

As I've said, it's intended to work as before. They were always going to be a few cases that I missed, so I added the `Create` methods as fallbacks until I got them all resolved. The target is to make `CefSharp.Core.Runtime.dll` a runtime only assembly, that is `CefSharp.Core` doesn't directly export any of the types that come from `CefSharp.Core.Runtime.dll`, hence the wrapper objects.

https://github.com/cefsharp/CefSharp/issues/3319#issuecomment-759214337 details the choices and the option I choose.

**Comment by amaitland** [comment]
Looks like the `static_cast` just sails on through even if it fails.

**Comment by Scalibq** [comment]
You're right, I initially overlooked this line:
private CefSharp.Core.WindowInfo windowInfo = new CefSharp.Core.WindowInfo();

So it should have initialized the member, even if there is no explicit implementation of the constructor.
Nevertheless, the problem is there: if I pass a CefSharp.WindowInfo to CreateBrowser(), then nothing happens (I do not get an exception either), but if I pass an IWindowInfo created with WindowInfo.Create(), it works.

**Comment by Scalibq** [comment]
You're right, I initially overlooked this line:
private CefSharp.Core.WindowInfo windowInfo = new CefSharp.Core.WindowInfo();

So it should have initialized the member, even if there is no explicit implementation of the constructor.
Nevertheless, the problem is there: if I pass a CefSharp.WindowInfo to CreateBrowser(), then nothing happens (I do not get an exception either), but if I pass an IWindowInfo created with WindowInfo.Create(), it works.

**Comment by amaitland** [comment]
This will be fixed in the next release. Subscribe to release only notifications here on GitHub to be notified when a new version is available.
