### ISSUE TITLE
Source Maps are not loaded when using custom schema

### ISSUE THREAD

**Issue by andrewzjl** [cefsharp/CefSharp#3408]
![image](https://user-images.githubusercontent.com/10008129/108154529-07f2c000-70ab-11eb-8192-e6b4a1e8a717.png)

- **What version of the product are you using?**
    - 86.0.24 from Nuget 
    - It also reproducible in the latest cef.WPF 87.1.132

- **What architecture x86 or x64?**
    - x64

- **On what operating system?**
    - Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - WPF

- **What steps will reproduce the problem?**
    -  Create a customized handler to load from local js file, which is implemented the interface `IResourceHandler`. Example like in https://stackoverflow.com/questions/35965912/cefsharp-custom-schemehandler
    - In RequestHandler method `GetResourceRequestHandler` return a customized `ResourceRequestHandler`
    - In the ResourceRequestHandler method `GetResourceHandler` return the customized `ResourceHandler`
    - Build the files with sourceMaps, e.g. xxx.js.map, or css files with xxx.css.map

- **What is the expected output? What do you see instead?**
    When load the DevTool, it should load all the map files well.
    It's no problem in cefsharp 73, but the warning shown in DevTool after upgraded to cef 86

- **Please provide any additional information below.**
    _- A stack trace if available, any Exception information._
        Only the sourceMaps are failed to load. The warning can be hide by this option.
        
![image](https://user-images.githubusercontent.com/10008129/108154742-746dbf00-70ab-11eb-8e88-1a2ba4677e23.png)

  _- Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)_
     Not found the log file
    _- Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?_
 It may be related to the issue of chromium https://bugs.chromium.org/p/chromium/issues/detail?id=1052872
 
- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
Not try
   <del> - To compare with WPF run cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu
    - To compare with WinForms run cefclient --multi-threaded-message-loop
    - If you can reproduce the problem with `cefclient` then you'll need to report the bug on https://bitbucket.org/chromiumembedded/cef/overview there is no point opening an issue here. (Make sure you search before opening an issue)
    - Please include the version you tested with e.g. `cef_binary_3.3029.1611.g44e39a8_windows64_client.tar.bz2`. It's important to you test with the same version that `CefSharp` is based on. Check the release notes to determine the version (https://github.com/cefsharp/CefSharp/releases) or load `chrome://version` in the browser. </del>

**Comment by amaitland** [comment]
I'd suggest testing using the https scheme and specifying a domain name when you register your scheme handler. I expect you'll get a name not resolved error as discussed at https://magpcss.org/ceforum/viewtopic.php?f=6&t=17910 I'd suggest asking there to see if an issue was ever created, either way it would appear to be CEF isn't hooked up for source map requests. 

I'm going to close this as upstream as fixes need to be made in CEF and probably chromium. There's nothing actionable from a CefSharp point of view.

**Comment by andrewzjl** [comment]
It's not related to the customized handler, but also in the https schema.
![image](https://user-images.githubusercontent.com/10008129/108237866-56897400-7116-11eb-8a19-a8d3ea5deaea.png)
What's more, it also happens in Chrome browser 88.0.4324.150 (Official Build) (64-bit).

**Comment by peitschie** [comment]
In case it's of any interest, I made this very rough implementation based on CefSharp's FolderSchemeHandlerFactory that inlines the external source map on access to the JS file.

I added this chunk of code just in here: https://github.com/cefsharp/CefSharp/blob/d0486b317967fe4a3eb00e783c26d93d2a00e594/CefSharp/SchemeHandler/FolderSchemeHandlerFactory.cs#L119

```csharp
        //Check the file requested is within the specified path and that the file exists
        if (filePath.StartsWith(rootFolder, StringComparison.OrdinalIgnoreCase) && File.Exists(filePath))
        {
            var fileExtension = Path.GetExtension(filePath);
            var mimeType = ResourceHandler.GetMimeType(fileExtension);

            // Begin customisation
            if (InlineSourceMaps && fileExtension == ".js")
            {
                var contents = File.ReadAllText(filePath);
                var sourceMappingUrl = $"//# sourceMappingURL={Path.GetFileName(filePath)}.map";
                var sourceMappingUrlIndex = contents.LastIndexOf(sourceMappingUrl);
                if (sourceMappingUrlIndex != -1 && File.Exists($"{filePath}.map"))
                {
                    var sourceMap = File.ReadAllBytes($"{filePath}.map");
                    var encodedSourceMap = Convert.ToBase64String(sourceMap);
                    contents = contents[..sourceMappingUrlIndex] + "//# sourceMappingURL=" + DataJsonUriPrefix + encodedSourceMap + "\n";
                    return ResourceHandler.FromString(contents, mimeType: mimeType);
                }
            }
            // End customisation

            var stream = new FileStream(filePath, FileMode.Open, FileAccess.Read, resourceFileShare);
            return ResourceHandler.FromStream(stream, mimeType, autoDisposeStream: true);
        }
```

My local directory structure I'm serving from has the .js and .js.map file living side-by-side. All this logic is doing is detecting the external sourcemap url, and converting it to an embedded sourcemap on read.

This allows me to enable this feature only on special debug builds.
