### ISSUE TITLE
Cannot copy text to clipboard in Google Translate using the new version.

### ISSUE THREAD

**Issue by houssam11350** [cefsharp/CefSharp#3410]
Hallo; 
Cannot copy text to clipboard in Google Translate using the new version.
in the old version (May be 69); copying works perfectly.
NOTE : The same project, with same settings;
I have enabled JS:

```
BrowserSettings browserSettings = new BrowserSettings();
browserSettings.Javascript = CefState.Enabled;
browserSettings.JavascriptAccessClipboard = CefState.Enabled;
browser.BrowserSettings = browserSettings;
```
Problem is here:
![err01](https://user-images.githubusercontent.com/19496167/108632222-13a90280-746e-11eb-8ab1-b6ea3d68f164.png)
OK:
![err02](https://user-images.githubusercontent.com/19496167/108632224-14419900-746e-11eb-9291-3b2c99e91c35.png)

Used in:
[MyOnlineDict on Github](https://github.com/houssam11350/MyOnlineDict)

**Comment by amaitland** [comment]
Please fill out the bug report see https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report

Make sure you test with the CEF Sample application.

**Comment by houssam11350** [comment]
- What version of the product are you using?
   88.2.40-pre from Nuget / 
- What architecture x86 or x64? 
  OS: Windows 10 x64 ; the project is compiled to: x86
- On what operating system? 
  Win10
- Are you using WinForms, WPF or OffScreen?
  WinForms
- What steps will reproduce the problem?
  Simply, run the minimal example; open google translator : [Example](https://translate.google.com/?sl=de&tl=ar&text=belassen&op=translate) ; click on the button (copy) [As described in the above attached image](https://user-images.githubusercontent.com/19496167/108632222-13a90280-746e-11eb-8ab1-b6ea3d68f164.png); the text cannot be copied.
I have tried to enable Javascriot Clipboard;

```
BrowserSettings browserSettings = new BrowserSettings();
browserSettings.Javascript = CefState.Enabled;
browserSettings.JavascriptAccessClipboard = CefState.Enabled;
browser.BrowserSettings = browserSettings;
```
also; does not work.
- What is the expected output? What do you see instead?
  Expected: When I click on the button (copy) in google translator; the text should be copied as in previous versions [Screenshot](https://user-images.githubusercontent.com/19496167/108632224-14419900-746e-11eb-9291-3b2c99e91c35.png)
  What Seen: text cannot be copied as shown in the attached image [Screenshot](https://user-images.githubusercontent.com/19496167/108632222-13a90280-746e-11eb-8ab1-b6ea3d68f164.png)
- Please provide any additional information below.
  I see an error message in the status bar.
![err03](https://user-images.githubusercontent.com/19496167/108637113-6ba13280-7489-11eb-857b-f068474c31ae.png)
- Does this problem also occur in the CEF Sample Application
 YES

**Comment by amaitland** [comment]
Thanks for confirming, this will need to be fixed in CEF as it reproduces with the CEF Sample application. The CEF issue tracker is at https://bitbucket.org/chromiumembedded/cef/issues?status=new&status=open

When you open an issue please post a link back here for reference. 

Closing as upstream,  this issue can be reopened if code changes are required.

**Comment by amaitland** [comment]
It's possible this is related to https://bitbucket.org/chromiumembedded/cef/issues/2921/add-support-for-asynchronous-clipboard-api

**Comment by houssam11350** [comment]
[An Issue is open](https://bitbucket.org/chromiumembedded/cef/issues/3093/cannot-copy-text-to-clipboard-in-google)

**Comment by houssam11350** [comment]
SOLVED, by restarting the PC.
may be it is a problem with cache !!!
