### ISSUE TITLE
Different build output for v87 and v88 packages in WinForms AnyCPU project

### ISSUE THREAD

**Issue by jozefizso** [cefsharp/CefSharp#3428]
---
### Bug Report
Delete this line and everything above, and then fill in the details below.

- **What version of the product are you using?**
    - NuGet releases
	- CefSharp.WinForms **v87.1.132** upgraded to **v88.2.90**

- **What architecture x86 or x64?**
    The project targets AnyCPU platform.
	
- **What version of .Net?**
    .NET 4.8
    
- **On what operating system?**
    Windows 10 20H2

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WinForms
    
- **What steps will reproduce the problem?**
    - Create simple WinForms project in Visual Studio 2019
    - Add reference to CefSharp.WinForms **v87.1.132** using NuGet package manager
    - Build the project
    - Observe the build output - the **v87** will automatically create the `x86` and `x64` folders with respective CefSharp libraries.
    - I think this is the correct behavior here as v87 changed the structure of packages #3319. This sample project does not use the `<CefSharpAnyCpuSupport>true</CefSharpAnyCpuSupport>` project in .csproj file.
    - Upgrade the project to use CefSharp.WinForms **v88.2.90**
    - Rebuild the project
    - Observe the build output - the **v88** will copy only CefSharp 32-bit libraries to the default output folder for the project. It will not create the `x86` nor `x64` directories.

- **What is the expected output? What do you see instead?**
    I think the **v88.2.90** should preserve the behavior of **v87** packages for the AnyCPU solutions.

- **Please provide any additional information below.**
    - Sample project: https://github.com/jozefizso/CefSharp-MyApp-3428
    - Here is a gist with build output structure: https://gist.github.com/jozefizso/c5e28b078680ca29ebb9d6e0cbed37b4

#### CefSharpAfterBuildDiagnostic from CefSharp.WinForms **v87.1.132**
```
1>  MyApp -> C:\Users\jozef\source\repos\MyApp\bin\Debug\MyApp.exe
1>  CefSharp After Build Diagnostic
1>  CefSharpBuildAction = None
1>  CefSharpTargetDir = 
1>  CefSharpTargetDirAnyCpu32 = x86\
1>  CefSharpTargetDirAnyCpu64 = x64\
1>  RuntimeIdentifier = 
1>  TargetFramework = AnyCPU
1>  libcef.dll exists AnyCPU(x86) = bin\Debug\x86\libcef.dll
1>  libcef.dll exists AnyCPU(x64) = bin\Debug\x64\libcef.dll
1>  CefSharpTransformXmlDllPath = C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\Web\Microsoft.Web.Publishing.Tasks.dll
1>  NuGetProjectStyle = 
1>  OutDir = bin\Debug\
```

#### CefSharpAfterBuildDiagnostic from CefSharp.WinForms **v88.2.90**
```
1>------ Build started: Project: MyApp, Configuration: Debug Any CPU ------
1>  MyApp -> C:\Users\jozef\source\repos\MyApp\bin\Debug\MyApp.exe
1>  CefSharp After Build Diagnostic
1>  CefSharpBuildAction = None
1>  CefSharpTargetDir = 
1>  CefSharpTargetDirAnyCpu32 = x86\
1>  CefSharpTargetDirAnyCpu64 = x64\
1>  RuntimeIdentifier = 
1>  Platform = AnyCPU
1>  PlatformName = AnyCPU
1>  Platforms = 
1>  PlatformTarget = AnyCPU
1>  CefSharpPlatformTarget = x86
1>  PlatformTargetAsMSBuildArchitecture = x86
1>  TargetFramework = 
1>  TargetFrameworkVersion = v4.8
1>  libcef.dll exists = bin\Debug\libcef.dll
1>  CefSharpTransformXmlDllPath = C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\Web\Microsoft.Web.Publishing.Tasks.dll
1>  NuGetProjectStyle = 
1>  OutDir = bin\Debug\
```

- Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
  There is no debug.log in the bin folder.

- Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
  I'm trying to figure out why our app suddenly builds differently after upgrade to v88 and how to configure our projects to have the behavior from v86 and v87.
      

- **Does this problem also occur in the `CEF` Sample Application**
    N/A

**Comment by amaitland** [comment]
> Observe the build output - the v88 will copy only CefSharp 32-bit libraries to the default output folder for the project. It will not create the x86 nor x64 directories.

This is expected as the default project created by visual studio comes with Prefer32Bit set by default which is actually a x86 build. Remove this flag and the arch specific folders will be created. 

If you set CefSharpAnyCpuSupport true then you should get the old behaviour for backwards compatibility. 

This is an intentional change.

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/blob/cefsharp/88/NuGet/CefSharp.Common.targets#L104

Only if Prefer32Bit is true will the default to x86. Which I believe is the default for new projects. 

This greatly simplifies getting started for new users.

**Comment by jozefizso** [comment]
Thanks a lot for the explanation. Yes, removing the Prefer32Bit in the sample project does change the behavior and both `x86` and `x64` subfolders are created.
