### ISSUE TITLE
ManagedCefBrowserAdapter::InitializeBrowserProcessServiceHost - System.ObjectDisposedException: Cannot access a disposed object.

### ISSUE THREAD

**Issue by prat-coder** [cefsharp/CefSharp#3437]
Bug:

- **What version of the product are you using?**
      85.3.121.0
- **What architecture x86 or x64?**
    x86
	
- **What version of .Net?**
    .NET framework 4.6.2
    
- **On what operating system?**
   Windows 10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WPF
    
- **What steps will reproduce the problem?**
    Its probably happening due to quick close and open of the browser within short time.  There have been issues reported previously around BrowserProcessServiceHost constructor previously  also due to timing and memory corruption issues. GetIdentifier on the browser object fails in this case.
    - Does the problem reproduce using the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample)? No
    

- **What is the expected output? What do you see instead?**
Expected output is browser shouldnt crash with an unhandled exception. Currently ObjectDisposedException is being thrown.
- **Please provide any additional information below.**
   Callstack as below:
    **System.ObjectDisposedException: Cannot access a disposed object.**
Object name: 'This instance of CefSharp.IBrowser been disposed!'.
  Module "CefSharp.Internals.CefWrapper", in ThrowIfDisposed
  Module "CefSharp.Internals.CefBrowserWrapper", in get_Identifier
  Module "CefSharp.ManagedCefBrowserAdapter", in InitializeBrowserProcessServiceHost
  Module "CefSharp.ManagedCefBrowserAdapter", in OnAfterBrowserCreated
  Module "(unknown)", in CefSharp.Internals.ClientAdapter.OnAfterCreated

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
      WPF desktop application which uses cef browser. 
- **Does this problem also occur in the `CEF` Sample Application**
      No

**Comment by hdanzl** [comment]
@amaitland, we're running into WCF problems at a customer site where security policies restrict inter-process communication using named pipes. The "ignore all" exception handler masks this from the logs and it's very difficult to understand what's going on.

Would it be possibe to change this to something like:

`            //As the default the browser is Disposed on a different thread to this method it's possible that
            //we arrive here after browser has started Disposing. In that case there's likely to be an exception
            //accessing the Browser and possibly the serviceHost.
            //https://github.com/cefsharp/CefSharp/issues/3437
            try
            {
                _browserProcessServiceHost = gcnew BrowserProcessServiceHost(_javaScriptObjectRepository, Process::GetCurrentProcess()->Id, browser->Identifier, _javascriptCallbackFactory);
                //NOTE: Attempt to solve timing issue where browser is opened and rapidly disposed. In some cases a call to Open throws
                // an exception about the process already being closed. Two relevant issues are #862 and #804.
                if (_browserProcessServiceHost->State == CommunicationState::Created)
                {
                    auto serviceName = RenderprocessClientFactory::GetServiceName(Process::GetCurrentProcess()->Id, browser->Identifier);
                    std::string log = "BrowserProcessServiceHost: Create channel " + msclr::interop::marshal_as<std::string>(serviceName);
                    LOG(INFO) << log;

                    _browserProcessServiceHost->Open();
                    LOG(INFO) << "BrowserProcessServiceHost: Successfully created channel";
                }
            }
            catch (System::ObjectDisposedException^ ex)
            {
                std::string error = "BrowserProcessServiceHost: refer to https://github.com/cefsharp/CefSharp/issues/3437 \n" + msclr::interop::marshal_as<std::string>(ex->ToString());
                LOG(ERROR) << error;
            }
            catch (Exception^ ex)
            {
                std::string error = "BrowserProcessServiceHost: " + msclr::interop::marshal_as<std::string>(ex->ToString());
                LOG(ERROR) << error;
            }`

There is a similar ignore-all catch in void WcfEnabledSubProcess::OnBrowserCreated which I'd suggest to change to:

`            auto browserProcess = channelFactory->CreateChannel();
            auto clientChannel = ((IClientChannel^)browserProcess);

            try
            {
                std::string log = "WcfEnabledSubProcess: Connect to channel " + msclr::interop::marshal_as<std::string>(serviceName);
                LOG(INFO) << log;
                clientChannel->Open();
                LOG(INFO) << "WcfEnabledSubProcess: successfully connected";

                browser->ChannelFactory = channelFactory;
                browser->BrowserProcess = browserProcess;
            }
            catch (Exception^ ex)
            {
                std::string error = "WcfEnabledSubProcess: " + msclr::interop::marshal_as<std::string>(ex->ToString());
                LOG(ERROR) << error;
            }`

**Comment by amaitland** [comment]
Happy to accept changes in the form of a Pull Request 👍
