### ISSUE TITLE
Error when trying to stop load

### ISSUE THREAD

**Issue by marianrs89** [cefsharp/CefSharp#3445]
Hi,

Visual studio crashes when I use e.Browser.StopLoad() in LoadingStateChanged to cancel the navigation.

**Comment by amaitland** [comment]
Please fill out the bug report using the template provided at https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report

**Comment by marianrs89** [comment]
**What version of the product are you using?**

87.1.132 from nuget package

**What architecture x86 or x64?** x86

**What version of .Net?** .Net 4.5.2

**On what operating system?** Win10

**Are you using WinForms, WPF or OffScreen?** WinForms

**What steps will reproduce the problem?**

I have browser into a control and I use LoadingStateChanged to control if website IsLoading or not, to change the cursor. While website is loading, I need to check if the website is permitted or not, to cancel navigation. I use e.Browser.StopLoad() if I have to cancel navigation but Visual studio crashes.


`  private void _chromeBrowser_LoadingStateChanged(object sender, CefSharp.LoadingStateChangedEventArgs e)
        {
            if (e.IsLoading)
            {
                _current = Cursor;
                this.Invoke((Action)(() => {
                    Application.UseWaitCursor = true;
                    Application.DoEvents();
                }));
                switch (navigationType)
                {
                    case (RestrictionTypes.RestrictToOnePage):
                        if (_url.Length > 0 && (e.Browser.MainFrame.Url.ToString() != _url))
                        {
                            **e.Browser.StopLoad();**
                        }
                        break;

                    case (RestrictionTypes.Free):
                        break;
                }

            }
            else
            {
                this.Invoke((Action)(() => {
                    Application.UseWaitCursor = false;
                    Application.DoEvents();
                }));

            }
        }
`
**What is the expected output? What do you see instead?** Cancel navigation and show blank page.

**Please provide any additional information below.**

I don't have any exception, only visual studio closes.


**Does this problem also occur in the CEF Sample Application**
No.

**Comment by amaitland** [comment]
Does the problem reproduce with version 88.2.90?

This is more than likely a bug in CEF and unlikely something that can be fixed directly  in CefSharp. 

> Does this problem also occur in the CEF Sample Application
> No.

Did you actually test with the CEF Sample application? Changes to the code would be required for a meaningful test.

**Comment by marianrs89** [comment]
Yes, I have the same problem with the version 88.2.90.

I can't test this part with sample application.

**Comment by amaitland** [comment]
The preferred approach for canceling navigation is to use OnBeforeBrowse. Basically the pattern outlined in https://github.com/cefsharp/CefSharp/wiki/General-Usage#protocol-execution

If your url matches then return true to cancel, otherwise return false.

**Comment by amaitland** [comment]
The problem reproduces with `cefclient` when adding a call to `StopLoad` into the `ClientHandler::OnLoadingStateChange`

```c++
void ClientHandler::OnLoadingStateChange(CefRefPtr<CefBrowser> browser,
                                         bool isLoading,
                                         bool canGoBack,
                                         bool canGoForward) {
  CEF_REQUIRE_UI_THREAD();

  if (!isLoading && initial_navigation_) {
    initial_navigation_ = false;
  }

  if (isLoading)
  {
      browser->StopLoad();
  }

  NotifyLoadingState(isLoading, canGoBack, canGoForward);
}
```

Closing as `upstream` as the issues reproduces with `cefclient`. You'll need to report the problem on https://bitbucket.org/chromiumembedded/cef/issues?status=new&status=open (post a link back here for reference).

If code changes are required this issue can be reopened.

See https://gist.github.com/amaitland/14a926e0545cf544ef41fe3baa4ad7f3 for a basic example of the approach I'd reccommend for blocking websites from loading based on Url.
