### ISSUE TITLE
WPF  - ChromiumWebBrowserWithTouchSupport is stuck when fullscreen 

### ISSUE THREAD

**Issue by zhanghaigang666** [cefsharp/CefSharp#3459]
An application built on wpf, using the ChromiumWebBrowserWithTouchSupport class, found that when the size of the window is full of the full screen (1920*1080 resolution), the operation of the web page will be very stuck, if you reduce the resolution of the window, the stuck will be alleviated, but I For applications that require full screen, is there any way to optimize the performance experience like the browser?

**Comment by amaitland** [comment]
Please fill out the bug report temple available at https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report

**Comment by zhanghaigang666** [comment]
dll version : cefsharp 88.2.4
architecture :x86
.net version: 4.6.2
os: win10
WPF  UI

**Comment by amaitland** [comment]
Please use the bug report temple. Stuck doesn't clearly define the behaviour you are seeing,  you haven't provided an example that reproduces the problem.

**Comment by zhanghaigang666** [comment]
[CefSharpTest0327.zip](https://github.com/cefsharp/CefSharp/files/6215402/CefSharpTest0327.zip)
   This is a demo I made,
   We found that the more pre-loaded url links,the FPS frame rate of each linked page will drop quickly and become very stuck,
but the same number of url links are pre-loaded in the google chrome browser,and each link page is opened to find the FPS The frame rate can basically be maintained to 60PFS

**Comment by amaitland** [comment]
Performance of the WPF implementation is always going to be slower than chromium, it's a limitation of it's design. See https://github.com/cefsharp/CefSharp/wiki/General-Usage#offscreen-rendering-osr for background. See also #2275, WPF doesn't by default render at high speed.

You can use https://github.com/cefsharp/CefSharp.Wpf.HwndHost for a drop in replacement for the WPF control. 

I'm going to close this as there doesn't appear to be anything actionable.

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/issues/2275#issuecomment-609536970 for details on one of the other rendering implentations which may yield different performance characteristics. 

Ultimately if you need chromium like performance then you'll need to use https://github.com/cefsharp/CefSharp.Wpf.HwndHost or use the WinForms version with a WindowsFormsHost.
