### ISSUE TITLE
WPF - Browser flickers / blinks when window is resized via bound object

### ISSUE THREAD

**Issue by CedricInfeeny** [cefsharp/CefSharp#3466]
Hello,

What version of the product are you using?
Since Nuget 81.3.100 (not reproducible on 79.1.360)

What architecture x86 or x64?
x64

On what operating system?
Win 7 and Win10

Are you using WinForms, WPF or OffScreen?
WPF

What steps will reproduce the problem?
Use ChromiumWebBrowser pointing to custom site and which uses in Javascript a function allowing the enlargement of the WPF window (Javacript call C# functions)
On the click of the button of the HTML page contained in ChromiumWebBrowser carrying out an enlargement of the window, a flickering, blinking appears from the browser (see video attached : [exemple_video.zip](https://github.com/cefsharp/CefSharp/files/6248724/exemple_video.zip)).

Code snippet JS:

            _webBrowser.JavascriptObjectRepository.Settings.LegacyBindingEnabled = true;

            _webBrowser.JavascriptObjectRepository.ResolveObject += (s, e) =>
            {
                if (e.ObjectName == JavascriptObjectRepository.LegacyObjects)
                {
                    //ADD YOUR LEGACY                    
                    e.ObjectRepository.Register("containerObjectForJs", new ContainerObjectForJs(), isAsync: true);
                }
            };

Code snippet C# (ContainerObjectForJs.cs)

        public void callCSharpContainerCustomAction(string action, string direction, string pixels)
        {
            _log.Debug(action + " " + direction + " " + pixels);

            Application.Current.Dispatcher.Invoke(new Action(() =>
            {
                try
                {
                    WithoutAppBar main = (WithoutAppBar)Application.Current.MainWindow;
                    main.ResizeContainerCustom((Enums.TypeAction)Enum.Parse(typeof(Enums.TypeAction), action),
                                            (Enums.TypeDirection)Enum.Parse(typeof(Enums.TypeDirection), direction),
                                            int.Parse(pixels));
                }
                catch (Exception ex)
                {
                    throw ex;
                }
            }));
        }

ResizeContainerCustom changes the Top, Left, Width, and Height properties of the WPF window.

Code snippet Html page :
button onclick="(window.containerObjectForJs || window.external).callCSharpContainerCustomAction('expand', 'top', '30')">Expand top</button>

Thanks for your help.

Cedric

**Comment by amaitland** [comment]
Does the problem reproduce if you resize the window from a WPF button click.

> ResizeContainerCustom changes the Top, Left, Width, and Height properties of the WPF window.

Please update your code so the example is self contained. Rather than describing the code, please update your example to resize the window directly. 

Calling invoke and blocking the calling thread is not recommend, use BeginInvoke instead.

**Comment by CedricInfeeny** [comment]
The problem NOT reproduce with WPF button click, but my need is though that this is the website that interacts with the WPF container.

I will prepare a stand-alone example.

I fixed Invoke by BeginInvoke.

I added a video (exemple_video.zip) on the ticket.

**Comment by CedricInfeeny** [comment]
Here is my application: [FULL_EXAMPLE.zip](https://github.com/cefsharp/CefSharp/files/6248787/FULL_EXAMPLE.zip)
Contains:
- testsbandeau.html : test page html (to expose in a web server like IIS)
- WebBrowserContainer.zip : C# source WPF application
- CommandArgsLaunchExe.txt : command args to launch executable

**Comment by amaitland** [comment]
> Please no binary attachments (zip, 7z, etc), code needs to be easily reviewed in a web browser.

As per https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report 

- If code is required to reproduce your problem then please provide one of the following
      - Fork the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) and push your changes to `GitHub` (this is the preferred option).
      - Use a code sharing service list `Gist` or `Pastebin`
      - Paste your **formatted code as part of this issue** (only do this for small amounts of code and make sure you **format the code so it's readable**)
      - Please no binary attachments (zip, 7z, etc), code needs to be easily reviewed in a web browser.

In this case a fork of the minimal example would be preferable.

**Comment by CedricInfeeny** [comment]
Since project CefSharp.MinimalExample.Wpf :
- add class ContainerObjectForJs :
namespace CefSharp.MinimalExample.Wpf.Issue3466
{
    public class ContainerObjectForJs
    {        
        public ContainerObjectForJs()
        {
        }    

        /// <summary>
        /// 
        /// </summary>
        /// <param name="action"></param>
        /// <param name="direction"></param>
        /// <param name="pixels"></param>
        public void callCSharpContainerCustomAction()
        {
            Application.Current.Dispatcher.BeginInvoke(new Action(() =>
            {
                try
                {
                    MainWindow main = (MainWindow)Application.Current.MainWindow;
                    main.ResizeContainerCustom();
                }
                catch (Exception ex)
                {
                    throw ex;
                }
            }));
        }
    }
}

- modify class MainWindow.xaml.cs :
public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();

            Browser.JavascriptObjectRepository.Settings.LegacyBindingEnabled = true;

            Browser.JavascriptObjectRepository.ResolveObject += (s, e) =>
            {
                if (e.ObjectName == JavascriptObjectRepository.LegacyObjects)
                {
                    //ADD YOUR LEGACY                    
                    e.ObjectRepository.Register("containerObjectForJs", new ContainerObjectForJs(), isAsync: true);
                }
            };
        }

        public void ResizeContainerCustom()
        {
            this.Top += 30;
            this.Height += 30;
        }
    }

- expose HTML Page : issue3466.html
<html>
<head>
	<meta charset="UTF-8">
	<script type="text/javascript">
		function customActionOnContainer()
		{
			(window.containerObjectForJs || window.external).callCSharpContainerCustomAction();
		}
	</script>
</head>
<body>
	<div style="width:100%;height:100%;background-color:red;">
		<span>Test Cédric</span>		
		<button onclick="customActionOnContainer()">Expand height 30px</button>		
	</div>
</body>
</html>

Launch Application. Go to the web page http://localhost/issue3466.html
Minimize the window with the square at the top right.
Click on the "Expand height 30px" button. Browser flickers / blinks. No problem with CefSharp.WPF <= 79.1.360

**Comment by amaitland** [comment]
Thanks,  I'll have a look in a few days.

**Comment by amaitland** [comment]
In the mean time you can compare the 79 and 81 Git branches at https://github.com/cefsharp/CefSharp/compare/cefsharp/79...cefsharp/81

Only commit that stands out is https://github.com/cefsharp/CefSharp/commit/924e7bd4572ab691d64a031489d53c21f3c5fd2b

GPU compositing was disabled, in version 79.

**Comment by amaitland** [comment]
Disabling `GPU Compositing` appears to resolve the issue (this was last disabled by default in version `79`). 

```c#
settings.CefCommandLineArgs.Add("disable-gpu-compositing");
```

**Comment by CedricInfeeny** [comment]
Perfect it works!
Thank you very much :)
