### ISSUE TITLE
CefSharp.BindObjectAsync with no parameters does not bind registered objects, nor fire ResolveObject event 

### ISSUE THREAD

**Issue by ensign-nemo** [cefsharp/CefSharp#3470]
NuGet package version 88.2.90, in .NET framework v4.7.2 C# WinForms application.

Attempting to implement SYNC javascript object binding as part of migration from CEF 1 and its RegisterJsObject pattern.

[Documentation](https://github.com/cefsharp/CefSharp/wiki/General-Usage#sync-javascript-binding-jsb) declares:

> For calls to CefSharp.BindObjectAsync without any params, then if objects have already been registered then they will all be bound, if no objects have been registered then ResolveObject will be called with the ObjectName set to All.

I am finding that this is not the case. Trying a call as follows:
```
$(document).ready(function () {
    CefSharp.BindObjectAsync().then(function (result) {
        myCSharpObject.documentReady();
    });
});
```
I have tried both approaches of registering an object:

* "pre registering" of objects directly with the WebView instance as part of its initialisation via `_webView.JavascriptObjectRepository.Register(...)`
  * BindObjectAsync() does not bind as js object to my C# instance
  * BindObjectAsync("myCSharpObject") _does_ bind

* "dynamic" registering on demand in event handler of ResolveObject via `e.ObjectRepository.Register(...)`
  * BindObjectAsync() does not cause ResolveObject event to be raised
  * BindObjectAsync("myCSharpObject") _does_ raise the event and a js object _is_ bound to a C# instance created in the event handler. 

I'm no C++ guru but my grokking around has led me to [this class](https://github.com/cefsharp/CefSharp/blob/e3e4c3fe35fe83299b08dc2d7479bb94f85772ff/CefSharp.BrowserSubprocess.Core/BindObjectAsyncHandler.h) which seems to handle the binding and I can see no reference to an "All" case being handled. Similarly, I can find no unit tests that attempt to validate this scenario either.

I would like this to function as documented as I do not know at design time what named objects will be passed in. A single JS call that lets me bind everything that has been registered with my WebView wrapper/descendant would be extremely convenient.

**Comment by amaitland** [comment]
> and I can see no reference to an "All" case being handled

The logic is split between the browser and render processes. https://github.com/cefsharp/CefSharp/blob/cefsharp/89/CefSharp/Internals/JavascriptObjectRepository.cs#L118

If you add a breakpoint is IJavascriptObjectRepositoryInternal.GetObjects called?

**Comment by amaitland** [comment]
I can confirm there is a problem, use the following as a workaround in the short term.

```javascript
CefSharp.BindObjectAsync({ IgnoreCache: true });
```

**Comment by ensign-nemo** [comment]
Thank you for checking and validating. I'll be using the workaround for now to get on with my workload. 

Do you still want me to try the breakpoint test when I get some 'spare time' ?

**Comment by amaitland** [comment]
> Do you still want me to try the breakpoint test when I get some 'spare time' ?

The promise returns as fulfilled so I think it's returning immediately. I don't think the problem lies in the JavaScriptObjectRepository,
