### ISSUE TITLE
WinForms - parentControl.Dispose() in LifeSpanHandler crashes the whole host application

### ISSUE THREAD

**Issue by cbries** [cefsharp/CefSharp#3493]
First, I recognized this issue in our business logic.
That line disposes the parent, but results in an application crash:
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.WinForms.Example/Handlers/LifeSpanHandler.cs#L110

It is reproducible with the provided example code of your `CefSharp`.

In our business code the exception looks like the exception in the following screenshot and looks like an `Cef` (Chromium) issue and not like a `CefSharp` issue.

Do you know a way to handle/bypass that case?

![image](https://user-images.githubusercontent.com/5418062/114371885-3e1b6000-9b81-11eb-9d9d-25735b6009ae.png)

The used versions are:

![image](https://user-images.githubusercontent.com/5418062/114371997-5f7c4c00-9b81-11eb-83a0-70bb7e51ce93.png)

**Comment by amaitland** [comment]
> If you are seeing a crash in libcef.dll then please download libcef.dll.pdb and place it next to libcef.dll to obtain a detailed stack trace, see https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#loading-native-symbols-for-easier-diagnosis for details.

As per https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report

Download the libcef.dll.pdb and get a stack trace. In future please use the bug report temple linked above. 

CEF has it's own issue tracker at https://bitbucket.org/chromiumembedded/cef/issues?status=new&status=open once you have a stack trace you can search for already open issues.

**Comment by cbries** [comment]
Alright, as I see not isses in CefSharp. Thanks.
