### ISSUE TITLE
Control is not Docking properly on 1st load.

### ISSUE THREAD

**Issue by melegant** [cefsharp/CefSharp#3502]
### Bug Report

Version  89.0.170.0
Nuget
architecture x86
Windows 10
WinForms

- **What steps will reproduce the problem?**
The dock property of the control is not docking the control Full inside the Tab Container until the second time we open the form. 

- **What is the expected output? What do you see instead?**
1st time we open the form:
![image](https://user-images.githubusercontent.com/19844309/114607476-99754d00-9c6a-11eb-95e5-2b71bc40206a.png)
2nd time we open the form
![image](https://user-images.githubusercontent.com/19844309/114607539-abef8680-9c6a-11eb-98b6-f2237cd82f70.png)
For the rest of the session the browser control displays properly.

- **Please provide any additional information below.**
We create the instance of the control in the constructor of the form that ends up being the shown inside the tab. 
`           InitializeComponent();

            _systemSettings = ServiceLocator.Resolve<ISystemSettings>();
            _tokenService = ServiceLocator.Resolve<ITokenService>();
            _userService = ServiceLocator.Resolve<IUserService>();

            WindowState = FormWindowState.Maximized;
            browser = new ChromiumWebBrowser("www.google.com") { Dock = DockStyle.Fill };
            Controls.Add(browser);

            browser.IsBrowserInitializedChanged += OnIsBrowserInitializedChanged;`

   `private void OnIsBrowserInitializedChanged(object sender, EventArgs e)
        {
            var b = ((ChromiumWebBrowser)sender);

            this.InvokeOnUiThreadIfRequired(() => b.Focus());
            this.InvokeOnUiThreadIfRequired(() => b.Refresh());
        }`

In the load of the application we are initializing settings :

```
 if (!Cef.IsInitialized)
                {
                    Cef.EnableHighDPISupport();
                    var settings = new CefSettings();

                    Cef.Initialize(settings, performDependencyCheck: false, browserProcessHandler: null);
                }
```

NOTE - We discovered that be putting this in app manifest it fixes this issue but breaks the rest of the application :)

`<asmv3:windowsSettings xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
      <ms_windowsSettings:dpiAware xmlns:ms_windowsSettings="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</ms_windowsSettings:dpiAware>
    </asmv3:windowsSettings>
`

Thanks for the help.

**Comment by melegant** [comment]
https://user-images.githubusercontent.com/19844309/114611111-aa27c200-9c6e-11eb-8a6b-e08597cbfc5f.mp4

Attached a movie of what is happening.

**Comment by amaitland** [comment]
This is a limitation of chromium, 
 https://github.com/cefsharp/CefSharp/wiki/General-Usage#high-dpi-additional-info has details about a workaround. 

Issue https://github.com/cefsharp/CefSharp/issues/2927 already tracks adding additional options.

**Comment by melegant** [comment]
@amaitland Hi that did that trick. 
We put this in the settings and now it works.
    settings.CefCommandLineArgs.Add("disable-gpu", "1");

**Comment by amaitland** [comment]
Disabling only GPU compositing is preferable.
