### ISSUE TITLE
Core - Make ModuleInitializerAttribute internal

### ISSUE THREAD

**Issue by centreboard** [cefsharp/CefSharp#3519]
- **What version of the product are you using?**
   CefSharp.OffScreen.NETCore, reproducible with any of Nuget packages 87.1.132, 88.2.90, 89.0.170

- **What architecture x86 or x64?**
    <x86/x64>
	
- **What version of .Net?**
    Net 5.0
    
- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    OffScreen
    
- **What steps will reproduce the problem?**
  Create a .NET 5 project that uses `[ModuleInitializer]` on a method
  Add a reference to CefSharp.OffScreen.NETCore, reproducible with any of 87.1.132, 88.2.90, 89.0.170

- **What is the expected output? What do you see instead?**
The build fails due to public `ModuleInitializerAttribute` exported from CefSharp.Core clashing with the BCL
>  Program.cs(14, 10): [CS0433] The type 'ModuleInitializerAttribute' exists in both 'CefSharp.Core, Version=89.0.170.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138' and 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

- **Please provide any additional information below.**
Example project https://github.com/centreboard/ModuleInit
The attribute defined in the package can be made internal and the compiler will still generate and call the module initialiser method https://github.com/cefsharp/CefSharp/blob/4608924d5a0c676857720917550674b88bd7b701/CefSharp.Core/ModuleInitializerAttribute.cs#L4

- **Does this problem also occur in the `CEF` Sample Application**
  N/A

**Comment by amaitland** [comment]
Thanks for the detailed bug report and the suggested workaround 👍 

So far making the attribute `internal` appears to be working as expected.
