### ISSUE TITLE
WPF - Update NotifyDpiChange xml doc to clarify allowed values.

### ISSUE THREAD

**Issue by BeanYa** [cefsharp/CefSharp#3561]
## What version of the product are you using?
Nuget 88.2.90/90.6.50

## What architecture x86 or x64?
x64

## What version of .Net?
.Net 4.6.1

## On what operating system?
Win10

## Are you using WinForms, WPF or OffScreen?
WPF

## What steps will reproduce the problem?

- Implement an Control inherited from ChromiumWebBrowser
- Override the NotifyDpiChange(float) like: 
`public override void NotifyDpiChange(float newDpi)  { base.NotifyDpiChange(UsingDpi); }`
- Zoom in/out to change scaletransform of a `Grid` Which held the `ChromiumWebBrowser` control.
- Call `NotifyDpiChange(float)` with the `UsingDpi(value of scaletransform)`, the `ChromiumWebBrowser` control will shake.
- And I found out that the width/height would increase/decrease 1px in devtool.
- Because the increased/decreased 1px, the resizing process of HTML give a unexpected result.

### I reproduced this in `CefSharp.Wpf.Example` from source code:

- Add `OnKeyDown` in `ChromiumWebBrowser.cs` of `CefSharp.Wpf`

``` 
float tmpFactor = 1f;
protected override async void OnKeyDown(KeyEventArgs e)
{
    base.OnKeyDown(e);

    if(e.Key == Key.X)
    {
        tmpFactor += 0.1f;
        NotifyDpiChange(tmpFactor);
    }

    if(e.Key == Key.F12)
    {
        this.GetBrowserHost().ShowDevTools();
    }
}
```

- Run the `CefSharp.Wpf.Example`
- Wait for initialization
- Press F12
- Press X

From the devtool the width/height of page has changed to a float value. 
I guess the width/height had a rounding down in my Application that the width/height increase/decrease 1px?

## What is the expected output? What do you see instead?

- During above steps, the width/height of control was not changed. The width/height shouldn't change.
- Can I set the size manually?

I guess this is a side impact that I manually call `NotifyDpiChange(float)`, Or is there any alternative solution that can keep clarity when scaletransform has changed?

## Please provide any additional information below.
- `UsingDpi` is a double variable apply to ScaleTransform
- The Application is kind of software like PowerPoint coded by WPF
- The Application used ScaleTransform for zoom in/out.
- For compatibility, I can only use ScaleTransform to zoom in/out controls.
- We made a list of control in HTML and we want to embedded that into this Application.
- The controls in HTML has a resizing process for fit the gird size automatically.
- I found out that if call `NotifyDpiChange(float)` with the value of `ScaleTransform`, the browser control can keep clarity like a original WPF control.

**Comment by amaitland** [comment]
Thanks for taking the time to fill out the bug report in detail 👍 

> * Call `NotifyDpiChange(float)` with the `UsingDpi(value of scaletransform)`, the `ChromiumWebBrowser` control will shake.

`NotifyDpiChange` is indented to be called as the result of a [WM_DPICHANGED](https://docs.microsoft.com/en-us/windows/win32/hidpi/wm-dpichanged) message or via the `WPF` specific handlers e.g. [Window.DpiChanged](https://docs.microsoft.com/en-us/dotnet/api/system.windows.window.dpichanged?view=net-5.0)

The allowed values are `1.0`, `1.25`, `1.5` and `2.0`. The xml documentation should be updated to clarify this.
These correspond to `96, 120, 144, or 192` dpi (referred to as `100%`, `125%`, `150%`, `200%` in the `Windows GUI`.

> For example, if the DPI is 120 , DpiScaleX would be 1.25 (120/96).

As per https://docs.microsoft.com/en-us/dotnet/api/system.windows.dpiscale.dpiscalex?view=net-5.0#System_Windows_DpiScale_DpiScaleX

The simple math is that `96 x dpiScale`. Which in your case is

```
96 x 1.1 = 105.6
```

Which is `105.6` dots per inch, which isn't included in the supported list of values above.

I believe the `NotifyDpiChange` is working for it's intended purpose in conjunction with the [WM_DPICHANGED](https://docs.microsoft.com/en-us/windows/win32/hidpi/wm-dpichanged) notification (the width/height should also be scaled accordingly), updating the `xml` doc is the only action (title has been updated to reflect this).

**Comment by amaitland** [comment]
> * The Application used ScaleTransform for zoom in/out.
> * For compatibility, I can only use ScaleTransform to zoom in/out controls.

Not scaling the browser and using the built in `Chromium` zoom functionality would likely be preferable. If for some reason you cannot exclude the browser from being transformed then perhaps you can switch to using https://github.com/cefsharp/CefSharp.Wpf.HwndHost which is a `HwndHost` control (like hosting the `WinForms` version in a `WindowsFormsHost`). The `AirSpace` limitations would mean the browser isn't scaled and you can manually control the browser zoom.

https://github.com/cefsharp/CefSharp.Wpf.HwndHost/blob/master/CefSharp.Wpf.HwndHost/ChromiumWebBrowser.cs#L1197

**Comment by BeanYa** [comment]
Thanks for your reply

## More additional info

I had tried

- `NotifyDpiChange(4f)` 
- `NotifyDpiChange(2.5f)` 

Both in `<ScaleTransform ScaleX="4" ScaleY="4"/>` (In Nuget 88.2.90)

I can see  `NotifyDpiChange(4f)` was much more clear than  `NotifyDpiChange(2.5f)`.

According to this, we tried to align the value of `NotifyDpiChange(float)` with `ScaleTransform` to fixed the clarity issues.

And it seems work well.

## Questions

### NotifyDpiChange

But you said

> The allowed values are 1.0, 1.25, 1.5 and 2.0. 

- Is there have more allowed values? 

I know `NotifyDpiChange` should only called when DPI Changed. 

But I tried `SetDeviceMetricsOverrideAsync` in DevTools

My idea is to increase the pixel density that the CefSharp can gives out a more clear image in high resultion when I change scaletransform.

If I shouldn't do this. 

Is there an approximate way to implement him?

### HwndHost

I tried `WebView2` before, but it would overlap some WPF control under the browser control when zoom in it.

> Zoom in in here means change scaletransform

I saw them named it `AirSpace` issue in StackOverflow.

- Would the `CefSharp.Wpf.HwndHost` cause the same problem?

I need to evaluate the impact between above issues.

**Comment by amaitland** [comment]
> * Is there have more allowed values?

I'm not planning on enforcing any restriction, just update the documentation. If your values multiply by `96` and result in an even number then it'll probably work. It is also unlikely that `Chromium` has been tested with values outside those used by `Windows`.

> I know `NotifyDpiChange` should only called when DPI Changed.

As windows only supports `1.0, 1.25, 1.5, 2.0` currently those are the only values I'll test against/support. If you use higher and it works, great, they won't be anything to stop you. Just know that if you run into any problem you'll need to debug them yourself. Make sure you test every time you upgrade to a new version to validate this still works.

I'd suggest you test with a machine that already has a `DPI` set to say `125%` and make sure your manually changing the `DPI` scale doesn't cause you any problems. You'll at a minimum have to store the value the user previously had to revert back when no `ScaleTransform` is applied.

> Is there an approximate way to implement him?

What do you mean exactly? Implement him????

`ChromiumWebBrowser` is capable of zooming itself, this is the recommended approach. Using a `ScaleTransform` has a performance penalty as every bitmap has to be scaled, if your webpage is playing a video/animation then it may perform poorly on low level video cards.

I haven't looked into it, perhaps you can find a way to tell `WPF` to exclude the `ChromiumWebBrowser` from being transformed, you'll need to do your own research to see if this is viable.

> SetDeviceMetricsOverrideAsync in DevTools

Likely related to issue https://bitbucket.org/chromiumembedded/cef/issues/3103/offscreen-capture-screenshot-with-devtools

`CEF` doesn't update it's size accordingly when `Devtools` performs and override. You'd have to submit a `PR` that fixes the problem in `CEF` to support this.

> * Would the `CefSharp.Wpf.HwndHost` cause the same problem?

You will have problem with overlapping, standard `AirSpace` issues apply. `WebView2` is also a `HwndHost` implementation.

**Comment by BeanYa** [comment]
Thanks

> What do you mean exactly? Implement him????

Sorry, just a mistake.

Should be "Is there an approximate way to implement this ?"

Forget it.

---

> I'd suggest you test with a machine that already has a DPI set to say 125%

Actually I did calculate that.

```
private void VisualSourceChanged(object sender, SourceChangedEventArgs e)
{
    if(e.NewSource != null)
    {
        var source = (HwndSource)e.NewSource;

        var matrix = source.CompositionTarget.TransformToDevice;

        DeviceScale = (float)matrix.M11;
    }
}
```

The actual code will be `NotifyDpiChange(DeviceScale * ScaleTransform)`. And it works well.

I omitted some details that I think is unnecessary.

--- 

> ChromiumWebBrowser is capable of zooming itself, this is the recommended approach. Using a ScaleTransform has a performance penalty as every bitmap has to be scaled, if your webpage is playing a video/animation then it may perform poorly on low level video cards.

I know you mentioned this in other issue, but my Application will increase/decrease the scaletransform of its container and the `ChromiumWebBrowser` would be blurry because of the bitmap scaling.

In order to use scaletransform of `ChromiumWebBrowser`'s container and keep clarity.

My idea had mentioned in previous commnet.

> My idea is to increase the pixel density that the CefSharp can gives out a more clear image in high resolution when I change scaletransform.

My last question is there have a way to control the resolution(width/height) of the bitmap that `ChromiumWebBrowser` gives out.

**Comment by amaitland** [comment]
> I know you mentioned this in other issue, but my Application will increase/decrease the scaletransform of its container and the `ChromiumWebBrowser` would be blurry because of the bitmap scaling.

I'm suggesting you find a way to exclude the `ChromiumWebBrowser` instance from scaling.

If using `NotifyDpiChange` works for you then I'm not stopping you.

The `xml doc` for `NotifyDpiChange` will be updated.

> My lastest question is there have a way to control the resolution(width/height) of the bitmap that `ChromiumWebBrowser` gives out.

I'd suggest you look at the source to better understand how the rendering implementation works. If you have a specific question please open a new [discussion](https://github.com/cefsharp/CefSharp/discussions)

**Comment by BeanYa** [comment]
Got it, Thanks
