### ISSUE TITLE
disable-web-security switch causing visual bug

### ISSUE THREAD

**Issue by DrabanL** [cefsharp/CefSharp#3568]
- **What version of the product are you using?**
    master commit 842429a76e03bef75e6a47543f84aa6e513bbf74 (latest as of this moment)

- **What architecture x86 or x64?**
    x64
	
- **What version of .Net?**
    .net 5.0
    
- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WinForms
    
- **What steps will reproduce the problem?**
- modify & build WinForms.Example.netcore project with disable-web-security switch enabled
`settings.CefCommandLineArgs.Add("disable-web-security", "1");`
- browse to https://hwzone.co.il or https://cartube.co.il
 
- **What is the expected output? What do you see instead?**
after the page fully loads, you will notice some parts of the page shrinks (seems like it is treated as mobile resolution)

- **Please provide any additional information below.**
it could be related to a common js library used by this websites (AMP HTML) but... i could not reproduce with cefclient

- **Does this problem also occur in the `CEF` Sample Application**
at first i was sure it must be rooted in CEF code, but no. the visual abnormality is not present there (tested running cefclient with --disable-web-security switch)

**Comment by amaitland** [comment]
> at first i was sure it must be rooted in CEF code, but no. the visual abnormality is not present there (tested running cefclient with --disable-web-security switch)

Please test with the command line args listed in the bug report, in addition to disable web security. 

Which version of CEF did you test with? The version linked is not the same version used by the master branch.

**Comment by amaitland** [comment]
Please test with the current release branch. 

https://github.com/cefsharp/CefSharp/tree/cefsharp/90

I'm aware the current examples aren't copying the locales and swiftshader folders correctly, problem was likely introduced in #3359

This is only a problem for the master examples and not the release packages.

**Comment by DrabanL** [comment]
after checking again, it really seems like a bug in CEF.
my initial test was running cefclient with '--disable-web-security' however the correct argument (which causes the issue) is '--disable-web-security=1'

after running cefclient with this parameter, I can reproduce the bug without cefsharp intervention 

thank you for bothering
