### ISSUE TITLE
Feature Request - JavascriptBinding root

### ISSUE THREAD

**Issue by bbday** [cefsharp/CefSharp#3570]
I know at the moment is possible setup JavascriptBindingApiGlobalObjectName with custom name but it happear on 
Object.getOwnPropertyNames(window) then is easy way to find it.

I think a better idea if we can choice where we can place root of object like in window.navigator or window.history or other objects, than can improve so much hidding service.

**Comment by amaitland** [comment]
> with custom name but it happear on
> Object.getOwnPropertyNames(window) then is easy way to find it.

#3571 will allow for disabling creation of the `cefSharp/CefSharp` objects.

**Comment by bbday** [comment]
thanks for answer the issue is i use EvaluateScriptAsPromiseAsync i think you can do something like add temp object when promise start then will delete after execution (delete X).
Best idea to be paranoic is like wrote before create temp object in other root path like window.navigator

**Comment by amaitland** [comment]
> issue is i use EvaluateScriptAsPromiseAsync

You can likely achieve the same result using the DevTools protocol. You can execute DevTools commands directly (#3165)

https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-runScript

> i think you can do something like add temp object when promise start then will delete after execution (delete X).

That would be problematic for multiple concurrent calls. 

If you (or someone else) would like to sponsor development then I'm happy to discuss further.

**Comment by amaitland** [comment]
Closing as this isn't something I'm planning on implementing currently.

If someone would like to discuss sponsoring development then happen to discuss reopening.
