### ISSUE TITLE
Feature Request - Secure Playback/Fairplay (Spotify and Apple Music)

### ISSUE THREAD

**Issue by stevenboeren** [cefsharp/CefSharp#3600]
Please ask your questions under the Discussions section here on GitHub 
- https://github.com/cefsharp/CefSharp/discussions

---

`CefSharp` is a wrapper around the [Chromium Embedded Framework](https://bitbucket.org/chromiumembedded/cef/overview) in a lot of cases a feature must be added to `CEF` first before it can be used in `CefSharp`. `CEF` has its own `Feature Request Forum` at https://magpcss.org/ceforum/viewforum.php?f=7

--- 

**Describe the solution you'd like**
A clear and concise description of the feature you are proposing

**Describe alternatives you've considered**

**Additional context**

**Checklist:**
- [ ] I have reviewed the [CEF API](https://magpcss.org/ceforum/apidocs3/index-all.html) and have confirmed the feature I'm requesting is possible.
- [ ] The Feature I'm requesting is an improvement to Async Javascript Binding (No new feature are being added to the Sync Javascript binding)
- [ ] An open `PR` exists on the [CEF Pull Requests](https://bitbucket.org/chromiumembedded/cef/pull-requests/) and I'd like to propose this feature is added to `CefSharp` when/if it's merged.

**Comment by amaitland** [comment]
They both require audio codecs that require royalties. See https://github.com/cefsharp/CefSharp/wiki/General-Usage#multimedia-audiovideo

Closing as this isn't something we can support out of the box. You have to build CEF from source.

**Comment by stevenboeren** [comment]
Hi Guys,

I wanted to make Apple Music program with CefSharp, so could use the program instead of webpage.
The website loads fine exept it will not load a song. After alot of reseaching yesterday I saw that you need to enable secured content (DRM). Because I tried Spotify web player and asks to enable secure playback. 

I was searching for hours and found something about WidevineCDM. But I am new to this and have no idea how it actually works. I will make a repo for this project if anyone wants to help.

Hope to hear from some of you soon!
Here are some screenshots of code and the errors.
![Code1](https://user-images.githubusercontent.com/70892306/120886064-4d041900-c5ec-11eb-93d0-9f4aaf4dc793.png)
![Code2](https://user-images.githubusercontent.com/70892306/120886066-5097a000-c5ec-11eb-9181-803a3eb40063.png)
![Screen1](https://user-images.githubusercontent.com/70892306/120885887-9011bc80-c5eb-11eb-9e07-851b844586c8.png)
![Screen2](https://user-images.githubusercontent.com/70892306/120885984-f72f7100-c5eb-11eb-936c-b1985c68ff15.png)
