### ISSUE TITLE
Nuget - Update post nuget restore instructions

### ISSUE THREAD

**Issue by gitmarcalinascris** [cefsharp/CefSharp#3615]
Cefsharp Dependencies are not downloading from a clean folder( No prior Cefsharp packages). 

What I my by clean folder is when i deleted all packages from my working folder via git repository.

![image](https://user-images.githubusercontent.com/47529366/121880227-599d1580-cd40-11eb-9419-66a3e2af17f2.png)

What I have found out , it doesn't download the dependencies such as  "icudtl.dat", "CefSharp.BrowserSubprocess.exe", "CefSharp.BrowserSubprocess.Core.dll", "resources.pak","locales folder".

![image](https://user-images.githubusercontent.com/47529366/121879981-0c20a880-cd40-11eb-941c-b85836c08f95.png).

I have to clean and rebuild the library that contains the CEFSharp folders in order to download it (Which is basically re run the build). 

Take note:
My internet is stable

Can anyone shed a light?

**Comment by amaitland** [comment]
> Whilst it is no longer necessary to close Visual Studio for the references to show up (dotnet/project-system#4158) the runtime dependencies, libcef.dll etc still aren't copied until the project is closed/reopened when using packages.config style projects. Using PackageReference works correctly and is the recommended option. Please note you can use PackageReference with older non SDK Style projects (ones that would typically have used packages.config) under VS2017/2019.

As per #3319

If you are using the older packages.config you need to close and reopen the project after a Nuget restore. There should be a message in your build output instructing you to close and reopen the project. 

https://github.com/cefsharp/CefSharp/blob/cefsharp/90/NuGet/CefSharp.Common.targets#L367

If you are using VS 2017 or higher you can switch to using PackageReference as per https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference

**Comment by amaitland** [comment]
Looks like I accidentally removed the instructions from https://github.com/cefsharp/CefSharp/blob/cefsharp/90/NuGet/Readme.txt#L12

They should be re-added.

**Comment by gitmarcalinascris** [comment]
Thats good. Thankyou team.
