### ISSUE TITLE
WinForms - Incorrectly positioned inside Form with FormStartPosition set to CenterParent

### ISSUE THREAD

**Issue by ohlookitsben** [cefsharp/CefSharp#3625]
- **What version of the product are you using?**
    package id="CefSharp.WinForms" version="90.6.70" targetFramework="net472"

- **What architecture x86 or x64?**
    x64
	
- **What version of .Net?**
    .Net 4.7.2
    
- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WinForms
    
- **What steps will reproduce the problem?**
    1. Run the attached application
    2. Resize the main form to be larger than its intial size (this seems to be important)
    3. Click the "Open 50 dialogs" button. This issue is intermittent, but 50 seems to be enough to reliably see at least one instance of the issue.

    The issue is not reproducible in the example code as there are no dialogs launched  in this way.
- **What is the expected output? What do you see instead?**
    I expect the contents of the CEF browser window to render inside the form that contains the browser control with correct alignment.

    The contents are instead misaligned relative to the window containing the browser control. This is visible in the [video of the issue](https://youtu.be/a8KoV5EH_K8) at [0:51](https://youtu.be/a8KoV5EH_K8?t=51).

- **Please provide any additional information below.**
    I have attached a sample application that reproduces this issue. This is the application used in the video linked previously.
[CefFormStartPosition.zip](https://github.com/cefsharp/CefSharp/files/6666625/CefFormStartPosition.zip)
https://github.com/ohlookitsben/cefformstartposition

    The commented line in this file appears to be the trigger for this bug. Removing it will cause the browser to position correctly. https://github.com/ohlookitsben/cefformstartposition/blob/main/CefFormStartPosition/BrowserDialog.cs
    
    This may be possible to reproduce without resizing the main form, but I'm yet to see it. This issue does not seem to appear if the parent form is the same size as the dialog.

    Setting FormStartPosition to CenterScreen also produces the same issue

- **Does this problem also occur in the `CEF` Sample Application**
    The sample applications do not open dialogs so the issue cannot be reproduced.

**Comment by amaitland** [comment]
Thanks for the detailed bug report 👍 

If you add a border around the `ChromiumWebBrowser` instance does it fill the entire `Form` when the control renders incorrectly? If yes then it's probably a timing issue when the internal `CefBrowser` has it's `width/height` set.

**Comment by ohlookitsben** [comment]
Apologies for the delay in response. I haven't easily been able to capture an image of the control with a border around it - the incidence of this failure on my test application has really dropped off lately and I'm not sure why. I've captured a video of the failure in our actual application that might answer some questions around how the control is being laid out.

A few observations
- At the start of the video I am right clicking across the window trying to bring up the custom context menu we have configured for the browser. The context menu can only be triggered once the cursor moves inside the painted area of the browser. 
- The browser can be interacted with normally
- (Not shown) when this occurs on a resizable dialog (this one is not resizable), resizing the dialog will cause the browser to correctly fill the dialog.

https://www.youtube.com/watch?v=z3K91syDl5U

**Comment by amaitland** [comment]
> I've captured a video of the failure in our actual application that might answer some questions around how the control is being laid out.

If you can reliably reproduce the problem in your application then you can do some debugging. `CefSharp` is built with [GitLink](https://github.com/GitTools/GitLink/blob/develop/README.md), there are  instructions on the `GitLink` site about how to enable within `Visual Studio`. You can step into `ChromiumWebBrowser` and add some breakpoints to the following:

- https://github.com/cefsharp/CefSharp/blob/cefsharp/91/CefSharp.WinForms/ChromiumWebBrowser.cs#L637
- https://github.com/cefsharp/CefSharp/blob/cefsharp/91/CefSharp.WinForms/ChromiumWebBrowser.cs#L748

The video doesn't really tell me anything meaningful.

**Comment by amaitland** [comment]
I just ran your example three times (total of 150 browsers created) and I've yet to see the problem reproduce.

Does the problem reproduce on multiple machines with different hardware/software configurations or is it limited to a single hardware/software config?

**Comment by ohlookitsben** [comment]
The problem is reproducible on a few different machine configurations. We've had 2 or 3 clients report this issue that would be using different machines to us. The machines we're using for development also display these issues. The models we know of that can reproduce this are Dell Precision 5530, Dell Precision M4800, Panasonic Toughbook FZ-G1, Dell Precision 7530. The issue has been long-standing for us, and we have records of it back to CEF 65.0, so I don't think this is likely to be a recently introduced thing.

**Comment by amaitland** [comment]
If you can reproduce the problem on a machine with visual studio installed you should fairly easily be able to debug this. If the ChromiumWebBrowser instance fills the space correctly then it's likely something related to the internal ResizeBrowser calls.

**Comment by ohlookitsben** [comment]
Still in the process of digging into this:

- I've hacked the example code I uploaded into the example app in the CefSharp project, and have started removing pieces to see what allows me to reproduce the issue. So far I have removed the resize handling from both the `ChromiumWebBrowser` and the `ManagedCefBrowserAdapter` and am still able to reproduce, so I don't think it's caused by running any code inside these handlers at this stage.
- I've logged out the x/y from the `WindowInfo` passed in here and it's consistently 0,0 even when the issue occurs (though setting it to some negative value in a debugger reproduces the symptoms of the issue).
- Reproduction seems significantly easier in a debug build for me today, but ease of reproduction seems to vary wildly according to some factor I don't understand yet. Running under high load with furmark and intel burn test in the background didn't yield any increase in the frequency this occurs, but today I've been getting 1-2 per 50 occurrences.

**Comment by juanbucz** [comment]
Has there been any resolution on this issue? 

I'm seeing the behaviour consistently here.

I create a simple Form with a panel.
I add the Cef control to the panel.
The contents are misaligned and offset (down and to the right).
I've tried several small sample apps I found on the web.
I've tried previously releases of the Cef library.
I see the same results every time.

I've attached a zip of my project here.

Can anyone shine any light on this?
Until I can get this resolved the control will be unusable for us.

Thanks
[CefTest.zip](https://github.com/cefsharp/CefSharp/files/7687180/CefTest.zip)

**Comment by juanbucz** [comment]
After much googling, I found a solution that worked for me.
The issue appears to be DPI related.

I added this to my winforms App.config file:
```
  <System.Windows.Forms.ApplicationConfigurationSection>
    <add key="DpiAware" value="true"/>
    <add key="DpiAwareness" value="PerMonitorV2"/>
  </System.Windows.Forms.ApplicationConfigurationSection>
```

I also set my .Net Framework version to be 4.7.2 (anything prior to that causes the same issue).

With the combination of these changes, the Cef browser control aligns correctly in it's parent container.

Hope this helps someone else.

**Comment by amaitland** [comment]
> The issue appears to be DPI related.

See https://github.com/cefsharp/CefSharp/wiki/General-Usage#high-dpi-displayssupport for information regarding DPI. 

This particular issue isn't related to DPI.

**Comment by amaitland** [comment]
I'm going to close this issue for now as I've not seen any further reports and I've never been able to reproduce the issue myself so this isn't something I can debug.

Based on the described behaviour it's entirely possible it's a problem deep within `Chromium` that only reproduces with a set `GPU`.
