### ISSUE TITLE
Can't log into google

### ISSUE THREAD

**Issue by MarcelskyXD** [cefsharp/CefSharp#3628]
- **What version of the product are you using?**
    91.1.160

- **What architecture x86 or x64?**
    x86
	
- **What version of .Net?**
    Net 5.0
    
- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
   WPF

- **What steps will reproduce the problem?**
- Trying to login to google causes it to say that its a insecure browser.

**Comment by amaitland** [comment]
The behaviour you are seeing is expected, to my knowledge Google haven't provided an official means of logging in. Closing as this is not a bug, it's a deliberate action by Google to block all CEF based browsers, for which CefSharp is one of many.

There's already a discussion on the topic at https://github.com/cefsharp/CefSharp/discussions/3506
