### ISSUE TITLE
Custom sec-ua value Request

### ISSUE THREAD

**Issue by bbday** [cefsharp/CefSharp#3635]
I would like to setup _sec-ch-ua_ value header, at the moment is just _"Chromium";v="91_ but when you emulate other browser or device should be different, as you know you can setup only user agent on main setting.
Example on real chorme is _" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"_

**Comment by amaitland** [comment]
This needs to be implemented upstream. There is an open PR to improve support. 

https://bitbucket.org/chromiumembedded/cef/pull-requests/372

You can track the progress there.

**Comment by amaitland** [comment]
> as you know you can setup only user agent on main setting.

You can set the user agent at runtime using DevTools protocol. See https://github.com/cefsharp/CefSharp/wiki/General-Usage#useragent

**Comment by zxcvqwerasdf** [comment]
Any updates? sec-ch-ua now is empty on default cef/cefsharp. I see only one option set header on request. But maybe there is another way?
