### ISSUE TITLE
Update min required Visual C++ runtime from 2015 to 2019

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#3636]
CEF is dropping support for compiling the C++ wrapper with Visual Studio 2015/2017 see https://groups.google.com/g/cef-announce/c/IMgnaeWipwc/m/so6nGWgWBgAJ for details. 

As a flow on from we will be forced to migrate from Visual C++ 2015 as the minimum to Visual C++ 2019 runtime. A lot of users will already have the Visual C++ 2015-2019 runtime, so no action will be required. 

I will provide further updates once M93 builds are available and I can confirm exactly what  changes are required. 

- [x] Update release notes
- [x] Update General Usage
- [x] Update FAQ
- [x] Update Readme.md

For those using the `.Net Core 3.1/.Net 5.0` packages `VC++ 2019` is already required.

**Comment by amaitland** [comment]
> Include include/base/cef_callback.h instead of include/base/cef_bind.h

As per https://groups.google.com/g/cef-announce/c/IMgnaeWipwc/m/so6nGWgWBgAJ we should use `cef_callback.h` instead. https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core.Runtime/RequestContext.cpp#L17

**Comment by amaitland** [comment]
> I will provide further updates once M93 builds are available and I can confirm exactly what changes are required.

Beta builds of version `93` are now available on https://cef-builds.spotifycdn.com/index.html

As expected attempting to build with `VS2015/VS2019` [failed](https://ci.appveyor.com/project/cefsharp/cef-binary-5r1rw/builds/40186563).

As a result `CefSharp` will now require `VS2019` to compile, `Visual C++ 2019` will now be the new minimum (`Visual Studio 2022 is in preview and I expect that Visual C++ 2020 will be backwards compatible`).

**Comment by amaitland** [comment]
For those that have the `Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019` installed then **no change** will be required.

For those that have an older `VC++ 2015/2017` installation there are a two options:
- Install the [Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0) runtime (
- Include the `VC++ 2019` dlls with your application ([Local Deployment](https://docs.microsoft.com/en-us/cpp/windows/deployment-in-visual-cpp?view=msvc-160#local-deployment)).

**Local Deployment**
As you should already have the `Universal CRT` installed as you previous had `VC++ 2015/2017` installed (`Universal CRT` is also included as part of `Windows 10` by default) you can bin deploy the `VC++ 2019` dlls alongside your application.

The following should copy the `VC++` runtime into the bin/publish folders when run under `Visual Studio` (won't work from the command line). 

```xml
  <Import Project="$(DevEnvDir)..\..\VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.props"/>
  
  <Target Name="IncludeVisualCppInOutFolder" AfterTargets="ResolveReferences">
    <PropertyGroup>
      <_VCRedistLocation>$(DevEnvDir)..\..\VC\Redist\MSVC\$(VCToolsRedistVersion)\$(PlatformTarget)\Microsoft.VC142.CRT</_VCRedistLocation>
    </PropertyGroup>
    <Message Importance="high" Text="_VCRedistLocation = $(_VCRedistLocation)" />
    <ItemGroup>
      <ReferenceCopyLocalPaths Include="$(_VCRedistLocation)\**\*" />
    </ItemGroup>
  </Target>
```

**References**

- https://docs.microsoft.com/en-us/cpp/windows/deployment-in-visual-cpp?view=msvc-160#local-deployment
- https://docs.microsoft.com/en-us/cpp/windows/redistributing-visual-cpp-files?view=msvc-160
- https://docs.microsoft.com/en-us/cpp/windows/universal-crt-deployment?view=vs-2019
- https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/
- https://docs.microsoft.com/en-us/cpp/windows/determining-which-dlls-to-redistribute?view=msvc-160

**Comment by jsoldi** [comment]
Is this only for NET Core? According to [this page](url=https://github.com/cefsharp/CefSharp/wiki/Output-files-description-table-(Redistribution)#Requirements) you only need the 2019 redistributables if you target NET Core, otherwise you can just use the 2015 redistributables.

**Comment by amaitland** [comment]
> As a flow on from we will be forced to migrate from Visual C++ 2015 as the minimum to Visual C++ 2019 runtime

VC++ 2019 is required for all packages now.

> According to https://github.com/cefsharp/CefSharp/wiki/Output-files-description-table-(Redistribution)#Requirements

Wiki has been updated, thanks.
