### ISSUE TITLE
Feature Request - Get Request/Response from DevToolClient

### ISSUE THREAD

**Issue by bbday** [cefsharp/CefSharp#3649]
I'm try to get request / response from devtoolclient

using (var devToolsClient = _browser.GetDevToolsClient())
devToolsClient.Network [...]

But i didnt find anything to collect http request/response from browser, i checked also here http://cefsharp.github.io/api/91.1.x/html/N_CefSharp_DevTools_Network.htm no clue

Can you provide a small example? thanks.

**Comment by amaitland** [comment]
Please use https://github.com/cefsharp/CefSharp/discussions to ask questions.
