### ISSUE TITLE
Feature Request - Add PrintToPDF without Print-Dialog

### ISSUE THREAD

**Issue by KevinKrueger** [cefsharp/CefSharp#3650]
I need a function that allows me to save a PDF without a print dialog.

I have already seen that you have such a function in your library ("PrintToPDF"). Basically it does exactly what I want, but it is not suitable to save a PDF without further clicks.

Long story short: PrintToPDF(...) without Print-Dialog.

**Comment by amaitland** [comment]
This needs to be fixed in CEF.  You can track progress at https://bitbucket.org/chromiumembedded/cef/issues/2790/windows-printtopdf-on-website-which

Closing as upstream.

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/blob/ff19eaa0056db1360c941e0b6af7a8ba58bad4e3/CefSharp.Test/OffScreen/OffScreenBrowserBasicFacts.cs#L409 for example of some new extension methods I added to simplify downloading files.

**Comment by KevinKrueger** [comment]
Hi, thanks for your reply.

I think I need to add something, that's what I mean:

I want to load a PDF locally(works already), then if changes were made to this pdf, should be the possibility to download this modified PDF without printdialog. The PDF is local!

This doesn't work "var data = await mainFrame.DownloadUrlAsync(url);" because it pulls data from a web address on the internet.

Greetings Kevin

**Comment by amaitland** [comment]
The CEF bug will need to be fixed.
