### ISSUE TITLE
Feature Request - Make DevToolsClient.ExecuteDevToolsMethodAsync generic

### ISSUE THREAD

**Issue by campersau** [cefsharp/CefSharp#3665]
Making `DevToolsClient.ExecuteDevToolsMethodAsync` generic would allow us to deserialize the type directly from the dev tools method result stream instead of copying it into a memory stream, convert it to bytes and then to a string and then deserializing it from the string to the type. We could special case the `DevToolsMethodResponse` type so it could be returned as is. This would also allow users to specify their own result types (they could still specify the `DevToolsMethodResponse` type and/or we could provide a none generic overload).

https://github.com/cefsharp/CefSharp/blob/a7dc73b681afb3d9c687300c3bd1a0cc8f99a6b4/CefSharp/DevTools/DevToolsClient.cs#L209-L214

Instead of storing the `SyncContextTaskCompletionSource<DevToolsMethodResponse>` in the `queuedCommandResults` we would just store an `Action<DevToolsMethodResponse>` which would be called immediately and handle the deserialization and setting the `TaskCompletionSouce` result / exception in the correct `syncContext`. 

https://github.com/cefsharp/CefSharp/blob/a7dc73b681afb3d9c687300c3bd1a0cc8f99a6b4/CefSharp/DevTools/DevToolsClient.cs#L28

The generated code would need to be adjusted like this:

```c#
public async System.Threading.Tasks.Task<GetAllCookiesResponse> GetAllCookiesAsync()
{
    System.Collections.Generic.Dictionary<string, object> dict = null;
    var methodResult = await _client.ExecuteDevToolsMethodAsync<GetAllCookiesResponse>("Network.getAllCookies", dict);
    return methodResult; // no `DeserializeJson<GetAllCookiesResponse>`
}

public async System.Threading.Tasks.Task<DevToolsMethodResponse> DisableAsync()
{
    System.Collections.Generic.Dictionary<string, object> dict = null;
    var methodResult = await _client.ExecuteDevToolsMethodAsync<DevToolsMethodResponse>("Network.disable", dict); // need to explicitly specify the generic type `DevToolsMethodResponse`
    return methodResult;
}
```

Here is a quick prototype of what I have described above (does not include the generated code changes): https://github.com/cefsharp/CefSharp/compare/master...campersau:genericExecuteDevToolsMethodAsync

If you agree with the overall design I would submit a PR for it.

---

Currently there is no method for deserializing synchronously from a `Stream` in `System.Text.Json` so we would still need a `MemoryStream` / `byte[]` conversion for that but we don't have to allocate a string. In the future it will be supported though: https://github.com/dotnet/runtime/pull/54632

**Comment by amaitland** [comment]
> |result| is only valid for the scope of this callback and should be copied if necessary.

As per https://github.com/chromiumembedded/cef/blob/a4d71d8fe2d7422c8e48128f55a503753e2d01c8/include/cef_devtools_message_observer.h#L87

The `Stream` is currently copied in all cases as it might be accessed from a different thread if a `SyncContext` is provided. I haven't run the code, it looks like we'd be trying to access the `Stream` directly without copy if `SyncContext` is specified.

`ExecuteDevToolsMethodAsync` should probably implement some sort of constraint, I don't remember seeing an example where `ExecuteDevToolsMethodAsync<string>` would be valid. Correct me if I'm mistaken. 

In general the idea sounds fine.

**Comment by amaitland** [comment]
Can we avoid making this a breaking change? Can an `public async Task<DevToolsMethodResponse> ExecuteDevToolsMethodAsync(string method, IDictionary<string, object> parameters = null)` remain?

**Comment by campersau** [comment]
> The Stream is currently copied in all cases as it might be accessed from a different thread if a SyncContext is provided. I haven't run the code, it looks like we'd be trying to access the Stream directly without copy if SyncContext is specified.

Yes, the stream will be accessed in the same thread without any awaits because of this restriction. 

> ExecuteDevToolsMethodAsync should probably implement some sort of constraint, I don't remember seeing an example where ExecuteDevToolsMethodAsync<string> would be valid. Correct me if I'm mistaken.

We could add a constraint to `DevToolsDomainResponseBase` but then `DevToolsMethodResponse` would need to inherit from it as well, but I think that's fine.

> Can we avoid making this a breaking change? Can an public async Task<DevToolsMethodResponse> ExecuteDevToolsMethodAsync(string method, IDictionary<string, object> parameters = null) remain?

Yes, but it would still be "breaking" as this would still change or add a method declaration on `IDevToolsClient`.

**Comment by amaitland** [comment]
> Yes, but it would still be "breaking" as this would still change or add a method declaration on `IDevToolsClient`.

Make the breaking changes the `interface`,  add an additional method overload to the `DevToolsClient` implementation, from memory the extension methods actually return the implementation.
