### ISSUE TITLE
Core - Crash opening popup window

### ISSUE THREAD

**Issue by netmaxik** [cefsharp/CefSharp#3670]
Delete this line and everything above, and then fill in the details below.

- **What version of the product are you using?**
   92.0.90-CI4112

- **What architecture x86 or x64?**
   x86
	
- **What version of .Net?**
    .Net 4.x
    
- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WinForms
    
- **What steps will reproduce the problem?**
This happened from version 92. all previous was working perfect.
Last version it was working : 90.5.70-RCI4015 
After update to new version 92.0.90-CI4106 stop wortking.

I used your CefSharp.WinForms.Example application.

load url : http://netmaxik.com/ceftest.html
On press button its function : 
FB.ui({
    display: 'popup',
    method: 'live_broadcast',
    phase: 'create',
}, function(response) {
    if (!response.id) {
      alert('dialog canceled');
      return;
    }

As soon as popup window open browser crashed.

- **What is the expected output? What do you see instead?**
It have to be popup FaceBook login window, instead it crashed,

- **Please provide any additional information below.**
Faulting application name: CefSharp.BrowserSubprocess.exe, version: 89.0.60.0, time stamp: 0x60e24fb4
Faulting module name: libcef.dll, version: 92.0.9.0, time stamp: 0x60c15fb2
Exception code: 0x4000001f
Fault offset: 0x0242a782
Faulting process id: 0x5ca4
Faulting application start time: 0x01d771339c3e9bea
Faulting application path: D:\WORK\TEST\CEF\CefSharp-master\CefSharp.BrowserSubprocess\bin\x86\Debug\CefSharp.BrowserSubprocess.exe
Faulting module path: D:\WORK\TEST\CEF\CefSharp-master\CefSharp.WinForms.Example\bin\x86\Debug\libcef.dll
Report Id: ced55d72-d6a7-4320-9e3f-346c5cafc52d
Faulting package full name: 
Faulting package-relative application ID: 
   

- **Does this problem also occur in the `CEF` Sample Application**
CEF sample working perfect without problem.
cefclient.exe --multi-threaded-message-loop --no-sandbox --disable-site-isolation-trials

**Comment by amaitland** [comment]
> * CEF sample working perfect without problem.

You'll need to test with https://cef-builds.spotifycdn.com/cef_binary_92.0.9%2Bg847fba0%2Bchromium-92.0.4515.51_windows32_beta_client.tar.bz2

If that crashes then please test with https://cef-builds.spotifycdn.com/cef_binary_92.0.14%2Bgadd734a%2Bchromium-92.0.4515.81_windows32_beta_client.tar.bz2

I haven't had a chance to upgrade `master` to the latest `CEF` build yet.

Crashes in `libcef.dll` are rarely bugs in `CefSharp`. Your likely comparing two different versions of `CEF`.

**Comment by netmaxik** [comment]
I did test and it all working in new version, I did download and test

**Comment by amaitland** [comment]
Does the problem reproduce in the current supported release (`91.1.211`)? Is there a reason you are building `master`?

It's still unlikely this is a bug in `CefSharp`, most likely a difference in settings. You'll need to download `libcef.dll.pdb` and get a proper stack trace. See https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#loading-native-symbols-for-easier-diagnosis

**Comment by netmaxik** [comment]
91.1.211 same issue. 
last working  : 90.5.70-RCI4015

**Comment by amaitland** [comment]
Are you using the official Nuget package for testing? Please confirm the problem reproduces using https://github.com/cefsharp/CefSharp.MinimalExample

> last working : 90.5.70-RCI4015

This is a nightly build. Have you tested with the latest stable version 90 release? 

You'll need to get a stack trace as detailed above.

**Comment by netmaxik** [comment]
Sorry for long answer..
https://github.com/cefsharp/CefSharp.MinimalExample - I did test and all working perfect.

**Comment by amaitland** [comment]
What features is your application using? RequestHandler? JavaScript Binding? 

You'll need a stack trace to get a better understanding of what's going on.

**Comment by netmaxik** [comment]
In this case Just open second windows. RequestHandler and JavaScriptHandler default.
 

Application: CefSharp.BrowserSubprocess.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at <Module>.CefSharp.BrowserSubprocess.CefAppUnmanagedWrapper.OnBrowserCreated(CefSharp.BrowserSubprocess.CefAppUnmanagedWrapper*, scoped_refptr<CefBrowser>*, scoped_refptr<CefDictionaryValue>*)
   at <Module>.CefExecuteProcess(CefMainArgs*, scoped_refptr<CefApp>*, Void*)
   at CefSharp.BrowserSubprocess.SubProcess.Run()
   at CefSharp.BrowserSubprocess.BrowserSubprocessExecutable.Main(System.Collections.Generic.IEnumerable`1<System.String>, CefSharp.RenderProcess.IRenderProcessHandler)
   at CefSharp.BrowserSubprocess.Program.MainInternal(System.String[])
   at CefSharp.BrowserSubprocess.Program.Main(System.String[])

**Comment by netmaxik** [comment]
Will test same code with 91.1.211

**Comment by amaitland** [comment]
> Exception Info: System.NullReferenceException
> at .CefSharp.BrowserSubprocess.CefAppUnmanagedWrapper.OnBrowserCreated(CefSharp.BrowserSubprocess.CefAppUnmanagedWrapper*, scoped_refptr_, scoped_refptr_)
> at .CefExecuteProcess(CefMainArgs*, scoped_refptr_, Void_)
> at CefSharp.BrowserSubprocess.SubProcess.Run()
> at CefSharp.BrowserSubprocess.BrowserSubprocessExecutable.Main(System.Collections.Generic.IEnumerable`1<System.String>, CefSharp.RenderProcess.IRenderProcessHandler)
> at CefSharp.BrowserSubprocess.Program.MainInternal(System.String[])
> at CefSharp.BrowserSubprocess.Program.Main(System.String[])

Thanks, that gives me somewhere to start.

**Comment by amaitland** [comment]
With https://bitbucket.org/chromiumembedded/cef/issues/3123/convert-legacy-ipc-messages-to-mojo the `extraInfo` param can now be null for popups. We need to adjust the code in [CefAppUnmanagedWrapper::OnBrowserCreated](https://github.com/cefsharp/CefSharp/blob/cefsharp/91/CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.cpp#L95)

**Comment by amaitland** [comment]
This should now be fixed in commit https://github.com/cefsharp/CefSharp/commit/20dad8aced51e077780ce3fe3b9a3766c15a7102
