### ISSUE TITLE
Cookie Header added

### ISSUE THREAD

**Issue by bbday** [cefsharp/CefSharp#3673]
I notice cef add cookies on request (when not necessary) by it self if use "interceptor"

```
class FRequestHandlerFactory : IResourceRequestHandlerFactory
{
        public FRequestHandlerFactory ()
        {
            InterceptorData = new InterceptorHandler();
        }

        public bool HasHandlers => true;

        public InterceptorHandler InterceptorData { get; }

       public IResourceRequestHandler GetResourceRequestHandler(...)
       {
            return Interceptor; //auto add cookie header
                   
            //return null; //normal behavior without cookie like real chrome
        }
}
```
            
```
class InterceptorHandler : ResourceRequestHandler
    {
    private MemoryStream _memoryStream;
    
    protected override void OnResourceLoadComplete(IWebBrowser chromiumWebBrowser, IBrowser browser, IFrame frame, IRequest request, IResponse response, UrlRequestStatus status, long receivedContentLength)
        { ... }
        
        protected override IResponseFilter GetResourceResponseFilter(IWebBrowser chromiumWebBrowser, IBrowser browser, IFrame frame, IRequest request, IResponse response)
        {
            _memoryStream = new MemoryStream();
            return new CefSharp.ResponseFilter.StreamResponseFilter(_memoryStream);
        }
    }
```

Test to replicate issue: **https://reqbin.com/req/v0crmky0/rest-api-post-example**
if you click send a generic packet and intercept it /api/v1/requests call you will see if no Intercept class not have cookie in request header and have it if you enable Interceptor class.
_Look like while using ResourceRequestHandler class auto add Cookie header for request made by Javascript_

Img 1 with interceptor class show cookie: [Img1](https://postimg.cc/DSnvPnFW)
Img 2 without interceprtor class not have cookie [Img2](https://postimg.cc/0zn8tF2V)

**Comment by amaitland** [comment]
CEF has it's own support forum at https://magpcss.org/ceforum/index.php

CefSharp doesn't add any headers.

**Comment by amaitland** [comment]
Should you wish to do some debugging yourself then I'd probably start looking in the following:

https://github.com/chromiumembedded/cef/blob/4472/libcef/browser/net_service/resource_request_handler_wrapper.h
https://github.com/chromiumembedded/cef/blob/4472/libcef/browser/net_service/resource_request_handler_wrapper.cc

Once you post on https://magpcss.org/ceforum/index.php please post a link back here for reference.

**Comment by bbday** [comment]
https://magpcss.org/ceforum/viewtopic.php?f=18&t=18494
