### ISSUE TITLE
Net 5.0 - SelfContained Cannot use file stream CefSharp.BrowserSubprocess.deps.json error in event viewer

### ISSUE THREAD

**Issue by johnendev** [cefsharp/CefSharp#3726]
- **What version of the product are you using?**
   v91.1.230 from Nuget

- **What architecture x86 or x64?**
   x86 and x64 both have the same crash

- **What version of .Net?**
   .Net 5.0

- **On what operating system?**
   Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
   OffScreen

- **What steps will reproduce the problem?**
    - [MinimalExample fork](https://github.com/0x0309/CefSharp.MinimalExample), converted to .NET 5. Note that this crash does not occur with the .NET Framework version of the MinimalExample, so it appears the bug is specific to .NET 5.
    - Run and it generates the image and pauses waiting for input
    - Press a key to continue
    - `Cef.Shutdown()` is called and a crash is logged in the windows event log for `CefSharp.BrowserSubprocess.exe`
![image](https://user-images.githubusercontent.com/20271944/127791107-3dbada12-badb-4f7d-a1d2-cc7519e5b6eb.png)

- **Please provide any additional information below.**
    - There are no exceptions in the host process and it continues to run. This is not like a crash where one has forgotten to dispose a browser instance and it crashes the host process as well during the shutdown call.
    - The cef browser log is empty.
    - Get the same behavior whether debugging in VS or running independently.
    - WER does not generate a dump file.

I tried to attach the VS debugger (with native debugging enabled) to each of the browser sub-processes before the crash, and VS just exits debug mode when `Cef.Shutdown()` is called.

Any ideas why this happens, or how to debug the sub-process to try get more details? E.g. where can I get the missing `deps.json` file and symbols?

**Comment by amaitland** [comment]
> MinimalExample fork, converted to .NET 5. Note that this crash does not occur with the .NET Framework version of the MinimalExample, so it appears the bug is specific to .NET 5

Please test with .Net Core/.Net 5 example already provided. 

https://github.com/cefsharp/CefSharp.MinimalExample/blob/master/CefSharp.MinimalExample.OffScreen/CefSharp.MinimalExample.OffScreen.netcore.csproj#L14

https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#unmanaged-crashes-when-the-process-dies

The pdb for the Browsersubprocess is included in the Nuget package, not copied by default. You can manually copy the file.

Check if crash_reporter.cfg is in the bin folder, if not manually copy it from the program root. Example should be updated to copy the file if it isn't already.

Run the example exe outside of visual studio. Crash pad should create a mini dump in C:\Users\[CurrentUser]\AppData\Local\CefSharp.MinimalExample\User Data, you can then get a stack trace from the mini dump.

**Comment by 0x0309** [comment]
> Please test with .Net Core/.Net 5 example already provided.

Didn't notice the other solution file sorry.

> Check if crash_reporter.cfg is in the bin folder, if not manually copy it from the program root. Example should be updated to copy the file if it isn't already.

It isn't, so created cefsharp/CefSharp.MinimalExample#135
<br/>

I've updated the [fork](https://github.com/cefsharp/CefSharp.MinimalExample) to replicate the crash on the existing netcore project instead. It doesn't crash out-of-the-box. The change which causes it to crash during shutdown is having `SelfContained=true`.
Crash pad still doesn't generate a dump file though, and VS doesn't break on any errors when attached to the sub-processes during shutdown, so not sure what to do from here.

**Comment by amaitland** [comment]
I quickly ran the .Net 5.0 OffScreen example with SelfContained set to true. I didn't get any crash on Shutdown.

Are you able to test on a machine with different hardware?

**Comment by johnendev** [comment]
Tested on a vm and same thing happens.

Did you check the windows application event log? It doesn't seem to be a regular crash, as there are no dump files and WER doesn't kick in. Just a message in the event log that a .NET Core application has failed. The host MinimalExample app doesn't crash, only the browser subprocess seems to have some kind of error.

The error is not logged when running the AnyCPU build, but it happens for both x86 and x64. The only difference I can think of which may be causing this is that the folder structure for the cef resources in AnyCPU builds is different from the other 2. Maybe having all the dlls in the same folder as the host app is causing some confusion during shutdown on the x86 and x64 builds. Also the fact that no dump file is created suggests it's not a crash, maybe it's just the dotnet core host trying to load that deps.json file during shutdown and the event is logged because it doesn't exist. Having that deps.json file may help get some more details but I don't know where to get it from as it's not included in the nuget package.

**Comment by amaitland** [comment]
Try adding a `Thread.Sleep(500)` before calling `Cef.Shutdown`.

**Comment by johnendev** [comment]
It's not time related. In the example fork you'll see I added a Console.ReadLine before the Shutdown call. Waiting for a minute still results in the same error.

**Comment by amaitland** [comment]
> The error is not logged when running the AnyCPU build, but it happens for both x86 and x64. The only difference I can think of which may be causing this is that the folder structure for the cef resources in AnyCPU builds is different from the other 2

I believe you'll find that when running from the subfolder the CefSharp.BrowserSubProcess.exe will be using the system installed .Net runtime. 

> Also the fact that no dump file is created suggests it's not a crash, maybe it's just the dotnet core host trying to load that deps.json file during shutdown and the event is logged because it doesn't exist. Having that deps.json file may help get some more details but I don't know where to get it from as it's not included in the nuget package.

The .deps.json file is optional, at least that's my understanding. See https://github.com/dotnet/cli/blob/master/Documentation/specs/runtime-configuration-file.md#what-produces-the-files-and-where-are-they


https://github.com/cefsharp/CefSharp/issues/3407#issuecomment-786416629 has some background information about the current structure (actually #3407 has lots of information about the differences in runtime versions and the testing done so far).

This use case might be a candidate for self hosting the browser sub process. See https://github.com/cefsharp/CefSharp/issues/3407#issuecomment-791074876

The OffScreen example hasn't been updated to include an example of self hosting the browser sub process, the fundamentals are the same as the WinForms version https://github.com/cefsharp/CefSharp.MinimalExample/blob/cefsharp/91/CefSharp.MinimalExample.WinForms/Program.PublishSingleFile.cs#L25

**Comment by amaitland** [comment]
Ultimately I think this has is a bug in the `.Net 5` runtime and should be lodged at https://github.com/dotnet/runtime

> MyApp.deps.json - A list of dependencies, compilation dependencies and version information used to address assembly conflicts. Not technically required, but required to use the servicing or package cache/shared package install features, and to assist during roll-forward scenarios to select the newest version of any assembly that exists more than once in the application and framework(s). If the file is not present, all assemblies in the current folder are used instead.

As https://github.com/dotnet/cli/blob/master/Documentation/specs/runtime-configuration-file.md#what-produces-the-files-and-where-are-they states the file isn't technically required then producing an error would appear to be the incorrect behaviour.

The error would appear to be produced at https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/native/corehost/json_parser.cpp#L138

If we need to include the `CefSharp.BrowserSubprocess.deps.json` file then that also means we need to include `CefSharp.BrowserSubprocess.runtimeconfig.json` which when I last tested was problematic for `PublishSingleFile` and some other scenarios  #3407. It is possible that the `.Net Runtime` has made improvements, that would require a substantial amount of testing though.

**Comment by amaitland** [comment]
> The error would appear to be produced at https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/native/corehost/json_parser.cpp#L138

It doesn't appear that an actual exception is occurring, it's simply logging an error to the `EventViewer`.

**Comment by amaitland** [comment]
I've updated the [CefSharp.MinimalExample.OffScreen](https://github.com/cefsharp/CefSharp.MinimalExample/tree/master/CefSharp.MinimalExample.OffScreen) to demo `Self Hosting` the `BrowserSubProcess` when `PublishSingleFIle=True` in commit https://github.com/cefsharp/CefSharp.MinimalExample/commit/5d0c8ee766927cf8bf397e925709bcec145ea47f

The same technique can be used to self host the `BrowserSubProcess` in this scenario. It's important to note that `crash_reporter.cfg` needs to be updated to remove the `ExternalHandler` line otherwise the `CefSharp.BrowserSubprocess.exe` will be used for `Crash Reporting` and you'll still see this error.

```ini
#Example crash_reporter.cfg for use when self hosting the `BrowserSubProcess`
#Dumps will be generated in C:\Users\[CurrentUser]\AppData\Local\[AppName]\User Data
[Config]
ProductName=CefSharp.MinimalExample.OffScreen
ProductVersion=1.0.0
AppName=CefSharp.MinimalExample
```

I'm going to close this now. If `Microsoft` come back stating that the `.deps.json` file is now strictly required then we can reopen this.

**Comment by alextrxtrx** [comment]
@amaitland Hello! I have this problem too. I use self-contained build of my app, which uses CefSharp (102.0.100). Also I use auto update function for my app. When my app check update (timer) and update is available I call Application.Restart for start update. Very often I have error in event viewer:

![image](https://github.com/cefsharp/CefSharp/assets/46885464/1c4e9bb7-a729-4b6b-9039-517007f77892)

When I call Application.Restart also I call Cef.Shutdown before correctly, but error still here. If I look this error in event viewer it means that my application doesn't restart but close with error.

**Comment by amaitland** [comment]
As stated above you need to `SelfHost` the `BrowserSubProcess`.

Additional instructions at https://github.com/cefsharp/CefSharp/wiki/SelfHost-BrowserSubProcess
