### ISSUE TITLE
Can we build CEFSharp with Openh264

### ISSUE THREAD

**Issue by schandra09net** [cefsharp/CefSharp#3727]
Hello Team,

I have followed the procedure to build CEF with proprietary codecs with **v91.1.230** and was able to succeed (My only one requirement is to play video's from any webistes, when they are clicked/opened). The browser is now playing the videos without any issues (Like links from Youtube, Vimeo, NDTV news, etc. with MP4 or MP3). 

While reading the articles associated with CEF and H.264 requires MPEG.LA license(which is tideous, my opinion), and there is an alternative to it, that is CISCO OpenH264, which is not having any license cost associated to it.

If yes, can we build **CEF v91.1.230 with OpenH264** and the what is process associated with it.

Any help/guidance from the commuity is very much appreciated.

Thanks.

**Comment by amaitland** [comment]
> If yes, can we build CEF v91.1.230 with OpenH264 and the what is process associated with it.

To much knowledge this is not possible. 

CEF has it's own support forum at https://magpcss.org/ceforum/index.php

**Comment by amaitland** [comment]
Asked at https://magpcss.org/ceforum/viewtopic.php?f=18&t=18556

Confirming this is not supported.
