### ISSUE TITLE
Add Cef.IsShutdown property to allows checks for shutdown state

### ISSUE THREAD

**Issue by jozefizso** [cefsharp/CefSharp#3782]
**Describe the solution you'd like**
We miss a property to check if Cef was already shutdown in the process. As we are developing an addin which may be run along side other plugins which may call `Cef.Shutdown()` outside of our control, we would like to check for the Cef status using a property instead of catching an exception.

**Describe alternatives you've considered**
We may try/catch some calls to Cef for the exception with test `Cef.Shutdown has already been called.`. As this  is a generic exception it is hard to distinguish it from other exception states in the app.

**Additional context**
None.

**Checklist:**
- [x] I have reviewed the [CEF API](https://magpcss.org/ceforum/apidocs3/index-all.html) and have confirmed the feature I'm requesting is possible.
- [ ] The Feature I'm requesting is an improvement to Async Javascript Binding (No new feature are being added to the Sync Javascript binding)
- [ ] An open `PR` exists on the [CEF Pull Requests](https://bitbucket.org/chromiumembedded/cef/pull-requests/) and I'd like to propose this feature is added to `CefSharp` when/if it's merged.

**Comment by amaitland** [comment]
Seems reasonable. Pull requests welcome.
