### ISSUE TITLE
CefSharp 90 on .NET Framework 4.0

### ISSUE THREAD

**Issue by cuchma19** [cefsharp/CefSharp#3788]
How to make CefSharp 90 work on .NET Framework 4.0 and Windows XP?
I need to create a browser for Windows XP with its own interface
I am used to working with WinForms and WPF. And they are simple for me

**Comment by amaitland** [comment]
> How to make CefSharp 90 work on .NET Framework 4.0 and Windows XP?

You cannot, Chromium removed support for Windows XP years ago. Even if you downgraded CefSharp to .Net 4.0 it still wouldn't work.

In future please use discussions to ask questions. 

https://github.com/cefsharp/CefSharp/discussions
