### ISSUE TITLE
RFC: Change examples to use async/await pattern + drop VS2010 compatibility

### ISSUE THREAD

**Issue by perlun** [cefsharp/CefSharp#381]
Hi,

One question that has arisen after the discussion we had in #373 (as to the "be or not to be" for a locking-synchronous-Task-Wait-based approach), and the suggested approach for these kind of things for the future, is the way we we should recommend that these kind of things be done.

I mean, normally if you would have a method like this:

    Task<string> GetSourceAsync()
    {
        return "foo";
    }

...which you would then call perhaps like this:

    string source = await GetSourceAsync();

All fine and dandy. Only one problem:

1. This requires VS2012 or newer, *and*
1. It requires .NET 4.5, or the use of [Microsoft.Bcl.Async](https://www.nuget.org/packages/Microsoft.Bcl.Async/) which works quite well actually (using it personally).

In any way, I feel that since this is the "preferred approach" that we want to recommend people to use, it would be good if we would use it ourselves. :smiley: So, here's my recommendation:

1. We drop support for VS2010, and only support 2012 and 2013 onwards.
1. We upgrade the example projects to use .NET 4.5, so we can go with `async`. **Note**: only the example projects; CefSharp still needs to be .NET 4.0 for a little while, since there might be user's who cannot upgrade to .NET 4.5 so easily (I happen to be one of them. :wink:)

Comments?

**Comment by amaitland** [comment]
For version `39` I'm going to upgrade the examples to `.Net 4.5`. The core libraries are still `.Net 4.0`.

It's ticked over to `2015`, so I think it's time, specially with the release of `VS 2013 Community Edition` allowing small companies and open source contributors free access to the equivalent of `VS 2013 Professional`

http://www.visualstudio.com/en-us/news/vs2013-community-vs.aspx

**Comment by amaitland** [comment]
Commit https://github.com/amaitland/CefSharp/commit/fc65192e4252bd3ccbf4b82eb09b392fb016ff82 resolves this Issue.

**Comment by perlun** [comment]
Great, thanks! I think we should not bump the core libraries to .Net 4.5 yet, unless it really causes problems for us to have them on 4.0.

As for me - has been extremely unavailable from the project for the last few months. Will maybe come in for a minor return within the next few months, since we will start upgrading to CefSharp3 (i.e. 37 or 39 or whatever the version is nowadays. :smile:) But anyway, don't count on me as a "major" contributor this year, but more a minor collaborator amongst the peers.

**Comment by jornh** [comment]
Agree! (on the 4.0 vs 4.5 situation)

Anyho' good to "hear" from you @perlun :+1: ... I'm also still mostly lurking in the background :dizzy_face: and @amaitland + a few other semi-regular contributors have recently done **a lot** of good work!
