### ISSUE TITLE
Wishlist: Be able to access Javascript objects using DynamicObject and dynamic

### ISSUE THREAD

**Issue by perlun** [cefsharp/CefSharp#382]
This one would be very cool. The idea is to expose the whole Javascript object model using the C#/CLR `dynamic` feature, so that you can do something remotely similar to this:

```
dynamic obj = ChromiumWebBrowser.GetObject("window");
obj.Alert("Hello World!");
```

The same "name mangling" that we already have for Javascript methods (#310) should be used here also, so that you can access camelCase() methods using CamelCase(). In case the method is actually defined as CamelCase on the Javascript side, it should also work (so we may have some case clash issues to take into account).

This would also provide for very cool integration scenarios like this:

```
dynamic element = await (Task<dynamic>)ChromiumWebBrowser.ExecuteScript("document.getElementById('foo')");
string html = element.innerHtml;
```

Wouldn't that just be **so cool**? :smiley:

**Comment by midas643** [comment]
I've just tried it too:
    async void browser1_FrameLoadEnd(object sender, FrameLoadEndEventArgs e)
    {
        if(e.Frame.IsMain)
        {
            var jsResponse = await e.Frame.EvaluateScriptAsync("document");
            var document = (JavascriptObject)response.Result; // JavascriptObject from CefSharp.Internals
            // or dynamic document = response.Result; 
            var cookies = document.cookie;
        }
    }

**Comment by amaitland** [comment]
@midas643 If you have some ideas, then a `PR` that implements this would be most welcome :+1:
