### ISSUE TITLE
please compile cefsharp for win arm32v7.

### ISSUE THREAD

**Issue by wmjb** [cefsharp/CefSharp#3821]
win-arm64 support exists, please compile runtimes so we can use cefsharp with win-arm32v7 projects.

**Comment by amaitland** [comment]
Closing as there is no upstream support for the ARM32 platform on Windows.

**Comment by wmjb** [comment]
thanks for looking into it, it's such a shame microsoft have dropped arm32.. there are thousands of arm32 devices running on a leaked arm32 build 15035 of windows 10, that could do with a new browser update and cef/net3.1 could have provided this if we had runtime binaries at least for arm32.  thanks.

**Comment by amaitland** [comment]
For what it's worth CEF supports ARM32 on Linux, you can download precompiled builds from https://cef-builds.spotifycdn.com/index.html#linuxarm
