### ISSUE TITLE
Feature Request - Publish XML documentation in net core nuget package

### ISSUE THREAD

**Issue by SchreinerK** [cefsharp/CefSharp#3843]
at least CefSharp.Wpf.NETCore package contains no *.xml file with the documentation.

_I wonder why this is not included by default. No developer wants to work without context help and when you're new, that's even more needed. The cumbersome search on the web should actually be a thing of the past with modern IDE._

**Comment by amaitland** [comment]
Blocked on https://github.com/dotnet/sdk/issues/1458

**Comment by amaitland** [comment]
For reference the `API Docs` are available online at https://cefsharp.github.io/api/

xml files added to the packages in commit https://github.com/cefsharp/CefSharp/commit/6953d82f250f420ad6cb5d79bbad0285b0fe26f6

If/when https://github.com/dotnet/sdk/issues/1458 is resolved the files will be come available. I've not tried any of the workarounds listed.
