### ISSUE TITLE
Core - V8Serialization incorrectly returns negative numbers

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#3858]
The types of these properties are inferred by the `SerializeV8Object` method in [`CefSharp.BrowserSubprocess.Core\Serialization\V8Serialization.cpp`](https://github.com/cefsharp/CefSharp/blob/cefsharp/94/CefSharp.BrowserSubprocess.Core/Serialization/V8Serialization.cpp#L43).

If setting a numeric property's value to something that fits into 32 bits, the property's type is inferred to be `System.Int32`.
If the value is greater than 2147483647 (which is 2^31-1) then the value is mistakenly interpreted to be a negative number:
- `2147483647` is correctly seen as `2147483647`
- `2147483648` is **in**correctly seen as `-2147483648`
- `2147483649` is **in**correctly seen as `-2147483647` and so on

One can easily test this by evaluating the following code in the CefSharp.Wpf.Example project, under "Evaluate Javascript (Async)"
`(() => { var a = { s: 2147483648 }; return a.s; })()`
and see that the result is a negative number.

@amaitland has suggested a workaround in a discussion in [Gitter](https://gitter.im/cefsharp/CefSharp):
```
[...]
else if (obj->IsInt())
{
    //CEF Doesn't differentiate between UINT and INT
    //so we have to do some additional bounds checking
    //To make sure the correct value is returned
    auto uIntVal = obj->GetUIntValue();
    if (uIntVal > INT_MAX)
    {
        //We have to use double as there is no IPC support
        //for UInt
        list->SetDouble(index, obj->GetDoubleValue());
    }
    else
    {
        list->SetInt(index, obj->GetIntValue());
    }
}
[...]
```
which does the trick in both the code I posted above, and my team's specific case.
Seeing as Javascript [always treats numbers as double](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number) anyway, is there a reason not to apply the suggested fix?

 I can create a pull request if need be, just wondering if/what I'm missing.

Thanks!

_Originally posted by @riprwwa in https://github.com/cefsharp/CefSharp/discussions/3853_

**Comment by amaitland** [comment]
https://github.com/amaitland/CefSharp/commit/076e321beb806830584b778acfe83c69d20441d8 has a slightly different set of checks to determine if the value is an int otherwise return a double.

A seperate test class should be added that initializes one browser instance rather than a new browser per piece of test data.
We'll also need to add a test that deals with comparing doubles with some degree of precision. `xUnit` looks like it has `Assert.Equal` overload for doubles with precision.

**Comment by amaitland** [comment]
The fix is included in [95.7.140-pre](https://github.com/cefsharp/CefSharp/issues/3866#issuecomment-955950545) which is now available for testing. A new stable release will follow shortly.

---

If you are using `CefSharp` in a commercial product and not already a sponsor then please consider [supporting](https://github.com/cefsharp/CefSharp#financial-support) my efforts. Developing/maintaining/supporting the project takes a considerable amount of time.

**Comment by riprwwa** [comment]
Thank you!
Also, I hope we can work something out to support you.

**Comment by amaitland** [comment]
> I hope we can work something out to support you.

Greatly appreciated 😄
