### ISSUE TITLE
cefsharp3 countn't play flash.how can i solve the problem？

### ISSUE THREAD

**Issue by tuablove** [cefsharp/CefSharp#386]
i used cefsharp1 for some times.it play flash well,but cefsharp1 countn't play local flash,
e.x: file:///C:/Users/tobin/Desktop/flash.swf. cefsharp1 even cannot load it.
so.i try to update to cefsharp3 ,but frist problem is i cannot play flash,even in network.
i cann't find the settings like "plugin path" in CefSettings. and  also i create folder named plugins in outdir is also play out .

that two questions :
fri. How Can I play a swf using flash player in cefsharp3?
sec.cefsharp3 can load local swf and play it well?

wish your answer!

**Comment by naveen1941** [comment]
I am using CefSharp.Wpf.Example, But still i am not able play any flash files. Both online and local files?
