### ISSUE TITLE
Application crash when signing out off windows

### ISSUE THREAD

**Issue by RachidiL** [cefsharp/CefSharp#3865]
### Bug Report
Delete this line and everything above, and then fill in the details below.

- **What version of the product are you using?**
    - What version are you using? Nuget? CI Nuget? build from a branch? If so please link to the relevant commit.
    https://github.com/cefsharp/CefSharp/releases/tag/v94.4.50
	- Please include the exact version number you are using: v94.4.50 ; Chromium 94.0.4606.71

- **What architecture x86 or x64?**
    x64
	
- **What version of .Net?**
    .Net 4.x
    
- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WPF
    
- **What steps will reproduce the problem?**
We have an MFC-application and use CefSharp.WPF to display the Chromium Webbrowser to 
enable users to use the Webbrowser in our application. As of v92 there was a change in the class ConcurrentMethodRunnerQueue. 
Previously, in the method ConcurrentMethodRunnerQueue::Enqueue, tasks were started using the method Task.Start which scheduled the task on the current TaskScheduler, which means the task was run on a different thread than the main thread.See left side of the screenshot. 

![code_snippet](https://user-images.githubusercontent.com/46988716/139209978-07f42712-7774-4fbe-8e23-c93822643d8c.png)

With the changes in v92, the method schedules the task on the thread pool, this has the effect that the task is run on the main thread. 

Now to my problem: With the above mentioned changes in v92, when a user has our application running and clicks on sign out from the current Windows session, there is an exception thrown on the main thread(and not anymore on a different thread) due to the above mentioned facts and this crashes our application. This means that the application is not closed properly. 
After signing in and starting the application, we get error messages that says that the application was not shut down properly, which can cause database-related problems. 

In v91 and downwards, this did not happen... 

- **What is the expected output? What do you see instead?**
It should not crash the application, when signing out off windows.

**Comment by amaitland** [comment]
> Queues the specified work to run on the ThreadPool and returns a task or Task<TResult> handle for that work.

As per [Task.Run](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.run?view=net-5.0) the task will be queued on the `ThreadPool`.

Looking at the [.Net Reference Source](https://referencesource.microsoft.com/#mscorlib/system/threading/Tasks/Task.cs,5faac53c590b086f) and `TaskScheduler.Default` is also used for `Task.Run`

So the changes made in commit https://github.com/cefsharp/CefSharp/commit/4ab6d2ad25cb0dc19ced4dc0dad040a863c1a616#diff-df112b02559a8f6e4974da2943e081757cde96d23e5e7ec39ffcf3ab70a10de3 should also queue the `Task` for execution in the `ThreadPool`.

I need a stack trace and or an example that clearly reproduces the problem (preferably both).
