### ISSUE TITLE
Cant input Chinese

### ISSUE THREAD

**Issue by Ms-Kelly-Yu** [cefsharp/CefSharp#3883]
cef version
<PackageReference Include="CefSharp.Wpf.NETCore" Version="93.1.111" />
win10   *64  WPF
sometimes can input chinese, sometimes cant.
when I pressed a outter button then came back to the browser,  the browser will cant intput chinese.

**Comment by amaitland** [comment]
Closing as duplicate of #1262

**Comment by ChanceLai** [comment]
It is still present in the new version（v94.4.110）

**Comment by amaitland** [comment]
> It is still present in the new version（v94.4.110）

This is an old unsupported version. 

IME is not enabled by default see https://github.com/cefsharp/CefSharp/issues/1262#issuecomment-659294710

**Comment by ChanceLai** [comment]
`            _browser.WpfKeyboardHandler = new CefSharp.Wpf.Experimental.WpfImeKeyboardHandler(_browser);
`
 I've added this code.

**Comment by ChanceLai** [comment]
> > It is still present in the new version（v94.4.110）
> 
> This is an old unsupported version.
> 
> IME is not enabled by default see [#1262 (comment)](https://github.com/cefsharp/CefSharp/issues/1262#issuecomment-659294710)

_browser.WpfKeyboardHandler = new CefSharp.Wpf.Experimental.WpfImeKeyboardHandler(_browser);
I've added this code.

**Comment by amaitland** [comment]
You also need to upgrade to a newer version .

**Comment by ChanceLai** [comment]
> You also need to upgrade to a newer version .

upgrade to v100.0.140.
In  one week's use, there is still the problem of being unable to input Chinese

**Comment by amaitland** [comment]
All problems with IME should be reported on https://github.com/cefsharp/CefSharp/issues/1262 providing sufficient detail so someone else can reproduce the problem.
