### ISSUE TITLE
Core - Infinite recursion when calling ExecuteScriptAsync

### ISSUE THREAD

**Issue by s-ve** [cefsharp/CefSharp#3914]
Due to [this recent refactoring](https://github.com/cefsharp/CefSharp/commit/b72d41353e6e9c964a51ea66c5aaad2527f9a383#diff-365a64085d19bad852c00c0769656b9a2deb678b74ac09807fe102e1f9787b72R501), this `ExecuteScriptAsync` [overload](https://github.com/cefsharp/CefSharp/blob/b72d41353e6e9c964a51ea66c5aaad2527f9a383/CefSharp/WebBrowserExtensions.cs#L476) now calls itself infinitely.

- **What version of the product are you using?**
    96.0.141

- **What architecture x86 or x64?**
    x64
	
- **What version of .Net?**
    .Net 6.0
    
- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WinForms
    
- **What steps will reproduce the problem?**
    - Call the method `WebBrowserExtensions.ExecuteScriptAsync(this IWebBrowser browser, string methodName, params object[] args)`

- **What is the expected output? What do you see instead?**
    - Calling this method causes an infinite loop and crashes the program.

**Comment by amaitland** [comment]
Thanks, if all goes well I'll release an updated version later today.
