### ISSUE TITLE
WinForms - NullReferenceException in ChromiumWebBrowser.OnHandleDestroyed 

### ISSUE THREAD

**Issue by SirSparkles** [cefsharp/CefSharp#3931]
- **What version of the product are you using?**

96.0.142

- **Are you using `WinForms`, `WPF` or `OffScreen`?**

WinForms

---
StackTrace

```
System.NullReferenceException: Object reference not set to an instance of an object. at CefSharp.WinForms.ChromiumWebBrowser.OnHandleDestroyedInternal() at CefSharp.WinForms.ChromiumWebBrowser.OnHandleDestroyed(EventArgs e) at System.Windows.Forms.Control.WmDestroy(Message& m) at System.Windows.Forms.Control.WndProc(Message& m) at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

See https://github.com/TV-Rename/tvrename/issues/871 for the stack trace we received in our app

**Comment by amaitland** [comment]
I've added a basic check that should avoid the `NRE`. It's still possible your code might have some problems, without an example that reproduces the problem I can only speculate.

Best guess would be that `OnHandleDestroyed` is being called before the underlying `CEF Browser` is actually created (`CreateBrowser` is async call). Reparenting the the underlying `CEF Browser` simply wouldn't be possible in this case.

Are you moving the `ChromiumWebBrowser` to a different parent when this happens?

**Comment by SirSparkles** [comment]
Looking through the logs there does seem to be a higher proportion of this error occurring when the program is run in headless mode (the UI is still created, but hidden). They also occur with in 1-4 seconds of application starting, so probably it has not had time to fully initialise yet?

**Comment by amaitland** [comment]
> They also occur with in 1-4 seconds of application starting, so probably it has not had time to fully initialise yet?

Seems likely. What causes the handle to be recreated?
