### ISSUE TITLE
WPF - Error if click over 4 time

### ISSUE THREAD

**Issue by mountrivers** [cefsharp/CefSharp#3940]
- **What version of the product are you using?**
 Build from branch 4664

- **What architecture x86 or x64?**
 x64
	
- **What version of .Net?**
 .Net 4.6.1
    
- **On what operating system?**
    win 10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF
    
- **What steps will reproduce the problem?**
   Just click anything more than 4 times like double click
- **Please provide any additional information below.**

```
[1231/124738.468:FATAL:event.cc(601)] Check failed: 3 >= click_count (3 vs.  4)
```

**Comment by amaitland** [comment]
> What version of the product are you using?
Build from branch 4664

Are you using an official release? If so what is the exact version. If you've built a custom version does the problem reproduce with an official release?

Please test with https://github.com/cefsharp/CefSharp.MinimalExample

**Comment by mountrivers** [comment]
i was using build with debug64. But after I use release64  the problem was solved

**Comment by amaitland** [comment]
A quick look at the `Chromium` source and it appears you were hitting the `DCHECK` at https://source.chromium.org/chromium/chromium/src/+/main:ui/events/event.cc;l=600

The `upstream` documentation for [SendMouseClickEvent](https://github.com/chromiumembedded/cef/blob/a7bbd8a62bfc91b0d53eeef8d07b64a5ed719a5f/include/cef_browser.h#L680) doesn't actually mention `click_count`. Looking at the `Chromium` source and it would appear that only single, double and triple (1, 2, 3 respectively) are supported.

https://source.chromium.org/chromium/chromium/src/+/main:ui/events/event.h;l=540?q=SetClickCount&sq=&ss=chromium

Whilst it's only a `DCHECK` and won't ever crash in a release build I've updated to send `click count` of `1` of greater than `3`. Potentially we could make further improvements if a valid use case presents itself.

> i was using build with debug64

Debug builds should only be used for actual debugging of `Chromium`.
