### ISSUE TITLE
WPF - Drag&Drop feature inside canvas does not handle DragEnd event

### ISSUE THREAD

**Issue by diakov193** [cefsharp/CefSharp#3941]
- **What version of the product are you using?**

   87 and higher

- **What architecture x86 or x64?**
    
x86/x64
	
- **What version of .Net?**
   
 .Net 4.x
    
- **On what operating system?**
    
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**

WPF
    
    
- **What steps will reproduce the problem?**

    You can test using WpfMinimalExample and this testing app: https://cefsharp-drag-end-issue.vercel.app/

- **What is the expected output? What do you see instead?**

It works as expected on versions 81-86. Bot does not works as expected on versions 87+.

**Comment by amaitland** [comment]
> Drag&Drop feature inside canvas does not handle DragEnd event 

What DragEnd event are you referring to exactly? 

Have you tested with the CEF Sample application? 

> It works as expected on versions 81-86. Bot does not works as expected on versions 87+.

Most likely an upstream bug that would need to be raised at https://bitbucket.org/chromiumembedded/cef/issues?status=new&status=open

**Comment by diakov193** [comment]
> What DragEnd event are you referring to exactly?

In version 86 it was here: https://github.com/cefsharp/CefSharp/blob/cefsharp/85/CefSharp/IBrowserHost.cs#L166



> Have you tested with the CEF Sample application?

Yes, and issue appears in WPF example, in WinForms it works.

**Comment by amaitland** [comment]
> In version 86 it was here: https://github.com/cefsharp/CefSharp/blob/cefsharp/85/CefSharp/IBrowserHost.cs#L166

What do you mean? IBrowserHost has never had any events.

As the problem appears in version 87 you can bisect the commits and work out exactly which commit introduced the problem. 

https://github.com/cefsharp/CefSharp/tree/cefsharp/87

I suspect it's a CEF/Chromium update that changed the behaviour. 

> Yes, and issue appears in WPF example, in WinForms it works.

Did you test with the CEF Sample application as detailed in the bug report? You skipped that section. Refer to https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report



It's unclear what drag event you are referring so you'll have to do this yourself.
