### ISSUE TITLE
Callback that is never invoked causes other async callbacks to stop working

### ISSUE THREAD

**Issue by andulv** [cefsharp/CefSharp#3979]
- **What version of the product are you using?**
97.1.60

- **What architecture x86 or x64?**
x86 and x64
	
- **What version of .Net?**
net472
    
- **On what operating system?**
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF (also reproduced with WinForms)
    
- **What steps will reproduce the problem?**
The problem can be reproduced in CefSharp.Wpf.Example, by doing following changes

AsyncBoundObject.cs
```
public async Task<string> JavascriptCallbackEvalPromise(bool invokeCallback, string msg, IJavascriptCallback callback)
{
    System.Diagnostics.Debug.WriteLine("JavascriptCallbackEvalPromise callback.Id " + callback.Id);
    if(invokeCallback)
    {
        var response = await callback.ExecuteAsync(callback.Id, msg);
        //Echo the response
        return (string)response.Result;
    }
    else
    {
        return msg;
    }
}
```

BindTestsAsyncTask.html 
Replace last two lines of QUnit.test "JavascriptCallback EvalPromise:" with these
```
//Invoke C# method, and tell it to invoke supplied callback
const firstResult = await boundAsync.javascriptCallbackEvalPromise(true, "First call", callback);
assert.equal(expectedResult, firstResult, "Echo response after promise execution 1");

//Invoke C# method, and tell it to NOT invoke supplied callback
const secondResult = await boundAsync.javascriptCallbackEvalPromise(false, "Second call", callback);
assert.equal("Second call", secondResult, "Echo response after promise execution 2");

//Invoke C# method, and tell it to invoke supplied callback
const thirdResult = await boundAsync.javascriptCallbackEvalPromise(true, "Third call", callback);
assert.equal(expectedResult, thirdResult, "Echo response after promise execution 3");
```

- **What is the expected output? What do you see instead?**
I expect all three calls to javascriptCallbackEvalPromise to complete.
But the third call never completes. 

If I remove the second call or change it so that the callback actually is invoked, everything works as expected.

- **Please provide any additional information below.**
It seems to me like when a callback has been passed to a C# method but the callback is not invoked CefSharp enters a state where all further usage of async callbacks is not working.

When in this state I have noticed the following:
- The callback is invoked (awaited) from C# code (await callback.ExecuteAsync(callback.Id, msg)). 
- The callback (Javascript code) does its thing and ends with cefSharp.sendEvalScriptResponse(callbackId, true, response, true);
- But the C# code is still stuck at awaiting the callback (Task never completes at C# side)

This is the Debug Output from Visual Studio:
```
JavascriptCallbackEvalPromise callback.Id 1
Before Method Call:JavascriptCallbackEvalPromise
After Method Call:JavascriptCallbackEvalPromise
JavascriptCallbackEvalPromise callback.Id 2
Before Method Call:JavascriptCallbackEvalPromise
After Method Call:JavascriptCallbackEvalPromise
JavascriptCallbackEvalPromise callback.Id 3
Before Method Call:JavascriptCallbackEvalPromise
The thread 0x5564 has exited with code 0 (0x0).
```

**Comment by amaitland** [comment]
> The problem can be reproduced in CefSharp.Wpf.Example, by doing following changes

Rather than describe the code changes  please create a failing xunit test and submit a pull request.

**Comment by andulv** [comment]
Do you mean QUnit test? I can only reproduce this through Javascript, so I don't know how to use a xunit test for this issue.

I have also not been able to create an actual failing test. The tests I have created just don't run to completion and/or causes further tests that uses async callbacks to not complete.

I have made a fork with a new branch for reproducing this issue at [(https://github.com/andulv/CefSharp/tree/issue3979)]

Is this what you need? Should I submit this as a PR?

In this branch I have added a new QUnit test to BindingTestAsyncTask.html. This test passes a callback (ordinary callback, not async callback) to the C# method, but the callback is never invoked. The test passes, but it causes any following tests to hang (never complete) if they use async callbacks.

I added the new test before the existing "JavascriptCallback EvalPromise" test. And now the existing test never completes.

![image](https://user-images.githubusercontent.com/5376458/151259521-eb6e85c6-ca1c-4e28-b174-6230d0cb1b96.png)

**Comment by amaitland** [comment]
> Do you mean QUnit test? I can only reproduce this through Javascript, so I don't know how to use a xunit test for this issue.

No, I meant `XUnit`. There are a number of automated tests, some run the `QUnit` tests and others call scripts directly.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Test/JavascriptBinding/IntegrationTestFacts.cs

> In this branch I have added a new QUnit test to BindingTestAsyncTask.html. This test passes a callback (ordinary callback, not async callback) to the C# method, but the callback is never invoked

Passing a promise directly in the callback is not supported so this isn't a great reproduction. 

A quick look and it would appear if you don't execute the callback the internal Id's used to track the tasks between the different processes become out of sync.

If you don't plan on executing a callback then passing in `null` rather than a function pointer should workaround the problem.

**Comment by amaitland** [comment]
This should be resolved in commit https://github.com/cefsharp/CefSharp/commit/8b247a6a37e70ed1f3aa3eaf43663284838cab8e

**Comment by andulv** [comment]
Thanks a lot for quick response and fix!

Just got my company (Definit AS) to sign up for a sponsorship.

Keep ut the good work. :)

**Comment by amaitland** [comment]
Thank you! Greatly appreciated!

An updated version (97.1.61) has been pushed to nuget.org and should be available shortly.
