### ISSUE TITLE
about:blank in OnBeforePopup 

### ISSUE THREAD

**Issue by karlovm** [cefsharp/CefSharp#3997]
I'm sorry for skipping bug report form. It's just because the issue is independent. 

The Bug:
Sometimes the targetUrl in OnBeforePopup is about:blank and there is no way to get final url, but the default popup window works well. I've tried to use experimental code from Wpf Example, but there is no results.

You can reproduce it by opening yandex.ru, type vk.com and press enter on icon-styled result.

**Comment by amaitland** [comment]
In future please use discussions to ask questions. 

https://github.com/cefsharp/CefSharp/discussions
