### ISSUE TITLE
jQuery warning with event.returnVAlue is deprecated

### ISSUE THREAD

**Issue by pubblisoft** [cefsharp/CefSharp#402]
This is a known bug in JQuery 1.10.2. See the following links http://bugs.jquery.com/ticket/14599 http://bugs.jquery.com/ticket/14282

**Comment by amaitland** [comment]
Update to latest version of `jQuery 1` 

https://github.com/cefsharp/CefSharp/commit/679e5e70c777938e44f503ba66807d62b245b522
