### ISSUE TITLE
WPF:  When I use the Reload or Reload(ignoreCache) methods to Refresh I lose my bound objects.

### ISSUE THREAD

**Issue by kpartlow** [cefsharp/CefSharp#4020]
If you have bound objects and do a refresh then you lose those objects in the browser and it doesn't try to reregister the objects.

A work around is to use the ignoreCache flag when registering the object in HTML.

**Comment by amaitland** [comment]
Please edit your original question and fill out the bug report temple. 

https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report

**Comment by kpartlow** [comment]
Is there a way I can test the whether or not binding gets lost on reload using the ,net core WPF example?

**Comment by kpartlow** [comment]
What version of the product are you using?
97.1.61, but saw this in earlier version, too.
Tested this on both x64 and x86.


What version of .Net? <.Net 4.x/.Net Core 3.1/.Net 5.0>
.NET 3.1

On what operating system? <Win7/Win8.1/Win10>
Windows 10

Are you using WinForms, WPF or OffScreen? <WinForms/WPF/OffScreen>
WPF

What steps will reproduce the problem?

1)  Call to bind an object.  

    await CefSharp.BindObjectAsync('nameOfObject')
        .catch(err => console.log(err));
		
	All calls to bound object work.	

2)  Reload the page (our html will try and rebind object).

    All calls do not work.  I would expect it to grab the object our of the cache and work, but it does not.
	


Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?

	NOTE.  If we pass in the parameter to ignoreCache, this does seem to work.


Does this problem also occur in the CEF Sample Application

**Comment by amaitland** [comment]
> Is there a way I can test the whether or not binding gets lost on reload using the ,net core WPF example?

There are a number of test options available in the menu.

https://github.com/cefsharp/CefSharp/blob/cefsharp/98/CefSharp.Wpf.Example/MainWindow.xaml#L29

> If we pass in the parameter to ignoreCache, the object is rebound and works 

Please clarify. Do you mean Reload(true)?

**Comment by kpartlow** [comment]
So, I did a little more testing and figured this out.   I was calling the **`CefSharp.BindObjectAsync()`** from our WPF App.  I was doing this mainly to eliminate having to call our object on every page because we want it available on every page regardless.

I had seen somewhere on **StackOverflow** where you said we could listen for the` **LoadingStateChange**` and from there you could call `**Browser.ExecuteScriptAsync()**` with the following:

```
		@"(async function ()
		{
			await CefSharp.BindObjectAsync('objectName');
		})();";
```

to add our object to every page.  The page used to look like this:

```
<html>
<head>
    <title>title</title>
    // stylesheets, etc.
</head>
<body>

<script type="module">
    import { moduleThatUsesBoundObject } from 'http://somewhere';

    (async () => {

// I wanted to eliminate having this on every page so this was removed.
		await CefSharp.BindObjectAsync('objectName');
		

        await Promise.all([
            moduleThatUsesBoundObject.initializeWindow(),
            moduleThatUsesBoundObject.addEventListeners()
        ])
    })()
    .catch(error => {
        console.log(error);
    })
    .finally(() => {
    });

</script>
</body>
</html>

```





What I found out is that the only time this would be called before my html javascript modules are loaded is in the case where the browser is being created (where _event.IsLoading_ is true in the **LoadingStateChanged** handler).

Once isLoading is false my javascript modules were already doing their work and accessing my object.

The problem with using that event handler is on a reload of the page you don't get the first event to the **LoadingStateChange**.  You only get the one after the browser has refreshed.  So I wasn't able to call CefSharp.BindObjectAsync before my javascript modules tried using it.

With some crafty debugging (I used Execute Script Async to send messages to the browsers console.log

```
        private void LogToBrowser(string log)
        {
            string script = @"(function () {
            console.log('" + log + "')})();";

            this.Browser.ExecuteScriptAsync(script);
        }
```

I was able to find this out....and find out that if I used the **FrameLoadStart** instead with transition types **Explicit** and **Reload** I could do what I wanted to do.  

Thanks for your work on this project, btw!!

**Comment by amaitland** [comment]
Thanks for the detailed analysis. 

> The problem with using that event handler is on a reload of the page you don't get the first event to the LoadingStateChange. You only get the one after the browser has refreshed. So I wasn't able to call CefSharp.BindObjectAsync before my javascript modules tried using it.

I'd suggest raising this on the CEF support forum at https://magpcss.org/ceforum/index.php

It's likely the chromium behaviour has changed at some point. At a minimum the documentation should be changed. 

https://github.com/chromiumembedded/cef/blob/4896/include/cef_load_handler.h#L64

> With some crafty debugging (I used Execute Script Async to send messages to the browsers console.log

You can add breakpoints in JavaScript using DevTools. 

Closing as upstream changes would be required to change the LoadingStateChange behaviour.
