### ISSUE TITLE
CefSharp.Core.dll dependencies could not be found

### ISSUE THREAD

**Issue by simonall** [cefsharp/CefSharp#409]
CefSharp works really great in my development environment, but fails to initialize on other people's computers. The exception they get is as following:
![image](https://cloud.githubusercontent.com/assets/7994519/3396662/08bd85b4-fd13-11e3-8f18-5d6bd1f68342.png)
Running dependency walker on CefSharp.Core.dll gives these errors:
![image](https://cloud.githubusercontent.com/assets/7994519/3396723/98fa784e-fd13-11e3-8d63-f4465b66277d.png)

Comparing to the errors I get through dependency walker, MSVCR120.DLL seems to be the only additional missing module.

This is how the folder structure looks like: http://puu.sh/9KJL9/f594b80a9a.png

Any ideas?

**Comment by clwm01** [comment]
Hey, simonall,you saved me from the suffering, I met the same problem as you described, but I didn't know what to do until i found "dependency walker"-you said above, so I can't wait to use "dependency walker" to detect what is missing.
Finally, I found that some dlls are missing, so I copied them from my dev-computer to the test-computer, then, everything goes well.
Thank all of you! :+1:
