### ISSUE TITLE
Desktop notification support

### ISSUE THREAD

**Issue by simonall** [cefsharp/CefSharp#410]
Is there any way to receive and display notifications using CefSharp?

I'm referring to these APIs specifically:
http://www.html5rocks.com/en/tutorials/notifications/quick/
https://developer.chrome.com/extensions/desktop_notifications
https://developer.chrome.com/extensions/notifications
https://developer.mozilla.org/en-US/docs/Web/API/notification

**Comment by AndrewBragdon** [comment]
Is this something we can add support for?

**Comment by rlmcneary2** [comment]
If you control the web page then the workaround would be to pass your own custom notification data from the JS runtime to the .Net runtime and then use .Net notification support (which I'm just assuming exists).

**Comment by seikosantana** [comment]
> If you control the web page then the workaround would be to pass your own custom notification data from the JS runtime to the .Net runtime and then use .Net notification support (which I'm just assuming exists).

What if we don't control the web page?
