### ISSUE TITLE
How to set default language and theme for devtools?

### ISSUE THREAD

**Issue by lusida** [cefsharp/CefSharp#4114]
When I call ShowDevToolsDocked to open the devtools panel, it always prompts "Always match Chrome^s language", and the current language setting will not be automatically applied. How can I set the default language and theme for devtools?

**Comment by amaitland** [comment]
You'll need to create an issue at https://bitbucket.org/chromiumembedded/cef/issues?status=new&status=open and post a link back here. CEF needs to add support. 

Closing as upstream,  can be reopened if CefSharp changes required.

**Comment by amaitland** [comment]
Upstream issue https://bitbucket.org/chromiumembedded/cef/issues/3334/how-to-set-default-language-and-theme-for
