### ISSUE TITLE
WPF - Page Unable to interact

### ISSUE THREAD

**Issue by Cashew-wood** [cefsharp/CefSharp#4144]
### Bug Report
Delete this line and everything above, and then fill in the details below.
- **What version of the product are you using?**
  version 102.0.9

- **What architecture x86 or x64?**
    x86 and x64
	
- **What version of .Net?**
    .Net 4.7.2
    
- **On what operating system?**
    Win11

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WPF
    
- **What steps will reproduce the problem?**
   use https://github.com/cefsharp/CefSharp/wiki/Quick-Start
- **What is the expected output? What do you see instead?**
Normal input, scrolling and operation
- **Please provide any additional information below.**
After the program runs, the Browser opens the Google page but cannot operate it (keyboard input/scroll/mouse click).
`<Window x:Class="WpfApp1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp1"
        xmlns:wpf="clr-namespace:CefSharp.Wpf;assembly=CefSharp.Wpf"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <Border Grid.Row="1" BorderBrush="Gray" BorderThickness="0,1">
            <wpf:ChromiumWebBrowser x:Name="Browser" Address="www.google.com"/>
        </Border>
    </Grid>
</Window>`
- **Does this problem also occur in the `CEF` Sample Application**
 use " cefclient.exe --multi-threaded-message-loop --no-sandbox --off-screen-rendering-enabled --enable-gpu" does not appear
Demo Project
[WpfApp1.zip](https://github.com/cefsharp/CefSharp/files/8929176/WpfApp1.zip)

**Comment by amaitland** [comment]
As per the bug report does the issue reproduce with the minimum example? 

https://github.com/cefsharp/CefSharp.MinimalExample

**Comment by amaitland** [comment]
> Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)

Did you check the log file?

**Comment by amaitland** [comment]
> WPF the browser stops redrawing when running on Intel Iris Xe Integrated GPU(11th Gen). Intel have released an updated driver, see https://www.intel.com/content/www/us/en/support/articles/000058136/graphics/graphics-for-11th-generation-intel-processors.html See https://github.com/dotnet/wpf/issues/3817 for workaround if you are unable to install the updated driver.

As per the known issues section of the release notes. 

Are you using an integrated Intel GPU?

**Comment by Cashew-wood** [comment]
I can use it normally after updating the latest version of GPU
