### ISSUE TITLE
Application freezes when clicking on browser through semi transparent form intercepting WM_NCHITTEST

### ISSUE THREAD

**Issue by imergu** [cefsharp/CefSharp#4183]
- **What version of the product are you using?**

103.0.120

- **What architecture x86 or x64?**

x64

- **On what operating system?**

Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**

WinForms

- **What steps will reproduce the problem?**

1. Start the MinimalExample.WinForms project from this fork: https://github.com/imergu/CefSharp.MinimalExample_Deadlock_WM_NCHITTEST
2. Click "Show an adorner form" in the toolstrip menu
3. Now click on the browser through the semi transparent form multiple times

- **What is the expected output? What do you see instead?**

Expected result: Nothing should happen, application should stay responsive
What happens instead: Application freezes after a few clicks

- **Please provide any additional information below.**

The issue originally occured in combination with DevExpress controls, which is why we submitted a support ticket here: https://supportcenter.devexpress.com/ticket/details/t1103456/documentmanager-adorneruimanager-cefsharpbrowser-application-freezes-when-clicking
(While it turns out DevExpress has nothing to do with the problem, the findings in this ticket may provide some additional insight.)

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

Page is not available anymore

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/wiki/General-Usage#multithreadedmessageloop

You'll need to integrate CEF into your apps existing message loop. HTTRANSPARENT is known to be problematic when using multiple threads. 

> The problem was a WM_NCHITTEST handler I had put in to accommodate the cropping UI. The cropping UI needs mouse clicks to go through the display, so the display code returns HTTRANSPARENT so that all mouse input propagates to the parent window. There is a warning in MSDN saying that this only applies to windows within the same thread, and it turns out that returning HTTRANSPARENT when your parent is on a different thread is indeed a very bad idea. What happens is that Windows has problems determining which window "owns" the mouse message, and keeps bouncing it back and forth between the threads, resending WM_NCHITTEST to the transparent window each time.

https://www.virtualdub.org/blog2/entry_147.html has a pretty good explanation of the problem. 

Closing as this is not something I can fix, applications wanting to use HTTRANSPARENT will need to integrate CEF into your apps existing message loop.
