### ISSUE TITLE
Feature Request - More Error Reporting for Error "Object Not Found Matching Id"

### ISSUE THREAD

**Issue by indeediansbrett** [cefsharp/CefSharp#4209]
**Describe the solution you'd like**
In `JavascriptObjectRespitory` there's an error thrown that says "Object Not Found Matching Id: `objectId`". We get this error on our Datadog logs, but have no idea what .net app that it came from or whom to contact regarding the issue. Is there any way to add additional context to the error? It would appear the user of this library is unregistering an object before it should be unregistered.

https://github.com/cefsharp/CefSharp/blob/445fb9ab2d178b55e3ca6561722d151ce3d9337e/CefSharp/Internals/JavascriptObjectRepository.cs#L293

**Describe alternatives you've considered**
This is what we get on our end in Datadog, so really have next to little information to go off of:
```
Uncaught "Object Not Found Matching Id:6"
No stack, consider using an instance of Error
```

**Additional context**

**Comment by amaitland** [comment]
You could easily add the method name and param count to the error message. Your welcome to submit a `Pull Request`.

**Comment by indeediansbrett** [comment]
Is there anything else we can add? Basically have people running our website inside their .net app, but we have no idea what .net app is running it. So we have zero traceability on how to prevent users from experiencing an error.

**Comment by amaitland** [comment]
Providing details of the host application may have unforeseen security implications. For now adding method name and param count should help developers track errors.

I'd suggest trying to obtain a call stack for the error from your logging tool.
