### ISSUE TITLE
Feature Request - Custom LibCefPath

### ISSUE THREAD

**Issue by bastianeicher** [cefsharp/CefSharp#4212]
I would love to have an option to specify a custom value for `Initializer.LibCefPath`. This would allow me to have multiple .NET applications installed in separate directories share a single copy of `libcef.dll` (and related files) to save space.

**Comment by amaitland** [comment]
> I would love to have an option to specify a custom value for `Initializer.LibCefPath`

As `LibCefPath` is used in the `Module Initializer` it's my understanding any direct attempt to set the property would result in the module initializer running first, the property would be set second.

You can manually call `NativeLibrary.TryLoad` and set `CefSettings.BrowserSubProcessPath` yourself which is basically all it does typically.

> This would allow me to have multiple .NET applications installed in separate directories share a single copy of `libcef.dll` (and related files) to save space.

Nothing stopping you from doing this now. Generally I'd recommend including `CefSharp.Core.Runtime.dll`, `CefSharp.dll` and the browser subprocess with `libcef.dll`. Then you only need to load `CefSharp.Core.Runtime.dll`.

I'm going to close this as I believe this would be problematic (and not necessary).
