### ISSUE TITLE
WinForms/WPF - PDF copy/paste not working via context menu

### ISSUE THREAD

**Issue by roybrand** [cefsharp/CefSharp#4224]
Hi

right click on copy, in pdf file, doesn't work,

ctrl c works

details:

- **What version of the product are you using?**
   104.4.240 Nuget

- **What architecture x86 or x64?**
    x86
	
- **What version of .Net?**
    4.6.2
    
- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WinForms && WPF
    
- **What steps will reproduce the problem?**
   Open any PDF file. Mark some text. Right click. Select 'Copy'
The issue is reproducible using the MinimalExample.

- **What is the expected output? What do you see instead?**
- I expect the selection to be copied to the clipboard. Nothing happens.

- **Please provide any additional information below.**
   No exceptions are thrown. Log shows nothing. Using the keyboard Ctrl+C does work.

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?

- **Does this problem also occur in the `CEF` Sample Application**
  yes

**Comment by amaitland** [comment]
Please edit your original question and fill out the bug report temple. See https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report

This is very likely a bug in CEF so make sure to test with the CEF Sample application, make sure to follow the instructions in detail.

**Comment by amaitland** [comment]
Thank you for filling out the bug report temple.

> Does this problem also occur in the CEF Sample Application
yes

Please create an issue at https://bitbucket.org/chromiumembedded/cef/issues?status=new&status=open and post a link back here.

Closing as upstream as this will need to be fixed in CEF.

**Comment by amaitland** [comment]
Potentially you could implement your own context menu handler and send key presses as a workaround. 

- http://cefsharp.github.io/api/104.4.x/html/M_CefSharp_Handler_ContextMenuHandler_OnContextMenuCommand.htm
- http://cefsharp.github.io/api/104.4.x/html/M_CefSharp_IBrowserHost_SendKeyEvent.htm

If you are using WPF there's already a ContextMenuHandler implementation you can extend https://github.com/cefsharp/CefSharp/blob/cefsharp/104/CefSharp.Wpf/Handler/ContextMenuHandler.cs#L173

**Comment by roybrand** [comment]
a new issue has been created:
https://bitbucket.org/chromiumembedded/cef/issues/3397/winforms-wpf-pdf-copy-paste-not-working

**Comment by amaitland** [comment]
This has reportedly been fixed `upstream`, changes available in `M109`.
