### ISSUE TITLE
Feature Request - Support The SendTouchEvent In Winform 

### ISSUE THREAD

**Issue by flowerlove** [cefsharp/CefSharp#4225]
Describe the solution you'd like
I would like to be able to use the SendTouchEvent feature in CEF from the WinForm browser.
Current the SendTouchEvent only support in WPF/OffScreenRender,I'm very curious what is the reason for this.

Describe alternatives you've considered
I use PostMessage or InjectInput to the CEF WinForm Window, But it does not work.

Additional context
I Use CefSharp 97.1.11 On Windows 10 21H2 Professional

**Comment by amaitland** [comment]
> I would like to be able to use the SendTouchEvent feature in CEF from the WinForm browser.

Closing as this is not something that can be directly implemented in CefSharp, changes would need to be made in [Chromium Embedded Framework](https://bitbucket.org/chromiumembedded/cef/). 

> Describe alternatives you've considered
I use PostMessage or InjectInput to the CEF WinForm Window, But it does not work.

CDP has https://chromedevtools.github.io/devtools-protocol/tot/Input/#method-dispatchTouchEvent which is worth trying. 

See https://github.com/cefsharp/CefSharp.Dom/blob/main/lib/PuppeteerSharp/Input/Touchscreen.cs#L33 for a basic example.
