### ISSUE TITLE
Hwndhost  Transparent support?

### ISSUE THREAD

**Issue by fallingrust** [cefsharp/CefSharp#4259]
I noticed that Microsoft's WebView2 WPF Control is a Win32 control wrapped in WindowsFormHost, but it supports Transparent.  Will CefSharp for wpf .hwndhost  or windowsform also support Transparent in the future

**Comment by amaitland** [comment]
CEF needs to add support you can subscribe to https://bitbucket.org/chromiumembedded/cef/issues/2315/allow-transparent-browser-for-windowed for updates. 

The CefSharp.Wpf implementation supports transparency.
