### ISSUE TITLE
CefSettings workable in v86 and not in v106

### ISSUE THREAD

**Issue by dddns** [cefsharp/CefSharp#4284]
Howdy,

I've been using this code to set some settings, till version 81.x worked, but now in 106.x, there's no error in edit mode, but the project doesn't start if I have this.
Any idea? If there new parameters?
Thanks in advanced,

        Dim settings As New CefSettings
        settings.LogSeverity = CefSharp.LogSeverity.Disable
        settings.CefCommandLineArgs.Add("disable-gpu", "1")
        settings.CefCommandLineArgs.Add("disable-gpu-vsync", "1")
        settings.CefCommandLineArgs.Add("disable-gpu-shader-disk-cache", "1")
        CefSharp.Cef.Initialize(settings)

**Comment by dddns** [comment]
I'm sorry, just replace:

        Dim settings As New CefSettings
to
        Dim settings As New CefSharp.WinForms.CefSettings

**Comment by amaitland** [comment]
In future please use discussions to ask questions.  Thanks. 

https://github.com/cefsharp/CefSharp/discussions

**Comment by dddns** [comment]
I'll, thank you,
