### ISSUE TITLE
Net Core - Unable to use Central Package Management

### ISSUE THREAD

**Issue by hhu-mahmoud** [cefsharp/CefSharp#4362]
The project need the Nuget Package : "CefSharp.Wpf.HwndHost" to be installed, but if I want to use the "Central Package Version Management" it throw always exception: 
"error NU1008: Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: CefSharp.Wpf.HwndHost.
15>Done building project "Application.csproj" -- FAILED."

To produce the exception:

1 - Create an empty project
2 - Add CefSharp and the Nuget Package "CefSharp.Wpf.HwndHost" 
3 - Use CPM => Create under "Solution Items" The CPM file "Directory.Package.props" and enable the "ManagePackageVersionsCentrally"
```xml
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="CefSharp.Common" Version="108.4.130" />
    <PackageVersion Include="CefSharp.Wpf.HwndHost" Version="108.4.130" />
    <PackageVersion Include="CefSharp.Wpf.NETCore" Version="108.4.130" />
  </ItemGroup>
</Project>
```

Then remove the Version of Nuget Packages from the "csproj"

4- Build the project and you will see the exception

**Comment by amaitland** [comment]
Please use [Fenced Code Blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to format code.

> The project need the Nuget Package : "CefSharp.Wpf.HwndHost" to be installed

Was it working when you just referenced `CefSharp.Wpf.NETCore`?

> "error NU1008: Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: CefSharp.Wpf.HwndHost.

Likely someone will need to reach out to the relevant `Microsoft` team for some guidance.

**Comment by hhu-mahmoud** [comment]
> Was it working when you just referenced `CefSharp.Wpf.NETCore`?

Yes it works also but with the same problem

I think, because this 3 Packages are automatically installed and locked with the CefSharp.Wpf.NETCore or CefSharp.Wpf.HwndHost =>

![grafik](https://user-images.githubusercontent.com/32834850/212469861-9ea75438-b05a-4d79-bdbf-5aef6e7f9b94.png)

**Comment by amaitland** [comment]
> Yes it works also but with the same problem

It's not clear if it works or not based on this statement.

> I think, because this 3 Packages are automatically installed and locked with the CefSharp.Wpf.NETCore or CefSharp.Wpf.HwndHost

Rather than speculate how about testing out your theory? Delete the entries from the `.targets` file in your `Nuget Cache`.

**Comment by ljdorey** [comment]
We're also Experiencing this, on a project that targets both NET48 and NET6.0, creates a super annoying restore loop in Visual Studio 2022 which is all kinds of pain.

**Comment by amaitland** [comment]
Make sure you've set a [RuntimeIdentifier](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#runtimeidentifier) as detailed in https://github.com/cefsharp/CefSharp/wiki/Quick-Start-For-MS-.Net-5.0-or-greater#20-set-a-runtimeidentifier-in-your-proj-file

**Comment by amaitland** [comment]
A quick test using https://github.com/cefsharp/CefSharp.Wpf.HwndHost as an example, adding `Central Package Management` support works as expected with the default configuration.

Commenting out the `RuntimeIdentifier` and I get a better error message.

```
NU1008	Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items:
chromiumembeddedframework.runtime.win-arm64;
chromiumembeddedframework.runtime.win-x64;
chromiumembeddedframework.runtime.win-x86;
```

The `PackageReference` entries are only added when no `RuntimeIdentifier` is specified

https://github.com/cefsharp/CefSharp/blob/2ee7e9d442217a76770ae6ceba276d076b6c5199/NuGet/PackageReference/CefSharp.Common.NETCore.targets#L144-L146

The `.targets` file will need to be updated, possibly try `VersionOverride` when `ManagePackageVersionsCentrally` is true.

Using a `RuntimeIdentifier` is the recommended approach.

> Just confirming now to see if applies to the standard and NetCore versions of the nuget packages but I believe that it does.

I've not seen anything to suggest this is the case.

**Comment by ljdorey** [comment]
Yup only the net core, I've added the identifier which was the root
problem, but that's causing issues with our cross targeting, but that's on
us, thanks for the help, the version override worked locally as a temp fix
as well.
