### ISSUE TITLE
WinForms - Reusing browser after closed Dialog in a new dialog

### ISSUE THREAD

**Issue by ma1982en** [cefsharp/CefSharp#4368]
- **What version of the product are you using?**
    - You can reproduce it with Version v107.1.120.

- **What architecture x86 or x64?**
    - x86
	
- **What version of .Net?**
    - .Net 4.x
    
- **On what operating system?**
    - Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - WinForms
    
- **What steps will reproduce the problem?**
    -  In this example, a ChromiumWebBrowser is inserted into a Windows.Form dialog after a button is clicked and the [www.google.com](http://www.google.com/) URL is loaded. The ChromiumWebBrowser is kept in a local instance, so I don't have to initialize the ChromiumWebBrowser control again when I press the button again. After the first button press and opening the Windows.Form dialog with the ChromiumWebBrowser control, I close the Windows.Form dialog. Now I click the button again. The local ChromiumWebBrowser instance is available and not disposed and shows no problem. In [TestCase 1] an attempt is made to load the URL immediately and this leads to a NullReferenceException. In [Testcase 2] the URL is only loaded when the Windows.Form dialog is fully displayed. [Test case 2] works perfectly.

    - Why does the URL call only work when the Windows.Form dialog is fully visible?

```c#

    private static ChromiumWebBrowser browser = null;

    /*
    [TestCase 1]
    */

    private void button_Click(object sender, EventArgs e)
    {
        var dialog1 = new Form();
        if (browser == null)
        {
            browser = new ChromiumWebBrowser();
            browser.Load("http://www.google.de/");
        }
        else
        {
            browser.Load("http://www.google.de/");

            /* System.NullReferenceException: 
            bool CefFrameWrapper::IsValid::get()
            {
                ThrowIfDisposed();
                return _frame->IsValid();
            }
            
            */
        }
        dialog1.Text = browser.GetHashCode().ToString();
        dialog1.Controls.Add(browser);

        dialog1.Shown += (oo, ee) =>
        {
            dialog1.Show();
            dialog1.BringToFront();
            dialog1.Refresh();
            browser.Load("http://www.google.de/");
        };

        try
        {
            dialog1.ShowDialog();
        }
        catch (Exception exception)
        {
            Console.WriteLine(exception);
        }
    }

    /*
    [TestCase 1]
    */

    private void button_Click(object sender, EventArgs e)
    {
        var dialog1 = new Form();
        if (browser == null)
        {
            browser = new ChromiumWebBrowser();
            browser.Load("http://www.google.de/");
        }
        else
        {
            //browser.Load("http://www.google.de/");
        }
        
        dialog1.Text = browser.GetHashCode().ToString();
        dialog1.Controls.Add(browser);

        dialog1.Shown += (oo, ee) =>
        {
            dialog1.Show();
            dialog1.BringToFront();
            dialog1.Refresh();
            browser.Load("http://www.google.de/");
        };

        try
        {
            dialog1.ShowDialog();
        }
        catch (Exception exception)
        {
            Console.WriteLine(exception);
        }
    }

```

- **What is the expected output? What do you see instead?**

- It should not raise a Nullreference Exception.

**Comment by amaitland** [comment]
Both your test cases are labeled **1**, so it's not clear which is supposed to work.

> * It should not raise a Nullreference Exception.

When the `Form` closed I suspect a `WM_Close` is sent to the native `CefBrowser` instance resulting in it being closed. 

If you plan on reusing the `ChromiumWebBrowser` instance then you need to remove it from the parent.

**Comment by amaitland** [comment]
> * Why does the URL call only work when the Windows.Form dialog is fully visible?

The `Handle` was destroyed when the Form `Closed`, when you show the dialog again a new `Handle` is created, subsequently a new `Chromium` instance is created.

Going forward we'll throw an `InvalidOperationException` if an attempt is made to call `Load()` when the underlying browser instance is invalid (in this case it's parent handled was destroyed).

I did consider setting the `initialAddress` when `IBrowser.IsValid == false`, I think an exception is more meaningful here.

As the intention is to reuse the `ChromiumWebBrowser` instance, removing it from the parent in [Form.Closing](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.form.closing?view=windowsdesktop-7.0) is the approach I'd recommend, this allows you to call `Form.Dispose()` to cleanup the resources you've allocated.

The other option would be to set [ChromiumWebBrowser.ParkControlOnHandleDestroyed](https://cefsharp.github.io/api/109.1.x/html/P_CefSharp_WinForms_ChromiumWebBrowser_ParkControlOnHandleDestroyed.htm), where the `IBrowser` instance is moved to a temporary parent when the handled is destroyed. I think `Form.Closing` would be preferable in this instance.
