### ISSUE TITLE
Update build.ps1 version number via update script

### ISSUE THREAD

**Issue by Hyrius** [cefsharp/CefSharp#4418]
The **CefSharp.Cef.CefSharpVersion** property is returning the string **109.1.110.0** even though I'm using the latest preview version of CefSharp, **111.0.110-CI4706**. 
Is it not being updated anymore or am I missing something? 

**CefSharp.Cef.CefVersion** and **CefSharp.Cef.ChromiumVersion** are returning the correct values: 
**r111.0.11+geb023d1+chromium-111.0.5563.50** and **111.0.5563.50**.

**Comment by amaitland** [comment]
If you were using the a stable version then it would have been correct as the version is derived from the tag.

For CI/local builds the build script needed to be manually updated, it should now be updated as part of the update script.
