### ISSUE TITLE
CEF3 and HTML5 audio tag

### ISSUE THREAD

**Issue by reccardt** [cefsharp/CefSharp#444]
Using the latest CefSharp.WPF.Example from github, HTML5 audio tags show the message that the tag is not supported. See it here: http://www.w3schools.com/html/tryit.asp?filename=tryhtml5_audio_all
After some googling, I found that you should be including ffmpegsumo.dll : https://code.google.com/p/chromiumembedded/issues/detail?id=948 After copying it over from my Chrome installation, the normal audio transport appears, but the speaker shows up as disabled and the audio doesn't play. The video tag doesn't work either.

**Comment by noisedaddy** [comment]
I tried various ffmpegsomo.dll but nothing works for me. I have CEF 3.2704.1432.g60b3718 version and could not find ffmpegsumo.dll for my version on http://cefbuilds.com/#branch_1650 link which amaitland provided. Is there somethig im doing wrong or some version include ffmpegsumo.dll-s and some not.
Am i right? Where can i find ffmpegsumo dll for my version?

**Comment by amaitland** [comment]
> I tried various ffmpegsomo.dll but nothing works for me. I have CEF 3.2704.1432.g60b3718 version and could not find ffmpegsumo.dll for my version on http://cefbuilds.com/#branch_1650 link which amaitland provided. Is there somethig im doing wrong or some version include ffmpegsumo.dll-s and some not.
> Am i right? Where can i find ffmpegsumo dll for my version?

@noisedaddy Please don't comment on an issue that's been closed for over two years, the information provided here isn't relevant anymore. `ffmpeg` is now statically compiled into `libcef.dll`, so there is no separate dll.
