### ISSUE TITLE
CefSharp.WinForms.Example.netcore crashes when selfHostSubProcess = true

### ISSUE THREAD

**Issue by Scalibq** [cefsharp/CefSharp#4456]
- **What version of the product are you using?**
    111.2.2

- **What architecture x86 or x64?**
    x86 and x64
	
- **What version of .Net?**
    .Net 6.0
    
- **On what operating system?**
    Win11

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WinForms
    
- **What steps will reproduce the problem?**
Download the CefSharp examples from GitHub, open CefSharp3.netcore.sln in Visual Studio 2022 and go to the CefSharp.WinForms.Example.netcore project. Set selfHostSubProcess = true in Program.cs. Run the project.

- **What is the expected output? What do you see instead?**
Expected is that the application starts and shows the browser example with the test webpage loaded.
The application starts, a browser window is shown, but the page is not actually loaded. After a few seconds, the entire application closes.

With selfHostSubProcess = false, the application works as expected.
The .NET 4.7.2 version (CefSharp.WinForms.Example in CefSharp3.sln) works in both selfHostSubProcess modes, so it appears to be an issue specific to the .NET Core version of the code.

**Comment by amaitland** [comment]
> * **What version of the product are you using?**
>   111.2.2

If you are going to build from source then please specify the exact commit you tested with.

> * Download the CefSharp examples from GitHub, open CefSharp3.netcore.sln in Visual Studio 2022 and go to the CefSharp.WinForms.Example.netcore project. Set selfHostSubProcess = true in Program.cs. Run the project.

Testing with commit https://github.com/cefsharp/CefSharp/commit/5cf01850a0b3dc55d77eddbbcc86a3da14c366a5 on `Windows 10`.

- Change selfHostSubProcess to true
- Edit `crash_reporter.cfg` and comment out `ExternalHandler`
- Change `Framework` to `.net6.0-windows` from the dropdown

Everything works as expected.

> * The application starts, a browser window is shown, but the page is not actually loaded. After a few seconds, the entire application closes.

Did you check the log file as per the bug report template? Check `Event Viewer` for errors?

**Comment by amaitland** [comment]
Closing due to lack of feedback. Can be reopened if someone can provide more details.
