### ISSUE TITLE
Sync JavaScript Binding - Support Generic Lists

### ISSUE THREAD

**Issue by daxiabiluo** [cefsharp/CefSharp#4458]
- **What architecture x86 or x64?**
    -<x 64>
	
- **What version of .Net?**
    <.Net 4.5.2   CefSharp.WinForms.111.2.20>
    
- **On what operating system?**
    <Win 10>
    
- **What steps will reproduce the problem?**
first, js call c#function，return string[]     normal
then, change string[] to List<string>,System.IO.PipeException
![1680850520395](https://user-images.githubusercontent.com/30133535/230558041-fb444c8c-ef67-4d4d-9110-93b0d9db4e22.png)

change into dataTable alse System.IO.PipeException

**Comment by amaitland** [comment]
Currently only basic arrays are supported. You can implement [BindingOptions.MethodInterceptor](https://cefsharp.github.io/api/111.2.x/html/P_CefSharp_BindingOptions_MethodInterceptor.htm) to programmatically convert all collections to primitive arrays if you wish.

If you'd like to see the current `WCF` implemented extended to support `Generic Lists` then you are welcome to submit a `PR` for review.

**Comment by daxiabiluo** [comment]
OK  Thinks
