### ISSUE TITLE
LoadHtml renders empty content

### ISSUE THREAD

**Issue by msc-bsw** [cefsharp/CefSharp#448]
Hey,

when I try to load a simple html string through LoadHtml(string html, string url), the web browser remains empty. Viewing the source just showing empty html, head and body tags. 

Do I need something more than just calling the LoadHtml method?

What is the **url** parameter used for in the LoadHtml method? I mostly just got a stream object that I want to get loaded with the browser. So I don't have a valid url.

Regards

Mark

**Comment by ljani** [comment]
I had problems with the [current implementation](https://github.com/cefsharp/CefSharp/blob/e6c2e13078dee058a02d37be27da33b15fdd13e0/CefSharp.WinForms/ChromiumWebBrowser.cs#L172) of `LoadHtml` too, but turns out the `url` parameter passed to `LoadHtml` must end with a slash if it only contains a domain.

In other words, this failed:
```
browser.LoadHtml("<html><body><h1>Hello world!</h1></body></html>", "http://example");
```
Whereas this works:
```
browser.LoadHtml("<html><body><h1>Hello world!</h1></body></html>", "http://example/");
```

Here's a complete, working WinForms example as of e6c2e13078dee058a02d37be27da33b15fdd13e0 if anyone is interested:
```
public partial class UnitTemplateUsageForm : Form
{
    private readonly ChromiumWebBrowser _browser;

    public ExampleForm()
    {
        InitializeComponent();

        _browser = new ChromiumWebBrowser(string.Empty)
        {
            Dock = DockStyle.Fill,
        };

        _browser.LoadHtml("<html><body><h1>Hello world!</h1></body></html>", http://example/);

        Controls.Add(_browser);
    }

    protected override void OnClosed(EventArgs e)
    {
        base.OnClosed(e);

        if (_browser != null)
        {
            _browser.Dispose();
        }
    }
}
```

Thanks for the hard work!

**Comment by amaitland** [comment]
@ljani Nice pickup, appreciate the feedback :+1:

**Comment by bharatdwarkani** [comment]
I have tried same in WPF but it is not loading it 

MainWindow.xaml

<Window x:Class="CeffBrowser.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:cefSharp="clr-namespace:CefSharp.Wpf;assembly=CefSharp.Wpf"
        Title="MainWindow" Height="350" Width="525">
    <Grid>
        <cefSharp:ChromiumWebBrowser Grid.Row="0" x:Name="webBrowser"
        />
    </Grid>
</Window>
App.xaml.cs

 public partial class App : Application
    {
        public App()
        {
            var settings = new CefSettings();          

            Cef.Initialize(settings);
        }
    }

MainWindow.xaml.cs
 public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
 
            webBrowser.Load("www.google.com");
            webBrowser.LoadHtml("<html><body><h1>Hello world!</h1></body></html>", "http://example/");
        }


            
    }


Is any settings missed? Note if I assign to address field in code behind cs file it works.

**Comment by jankurianski** [comment]
Does it work if you remove `webBrowser.Load("www.google.com");`?

**Comment by amaitland** [comment]
@bharatdwarkani Please markup your code, very hard to read. See https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code

**Comment by amaitland** [comment]
Check the state of `webBrowser.IsBrowserInitialized`, if it's `false` when you make a call to `Load` or `LoadHtml`, then it's basically ignored.

**Comment by bharatdwarkani** [comment]
Yes state is false. How to make that true?

**Comment by bharatdwarkani** [comment]
@jankurianski It doesnt work if I remove or use any one at a time.

**Comment by amaitland** [comment]
> Yes state is false. How to make that true?

You wait for the browser to init. See `IsBrowserInitializedChanged`

**Comment by bharatdwarkani** [comment]
@amaitland  Thanks it works now but there is an noticeable delay in browser initialisation how can this be minimised. Because in application there are 5-6 browsers and it depends on html content retrieved from Data base.

**Comment by amaitland** [comment]
Please open a new thread as that's rather off topic.

**Comment by bharatdwarkani** [comment]
Ok I have opened a new thread regarding this

**Comment by DhivyaLakshmiG** [comment]
How to make the browser to load faster? When we load more content in browser, it takes time to load. Until it loads we can see empty content in browser. Please suggest me.

**Comment by amaitland** [comment]
@DhivyaLakshmiG Specify the default `Url` as you would to load and register your `html` manually, see link below for example of how it's done internally. Also you can disable proxy lookup i
 
https://github.com/cefsharp/CefSharp/blob/cefsharp/47/CefSharp/WebBrowserExtensions.cs#L302 

Any follow up questions, ask them on `Gitter`.

https://github.com/cefsharp/CefSharp#contact
