### ISSUE TITLE
Open a pdf  by click on a link with target="_blank" in a second window hangs after closing mainwindow

### ISSUE THREAD

**Issue by stephanema1** [cefsharp/CefSharp#4499]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

112.3.0 and 113.0.0

### Operating System

Windows 10

### Architecture

x64

### .Net Version

.net 4.5

### Implementation

WPF

### Reproduction Steps

Seems to be a cefclient.exe problem with the parameter --multi-threaded-message-loop
as reported in discussion #4488 

### Expected behavior

I expect that the whole application closes without hanging

### Actual behavior

See #4488

### Regression?

No idea

### Known Workarounds

run without the parameter --multi-threaded-message-loop

### Does this problem also occur in the CEF Sample Application

Not Tested

**Comment by amaitland** [comment]
Closing as `upstream`.

Issue should be reported at https://github.com/chromiumembedded/cef

**Comment by amaitland** [comment]
https://github.com/chromiumembedded/cef/issues/3499
