### ISSUE TITLE
Remove CefSettings.UserDataPath

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#4518]
https://github.com/chromiumembedded/cef/commit/b5386249bd9075982db0874d3a981c44adc4c420

**Comment by Danielx64** [comment]
So does this mean that I will be forced to have the user's cache in the same folder as the main app itself?

**Comment by amaitland** [comment]
> So does this mean that I will be forced to have the user's cache in the same folder as the main app itself?

No
