### ISSUE TITLE
NetCore - Reference assemblies not generated when building with VS2022

### ISSUE THREAD

**Issue by developersthinksmartbox** [cefsharp/CefSharp#4558]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

114.2.12

### Operating System

Windows 10

### Architecture

x64

### .Net Version

netcoreapp3.1

### Implementation

WinForms

### Reproduction Steps

Run the build script with the following args:
```
./build.ps1 -Target vs2022 -TargetFramework NetCore -BuildArches "x86 x64"
```
Package restore and compilation steps complete successfully.
Error on packing via nuspec files:

```
Attempting to build package from 'CefSharp.Common.NETCore.nuspec'.
Could not find a part of the path 'C:\Dev\other_source\CefSharp\CefSharp\bin.netcore\Release\netcoreapp3.1\ref'.
Attempting to build package from 'CefSharp.WinForms.NETCore.nuspec'.
Could not find a part of the path 'C:\Dev\other_source\CefSharp\CefSharp.WinForms\bin.netcore\Release\netcoreapp3.1\ref'.
Attempting to build package from 'CefSharp.Wpf.NETCore.nuspec'.
Could not find a part of the path 'C:\Dev\other_source\CefSharp\CefSharp.Wpf\bin.netcore\Release\netcoreapp3.1\ref'.
Attempting to build package from 'CefSharp.OffScreen.NETCore.nuspec'.
Could not find a part of the path 'C:\Dev\other_source\CefSharp\CefSharp.OffScreen\bin.netcore\Release\netcoreapp3.1\ref'.
```

### Expected behavior

The nuspec files state that the reference assemblies should be available from the bin.netcore folders for various projects.

### Actual behavior

The reference assemblies are not available from the bin.netcore folders. 

### Does this problem also occur in the CEF Sample Application

Yes using WPF/OffScreen command line args

### Other information

The csproj files have the ProduceReferenceAssembly attribute but, I believe, are [missing the ProduceReferenceAssemblyInOutDir](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/output#producereferenceassembly) required to copy them to the bin folder.

If I'm correct I'm more than happy to submit a PR to correct this.

**Comment by amaitland** [comment]
Looks like the `.NET SDK 6.0.200` introduced a breaking chance to the behaviour. Official builds still use `VS2019` so are likely using an older `SDK`.

https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/write-reference-assemblies-to-obj

A `PR` with a fix would be welcomed 👍

**Comment by developersthinksmartbox** [comment]
Hey @amaitland, very happy to oblige. Thanks for your research into the problem and was interesting to learn where the breaking change came in. I suspected that this would work on VS2019 msbuild but wasn't easily able to test it. 

I'll put in a PR for master but do you mind if I put one in for cefsharp/114 as we might need to build it again in the future? Happy to target any additional branches you'd like.
