### ISSUE TITLE
libcef.dll, CefSharp.Core.dll not certificate signed

### ISSUE THREAD

**Issue by uptodatehuang** [cefsharp/CefSharp#4589]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

114.2.120

### Operating System

Windows 10

### Architecture

x64

### .Net Version

4.7.2

### Implementation

WinForms

### Reproduction Steps

install a C# winform app which include packages CefSharp.Common, CefSharp.OffScreen,  CefSharp.WinForms from VisualStudio's NuGet.

### Expected behavior

once install this C# winform app to PC, check properties of libcef.dll, CefSharp.Core.dll , those dll should be certificate signed.

### Actual behavior

libcef.dll, CefSharp.Core.dll are not certificate signed.

### Regression?

previous version also have same issue.

### Known Workarounds

no

### Does this problem also occur in the CEF Sample Application

Not Tested

### Other information

no

**Comment by amaitland** [comment]
The project doesn't currently have a code signing certificate, so this is expected.
