### ISSUE TITLE
WPF - Drag-Drop not working when using touchscreen

### ISSUE THREAD

**Issue by SUHASABOROLE** [cefsharp/CefSharp#4592]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

116.0.230

### Operating System

Windows 10

### Architecture

x64

### .Net Version

.NET 4.7

### Implementation

WPF

### Reproduction Steps

I'm currently using the **version 65** of cefsharp. I had a  **2 finger touch scroll problem in this version,** but **image drag and drop worked**, so I updated to **cefsharp 116.0.230**, and then **2 finger touch scroll problem was resolved**, however, **drag and drop capability is broken in this version.**

### Expected behavior

drag and drop and touch scroll both should be working in wpf application.

### Actual behavior

 In cefsharp 116.0.230, Two finger touch scroll working but drag & drop does not work.

### Known Workarounds

 I am using version cefSharp65 Their image and YouTube video are Drag and Drop in Incanvas. But when I update the version  latest version does not work on my preview code 

### Does this problem also occur in the CEF Sample Application

Yes using WPF/OffScreen command line args

**Comment by amaitland** [comment]
> ### Reproduction Steps
> I'm currently using the **version 65** of cefsharp. I had a **2 finger touch scroll problem in this version,** but **image drag and drop worked**, so I updated to **cefsharp 116.0.230**, and then **2 finger touch scroll problem was resolved**, however, **drag and drop capability is broken in this version.**

This needs to be a list of steps to reproduce the problem. So someone can follow the steps to clearly and reliably reproduce hte issue. Just saying it's broken is meaningless.

> ### Known Workarounds
> I am using version cefSharp65 Their image and YouTube video are Drag and Drop in Incanvas. But when I update the version latest version does not work on my preview code

No idea what you mean by this. What is the workaround exactly?

> ### Does this problem also occur in the CEF Sample Application
> Yes using WPF/OffScreen command line args

Did you actually test with the `CEF Sample Application`? If not then you'll need to do that before this issue can be reviewed.

**Comment by SUHASABOROLE** [comment]
I am developing a C#, WPF application for touch screens where user can search a text entered. The search results are opened in a cefsharp browser from which the user can drag and drop the searched images or videos to my canvas app where the searched images/videos can be saved offline. 
With version 65, we were able to drag and drop images using touch gestures. While after updating to the latest version, the touch-based drag and drop to canvas is not working anymore. We are able to scroll the page using touch with the latest version though. In ver 65, touch scroll was not working.

Seems like touch based scroll is conflicting with touch drag function in latest versions. Is it possible to disable touch scroll so that drag and drop using touch works?

**Comment by SUHASABOROLE** [comment]
Any update on my issues ?

**Comment by amaitland** [comment]
> This needs to be a list of steps to reproduce the problem. So someone can follow the steps to clearly and reliably reproduce hte issue. Just saying it's broken is meaningless.

Still waiting on a clear list of steps to reproduce.

> Did you actually test with the `CEF Sample Application`? If not then you'll need to do that before this issue can be reviewed.

Still waiting on results of testing with the `CEF Sample Application`.

**Comment by SUHASABOROLE** [comment]
Please check this link I am also facing a problem with this link.

Please open the link I provided to learn more about the problems I am currently facing.

https://support.google.com/chrome/thread/18609718/how-to-get-drag-drop-working-with-touch-screen-working-on-latest-version-of-chrome?hl=en

**Comment by SUHASABOROLE** [comment]
We tried using the CEF sample application. Here also, I can drag and drop an image from a web page to my desktop using mouse, but when i try to do the same using touch on a touch screen laptop, on long press, the image is not selected only. 

How can I enable touch event on Chromium browser, so that I can drag and drop an image from browser to another application or folder.

Tried --touch-events, #enable-touch-drag-drop etc. nothing works

**Comment by amaitland** [comment]
> Here also, I can drag and drop an image from a web page to my desktop using mouse, but when i try to do the same using touch on a touch screen laptop, on long press, the image is not selected only.

You'll need to create an issue at https://github.com/chromiumembedded/cef/issues

Once you've created an issue please post a link back here for reference.

This issue requires `upstream` changes and is not something that can be fixed directly in `CefSharp`.

> How can I enable touch event on Chromium browser, so that I can drag and drop an image from browser to another application or folder.

You can switch to using https://github.com/cefsharp/CefSharp.Wpf.HwndHost as a workaround until the `upstream` issue has been resolved.

**Comment by amaitland** [comment]
> You'll need to create an issue at https://github.com/chromiumembedded/cef/issues

Closing as `upstream`. If the problem reproduces with the current supported version of `CEF` (M121 at time of writing) then you'll need to raise an issue on the CEF issue tracker. (Post a link back here for reference)

**Comment by SUHASABOROLE** [comment]
CefSharp ver 65 support drag and drop with out having to write any separate function for it. But it is not supporting Google Map API anymore for which I have to migrate to ver 98 or above. But with ver 98 drag and drop does not work.

Give me an example where I can use CefSharp ver98 and above and still drag and drop images or youtube videos from the cefsharp browser to my InkCanvas

**Comment by SUHASABOROLE** [comment]
> CefSharp ver 65 support drag and drop with out having to write any separate function for it. But it is not supporting Google Map API anymore for which I have to migrate to ver 98 or above. But with ver 98 drag and drop does not work.
> 
> Give me an example where I can use CefSharp ver98 and above and still drag and drop images or youtube videos from the cefsharp browser to my InkCanvas
