### ISSUE TITLE
WPF - Browser not recognized by Verint DPA validator tool

### ISSUE THREAD

**Issue by linhnguyenm** [cefsharp/CefSharp#4596]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

116.0.230

### Operating System

Windows 11

### Architecture

x64

### .Net Version

.NET Framework 4.8

### Implementation

WPF

### Reproduction Steps

I have a tool called Verint DPA validator https://www.verint.com/desktop-and-process-analytics/ to capture control of window application. 
I want to use this tool to capture the Cefsharp web browser which is embedded inside the WPF application but I unable to capture it. 
I use the Cefsharp WPF sample here https://github.com/cefsharp/CefSharp.MinimalExample and run the WPF project to render the https://google.com but what I got is just an image.

I tried to use the normal Chrome web browser and install this extension and can capture more detail of html controls (text, input ...) on page https://chrome.google.com/webstore/detail/verintdpachromevalidator/gofohnjbcabckdcbamaelhmppjoegikd/related 
Does any one have the same issue? How can we make it work on Cefsharp chromium inside WPF?

### Expected behavior

The DPA tool can capture html control of Cefsharp chromium browser inside WPF app.

### Actual behavior

The DPA tool unable to capture html control of Cefsharp chromium browser inside WPF app

### Does this problem also occur in the CEF Sample Application

No

**Comment by amaitland** [comment]
> but what I got is just an image.

This is by design, each frame is rendered as a bitmap.

See https://github.com/cefsharp/CefSharp/wiki/General-Usage#offscreen-rendering-osr for more information.

You can use https://github.com/cefsharp/CefSharp.Wpf.HwndHost#cefsharpwpfhwndhost if you need a more traditional browser.

> Does any one have the same issue? How can we make it work on Cefsharp chromium inside WPF?

In future please use https://github.com/cefsharp/CefSharp/discussions to ask  questions.
