### ISSUE TITLE
WPF - Tooltip during mouseover not available

### ISSUE THREAD

**Issue by azerios** [cefsharp/CefSharp#4602]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

116

### Operating System

Windows 10

### Architecture

x64

### .Net Version

.Net 4.8

### Implementation

WPF

### Reproduction Steps

Create Sisense dashboard with https://www.sisense.com
Browse the url with the WPF sample
Tooltip of icons during mouseover are not present

### Expected behavior

Tooltip should be present

### Actual behavior

Not any tooltip is present in Cefsharp but using the direct link it's working

### Does this problem also occur in the CEF Sample Application

Not Tested

### Other information

Not applicable

**Comment by amaitland** [comment]
> ### Does this problem also occur in the CEF Sample Application
> Not Tested

You need to test with the `CEF Sample application`.

**Comment by amaitland** [comment]
Closing due to lack of feedback
