### ISSUE TITLE
EvaluateScriptAsync no longer returns meaningful error messages

### ISSUE THREAD

**Issue by smunnik** [cefsharp/CefSharp#4629]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

119.4.30

### Operating System

Windows 10

### Architecture

x64

### .Net Version

.Net 7

### Implementation

WPF

### Reproduction Steps

Link this method below to a button click. The javascript intentionally includes an error.

private async void ScriptTest_OnClick(object sender, RoutedEventArgs e)
{
    const string javascript = "1 + A;";
    var response = await WebBrowser.EvaluateScriptAsync(javascript);
    if (!response.Success)
    {
        MessageBox.Show(response.Message);
    }
}

### Expected behavior

response.Message should be:  "Uncaught ReferenceError: A is not defined\n@ about:blank:1:4"

### Actual behavior

response.Message is: "00000ACC008D39C0\n@ 00000ACC0089D1C0:1:4"

Any javascript error returns a message similar to this.

### Regression?

This started happening from version 115.3.110.
Version 114.2.120 and earlier worked correctly.

### Does this problem also occur in the CEF Sample Application

Not Tested

**Comment by amaitland** [comment]
> Regression?
> This started happening from version 115.3.110. Version 114.2.120 and earlier worked correctly.

Thanks. Very helpful.

Upstream commit https://bitbucket.org/chromiumembedded/cef/commits/5042d7140822cd13b80990f61ce2d3865864a3d8 changed the char type. 

The type returned from `c_str()` call now needs a cast/conversion.

This should be an easy one to fix.
