### ISSUE TITLE
WPF - Cannot type the character "ě" in input fields (Czech Republic)

### ISSUE THREAD

**Issue by karthikrs1993** [cefsharp/CefSharp#4653]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

117.2.40

### Operating System

Windows 10

### Architecture

x64

### .Net Version

.NET 6

### Implementation

WPF

### Reproduction Steps

Download Czech language pack in Windows 10/11
Change your default language to Czech ( You may chose to use onscreen keyboard for identification of the key stroke)
Launch browser hosted in WPF
Run an angular application with a input box
Type the character "ě" in the input box. This is the character above W key
User will not see the keystroke entered in the input field

### Expected behavior

User should be able to use the "ě" in all the fields in the CefSharp browser.

### Actual behavior

User is not seeing the keystroke entered in the input field "ě"

### Regression?

This last worked in 116.0.230

### Known Workarounds

Only copy paste from clipboard on the the CefSharp is working at the moment for that character "ě"

### Does this problem also occur in the CEF Sample Application

Yes using WPF/OffScreen command line args

### Other information

None

**Comment by amaitland** [comment]
> Does this problem also occur in the CEF Sample Application
> Yes using WPF/OffScreen command line args

Please confirm you've tested with the `CEF Sample Application`.

- Download https://cef-builds.spotifycdn.com/cef_binary_120.1.8%2Bge6b45b0%2Bchromium-120.0.6099.109_windows64_client.tar.bz2
-  Extract and run cefclient.exe using the following command line args. **IMPORTANT** you must use the args below.

```
cefclient.exe --multi-threaded-message-loop --no-sandbox --off-screen-rendering-enabled --enable-gpu
```

This is probably an `upstream` bug.

**Comment by karthikrs1993** [comment]
Yes, this works with the above sample application.

**Comment by amaitland** [comment]
Did you test with `cefclient.exe --multi-threaded-message-loop --no-sandbox --off-screen-rendering-enabled --enable-gpu`?

**Comment by karthikrs1993** [comment]
We tried with the sample, and it doesn't work. Thanks!

**Comment by amaitland** [comment]
If the problem reproduces with the `CEF Sample Application (cefclient)` then you will need to raise an issue at https://github.com/chromiumembedded/cef/issues

Post a link back here.

**Comment by ratiwar** [comment]
We tried with CEF Sample Application (cefclient), there also we are able to reproduce.

Here is the ticket - https://github.com/chromiumembedded/cef/issues/3624

**Comment by amaitland** [comment]
> Here is the ticket - [chromiumembedded/cef#3624](https://github.com/chromiumembedded/cef/issues/3624)

Closing this as `upstream. Subscribe to the `CEF` issue to track progress.

If code changes in `CefSharp` are required then this can be reopened once the `upstream` issue has been resolved.
