### ISSUE TITLE
"Could not load file or assembly 'CefSharp.Core.dll' or ..." when running CefSharp.Wpf.Example from another project

### ISSUE THREAD

**Issue by KennyKay** [cefsharp/CefSharp#466]
When I run the CefSharp.Wpf.Example project from another WinForms project , it crashes on the CefExample.Init() call even though all the necessary references are added.
I added the CefExample.Init() call in the constructor of the MainWindow.xaml.cs.

An unhandled exception of type 'System.IO.FileNotFoundException' occurred in CefSharp.Wpf.Example.exe
Additional information: Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found.

My main goal is to be able to show the Wpf CefSharp browser from a WinForms application using the WPF integration in WinForms (http://weblogs.asp.net/jdanforth/open-a-wpf-window-from-winforms):
var wpfwindow = new MainWindow();
ElementHost.EnableModelessKeyboardInterop(wpfwindow);
wpfwindow.Show();

It works fine when I start the CefSharp.Wpf.Example project although it doesn't work when running it from another project. The configuration of all project are set to x86 .Net 4.

Am I doing anything wrong or is it an issue?
Thanks.

**Comment by Apurv1516** [comment]
@Pkotian80 I am also facing the same problem . Please share if you have found the solution.
