### ISSUE TITLE
Support process singleton with IBrowserProcessHandler.OnAlreadyRunningAppRelaunch callback

### ISSUE THREAD

**Issue by Mik4sa** [cefsharp/CefSharp#4668]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

120.1.110

### Operating System

Windows 11

### Architecture

x64

### .Net Version

.NET 4.7.2

### Implementation

WinForms

### Reproduction Steps

Reproducible with [CefSharp.MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) since `120.1.110` (https://github.com/cefsharp/CefSharp.MinimalExample/commit/136a65e31959cb9f271094bf84c22589986df20a).
Just launch the application twice.

### Expected behavior

A second launch of the application should be possible (without any restrictions).

### Actual behavior

A launch of any more instances result in a crash.

This is the output of the`debug.log` from the second launch:
```
[0109/101550.274:ERROR:crashpad_client_win.cc(546)] CreateProcess: Das System kann die angegebene Datei nicht finden. (0x2)
[0109/101550.285:INFO:crash_reporting.cc(216)] Crash reporting enabled for process: browser
[0109/101550.289:WARNING:alloy_browser_main.cc(167)] Unhandled app relaunch; implement CefBrowserProcessHandler::OnAlreadyRunningAppRelaunch.
[0109/101550.289:ERROR:crashpad_client_win.cc(143)] crash server failed to launch, self-terminating
```

### Regression?

This was working with v120.1.80.

### Known Workarounds

No known workarounds

### Does this problem also occur in the CEF Sample Application

No

**Comment by yngwu** [comment]
Same here in our WPF application, but crashes in both v120 version.  Reverting back to v119 works. Probably an upstream bug.

debug.log from120.1.110
```
0110/102929.043:WARNING:alloy_browser_main.cc(167)] Unhandled app relaunch; implement CefBrowserProcessHandler::OnAlreadyRunningAppRelaunch.
[0110/103024.131:WARNING:alloy_browser_main.cc(167)] Unhandled app relaunch; implement CefBrowserProcessHandler::OnAlreadyRunningAppRelaunch.
[0110/103203.453:WARNING:alloy_browser_main.cc(167)] Unhandled app relaunch; implement CefBrowserProcessHandler::OnAlreadyRunningAppRelaunch
``` 
debug.log from vv120.1.80
```
[0110/103246.333:WARNING:frame_impl.cc(420)] SendProcessMessage sent to detached frame 21474836486 [5,6] will be ignored
[0110/103246.335:WARNING:frame_impl.cc(420)] SendProcessMessage sent to detached frame 21474836481 [5,1] will be ignored
[0110/103246.353:WARNING:sqlite_persistent_store_backend_base.cc(198)] Failed to post task from FlushAndNotifyInBackground@net\extras\sqlite\sqlite_persistent_store_backend_base.cc:246 to client_task_runner_.
[0110/103246.353:WARNING:sqlite_persistent_store_backend_base.cc(198)] Failed to post task from FlushAndNotifyInBackground@net\extras\sqlite\sqlite_persistent_store_backend_base.cc:246 to client_task_runner_
```

**Comment by amaitland** [comment]
`Chromium` is designed so only a single process can access a `Cache` at a time. Multiple processes is not supported. If it worked previously then it was by luck, not design.

> This was working with v120.1.80.

The only `CefSharp` change was to upgrade to a newer `CEF` version.  You can easily compare tags on github https://github.com/cefsharp/CefSharp/compare/v120.1.80...v120.1.110

> Reproducible with [CefSharp.MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) since `120.1.110` ([cefsharp/CefSharp.MinimalExample@136a65e](https://github.com/cefsharp/CefSharp.MinimalExample/commit/136a65e31959cb9f271094bf84c22589986df20a)).
> Just launch the application twice.

The` MinimalExample` isn't designed to be run multiple times. It has a fixed `CachePath`.

> A second launch of the application should be possible (without any restrictions).

That's not really something `CefSharp` has control over. Someone should ask on https://github.com/chromiumembedded/cef/issues/3615 to see if the change in behaviour is expected. 

> [0109/101550.289:WARNING:alloy_browser_main.cc(167)] Unhandled app relaunch; implement CefBrowserProcessHandler::OnAlreadyRunningAppRelaunch.

We need to add `IBrowserProcessHandler.OnAlreadyRunningAppRelaunch` we can use this issue to track that work.

**Comment by amaitland** [comment]
```cpp
///
/// Implement this method to provide app-specific behavior when an already
/// running app is relaunched with the same CefSettings.root_cache_path value.
/// For example, activate an existing app window or create a new app window.
/// |command_line| will be read-only. Do not keep a reference to
/// |command_line| outside of this method. Return true if the relaunch is
/// handled or false for default relaunch behavior. Default behavior will
/// create a new default styled Chrome window.
///
/// To avoid cache corruption only a single app instance is allowed to run for
/// a given CefSettings.root_cache_path value. On relaunch the app checks a
/// process singleton lock and then forwards the new launch arguments to the
/// already running app process before exiting early. Client apps should
/// therefore check the CefInitialize() return value for early exit before
/// proceeding.
///
/// This method will be called on the browser process UI thread.
///
/*--cef(optional_param=current_directory)--*/
virtual bool OnAlreadyRunningAppRelaunch(
    CefRefPtr<CefCommandLine> command_line,
    const CefString& current_directory) {
  return false;
}
```

> On relaunch the app checks a process singleton lock and then forwards the new launch arguments to the
already running app process before exiting early. Client apps should therefore check the CefInitialize() return value for early exit before proceeding.

As per `CEF API doc` (from above).

**Comment by Mik4sa** [comment]
Ok, got it, thanks
Afaik in our main application we do not have a CachePath set (so no cache is written to the disk) and still the application is crashing. Maybe this info is relevant to you too.

**Comment by amaitland** [comment]
> [0109/101550.289:WARNING:alloy_browser_main.cc(167)] Unhandled app relaunch; implement CefBrowserProcessHandler::OnAlreadyRunningAppRelaunch.

CEF thinks your application has relaunched with a `CachePath` or `RootCachePath` identical to another process. `RequestContext` cache paths would also count.

> Afaik in our main application we do not have a CachePath set (so no cache is written to the disk) and still the application is crashing. Maybe this info is relevant to you too.

Load `chrome://version` in a `ChromiumWebBrowser` instance within your application to see what `CEF` thinks your path values are.

Again from a `CefSharp` point of view the only thing that changed was an upgrade to a newer version of `CEF`.

If your application doesn't have a cache set then you'll need to raise an issue at https://github.com/chromiumembedded/cef/issues as that would be an upstream bug.

**Comment by Mik4sa** [comment]
Ok I see. There is always a root cache path:
![image](https://github.com/cefsharp/CefSharp/assets/8343141/d13cd3b0-4bdf-4145-8a3b-c49222083afc)

**Comment by Mik4sa** [comment]
@amaitland Is there a function to get the default root cache path?
Or a way to call native functions from them? Like `GetDefaultUserDataDirectory`? See: https://source.chromium.org/chromium/chromium/src/+/main:chrome/common/chrome_paths_internal.h?q=GetDefaultUserDataDirectory&ss=chromium

**Comment by amaitland** [comment]
> Client apps should therefore check the CefInitialize() return value for early exit beforeproceeding.

If the second process call to `Cef.Initialzie()` isn't returning a value (if it's crashing or terminating the process), then someone needs to create an issue at https://github.com/chromiumembedded/cef/issues

**Comment by amaitland** [comment]
Looks like `CEF` is causing an `access violation` for the second process(`CefSharp.MinimalExample.WinForms.net472.exe`) call to `Cef.Initialize (CefInitialize)`

```
Faulting application name: CefSharp.MinimalExample.WinForms.net472.exe, version: 1.0.0.0, time stamp: 0xb8fa0b28
Faulting module name: libcef.dll, version: 120.2.5.0, time stamp: 0x659c57ab
Exception code: 0x80000003
Fault offset: 0x00000000046d32e7
Faulting process ID: 0x36ac
Faulting application start time: 0x01da4b157e671427
Faulting application path: C:\projects\CefSharp.MinimalExample\CefSharp.MinimalExample.WinForms\bin.net472\Debug\net472\CefSharp.MinimalExample.WinForms.net472.exe
Faulting module path: C:\projects\CefSharp.MinimalExample\CefSharp.MinimalExample.WinForms\bin.net472\Debug\net472\x64\libcef.dll
Report ID: e5039ffe-5121-4f92-9ecf-27fccc4854c4
Faulting package full name: 
Faulting package-relative application ID: 
```

Someone will need to raise an issue at https://github.com/chromiumembedded/cef/issues

**Comment by amaitland** [comment]
Problem reproduces with the CEF sample application, only appears to be a problem when `multi threaded message loop` is used (the default in `CefSharp`).

Upstream issue https://github.com/chromiumembedded/cef/issues/3635

You can try integrating `CEF` into your applications existing message loop to workaround the problem for now. See https://github.com/cefsharp/CefSharp/wiki/General-Usage#multithreadedmessageloop

**Comment by amaitland** [comment]
> Upstream issue [chromiumembedded/cef#3635](https://github.com/chromiumembedded/cef/issues/3635)

The upstream issue has been resolved. If I'm reading the fix correctly the `UI Thread` will be shutdown if the process singleton detects an already running instance. So the previous behaviour of having multiple application instances running without providing a `RootCachePath` is no longer supported/possible.

- https://github.com/chromiumembedded/cef/issues/3615
- Related forum discussion https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=19665

> Please customize CefSettings.root_cache_path for your application. Use of the default value may lead to unintended process singleton behavior

`CEF` will log this message if `RootCachePath` is not set, you should ensure that at a minimum you set `CefSettings.RootCachePath` to a unique folder per application to avoid unwanted calls to `OnAlreadyRunningAppRelaunch`.

`OnAlreadyRunningAppRelaunch` can be used to achieve the same behaviour as `Chromium`. (Single process instance with multiple windows within the one process). 
If you need multiple instances that are entirely isolated, then you will need to specify a unique `RootCachePath` for each.

**Comment by amaitland** [comment]
It's important to implement `IBrowserProcessHandler.OnAlreadyRunningAppRelaunch`. The default `upstream` behavior is to launch a new `Chrome styled` window when relaunch is detected. 

`BrowserProcessHandler` provides a default implementation of `IBrowserProcessHandler` which you can override just the specific methods you are interested in.

> Return true if the relaunch is handled or false for default relaunch behavior. Default behavior will create a new default styled Chrome window.

https://cefsharp.github.io/api/130.1.x/html/M_CefSharp_IBrowserProcessHandler_OnAlreadyRunningAppRelaunch.htm

 You can `return true` in `IBrowserProcessHandler.OnAlreadyRunningAppRelaunch` to override this behavior.
