### ISSUE TITLE
Since  v120.1.80: Cefsharp only supports one instance of WinForms desktop app and closes other instances of the app

### ISSUE THREAD

**Issue by Skorpjun161** [cefsharp/CefSharp#4686]
### Is there an existing issue for this?

- [x] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

v120.2.7

### Operating System

Windows 11

### Architecture

AnyCPU

### .Net Version

.Net 4.8.1

### Implementation

WinForms

### Reproduction Steps

- Create a new C# Windows Desktop project .Net Framework 4.8.1 with one Form1
- Code:
---
using CefSharp;
using CefSharp.WinForms;
using cefsharpcpp.Properties;
using System;
using System.Windows.Forms;

namespace cefsharpcpp
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            Cef.Initialize(new CefSettings()); // This closes the app. No errors or anything. The code after this line is simply not executed.
            ChromiumWebBrowser web;
            Cef.Initialize(new CefSettings());
            web = new ChromiumWebBrowser();
            web.Dock = DockStyle.Fill;
            this.Controls.Add(web);
            web.LoadUrl("https://www.google.com");
        }
    }
}
---
- Compile as release and run the exe
- Then run the app from Visual Studio as debug.
- The debugged program just stops without any errors (at least none that I could find).

### Expected behavior

Running multiple instances of the same app should not cause issues as far I know as it worked prior to v120.

### Actual behavior

Running multiple instances of the same app causes any other instance than the first one to automatically close.

### Regression?

It worked prior to v120, so up to and including v119.4.30

### Known Workarounds

None that I know of

### Does this problem also occur in the CEF Sample Application

No

**Comment by campersau** [comment]
See https://github.com/cefsharp/CefSharp/issues/4668#issuecomment-1890241487 / https://github.com/cefsharp/CefSharp/issues/4668#issuecomment-1890331903
