### ISSUE TITLE
Feature Request - Improve documentation to understand how to enable dark mode for ChromiumWebBrowser

### ISSUE THREAD

**Issue by ElektroStudios** [cefsharp/CefSharp#4723]
**Describe the solution you'd like**
A clear and concise documentation article, FAQ entry, and/or a guided/automated public method in the **CefSharp** API that can let the non-advanced end-user to help him figure out and understand how to enable/disable dark mode on a [ChromiumWebBrowser](https://cefsharp.github.io/api/75.1.x/html/T_CefSharp_WinForms_ChromiumWebBrowser.htm) object.

For .NET Core Windows Forms and .NET Framework Windows Forms.

**Additional context**
I've opened this simple and detailed question in Stackoverflow, but I still can't get the help that I'm looking for...

 - [How to enable dark mode for CefSharp web browser in .NET?](https://stackoverflow.com/questions/78011208/how-to-enable-dark-mode-for-cefsharp-web-browser-in-net)

> My intention is that when loading a web page in the CEF-based browser, it will automatically be colored with a dark theme.
> 
> Or at least, and as a last resort, only a solution for websites that checks whether the web browser is using dark or light mode and then the website automatically adapts its colors.

Thanks in advance if someone could clear my doubts.

**Checklist:**
- [x] I have reviewed the [CEF API](https://magpcss.org/ceforum/apidocs3/index-all.html) and have confirmed the feature I'm requesting is possible.
- [x] The Feature I'm requesting is an improvement to Async Javascript Binding (No new feature are being added to the Sync Javascript binding)
- [ ] An open `PR` exists on the [CEF Pull Requests](https://bitbucket.org/chromiumembedded/cef/pull-requests/) and I'd like to propose this feature is added to `CefSharp` when/if it's merged.

**Comment by amaitland** [comment]
[prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) is the only option that CEF officially supports.

I've updated https://github.com/cefsharp/CefSharp/discussions/3955#discussioncomment-1944133 to better document the options.

Forcing a website that doesn't not support a dark theme to display in a dark mode is not officially supported.
