### ISSUE TITLE
After updating to v122.1.120, disabling User Agent Client Hints using command line settings has stopped working

### ISSUE THREAD

**Issue by jstashblr** [cefsharp/CefSharp#4760]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

122.1.120

### Operating System

Windows 11

### Architecture

x64

### .Net Version

5.11.2.2

### Implementation

WinForms

### Reproduction Steps

Add settings.CefCommandLineArgs.Add("--disable-features", "UserAgentClientHint")

### Expected behavior

User agent clients should not be sent over HTTP request headers

### Actual behavior

User agent clients are currently being sent over HTTP request headers

### Known Workarounds

Manually removing request headers relating to client hints

### Does this problem also occur in the CEF Sample Application

Yes using WinForms command line args

**Comment by jcp-blr** [comment]
@amaitland, requesting you to investigate this.

**Comment by jcp-blr** [comment]
Reported by mistake
