### ISSUE TITLE
Nuget - Add repository to packages

### ISSUE THREAD

**Issue by thompson-tomo** [cefsharp/CefSharp#4762]
**Describe the solution you'd like**

The licence expression property should be set to the correct licence type (depending on the repo) as this will enable analysis of licences in use to occur in external tools & the license type will be shown in Nuget etc. By providing the repo url it will make it easier to contribute and can be used by sourcelink.

**Describe alternatives you've considered**

**Additional context**
m/a

**Checklist:**
- [x] I have reviewed the [CEF API](https://magpcss.org/ceforum/apidocs3/index-all.html) and have confirmed the feature I'm requesting is possible.

**Comment by amaitland** [comment]
> The licence expression property should be set to the correct licence type (depending on the repo) as this will enable analysis of licences in use to occur in external tools & the license type will be shown in Nuget etc.

The `Nuget` packages should have an embedded `License`. Whilst the license is `3-BSD` it does contain additional wording which would be lost of we switched to an expression. 

If the  license is embedded correctly then I believe everything is as intended.

> //    * Neither the name of Google Inc. nor the name Chromium Embedded
> //      Framework nor the name CefSharp nor the names of its contributors
> //      may be used to endorse or promote products derived from this software
> //      without specific prior written permission.

The third clause was customised (long before I took over the project). Switching to an expression would revert back to the vanilla license which I don't believe is desirable.

> By providing the repo url

Seems resonable. Pull requests welcome.

**Comment by amaitland** [comment]
https://learn.microsoft.com/en-us/nuget/reference/nuspec#repository

**Comment by thompson-tomo** [comment]
Thanks for that insight @amaitland regarding the licence. And I notice someone has already picked up the repo url property.

**Comment by amaitland** [comment]
Thanks to @campersau the packages should now correctly include the repository + commit hash
