### ISSUE TITLE
Javascript not working in CEF3 when running with --single-process

### ISSUE THREAD

**Issue by bjarteskogoy** [cefsharp/CefSharp#477]
This is executed: https://github.com/cefsharp/CefSharp/blob/JsBinding_WIP/CefSharp/Internals/BrowserProcessServiceHost.cs#L54
but this never happens: https://github.com/cefsharp/CefSharp/blob/JsBinding_WIP/CefSharp/Internals/BrowserProcessServiceHost.cs#L56

I'm more than happy to contribute but I'm not sure where to start.

**Comment by georgiosd** [comment]
Hey guys,

Is there an example for single-process or at least some docs on how to make it work? I'm getting weird random crashes with it, and I can't even attach the debugger...

**Comment by amaitland** [comment]
> It is designed for testing and development purposes, and it may contain bugs that are not present in the other architectures. 

http://www.chromium.org/developers/design-documents/process-models#TOC-Single-process

> I'm getting weird random crashes with it, and I can't even attach the debugger...

`CefSharp` doesn't support single process mode, most of it's features are implemented in it's custom subprocess.  `CEF` doesn't support it either (no bugs will be fixed). If you search on http://magpcss.org/ceforum/index.php you'll see nothing but problems.

**Comment by georgiosd** [comment]
Yes, I see now... too bad - I'm spawning a lot of browsers and resource usage is a primary concern. It seems that single process was the most efficient - and most unstable.

Any idea how CEF1 would fair in terms of resources? I don't mind that it won't have the latest features, I only need some basic rendering and Javascript execution. If I read correctly, it's at Chromium 25.

**Comment by amaitland** [comment]
Chromium does have other process models to choose from. 

CEF1 is before my time. You might be better to look at geckofx, from memory it has a single process model.

**Comment by georgiosd** [comment]
Yes, I have looked at them extensively. However I'm thinking it's a risk to control too many pages from one process. If the process crashes for whatever reason, they're all orphaned/dead. The renderer crashing is not a problem of course.

I also heard that the network requests all go through one thread which would slow things down for a lot of pages. I haven't been able to verify that though, so it could be misinformation.

I guess I should run some more tests before committing.

Thanks for the link! I'll check it out!
