### ISSUE TITLE
Remove Alloy Bootstrap (M128)

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#4795]
`CEF` is going to remove the `Alloy Bootstrap`

- Upstream issue https://github.com/chromiumembedded/cef/issues/3685
- [Announcement](https://groups.google.com/g/cef-announce/c/s1WaovAopFo/m/LV5eiNX1BgAJ)

Starting in `M125` it will be possible to migrate over to the `Chrome Bootstrap`.

**Comment by amaitland** [comment]
`CefSharp` will likely switch to using the `Chrome Bootstrap` by default in `M126` to ensure any underlying issues are identified **before** the `alloy bootstrap` is removed.

**Comment by amaitland** [comment]
> `CefSharp` will likely switch to using the `Chrome Bootstrap` by default in `M126` to ensure any underlying issues are identified **before** the `alloy bootstrap` is removed.

Confirming this change (https://github.com/cefsharp/CefSharp/issues/4835)

**Comment by amaitland** [comment]
### Important
If you discover an issue with the `Chrome Bootstrap` then you need to raise the issue on the  **CEF ISSUE TRACKER**

https://github.com/chromiumembedded/cef/issues

Please post a link in https://github.com/cefsharp/CefSharp/issues/4835, don't create an issue in this repository.

**Comment by amaitland** [comment]
The `Alloy` bootstrap will be removed upstream in M128

**Comment by amaitland** [comment]
The disable-pdf-extension flag is not supported with Chrome bootstrap.

**Comment by amaitland** [comment]
- https://github.com/chromiumembedded/cef/issues/3750
- https://github.com/chromiumembedded/cef/issues/3749
- https://github.com/chromiumembedded/cef/issues/3726
- https://github.com/chromiumembedded/cef/issues/3740
- https://github.com/chromiumembedded/cef/issues/3739

**Comment by amaitland** [comment]
> The disable-pdf-extension flag is not supported with Chrome bootstrap.

Workaround https://github.com/chromiumembedded/cef/issues/3739#issuecomment-2250694767

**Comment by mattwildgoose** [comment]
[Submitting a form with newly entered address details causes the hosting app to crash (if CefSettings.Locale is set)](https://github.com/chromiumembedded/cef/issues/3796)

**Comment by mol** [comment]
@amaitland https://github.com/chromiumembedded/cef/issues/3860 means WPF has this issue, since as I understand it, WPF is still using Alloy.

I've searched everywhere, but I'm unclear what the eventual complete removal of Alloy in CEF is going to mean for CefSharp WPF? Will the Chrome Bootstrap support WPF?

**Comment by amaitland** [comment]
My understanding there's two parts, bootstrap and style. The alloy bootstrap has already been removed. The chrome bootstrap is the only option now.

The chrome bootstrap supports alloy styling. OSR which the WPF implementation uses is only supported with alloy styling.

I'm not aware of any plans to remove alloy styled browsers. If you're seen something to the contrary then please share a link.

There are a number of issues that you might run into with the OSR implementation as it stands, the key ones being 

https://github.com/chromiumembedded/cef/issues/3826
https://github.com/chromiumembedded/cef/issues/3822
https://github.com/chromiumembedded/cef/issues/3764

There is the hwndhost implementation which can be configured to use chrome styling. (Airspace issues apply) https://github.com/cefsharp/CefSharp.Wpf.HwndHost

I'm not sure if this is viable for you as an alternative, just pointing it out just in case.

I'm in the process of moving the source into the main repo https://github.com/cefsharp/CefSharp/pull/4981

**Comment by mol** [comment]
> My understanding there's two parts, bootstrap and style. The alloy bootstrap has already been removed. The chrome bootstrap is the only option now.

Ah, I see. I wasn't fully aware of this distinction - good to know, thanks.

Thanks for the other links - I'll play around with it some more and see what I can find.
