### ISSUE TITLE
WPF - JavaScript DragEnd event not emitted

### ISSUE THREAD

**Issue by WilliamTomOBrien** [cefsharp/CefSharp#4801]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

124.3.50.0

### Operating System

Windows 11

### Architecture

x64

### .Net Version

4.7.2

### Implementation

WPF

### Reproduction Steps

1. Run CefSharp.Wpf.Example
2. Load the [following gist](https://gist.github.com/WilliamTomOBrien/5d6a457062302dd3b9df8d722e1fa94c) in the browser
3. Drag the blue box from one grey box to the other
4. View the emit drag and drop events listed below

### Expected behavior

I would expect the `dragend` event to be emit when the drag operation ended, as described [here](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API#drag_events). In this example, this would be reflected by `dragend` being printed at the bottom of the event list.

This behavior does occur when using the CEF browser, as shown below.
![cef-124-drag-and-drop-events](https://github.com/cefsharp/CefSharp/assets/29744773/a2ec2b59-d64e-4ed9-ad01-be86abc35e95)

### Actual behavior

The `dragend` event is not emit after dragging and dropping an element. 

![cefsharp-124-drag-and-drop-events](https://github.com/cefsharp/CefSharp/assets/29744773/e57b2f0f-f44c-4a9f-9b2c-e6549b109bd0)

Apologies for printing the events to the screen - I wanted the gif showing the behavior in CEF to match, and unfortunately trying to load DevTools when running the `cefclient.exe --multi-threaded-message-loop --no-sandbox --off-screen-rendering-enabled --enable-gpu` command would crash my instance of CEF.

### Regression?

[This issue](https://github.com/cefsharp/CefSharp/issues/3941) seems like it may potentially be relevant, however was not followed up on by the creator. Unfortunately, I was unable to verify if this was the case, as I was unable to build the [cefsharp/86](https://github.com/cefsharp/CefSharp/tree/cefsharp/86) branch.

### Known Workarounds

No known workarounds, aside from avoiding any functionality that would rely on an event handler for `dragend`.

### Does this problem also occur in the CEF Sample Application

No

**Comment by amaitland** [comment]
If `cefclient` with `--off-screen-rendering-enabled` works correctly then you can compare the behaviour and see what changes are required in the `WPF` implementation.

- https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf/ChromiumWebBrowser.cs#L895
- https://github.com/chromiumembedded/cef/blob/8283317cb1b1289bbe362bb33b7ceaea631227ff/tests/cefclient/browser/osr_window_win.cc#L1067

Pull requests welcome.

> unfortunately trying to load DevTools when running the `cefclient.exe --multi-threaded-message-loop --no-sandbox --off-screen-rendering-enabled --enable-gpu` command would crash my instance of CEF.

This is expected if you are running `M125` as there is an `upstream` issue as discussed at https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=19782

I wouldn't expect this issue if you are testing with the `124` build.

> No known workarounds, aside from avoiding any functionality that would rely on an event handler for `dragend`.

Using https://github.com/cefsharp/CefSharp.Wpf.HwndHost should likely work as expected.
