### ISSUE TITLE
After upgrading cefsharp, the program cannot run two instances at the same time.

### ISSUE THREAD

**Issue by Jun-GY** [cefsharp/CefSharp#4804]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

124.3.80

### Operating System

Windows 10

### Architecture

x64

### .Net Version

.Net 8

### Implementation

WinForms

### Reproduction Steps

The wpf program cefsharp control version is upgraded to 124.3.80. The program cannot run two instances at the same time.what do i need to do？

[Demo code](https://github.com/cefsharp/CefSharp/files/15369459/CefSharpDemo.zip)

### Expected behavior

Run correctly

### Actual behavior

There is no exception, the second startup process cannot be started

### Does this problem also occur in the CEF Sample Application

Yes using WPF/OffScreen command line args

**Comment by amaitland** [comment]
CEF now supports the Chromium process singleton, this brings with it changes to how CachePath/RootCachePath are accessed from multiple processes. See https://github.com/cefsharp/CefSharp/issues/4668 for more details

What you are seeing is the expected behaviour.
