### ISSUE TITLE
Chrome Runtime proxies don't work unless flag is set.

### ISSUE THREAD

**Issue by GrabzIt** [cefsharp/CefSharp#4830]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

125.0.210

### Operating System

Windows 10

### Architecture

x64

### .Net Version

.NET 6

### Implementation

OffScreen

### Reproduction Steps

Try and call a proxy it won't call the GetAuthCredentials method when using the new ChromeRuntime.

### Expected behavior

Try and get the credentials

### Actual behavior

It never calls it due to this issue: https://github.com/chromiumembedded/cef/issues/3603

This flag should probably be set automatically by cefsharp as its quite confusing.

### Does this problem also occur in the CEF Sample Application

Yes using WPF/OffScreen command line args

### Other information

Great work as always @amaitland this is more a heads up for people than a true bug as it had me stumped for a while.

**Comment by amaitland** [comment]
Thanks for the heads up 👍 

I'm inclined to set this command line arg by default in M126

**Comment by GrabzIt** [comment]
Great, thanks it's a really weird issue.
