### ISSUE TITLE
Change to using Chrome bootstrap by default

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#4835]
CEF is planning on removing the `Alloy Bootstrap` (#4795) in `~M127`.

In `M126` we will switch to using the `Chrome Bootstrap` by default.

--- 

https://github.com/chromiumembedded/cef/issues/3685

**Comment by amaitland** [comment]
`CefSharpSettings.RuntimeStyle` has been added to simplify switching to using the `Chrome` styled windows. This is a global setting, must be set before creating your first `ChromiumWebBrowser` instance.

```c#
CefSharpSettings.RuntimeStyle = true;
```

Behaviour can be controller on a per `ChromiumWebBrowser` instance via overriding `ChromiumWebBrowser.CreateBrowserWindowInfo`.

This is only for `WinForms` and `Wpf.HwndHost`. The `OffScreen` and `WPF` implementations will always use `Alloy` styled windows (that's all `CEF` supports, the property is ignored for offscreen rendering).

**Comment by amaitland** [comment]
For a limited time you will be able to revert to using the `Alloy` bootstrap by setting `CefSettings.ChromeRuntime` to `false`.

```
cefSettings.ChromeRuntime = false;
```

Once https://github.com/chromiumembedded/cef/issues/3685 has been resolved the `Alloy` bootstrap will be removed. 

CEF has it's own support forum and issue tracker should you discover any bugs or changes in behaviour with the `Chrome bootstrap`, you can discuss them on the forum or raise issues on the issue tracker.

- https://www.magpcss.org/ceforum/index.php
- https://github.com/chromiumembedded/cef/issues

**Comment by amaitland** [comment]
> `CefSharpSettings.RuntimeStyle` has been added to simplify switching to using the `Chrome` styled windows. This is a global setting, must be set before creating your first `ChromiumWebBrowser` instance.

For those using the `Chrome` runtime currently will need to change the runtime style to `Chrome` to keep the same behaviour.

**Comment by amaitland** [comment]
#### Known issues

- #4847

**Comment by amaitland** [comment]
### Important
If you discover an issue with the `Chrome Bootstrap` then you need to raise the issue on the  **CEF ISSUE TRACKER**

https://github.com/chromiumembedded/cef/issues

Please post a link here for reference, don't create an issue in this repository.

**Comment by amaitland** [comment]
> If you discover an issue with the `Chrome Bootstrap` then you need to raise the issue on the **CEF ISSUE TRACKER**
> 
> https://github.com/chromiumembedded/cef/issues

If something doesn't work with the `Chrome bootstrap` and you switch back to the `Alloy bootstrap` and it **works as expected** then you'll need to raise an issue on https://github.com/chromiumembedded/cef/issues

In the short term keep using the `Alloy bootstrap` until the bug is fixed `upstream`

**Comment by amaitland** [comment]
The `Alloy` bootstrap will be removed upstream in M128

**Comment by amaitland** [comment]
The disable-pdf-extension flag is not supported with Chrome bootstrap.

**Comment by amaitland** [comment]
> Known issues

List at #4795

**Comment by chacham2** [comment]
> The disable-pdf-extension flag is not supported with Chrome bootstrap.

Will it ever be?

**Comment by max3163** [comment]
Add link to https://github.com/chromiumembedded/cef/issues/3785

**Comment by amaitland** [comment]
List of known issues is now at https://github.com/cefsharp/CefSharp/issues/4795#issuecomment-2241756717

Links have been updated, going forward will just keep the list updated there (if you find an upstream issue that effects `CefSharp` then please add the link in #4795)
