### ISSUE TITLE
IDialogHandler.OnFileDialog add new extensions and descriptions arguments

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#4838]
The method signature has changed, CEF has added two new params.

The `acceptFilters` param will also change from `List<string>` to `IReadOnlyCollection<string>` as it's immutable effectively.

**Comment by kissqy** [comment]
Since OnFileDialog was modified in this version, cefsharp cannot upload files correctly after the remote desktop is closed. I don’t know why. Please help.
