### ISSUE TITLE
Enable browser After RequestContext, open the developer tool and the application will crash

### ISSUE THREAD

**Issue by Amomo-CN** [cefsharp/CefSharp#4839]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

126,1,140

### Operating System

Windows 10

### Architecture

x64

### .Net Version

4.6.2

### Implementation

WinForms

### Reproduction Steps

BrowserTabView.xaml   browser.RequestContext = new RequestContext(new RequestContextHandler());

### Expected behavior

Open developer tools

### Actual behavior

Application Flashback

### Known Workarounds

NO

### Does this problem also occur in the CEF Sample Application

Not Tested

### Other information

no

**Comment by amaitland** [comment]
You'll need to raise this at https://github.com/chromiumembedded/cef/issues

Please post a link back here for reference.

**Comment by amaitland** [comment]
Closing as `upstream.`
