### ISSUE TITLE
Deleting the RootCache directory after Cef.Shutdown doesn't work with the Chrome Bootstrap

### ISSUE THREAD

**Issue by Mik4sa** [cefsharp/CefSharp#4852]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

126.2.70

### Operating System

Windows 11

### Architecture

x64

### .Net Version

.Net 4.8

### Implementation

WinForms

### Reproduction Steps

Checkout my example: https://github.com/Mik4sa/CefSharp.MinimalExample
I took the current MinimalExample, upgraded it to the latest version 126.2.70 and made a small change which reflects our situation: https://github.com/Mik4sa/CefSharp.MinimalExample/commit/28c9693673d1d784af68157f53ba852740712229

### Expected behavior

Calling Cef.Shutdown should release all resources / handles so that deleting the RootCache directory works.

### Actual behavior

After calling Cef.Shutdown some handles are still kept (for example to the debug.log file). The RootCache directory can't be deleted.

### Regression?

This worked in the previous version 125.0.210. Also this works when changing back to `Alloy Bootstrap`

### Known Workarounds

This works when changing back to `Alloy Bootstrap`

### Does this problem also occur in the CEF Sample Application

Not Tested

### Other information

In our application we want to delete the custom configured RootCache directory. Doing so worked until 126.2.70. With this version **and** the `Chrome Bootstrap` this is no longer possible. The reason is that there are still some handles to some files in that directory. For example the debug.log file. So the whole directory can't be deleted. I also noticed that way more files are written as before. Is this expected? Or is this maybe already the underlaying reason?

With `Alloy Bootstrap`:
![image](https://github.com/cefsharp/CefSharp/assets/8343141/db27f8fe-7c7c-46c5-9d1b-3f7f945f162a)

With `Chrome Bootstrap`:
![image](https://github.com/cefsharp/CefSharp/assets/8343141/65044cff-a6b1-48ed-9c7f-ab11de611c91)

**Comment by amaitland** [comment]
You'll need to raise your issue on https://github.com/chromiumembedded/cef/issues (post a link back here for reference)

**Comment by Mik4sa** [comment]
Thanks. Wasn't sure if this is really upstream. Will do later this day :)

**Comment by Mik4sa** [comment]
Do you think it's okay to write basically the same and that I'm coming from CefSharp? Or do I need to write more generally?

**Comment by amaitland** [comment]
Closing as upstream. Please continue the conversation at https://github.com/chromiumembedded/cef/issues/3726
