### ISSUE TITLE
OnBeforeDownload，showDialog:true  ：Exit immediately after confirming the download and save dialog box

### ISSUE THREAD

**Issue by QQ-X5zj** [cefsharp/CefSharp#4857]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

126.2.70

### Operating System

Windows 10

### Architecture

x86

### .Net Version

.net 4.6.2

### Implementation

WinForms

### Reproduction Steps

OnBeforeDownload，showDialog:true
if set OnBeforeDownload，showDialog:false。is ok
Exit immediately after confirming the download and save dialog box

### Expected behavior

v126.2.70
Exit immediately after confirming the download and save dialog box

### Actual behavior

Exit immediately after confirming the download and save dialog box

### Does this problem also occur in the CEF Sample Application

Yes using WPF/OffScreen command line args

**Comment by amaitland** [comment]
This is an upstream bug and should be fixed in the next release.

https://github.com/chromiumembedded/cef/issues/3720

See https://github.com/chromiumembedded/cef/issues/3720#issuecomment-2186780967 for a short term workaround.

**Comment by amaitland** [comment]
Another similar upstream issue https://github.com/chromiumembedded/cef/issues/3722

**Comment by EugeneSunrise** [comment]
Will there be an update soon?

--disable-features=PartitionAllocDanglingPtr,PartitionAllocUnretainedDanglingPtr  - doesn’t fix

**Comment by EugeneSunrise** [comment]
> Another similar upstream issue https://github.com/chromiumembedded/cef/issues/3722

Will there be an update soon?

--disable-features=PartitionAllocDanglingPtr,PartitionAllocUnretainedDanglingPtr - doesn’t fix

**Comment by amaitland** [comment]
Another potentially related issue https://github.com/chromiumembedded/cef/issues/3750

> --disable-features=PartitionAllocDanglingPtr,PartitionAllocUnretainedDanglingPtr - doesn’t fix

If your are having trouble with the suggested workaround then you should ask for help on the upstream issue.

Please don't delete comments and repost the exact same content
