### ISSUE TITLE
WinForms - Tooltip not correctly shown when DPI > 100%

### ISSUE THREAD

**Issue by Pauline3** [cefsharp/CefSharp#4878]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

125.0.210

### Operating System

Windows 10

### Architecture

x64

### .Net Version

.net framework 4.7.2

### Implementation

WinForms

### Reproduction Steps

if the screen configuration, configure the text size to 125%
![image](https://github.com/user-attachments/assets/4cb12af6-dd58-4fe7-8786-22f282dee22e)

Download the minimal example https://github.com/cefsharp/CefSharp.MinimalExample 
Launch the WinForm project
Go on a page with hints (for example wikipedia :https://fr.wikipedia.org/wiki/Wiki)
hover a text/button with the hint several times

### Expected behavior

the hint tooltip should be correctly shown like on other browser or with a 100% text size configutation

### Actual behavior

the hint tooltip is cut 
![image](https://github.com/user-attachments/assets/69657893-e5ad-4741-8cf8-38f90561867a)

### Regression?

Yes it works on version 108.4.130
 

### Does this problem also occur in the CEF Sample Application

Yes using WPF/OffScreen command line args

**Comment by amaitland** [comment]
> Does this problem also occur in the CEF Sample Application

You seem to have skipped this part. Please test with the CEF sample application.


> To help determine where the problem needs to be fixed please download and test using the `CEF Sample Application(cefclient)`.
          1. Download for [x86](https://cef-builds.spotifycdn.com/cef_binary_126.2.12%2Bg162c3d6%2Bchromium-126.0.6478.127_windows32_client.tar.bz2) or [x64](https://cef-builds.spotifycdn.com/cef_binary_126.2.12%2Bg162c3d6%2Bchromium-126.0.6478.127_windows64_client.tar.bz2) or [arm64](https://cef-builds.spotifycdn.com/cef_binary_126.2.12%2Bg162c3d6%2Bchromium-126.0.6478.127_windowsarm64_client.tar.bz2).
          2. Extract tar.bz2 file
          3. Execute cefclient.exe using the **command line args below**:

Please run `cefclient` with the following args

```
cefclient.exe --multi-threaded-message-loop --no-sandbox
```

**Comment by alanareal** [comment]
Sorry, we tested it but skiped the section below.
The problem also occurs when using the CEF sample application.
We are going to report the issue on CEF issue tracker, so this can be closed.
Thanks

**Comment by amaitland** [comment]
Closing as upstream.

https://github.com/chromiumembedded/cef/issues/3744

In future please post a link as reference.
