### ISSUE TITLE
cefsharp 126.2.7  settings.CefCommandLineArgs.Add("disable-pdf-extension", "1");    pdf file is still being loaded

### ISSUE THREAD

**Issue by yyjj7788** [cefsharp/CefSharp#4880]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

126.2.7

### Operating System

Windows Server 2022

### Architecture

x64

### .Net Version

.net 4.8

### Implementation

WinForms

### Reproduction Steps

settings.CefCommandLineArgs.Add("disable-pdf-extension", "1");

### Expected behavior

PDF file not loaded, download directly

### Actual behavior

pdf file is still being loaded

### Regression?

125.0.210  normal

### Does this problem also occur in the CEF Sample Application

Not Tested

**Comment by amaitland** [comment]
You'll need to raise an issue at https://github.com/chromiumembedded/cef/issues (post a link back here for reference). 

Will need to be fixed in `CEF`.

As a short term workaround try reverting back to the alloy bootstrap. See https://github.com/cefsharp/CefSharp/issues/4835#issue-2350564824

Closing as `upstream`.

**Comment by amaitland** [comment]
Looks like you already opened https://github.com/chromiumembedded/cef/issues/3739

CEF no longer supports that argument with the `Chrome Bootstrap`.

**Comment by chacham2** [comment]
I have an application whose primary purpose is to download PDFs. I just updated via NuGet and got version 126.2.18 and ran into this issue. The PDF is not being downloaded. Fwiw, i had to reenable popups (in the Lifespan handler) to see the PDF come up in another window.

Is there a workaround? If bot, what is the latest version that supports this option?
