### ISSUE TITLE
NullReferenceException in the WaitForRenderIdleAsync method

### ISSUE THREAD

**Issue by AlexZhirkov1** [cefsharp/CefSharp#4902]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

126.2.180

### Operating System

Windows 10

### Architecture

AnyCPU

### .Net Version

.NET 8

### Implementation

WinForms

### Reproduction Steps

1. Launch the attached project
2. Press a single button
3. Wait a few hours
[labelprinter-desktop.zip](https://github.com/user-attachments/files/16506942/labelprinter-desktop.zip)

### Expected behavior

The NullReferenceException error does not occur

### Actual behavior

The NullReferenceException error occur with following call stack
Application: Dodo.LabelPrinterDesktop.Windows.exe
CoreCLR Version: 8.0.724.31311
.NET Version: 8.0.7
Description: The process was terminated due to an unhandled exception.
```
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Timers.Timer.UpdateTimer()
   at System.Timers.Timer.set_Enabled(Boolean value)
   at CefSharp.OffScreen.ChromiumWebBrowser.<>c__DisplayClass76_0.<WaitForRenderIdleAsync>b__1(Object s, OnPaintEventArgs args) in C:\projects\cefsharp\CefSharp.OffScreen\ChromiumWebBrowser.cs:line 765
   at CefSharp.Internals.RenderClientAdapter.OnPaint(RenderClientAdapter*, scoped_refptr<CefBrowser>* browser, cef_paint_element_type_t type, vector<CefRect\,std::allocator<CefRect> >* dirtyRects, Void* buffer, Int32 width, Int32 height)
```

### Regression?

[There is a similar problem](https://github.com/cefsharp/CefSharp/issues/4597#issue-1914842453) where version 116.0.190 is specified

### Does this problem also occur in the CEF Sample Application

No

### Other information

We have researched your recommendations that you gave [here](https://github.com/cefsharp/CefSharp/issues/4597#issuecomment-1751842645) and are following them. However, the problem was reproduced anyway. 
We also researched the code of the `WaitForRenderIdleAsync` method and it looks like a race condition is taking place in it. The error occurs after calling method `WaitForRenderIdleAsync` from our code, but our code is not in the call stack. But there is a `RenderClientAdapter.OnPaint`. Perhaps the calls occur in parallel and in one of them some property of `idleTimer` is null.

Since the error occurs outside of our code, we cannot even protect ourselves from it by placing the appropriate call in the `try/catch` block.
We hope for your help in fixing this bug

**Comment by amaitland** [comment]
Your welcome to submit a PR with a proposed solution.

**Comment by amaitland** [comment]
> The error occurs after calling method `WaitForRenderIdleAsync` from our code, but our code is not in the call stack.

For now we'll catch the exception and push it back to the calling `Thread` so it can be handled.
