### ISSUE TITLE
Set --hide-crash-restore-bubble by default to prevent Chromium window from opening after unsuccessful shutdown.

### ISSUE THREAD

**Issue by razor999920** [cefsharp/CefSharp#4903]
### Is there an existing issue for this?

- [x] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

126.2.70

### Operating System

Windows 11

### Architecture

x86

### .Net Version

8

### Implementation

WPF

### Reproduction Steps

I have no been able to pin point the cause for this issue. It happens every 2/3 times of me opening my applicatio.

### Expected behavior

There should be no chromium browser tab or any other window opening besides the application.

### Actual behavior

When I open my WPF application, it opens a chromium browser tab
![cef](https://github.com/user-attachments/assets/a2b24a2d-236b-4bf3-8279-aee3649d9458)

### Regression?

When I downgrade the version the problem goes away but this happens when I upgrade to 126.7.2 or new versions.

### Known Workarounds

Downgrading the version resolves the issue for now.

### Does this problem also occur in the CEF Sample Application

Yes using WPF/OffScreen command line args

### Other information

After going through all the issues, it seems only I have having this problem and I'm assuming I'm missing something during my CefSetting initialization.

Following is my code:
App Startup:
`
 private void Application_Startup(object sender, StartupEventArgs e)
    {
        var settings = new CefSettings()
        {
            ChromeRuntime = true,
            LogFile = "Debug.log",
            LogSeverity = LogSeverity.Verbose,
            CachePath = System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "CefSharp\\Cache"),
        };

        // //Perform dependency check to make sure all relevant resources are in our output directory.
        // settings.CefCommandLineArgs.Add("disable-gpu", "1");
        // settings.CefCommandLineArgs.Add("disable-gpu-compositing", "1");
        // settings.CefCommandLineArgs.Add("disable-extensions", "1");
        // Cef.Initialize(settings, performDependencyCheck: true, browserProcessHandler: null);

        Cef.Initialize(settings);

        // Open Window
        MainWindow mainWindow = new MainWindow();
        mainWindow.Show();
    }
`

MainWindow.xaml
`
<Window x:Class="WpfApp1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:cefSharpWpf="clr-namespace:CefSharp.Wpf;assembly=CefSharp.Wpf"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">

    <Border>
        <cefSharpWpf:ChromiumWebBrowser Name="Browser" />
    </Border>
</Window>
`

MainWindow.xaml.cs
`
public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();

        Browser.LoadUrl("www.google.com");
}
}
`

**Comment by amaitland** [comment]
You'll need to raise an `upstream` issue on the CEF issue tracker at https://github.com/chromiumembedded/cef/issues

Please post a link back here.

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/issues/4835 for backaround

**Comment by razor999920** [comment]
Thank you @amaitland the issue seems to be with the runtime. When i switched back to alloy it stopped working.
I have also filed this issue in the CEF repo and following is the link: https://github.com/chromiumembedded/cef/issues/3767

**Comment by amaitland** [comment]
@razor999920 Thanks 👍 

Based on comment https://github.com/chromiumembedded/cef/issues/3767#issuecomment-2273848911

I think it might be worth setting `--hide-crash-restore-bubble` by default.

Renaming and reopening this issue.
