### ISSUE TITLE
Error code: Crashpad_NotConnectedToHandler

### ISSUE THREAD

**Issue by sergey-prokhorov** [cefsharp/CefSharp#4912]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

127.3.50.0

### Operating System

Windows 11

### Architecture

x64

### .Net Version

4.8.2

### Implementation

WinForms

### Reproduction Steps

randomly time by time

### Expected behavior

loaded content

### Actual behavior

![Screenshot 2024-08-22 224755](https://github.com/user-attachments/assets/dfafc8b9-5093-4e29-8b63-ab88813cbca8)

### Regression?

happens after upgrade 124->127 and CefSharpSettings.RuntimeStyle = CefRuntimeStyle.Chrome;
never seen before on earlier versions.

### Does this problem also occur in the CEF Sample Application

not tested

**Comment by n303ef** [comment]
Yes, it happens when CEF was not shutdown properly (application terminated) and when PersistSessionCookies set to True. It seems that Chromium tries to restore window but doesn't work with CEF.  And "--hide-crash-restore-bubble" which is default now doesn't help.

**Comment by sergey-prokhorov** [comment]
my app doesn't stores sessions. this is 100% not a window restore issue.

**Comment by amaitland** [comment]
Try enabling crashpad see https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#crash-reporting

If the problem persists then you'll need to raise an issue at https://github.com/chromiumembedded/cef/issues

Please post a link back here for reference if you do.

There have been major upstream changes see https://github.com/chromiumembedded/cef/issues/3685 for background

**Comment by sergey-prokhorov** [comment]
@amaitland thanks! after I add crash_reporter.cfg the error changed to
<img width="515" alt="image" src="https://github.com/user-attachments/assets/6f731e20-83fe-4204-8e46-17da4290790c">

**Comment by amaitland** [comment]
Check the log file for a more detailed error.

If there isn't one then analyse the crash dump generated by crashpad, get a stack trace

Search the CEF issue tracker for existing issues.

https://github.com/chromiumembedded/cef/issues

If you cannot find an issue that matches then create a new one.
