### ISSUE TITLE
Unable to Remote Debug when using Chrome Runtime

### ISSUE THREAD

**Issue by puresimmer** [cefsharp/CefSharp#4919]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

127.3.50

### Operating System

Windows 11

### Architecture

x64

### .Net Version

.NET Core 8

### Implementation

WinForms

### Reproduction Steps

If I set the CefSettings.RemoteDebugging = X and then try and debug remotely it is just a blank page or won't load.

Note, I am using Bog-standard Winforms and .NET Core (default MultiThreaded msg loop, no offscreen stuff etc).  The code all works fine if I flip back to the Alloy runtime via CefSettings.ChromeRuntime = false 

I was also able to duplicate in CEFSharp CefSharp.WinForms.Example.netcore source (Latest Master) by adding CefSettings.RemoteDebugging = X  and confirming the same issue in the CEFSharp Example.

Thanks for a great project that I have been happily financially supporting monthly for years!

Shaun

### Expected behavior

Should be able to point at localhost:[remote debugging port] and attach to Devtools

### Actual behavior

Empty page

### Regression?

I have used this for years.  Only a regression on ChromeRuntime - still works on depracated Alloy path. 

### Known Workarounds

Use CefSettings.ChromeRuntime = false

### Does this problem also occur in the CEF Sample Application

Not sure, I will need to add RemoteDebuggingPort code to it in order to test, as I don't see any way to test this using the off-the-shelf sample app.

**Comment by puresimmer** [comment]
Looking deeper in CEFSharp code, this could be an upstream issue in CEF, as it doesn't look like you do anything magical and CEF seemingly fully handles the implementation of RemoteDebuggingPort.  I'll keep you posted on what I find.

Shaun

**Comment by amaitland** [comment]
> this could be an upstream issue in CEF,

See https://github.com/chromiumembedded/cef/issues/3740

**Comment by puresimmer** [comment]
I can't believe I didn't find that in all my spelunking.  Please go ahead and close this.  I'm sure I can make it work with "chrome://inspect" as Marshall suggested.

Thanks for the quick response, great project, and support as always.

Shaun

**Comment by nygis** [comment]
@puresimmer  were you able to remote debug from a different machine via chrome://inspect?  I have no issues doing it locally, but not 100% sure how to discover/inspect on another machine.  Under chrome://inspect 's "Discover Network targets" I can specify an ip:port, but using the remote machine's IP + my CefSettings -> RemoteDebuggingPort of 8088 is never found
