### ISSUE TITLE
[Chrome Runtime] Impossible to use window.open during page load.

### ISSUE THREAD

**Issue by max3163** [cefsharp/CefSharp#4920]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

126.2.180 or later

### Operating System

Windows 10

### Architecture

AnyCPU

### .Net Version

4.8

### Implementation

WinForms

### Reproduction Steps

```
<!DOCTYPE html>
<html lang="en">
  <head>

  </head>
  <body>
    <script>
      let count = 0;
      function openWindowRec() {
        console.log("Try :" + count );
        if (!window.open('', 'ID321')) {
          setTimeout(() => {
            count++;
            openWindowRec();
          }, 500)
        }
      }
    </script>
  </body>
</html>
```

Load this simple page which try to open a new window.

### Expected behavior

A new window is create directly when window.open call is made.

### Actual behavior

Actually nothing happen during many seconds, works only after (about) 10-15 seconds.

### Regression?

It works perfectly on 125 and with settings.ChromeRuntime = false parameter

### Known Workarounds

use settings.ChromeRuntime = false;

### Does this problem also occur in the CEF Sample Application

Not Tested

**Comment by amaitland** [comment]
If you discover an issue with the `Chrome Runtime` then you need to raise the issue on the  **CEF ISSUE TRACKER**

https://github.com/chromiumembedded/cef/issues

Then please post a link in https://github.com/cefsharp/CefSharp/issues/4835

**Comment by amaitland** [comment]
Thanks.

For reference https://github.com/chromiumembedded/cef/issues/3785

**Comment by max3163** [comment]
I re-open this ticket because I just test the issue with the CefClient minimal application and it work as expected ! But it's not the case with the C# Minimal Application. So the problem is on CEfSharp side.

**Comment by max3163** [comment]
arf it's not possible to re-open a ticket...????? I will create a new one so...

**Comment by amaitland** [comment]
> arf it's not possible to re-open a ticket...????? I will create a new one so...

Please don't create duplicate issues. In future please ask for the issue to be reopened.

We don't need unnecessary duplicates.
