### ISSUE TITLE
After setting CefSharpSettings.RuntimeStyle = CefRuntimeStyle.Chrome;, there is a chance that a Chromium error popup will appear when loading the Line extension.

### ISSUE THREAD

**Issue by AB901** [cefsharp/CefSharp#4923]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

127.3.50

### Operating System

Windows 11

### Architecture

x64

### .Net Version

.NET 6.0

### Implementation

WinForms

### Reproduction Steps

```
public partial class App : Application
    {
        protected override void OnStartup(StartupEventArgs e)
        {
            base.OnStartup(e);
            CefSharpSettings.RuntimeStyle = CefRuntimeStyle.Chrome;
        }
    }
```

```
public partial class MainWindow : Window
    {
        ChromiumWebBrowser browser;
        public MainWindow()
        {
            InitializeComponent();
            var url = @"chrome-extension://ophjlpahpchlmihnnnihgmmeilfjmjjc/index.html";
            RequestContextSettings contextSetting = new RequestContextSettings()
            {
                CachePath = @"C:\Users\pc\Desktop\demo\demo_team\demo\bin\x64\Debug\net6.0-windows\data\chrome_user\user_data_1",

            };
            var requestContextBuild = RequestContext.Configure();
            requestContextBuild.WithSharedSettings(new RequestContext(contextSetting));
            browser = new ChromiumWebBrowser(url, requestContextBuild.Create());
            fromHost.Child = browser;
        }
    }
```

### Expected behavior

When I set CefSharpSettings.RuntimeStyle = CefRuntimeStyle.Chrome; and load the Line extension, there is a chance that a Chrome error window will pop up with the error code: STATUS_ACCESS_VIOLATION.

### Actual behavior

![111](https://github.com/user-attachments/assets/cbf370b0-50e7-424e-8c0d-9edad4a439a8)

### Does this problem also occur in the CEF Sample Application

Yes using WPF/OffScreen command line args

**Comment by amaitland** [comment]
If you discover an issue with the `Chrome Runtime` then you need to raise the issue on the  **CEF ISSUE TRACKER**

https://github.com/chromiumembedded/cef/issues

Then please post a link in https://github.com/cefsharp/CefSharp/issues/4835
