### ISSUE TITLE
Feature Request - Add Zoom Support for WinForms version

### ISSUE THREAD

**Issue by chaau** [cefsharp/CefSharp#4927]
The WPF Version of the ChromiumWebBrowser supports zoom controls (https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf/ChromiumWebBrowser.cs#L2635-L2663) 

Can we also add the support for Zoom to the WinForms Version (https://github.com/cefsharp/CefSharp/blob/master/CefSharp.WinForms/ChromiumWebBrowser.cs)?

**Checklist:**
- [x] I have reviewed the [CEF API](https://magpcss.org/ceforum/apidocs3/index-all.html) and have confirmed the feature I'm requesting is possible.
- [x] The Feature I'm requesting is an improvement to Async Javascript Binding (No new feature are being added to the Sync Javascript binding)
- [ ] An open `PR` exists on the [CEF Pull Requests](https://bitbucket.org/chromiumembedded/cef/pull-requests/) and I'd like to propose this feature is added to `CefSharp` when/if it's merged.

**Comment by amaitland** [comment]
The `WinForms` implementation already has zoom support.

See https://github.com/cefsharp/CefSharp/blob/cefsharp/128/CefSharp.WinForms.Example/BrowserForm.cs#L354 for an example.
