### ISSUE TITLE
PermissionRequestType is out of sync compared to cef_permission_request_types_t

### ISSUE THREAD

**Issue by szanto90balazs** [cefsharp/CefSharp#4935]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

128.4.90

### Operating System

Windows 11

### Architecture

x64

### .Net Version

.Net 6.0

### Implementation

WPF

### Reproduction Steps

1. Run the CefSharp.Wpf.Example app with debugger attached
2. Go to `https://permission.site/`
3. Click on the `Location` button
4. Go to the Debug output and find the following debug line sent by this code ([System.Diagnostics.Debug.WriteLine($"{promptId}|{requestedPermissions} {requestingOrigin}");](https://github.com/cefsharp/CefSharp/blob/53d551f541b4cf7412bc38b45f2fa43255f5d837/CefSharp.Example/Handlers/ExamplePermissionHandler.cs#L19C17-L19C109))

### Expected behavior

Expected: `1|Geolocation https://permission.site/`

### Actual behavior

Actual: `1|MicStream https://permission.site/`

### Regression?

The C# `PermissionRequestType` enum and the C++ [cef_permission_request_types_t enum](https://github.com/chromiumembedded/cef/blob/6459917c0ae092e64ebd77a2bbb84e16d8b46e0c/include/internal/cef_types.h#L3644) got out of sync, seems like since this CEF commit: https://github.com/chromiumembedded/cef/commit/dc2231cdfb6c355d83c6121ffe2912ea30e6eef0

![image](https://github.com/user-attachments/assets/a0451de5-61de-468e-9f35-ce415cd1553e)
 

### Known Workarounds

You could introduce `MyPermissionRequestType` based on the values of `cef_permission_request_types_t` and cast `PermissionRequestType` to `uint` to `MyPermissionRequestType`, this will require a custom permission handler implementation.

### Does this problem also occur in the CEF Sample Application

No

**Comment by szanto90balazs** [comment]
I'm happy to send a PR with and updated `PermissionRequestType` and potentially come up with some tests. In the past the uint value of Geolocation changed two times in the enum according to [the history of cef_types.h](https://github.com/chromiumembedded/cef/blame/6459917c0ae092e64ebd77a2bbb84e16d8b46e0c/include/internal/cef_types.h#L3644)

**Comment by amaitland** [comment]
PR would be most welcome 👍
