### ISSUE TITLE
DevTools does not open as child popup window.

### ISSUE THREAD

**Issue by AASanch** [cefsharp/CefSharp#4936]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

128.4.90

### Operating System

Windows 10

### Architecture

x64

### .Net Version

net472

### Implementation

WinForms

### Reproduction Steps

Showing DevTools on the MinimalExample  using the code below does not work as it did previously.

```
        private void ShowDevToolsMenuItemClick(object sender, EventArgs e)
        {
            var host = browser.GetBrowserHost();
            var windowInfo = new WindowInfo();
            windowInfo.SetAsPopup(host.GetWindowHandle(), "DevTools");
            browser.ShowDevTools(windowInfo);

        }
```

In version 128.4.90, the code above shows DevTools on top of the browser control, covering up large part of its top-left are.

![image](https://github.com/user-attachments/assets/88dbba26-292b-48e1-941d-b06aec0d516f)

In a previous version (121.3.70), the same code above shows DevTools as a child popup window of the browser.

![image](https://github.com/user-attachments/assets/d6752783-c60d-49e6-bb6f-19350e4507ac)

### Expected behavior

DevTools should show up as a popup window.

### Actual behavior

DevTools is rendered on top of the browser control, covering up a large part of its top-left area.

### Regression?

Yes.  This works in v121.3.70.

### Does this problem also occur in the CEF Sample Application

Not Tested

**Comment by amaitland** [comment]
Major upstream changes happened recently, see https://groups.google.com/g/cef-announce/c/s1WaovAopFo/m/LV5eiNX1BgAJ?pli=1 for background.

--- 
The `Chromium Embedded Framework (CEF)` project has it's own [Issue Tracker](https://github.com/chromiumembedded/cef/issues), please report this issue there. `CefSharp` is just one of many wrappers around the [Chromium Embedded Framework (CEF)](https://bitbucket.org/chromiumembedded/cef/)

If you do find an existing issue that matches this one or create a new one then post a link here for others. 

Closing this as `upstream` as changes/fixes need to be made in `CEF`.
