### ISSUE TITLE
bool IDownloadHandler.CanDownload in second time Run Javascript Click Download File Can't Download

### ISSUE THREAD

**Issue by chendemand** [cefsharp/CefSharp#4952]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

129.0.110

### Operating System

Windows 10

### Architecture

x64

### .Net Version

.Net 4.8

### Implementation

WinForms

### Reproduction Steps

script = $@"document.getElementById({si}).click();";

first time Can Download file.

bool IDownloadHandler.CanDownload --> bool IDownloadHandler.OnBeforeDownload -->void IDownloadHandler.OnDownloadUpdated (many time) --> Successful Download file

but second time Can't Download file .

only 
bool IDownloadHandler.CanDownload

I try many way,After then copy url example
https://github.com/cefsharp/CefSharp/blob/d0486b317967fe4a3eb00e783c26d93d2a00e594/CefSharp/Handler/DownloadHandler.cs 
code to use

it is same problem.

I have  add code 『chromiumWebBrowser1.ShowDevTools();』
use javascript code to click , second time is same problem Download failed. 

### Expected behavior

I want download many files use   javascript ".Click" to Downlaod file

for 1 ~ 20 files in page

### Actual behavior

It can Download file in first time only. 

### Regression?

I in 126.xxx ~ 129.0.110 can't to Run

### Known Workarounds

Pleas help me 。
How to use ？ thanks . 

### Does this problem also occur in the CEF Sample Application

Yes using WPF/OffScreen command line args

**Comment by amaitland** [comment]
The `Chromium Embedded Framework (CEF)` project has it's own [Issue Tracker](https://github.com/chromiumembedded/cef/issues), please report this issue there. `CefSharp` is just one of many wrappers around the [Chromium Embedded Framework (CEF)](https://github.com/chromiumembedded/cef/)

If you do find an existing issue that matches this one or create a new one then post a link here for others. 

Closing this as `upstream` as changes/fixes need to be made in `CEF`.

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/wiki/General-Usage for background

**Comment by m-aljammali-stramit** [comment]
I have created https://github.com/chromiumembedded/cef/issues/3957  at Chromium Embedded Framework (CEF) project [Issue Tracker](https://github.com/chromiumembedded/cef/issues)
