### ISSUE TITLE
JS-click events and LifeSpanHandler are not working in ChromeRuntime

### ISSUE THREAD

**Issue by MyzLee** [cefsharp/CefSharp#4974]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

130.1.90

### Operating System

Windows 11

### Architecture

x64

### .Net Version

4.8

### Implementation

WPF

### Reproduction Steps

take a look at https://github.com/cefsharp/CefSharp/discussions/4913

### Expected behavior

Trigger events

### Actual behavior

nothing happens

### Does this problem also occur in the CEF Sample Application

Yes using WPF/OffScreen command line args

**Comment by amaitland** [comment]
> take a look at #4913

Closing as there is already a discussion regarding this topic.
