### ISSUE TITLE
WinForms - A window.confirm() dialog generated by this page was suppressed because this page is not the active tab

### ISSUE THREAD

**Issue by rustak** [cefsharp/CefSharp#4976]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

126.2.180 

### Operating System

Windows 10

### Architecture

x64

### .Net Version

.Net 4.8

### Implementation

WinForms

### Reproduction Steps

1. In the test application `CefSharp.WinForms.Example`, open the following webpage: https://googlechrome.github.io/samples/block-modal-dialogs-sandboxed-iframe/
2. Click on the red and blue `window.confirm("Hello")` buttons.

### Expected behavior

A confirm dialog opens.

### Actual behavior

The dialog does not open, and the following message appears in the status bar:

> A window.confirm() dialog generated by this page was suppressed because this page is not the active tab of the front window. Please make sure your dialogs are triggered by user interactions to avoid this situation. https://www.chromestatus.com/feature/5140698722467840

### Regression?

In version 124.x, this was working, likely because it still used the Alloy style by default.

### Known Workarounds

If the Alloy style is used with `CefSettings.ChromeRuntime = false`, the dialog opens as expected. 

However, Alloy style has another issue that can be resolved by upgrading to Chromium Runtime, and since it is now deprecated, I don’t consider this a valid workaround.

### Does this problem also occur in the CEF Sample Application

No

### Other information

I tested this in the Cef Sample application, and it worked fine there. The dialogs opened even when I ran `cefclient.exe` without the `--use-alloy-style` flag. Therefore, I believe this is not an issue with CEF itself, but with CefSharp.

However, I found similar issue here:
* https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=20022
* https://github.com/chromiumembedded/cef/issues/3818

But I couldn't replicate it in the CEF sample application. The issue only occurs in `CefSharp.WinForms.Example`.

**Comment by amaitland** [comment]
> ### CefSharp Version
> 126.2.180

Have you confirmed this exists in the current supported version? `M130` at time of writing.

> Alloy style has another issue that can be resolved by upgrading to Chromium Runtime, and since it is now deprecated, I don’t consider this a valid workaround.

The `Alloy bootstrap` was deprecated and removed. The `Alloy styling` is still supported and used by default.

**Comment by amaitland** [comment]
> I tested this in the Cef Sample application, and it worked fine there. The dialogs opened even when I ran `cefclient.exe` without the `--use-alloy-style` flag.

Testing with `cef_binary_130.1.9+gfc42567+chromium-130.0.6723.70_windows64_client` using 

```
cefclient.exe --multi-threaded-message-loop --no-sandbox --use-alloy-style
```

Clicking on the `Red` confirm example logs the following to the console

```
A window.confirm() dialog generated by this page was suppressed because this page is not the active tab of the front window. Please make sure your dialogs are triggered by user interactions to avoid this situation. https://www.chromestatus.com/feature/5140698722467840
```

Opening `DevTools` and then the dialog shows.

Behavior appears to be consistent with the `MinimalExample`.

Making this as `upstream` as the issue reproduces with `cefclient.`

**Comment by amaitland** [comment]
Appears that https://github.com/chromiumembedded/cef/issues/3818 is the correct `upstream` issue.

Closing as upstream

**Comment by rustak** [comment]
Switching to a `Chrome Styled` window indeed resolved the issue. I was confused about `RuntimeStyle` and didn't realize that `Alloy` is used by default. Thank you for your help!
