### ISSUE TITLE
File downloads to users\..\downloads in background

### ISSUE THREAD

**Issue by DragonHawkAlpha** [cefsharp/CefSharp#4999]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

131.2.70

### Operating System

Windows 11

### Architecture

x64

### .Net Version

.Net 4.8.1 (.Net 4.8.9282.0)

### Implementation

WinForms

### Reproduction Steps

Using an IDownloadHandler with CanDownload returning true.  With IDownloadHandler.OnBeforeDownload firing (and debug pausing).  File downloads to: c:\users\...\downloads.  On version 124.3.50 this did not happen code from the application could take-over.  Now the application downloads as before but a rouge copy downloads in the background to the users' download folder.

### Expected behavior

Do not auto-download to users downloads folder. But let the application code handle the download as with version 124.3.50 when IDownloadHandler is used.

### Actual behavior

Downloads automatically to users downloads folder.

### Regression?

Yes 124.3.50.

### Known Workarounds

Downgrade.

### Does this problem also occur in the CEF Sample Application

Not Tested

### Other information

Is this due to an additional I/Handler that was not required in older versions?

**Comment by amaitland** [comment]
`CEF` handles the download behavior, so you'll need to raise an issue on https://github.com/chromiumembedded/cef/issues

Please search to see if there's an open issue, if not, open one.

Please post a link back here for reference.

Closing as `upstream` as will need to be resolved in `CEF`.

> Is this due to an additional I/Handler that was not required in older versions?

Unlikely. More likely major upstream changes that happened recently.

https://github.com/chromiumembedded/cef/issues/3685
