### ISSUE TITLE
Running without renderer sandbox

### ISSUE THREAD

**Issue by Healian** [cefsharp/CefSharp#501]
i don't know why i am always getting in trouble. been a couple of hours without a simple reason to this error... can you help me please. 

note: this issue only occurs with cef 33.0.. 
also i tried setting a sub render process with no luck ..

**Comment by pipiscrew** [comment]
**v39.0.0-pre02**
on windows 8 x64, running with x86 dlls, the debug.log 
[0225/143115:ERROR:renderer_main.cc(207)] Running without renderer sandbox
[0225/143148:WARNING:message_in_transit_queue.cc(18)] Destroying nonempty message queue

**Comment by amaitland** [comment]
@pipiscrew See my comment above, it's safe to ignore that error.

**Comment by tylerlong** [comment]
I can reproduce this issue with version 45.0 from NuGet, Windows 10, VS 2015. I am wondering is there any way to disable the generation of `debug.log`.

**Comment by jankurianski** [comment]
Try `LogSeverity.Disable`.  Search the GitHub code for an example of how to set it: https://github.com/cefsharp/CefSharp/search?utf8=%E2%9C%93&q=LogSeverity&type=Code

If you have any follow-up questions, please ask on Gitter, we are moving there for all questions: https://gitter.im/cefsharp/CefSharp

**Comment by amaitland** [comment]
> I can reproduce this issue with version 45.0 from NuGet, Windows 10, VS 2015.

It's not really an issue, it's more of a warning that's safe to ignore.
