### ISSUE TITLE
CefSharp3 WPF does not load MP4/PDF/SWF

### ISSUE THREAD

**Issue by KennyKay** [cefsharp/CefSharp#523]
I've been trying to load plugins in chromium browser such as VLC (for mp4), Adobe Reader (for pdf) and Flash(swf).

I found out that all plugins work in CefSharp.WinForms.Example but it does not work properly for CefSharp.Wpf.Example: when using the wpf application and loading any plugin, the screen becomes gray but the sound still works.

Is there a way to make plugins work for the WPF version of CefSharp3?
Thanks,

**Comment by dandanyouxiang** [comment]
settings.CefCommandLineArgs.Add("ppapi-flash-path", "PepperFlash\pepflashplayer.dll");
settings.CefCommandLineArgs.Add("ppapi-flash-version", "20.0.0.228");
