### ISSUE TITLE
How to implement downloading the files to specific path

### ISSUE THREAD

**Issue by rsanjay23** [cefsharp/CefSharp#545]
I have issue in downloading the files to my system.

Please provide samples to achieve it.

**Comment by rizkidzulkarnain** [comment]
can I custom path file where file downloaded ? thx

**Comment by merceyz** [comment]
> can I custom path file where file downloaded ? thx

See https://github.com/cefsharp/CefSharp/issues/545#issuecomment-61219883

**Comment by rizkidzulkarnain** [comment]
thx
i have done with this 

public void OnBeforeDownload(IBrowser browser, DownloadItem downloadItem, IBeforeDownloadCallback callback)
        {
            OnBeforeDownloadFired?.Invoke(this, downloadItem);
            string downloadPath = @"C:\File\cefsharp\";
            if (!callback.IsDisposed)
            {
                using (callback)
                {
                    callback.Continue(downloadPath + downloadItem.SuggestedFileName, showDialog: false);
                }
            }
        }
