### ISSUE TITLE
Scrollbars on the browser control

### ISSUE THREAD

**Issue by toml86** [cefsharp/CefSharp#55]
I cannot work out how to disable the scroll bars on the browser window. Is this possible?

**Comment by boorsekala** [comment]
in winform examples on method AddTab just comment Dock = DockStyle.Fill
example
  var browser = new BrowserTabUserControl(......)
            {

              //  Dock = DockStyle.Fill
                
            };

it worked for me

**Comment by gstgusts** [comment]
You can disable scrollbars, by executing javascript, then browser has loaded.

`
 var script = "var css='body {   overflow-x: hidden; overflow-y: hidden;}  }'; " +
                   "var head = document.head || document.getElementsByTagName('head')[0]; var style = document.createElement('style'); style.type = 'text/css'; if (style.styleSheet){  style.styleSheet.cssText = css} else { style.appendChild(document.createTextNode(css));  head.appendChild(style);}";

 private void CefWebBrowserFrameLoadEnd(object sender, FrameLoadEndEventArgs e) {
            if (e.Frame.IsMain) {
                Dispatcher.Invoke(() => {
                    e.Browser.MainFrame.ExecuteJavaScriptAsync(script));
                });
            }
        }`
