### ISSUE TITLE
RegisterJSObject does not Register

### ISSUE THREAD

**Issue by DocBond** [cefsharp/CefSharp#567]
The following code doesn't fail but does not register the JS object correctly.  typeof(TOBJ) in Javascript returns 'undefined'.

```
public MainWindow()
{
    Cef.Initialize(new CefSettings());
    InitializeComponent();
    CefSharp.Wpf.ChromiumWebBrowser Browser = new CefSharp.Wpf.ChromiumWebBrowser();
    Cef.RegisterJsObject("TOBJ", new TestJSObject());
    Browser.Load("file://c:/dev/test.html");
    TheGrid.Children.Add(Browser);
}
```

**Comment by Squeaky-bed** [comment]
It's stupid because I wasted an hour on this only to find out that if the method is called "OnJavaMessage" it would only see it if I call "onJavaMessage" with a lower case o :|
