### ISSUE TITLE
by using cefsharp how to get the browser page source

### ISSUE THREAD

**Issue by gyaneshtsg** [cefsharp/CefSharp#57]
HI,

how can i use the cefsharp browser to get the page source. I mean i would like to use cefsharp just like a form filling page programmatically , by using cefsharp browser by programmatically i want to fill some content with in the site it displays, can i perform a click on a button of the browser by programmatically.

**Comment by JohnBergman** [comment]
Bump, I don't see a way in the current code to do this, how does one get the current source html of that is being displayed?

**Comment by jankurianski** [comment]
@JohnBergman Using `GetSourceAsync()`.

Documentation: https://github.com/cefsharp/CefSharp/blob/bae3c28e9231febcb620701bfbacae43299c4f5e/CefSharp/WebBrowserExtensions.cs#L161

Example: https://github.com/cefsharp/CefSharp/blob/8a93ba65649cd3f9d3330b2bef6d01d927f17e29/CefSharp.WinForms.Example/BrowserTabUserControl.cs#L263

**Comment by JohnBergman** [comment]
Perfect!  Thanks @jankurianski
