### ISSUE TITLE
Clicking on Control using Winforms does not Set Focus

### ISSUE THREAD

**Issue by RadicalLinux** [cefsharp/CefSharp#570]
When using docking tabs menus etc. that should automatically close when they no longer have focus, clicking on the browser does not fire the event needed.  You can duplicate the issue by running the winforms example. After the browser is fully loaded click on the edit menu.  Now click back on the browser.  The edit menu will not close like it should.  Also the mouse events are not triggered.

BTW All the other issues have been resolved!  Great Work!

**Comment by jankurianski** [comment]
@RadicalLinux Not sure if it helps you any more, but I found a hack to make this work for my case.  If you paste this into `BrowserTabUserControl.cs` in the WinForms example project then the `ToolStrip` will get dismissed when you click into the browser:

https://gist.github.com/jankurianski/2163d7928d3d6f839e47

**Comment by RadicalLinux** [comment]
Thanks, I'm giving it a try now.

**Comment by asdorius** [comment]
Hey guys, thanks for the great workaround. Almost got it working for me.. almost. My problem is that the workaround is causing Chromium to lose focus for a short time. This destroys functionality in my app because as a graphics editor it relies heavily on mouse event handling.Any ideas on how to fix this?

**Comment by jankurianski** [comment]
You could try posting a different message type instead of WM_LBUTTONDOWN? See here for the messages that will cause the ToolStrip to close:
http://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/ToolStripManager.cs,1249

**Comment by asdorius** [comment]
This is it! Thank you so much. When posting WM_NCLBUTTONDOWN (0x00A1), cef doesn't lose focus and handles the following mouse click correctly.

**Comment by amaitland** [comment]
@jankurianski Is it worth adding your `Gist` example to the `WinForms.Example` project? Seems like there's enough interest.

**Comment by jankurianski** [comment]
> This is it! Thank you so much. When posting WM_NCLBUTTONDOWN (0x00A1), cef doesn't lose focus and handles the following mouse click correctly.

@asdorius No, thank you.  :+1:   I had a bug in my app when running on VMs where the `mouseup` never got sent to CefSharp, and `WM_LBUTTONDOWN` was the cause of the problem.

I've updated my `Gist` and the `WinForms.Example` PR to use `WM_NCLBUTTONDOWN` now.

**Comment by jankurianski** [comment]
> @jankurianski Is it worth adding your Gist example to the WinForms.Example project? Seems like there's enough interest.

Good idea.  It's too hacky to be built-in to the `ChromiumWebBrowser` class, but putting it in `WinForms.Example` makes sense.
