### ISSUE TITLE
Implementing UserStyleSheetLocation in CefSharp

### ISSUE THREAD

**Issue by Netizine** [cefsharp/CefSharp#571]
Does anyone know how to inject custom css into a page before the page renders. I have tried achieving this using javascript but it doesn't remove the scroll bars. 

If it isn't currently in the road-map, would anyone be interested in a Paypal donation to a Friday night out to try implement this. :-) 

The CSS is as follows.
html, body, iframe {margin: 0 ;padding: 0;border: 0 ;overflow-y: auto;overflow-x: hidden;max-width: 320px;}::-webkit-scrollbar {width: 0;height: 0;}::-webkit-scrollbar-thumb {min-height: 0;min-width: 0;}

In Chromium and xilium it is set by implementing the UserStyleSheetLocation which is basically a style sheet added to every page before its rendered. Line 121 here https://searchcode.com/codesearch/view/66862333/

**Comment by evaldsurtans** [comment]
JS snippet to inject CSS Link hrefs

Maybe someone find it helpful

```
$('link[rel="stylesheet"]').each(function () {
   var href = $(this).attr('href');
    $.get( href, function( data ) {
        //console.log( "Data Loaded: " + data );
        var node = document.createElement('style');
        node.innerHTML = data;
        document.body.appendChild(node);
    });
});
```
