### ISSUE TITLE
Feature Request - Change Locale at runtime

### ISSUE THREAD

**Issue by Bodekaer** [cefsharp/CefSharp#574]
Hey,
We're trying to change the `Locale` after launching a browser.
Basically we want to change the spellchecking language.

We can change the initial value here:
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/CefSettings.h#L93

However that doesn't allow us to change it later. Or can we somehow "re-initialize" or perhaps run command line args after CEF has been loaded and is running?

**Comment by Bodekaer** [comment]
Asked for update here:
https://code.google.com/p/chromiumembedded/issues/detail?can=1&start=0&num=100&q=change%20settings%20runtime&colspec=ID%20Type%20Status%20Priority%20Milestone%20Owner%20Summary&groupby=&sort=&id=1058

**Comment by rfgamaral** [comment]
Just a heads up that currently changing the `Locale` option to change the spell checking dictionary also changes the context menus items language. Which is probably not expected.

These should be two separate options, one to change the dictionary language during runtime and another to really change the language context menus (and probably other controls) are displayed on.

**Comment by Bodekaer** [comment]
Is it possible now to change the spell checking language at run-time? (or is a restart still required?)

**Comment by amaitland** [comment]
> Which is probably not expected.

What's unexpected about that? It's like changing the locale on windows, changes menus, dictionaries.

> These should be two separate options, one to change the dictionary language during runtime and another to really change the language context menus (and probably other controls) are displayed on.

Would first need to confirm that `Chromium` supports the ability to specify them separately, and likely have to submit a patch to `CEF`.

**Comment by rfgamaral** [comment]
It's unexpected because I look at other browsers (Firefox/Chrome) and changing the locale does not change the spell checking dictionary, or vice-versa. Maybe the `Locale` option shouldn't be changing the spell checking dictionary and maybe that's what can be considered unexpected (and not the other way around, like I initially stated). They are (or should be) independent of each other. That's all I'm saying.

**Comment by amaitland** [comment]
> They are (or should be) independent of each other. That's all I'm saying.

Feel free to discuss the issue `upstream`.

**Comment by amaitland** [comment]
Just updating the link to https://bitbucket.org/chromiumembedded/cef/issues/1058

**Comment by amaitland** [comment]
A new issue has been opened that covers this see https://bitbucket.org/chromiumembedded/cef/issues/1709/allow-configuration-of-preferences-during

Sounds somewhat promising that it will be implemented in the near future.

**Comment by amaitland** [comment]
`upstream` issue has been resolved on the `CEF master` branch, there is no release branch of `CEF` that includes these changes. When the next release branch is created we can look at upgrading.

Code changes will be required, so anyone keep on implementing this feature please make yourself known.

**Comment by amaitland** [comment]
`master` has been upgraded to `CEF 3.2526.1347`

**Comment by amaitland** [comment]
See  #1444 for a partial implementation of this

**Comment by amaitland** [comment]
Change have been merged into `master`. New feature needs testing/feedback so please let me know how it goes.

**Comment by codingyourlife** [comment]
State closed and it seems this was implemented but I don't know how to use it. I opened a Stackoverflow question for this: [Change Cefsharp Locale at runtime](https://stackoverflow.com/questions/45327984/change-cefsharp-locale-at-runtime)
