### ISSUE TITLE
CefSharp.Wpf Can‘t support other Input Method

### ISSUE THREAD

**Issue by willent** [cefsharp/CefSharp#583]
cef version:33.0.1750 r1738 cefsharp version 33.0.2.0
CefSharp.Wpf it is unable to input any Chinese。

**Comment by ssdyz** [comment]
Is this problem solved? Very worried, please do me a favor, thank you

**Comment by amaitland** [comment]
Updating link to cef bitbucket site https://bitbucket.org/chromiumembedded/cef/issue/1019

Issue is still unsolved, you can try the workaround proposed above.

**Comment by ralphmayr** [comment]
I created a PR that contains the fix proposed in this issue - as mentioned before, I'm confident that this fixed the issue for most cases.
We'd be very grateful if this would make it into the next CefSharp release ;)

**Comment by amaitland** [comment]
So the upstream issue has been marked as closed
https://bitbucket.org/chromiumembedded/cef/issues/1019

Anyone care to take the current `master` for a spin and see how it goes? (Will of course have to comment out https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf.Example/Views/BrowserTabView.xaml.cs#L30)

**Comment by amaitland** [comment]
I've removed the workaround from `master` see https://github.com/cefsharp/CefSharp/commit/c7c90581da7ed3dda80fd8304a856462d133d9a7

As the `upstream` issue has been resolved I'm closing this. (If someone can still reproduce the problem with latest `master` then this can be reopened).

**Comment by luciusli** [comment]
I can still reproduce this problem. FYI cefclient build 2454 from cefbuilds.com works flawlessly.

**Comment by amaitland** [comment]
> FYI cefclient build 2454 from cefbuilds.com works flawlessly.

Just confirming that you ran `cefclient` with the `--off-screen-rendering-enabled` command line argument?

**Comment by luciusli** [comment]
I didn't but if run with that argument, the character selection box is misaligned.

**Comment by amaitland** [comment]
`WPF` uses `off screen rendering`, without that argument it behaves like the `WinForms` version.

If the problem still persists then someone with a vested interest in `IME` will have to troubleshoot the issue.

**Comment by amaitland** [comment]
Looks like the problem still exists, rather than multiple issues, closing this one in favor of  #1262
