### ISSUE TITLE
Download Updates stopping after navigating to a different domain

### ISSUE THREAD

**Issue by busy75** [cefsharp/CefSharp#595]
I have been playing with the download functionality and noticed an unexpected behavior. I initiated a download and navigated to a different page of the same domain. The OnDownloadUpdated() method of the DownloadHandler still kept being called. Then I have left the domain (went to google.com) and suddenly OnDownloadUpdated() is not called anymore though the file download still progressed in the background.

The only modification I made to the code base of the master branch is that I have created an instance of the DownloadHandler() and assigned it to the browser in the constructor of the BrowserTabView (WPF Example).

        public BrowserTabView()
        {
            InitializeComponent();

            browser.RequestHandler = new RequestHandler();
            browser.RegisterJsObject("bound", new BoundObject());
            
            browser.DownloadHandler = new DownloadHandler(); 
            ^^
        }

**Comment by amaitland** [comment]
`Upstream` issue has been created for this, see https://bitbucket.org/chromiumembedded/cef/issues/1833/ondownloadupdated-is-no-longer-called#comment-None

**Comment by amaitland** [comment]
`Upstream` issue has been resolved, tagging this as `49` as changes are in `2623` branch.

**Comment by amaitland** [comment]
`master` has been upgraded to `2623` so closing.
