### ISSUE TITLE
Disallow new window/tab

### ISSUE THREAD

**Issue by richmondwang** [cefsharp/CefSharp#600]
Hi, I was looking anywhere and tried anything I can but I cant seem to disable or disallow creating new window (or tab).
Like when I click the middle mouse button, or shift+Enter on forms, etc..
I like to disallow that, because my app should only have one IWebBrowser view. 

CefSharp is great! I'm loving it ^_^

**Comment by CFlanc** [comment]
How To Do the same on WinForm

**Comment by amaitland** [comment]
The `OnBeforePopup` method may have changed, the basic concept should still be the same.

**Comment by sohaibameen** [comment]
@amaitland : I have want to open a page in new tab with target="_blank". 

Parent link:
"http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_target"

Child link that needs to be opened in a new tab
Visit W3Schools.com!
"<a href="http://www.w3schools.com" target="_blank">Visit W3Schools.com!</a>"

I have modified OnBeforePopup() function 
with 
browserControl.Load(targetUrl);
            //Default behaviour
newBrowser = null;

and It load child page in the same window which is needs to be opened in new tab.
Please suggest how to open it in a new tab?

**Comment by lavkeshdwivedi** [comment]
Hi Alex,

public virtual bool OnBeforePopup(IWebBrowser browser, string url, ref int x, ref int y, ref int width, ref int height)
    {
        // Preserve new windows to be opened and load all popup urls in the same browser view
        browser.Load(url);
        //
        return true;
    }

    public virtual void OnBeforeClose(IWebBrowser browser)
    {
        // DO NOTHING
    }

this solution is not working in version 57

**Comment by judge2020** [comment]
New one that works with the current stable nuget release 57

```
    public class BrowserLifeSpanHandler : ILifeSpanHandler
    {
        public bool OnBeforePopup(IWebBrowser browserControl, IBrowser browser, IFrame frame, string targetUrl, string targetFrameName,
            WindowOpenDisposition targetDisposition, bool userGesture, IPopupFeatures popupFeatures, IWindowInfo windowInfo,
            IBrowserSettings browserSettings, ref bool noJavascriptAccess, out IWebBrowser newBrowser)
        {
            Process.Start(targetUrl);
            newBrowser = null;
            return true;
        }

        public void OnAfterCreated(IWebBrowser browserControl, IBrowser browser)
        {
            //
        }

        public bool DoClose(IWebBrowser browserControl, IBrowser browser)
        {
            return false;
        }

        public void OnBeforeClose(IWebBrowser browserControl, IBrowser browser)
        {
            //nothing
        }
    }
```
