### ISSUE TITLE
libcef

### ISSUE THREAD

**Issue by bjarteskogoy** [cefsharp/CefSharp#601]
Is it possible to place libcef.dll in another folder than CefSharp.BrowserSubprocess.exe ?

**Comment by amaitland** [comment]
Adding this for my own reference, it maybe possible to use the `<probing/>` app config entry to move all of `CefSharp` to a sub folder.

https://msdn.microsoft.com/en-us/library/4191fzwb.aspx

**Comment by amaitland** [comment]
Quick test and it appears that it works as advertised.

- Update `MinimalExample` app to set `BrowserSubprocessPath = @"cefsharp\CefSharp.BrowserSubprocess.exe"}`
- Edit `app.config` and add `<probing privatePath="cefsharp"/>` as outlined in msdn article
- Copy all `CefSharp` dll's in `cefsharp` subfolder (do this second so the `msbuild` task doesn't copy the dll's)
- Run app.

**Comment by amaitland** [comment]
You'll also have to set the `CefSettings.BrowserSubprocessPath` property, currently defaults to being the executing path.

https://github.com/cefsharp/CefSharp/blob/cefsharp/47/CefSharp.Core/CefSettings.h#L29

**Comment by amaitland** [comment]
Example using new `CefLibraryHandler` class, dlls in this example have been moved to `D:\projects\CefSharp.MinimalExample\libs\` and the `cef.redist.x86.targets`, `cef.redist.x64.targets` and `CefSharp.Common.targets` files removed from the `csproj`, they will be re-added next time you upgrade the `Nuget` packages. This is a rough example, only attempt if your comfortable supporting yourself. Make sure you read the comments inline below.

```c#
// Copyright © 2010-2015 The CefSharp Authors. All rights reserved.
//
// Use of this source code is governed by a BSD-style license that can be found in the LICENSE file.

using System;
using System.Runtime.CompilerServices;
using System.Windows.Forms;

namespace CefSharp.MinimalExample.WinForms
{
    public class Program
    {
        [STAThread]
        public static void Main()
        {
            var libraryLoader = new CefLibraryHandle(@"D:\projects\CefSharp.MinimalExample\libs\libcef.dll");

            var isValid = libraryLoader.IsInvalid;

            //Calls to CEF cannot be made directly in this method, doing so would
            //attempt to load `CefSharp.Core` which requires `libcef.dll` which
            //we are now dynamically loading from our own folder. 
            LoadForm();
            
            libraryLoader.Dispose();
        }

        //Must make this this method isn't inlined otherwise it will
        // dynamically load CefSharp.Core
        [MethodImpl(MethodImplOptions.NoInlining)]
        private static void LoadForm()
        {
            var settings = new CefSettings();
            //Must specify these three paths
            settings.BrowserSubprocessPath = @"D:\projects\CefSharp.MinimalExample\libs\CefSharp.BrowserSubprocess.exe";
            settings.LocalesDirPath = @"D:\projects\CefSharp.MinimalExample\libs\locales";
            settings.ResourcesDirPath = @"D:\projects\CefSharp.MinimalExample\libs";

            //Must set performDependencyCheck: false 
            Cef.Initialize(settings, shutdownOnProcessExit: false, performDependencyCheck: false);

            var browser = new BrowserForm();
            Application.Run(browser);
        }
    }
}


```

**Comment by amaitland** [comment]
You can copy paste `CefLibraryHandler` into your project if you require this in older versions, it's a purely **managed** implementation.

**Comment by amaitland** [comment]
With #1714 it should also be possible to modify the example `Assembly Resolver` to load the resources from any folder you like. Probably slightly easier than the method listed above.

**Comment by BlackBooth** [comment]
Hi, I created a gist, where I combined all the techniques mentioned above to move the cefsharp files to a subfolder. You can find it [here](https://gist.github.com/BlackBooth/19ce027c4f68c1eb4fc1144988ca6662). When you compile it in debug mode nothing happens, but when you use release mode the AssemblyResolver does its magic and redirects all cefsharp dll requests to the designated subfolder. Right now I manually move the cefsharp files to the subfolder. Maybe there is a better solution, to do this automatically when compiling in release mode.

**Comment by amaitland** [comment]
I've never seen a problem with `Debug` mode, so maybe that's specific to your environment? Regardless, going forward the recommended approach would be to use #1714

**Comment by BlackBooth** [comment]
It does nothing on `debug` because I want it to ;)
```csharp
#if !DEBUG
            AppDomain.CurrentDomain.AssemblyResolve += CurrentDomain_AssemblyResolve;
#endif
```
It uses the approach of #1714

**Comment by amaitland** [comment]
> It does nothing on debug because I want it to ;)

I have no idea what the purpose of your comments is then?

**Comment by BlackBooth** [comment]
Sorry, I had my mind on another problem, which turned out not to be one. So i changed my gist to be more flexible. 

- [Link to Gist](https://gist.github.com/BlackBooth/19ce027c4f68c1eb4fc1144988ca6662)
- Compile mode doesn't matter (release / debug)
- When you run your program, the main assembly looks for the chefsharp files in the same directory like the main executable and loads them
- If it can't find them there the assembly resolver gets to work and tries to load the assembly from the designated `cefSubFolder`

So if you like a clean folder structure you move all cefsharp files to the `cefsharp` subfolder

**Comment by amaitland** [comment]
> Sorry, I had my mind on another problem, which turned out not to be one. So i changed my gist to be more flexible.

@BlackBooth Ok, thanks for the example :+1: In general I'd recommend removing all unnecessary pieces of code when providing an example, like `javascript binding`, browser settings`, form resizing. Inline comments would be worth adding as your providing a reference that others will use.

**Comment by XanderLuciano** [comment]
For future reference, I just followed your steps and did a quick tutorial on StackOverflow to (hopefully) make the steps a little easier to follow.

http://stackoverflow.com/questions/39400139/how-to-move-cefsharp-dependencies-and-files-to-subdirectory/39400140#39400140

**Comment by amaitland** [comment]
> For future reference, I just followed your steps and did a quick tutorial on StackOverflow to (hopefully) make the steps a little easier to follow.

@XanderLuciano Your example is unnessicarily complex, you don't need a `probingPath`, and an `assembly resolver`. Just use something like https://gist.github.com/BlackBooth/19ce027c4f68c1eb4fc1144988ca6662

When `53.0.0` is released you'll be able to specify where the libs are copied as well, aka #1753
