### ISSUE TITLE
cefSharp causes the host application to crash if it cannot load its dependencies

### ISSUE THREAD

**Issue by sylvain-hamel** [cefsharp/CefSharp#605]
In our application, we are thorough with regards to exception handing. **All** unhandled exceptions that occur in our application are *handled* and logged (and reported to our servers for investigation). We never have any hard crash where Windows shows its own crash dialog.

After integrating cefSharp, we did some testing to make sure we could still handle all types of errors. One fairly simple test is to delete `libcef.dll` and start our application. The problem is that no exception is raised at all; our host process just crashes (and Windows does show its own crash dialog). This means there is no way for us to send this information to our servers.

We need cefSharp to be bullet proof in this area. Is there a way for cefSharp to handle all types of unmanaged errors (c++) to rethrow managed exceptions?

I'm willing to contribute in a fix but I don't really know where to start.

**Comment by amaitland** [comment]
Closing this with #900, whilst it's not quite as I'd like it yet, it does allow you to check for dependencies on startup.
