### ISSUE TITLE
Feature Request - Add Support for Custom cursor in WPF

### ISSUE THREAD

**Issue by Dvornik** [cefsharp/CefSharp#606]
It works fine in CefSharp1.25.5, but doesn't work in CefSharp33.0.2

Use it for testing: http://html5advent2011.digitpaint.nl/3/index.html

![image](https://cloud.githubusercontent.com/assets/1733249/5049962/f2882172-6c3a-11e4-9269-296884aff9f3.png)

WPF, built as x86, Win7x64

**Comment by amaitland** [comment]
Updating `CEF` project link.

https://bitbucket.org/chromiumembedded/cef/src/ae25a352d0002c0d0a1cc20404ac58fd8338d130/include/cef_render_handler.h?at=master&fileviewer=file-view-default#cef_render_handler.h-136

**Comment by TheMetador** [comment]
I'll participate in working this issue.  If there's any new developments please chime in.

**Comment by heyanctil** [comment]
@Project-Metador we've started to use CefSharp some days ago and we have discovered this problem today.

**Comment by amaitland** [comment]
@heyanctil Did you actually have a question? If your interested in contributing a `PR` then great, if not then there isn't really anything else to discuss.

**Comment by heyanctil** [comment]
@amaitland No question. I just pointing out that the problem is still there. I've raised a bug to the CEF team.

**Comment by amaitland** [comment]
> @Dvornik see this thing which got implemented upstream in CEF yesterday: https://code.google.com/p/chromiumembedded/issues/detail?id=1443

@heyanctil Did you read the comment above? `CEF` added support almost two years ago.

**Comment by amaitland** [comment]
I've removed all the old comments to reduce this issue to the bare information.

`CefRenderHandler::OnCursorChange` handler passes in custom cursor information, this needs to be mapped into a `Cursor` object in `WPF`. Unfortunately custom cursors in `WPF` are troublesome and this isn't straight forward.

Relevant `CEF API` link is http://magpcss.org/ceforum/apidocs3/projects/(default)/CefRenderHandler.html#OnCursorChange(CefRefPtr%3CCefBrowser%3E,CefCursorHandle,CursorType,constCefCursorInfo&)

`CefSharp` implementation of `CefRenderHandler::OnCursorChange` is https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Internals/RenderClientAdapter.h#L175

**Comment by amaitland** [comment]
There is currently no plan to implement this feature. If your interested in implementing this feature please comment below.

**Comment by amaitland** [comment]
Actually, looking at the `CEF` implementation it doesn't do anything special with the `HCURSOR`. So it occurred to me the updating the cursor in an `async` fashion might be the problem. Updated `master` to update custom cursor in a `sync` fashion and the problem appears to be resolved.

Adding this to the `55.0.0` milestone. If I get around to releasing a `53.0.1` version then I'll probably include this, for now there is no plans for that.

**Comment by sergiubologa** [comment]
I'm testing this in version v84.4.10 and it's not working anymore. It used to work in v75.1.143 and before, but seems like somewhere in between it got broken again. Is it a known issue?

**Comment by amaitland** [comment]
Does the problem reproduce with version 85? If yes please test with the CEF Sample application see https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-chromium-embedded-frameworkcef 

The upstream implementation will change in version 87, so changes will be required https://bitbucket.org/chromiumembedded/cef/commits/be119b4c9af947a730a6b62907182a563672005a

**Comment by lukasrmattos** [comment]
I'm using version 85 and my custom cursor are not working too. I downgrade to v75.1.143 as pointed by @sergiubologa and its working.

**Comment by amaitland** [comment]
This will be fixed in version 86, relevant commit https://github.com/cefsharp/CefSharp/commit/0386a7a71dc22cf248bb097a16a557e538f98c8b

In future rather than commenting on an issue that has been inactive for 4 years please create a new issue using the bug report temple. Thanks.
