### ISSUE TITLE
CEF3 can't handle input method

### ISSUE THREAD

**Issue by wangan** [cefsharp/CefSharp#607]
![Like this](https://lh6.googleusercontent.com/-velpWmUgNww/VGa2h8aAVbI/AAAAAAAAAII/meoiswZuH7U/s1600/q.png)

**Comment by ssdyz** [comment]
Is this problem solved? Very worried, please do me a favor, thank you

**Comment by amaitland** [comment]
> OK. Since we already have #583 lets close this one. One place to track this issue should be enough :)

As stated refer to #583
