### ISSUE TITLE
Cef.Shutdown() too slow on version compiled from source

### ISSUE THREAD

**Issue by rfgamaral** [cefsharp/CefSharp#614]
I have been running CefSharp v33.0.2 (from NuGet) and so far so good. But because of recent issues (i.e. #608) I felt the need to compile CefSharp from source and use the latest `master` build in my project.

Maybe I missed something important, but here's the process I followed for this:
1. Cloned CefSharp and restored all packages with NuGet.
2. Opened `CefSharp3.sln` and built **everything** from `Build » Batch Build...`.
3. Built the `CefSharp.Common` and `CefSharp.WinForms` NuGet packages with commands from `build.ps1` file.
   - The files `CefSharp.Common.37.0.0-pre01.nupkg` and `CefSharp.WinForms.37.0.0-pre01.nupkg` were generated.
4. Configured the NuGet Package Sources (Visual Studio settings) to look for packages inside the cloned `CefSharp\NuGet` folder where the `.nupkg` files are located (placed this source at the top).
5. Updated my project to the pre-release packages available.

My project `packages.config` went from this:

``` xml
<package id="cef.redist" version="3.1750.1738" targetFramework="net45" />
<package id="CefSharp.Common" version="33.0.2" targetFramework="net45" />
<package id="CefSharp.WinForms" version="33.0.2" targetFramework="net45" />
```

To this:

``` xml
<package id="cef.redist.x64" version="3.2062.1898" targetFramework="net45" />
<package id="cef.redist.x86" version="3.2062.1898" targetFramework="net45" />
<package id="CefSharp.Common" version="37.0.0-pre01" targetFramework="net45" />
<package id="CefSharp.WinForms" version="37.0.0-pre01" targetFramework="net45" />
```

Assuming my process is correct, after building a new version of my application with the latest "pre-release" from CefSharp's `master` branch. The call to `Cef.Shutdown()` has become incredibly slow. I'm calling the `Shutdown` method when the user exits the application (by pressing `Exit` in a context menu) and it took more than 10 seconds to close the whole thing.

This did not happen on the previous version.

After looking closer to IntelliTrace I noticed a bunch of thrown and caught exceptions, 5 of each of the following:

```
Exception:Thrown: "The ServiceHost close operation timed out after 00:00:09.9857724.  This could be because a client failed to close a sessionful channel within the required time.  The time allotted to this operation may have been a portion of a longer timeout." (System.TimeoutException)
A System.TimeoutException was thrown: "The ServiceHost close operation timed out after 00:00:09.9857724.  This could be because a client failed to close a sessionful channel within the required time.  The time allotted to this operation may have been a portion of a longer timeout."
Time: 17/11/2014 23:06:27
Thread:<No Name>[8836]
```

```
Exception:Thrown: "The operation cannot be completed because the pipe was closed.  This may have been caused by the application on the other end of the pipe exiting." (System.ServiceModel.CommunicationObjectAbortedException)
A System.ServiceModel.CommunicationObjectAbortedException was thrown: "The operation cannot be completed because the pipe was closed.  This may have been caused by the application on the other end of the pipe exiting."
Time: 17/11/2014 23:06:27
Thread:Worker Thread[1548]
```

Is there anything else that I should probably be doing to make sure this v37 works as expected?

**Comment by devcor** [comment]
Hi everyone, I have a similar problem calling to browser.Dispose() function in winforms. I'm using newest cefsharp version exposed in NuGet (39.0.0.0). When i call browser.Dispose() inside onClosing event, it takes 10 seconds (aprox) without errors or exceptions, just it takes a lot of time to do it. Thanks for any idea or advise to solve this issue.

**Comment by rassilon** [comment]
@devcor, Are you using a debug build of CefSharp? The debug build has loads of histogram output from Cef that you can see in the VS IDE output window.

**Comment by devcor** [comment]
@rassilon I've been testing with a debug build of CefSharp as you said and the delay happens in line 70 of the class CefSharp.Internals.BrowserProcessServiceHost doing the base.OnClose(timeout) instruction.

**Comment by amaitland** [comment]
`10 second` delay is the standard `WCF` timeout. So for some reason the `WCF` channel is waiting to be closed and eventually times out. Reducing the timeout will cosmetically fix the issue, I'd be curious as to what's actually causing it though.

@devcor Can you elaborate on how your using `CefSharp`?

**Comment by rassilon** [comment]
The WCF duplex shutdown process seems to want the subprocess to be around when it shuts down. When I've done WCF (and I'm definitely no WCF expert) I've just called `.Close(new TimeSpan(<either 0ms or 500ms or something else rather small>))' and catch any timeout exceptions that might get thrown and ignore them.

I was thinking he might be seeing the shutdown delay caused by Chromium's perf historgrams being dumped to the debugger output window in Debug builds.

**Comment by amaitland** [comment]
> I've just called `.Close(new TimeSpan())' and catch any timeout exceptions that might get thrown and ignore them.

I was thinking of keeping the timeout, just lowering it to say `2 seconds`, give everything at least a little time to close.

**Comment by rassilon** [comment]
Works for me, to be honest unless a user provides more details about stacktraces when things like this (or the shutdown blocks forever issue) happen there's not much to go on. :smile:

**Comment by devcor** [comment]
I modified Browser BrowserProcessServiceHost in the base.OnClose(timeout) changing timeout value to 0 seconds and everything is working fine, but I don´t know what is the real problem. Is there a way to control the timeout value from the browser winform?

**Comment by amaitland** [comment]
> Is there a way to control the timeout value from the browser winform?

Not at the moment.

**Comment by devcor** [comment]
At the moment i´ll apply this solution, if i find some specific exception or an output message informing about what is really happening i´ll inform you. I tried to modify the CefSharp minimal example to show you my scenario which works with threads but i couldn´t reproduce the problem, in minimal example project it works fine. @amaitland, @rassilon Thanks for your help (Y)

**Comment by expertsonline** [comment]
Hi

I upgraded to 43.0.0 and started to see this issue. For each browser instance, dispose took exactly 10 seconds to complete. I ensured that the initialize and dispose / Shutdown were all called on the main thread.

Downgrading back down to 41.0.1 did not show this issue. 

Regards,
Deep

**Comment by amaitland** [comment]
Please open a new `issue`, including version, `WinForms` or `WPF`, a way to reproduce the problem. Any other background information that might be relevant.

**Comment by amaitland** [comment]
Seems like someone else has opened an issue, please contribute there.

See #1304
