### ISSUE TITLE
CefSharp.Core unable to load when published (ClickOnce)

### ISSUE THREAD

**Issue by dtbiedrzycki** [cefsharp/CefSharp#625]
Hey all,

I've recently created a project using the latest Prerelease version through NuGet. It runs swimmingly through Visual Studio, however, when I publish the application (through VS creating the one click install type of application), the installed application always fails to start.

When I've been able to catch the error, it states that it was unable to load the CefSharp.Core dependency. I've tinkered with the cef.redist package as well and got it so that the application would install and actually open a window, but the browser fails to load properly.

Now this could be my own mistake as I'm new to publishing applications, but I haven't had this problem with other small projects that have third party dependencies.

So far I've tried building in both x86 and x64 as well as building in a specific configuration and removing the unnecessary references (i.e. build in x86 and remove all x64 references). That didn't seem to change anything. When I've looked at the other issues listed here, they seemed to be revolving around errors while in VS, not in a published application, so I thought this would still be fit as a new issue.

**Comment by stepanets** [comment]
Hi, I dont understand where should I copy dlls

**Comment by jankurianski** [comment]
@stepanets The full source for a working example is available at https://github.com/dtbiedrzycki/SlackWindowsApp  - have you checked to see what it does?

**Comment by stepanets** [comment]
What exactly should I check? I dont see dll and pak files in this project.

**Comment by amaitland** [comment]
For `CefSharp` to run all the `CEF` dependencies need to be in the same directory as your executable.

**Comment by stepanets** [comment]
I copy dependencied to project, it works fine if I run application from project Release folder, but after ClickOnce setup I get error in libcef.dll.

**Comment by amaitland** [comment]
Have you read #500 as noted above?

**Comment by stepanets** [comment]
About SlackWindowsApp - I've published it by clickonce and inslalled and I got same error 
```
An unhandled exception of type 'System.IO.FileNotFoundException' occurred in SlackApp.exe 
Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found.
```

**Comment by amaitland** [comment]
> About SlackWindowsApp - I've published it by clickonce and inslalled and I got same error

No, #500 has details on `ClickOnce`

**Comment by stepanets** [comment]
I've read #500. When I add dependencies dlls to my project I get error not about "Could not load file or assembly 'CefSharp.Core.dll'". But error about libcef.dll (sorry for russian lang)
![error](https://cloud.githubusercontent.com/assets/2420662/8347976/521665e4-1b37-11e5-8433-2a7cfcb30f5e.png)
When I try debug it I get only
```
The program '[8660] RealtTranslator.exe' has exited with code 1073741855 (0x4000001f).
The program '[6828] RealtTranslator.vshost.exe: Program Trace' has exited with code 0 (0x0).
The program '[6828] RealtTranslator.vshost.exe' has exited with code 0 (0x0).
```

**Comment by amaitland** [comment]
The exception says that `CefSharp.Core.dll` cannot find `libcef.dll`, so check that it's part of your click once distribution and is in the same path as your executable.

You can use the `Cef.Initialize` `dependencyCheck` option to confirm all the files are present.

**Comment by stepanets** [comment]
This is folder generated by click once
![files](https://cloud.githubusercontent.com/assets/2420662/8350402/9e896152-1b4f-11e5-81b1-ad8fcb572dfa.png)

**Comment by amaitland** [comment]
Have you got `VC++ 2012 Update 4` loaded on your target machine? 

See what the dependency checker tells you, it'll throw an exception if it can't find key files.

**Comment by stepanets** [comment]
@amaitland BIG thx!!! dependencyCheck shows that next dependencies was missed
```
/loacales
icudtl.dat
CefSharp.BrowserSubprocess.Core.dll
CefSharp.BrowserSubprocess.exe
```

**Comment by Cyberneticist-UK** [comment]
I know this is closed, but I had the same issue and this was a life saver! I also had to do a bit of coding with it to get it working, so I fixed it by:
Referencing as set out here, after removing the references created by NuGet.

I told the settings file NOT to check for dependency:

CefSharp.CefSettings set = new CefSharp.CefSettings();
                set.CachePath = CacheStorage;
                set.LocalesDirPath = Application.StartupPath + "\\Locales";
                CefSharp.Cef.Initialize(set, true, false);

Until I did this, I couldn't do ClickOnce, nor would the application open when called as a process or from a shortcut yet WOULD work when double clicking on the Exe file! Took a bit of hunting through log files, and this article to get it sorted!!

**Comment by SQ0227** [comment]
Facing same issue. 
Can we please have a documented guide on how to resolve such issues rather than going through 100 threads on stackoverflow and git on the same.

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/issues/1314#issuecomment-859802748 for details. 

Locking this conversation as it's entirely outdated (hasn't been updated since 2016). If you are still having problems then please join in the discussion at https://github.com/cefsharp/CefSharp/discussions/3613
