### ISSUE TITLE
CefSharp WinForms, Server 2003... runs once, but never again until reboot?

### ISSUE THREAD

**Issue by murphmar** [cefsharp/CefSharp#627]
Really trying to get this to work for us to replace IE7 in our PowerBuilder application. Everything works great on a Windows 7 or 2012 environment, but on 2003 I'm having a weird issue. Unfortunately we can't go ahead with this unless it's 100% on 2003.

When you run our app and then open the internal window which houses the browser control everything works great, as you would expect. You can close and reopen that internal window as many times as you want and browser will close and reopen as it should. The issue comes when you close the application itself. If you reopen the application and then try to open the internal browser window it will hang until you force close. Nothing seems to repair the problem except for a total system reboot. It works again after that.... once.

If anyone has any input that would be great. I can share whatever might be needed.

Thanks.

**Comment by rover886** [comment]
@jornh and @murphmar I don't whether reopening this issue is correct or not but I am facing the same issue on Windows 2003. I am using cefsharp version 37 (Stable). In my case debug.log file is not generating. I have checked that .NET 4.0 Client Profile is installed on machine as well as VC ++ 11 redistributable is also installed.

After checking Event Viewer I got two errors in it :

```
Application: MyApp.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.IO.FileLoadException Stack: at MyApp.Program.Main()
```

```
Faulting application MyApp.exe, version 1.0.0.0, stamp 5507c7af, faulting module kernel32.dll, version 5.2.3790.3959, stamp 45d70ad8, debug? 0, fault address 0x0000bee7.
```

**Comment by amaitland** [comment]
> When you run our app and then open the internal window which houses the browser control everything works great, as you would expect. You can close and reopen that internal window as many times as you want and browser will close and reopen as it should. The issue comes when you close the application itself. If you reopen the application and then try to open the internal browser window it will hang until you force close.

@rover886 Are you seeing the exact same issue? It sounds like your app doesn't run at all.

**Comment by amaitland** [comment]
#849 sounds more like your problem

**Comment by rover886** [comment]
@jornh umm may be not, When I execute application windows got hang for sometime after sometime windows get resume but application is not get open.

**Comment by amaitland** [comment]
If #849 sounds like your problem then comment there, otherwise open a new issue with full details on your environment, versions, flavour of `CefSharp`, etc.
