### ISSUE TITLE
CEF causes host to crash if using CEF in a .Net User Control

### ISSUE THREAD

**Issue by ghost** [cefsharp/CefSharp#642]
I am creating a .Net UserControl and attempting to initialize CEF and embed the ChromiumWebBrowser in my UserControl.  As soon as I attempt to drop my UserControl onto a WindowsForm it appears that CEF is crashing my host process.  If I however spawn a windows Form from my UserControl the Form with CEF works fine.

I suppose my question is "is it not possible to user CefSharp or CEF directly from a UserControl"?

**Comment by AhmedAlayat** [comment]
I have also the same problem but i still can't solve it so please can any one
tell me the steps to solve it

**Comment by Bodmoor** [comment]
Same here. My exact error is:

Could not load file or assembly 'CefSharp.Core, Version=57.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138' or one of its dependencies. An attempt was made to load a program with an incorrect format.

Using x64/x86 as platform target and in the configuration manager.

**Comment by dreamminister** [comment]
Have this issue too! I'm trying to create browser in MsTest method and have similar exception!
![chromiumcrash](https://user-images.githubusercontent.com/1550289/30061419-f23ab1b0-924f-11e7-996c-7a15ff89dea2.jpg)

```
[TestMethod]
        public void TestMethod1()
        {
            var settings = new CefSettings();
            Cef.Initialize(settings);
            ChromiumWebBrowser browser = new ChromiumWebBrowser("");
            //Shutdown before your application exists or it will hang.
            Cef.Shutdown();
        }
```

![file_list](https://user-images.githubusercontent.com/1550289/30061472-2a7a1fa2-9250-11e7-8056-53a65b708155.jpg)

**Comment by jankurianski** [comment]
@dreamminister CefSharp cannot be unit tested with MsTest.  See the solution here: https://github.com/cefsharp/CefSharp/issues/700#issuecomment-297209620

**Comment by dreamminister** [comment]
@jankurianski thanks. I've tried similar one for mstest: [mstest example](https://stackoverflow.com/a/46112675/2718884)
