### ISSUE TITLE
Download and Save PDF document 

### ISSUE THREAD

**Issue by Gunargs** [cefsharp/CefSharp#649]
we will provide a URL , cefsharp browser needs to download that document and save it , how to do this ?

**Comment by RIGHTTHEN** [comment]
i am having the same issue cant download files with cefsharp. copied the DownloadHandler from example code to my solution but nothing happens. tried using webclient but file always downloads with 0 bytes or says forbidden. guess server wants request from browser itself. putting the same link in address bar does download file. i am using CefSharp.Wpf.47.0.2. Windows 7 64 bit.
Thanks
Regards

**Comment by amaitland** [comment]
Here is an example https://github.com/cefsharp/CefSharp/blob/cefsharp/47/CefSharp.Example/DownloadHandler.cs

We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask followup questions there.
