### ISSUE TITLE
GPU and WPF

### ISSUE THREAD

**Issue by bjarteskogoy** [cefsharp/CefSharp#654]
Would the solution this article describe make gpu rendering possible for WPF? http://www.codeproject.com/Articles/28526/Introduction-to-D-DImage

**Comment by amaitland** [comment]
For the fun of it I've implemented `WritableBitmap` and performance wise It's probably a little slower, even with using `Dirty Rect` support, which was quite surprising.

If your interested then check out https://github.com/amaitland/CefSharp/commits/enhancement/writeablebitmap

**Comment by trevorlinton** [comment]
Hi All,

I've been playing around with IWebBrowser (the C OLE MSHTML object) for Internet Explorer and how I might be able to get it to avoid the airspace issues in WPF (while being hardware accelerated). 

I've recently started playing with CEFSharp and saw you were bitblt'ing with the interop image.  I was wondering if you've thought of using a D3DImage object and bouncing the HDC.  Surprisingly in windows 7+ if you bounce a HDC to a D3DImage the underlying surfaces can recognize you're actually using a DirectX->DirectX call and so long as there isn't any translation of surface types it takes place in video memory (huzzah!) 

You can see a (once again, playground example) here: https://gist.github.com/trevorlinton/7abac1c5f044be153833  The results were fairly promising although not perfect.  I'm curious if anyone on this thread has had any experience and if I should try my luck at implementing this on CEFSharp.

Here's the gist: https://gist.github.com/trevorlinton/7abac1c5f044be153833

**Comment by trevorlinton** [comment]
A little embarrassed at the code i decided to reduce it to the most important parts:

1. Initialize a D3D device, get its surface DC
2. Get the DC of the hwnd (or if its offscreen, even better, just a memory DC, hardware accelerated off of a directx surface is optimal here).

Then, on any invalidation:

```C++
  // WPF Managed C++ code
  void SomeInvalidationEvent(Object^ sender, EventArgs^ e) {
    if (d3dimg->IsFrontBufferAvailable)
    {
      // Try lock will begin to fail persistently, setting the timespan higher helps,
      // but once it locks it seems unable to re-lock, levels tried were 2, and 22.
      d3dimg->TryLock(Duration(TimeSpan(22)))
      d3dimg->Lock();
      RenderD3D();
      d3dimg->AddDirtyRect(DirtyRect);
      d3dimg->Unlock();
    } 
  }
 
  void RenderD3D() {
    // Note, this is C++ but interops for C# are available
    // d3ddev is an initialized directx device set as the back buffer, if theres
    // an existing directx back buffer for CEF that would make this all the simpler, and
    // this entire function probably isn't even necessary....
    // hdcFrom is the HDC coming off of CEF somewhere? from a hwnd? from internals?
    if (SUCCEEDED(d3ddev->BeginScene()))
    {
      HDC surfaceDC;
      d3dev->GetDC(&surfaceDC); 
      BitBlt(surfaceDC, 0, 0, DpiWidth, DpiHeight, hdcFrom, 0, 0, SRCCOPY);
      d3ddev->ReleaseDC(surfaceDC);
      d3ddev->EndScene();
    }
}
```

**Comment by amaitland** [comment]
> I'm curious if anyone on this thread has had any experience and if I should try my luck at implementing this on CEFSharp.

I think the general plan was to wait for `CEF` issue 1006 to be resolved (new link as they moved to bitbucket https://bitbucket.org/chromiumembedded/cef/issue/1006)

Are there additional libs required for the `D3D` side of things?

**Comment by amaitland** [comment]
If you can knockup something then feel free to submit a PR :+1:

**Comment by trevorlinton** [comment]
@amaitland I don't believe so, if i'm reading the issue tracker correctly they plan on allowing the client to provide the d3d device (which is great, and easy from WPF without any new libs).  However my gut says they're using (or will be) only DX11 which will require some interops to convert the pointer structure, but i'm not sure at the git-go if that requires linking against the DX lib or if its a shared library call.  I suppose i'll keep an eye on this, might as well proceed with the work on CEFSharp's side and for the moment tie it to the shared memory area where CEF is writing to, it won't be accelerated, but it could very likely be faster than memory copies in WPF.  I'll give it a go and let you know the results.

**Comment by amaitland** [comment]
> I'll give it a go and let you know the results

Cool, hopefully the code is relatively easy to follow now, there's a couple of parts that I think still could use a rewrite. Anyways, if you have any questions then let me know.

**Comment by amaitland** [comment]
@trevorlinton Any followup questions? I know very little about `DX`, so I'm curious to see what's involved.

**Comment by trevorlinton** [comment]
@amaitland Yes, i have it implemented, but have a few bugs to work out and i'll submit a pull request. 

A larger issue is it seems the bitblt method currently used uses events(non-rendering-bound) or timers instead of redrawing directly from the rendering event (unsure if i made a mistake or if its built that way, might have to do with redirecting to the async thread).  It's making it difficult to get quantitative data on how much faster (or if its faster) then the bitblt method used. Just from eyeballing it everything seems faster... and I know the memory use is lower, so thats a plus.

**Comment by amaitland** [comment]
If you could base your PR on the 2272 branch that would be ideal :+1: 

I'm unsure which timer your exactly referring to, the tooltip one? If you submit a pr now you can always push more commits before it's merged. Might make it easier to discuss inline?

**Comment by bjarteskogoy** [comment]
Any news here @trevorlinton  ?

**Comment by amaitland** [comment]
Doesn't seem like anything is happening with this, so closing. 

Anyone wishes to discuss this further, jump on [Gitter Chat](https://gitter.im/cefsharp/CefSharp) to discuss your ideas or tell us about the new `PR` your working on :wink:
