### ISSUE TITLE
Copy image to clipboard

### ISSUE THREAD

**Issue by myrnazhou** [cefsharp/CefSharp#665]
Just like in common webbrowsers there is a way to copy image by right clicking then copy image. Is there a way to do that in CefSharp? 
I've been looking around but couldn't find the best solution, currently I copied it directly from the url by downloading the image. But that is just not ideal, since technically the image is already downloaded by the CefSharp.

**Comment by amaitland** [comment]
If `CEF` ever adds this feature we can reopen this.
