### ISSUE TITLE
WinForms DropDown Incorrect Position After Move

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#672]
After moving the Window, drop downs are positioned incorrectly.

Background info in #661 comments
https://github.com/cefsharp/CefSharp/pull/661#issuecomment-65368734

At some point need to call `NotifyMoveOrResizeStarted` method so that `Cef` gets updated coordinates.

Steps to reproduce
- Open Winforms Example app
- Navigate to Url that has DropDowns
- Move Window
- Open DropDown

**Comment by mblandfo** [comment]
Workaround/Hack for WinForms using a ChromiumWebBrowser:

        void Form1_Move(object sender, EventArgs e)
        {
            Size sz = _chromeBrowser.ClientSize;
            sz.Width++;
            _chromeBrowser.ClientSize = sz;
            sz.Width--;
            _chromeBrowser.ClientSize = sz;
        }

**Comment by amaitland** [comment]
That's quite the hack! You actually just need to call `NotifyMoveOrResizeStarted`, rather than fiddling with the `ClientSize`

**Comment by mblandfo** [comment]
Is that available in v37.0.0 ? I didn't see it on the ChromiumWebBrowser object

**Comment by amaitland** [comment]
It's in the `39.0.0-pre02` release. Method was introduced in the `2172` branch.

**Comment by amaitland** [comment]
Resolved with merge of #787
