### ISSUE TITLE
Focus and windows tablet keyboard input issues

### ISSUE THREAD

**Issue by DDeas** [cefsharp/CefSharp#684]
Once the chromium browser control has lost and regained focus (to another form within our application), we no longer receive keyboard input to any html elements. 

Other text boxes within the application receive keyboard input ok, but no matter how we force focus back to the web-browser control, the IKeyboardHandler.OnKeyEvent() is no longer fired.

This works fine on a desktop computer, but will not work on a DELL tablet.

Winforms, CEF3, .Net 4.0, Windows 8.1

**Comment by Avie1** [comment]
SetFocus after FrameLoadEnd event works for me.

 chromeBrowser.FrameLoadEnd += ChromeBrowser_FrameLoadEnd;

        private void ChromeBrowser_FrameLoadEnd(object sender, FrameLoadEndEventArgs e)
        {
            chromeBrowser.GetBrowserHost().SetFocus(true);
        }

**Comment by berrywing012** [comment]
> SetFocus after FrameLoadEnd event works for me.
> 
> chromeBrowser.FrameLoadEnd += ChromeBrowser_FrameLoadEnd;
> 
> ```
>     private void ChromeBrowser_FrameLoadEnd(object sender, FrameLoadEndEventArgs e)
>     {
>         chromeBrowser.GetBrowserHost().SetFocus(true);
>     }
> ```

Thank you. This helped me.
