### ISSUE TITLE
Set popup window title and inherit icons from parent window

### ISSUE THREAD

**Issue by rfgamaral** [cefsharp/CefSharp#686]
The current behavior for all popup windows is:
- No window title (taskbar has no title too)
- Default window icon (taskbar too)

Suggestions:
- All popup windows should have a title from the page they are currently loading.
- Inherit the icon from the parent window instead of using the ugly default one.

Bonus:
- Implement `IDisplayHandler` interface.

CEF Python did this: https://code.google.com/p/cefpython/source/detail?r=3468dd17c548

**Comment by dem219** [comment]
Btw, if you are still looking for a solution to setting a popup windows icon, you can do the following:
- Implement ILifeSpanHandler
- Capture the hwnd of a popup in OnAfterCreated
- Then set the popup's icon using this code: http://www.ogre3d.org/tikiwiki/tiki-index.php?page=Set+icon+of+Window+(Mogre)
