### ISSUE TITLE
JS Binding with functions not working

### ISSUE THREAD

**Issue by Bodekaer** [cefsharp/CefSharp#690]
Hey @amaitland,

We just found a bug, that's limiting our use of the JS binding system.
I think it will be easy for you to fix. Here is how to replicate it:

In the BoundObject.cs, add this:

        public SubBoundObject GetSubObject()
        {
            return SubObject;
        }

Then run the project, and execute this script:
`bound.getSubObject().simpleProperty;`

This will cause the browser to crash.
What's interesting, is that this works fine:
`bound.subObject.simpleProperty;`

So it seems to just be an error with *functions* returning classes. (*properties* can easily return classes)

Hope you can fix this quickly (cc'ing @tkrakowiak)

**Comment by Bodekaer** [comment]
@amaitland, is there any way we could convince you to work on updating the JS bindings to support this?
We'll be happy to donate money to the CefSharp team if possible, as it's a really key feature for our new Javascript API system that Tomasz has worked on.

Perhaps drop me an email if it's an option: michael@liv.it

**Comment by amaitland** [comment]
@Bodekaer I'm actually considering scaling my contribution to `CefSharp` right back, so I'm not really comfortable committing to anything.

I've committed https://github.com/cefsharp/CefSharp/commit/901a70ac00079802a424faa1f57b436284fe6d3d which solves half the problem, you could probably add a `CefSharp.BrowserSubprocess.exe.config` file with the relevant known type entries and get this basically working.

See http://msdn.microsoft.com/en-us/library/ms730167%28v=vs.110%29.aspx for an example config (at the bottom).

**Comment by amaitland** [comment]
@Bodekaer I've committed some changes to `cef/2171` that should provide the ability to return a relatively complex type. There's a few caveats though:

- Only properties work (functions are a much harder proposition)
- Analysis is done upon the method returning, so there's an overhead, on the upside it means you can return polymorphic objects.
- I'm not sure of a way to cleanup the CefV8Objects, so it may leak memory (I'm hopeful that it doesn't as there's no references left after the values are passed to `Cef`).

As a favor I was wondering if you might have access to a design resource? Someone familiar with `WPF`. I'd really like to get the `WPF` example looking nicer, it would be cool to switch to it for daily browsing.

(I've decided to hang around at least long enough to see `39` get pushed out the door).

**Comment by Bodekaer** [comment]
Great! Very much looking forward to test it out. 
The overhead sounds fine, as it will not be too many calls back/forth - so a small leak is also very unlikely to cause problems, as we'll be reusing the same API objects.
Really nice.

For the design, I would recommend that we just implement the `MahApps` open-source project, and apply those styles. http://mahapps.com/
That's what I've done so far, and it works really nicely with theming support too + no design work is really needed.

**Comment by Bodekaer** [comment]
Btw. great news that you are still with us! :)
Any news on bringing other people on the CefSharp team?

**Comment by amaitland** [comment]
> Great! Very much looking forward to test it out.

Let me know how it goes :+1: 

> For the design, I would recommend that we just implement the MahApps open-source project, and apply those styles. http://mahapps.com/

Do they have a `nuget` package? How much effort is involved do you reckon? Do you think you'd have any time or resources available to applying a touch of style? UI is not my strong suite :smile: 

> Any news on bringing other people on the CefSharp team?

No expressions of interest so far, I think the `C++` side puts a lot of people off.

**Comment by amaitland** [comment]
@Bodekaer Did you ever get around to trying this out?

**Comment by Bodekaer** [comment]
Yeah, I did.
Unfortunately we couldn't use it without the ability to use functions to access complex methods.
E.g. a common scenario we needed was:

`DotNetObject.GetAnotherDotNetObject('someName').Title`

This seemed to always fail, and I believe it would require a large upgrade to enable the above code right?
In any case, we're using a temporary work-around for now with JSON objects which is ok. And that works fine.

The above would although be incredibly nice for us to have, as it would enable a pure JS API for app developers on our platform, and make it 10x easier for non-C# developers to interact with our C# API via a special JS API.

Let me know what you think.

**Comment by amaitland** [comment]
> E.g. a common scenario we needed was:
> 
> DotNetObject.GetAnotherDotNetObject('someName').Title

Would have expected that to work. I've only done some rough testing though. Can you modify one of the examples to reproduce your problem?

For reference this is the basic test that's working now:
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/Resources/BindingTest.html#L40

**Comment by Bodekaer** [comment]
Ahh interesting.
@tkrakowiak what's your thoughts on this. Do you think it actually would be possible for us to use it and avoid the `getJSON()` methods given the above example from Alax?

**Comment by amaitland** [comment]
@Bodekaer Did you ever end up using functions?

**Comment by Bodekaer** [comment]
Yeah! It works very well.

I do have one question: 
When trying to return an object of type  `List<MyClass>` it throws an error.

Should this still be possible somehow? If yes, how?

**Comment by Bodekaer** [comment]
This is the error btw.:

	Faulted state.message: 
	"The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state."stack: (...)get stack: function () { [native code] }set stack: function () { [native code] }__proto__: d

**Comment by amaitland** [comment]
Likely to be another `KnownType` issue. Will have a look when I get a minute.

**Comment by amaitland** [comment]
If #972 is given the green light then this should be simple enough to fix.

**Comment by Erguotou** [comment]
Indeed, #972 modified method calls to return full objects, just like property calls. This issue is fixed there.

**Comment by amaitland** [comment]
Your implementati works with arrays, don't believe it works with collections yet.
