### ISSUE TITLE
WPF ALT-S Key Combination Not Working

### ISSUE THREAD

**Issue by drumboog** [cefsharp/CefSharp#694]
The accesskey attribute works as expected in CEF and the WinForms sample, but the keystroke seems to be intercepted in a Wpf application.

Steps to reproduce:
Run CefSharp.Wpf.Example.
Navigate to http://www.w3.org/WAI/UA/TS/html401/cp0101/0101-ACCESSKEY-INPUT.html
Press Alt+s
No action is taken

Run CefSharp.WinForms.Example
Navigate to http://www.w3.org/WAI/UA/TS/html401/cp0101/0101-ACCESSKEY-INPUT.html
Press Alt+s
The page is redirected because of the accesskey attribute

**Comment by amaitland** [comment]
I've created merged #695 into the `cef/2171` branch, so your welcome to test this again against that branch.
