### ISSUE TITLE
cefsharp 37.0.0-pre02 64bit (winform)  - libcef.dll application error

### ISSUE THREAD

**Issue by fsimon21** [cefsharp/CefSharp#696]
hello!

i have this new problem, sometimes my program stops to work and gives the 0x80000003 exception to the libcef.dll.

The strange thing is that this program is used from 4 or 5 people on a server connected with terminal server, and the error happens only to the same person one time a day, and she doesn't do the same operation with this program...it's random.

is there a some kind of operation to do for try to figure out what is the problem? 
![erroredll](https://cloud.githubusercontent.com/assets/9480493/5487273/31a0bd12-86b0-11e4-86ef-5f847678dc8f.jpg)

thanks!

**Comment by fsimon21** [comment]
i have to understand how the class works in detail first, before trying to hypotize a solution

**Comment by amaitland** [comment]
Can you provide a sample project that reliably reproduces the problem?

**Comment by amaitland** [comment]
Upgrading to `37.0.0` or a build from `master` would also be beneficial.

**Comment by fsimon21** [comment]
ok thanks, i'll try ;-)

**Comment by amaitland** [comment]
Great :+1:

No links to zip files please, either a `Gist` or upload the project to `GitHub`, you can fork one of examples as a starting point if required.

**Comment by fsimon21** [comment]
Ok!

For now i have changed the way to opening of the form in my application and it works.

Thank you for your help!

**Comment by amaitland** [comment]
Any chance you could provide a sample of your solution? A reference to others, showing what you had and what you ended up. Doesn't have to be fancy, you can add a FAQ item if you'd like, anyone can contribute to the wiki.

**Comment by fsimon21** [comment]
OK, sorry but i'm a kind of a beginner  to how it works here, i'll write here a little explanation as soon as is possibile ;)

**Comment by amaitland** [comment]
Closing this issue for now. @fsimon21 If you have time to post even a few lines basically saying `what not to do` that would be great :+1:

**Comment by fsimon21** [comment]
here i am,
The problem in my case concerns the opening of a form that wound up a list that had to be updated every time you open.
So I did nothing but simply a Form.Close when it was open and then a Form.Show regarding the form containing the list.
The problem was that the Form.Close had a minimum of delay in closing and when I tried to open it again with .show was in error.

Now I have not done anything but eliminate Form.Close, always keep open the form of the list and update content only when you need it

thanks again for the help and sorry for the delay in writing this post!

**Comment by amaitland** [comment]
> thanks again for the help and sorry for the delay in writing this post!

@fsimon21 No problem, thanks :+1:

**Comment by amaitland** [comment]
I believe the problem stems from `CefSharp` attempting to call `Shutdown` when the `AppDomain` exits.
(Basically when you close the form, `CefSharp` is a little to aggressive in it's cleanup/shutdown handling).

I've committed https://github.com/cefsharp/CefSharp/commit/cab00326f213d271212be63c767484b508bad263 which will allow more control over this behavior.
