### ISSUE TITLE
Feature Request - Implement Sandbox

### ISSUE THREAD

**Issue by acron0** [cefsharp/CefSharp#697]
I gather from some of the comments that this is a big and scary change. I am curious as to whether you think this will get looked at in 2015?

**Comment by amaitland** [comment]
Blocked on #1149 

Same executable must be used for main application execution and sub process.

**Comment by alzritm** [comment]
Can I try to implement Sandbox - as I see here https://code.google.com/p/chromiumembedded/issues/detail?id=524
sandbox in main application exe compiled in C# jet  - may be this will be not so hard task ?

**Comment by amaitland** [comment]
> sandbox in main application exe compiled in C# jet - may be this will be not so hard task ?

There are a lot of little pieces that need to come together before this can be implemented.

1. Add `cef_sandbox.lib` to the `cef-binary` nuget packages 
2. Expose relevant methods of `BrowserSubProcess` so they can be executed within your main application.
3. Implement the specific `Sandbox` methods.
4. Determine what changes are required for `Link the executable with the cef_sandbox static library.`

http://magpcss.org/ceforum/apidocs3/projects/%28default%29/cef_sandbox_win.h.html

All in all, it's a non trivial task. If it's something you require then by all means get involved :+1:

**Comment by amaitland** [comment]
IN this context of `CefSharp` this won't be possible it seems.

http://magpcss.org/ceforum/viewtopic.php?f=6&t=13781#p29125

Someone absolutely requiring sandboxing would implement a `VC++` loader for their app, link the relevant `lib` and make the calls directly. This would need to be a custom implementation. Still would require a few of the changes from my previous comment. I think it's possible, just outside of the scope of this project so closing.
