### ISSUE TITLE
Chrome not making a real post request - "CAUTION: Provisional headers are shown" 

### ISSUE THREAD

**Issue by vivekcoer** [cefsharp/CefSharp#698]
I am facing one issue. I am loading resource files from my local file system using file:/// (I disabled the security and allowed localfile loading in browser settings) and its working fine for me. Except that in one of JS files I am making a XMLHTTP POST request to another domain.

But this call apparently never reaches to server because in chrome debugger I keep getting the infamous "CAUTION: Provisional headers are shown" error in network tab - this error is only shown when the request never actually reaches the domain -
http://stackoverflow.com/questions/21177387/caution-provisional-headers-are-shown-in-chrome-debugger

Suspecting that it might be a cross domain issue I added CORS headers as below too (as below) but that didnt help either.

I added CORS headers - "Access-Control-Allow-Origin: https://***.com, Access-Control-Allow-Credentials: true"

![chrome_issue](https://cloud.githubusercontent.com/assets/7366146/5491487/6cc2c86c-868e-11e4-8073-842e2804461d.png)

Everything works fine in chrome browser with the same local files (with an added command line switch --disable-web-security).

please could you help me figuring out what is going wrong here?

**Comment by vivekcoer** [comment]
hello @amaitland , @jankurianski 
sorry for late response (I went on a vacation).  I looked at the task manager for cef browser processes and found 3 - but I dont see "disable-web-security" in any of them (as mentioned above, I have already added - 
settings.CefCommandLineArgs.Add("disable-web-security", "disable-web-security");

![command_line](https://cloud.githubusercontent.com/assets/7366146/5748571/d82a24ac-9bf5-11e4-989b-93fe12349827.PNG)


I have also done
 CefSharp.BrowserSettings browser_setting = new CefSharp.BrowserSettings();
        browser_setting.FileAccessFromFileUrlsAllowed = true;
        browser_setting.UniversalAccessFromFileUrlsAllowed = true;
        browser_setting.WebSecurityDisabled = true;
        browser.BrowserSettings = browser_setting;

**Comment by amaitland** [comment]
Another option for checking command line params is loading `chrome://version`

> How do I disable web security in CEFSHARP browser?

I don't have any experience with the security side of things, so not sure that I can provide any further assistance.

**Comment by amaitland** [comment]
You can try `settings.CefCommandLineArgs.Add("disable-web-security", "1");` though that should be exactly the same result.

**Comment by amaitland** [comment]
Possibly `CefAddCrossOriginWhitelistEntry` may be useful for this scenario?

http://magpcss.org/ceforum/apidocs3/projects/%28default%29/%28_globals%29.html#CefAddCrossOriginWhitelistEntry%28constCefString&,constCefString&,constCefString&,bool%29

**Comment by amaitland** [comment]
Closing this, reopen if required.

**Comment by Aziz199505** [comment]
Although this will not fix your chrome issue at least you can take loot at it in console.log

`axios.interceptors.request.use((config) => {
  console.log('Request Interceptor',config)
  return config
})`
