### ISSUE TITLE
Why don't run at another pc?

### ISSUE THREAD

**Issue by BestofBestDeokwan** [cefsharp/CefSharp#709]
HI, all.

This project build and run very well on My PC.

but at another PC, don't run.

What is sequence to run at another PC?

help me, give me your knowledge...

**Comment by amaitland** [comment]
@BestofBestDeokwan Is this issue resolved? Can we close this?

Also make sure you build in `Release` mode, it's important for the `VC++` side of things.

**Comment by amaitland** [comment]
Closing now, if anything further then feel free to reopen.
