### ISSUE TITLE
Winform C# 4.0 Javascript Confirm Box Not handled correctly on Exit?

### ISSUE THREAD

**Issue by daveaton** [cefsharp/CefSharp#712]
I am having issues where I am trying to block javascript confirm alert boxes..

like this..  

http://www.eatoncode.com/shareit/2014-12-24_0923.png

it's not being handled when it's loading or unloading... 

Here is an example

http://www.mkyong.com/wp-content/uploads/jQuery/jQuery-stop-page-from-exit.html

Here is the code I am using...

        /// <summary>
        /// Event is Triggered when a Javascript Confirm is detected
        /// </summary>
        /// <param name="browser"></param>
        /// <param name="url"></param>
        /// <param name="message"></param>
        /// <param name="retval"></param>
        /// <returns></returns>
        bool IJsDialogHandler.OnJSConfirm(IWebBrowser browser, string url, string message, out bool retval)
        {
            MessageBox.Show(string.Format("This should show up first!!  Test Confirm From {0}", url));

                
                retval = MessageBox.Show(message, url, MessageBoxButtons.OKCancel) == DialogResult.OK;

            //handled
            return true;
        }

No matter what I do I can't catch the Confirm box.

Now if you load the confirm box on a page that's not loading or exiting then it works as normal

Like this  http://www.w3schools.com/js/tryit.asp?filename=tryjs_confirm

I am thinking this is a bug or I may not be handling it correctly ?

It's reproduce able in the latest master and the last 37 release.  

Thanks.

**Comment by amaitland** [comment]
Merged #715 so closing this. Thanks @daveaton greatly appreciated :smile:
