### ISSUE TITLE
Chrome Extension in CefSharp

### ISSUE THREAD

**Issue by hpposch** [cefsharp/CefSharp#719]
Hello!
Is there a way to get a chrome extension like "Adblock" running in CefSharp.
I already read that i would need to implement an own extension system for this.
But is there already any extension system availiable, or how does this work in general.

**Comment by hpposch** [comment]
@amaitland i had a look at the Google Extension API.. 
It seems that it is just a bunch of javascript that is executed, and CEF can do that, am i right?
So if i someone creates an Adapter for the Google Extension API, all the Extensions should work in Cefsharp as well?!

**Comment by blgnklc** [comment]
I think so, it could support. I tried some piece of codes that immitates google.chrome objects.. any body else trying to achive this?

**Comment by okatip1** [comment]
@amaitland
Please do that buddy. You will save my life if you do that

**Comment by hpposch** [comment]
@blgnklc what would you say if we create a new branch and try to design a new adapter for this?

**Comment by blgnklc** [comment]
@hpposch I can do share the codes that are using cefsharp wrapper and of course cef extension and js bind capabilities. 
Actually I have tried it with AdBlock and I could not go beyon some obstacles. 

Have you tried anything smilar? Could you please tell me your point of view.

I promise to continue and see where I am in this weekend and I feel it will work soon. Then glad to share with you and sir @amaitland

**Comment by hpposch** [comment]
@blgnklc I have not tried anything like this. I am developing a new application at the moment and i noticed that the Chrome Extensions would be very nice to have.
But i did not have time to implement something like this, i was just thinking about this.
If you like we could discuss about it, but it seems that you already have a good solution..

**Comment by hpposch** [comment]
@blgnklc are you interested in creating a new branch..
Maybe we can find some more developers for this 'project'

**Comment by blgnklc** [comment]
@amaitland @hpposch @okatip1  hey people. cefsharp is quite capable of registring the js obejects. Thanks all community about this project. I keep in touch with adblock team to get the idea of simple way of adaptiong the adblock to the current cefsharp project with using v8 capabilities. https://help.getadblock.com/support/tickets/487 this link to all interested people. best

**Comment by hpposch** [comment]
@blgnklc thanks for the info..
Please keep me up to date and tell me if you need manpower to implement this feature ;-)

**Comment by hpposch** [comment]
Btw. i cant access the support ticket from you :(

**Comment by AW1534** [comment]
hey @bilginkilic , how is this going? i would love to try this if this is even remotely done.

**Comment by tobuf** [comment]
This is the official forum respond to your question. It does not support.
https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=12199

And I think you can transform any extensions to the corresponding js file ,
which can be injected into the page.

**Comment by mitchcapper** [comment]
@tobuf the response is  out of date but this ticket is very old.  CEF has added limited extension support but the api is really not fleshed out, search some of the other cefsharp or CEF tickets for detals.
