### ISSUE TITLE
Video Fullscreen does not work

### ISSUE THREAD

**Issue by hpposch** [cefsharp/CefSharp#720]
Hello!

I have a simple WPF Application which has a ChromiumWebBrowser as Content.
When i now open a youtube video and click on the fullscreen button, the video is only show inside the control, and not over the complete screen.
Is this a know behaviour, if yes what can i do to fix this?

This is the Code i used for the sample:
ChromiumWebBrowser browser = new ChromiumWebBrowser();
browser.Address = "http://www.youtube.com";
MainGrid.Children.Add(browser);

**Comment by amaitland** [comment]
Updated issue like https://bitbucket.org/chromiumembedded/cef/issue/562

**Comment by hpposch** [comment]
Hi there!
I looked on the issues again and noticed that there has been something done..
Does this mean that Fullscreen is no possible with CEF Sharp?

**Comment by amaitland** [comment]
`Upstream` issue is still unresolved.

**Comment by amaitland** [comment]
`Upstream` issue has been resolved.

>  Add new CefDisplayHandler::OnFullscreenModeChange method.
>  Allow calls to CefBrowserHost::WasResized for windowed browsers.
>  Call WasResized internally so that fullscreen toggle displays correctly for HTML/JS content.

Standard disclaimer as always, `CefSharp` will wait until an official release branch of `CEF` before upgrading.

**Comment by hpposch** [comment]
Thats really good news :)

When do you think there will be a new release branch?
So that it is implementet in CefSharp?

**Comment by amaitland** [comment]
> When do you think there will be a new release branch?

3-6mths realistically

**Comment by amaitland** [comment]
`master` has been upgraded to `2454` which has the updated `API`. This is an experimental branch and doesn't have the official `45` release of `Chromium` yet as `CEF` has yet to upgrade.

The relevant `API` for this hasn't been exposed yet, will hopefully push the change sometime soon.

**Comment by amaitland** [comment]
`API` has been implemented see https://github.com/cefsharp/CefSharp/commit/63157b8e1bc16f60ba7f4eccc017a8913cedcd6c

**Comment by hpposch** [comment]
Does this mean full screen videos can now be displayed?

**Comment by hpposch** [comment]
And how can i use it now?!

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/blob/master/CefSharp/IDisplayHandler.cs#L44

Implement `IDisplayHandler` and handle the notification. You have to make your app toggle between fullscreen, so hide everything else that's not relevant basically.

**Comment by hpposch** [comment]
Ok, thats sounds quite easy..
But i have to exchange the assemblies, or do i get the latest version with NuGet?

**Comment by amaitland** [comment]
> But i have to exchange the assemblies,

You can't just swap things around as this change relies on a new version of `CEF`

> or do i get the latest version with NuGet?

As it's only in the development version it's not available on `Nuget` yet. The version isn't based on a release version of `Chromium` either, far as I know it's stable though there could be problems. If you really need this feature you can try the `CI` packages on `MyGet`

https://www.myget.org/F/cefsharp/

**Comment by hpposch** [comment]
Ok so if i compile the master branch, reference the new assemblies and then change the corresponding code, it shold work?

**Comment by amaitland** [comment]
Easiest way is to us the `build.ps1` script (for which there is a .bat file short cut).

https://github.com/cefsharp/CefSharp/blob/master/Build.bat

It will generate the `Nuget` packages, then you can reference them from a local directory

https://docs.nuget.org/create/hosting-your-own-nuget-feeds

**Comment by hpposch** [comment]
Ok.. 
Thank you very much for your support!!

**Comment by amaitland** [comment]
I have just upgraded `master` to version `CEF 3.2454.1326`, which is based on `Chromium 45.0.2454.85` (A stable release build)

**Comment by hpposch** [comment]
Nice.. 
I really should upgrade now :)

Where can i see the release notes of cefsharp or the changes since the last versions?!

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/wiki/ChangeLog

**Comment by hpposch** [comment]
Ok.. Thank you very much!

**Comment by hpposch** [comment]
> Easiest way is to us the build.ps1 script (for which there is a .bat file short cut).

The script fails with any error..
But i cant see it because the console closes after execution, is there any logfile?

**Comment by amaitland** [comment]
> The script fails with any error..
> But i cant see it because the console closes after execution, is there any logfile?

Open `poweshell`, run the script manually. All output is logged to the console.

**Comment by CRoemheld** [comment]
@amaitland What file am I looking for after starting the Build.bat file? The output was shown and I realized some additional files in my CefSharp folder, but what file do I need to use for a Nuget package with version 45.0.0 to install for my project?

**Comment by amaitland** [comment]
If the build was successful then check your `Nuget` folder, it should have generated `.nupkg` files. The output from the build script will tell you which files were generated.

> Successfully created package 'nuget\CefSharp.Wpf.45.0.0-CI1511.nupkg'

Example output from build.
https://ci.appveyor.com/project/cefsharp/cefsharp/build/45.0.0-CI1511#L44

You might be better to use the `CI` builds if your having problems building locally.

> It will generate the Nuget packages, then you can reference them from a local directory
> 
> https://docs.nuget.org/create/hosting-your-own-nuget-feeds

Follow the steps in this article to reference local packages.

**Comment by CRoemheld** [comment]
@amaitland Oh, on your example output there's a lot more output on the console. The output on my console stopped at the toolchain output.
Did I started the Build.bat correctly?

> start Build.bat

That's the only way I know to run those .bat files...

**Comment by amaitland** [comment]
> That's the only way I know to run those .bat files...

I personally start powershell and just run the script directly with `.\build.ps1`

> The output on my console stopped at the toolchain output.

Was there an error? Do you have `VS2013` or `VS2015` installed? (The default is `VS2013`, you can use `VS2015` with `.\build.ps1 vs2015`

**Comment by CRoemheld** [comment]
@amaitland Well after running build.ps1 and enabling powershell scripts on my machine before, the error is simply "Build failed".
 + CategoryInfo: NotSpecified: (:) [WriteError], WriteErrorEception 
 + FullyQualifiedErrorId: Microsoft.PowerShell.Commands.WriteErrorEception,Die

Visual Studio 2013 installed.

**Comment by amaitland** [comment]
Unfortunately that's not enough information to go on as I've not seen that error before.

Are you able to use the `nuget packages` generated by the `CI` server?

https://www.myget.org/F/cefsharp/

**Comment by CRoemheld** [comment]
At what point should I run the powershell script? After building the WPF project for the first time or just after I downloaded the CefSharp project via git clone?
I'm sorry I'm just too new in this topic, I don't know what you mean with the nuget packages from the CI server.

I'm able to use the 43.0.0 version via nuget package manager, the project even works fine with 43.0.0. But now I just can't get the version 45.0.0 though I tried many different ways to get a .nupkg file.

**Comment by amaitland** [comment]
> At what point should I run the powershell script? After building the WPF project for the first time or just after I downloaded the CefSharp project via git clone?

Shouldn't matter either way. Do you have the `VC++` development tools installed as part of `Visual Studio`?

> https://www.myget.org/F/cefsharp/

This `URL` is a `nuget` feed, that `countinous integration` builds are pushed to.

Using the following guide, try the 'Creating Local Feeds` option, instead of using a folder as the `source`, use the url above. Don't forget to check `Include Pre-Release`.

https://docs.nuget.org/create/hosting-your-own-nuget-feeds

**Comment by CRoemheld** [comment]
@amaitland See my edit in the post above.

Okay, when using the CI server, the nuget package manager does list 3 libs:
 + cef.redist.x64
 + cef.redist.x86
 + CEF SDK
The first two entries in the list are usually installed when installing the other versions of CefSharp (e.g. 43.0.0) via nuget package manager. As far as I know, the CEF SDK has never been installed in any of my projects.

**Comment by amaitland** [comment]
You can browser the packages using https://www.myget.org/gallery/cefsharp

You'll see there's `v45.0.0-CI1511`, if your not seeing this in your feed, likely you need to include `pre-release` packages (It's a drop down list, which defaults to `Stable Only`, you need to select `Include prerelease`).

**Comment by CRoemheld** [comment]
@amaitland 

Thanks. When looking for pre-released versions, there appear 45.0.0 versions of CefSharp.Wpf and other packages. I'm gonna take this and try if everything will work then.
Thanks a lot!
