### ISSUE TITLE
FocusHandler doesn't work in WPF

### ISSUE THREAD

**Issue by myrnazhou** [cefsharp/CefSharp#721]
Hi Guys,
I have a problem with the `IFocusHandler`, I've implemented it and set it to the `Browser.FocusHandler`. But after I put the breakpoint in `OnTakeFocus`, it was never been hit. Do you know what causes that? I've pushed it to our fork branch here https://github.com/Bodekaer/CefSharp/commit/c49fb5c768846eefbed1329d0354157e8c63883a

I've tested the one in WinForm, and it works fine, so it might be an issue with the one in WPF.

**Comment by amaitland** [comment]
If `CEF` ever adds support then we can reopen this.

**Comment by amaitland** [comment]
`CEF` has made some changes in regards to `osr` focus handling. 

https://bitbucket.org/chromiumembedded/cef/commits/6cccc3b8a7f3282be046865b91c75a635225d463

**Comment by amaitland** [comment]
Looks like this maybe fixed eventually.

https://bitbucket.org/chromiumembedded/cef/issues/1826/focus-handler-not-called-for-offscreen

**Comment by amaitland** [comment]
>  Fix delivery of CefFocusHandler callbacks to windowless clients.

https://bitbucket.org/chromiumembedded/cef/commits/406867f293042006e9f5f1a1e5201db012e50adf

Potentially this has been resolved with the above commit.
