### ISSUE TITLE
Cannot set Referer Header : 

### ISSUE THREAD

**Issue by hshiravi** [cefsharp/CefSharp#722]
I have a custom requesthandler class that is used to set the Referer header when loading a url. Using this class I can set any arbitrary header and all works fine except for the Referer header which can never be set. Seems as though it is always ignored or overwritten. The collection of request.Headers will have the Referer key/value but when analyzing the outgoing traffic its never set.

```
class myrequesthandler : IRequestHandler
{
    bool IRequestHandler.OnBeforeResourceLoad(IWebBrowser browser, IRequest request, IResponse response)
    {
        var headers = request.Headers;

        if (headers.Get("Referer") != null)
            headers.Remove("Referer");
        headers.Add("Referer", "http://www.example.com");

         //Must set the headers back on the property, we get a copy of the
         //headers above not a reference.
        
        request.Headers = headers;

        // False means continue.
        return false;
    }

...
}
```

**Comment by amaitland** [comment]
Try `OnBeforeBrowse` instead of `OnBeforeResourceLoad`.

**Comment by amaitland** [comment]
@hshiravi How'd you go? Problem sorted?

**Comment by hshiravi** [comment]
Actually you cant use OnBeforeBrowse because the request object is readonly and you cannot modify or update the headers. Thats why I went with OnBeforeResourceLoad which the request object can be modified but as mentioned the referer header is still overwritten. Still looking for a solution.

**Comment by amaitland** [comment]
#534

**Comment by amaitland** [comment]
Are you able to use the debugger and step into the code? Maybe modify one of the Example projects?

I refactored `IRequest` a while ago, possible that something is broken.

Also it would be helpful to know what version your using? (Should be included in every issue please)

**Comment by amaitland** [comment]
It's probably also worth trying to set another header, see if perhaps `Cef` is doing something special with referrer.

**Comment by amaitland** [comment]
@hshiravi How did you go investigating the problem?

**Comment by jornh** [comment]
@hshiravi what tool do you use to analyse the traffic? What CefSharp version?

My testing is done with current `master` ~ CefSharp `39.0.0-pre02`

I tried with https://www.whatismybrowser.com/developers/what-http-headers-is-my-browser-sending and https://referer.rustybrick.com/ it works with the code posted in #778 so probably also your code.

I tried with a few others:
* http://www.whatismyreferer.com/
* http://www.ericgiguere.com/tools/http-header-viewer.html
* http://pgl.yoyo.org/http/browser-headers.php

Which don't display the `Referer` header reliably. Lesson learned - if your test fails check the tools you use for testing :wink: 

Maybe there is something going on with Chromium not wanting to reveal `Referer` to insecure http hosts in all cases? Specially if `Referer` is a https host.

**Comment by jornh** [comment]
Since #722 got closed by it OP and no response from @hshiravi I think it's safe to close this one as well.
