### ISSUE TITLE
Shortcut keys don't work in WinForms

### ISSUE THREAD

**Issue by jr01** [cefsharp/CefSharp#723]
Shortcut keys don't work in WinForms.

Steps to reproduce:
Open the WinForms example and open the BrowserForm in the designer.
Set ALT-F as shortcut to the file menu item: Set Text property to "&File".
Build and run the Winforms example.
Set focus to the URL textbox.
Press ALT-F and notice that the file-menu gets focus and is expanded.
Set focus to browser control, i.e. select some text.
Press ALT-F and notice that nothing is happening.

I came up with a 'workaround' based on: http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=10927. 

In ClientAdapter.cpp/OnKeyEvent handler:

            if(!handler->OnKeyEvent(_browserControl, (KeyType)event.type, event.windows_key_code, (CefEventFlags)event.modifiers, event.is_system_key == 1)) {

				// post any unhandled keys to the active window, so that hot keys can be captured
				if(os_event != nullptr) {
					HWND activeWindow = GetActiveWindow();
					PostMessage(activeWindow, os_event->message, os_event->wParam, os_event->lParam);
					return true;
				}
				return false;
			}
			return true;

**Comment by jr01** [comment]
Seems this is known issue and there is a patch: http://code.google.com/p/chromiumembedded/issues/detail?id=1387

**Comment by jornh** [comment]
@jr01 thanks for sharing the local CefSharp workaround and digging up the CEF issue too :smile: much appreciated!

**Comment by amaitland** [comment]
Change was merged into `trunk` (2271) branch, so when we eventually upgrade this will be fixed.

https://code.google.com/p/chromiumembedded/source/detail?r=1967

**Comment by ljani** [comment]
As a workaround, you can also use [`IKeyboardHandler`](https://github.com/cefsharp/CefSharp/blob/87651fece834d03e612a07cf134291642d2159ef/CefSharp/IKeyboardHandler.cs) to route the key events for now.

**Comment by amaitland** [comment]
Resolved by using the `2272` branch.

 https://github.com/cefsharp/CefSharp/tree/cef/2272

**Comment by apzloy** [comment]
model.SetAccelerator(CefMenuCommand.Print, (int)Keys.P, false, true, false) (and other) just displays the shortcut in the context menu, nothing else. Key combination doesn't work, while it MUST. And i believe it's not the CEF bug because i've never seen it anywhere else. Even in delphi wrapper it works as expected (CEF4Delphi for example) with a same CEF release.
