### ISSUE TITLE
Renameing of CefSharp.BrowserSubprocess 

### ISSUE THREAD

**Issue by hpposch** [cefsharp/CefSharp#724]
Hello!

Is it possible to rename the subprocess of cefsharp?

**Comment by jornh** [comment]
It should be possible via `CefSettings` see https://github.com/cefsharp/CefSharp/blob/v37.0.0/CefSharp.Example/CefExample.cs#L27

**Comment by hpposch** [comment]
Ok, thank you.
I will try that.

**Comment by amaitland** [comment]
For those wishing to rename the subprocess, it's not possible to implement your own (call it whatever you like). See https://github.com/cefsharp/CefSharp/issues/1149#issuecomment-225547869
