### ISSUE TITLE
Bug: Browser not selectable in WPF ListBox

### ISSUE THREAD

**Issue by hpposch** [cefsharp/CefSharp#725]
Hello!

I have created a TabControl with 5 TabItems, each item contains a ChromiumWebBrowser (WPF).
Now i want all the Browser to be loaded at the same time. (Normaly it only loads when the tabitem is rendered)
For this i found a Solution with a special style, that overrides the tabcontrol-style.
You can find it here: https://github.com/hpposch/CefSharpInListBox/blob/master/MainWindow.xaml

With that solution everything works fine and all tabs are loaded at the same time.
The only problem is that now i can not select any text anymore, also it is not possible to click inside the google searchbar.

Do you have any idea why this happens?

**Comment by hpposch** [comment]
You can navigate to the google searchbar using the "Tab" Key

**Comment by amaitland** [comment]
In our `WPF Example` we use a modified `TabControl`, it might be worth having a look at.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf.Example/Controls/NonReloadingTabControl.cs

Otherwise try replacing the `ChromiumWebBrowser` controls with TextBoxes and make sure your style is working correctly.

**Comment by hpposch** [comment]
Does parallel loading work in your example?

I already tried to replace it with a textbox. When i use one everything works fine

**Comment by amaitland** [comment]
It should, your welcome to test it for yourself.

**Comment by amaitland** [comment]
I don't believe this is an issue with `CefSharp`, so I'm going to close this.

**Comment by hpposch** [comment]
Ok, i will try this today.
Thank you very much.

**Comment by hpposch** [comment]
Hello.
I have now figured out that it is a problem with CefSharp.
I have updated the Example: https://github.com/hpposch/CefSharpInListBox/blob/master/MainWindow.xaml

The first tab uses the built in Webbrowser and the second one uses ChromiumWebBrowser.
In the first tab i can enter everything inside the google searchbar, in the second one i am not able to enter anything.

Can you please have a look on that.
Because i think this would also help other users.

**Comment by amaitland** [comment]
@jankurianski Excellent suggestions!

I'd also suggest you do some more reading about styling `TabControl`, it's a notoriously complex control.

- http://stackoverflow.com/questions/9794151/stop-tabcontrol-from-recreating-its-children/9802346#9802346
- http://www.codeproject.com/Articles/460989/WPF-TabControl-Turning-Off-Tab-Virtualization

Also some Google searching is probably required.

I've tried to run your project and it's incomplete.
- There is no solution file.
- Shouldn't include the `obj` folder

I extracted your code, created my own project, if I remove your custom style everything works as expected. So I'd be looking at your style as first point of reference.

**Comment by hpposch** [comment]
Ok, i tried many solutions now to load 2 Tabs or more at the sime time, but it is not possible with the the standard TabControl, so i implemented my own TabControl which allows me now to load Tabs at the same time.

If anyone needs something like this, feel free to contact me, and i will try to help you.

**Comment by amaitland** [comment]
@hpposch Perhaps post a `Gist` of your sample solution? That way others can easily access the information :+1:
