### ISSUE TITLE
RegisterJsObject callback function with complex type crashes

### ISSUE THREAD

**Issue by ChristianWeyer** [cefsharp/CefSharp#726]
We have some code like this that worked fine with CEF1:
public class CefBridge
{
        public void SampleDataResult(object result)
        {...}
}

The JS code looks similar to this:
window.cefCallback.sampleDataResult(resultData);

resultData is a complex object.

Since we switched to CEF3 with CefSharp 37.0.0 this no longer works and crashes.

Is this behavior expected?
Thanks.

**Comment by amaitland** [comment]
> public void SampleDataResult(object result)

What type of object are you expecting `result` to be?

I'm not surprised this doesn't work, `functions` don't currently work with complex types.

**Comment by amaitland** [comment]
Looks like `CefSharp1` was returning a `Dictionary<string,object>`, if that's the case then it should be a simple matter of adding the additional knownType attributes for the `WCF` service.

I've committed https://github.com/cefsharp/CefSharp/commit/0a3ef1d0e2f27a63d0f9a1e893cf674ea4e37faa to the `cef/2171` branch. If your up for building from source then feel free to take it for a spin. If your happen then the change can be merged into `master`. (Currently CI builds are broken, so there are no pre made nuget packages at the moment)

**Comment by ChristianWeyer** [comment]
Yep, it is Dictionary<string, object> ;)
Thanks for the commit - however I currently do not have the spare cycles to build it from source :/

Sorry.
