### ISSUE TITLE
StackoverflowException

### ISSUE THREAD

**Issue by derroman** [cefsharp/CefSharp#728]
Hi!
I've discovered a StackoverflowException while testing the CefSharp framework.

The message is 
> An unhandled exception of type 'System.StackOverflowException' occurred in CefSharp.BrowserSubprocess.Core.dll

and it occures in the class which is in my opinion not the original source.
> cef_string_wrapper.h line 184

The detail view is not very helpful either:
![image](https://cloud.githubusercontent.com/assets/3176905/5626571/82ccac50-958d-11e4-8784-ba4f314092aa.png)

I can explain how to reproduce this:

- I'm using the CefSharp.Wpf.Example project
- I've added a new html file to the project containing [the following code(gist)](https://gist.github.com/derroman/3356f612b2aa1dde0a7f#file-testfile)
- - it's basically a span having an id and a little JavaScript function trying to get and return a selected range by a given element id. Not nice but it's a working test case.
- locally tested in the browser it looks like this:
![JavaScript console in Google Chrome](https://cloud.githubusercontent.com/assets/3176905/5626367/b7dbed64-958a-11e4-9014-626ba9a9d464.png)
- When I start debugging the project, assigning the debugger also to all CefSharp.BrowserSubprocceses, opening my local file in the example "browser" and put the function call in the little box on the right a StackoverflowException occurs.
![StackoverflowException](https://cloud.githubusercontent.com/assets/3176905/5626476/560a03da-958c-11e4-958a-a69f25126bab.png)

![Exception](https://cloud.githubusercontent.com/assets/3176905/5626220/0a32aa14-9589-11e4-8f75-cbbb2c579386.png)

As far as I can see (I'm not a C++ expert) this happens somewhere over here:
![image](https://cloud.githubusercontent.com/assets/3176905/5626506/d5d7250c-958c-11e4-9436-1c98a41e33c1.png)

(Is this the attempt to somehow "convert" the JavaScript object? I think this "range" object which should be returned by my JavaScript function is somehow leading to this exception.)

Hopefully my remarks will help you. Please let me know if I did something wrong or if I could help at least testing.

**Comment by derroman** [comment]
I forgot to mention that I'm using the nuget package:
Version 39.0.0-pre01

**Comment by amaitland** [comment]
@derroman Thanks for the very detailed bug report!

Unfortunately `EvaluateScriptAsync` is only capable of mapping relatively simple data from the browser into `.NET` objects, basically primitive types, one dimensional arrays, and basic objects can be turned into keyvalue pairs. For your situation you'll need to parse the data and only return exactly what you need in your javascript code. The `Range/Selection` object returned currently is an incredibly complex graph which `CefSharp` simply cannot map.

**Comment by derroman** [comment]
thanks for your fast response. 
Parsing my needed data is what I've already did meanwhile. So one can say my workaround is no longer a workaround but the correct way of handling it.

Good to know. Maybe a little hint in the documentation would be helpful for others?

**Comment by amaitland** [comment]
> Good to know. Maybe a little hint in the documentation would be helpful for others?

I'm sure it would be helpful. We're a little light on documentation at the moment. Suggestions on where you'd expect to find said documentation?

Currently `IWebBrowser` has a fair description of most methods, though I don't know that many people actually look at it. As there are three `IWebBrowser` implementations, I'm not really keen to duplicate comments.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp/IWebBrowser.cs#L103

**Comment by derroman** [comment]
In addition in my opinion it would be great to get a proper exception which tells me as a developer what's the problem. 
It would be much more fun instead of just seeing the browser die. I would have never discovered this behavior without spending the time with the test project containing all the sources.

So maybe in a future release one could add some custom error handling to inform the developer what's wrong.

**Comment by derroman** [comment]
> Suggestions on where you'd expect to find said documentation?

As I've just discovered there is actually a comment in the [FAQ "CallJSWithResult"](https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#CallJSWithResult)

>Note that only trivial values can be returned (like int, bool, string etc) - not a complex (user-defined) type which you have defined yourself. This is because there is no (easy) way to expose a random JavaScript object to the .NET world, at least not today.

So it is obviously not only about some missing documentation it is also about developers like me not reading the fine print. ;)

**Comment by amaitland** [comment]
> In addition in my opinion it would be great to get a proper exception which tells me as a developer what's the problem.

I have improved the error handling, will be included in the next major release.

https://github.com/cefsharp/CefSharp/commit/fc4cde6e7847d55bc1e89a595070a1e25b502df9

**Comment by derroman** [comment]
okay. Great. Thank you.
