### ISSUE TITLE
WPF Video Performance

### ISSUE THREAD

**Issue by canartuc** [cefsharp/CefSharp#729]
Hi,

When I open youtube video on both WPF Example and my implementation, it is like stop motion. My computer: Intel Core i5-4590 CPU @ 3.30GHz, 12GB RAM, 64 bit Genuine Windows 7. There is not any problem in WinForms implementations.

Sorry, if it was discussed before, I checked both Google search and issues.

NOTE: v37.0.0

**Comment by amaitland** [comment]
- Are you by any chance using the stock onboard `Intel Graphics Card`?
- Are you running `.Net 4.5.3`? Please make sure you are.

I'd suggest trying a few things
- Try you app on a different machine, preferably with a different video card
- Make sure you have the latest Graphics Card Drives installed
- Make sure you have all the required libs in your bin folder (see https://github.com/cefsharp/cef-binary/blob/master/README.txt#L116)
- Check in `Task Manager` that and instance of `CefSharp.BrowserSubProcess.exe` with command line args including `--type=gpu-process` has been spawned.
- Try disabling GPU acceleration (see https://github.com/cefsharp/CefSharp/issues/627#issuecomment-64232089)
- Look in the `Debug.log` file located in your bin directory, see if any errors are shown (ignore render sandboxing)
- Try the latest `39.0.0-pre01` release, as it has some rendering improvements (See https://www.nuget.org/packages/CefSharp.Wpf/39.0.0-pre01)
- Try the `CefSharp.MininimalExample` WPF App (See https://github.com/cefsharp/CefSharp.MinimalExample)
- Download the relevant `Cef Test App` from http://cefbuilds.com/#branch_2062, the matching version for `37.0.0` is CEF 3.2062.1898. Run `cefclient --off-screen-rendering-enabled`, load the same youtube clip and see what you get.

There isn't a whole lot we can do from the `CefSharp` side of things, if none of that proves useful, try looking in the `Cef Forum`. (`CefSharp` is just a wrapper around `Cef`)

**Comment by canartuc** [comment]
Hi,

I am sure for 2 points that you wrote (.Net version and Intel Graphics card). I will do your suggestions and will inform if anybody have same thing.

I consider it may WPF problem but the thing is .Net default browser control is so smooth (IE Wrapper). So I consider as it may CEF Sharp or CEF problem.

Thank you for your quick reply.

**Comment by amaitland** [comment]
> I am sure for 2 points that you wrote (.Net version and Intel Graphics card)

Can you please clarify? Do you have an Intel Graphics Card? Are you using `.Net 4.5.3`?

> So I consider as it may CEF Sharp or CEF problem.

I don't believe it to be a `CefSharp` problem, `YouTube` clips play fine on my development machines. 

Also please note:
- Issue #720 is outstanding, which will be a problem if your trying to play fullscreen 
- H.264 is not supported

Can you provide a link to the youtube click you were trying?

**Comment by canartuc** [comment]
Yes, I can clarify:
Display Adapter: Intel HD Graphics 4600 (there is no more graphics card, this is stock HP's company PC)
Framework version: 4.5.51209 with Visual Studio 2013 Community Edition

There is not specific video (all of them are slow but I feel the problem while typing letters in search, it is slow too) but my latest test for this: http://www.youtube.com/watch?v=y6Sxv-sUYtM . May be WPF is getting happier and doesn't care whatever it should handle : D

I will test it in my home computer too with AMD Radeon. Thank you!

**Comment by amaitland** [comment]
> Display Adapter: Intel HD Graphics 4600 (there is no more graphics card, this is stock HP's company PC)

Intel Graphics cards are notoriously poor performing, if updating to the latest drivers doesn't help then I'd be disabling gpu acceleration. (I'd still try all the other steps as well).

**Comment by canartuc** [comment]
I tried Example WPF project in my home computer yesterday.Even it doesn't have good graphics card (AMD Mobility Radeon HD 5730), there wasn't a problem about videos. It works very smooth. I will try disabling GPU acc. and other steps in my work computer today.

**Comment by canartuc** [comment]
OK, solved! `--disable-gpu` parameter solving the problem, thank you!

I am adding this command in Visual Studio's Debug options or calling it from the command line. I saw we can add command line parameters programmatically, but I had no luck to do it:
```
var settings = new CefSharp.CefSettings
{
    PackLoadingDisabled = true
};
settings.CefCommandLineArgs.Add("disable-gpu", "");
Cef.Initialize(settings);
```

**Comment by jornh** [comment]
Just speculating but ... maybe try adding an assignment of `1` to mimic a command line of `--disable-gpu=1`:

```
settings.CefCommandLineArgs.Add("disable-gpu", "1");
```

**Comment by amaitland** [comment]
If that doesn't work then try

```c#
settings.CefCommandLineArgs.Add("disable-gpu", "disable-gpu");
```

**Comment by canartuc** [comment]
Thank you @jornh and @amaitland but no luck. I tried to add 1 as integer but CommandLineArgs accepts both string parameters.

**Comment by daveaton** [comment]
@canartuc I just tried the last command that @amaitland has suggested

settings.CefCommandLineArgs.Add("disable-gpu", "disable-gpu");

After you recompile you can test it's it's set by pointing your browser to 

chrome://version

see my example
http://www.eatoncode.com/shareit/2015-01-11_1741.png

Thanks,
David

**Comment by amaitland** [comment]
@daveaton Nice tip about the `chrome://version` url :+1:

**Comment by canartuc** [comment]
@daveaton chrome://version is very good tip, thank you for your info. But I have no luck with the following code:
````
var settings = new CefSharp.CefSettings
{
    PackLoadingDisabled = true
};
settings.CefCommandLineArgs.Add("disable-gpu", "disable-gpu");
Cef.Initialize(settings);
````
http://i60.tinypic.com/qpp155.jpg

Do you use the similar code?

**Comment by daveaton** [comment]
Hi... 

From what I understand GPU takes advantage of the graphics cards from the browser.

Here is what I was using to test it.   http://ie.microsoft.com/testdrive/performance/fishbowl/

Here is a screen shot with GPU :NOT disabled...
http://www.eatoncode.com/shareit/2015-01-13_0933.png


Here is a screen shot with GPU disabled 
http://www.eatoncode.com/shareit/2015-01-13_0938_001.png

I did not notice any difference between using PackLoadingDisabled = true or not....

I turn off GPU only because it's not supported by everyone...  I have a $400 + Graphics card and it works great with GPU not disabled but others running the cheapest laptop in town it's very bad.... in this case disabling GPU does better of the 2 evils.

I also notice screen size has a big factor.. running 800X600 is about 5 times faster than running at 1440X900

Here is the code I use to disable......


           

           //settings.CefCommandLineArgs.Add("disable-gpu", "disable-gpu"); //works
            settings.CefCommandLineArgs.Add("disable-gpu", "1");
            settings.CefCommandLineArgs.Add("disable-gpu-vsync", "1");


Hope that helps.

**Comment by daveaton** [comment]
Just as a side note... running this test  http://ie.microsoft.com/testdrive/performance/fishbowl/

I can run about 2,000 fish with any issues running v39 of the Official Chrome Browser but I can only run about 750 using the CefSharp v37..... interesting....

Thanks,
David

**Comment by jornh** [comment]
@daveaton good performance info there! BTW are your test results with WPF - which the OP posted about - or WinForms? If you're not on WPF that could explain the difference in `settings.CefCommandLineArgs.Add("disable-gpu", "disable-gpu");` success rate.

Note: One difference in performance with Chrome could be due to that WPF is OffScreen and Chrome is running WinForms which is closer to Chrome. I wouldn't at any point expect something CEF based, like CefSharp, to perform *better* than Chrome. After all Google have more engineers to throw at this than CEF's one-person endavour with contributions. I think only thing we can ever hope for is similar-ish performance. 

Finally a bit of performance info from me (CefSharp 39 - CEF 3.2171.1949), on a Lenovo W510 claiming to use a NVIDEA Quadro FX 880M: 

  * With the 32bit CefSharp.Wpf.Example the Fishbowl demo above set to auto *with* GPU acelleration goes above 1500 fish.
  * With `settings.CefCommandLineArgs.Add("disable-gpu", "disable-gpu");` *and* a small window I can only get to 30 fish. 
  * Fullscreen it goes to **one** fish with GPU disabled!

The YouTube video plays alright even with GPU disabled.

**Comment by amaitland** [comment]
> I can run about 2,000 fish with any issues running v39 of the Official Chrome Browser but I can only run about 750 using the CefSharp v37..... interesting....

In general `39` has some major performance improvements in rendering, both `WPF` and `WinForms` benefit from major speed boosts when upgrading to `39` :smile: 

From me using an `i7-3770K`, 16gb of ram, `ATI 7850 1gb`
- With the 32bit CefSharp.Wpf.Example the Fishbowl demo above set to auto with GPU acceleration I can get ~2800 fish.
- Similar results with gpu disabled

Disabling gpu using command line args in `WPF` worked as expected in `39`, haven't tried `37`

**Comment by amaitland** [comment]
For future reference I added the `disable-gpu` and `disable-gpu-vsync` commands (commented out) to the `CefExample` file in `cef/2171` branch.

See commit https://github.com/cefsharp/CefSharp/commit/eded1747111cf8120f110d3b24ded20b2ff13717

**Comment by amaitland** [comment]
@canartuc Did you eventually solve your problem?

**Comment by amaitland** [comment]
It only just occurred to me that you maybe able to use `BrowserSettings.WebGlDisabled`

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/BrowserSettings.h#L269

I haven't tested, so it's just a though.

**Comment by jankurianski** [comment]
@amaitland @daveaton Added some of your helpful messages from here to a new section on troubleshooting graphics problems on the wiki, let me know if you can think of more: https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#troubleshooting-graphics-video-or-performance-problems

**Comment by amaitland** [comment]
@jankurianski Nice one! I'll let you know if I think of anything else :+1:

**Comment by daveaton** [comment]
@amaitland - I still have some issues.. so I tried your suggestion with   BrowserSettings.WebGlDisabled

I only got errors when trying to use it.

    browser.BrowserSettings.WebGlDisabled = 1;

I get a Null Exception.  I tried setting it right after I defined the browser.

So I tried the command line at startup settings and it worked nicely..

    settings.CefCommandLineArgs.Add("disable-webgl", "1");

You can test if WebGl has been disabled here.

http://doesmybrowsersupportwebgl.com/

Example of WebGL disabled - http://www.eatoncode.com/shareit/2015-02-01_0855.png

**Comment by daveaton** [comment]
Hum... It seems that any time you try to set any BrowserSettings they all come back as Null Exception

**Comment by daveaton** [comment]
It seems that the problem was WebGL all along..

It seems that firefox blocks graphic cards with certain drivers to prevent this..

http://www.sitepoint.com/firefox-enable-webgl-blacklisted-graphics-card/

Is there anyway we can do this ?  Anyone have any ideas how to Implement such a feature ?

**Comment by jornh** [comment]
@daveaton, more an upstream (Chromium) thing I'd say. Googling for "chromium webgl blacklist" yields [this on SO](http://stackoverflow.com/questions/12506678/where-can-i-find-chromes-webgl-gpu-blacklist) leading to that [Chromium already has it](https://code.google.com/p/chromium/codesearch#chromium/src/gpu/config/software_rendering_list_json.cc)

But let's get back to the original issue at hand from @canartuc related to WPF. Looks like https://github.com/cefsharp/CefSharp/issues/729#issuecomment-68997256 resolved it. Anything else @canartuc before we close this issue?

**Comment by canartuc** [comment]
@amaitland @jornh I am really sorry that I couldn't follow this issue because of my business trip. I couldn't check it right now but I am fine with disabling with command line parameter. Thank you very much for all effort and help!

**Comment by jornh** [comment]
@canartuc don't be sorry :smile: have a safe trip! 

Closing as OP has a working solution. On top of that this issue helped dig up various GPU related info!
