### ISSUE TITLE
Browser In A State of Permanent Loading After Clicking #links

### ISSUE THREAD

**Issue by murphmar** [cefsharp/CefSharp#733]
37.0.0 release, WinForms.

When clicking a #link the browser seems to get set to an endless state of loading. I previously had a loop OnBeforeClose that waited until browser.IsLoading == false before disposing the browser. With that in place with this release the app will hang endlessly when trying to close the browser after clicking a #link. I've removed the loop for now and everything works fine, but I'm sure some issues will come of it...

**Comment by amaitland** [comment]
> I previously had a loop OnBeforeClose that waited until browser.IsLoading == false before disposing the browser.

That sounds fraught with danger to start with! Sure you loop isn't blocking the thread?

What exactly are you trying to achieve? I don't see a single question in your entire post.

**Comment by amaitland** [comment]
Are you implying you need to wait for the browser to finish loading before it can be disposed?

**Comment by murphmar** [comment]
Sorry for the delayed response. You can ignore the loop part, it's just a workaround for our situation. Without it in place our entire host application would force close on occasion if the browser was closed while in a state of loading. I don't have an issue with that, and it's taken out for now.

I wasn't actually asking a question, just presenting a possible issue and looking for input/checking to see if anyone else had come across it. It doesn't seem right that the browser would become locked in a loading state by clicking a # navigation link.

**Comment by amaitland** [comment]
You should always ask a question when creating an issue :+1: 

The browser isn't locked in a loading state per say, it's just a flag. 'Cef' doesn't make any guarantees that the load end event will be called, which is where the flag is set.

Look at 'NavStateChanged' event for the more reliable loading indicator. Depending on version you can check the 'CanReload' event property, or in newer versions there is a is loading property. Same value, one is just the inverse of the other.

The randomly closing part is more concerning, can you provide sample code to reproduce?

**Comment by amaitland** [comment]
@murphmar Anything further to add on this one?

**Comment by murphmar** [comment]
No, if this is working as intended then that's that. Consider it closed :smile:

**Comment by amaitland** [comment]
@murphmar Did you try `NavStateChanged` instead?

**Comment by amaitland** [comment]
Background information http://magpcss.org/ceforum/viewtopic.php?f=6&t=10906

(`CEF` maintainer suggests `OnLoadingStateChange` which maps to `NavStateChanged` in `CefSharp` land)
