### ISSUE TITLE
How do you handle the href tel: links

### ISSUE THREAD

**Issue by wiscow** [cefsharp/CefSharp#735]
Good Morning,

I am currently using CEFSharp prerelease version 39.0.0.1 and my application is in WPF.
Currently when i try to click on a tel link in the CEFSharp browser nothing is currently happening. 
I was wondering if anyone had some insight into this?  It sounds like this is a supported feature in chromium.  I am not sure if this is something that is easily achieved in CEFSharp?  Any insight or point in the right direction would be great!  

Thanks,
Kyle.

**Comment by daveaton** [comment]
What did you exptect to happen?

I think your referring to these.  http://webdev-il.blogspot.com/2011/03/how-to-make-html-link-to-call-phone.html#!/2011/03/how-to-make-html-link-to-call-phone.html

Without checking and off the top of my head I am thinking these could be checked either BeforeBrowse or BeforeResourceLoad where you would need to do some compare and launch the application of your choice by passing the correct arguments.

The same thing happens on Skype urls like this..  http://www.ehow.com/how_6931969_hyperlink-skype.html

Once I get back to a computer I can confirm..  but maybe that should give you an ideas of where to start.  Unless somone else has better idea of how to do this.

Thanks,
David

**Comment by wiscow** [comment]
Yeah i started down the path of the RequestHandler and i think that is actually the perfect spot considering I will have to do some other processing before making the call as well.  Yes the link in chrome/IE/Firefox prompts for an "external protocol" and i can make the call straight from Lync or another softphone.  Anyway thanks for the answer.  Ill come back here if i continue to be stumped. However, for the time being the RequestHandler seems to be a good spot for investigation.

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/blob/master/CefSharp/IRequestHandler.cs#L19

`OnBeforeBrowser`, check the `request.Url` to see if it matches, if it does, load your external application and return true to let `CefSharp` know that you've handled the request.

**Comment by wiscow** [comment]
Yup totally worked i used this for 'maito:' and 'tel:'  just use Process.Start("...") and pass the link in.  Windows will handle the link for you.

**Comment by amaitland** [comment]
Excellent!

For reference to others any chance you could post a code snippet demonstrating your solution?
