### ISSUE TITLE
JS Function Unable to Return Variable in Another Class.

### ISSUE THREAD

**Issue by Spiderpig86** [cefsharp/CefSharp#736]
Hello. I've set up a small demo using CefSharp and everything seems to run correctly. I've also registered a JS Object and it is working fine. In one function, I tried to make it return a value that exists in another class just to test. Even though that value is a public string, the Javascript function always results in an error: 'Error: Exception has been thrown by the target of an invocation.' 

Example: 
Public Function getVar()
        Return SomeForm.Variable
    End Function

Is there something I am doing incorrectly?

**Comment by amaitland** [comment]
If you put a breakpoint on the return and step out does it return correctly? In theory I don't see a problem with what your doing.

For future reference could you also include the version you are using when creating an issue.

**Comment by Spiderpig86** [comment]
I am currently using CefSharp 37.0.0. I've also tested out the right click menu. The only issue is that the text on the menuitems such as "Back", "Print", and more do not show at all.

**Comment by amaitland** [comment]
Let's focus on the issue at hand.

The degging issue isn't 'CefSharp' related, try resolving that first and see how you go.

**Comment by Spiderpig86** [comment]
There is something really weird going on. When I tried to return the value in the same class itself or any other class that is not the JSObject class, it returns the right result. The JSObject class seems to only be returning a null string unless I hardcode something into it such as return "test".

**Comment by amaitland** [comment]
Maybe some sort of strange byref/byval issue? Try taking a reference to your property before returning it.

**Comment by Spiderpig86** [comment]
Thanks for pointing that out. I will look into it. A strange behavior I ran into is how I was able to return the title of a form, but no the variables.

**Comment by amaitland** [comment]
How'd you go? Track down the problem?

**Comment by Spiderpig86** [comment]
Unfortunately, I am still unable to track down what may be causing the issue.I will continue investigating.

**Comment by amaitland** [comment]
Closing due to lack of feedback. Feel free to reopen if required.

**Comment by Spiderpig86** [comment]
I'm going to reopen this topic if you guys don't mind. I have tested with CefSharp 41.0.1 on Windows 10 with .NET 4.0 and 4.5 with an offscreen webview. I still have the same issue. Code: 
```
Public Class MainAPI
    Public test As String
    Public myProperty As Integer
    Public Sub New()
        test = "potatoes"
        myProperty = 42

    End Sub
    Public Function EchoMyProperty() As Integer
        Return myProperty
    End Function
    Public Function getCurrentURL()
        MsgBox(Mainfrm.getWebControl().Address)  //Runs and returns website url correctly
        test = Mainfrm.getWebControl().Address //Results in error
        Return test
End Function
End Class
```
Code in Mainfrm:
Public Sub New()
InitializeComponent()
//WebControl initialization
 WebControl.RegisterJsObject("polarity", New MainAPI)
End Sub

The EchoMyProperty() function returns 42 as it should. I'm not sure why I'm still getting this error. Am I implementing the API incorrectly?

**Comment by amaitland** [comment]
Not knowing anything about `VB.Net`, my guess is that you have a threading issue and are trying to access part of your `UI` on a `non UI` thread, so try marshaling the call.

**Comment by Spiderpig86** [comment]
Ok. I have a working solution that may work in the API. I'm not sure how I'm going to implement this into the API class:
```
 Dim js As String = "document.cookie;"
            Dim cookieTask = WebControl.EvaluateScriptAsync(js)
            cookieTask.ContinueWith(Function(t)
                                        If Not t.IsFaulted Then
                                            Dim response = t.Result
                                            cookieStr = If(response.Success, (If(response.Result, "null")), response.Message)
                                        End If
                                        If t.IsCompleted Then
                                           //List of cookies are successfully returned.
                                    End Function, Tasks.TaskScheduler.FromCurrentSynchronizationContext())
```
Is it possible to do something like this with JS binding? I know you may not be familiar with VB.NET, but I thank you for trying your best to understand.

**Comment by amaitland** [comment]
> Is it possible to do something like this with JS binding?

Should be possible, just execute a function that performs whatever javascript you require and then interact with the bound object to return your results.

For reference there are cookie specific methods available like https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.Core/Cef.h#L301

**Comment by Spiderpig86** [comment]
Just to clarify a bit, the error is from executing the javascript function from the devtool console. Executing from native code works fine.
