### ISSUE TITLE
Winform C# 4.0 v37 master 12 JAN 15 Window.Open has 2 Popups ? With 2 Address Changes?

### ISSUE THREAD

**Issue by daveaton** [cefsharp/CefSharp#737]
Hi.

Here is a video where Chrome v39 latest only popups 1 time using a Window.Open method  while the last v37 master build on 12 JAN 15 has 2 popups when I was only expecting 1.

Also the Url Changed when it was not suppose to.  It did not Load the new content but it should not change the url if it was a popup or at least I did not expect it to.

http://www.eatoncode.com/shareit/2015-01-12_0930_001.swf

Thanks,
David

**Comment by amaitland** [comment]
@daveaton Sounds like an upstream issue at first though.

Got a sample of the script used to open the windows? Preferably as a `JsFiddle` :+1:

**Comment by daveaton** [comment]
Here you go..  http://jsfiddle.net/atpkoww2/

**Comment by amaitland** [comment]
http://stackoverflow.com/questions/128923/whats-the-effect-of-adding-return-false-to-an-onclick-event

To prevent the default behavior happening you need to `return false` in your `onclick` handler, that part's expected. I'm actually surprised it doesn't open two windows in `39`, they must have changed some behavior.

I think both `Address` and `Title` change when loading a popup, which is slightly inconsistent with the others that ignore popups, happy to see that changed.

**Comment by daveaton** [comment]
Adding the return false value did solve the issue.. I just need to tell everyone on the web to start using it... I noticed the Address still changed.

Are you saying this has been fixed in CEFSharp 39 or Official v39 Chrome ?

And was you referring to the 2 window issue or the address part ?

Thanks,
David

**Comment by jornh** [comment]
> I just need to tell everyone on the web to start using it...

Yes start doing that and see if you succeed :stuck_out_tongue:

Both CefSharp 39 (tested with WinForms and WPF) and Chrome 39 behaves the same on your http://jsfiddle.net/atpkoww2/ *if you disable the Chrome popup blocker for that page* so I'd say CefSharp 39 is working according to spec (on the opening two popupf for your JSFiddle part at least). Whether version 37 behaves differently I care less about - better to move forward as I see it ...

**Comment by amaitland** [comment]
> Adding the return false value did solve the issue.. I just need to tell everyone on the web to start using it...

They should already know! lol

> I noticed the Address still changed.

In `CefSharp` we typically ignore the events raised by `Cef` when the browser is a popup. I think short term, we just add a `IsPopup()` check.

For both event handlers in `CefSharp` 
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Internals/ClientAdapter.cpp#L68
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Internals/ClientAdapter.cpp#L76

Example of checking for popup and ignoring.
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Internals/ClientAdapter.cpp#L137

**Comment by jornh** [comment]
@daveaton agree to my findings in https://github.com/cefsharp/CefSharp/issues/737#issuecomment-69784576 or did I miss something? 

Did @amaitland's comments help?

**Comment by daveaton** [comment]
@jornh Are you saying you found that Chrome 39 is has 2 windows if you turn off Popup Blocker ?

I have upgraded to v39 now..  I have not been able to figure out how to use IsPopup()

But I see the address changing anymore on a popup.

On a side note it seems that v39 freezes up a bit more then v37 did... I might have to revert back down to v37 if I can't figure out what's happening. collecting more data.

**Comment by jornh** [comment]
> Are you saying you found that Chrome 39 is has 2 windows if you turn off Popup Blocker ?

Yes exactly!

**Comment by amaitland** [comment]
> On a side note it seems that v39 freezes up a bit more then v37 did... I might have to revert back down to v37 if I can't figure out what's happening. collecting more data.

I'm surprised to hear that, from everything I've seen `39` is a huge step forward performance wise.

**Comment by amaitland** [comment]
> I have not been able to figure out how to use IsPopup()

With the merge of `cef/2171` my links are no longer valid

Need to change [OnAddressChange](https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Internals/ClientAdapter.cpp#L125) to something like the following


```c++
if (!browser->IsPopup() && frame->IsMain())
{
    _browserControl->SetAddress(StringUtils::ToClr(address));
}
```



For `OnTitleChange` I've already handled the `Popup` scenario (the code now sets the popup window title)
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Internals/ClientAdapter.cpp#L133

**Comment by jornh** [comment]
@amaitland (and others) a tip: I always prefer to link to tags,or for non tagged code a specific commit) this way the links don't break so much - but it's of course up to the reader to detect that the code *ma* have schanged later on..

**Comment by amaitland** [comment]
@jornh Makes sense :+1:

**Comment by daveaton** [comment]
@amaitland @jornh -  I have not had a chance to truly take a look into this since I started my busy cycle with students in class..  I will take a hard look at it later on..   Do you think we can pass the Is Popup variable some how ? I can think of a couple of instances I wish I had it.  I will look into more of this later on and modify code.  Right now with the recent code It's works pretty well with v39. 

On another note I am having some major issues with v39 freezing up in certain cases..  It works great on my desktop machine with WebGL disabled but really, really, bad on another laptop of mine.  I want to collect more data to see the triggers of a reproduce able events and try different settings then I will open up a seperate ticket with all the facts or at lease some examples of what's happening.. 

As far as this ticket.. I think we have enough info to close this issue since it does works the same as the Chrome v39 counter part  when you disable popups and we can include the return false to prevent this from happening in my examples and even a way to detect it using code with browser->IsPopup().

Thanks,
David

**Comment by amaitland** [comment]
> I want to collect more data to see the triggers of a reproduce able events and try different settings then I will open up a seperate ticket with all the facts or at lease some examples of what's happening..

Unfortunately there is very little we can do when it comes to performance, it's very much controlled by the version of `cef` that's being used. It maybe worth grabbing a version from http://cefbuilds.com/ possibly from the `2272` branch to see if performance is any better?
