### ISSUE TITLE
Wpf cefshrp WebBrowser control not rendering xml/xhtml from Memorystream or string

### ISSUE THREAD

**Issue by jitsingh89** [cefsharp/CefSharp#739]
hi,
I have xhtml,xml file in Memorystream or string
If I am rendering in cef webbrowser control it's not rendering

**Comment by jankurianski** [comment]
Please provide a complete example via https://gist.github.com or a fork of CefSharp's MinimalExample project on GitHub.

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue

**Comment by amaitland** [comment]
@jitsingh89 Further comment before we close this issue?
