### ISSUE TITLE
CefSharp v37.0 Winforms make the whole application freeze when interacting with any other control like button or textbox

### ISSUE THREAD

**Issue by Ahmedgis** [cefsharp/CefSharp#740]
I'm using CefSharp WinForms v37.0, i works great unless not interacting with any other control on the form, i added a new instance from (ChromiumWebBrowser) to a panel and put some button and labels around it.

When starting the application and passing the url address to open, it opens successfully, but when i tried to click on any button on the form the all form freeze and no response.

This also happened when using either the executable version, or from the VS2010 debugger for my solution.

I also noticed that the application form which contain the (ChromiumWebBrowser) instance moved its focus to the back from other windows opened application or directories and another window called (cef...) opened and closed repeatedly until i kill the task from the Windows Task Manager.

In the Windows Task Manager i found two processes called (CefSharp.BrowserSubprocess.exe) running and consuming a lot of memory (~ 130 MB) each.

so can anyone help me solving this problem because i need this library very much to run a WebGL enabled website.

Note: I'm Using Windows 7 Ultimate 64bit , Visual studio 2010, VB.Net, CefSharp v37.0.0.0 x86 version and the build target is x86.

Thanks

**Comment by amaitland** [comment]
> In the Windows Task Manager i found two processes called (CefSharp.BrowserSubprocess.exe) running and consuming a lot of memory (~ 130 MB) each.

That's actually very low in web browser terms, it's quite possible to get well over `1gb` in memory usage.

> Note: I'm Using Windows 7 Ultimate 64bit , Visual studio 2010, VB.Net, CefSharp v37.0.0.0 x86 version and the build target is x86.

If your using the `nuget` package make sure you've got the latest `VC++ 2012 Redist` installed (Update 4 at time of writing). (I know your using VS2010, the `VC++` version is not directly related).

http://support.microsoft.com/kb/2019667

Also make sure you've got the latest `.Net` patches installed

Thirdly try building from source in `VS2010` (we don't directly support `VS2012` anymore, though it should still work)

> I also noticed that the application form which contain the (ChromiumWebBrowser) instance moved its focus to the back from other windows opened application or directories and another window called (cef...) opened and closed repeatedly until i kill the task from the Windows Task Manager.

You'll have to be more specific, I don't understand what your saying there.

**Comment by amaitland** [comment]
It sounds environment specific, though it may be helpful to isolate with an example. (Please no binary uploads).

Can you fork https://github.com/cefsharp/CefSharp.MinimalExample, modify and upload an example to `GitHub`?

**Comment by amaitland** [comment]
@Ahmedgis Any further comment?

**Comment by Ahmedgis** [comment]
Thanks @amaitland for help.

I think the problem in the WebGL support, it's still experiment, because when using CefSharp to browes for any other website it works great. 

I'm using Cesium (http://cesiumjs.org/) it is a JavaScript library for creating 3D globes and 2D maps in a web browser without a plugin. It uses WebGL for hardware-accelerated graphics, and try to control the Cesium globe through .Net desktop application using CefSharp.

Thanks for help
