### ISSUE TITLE
Weird behavior when pressing right key in textbox

### ISSUE THREAD

**Issue by myrnazhou** [cefsharp/CefSharp#746]
After pulling latest commit from 'cef/2171' of https://github.com/cefsharp/CefSharp, I noticed that each time I press right key in textbox in cefsharp WPF, the focus was moving away from the browser. I tried it in the wpf example. Do yo know what causes this?

**Comment by amaitland** [comment]
Interesting! https://github.com/cefsharp/CefSharp/commit/ae3bfb3d3aad637c8f2911768a1116b9636b65f8 should fix

**Comment by myrnazhou** [comment]
Great, that fixes it
