### ISSUE TITLE
Getting a "System.AccessViolationException' occurred in CefSharp.Core.dll" exception when setting cookie.

### ISSUE THREAD

**Issue by wiscow** [cefsharp/CefSharp#748]
I am currently running version 39.0.0.1 and when I attempt to set a cookie using the CEF.SetCookie method.  The one thing to note is that the WPF control is actually launched from a Winforms application.  When i launch the application as a standalone WPF application i am not recieving the error. The error message is:

"Attempted to read or write protected memory. This is often an indication that other memory is corrupt."

the pertinent part of the stack trace is:

```
   at CefCurrentlyOn(cef_thread_id_t )
   at CefSharp.Cef.SetCookie(String url, String name, String value, String domain, String path, Boolean secure, Boolean httponly, Boolean has_expires, DateTime expires)
   at CefSharp.Cef.SetCookie(String url, String domain, String name, String value, DateTime expires)
```

Any Ideas?

Thanks,
Kyle.

**Comment by amaitland** [comment]
On what thread was `Cef.Initialize` called? Cookies are run on different `Cef Threads`.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Cef.h#L246

Can you try making `Cef.Initialize` and all your cookie calls using the dispatcher?

FYI https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting

**Comment by amaitland** [comment]
@wiscow Any further comment?

**Comment by wiscow** [comment]
Hey @amaitland,  Sorry our team shifted gears.  I was able to test using Dispatcher and I was still getting the same error.  I should be able to look into this a little bit more in the coming days.

**Comment by wiscow** [comment]
@amaitland Wrapping both Cef.Initialize and SetCookie in a Dispatcher action worked in version 39!  Thanks for the help.
