### ISSUE TITLE
Redistribution instructions for creating an installer?

### ISSUE THREAD

**Issue by roschler** [cefsharp/CefSharp#749]
Hello.  A big thanks to the author of this project!  While installing the Nuget package into Visual Studio 2013, I saw a number of "redist" Nuget packages apparently for redistributing a Windows Forms app that uses CefSharp?

Is there a web document or readme that explains which of those "redist" NuGet packages I should install when creating a one-click installer for my users?  If it helps, I use InnoSetup for building my installers?  Also, any instructions on what DLL, LIB, or other files I need to included in the installer payload would be very helpful, including anything I need to know about 64-bit vs. 32-bit.  My target install base will be Windows 8.1 users.

**Comment by jornh** [comment]
See #625 for the current best starting point. For a WinForms app you need the `CefSharp.WinForms` NuGet and follow its dependency chain.  You only need to pick either `x64` or `x86` binaries of the `CefSharp.WinForms`, `CefSharp.Common` and the repackaged `cef.redist` dependency plus .pak resources from `cef.redist`.

**Comment by amaitland** [comment]
Looking a the `nuspec` may prove useful. (As @jornh says, ignore `cef.sdk`)

https://github.com/cefsharp/cef-binary/tree/master/NuGet
https://github.com/cefsharp/CefSharp/tree/master/NuGet

**Comment by amaitland** [comment]
Followup issue is #796
