### ISSUE TITLE
replace text or button in html

### ISSUE THREAD

**Issue by kimtaein1** [cefsharp/CefSharp#750]
I am trying to mimicing chrome translate where certain text is replaced with different text when displayed on the browser. How would i do this?
I see there is GetSource but i don't see SetSource().
I think logical place to do this is before rendering website so for example
```
void PreRender(ref string html)
{
   html.Replace("apple", "...");
}
```

But i am not sure how i can do this.
Thanks!

**Comment by jornh** [comment]
You probably want to do it by injecting JavaScript into the page - see this FAQ item: https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#CallJS

**Comment by amaitland** [comment]
@kimtaein1 Anything more required for this one?

**Comment by kimtaein1** [comment]
nope that nailed it. thanks!
