### ISSUE TITLE
Add Readme.txt to Nuget Packages

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#752]
Add a `Readme.txt` file to the `nuget` packages as per http://docs.nuget.org/docs/creating-packages/creating-and-publishing-a-package

Include 
- Basic troubleshooting info
- The all important `AnyCpu` info
- The close Visual Studio after install if you don't see the references trick
- Links to FAQ, Troubleshooting Guide, Google Group, Github page
- Excerpt from Contributing.md around creating an issue

**Comment by amaitland** [comment]
Anyone else have anything they'd like to add/remove?

**Comment by amaitland** [comment]
Added the basic `Readme.txt` with commit https://github.com/cefsharp/CefSharp/commit/fb3415b5bd29b5198dba8db70d69c11a2fb3b034

Only problem is that it currently only shows the readme when installing the package clean, not when upgrading.

**Comment by amaitland** [comment]
Additions to the readme are most welcome :+1:

**Comment by amaitland** [comment]
Alternatively should we open a Url?

**Comment by jankurianski** [comment]
> Alternatively should we open a Url?

I like your idea here, because a web page is more likely to be read and kept open as a reference while users take their first steps (unlike readme.txt which goes away after installation).  But how would it work?  Can you open a web browser?

**Comment by amaitland** [comment]
I haven't tried it yet, apparently you can use powershell via an install script that runs every time. Looks easy enough to implement. Unsure if it opens a new browser instance, or just a browser inside of `VS`

http://stackoverflow.com/questions/15401521/how-to-open-readme-url-for-nuget-package

**Comment by rassilon** [comment]
The SO answer that says to use $DTE...Navigate would be the VS browser. The "start url" suggestion would launch the default browser outside of VS.

Bill

**Comment by amaitland** [comment]
I think for the `-pre` I'll just keep the `Readme.txt` file. Long term I'd like to change over.

Was more looking for any additional comments on the content https://github.com/cefsharp/CefSharp/blob/master/NuGet/Readme.txt
