### ISSUE TITLE
Feature Request - Add Inspect Element

### ISSUE THREAD

**Issue by kimtaein1** [cefsharp/CefSharp#753]
Hi,
How would i go about adding inspect element feature. I think i need to get mouse position and what element is below the cursor but i am wondering how i would do that. 
I was also going down this route
http://stackoverflow.com/questions/6186065/element-id-on-mouse-over

but it doesn't seem like the right solution as i need to add onmouseover to all controls

**Comment by amaitland** [comment]
The ability to inspect element hasn't been implemented in `CefSharp` yet.

**Comment by kimtaein1** [comment]
is there at least a way to know element id?

**Comment by amaitland** [comment]
You can use the `Dev Tools`.

**Comment by jornh** [comment]
To make it a bit easier @kimtaein1 (or anyone else interested in jumping in on this :smile:) here's a pointer to get started:

On the `cef/2171` branch the CEF API now has a `CefPoint()` parameter at https://github.com/cefsharp/CefSharp/blob/cef/2171/CefSharp.Core/Internals/ClientAdapter.cpp#L31 it can take coordinates for the element to inspect. It need to be exposed in the CefSharp API and for added bonus points :+1: demonstrated in the CefSharp example applications.

Further details in this CEF commit: https://code.google.com/p/chromiumembedded/source/detail?r=1871

**Comment by kimtaein1** [comment]
Thanks jornh,
I wasn't clear on what i was trying to do. I want to add context menu to CEF that i can click and it shows a message box of the element's ID. That is all i want. sorry i confused :)
I found that you can do document.elementAtPoint but i am having hard time getting coordinate point that the script understands. At the moment, i am using javascript to get mouse cursor position but I never get the right element... Is there a way to get mouse cursor location using CEF?

**Comment by kimtaein1** [comment]
To add  more details, i ran this script right after IsLoading becomes false:
@"var mouse = {x: 0, y: 0};

document.addEventListener('mousemove', function(e){ 
    mouse.x = e.clientX || e.pageX; 
    mouse.y = e.clientY || e.pageY 
}, false);"

and then on my right click, i do this:
(function() {{ return  document.elementFromPoint(mouse.x, mouse.y).innerHtml;; }})(); 
In both cases, i call EvaluateScriptAsync and Wait() on the returned task.
"mouse.x, mouse.y" returns some coordinate looking position but document.elementFromPoint always returns null or empty string even when the element does have innerHtml

**Comment by amaitland** [comment]
With `JavaScript Binding` you could populate a bound property on enter (and clear it on leave)?

```javascript
bound.selectedElement = element.id;
```

https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#3-how-do-you-expose-a-net-class-to-javascript

If you have `jQuery` you could use the `hover` method http://api.jquery.com/hover/

Not sure how this will go with a right click context menu, may get in the way of the enter/leave events. It's just an idea.

**Comment by amaitland** [comment]
(If you edit your last comment you'll see I marked up your code blocks for easier reading, makes things a lot clearer)
