### ISSUE TITLE
Calling method from external objects no longer works

### ISSUE THREAD

**Issue by myrnazhou** [cefsharp/CefSharp#754]
After pulling the latest commit from https://github.com/cefsharp/CefSharp/commits/cef/2171, I experience an issue with calling method from external objects. It always throws this exception "Uncaught Error: Object reference not set to an instance of an object."

I'm using the CefSharp for Wpf. I can easily replicate it. I modified the cef example project. I registered an object when the webcontrol was initialized. I added a dummy method, so it's basically empty method. Then I tried to call the method from the "Execute Javascript (synchronously)" textbox. And it shows the error.
Do any of you guys encounter the same issue?

**Comment by amaitland** [comment]
> I can easily replicate it. I modified the cef example project.

Can you push your example to `GitHub` please.

**Comment by myrnazhou** [comment]
I pushed to here https://github.com/Bodekaer/CefSharp/tree/RegisterJsObjectTest

**Comment by myrnazhou** [comment]
I also made small screencast here http://screencast.com/t/cKFHCUknJ

**Comment by amaitland** [comment]
> I pushed to here https://github.com/Bodekaer/CefSharp/tree/RegisterJsObjectTest

Thanks!

Functions with no return value weren't being handled correctly. Commit https://github.com/cefsharp/CefSharp/commit/bf4983b52d37549c5ba0c5718203b520ac3605c7 should fix that.

**Comment by myrnazhou** [comment]
Ok thanks, that fixes the issue
