### ISSUE TITLE
Misplaced Select Options in WPF on Windows Tablet with Win 8

### ISSUE THREAD

**Issue by ischas** [cefsharp/CefSharp#755]
- **What is the expected output?**

The options should appear next to the select box.

(Example image taken from the MinimalExample with WinForms with proper behavior)
![wf](https://cloud.githubusercontent.com/assets/8558126/5798741/caea455a-9fca-11e4-9846-d836ee1467d6.png)

- **What do you see instead?**

The options appear misplaced.

![wpf](https://cloud.githubusercontent.com/assets/8558126/5798742/caea70d4-9fca-11e4-98d2-5e49406e8086.png)

- **What steps will reproduce the problem?**

I navigated to a page with a select box (verified with .NET ASPX and .NET MVC5 web pages). The first time the options will be placed well, but from the second click on any select the options were misplaced. **The misplacement applies only on the visualization of the options, the click area is still at the right place underneath or above the select box.**

- **What version of the product are you using? On what operating system? x86 or x64?**
- **What version are you using?**

The behavior occured with Nuget versions 33, 37 and 39pre of the WPF package. I always compiled for x86.

I was able to reproduce this behavior on two different Windows 8 Tablets with **Intel Atom** processor. No problems appeared with Win7 or Windows 8 desktops (Intel Core i3 and i5) and Win8 Tablet (i5).

Sorry for the disguise of most parts of the screenshots, but the data is confidential and I wouldn't be able to post any screenshots without it.

**Comment by amaitland** [comment]
@ischas Excellent bug report :+1: What `DPI` are the tablets running? Are they both the same?

I'm not really sure how to go about investigating this without being able to reproduce the issue, any thoughts?

**Comment by jankurianski** [comment]
@ischas Does this problem occur with all select boxes?  Can you try this select box your tablet: http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select

If a normal select box does work, but yours does not, could you make a http://jsfiddle.net/ that reproduces the problem select box `HTML` and `CSS`?

**Comment by ischas** [comment]
@amaitland The first tablet is an **Acer Iconia W4-821**, resolution of 1280x800 and a display size of 8", which corresponds to a resolution of about 200 dpi. The Windows dpi scale is set to 125%, but I tested 100% as well. The CPU is an **Intel Atom Z3740**.

The second tablet was a **Dell Latitude 10**, which has a resolution of 1366x768, so it's dpi is round about 150. It has an **Intel Atom Z2760 CPU**.

@jankurianski I was able to reproduce the problem with the w3schools exampe, so no JSFiddle is needed. If it is of interest: Chrome doesn't show this behavior.
![w3c](https://cloud.githubusercontent.com/assets/8558126/5815196/c70946f6-a093-11e4-976f-5d93c6bfb850.png)

**Comment by amaitland** [comment]
@ischas Can you try disable `DPI` scaling if it's enabled?

http://en.kioskea.net/faq/32589-windows-8-1-disable-display-scaling-on-high-dpi-settings

**Comment by ischas** [comment]
@amaitland Neither this nor the "Run in 640 x 480 screen resolution"-option changes the behavior of the select box.

**Comment by amaitland** [comment]
Ok, was worth a go.

So any thoughts on how to reproduce the problem?

**Comment by ischas** [comment]
The easiest way is to get you a Windows tablet with Atom processor (if that is the bad factor). ;-)

I'm not sure if I can install a current version of Visual Studio on the mentioned device (it's not mine). I know there is a legacy version (I think it's 2008), which is needed by my boss, so I think there is no chance to compile for .NET 4.x.

If I'm able to debug the program, maybe you have to give me advice where to look for. Nevertheless, I'm on a business trip and won't be in office until next week.

**Comment by jornh** [comment]
@ischas (for when you get back in the office :smile:) does the error reproduce with `cefclient.exe` in "OSR" mode on the given hardware? See https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

**Comment by murakami1028** [comment]
I detected a issue similar to previous #378 .

**Comment by ischas** [comment]
@jornh Okay, I've started cefclient from the command line with the given parameters and checked the w3schools-page. The select box works as intended.

**Comment by ischas** [comment]
A colleague was able to test the issue on a Surface Pro 3 and the misplacement occured as well. So we can eliminate the Atom processor as cause of the problem.

**Comment by amaitland** [comment]
When I have a spare few minutes I'll try on my `Surface Pro 1`.

**Comment by amaitland** [comment]
Hopefully #916 Fixes this

@ischas Any chance you can take that `PR` for a spin?

**Comment by amaitland** [comment]
#916 has been merged
