### ISSUE TITLE
default parameters when calling from JS

### ISSUE THREAD

**Issue by ray007** [cefsharp/CefSharp#757]
in my bound object in C# I have a method
```public void showPage(string page, string title = null)```

In CefSharp1 calling this method from JS with just 1 parameter worked fine, with CefSharp3 it produces an exception.

**Comment by ray007** [comment]
another maybe related problem:

calling a C# method with a JS-Object as parameter always worked with the parameter on the C# side being `Dictionary<string, object> o`, now I'm getting a PipeException...

**Comment by jornh** [comment]
What exact CefSharp version are you using? Nuget? CI Nuget? If source build, then commit SHA or date? from a branch? If so which branch?

https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue

**Comment by amaitland** [comment]
> another maybe related problem:
> 
> calling a C# method with a JS-Object as parameter always worked with the parameter on the C# side being Dictionary<string, object> o, now I'm getting a PipeException...

Unrelated. That's been fixed in `master` and will be included in the next `39.0.0-pre02` release.

**Comment by amaitland** [comment]
Support for optional params added 

https://github.com/cefsharp/CefSharp/commit/953d9172263424ccd34ebcdf370b50e87cdc5fb1

You can try our the latest `CI` build using `MyGet` see #617

**Comment by ray007** [comment]
Thanks for all the answers, and I'm using current NuGet stable.

**Comment by jornh** [comment]
Thanks! :smile: Are you able to help verify if 953d917 == 39.0.0-CI643 or later from our MyGet feed (according to https://ci.appveyor.com/project/cefsharp/cefsharp/history) resolves both your issues?

**Comment by ray007** [comment]
I'll try to test it once manage to take care of my other troubles.
I assume/hope the latest NuGet beta contains this commit?

**Comment by jornh** [comment]
Yes it does. It's even been push to official NuGet as a `39.0.0-pre02`
which we encourage everyone to take for a spin.

We will focus on merging PRs already in by now - and new critical bug
fixes - leading up to the final `39.0.0`. So now is a good time to test!

**Comment by ray007** [comment]
Yes, the current NuGet snapshot helps with my 2 problems, thank you.

Just for information, I've observed another change in behavior:
Elements under css `transform: scale3d(1,1,0);` were previously visible, now they aren't, unless I modify the last argument to a value != 0.

Still investigating my last problem where the BrowserSubprocess doesn't always start as expected...

**Comment by jornh** [comment]
> Elements under css `transform: scale3d(1,1,0);` were previously visible, now they aren't, unless I modify the last argument to a value != 0.

My Google Chrome `39` browser behaves exactly the same. Just tried it out at the 2nd example link
 at http://w3.eleqtriq.com/2010/05/understanding-css-3d-transforms/ 

Note, I had to go into the WebConsole to set the scaling factors to < 0.5 ... but if I do that with any of the three dimensions X, Y, Z it collapses. I think that's what you would expect. What happens if you multiply something by `0`. I suspect it worked before because there might have been an error in the Chromium CSS 3D implementation used in CefSharp 1

![understanding css 3d transforms 1 eleqtriq - google chrome](https://cloud.githubusercontent.com/assets/766423/5878834/1dee1f6c-a32a-11e4-9764-c944e5395d97.jpg)

**Comment by jornh** [comment]
> Yes, the current NuGet snapshot helps with my 2 problems, thank you.

Cool thanks for testing :+1: Hope you agree to close this issue then.

**Comment by jornh** [comment]
Regarding difference in handling the Z dimension = 0 in `scale3d` I just tested on my iPad. It behaves the same as CefSharp1 and it's running WebKit as rendering. Apparently [Blink was introduced in Chromium 28](http://www.omgchrome.com/blink-arrives-in-chrome-stable-28/) so it could explain the difference.

**Comment by ray007** [comment]
Hmm, the issue with `scale3d` sounds to me like a bug in Chrome 39 - something time 0 is hopefully always 0.
IIRC it was done that way because I read it was required so the browser could do the scaling with hardware accereration...
