### ISSUE TITLE
PipeException  when try accesing to closing tab. Winforms

### ISSUE THREAD

**Issue by Dr-MLJC** [cefsharp/CefSharp#760]
When i try to close tab with cef ,which javascript. its rise a pipeException. How to verify ready state of cef to javascript execute?
p.s. way to reproduce- just add 
```
private void test()
        {
            if(browserTabControl.TabPages.Count>1)
            {
                var tabPage = browserTabControl.Controls[1];
                var control = (BrowserTabUserControl)tabPage.Controls[0];
                Task testme = new Task(() => {while(true){ control.ExecuteScript("console.log('mesript')"); }});
            }
        } 
```
in BrowserForm.cs, then just call test() after AddTab function.

**Comment by jornh** [comment]
The `FrameLoadEnd` event:
* API https://github.com/cefsharp/CefSharp/blob/v39.0.0-pre02/CefSharp/IWebBrowser.cs#L36
* Example usage https://github.com/cefsharp/CefSharp/blob/v37.0.0-pre02/CefSharp.OffScreen.Example/Program.cs

**Comment by amaitland** [comment]
Looping endlessly without some sort of checking is always going to cause problems. Need to rethink your design.

**Comment by amaitland** [comment]
@Dr-MLJC Any follow up on this?

**Comment by amaitland** [comment]
Closing due to lack of feedback.
