### ISSUE TITLE
Any support/doc for using Selenium?

### ISSUE THREAD

**Issue by kimtaein1** [cefsharp/CefSharp#761]
I should ask first if this is even supported?
If yes, is there any examples or some pointers i can start form?

**Comment by amaitland** [comment]
> If yes, is there any examples or some pointers i can start form?

That relate directly to `CefSharp` not that I'm aware of. Remembering that `CefSharp` is just a wrapper around `CEF3` then you may be in luck https://code.google.com/p/chromiumembedded/issues/detail?id=549

It's likely to take a fair bit of digging, probably compiling from source and getting the debugger out, so I wouldn't recommend it unless **your** prepared to do the hard yards :+1:

**Comment by amaitland** [comment]
@kimtaein1 Did you make any progress with this?

**Comment by jornh** [comment]
There is now this tutorial in the CEF project: https://code.google.com/p/chromiumembedded/wiki/UsingChromeDriver

@kimtaein1 does it answer your question?

**Comment by jornh** [comment]
No response from OP assuming resolved by above CEF info.
