### ISSUE TITLE
Documentation - Request for Help

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#762]
With the official release of version `39.0.0` approaching fast it would be great to give the documentation an overhaul. 

Primarily this wold involve:
- Giving the `Wiki` an overhaul/restructure/adding some additional examples
- Adding a `Readme.txt` to the nuget package see #752 

Please consider taking the time to help out, multiple volunteers would be so greatly appreciated! :+1:

**Comment by Andorbal** [comment]
I've been going through the Getting Started page of the wiki fixing simple spelling and grammar issues. I'd be interested in doing a more thorough review of the grammar, but didn't want to just start changing large sections of the wiki without asking if that's something you'd want done. I don't know the library well enough to feel comfortable adding or removing content (I've only been using it a few weeks), but I'd be happy to clean up the content that is already there.

If you'd like, I can work on a few paragraphs so you can see the sorts of changes I'm talking about.

Thanks for the great work, by the way!

**Comment by amaitland** [comment]
> I don't know the library well enough to feel comfortable adding or removing content (I've only been using it a few weeks), but I'd be happy to clean up the content that is already there.

By all means 👍 You can refer back to the [CEF General Usage Guide](https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage.md) if need be.

> If you'd like, I can work on a few paragraphs so you can see the sorts of changes I'm talking about.

Long as the technical details are accurate you can rewrite the whole thing if you like 😄 I've paid no attention to spelling or grammar, just the technical detail. If you'd like to add a new section or two then there is a rough outline for a few different ones in the comments of https://gist.github.com/amaitland/aa976285407ba35cf895c67c614ba82c
