### ISSUE TITLE
InspectorFrontEnd is not defined?

### ISSUE THREAD

**Issue by roschler** [cefsharp/CefSharp#764]
Hello,

I have the CefSharp browser control working well in my app.  However, when I try to show the Dev Tools, I get the error message "InspectorFrontEndAPI is not defined".  How can I fix this?

Interesting anecdote.  The web page I have shown in the CefSharp browser control is a computationally intensive Three.js 3D model.  It actually renders noticeably smoother when in the CefSharp browser control than in the Chrome browser itself.

Robert.

**Comment by jankurianski** [comment]
Hi Robert, could you post using this issue template:  https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue

This will allow others to help you with your problem much more easily.  In particular for this problem, it is hard to understand the source of the error message (C# exception, stdout, browser console message, debug.log, etc.).

**Comment by roschler** [comment]
@jankurianski ,

Thanks for the link.  I'll use that template and repost.

**Comment by roschler** [comment]
I found the problem.  Question #4 in the FAQ says to disable PackLoading to make sure that CefSharp.dll loads properly.  Unfortunately, at least if you are using the CefSharp source code instead of the NuGet package, this disables the dev tools as a side effect.  I removed the code that did that so pack loading is *enabled* (PackLoadingDisabled is FALSE by default), and I've go the dev tools now and *I don't have any problems loading CefSharp.dll".  It appears that disabling pack loading leaves the local_file_path variable in the CefSharp.BrowserSubProcess DLL(s) "empty", and then the browser subprocess process can't load the dev tools.  I don't have time to see if this happens when you are using the NuGet package instead of the source code.  But I'm leaving this answer in case it helps others.

Note:. The CefSharp.Example.WinForms project does *not* disable pack loading either.

**Comment by jornh** [comment]
@jankurianski @amaitland (others?) is it maybe time to ditch the FAQ - and example code mention of `DisablePackLoading` ... I think it does more harm than good for us with `cef.redist.*` NuGets taking care of upstream dependencies.

**Comment by roschler** [comment]
@jornh - I know your reply isn't meant for me, but I think the FAQ is very useful.  This was an odd context that happened to me because first I started with the Nuget package, followed the FAQ, switch to the source, and ended up in a odd place.  For what happened to me, the best change if anyone sees fit is to have an Exception trap in the interface DLL that looks to see if the Exception occurred while trying to load the Dev tools, and add a note to the message warning the dev to check if PackLoadingDisabled is TRUE if they are using the source since that will disable the dev tools.  It's a very peculiar context.

**Comment by jornh** [comment]
> It's a very peculiar context.

@roschler yep, I know (and by all means **do** comment, the more qualified comments the merrier). Adding the exception might be a cool thing to add, if we get something useful we can catch over from the unmanaged CEF side. 

What I was thinking was merely to simplify our default for most people - with "batteries included"  + extra cheese even - and maybe point to something like #527 in the FAQfor those who need to lean it down

**Comment by amaitland** [comment]
> @jankurianski @amaitland (others?) is it maybe time to ditch the FAQ - and example code mention of DisablePackLoading ... I think it does more harm than good for us with cef.redist.* NuGets taking care of upstream dependencies.

@jornh I'm all for simplifying the `FAQ`, I don't think `DisablePackLoading = true` is a valid debugging step anymore. I can't remember the issue exactly though I do remember a case where some of the pack files were required for basic scroll bars, and they're also needed for PDF support.

**Comment by amaitland** [comment]
> For what happened to me, the best change if anyone sees fit is to have an Exception trap in the interface DLL that looks to see if the Exception occurred while trying to load the Dev tools, and add a note to the message warning the dev to check if PackLoadingDisabled is TRUE if they are using the source since that will disable the dev tools. It's a very peculiar context.

@roschler I don't believe there's an exception throw generally when you open `DevTool` when pack loading is disabled. You could check if the setting and manually throw an exception. Contributions are most welcome :+1:
