### ISSUE TITLE
High Contrast doesn't work

### ISSUE THREAD

**Issue by ltsz16** [cefsharp/CefSharp#766]
When you set high contrast mode in Windows nothing happens with web pages displayed with CEFSharp winforms browser.

**Comment by jornh** [comment]
Please check if it's a CEF or CefSharp only issue, see https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

**Comment by ltsz16** [comment]
Ok,  I checked.  It is a problem with chromium but in Chrome they handle it but allowing the functionality via extensions.  Does CEFSharp support Google extensions?  If not then it is simply an issue in Chromium without a fix otherwise it should be documented how to utilize Google extensions for this ACC functionality.

**Comment by jornh** [comment]
No Chrome extensions are only supported by Chrome. Neither Chromium -> CEF -> any CEF language binding, like CefSharp supports it.

Closing as a new `faq-able!` item. I assume you agree :smile:

**Comment by ltsz16** [comment]
Yes.  Thank you.
