### ISSUE TITLE
weired behavior with right to left browser control

### ISSUE THREAD

**Issue by MajedDH** [cefsharp/CefSharp#770]
I'm using CEF Sharp 37 with WPF and the browser control have `FlowDirection="RightToLeft"` property. when i run the app  ,  the browser control responses to the mouse as the browser is horizontal flipped. the rendering is all right with no problems but the problem is with the mouse . when i press some where in the right half of the screen  the left half takes the input.   

sorry for my bad English

**Comment by amaitland** [comment]
> browser control have FlowDirection="RightToLeft" property

Are you saying your applying `FlowDirection` directly to the `<ChromiumWebBrowser/>` element?

Can you provide a code snippet please. Preferably as a `Gist`.

**Comment by MajedDH** [comment]
OK this is the `Gist` :
https://gist.github.com/MajedDH/52e2ad688bf80920431d

**Comment by amaitland** [comment]
Have you tried wrapping the browser in an element with `FlowDirection="LeftToRight"`. 

What are you trying to achieve? Code snippet is a little vague.

**Comment by MajedDH** [comment]
actually i solved the problem by setting `FlowDirection="LeftToRight"` on the browser element directly.
this problem happens only when browser element inherits `RightToLeft` .

**Comment by amaitland** [comment]
@MajedDH Glad to hear you got this sorted :+1:

**Comment by FWennerdahl** [comment]
Ran into this issue as well. Setting FlowDirection="RightToLeft" on a containing element caused mouse events (not just click but also movement) to be inverted on the X-axis in the browser. As mentioned above this is resolved by overriding FlowDirection on the browser element with "LeftToRight" but the behaviour was unexpected.

**Comment by amaitland** [comment]
If you can find a way to hard code the flow direction the please submit a `PR` :+1:
