### ISSUE TITLE
fire native keyboard events in offscreen browser

### ISSUE THREAD

**Issue by alexeyk777** [cefsharp/CefSharp#772]
Hello! Subj. Is it possible to fire Native keyboard events? Like enter some text , press Enter etc.
Not using js simulate.
Thanks!

**Comment by amaitland** [comment]
Hi @alexeyk777 

The `OffScreen` browser is relatively new compared to the `WPF` and `WinForms` versions and as such only fairly basic features have been implemented to date.

Whilst technically possibly, neither sending `Key Events` or `Mouse Events` have been implemented.

The `Cef` framework provides such events, they're  just not exposed in the `OffScreen` version.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/ManagedCefBrowserAdapter.h#L178
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/ManagedCefBrowserAdapter.h#L304
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/ManagedCefBrowserAdapter.h#L325
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/ManagedCefBrowserAdapter.h#L340

The relevant functions are used in the `WPF` version and could be used as a reference should you be interested in creating a PR that implements the features your after?

**Comment by alexeyk777** [comment]
Thanks for an answer. So I will implement this functions in Offscreen mode using WPF version as reference. Then I will make push request to add it in master branch! Regards!
