### ISSUE TITLE
Native drag & drop on mousedown w/ CEFSharp for Win forms

### ISSUE THREAD

**Issue by ashkandaie** [cefsharp/CefSharp#773]
I am trying to switch over fmor embedded IE control to CEF Sharp.

We have a legacy application that we drag & drop to which requires custom clipboard formats.

The way I have implemented is by registering a custom js object and implementing native drag & drop.

    public class TestObject
    {
        private readonly ChromiumWebBrowser browser;

        public TestObject(ChromiumWebBrowser browser)
        {
            this.browser = browser;
            this.container = container;
        }

        public void StartDragDrop(string data)
        {
            Console.WriteLine("Start Drag & Drop");
            browser.DoDragDrop(data, DragDropEffects.Copy | DragDropEffects.Link);
            Console.WriteLine("End Drag & Drop");
        }

        public void ClearConsole()
        {
            Console.Clear();
        }
    }

browser.DoDragDrop is a blocking function. 

The problem is that sometimes this works. But the majority of the time, the DoDragDrop function returns immediately.

All of this works fine in embedded IE when using the exact same approach & ObjectForScripting. I really don't want the headache of supporting multiple IE versions.

Is there a better way to achieve the same results using CEFSharp?

Am I doing something wrong? 

Your help is greatly appreciated and keep up the good work.

**Comment by ashkandaie** [comment]
I think I figured it out.

Read up some more on CEF and seems like the DroDragDrop has to happen on the UI thread.

Would still love to see if tehre are better ways to do what I am trying to do.

**Comment by ashkandaie** [comment]
I spoke too soon. 

It does work better when running the DoDragDrop in the UI thread but not 100% of the time. And it crashes the process sometimes.

**Comment by amaitland** [comment]
There are a number of drag methods in the `Cef API` which haven't been exposed as yet.

There's an unmerged PR #756 that implements those features in the context of the `WPF` control. Might be worth having a look there for some clues.

**Comment by rassilon** [comment]
The CEF code LOOKS like it might only support it in OSR mode. The code only checks `IsWindowless()`. I just couldn't dig out the place where that's done to determine if WinForms driven rendering `IsWindowless()` returns what CEF's `OnDragEnter` named equivalent is in (IIRC, `CefBrowserHostImpl` or something similar.

Bill
