### ISSUE TITLE
Geolocation - Google API key

### ISSUE THREAD

**Issue by khoaakt** [cefsharp/CefSharp#775]
where i can put the google api key for geolocation handler?

**Comment by jornh** [comment]
Does https://github.com/cefsharp/CefSharp/blob/0f23b663a28463a6807eeb4b8f6cec41588fa85f/CefSharp.Example/CefExample.cs#L18-L21 in the `CefSharp.Example` dir and the **Providing Keys at Runtime** paragraph in http://www.chromium.org/developers/how-tos/api-keys help?

**Comment by jornh** [comment]
@khoaakt did that resolve your question? If it did then please confirm by closing the issue :+1:
