### ISSUE TITLE
Bug: Flash is completely transparent when no HTML background color is defined and wmode=transparent

### ISSUE THREAD

**Issue by mtinnes** [cefsharp/CefSharp#776]
#### Issue Summary
What is the expected output?
Opaque flash content should remain visible when HTML background color is defined as 'transparent' and the Flash wmode property is set to 'transparent'. Only the transparent regions of the Flash content should be remain as transparent through to the underlying control.

What do you see instead?
Nothing, entire Flash area is rendered transparent. Its as if the Flash content is being merged with the HTML page background and since the HTML background color is transparent - the Flash too is rendered as transparent. This is also demonstrated by setting HTML background to 50% alpha which renders the Flash at 50% alpha as well. The Flash renders fine when an HTML background color is defined.

#### Steps to Reproduce
1. Create HTML page with transparent background and a Flash object utilizing transparent regions.
2. Sample GIST: https://gist.github.com/mtinnes/0083dfa1b178bfd216d6

#### Technical details
CefSharp-39.0.0-pre02
cef.redist.x86 3.2171.1972
Win7 x64
WPF

**Comment by jankurianski** [comment]
Can you try running the `cefclient.exe` program with WPF parameters (instructions on that here: https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef)?

This will help figure out if it is a problem in CefSharp or CEF.

**Comment by mtinnes** [comment]
Thanks, running cefclient in both WPF and WinForms modes renders fine. I've attached both the cefclient and my CefSharp WPF app properties.

cefclient:

CEF	3.2271.2001
Chromium	41.0.2271.0
OS	Windows
WebKit	537.36
JavaScript	3.32.7
Flash	16,0,0,296
User Agent	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2271.0 Safari/537.36
Command Line	cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --lang=en-US
Module Path	E:\Users\Mike\Downloads\cef_binary_3.2271.2001_windows32_client\Release\libcef.dll
Cache Path	C:\Users\Mike\AppData\Local\Temp\scoped_dir22044_10419

CefSharp.Wpf.Example - x86

CEF	3.2171.1972
Chromium	39.0.2171.95
OS	Windows
WebKit	537.36
JavaScript	3.29.88.17
Flash	16,0,0,296
User Agent	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36
Command Line	"E:\Users\Mike\Documents\Visual Studio 2013\3rd Party\CefSharp-39.0.0-pre02\CefSharp.Wpf.Example\bin\x86\Release\CefSharp.Wpf.Example.vshost.exe" --browser-subprocess-path=CefSharp.BrowserSubprocess.exe --no-sandbox --lang=en-US --log-severity=verbose --touch-events=enabled
Module Path	E:\Users\Mike\Documents\Visual Studio 2013\3rd Party\CefSharp-39.0.0-pre02\CefSharp.Wpf.Example\bin\x86\Release\libcef.dll
Cache Path	C:\Users\Mike\AppData\Local\Temp\scoped_dir19008_14935

**Comment by amaitland** [comment]
@mtinnes Can you compare the same versions? Potentially something has changed in Chromium.

**Comment by mtinnes** [comment]
tests equally well with identical chromium version:

CEF	3.2171.1979
Chromium	39.0.2171.95
OS	Windows
WebKit	537.36
JavaScript	3.29.88.17
Flash	16,0,0,296
User Agent	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36
Command Line	cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --lang=en-US
Module Path	E:\Users\Mike\Downloads\cef_binary_3.2171.1979_windows32_client\Release\libcef.dll
Cache Path	C:\Users\Mike\AppData\Local\Temp\scoped_dir27920_20378
