### ISSUE TITLE
javascript confirm dialog rendering problem on windows 7 64bit - CefSharp 39.0.0.0 (winforms 64bit)

### ISSUE THREAD

**Issue by fsimon21** [cefsharp/CefSharp#777]
hello,
I have a problem with the confirm dialog in javascript .
With active the Aero effects on windows you cans see the dialog correctly with the buttons :
![ok](https://cloud.githubusercontent.com/assets/9480493/5961667/9a38ab92-a7de-11e4-80aa-3ff42ca0530f.jpg)

While disabling Aero looks like this dialog without buttons
![ko](https://cloud.githubusercontent.com/assets/9480493/5961674/ac9e35ea-a7de-11e4-9777-b25d56c88e7c.jpg)

thanks for help!

**Comment by amaitland** [comment]
I'd say this is an `Upstream` issue, can you confirm by comparing with `cefclient`, more details here https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

**Comment by fsimon21** [comment]
same problem with the cefclient,so i've changed to windows 8.1 and everything works right, i can see that everything works better than on windows 7

**Comment by jornh** [comment]
Thanks for verifying :smile:  - flagged as upstream

> so i've changed to windows 8.1 and everything works right, i can see that everything works better than on windows 7

 ... And good observation that it's a Win7 only issue - worth updating the subject above?

**Comment by fsimon21** [comment]
updated ;-)

**Comment by rassilon** [comment]
This can be worked around though. IJSDialogHandler lets you supply your own dialogs for this UI.

CefSharp doesn't currently expose the current API shape though.

CEF's default JsDialog implementation (among other things) has a fixed size Win32 dialog that is displayed.

Bill

**Comment by rassilon** [comment]
Oh, ick. `IJsDialogHandler` doesn't map the API properly at all. :frowning:

`IJsDialogHandler` fails to deal with:
* Allowing the `IJsDialogHandler` implementation to create a non-modal UI:
   - Once the handler returns the C++ wrapper in ClientAdapter auto completes the callback.
* `accept_lang` isn't passed through
* `suppress_message` isn't passed through

Bill

**Comment by rassilon** [comment]
I'm not sure how important not being able to create a non-modal UI is though.
Thoughts?

Bill

**Comment by amaitland** [comment]
Most of the `JS Dialog` code is left over from `CefSharp1`, overall it could use a rework. Ideally we'd come up with a general strategy for exposing the async callbacks. I think the `Action` approach used by `SchemeHandler` is a little clunky.

Were you looking to rewrite the public `API`?

**Comment by rassilon** [comment]
Not particularly per-say, but CEF's default JS dialog could really use being replaced by a better CefSharp DefaultJsDialogHandler. Might as well update the API as we go.

Bill

**Comment by rassilon** [comment]
i.e. i'm very less concerned about creating a non-modal UI and thus we could in theory keep the callback in the C++ layer.

Bill

**Comment by amaitland** [comment]
Historically most handlers do not to provide default implementations, I guess that could change.

Anything that dramatically changes the `API` would need to be done before releasing `39`, otherwise I think it will have to wait until `41`

**Comment by rassilon** [comment]
Replacing the default Ui is easier to do in CefSharp than in CEF. :smile:

I think that the `API` should be changed now, and then we can worry about the actual replacement later.

Bill

**Comment by amaitland** [comment]
> I think that the API should be changed now, and then we can worry about the actual replacement later

If you have the time, by all means :+1:

**Comment by rassilon** [comment]
Updated issue 760 in CEF with before/after pictures from Win7 and a patch to fix the Win7 issue you were seeing above.

**Comment by rassilon** [comment]
The fix for issue 760 upstream has been committed to branches 2171 and later.
Just need to wait for cefbuilds.com now. 

Fyi,
Bill

**Comment by rassilon** [comment]
(to be clear, the upstream fix deals with the button issue and not the clipped text)

**Comment by amaitland** [comment]
If they don't show up in a few days it might be worth asking on `ceforum`, strange the `Windows` builds are behind the others.

**Comment by rassilon** [comment]
Wow. cefbuilds.com still hasn't updated the Windows builds. Ugh.

Bill

**Comment by rassilon** [comment]
I just asked on the CEF forum.

Bill

**Comment by avspeed** [comment]
One more reason to build these ourselves ;)

**Comment by amaitland** [comment]
> Wow. cefbuilds.com still hasn't updated the Windows builds. Ugh.

I think it's related to the switch from google code to bitbucket. Imagine that's messed up a few things.

> One more reason to build these ourselves ;)

The number of hours a build takes is a little prohibitive. Takes between 5-10mins to repackage a build, so we'll keep doing that for now.

**Comment by rassilon** [comment]
@amaitland , How would I go about packaging a build? Building CEF 2171 shouldn't take me too long as I've got an enlistment already. I do only have VS 2013 Update 4 installed atm since that's what trunk CEF/Chromium require (and VS2012 and VS2010 just currently aren't on that machine, which could be fixed)

Bill

**Comment by rassilon** [comment]
Apparently, cefbuilds.com also lags for Windows builds against trunk as well. *sigh*

Bill

**Comment by amaitland** [comment]
I wrote someone basic the other day for how it works when downloading from `cefbuilds.com` see https://github.com/cefsharp/cef-binary/wiki. Will have to be adapted slightly of course.

@avspeed Kindly wrote https://github.com/cefsharp/cef-binary/wiki/Building-Cef-from-source which may also be useful.

We only build for `VS2012` and `VS2013`, so no need for `VS2010`.

**Comment by amaitland** [comment]
@fsimon21 Any chance you can try `master`? Thanks to @rassilon this should now be resolved.

**Comment by fsimon21** [comment]
hi,
thanks for having solved this problem, but all our systems now are upgraded to windows 8.1, so i can't try at this moment.
i will give you an answer as soon as possible, but i can close this post trusting in your good job ;-)
