### ISSUE TITLE
Crash with Https Referer on 37.0.0, varying results on 39.0.0

### ISSUE THREAD

**Issue by noone2407** [cefsharp/CefSharp#778]
I try to add the referrer header to the request.
I am using WinForms and x86 version on window 7 64 bit
 
this is the code

```csharp
      public bool OnBeforeResourceLoad(IWebBrowser browser, IRequest request, IResponse response)
        {
string Referer ="some url";
                var newHeader = request.Headers;
                bool contain = false;
                var keys = request.Headers.Keys.GetEnumerator();
                while (keys.MoveNext())
                {
                    if (keys.Current.Equals("Referer"))
                    {
                        contain = true;
                    }
                }
                if (contain)
                    newHeader.Set("Referer", Referer);
                else
                    newHeader.Add("Referer", Referer);
                request.Headers = newHeader;
            return false;
        }
```

I tested with the version on nuget (37.0.0) and it crashes, but when I test the latest version on github (39.0.0) it does not crash but the referrer header remains empty. It only happens with url starts with https
![right](https://cloud.githubusercontent.com/assets/5617222/5987375/5f5e906a-a958-11e4-9986-badad642a349.PNG)
![wrong referer](https://cloud.githubusercontent.com/assets/5617222/5987376/5f898aa4-a958-11e4-80f6-b58eb8346299.PNG)

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue

**Comment by noone2407** [comment]
I have updated more specific information  and screenshots

**Comment by jornh** [comment]
@noone2407 thanks for the extra info. It gave a much better starting point :+1: and a few hints on 

My testing is done with current `master` ~ CefSharp `39.0.0-pre02`

I tried with https://www.whatismybrowser.com/developers/what-http-headers-is-my-browser-sending and https://referer.rustybrick.com/ it works with your code added to the CefSharp.WinForms.Example. 

Note for readability I added a bit of `markdown` formatting to your code above. Edit your post and you'll see how.

I tried with a few others:
* http://www.whatismyreferer.com/
* http://www.ericgiguere.com/tools/http-header-viewer.html
* http://pgl.yoyo.org/http/browser-headers.php

Which don't display the `Referer` header reliably. Lesson learned - if your test fails check the tools you use for testing :wink: 

Maybe there is something going on with Chromium not wanting to reveal `Referer` to insecure http hosts in all cases? Specially if `Referer` is a https host ... it would make some sense.

**Comment by noone2407** [comment]
Thank you @jornh

**Comment by amaitland** [comment]
@noone2407 Anything more before we close this?
