### ISSUE TITLE
Does calling a method from Javascript on an exposed C# class trigger a thread switch?

### ISSUE THREAD

**Issue by roschler** [cefsharp/CefSharp#780]
If I call a method on a C# class I've exposed with RegisterJsObject() does that trigger a thread switch due to some marshaling activity?  Or is the C# method executed in the same thread context as the Javascript thread that calls it (the Javascript thread that is running in the embedded Browser instance)?

I'm asking this for execution performance reasons.  If there's a thread switch involved then I don't want to call any C# methods in a tight loop in my Javascript code.  If there is not a thread switch involved, then I will, but please share any other performance considerations that may be useful to know.

**Comment by jornh** [comment]
> If I call a method on a C# class I've exposed with RegisterJsObject() does that trigger a thread switch due to some marshaling activity?

Short answer: Yes

Further background: https://github.com/cefsharp/CefSharp/wiki/Versions and https://code.google.com/p/chromiumembedded/wiki/Architecture#Process_Considerations

**Comment by roschler** [comment]
Thanks, that's exactly what I needed to know.
