### ISSUE TITLE
C# .Net 4.0 Winforms BrowserSettings Return Null Exception.

### ISSUE THREAD

**Issue by daveaton** [cefsharp/CefSharp#781]
Using Master 31 JAN 2015

It seems when you try to set any BrowserSettings they return Null Exeption.

Maybe I am doing it wrong?

Here is how to reproduce the problem.

In BrowserTabUserControl.cs  under line 19 add the following code.

            //try
            browser.BrowserSettings.PluginsDisabled = true;
            //browser.BrowserSettings.LocalStorageDisabled = true;
            //browser.BrowserSettings.JavaDisabled = true;
            //browser.BrowserSettings.DatabasesDisabled = true;

Then try to run the it...

http://www.eatoncode.com/shareit/2015-02-01_0920.swf

Thanks.
David

**Comment by jornh** [comment]
I think it need to be passed in on `new` of the `browser`.Try with:

```csharp
        public BrowserTabUserControl(string url)
        {
            InitializeComponent();

            var browserSettings = new BrowserSettings()
            {
                WebGlDisabled = true,
            };

            var browser = new ChromiumWebBrowser(url)
            {
//                Dock = DockStyle.Fill,
                BrowserSettings = browserSettings
            };

            ... snip ....
```

... and BTW - but completely unrelated -  doesn't look like we need `DockStyle.Fill` any more ...

**Comment by amaitland** [comment]
`BrowserSettings` is `null` by default in `WinForms`, I changed that in `WPF` recently, as its wrapping an `unmanaged` object I'd prefer that it was explicitly disposed. So I've changed that in `WinForms` now. See https://github.com/cefsharp/CefSharp/commit/4405d55221fac5ab002c193b2876318dc59150b7

**Comment by amaitland** [comment]
@daveaton Anything more required before closing?

**Comment by jornh** [comment]
Sweet: 4405d55 :+1: @amaitland :tada:

**Comment by amaitland** [comment]
My change was a little hasty, thankfully there's been a fantastic contribution! 

I've just merged #786

**Comment by rassilon** [comment]
Does CEF even allow you to change the settings after you create the browser? 

If not, I could write up a PR to make BrowserSettings setter more intelligent in this case. i.e. throw new InvalidOperationException() or something with a helpful comment.

Bill

**Comment by amaitland** [comment]
> Does CEF even allow you to change the settings after you create the browser?

The reference to the underlying browser settings is passed to `CEF` when the browser is created, changing the `BrowserSettings` property after `CEF` was initialized would have no effect (You'd effectively lose your reference to the underlying object).

**Comment by daveaton** [comment]
New commits looks great!
