### ISSUE TITLE
Is there an "ignore" attribute for public properties for C# classes exposed to Javascript?

### ISSUE THREAD

**Issue by roschler** [cefsharp/CefSharp#783]
Is there an "ignore" attribute for public properties for C# classes exposed to Javascript, so that the Javascript object evaluation code does not trigger an Exception on them?  

For example:

[Ignore]
prop SomeComplexTypeJSWillNotHandle ComplexProp
{
    get; seet;
}

For now I'm getting around this by substituting any complex C# typed properties with public fields.

BTW, CefSharp is amazing.  Thanks to all of you for your hard work!

**Comment by jornh** [comment]
Searching for "JsBinding attribute" yielded https://github.com/cefsharp/CefSharp/issues/476#issuecomment-60881391 for me

**Comment by jornh** [comment]
... And then https://github.com/cefsharp/CefSharp/search?utf8=%E2%9C%93&q=JavascriptIgnoreAttribute confirms its in the codebase ...

**Comment by roschler** [comment]
Thanks Jornh!

Robert
