### ISSUE TITLE
Creating Extra Tab, Waiting, Closing Tab in Winforms.Example throws null-deref exception

### ISSUE THREAD

**Issue by rassilon** [cefsharp/CefSharp#785]
NOTE: I reproduced this with CefSharp/master and NuGet pulling down whatever it's currently configured to pull down for cef.dll purposes.

The underlying cause is that WinForm's ChromiumWebBrowser::Dispose(bool disposing) method wasn't conditionally disposing BrowserSettings and BrowserTabUserControl in WinForms.Example was disposing the ChromiumWebBrowser twice. 

Once via default WinForm control disposing because the browser was reachable via this.browserPanel.Controls. 

The other was calling the Dispose() method specifically in the ChromiumWebBrowser Dispose event listening function: BrowserTabUserControlDisposed.

This is of course fairly straight forward to fix, but when I went to do so, I noticed that bunch of IDisposable pattern fixes needed to occur as well. PR to follow.

FYI,
Bill

**Comment by amaitland** [comment]
> PR to follow.

Great!

Please make sure you read `Contributing.md` in particular https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#coding-style

**Comment by amaitland** [comment]
Closing with merge of #786
