### ISSUE TITLE
PipeException occured

### ISSUE THREAD

**Issue by ray007** [cefsharp/CefSharp#788]
My program reads the customer data as xml file (served gzip-encoded form server).
When the xml string gets too big (somewhere beyond 50MB), I get the following exception:
```
System.IO.PipeException occurred
  HResult=109
  Message=There was an error reading from the pipe: Unrecognized error 109 (0x6d).
  Source=System.ServiceModel
  ErrorCode=109
  StackTrace:
       at System.ServiceModel.Channels.PipeConnection.OnAsyncReadComplete(Boolean haveResult, Int32 error, Int32 numBytes)
  InnerException=null
  TargetSite={Void OnAsyncReadComplete(Boolean, Int32, Int32)}
```
I had a similar problem earlier with safari on iOS (dependend on size of xml and number of tags), which I worked around by splitting up the big xml string and parsing its constituent parts.
Same workaround works here too, but crashing the communication when trying to parse a big xml string is not nice...

**Comment by amaitland** [comment]
Try catching `OnRenderProcessTerminated`, my guess is that you've crashed the Render Subprocess and the exception your seeing is just a side effect of that.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/RequestHandler.cs#L45

> but crashing the communication when trying to parse a big xml string is not nice...

Your welcome to improve things, this is open source after all :+1:

**Comment by ray007** [comment]
As you expected, the RenderProcess did crash.
I'm just wondering why parsing a long xml string would do that - especially since various versions of google chrome don't have the problem...

**Comment by jornh** [comment]
No need to wonder - Google Chrome  has more engineers - and users - than CEF and CefSharp (even combined :stuck_out_tongue:).

Some suggested next steps: Explore further to isolate using e.g. https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef and maybe `debug.log` which CEF is outputting, or can be configured to output with different error levels.

**Comment by rassilon** [comment]
I'm not sure debug.log is going to say much. The exception suggests it might be related to the JS Binding support in the subprocess. Specifically, one of the IRenderProcess methods in CefRenderProcess.cs. I wouldn't be surprised if you're hitting a WCF transmission limit from the client to the server, or something similar that might trigger an non-handled exception causing the render process to die a horrible death. We'd need a subprocess stack trace to verify of course.

You also didn't mention how your data is flowing through CefSharp, the above paragraph presumes that you've exposed a method to pass the XML as a parameter to a method in your CefSharp hosting application. (and thus using the JS Binding support)

CefSharp devs:
Was there a particular reason CEF's SendProcessMessage or cef_message_router.h wasn't used for the JavaScript bindings? WCF seems kind of interesting when the processes are already communicating via named pipes under the covers inside of CEF/Chormium.

Curious minds,
Bill

**Comment by jornh** [comment]
@rassilon yes good points (better than mine) on the WCF transmission etc. being the possible cause.

The reason WCF was chosen is AFAICT that `SendProcessMessage` wasn't part of the CEF API when the CefSharp 3 implementation started.

**Comment by amaitland** [comment]
@rassilon It would be great to remove `WCF` from the equation, I had considered it though haven't found the time. 

> The reason WCF was chosen is AFAICT that SendProcessMessage wasn't part of the CEF API when the CefSharp 3 implementation started.

Interesting! I had also wondered why `WCF` was used when `CEF` provides it's own `IPC`. Makes sense.

> I'm not sure debug.log is going to say much. The exception suggests it might be related to the JS Binding support in the subprocess. Specifically, one of the IRenderProcess methods in CefRenderProcess.cs. I wouldn't be surprised if you're hitting a WCF transmission limit from the client to the server, or something similar that might trigger an non-handled exception causing the render process to die a horrible death. We'd need a subprocess stack trace to verify of course.

That is a possibly, need more info from OP to verify. Currently `MaxReceivedMessageSize` is `16MB`
https://github.com/cefsharp/CefSharp/blob/master/CefSharp/Internals/BrowserProcessServiceHost.cs#L102

**Comment by ray007** [comment]
WCF transmission limit sounds like a reasonable explanation, we are talking about a string > 50 MB.
I got the same error when reading the data from a file in C# and tried to pass it to JS from there...
OTOH we've had lots of tests with data size in the range between 16 and 50 MB without any problems.

But I'm not sure why it would apply here. The string is loaded with an XMLHttpRequest, does the XML parser pass the data to parse to a different process?

Not sure how to get a stack trace from the subprocess, I'll try to look into it...

**Comment by amaitland** [comment]
> WCF transmission limit sounds like a reasonable explanation, we are talking about a string > 50 MB.

For clarity, are you using javascript binding to transmit this string to or from the browser?

**Comment by ray007** [comment]
I had used the JS bindings to move the data from C# to JS in some cases. But I don't anymore.
The current problem is caused by just calling the XML parser (via jQuery's $.parseXML) on a big input string. And the input string is retrieved with a XMLHttpRequest...

**Comment by amaitland** [comment]
Thanks for the clarification. I think it's likely the render process has crashed for some reason and the `PipeException` is just a side effect. Did you try upping the log verbosity and seeing if `debug.log` has any insights?

**Comment by ray007** [comment]
I always have loglevel=verbose in debug mode, but there's nothing to see in the log.
I also attached the debugger to the renderer process, but it seems to just terminate - at least visual studio doesn't manage to catch an exception...

**Comment by ray007** [comment]
Related question: is there a way to catch the `PipeException` that occurs when the RenderProcess terminates/dies? Or the gpu-Process, though I haven't had a problem with that one so far...

**Comment by ray007** [comment]
Just for the record, I don't think this issue is resolved.

**Comment by amaitland** [comment]
Without more information there isn't much we can do.

**Comment by ray007** [comment]
I agree with that, but closing the issue suggests a solution was found.

While forcing a reload of the webView from `OnRenderProcessTerminated()` works to reduce the severity of the issue, the `PipeException` still does happen occasionally.
Maybe the `WCF MaxRecieveMessageSize` change I saw a few days ago will help here too.

**Comment by amaitland** [comment]
> I agree with that, but closing the issue suggests a solution was found.

2 1/2 months of inactivity on an issue that we can't reproduce gets closed around here...
