### ISSUE TITLE
problem with ExecuteScriptAsync

### ISSUE THREAD

**Issue by capo0** [cefsharp/CefSharp#790]
browser.ExecuteScriptAsync("document.getElementsByClassName(\"ember-view ember-text-area\")[0].value= 'test'");
Thread.Sleep(5000); // this line won't make UI freeze.
browser.ExecuteScriptAsync("document.getElementsByClassName(\"button send-chat-button primary float-right\")[0].click()");

the third line is called but the javascript is not working. But if i put a breakpoint on the third line and i click continue, the javascript will work 

If i put the third line on a button and i click on it, its always work.

and if i do this :
(interval 200)
        private void timer2_Tick(object sender, EventArgs e)
        {
         browser.ExecuteScriptAsync("document.getElementsByClassName(\"button send-chat-button primary float-right\")[0].click()");
        }

its not working but if i click on this button while the timer is running its working

        private void button1_Click(object sender, EventArgs e)
        {

            browser.ExecuteScriptAsync("document.getElementsByClassName(\"button send-chat-button primary float-right\")[0].click()");
   
        }

and something strange if i do this it seem to work :

browser.ExecuteScriptAsync("document.getElementsByClassName(\"ember-view ember-text-area\")[0].value= 'test'");
Thread.Sleep(5000); // this line won't make UI freeze.
browser.ExecuteScriptAsync("document.getElementsByClassName(\"button send-chat-button primary float-right\")[0].click()");
this.WindowState = FormWindowState.Minimized;
this.WindowState = FormWindowState.Maximized

(im using the winform minimal example) cef 37.0.0.0

**Comment by amaitland** [comment]
Try using `EvaluateScriptAsync` and chaining the `Tasks` together, when one is complete, then execute the other.

**Comment by capo0** [comment]
samething happen with EvaluateScriptAsync. its not a executing time problem because as i said above,  i can put the code on a timer that will execute the code after each 5 seconds and the javascript will never be triggered and meanwhile  whennever i click on Button1 on my form, the code will work.

**Comment by amaitland** [comment]
Problem sorted?

**Comment by amaitland** [comment]
(It's handy if you post a followup incase anyone else has the same problem)

**Comment by capo0** [comment]
Yes it was my bad. i was trying to fill a textarea and after to click on the submit button of the page. but the website is verifying if the textarea had the focus, if not the data is not sent

**Comment by amaitland** [comment]
Cool, thanks for the clarification :+1:
