### ISSUE TITLE
Sets the ChromiumWebBrowser initialization ZoomLevel

### ISSUE THREAD

**Issue by az235** [cefsharp/CefSharp#792]
Hi,ALL:
I want ChromiumWebBrowser ZoomLevel effect during initialization, how am I supposed to do? Because the resolution is 2160*1440 Surface Pro 3, and page was blank when it is initialized, I want to solve this problem.
PS: in the HTML page loads and displays the ZoomLevel after operation is taking effect.

**Comment by jornh** [comment]
With WPF or WinForms? 

If it's WPF then see #738 it sounds related to your description. #738 mention some known unresolved upstream CEF issue and also some local workaround.

**Comment by az235** [comment]
I'm using WPF,#738 is not resolved

**Comment by jornh** [comment]
> #738 is not resolved

No exactly, due to the unresolved upstream CEF project issue. 

Can you confirm if your issue is the same/related or something different?

**Comment by az235** [comment]
My problem with 738 issues basically the same, were due to ChromiumWebBrowser currently only supports 1920*1080, and ZoomLevel attributes and problems arising from the need to be modified after the page is displayed again.

Thank you for your patience to answer

**Comment by az235** [comment]
If I need to solve this problem, may I ask, at this stage, do you have any good ways?

**Comment by jornh** [comment]
Well, yes #738 is a pretty long discussion. If you start at https://github.com/cefsharp/CefSharp/issues/738#issuecomment-69965805 you see a few upstream CEF references. The best is of course if you are able to work on contributing a fix to CEF. If that's not possible maybe the workaround the original poster over there (@mookrs) used also works for you?

**Comment by mookrs** [comment]
You can see https://github.com/amaitland/CefSharp/commit/a83e4804f5daabf41fdc7270947482a52a728dfc and https://github.com/amaitland/CefSharp/commit/7c4ef7d9f23b54d93e3ba0b97fe85df4af7f31ba then change https://github.com/bjarteskogoy/CefSharp/commit/d08df3d96a5f3402894cdbe38950c9663a5912b1, compile `CefSharp.Wpf` and get its DLL. This is maybe a temporary solution, although our project remains the HiDPI bug.

**Comment by amaitland** [comment]
Setting the `ZoomLevel` `DependencyProperty` causes problems, in the short term I'm inclined to just expose `SetZoomLevel` on the `WPF` control so users can call it on `FrameLoadStart` until a clean solution can be derived.

**Comment by bjarteskogoy** [comment]
Fixed by this: https://github.com/cefsharp/CefSharp/pull/842

**Comment by amaitland** [comment]
As of `39.0.0` there is a usable workaround. See https://github.com/cefsharp/CefSharp/issues/738#issuecomment-91100299

As there are a number of other issues that represent this topic I'm going to close this one.
