### ISSUE TITLE
Feature Request - Add Support for screen sharing using WebRTC

### ISSUE THREAD

**Issue by murakami1028** [cefsharp/CefSharp#793]
I have tried the WebRTC on CefSharp. I have succeeded to operate the video and audio, but I cannot work screen sharing.
Although it does not work I tried to set the various command line.
Do you have any good information?

--enable-media-stream --enable-usermedia-screen-capturing --allow-http-screen-capture

**Comment by amaitland** [comment]
Whilst `CEF` is based on `Chromium`, it doesn't implement all of it's features. Try searching in relation to `CEF` (Chromium Embedded Framework) to see if it supports the features your after.

**Comment by murakami1028** [comment]
Thank you very much!

**Comment by jornh** [comment]
http://www.magpcss.org/ceforum/search.php?keywords=screen+sharing => http://code.google.com/p/chromiumembedded/issues/detail?id=1065 - :star: it or even better help making a patch in the CEF project.

**Comment by amaitland** [comment]
As google code is shutting down, updating `upstream` link
https://bitbucket.org/chromiumembedded/cef/issue/1065

**Comment by amaitland** [comment]
Closing this as it needs to be fixed in `CEF`, track the progress on the link above.
