### ISSUE TITLE
Does the CefSharp browser instance have full support for the latest WebRTC?

### ISSUE THREAD

**Issue by roschler** [cefsharp/CefSharp#794]
Does the CefSharp browser instance have full support for the latest WebRTC?

https://groups.google.com/forum/#!topic/discuss-webrtc/LuY7zYLA8sA

I tried loading up a WebRTC demo page and got the error:

Sorry. navigator.getUserMedia() is not available

Here's the page I tried.

https://stemkoski.github.io/Three.js/Webcam-Texture.html

Robert

**Comment by jornh** [comment]
Add ` --enable-media-stream` on the command line as mentioned in 2nd post of your first link... and ... :tada: 
![cefsharp winforms example - x64](https://cloud.githubusercontent.com/assets/766423/6085553/1fa89fc8-ae3b-11e4-8826-ea8c01ff93c9.jpg)

**Comment by jornh** [comment]
For further on WebRTC or *almost anything* really, at least in relation to CefSharp do a https://github.com/cefsharp/CefSharp/search?q=webrtc&type=Issues&utf8=%E2%9C%93 (of course replace the search word if you want to know about something else than WebRTC :smile:)

**Comment by roschler** [comment]
Thanks jornh.  Is that you in the picture?  Doesn't look like your avatar.

**Comment by jornh** [comment]
Yes it's entirely possible it could be me :smile:  Funny how much a change of glasses, (facial) hair and another not so conventional camera angle makes a change. 

Anyways, did my answers resolve the issue at hand?

**Comment by roschler** [comment]
Yes it does and thanks again.  Have a great weekend.

**Comment by amaitland** [comment]
I've added the command line option to `CefExample`, https://github.com/cefsharp/CefSharp/commit/572f2bfc7047e41da2c1229a19635e12b279dd66. Starting to keep a list of all the command line options people are using, for future reference. Probably need to add a comment about each one.
