### ISSUE TITLE
FAQ suggestion for those using the Source files instead of the NuGet package with an installer like InnoSetup.

### ISSUE THREAD

**Issue by roschler** [cefsharp/CefSharp#796]
I'm putting this here since it cost me a bit of time.  For those of you using the CefSharp source files instead of the NuGet package, don't forget to include the executable contents of the CefSharp Browser sub-process project or you will get a blank screen when you try to load a web page.  You can double-check if this is your problem by checking your CefSharp log file for the following error:

Failed to launch child process
[0208/221941:ERROR:child_process_launcher.cc(344)]

If you use an installer like InnoSetup like I do, or any other installer where you explicitly choose the files and directories to include in your installation payload, you will need to include the executable contents of the *CefSharp.BrowserSubprocess* project *bin* folder in your installation payload.  You can the necessary files here:

[project home directory]\CefSharp.BrowserSubprocess\bin\x86\Debug

or here in Release mode:

[project home directory]\CefSharp.BrowserSubprocess\bin\x86\Release

In my installer I just copied the contents contents of that folder and had the installer place them in the same directory as the host EXE and everything worked fine.  

I'll say it once again, CefSharp is amazing.  Thanks guys for making it happen.

Robert

**Comment by amaitland** [comment]
@roschler As the Wiki in general is editable by anyone with a github account, your welcome to add your suggestions, I'm sure others will find the information valuable :+1:

**Comment by jankurianski** [comment]
Thanks Robert - I've added the  [`faq-able!`](https://github.com/cefsharp/CefSharp/issues?q=label%3Afaq-able!) label so people can find this in future.  Hope it's fine with you if I close this now.
