### ISSUE TITLE
PPAPI Support

### ISSUE THREAD

**Issue by sebatiandev** [cefsharp/CefSharp#799]
Hi, I have a doubt about CefSharp 37. I am using the Winforms version and I want to know if the PPAPI for flash is enabled by default. In negative case, can I enable it?

Thx!

**Comment by jornh** [comment]
As far as I know it's not quite there yet upstream in CEF (and maybe not even Chromium yet?) 

See e.g. http://www.magpcss.org/ceforum/viewtopic.php?f=7&t=11847 found via a Google on "cef3 ppapi"

**Comment by sebatiandev** [comment]
Thanks for your response jornh!

**Comment by amaitland** [comment]
This was resolved recently https://bitbucket.org/chromiumembedded/cef/issue/1586/add-pepper-flash-plugin-support

It will be a while before there's a build of `CefSharp` that supports this though. 

There are some instructions on how to repackage the latest `CEF` here https://github.com/cefsharp/cef-binary/wiki should you choose to.

**Comment by amaitland** [comment]
`CEF` has created a new branch, this change is in `2357` aka `43`

https://bitbucket.org/chromiumembedded/cef/commits/branch/2357

**Comment by amaitland** [comment]
`master` has been updated, should now support `PPAPI`

**Comment by amaitland** [comment]
I've enabled `PPAPI` by default now see https://github.com/cefsharp/CefSharp/commit/1ca9d90bd841dfb40436ef01e00c191ed64f5c68

It's possible to override this setting if required as it's just appended by default to the command line arguments.

Without this it would appear that no plugins are loaded at all (as `NPAPI` is disabled by default in `2357`)

**Comment by amaitland** [comment]
Tested using `http://www.twitch.tv/` and both the `WinForms` and `WPF` examples appear to be working in `x86` mode.

A `console` window flashes up briefly. This seems to be a known issue see http://magpcss.org/ceforum/viewtopic.php?f=6&t=13094

**Comment by amaitland** [comment]
Instructions for downloading system wide pepper flash can be located at https://bitbucket.org/chromiumembedded/cef/issues/1586/add-pepper-flash-plugin-support#comment-16898332

**Comment by amaitland** [comment]
`Plugin Placeholders` affect flash, see https://bitbucket.org/chromiumembedded/cef/issues/1708/add-support-for-plugin-placeholders-and for command line options for configuring this in versions `45` and above.
