### ISSUE TITLE
CefSharp C# 37 VS 39 WinForm Freezing Issues.

### ISSUE THREAD

**Issue by daveaton** [cefsharp/CefSharp#802]
I am experiencing freezing issues where if the page crashes it does not recover like it does in v37.

It seems that page crashes and does not respond to user input..  Sorta like a screen shot, you cant move the scroll bar and you can't interact with any input boxes.  Other than that the rest of the program seems to work correctly... you can change tabs and min/max the program ect...

In v37 you can reload the page to recover the page after a crash. but I can't to do this 100% of the time in v39

Its seems that 60% of my beta testers love v39 with very noticeable speed improvements...  while the other 40% hate it and literately can't run it with it crashing by freezing  the scroll bar and the content.  I have tried every settings that I know of to fix this but it keeps happening.

11 JAN 2015 Master using default browser settings works perfect.

While the testing the following

24 JAN 2015 Master
30 JAN 2015 Master
08 Feb 2015 Master

Suffers from this unusual freezing issue.

So Far I can only reproduce it on on Dell Latitude Laptops with Intel Graphics cards.. some of my users have reported it on different models made by dell that also have Intel Graphics cards.  I can't really be sure if it's 100% related to either dell laptops or Intel Graphics cards.

Here is how I reproduce the problem

1.  You need a dell laptop I am using a Dell Latitude (made in 2009) using Windows 7 Home with 4 gigs on a 64 bit OS.  I am compiling 08 Feb 2015 master to target C# 4.0 .NET (Full) 32 bit. using default browser settings.  I am removing the 4.5 .Net requirements by commenting out those features that use anysc

2.  Open up 19 tabs and do a Google search then switch tabs until every tab has search output.  If it does not happen on first cycle..  try again with a different search.

(Note using 11 Jan 2015 master I can safely have 30 tabs with out issues) 

Has anyone else experienced this issue ?  

Thanks.
David

**Comment by amaitland** [comment]
> 11 JAN 2015 Master using default browser settings works perfect.
> 
> While the testing the following
> 
> 24 JAN 2015 Master
> 30 JAN 2015 Master
> 08 Feb 2015 Master
> 
> Suffers from this unusual freezing issue.

I'm guessing the key part here is the different upstream version of `Cef`, I upgraded a to new versions a couple of times. If you look at https://www.nuget.org/packages/cef.redist.x86/ you'll see there's three different versions of `2171`, it looks like your experiencing problems in the newer versions. As for what's causing it, that's unclear. I'd be guessing it's an upstream issue.

**Comment by amaitland** [comment]
@daveaton I forgot to update the build script to the latest `3.2171.1979` version. How were you building your `master` versions?

**Comment by daveaton** [comment]
I am using the 11 JAN 2015 Master as a base and have started my own custom branch.

Then I Just build as normal in Visual Studio 2013.

I have built a custom installer from Inno Setup

http://stackoverflow.com/questions/27582762/inno-setup-for-visual-c-redistributable-package-for-visual-studio-2013

In Turn which the Original Author Included http://www.codeproject.com/Articles/20868/NET-Framework-Installer-for-InnoSetup in his master project for anyone to use.  :)

v39 still does not work correctly for me for all users.. I was forced to say with v37 at the moment.

**Comment by amaitland** [comment]
@daveaton Today I created an experimental branch that uses upstream `2272`, might be worth checking out at some point to see if your issue has been resolved in a newer version of `CEF`.

https://github.com/cefsharp/CefSharp/tree/cef/2272

**Comment by daveaton** [comment]
@amaitland - Thanks I will check it out.

**Comment by daveaton** [comment]
Just an update..  I have been playing around with 2272 and it's super fast..  I am still waiting for the users who have had the freezing issues in the past.

The freezing issues with v37 after 12 Jan 2015 and all of v39 I suspect deal with the input box such as a chat input box nested in frames.   I have a sneaky feeling it's has something to do with focus or keyboard commands because It actually happened on my machine and when I gave focus to a input but and tried to type the screen froze just like my users complained about..  while trying to figure out when went wrong after a few minutes it unlocked it self.  And slowly began to show the typed text  1 letter at a time with 5 to 10 seconds pause between.  I guess it was doing something with the text...  I typed  "how is everyone one" in a chat box and it took 10 min to complete the sentence and unfreeze. then all the animation and rest of the page began to function normally..  I tried to type again and it happened again.

Since that happened I was not able to reproduce the issue again on my machine.  I have not changed any settings since that time. 

This was why the page never recovered it self because it did not actually crash, something was just keeping it busy.   I do my subscribe to any handlers with keyboard commands such as the dictionary or focus that I know of.  

If I get any reports on the 2272 for my problem child clients I will weed out those features 1 by one and report back.

**Comment by rassilon** [comment]
Based on your comments, I wouldn't be surprised if this was an upstream issue.

Thanks for giving 2272 a try,
Bill

**Comment by daveaton** [comment]
Well just trying out 2272 with a few beta users.

Here are the details.

1. Popups crash if they are open for along time.
2. Memory goes over 1 million K
3. Tabs crash ever 75 pages or so.
4. Freezing issues are still present probably due to memory.

The last working version is still on 11 JAN 2015

My beta tester is on a bulgarian language system.  I thought I seen another issue on bulgarian language conflict but I can't find that one now.  It's hard to think that the problem is still and upline issue..  I am going to start weeding out the new features that was added after 11 Jan 05 - 25 Jan 2015 that might be the problem.

I find it very odd that the build 11 JAN 2015 is the only one that seems to work correctly. but the following master builds still fail

24 JAN 2015 Build Master (37)
30 JAN 2015 Build Master (37)
08 Feb 2015 Build Master (39)
07 Mar 2015 Build Master (39)

22 Mar 2015 Build 2272 (41)

My Program will open 15 pages and load pages in them each time a user clicks a link.  I could have 2-3 more pages opened in popups at any given time.  A user may load  between 500 - 9000 pages.  Normal usage is between 45 min and 7 hours

I will keep you updated.

**Comment by amaitland** [comment]
> The last working version is still on 11 JAN 2015

I've had a quick look at the commits that happened after that date and can't really see much that would affect the `WinForms` version.

To get a better understanding of what is going on, you might considering taking a heap snapshot, see what the internal `Chromium` performance counters look like. You can look at https://github.com/canton7/SyncTrayzor/issues/37#issuecomment-85475917 for a rough guide (Basically just enable remote debugging, then connect `Chrome`).

I'd also say it's probably worth memory profiling `CefSharp`, specially under such heavy load. I wouldn't be surprised if there was a leak or two.
