### ISSUE TITLE
CefSharp WPF 37.0.0 (stable): browser is empty

### ISSUE THREAD

**Issue by udo75** [cefsharp/CefSharp#805]
Hi all,

I encountered an interesting issue when working with CefSharp WPF. 
In the Code behind of a xaml the CefSharp is initialized in the constructor and in a method called when the view is created I call the LoadHTML() method to load a page.
It happens that the page is displayed but from time to time I have also the result that nothing is displayed in the browser.

This is done in the constructor:

```csharp
 public AltBrowserWindow(IBrowserWindowModel model, ILoggerManager loggerManager)
        {
            Cef.Initialize(new CefSettings());
            InitializeComponent();
            Model = model;
            _logger = loggerManager.GetLogger(Module.LOGGER_NAME);
        }
```

This is done in a method call when the view is created:

```csharp
 public void Create()
        {
             Model.Initialize();
             if (!String.IsNullOrWhiteSpace(Model.Url))
             {
                PostkorbWb.RegisterJsObject("dialer", Model);
                string postPage = BuildPostRequestPage();
                PostkorbWb.LoadHtml(postPage, "http://postpage/html");
             }
         }
```

If I put a Thread.Sleep(2000) before calling LoadHTML(), then I never run into this issue.

The question is, if I need to wait until the browser is initialized before calling LoadHTML() and how to do this. There is a property called IsBrowserInitialized but is seems that it is always false, also in the cases where the page is displayed.

Thanks for your help!

**Comment by amaitland** [comment]
`LoadHtml` is just registering an loading a `ResourceHandler` see https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf/ChromiumWebBrowser.cs#L1220

Try the following
- Register your resource handler immediately after the `ChromiumWebBrowser` is created.
- Set `Address` to that which you registered for your `ResourceHandler` e.g. http://postpage/html

**Comment by udo75** [comment]
Thanks for your reply. Can you tell me short how I can setup a ResourceHandler and register it. Any example I can have a look at? Sorry for this question but I did not use any ResourceHandler and I do not really know why I would need it.
Would be great if I can get a hint

**Comment by amaitland** [comment]
Code is the best documentation, the link I provided above shows how we register a `ResourceHandler` internally, the principal is the same.

**Comment by udo75** [comment]
correct, but I cannot find the class DefaultResourceHandler in namespace CefSharp. So how to instantiate a resource handler?

**Comment by jornh** [comment]
Try GitHubs excellent search feature right at the top of this page and you should be able to dig it up: https://github.com/cefsharp/CefSharp/search?utf8=%E2%9C%93&q=DefaultResourceHandler

**Comment by udo75** [comment]
great hint, thanks!
I have still the problem that I don't see any ResourceHandler Property in my CefSharp.Wpf.ChromiumWebBrowser instance to register a handler for it...

**Comment by jankurianski** [comment]
Here is where it is defined in v37: https://github.com/cefsharp/CefSharp/blob/v37.0.0/CefSharp.Wpf/ChromiumWebBrowser.cs#L57

`-pre02` release did not have the `ResourceHandler` property.. I suspect you are on a pre release and not the stable release.

**Comment by udo75** [comment]
Thanks for the hint - that was actually the issue, wrong referencing. Sorry for this confusion.
I changed the code as suggested from @amaitland but now the browser is always empty. Here my changes

in the constructor of the code behind, after InitializeComponent() I call BuildPostRequestPage() to create the html and then register a Resource Handler

PostkorbWb is my instance of the ChromiumWebBrowser

public AltBrowserWindow(IBrowserWindowModel model, ILoggerManager loggerManager)
        {
            Cef.Initialize(new CefSettings());
            InitializeComponent();
            Model = model;
                       _resourceHandler = PostkorbWb.ResourceHandler;
            string postPage = BuildPostRequestPage();
            _resourceHandler.RegisterHandler(POST_URL, CefSharp.ResourceHandler.FromString(postPage));
        }

In the Create() method that is called to create the view I set the Address-Property to the POST_URL used in the register of the ResourceHandler
 public void Create()
        {
            Model.Initialize();
            if (!String.IsNullOrWhiteSpace(Model.Url))
            {
               PostkorbWb.RegisterJsObject("dialer", Model);
               PostkorbWb.Address = POST_URL;
            }
        }

Any idea why I don't see anything displayed?

**Comment by udo75** [comment]
with the old implementation one interesting effect is also, that each opening and closing, the next opening of the page takes longer and longer, until nothing is displayed....hope that helps to understand the issue

**Comment by amaitland** [comment]
There is a small bug in the `ResourceHandler` implementation that was fixed just recently, it's probably worth trying the latest `CI` build. 

https://github.com/cefsharp/CefSharp#nuget-packages

**Comment by amaitland** [comment]
(Also please markup your code as it's hard to read).

**Comment by udo75** [comment]
Sorry, was sick the last days... Thanks for the hint I'll check this.

About marking up the code, I'll have a look how to do it. Up to now it seemed that it was done automatically. Sorry for that

**Comment by amaitland** [comment]
> About marking up the code, I'll have a look how to do it. Up to now it seemed that it was done automatically. Sorry for that

If you edit one of the comments that has been marked up, you can see an example of how it's done.

**Comment by jornh** [comment]
@udo75 did https://github.com/cefsharp/CefSharp/issues/805#issuecomment-74356084 resolve the issue?

**Comment by udo75** [comment]
@jornh first of all: thank you for the "automation" of the mark up :). I promise doing it better next time :)

I was the last weeks on conferences and did not have time to take a closer look. The first attempt before I left was not successful - the application crashed when I initialized Cef. I'll give another try.

@amaitland: Is the fix for the ResourceHandler only available in the version 39.x or will be there also a fix for this with version 37 - which I basically use.

**Comment by amaitland** [comment]
> @amaitland: Is the fix for the ResourceHandler only available in the version 39.x or will be there also a fix for this with version 37 - which I basically use.

There is a pre-release of `39` e.g. `39.0.0-pre03`. The official release should be in the next few weeks. (There are no plans for a followup `37.0.0` release)

**Comment by udo75** [comment]
Hi Guys, 
in Visual Studio I see in the NuGet Package Manager only the stable version 37. Are the pre-releases for 39 not available as binaries? Do I need to compile the solution to get the binaries?

Thank you for your help!

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp#nuget-packages

Make sure you tell the Package manager to include `pre-release` packages.

**Comment by udo75** [comment]
Hi Guys,

unfortunately I still see only a white window when using the approach with registering a resource handler and setting the Address property to the fake URL.

This is now my constructor looking like:
```csharp
            Cef.Initialize(new CefSettings());
            InitializeComponent();
            Model = model;
            IResourceHandler handler = PostkorbWb.ResourceHandler;
            string postPage = BuildPostRequestPage();
            handler.RegisterHandler("http://postpage/html", CefSharp.ResourceHandler.FromString(postPage));
            PostkorbWb.Address = "http://postpage/html";
```

This method is called afterwards by the framework we use to create the view where the browser is hosted:

```csharp
        public void Create()
        {
            Model.Initialize();
            if (!String.IsNullOrWhiteSpace(Model.Url))
            {
                _logger.Debug("[AltBrowserWindow] Registering JsObject dialer in the Cef browser...");
                PostkorbWb.RegisterJsObject("dialer", Model);
                //PostkorbWb.Address = "http://postpage/html";
            }
        }
```

I tried also to - as you can see the commented line - to set the Address Porperty also in the ```Create()``` method but it did not help.

When I look to the properties of the CefSharp.dll I see the version number 39.0.0.0, so it should be the correct pre-release version I'm referencing.

Any other idea or ways to post data?

Thank you for your support!

**Comment by amaitland** [comment]
`RegisterJsObject` has to be called pretty much straight after the browser is created. e.g. https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf.Example/Views/BrowserTabView.xaml.cs#L18

It's really hard to get a proper idea of the order of execution from your snippets. Can you post a `GIST` or fork the `MinimalExample` to demo your problem?

**Comment by udo75** [comment]
I'll give a try to fork the ```MinimalExample```. I placed the ```RegisterJsObject``` into the constructor, it did not help. I hope that I can reproduce it with the MinimalExample as this was the starting point for my changes in the current project. I'll also have a detailed look to the Wpf.Example to check if I missed anything as we also create tabbed views where the browser is hosted.

**Comment by amaitland** [comment]
Rather than setting `Address`, perhaps try calling `Load(url)` directly (from memory `Address` uses `Load` under the hood).

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf/ChromiumWebBrowser.cs#L1250

**Comment by amaitland** [comment]
Other option you have is to include the source code in your project and debug yourself. Most of the `WPF` stuff is pretty easy to follow at a high level.

**Comment by udo75** [comment]
Ok, so I started really a small WPF application to see that I get the things running outside the solution I'm working on and it works fine on my very minimal test solution :)
I started to check the code on the solution I wanted to get run and saw some wrong execution order. So finally I got now the resource handler running also on my solution - that really great :)

In the next step I need to analyze now if I still get the blank screen - which was basically the starting point of this issue.

I'll continue on Monday as I'm going to leave for some days. Hopefully I have good news for you and me on Monday :)

Thank you very much so far Guys - you are great!!

**Comment by udo75** [comment]
Hi!

I got finally the positive answer from testers that the issue with blank web browser did not come up any longer! That's really great! Thank you again for you support.
Before I close the issue I'd like to ask if you now have a planed date for the stable release for Cef 39?

Thanks again Guys!

**Comment by amaitland** [comment]
> Before I close the issue I'd like to ask if you now have a planed date for the stable release for Cef 39?

When it's ready is the only real answer we can give at the moment. 

There are still a number of open issues that need to be resolved before release see https://github.com/cefsharp/CefSharp/milestones/39.0.0

We're always looking for more people to help out if you have time :+1:

**Comment by udo75** [comment]
I would really like to join a group like this, but as told before C++ is not really my strength field

**Comment by amaitland** [comment]
I personally had never written `C++` before getting involved with this project, there are a few quirks, it's for the most part not too complicated. Plenty of people to ask for help :smile:
