### ISSUE TITLE
downloading files to persistance cache storage

### ISSUE THREAD

**Issue by rover886** [cefsharp/CefSharp#806]
I have an webpage where some links of .swf files are given when user clicks on an link I need to download the swf file into an persistent location. I also want to check whether an .swf file is available in local persistent storage or not if not then download, if available then skip downloading and referfer from local storage.

How can I set  an local directory as persistent cache storage where files get downloaded and remain as it is even if cef get shutdown?

How can I check the requesting .swf file is available in local storage or not, if not then download otherwise refer from local?

**Comment by amaitland** [comment]
You can set `CefSettings.CachePath` when you call `Cef.Initialize`
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/CefSettings.h#L94
Documentation
https://bitbucket.org/chromiumembedded/branches-2171-cef3/src/cfa746b389c9b1f77746071bd0ee76412899cb49/include/internal/cef_types.h?at=master#cl-242

> How can I check the requesting .swf file is available in local storage or not, if not then download otherwise refer from local?

Not aware of any extendability points in `Cef` that pertain to that, doesn't mean there aren't any, you'll just have to look `upstream`

**Comment by rover886** [comment]
I tried by setting `settings.CachePath = @"E:\Desktop\Cache\";` and run the app. after browsing website folder contains files like `Cookies, Cookies-journal, data_0, data_1, f_00000a, f_00000b...` how can i find the swf files which is downloaded?

**Comment by amaitland** [comment]
From other issues it sounds like your using a very old version, it would be worth upgrading and trying again. Far as I know `CEF` stores it's cache in the directory you specify or memory. The documentation link I posted about contains as much information as I have on the subject.
