### ISSUE TITLE
Respond is not yet supported.

### ISSUE THREAD

**Issue by rover886** [cefsharp/CefSharp#807]
I am using cefsharp version 31.0.1650.57. I am trying to load an resource from my local path if loading resource is having some specific file name. Please check to code below:

    bool IRequestHandler.OnBeforeResourceLoad(IWebBrowser browser, IRequestResponse requestResponse)
        {
            if (requestResponse.Request.Url.Contains("splash_animation_compress.swf"))
            {
                MessageBox.Show(requestResponse.Request.Url);
                Stream resourceStream = new MemoryStream(File.ReadAllBytes(@"E:\Desktop\Car-speakers-590x90.swf"));
                requestResponse.RespondWith(resourceStream, "application/x-shockwave-flash");
            }
            return false;
        }

I want that if loading resource contains file name `splash_animation_compress.swf` then I want to load an .swf file which at some specific path. I tied by loading into `Stream` and giving this stream to `requestResponse` but it gives me exception `Respond is not yet supported.` from `ClientAdapter.cpp`.

**Comment by amaitland** [comment]
> I am using cefsharp version 31.0.1650.57.

Please upgrade to version `37.0.0`, what your looking for now is now called a `ResourceHandler` and is registered directly on `ChromiumWebBrowser`.

**Comment by rover886** [comment]
Ohh okay thanks.

**Comment by rover886** [comment]
Hey, instead of downloading all can't take just update over 31.0.1650.57?

**Comment by amaitland** [comment]
> Hey, instead of downloading all can I take just update over 31.0.1650.57?

Not sure I understand. Can you clarify?
