### ISSUE TITLE
Some plugins don't seem to work

### ISSUE THREAD

**Issue by ksophocleous** [cefsharp/CefSharp#808]
On `f6d8685c6df4b7cccf13d009c4df837edd77c7ba` some plugins aren't working for me.

Flash and PDF are working
Silverlight and `Unreal Media Player Plugin - Version: 6.2.0.161` are NOT working

I've tried `CEF 3.2171.1979` and plugins are loaded and everything is awesome and also both we tried CefSharp release `v1.25.8` and all is working as expected.

I'm using Visual Studio Express 2013 for Desktop

`chrome://version`
> CEF	3.2171.1979
> Chromium	39.0.2171.95
> OS	Windows
> WebKit	537.36
> JavaScript	3.29.88.17
> Flash	12,0,0,44
> User Agent	Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36
> Command Line	"E:\env\msys64\home\ksophocleous\CefSharp_old\CefSharp.WinForms.Example\bin\x86\Debug\CefSharp.WinForms.Example.vshost.exe" --browser-subprocess-path=CefSharp.BrowserSubprocess.exe --no-sandbox --lang=en-US --log-file="E:\env\msys64\home\ksophocleous\cefsharp.log" --log-severity=verbose --remote-debugging-port=8088 --debug-plugin-loading=1 --allow-outdated-plugins=1 --always-authorize-plugins=1 --enable-npapi=1
> Module Path	E:\env\msys64\home\ksophocleous\CefSharp_old\CefSharp.WinForms.Example\bin\x86\Debug\libcef.dll
> Cache Path	C:\Users\KSOPHO~1\AppData\Local\Temp\scoped_dir7112_17816

**Comment by amaitland** [comment]
Silverlight not working is a known issue see #467

**Comment by jornh** [comment]
Can confirm your experiences with the Unreal Media Player plugin - though I tried with version 6.3. With the UMS On Demand demo streams from http://www.umediaserver.net/umediaserver/UMSBigFile.html I even get a:

```
System.AccessViolationException was unhandled
Message: An unhandled exception of type 'System.AccessViolationException' occurred in CefSharp.BrowserSubprocess.Core.dll
Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
```
