### ISSUE TITLE
getUserMedia not finding my DirectShow capture filter as a video source?

### ISSUE THREAD

**Issue by roschler** [cefsharp/CefSharp#812]
Hello CefSharp team.  I have a C# DirectShow filter taken from this article:

http://www.codeproject.com/Articles/437617/DirectShow-Virtual-Video-Capture-Source-Filter-in

It works fine and in all of my Windows apps it shows up as a video source.  However, when I call getUserMedia() with video = true in the constraints object, it doesn't come back in the list.  I downloaded the SVN source tree for Embedded Chromium, and I can't find the keyword getUserMedia anywhere..  I want to look at the source so I can see how they are structuring their device enumeration calls and hopefully find out why getUserMedia skips over my DirectShow filter.

Has anybody encountered this or a similar situation with getUserMedia and knows how to fix this, or knows where I can find the source that implements that call?

Thanks,
Robert

**Comment by amaitland** [comment]
Does `getUserMedia` rely on `WebRTC`?

If it does then you need to specifically enable `WebRTC` see https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/CefExample.cs#L29

**Comment by roschler** [comment]
Already did that.  If I didn't, getUserMedia would not work at all.  The getUserMedia interface is present and executes well, it's just not finding my DirectShow filter when all the other apps in my system can.

**Comment by amaitland** [comment]
> Already did that. If I didn't, getUserMedia would not work at all. The getUserMedia interface is present and executes well, it's just not finding my DirectShow filter when all the other apps in my system can.

Background information is important when posting, we get a lot of support requests and it's hard to remember ever one.

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue

**Comment by amaitland** [comment]
You should also include the version your working with, `WinForms` or `WPF`, as much information as possible please :+1:

**Comment by roschler** [comment]
"Background information is important when posting, we get a lot of support requests and it's hard to remember ever one."

The background information is included in the post you linked me.  If you don't add ""enable-media-stream" to the Chromium command line settings, the getUserMedia call is not present in the Javascript namespace.  That's what I was referring to when I said if I had not of done that, "getUserMedia" wouldn't work at all.
