### ISSUE TITLE
Feature Request - JSB Support UInt Return Type

### ISSUE THREAD

**Issue by ray007** [cefsharp/CefSharp#814]
On the bound C# object I have a method
```
public void showInfo(uint Id)
{
	doWork(id);
}
```
This was working fine so far, but once I got to an `id > 0x7fffffff` the call from JS failed and threw an exception: `Object of type 'System.Int32' cannot be converted to type 'System.UInt32'.`.
I guess I can work around the problem by declaring an `int` parameter and convert it to `uint` before passing it on, even though negative numbers don't make sense for IDs...

**Comment by amaitland** [comment]
Feel free to create a PR

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.BrowserSubprocess.Core/TypeUtils.cpp#L153

**Comment by amaitland** [comment]
If someone wishes to submit a `PR` then please make yourself known and we'll reopen this.
