### ISSUE TITLE
How does CefSharp pick the default fonts to use?

### ISSUE THREAD

**Issue by rfgamaral** [cefsharp/CefSharp#816]
Chrome itself allow one to configure the `standard`, `serif`, sans-serif` and `fixed-width` fonts. How does CefSharp/CEF picks the exact fonts to use for all of these according to the user locale (for instance, for Korean users)?

I'm asking this because a user of my SlackUI application [opened an issue](https://github.com/rfgamaral/SlackUI/issues/19) regarding Korean fonts. Basically, my app was not using the new default Windows fonts but the old ones (much like Segoe UI is now the default font for UI components where before it was Tahoma).

Is there any way I can make this configurable or not at all?

**Comment by amaitland** [comment]
The only font settings I'm aware of are

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/BrowserSettings.h#L91
Upstream API doc
http://magpcss.org/ceforum/apidocs3/projects/%28default%29/_cef_browser_settings_t.html

For more information I'd say you'd searching in regards to `CEF` may yield more information.

**Comment by rfgamaral** [comment]
That clarified it for me. Thank you.
