### ISSUE TITLE
Can I do modification in cefSharp v 37.0.0

### ISSUE THREAD

**Issue by rover886** [cefsharp/CefSharp#817]
Hello team :smile: ,

   I downloaded `cefSharp.Winforms` from nuget and implemented in my winforms application. In that I have written an `RequestHandler` with some line of code in `OnBeforeResourceLoad` method to load an particular resource from local other then web. Implementation is as follow :

    public bool OnBeforeResourceLoad(IWebBrowser browser, IRequest request, IResponse response)
        {
            if (request.Url.Contains("splash_animation_compress.swf"))
            {
                var handler = browser.ResourceHandler;
                if (handler != null)
                {
                    handler.RegisterHandler(request.Url, ResourceHandler.FromFileName(@"E:\Desktop\Car-speakers-590x90.swf", "swf"));
                }
            }
            
            return false;
        }

This code is working fine, Now what I want is to load resource from `Stream`. In current `master` which is version 39 having method `ResourceHandler.FromStream()` but I guess version 39 is in pre-release. so can I download v 37.0.0 `master` and add method in `ResourceHandler`. Why in version 37 is I don't want to use pre-release version so I am thinking to do modifications in stable version only. Is this possible or any other alternative other then shifting to v 39

**Comment by amaitland** [comment]
All releases are tagged, you can use the tag as your starting point.

https://github.com/cefsharp/CefSharp/releases/tag/v37.0.0

Personally I'd use the `39.0.0-pre02` release.
