### ISSUE TITLE
WPF blurry problem Windows 8.1

### ISSUE THREAD

**Issue by mshumilov** [cefsharp/CefSharp#819]
I have a blurry font problem for WPF CefSharp browser (in my app or when I run default CefSharp.Wpf.Example). There is no such a problem in WinForms. The quality of fonts in WPF is much worse. 
Also if I click to link from the wpf browser then new window is open and the quality in this new window is perfect.

Default windows font settings and screen resolution are used. 
I've tried to change SnapsToDevicePixels, UseLayoutRounding, TextOptions on the parent (TextFormattingMode, TextHintingMode, TextRenderingMode) with no success. 
I've tried 37.0.0 (stable) and the latest 39.0.0-pre02. It's all the same.

Screenshot, first is WinForms, second is WPF:
![screenshot_7](https://cloud.githubusercontent.com/assets/3007389/6229958/f69a515e-b6e5-11e4-8996-57fdff56b153.jpg)

Do you have an idea what's the reason and how to fix it?

**Comment by jankurianski** [comment]
This may be a CEF issue rather than a WPF issue.  Can you try the official `cefclient.exe` test app using WPF-like parameters and compare the text to what you see in CefSharp?  The process is described here: https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

**Comment by amaitland** [comment]
> Also if I click to link from the wpf browser then new window is open and the quality in this new window is perfect.

The `popup` windows aren't actually `WPF` windows, they're native ones and as such are rendered differently.

> Default windows font settings and screen resolution are used.
> I've tried to change SnapsToDevicePixels, UseLayoutRounding, TextOptions on the parent (TextFormattingMode, TextHintingMode, TextRenderingMode) with no success.

The `WPF` control is actually an image for which you interact, so text options won't work.

What `DPI` and resolution are you running? The `WPF` control has a few problems when running on high dpi devices.

As @jankurianski suggests, isolating the problem is an excellent first step :+1:

**Comment by mshumilov** [comment]
I've tested it with: "cefclient --multi-threaded-message-loop --off-screen-rendering-enabled" 37.0.0/39.0.0. And there is no such a problem there.

Resolution is 1440x900 that is recommended, DPI scaling 100% (default) on my 13-inch MacBook Air.

**Comment by amaitland** [comment]
Can you try `Fix Blurry Fonts in Specific Applications` from http://www.howtogeek.com/175664/how-to-make-the-windows-desktop-work-well-on-high-dpi-displays-and-fix-blurry-fonts/?

Are you up for debugging the issue? Very difficult to troubleshoot something like this without being able to reproduce it.

**Comment by mshumilov** [comment]
> Are you up for debugging the issue? Very difficult to troubleshoot something like this without being able to reproduce it.

Yes, I understand that, and ready for debugging.

> Can you try Fix Blurry Fonts in Specific Applications from http://www.howtogeek.com/175664/how-to-make-the-windows-desktop-work-well-on-high-dpi-displays-and-fix-blurry-fonts/?

I'm using this model of notebook: http://support.apple.com/kb/SP631. No retina or something. My dpi is 96x96. I mean it's a standard DPI. 

In the topic you provided I should set "Disable display scalling on high DPI settings" to the app. But my settings are not high and scalling disabled already. Anyway, I've tried this option, no changes.

**Comment by amaitland** [comment]
> In the topic you provided I should set "Disable display scalling on high DPI settings" to the app. But my settings are not high and scalling disabled already. Anyway, I've tried this option, no changes.

I'm just going through the standard list of troubleshooting steps.

> Yes, I understand that, and ready for debugging.

Great :+1: Can you debug the `WPF Example` and see what values `matrix.M11` and `matrix.M22` have? They should be `1` by default unless something strange is going on.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf/ChromiumWebBrowser.cs#L645

Basically `Cef` renders a bitmap offscreen, then we use `WPF` to perform a `ScaleTransform` to upscale the output.

**Comment by mshumilov** [comment]
M11: 1.0 
M12: 0.0 
M21: 0.0
M22: 1.0
_type: TRANSFORM_IS_SCALING
Determinant: 1.0
HasInverse: true
IsDistinguishedIdentity: false
IsIdentity: true

**Comment by Bodekaer** [comment]
FYI we had a similar issue, and activating the "disable-direct-write" command line argument fixed it for us. (seems to be some graphic cards that caused the blurry issue)

**Comment by amaitland** [comment]
> FYI we had a similar issue, and activating the "disable-direct-write" command line argument fixed it for us. (seems to be some graphic cards that caused the blurry issue)

@Bodekaer That's very interesting! @mshumilov Does your `MacBook` have an `Intel` graphics card by any chance? They seem to have 10x more problems than any others from my experience.

**Comment by mshumilov** [comment]
Intel HD Graphics 3000. But why I have no such problems in any other app, and also have no it with cefclient --off-screen-rendering-enabled? I'll try with "disable-direct-write"...

**Comment by amaitland** [comment]
`cefclient` being the native `c++` application that it is uses `OpenGL` for `OSR` rendering, we use `WPF InteropBitmap` to render the image. Whilst it's a reasonable test to compare the two, they are totally different in reality.

If you search though past issues, you'll see lots of different problems with `Intel` graphics cards, particular with `gpu acceleration`.

You'll find that `Chrome` it's self will `enable/disable` features automatically based on your hardware to give the best user experience and workaround known problems. If you google `google chrome intel graphics` you'll find a myriad of posts where users are having problems.

**Comment by mshumilov** [comment]
I've added "settings.CefCommandLineArgs.Add("disable-direct-write", "1");". And it's decrease blurriness little bit, yes. But still not good.

**Comment by amaitland** [comment]
You may also want to try `disable-gpu`, it's been known to cause problems with `Intel`, it's a long shot.

**Comment by mshumilov** [comment]
> You may also want to try disable-gpu

No effect.
Will use WinForms version within WindowsFormsHost instead. There is no such a problem there.

**Comment by amaitland** [comment]
Great :+1:
