### ISSUE TITLE
Jquery modal popups appear behind flash content

### ISSUE THREAD

**Issue by rover886** [cefsharp/CefSharp#821]
I implemented `CefSharp version 37.0.0` in windows application, while browsing through websites I observed that when an webpage having flash content and when Jquery modal popup comes then that popup appear behind to flash content. I also experienced that even it happens with dropdown menu also, dropdown menu goes behind to flash content. An screenshot is added
![cef](https://cloud.githubusercontent.com/assets/8499500/6252503/e7a36a7e-b7c0-11e4-8971-aaab9601586f.png)

Can we do anything?

**Comment by jornh** [comment]
Please check if it's an upstream CEF issue or local to CefSharp: https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

**Comment by jornh** [comment]
Also this may be a duplicate of (or related to) an already identified `upstream` error - https://github.com/cefsharp/CefSharp/labels/upstream ... Specifically #657

**Comment by rover886** [comment]
Ohh yeah, it's `upstream`, sorry :grimacing: for posting without trying on Test app from cefbuilds.com.
