### ISSUE TITLE
response.RedirectUrl in ProcessRequestAsync is not working

### ISSUE THREAD

**Issue by rover886** [cefsharp/CefSharp#822]
I am using `cefSharp version 37.0.0` in windows application. I have written custom scheme handler from which I want to redirect to an particular url for that I have written `response.RedirectUrl` in `ProcessRequestAsync()` but it's not working.

    public bool ProcessRequestAsync(IRequest request, ISchemeHandlerResponse response, OnRequestCompletedHandler requestCompletedCallback)
    {
	response.RedirectUrl = "www.google.com";           
         return false;          
    }

Is there any thing I am missing?

**Comment by amaitland** [comment]
Try this

```c#
response.RedirectUrl = "http://github.com";
response.MimeType = "text/html";

requestCompletedCallback();

return false;
```

You need to call `requestCompletedCallback` otherwise `GetResponseHeaders` is never called, which sets the redirect Url.

You need to set the mime type to something valid otherwise it'll cause an exception and `cef` will crash.

**Comment by rover886** [comment]
Thanks.
