### ISSUE TITLE
CSS calc doesn't seem to be supported

### ISSUE THREAD

**Issue by adam-marshall** [cefsharp/CefSharp#823]
i.e. https://developer.mozilla.org/en-US/docs/Web/CSS/calc#Browser_compatibility

e.g, 
            width: calc(~'100% - 57px');

**Comment by amaitland** [comment]
Is `css calc` supported by `CEF`? (`CefSharp` being a lightweight wrapper around `CEF`).

**Comment by adam-marshall** [comment]
Quite possibly, haven't tested! Will investigate and if so then I'll log an issue there.

**Comment by amaitland** [comment]
Are you using version `37` or `39-pre`? If you haven't tried the latest version then take it for a spin.

**Comment by jankurianski** [comment]
It works for me on `39`, and I think it did on `37` too.

Your example is `width: calc(~'100% - 57px');` but I think this is invalid syntax (the tilde, the quotes).
Try `width: calc(100% - 57px);` instead.  Another thing to be wary of is that the whitespace around the `-` operator is essential.

**Comment by adam-marshall** [comment]
Ah ok, thats good to hear. I'm on 25 so way off :) Might be worth upgrading then! 

The tilde syntax was because I copied the example from LESS, sorry.
