### ISSUE TITLE
Focus change inside browser does not clear IME input

### ISSUE THREAD

**Issue by wdch-nseeley** [cefsharp/CefSharp#824]
I'm not sure if this is a problem with CefSharp or with CEF.  I'll carry the issue upstream if that's where it goes.

Basically, there is a very confusing issue with IME input using the WinForms browser in a WPF project.  With the IME turned on, start entering text into a field.  The IME window pops open right where it should, beneath the focused input control.  Then, without pressing ENTER to end composition, click another text field to change focus.

What's expected to happen: The IME window should close.
What actually happens: The IME window stays open on the previously focused control.  Pressing ENTER sends the composed text to the newly focused input.

A more confusing situation is encountered when focus is changed automatically through Javascript rather than user interaction.  For example, entering text into a search field which changes focus when a match is encountered.

To fix this, I need to close the IME window when control focus changes within the browser.  I haven't found any focus events pertaining to browser elements, so I'm thinking I have to write a Javascript focus event and attach it to every input.  Then figure out how to close the IME.

**Comment by amaitland** [comment]
`cefclient` is the `CEF` reference implementation
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

Also you haven't included which version of `CefSharp` your using.

**Comment by wdch-nseeley** [comment]
Using version "CefSharp.WinForms.39.0.0-pre01"

I'll report back once I can use the reference implementation.  It keeps dying with "Couldn't mmap v8 natives data file"

**Comment by wdch-nseeley** [comment]
The current reference implementation contains the a-fore mentioned bug.  A build from the month prior runs just fine.

I have verified the problem exists within the reference implementation, so this issue will be closed with my apologies.

Thanks for all your help.

**Comment by amaitland** [comment]
`39.0.0-pre02` uses the latest official `cef` release, `3.2171.1979`. The official `39` release will be based on the same verison.

If you find a newer `cef` branch that works, e.g. `2272` or `trunk` then it's possible that you could upgrade `CefSharp` to use that newer version. It would be a fair amount of work, so depends on how much of an issue this bug is.

**Comment by wdch-nseeley** [comment]
I'm going to try a javascript or javascript-c# solution capturing focus events.

Opened an issue with CEF
https://code.google.com/p/chromiumembedded/issues/detail?id=1541&thanks=1541&ts=1424400660

**Comment by rassilon** [comment]
@wdch-nseeley , I didn't see you mention in the CEF issue that it worked previously, you should mention which version it did work in for your upstream CEF issue.

**Comment by wdch-nseeley** [comment]
@rassilon My sentence was confusing.  I never found the IME problem working in the reference implementation. The "a-fore" mentioned bug I was referring to was the bug preventing the reference client from running. The "mmap" error.
