### ISSUE TITLE
Call .NET method when JS function is called

### ISSUE THREAD

**Issue by rfgamaral** [cefsharp/CefSharp#833]
I'm not sure if this has been answered before but I've been searching this repository (and Google) for the past hour and couldn't find a thing about this topic. I'm sorry if it's there and I just couldn't find it...

Say you have a `ChromiumWebBrowser` pointing to some URL where you have `window.OBJ` object with a bunch of functions, for instance `window.OBJ.myFn = function () { /* does stuff */ }`. You have no control over this object because it's not your site. Now, you want to be notified on your .NET app every time `myFn()` is called, like an event handler.

The only solution I found so far was something like this:

```csharp
public class MyObj {
    public void MyFn() {
        System.Diagnostics.Debug.WriteLine("MyObj.MyFn()");
    }
}

chromium.RegisterJsObject("FOO", new MyObj());

chromium.EvaluateScriptAsync(
    "var f = OBJ.myFn; OBJ.myFn = function() {" +
        "var r = f.apply(this, arguments);" +
        "FOO.myFn();" +
        "return r;" +
    "}");
```

This seems to work just fine, but is this the only way to achieve what I'm after or **is there a built-in mechanism that I'm missing?**

**Comment by rassilon** [comment]
Nope, the basic idea of what you have there is required: i.e. setting OBJ.myFn to something else that calls FOO.myFn.

The mechanics of what that something else does is your problem. :)

Bill

**Comment by rfgamaral** [comment]
Thank you :)
