### ISSUE TITLE
WPF - Implement CefScreenInfo

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#836]
Look at implementing `CefRenderHandler.GetScreenInfo` and specifying `device_scale_factor`. Hopefully be able to get `CEF` to do all the scaling and remove the custom WPF `Transform`.

http://magpcss.org/ceforum/apidocs3/projects/%28default%29/CefRenderHandler.html#GetScreenInfo%28CefRefPtr%3CCefBrowser%3E,CefScreenInfo&%29

http://magpcss.org/ceforum/apidocs3/projects/%28default%29/_cef_screen_info_t.html#device_scale_factor

```c++
//CefRenderHandler
virtual bool GetScreenInfo(CefRefPtr< CefBrowser > browser, CefScreenInfo& screen_info) OVERRIDE
{
	
};
```

Really just adding this as a note to self.

**Comment by bjarteskogoy** [comment]
I'm looking into this one. A quick test seem to prove that this works.

**Comment by amaitland** [comment]
More info
https://code.google.com/p/chromiumembedded/issues/detail?id=946#c6

**Comment by bjarteskogoy** [comment]
I wonder if a part of the problem is the dpiSize referred to here:
gfx::Size ToPixelSize(gfx::Size dipSize, float scale) {
  return gfx::ToCeiledSize(gfx::ScaleSize(dipSize, scale));
}
