### ISSUE TITLE
MessageBox on OnBeforeResourceLoad goes behind form

### ISSUE THREAD

**Issue by rover886** [cefsharp/CefSharp#837]
I am using `CefSharp 37` in `winforms`. I have implemented `IRequestHandler` and want to write some `ResourceHandler` code in method `OnBeforeResourceLoad`. 

in `OnBeforeResourceLoad()` I check some condition and on that basis I display a `MessageBox` with OK and Cancel buttons. By pressing `Cancel` I want to return `true` otherwise `false`. Code as below:

```
		public bool OnBeforeResourceLoad(IWebBrowser browser, IRequest request, IResponse response)
        {            
                if (!request.Url.Contains(ContentHelper.requestTrapKey)
                {                    
                    var handler = browser.ResourceHandler;
                    if (handler != null)
                    {
                        handler.RegisterHandler(request.Url, ResourceHandler.FromStream(File.OpenRead(ContentHelper.contentRootPath), Path.GetExtension(ContentHelper.contentRootPath + final));                        
                    }
                }
                else if (!request.Url.Contains(ContentHelper.requestTrapKey + "course") && request.Url.Contains(ContentHelper.requestTrapKey))
                {                      
                    if (MessageBox.Show("message", "title", MessageBoxButtons.OKCancel, MessageBoxIcon.Question, MessageBoxDefaultButton.Button1) == DialogResult.Cancel)
                    {
                        return true;
                    }                  
                }
           
            return false;
        }
```
It is observed that sometime `MessageBox()` goes behind to main form and user waits for messagebox to come and also next code also in wait state to execute. I know that as `MessageBox.Show()` is called on other thread than main thread so that's why it's going behind. But I tried to wrap the code by `MethodInvoker` then `MessageBox` remain on top of form but as when I press any button on message box application get hanged.

So is there any way where I can show `MessageBox` or a message to user without going it behind and take input from user and accordingly return true or false to load resource.

**Comment by jornh** [comment]
I'd say this is more a generic "WinForms MessageBox behind" problem than a CefSharp issue. Googling on those exact words picked from your post above gives me http://stackoverflow.com/questions/3467403/dialog-messagebox-sometimes-hidden-behind-the-main-form as the 2nd hit which looks useful in your case

You need to practice on your http://en.wiktionary.org/wiki/Google-fu my friend :+1: 

Closing!
