### ISSUE TITLE
Can't notify changes in proxy credentials

### ISSUE THREAD

**Issue by Antonyo** [cefsharp/CefSharp#838]
Hello,

I have my class that implements IRequestHandler.GetAuthCredentials and it successfully set the credentials in an authentication needed proxy environment. It works fine because until I provide the right credentials this method is being called upon each request, once I provide the right credentials I can navigate and this method is not called anymore.

The problem is, since this method is not called anymore, if I change the credentials to an invalid ones I'm still being able to navigate and I haven't found a way to notify the browser that the credentials are not valid and they need to be refreshed.

It might seems an unusual scenario but in my application it does not make sense that you can have a wrong password or even disable proxy authentication and you're still able to navigate.

Thanks in advance for the help.

**Comment by jornh** [comment]
If you send a request with invalid credentials are you getting e.g. a **401** error in return  (http://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_Error) or something similar - which you can detect the host of and prompt your user accordingly? 

Or are you saying that the proxy still allows traffic to pass (for the same session)? Then I guess it's "working as the proxy is designed" ...

Maybe try comparing/describing the UX behaviour of Chrome for the same scenario. Then I guess we are a step closer to a common understanding of what you want to achieve, and how it can be done with CefSharp.

**Comment by Antonyo** [comment]
Thanks for the answer, regarding your question, it did return a 401 response if the credentials are invalid, so that's perfectly correct. Comparing to Chrome, it does not allow you to explicitly change your current proxy credentials, it only asks  for them as long as they're invalid so it's the same behaviour I'm experiencing with CefSharp so I guess that's how it's suppose to work and I will need to change my program behaviour. Thanks again.
