### ISSUE TITLE
select dropdown problem

### ISSUE THREAD

**Issue by ray007** [cefsharp/CefSharp#839]
Not yet sure if it's a problem of CefSharp or the chromium frame within (doesn't happen in a normal browser), but when the window with the browser component is higher than the screen it's on, the dropdown of a select box doesn't have sufficient width:

![select_problem](https://cloud.githubusercontent.com/assets/126712/6351206/d02f673a-bc39-11e4-82ca-92384896adfa.png)

Anyone an idea what could cause such a problem or how to counter it?

Observed with CefSharp 39.0.0pre02, will do further debugging and testing...

Edit 1: an older version of our software using CefSharp1 doesn't have the problem.
Edit 2: using `WPF`, no idea if `WinForms` have the same problem.

**Comment by jornh** [comment]
> Not yet sure if it's a problem of CefSharp or the chromium frame within

Standard check: https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef to figure out if it's an upstream CEF issue or CefSharp

> Observed with CefSharp 39.0.0pre02, will do further debugging and testing...

Good :+1: ... also important is this WPF or WinForms? - https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue

**Comment by ray007** [comment]
Some more info:

checking on the cefsharp-vs-cef issue, it looks somewhat similar to http://magpcss.org/ceforum/viewtopic.php?f=6&t=12556&p=24061&hilit=select#p24061, which is supposedly fixed.

I also found the error to depend on the window size. Reducing window-size (to about 800x600) or smaller makes the error go away, switching to fullscreen (1680x1050) makes all of my select dropdowns disappear completely.

Using the lasted `MyGet` version also didn't help.

**Comment by ray007** [comment]
Not sure if I found the cause, but it does look like a candidate:

My window has in its xaml-config `Height="550" Width="525"`, which results in inner dimensions of 509x512.
Unfortunately `window.screen` seems to take it's dimensions from the initial window size instead of the monitor dimensions.
After resizing the window, properties like `innerWidth` and `innerHeight` correctly show the new value, but `window.screen` still has its initial wrong values...

The `CefSharp.Wpf.Example` app shows the same behaviour.

**Comment by ray007** [comment]
Update: getting the new snapshot `39.0.0-pre03` didn't change anything.

**Comment by rassilon** [comment]
Are you sure CEF in WPF is getting the correct resize change notification? In WinForms we recently fixed a bug (in 39.0.0-pre03 I think) where we weren't always notifying CEF of our size changes.
I'm afraid I don't know anything about the WPF code.

Bill

**Comment by ray007** [comment]
What does the resize notification have to do with this?
It's `window.screen` that's wrong, with the size initialized to the initial window size.

And as I said above: I don't know if this has anything to do with the misplaced select-dropdowns, it just seemed to be a possible candidate from my pov.

**Comment by ray007** [comment]
For testing I've changed `GetScreenInfo()` method in `ChromiumWebBrowser.cs` to
```
ScreenInfo IRenderWebBrowser.GetScreenInfo()
{
    var screenInfo = new ScreenInfo();
    var point = matrix.Transform(new Point(ActualWidth, ActualHeight));

    screenInfo.Width = (int)System.Windows.SystemParameters.PrimaryScreenWidth; // (int)point.X;
    screenInfo.Height = (int)System.Windows.SystemParameters.PrimaryScreenHeight; // (int)point.Y;
    screenInfo.ScaleFactor = (float)matrix.M11;

    return screenInfo;
}
```
This change now  gets me a correct `window.screen` object. Unfortunately the browser now also takes this as inner window size - there seems to be some confusion between the two in `CefSharp.Wpf`.
No idea yet whether it would help with the select dropdown bug.

**Comment by amaitland** [comment]
Please retest with the latest release (`43.0.1`). `GetScreenInfo` and related methods were rewritten when improving support for `High DPI devices`.

**Comment by ray007** [comment]
I'll try to find time to test this, but I can't upgrade to version `43.0.1` since that still has the `RenderProcess` issue...

**Comment by amaitland** [comment]
If the problem reproduces in the latest release please comment and we can reopen.

**Comment by ray007** [comment]
Seems fixed, thank you.

**Comment by bedantaguru** [comment]
I'm facing the same issue 
```

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using CefSharp;
using CefSharp.WinForms;

namespace VLabDemo
{
    public partial class Form1 : Form
    {
        public ChromiumWebBrowser chromeBrowser1;
        public ChromiumWebBrowser chromeBrowser2;
        public ChromiumWebBrowser chromeBrowser3;

        public Form1()
        {
            InitializeComponent();
            // Start the browser after initialize global component
            InitializeChromium();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            this.TopMost = true;
            //this.FormBorderStyle = FormBorderStyle.None;
            this.WindowState = FormWindowState.Maximized;
        }

        public void InitializeChromium()
        {
            CefSettings settings = new CefSettings();
            // Initialize cef with the provided settings
            Cef.Initialize(settings);
            // Create a browser component
            chromeBrowser1 = new ChromiumWebBrowser("https://vlab.stern.nyu.edu/analysis/VOL.NIFTY:IND-R.GJR-GARCH");
            chromeBrowser2 = new ChromiumWebBrowser("https://vlab.stern.nyu.edu/analysis/RISK.WORLDFIN-MR.GMES?selectedDate=2017-06-23&tableView=diff&selectedDiffDate=2017-05-31&selectedRegion=asia&selectedAsset=450&selectedCountry=India");
            chromeBrowser3 = new ChromiumWebBrowser("https://vlab.stern.nyu.edu/analysis/VOL.USDINR:FOREX-R.GJR-GARCH");
            // Add it to the form and fill it to the form window.
            //this.Controls.Add(chromeBrowser);
            panel1.Controls.Add(chromeBrowser1);
            panel2.Controls.Add(chromeBrowser2);
            panel3.Controls.Add(chromeBrowser3);

            chromeBrowser1.Dock = DockStyle.Fill;
            chromeBrowser2.Dock = DockStyle.Fill;
            chromeBrowser3.Dock = DockStyle.Fill;

        }

        private void Form1_FormClosing(object sender, FormClosingEventArgs e)
        {
            Cef.Shutdown();
        }
    }
}

```

**Comment by bedantaguru** [comment]
There are couple of drop-down menu which I'm not able to click.
