### ISSUE TITLE
PipeException when ChromiumWebBrowser embedded in Tab Control (WinForms)

### ISSUE THREAD

**Issue by tbowers** [cefsharp/CefSharp#840]
I am receiving  `'System.IO.PipeException' occurred in System.ServiceModel.dll` when using `ChromiumWebBrowser` inside a control that is nested inside a `Infragistics.Win.UltraWinDock.UltraDockManager` tab control.

This seems very similar to an issue posted here https://github.com/cefsharp/CefSharp/issues/528 that seems to still exist.

Is anyone else experiencing this or know workarounds?

Thanks,
Travis

**Comment by rassilon** [comment]
Do you only see this in the debugger? i.e. does your app when not run from the debugger get exposed to these exceptions as unhandled?

I've seen this occur in the IDE occasionally during application shutdown, but some of the commentary on the exception seems to indicate it's trying to point out a problem for me. (i.e. an exception not being caught before code transitions out of managed code for instance). When I've looked at the call stacks of the exception, it's appeared as if the exception is actually handled somewhere on the call stack (as long as it gets passed through native/managed transitions correctly.)

Bill

**Comment by tbowers** [comment]
Interesting. I don't see this outside the debugger. You are correct. I still get often caught in an exception when shutting down the consuming app while Visual Studio is attached but I suppose that's not a deal breaker (just off putting). Thanks for the help.
