### ISSUE TITLE
reuse the cookies of last session (?)

### ISSUE THREAD

**Issue by pipiscrew** [cefsharp/CefSharp#843]
hi, wondering if in an application I have create can have browser functionality, 
for example today I visited www.x.com where I logged in, in the end of the day I close the application. The next day when I go to www.x.com Im already logged in...

Session  / Cookies / CookieContainer

thanks

**Comment by amaitland** [comment]
See if this helps
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/CefSettings.h#L94

http://magpcss.org/ceforum/apidocs3/projects/%28default%29/_cef_settings_t.html#cache_path

**Comment by pipiscrew** [comment]
hi, 

thanks for quick responses, 

I take a look at #cache_path# should be use also #persist_session_cookies# aka 

http://magpcss.org/ceforum/apidocs3/projects/%28default%29/_cef_settings_t.html#persist_session_cookies

![snap510](https://cloud.githubusercontent.com/assets/3852762/6389401/60f61048-bdac-11e4-952e-3c534bea50ab.png)


but how!?

**Comment by rassilon** [comment]
You add command line args like so:

            settings.CefCommandLineArgs.Add("renderer-process-limit", "1");

Persisting session cookies could be a security issue waiting to happen. (session cookies are only supposed to last the length of the browser instance)

Fyi,
Bill

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/CefSettings.h#L94

**Comment by pipiscrew** [comment]
hmm today I discover **SetCookiePath**
![snap518](https://cloud.githubusercontent.com/assets/3852762/6410311/eda27a98-be76-11e4-98af-68baba8ebebf.png)

either using
settings.CefCommandLineArgs.Add("persist_session_cookies", "1");

either
Cef.SetCookiePath(cache_dir, true);

the result is the same, store cookies.. 


on a normal browser when I logged in to x.com then close the browser, open it and navigate again to x.com still identify me without login.. 

while using my TestApp with **persist_session_cookies** when go for second time to x.com still needs the login credentials. (btw the username **autofilled** by cookies, while when not using **persist_session_cookies** is blank)

**Comment by amaitland** [comment]
@pipiscrew Did you resolve your problem?

**Comment by pipiscrew** [comment]
Is not resolved, I stop searching by the time posted, if you like you can close it. I made an ancient technique (and not secure) save credentials to a file near browser, auto fill <input's when url = x.com... 2000?

**Comment by amaitland** [comment]
From what I can tell it needs to be call after the browser context has been initialized e.g. `OnContextInitialized`, same as a few other plugin methods. 

This method has yet to be implemented.

**Comment by amaitland** [comment]
@pipiscrew Maybe you could test #929 and let me know if that makes any difference?

**Comment by amaitland** [comment]
Have tested in the `WPF Example` and it appears that this is working with the latest `master` (#929 has been merged)

- Login to `gmail`
- Wait for mail to load
- Close browser
- Open new browser
- Open `gmail` (was already logged in)

**Comment by pipiscrew** [comment]
I can test by next week, I will let you know.. 

thanks

**Comment by amaitland** [comment]
@pipiscrew How'd you go?

**Comment by pipiscrew** [comment]
oops I forgot^, tested now, for me is not working... any special code line I should add ?

**Comment by amaitland** [comment]
Try https://github.com/cefsharp/CefSharp/pull/929/files#diff-8504643e16a7bcd2d9428f463a767ff9R55

**Comment by pipiscrew** [comment]
tested with GMAIL - working
tested with CRM (login with facebook) - not working - (on **Google Chrome Browser**, when login once, the next days no needed)

you can close the thread, I dont have time for more tests...


thanks

**Comment by amaitland** [comment]
You need to use `master`.

I've only tested with `GMail`

**Comment by kpstolk** [comment]
@amaitland I read this issue but can't get it to work.

I tried:
```
Cef.Initialize(new CefSettings { CachePath = "MyCachePath", PersistSessionCookies = true });
Cef.GetGlobalCookieManager().SetStoragePath("MyCookiePath", true);

// ... <Get a browser instance>
await browser.LoadPageAsync("http://www.html-kit.com/tools/cookietester/");
// Clicks button to set a cookie
await browser.EvaluateScriptAsync("document.getElementsByClassName('zp')[0].submit()");
await browser.LoadPageAsync();

// ... Cef.Shutdown();
```
Cookie and cache files are stored on disk, but the next time I run this code the page has no cookies set (tested by creating a screenshot of that page). I'm using CefSharp.OffScreen 47.0.2.0 BTW.

Is this not fixed completely or is there a difference with the CefSharp.OffScreen version? Did I miss something?

**Comment by amaitland** [comment]
> Is this not fixed completely or is there a difference with the CefSharp.OffScreen version?

No differences that I'm aware of. You have to remember that `CefSharp` is just a wrapper, has no controls over how cookies are persisted, just expose the relevant settings/methods.

Is there a reason your calling both `Initialize` and SetStoragePath` with the same values? You need to wait for the `Global Context` to be initialized before attempting to access the cookie manager, that was the overall gist of this issue.

**Comment by kpstolk** [comment]
Because it didn't work I tried to set both the `CachePath` and `SetStoragePath`. With different values BTW, "MyCachePath" and "MyCookiePath".

I also tried this but didn't make a difference:

```
Cef.OnContextInitialized = () => Cef.GetGlobalCookieManager().SetStoragePath("MyCookiePath", true)
Cef.Initialize(new CefSettings { CachePath = "MyCachePath", PersistSessionCookies = true });
```

**Comment by amaitland** [comment]
> Because it didn't work I tried to set both the CachePath and SetStoragePath. With different values BTW, "MyCachePath" and "MyCookiePath".

They basically do the same thing under the hood, best to call either one or the other.

**Comment by amaitland** [comment]
You can try isolate the problem using `cefclient` (the reference `CEF` application).

https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

You can use command line arguments to set the cache path and persist session cookies.

http://magpcss.org/ceforum/apidocs3/projects/%28default%29/_cef_settings_t.html#persist_session_cookies

`cefclient.exe --cache-path=c:\temp\cache2 --persist-session-cookies`

**Comment by kpstolk** [comment]
So I tried the CEF client (3.2526.1366.g8617e7c Windows64):
`cefclient.exe --cache-path=testcachepath`

That just works. The cookies are stored in the file `testcachepath/Cookies`.
The only difference I can see is that this file is also created, but no cookies are added using CefSharp.

Please [see my test code](https://gist.github.com/kpstolk/ef8bd103b972867d049e) if that would help.

**Comment by amaitland** [comment]
> cefclient.exe --cache-path=testcachepath

That's not equivalent to the code you've been using, missing the persist session cookies option.

> Please see my test code if that would help.

I don't have any time to test this at the moment. Sorry.

**Comment by kpstolk** [comment]
I also tested with cefclient.exe --persist-session-cookies but that didn't make any difference, the cookies from that example are not session cookies, I enabled that just to be sure.

This also didn't work unfortunately:

```
cefclient.exe --cache-path=testcachepath  --persist-session-cookies
cefclient.exe --cache-path=testcachepath  --persist-session-cookies --multi-threaded-message-loop --off-screen-rendering-enabled
```

**Comment by kpstolk** [comment]
Should I open a separate issue? I don't know how I can troubeshoot this further either..
As far as I can see this is not an issue in CEF / cefclient, or it might be a bug in my code sample.

**Comment by amaitland** [comment]
> Should I open a separate issue?

Separate issue for what exactly?

**Comment by amaitland** [comment]
> As far as I can see this is not an issue in CEF / cefclient, or it might be a bug in my code sample.

- Open `CefSharp.WinForms.Example` from `cefsharp/47` branch
- Load http://www.html-kit.com/tools/cookietester/
- Click `Set cookie value`
- Close app
- Reopen
- Load http://www.html-kit.com/tools/cookietester/

Cookie is persisted as expected.

> I don't know how I can troubeshoot this further either..

You should be able to open `DevTools` even in `OffScreen`, just add some sort of wait like a `Console.Readline()`

**Comment by amaitland** [comment]
> it might be a bug in my code sample.

Looking very likely, https://github.com/amaitland/CefSharp.MinimalExample/blob/demo/persistcache/CefSharp.MinimalExample.OffScreen/Program.cs works for me.

**Comment by kpstolk** [comment]
Thanks for your sample, it works indeed. Still having trouble testing CefSharp, getting 'Access Violation' errors now and then, but that's not related to this issue.

**Comment by Herya** [comment]
I have the same problem. Is there an update on that ?

I access "http://www.html-kit.com/tools/cookietester/" set a cookie, then close the app, run again, and the cookie is not there anymore.
Moreover if just after setting the cookie I try to call VisitAllCookies() I have 0 cookies returned.

**Comment by zmp2000** [comment]
I Have the same problem, I´m running the pre release 65.0.0
I would like to add some information I have discovered.
I've tested the Minimal Example Offscreen and it does work!

So, if you set a **RequestContextSettings** with CachePath, it does not work at All.
If you set your CachePath dir on the CefSettings object, it will work, as long as you not declare a cachepath dir for the RequestContextSettings

I Belive this is a bug. The CachePath from RequestContextSettings should override the CefSettings.
I've tested it on CefWinForms, and it does override the CefSettings and it does work nice.

**Comment by pipiscrew** [comment]
hi @zmp2000, please check @ 
http://www.pipiscrew.com/2015/02/csharp-cefsharp-hints/

@ Browser Settings – change useragent / use cache / store cookies (CefSharp3 only)

**Comment by katzdan** [comment]
This thread helped me figure out some things about a feature I'm supposed to implement - cookie persistence but there is one aspect that needs to be addressed - are the cookies encrypted when stored in cache? if not - it would be a security concern (which means I'll have to store them manually and then reload them manually the next time a user starts a new session in my app.
So, does any one know if the cookies are encrypted when stored ?

**Comment by jankurianski** [comment]
@katzdan cookies appear to be stored unencrypted.  There is a CEF issue for adding encrypted storage support: https://bitbucket.org/chromiumembedded/cef/issues/2088/

**Comment by OoDeLally** [comment]
> You add command line args like so:
> ```
>         settings.CefCommandLineArgs.Add("renderer-process-limit", "1");
> ```

This did the trick for me, thank you!
Why does this work ?

I have a vague understanding of how Chrome uses process, thanks to this page: http://chromium-kr.blogspot.com/2012/06/about-renderer-process.html

However I dont understand why having multiple renderers messes with sessions/cookies. As far as I understand, sessions/cookies are cross-tabs and cross-renderers. e.g. I can have my facebook session open on multiple tabs and windows.

Any clue?

**Comment by amaitland** [comment]
The information in this issue is almost entirely out of date. 

If you have questions please ask them on https://magpcss.org/ceforum/index.php

CefSharp is just one of many chromium embedded framework(CEF) wrappers,  cookie handling is implementation by CEF/Chromium.
