### ISSUE TITLE
Inject JavaScript without exec/evaluate? (CORS)

### ISSUE THREAD

**Issue by rfgamaral** [cefsharp/CefSharp#845]
I first tried `ExecuteScriptAsync` as soon as the page was loaded but this didn't work for my scenario where I need to decorate some method that was already executed after the `ExecuteScriptAsync` injection.

I solved this issue by handling `GetResourceHandler`, listen for a specific JS file to be request and concat my code to the end of that file. This almost worked at first but I was given the CORS error as soon as I tried to intercept JS requests and download the files myself.

After researching for a bit, I found `BrowserSettings.WebSecurityDisabled` and set it to `true`. No more CORS error and my script was injected and ran sucessfully.

My question now becomes. Is there something wrong with this approach? Can I solve my problem any other [better] way? Or is this OK?

**Comment by amaitland** [comment]
Potentially you can add an entry to the whitelist rather than fully disable security see https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Cef.h#L213 (only merged into `master` yesterday)

`Javascript Extensions` would be handy though not implemented.
https://code.google.com/p/chromiumembedded/wiki/JavaScriptIntegration#Extensions

**Comment by rfgamaral** [comment]
That looks a little bit safer :)

But I'm confused by the parameters, could you provide a small example? What exactly would I add `targetDomain`, for instance?

**Comment by rassilon** [comment]
The CEF documentation for the function and the CEF unit tests explain this a bit better.

In the whitelist function:
* Source means: The domain you're trying to access
* Target means: The domain you're trying to access source *FROM*

So, if you had a Netflix API key for example you might want to do this:

            Cef.AddCrossOriginWhitelistEntry("https://netflix.com", "https", "mydomain.com", true);

The target domain can be String.Empty, but that means ANY web page that gets rendered can successfully do a cross-domain request to netflix.com.

Fyi,
Bill

**Comment by rfgamaral** [comment]
I'm still a little bit confused because my app is a wrapper around one specific website (always the same domain). So, am I right to assume that both the source and target will be the same domain?

**Comment by rassilon** [comment]
Possibly, I'm not sure. Your case is a bit different from most cases for cross origin violations, since you're injecting code at the end of a .js download. Seems like something you should ask in the CEF forum.

**Comment by rassilon** [comment]
Ok. So, I think the problem might be that the cross-origin whitelist appears to ONLY be for cases of redirections where the whitelist will auto-add the correct CORS headers.

If you're supplying your own response that crosses domains, you have to add your own CORS headers. 

i.e.:

        public static ISchemeHandlerResponse CreateEmptyResponse(this ISchemeHandlerResponse response, string allowedOrigin)
        {
            response.ContentLength = 0;
            response.StatusCode = 200;
            response.CloseStream = true;
            response.ResponseStream = new MemoryStream();
            if (!String.IsNullOrEmpty(allowedOrigin))
            {
                response.ResponseHeaders = new NameValueCollection(1);
                response.ResponseHeaders.Add("Access-Control-Allow-Origin", allowedOrigin);
            }
            return response;
        }

Hope this helps you, it appears to have solved my problem.

Bill

**Comment by rfgamaral** [comment]
That's the thing I don't understand, why am I getting a CORS error.

I mean, I'm loading this website and just handling the .js download myself. Even if I don't inject anything and just handle the download myself (I'm using `WebClient`) and do `return ResourceHandler.FromString(webClient.DownloadString(url));` I get the CORS error.

However, it seems we are doing things differently. To be clear, I'm handling the .js download with on `GetResourceHandler` method from `IResourceHandler`. Where would I use that piece of code?

**Comment by rassilon** [comment]
You wouldn't, but you'd use something similar. ResourceHandler has this property:

        public NameValueCollection Headers { get; private set; }

However, the bummer is that ResourceHandler.cs doesn't currently actually set the `Headers` property to an instance of the collection. Ugh.

I'll see about putting up a PR with a fix for that.

Bill

**Comment by rfgamaral** [comment]
But if the `set` is private, maybe it's there for a good reason? Just wondering... But thanks for looking into this.

**Comment by rassilon** [comment]
Set is private for a reason, it's a best practice to not make collection properties externally settable.
The solution is to create an empty NamveValueCollection in ResourceHandler's constructors.

However, the additional bummer is ClientAdapter (due to a CEF debug build issue I think I understand, I haven't tried a release build yet) doesn't call the constructor that passes the header information along at the moment.

Ugh.

Bill

**Comment by rassilon** [comment]
Yeah, the ClientAdapter.cpp mentioned crash happens in DEBUG flavor due to a missing member initializer in CEF. I'll create an upstream issue/patch. Hopefully, Marshall will apply it to 2171 branch since it's a crasher. (invokes a debug breakpoint)

Bill

**Comment by amaitland** [comment]
> Hopefully, Marshall will apply it to 2171 branch since it's a crasher. (invokes a debug breakpoint)

I imagine he will for that sort of change, might take a few days/weeks to get merged.

**Comment by amaitland** [comment]
> Yeah, the ClientAdapter.cpp mentioned crash happens in DEBUG flavor due to a missing member initializer in CEF.

Just for clarity is it the `cef.redist` package or` cef.sdk` package that has `debug` builds instead of `release` ones included? I haven't looked into this, though I'm guessing it's a slight mistake in the `build.ps1` script.

**Comment by rassilon** [comment]
I haven't really looked. Ah, WinForms.Example uses `cef.redist`.

In IDE Debug flavor it crashes, in Release flavor it's fine. 

WinForms.Examples uses `cef.redist`, and CefSharp.Core uses `cef.sdk`.

Bill

**Comment by amaitland** [comment]
`cef.redist` contains `libcef.dll`, locales, etc.
`cef.sdk` contains the header files and `libcef_dll_wrapper`, only required for building the `CefSharp C++` libs.

Does switching between `Debug` and `Release` in `VS` resolve the problem?

**Comment by rassilon** [comment]
Yep.

Bill

**Comment by rassilon** [comment]
Ah, here's the issue. libcef_dll_wrapper (which is where the actual problem is) is a static library that comes in a Debug version with `cef.sdk`.

Bill

**Comment by amaitland** [comment]
> Ah, here's the issue. libcef_dll_wrapper (which is where the actual problem is) is a static library that comes in a Debug version with cef.sdk

There should be a `Release` version as well, and it should choose based on the build configuration.

**Comment by rassilon** [comment]
Oh, it does choose correctly based on build config. That's why just the `Debug` version has the problem though. I went looking after you explained how the NuGet Pkgs are structured.

**Comment by amaitland** [comment]
Oh cool, you had me worried for a minute there that we had been shipping debug builds :smile: Perhaps for now we switch to the full `CefStreamResourceHandler` constructor and add a comment in saying the code doesn't work for a `Debug` build and hopefully revisit when the `upstream` patch has been applied?

**Comment by rassilon** [comment]
Works for me. I'll push the change up in the PR.

**Comment by rassilon** [comment]
I've submitted a patch against CEF trunk against issue [1187]( https://code.google.com/p/chromiumembedded/issues/detail?id=1187) for the debug build issue.

**Comment by rfgamaral** [comment]
Wow... A lot of work around this issue :)

Can you guys please sum it up and translate what all that means for guys like me which are not very knowledgeable about CEF?

**Comment by rassilon** [comment]
Debug builds of CefSharp.Core can trigger a debugger breakpoint CPU instruction (`int 3`) due to an upstream CEF bug. (after my `ClientAdapter.cpp` change that @amaitland committed for me)
Release builds of CefSharp.Core don't have this problem.

Bill

**Comment by amaitland** [comment]
Basically you can now set `Headers` and `StatusCode/Text` when using a `ResourceHandler`

**Comment by rassilon** [comment]
Marshall has pushed the Debug bug fix to 2171, just need to wait for cefbuilds.com to pick it up, @amaitland .

Bill

**Comment by avspeed** [comment]
Once a patch makes into one of the builds on cefbuilds.com, what is the process to integrate it into cefsharp ?

**Comment by amaitland** [comment]
@avspeed Are you askin as a general question or specifically about this fix?

**Comment by avspeed** [comment]
@amaitland thanks. I am asking in general.

**Comment by amaitland** [comment]
For this fix someone just has to ask nicely :smile: 

In general if upgrading to a new branch then we need to upgrade the https://github.com/cefsharp/cef-binary project, then upgrade the main project to use the new nuget packages.

We usually wait for an official upstream release before putting out an official release. Once '39.0.0' is released I'll prob create a new 'unstable' branch. If you need a version based on a newer branch then feel free to open a new issue and we can discuss as a wider group.

**Comment by avspeed** [comment]
Thank you very much for the explanation and thank you for this project.

**Comment by rfgamaral** [comment]
Thanks a lot for all the work involved in "fixing" this.

Feel free to close the issue whenever it suits you best :)
