### ISSUE TITLE
Textarea Placeholder Ghosting

### ISSUE THREAD

**Issue by pipiscrew** [cefsharp/CefSharp#846]
![snap508](https://cloud.githubusercontent.com/assets/3852762/6372883/ba9d1832-bd0f-11e4-88f4-04294fedc4ed.png)

for test navigate to 
http://jsfiddle.net/DTcHh/4815/

FYI the debug.log :
[0225/165526:ERROR:renderer_main.cc(207)] Running without renderer sandbox
[0225/165618:WARNING:message_in_transit_queue.cc(18)] Destroying nonempty message queue

**Comment by amaitland** [comment]
You should also include `WinForms`, `WPF` or `OffScreen`. Potentially architecture as well though potentially not relevant in this case.

Issue should be completely self contained. See https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue there's a `Report bug template` link that's a handy place to start.

**Comment by amaitland** [comment]
Also are you using a High DPI display?

**Comment by pipiscrew** [comment]
I cant find **dpi setting** on Graphics as is on **windowsXP**, 
for windows 7 - http://www.sevenforums.com/tutorials/443-dpi-display-size-settings-change.html
for windows 8 - http://nvidia.custhelp.com/app/answers/detail/a_id/3153/~/adjusting-windows-8-display-size%2Fscaling-for-high-dpi%2Fppi-monitors

my machine specs : 
![snap513](https://cloud.githubusercontent.com/assets/3852762/6409912/3d5276d8-be72-11e4-86f3-b0b83a279e65.png)

**Comment by amaitland** [comment]
'-pre03' is out, has a slightly newer version of 'CEF'

**Comment by amaitland** [comment]
Are you using `WinForms` or `WPF`?

**Comment by pipiscrew** [comment]
winforms, didnt happen to your app?

**Comment by amaitland** [comment]
Looks like an `upstream` issue

See https://code.google.com/p/chromiumembedded/issues/detail?id=1563&start=200

**Comment by amaitland** [comment]
Update `bitbucket` link https://bitbucket.org/chromiumembedded/cef/issues/1563

**Comment by amaitland** [comment]
Tested with http://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_textarea_placeholder

Problem persists in `43`, resolved in `45`
