### ISSUE TITLE
cefsharp related dlls not found

### ISSUE THREAD

**Issue by sumnamalik** [cefsharp/CefSharp#847]
I am not able to find the cefsharp related dlls like cefsharp.dll, cefsharp.windowsform.dll,icudt.dll and libcef.dll.

Please let me know where i can find these for me to run the web browser control properly in my c#.net project

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp#nuget-packages

**Comment by sumnamalik** [comment]
it is not working. could you please provide me with the dlls so that i can add them to my project reference.

thanx

**Comment by almalkawi** [comment]
@sumnamalik what is not working? When you install the NuGet packages (see link from Alex), you will get all the binaries you need.

**Comment by sumnamalik** [comment]
how do i install the NuGet package?

**Comment by sumnamalik** [comment]
while installing it is showing me an error " the underlying connection was closed. an unexpected error occured on send."

**Comment by pipiscrew** [comment]
@sumnamalik read : 
http://bit.ly/1FYLrTK

**Comment by amaitland** [comment]
Make sure you have the latest `nuget` version installed.

**Comment by amaitland** [comment]
@sumnamalik Any further comment? Can we close this?

**Comment by sumnamalik** [comment]
Yes you can close this.
