### ISSUE TITLE
sockets and ssl certificate support

### ISSUE THREAD

**Issue by sumnamalik** [cefsharp/CefSharp#848]
does cefsharp support sockets and ssl certificate as this is the main part of my project.

**Comment by jornh** [comment]
See http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=12010 ... looks like some upsteram CEF implementation is needed. (If I understood your question correctly?)

**Comment by rassilon** [comment]
Just to clarify for this CefSharp issue, jornh's link presumes you mean WebSockets and client SSL certificate support.

Bill

**Comment by sumnamalik** [comment]
Yes I mean the same. Does it support?

**Comment by rassilon** [comment]
No, CefSharp and CEF both do NOT currently support client SSL certificates.

Bill

**Comment by sumnamalik** [comment]
Thank you. Do you have any idea if webkitdotnet or openwebkitsharp
supports?? Or any other embedded web browser control based on chromium
which is open source?? I would really appreciate your help.

Thanx

**Comment by rassilon** [comment]
No idea. However, both of those projects you mention haven't had a commit since sometime in 2013.

You can always look at the source code for Chrome to determine what work is needed in CEF and scratch your own itch.

Bill

**Comment by sumnamalik** [comment]
I am very much new to embedded web browser and doesn't have much time to
break my head on this.. Anyway thank you so much.
