### ISSUE TITLE
Bug: Can not load file or assembly 'CefSharp.Core.dll' or one of its dependencies

### ISSUE THREAD

**Issue by pipiscrew** [cefsharp/CefSharp#850]
#### Issue Summary
I have create a test application WinFormsFramework4x86, uses CefSharp3, where on Form1.ctor instantiate the browser. The test application running ok on my dev-machine (win8x64). 
Distribute at **Client2PC** (win8x64) working.
Distribute at **Client3PC** (win8x64) working.

Distribute at **Client4PC** (win8x64) no working.

all PCs get the application + dependencies by the same zip file (verified 3times)

#### Steps to Reproduce
run the application

//Does this problem also occur in the `Cef` TestApp from http://cefbuilds.com?
//use cef_binary_3.2295.2034_windows32_client.7z

even use x86 or x64 TestApp writes a debug.log as : 
Couldn't mmap v8 natives data file

Windows Error Dialog Displayed then ends.

^this occurred (TestApp) on dev-machine + ClientPC4

#### Technical details
The )my) application custom exception handler log :
Executable Path: C:\Users\client4PC\Desktop\TestAppCRM\TestAppCRM.exe
Product Version: 1.2.0.0
CLR Version: 4.0.30319.34014

Exception : System.IO.FileNotFoundException
   Message: Can not load file or assembly 'CefSharp.Core.dll' or one of its dependencies.
   Source: TestAppCRM
   Target Site: Void .ctor()

Exception Stack Trace

   at TestAppCRM.Form1..ctor()
   at TestAppCRM.Program.Main()

Environment Stack Strace

   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at ErrorReporter.UpdateStackTrace(Exception e)
   at ErrorReporter..ctor(Exception e)
   at TestAppCRM.Program.CurrentDomain_UnhandledException(Object sender, UnhandledExceptionEventArgs e)
   at TestAppCRM.Form1..ctor()
   at TestAppCRM.Program.Main()

I installed VC 2010x86 + x64 runtimes... without hope...

**Comment by jornh** [comment]
> I installed VC 2010x86 + x64 runtimes... without hope...

Are you building CefSharp from source or using the official CefSharp NuGet binaries? With official NuGet you need VC 20**12** redistributable. If you build CefSharp from source you need the VC version matching your compiler version. 

https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#Runtime_dependencies (last bullet)


Dependency Walker and comparing your different machines might help, see #409

**Comment by amaitland** [comment]
Make sure you compile in 'Release' if building from source.

**Comment by pipiscrew** [comment]
hi, 

using NuGet x86 libs, as **Jornh** pointed out, installing VC++2012x86 on win8x64 - solve the problem

thanks all!

**Comment by KingTsunamy** [comment]
Can someone just give the dlls from the latest version ? Spent half a day trying all the solutions and nothing worked :(

**Comment by amaitland** [comment]
This issue is three years old and information contained within it is no longer relevant. 

If you are having problems deploying CefSharp then read the FAQ

https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#Runtime_dependencies

If you require further assistance then read https://github.com/cefsharp/CefSharp#contact
