### ISSUE TITLE
mpeg-dash streaming is not rendering in cefsharp

### ISSUE THREAD

**Issue by chebyrenok** [cefsharp/CefSharp#851]
trying to play mpeg - dash format http://dashif.org/reference/players/javascript/1.3.0/samples/dash-if-reference-player/index.html. does not render in wpf sample. Desktop chrome is rendering fine. I would expect chromium would be able to render this format. using cefsharp3 latest. Chrome supports this format since version 23. in outmessage in sampe I saw it tries to locate certain codecs but fails saying codec not supported and stream is not found.

**Comment by jankurianski** [comment]
Hi, could you add a little more detail about what you're trying - follow this guide:
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue

And also see if it works in the official chromium-embedded test app.  Here are instructions for launching the app with parameters that match our WinForms or WPF controls:
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

**Comment by chebyrenok** [comment]
I am trying to deremine if CEF supports rendering of mpeg-dash stream
http://dashif.org/reference/players/javascript/1.3.0/samples/basic-page-embed/auto-load-single-video.html i put this url in wpf starter sample and video is not rendering.
if you load this link in desktop chrome it renders video

**Comment by jankurianski** [comment]
> I am trying to deremine if CEF supports rendering of mpeg-dash stream

CefSharp is a wrapper around CEF, but there are often differences in configuration or implementation that causes something to work in CEF but not in CefSharp.

Can you try the mpeg-dash stream on the `cefclient.exe` test app and let us know if it works in CEF?  That would be really helpful :+1: 

You can find instructions here
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

**Comment by chebyrenok** [comment]
Thank you for taking the time and looking into it. I will run client test app as soon as get chance and will report my results here

**Comment by chebyrenok** [comment]
I ran the cefclient.exe test app and mpeg-dash is not rendering. I have console.log file generated.
Message: Converted video element to dash.js player and added content: http://dash.edgesuite.net/envivio/dashpr/clear/Manifest.mpd

Source: http://dashif.org/reference/players/javascript/1.3.0/dist/dash.debug.js

Line: 10143

-----------------------

Message: Parsing complete: ( xml2json: 10ms, objectiron: 4ms, total: 0.014s)

Source: http://dashif.org/reference/players/javascript/1.3.0/dist/dash.debug.js

Line: 10143

-----------------------

Message: Manifest has loaded.

Source: http://dashif.org/reference/players/javascript/1.3.0/dist/dash.debug.js

Line: 10143

-----------------------

Message: Manifest has been refreshed.

Source: http://dashif.org/reference/players/javascript/1.3.0/dist/dash.debug.js

Line: 10143

-----------------------

Message: MediaSource is open!

Source: http://dashif.org/reference/players/javascript/1.3.0/dist/dash.debug.js

Line: 10143

-----------------------

Message: [object Event]

Source: http://dashif.org/reference/players/javascript/1.3.0/dist/dash.debug.js

Line: 10143

-----------------------

Message: Added 0 inline events

Source: http://dashif.org/reference/players/javascript/1.3.0/dist/dash.debug.js

Line: 10143

-----------------------

Message: video codec: video/mp4;codecs="avc1.4D400D"

Source: http://dashif.org/reference/players/javascript/1.3.0/dist/dash.debug.js

Line: 10143

-----------------------

Message: videoCodec (video/mp4;codecs="avc1.4D400D") is not supported.

Source: http://dashif.org/reference/players/javascript/1.3.0/dist/dash.debug.js

Line: 10143

-----------------------

Message: No buffer was created, skipping video data.

Source: http://dashif.org/reference/players/javascript/1.3.0/dist/dash.debug.js

Line: 10143

-----------------------

Message: audio codec: audio/mp4;codecs="mp4a.40.2"

Source: http://dashif.org/reference/players/javascript/1.3.0/dist/dash.debug.js

Line: 10143

-----------------------

Message: audioCodec (audio/mp4;codecs="mp4a.40.2") is not supported.

Source: http://dashif.org/reference/players/javascript/1.3.0/dist/dash.debug.js

Line: 10143

-----------------------

Message: No buffer was created, skipping audio data.

Source: http://dashif.org/reference/players/javascript/1.3.0/dist/dash.debug.js

Line: 10143

-----------------------

Message: No text data.

Source: http://dashif.org/reference/players/javascript/1.3.0/dist/dash.debug.js

Line: 10143

-----------------------

Message: No streams to play.

Source: http://dashif.org/reference/players/javascript/1.3.0/dist/dash.debug.js

Line: 10143

**Comment by chebyrenok** [comment]
looks like chromiium is missing certain codecs, Can these be added into chromium? 
Message: videoCodec (video/mp4;codecs="avc1.4D400D") is not supported.

**Comment by rassilon** [comment]
Chromium is likely missing certain codecs just like its missing the MP3 decoder codec. Google for Desktop *Chrome* pays license holders for the right to distribute the decoders. If you pay the license holders you could go through the steps to have a CEF build that has those codecs enabled.

Regardless, this clearly isn't a CefSharp issue.

Bill

**Comment by chebyrenok** [comment]
Bill, Thank you for your response

**Comment by jornh** [comment]
> looks like chromiium is missing certain codecs, Can these be added into chromium?

As @rassilon says, it's:
* a legal/financial matter (you need to license codecs etc) 
* technically do your own build of CEF binaries from source with the codecs replacing/adding to what CefSharp includes via the `cef.redist.[x86|x64]` NuGet  

Closing!

**Comment by netroby** [comment]
http://www.openh264.org/  seems cisco have open h264. can we built support with it?
