### ISSUE TITLE
Clean build fails when running with MSBuild v12.0

### ISSUE THREAD

**Issue by ljani** [cefsharp/CefSharp#853]
The errors:
```
The type or namespace name 'CefSharp' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'CefSharp' could not be found (are you missing a using directive or an assembly reference?)
```

Setup:
- TFS 2013u4
- Windows Server 2012R2
- MSBuild v12.0
- [MSBuild task](https://msdn.microsoft.com/en-us/library/z7f65y0d.aspx) is invoked through MSBuild script
- Project is using `ToolsVersion="12.0"`

Checklist:
- The platform is set correctly to x86
- The binaries' `HintPath`s are correctly correctly resolved to `CefSharp.Common.37.0.0\build\..\CefSharp\x86\CefSharp.dll`, `CefSharp.Common.37.0.0\build\..\CefSharp\x86\CefSharp.Core.dll` and `CefSharp.WinForms.37.0.0\build\..\CefSharp\x86\CefSharp.WinForms.dll`
- But MSBuild fails to associate those `Reference`s and `HintPath`s with the project and thus it won't pass them to `csc.exe`
- Other NuGet packages work fine (for example [Magick.NET-Q8-x86](https://www.nuget.org/packages/Magick.NET-Q8-x86/))

Short example of the `build.msbuild` file:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="12.0">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Release</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">x86</Platform>
  </PropertyGroup>
  <Target Name="Build">
    <MSBuild Projects="..\Solution\MyProject.sln" Properties="VisualStudioVersion=12.0;Configuration=$(Configuration);Platform=$(Platform)" StopOnFirstFailure="true" Targets="Rebuild" ToolsVersion="12.0"/>
  </Target>
</Project>
```

Possible solutions:
- Getting rid of the `Import`s somehow?
- Figure out how to properly reference the assemblies?

Initial discussion at #205, but I created a new issue, because I guess the original reporter had a different issue and was not using MSBuild. More logs in the #205 issue, especially in [this comment](https://github.com/cefsharp/CefSharp/issues/205#issuecomment-76351601)

**Comment by ljani** [comment]
Ha.. I think I found the issue. Comparing manually invoked `msbuild` and `msbuild` invoked by TFS, there's this difference in the environment variables:
```
VCBuildOverride = C:\Builds\Agents\5\MyCollection\MyProject\src\Scripts\Build.msbuildproj.x86.Debug.vsprops
```
Now I need to hunt down where does that come from...

**Comment by ljani** [comment]
Turns out it's not about `VCBuildOverride`.

If I clean my `packages` directory and try to build the solution, it fails. But if I do not clean it, the solution compiles fine with or without `VCBuildOverride`.

**Comment by ljani** [comment]
Okay, so you can leave TFS out of this. I got it failing on my local computer as well. Here are steps to reproduce this:
- Create a project, which references from a file CefSharp
- Build the project from Visual Studio 2013, it should be okay
- Delete `cef.redist.x64.3.2062.1898`, `cef.redist.x86.3.2062.1898`, `CefSharp.Common.37.0.0`, `CefSharp.WinForms.37.0.0` in the `packages` directory
- Open `Developer Command Prompt for VS2013`
- Run `msbuild MyProject.csproj /p:Configuration=Debug /p:Platform=x86`

Again, I'm using MSBuild v12.0:
```
MyProject> msbuild /version
Microsoft (R) Build Engine version 12.0.31101.0
[Microsoft .NET Framework, version 4.0.30319.34209]
Copyright (C) Microsoft Corporation. All rights reserved.

12.0.31101.0
```

**Comment by amaitland** [comment]
http://www.xavierdecoster.com/migrate-away-from-msbuild-based-nuget-package-restore

> The MSBuild-based NuGet package restore has issues. For one: it's MSBuild-based. This means that anything that happens during package restore is run within the MSBuild process, which is particularly annoying for packages that want to modify project files and inject MSBuild targets (as these aren't picked up until the next run).

**Comment by amaitland** [comment]
@ljani Great work on troubleshooting the issue :+1: I'm going to mark this as `faq-able`.

As part of our own build process we manually restore packages before build.

Happy to close this?

**Comment by amaitland** [comment]
This is also probably relevant.

http://docs.nuget.org/consume/package-restore/migrating-to-automatic-package-restore

**Comment by ljani** [comment]
@amaitland Thanks! And thanks for the links.

Sorry, lunch got in the way. Before lunch, I was reading the same article. I'll let you guys know how it goes. So far I've ran [the clean scripts](https://github.com/owen2/AutomaticPackageRestoreMigrationScript), which seemed to automate everything nicely. Next up is figuring out [how to make TFS restore the new packages](http://blogs.msdn.com/b/dotnet/archive/2013/08/27/nuget-package-restore-with-team-foundation-build.aspx).

**Comment by amaitland** [comment]
We do something similar with our powershell build script https://github.com/cefsharp/CefSharp/blob/master/build.ps1#L235

So hopefully the `msbuild` version is just as easy.
```
<Target Name="RestorePackages">
    <Exec Command="&quot;$(MSBuildThisFileDirectory)tools\NuGet\NuGet.exe&quot; restore &quot;%(Solution.Identity)&quot;" />
</Target>
```

**Comment by ljani** [comment]
@amaitland Success! :) Did that, except I didn't check NuGet to TF, instead read its path as follows:
```
  <PropertyGroup>
    <TFSToolsPath>$(Registry:HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\TeamFoundationServer\12.0@InstallPath)\Tools\</TFSToolsPath>
  </PropertyGroup>
  <Target Name="RestorePackages">
    <Exec Command="&quot;$(TFSToolsPath)NuGet.exe&quot; restore &quot;%(Solution.Identity)&quot;" />
  </Target>
```

Okay, quick recap:
- The problem was indeed the old `Enable package restore`
- To get rid of it, I ran [the wonderful scripts](https://github.com/owen2/AutomaticPackageRestoreMigrationScript) by @owen2, thanks!
- Configured the msbuild script to restore the packages before build [as instructed](http://docs.nuget.org/consume/package-restore/team-build).

Again, thanks for support!

**Comment by amaitland** [comment]
> Okay, quick recap:

@ljani Thanks for the recap, very useful for other ppl :+1:

**Comment by owen2** [comment]
@ljani Glad I could help! :smile:

**Comment by amaitland** [comment]
I've upgraded `master` and `MinimalExample` to use the newer `nuget` restore method.
