### ISSUE TITLE
Immediate Loading of URL Triggers "Aborted" Error

### ISSUE THREAD

**Issue by tbowers** [cefsharp/CefSharp#859]
When writing a library wrapper around the `ChromiumWebBrowser `, it seems very reasonable to want to do the following.

```
Wrapper w = new Wrapper();
// sometime later in loading of the program, retrieving resources, etc.
w.HomeUrl = "www.google.com";
w.GoHome();
```

However, I'm finding that when `GoHome()` hits and subsequently calls `.Load(url)`, that my `LoadError` handler is hit saying it was `Aborted`.

If I introduce a delay before `GoHome()`, it seems to work so I'm guessing that I'm attempting to do this while `ChromiumWebBrowser` is still initializing? Why does its `ctor` want an address immediately? It seems reasonable to use "about:blank" or something here if you know it's going to be specified later.

To work around this I was looking for somewhat to know the browser had finished loading and then navigate home so I added the following to my to my `IsBrowserInitializedChanged` handler.

```
 void browser_IsBrowserInitializedChanged(object sender, CefSharp.IsBrowserInitializedChangedEventArgs e) {
            if (e.IsBrowserInitialized) {
                NavigateHome();
            }
        }
```

This also doesn't appear to solve the problem. Any other workarounds?

**Comment by amaitland** [comment]
Can you provide some additional information please, `WinForms`, `WPF`? Version?

See https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue for more info

**Comment by tbowers** [comment]
Ah I apologize for that. I have been using the `WinForms` controls. I built the latest v39 tag and have been using the resulting artifacts from that.

**Comment by amaitland** [comment]
Calls to `Load` need to be made on the `UI` thread.

Try

```c#
private void BrowserIsBrowserInitializedChanged(object sender, IsBrowserInitializedChangedEventArgs e)
{
	if(e.IsBrowserInitialized)
	{
		this.InvokeOnUiThreadIfRequired(() => browser.Load("www.google.com.au"));
		
	}
}
```

**Comment by tbowers** [comment]
That doesn't appear to have any affect on behavior (though is a good check to have in place).

I believe this is a timing issue. If I immediately navigate home after creating my browser, that `.Load()` is aborted. However when I wait a few seconds and then click a button that triggers the same `GoHome` behavior, the page loads fine.

Could it be tied to where/how I call initialize? I tried putting it in the static `ctor` of my wrapper but that didn't appear to work so I added a `static bool initialized = false` flag and then added the following to my `ctor`.

```
            if (initialized == false) {
                CefSettings settings = new CefSettings();
                settings.IgnoreCertificateErrors = true;
                Cef.Initialize(settings);
                initialized = true;
            }
```

**Comment by amaitland** [comment]
Demo using the `WinForms Example` as a base https://github.com/amaitland/CefSharp/commit/4ec33c668bc924677d7eaf68756ce90d6e303336

You can only effectively call `Cef.Initialize()` once, see https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Cef.h#L153

**Comment by amaitland** [comment]
If your still having problems then please modify one of the examples to reproduce your problem.

**Comment by tbowers** [comment]
I've modified the WinForms example here (https://github.com/tbowers/CefSharp/commit/cb0aae35bd44660bafc1b675d6dcb4bbc2d54eaf).

You can see I immediately try to load another page and that page will not load. One difference I do see on master as of today (3/5/15) is that my `LoadError` handler is not called.

**Comment by amaitland** [comment]
> You can see I immediately try to load another page and that page will not load.

As it stands you either pass in a `Url` into the constructor or wait for the browser to initialize before calling `Load`. Should you wait for initialze you'll need to call `Load`

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/commit/602ba52ad5e67453130a5e1be9671b2e83fb2973

**Comment by tbowers** [comment]
Ok that appears to be working as expected. If I hook up the `IsBrowserInitializedChanged`, then change the URL, it works. Thanks so much.
