### ISSUE TITLE
failed to get the cef.sdk for the version 3.2171.1979

### ISSUE THREAD

**Issue by karliehgf** [cefsharp/CefSharp#860]
yesterfday after i updated the source code into the latest version (cefsharp 39.0.0), it couldn't get the cef.sdk when compiling the project. it didn't work when using the Package Manager Console.

**Comment by amaitland** [comment]
What was the error message? Have you tried a `nuget restore` using the command line?

The package is https://www.nuget.org/packages/cef.sdk/3.2171.1979 and has been downloaded over 700 times, so I'm thinking this is more likely a communications issue?

**Comment by amaitland** [comment]
You should also make sure `VS` has the latest `nuget` extension installed.

**Comment by karliehgf** [comment]
When i run the command in Package Manager Console like this:
Install-Package cef.sdk 
it installed the cef.sdk 3.2062.1898 instead of 3.2171.1979
And when run the command like this:
Install-Package cef.sdk -Version 3.2171.1979
it was failed and the error message was:
 + Install-Package <<<<  cef.sdk -Version 3.2171.1979
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by amaitland** [comment]
> You should also make sure VS has the latest nuget extension installed.

Check your version. If that fails then do a restore from the command line.

**Comment by amaitland** [comment]
I've updated to using the latest `nuget restore` method which better suites our project.

See https://github.com/cefsharp/CefSharp/commit/a7946d53d0b5c44a2e3403886888bd1cd2b198dd

Feel free to grab the latest `master` and try again.

**Comment by karliehgf** [comment]
thanks so much.
i tried again but still nothing works.
i have updated the nuget extension to the version 2.8.50926.663 in VS2013, is it right?
but this time, the error message was:
![image](https://cloud.githubusercontent.com/assets/8002468/6521831/77c7a0d6-c417-11e4-8127-3c6d261b3d43.png)
it still seems that it can't find the cef.sdk for the version 3.2171.1979 from the remote server。

**Comment by amaitland** [comment]
I made one more change, see https://github.com/cefsharp/CefSharp/commit/649c4973874fdcdee4d1be16278aabb5e56c34c4

Try again.

Was there there a particular reason you need to build from source?

**Comment by karliehgf** [comment]
wahaha~~
So happy it allready works sucessfully!!
So much thanks!!
:+1: :+1:

**Comment by amaitland** [comment]
Anything else before I close this?
