### ISSUE TITLE
logoff automatically (?)

### ISSUE THREAD

**Issue by pipiscrew** [cefsharp/CefSharp#861]
here I develop & maintain a CRM, written on PHP... 

When using a browser, users logon, on morning and logoff at afternoon normally without the system transfer them for second time on login page.

When users using the winforms app w/ CefSharp3 as :
```javascript
            var settings = new CefSettings();
            settings.CachePath = cache_dir;
            settings.CefCommandLineArgs.Add("persist_session_cookies", "1");

            Cef.Initialize(settings);
```

This occurs on all clients > 
after 4-5hours of use, going to CRM login page (my top.php code is code like :
```javascript
<?php
	session_start();

	if (!isset($_SESSION["u"])) {
		header("Location: login.php");
		exit ;
	}
```

users re-login, no problem, the strange thing is after second logon there is no **PHPSESSID** variable!!!! in cookies!! totally strange!!!

I have to disable the cache?

thanks!

**Comment by pipiscrew** [comment]
manually, deleting files :
Cookies
Cookies-journal

//which enabled/created by this switch 
```javascript
settings.CefCommandLineArgs.Add("persist_session_cookies", "1");
```

looks that fix the problem, I will post back when this verified.

**Comment by pipiscrew** [comment]
confirm the **persist_session_cookies** made the confusion... 

DELETE it, all working flawless...

**Comment by pipiscrew** [comment]
the past days all working flawless (as I wrote), yesterday the problem occured (there is no PHPSESSID variable)

today, code made as 

```javascript
       public Form1()
        {
            InitializeComponent();

            Directory.CreateDirectory(General.cache_dir);
			
            try
            {
                if (File.Exists(General.cache_dir + "\\Cookies"))
                    File.Delete(General.cache_dir + "\\Cookies");

                if (File.Exists(General.cache_dir + "\\Cookies-journal"))
                    File.Delete(General.cache_dir + "\\Cookies-journal");
            }
            catch (Exception e) { MessageBox.Show(e.Message, "ERROR!"); }

            var settings = new CefSettings();
            settings.CachePath = General.cache_dir;

            Cef.Initialize(settings);
```

![snap548](https://cloud.githubusercontent.com/assets/3852762/6615857/79db5d16-c8b0-11e4-95b3-160156c3f71d.png)

I will update the topic after a week!

thanks

**Comment by jornh** [comment]
@pipiscrew any news on this?

**Comment by pipiscrew** [comment]
deleting the files mention above the 'bug' not appear again.. 

thanks for your time..

**Comment by amaitland** [comment]
https://bitbucket.org/chromiumembedded/cef/issue/1595/cookies-are-deleted-suddenly-with-cache

Just as an FYI, it's interesting to know that `CEF` performs cleanup tasks periodically on the cache folder, which can delete cookies. Changing the path might be worth while see https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Cef.h#L397

Just putting this as a note incase it's relevant to anyone else.
