### ISSUE TITLE
WPF: Select dropdown displays properly the first time but is shifted to the left every time after that

### ISSUE THREAD

**Issue by jeffxpx** [cefsharp/CefSharp#864]
Hello,

You guys are probably sick of seeing these issues that revolve around the select element.  I've got one more for you.

To reproduce the problem:

1. Instantiate a ChromiumWebBrowser instance using the CefSharp.Wpf package (still there as of 39.0.0-pre3 and in the nightly build--I'm using the x86 flavor). 
2.  Load up facebook.com on it.
3. All you need to do is click on the month, day, or year dropdown.  
   * The first time you click it, everything shows up as it should.  
   * The second time you click that dropdown or any dropdown at all, the X positioning is wrong.  It's almost as if it's trying to set the X position to so the rightmost pixel is where the leftmost pixel is.

I tried it in the upstream build and it works there.  I originally tried it in build 2039, but I found the 1979 test app as well and it worked there too.

Here's a quick video of it working in build 2039 of the upstream test app: http://youtu.be/swg3SIRNT4w
Here's a quick video of it *not* working in a sample WPF test app: http://youtu.be/xUdJkYg5Clg

**Sadly, this doesn't have anything to do with resizing or moving the window and calling NotifyMoveOrResizeStarted does not help.**  I already tried that using a small JS shim that I wrote and inject using EvaluateScriptAsync().  The script creates an onchange handler for every select it finds and calls dropdownWorkaround() on a bound object.  The DropdownWorkaround() method consists of this:

```c#
        public void DropdownWorkaround()
        {
            // _browser is the ChromiumWebBrowser instance.
            var field = _browser.GetType()
                .GetField("managedCefBrowserAdapter", BindingFlags.Instance | BindingFlags.NonPublic);

            var adapter = (ManagedCefBrowserAdapter) field.GetValue(_browser);

            adapter.NotifyMoveOrResizeStarted();
        }
```

I looked through the code for ChromiumWebBrowser.SetPopupSizeAndPositionImpl and it looks like it's relying on matrix and a mouse point for its positioning.  Matrix is a private variable that is updated in a different method and the point is passed in as an argument.

Any ideas on what could be causing this?

**Comment by amaitland** [comment]
`SetPopupSizeAndPosition` is actually for the tooltip, not for the dropdown, so unlikely to be causing your problem.

Are you using a non standard `DPI`? What operating system are you using? Are you able to test on a different machine?

I'm not seeing a problem on `Windows 7 SP1` running at `1080`. So there must be some other factor coming into play?

There is currently work going on to rewrite the `High DPI` support which might be worth checking out, see #858, in particular check out https://github.com/bjarteskogoy/CefSharp/tree/enhancement/wpf-high-dpi

**Comment by jeffxpx** [comment]
The machine that's having the issue is Windows 8.1 Update 1 or whatever the latest Windows 8.1 is.  I can confirm that it works fine on Windows 7 SP1.  

I can also confirm that it works in WinForms on my Windows 8.1 machine.  It's just the WPF code that's not behaving correctly.

I had the DPI settings at whatever the normal setting is.  I also tried turning the scaling up a notch, but that didn't fix the issue.  The good news is whatever that is didn't affect it either way.  It was still the same sort of offset on your branch.  It was up the to the left quite a bit on the bjarteskogoy branch.

I checked out both the bjarteskogoy and your branch of the wpf-high-dpi branch and neither yours nor bjarteskogoy fixes the issue.  I like the CefSharp.Wpf.Example project better than my test project and I can build from the source, so any screen casts I do will use that going forward.  

SetPopupSizeAndPosition is actually for the dropdown.  The ToolTips use something else.  "Popups" in WPF is for things like ComboBoxes and auto-completes so it makes sense that it's a "Popup" in WPF.  It's a cool hack.  If I read the code correctly, the Popup displays a rendered bitmap in the right position.  The SetPopupSizeAndPosition call is probably not causing the problem, though.  It's probably something in the call stack before that.

Also, I don't know if you noticed it before, but the mouse tracking is spot on even when the Popup is displayed incorrectly.

Check out this screencast (with mic audio): http://youtu.be/l1MBd9HJSWE

I think it answers all of your questions a bit better than just text can.

I'm going to keep digging into the source and see what I can find.

**Comment by jeffxpx** [comment]
It gets more interesting!  I added a simple Debug.Print statement to give me what was being passed to the function so it could display the Popup.

I got this line the first time I opened the Popup: 

Popup set to: 72 x 210, moved to: 877, 453

I got this line the second time I opened the Popup:

Popup set to: 72 x 210, moved to: 877, 453

So...a quick google search turns up that Windows / WPF is trying to be "helpful" for people with touch screens.  It will flip the orientation of popups and tooltips for a left/right-handed preference.  You may want to put this in the FAQ.

It's not you, it's Windows!  You were sending the right point, but windows was choosing to re-orient the dropdown!

http://stackoverflow.com/questions/18113597/wpf-handedness-with-popups?answertab=votes#tab-top
