### ISSUE TITLE
Accessing the Address in a RequestHandler to determine if the request is the main page and not a css page, a iframe etc

### ISSUE THREAD

**Issue by Jayman1305** [cefsharp/CefSharp#865]
Anything as simple as this throws a exception in wpf.
The calling thread cannot access this object because a different thread owns it.
Trying anything like this also doesnt help as OnBeforeResourceLoad is not static
string currentUrl;
Dispatcher.BeginInvoke((Action)(() => currentUrl = browser.Address));

bool IRequestHandler.OnBeforeResourceLoad(IWebBrowser browser, IRequest request, IResponse response)
{

}

**Comment by amaitland** [comment]
Look at `request.Url` for the current url.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp/IRequest.cs#L11

Also please markup code, it's very hard to read.

**Comment by Jayman1305** [comment]
Thanks @amaitland I think i didn't word my query correctly. What i mean is how do i get the browser address, not the request.Url of the current resource which could be the page but could also be scripts images etc. Im trying to avoid looking at the headers to get the mime type etc

**Comment by amaitland** [comment]
Gotcha. The best way would be for 'CefSharp' to expose at least the basic frame information that's passed in from 'CEF' currently and basically ignored.

With the exception your seeing does it make any difference if you cast 'IWebBrowser' to 'ChromiumWebBrowser' and use it's dispatcher? You'll have to call 'Invoke' as you need a sync call so you can return the appropriate bool.

**Comment by Jayman1305** [comment]
Afraid that doesn't help either. I exposed my view model to get around this for now but i think it would be helpful if we could get the URL of the main page in the handler. ;-)

**Comment by amaitland** [comment]
Feel free to submit a PR :+1:

**Comment by amaitland** [comment]
Closing with merge https://github.com/cefsharp/CefSharp/commit/0572ef6a253014a740fa62ce4f2cf9039f894e0c
