### ISSUE TITLE
C# .Net 4.0 Winforms Right Click "Copy Link Address"

### ISSUE THREAD

**Issue by daveaton** [cefsharp/CefSharp#866]
I was wondering how and where to start searching on how to implement a new item in the right click menu?

Here is what I would like to see.

http://www.eatoncode.com/shareit/2015-03-07_1841.png

I often right click and copy or save the link address to book mark manually especially from iframes ect.

Is there a way to add new menu items to the right click or hide existing items such as print ?

From url: http://magpcss.org/ceforum/apidocs3/projects/(default)/cef_context_menu_handler.h.html

I can see this code.

       ///
       // Returns the link URL, if any, to be used ONLY for "copy link address". We
       // don't validate this field in the frontend process.
       ///
       /*--cef()--*/
       virtual CefString GetUnfilteredLinkUrl() =0;

and in the latest master IContextMenuParams.cs

        string UnfilteredLinkUrl { get; }

I am just not sure how to add this to the right click menu.

Looking at code am I can access the Right Click item I am looking for.

     namespace CefSharp.WinForms.Example
     {
         internal class MenuHandler : IMenuHandler
         {
             public bool OnBeforeContextMenu(IWebBrowser browser, IContextMenuParams parameters)
             {
                 //test
                 MessageBox.Show(parameters.UnfilteredLinkUrl);
            

                 // Return false if you want to disable the context menu.
                 return true;
             }
         }
     }

Am I safe to assume that there is no way to add a new item.. I will have to remove the default one and replace it by calling false in the code above ?

Thanks,

**Comment by amaitland** [comment]
As you've discovered this isn't currently supported. It should be possible.

If you take a look at the `cefclient` example, look for `OnContextMenuCommand` and `OnBeforeContextMenu`, they go together. Look at how the `Show Devtools` example is implemented. You add custom menu items, and then handle them. 
We currently only expose part of the `CefContextMenuHandler` handler.

http://magpcss.org/ceforum/apidocs3/projects/(default)/CefContextMenuHandler.html

http://magpcss.org/ceforum/apidocs3/projects/%28default%29/cef_menu_id_t.html#cef_menu_id_t

**Comment by daveaton** [comment]
This has been resolved.

I was able to set a global variable so when the right click menu was activated I could cancel the default context menu, set the global variable and show my own premade context menu using the X and Y.


Here is the code I used.

        /// <summary>
        /// Event happens before context menu appears
        /// </summary>
        /// <param name="browser"></param>
        /// <param name="parameters"></param>
        /// <returns></returns>
        public bool OnBeforeContextMenu(IWebBrowser browser, IContextMenuParams parameters)
        {
            //set defaults from premade context menu
            tsmBack.Enabled = false;
            tsmForward.Enabled = false;
            tsmCopyLink.Enabled = false;
            tsmCopyText.Enabled = false;
            tsmOpenPopupFromLink.Enabled = false;
            tsmReloadMenu.Enabled = false;

            copyBrowserLink = parameters.UnfilteredLinkUrl;
            copyBrowserSelectedText = parameters.SelectionText;

            if (Browser.CanGoBack)
            {
                tsmBack.Enabled = true;
            }

            if (Browser.CanGoForward)
            {
                tsmForward.Enabled = true;
            }

            if (parameters.UnfilteredLinkUrl != "")
            {
                tsmCopyLink.Enabled = true;
                tsmOpenPopupFromLink.Enabled = true;
            }

            if (parameters.SelectionText != "")
            {
                tsmCopyText.Enabled = true;
            }

            if (Browser.CanReload)
            {
                tsmReloadMenu.Enabled = true;
            }

            //shows premande context menu
            cmsBrowserContext.Show(Browser, new System.Drawing.Point(parameters.XCoord, parameters.YCoord));

            return false;
        }


Thanks for the help.
