### ISSUE TITLE
Spellchecking dictionaries

### ISSUE THREAD

**Issue by rfgamaral** [cefsharp/CefSharp#867]
I couldn't find any information regarding this (sorry if it's there somewhere and I just didn't look well enough) so I'm asking here... How can one add and switch dictionaries?

I'm trying the latest v39.0.0-pre03 version and spellchecking works great (awesome work). I right-click a misspelled word and I'm presented with possible corrections and with the option to add the word to the dictionary. Which will be added to `Custom Dictionary.txt` stored in the `Cache` folder. This works great for the en-US dictionary which is stored as `en-US-3-0.bdic` file in the `Cache\Dictionaries` folder.

But how can I have multiple dictionaries for different languages and let the users pick the one they want? Will the "custom dictionary" differentiate added words for each of those different language dictionaries?

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/issues/574#issuecomment-62247392

**Comment by rfgamaral** [comment]
I guess that is not yet implemented in upstream CEF but it seems we are talking about runtime switching. What about picking a "default" language/dictionary at startup, is this possible somehow?

I'm also unaware if there's a way for users to provide the dictionary themselves or if I have to package them with my app distribution. Where can the dictionaries be downloaded from (Google Chrome ones will work?) and where should they be placed?

**Comment by amaitland** [comment]
Try setting the `Locale`.

http://magpcss.org/ceforum/apidocs3/projects/%28default%29/_cef_settings_t.html#locale
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/CefSettings.h#L106

I can't help you with the rest. Try googleing in relation to `CEF`.

**Comment by rfgamaral** [comment]
Will try that when I get home.

Thanks.

**Comment by rfgamaral** [comment]
I just tested the `Locale` option and it worked. I changed it to `pt-PT` and the proper dictionary was loaded and spell checking was working for it. There was one problem though, this also changed the language on the context menus, which was unexpected.

Anyway, the main issue here is solved. Thank you.
