### ISSUE TITLE
Handling 404's

### ISSUE THREAD

**Issue by tbowers** [cefsharp/CefSharp#870]
First, how do I know I've hit a bad page? In my testing I see my `LoadError` handler called w/ a code -118 but I wasn't sure if that's the most robust indicator.

Second, I'm if anyone has any pointers to documentation or thoughts on handling 404's or bad URLs in general. The built in WinForms `WebBrowser` gives you the nicely formatted "Page Not Found" page.

Thanks.

**Comment by amaitland** [comment]
Please include full details please, version, flavor, steps to reproduce.

`Contributing.md` contains a basic `Bug Report Template` to make life easier see 
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue

It's likely `CefErrorCode` should be marked as `[Flags]`. How do you reproduce the error code you seeing?

**Comment by tbowers** [comment]
I apologize for the lack of information. I wasn't intending to report a bug so much as ping the community for thoughts so I wasn't sure if that information was relevant.

#### Issue Summary
I would like CEF to display an error page when a bad URL is entered similar to Chrome or the `Forms.WebBrowser` control.

![chrome](https://cloud.githubusercontent.com/assets/456638/6598204/16551164-c7d0-11e4-869a-f908407d6ccd.png)
![ie](https://cloud.githubusercontent.com/assets/456638/6598206/183efee0-c7d0-11e4-9ebb-bc1490bdb350.png)

#### Steps to Reproduce
1. Startup CEF WinForms example, type in a bad URL like http://http//www.nowayisthisarealsite.com
2. Note that no page is displayed at all.

#### Technical details
* CefSharp Version: tag v39.0.0-pre03
* Operating System: Windows 7
* x86 
* WinForms

**Comment by jankurianski** [comment]
CEF doesn't do anything with load errors by default (except call the [`OnLoadError` handler](https://github.com/svn2github/chromium-embedded-framework/blob/801006110224ec0c967c3ff89d9c2f82d3162377/cef3/include/cef_load_handler.h#L93-L105)), that's why you're getting the blank page.

Here is a C++ example of how you could load a custom HTML error page upon receiving the `LoadError` event:
https://github.com/svn2github/chromium-embedded-framework/blob/801006110224ec0c967c3ff89d9c2f82d3162377/cef3/tests/cefsimple/simple_handler.cc#L77-L95

**Comment by amaitland** [comment]
Specifically is there a way to generate a `-118 ` error code? It's not in the `CefErrorCode` enum values and I'm wondering if it's an omission (It's not listed in the upstream documentation) or if it's being passed as a set of flags and contains multiple values

**Comment by amaitland** [comment]
> I apologize for the lack of information. I wasn't intending to report a bug so much as ping the community for thoughts so I wasn't sure if that information was relevant.

Thanks for the extra information :+1:  I think it's helpful for a few reasons, looking at historic issues, it gives a context. There are quite a few differences between the differents version e.g. `37 vs 39` and also the different flavours, e.g. `WinForms` vs `WPF`. So I'd rather have too much information than not enough.
(The number of issues we get that basically say `It's broken, fix it for me` is quite ridiculous).

**Comment by jankurianski** [comment]
> Specifically is there a way to generate a -118 error code? It's not in the CefErrorCode enum values and I'm wondering if it's an omission (It's not listed in the upstream documentation) or if it's being passed as a set of flags and contains multiple values

I found references in CEF like this: `See net\base\net_error_list.h for complete descriptions of the error codes.`

[net_error_list.h](https://src.chromium.org/svn/trunk/src/net/base/net_error_list.h) has this:

```// A connection attempt timed out.
NET_ERROR(CONNECTION_TIMED_OUT, -118)```

Not sure what the right thing to do is: add to the `enum` values in CefSharp so they are complete (more helpful, but more work and can get out of date), or simply add a comment to the file as CEF has done?

**Comment by amaitland** [comment]
@jankurianski Nice one, that makes sense. Last time I updated `CefErrorCode` it was based off http://magpcss.org/ceforum/apidocs3/projects/%28default%29/cef_errorcode_t.html, I totally missed the reference to `net_error_list.h`.

I'm guessing they don't often change existing error codes, simply add new ones. So hopefully just periodically updating will handle most cases. So maybe a bit of both? Something like `error code not listed below, see xxx`?

**Comment by jankurianski** [comment]
> I'm guessing they don't often change existing error codes, simply add new ones. So hopefully just periodically updating will handle most cases. So maybe a bit of both? Something like error code not listed below, see xxx?

That makes sense, I'll make the change now.

**Comment by jankurianski** [comment]
@tbowers If you use the latest [CI NuGet Builds](https://www.myget.org/gallery/cefsharp) you'll see a lot of new values in [`CefErrorCode`](https://github.com/cefsharp/CefSharp/blob/d9e272c4d865d62b3ef643c52b280cbb8a401e27/CefSharp/CefErrorCode.cs), including `ConnectionTimedOut = -118`.

I think you may be the first to be interested in custom error pages.  If you come across more error codes that map to typical errors (like 404, bad URL, etc.), feel free to add them here as a comment for the benefit of others.

It might also be nice to have the CefSharp Example projects show basic error pages for the most typical errors.  PRs welcome :+1:

**Comment by tbowers** [comment]
@amaitland @jankurianski thanks for all the good info. It looks like the direction for me to go is to generate a custom HTML error page similar to the C++ example linked above. As for the Chrome 404 page I posted earlier, is that not part of CEF and instead implemented in the Chrome application layer? 

Thanks again.

**Comment by amaitland** [comment]
> As for the Chrome 404 page I posted earlier, is that not part of CEF and instead implemented in the Chrome application layer?

`CEF` is a barebones framework, doesn't come with any frills.

**Comment by tbowers** [comment]
Ok that makes sense. Thanks for helping me increase my understanding of the framework. I've modeled my application after that C++ example and am using custom error HTML. So far it is working good. Thanks everyone.
