### ISSUE TITLE
enable h264 decoding

### ISSUE THREAD

**Issue by abhinav4ever** [cefsharp/CefSharp#873]
Is there any way to enable h264 support in CEfSharp?

**Comment by CzarekTomczak** [comment]
See this topic on the CEF Forum: http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=12747

**Comment by abhinav4ever** [comment]
actually what I wanted to know was if the cef binary referred by CefSharp is built with or without mpeg support?

**Comment by jornh** [comment]
Without! We already have a `faq-able!` issue describing this for MPEG-dash https://github.com/cefsharp/CefSharp/issues/851#issuecomment-76429987 ... guess it could be expanded to cover MPEG in general... further http://en.wikipedia.org/wiki/H.264/MPEG-4_AVC#Patent_licensing 

Finally note IANAL (always wanted to write that :smile:)

**Comment by abhinav4ever** [comment]
thanks for the reply... guess i would have to build cef with MPEG support. For what i am trying to do licencing isn't really important.

**Comment by MalikMurtaza** [comment]
How to Enable H264 support in cefsharp Version 45 i had spend too much time on it but not found any successful result

**Comment by amaitland** [comment]
Due to licensing restrictions `CefSharp` is not compiled with `h246` support, you can compile from source for which there are already many questions/tutorials/links floating around address the subject.
