### ISSUE TITLE
upgrade libcef

### ISSUE THREAD

**Issue by avspeed** [cefsharp/CefSharp#875]
Hello Team CefSharp,

Not techbically an issue but I downloaded and built branch 2272 of cef and would like to use it with cefsharp. Are the steps needed to build my own cefsdk and subsequently rebuild cefsharp with the custom cefsdk documented anywhere ?

Thank you for any info that you could share.

**Comment by jankurianski** [comment]
I haven't personally done this, but I found some documentation on it here:
https://github.com/cefsharp/CefSharp/wiki/Building-CefSharp#building-cef-for-use-with-cefsharp
https://github.com/cefsharp/cef-binary
https://github.com/cefsharp/CefSharp/issues/810

**Comment by amaitland** [comment]
`CEF` no longer provides `Visual Studio Solution` files as part of the default build downloaded from http://cefbuilds.com/

There is a script to generate them, it requires `python`. I haven't really look at it in any detail, I just know there's some extra work required than before.

So step `1` is work out how to generate the required `sln` files.

**Comment by avspeed** [comment]
I did generate all the necessary sln files ( cef.sln ) and I even have the libcef_dll_wrapper.vcxproj ..
After successfully building I do see among all files  :  libcef.dll  and libcef.dll.lib .. I am just not sure what to do with them .. My guess is that I have to change something in cefsharp to make it recognize the new version of libcef ?

**Comment by avspeed** [comment]
and.. thanks @jankurianski for the links also

**Comment by amaitland** [comment]
> I did generate all the necessary sln files ( cef.sln ) and I even have the libcef_dll_wrapper.vcxproj

Great :+1: Can you include a brief `HOWTO`, so we can include that in the `cef-binary` project, will be very useful for anyone who builds the packages.

`CefSharp` uses `nuget` packages provided by `cef-binary`.

Fork `cef-binary` then
- Update build version in `build.ps1`
- Copy the `x86` and `x64` sources with the newly generated `sln` files into `cef_binary_3.y.z_windows32` and `cef_binary_3.y.z_windows64` respectively.
- Run `build.ps1`, if all goes well it will generate nuget packages in the `nuget` folder.
- Add local `nuget` repository to `CefSharp` solution and then upgrade the `nuget` package references to your newly created version.

By default it will attempt to generate `vs2012` and `vs2013` packages, if you don't have both installed then you'll have to comment a line out in `build.ps1`.

**Comment by avspeed** [comment]
@amaitland thank you for the instructions. I will follow the steps. I will surely write a HOWTO about building libcef and generating the vs files, I agree that this will be useful. I started building chromium 2 days ago and moved on to cef today. It took such a long time to get the source of these 2 projects and build and I kind of had to scour the net to find some good documentation on how to build, but it finally worked out! 
I will try your instructions and will follow up here upon success! Thank you again.

**Comment by amaitland** [comment]
> I started building chromium 2 days ago and moved on to cef today.

You built `chromium` from source? We just repackage the versions from `cefbuilds.com` :smile:

**Comment by gsiry** [comment]
Hello again - 

Working on upgrading the cef version used by CefSharp  and running into some issues ( I have never done this before so please bear with me )

I am getting a bunch of the errors below 

error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in AssemblyInfo.obj	C:\Users\xxx\Downloads\CefSharp-master\CefSharp-master\CefSharp.Core\libcef_dll_wrapper.lib(libcef_dll_wrapper.zip_reader_ctocpp.obj)	CefSharp.Core


Does that mean that the libcef_dll_wrapper.lib that I rebuilt was built using the /MT Runtime as opposed to /MD

Do I need to rebuild it using /MD ?

Thanks

**Comment by amaitland** [comment]
@avspeed If you can provide some basic instructions on how to generate the project solution files for the latest `cef` branch I'll happily build and publish the latest `2272` branch from http://cefbuilds.com/#branch_2272

How does that sound?

**Comment by avspeed** [comment]
@amaitland that sounds like a plan - Since I ran into many issues while doing it the first time, I am going to redo the whole process from scratch on a clean VM and take some fresh notes. I will catch up with you sometimes tonight. Thanks

**Comment by amaitland** [comment]
Great :+1: You can edit the `wiki` and add your info there if you like? Doesn't have to be fancy to start with. 

(Anyone with a `github` account can edit the `wiki`)

**Comment by avspeed** [comment]
Hello @amaitland here is a 1st version. It basically goes through the automated git workflow and the last section ( provided the automated got workflow succeeded ) talks about generating the VS 2013 solution and projects. Installing Depot Tools is the critical first step. 

https://github.com/cefsharp/CefSharp/wiki/Building-Cef-from-source

**Comment by amaitland** [comment]
First attempt at packaging `3.2272.2035` is available on `MyGet`. Haven't had a chance to run them as yet.

https://www.myget.org/gallery/cefsharp

**Comment by avspeed** [comment]
That is great! I will check this out tonight. Thanks

**Comment by amaitland** [comment]
Looks like they basically work, branch is here https://github.com/cefsharp/CefSharp/tree/cef/2272

**Comment by avspeed** [comment]
Yup .. Works great on this end too... thanks again.

**Comment by amaitland** [comment]
No problem. Thanks for adding info to the `wiki`. I'll include some info about how to repackage a version from `cefbuilds.com` when I get a chance.

**Comment by amaitland** [comment]
I've put the basic steps up on the `cef-binary` wiki.

https://github.com/cefsharp/cef-binary/wiki

Was thinking it might be worth moving your article there as it's in context then. Still keep a link on the main wiki as that's where people are more likely to land.

Feel free to give it a go if your interested.

**Comment by avspeed** [comment]
Thank you. I have moved my article to the cef-binary wiki.

https://github.com/cefsharp/cef-binary/wiki/Building-Cef-from-source

I think that this thread can be closed now - Have a good day.
