### ISSUE TITLE
Add DependencyChecker

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#876]
It's a very common problem for people to be missing dependencies. So I'm thinking we add a simply class that has a list of hard coded dependencies and provide diagnostic information if some are missing. 

Might add the code to the example project, just incase it gets out of sync.

Thoughts?

**Comment by jankurianski** [comment]
Very good idea.  Would you just check if the file exists alongside the executing assembly?

**Comment by gsiry** [comment]
I think that would be immensely useful! An exception that would be thrown before the usual 
"Could not load file or assembly 'CefSharpxxx.dll' or one of its dependencies".

**Comment by amaitland** [comment]
> Would you just check if the file exists alongside the executing assembly?

Yeah I think so. Just something basic, to check the minimum requirements.

We could include it in the mainline project and call it on init? Though that maybe too invasive, could cut down on a number of questions though.

**Comment by jankurianski** [comment]
> We could include it in the mainline project and call it on init? Though that maybe too invasive, could cut down on a number of questions though.

It is invasive and some may not like the extra IO being done in their app's startup.  How about doing it by default, but adding a flag to `Cef.Initialize` or new field to `CefSettings` so developers can skip the behaviour?

**Comment by amaitland** [comment]
> How about doing it by default, but adding a flag to Cef.Initialize or new field to CefSettings so developers can skip the behaviour?

Works for me :+1: I'll see about implementing something when I get a chance,
