### ISSUE TITLE
DoEvaluteScript() exception

### ISSUE THREAD

**Issue by Bodekaer** [cefsharp/CefSharp#878]
Hey,

We just launched today, and some users report this error below.
Any idea, what to do to fix this?

    System.Exception: System.NullReferenceException: Object reference not set to an instance of an object. 
	at CefSharp.CefBrowserWrapper.DoEvaluateScript(Int64 frameId, String script) 
	at CefSharp.BrowserSubprocess.CefRenderProcess.<>c__DisplayClass4.<EvaluateScriptAsync>b__3() 
	at Mailbird.Shared.Controls.WebControl.EvaluateScript(String script) 
	at (Object , String ) 
	at A..(Object , String ) 
	at Controls.MailViewerControl.get_BodyHtml()

**Comment by amaitland** [comment]
What other information do you have?

- Is it for every execution of `get_BodyHtml`?
- Are there other methods that have the same error?
- What does the script look like that your trying to execute?

**Comment by Bodekaer** [comment]
It appears to be happening when CEF is not ready/fully loaded.
It only rarely happens (our alpha tests didn't report this).

But we have had 8 users reporting this so far in a last hour, since the launch.
All happens after calling `get_BodyHtml()`.

Method looks like this:

      public string BodyHtml
        {
            get
            {
                return (string)EvaluateScript("getHtml();");
            }
            private set
            {
                // Set the html synchronously (blocking)
                SetBodyHtmlAsync(value).Wait();
            }
        }


I'm reviewing CefSharp code now for more details on why it throws an exception.
In all cases, we can see that the Cef browser is blank on the screenshots from the users.
So it appears to be because it's not loading CEF completely in some cases.

**Comment by Bodekaer** [comment]
I believe this is where it fails.
https://github.com/cefsharp/CefSharp/blob/9fe07e50cedde2d8b8c17d2d081118c16ed11ae1/CefSharp.BrowserSubprocess.Core/CefBrowserWrapper.h#L80

Would we need a null check here on `context`?

**Comment by mol** [comment]
Basically the exception happens there, but it appears as though CEF was never ready to begin with.

It happens in our compose windows, and for all of the reports so far the window is blank, meaning whatever we loaded into it appears to not be displayed. So I'm thinking something went wrong to begin with, and then 30 seconds later when we call the method above, we get the exception. But the issue lies earlier in the process.

**Comment by Bodekaer** [comment]
Yeah, makes sense.
On the screenshots, can you see CEF loaded elsewhere? (e.g. showing messages in the main window)

**Comment by amaitland** [comment]
> Would we need a null check here on context?

`context.get()` is the equivalent of a null check.

**Comment by mol** [comment]
Plus like I said I think the issue occurs earlier. It's like the contents of the window is never really loaded.

**Comment by Bodekaer** [comment]
Yeah ok. So it must be happening in the line above. Perhaps `_cefBrowser` is null, as it's never loaded.
Interesting we don't see any earlier load errors though.

@amaitland, do we need to catch initialization errors in a specific way perhaps? An event?

**Comment by Bodekaer** [comment]
FYI Alex, there seems to be no errors before this error, about CEF not initializing properly.

**Comment by amaitland** [comment]
> Perhaps _cefBrowser is null, as it's never loaded.

It's unlikely that it's `null` as one of the first things we do is get the identifier see https://github.com/cefsharp/CefSharp/blob/master/CefSharp.BrowserSubprocess.Core/CefBrowserWrapper.h#L34

I'd probably add `if (_cefBrowser.get())` wrapping the whole block in `DoEvaluateScript` to start with.

**Comment by Bodekaer** [comment]
Hmm, unless perhaps `Dispose()` was called before we call `DoEvaluateScript`.
We do have code that "cleans" up the browsers when unused, might be what's causing this, if the reference is still kept for some reason.

If you have any other suggestions Alex, please share. This is an urgent one for us, and we're working on a hotfix to get out asap.

**Comment by amaitland** [comment]
I had wondered about `Dispose` coming into play.

> I'd probably add if (_cefBrowser.get()) wrapping the whole block in DoEvaluateScript to start with.

This should cover the `Dispose` scenario as well.

**Comment by amaitland** [comment]
Probably add a check for frame as well just to be safe.

**Comment by amaitland** [comment]
Is the code actually throwing an exception or returning a `JavascriptResponse` with a message that contains the stacktrace?

**Comment by Bodekaer** [comment]
It's throwing the above exception.
I think it's somewhere in our code, but we might add a check in CEFSharp even. E.g.:
`if (_isDisposed) throw exception;`

**Comment by amaitland** [comment]
> browser, but we might add a check in CEFSharp even. E.g.:

Be careful not to fault the `WCF` channel, it's not particularly fault tolerant.

**Comment by amaitland** [comment]
I think throwing an sort of `Exception` is likely to cause problems with `WCF`.

I'd do something like this https://github.com/amaitland/CefSharp/commit/6da4dde63c862a2b51ee9b1783d9295da2b14e13

**Comment by Bodekaer** [comment]
Yeah I'm adding the disposed check in our code instead. 
I've been able to replicate it, so we should be able to have a fix ready soon (again, I don't think it's a CefSharp bug)

**Comment by amaitland** [comment]
> I've been able to replicate it, so we should be able to have a fix ready soon

Excellent news :smile: 

I'm still inclined to add some additional checks and provide some more info.

**Comment by amaitland** [comment]
I take it you got it sorted?

**Comment by Bodekaer** [comment]
Yep. I hope so :)
We've been alpha testing today, and will release publicly soon, and then we'll know for sure.
It's only 1% of our users that seem to experience it.

Did you try our version 2.0 yet? :)

**Comment by Bodekaer** [comment]
Hey @amaitland,

I just got another similar error today (after our recent attempt to fix the other bug).
Perhaps you can see something from this stack trace? You think it's because the control has been disposed, or perhaps another reason?

`Object reference not set to an instance of an object.`
	
	   at CefSharp.Internals.ClientAdapter.GetCefBrowser(ClientAdapter* , CefRefPtr<CefBrowser>* )
	   at CefSharp.ManagedCefBrowserAdapter.EvaluateScriptAsync(String script, Nullable`1 timeout)
	   at CefSharp.Wpf.ChromiumWebBrowser.EvaluateScriptAsync(String script)
	   at Shared.Controls.WebControl.<ExecuteScriptAsync>d__10.MoveNext() in line 464
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	   at Controls.MailViewerControl.<SetBodyHtmlAsync>d__0.MoveNext() in line 71
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
	   at Controls.MailViewerControl.<LoadMessageHtml>d__a.MoveNext() in line 208

**Comment by amaitland** [comment]
> Perhaps you can see something from this stack trace?

This `stracktrace` is a little more descriptive at least. For what your seeing I'm guessing it's part way through executing the `Dispose` and you've made a a call to `EvaluateScriptAsync`. Do you ever call `EvaluateScriptAsync` from a thread other than the `UI` one?

At the moment there really aren't any guards in place to stop something like that happening.

**Comment by amaitland** [comment]
> Did you try our version 2.0 yet? :)

I haven't as yet, will give it a go on my work machine, replace `Thunderbird` :smile:

**Comment by amaitland** [comment]
Found time to switch over to `Mailbird 2.0`, one thing to note, I downloaded the installer onto a network drive, ran from there, it's now got a `debug.log` and `locales` directory. So it would appear that `cef` took the initial path (e.g. `P:\Software\Mailbird`) and used that for the first run. Subsiquent app launches refer to the correct locales directly.

Apart from that everything is running nicely :smile:

**Comment by Bodekaer** [comment]
Great :)
Yeah we just fixed the "working directory" issue this weekend.

I think you're right with the Dispose and async JS Execution. 
It's just rare that we call dispose, but in theory it could happen, as we use the `async` calls.

We'll investigate some more this week.
Thanks a bunch.

**Comment by amaitland** [comment]
Perhaps short term check `_clientAdapter` for `null` and see if the error goes away?
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/ManagedCefBrowserAdapter.h#L558

I'd like to come up with a consistent strategy for dealing with `Dispose` for all of `CefSharp`. I think we should definitely add an `IsDisposed` to the `WPF` version.

It's probably also noting that cef exposes it's logging capability via `cef_log()`, I haven't yet implemented the function to see how it works, though I think it's probably worth doing, add some additional logging for tracking down problems like your original one.

http://magpcss.org/ceforum/apidocs3/projects/%28default%29/%28_globals%29.html#cef_log%28constchar*,int,int,constchar*%29

**Comment by amaitland** [comment]
Are any of the changes you've made so far worth turning into a `PR`?

**Comment by Bodekaer** [comment]
All changes so far was made in Mailbird directly. 
Actually mostly because it's quicker for us to do the updates there right now.
Once we've stabilized it all, and found the best solutions, then we should definitely implement it.

Most of it so far, is mostly due to our extreme performance optimizations with multiple threads.
I don't expect most CefSharp users to experience the same.

The additional logging would be really great. We're asking users now to share them too.
Right now, most have been fixed, and we have very few reports still coming in.

There is one though, where sometimes the mail displays as blank.
It seems to be related to the background rendering, not rendering when the control is not visible (off-screen).
Is that correct? Is there a way to force rendering even while the control is not attached to any parent?

**Comment by amaitland** [comment]
> It seems to be related to the background rendering, not rendering when the control is not visible (off-screen).

When the control is no longer `Visible` then we notify `Cef` to save resources.
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf/ChromiumWebBrowser.cs#L872

You can always specifically ask `Cef` to redraw using `Invalidate(PaintElementType.View)`
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf/ChromiumWebBrowser.cs#L1474

> Is there a way to force rendering even while the control is not attached to any parent?

You could probably just expose `WasHidden` and override the behavior yourself, tell it to continue rendering. That's just a guess. Overall it's definitely possible, might take a little toying around.

Are you able to easily replicate the problem?

**Comment by Bodekaer** [comment]
That did the trick! 
I simply clear all HTML, and call `Invalidate(View)` afterwards. So simple :) Thx.

**Comment by amaitland** [comment]
> That did the trick!
> I simply clear all HTML, and call Invalidate(View) afterwards. So simple :) Thx.

That was easy :smile:
