### ISSUE TITLE
How to get current page source code?

### ISSUE THREAD

**Issue by arturogrc** [cefsharp/CefSharp#88]
How to get the current page source code as string from my webview control?

**Comment by Paulo-Faustino** [comment]
Is this still not possible except by using the javascript hack above?
I ask cause I'm trying to read a huge page html and through javascript it hangs for more than a minute.

Thanks

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp/IWebBrowser.cs#L262

**Comment by Paulo-Faustino** [comment]
Ouch, I should have checked all methods and parameters before asking.

If you don't mind me asking is there a solution to get the source of a specific frame on the page? In my case I need to grab the source from the third frame on the page to  parse some values using htmlagilitypack.

Thanks a lot man.

**Comment by amaitland** [comment]
> If you don't mind me asking is there a solution to get the source of a specific frame on the page? In my case I need to grab the source from the third frame on the page to parse some values using htmlagilitypack.

In the current version no, it's limited to the main frame.

Next version (`master` branch) is a major rewrite, as part of that there's access to the individual frames.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp/IFrame.cs#L66
