### ISSUE TITLE
Feature Request - Publish packages to symbolsource.org

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#880]
Create additional nuget packages and push them to http://symbolsource.org/
http://docs.nuget.org/create/creating-and-publishing-a-symbol-package

Background `Stackoverflow` topic http://stackoverflow.com/questions/13488280/best-practices-with-nuget-debug-or-release

**Comment by amaitland** [comment]
http://blog.davidebbo.com/2011/04/easy-way-to-publish-nuget-packages-with.html

**Comment by amaitland** [comment]
Details about `MyGet` symbols feed see http://docs.myget.org/docs/reference/symbols

The `Pre-Authenticated` symbols feed is available from https://www.myget.org/F/cefsharp/auth/49b91d8f-ee25-4906-8624-6f67d9423c63/symbols/

Hasn't been fully tested yet, anyone that's interested feel free to check it out though.

**Comment by amaitland** [comment]
https://www.symbolsource.org/Public/Wiki/Using

**Comment by amaitland** [comment]
Using Symbols loaded from `MyGet.org` appears to be working quite nicely. 


To load symbols for the `BrowserSubProcess`, add the following command line option. When the message box opens, attach the debugger to the matching process. (Should be named `Chromium Renderer`). Short while and the symbols should be loaded.

```c#
settings.CefCommandLineArgs.Add("renderer-startup-dialog", "1");
```

Additional download the `Release Symbols` that match the `CEF` version your using from https://cefbuilds.com/ Then extract `libcef.dll.pdb` into the executing folder (same directory as `libcef.dll`).

Another helpful debugging tip can be found at https://github.com/cefsharp/CefSharp/issues/944#issuecomment-92369129

**Comment by jankurianski** [comment]
Nice one @amaitland :+1: 

I've added your tips into a new section in the Trouble Shooting wiki guide: https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#unmanaged-crashes-when-the-process-dies

**Comment by amaitland** [comment]
> I've added your tips into a new section in the Trouble Shooting wiki guide:

Cool, thanks :smile: 

Looks pretty promising, the `Symbol Packages` include the source, so you can actually step into the code if required which is pretty neat :smile: I'm not quite sure how they get pushed to `symbolsource.org`, I'm hopeful this will just happen magically when the packages are pushed to `Nuget.org`. I guess we'll find out when the first `49.0.0-pre` package is ready. (Hopefully one day soon `cefbuilds.com` will be up and running again).

**Comment by amaitland** [comment]
So the `49.0.0` packages are on `Nuget.org`, they are supposed to automatically appear on `SymbolSource.org`, they appear to be having some technically difficulties. So I've created a `MyGet` feed that hosts the `49.0.0` symbols. See https://www.myget.org/feed/Packages/cefsharp-symbols

> Browse the sources in this package using Visual Studio or WinDbg by configuring the following symbol server URL: https://www.myget.org/F/cefsharp-symbols/symbols/

The `pdb` files and source code are included in the symbols, quick test and they appear to load correctly. For instructions on how to setup symbols check the links posted above.

**Comment by amaitland** [comment]
Seems like `symbolsource.org` made some changes that aren't reflected in the default guide.

https://tripleemcoder.com/2015/10/04/moving-to-the-new-symbolsource-engine/

**Comment by amaitland** [comment]
Manually pushed the `symbol packages` with

```
nuget.exe push CefSharp.Common.49.0.0.symbols.nupkg <api key goes here> -source http://nuget.smbsrc.net
nuget.exe push CefSharp.OffScreen.49.0.0.symbols.nupkg <api key goes here> -source http://nuget.smbsrc.net
nuget.exe push CefSharp.WinForms.49.0.0.symbols.nupkg <api key goes here> -source http://nuget.smbsrc.net
nuget.exe push CefSharp.Wpf.49.0.0.symbols.nupkg <api key goes here> -source http://nuget.smbsrc.net
```

Have to wait and see if they're uploaded successfully. Otherwise we'll just have to rely on the `MyGet` feed.

**Comment by amaitland** [comment]
Not entirely happy with this. I think #1680 maybe a better option.
