### ISSUE TITLE
Implement CriticalFinalizerObject

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#881]
So I'm thinking some of our classes may need to implement `CriticalFinalizerObject` to grantee that their resources are disposed of correctly. 

https://msdn.microsoft.com/en-us/library/system.runtime.constrainedexecution.criticalfinalizerobject%28v=vs.110%29.aspx

> Implementing IDisposable on a CriticalFinalizerObject-derived type is tricky because void Dispose(bool disposing) is virtual, yet it must run within a Constrained Execution Region. This may require an explicit call to RuntimeHelpers.PrepareMethod.

http://www.codeproject.com/Articles/29534/IDisposable-What-Your-Mother-Never-Told-You-About

Anyone have past experience implementing `CriticalFinalizerObject`? Is it worth doing?

**Comment by amaitland** [comment]
I'm wondering if this might resolve issues like #800 (Cef Shutdown is fine under normal circumstances, crashes when rebooting/shutting down windows).

**Comment by rassilon** [comment]
Interesting. I sure appreciate the codeproject URL, I ended up using that pattern for wrapping power change notifications (AC <-> DC transitions, battery level, etc..) for my project.

I'm not quite sure how this would apply to CefSharp yet though.

Bill

**Comment by amaitland** [comment]
> I'm not quite sure how this would apply to CefSharp yet though.

It was just an idea, something I stumbled across. Searching for ideas on how to make sure the managed resources are always disposed. When shutting down/restarting when the `WPF` app is open causes an error. Closing the app normal is fine. Likely due to the `OSR`, which is the major different between `WinForms` and `WPF`. (Problem doesn't happen on `WinForms`).

So if you've got any thoughts/suggestions?

**Comment by amaitland** [comment]
Potentially look at using a `SafeHandle` for the filehandle used by `WPF`

**Comment by rassilon** [comment]
Maybe I'm being dense, but what filehandle is used by `WPF`?

**Comment by amaitland** [comment]
Really just a note to myself to look into something further. Need to make sure those unmanaged resources we allocate get handled cleanly. When abruptly exiting e.g. `Environment.Exit()`, I think there's a chance that some of the cleanup code doesn't get executed.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Internals/RenderClientAdapter.h#L146

https://msdn.microsoft.com/en-us/library/windows/desktop/aa366537%28v=vs.85%29.aspx

> CreateFileMapping creates a file mapping object of a specified size that is backed by the system paging file instead of by a file in the file system.

**Comment by amaitland** [comment]
> If hFile is INVALID_HANDLE_VALUE, the calling process must also specify a size for the file mapping object in the dwMaximumSizeHigh and dwMaximumSizeLow parameters. In this scenario, CreateFileMapping creates a file mapping object of a specified size that is backed by the system paging file instead of by a file in the file system.

I should have included the first part for clarity.

**Comment by amaitland** [comment]
https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.safehandle%28v=vs.100%29.aspx

Has a `SafeHandleDemo` that shows `CloseHandle`, which is used. Also referenced `UnmapViewOfFile` which is also used. So probably need one `SafeHandler` for each handle.

Ideally keep this all in `c++` and use native calls if possible.

**Comment by amaitland** [comment]
@rassilon Have you ever implemented a `SafeHandle`? Current cleanup code looks like https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Internals/RenderClientAdapter.h#L181

**Comment by amaitland** [comment]
More reading to do
http://blogs.msdn.com/b/bclteam/archive/2005/03/15/396335.aspx

**Comment by amaitland** [comment]
This looks promising 

https://github.com/Microsoft/referencesource/blob/master/System.Core/Microsoft/Win32/SafeHandles/SafeMemoryMappedViewHandle.cs

**Comment by amaitland** [comment]
https://github.com/Microsoft/referencesource/blob/74706335e3b8c806f44fa0683dc1e18d3ed747c2/mscorlib/microsoft/win32/safehandles/safefilemappinghandle.cs

**Comment by amaitland** [comment]
https://github.com/Microsoft/referencesource/blob/master/System.Core/Microsoft/Win32/SafeHandles/SafeMemoryMappedFileHandle.cs

**Comment by amaitland** [comment]
Resolved with #2237

Have no switched to a totally managed solution using build in classes that implement `CriticalFinalizerObject`
