### ISSUE TITLE
web_view.LoadCompleted does not fire if it is not added in   toolStripContainer

### ISSUE THREAD

**Issue by SAWyen** [cefsharp/CefSharp#882]
Hi all !!!

I am making a small stress utility using CefSharp. The utility will launch 200-500 web_view incidents and on web_view.LoadCompleted it will take the snap. Right now , i am facing an issue if i comment the following line  

       toolStripContainer1.ContentPanel.Controls.Add(web_view);

web_view.LoadCompleted event does not fire. It means it is mandatory to load the web_view control in  toolStripContainer1 and display it.

Is there any alternate way that Web_view does not came in front of the user and its snapshot can be taken on web_view.LoadCompleted event?

Note: The code is compiled in x86 form on  visual studio 2008

```c#
namespace WindowsFormsApplication4
{
	public partial class Form1 : Form
    {
        Bitmap bitmap;

        private  WebView web_view;
     
        public Form1()
        {
            InitializeComponent();
            this.WindowState = FormWindowState.Maximized;


            CefSharp.Settings abc = new Settings();
            abc.PackLoadingDisabled = true;

            if (CEF.Initialize(abc))
            {

                web_view = new WebView("http://localhost/ultweb/ultisapi/FormAccess.dll?LaunchProcess?WE", new BrowserSettings());
                web_view.Dock = DockStyle.Fill;
            toolStripContainer1.ContentPanel.Controls.Add(web_view);
                

                web_view.LoadCompleted += new LoadCompletedEventHandler(web_view_LoadCompleted);

            }
           
        }

        private void web_view_LoadCompleted(object sender, LoadCompletedEventArgs e)
        {
           
            Thread th = new Thread(new ThreadStart(WorkThread));
            th.Start();

        }

        private void Test()
        {
            if (InvokeRequired)
            {
            
                MethodInvoker method = new MethodInvoker(Test);
                Invoke(method);
                return;
            }
        

            bitmap = ControlSnapshot.Snapshot(web_view);  
          
            bitmap.Save(DateTime.Now.ToShortDateString().Replace("/", "-") + " " + DateTime.Now.ToLongTimeString().Replace(":", " ") + ".png", System.Drawing.Imaging.ImageFormat.Png);
        }

        private void WorkThread()
        {
            Test();
        }
    }
}
```

**Comment by amaitland** [comment]
Couple of things

- Your using `CefSharp1` which is no longer supported.
- Using the `WinForms` version then it must be attached to a parent container.
- For rendering purely offscreen then there's a special distribution of `CefSharp` for that, see https://www.nuget.org/packages/CefSharp.OffScreen/
- Minimal Example of `CefSharp.OffScreen` can be found at https://github.com/cefsharp/CefSharp.MinimalExample/blob/master/CefSharp.MinimalExample.OffScreen/Program.cs

**Comment by SAWyen** [comment]
do you have any other non-nuget link( " https://www.nuget.org/packages/CefSharp.OffScreen/" ) for purely offscreen package ?. I am facing issue with nuget.

**Comment by jankurianski** [comment]
The only binaries are NuGet packages.  You can also download the CefSharp source code and build it yourself.  All of the binary files you need to copy into your app's directory will be in `CefSharp\CefSharp.Offscreen.Example\bin\x64\Release` (or `x86`).

**Comment by amaitland** [comment]
You could also get `CI` builds from our `MyGet` feed see https://www.myget.org/gallery/cefsharp

Though they all at some point rely on `Nuget.org` to provide `cef-binary` packages.

**Comment by amaitland** [comment]
@SAWyen Anything further before closing this?

**Comment by SAWyen** [comment]
Close it .......Thankx a lot for all your help
