### ISSUE TITLE
C# Winforms .Net 4.0  How to pass the Referer Url to a new popup ?

### ISSUE THREAD

**Issue by daveaton** [cefsharp/CefSharp#884]
Is there a way to look-up the referrer information to pass to a new popup?

I can see from the Master default windows when you open a new popup the referrer information is passed to the new popup. I can't see where it's doing this.  

Here is a demo of this.

http://www.eatoncode.com/shareit/2015-03-16_2150.swf

I was expecting to get the referrer information from this method

public bool OnBeforePopup(IWebBrowser browser, string url, ref int x, ref int y, ref int width, ref int height)

But I did not see any values for Referrer.  I am trying to use my own custom version of the popup window instead of using the default hard coded windows.

I could simply pass the url it came from [Browser.Url] but if it's done from frames I will incorrectly set the wrong referrer if the link actually came from a sub inner frame.

Any ideas ?

**Comment by daveaton** [comment]
I think that this https://github.com/cefsharp/CefSharp/issues/869  is related.  Currently the way I am using popups I start a  new instance and I am loosing the referer information that should be passed to the new popup instance from the parent.

Since I wish to have this feature implemented quickly I wish to offer a bounty of $125  bounty payable via paypal for this feature to be implemented for the good of the open source project.  Currently this is critical and time sensitive issue in my own application and this is the best place to find the best programmers.

I am more interested in the referer information being based to the new popup for a custom popup C# Winforms.  Currently it only seems to work when using the default popups.

PS:  I wish there was a place to donate to this project since all of us are not the best programmers using C++  I appreciate all the people who have been so very patient.

**Comment by rassilon** [comment]
It's sort of, but not directly related. Fortunately, the CEF OnBeforePopup handler gets the data via `frame->GetUrl`, so this shouldn't be too hard to fix. (just not tonight)

Bill

**Comment by rassilon** [comment]
@amaitland , API discussion here:

The simplest thing to do here might to be just add a referrerUrl param from `frame->GetUrl` to `OnBeforePopup`. Thoughts?

I don't think we really pass `CefBrowser/CefFrame`s to .NET code yet do we?

Bill

**Comment by amaitland** [comment]
> The simplest thing to do here might to be just add a referrerUrl param from frame->GetUrl to OnBeforePopup. Thoughts?

That's the quick fix for this yeah. For the `39` release I think that's the way to go. For `41` I think we should consider creating a browser/frame wrappers.

> I don't think we really pass CefBrowser/CefFrames to .NET code yet do we?

Currently there aren't wrappers for either. I think the frame wrapper would be quite useful, there are a lot of methods that could be done conditionally in the context of a specific frame and we only allow them to be executed on the MainFrame. I think basically where `browser->GetMainFrame()` is referenced in `ManagedCefBrowserAdapter`, you should be able to pass in a frame Id. e.g. Cut/Copy/Paste

Going forward I think, add the `referrerUrl` param which should effectively close this issue. Then create another issue against the `41` milestone to add wrappers. 

@daveaton Can you confirm that adding `referrerUrl` param to `OnBeforePopup` will solve your immediate problem out?

**Comment by rassilon** [comment]
@daveaton , the above presumes you're not trying to create the custom popup as a CEF Browser/frame of course and instead use something else to create UI (i.e WinForms/WPF). I couldn't quite tell what kind of custom popup you had in mind.

**Comment by daveaton** [comment]
Well I am using custom popups not the default ones.  I am using DevExpress Skinned Winforms.
Me and another programmer tried to get #869 working and we managed to get it semi working but we had a major issue where the child was controlling the parent also.  After 3 days of trying to get that to work we came back to this idea of just passing the referer.  

Both ideas will pass the referrer info.  Passing the new popup as child or popup seems to work more correctly.

The idea of just passing the referer info even though it's not 100% it works.  The bad part is that some times it will pass the main url instead of actual frame it came from.  This is not a problem for us as long as something is in the Referer field.

Here is what we came up with.


      private string copyFrameUrl;
 
        public bool OnBeforePopup(IWebBrowser browser, string url, ref int x, ref int y, ref int width, ref int height)
        {
            var popupw = width;
            var popuph = height;

            this.InvokeOnUiThreadIfRequired(() =>
            {    
                 var popup = new XfBrowserPopup(url, popupw, popuph, GetReferrer());
                 popup.Show();
            });

      }

        public bool OnBeforeContextMenu(IWebBrowser browser, IContextMenuParams parameters)
        {

            if (parameters.FrameUrl != null)
            {
                copyFrameUrl = parameters.FrameUrl;
            }

           return false;
        }

        public string GetReferrer()
        {
            if (copyFrameUrl != null)
            {
                return copyFrameUrl;
            }
            else
            {
                return Browser.Address;
            }
        }




XfBrowserPopup  is just my custom form where I just add a new instance of ChromiumWebBrowser to the form.


     private readonly string popReferer;
     

       public XfBrowserPopup(string url, int width, int height, string referer = null)
        {
            this.InitializeComponent();

            if (width < 799)
            {
                this.Width = 800;
            }
            else
            {
                this.Width = width;
            }

            if (height < 599)
            {
                this.Height = 600;
            }
            else
            {
                this.Height = height;
            }

            popReferer = null;
            if (referer != null)
            {
                popReferer = referer;
            }

            this.InitializeBrowser(url);

            this.Disposed += BrowserTab_Disposed;
        }


        public bool OnBeforeResourceLoad(IWebBrowser browser, IRequest request, IResponse response)
        {
            if (popReferer != null)
            {

            var existingHeaders = request.Headers;

            if (!existingHeaders.AllKeys.Contains("Referer"))
            {
                var headers = new NameValueCollection();

                // Copy existing headers.
                foreach (var headerName in existingHeaders.AllKeys)
                {
                    headers.Add(headerName, existingHeaders[headerName]);
                }

                // Set referer.
                headers.Add("Referer", popReferer);

                // Update request headers.
                request.Headers = headers;
            }
        }

          return false;
        }


If there was a referer field that would work by passing the correct frame url would be very nice.

Thanks.

**Comment by amaitland** [comment]
@daveaton Is there are reason you do this:

```c#
var existingHeaders = request.Headers;

if (!existingHeaders.AllKeys.Contains("Referer"))
{
	var headers = new NameValueCollection();

	// Copy existing headers.
	foreach (var headerName in existingHeaders.AllKeys)
	{
		headers.Add(headerName, existingHeaders[headerName]);
	}

	// Set referer.
	headers.Add("Referer", popReferer);

	// Update request headers.
	request.Headers = headers;
}
```

instead of simply?

```c#
// Set referer.
headers["Referer"] = popReferer;
```

**Comment by daveaton** [comment]
@amaitland

yes...

because what I was trying

request.headers.add("Referer" "http://www.whatever.com");  //this never worked.....

was not working. because the container was read only...

So I recreated the container and only passed the Referer data if it was not already in the headers already while keeping all the existing headers... then passing the new container.

Never tried your code.  if non of my code existed it might have looked like this..

// Set referer.
request.headers["Referer"] = popReferer;

but the headers container was still read only...?

**Comment by amaitland** [comment]
```c#
var headers = request.Headers

// Set referer.
headers["Referer"] = popReferer;

// Update request headers.
request.Headers = headers;
```

That's what I would have done.

**Comment by daveaton** [comment]
hum....

Trying it now... you got me curious.. I have to try for my self...

Maybe the context auto fill in was confusing me..

the Add and Set is miss leading.. it just would not add or set anything :(

request.headers.Add("Referer" "http://www.whatever.com"); //don't work
request.headers.Set("Referer" "http://www.whatever.com"); //don't work

hum ... Your code seems to work... I was throwing everything at it... never occurred to me to use it like that. :)

**Comment by amaitland** [comment]
> the Add and Set is miss leading.. it just would not add or set anything :(

Correct, the `NameValueCollection` is just a copy of the values, not directly linked to the underlying header collection. Currently there is no wrapper for the underlying `Cef` type.
