### ISSUE TITLE
Printing without print dialog on default printer.

### ISSUE THREAD

**Issue by zigota** [cefsharp/CefSharp#886]
Is it possible to suppress the print dialog on  CefSharp.Wpf during an execute print() method and during call printing from page via  js "window.print()".

**Comment by amaitland** [comment]
Short answer is no. Long answer is it maybe possible if the upstream `Cef` project supports it.

Feel free to check out `CEF's` API documentation at http://magpcss.org/ceforum/apidocs3/index-all.html

It's probably worth searching the `Cef Forum` for info as well, maybe post a question if you can't find anything?
http://www.magpcss.org/ceforum/

Hope this helps!

**Comment by CzarekTomczak** [comment]
I've answered an exact question today, see here: https://groups.google.com/d/msg/phpdesktop/KZivvZrjnJo/yzIU7VY5fvMJ

**Comment by amaitland** [comment]
Thanks @CzarekTomczak. Marking this as `upstream`. One the open issues has been resolved we can look at implementing this.

**Comment by zigota** [comment]
I decided to try resolve this issue by using an bound object:
send data for print from js to bind's object method: "bound.AnyPrintMehod(data_for_print)", and handle print in c#

**Comment by amaitland** [comment]
http://magpcss.org/ceforum/viewtopic.php?f=6&t=12567#p24126
https://bitbucket.org/chromiumembedded/cef/issues/1478/pdf-printing-support-in-cef

So `CEF` has recently added `Print to PDF` support which can be used without displaying a dialog. This is currently the official workaround for this problem (Doesn't look like `CEF` will be implementing the exact feature any time soon and the only other option is to modify the source and recompile).

Hopefully `master` will be updated to include the changes in the next week or so.

**Comment by amaitland** [comment]
`Print to PDF` functionality is now in `master`. See PR #1278
