### ISSUE TITLE
CEF requiring administrative privileges under certain circumstances?

### ISSUE THREAD

**Issue by mol** [cefsharp/CefSharp#891]
We're having some issues with CEF possibly not initializing properly (is my theory, but still hoping to find confirmation) for a few users, where running Mailbird with administrative privileges fixes the issue.

Is there anything you can think of that might cause this issue? Again, only a small subset of users are experiencing this, so it's likely some kind of permission issue.

**Comment by rassilon** [comment]
I hate asking stupid obvious questions, but you did disable the creation of the 'debug.log' like file, right?
Since that could end up writing data to the location of the binary, which might fail depending on your OS and various other Windows settings. (I think some Windows settings/OS combinations can have the writes automatically redirected somewhere else, but its been a while since I looked into the details of that stuff.)

Thinking of other possible reasons for writing data in the installation directory might yield some benefits.

If you have a willing customer using SysInternal's ProcMon tool https://technet.microsoft.com/en-us/sysinternals/bb896645 to see if you can determine which file/registry operations fail with access denied might also help you find the root cause when Mailbird runs without Admin privileges.

You might need admin privileges to actually run ProcMon as well.

If the problem happens during CEF initialization this hopefully means reading the ProcMon data should be much quicker.

Bill

**Comment by mol** [comment]
Hi Bill,

I was thinking the same thing. I actually just now got a message from a user with the issue saying he couldn't find the debug.log file in the installation directory. Which everyone else seems to have, so I'm thinking that no it's not been disabled, and is maybe being created, or attempted created, somewhere else (we had someone have it created on the desktop). I bet this is it. Will investigate more, thanks :)

**Comment by mol** [comment]
That's odd. If CefSettings is constructed using its defaults for logging, which is what we were doing, LogSeverity is set to disabled, but a log file is still being created and written to in (usually) the application directory.

If I leave that to disabled however, but set the 'LogFile' location to another, no file is being created. Even if I set it to verbose no file is being created. Seems like it might be broken?

**Comment by mol** [comment]
Nevermind the file location issue. I was in the wrong branch and things weren't going where I expected :)

But disabled still seems broken.

**Comment by avspeed** [comment]
@mol what branch are you working with ?

**Comment by mol** [comment]
No it was just a Mailbird branch I was referring to, the email program we're using CEF in. When I changed the file path I was expecting it to end up in one place but it ended up in another. It was my bad :)

But it still appears as though setting LogSeverity to disabled does not disable creation of the log file. That's a separate issue to this though (the admin issue), which I expect is fixed now - just waiting for confirmation. So if you guys want me to create a new ticket for LogSeverity, let me know :)

**Comment by avspeed** [comment]
@mol ok I was just seeing if I could reproduce the LogSeverity issue on my side .. are you using the stable version of CefSharp ( 37.0.0 ) or the pre-release one ( 39 ... ) ?

**Comment by mol** [comment]
I'm using the pre-release one, 39.0.0.0.

**Comment by avspeed** [comment]
I cannot seem to reproduce on my end. With the LogSeverity set to disabled I do not get a file; when I switch it to verbose I get a file right away. I am using the CefSharp.WinForms.Example ..

Can you try passing the command line argument instead to see if it makes a difference in your case ?

settings.CefCommandLineArgs.Add("log-severity", "disable");

**Comment by mol** [comment]
I tested some more. The log file is only created if the settings are left to the default of disabled. If I explicitly set it to disabled (even though it already shows as set to that), after the settings object is constructed, it does not create the file.

**Comment by rassilon** [comment]
What makes you think the default value is disabled? The CEF code from 2171.1979 says the 0 value is: (and the 0 value stems from a `memset` inside of CEF)

    ///
    // Default logging (currently INFO logging).
    ///
    LOGSEVERITY_DEFAULT,

And CefSharp doesn't alter from the default value CEF provides.

Fyi,
Bill
Fyi,
Bill

**Comment by rassilon** [comment]
CefExample.cs does however set the `LogSeverity` to Verbose.

**Comment by mol** [comment]
If I examine the property in Visual Studio after the settings object has
been created with the defaults, it says the log severity is disabled.

**Comment by amaitland** [comment]
> If I examine the property in Visual Studio after the settings object has been created with the defaults, it says the log severity is disabled.

That's a bug in how the original enum mapping was implemented. I fixed that yesterday see https://github.com/cefsharp/CefSharp/commit/61dd781731f71527de9cdf4b9217cc03e42c5319

**Comment by mol** [comment]
Ah, excellent. All is good then. I also have confirmation that the original issue was caused by the log file, so I'll close this now. Thanks a lot for the quick help :)
