### ISSUE TITLE
listening to ILifeSpanHandler.OnBeforePopup

### ISSUE THREAD

**Issue by elibyy** [cefsharp/CefSharp#894]
i can't seem to understand why my create window is causing the ui to freeze
my code is 
```c#
class LifeSpanHandler : ILifeSpanHandler
    {
        public bool OnBeforePopup(IWebBrowser browser, string url, ref int x, ref int y, ref int width, ref int height)
        {
            var w = new TestWindow();
            w.InitializeComponent();
            w.Show();
            return true;
        }

        public void OnBeforeClose(IWebBrowser browser)
        {

        }
```

**Comment by amaitland** [comment]
Your executing a request on the `CEF IO` thread. I'm guessing your using `WPF` (You really need to say which version and what flavor of `CefSharp` your using, e.g. `WinForms`, `Wpf`, `OffScreen`, see https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue for more details on what to include when submitting an issue).

http://magpcss.org/ceforum/apidocs3/projects/%28default%29/CefLifeSpanHandler.html#OnBeforePopup%28CefRefPtr%3CCefBrowser%3E,CefRefPtr%3CCefFrame%3E,constCefString&,constCefString&,constCefPopupFeatures&,CefWindowInfo&,CefRefPtr%3CCefClient%3E&,CefBrowserSettings&,bool*%29

Try either
- Invoke on the `WPF Dispatcher`
- Execute in a `Task`

**Comment by amaitland** [comment]
Also I've edited your initial comment and fixed up the code comment to make it readable.

See https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks for more info.

**Comment by elibyy** [comment]
thanks yeah i'm sorry i haven't provided flavor, i was using WPF and yes thanks the Dispatcher fixed it
