### ISSUE TITLE
EndEvaluateScriptAsync exception and great cpu consumption

### ISSUE THREAD

**Issue by Antonyo** [cefsharp/CefSharp#899]
Hello, one of our users are getting an exception when evaluating an script, he also indicates that when this occurs his pc becomes laggy being the cpu consumption by the BrowserSubprocess is around 25%, it only occurs with a particular html but so far the only thing I've noticed on it is that contains bad decoded cyrillical characters (I assume they're cyrillical since the user is bulgarian) so maybe the charset is bad specified in the html but I haven't been able to recreate it. 

App type: WPF 
OS: Windows7

This is the script being executed:

```
if (document.body.firstChild)
        return document.body.firstChild.innerHTML;
return '';
```

and this is the error log:

```
System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: One or more errors occurred.
Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.ThrowIfFaultUnderstood(Message reply, MessageFault fault, String action, MessageVersion version, FaultConverter faultConverter)
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeEndService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)
Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at CefSharp.Internals.IRenderProcess.EndEvaluateScriptAsync(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
```

thanks in advance

**Comment by jankurianski** [comment]
Hi, could you add the following details to help others understand where the problem may be:
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue

Also, could you reformat your code and error so it is readable?  If you click the `Markdown supported` text in the comment box there is help on this.

**Comment by jankurianski** [comment]
Is there some way you could share the HTML with us, like in a [gist](https://gist.github.com/)?

**Comment by amaitland** [comment]
What encoding are you using? Might be worth setting the default to `UTF-8` or something similar? The fallback for `CEF` I believe is `ISO-8859-1`

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/BrowserSettings.h#L157
http://magpcss.org/ceforum/apidocs3/projects/%28default%29/_cef_browser_settings_t.html#default_encoding

**Comment by amaitland** [comment]
> Is there some way you could share the HTML with us, like in a gist?

Or fork https://github.com/cefsharp/CefSharp.MinimalExample

**Comment by amaitland** [comment]
Also any ideas how big the request is? I'd usually advise against getting the source via `EvaluateScriptAsync`, I'd suggest using `GetSourceAsync()` where possible.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp/IWebBrowser.cs#L261

**Comment by Antonyo** [comment]
Hi, thanks for the answers, I've requested the CEF log file to the user, I'm still waiting the html content as soon as I have it I will share with you.

Thanks.

**Comment by ray007** [comment]
Shouldn't have to do anything with your problem, but `document.body.firstChild` in many cases is not an `Element` and therefore has no `innerHTML`.

**Comment by Antonyo** [comment]
Thanks for the help, after many changes in the cef setup and initialization the user is not reporting crashes or laggy performance, I still don't have the html source so I can't determine the source of the problem but I will keep you updated if I find something remarkable, we will consider using GetSourceAsync when possible since we need to keep performance as it highest. Thanks again.

**Comment by amaitland** [comment]
> after many changes in the cef setup and initialization the user is not reporting crashes or laggy performance,

Can you elaborate on your solution? Helps for us to have a record, just incase someone else has a similar problem.

**Comment by Antonyo** [comment]
Oh yes, when evaluating a previous script sometimes a timeout could occur because it could have been disposed or being disposed in another thread, for future script evluations we check if it was disposed before and recreate the browser again so no crash occur. Regarding the performance issue is hard to determine without the original html, I hope to get it and research was exactly causes the performance impact.
