### ISSUE TITLE
Keyboard is not working when CEF is put inside popup

### ISSUE THREAD

**Issue by myrnazhou** [cefsharp/CefSharp#901]
Hi Guys,
I'm using ```CEF``` in ```WPF```. I'm having an issue when the browser is put inside a popup, the keyboard is not working. I've made a demo in this branch https://github.com/Bodekaer/CefSharp/tree/PopupIssue.
Any help on this? Thanks :)

**Comment by amaitland** [comment]
My initial though is that you would have to rewrite the keyboard handling, removing the `SourceHook` and using the managed `OnPreviewKey` to send all the key events.

**Comment by amaitland** [comment]
Does `SourceHook` get called when you press a key?

**Comment by myrnazhou** [comment]
The ```SourceHook``` was called, but it stops at the ```IsKeyboardFocused``` checks. But even after I removed it, it still didn't work.
I tried to use snoop to see where the event is handled, but I couldn't see any. Like there was no event being fired.

**Comment by amaitland** [comment]
I'd expect the key presses to be handled at a higher level and not propagating down to the source hook.

**Comment by myrnazhou** [comment]
@amaitland 
I don't really understand, the thing is none of the keyboard keys work there. I've tried to just send all the keys with ```managedCefBrowserAdapter.SendKeyEvent```, but it still doesn't work. Can you guide me to fix this issue?

**Comment by amaitland** [comment]
> Can you guide me to fix this issue?

You need to map the `WPF` keyboard events to `_cef_key_event_t`. It's quite a complex task to make all the key combinations, modifiers, etc.

http://magpcss.org/ceforum/apidocs3/projects/%28default%29/_cef_key_event_t.html

**Comment by myrnazhou** [comment]
isn't the ```managedCefBrowserAdapter.SendKeyEvent``` already maps it to ```_cef_key_event_t``` ?

**Comment by amaitland** [comment]
The `wParam` and `lParam` values aren't being populated fully in `OnPreviewKey`, hence the reason it doesn't work. You can remove the need for the source hook if you can fully map from the `WPF` keyboard to `_cef_key_event_t`. You'd rewrite the `SendKeyEvent` method header dramatically.

I'd suggest you debug the method under normal working circumstances, so you can see some values.

**Comment by amaitland** [comment]
Had a quick look, you can probably reverse engineer the mapping using the `.Net Source`

http://referencesource.microsoft.com/#PresentationCore/Core/CSharp/System/Windows/Interop/HwndKeyboardInputProvider.cs,abd4c8f95f09e515,references

**Comment by amaitland** [comment]
Maybe able to read the raw message from http://referencesource.microsoft.com/#WindowsBase/Base/System/Windows/Interop/ComponentDispatcher.cs,3318a6acdecb3267,references

**Comment by amaitland** [comment]
I was hopeful that something like the following would work

```c#
private void OnPreviewKey(KeyEventArgs e)
{
	if (e.Key == Key.System && e.SystemKey == Key.F4)
	{
		// We don't want CEF to receive this event (and mark it as handled), since that makes it impossible to
		// shut down a CefSharp-based app by pressing Alt-F4, which is kind of bad.
		return;
	}

	var msg = ComponentDispatcher.CurrentKeyboardMessage;

	Debug.WriteLine("message:" + msg.message + ";wParam:" + msg.wParam + ";lParam:" + IntPtrToInt32(msg.lParam));

	e.Handled = managedCefBrowserAdapter.SendKeyEvent(msg.message, msg.wParam.ToInt32(), IntPtrToInt32(msg.lParam));
}
```

Unfortunately the message for the KeyUp event is quite different to that of the source hook and doesn't work. So the message must be modified slightly as it passes through the chain.

**Comment by myrnazhou** [comment]
@amaitland yes, I tried the exact same code with the one you just posted, didn't work.

**Comment by amaitland** [comment]
> I tried the exact same code with the one you just posted, didn't work.

I only said it was a `maybe`. What else have you found out?

**Comment by myrnazhou** [comment]
I mean I tried that code before I saw your comment. No I haven't worked on this again.

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/pull/934#issuecomment-93906876 for a workaround for anyone else experiencing this issue.
