### ISSUE TITLE
Webroot SecureAnywhere detecting Cef process file as malware

### ISSUE THREAD

**Issue by mol** [cefsharp/CefSharp#903]
I'm not sure this is an issue as such, but just in case you guys want to look into it, Webroot is detecting the Cef process file as malware. See image.
![webroot](https://cloud.githubusercontent.com/assets/317217/6824543/7cb9a388-d2f3-11e4-8710-38d8aa7a7722.PNG)

**Comment by daveaton** [comment]
This is done because your webroot is not being told other wise.  It's learning and it appears that your building and running in the debug mode which it may find suspicious and if enough people do not change this by removing from the false positive, this is what you will end up with.

Add your development folder to the exclude list.

q:\Development

Thanks.

**Comment by mol** [comment]
Thanks for the reply Dave, I should have been more specific. The problem isn't *my* Cef process is being detected by Webroot as malware on installation (so before learning). I'm not using Webroot. I was just testing it because I was testing another issue one of our users were reporting, when I noticed this. The version packaged with our app is also being detected as malware. Those are the ones in the 'program files' directories. I was wondering if there was something that could be done to avoid that. So it doesn't show up as a false positive for any of our users using Webroot.

I suppose maybe signing it when we build it for release... we only do that with our own executable at the moment.

**Comment by daveaton** [comment]
I have same issue.  Every time I release a new version I always get a false positive.
To prevent this from happening I white list my program for review before releasing it in the wild.
It's a pain but it solves the issue.  I am currently using code signing from Comando
https://www.comodo.com/business-security/code-signing-certificates/code-signing.php

It's a cheaper code signing... $300 for 3 years...


If you buy a higher level of code signing  http://www.symantec.com/products-solutions/families/?fid=code-signing  $1700+ you will not have this issue. but then I could not afford to give my software out for free.

Thanks.

**Comment by mol** [comment]
Thanks for the great explanation Dave. We're using it in Mailbird, which is an email client. For viewing and editing emails. We release an update usually every week, so I suppose that would present a problem :)

So you're saying Fork CEF and change the Assembly Information GUID for the process yeah? Instead of using the NuGet package that we're currently using. I'm not seeing a GUID defined in the Assembly Information in the CEF source though, but I'm admittedly not clear on how that works exactly.

**Comment by daveaton** [comment]
If your building custom version of CEF then you need to change the GUID other wise just use the original.

I was doing the exact same thing as you in the beginning.  Releasing to many versions to soon.  This can cause a lot of false positives, because your software does not have any age on trust.  Security Suits see releasing to many versions as unstable software which could also contribute to mis-classification.

:)

**Comment by mol** [comment]
Thanks David,

We're not building a custom version at the moment. Just using the one in NuGet, so I guess we'll just keep doing that for now.

We haven't had any issues with Mailbird itself being classified as malware recently, that I'm aware of. Just the CEF process now, but so far I only know of Webroot doing it. So I was wondering if it was something in the CEF code that could be improved. We used Awesomium before, but I'm unsure if Webroot would catch that one as well.

Anyway, thanks for your help. As long as it's just Webroot we can deal with it :)

**Comment by amaitland** [comment]
Not the first antivirus issue to be raised, see https://github.com/cefsharp/CefSharp/issues/779

> We're not building a custom version at the moment. Just using the one in NuGet, so I guess we'll just keep doing that for now.

I was under the impression that you build your own `nuget` packages, has this changed?

**Comment by mol** [comment]
I see, thanks @amaitland. I'll definitely keep a close eye on this if we start getting more reports.

> I was under the impression that you build your own nuget packages, has this changed?

No we're building the nuget package. I just meant we're not using a modified (from that) version :)

**Comment by amaitland** [comment]
Code signing may go a ways to put some antivirus companies at easy. Likely more effective if implemented by the `CefSharp` project it's self, otherwise everyone else out there will have an unsigned version, which is likely to cause issues.

Possibly there's a `CA` out there that would provide a free cert to an open source project?

**Comment by mol** [comment]
I found something on this in stackoverflow: http://stackoverflow.com/questions/10202556/code-signing-for-an-individual-for-open-source-projects

Specifically:
> Certum (http://www.certum.pl) offers free code certificates for open source projects. I know the TortoiseSVN and AnkhSVN projects use certificates from them for their distributions.

> The problems with signatures expiring when the certicate does is not specific to a certificate provider but on how you sign the certificate. To keep the signature valid you should also sign a timestamp. See the FAQ of your certificate provider.

Maybe that would be an option?

**Comment by amaitland** [comment]
https://www.certum.eu/certum/cert,offer_en_open_source_cs.xml

**Comment by mol** [comment]
I've spoken with Webroot again and they say (although it may just have been a support staffer that agreed with my assumption) that in this case signing it will not help, as it's flagged by heuristics. I think with Webroot we may just have to live with it.

**Comment by amaitland** [comment]
In this case I think code signing would come into play if they were to whitelist the browsersubprocess.

Anyways, did they give any more information about what they think is malicious? Maybe there are some changes that can be made?

**Comment by mol** [comment]
Unfortunately they can only white list the MD5 at the moment, which changes
with every new version no?

I'll ask them if there's something that can be done to CefSharp to avoid
the heuristics.
