### ISSUE TITLE
CefSharp silently ignores missing subprocess.exe

### ISSUE THREAD

**Issue by perlun** [cefsharp/CefSharp#905]
I noted this while migrating our app (framework) to my unofficial CefSharp 37.0.1 package: If the subprocess.exe is MIA, CefSharp silently ignores this, but fails to function (naturally...). This is not so good, since it can cause hard-to-debug scenarios where time gets wasted just because no error/exception is produced.

Steps to reproduce:

1. Set `CefSharp.Wpf.Example` as the startup project
1. Place a breakpoint in `Cef.h`in the `Initialize` method.
1. Press F5.
1. When the breakpoint is triggered, manually open up the subprocess folder (`Y:\git\CefSharp-37\CefSharp.BrowserSubprocess\bin\x86\Debug` or whereever). Delete the `CefSharp.Subprocess.*` files.
1. Back to Visual Studio, press F5.

The CefSharp WPF example will now run, but completely non-functional, with no sign of any error whatsoever. Bug! :smile:

**Comment by amaitland** [comment]
I think #900 adequately resolves this. Perhaps check it out (it's still a little rough around the edges).
