### ISSUE TITLE
Bug: IsLoaded is unreliable until we've migrated to use OnLoadingStateChange instead

### ISSUE THREAD

**Issue by perlun** [cefsharp/CefSharp#909]
Hi,

I'm experiencing issues with <subj>. This is with CefSharp 37.0.1 (btw, should publish it from MyGet...).

I can reproduce the issue with the WPF example as well. If I open up http://www.google.com, and then type in something, and press Enter or click Search, the progress bar (bottom) will keep rolling, like this:

![image](https://cloud.githubusercontent.com/assets/630613/6869389/3c201ea6-d49c-11e4-86f0-4f80978f3d31.png)

Anyone feel like investigating? Has it already been fixed in the latest `master` mayhaps?

**Comment by amaitland** [comment]
I am aware of this one, `IsLoading` relies on `OnLoadStart` and `OnLoadEnd` which leads to this http://magpcss.org/ceforum/viewtopic.php?f=6&t=10906 post which should look familiar :smile: 

Relevant code
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf/ChromiumWebBrowser.cs#L321
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf/ChromiumWebBrowser.cs#L330

There's also this https://bitbucket.org/chromiumembedded/cef/issue/1050/cef3-onloadend-not-always-called-for

**Comment by amaitland** [comment]
Just as a followup http://magpcss.org/ceforum/apidocs3/projects/%28default%29/CefLoadHandler.html#OnLoadStart%28CefRefPtr%3CCefBrowser%3E,CefRefPtr%3CCefFrame%3E%29

>  For notification of overall browser load status use OnLoadingStateChange instead. 

`OnLoadStart` documentation actually now suggests using `OnLoadingStateChange` instead.

**Comment by perlun** [comment]
> I am aware of this one, IsLoading relies on OnLoadStart and OnLoadEnd which leads to this http://magpcss.org/ceforum/viewtopic.php?f=6&t=10906 post which should look familiar :smile:

Hehe, nice! :wink:

I think we should migrate over to using `OnLoadingStateChange` instead. Let's leave this issue open until we've done that. OK with you?

**Comment by amaitland** [comment]
Care to take #913 for a spin? Change only implemented in the context of `WPF` for now. If that solves the problem then we can look at the other flavors :smile:

**Comment by amaitland** [comment]
#931 contains the more drastic cleanup of the `API`, removing the old `IsLoading` and replacing with the recommended `OnLoadingStateChange` (Previously called `NavStateChanged`).

**Comment by amaitland** [comment]
Both #913 and #931 have been merged, so this should be resolved.
