### ISSUE TITLE
Feature Request - Load Request with Post Data

### ISSUE THREAD

**Issue by daveaton** [cefsharp/CefSharp#912]
I have a form that when filled out and clicked it does a POST to a new window.

How do I catch and pass the new POST info to the new window?

     public bool OnBeforePopup(IWebBrowser browser, string sourceUrl, string url, ref int x, ref int y, ref int width, ref int height)
     {
            var popupw = width;
            var popuph = height;
          
            this.InvokeOnUiThreadIfRequired(() =>
            {
            
                 var popup = new XfBrowserPopup(url, popupw, popuph, sourceUrl);
                  popup.Show();

           });

     }

I am not using the standard default popups.  I am using my own custom winforms.

XfBrowserPopup is just a new form that I create a new Browser Instance and dock with that form.

Any ideas ?

**Comment by amaitland** [comment]
Not implemented yet, though shouldn't be too hard. Without looking at it in too much detail it would be something like

- Expose the `LoadRequest` method
- Create a wrapper around `CefPostData`
- Add the `PostDataWrapper` to `IRequest`
- Create a method of mapping 

http://magpcss.org/ceforum/apidocs3/projects/%28default%29/CefFrame.html#LoadRequest%28CefRefPtr%3CCefRequest%3E%29
http://magpcss.org/ceforum/apidocs3/projects/%28default%29/CefRequest.html#Create%28%29
http://magpcss.org/ceforum/apidocs3/projects/%28default%29/CefPostData.html

There is an old `CefSharp1` PR that maybe useful https://github.com/cefsharp/CefSharp/pull/252 if ported to `CefSharp3`

The `cefclient` app has a basic example https://bitbucket.org/chromiumembedded/cef/src/6aea0d499afad0aa3651d3e47d4de0217e43e562/tests/cefclient/cefclient.cpp?at=2171#cl-140

**Comment by amaitland** [comment]
(I've edited the title of this issue, as a generic place holder for implementing `Post data`)

**Comment by amaitland** [comment]
This may not actually be possible currently, as `OnBeforePopup` doesn't appear to expose the `CefRequest` object that would be needed to get the post data.

Further investigation would be required.

**Comment by amaitland** [comment]
You can now provide a `ChromiumWebBrowser` instance to `OnBeforePopup` to use as the new browser rather than opening the default popup.

It's still somewhat experimental. See https://github.com/cefsharp/CefSharp/commit/326aaf70f83efe2a7b2c5867f455956a0fe19719 for a very basic not very well tested example.

**Comment by amaitland** [comment]
Might look at creating some extension methods in `vc++` to facilitate creating the wrapper instances.

http://stackoverflow.com/a/2176855/4583726

Haven't tried it yet, so will need to investigate.

**Comment by rover886** [comment]
@amaitland, Hi!

I am currently developing an flavoring application on CefSharp version 43. I want method to load the request object in CEF. To achive this `LoadRequest` method is helpful for me. So I searched for "LoadRequest" inside solution (downloaded from nuget) I found methods are there but commented. By some little modifications in 
`CefFrameWrapper.h` (Modified Line:137 as `virtual void LoadRequest(IRequest^ request);`)
`CefFrameWrapper.cpp` (Modification shown below at Line:136)
`iframe.cs`  (Modified at Line:80 as  `void LoadRequest(IRequest request);`)

I am able to call `ChromiumWebBrowser.GetMainFrame().LoadRequest(request)` where `request` is object of class `CefSharpRequest` written by me which implements `IRequest`.

Currently to check all the stuff is working and to give URL from flavoring application I created class  `CefSharpRequest` by implementing `IRequest`, which is as follows:

```
public class CefSharpRequest : IRequest
    {
        private string _url;
        private string _method;
        private System.Collections.Specialized.NameValueCollection _headers;
        private IPostData _postdata;
        private TransitionType _transitiontype;
        private bool _isdisposed;

        public string Url
        {
            get
            {
                return _url;
            }
            set
            {
                _url = value;
            }
        }

        public string Method
        {
            get { throw new NotImplementedException(); }
        }

        public System.Collections.Specialized.NameValueCollection Headers
        {
            get
            {
                throw new NotImplementedException();
            }
            set
            {
                throw new NotImplementedException();
            }
        }

        public IPostData PostData
        {
            get { throw new NotImplementedException(); }
        }

        public TransitionType TransitionType
        {
            get { throw new NotImplementedException(); }
        }

        public bool IsDisposed
        {
            get { throw new NotImplementedException(); }
        }

        public void Dispose()
        {
            throw new NotImplementedException();
        }
    }
```


 I implemented get;set; of `Url` property. All other stuff (PostData, PostDataElement) required for loading request is hard codded in `CefFrameWrapper.cpp` which is shown as follows:
```
// TODO: Do we need this?
///
// Load the request represented by the |request| object.
///
/*--cef()--*/
void CefFrameWrapper::LoadRequest(IRequest^ request)
{
	ThrowIfDisposed();
	CefRefPtr<CefRequest> Cefrequest(CefRequest::Create());

	Cefrequest->SetURL(StringUtils::ToNative(request->Url)); //request is object of CefSharpRequest class

	CefRefPtr<CefPostDataElement> postDataElement(CefPostDataElement::Create());
	std::string data = "param1=val1&param2=val2";
	postDataElement->SetToBytes(data.length(), data.c_str());
	CefRefPtr<CefPostData> postData(CefPostData::Create());
	postData->AddElement(postDataElement);
	Cefrequest->SetPostData(postData);

	Cefrequest->SetMethod("POST");

	_frame->LoadRequest(Cefrequest);
}
```

Now, can you guide to make `method` and `postData` dynamic from IRequest/CefSharpRequest ? I know for this I have to modify CefRequestWrapper.h, write wrapper for postData.

Or is it safe to create a property in `CefSharpRequest ` class which will take PostData in the format like "param1=val1&param2=val2", this property will accessed in  `LoadRequest`.
For eg.  `std::string data = StringUtils::ToNative(request->getPostData);` 
and same way for `method`.

**Comment by amaitland** [comment]
You need to expose the ability to create an instance of `CefRequestWrapper`, easiest way to do this is with a `VC++ Extension Method` on the `IFrame` interface. Implementing a class like your `CefSharpRequest` will create a lot of double handling.

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.Core/Internals/CefRequestWrapper.h

Rather than posting large code blocks, please create and submit a `PR`, I can then comment on your code inline.
