### ISSUE TITLE
Dropdown not working when form.TopMost=true

### ISSUE THREAD

**Issue by rover886** [cefsharp/CefSharp#914]
To reproduce this issue set form's `TopMost` property to `true`. after this navigate to webpage which contains dropdown list (`<select>`). clicking on it will just select the dropdown list. It's option cannot be shown.

I am using this code to make `form` topmost 

```
 public class Program
    {
        [STAThread]
        public static void Main()
        {
            Cef.Initialize(new CefSettings());            
            var browser = new BrowserForm();
            browser.TopMost = true;
            Application.Run(browser);
        }
    }
```

I am using version 37.

**Comment by amaitland** [comment]
I suspect this is a duplicate see https://github.com/cefsharp/CefSharp/issues/657

**Comment by rover886** [comment]
@amaitland, Before adding issue I have checked this post but I feel that is issue occurring without setting topmost property true.

I am facing it only when `TopMost` property of form made true, so I added separate issue. 

Surprising point is, previously I was using version 31, on this version dropdown is working perfectly even with TopMost is true. So how in latest build it's not working?

**Comment by amaitland** [comment]
> I am facing it only when TopMost property of form made true, so I added separate issue.

Both issues say when setting `TopMost = true`, so what about this makes it unique?

> So how in latest build it's not working?

Different version of `CEF`. Have you tried with version `39-pre03`?

**Comment by rover886** [comment]
Yes, checked with version 39-pre03. same issue.

**Comment by amaitland** [comment]
Can you clarify what's different from #657?

**Comment by amaitland** [comment]
Closing as this is a duplicate.
