### ISSUE TITLE
Unable to execute javascript in non administrator while other WCF service is running 

### ISSUE THREAD

**Issue by Antonyo** [cefsharp/CefSharp#915]
Hello,

some of our users have experience an issue that their WPF CEF browser wasn't responding, after some research we finally found a user that give us the clue, he was running voodooshield service which is a WCF service running as window service, he stated that in order to get it to work he need to either stop the voodooshield service or run our app as administrator.

I installed `https://voodooshield.com/`and I get to recreate it in Windows 7, W8.1 and W10 x64. Our WPF cef control wasn't working because we require some javascript to execute at initialization which was not being executed at all. 

I got to recreate it in your cefsharp solution examples, in the WPF example and the winform example. If you got the voodooshield service running (you don't need to enable voodooshield app actually, only get his service running) you will see that the `bound` object has not been register and you cannot execute javascript asynchronously. The bound object I refer is the one register in:

```CefSharp.Wpf.Example.Views.BrowserTabView.BrowserTabView line 19```

After some debugging (you need to run VS as not administrator to debug it) I think there must be some problem in the `BrowserProcessServiceHost`, I'm not sure but seems to be a problem with the named pipe, at least I noticed that the `BrowserProcessService`is never instantiated. Also the `BrowserProcessServiceHost.EvaluateScriptAsync` method also doesn't work because the `operationContextTask`never seems to terminate and the `ContinueWith` block is not executed.

The voodooshield team tell the user that they thought that this issue will occur while any generic WCF/Windows service is running but I've created a WCF running as windows service myself and there was no problem at all so we've contacted voodooshield to see what could be happening.

Thanks for the help

**Comment by amaitland** [comment]
As them if they specify a absolute address when creating their `WCF` service e.g. `net.pipe://localhost/CefSharpSubProcessProxy/6688/1`

You might find this useful http://stackoverflow.com/questions/10362246/two-unique-named-pipes-conflicting-and-invalidcredentialexception

**Comment by mol** [comment]
I talked to them and this is how the endpoint is defined in the config file:

```
<system.serviceModel>
    <bindings>
      <netNamedPipeBinding>
        <binding name="VoodooShieldServiceNetNamedPipeEndPoint" />
      </netNamedPipeBinding>
    </bindings>
    <client>
      <endpoint address="net.pipe://vswcfpipe/" binding="netNamedPipeBinding"
        bindingConfiguration="VoodooShieldServiceNetNamedPipeEndPoint"
        contract="VoodooShieldService.IVoodooShield" name="VoodooShieldServiceNetNamedPipeEndPoint">
        <identity>
          <certificateReference storeName="My" storeLocation="LocalMachine"
            x509FindType="FindBySubjectDistinguishedName" />
          <dns value="localhost" />
        </identity>
      </endpoint>
    </client>
  </system.serviceModel>
```

They also supplied me with a stripped down version of their service, for testing purposes. It also causes the problem with the CEF examples.

**Comment by amaitland** [comment]
Hmm, not giving their endpoint a unique address maybe a problem.

**Comment by mol** [comment]
I found this: http://stackoverflow.com/questions/2118114/prevent-named-pipes-conflict?rq=1 and tried adding a guid to the end of RenderprocessClientFactory.BaseAddress, but that didn't help.

The weird thing about this whole thing is that it won't work with standard privileges, but if you run it with admin privileges it works fine...

**Comment by amaitland** [comment]
Have you run `Process Monitor` to get a better understanding of what's happening? Being a named pipe you could be able to see the calls (at least I would expect you to be able to).

**Comment by mol** [comment]
I believe I have found the problem, but unfortunately no solution other than either moving away from WCF in CEF or having VoodooShield fix their implementation (which still leaves this issue open to happening with other 3rd party WCF named pipe apps). The issue is clearly described here: https://social.msdn.microsoft.com/Forums/en-US/ba1ad8e0-bf7d-4d90-b016-7add901cdc7a/wcf-netpipe-endpoint-not-found-exception-because-of-3rd-party-service-running?forum=wcf

The poster has a link to stackoverflow that also has a very thorough explanation of the issue.

**Comment by mol** [comment]
Oh and I tried the proposed workaround of setting the binding HostNameComparisonMode to Exact, but couldn't get that to work even without the VoodooShield service running.

**Comment by mol** [comment]
Update: I *could* get 'Exact' to work, but not while the service was running, so no change.

**Comment by amaitland** [comment]
> no solution other than either moving away from WCF in CEF

That's a valid option, `CEF` has it's own `IPC` which can be used. (Wasn't available when the `JSB` implementation was started). For speed, performance, reliability I think there's merit in moving away `WCF`, just a lot of work.

https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage#markdown-header-inter-process-communication-ipc

**Comment by amaitland** [comment]
Workaround for this issue is to use the `async` version of `JSB`. It's currently not practical to move the `WCF` implementation to `Native IPC` as the `render process` only has a single thread which prohibits making `sync` calls as the thread ends up being blocked.

`EvaluateScriptAsync` was ported to the `Native IPC`.

**Comment by fuzetsu** [comment]
To anyone experiencing a similar issue who is having trouble tracking down the offending WCF service:

This code will list the names of running WCF services.

```c#
var category = new PerformanceCounterCategory("ServiceModelService 4.0.0.0", Environment.MachineName);
var instances = category.GetInstanceNames();
foreach (var instance in instances)
{
    Console.WriteLine(instance);
}
```
