### ISSUE TITLE
Download updates and triggering LoadError

### ISSUE THREAD

**Issue by AJDev77** [cefsharp/CefSharp#919]
This is from https://stackoverflow.com/questions/29325009/cefsharp-download-window-for-showing-progress-in-vb-net.

I am creating a browser using Cefsharp in VB.Net, and I have been trying to create a download window that shows the progress of the current download. I don't know if I am doing something wrong or if it is the way CEF works, but I put in a download handler by adding <code>browser.DownloadHandler = New DownloadHandler</code> to <code>Form1_Load</code> and creating a new class like this (with <code>downloading</code> being the form I created for showing the progress):
```
    Public Class DownloadHandler
    Implements IDownloadHandler

    Public Function OnBeforeDownload(downloadItem As DownloadItem, ByRef downloadPath As String, ByRef showDialog As Boolean) As Boolean Implements IDownloadHandler.OnBeforeDownload
        downloadPath = downloadItem.SuggestedFileName
        showDialog = True
        downloading.Show()
        Return True
    End Function

    Public Function OnDownloadUpdated1(downloadItem As DownloadItem) As Boolean Implements IDownloadHandler.OnDownloadUpdated
        My.Settings.downloadpercent = downloadItem.PercentComplete.ToString
        Dim percentcomplete As Integer = My.Settings.downloadpercent * 5
        Return False
      End Function
   End Class
```
On the <code>downloading</code> form I have this code for showing the progress:
```
Private Sub Timer1_Tick(sender As Object, e As EventArgs) Handles Timer1.Tick
    Dim percentcomplete As Integer = My.Settings.downloadpercent * 5
    Me.PictureBox1.Size = New Size(percentcomplete, 25)
End Sub

Private Sub downloading_Load(sender As Object, e As EventArgs) Handles MyBase.Load
    Timer1.Start()
End Sub
```
This may not be the best way to show a <code>ProgressBar</code>, but I have a picture box that just has a green bar, and the total width of the form is 500px. The code is telling it to read the <code>PercentComplete</code> setting put in <code>My.Settings.downloadpercent</code>, multiply it by 5, so when the progress in 100%, it will go across the whole form.

The problem is that the ProgressBar is not being updated to show the current progress. It goes a little bit, but then it just stops. Am I doing something wrong, or is <code>OnDownloadUpdated</code> not a good place to put that? Any suggestions of how to fix this?

I am using CefSharp 39.0.0-pre03. Also, when the save file dialog comes up, no matter if you click Save or Cancel, the browser always triggers a <code>LoadError</code>, so it loads the custom HTML error page I made, and since it requires a URL for loading HTML, I put in "http://rendering/"... So I guess that would be a domain change. Issue #595 could be the problem, but then we also need to figure out why it is triggering a LoadError. I also created an issue on my browsers repository at  https://github.com/Emposoft/MySurf/issues/7, but it does not include any more information than what is here.

**Comment by amaitland** [comment]
I'd suggest starting by asking for clarification on http://magpcss.org/ceforum/

Had a quick look at the code, and both parts are very thin wrappers around the `CEF API`.

**Comment by AJDev77** [comment]
@amaitland  What do you mean by asking for clarification? Should I just post the same exact thing there?

**Comment by amaitland** [comment]
I would first ask about the load error behavior, ask if that's an expected behavior.

If you ignore the Aborted error, does the download progress continue?

**Comment by AJDev77** [comment]
@amaitland Okay, I will post there tonight. And yes, even though the progress bar stops working, the download will still complete.

**Comment by amaitland** [comment]
You mentioned redirecting on error, if you programmatically ignore the Aborted error does the progress get updated?

**Comment by AJDev77** [comment]
@amaitland Oh sorry for the misunderstanding... I just tried this and the download progress does get updated without the <code>LoadError</code> being put in. Now we know that issue #595 applies, because if I do go to a different page the progress stops... Now we just need to figure out what is causing the <code>LoadError</code> when the download gets started. I will make a post on the other website to ask them if it is expected or not.

**Comment by amaitland** [comment]
I'm unsure if the reporter of #595 actually reported the bug `upstream` so we may need to do that.

**Comment by AJDev77** [comment]
@amaitland Okay, how can we report this <code>upstream</code>? Is it just by posting something to the link you commented before? Because I was just about to do that...

**Comment by amaitland** [comment]
> Is it just by posting something to the link you commented before?

Yes, start with that.

**Comment by javathunderman** [comment]
@AJDev77 Sorry to barge in here- any updates on this?

**Comment by AJDev77** [comment]
@amaitland I am checking back on the other forum, and he has not responded for awhile now... did you hear anything?

**Comment by amaitland** [comment]
Not as yet, no.
