### ISSUE TITLE
JS exposed .NET Functions all lowercase

### ISSUE THREAD

**Issue by exinferis** [cefsharp/CefSharp#921]
All .NET Functions exposed towards Javascript within my JS Interface class are made lowercase. I have read that this is considered a feature. Yet it's absolutely not. 
It is imho clearly an error to dictate casing of functions. Please make it a choice, or remove this "feature".

My class is looking like this:

```C#
public class JavascriptInterface
{
  public void TokenCreated() {
    // Ultra fancy stuff here
  }
}
```

Within Javascript it will look like this:

```Javascript
window.JSInterface.tokenCreated()
```

**Comment by amaitland** [comment]
> It is imho clearly an error to dictate casing of functions. Please make it a choice, or remove this "feature".

Whilst that is your opinion, and you are entirely entitled to it, your comments come across as rude. A lot of people have spent countless hours contributing to this project. Should you not like it, then feel free to look for another solution.

I better approach would be `Is it possible to disable lowercase for javascript properties/functions? What changes are required? How can I help make that a reality?` 

I'm closing this post, should you wish to take a step back and reconsider your approach then feel free to create another.
