### ISSUE TITLE
Javascript exposed .NET functions lowercase

### ISSUE THREAD

**Issue by exinferis** [cefsharp/CefSharp#922]
Since my last attempt to post this issue was a bit...impulsive (sorry about that), I try again.

All Functions in C#/.NET which I expose towards Javascript are made lowercase, which in our case prevents Integration of CefSharp into our project.

What is the background of this and how can this be prevented? I do not have the possibility to change the JS, so I need to expose Uppercase Functions within an object towards JS. 

My class is looking like this:

```C#
public class JavascriptInterface
{
  public void TokenCreated() {
    // Ultra fancy stuff here
  }
}
```

Within Javascript it will look like this:

```Javascript
window.JSInterface.tokenCreated()
```

**Comment by avspeed** [comment]
you might want to look at https://github.com/cefsharp/CefSharp/blob/9fe07e50cedde2d8b8c17d2d081118c16ed11ae1/CefSharp/Internals/JavascriptObjectRepository.cs

mores specifically this 

jsMethod.JavascriptName = LowercaseFirst(methodInfo.Name);

**Comment by amaitland** [comment]
> What is the background of this and how can this be prevented? I do not have the possibility to change the JS, so I need to expose Uppercase Functions within an object towards JS.

The simplest approach would be to create an overload for `RegisterJsObject(string name, object objectToBind, bool lowerCaseJavascriptNames)`, from there it's just a matter of passing through the chain until it get to `JavascriptObjectRepository.Register`. Another option would be to create an `Attribute` to decorate your class, this has a few benefits for allowing other configuration options, and having them on a per class basis. I think for now the simple approach of another param is the best option.

Quickest way to make this happen is if you submit a `PR`.

> I am not sure why this was done this way .. maybe cef is excepting it to be lower case.

It's just a convention, not strictly required. It was the default for `CefSharp1`, so it just got carried over to `CefSharp3`.

**Comment by perlun** [comment]
This is by design, done by me. Rationale: It should be possible to write your .NET code using ".NET style", i.e. `Class.SomeMethodName()` while still exposing it JS style in the JS code. `class.someMethodName()`.

But making it parameterized or controlled by a .NET attribute is of course a way to work around it.
