### ISSUE TITLE
Unable to find version 3.2171.2069 of package cef.redist.x64

### ISSUE THREAD

**Issue by xelplogoog** [cefsharp/CefSharp#924]
So, how to build it from the sources?
can't restore nuget packages

![cef nuget](https://cloud.githubusercontent.com/assets/2188302/6966633/30e1b0ba-d963-11e4-8c27-3204aeac59ec.png)

**Comment by amaitland** [comment]
Packages are on `Nuget` see http://www.nuget.org/packages/cef.redist.x64/3.2171.2069 for an example.

If you simply build the solution what error did you get? What steps have you tried so far? Your not giving much information to go on there.

**Comment by amaitland** [comment]
Make sure you have the latest `Nuget` version installed.

**Comment by xelplogoog** [comment]
ok, thx, I've updated Nuget, now I can at least run wpf.example project
but I still have an error about restoring packages

![cef nuget](https://cloud.githubusercontent.com/assets/2188302/6979269/41482858-d9ea-11e4-9c17-87a12aa027cd.png)

**Comment by amaitland** [comment]
If you download `nuget.exe` and run it from the command line your likely to get a much more detailed error message.

**Comment by amaitland** [comment]
@xelplogoog Any further update before closing?

**Comment by xelplogoog** [comment]
no, now it works fine. thx!

**Comment by amaitland** [comment]
Great, closing :+1:
