### ISSUE TITLE
Support IME-aware

### ISSUE THREAD

**Issue by xland** [cefsharp/CefSharp#925]
It would be nice if CefSharp were enhanced to support IME-aware applications, so that CJK(China Japan Korea) text can be entered in a more natural form.
@shen6041 
@perlun 
@jstdoit

See:
https://code.google.com/p/chromiumembedded/issues/detail?id=254
And:
https://github.com/cefsharp/CefSharp/pull/211
(This issue is not fixed)

**Comment by amaitland** [comment]
> (This issue is not fixed)

Firstly that PR relates to `CefSharp1`, so isn't really relevant.

Also you made no reference to which flavour of `CefSharp` your referencing. I'm assuming `WPF`, for which there is already an open issue #583, please continue the conversation there.
