### ISSUE TITLE
at what point are the dependencies needed ?

### ISSUE THREAD

**Issue by avspeed** [cefsharp/CefSharp#926]
Hello,

Scenario: 
I am extracting the cefsharp dependencies to the application folder right before calling Cef.Initialize
and the call to Cef.Initialize fails.

Once all the dependencies are there in the application folder, and I rerun my app, Cef.Initialize returns true.

Obviously I am not extracting them at the right moment.

When are they needed exactly ?

**Comment by amaitland** [comment]
> I am extracting the cefsharp dependencies to the application folder right before calling Cef.Initialize
> and the call to Cef.Initialize fails.

I do something similar to deal with `ClickOnce` installer. Shouldn't be a problem to copy them at runtime, long as it's before `Cef.Initialize()`.

What does your code look like?

**Comment by avspeed** [comment]
Yeah ... it works my bad - closing.
