### ISSUE TITLE
Feature Request - Implement OnQuotaRequest

### ISSUE THREAD

**Issue by barriestewart** [cefsharp/CefSharp#927]
Hi,

I'm running v39.0.0-pre03 and was wondering if there was any way of tweaking the size of the HTML5 application cache? I think it's about 5MB but I was hoping to increase this to something closer to 20. Thanks.

-B

**Comment by avspeed** [comment]
@barriestewart  I believe that in CEF 3 you can currently only set it via Javascript

See http://magpcss.org/ceforum/viewtopic.php?f=6&t=10577

and https://developer.chrome.com/apps/offline_storage on how to request more storage

**Comment by amaitland** [comment]
`CefSharp` doesn't currently implement `OnQuotaRequest`. Shouldn't take more than 15mins to add.

http://magpcss.org/ceforum/apidocs3/projects/%28default%29/CefRequestHandler.html#OnQuotaRequest%28CefRefPtr%3CCefBrowser%3E,constCefString&,int64,CefRefPtr%3CCefQuotaCallback%3E%29

**Comment by amaitland** [comment]
This was resolved with #962 and will be available in the upcoming `41.0.0` release.
