### ISSUE TITLE
Copy and Paste Does not work Inside Iframe when using main menu

### ISSUE THREAD

**Issue by daveaton** [cefsharp/CefSharp#928]
I am using the latest master CEF r2069 and it seems if you right click on a text box the default context copy and paste seems to work great, but if you use the winform file menu from the top the controls do not work correctly.

Here is an example.

http://jsfiddle.net/zsv27p7d/

http://www.eatoncode.com/shareit/2015-04-04_1632.swf

As a work around I am using CTRL + v  by send keys.

		public class SimulateKeys
		{
			public static void SimulateKeyStroke(char key, bool ctrl = false, bool alt = false, bool shift = false)
			{
				List<int> keys = new List<int>();

				if (ctrl)
					keys.Add(VK_CONTROL);

				if (alt)
					keys.Add(VK_MENU);

				if (shift)
					keys.Add(VK_SHIFT);

				keys.Add(char.ToUpper(key));

				INPUT input = new INPUT();
				input.type = INPUT_KEYBOARD;
				int inputSize = Marshal.SizeOf(input);

				for (int i = 0; i < keys.Count; ++i)
				{
					input.mkhi.ki.wVk = keys[i];

					bool isKeyDown = (NativeMethods.GetAsyncKeyState(keys[i]) & 0x10000) != 0;

					if (!isKeyDown)
						NativeMethods.SendInput(1, ref input, inputSize);
				}

				input.mkhi.ki.dwFlags = KEYEVENTF_KEYUP;
				for (int i = keys.Count - 1; i >= 0; --i)
				{
					input.mkhi.ki.wVk = keys[i];
					NativeMethods.SendInput(1, ref input, inputSize);
				}
			}

			//[DllImport("user32.dll")]
			//static extern uint SendInput(uint nInputs, ref INPUT pInputs, int cbSize);

			//[DllImport("user32.dll")]
			//static extern short GetAsyncKeyState(int vKey);

			internal struct MOUSEINPUT
			{
				public int dx;
				public int dy;
				public uint mouseData;
				public uint dwFlags;
				public uint time;
				public IntPtr dwExtraInfo;
			}

			internal struct KEYBDINPUT
			{
				public int wVk;
				public ushort wScan;
				public uint dwFlags;
				public uint time;
				public IntPtr dwExtraInfo;
			}

			internal struct HARDWAREINPUT
			{
				public int uMsg;
				public short wParamL;
				public short wParamH;
			}

			[StructLayout(LayoutKind.Explicit)]
			internal struct MOUSEKEYBDHARDWAREINPUT
			{
				[FieldOffset(0)]
				public MOUSEINPUT mi;

				[FieldOffset(0)]
				public KEYBDINPUT ki;

				[FieldOffset(0)]
				public HARDWAREINPUT hi;
			}

			internal struct INPUT
			{
				public int type;
				public MOUSEKEYBDHARDWAREINPUT mkhi;
			}

			const int INPUT_KEYBOARD = 1;
			const uint KEYEVENTF_KEYUP = 0x0002;

			const ushort VK_SHIFT = 0x10;
			const ushort VK_CONTROL = 0x11;
			const ushort VK_MENU = 0x12;
		}

        private void tsmPasteText_Click(object sender, EventArgs e)
        {
            cmsBrowserContext.Hide(); //hide custom context menu
            SimulateKeys.SimulateKeyStroke('v', ctrl: true); //Paste

            //this.InvokeOnUiThreadIfRequired(() =>
            //{
            //    Browser.Paste();
            //});
        }

This seems to work perfect but some antivirus software flag this as a virus.

I noticed in ManagedCefBrowserAdapter.h there is a SendKeyEvent()  can this be used to do the same thing?

I am using C# Winforms .NET 4.0

Thanks.

Here is all I can find related to the subject.

https://groups.google.com/forum/#!topic/cefsharp/sF-yD9D5ZrA

**Comment by jankurianski** [comment]
Since the menus are simply calling the underlying [`CefFrame`](http://magpcss.org/ceforum/apidocs3/projects/(default)/CefFrame.html) methods `Cut` `Copy` `Paste`, it is probably a bug in CEF.  Unfortunately the `cefclient.exe` test app doesn't have the clipboard methods in its test menu, so you would have to whip up a C++ example before reporting upstream.

> I noticed in ManagedCefBrowserAdapter.h there is a SendKeyEvent() can this be used to do the same thing?

No, this method is just for `OSR` mode).

Maybe try the [`2272`](https://github.com/cefsharp/CefSharp/tree/cef/2272) branch of CefSharp and see if it is fixed there?

**Comment by jankurianski** [comment]
Just updated the title because the context menu (the menu invoked by right-clicking) actually does work, and this caused me confusion.

**Comment by amaitland** [comment]
From memory the commands are executed on the main frame, swapping them to current frame maybe enough. Otherwise some sort of frame identifier would need to be passed as a param.

**Comment by amaitland** [comment]
```c++
void Copy()
{
	auto browser = _clientAdapter->GetCefBrowser();
	if (browser != nullptr)
	{
		browser->GetMainFrame()->Copy();
	}
}
```

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/ManagedCefBrowserAdapter.h#L492

`GetFocusedFrame()`  might do the trick
http://magpcss.org/ceforum/apidocs3/projects/%28default%29/CefBrowser.html#GetFocusedFrame%28%29

**Comment by daveaton** [comment]
@amaitland This worked like a charm!  Yey!

        void Copy()
        {
            auto browser = _clientAdapter->GetCefBrowser();

            if (browser != nullptr)
            {
                browser->GetFocusedFrame()->Copy();
            }
        }

        void Paste()
        {
            auto browser = _clientAdapter->GetCefBrowser();

            if (browser != nullptr)
            {
                browser->GetFocusedFrame()->Paste();
            }
        }

**Comment by amaitland** [comment]
@daveaton Care to submit a PR?

**Comment by amaitland** [comment]
@daveaton Any comments on fixing this? Just working on what milestone it should go against. Were you planning on submitting a PR?

**Comment by daveaton** [comment]
Sorry.  I will post a PR soon, I am currently out of the reach of my desktop and only have ability to remote in with my phone..  As soon as I can get to desktop I can post the fix :)

**Comment by amaitland** [comment]
Great, thanks for the update :+1:

**Comment by rassilon** [comment]
@daveaton , I just pushed a PR for this, it'd be great if you could try it out. Maybe, I'll add an Edit menu tomorrow to the WinForms.Example app before I merge the PR in if you can't test it soon.

Fyi,
Bill
