### ISSUE TITLE
Possibility to look at the response of a request?

### ISSUE THREAD

**Issue by LeMoussel** [cefsharp/CefSharp#930]
I would like to look at the response (eg response header, mime type, status text, etc ...) that the server sends before returning it to the browser.

But in this topic [Intercept and modify response (CEF3)](http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=10794), it appears that there's no great way to get response contents with CEF3 currently.
But it would be possible to use CefResourceHandler via CefRequestHandler::GetResourceHandler and execute the request/return the response contents yourself using CefURLRequest.
And there is this [Python implementation - wxpython-response.py](https://code.google.com/p/cefpython/source/browse/cefpython/cef3/linux/binaries_64bit/wxpython-response.py?r=dfff7897665f).

I can work on this subject . But I'm starting with CefSharp/CEF3,It's  a bit hard for me - wouldn't know where to start. I need a little help getting started.

**Comment by rassilon** [comment]
Hrm. The easiest way to do this would be to start by wrapping `CefURLRequest/CefURLRequestClient` in C++/CLI happiness. 

I would then probably utilize them from a custom HTTP(S) SchemeHandler so the requests would get processed asynchronously.  (ResourceHandlers in CefSharp can't be async yet. :( )

Bill

**Comment by amaitland** [comment]
Closing with #1300
