### ISSUE TITLE
Failed to launch child process

### ISSUE THREAD

**Issue by perlun** [cefsharp/CefSharp#938]
Hi,

I get the following error when trying to use CefSharp 39. Version 37 works fine. What could be causing it?

```
[0410/101955:ERROR:child_process_launcher.cc(344)] Failed to launch child process
```

Are there any new files that have been added in the new version or what could be causing this? We have a slightly complex setup w/ postbuild that copies over files into the proper folders, so we need to explicitly mention stuff. It looks like this. Note that we e.g. only copy the `en-US.pak` file (which works fine w/ CefSharp 37).

```
    <Exec Command='
mkdir $(SolutionDir)..\ui\$(PlatformName)
mkdir $(SolutionDir)..\ui\\$(PlatformName)\locales
xcopy /i /y "$(TargetDir)*.dll" "$(SolutionDir)..\ui\$(PlatformName)"
xcopy /i /y "$(TargetDir)*.exe" "$(SolutionDir)..\ui\$(PlatformName)"
xcopy /i /y "$(TargetDir)*.pak" "$(SolutionDir)..\ui\$(PlatformName)"
xcopy /i /y "$(TargetDir)*.dat" "$(SolutionDir)..\ui\$(PlatformName)"
xcopy /i /y "$(TargetDir)locales\en-US.pak" "$(SolutionDir)..\ui\$(PlatformName)\locales"

if $(PlatformName) == x86 set sysdir=%25windir%25\SysWOW64
if $(PlatformName) == x64 set sysdir=%25windir%25\System32

xcopy /y %25sysdir%25\msvcr110.dll "$(SolutionDir)..\ui\$(PlatformName)"
xcopy /y %25sysdir%25\msvcp110.dll "$(SolutionDir)..\ui\$(PlatformName)"
    '/>
```

**Comment by amaitland** [comment]
What happens if you run the dependency checking at runtime? e.g.
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/CefExample.cs#L64

**Comment by pushplay** [comment]
I'm also having trouble running the sample projects from the latest version of CefSharp.  Cef.Initialize returns true but CefSharp.BrowserSubprocess never shows up in Task Manager.

**Comment by jankurianski** [comment]
@pushplay Typically this is due to missing dependencies.  What does the new dependency checker report?  (See @amaitland's comment above on how to run it)

**Comment by amaitland** [comment]
If your having problems with master I'd suggest doing a git cleanup and starting fresh.

**Comment by avspeed** [comment]
The last time I received the "Failed to launch child process" error , it was because I was missing the CefSharp.BrowserSubprocess.exe and CefSharp.BrowserSubprocess.Core.dll in the directory where my executable was running from...

**Comment by pushplay** [comment]
@jankurianski I did a git cleanup and rebuilt.  ```performDependencyCheck``` is true as it is in the example.  When running out of VS ```BrowserSubprocess``` doesn't start and I don't see any unusual output in the console.  *But* if I run ```CefSharp.WinForms.Example.exe``` out of the folder then ```BrowserSubprocess``` starts and the example behaves as expected.

**Comment by amaitland** [comment]
Comment out https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/CefExample.cs#L46

**Comment by pushplay** [comment]
@amaitland That got it going, thanks.  If the non-existence of that exe is a fatal problem maybe a simple File.Exists check would be a good idea?

**Comment by amaitland** [comment]
@pushplay There is a check in place, just for it to exist in the default location. Needs to be expanded to check if you provide a custom path.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp/DependencyChecker.cs#L182

**Comment by pushplay** [comment]
@amaitland Ok I see how that's done.  I can contribute that fix.  Why do the dependency checking functions take part of the CefSettings object?  Why not just accept the object?

**Comment by amaitland** [comment]
> I can contribute that fix.

Great :+1: 

> Why not just accept the object?

Just incase you wanted to call it yourself in whatever fashion you like. Looking back it probably can just take a `CefSettings` reference for simplicity.

**Comment by amaitland** [comment]
`Housekeeping`, closing old issues. Reopen if required.
