### ISSUE TITLE
Can not Build, can not download

### ISSUE THREAD

**Issue by pixartist** [cefsharp/CefSharp#939]
Yeah, the current version of cef is referencing non-existant NuGet packages, and the current and prerelease versions of NuGet Cef.Core are referencing non existant versions of Cef.Runtime.x86. So there is no way to use Cef ATM

**Comment by pixartist** [comment]
Okay I had to select NuGet as an additional source for packages in order to get the dependancies.

**Comment by amaitland** [comment]
> Cef.Core are referencing non existant versions of Cef.Runtime.x86

Where exactly did you get those packages names from? lol

All sorted now? Can we close this?

**Comment by amaitland** [comment]
I have seen something similar before, so I've opened #941, it's probably something trivial.
