### ISSUE TITLE
Custom context menu

### ISSUE THREAD

**Issue by Sential** [cefsharp/CefSharp#943]
Hi, how to implement custom context menu strip? 
Best regards, Eryk.

**Comment by amaitland** [comment]
> custom context menu strip

What exactly is that?

Please read over
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue and provide additional information.

**Comment by Sential** [comment]
I don't know how to implement context menu strip into the cefsharp browser. I tried browser.ContextMenuStrip = Context1; but it doesn't working. It shows the default Context menu, but I want to change this. ;) Sorry for my bad English, I'm from Poland :)

**Comment by jankurianski** [comment]
This is not implemented.  The context menu is controlled by the `MenuHandler` property.  Here is an example implementation:
https://github.com/cefsharp/CefSharp/blob/9fe07e50cedde2d8b8c17d2d081118c16ed11ae1/CefSharp.WinForms.Example/MenuHandler.cs

The only useful thing it does now is allow you to disable the context menu.

CEF has more complicated menu logic available (including changing the menu items), but it is not currently exposed in CefSharp: https://github.com/svn2github/cef3/blob/master/include/cef_context_menu_handler.h

I see a few ways to go from here:
a) Implement the rest of the CEF menu handler in CefSharp (requires simple C++ knowledge).
b) Disable the default CEF menu via the `MenuHandler`, and manually show/hide the `ContextMenuStrip`.
c) Disable the default CEF menu via the `MenuHandler`, and implement a context menu in JavaScript/HTML.  This is what I do in my application.

**Comment by Sential** [comment]
Ok thanks i will try that. Can you help me with js HTML context menu? If you can...

**Comment by amaitland** [comment]
@Sential For future reference it would have been helpful if you specified that you were using the `WinForms` flavor of `CefSharp`. That would have given context to your question. Also as a general rule it's preferable if you also include the version you are using.

**Comment by lxa520** [comment]
IContextMenuHandler
