### ISSUE TITLE
Implementation not found for OnBeforePopup

### ISSUE THREAD

**Issue by almalkawi** [cefsharp/CefSharp#945]
I updated my app's dependency from CefSharp.Wpf 39.0.0-pre03 to CefSharp.Wpf 39.0.0 and ran into: Method 'OnBeforePopup' in type 'MyApp.CefLifeSpanHandler' from assembly 'MyApp, Version=0.8.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

My CefLifeSpanHandler class implements ILifeSpanHandler and uses the new method signature for OnBeforePopup

```
public bool OnBeforePopup(IWebBrowser browser, string url, ref int x, ref int y, ref int width, ref int height)
 {
    return true;
}
```

I have no idea what the problem is. Any suggestions on what I might be missing?

**Comment by amaitland** [comment]
See `Breaking Changes` https://github.com/cefsharp/CefSharp/releases/tag/v39.0.0

New `targetUrl` param was added

https://github.com/cefsharp/CefSharp/blob/master/CefSharp/ILifeSpanHandler.cs#L35

**Comment by almalkawi** [comment]
I mistyped. I did update OnBeforePopup according to the breaking change notice

This is what I have:
```
public bool OnBeforePopup(IWebBrowser browser, string sourceUrl, string targetUrl, ref int x, ref int y, ref int width, ref int height)
```

but still failing at runtime with the same "method does not have an implementation" error.

**Comment by amaitland** [comment]
Sounds somewhat like `VS` has got an old reference somewhere in the output folders. Have you tried closing `VS`, remove all temp files, if your using `git`, then ` git clean`. That or manually delete all the `bin` and `obj` folders.

I'm sure it's something simple.

**Comment by almalkawi** [comment]
Thanks @amaitland for the suggestion. I cleaned my nuget cache, cleaned VS project and removed temp files, still the same issue :/

Just to confirm, these are the packages I am using:
```
  <package id="cef.redist.x64" version="3.2171.2069" targetFramework="net45" />
  <package id="cef.redist.x86" version="3.2171.2069" targetFramework="net45" />
  <package id="CefSharp.Common" version="39.0.0" targetFramework="net45" />
  <package id="CefSharp.Wpf" version="39.0.0" targetFramework="net45" />
```

**Comment by amaitland** [comment]
Everything is working fine with the `MinimalExample` when I add a `LifeSpanHandler` see https://github.com/amaitland/CefSharp.MinimalExample/commit/32e8f938ebe32311880f8e56ba00a8a275bdc463

If you create a new project or fork the `MinimalExample` are you able to reproduce the issue?

**Comment by almalkawi** [comment]
It was indeed some stale Visual Studio cache. Recreating the project fixes the issue. Thanks @amaitland and sorry for the false alarm.

**Comment by amaitland** [comment]
@almalkawi No problem, glad it's sorted :+1:
