### ISSUE TITLE
Implement TaskScheduler Wrapper around Cef Threads

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#946]
Moving conversation from #933 

https://github.com/cefsharp/CefSharp/pull/933#issuecomment-92511548

I looked some more into .Net Task stuff today, I'm thinking we probably need the following:

* A separate `SyncronizationContext` for each CEF thread type
* A `TaskScheduler` for each CEF thread type (unsurprisingly from a common base class)
* A `TaskFactory` instance per CEF thread type to that helps creates tasks against our `TaskScheduler` instance.
* Setting `TaskScheduler.Current` during callbacks from CEF to the correct scheduler.
* ditto for `SyncronizationContext.Current`
* The `TaskScheduler`s would only post one task at a time to the thread so that the `QueryPending` (or whatever its exact name is) method can return data on what isn't being processed yet. The idea would be to Post the next job after the current one finishes.
* We need to remember to use the new `base::Bind` stuff instead of the runnable stuff in the CEF API due to depreciation of the latter.
* We might not need a custom `TaskScheduler` if the default implementation for `ThreadScheduler.FromSyncronizationContext` static method meets our needs combined with our `SyncronizationContext` code.

Those are the broad strokes just thinking about it briefly after looking at the .Net Task docs today.
Some of this goo could be wrapped up in a ThreadManager component, having the `.Current` goo in the same method is a good idea. :smile:

**Comment by amaitland** [comment]
@rassilon Moving the conversation here, so it doesn't get lost in the closed PR :smile: 

> Those are the broad strokes just thinking about it briefly after looking at the .Net Task docs today.

Can you post any links that you might think are relevant for reference?

> Some of this goo could be wrapped up in a ThreadManager component,

I was thinking that `ThreadManager` (or whatever we call it) would be the public interface, and potentially lazy load some of the `TaskFactory/TaskScheduler` instances as they're not likely to all be needed by every user. Maybe some sort of `ConcurrentDictionary` with `enum` lookup?

> We need to remember to use the new base::Bind stuff instead of the runnable stuff in the CEF API due to depreciation of the latter.

We should probably do that as the first thing, upgrade the current code used by the `JSB` binding. Get that working and move on from there. Thoughts?

**Comment by rassilon** [comment]
I noticed that GetZoomLevel() wasn't ever running on the CEF UI thread like it is supposed to.
I tried using `base::Bind()`..., but that way lies madness for passing managed objects into the task,
even the `CefRunnable` way lay madness. No useful managed structure will marshal through it. (i.e. `Task`/`ManualEventResetSlim`/Action<*>/Func<*>/etc...).

Ugh ugh ugh.

Fyi,
Bill


We'll need to create a CefTask subclass that can handle nice things like Action/Func/Action<>/Func<> goo.

Blech.

Bill

**Comment by rassilon** [comment]
Based on discussions in the other PRs (since merged into 2272), it looks like we have these remaining tasks:

Remaining tasks:
- [ ] Unhandled exception pattern for `CefTaskWrapper`
- [ ] Breaking change on `IWebBrowser` for `ZoomLevel` -> `GetZoomLevelAsync`
- [ ] Wait for alex to think about whether or not `SyncContexts` are work persuing in CefSharp since it might help make `await` written tasks easier to deal with.
- [ ] Think about what might make it easier to deal with .Net `Task` vs `CefTask` given the inability to create `Func<>/Action<>' instances with C++ classes that are C++ template expansions.

**Comment by rassilon** [comment]
@amaitland , for `ZoomLevel -> GetZoomLevelAsync`, should WinForms/WPF cache the `ZoomLevel` at the `ChromiumWebBrowser` level, or should we **always** ask CEF what the current `ZoomLevel` is?

**Comment by amaitland** [comment]
> or should we always ask CEF what the current ZoomLevel is?

I would say for simplicity always get the current zoom level. It's no like your going to make the call hundreds of times a second and need some sort of performance improvement that caching gives. The `WPF` control only kept a local copy as the `GetZoomLevel()` method always returned `0` (as your aware).

**Comment by amaitland** [comment]
> Wait for alex to think about whether or not SyncContexts are work persuing in CefSharp since it might help make await written tasks easier to deal with.

On this one, I think we stay away from `SyncContexts` for now, keep it simple. For the most part calls will be made from within `CefSharp` it's self.

**Comment by rassilon** [comment]
> On this one, I think we stay away from SyncContexts for now, keep it simple. For the most part calls will be made from within CefSharp it's self.

Works for me, crossed that one off the list.

Bill

**Comment by rassilon** [comment]
Closing for now since the only thing left is a better way to create the necessary .Net func/action types for the small functions we need to schedule via tasks.
