### ISSUE TITLE
Trying to compile. Getting lots of errors.

### ISSUE THREAD

**Issue by pixartist** [cefsharp/CefSharp#947]
I'm trying to compile in VS2013 and I'm getting a bunch of errors: 

	Error		error C2976: 'std::array': too few template arguments	CefSharp.Core	StreamAdapter.cpp	24
	Error		error C3699: '^': cannot use this indirection on type 'std::array'	CefSharp.Core	StreamAdapter.cpp	24
	Error		error C2726: 'gcnew' may only be used to create an object with managed type	CefSharp.Core	StreamAdapter.cpp	24
	Error		error C2514: 'std::array': class has no constructors	CefSharp.Core	StreamAdapter.cpp	24
	Error		IntelliSense: too few arguments for class template "std::array"	CefSharp.Core	StreamAdapter.cpp	24
	Error		IntelliSense: expected a type specifier	CefSharp.Core	StreamAdapter.cpp	24
	Error		IntelliSense: too few arguments for class template "std::array"	CefSharp.Core	StreamAdapter.cpp	24
	Error		error C2664: 'int System::IO::Stream::Read(cli::array<unsigned char,1> ^,int,int)': cannot convert argument 1 from 'std::array *' to 'cli::array<unsigned char,1> ^'	CefSharp.Core	StreamAdapter.cpp	25
	Error		error C2440: 'initializing': cannot convert from 'std::array *' to 'cli::pin_ptr<unsigned char>'	CefSharp.Core	StreamAdapter.cpp	26
	Error		error C2976: 'std::array': too few template arguments	CefSharp.Core	SchemeHandlerWrapper.cpp	103
	Error		error C3699: '^': cannot use this indirection on type 'std::array'	CefSharp.Core	SchemeHandlerWrapper.cpp	103
	Error		error C2726: 'gcnew' may only be used to create an object with managed type	CefSharp.Core	SchemeHandlerWrapper.cpp	103

Why ? (Tried Master & 39.0)

edit: fixed the error by hand by using the cli:: namespace on the array types. Now I'm getting 

> error LNK1181: cannot open input file 'libcef_dll_wrapper.lib'	CefSharp.Core	LINK	

When I manually add the corresponding libcef_dll_wrapper.lib from the packages I'm getting

>  error LNK2038: mismatch detected for '_MSC_VER': value '1800' doesn't match value '1900' in AssemblyInfo.obj	CefSharp.Core	libcef_dll_wrapper.lib(allow_certificate_error_callback_ctocpp.obj)	

Edit: Got it to work by setting the target platform to 110 vs2012 (XP) and creating a new subfolder in the sdk next to vs2012 and vs2013 called vs2010 with the same lib file as 2012

**Comment by amaitland** [comment]
@pixartist As a general thing it's better to post followup comments rather than edit your original post, `GitHub` doesn't provide notifications when posts are edited only new comments made.

As for your errors, that's unclear. In general both `VS2012` and `VS2013` should work without problem. Can you confirm you have the latest version of Visual Studio installed (I believe that's `Update 4` at time of writing). Is there anything else about your dev environment that should be taken into account?

Are you building from source for a specific reason?

**Comment by pixartist** [comment]
I keep everything up to date. And I'm compiling from source to get XP compatibility which is not given by the Nuget package.

**Comment by jornh** [comment]
> Edit: Got it to work by setting the target platform to 110 vs2012 (XP) and creating a new subfolder in the sdk next to vs2012 and vs2013 called vs2010 with the same lib file as 2012

OK @pixartist thanks for updated info. :smile:  If you got it working now is anything more needed before closing this issue?

> I keep everything up to date. And I'm compiling from source to get XP compatibility which is not given by the Nuget package.

Right - Makes sense if you need that XP compat... Please also see the discussion in #907 which might interest you. Maybe you can team up with @lamerbug in https://github.com/cefsharp/CefSharp/issues/907#issuecomment-93699361 to work on XP support as long as it's feasible? We have an old issue in the cef-binary repo regarding splitting `cef.sdk` into more granular packages: https://github.com/cefsharp/cef-binary/issues/6 it would enable you guys to maintain VS2010 sdk separately (sounds healtier than just copying the VS2012 binaries over)

Thoughts?

**Comment by lamerbug** [comment]
>> Edit: Got it to work by setting the target platform to 110 vs2012 (XP) and creating a new subfolder in the sdk next to vs2012 and vs2013 called vs2010 with the same lib file as 2012

No no u'd better manually rebuild libcef wrapper and create custom packages in native XP environment with vs2010/net40.

**Comment by amaitland** [comment]
> No no if u need xp support u'd better manually rebuild libcef wrapper and create custom packages in native XP environment with vs2010/net40.

Not necessary. If you simply build in `VS2013` targeting `V120` then `CefSharp` will run just fine long as you install the `VC++ 2013 Redist`. Technically the official `nuget` packages will work if you can meet all dependencies.
