### ISSUE TITLE
Additions to `OnRenderProcessTerminated` wrapper

### ISSUE THREAD

**Issue by rassilon** [cefsharp/CefSharp#948]
It should be based on the logic in cefclient, and do something like:
- Call the CEF messge router `OnRenderProcessTerminated`
- Set wasCrashUrl based on 'chrome://crash'
- Determine MainFrame's URL of browser
- Pass `wasCrashUrl` and MainFrame's URL to user handler.
- (I'm not sure if we should bother passing start url to the handler, that behavior of cefclient seems possibly incorrect for the general case of CefSharp's users.)

The idea here is the CEF message router cancels pending messages involved in CEF's new JS communication stuff when the render process dies.

The user's handler would only need to decide what they want to do from there.
i.e. follow the cefclient example or not

We could have a `DefaultOnRenderProcessTerminated` function that could implement the rest of the `cefclient` logic if we wanted. (i.e. just reload the startup url if there was one)

Bill

**Comment by amaitland** [comment]
> Call the CEF messge router OnRenderProcessTerminated

Little unclear what you mean by this one? 

> We could have a DefaultOnRenderProcessTerminated function that could implement the rest of the cefclient logic if we wanted. (i.e. just reload the startup url if there was one)

How would this fit with the current `IRequestHandler.OnRenderProcessTerminated` method?

**Comment by rassilon** [comment]
> > Call the CEF messge router OnRenderProcessTerminated
> Little unclear what you mean by this one?

The [CEF message router](https://bitbucket.org/chromiumembedded/cef/src/9be541ef4ecfe02abeda2457357a8df0c6440788/include/wrapper/cef_message_router.h?at=2171) is the new fangled JS messaging mechanism that's built into CEF.

There's apparently other callbacks we'd have to call it from as well. (see the header for more details)

> > We could have a DefaultOnRenderProcessTerminated function that could implement the rest of the cefclient logic if we wanted. (i.e. just reload the startup url if there was one)
> How would this fit with the current IRequestHandler.OnRenderProcessTerminated method?

The idea would be the ClientAdapter.cpp would call the message router handling and then call the .Net layer handler method. That handler method then could call `DefaultOnRenderProcessTerminated` if it so desired.

Bill

**Comment by amaitland** [comment]
> The CEF message router is the new fangled JS messaging mechanism that's built into CEF.

Cool, looks like it's worth looking into :+1:

**Comment by rassilon** [comment]
Since we made the breaking change for IBrowser parameter addition, I might as well write this up (ignoring the js message router bit).

**Comment by amaitland** [comment]
> Since we made the breaking change for IBrowser parameter addition, I might as well write this up

Now is the time for breaking changes :smile:
