### ISSUE TITLE
Keyboard Events not firing when building with CefSharp

### ISSUE THREAD

**Issue by exinferis** [cefsharp/CefSharp#952]
I have a pretty straightforward Application on C#, which currently consists of a single form with CefSharp included in a splitpanel. When running the app non of the keyboard events (```OnKeyDown```...) seems to work and accessing the menu strips menu items via their key combination (Ctrl+F for example) doesn't work either.
When compiling the app without the ```ChromiumWebBrowser``` all keyboard events work fine. 

Is there a way to intercept the keyboard events before they get processed within CefSharp?

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/blob/master/CefSharp/IKeyboardHandler.cs

**Comment by amaitland** [comment]
For clarity are you using `WinForms` or `WPF`?

**Comment by exinferis** [comment]
I am using it within a ```WinForms``` Application.

**Comment by exinferis** [comment]
Exactly what was needed. Thanks a lot.

**Comment by mia-petkovic** [comment]
Is there a tutorial or an example how could key handling be implemented for simple WinForm application. The link from the comment to IKeyboardHandler is no longer accessible.
