### ISSUE TITLE
could not debug the program with CefSharp

### ISSUE THREAD

**Issue by Peterinor** [cefsharp/CefSharp#956]
Hello,

I couldn't debug my program with CefSharp 39. Debug process with exit auto without a error when the program run to `Cef.Initialize(settings)`; But just running the program is OK.

What i miss with the initialization?

**Comment by Peterinor** [comment]
Hello,

I couldn't debug my program with CefSharp 39. Debug process with exit auto without a error when the program run to `Cef.Initialize(settings)`; But just running the program is OK.

What i miss with the initialization?

**Comment by jankurianski** [comment]
Can you debug the MinimalExample?
https://github.com/cefsharp/CefSharp.MinimalExample

**Comment by amaitland** [comment]
@Peterinor Any further update on this?

**Comment by Peterinor** [comment]
debuging MinimalExample work well !

but the cefsharp project `https://github.com/cefsharp/CefSharp` not !

I'm working on VS2013 in windows8.1.

**Comment by jankurianski** [comment]
Will need more information.  Can you include everything from here: https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue

**Comment by Peterinor** [comment]
I found out the reason!

The program could not debug because I compressed the cef.dll using upx 'http://upx.sourceforge.net/' for less disk cost.

sorry for the mistake.
