### ISSUE TITLE
CefSharp.BrowserSubprocess.exe crashes on callback with large data

### ISSUE THREAD

**Issue by rstmm** [cefsharp/CefSharp#958]
Hi,

We are currently experiencing problems when loading data from a C# Application using a callback object:

    m_xx = new ChromiumWebBrowser();
    //[...]
    m_xx.RegisterJsObject("callbackObj", new DataAccess());

For simplification, assume that DataAccess has the method:

    public String LoadLongData()
    {
        var longString = new string('*', 20592341); // normally we load objects from database and serialize them to JSON, but this doesn't matter.
        return longString;
    }

Now doing the following call in JS:

    callbackObj.LoadLongData();

Crashes the subprocess without any message. When using a smaller return data set, this method works as expected. So this must be related to the size of returned data.

The only things i could find were in windows event viewer:

----------- First this error: -------------

Anwendung: CefSharp.BrowserSubprocess.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund eines Ausnahmefehlers beendet. (=~ Application was stopped due to an error)
Ausnahmeinformationen: System.ServiceModel.CommunicationException
Stapel:

Server stack trace: 
   bei System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   bei System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   bei System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)
   bei System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(System.Runtime.Remoting.Messaging.IMessage, System.Runtime.Remoting.Messaging.IMessage)
   bei System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(System.Runtime.Remoting.Proxies.MessageData ByRef, Int32)
   bei CefSharp.Internals.IBrowserProcess.CallMethod(Int64, System.String, System.Object[])
   bei CefSharp.JavascriptMethodWrapper.Execute(System.Object[])
   bei <Module>.CefSharp.JavascriptMethodHandler.Execute(CefSharp.JavascriptMethodHandler*, CefStringBase<CefStringTraitsUTF16>*, CefRefPtr<CefV8Value>*, std.vector<CefRefPtr<CefV8Value>,std::allocator<CefRefPtr<CefV8Value> > >*, CefRefPtr<CefV8Value>*, CefStringBase<CefStringTraitsUTF16>*)
   bei <Module>.CefExecuteProcess(CefMainArgs*, CefRefPtr<CefApp>*, Void*)
   bei CefSharp.CefAppWrapper.Run()
   bei CefSharp.BrowserSubprocess.Program.Main(System.String[])

---------- Followed by this error: --------

Name der fehlerhaften Anwendung: CefSharp.BrowserSubprocess.exe, Version: 37.0.0.0, Zeitstempel: 0x549256a5 
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 6.1.7601.18798, Zeitstempel: 0x5507b485
Ausnahmecode: 0xe0434352
Fehleroffset: 0x0000c42d
ID des fehlerhaften Prozesses: 0x2234
Startzeit der fehlerhaften Anwendung: 0x01d07b3f8bc54f61
Pfad der fehlerhaften Anwendung: D:\xxx\trunk\Implementation\Source\NativeWrappers\ChromiumWrapper\xxx\bin\x86\Debug\CefSharp.BrowserSubprocess.exe
Pfad des fehlerhaften Moduls: C:\windows\syswow64\KERNELBASE.dll
Berichtskennung: d30e8bc1-e732-11e4-bff1-5cc5d4533da5

Could you please have a look at this, since we need this for a client project?

Thanks in advance!

**Comment by amaitland** [comment]
Sounds like your crashing the `WCF` service. You'll have to toy with the `WCF` binding to find out which limit needs to be raised.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp/Internals/BrowserProcessServiceHost.cs#L124

**Comment by rstmm** [comment]
Hi,

thanks for your reply!

The limits in the file look ok - except this one:

    binding.MaxReceivedMessageSize = SixteenMegaBytesInBytes;

our current test string has ~20 MB, so I assume this is the one that causes the failure.

Is there any way I can access these binding objects after creating my browser process?

Greetings

**Comment by amaitland** [comment]
> Is there any way I can access these binding objects after creating my browser process?

Not currently. The `CreateBinding()` method is used by the service and client, so for simplicity it's hard coded. What's the max amount of data you'd be trying to transmit?

**Comment by amaitland** [comment]
If you wish to up the limit your welcome to submit a `PR`.

**Comment by rstmm** [comment]
That's hard to predict... Our client is tracking sensors for experiments which could run for days. We reached 20 MB after ~22 hours of tracking. 100MB or even more could be possible. Maybe we need to also introduce compression, but we also need to raise that limit.

What would speak against raising the limit to int.MaxValue, same as the others?

**Comment by amaitland** [comment]
> What would speak against raising the limit to int.MaxValue, same as the others?

Technically I believe that's valid, though I expect your `UI` performance will suffer if you go too crazy.

**Comment by amaitland** [comment]
I'm inclined to set the max size to `128MB` as per the internal `IPC`. At some point the current `WCF` implementation will be replaced and use `Chromium`'s native `IPC` mechanism. going past that limit doesn't make much sense.

https://code.google.com/p/chromium/codesearch#chromium/src/ipc/ipc_channel.h&l=93

**Comment by rstmm** [comment]
Ok that would be great! I think we could work with 128 MB and some more optimization - even for large experiments.

Is there any way you could also add some error-catching to prevent the process from crashing silently?

And thanks for your very fast support!

**Comment by amaitland** [comment]
> Is there any way you could also add some error-catching to prevent the process from crashing silently?

As it's the `BrowserSubProcess` that crashes it's somewhat difficult to report back on the errors. The native `IPC` will be more robust in that sense. If you've got some suggestions then my all means.

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/commit/1d2b5fa55cd47746ad2da3479f0411baf83953eb

**Comment by rstmm** [comment]
Not really at the moment... Looks a bit tricky. At least you can find something in event log, so I think before doing too complicated things here we can live with that.

Thanks for the commit, we'll try if this solves our problem and report back.

**Comment by rstmm** [comment]
Ok, this did the trick, we are now able to load huge amounts of data. :+1: 

Thanks again!
