### ISSUE TITLE
Print dialog Preferences bug

### ISSUE THREAD

**Issue by sandust** [cefsharp/CefSharp#960]
Using the Print command(context menu) in the WPF example or the Print button in a PDF sometimes makes the Print dialog not respond properly.

Steps to reproduce:
1. Run the WPF.Example
2. Open a New Tab
3. Right on the browser and select the "Print" menu item
4. Click on "Preferences" and then close it
5. Repeat step 4 until the "Preferences" button becomes unresponsive (sometimes only once is necessary)
6. Now none of these buttons will work: Print, Preferences, Cancel, Apply, Close.
7. Have to kill the process via Task Manager. (Or stop debugging if using Visual Studio)

Note: Sometimes it will keep working no matter how long you try, in that case close the application and try again. I'd say the chances of it happening are close to 50%

This problem happens in:
* Visual Studio 2012
* Visual Studio 2013
* Installed WPF application using ClickOnce

I'm using Windows 7 64bit fully updated.

I'm using version 39.0.0 from nuget, but I was also able to reproduce it with the Master branch.

**Comment by amaitland** [comment]
`CefSharp` is simply a wrapper in this case, we simply call the `Print()` command. At first glance I'd mark this as an upstream bug. Can you confirm by trying the `cefclient` example as explained below

https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

**Comment by sandust** [comment]
You are correct, this is not a CefSharp issue. I was able to reproduce the error using the latest cefclient.

for the records I ran the x86 version on my windows 7 64bit running the cefclient with the following command: cefclient --multi-threaded-message-loop --off-screen-rendering-enabled

Seems I was been optimistic about the 50%. It took me almost a full minute of clicking preferences and closing to get it to lock up.

**Comment by amaitland** [comment]
> Seems I was been optimistic about the 50%. It took me almost a full minute of clicking preferences and closing to get it to lock up.

At least you were able to reproduce the issue.

I see you opened a issue with `CEF` :+1: 
https://bitbucket.org/chromiumembedded/cef/issue/1613/print-dialog-preferences-locks-up-when-osr

**Comment by amaitland** [comment]
`master` has been updated to a newer version of `CEF`, so probably worth revisiting this, see if an update to `CEF` makes any difference.

**Comment by amaitland** [comment]
Closing this as it's been a long time. If the problem still persists with the current version (`45.0.0` at time of writing) then we can reopen.
