### ISSUE TITLE
.Net User Control hosted in IE, CEF fails to load browser

### ISSUE THREAD

**Issue by bjwallwin** [cefsharp/CefSharp#971]
I have a .Net user control that embeds a cef browser.  When I host the control from IE all of my non-cef content loads, but the browser fails to load.  I don't get any exceptions (that are presented to me), there is just no browser.

I had the same behavior with a .net client hosting the user control until I ensured that my client application was in the same directory with my CEF dependencies, then it worked fine.  Which makes me think it is a similar issue? The problem being is IE cannot be loaded from the same directory as my user control.

Is there some enviro variable or path that needs needs to be added in order for the CEF, CefSharp files to be loaded out of the install directory?

**Comment by amaitland** [comment]
Run `Cef.Initialize()` with dependency checking enabled to make sure the files are present. By default all the dependencies need to be in your apps binary directory.

See https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/CefExample.cs#L86

For clarity please include version and flavor e.g, `WinForms`

**Comment by bjwallwin** [comment]
Thank you for the quick reply.  To add some further context.  
- My .Net User Control is WinForms based.
- In my User Control (app) directory I have all of the dependency files.
   - If I run a test application from my app directory all woks well, if however I start my html page 
     (which is in my app directory) using IE, I can see my user control load and the non CEF content   
     loads, but the browser portion of my control never loads.

I have not tried initializing with dependency checking enabled, I will do that for completeness.

**Comment by amaitland** [comment]
> if however I start my html page (which is in my app directory) using IE, I can see my user control load and the non CEF content loads, but the browser portion of my control never loads.

I'm unsure how `IE` loads controls, likely that as it's the executing application that the `CEF` assemblies aren't within a discoverable location.

**Comment by amaitland** [comment]
@bjwallwin Did you find out the executing path of your `IE control`? Were the dependencies accessible?

**Comment by bjwallwin** [comment]
@amaitland  Not yet, I am working on that this morning.  Dumb question, If I have a path setup to my user control directory that has all dependencies, shouldn't that be discoverable by IE or for that matter any other executing application? 

I will provide updates hopefully in a little while, and hopefully a positive resolution.

**Comment by avspeed** [comment]
IE Protected Mode restriction is the only thing that come to mind here. CefSharp is, after all, trying to launch another process (CefSharp.BrowserSubprocess.exe ) from your user control which is hosted in IE
https://msdn.microsoft.com/en-us/library/bb250462%28v=vs.85%29.aspx

**Comment by rassilon** [comment]
Oh yeah, that probably is the cause. Good call. IE runs in a lower integrity level from the OS point of view, You would probably need to debug it to discover exactly what is going on. However, the linked article seems to indicate that using the pattern shown at [Staring Low Integrity Processes](https://msdn.microsoft.com/en-us/library/bb250462%28v=vs.85%29.aspx#dse_stlip) is how you successfully create Low Integrity child processes. I wouldn't be surprised if CefSharp doesn't end up calling `CreateProcessAsUser`.

**Comment by amaitland** [comment]
Anything else required before we close this one?

**Comment by rassilon** [comment]
Don't think so. If process launching happens in CefSharp, I wouldn't be against a PR that is low integrity process friendly. However, you or I are very unlikely to care to do it ourselves I would imagine.

**Comment by bjwallwin** [comment]
Bill, Alex,

This is and will be an issue for any user that chooses to use CefSharp in a .Net user control situation in which that control can be hosted in IE or any other container (i.e. browser) where a low integrity process would be necessary.  I think this would be a good fix (or enhancement) to extend the usefulness of CefSharp in the community at large.

Bill, you alluded to the fact that neither of you would be interested in doing this, does that then mean that I would have to fork CefSharp and do the work myself.

**Comment by rassilon** [comment]
That's the general idea, yeah. For, develop fix, submit PR. I haven't even checked to see if CefSharp is the code that launches the subprocess. 

If CefSharp does launch the process, then the change described by the previously linked urls needs to be made. 

(probably via pinvoke, but pinvoke.Net probably has declarations for any apis you might need.)

**Comment by avspeed** [comment]
Actually I do not believe that anything needs to be done in CefSharp. 
Read the section about "Starting Processes from Protected Mode". Technically all that you have to do is mark the location where CefSharp.BrowserSubprocess.exe resides as a low integrity location.
You do that by adding a few registry keys as described in the article. 
What you need to think about is how you will write those registry keys. 
Registering your .NET User control on a machine will require you to run regasm with elevated rights, so you should use whatever process you use to register your control to also add the 'low integrity registry keys'. 
@amaitland @rassilon It would be great if you could leave this thread opened so that we can discuss this further as @bjwallwin tries to implement this. 
Again, I do not believe that anything needs to be done with CefSharp.

**Comment by rassilon** [comment]
@avspeed , Those registry entries that are mentioned in the article appear to be about allowing a higher integrity IE extension to be launched.

Maybe the best bet is to install [Application Compatiliby Toolkit](http://www.microsoft.com/en-us/download/details.aspx?id=7352) as suggested in the article and see what gets logged.

Then we can maybe have a more specific clue about the underlying problem. 

Bill

**Comment by amaitland** [comment]
Any update on this? Happy to keep open if there's an active discussion, otherwise I'll probably close.

**Comment by bjwallwin** [comment]
@amaitland I am getting back to this, got sidetracked with other higher priority issues.  Will follow up soon with further findings and questions.

**Comment by bjwallwin** [comment]
@amaitland I am closing this issue as I no longer have a requirement to support execution from IE.  This doesn't fix the issue I was having, but its no longer relevant to me.
