### ISSUE TITLE
Custom scheme handler only invoked on first browser instance in 39.0.0

### ISSUE THREAD

**Issue by crystalbyte** [cefsharp/CefSharp#973]
Hi,

after updating from 37.0.0 to 39.0.0 I have noticed that only the first browser instance reacts to custom scheme handlers, all calls invoked on additional instances are ignored. 
Can any one reproduce this issue ?

**Comment by amaitland** [comment]
Are you able to reproduce the problem with either `WinForms.Example` or `Wpf.Example`? Quick test and I'm not seeing a problem. So more information is required.

If it's complex to reproduce then forking the `MinimalExample` might be the go.
https://github.com/cefsharp/CefSharp.MinimalExample

**Comment by jankurianski** [comment]
I use a custom scheme with multiple instances of ChromiumWebBrowser and have no issues in  39. It must be something specific to your app.

**Comment by amaitland** [comment]
@crystalbyte Can you provide a `GIST` of your code or fork the `MinimalExample` project to demo the problem?

https://github.com/cefsharp/CefSharp.MinimalExample

**Comment by crystalbyte** [comment]
I created a GIST which can be viewed here: https://gist.github.com/crystalbyte/bd4ff29f08f815a103ac
The Browser is wrapped in a custom control. The first file is the scheme handler in question.
The other two represent the two ways a navigation request can be issued, either by setting a dependency property or when the template is being applied.

The full source code is also publicly available here https://github.com/crystalbyte/paranoia and builds on the fly in Visual Studio.

**Comment by crystalbyte** [comment]
I have managed to pinpoint the problem.
It is not due to instancing, it seems no longer possible to call ChromiumWebBrowser.Load(...) from the OnApplyTemplate call. It is simply ignored, which is very sad indeed :(

**Comment by amaitland** [comment]
> it seems no longer possible to call ChromiumWebBrowser.Load(...) from the OnApplyTemplate call of a custom control.

You have to wait for the browser to be initialized before calling `Load()`

**Comment by crystalbyte** [comment]
> You have to wait for the browser to be initialized before calling Load()

Thanks, I did indeed call Load() before the browser was initialized, it must have worked simply by accident before. Sorry for the false alarm.

**Comment by amaitland** [comment]
I see your including the actual `CefSharp` source code in `paranoia`, do you make many changes to the code it's self to work in your app?

**Comment by crystalbyte** [comment]
>I see your including the actual  CefSharp  source code in  paranoia , do you make many changes to the >code it's self to work in your app?

No, we included the source for debugging purposes only since we have encountered a single machines where CEF simply does not run any JS code at all.
Currently we use the latest NuGet package so the source code will be dropped shortly.

**Comment by crystalbyte** [comment]
In general CefSharp seems very stable, the only downside we have encountered is the fact, that the controls totally mess up the designer. In 39.0.0 every control throws a NotImplementedException and issues a missing assembly reference warning in design time.

**Comment by amaitland** [comment]
> In 39.0.0 every control throws a NotImplementedException and issues a missing assembly reference warning in design time.

I personally gave up on the designer a long time ago. If you can narrow down what's causing the problem or find a viable solution feel free to open another issue or even better a `PR` :smile:

**Comment by crystalbyte** [comment]
There is a general problem with mixed mode assemblies and reflection.
http://stackoverflow.com/questions/4755453/designer-rejecting-user-control

If the assembly cannot be reflected, there is no way to make it work with the designer.
A move towards P/Invoke would probably be the easiest and quickest solution.

**Comment by amaitland** [comment]
> A move towards P/Invoke would probably be the easiest and quickest solution.

`P/Invoke = CefGlue`
