### ISSUE TITLE
Feature Request - Implement WPF Touch Scrolling

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#975]
Implement `Touch Scrolling` using `OnMouseWheel`

Should be able to use the `TouchMove` even to implement.
http://blogs.msdn.com/b/llobo/archive/2009/12/07/wpf-touch-basics.aspx

Might be worth digging into the `Microsoft® Surface® 2.0 SDK and Runtime` for some inspiration
http://www.microsoft.com/en-au/download/details.aspx?id=26716

**Comment by tolemac** [comment]
+1

**Comment by MihaMarkic** [comment]
The fact that WinForms version works with touch made me think. And for me in my specific case, it works, if I host WinForms version inside a WPF application (using WindowsFormsHost). Many thanks to @amaitland. If it won't work I'll definitely check the path mentioned in top post.

**Comment by amaitland** [comment]
Anyone looking to implement this can likely use #1418 as a basis.

**Comment by amaitland** [comment]
Changes have been merged into the `cefsharp/47` branch. They will be available in the official `47.0.0` release though not enabled by default. See #1418 for details.
