### ISSUE TITLE
function() properties don't work on bound objects

### ISSUE THREAD

**Issue by jamespearce2006** [cefsharp/CefSharp#989]
When creating a Javascript-bound object, creating a property to hold a Javascript function doesn't seem to work. Methods work fine - it just seems to be properties that don't work.

For example:

    public class BoundObject
    {
        IJavascriptCallback evt;
        public IJavascriptCallback MyEvent
        {
            get
            {
                return evt;
            }
            set
            {
                if (evt != null)
                    evt.Dispose();
                evt = value;
            }

        }
    }

If I call this in Javascript:

    bound.myEvent = function(){};

The value assigned that gets assigned to MyEvent property is null.

I've event tried an property of type "object", but assigning a function still results in a null value.

Should this work, or am I doing something wrong? What's the proper way of implementing an event on an object?

**Comment by amaitland** [comment]
> Should this work

No

> What's the proper way of implementing an event on an object?

Just use a regular method

**Comment by amaitland** [comment]
You can keep a reference to the `IJavascriptCallback`, so you could simply do

```
public void RegisterFunction(IJavascriptCallback javascriptCallback)
{
  //Store reference to javascriptCallback for later execution.
  //Dispose of previous reference if required
}

bound.registerFunction(function() { });
```

**Comment by amaitland** [comment]
`IJavascriptCallback` is only relevant to function/methods

**Comment by amaitland** [comment]
Anything else before closing?

**Comment by jamespearce2006** [comment]
No. My question was answered.
Please go ahead.
