### ISSUE TITLE
Update 2272 to 2357

### ISSUE THREAD

**Issue by Jayman1305** [cefsharp/CefSharp#991]
Given that 2272 is the dev build of sorts ;-) is there any chance that it could be ported to 2357 given that the dev chanel is now chrome 44 on cefbuilds and 2357 is the latest released build now. There is functionality in Chrome Remote Debugging Protocol that works in the samples from cef in 43 but not in 41. I tried to migrate but lets just say i failed horribly.

**Comment by amaitland** [comment]
With the appearance of `2357` the

**Comment by amaitland** [comment]
> CEF maintains two release branches at a time -- the stable release branch and the dev release branch. Each stable release branch is supported with crash/security bug fixes at least until the dev release reaches Chrome's stable channel, at which time the current dev release branch becomes the new stable release branch. The timing and creation of new CEF release branches currently matches approximately every other Chrome version.

With the appearance of `2357`, the `2272` branch is now the stable release branch and I imagine will be deemed release ready shortly. The `2357` branch is likely 2-3 months from being classes as stable.

> I tried to migrate but lets just say i failed horribly.

How far did you get? Did you manage to repackage the `cef-binary` pieces successfully?

**Comment by Jayman1305** [comment]
Thanks @amaitland. I basically tried a file replace (cef files) in my build. Wasn't expecting much and wasn't surprised. Would you classify 2357 as unstable at this point?

**Comment by amaitland** [comment]
> I basically tried a file replace (cef files) in my build.

Steps to repackage a release from `cefbuilds.com` are here https://github.com/cefsharp/cef-binary/wiki
Once you've done that, then it's a matter of using the `nuget` packages and upgrading `CefSharp` (you don't have to upload the `nuget` packages anywhere, you can use the directory based approach in `nuget`).

> Would you classify 2357 as unstable at this point?

It's still under active development. If you look at the `2171` branch as an example, which is a release branch https://bitbucket.org/chromiumembedded/cef/branch/2171 You'll see that there are a quite a few commits after the initial branching, same goes for `2272`. I'd expect `2357` to upgrade `Chromium` versions 2-3 times before it's release and have a number of patches and API changes also.

**Comment by Jayman1305** [comment]
Far to bleeding edge for me then. Thanks for the info.
