### ISSUE TITLE
So, how do I go about exactly using CefSharp?

### ISSUE THREAD

**Issue by Dgameman1** [cefsharp/CefSharp#992]
I'm currently trying to add CefSharp to my tools so that I can drag and drop a webbrowser onto my form.

I installed CefSharp via NuGet in Visual Studio 2013. 

I then right-clicked the tools section and selected "Choose Items"

In the ".NET Framework Components" I selected browse and click on CefSharp.wpf.dll

I then get this error

![http://i.imgur.com/wDAAabB.png][1]

**How can I add the CefSharp browser to my toolbox in Visual Studio 2013?**

  [1]: http://i.stack.imgur.com/Z5NiP.png

**Comment by amaitland** [comment]
A working example https://github.com/cefsharp/CefSharp.MinimalExample/

The `Nuget` package should have displayed a readme.txt, lots of information in that.

https://github.com/cefsharp/CefSharp/blob/master/NuGet/Readme.txt

**Comment by Dgameman1** [comment]
Where can I find the .dll for wpf?

What directory would it be in?

**Comment by Dgameman1** [comment]
I updated the opening question

**Comment by jornh** [comment]
That update made your question quite a bit more specific :+1:  I tried to answer it (or something very similar) at http://stackoverflow.com/a/29999884

Closing here!

**Comment by Dgameman1** [comment]
Lmao I'm honestly trying so hard right now. I promise I'm not this retarded, *usually*. You're saying it should be in the XAML Designer Window? Lol where is that exactly http://i.imgur.com/eoDt3S3.png or http://i.imgur.com/yj0klGW.png

**Comment by amaitland** [comment]
There are a couple of ways, one simple one 
- Right click on the `xaml` file
- `Open With`
- Select `Source Code (Text) Editor`
- Click `OK`

**Comment by Dgameman1** [comment]
Everyone keeps telling me to open up the xaml file.
Where would the XAML file be? That's my question. I don't see it anywhere!

**Comment by amaitland** [comment]
It would appear that your using `WinForms` and you've installed the `WPF` version of `CefSharp`.......

**Comment by amaitland** [comment]
For `WinForms` just add the control in code. Example:

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.WinForms.Example/BrowserTabUserControl.cs#L16

**Comment by amaitland** [comment]
Limited support is available in version 63. 

Please don't comment on issues that have been closed for years, the content is very likely out of date as is the case here. 

Please ask questions on https://gitter.im/cefsharp/CefSharp
