### ISSUE TITLE
For render process create a TaskScheduler for CefV8Context (or something)

### ISSUE THREAD

**Issue by rassilon** [cefsharp/CefSharp#994]
Not all CefV8Context's run on `TID_RENDER`, so we need an adapter to post tasks to `CefV8Context::GetTaskRunner()`

Bill

**Comment by amaitland** [comment]
Can you post a reference doc link?

**Comment by rassilon** [comment]
[CEF V8 header comment](https://bitbucket.org/chromiumembedded/cef/src/4715a1644e292e191d3840b59a74f821be91daec/include/cef_v8.h?at=master#cl-122)

**Comment by amaitland** [comment]
Were you thinking of being able to execute a `Task` or just be able to call ` CefTaskRunner.PostTask` in a convenient fashion?

**Comment by rassilon** [comment]
The latter, make calling `CefTaskRunner.PostTask` easy.

**Comment by amaitland** [comment]
Looks like only `WebWorkers` run on a different thread, and you can't access bound functions directly. Maybe this isn't required?

http://magpcss.org/ceforum/viewtopic.php?f=10&t=12813&p=25287&hilit=WebWorker#p25287
