### ISSUE TITLE
Wrap CefBrowser, and expose CefBrowser instances to CefSharp users

### ISSUE THREAD

**Issue by rassilon** [cefsharp/CefSharp#995]

**Comment by amaitland** [comment]
I was thinking with all the exposed wrappers eg IFrame we should make them disposable incase people keep a reference to them. Thoughts?

**Comment by rassilon** [comment]
Hrm. via the Cef disposable list? I was also thinking of just caching the wrapper objects in ManagedCefBrowserAdapter or ClientAdapter since the # of them tends to remain fairly low. The tricky part of course is thread safety.

**Comment by amaitland** [comment]
Not sure on the best approach, for the request handler methods, should the wrappers only be valid in the context of the method? I wouldn't keep a global list of handlers like `Cef.AddDIsposable()`

From the memory management side of things I think it's ok to make the user somewhat responsible if we provide an easy to follow pattern that they must adhere to.

`CefRequest` says it can be used on any thread, so that's straight forward. `CefFrame` and `CefBrowser` say they can be used on any thread in the browser process unless otherwise specified, and I can't see anything in the API doc, I'm not on my main computers, so I'm looking at the `2171` doc, so that may have changed. So overall I'm not overly worried about thread safety.

**Comment by rassilon** [comment]
I added ~ destructors so that we would null out the IBrowserAdapter reference, (and of course the MCefRefPtr gets cleaned up there as well, (verified via dotPeek) 

This of course exposes IDisposable in .Net land.

Aside from fixing up ClientAdapter to pass in IBrowsers correctly, (I was thinking as an additional parameter (i.e. the ManagedBrowserAdapter would still get passed in) and some testing...

I think the only other major thing is:
* How should the various ChromiumWebBrowser controls expose IBrowser instances?
ClientAdapter stores them in a `std::vector` at the moment, but how should we wrap the collection in .Net? `Dictionary<browserId, IBrowser>` or `List<IBrowser>` or `Dictionary<url, List<IBrowser>>`?

Thoughts?

Bill

**Comment by amaitland** [comment]
> How should the various ChromiumWebBrowser controls expose IBrowser instances? ClientAdapter stores them in a std::vector at the moment, but how should we wrap the collection in .Net? Dictionary<browserId, IBrowser> or List<IBrowser> or Dictionary<url, List<IBrowser>>?

What are some use cases? I would have started with a basic `List`

**Comment by rassilon** [comment]
The need to expose them somehow comes from trying to be flexible about when or via what API our users can do things with the popup windows. (i.e. get text/source/execute js/whatever)

I was thinking that we might want to expose the `IBrowsers` from the ChromiumWebBrowser and via the various handler callbacks. 

If we're going to expose them from `ChromiumWebBrowser` it'd be nice if the `IBrowser`s were a little easier to deal with than just a `List<IBrowser>`. Like maybe a `Dictionary<browserId, Lazy<IBrowser>>` or something. Or `Dictionary<url, Lazy<IBrowser>>` or whatever.

That's the general idea of why I'm asking.

Bill

**Comment by amaitland** [comment]
> The need to expose them somehow comes from trying to be flexible about when or via what API our users can do things with the popup windows. (i.e. get text/source/execute js/whatever)

I get the need to expose them :smile: I was thinking more about specific use cases, like functional ones. Would I know the `browserId` prior to accessing the dictionary? Do we encourage people to keep a reference to the `browserId` and only get a handle to the `IBrowser` instance when they actually need it to reduce memory leaks? What scenario would you lookup a `IBrowser` by it's `Url`?

Just trying to think about how you'd interact with the `API`.....

**Comment by amaitland** [comment]
Also should we `WeakReference` them?

**Comment by rassilon** [comment]
If `ChromiumWebBrowser` uses a `WeakReference` to `IBrowsers` via whatever data structure type, then we'd probably have a `Dictionary<browserId, Lazy<IBrowser>>` object in ClientAdapter. That way ClientAdapter would get rid of them sanely when the popup closes.

Seems sensible I think. We'd want to ensure that the ClientAdapter handler calls always occur on CEF's UI thread to verify thread safeness of the collection (around creating new popups of course)

**Comment by amaitland** [comment]
> Seems sensible I think. We'd want to ensure that the ClientAdapter handler calls always occur on CEF's UI thread to verify thread safeness of the collection (around creating new popups of course)

Sounds reasonable. Implementing `Lazy<>` in the `C++` side of things might be interesting. What are the benefits as opposed to just creating a new instance wrapper? As it just takes a refptr, I would imagine the overhead is low and as they're closed it's simple enough to remove them. If you think there's enough benefit to using `Lazy<>` then I've got no problem with that, just sounds like it'll be messy (I could be way off there).

**Comment by rassilon** [comment]
It's not really about overhead persay, just no need to do the work until asked, that's all. (If it doesn't cause too much C++/CLI compiler grief of course.)

**Comment by amaitland** [comment]
We already create a wrapper instance at least when `LifeSpanHandler` is implemented, so in some cases we do the work already.

Thinking about this more, we could follow the same approach `Cef` takes and keep things super simple. Just expose the `CefBrowser` instance in `OnBeforePopup` (as you've already implemented), letting the user keep a reference there and in `OnBeforeClose` we release the ref ptr. Provide a `ILifeSpanHandler` example implementation that cleanly adds and removes the browser instances. Even if they don't release their wrapper reference, the underlying pointer has been released. We'd need to add some `NULL` checks and throw exceptions if accessing the pointer after it's been released.

The main `ChromiumWebBrowser` instance exposes the key parts of `CefBrowser` (we can add any missing ones, though I think we have it covered already).

At some later point we could take this further as your suggesting, though maybe it's not necessary? Very few requests actually come up about accessing the underlying popup, most people are interested in intercepting popup creation and spawning their own instance so it's styled/themed like their application.

Thoughts?

**Comment by rassilon** [comment]
Sounds like a plan.

**Comment by rassilon** [comment]
Ok, I've merged #996 , I started working on part 2 with an improved IDisposable and prepping for ClientAdapter to auto create the `IBrowser` instances.

However, after ClientAdapter has the `IBrowser` instances, then we move onto the handlers.

`OnAfterCreated` isn't exposed for popups at all. Should we expose a `OnAfterCreated` that gets called regardless (and after) `OnInitialized`?

`OnBeforeClose` is ONLY called for the main `CefBrowser`, we should probably create a `OnBeforeClosePopup` for popups.

`OnTooltip` looks wrong for popups. :frowning: I should create a separate issue for that I think.

`OnConsoleMessage/OnStatusMessage` Is it worth passing `IBrowser` into here? I wouldn't think so.

`OnKeyEvent`: Add IBrowser param.
`OnPreKeyEvent`: ""
`OnLoadStart`: We should probably create an `OnPopupLoadStart`.
`OnLoadEnd`: ""
`OnLoadError`: Add IBrowser param.
`OnBeforeBrowser`: Add IBrowser param
`OnCertificateError`: ""
`OnQuotaRequest`: ""
`OnBeforePluginLoad`: ""
`OnPluginCrashed`: ""
`OnRenderProcessTerminated`': I don't think we need to change anything here.
`OnResourceRedirect`: Add IBrowser param
`OnProtocolExecution`: ""
`GetResourceHandler`: Add IBrowser and IFrame params.
`OnBeforeResourceLoad`: Add IBrowser param
`GetAuthCredentials`: ""
`OnBeforeContextMenu`: ""
`OnGetFocus`: ""
`OnSetFocus`: ""
`OnTakeFocus`: Hrm. Can this ever get called for a popup??
`OnJsDialog`: Add IBrowser param
`OnJsBeforeUnloadDialog`: ""
`OnFileDialog`: ""
`OnDragEnter`: ""
`OnRequestGeoLocation`: ""
`OnCancelGeolocationPermission`: ""

That look ok?

Feel free to merge some of your PRs in, this set of changes are going to take a bit. ugh.

Bill

**Comment by amaitland** [comment]
> OnAfterCreated isn't exposed for popups at all. Should we expose a OnAfterCreated that gets called regardless (and after) OnInitialized?

Maybe we should have another handler, like `IPopupHandler`, and push all those notifications to that? Separate them out and give them clear usages. `OnBeforeClosePopup` could happen in there. Other `CefDisplayHandler` events e.g. `OnStatusMessage` could be published here as well. Thoughts?

> OnTooltip looks wrong for popups. :frowning: I should create a separate issue for that I think.

I wonder if anyone uses it? I know it's relevant in the `OSR` implementation as we are responsible for rendering, in `WinForms` I can't imagine it's used a lot.

> That look ok?

Rest looks pretty solid at an initial glance. I'm sure once there's a `PR` there will be a few tweaks.

**Comment by amaitland** [comment]
> Feel free to merge some of your PRs in, this set of changes are going to take a bit. ugh.

I need to add some better examples, though maybe it's worth merging in sooner rather than later and update the examples once the interface updates are in place.

**Comment by rassilon** [comment]
Using `IPopupHandler` for `ILifespanHandler/CefDisplayHandler` equivalents makes sense.

**Comment by amaitland** [comment]
> Feel free to merge some of your PRs in, this set of changes are going to take a bit. ugh.

I merged the three PR's. Will add better examples later.

**Comment by rassilon** [comment]
For these few (At this moment) I'm not going to put on IPopupHandler due to reasons of impact paranoia of having more than one handler for these handlers. Thoughts? (I am adding an IBrowser param, it just never gets called on IPopupHandler.)

* OnCertificateError
* OnQuotaRequest
* OnPluginCrashed
* OnRenderProcessTerminated
* OnProtocolExecution

Thoughts?

Bill

**Comment by rassilon** [comment]
And OnBeforePluginLoad as well.

**Comment by amaitland** [comment]
> For these few (At this moment) I'm not going to put on IPopupHandler due to reasons of impact paranoia of having more than one handler for these handlers.

Conditional implementations for those sounds messy, so I think what your suggesting makes sense :+1: If they have access to the `IBrowser` param then that should be enough.

**Comment by rassilon** [comment]
I think the same should apply to:

* GetAuthCredentials as well.
