### ISSUE TITLE
WinForms Sample App: Keyboard shortcuts don’t work when the focus is in the browser control

### ISSUE THREAD

**Issue by ralphmayr** [cefsharp/CefSharp#997]
In the WinForms sample app, shortcuts like Alt+F don’t work if the focus is in the browser control. In this case, Alt+F selects the “File” menu, but doesn’t open it.
When the focus is in the address bar instead of the browser control, Alt+F opens the “File” menu as expected.

**Comment by amaitland** [comment]
Check out #1068 for an example of `IKeyboardHandler`.

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/issues/1326#issuecomment-149849463 for a **possible** alternate solution to this problem.

Having the message loop running on the same thread as the `WinForms` message loop may be another option here.

My proposed solution has not been tested.

**Comment by amaitland** [comment]
Using a single message loop appears to the resolve the problem.
