### ISSUE TITLE
DragHandler implementation of ChromiumWebBrowser not fired

### ISSUE THREAD

**Issue by ismailkocacan** [cefsharp/CefSharp#998]
<pre><code class='language-cs'>
    public partial class Form1 : Form, IDragHandler
    {
        ChromiumWebBrowser wb;

        public Form1()
        {
            InitializeComponent();

            wb = new ChromiumWebBrowser(String.Empty);
            wb.Dock = DockStyle.Fill;
            panel2.Controls.Add(wb);
            
            wb.AllowDrop = true;
            wb.DragHandler = this;

        }

     // this method not fired ???  
      public bool OnDragEnter(IWebBrowser browser, IDragData dragData, DragOperationsMask mask)
        {
            MessageBox.Show(dragData.FileName);
            return true;
        }
}
</code></pre>

**Comment by amaitland** [comment]
What version are you using?

**Comment by ismailkocacan** [comment]
CefSharp.WinForms.39.0.1

**Comment by amaitland** [comment]
Worked fine on my Windows 8.1 Pro x64bit machine. Privileges issue maybe?

http://stackoverflow.com/a/2833767

**Comment by amaitland** [comment]
Might be worth comparing your `app.manifest` to the one in the `WinForms.Example` project.

**Comment by ismailkocacan** [comment]
@amaitland Yes True. I'm using Windows 8.1 Pro x64bit.

**Comment by ismailkocacan** [comment]
When I added that code line  wb.Load("about:blank"); it worked. :)

**Comment by amaitland** [comment]
> When I added that code line wb.Load("about:blank"); it worked. :)

Presumably you could pass in `about:blank` into the constructor as well.
